// قَصَصُ النَّبِيِّينَ, volume twelve -- «قِصَّةُ سَيِّدِنَا عِيسَى ابْنِ مَرْيَمَ
// عَلَيْهِ الصَّلَاةُ وَالسَّلَامُ» (ʿĪsā ibn Maryam). The book shell the
// Library screen reads.
//
// Chapter numbering restarts at 1 in every Qaṣaṣ volume (see
// QASAS_AGENT_BRIEF.md §1), so each volume gets its own book id/shell rather
// than sharing one -- ch1 here is a different chapter from qasas-v1's,
// qasas-v2's, or qasas-v3's ch1. Volume 12 begins printed page 250,
// following volumes 4-11 (mapped but not all transcribed yet -- see
// QASAS_VOLUME_MAP.md) and closes the whole 288-page PDF at page 279; pages
// 280-288 are book back matter (a blank divider, the topical index, and a
// publisher's colophon), with no further story content.
//
// This volume's register is markedly different from volumes 1-3: dense
// classical apologetic/expository prose (chapters 1-11, 37, 42) alternating
// with direct, extensive Qur'anic block quotation (chapters 12, 13, 22, 34,
// 39, and the closing scene of ch41) -- rather than the simple graded
// narrative of the earlier volumes.
//
// Chapter BODIES are lazy: only `load()` pulls in a chapter-NN.js, so the
// shells here stay cheap enough to import eagerly from content-lit/index.js.
//
// Adding a chapter: transcribe the printed page (see ../CHAPTER-FORMAT.md
// and QASAS_AGENT_BRIEF.md), write chapter-NN.js, then add one entry here,
// in reading order -- order is what gates progression, chapter N unlocks
// when chapter N-1 is finished.
//
// IMPORTANT: this shell must be registered in ../index.js's LIT_BOOKS array
// the moment it exists, even with only one chapter -- an unregistered book
// is invisible to the app (this bit qasas-v1 once earlier in this project).
export const BOOK = {
  id: 'qasas-v12',
  title: { ar: 'قِصَّةُ سَيِّدِنَا عِيسَى ابْنِ مَرْيَمَ عَلَيْهِ الصَّلَاةُ وَالسَّلَامُ', en: 'ʿĪsā ibn Maryam' },
  volumeLabel: 'Volume Twelve',
  author: { ar: 'أَبُو الْحَسَنِ عَلِيٌّ النَّدْوِيُّ', en: 'Abū al-Ḥasan ʿAlī an-Nadwī' },
  blurb: "The story of ʿĪsā ﷺ, son of Maryam, told in dense classical prose interwoven with long direct Qur'anic quotation -- his extraordinary birth, his miracles and call, the Jews' plot against him, the Qur'an's own decisive denial of his crucifixion, and Christianity's long historical drift from his pure monotheism into a creed the author traces all the way to European paganism.",
  chapters: [
    {
      id: 'ch1',
      number: 1,
      title: { ar: 'قِصَّةٌ خَارِقَةٌ لِلْعَادَةِ', en: 'An Extraordinary Story' },
      pages: [250],
      blurb: "Opens the story of ʿĪsā ﷺ, the last messenger before Muhammad ﷺ, as a sign of Allah's overwhelming will and power -- a birth so extraordinary it suspended the very laws of nature materialist minds take as unshakeable.",
      load: () => import('./chapter-01.js'),
    },
    {
      id: 'ch2',
      number: 2,
      title: { ar: 'أَمْرٌ كُلُّهُ عَجَبٌ', en: 'A Matter Wholly Wondrous' },
      pages: [251],
      blurb: "Situates ʿĪsā's birth in history: an age when Greek rational and mathematical learning, and medicine, stood at their peak.",
      load: () => import('./chapter-02.js'),
    },
    {
      id: 'ch3',
      number: 3,
      title: { ar: 'خُضُوعُ الْيَهُودِ لِلْأَسْبَابِ الظَّاهِرَةِ', en: "The Jews' Submission to Outward Causes" },
      pages: [252],
      blurb: "The Jews, once rich in prophets, had grown so wedded to materialist explanation that they denied the soul itself -- making ʿĪsā's miracles the exact remedy their narrow minds needed.",
      load: () => import('./chapter-03.js'),
    },
    {
      id: 'ch4',
      number: 4,
      title: { ar: 'اسْتِخْفَافٌ وَتَمَرُّدٌ', en: 'Contempt and Rebellion' },
      pages: [253, 254],
      blurb: "Contempt for the prophets curdles into usury, hollowed-out religion, and hardened hearts, until the Jews of the latest age believe only what flatters their own conduct -- and turn violently on anyone who calls them to reform.",
      load: () => import('./chapter-04.js'),
    },
    {
      id: 'ch5',
      number: 5,
      title: { ar: 'نِعْمَةُ اللَّهِ عَلَى بَنِي إِسْرَائِيلَ', en: "God's Favor upon the Children of Israel" },
      pages: [254],
      blurb: "Quotes the Qur'an's own record of Allah's favor upon the Children of Israel, chosen among the nations of their time for the creed of monotheism.",
      load: () => import('./chapter-05.js'),
    },
    {
      id: 'ch6',
      number: 6,
      title: { ar: 'نُكْرَانٌ لِلْجَمِيلِ', en: 'Ingratitude' },
      pages: [254],
      blurb: 'Despite that favor, false beliefs and pagan customs crept in among them over time -- worship of the calf in Egypt, and reverence for ʿUzayr carried to blasphemous extremes.',
      load: () => import('./chapter-06.js'),
    },
    {
      id: 'ch7',
      number: 7,
      title: { ar: 'زَهْوٌ وَإِذْلَالٌ', en: 'Arrogance and Humiliation' },
      pages: [255],
      blurb: 'Even in their humiliation the Jews remain full of vain pride in lineage, claiming they are Allah\'s sons and beloved, and that the Fire could touch them for only a few numbered days.',
      load: () => import('./chapter-07.js'),
    },
    {
      id: 'ch8',
      number: 8,
      title: { ar: 'وِلَادَةُ الْمَسِيحِ تَتَحَدَّى الْمَحْسُوسَ الْمَعْرُوفَ', en: "The Messiah's Birth Defies the Known World" },
      pages: [255, 256],
      blurb: "ʿĪsā's birth, life, and mission challenge the settled, tangible world at every point -- an unfamiliar conception, speech from the cradle, and a childhood spent in his poor, devout mother's care.",
      load: () => import('./chapter-08.js'),
    },
    {
      id: 'ch9',
      number: 9,
      title: { ar: 'مُعْجِزَاتُ الْمَسِيحِ', en: 'The Miracles of the Messiah' },
      pages: [256, 257],
      blurb: 'Allah honors ʿĪsā with prophethood, the Gospel, and the Holy Spirit, supporting him with dazzling miracles: healing the sick, the blind, and the leper, giving life to the dead, and fashioning a bird from clay, all by Allah\'s permission.',
      load: () => import('./chapter-09.js'),
    },
    {
      id: 'ch10',
      number: 10,
      title: { ar: 'دَعْوَتُهُ إِلَى الدِّينِ وَتَكْذِيبُهُ الْيَهُودَ', en: "His Call to Religion and the Jews' Denial" },
      pages: [257],
      blurb: 'ʿĪsā calls the Jews back to the true spirit of religion -- love of Allah, mercy, and pure monotheism -- against everything they had distorted, forbidden, or wrongly permitted.',
      load: () => import('./chapter-10.js'),
    },
    {
      id: 'ch11',
      number: 11,
      title: { ar: 'الْيَهُودُ يَنْصُبُونَ لَهُ الْحَرْبَ', en: 'The Jews Wage War Against Him' },
      pages: [257, 258],
      blurb: 'The Jews rally as one against ʿĪsā, slandering him and his mother Maryam, stirring up the rabble, and blocking his path at every turn.',
      load: () => import('./chapter-11.js'),
    },
    {
      id: 'ch12',
      number: 12,
      title: { ar: 'قِصَّةُ عِيسَى فِي الْقُرْآنِ', en: 'The Story of Isa in the Qur’an' },
      pages: [258, 259],
      blurb: "Quotes the Qur'an's own sixteen-āyah account of ʿĪsā's story (Āl ʿImrān 3:45-60): the angels' annunciation to Maryam, his miracles, the disciples' pledge, and Allah's promise to raise him above the disbelievers.",
      load: () => import('./chapter-12.js'),
    },
    {
      id: 'ch13',
      number: 13,
      title: { ar: 'سِيرَتُهُ وَدَعْوَتُهُ فِي الْقُرْآنِ', en: 'His Biography and Call in the Qur’an' },
      pages: [260],
      blurb: "Quotes ʿĪsā's own words from the Qur'an (Maryam 19:30-33), speaking from the cradle: a servant of Allah, given the Scripture, commanded to prayer and almsgiving, and blessed at his birth, death, and resurrection.",
      load: () => import('./chapter-13.js'),
    },
    {
      id: 'ch14',
      number: 14,
      title: { ar: 'صِرَاعٌ قَدِيمٌ', en: 'An Ancient Struggle' },
      pages: [260],
      blurb: "What befell every prophet before him befalls ʿĪsā too: the chiefs and the wealthy keep their distance rather than give up their privilege -- exactly as the Qur'an describes every warner ever rejected by a town's affluent.",
      load: () => import('./chapter-14.js'),
    },
    {
      id: 'ch15',
      number: 15,
      title: { ar: 'إِيمَانُ عَامَّةِ النَّاسِ وَفُقَرَائِهِمْ', en: 'The Faith of the Common People and the Poor' },
      pages: [261],
      blurb: 'Having despaired of the elite, ʿĪsā turns to ordinary working people and the poor, whose hearts -- softened by honest labor -- prove ready to believe.',
      load: () => import('./chapter-15.js'),
    },
    {
      id: 'ch16',
      number: 16,
      title: { ar: 'نَحْنُ أَنْصَارُ اللَّهِ', en: "We Are Allah's Helpers" },
      pages: [261, 262],
      blurb: "The disciples believe and pledge themselves as Allah's helpers, in words the Qur'an records directly -- their declaration of faith when ʿĪsā asks who will stand with him.",
      load: () => import('./chapter-16.js'),
    },
    {
      id: 'ch17',
      number: 17,
      title: { ar: 'سِيَاحَةٌ وَدَعْوَةٌ', en: 'Travel and Preaching' },
      pages: [262],
      blurb: 'ʿĪsā spends his life traveling from place to place, calling the Israelites back to Allah and bearing hardship and ease alike with patience and gratitude.',
      load: () => import('./chapter-17.js'),
    },
    {
      id: 'ch18',
      number: 18,
      title: { ar: 'الْحَوَارِيُّونَ يَطْلُبُونَ مَائِدَةً مِنَ السَّمَاءِ', en: 'The Disciples Ask for a Table from Heaven' },
      pages: [262, 263],
      blurb: "Unable to match ʿĪsā's own extreme patience, the disciples ask him to pray for a table of food from heaven, so they might eat their fill after hunger and toil.",
      load: () => import('./chapter-18.js'),
    },
    {
      id: 'ch19',
      number: 19,
      title: { ar: 'سُوءُ أَدَبٍ', en: 'Bad Manners' },
      pages: [263],
      blurb: "The disciples' request comes out impolite, displeasing ʿĪsā both in content and tone -- prompting his reflection on why miracles are grave signs of faith, not tricks for entertainment.",
      load: () => import('./chapter-19.js'),
    },
    {
      id: 'ch20',
      number: 20,
      title: { ar: 'تَحْذِيرُ قَوْمِهِ مِنْ سُوءِ الْعَاقِبَةِ', en: 'Warning His People of a Bad End' },
      pages: [263],
      blurb: 'Isa, troubled by the disciples\' demand, warns them against testing Allah, who is far too exalted for that.',
      load: () => import('./chapter-20.js'),
    },
    {
      id: 'ch21',
      number: 21,
      title: { ar: 'إِلْحَاحٌ وَإِضْرَارٌ', en: 'Persistence and Harm' },
      pages: [264],
      blurb: "The disciples insist their question was never a test but a plea for reassurance -- meant to become a lasting proof of this religion's truth for every generation after them.",
      load: () => import('./chapter-21.js'),
    },
    {
      id: 'ch22',
      number: 22,
      title: { ar: 'الْقُرْآنُ يَحْكِي الْقِصَّةَ', en: "The Qur'an Narrates the Story" },
      pages: [264, 265],
      blurb: "The Qur'an itself narrates the episode in full (Al-Ma'idah 5:112-115): the disciples' request, ʿĪsā's prayer, and Allah's promise to send down the table while warning against ingratitude afterward.",
      load: () => import('./chapter-22.js'),
    },
    {
      id: 'ch23',
      number: 23,
      title: { ar: 'الْيَهُودُ يُحَاوِلُونَ التَّخَلُّصَ مِنْ سَيِّدِنَا عِيسَى', en: 'The Jews Try to Get Rid of Isa' },
      pages: [265],
      blurb: "The Jews' patience finally breaks, and they bring ʿĪsā's case before the Roman governor, accusing him of rebellion, division, and leading their youth astray.",
      load: () => import('./chapter-23.js'),
    },
    {
      id: 'ch24',
      number: 24,
      title: { ar: 'أُسْلُوبُ النَّاقِمِينَ وَالسِّيَاسِيِّينَ', en: 'The Method of the Resentful and the Politicians' },
      pages: [265],
      blurb: 'Their accusation follows a timeless script: paint the reformer as a danger to the state who respects nothing sacred, since unrest, once loosed, only escalates.',
      load: () => import('./chapter-24.js'),
    },
    {
      id: 'ch25',
      number: 25,
      title: { ar: 'مَكْرٌ وَدَهَاءٌ', en: 'Cunning and Craftiness' },
      pages: [266],
      blurb: 'The Jews deliberately tinge their complaint with politics rather than religion, knowing purely religious grievances would never move a ruler who stayed out of such affairs.',
      load: () => import('./chapter-25.js'),
    },
    {
      id: 'ch26',
      number: 26,
      title: { ar: 'مُشْكِلَةٌ', en: 'A Problem' },
      pages: [266],
      blurb: "The foreign rulers, absorbed in administration, struggle to grasp the case at first -- until the Jews' relentless pressure finally wears them down.",
      load: () => import('./chapter-26.js'),
    },
    {
      id: 'ch27',
      number: 27,
      title: { ar: 'سَيِّدُنَا الْمَسِيحُ فِي الْمَحْكَمَةِ', en: 'Our Master the Messiah in Court' },
      pages: [266, 267],
      blurb: 'Rushed by the coming Sabbath, the ruler hands down a hasty verdict just to be rid of a case he never wanted, on the eve of the Jewish day of rest.',
      load: () => import('./chapter-27.js'),
    },
    {
      id: 'ch28',
      number: 28,
      title: { ar: 'الْقَانُونُ الْجِنَائِيُّ فِي ذَلِكَ الْعَصْرِ', en: 'Criminal Law in That Era' },
      pages: [267, 268],
      blurb: "Describes the criminal procedure of the era -- the condemned forced to carry his own cross -- and the chaotic crowd and indifferent foreign police on the way to the execution ground as night falls.",
      load: () => import('./chapter-28.js'),
    },
    {
      id: 'ch29',
      number: 29,
      title: { ar: 'عِيسَى يَتَحَمَّلُ الْأَذَى', en: 'Isa Bears the Harm' },
      pages: [268],
      blurb: 'Worn out by his ordeal and the weight of the cross, the Messiah struggles under a burden too heavy for him to bear quickly.',
      load: () => import('./chapter-29.js'),
    },
    {
      id: 'ch30',
      number: 30,
      title: { ar: 'تَدْبِيرٌ إِلَهِيٌّ', en: 'A Divine Plan' },
      pages: [268, 269],
      blurb: 'A policeman orders a zealous young Israelite bystander to carry the cross instead, setting in motion the divine plan that follows.',
      load: () => import('./chapter-30.js'),
    },
    {
      id: 'ch31',
      number: 31,
      title: { ar: 'وَلَكِنْ شُبِّهَ لَهُمْ', en: '"But It Was Made to Appear So to Them"' },
      pages: [269],
      blurb: 'In the chaos and noise, the execution squad seizes the young man carrying the cross -- certain, wrongly, that he is the one condemned -- despite his own cries of innocence.',
      load: () => import('./chapter-31.js'),
    },
    {
      id: 'ch32',
      number: 32,
      title: { ar: 'تَنْفِيذُ حُكْمٍ', en: 'Execution of a Verdict' },
      pages: [269, 270],
      blurb: 'The sentence is carried out on the young man in the darkness, while the Jews watch from a distance, certain they have crucified the Messiah himself.',
      load: () => import('./chapter-32.js'),
    },
    {
      id: 'ch33',
      number: 33,
      title: { ar: 'رَفْعُ عِيسَى إِلَى السَّمَاءِ', en: 'The Raising of Isa to Heaven' },
      pages: [270],
      blurb: "Allah saves ʿĪsā from the Jews' plot, raising him to Himself, honored and purified from those who disbelieved.",
      load: () => import('./chapter-33.js'),
    },
    {
      id: 'ch34',
      number: 34,
      title: { ar: 'الْقُرْآنُ يَتَحَدَّثُ عَنِ الْقِصَّةِ', en: "The Qur'an Speaks of the Story" },
      pages: [270, 271],
      blurb: "Quotes the Qur'an's own decisive account (An-Nisa 4:156-158): the Jews' slander against Maryam, their false claim to have killed the Messiah, and Allah's declaration that they did not kill or crucify him -- it was only made to appear so.",
      load: () => import('./chapter-34.js'),
    },
    {
      id: 'ch35',
      number: 35,
      title: { ar: 'نُزُولُ عِيسَى قَبْلَ الْقِيَامَةِ', en: 'The Descent of Isa Before the Resurrection' },
      pages: [271],
      blurb: 'ʿĪsā will descend before the Resurrection to settle every dispute about him and uphold the truth, as the Prophet ﷺ himself foretold in authentic, mass-transmitted reports.',
      load: () => import('./chapter-35.js'),
    },
    {
      id: 'ch36',
      number: 36,
      title: { ar: 'بِشَارَتُهُ بِبَعْثَةِ سَيِّدِنَا مُحَمَّدٍ ﷺ', en: "His Glad Tiding of Muhammad's ﷺ Mission" },
      pages: [272],
      blurb: "Unable to finish his mission against the Jews' hostility, al-Masih gives his followers the glad tidings of a coming messenger who will complete and universalize what he began.",
      load: () => import('./chapter-36.js'),
    },
    {
      id: 'ch37',
      number: 37,
      title: { ar: 'مِنَ التَّوْحِيدِ الْخَالِصِ إِلَى عَقِيدَةٍ غَامِضَةٍ', en: 'From Pure Monotheism to a Vague Creed' },
      pages: [272, 273, 274],
      blurb: "Traces the tragic drift of al-Masih's pure, simple monotheism into a vague, complicated creed as his followers went to extremes over him after his departure.",
      load: () => import('./chapter-37.js'),
    },
    {
      id: 'ch38',
      number: 38,
      title: { ar: 'عِيسَى يَدْعُو إِلَى عِبَادَةِ اللَّهِ وَحْدَهُ', en: 'Isa Calls to Worship of Allah Alone' },
      pages: [274],
      blurb: "Quotes al-Masih's own words, from the Gospel and the Qur'an alike, calling people to worship Allah alone and denying that any prophet would ever call people to worship himself.",
      load: () => import('./chapter-38.js'),
    },
    {
      id: 'ch39',
      number: 39,
      title: { ar: 'الْقُرْآنُ يُصَرِّحُ بِدَعْوَةِ عِيسَى', en: "The Qur'an States Isa's Call Clearly" },
      pages: [275],
      blurb: "The Qur'an states ʿĪsā's monotheistic call in the plainest terms (Al-Ma'idah 5:72), condemning those who deified him as disbelievers in his own name.",
      load: () => import('./chapter-39.js'),
    },
    {
      id: 'ch40',
      number: 40,
      title: { ar: 'مَنْزِلَةُ التَّوْحِيدِ فِي دَعْوَتِهِ', en: 'The Place of Monotheism in His Call' },
      pages: [275, 276],
      blurb: "ʿĪsā speaks with eloquence on monotheism's true place in every prophet's mission, in Qur'anic words describing the angels and the Messiah alike as never disdaining to be Allah's servants.",
      load: () => import('./chapter-40.js'),
    },
    {
      id: 'ch41',
      number: 41,
      title: { ar: 'مَشْهَدٌ رَائِعٌ مِنْ مَشَاهِدِ الْقِيَامَةِ', en: 'A Magnificent Scene from the Resurrection' },
      pages: [276, 277],
      blurb: 'The Qur\'an paints a magnificent scene from the Resurrection in which ʿĪsā disavows what was falsely said of him and places the blame squarely on those who went to extremes in his name.',
      load: () => import('./chapter-41.js'),
    },
    {
      id: 'ch42',
      number: 42,
      title: { ar: 'مِنْ عَقِيدَةٍ غَامِضَةٍ إِلَى وَثَنِيَّةٍ سَافِرَةٍ', en: 'From a Vague Creed to Blatant Paganism' },
      pages: [277, 278, 279],
      blurb: "Closes the volume tracing Christianity's spread into an already deeply pagan Europe, and its own slow absorption of pagan belief and Greek philosophy into a genuinely new religion -- a tragedy, the author says, for Europe and for the humanity it has long led.",
      load: () => import('./chapter-42.js'),
    },
  ],
};
