// قَصَصُ النَّبِيِّينَ, volume 1 «مَنْ كَسَرَ الأَصْنَامَ؟», chapter 3 -- نَصِيحَةُ إِبْرَاهِيمَ.
// Printed page 11. Transcribed by hand from the scan (vision OCR, 300dpi
// render) against QASAS_AGENT_BRIEF.md and ../CHAPTER-FORMAT.md.
//
// New register: direct 2nd-person address (يَا أَبِي، لِمَاذَا تَفْعَلُ...؟), three
// times running -- the workshop below drills that vocative + rhetorical-
// question frame instead of repeating ch1/ch2's كَانَ or أَنَّ frames.
//
// No page footnotes (book_note) on this page.
export const CHAPTER = {
  id: 'ch3',
  title: { ar: 'نَصِيحَةُ إِبْرَاهِيمَ', en: "Ibrāhīm's Advice" },
  newWords: [
    'أَب', 'غَضِبَ', 'فَهِمَ', 'نَصَحَ', 'قَوْم', 'كَسَّرَ', 'وَضَعَ', 'شَرَاب', 'حِينَئِذٍ',
  ],
  lemmas: {
    'أَب': { gloss: 'father' },
    'غَضِبَ': { gloss: 'to become angry' },
    'فَهِمَ': { gloss: 'to understand' },
    'نَصَحَ': { gloss: 'to advise' },
    'قَوْم': { gloss: 'people, folk' },
    'كَسَّرَ': { gloss: 'to smash, break to pieces' },
    'وَضَعَ': { gloss: 'to put, place, set out' },
    'شَرَاب': { gloss: 'drink, beverage' },
    'حِينَئِذٍ': { gloss: 'at that time, then' },
    'إِنَّ': { gloss: 'indeed, verily' },
    'يَا': { gloss: 'O (vocative)' },
    'أَيّ': { gloss: 'which, what' },
    'إِذَا': { gloss: 'when, if' },
    'شَيْء': { gloss: 'thing' },
    'شَرِبَ': { gloss: 'to drink' },
  },
  paragraphs: [
    {
      en: "Ibrāhīm used to say to his father: 'O my father, why do you worship these idols? And O my father, why do you prostrate to them? And O my father, why do you ask them for anything? Indeed these idols neither speak nor hear, and they neither harm nor benefit. So for what do you set out food and drink for them? Indeed these idols, my father, neither eat nor drink!' Āzar would only grow angry and not understand. Ibrāhīm kept advising his people, and the people kept growing angry and not understanding. Ibrāhīm said: 'I will smash the idols once the people are gone -- and then they will understand.'",
      sentences: [
        {
          id: 'qs-v1-c03-001',
          ar: 'وَكَانَ إِبْرَاهِيمُ يَقُولُ لِوَالِدِهِ:',
          en: 'And Ibrāhīm used to say to his father:',
          tokens: [
            { surface: 'وَكَانَ', lemma: 'كَانَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ك و ن', gloss: 'to be; and...used to' },
            { surface: 'إِبْرَاهِيمُ', lemma: 'إِبْرَاهِيم', pos: 'proper', features: 'nom', gloss: 'Ibrāhīm' },
            { surface: 'يَقُولُ', lemma: 'قَالَ', pos: 'verb', features: 'impf.3ms', root: 'ق و ل', gloss: 'to say' },
            { surface: 'لِوَالِدِهِ', lemma: 'وَالِد', pos: 'noun', features: 'prep+gen+3ms', root: 'و ل د', gloss: 'to his father' },
          ],
        },
        {
          id: 'qs-v1-c03-002',
          ar: 'يَا أَبِي، لِمَاذَا تَعْبُدُ هَذِهِ الْأَصْنَامَ؟!!',
          en: 'O my father, why do you worship these idols?!',
          tokens: [
            { surface: 'يَا', lemma: 'يَا', pos: 'part', features: 'part', gloss: 'O' },
            { surface: 'أَبِي', lemma: 'أَب', pos: 'noun', features: 'acc+1s', root: 'أ ب و', gloss: 'my father' },
            { surface: 'لِمَاذَا', lemma: 'لِمَاذَا', pos: 'adv', features: 'adv', gloss: 'why' },
            { surface: 'تَعْبُدُ', lemma: 'عَبَدَ', pos: 'verb', features: 'impf.2ms', root: 'ع ب د', gloss: 'to worship' },
            { surface: 'هَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'dem.f', gloss: 'this, these' },
            { surface: 'الْأَصْنَامَ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.acc', root: 'ص ن م', gloss: 'idols' },
          ],
        },
        {
          id: 'qs-v1-c03-003',
          ar: 'وَيَا أَبِي لِمَاذَا تَسْجُدُ لِهَذِهِ الْأَصْنَامِ؟!!',
          en: 'And O my father, why do you prostrate to these idols?!',
          tokens: [
            { surface: 'وَيَا', lemma: 'يَا', pos: 'part', features: 'conj+part', gloss: 'and O' },
            { surface: 'أَبِي', lemma: 'أَب', pos: 'noun', features: 'acc+1s', root: 'أ ب و', gloss: 'my father' },
            { surface: 'لِمَاذَا', lemma: 'لِمَاذَا', pos: 'adv', features: 'adv', gloss: 'why' },
            { surface: 'تَسْجُدُ', lemma: 'سَجَدَ', pos: 'verb', features: 'impf.2ms', root: 'س ج د', gloss: 'to prostrate' },
            { surface: 'لِهَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'prep+dem.f', gloss: 'to this' },
            { surface: 'الْأَصْنَامِ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.gen', root: 'ص ن م', gloss: 'idols' },
          ],
        },
        {
          id: 'qs-v1-c03-004',
          ar: 'وَيَا أَبِي لِمَاذَا تَسْأَلُ هَذِهِ الْأَصْنَامَ؟!!',
          en: 'And O my father, why do you ask these idols?!',
          tokens: [
            { surface: 'وَيَا', lemma: 'يَا', pos: 'part', features: 'conj+part', gloss: 'and O' },
            { surface: 'أَبِي', lemma: 'أَب', pos: 'noun', features: 'acc+1s', root: 'أ ب و', gloss: 'my father' },
            { surface: 'لِمَاذَا', lemma: 'لِمَاذَا', pos: 'adv', features: 'adv', gloss: 'why' },
            { surface: 'تَسْأَلُ', lemma: 'سَأَلَ', pos: 'verb', features: 'impf.2ms', root: 'س أ ل', gloss: 'to ask' },
            { surface: 'هَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'dem.f', gloss: 'this, these' },
            { surface: 'الْأَصْنَامَ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.acc', root: 'ص ن م', gloss: 'idols' },
          ],
        },
        {
          id: 'qs-v1-c03-005',
          ar: 'إِنَّ هَذِهِ الْأَصْنَامَ لَا تَتَكَلَّمُ وَلَا تَسْمَعُ!',
          en: 'Indeed these idols neither speak nor hear!',
          tokens: [
            { surface: 'إِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'هَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'dem.f', gloss: 'this, these' },
            { surface: 'الْأَصْنَامَ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.acc', root: 'ص ن م', gloss: 'idols' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'تَتَكَلَّمُ', lemma: 'تَكَلَّمَ', pos: 'verb', features: 'impf.3fs', root: 'ك ل م', gloss: 'to speak' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'تَسْمَعُ', lemma: 'سَمِعَ', pos: 'verb', features: 'impf.3fs', root: 'س م ع', gloss: 'to hear' },
          ],
        },
        {
          id: 'qs-v1-c03-006',
          ar: 'وَإِنَّ هَذِهِ الْأَصْنَامَ لَا تَضُرُّ وَلَا تَنْفَعُ!',
          en: 'And indeed these idols neither harm nor benefit!',
          tokens: [
            { surface: 'وَإِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'conj+part', gloss: 'and indeed' },
            { surface: 'هَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'dem.f', gloss: 'this, these' },
            { surface: 'الْأَصْنَامَ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.acc', root: 'ص ن م', gloss: 'idols' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'تَضُرُّ', lemma: 'ضَرَّ', pos: 'verb', features: 'impf.3fs', root: 'ض ر ر', gloss: 'to harm' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'تَنْفَعُ', lemma: 'نَفَعَ', pos: 'verb', features: 'impf.3fs', root: 'ن ف ع', gloss: 'to benefit' },
          ],
        },
        {
          id: 'qs-v1-c03-007',
          ar: 'وَلِأَيِّ شَيْءٍ تَضَعُ لَهَا الطَّعَامَ وَالشَّرَابَ؟!!',
          en: 'So for what do you set out food and drink for them?!',
          tokens: [
            { surface: 'وَلِأَيِّ', lemma: 'أَيّ', pos: 'noun', features: 'conj+prep+gen.constr', gloss: 'and for which' },
            { surface: 'شَيْءٍ', lemma: 'شَيْء', pos: 'noun', features: 'indef.gen', root: 'ش ي أ', gloss: 'thing' },
            { surface: 'تَضَعُ', lemma: 'وَضَعَ', pos: 'verb', features: 'impf.2ms', root: 'و ض ع', gloss: 'to put, set out' },
            { surface: 'لَهَا', lemma: 'لِ', pos: 'prep', features: 'prep+3fs', gloss: 'for them' },
            { surface: 'الطَّعَامَ', lemma: 'طَعَام', pos: 'noun', features: 'def.acc', root: 'ط ع م', gloss: 'food' },
            { surface: 'وَالشَّرَابَ', lemma: 'شَرَاب', pos: 'noun', features: 'conj+def.acc', root: 'ش ر ب', gloss: 'and drink' },
          ],
        },
        {
          id: 'qs-v1-c03-008',
          ar: 'وَإِنَّ هَذِهِ الْأَصْنَامَ يَا أَبِي لَا تَأْكُلُ وَلَا تَشْرَبُ!',
          en: 'And indeed these idols, my father, neither eat nor drink!',
          tokens: [
            { surface: 'وَإِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'conj+part', gloss: 'and indeed' },
            { surface: 'هَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'dem.f', gloss: 'this, these' },
            { surface: 'الْأَصْنَامَ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.acc', root: 'ص ن م', gloss: 'idols' },
            { surface: 'يَا', lemma: 'يَا', pos: 'part', features: 'part', gloss: 'O' },
            { surface: 'أَبِي', lemma: 'أَب', pos: 'noun', features: 'acc+1s', root: 'أ ب و', gloss: 'my father' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'تَأْكُلُ', lemma: 'أَكَلَ', pos: 'verb', features: 'impf.3fs', root: 'أ ك ل', gloss: 'to eat' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'تَشْرَبُ', lemma: 'شَرِبَ', pos: 'verb', features: 'impf.3fs', root: 'ش ر ب', gloss: 'to drink' },
          ],
        },
        {
          id: 'qs-v1-c03-009',
          ar: 'وَكَانَ آزَرُ يَغْضَبُ وَلَا يَفْهَمُ.',
          en: 'And Āzar would grow angry and not understand.',
          tokens: [
            { surface: 'وَكَانَ', lemma: 'كَانَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ك و ن', gloss: 'to be; and...used to' },
            { surface: 'آزَرُ', lemma: 'آزَر', pos: 'proper', features: 'nom', gloss: 'Āzar' },
            { surface: 'يَغْضَبُ', lemma: 'غَضِبَ', pos: 'verb', features: 'impf.3ms', root: 'غ ض ب', gloss: 'to become angry' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'يَفْهَمُ', lemma: 'فَهِمَ', pos: 'verb', features: 'impf.3ms', root: 'ف ه م', gloss: 'to understand' },
          ],
        },
        {
          id: 'qs-v1-c03-010',
          ar: 'وَكَانَ إِبْرَاهِيمُ يَنْصَحُ لِقَوْمِهِ،',
          en: 'And Ibrāhīm kept advising his people,',
          tokens: [
            { surface: 'وَكَانَ', lemma: 'كَانَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ك و ن', gloss: 'to be; and...used to' },
            { surface: 'إِبْرَاهِيمُ', lemma: 'إِبْرَاهِيم', pos: 'proper', features: 'nom', gloss: 'Ibrāhīm' },
            { surface: 'يَنْصَحُ', lemma: 'نَصَحَ', pos: 'verb', features: 'impf.3ms', root: 'ن ص ح', gloss: 'to advise' },
            { surface: 'لِقَوْمِهِ', lemma: 'قَوْم', pos: 'noun', features: 'prep+gen+3ms', root: 'ق و م', gloss: 'to his people' },
          ],
        },
        {
          id: 'qs-v1-c03-011',
          ar: 'وَكَانَ النَّاسُ يَغْضَبُونَ وَلَا يَفْهَمُونَ.',
          en: 'and the people kept growing angry and not understanding.',
          tokens: [
            { surface: 'وَكَانَ', lemma: 'كَانَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ك و ن', gloss: 'to be; and...used to' },
            { surface: 'النَّاسُ', lemma: 'نَاس', pos: 'noun', features: 'def.nom', root: 'ن و س', gloss: 'people' },
            { surface: 'يَغْضَبُونَ', lemma: 'غَضِبَ', pos: 'verb', features: 'impf.3mp', root: 'غ ض ب', gloss: 'to become angry' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'يَفْهَمُونَ', lemma: 'فَهِمَ', pos: 'verb', features: 'impf.3mp', root: 'ف ه م', gloss: 'to understand' },
          ],
        },
        {
          id: 'qs-v1-c03-012',
          ar: 'قَالَ إِبْرَاهِيمُ أَنَا أُكَسِّرُ الْأَصْنَامَ إِذَا ذَهَبَ النَّاسُ،',
          en: 'Ibrāhīm said: I will smash the idols once the people are gone,',
          tokens: [
            { surface: 'قَالَ', lemma: 'قَالَ', pos: 'verb', features: 'perf.3ms', root: 'ق و ل', gloss: 'to say; said' },
            { surface: 'إِبْرَاهِيمُ', lemma: 'إِبْرَاهِيم', pos: 'proper', features: 'nom', gloss: 'Ibrāhīm' },
            { surface: 'أَنَا', lemma: 'أَنَا', pos: 'noun', features: '1s', gloss: 'I' },
            { surface: 'أُكَسِّرُ', lemma: 'كَسَّرَ', pos: 'verb', features: 'impf.1s', root: 'ك س ر', gloss: 'to smash, break to pieces' },
            { surface: 'الْأَصْنَامَ', lemma: 'صَنَم', pos: 'noun', features: 'pl.def.acc', root: 'ص ن م', gloss: 'idols' },
            { surface: 'إِذَا', lemma: 'إِذَا', pos: 'adv', features: 'adv', gloss: 'when, once' },
            { surface: 'ذَهَبَ', lemma: 'ذَهَبَ', pos: 'verb', features: 'perf.3ms', root: 'ذ ه ب', gloss: 'to go' },
            { surface: 'النَّاسُ', lemma: 'نَاس', pos: 'noun', features: 'def.nom', root: 'ن و س', gloss: 'people' },
          ],
        },
        {
          id: 'qs-v1-c03-013',
          ar: 'وَحِينَئِذٍ يَفْهَمُ النَّاسُ.',
          en: 'and then the people will understand.',
          tokens: [
            { surface: 'وَحِينَئِذٍ', lemma: 'حِينَئِذٍ', pos: 'adv', features: 'conj+adv', gloss: 'and then, at that time' },
            { surface: 'يَفْهَمُ', lemma: 'فَهِمَ', pos: 'verb', features: 'impf.3ms', root: 'ف ه م', gloss: 'to understand' },
            { surface: 'النَّاسُ', lemma: 'نَاس', pos: 'noun', features: 'def.nom', root: 'ن و س', gloss: 'people' },
          ],
        },
      ],
      checks: [
        {
          q: 'مَاذَا قَالَ إِبْرَاهِيمُ لِوَالِدِهِ عَنِ الْأَصْنَامِ؟',
          options: ['إِنَّهَا لَا تَتَكَلَّمُ وَلَا تَسْمَعُ', 'إِنَّهَا جَمِيلَةٌ جِدًّا', 'إِنَّهَا تَحْمِي الْقَرْيَةَ'],
          answer: 0,
          qEn: 'What did Ibrāhīm tell his father about the idols?',
          optionsEn: ['That they neither speak nor hear', 'That they are very beautiful', 'That they protect the village'],
        },
        {
          q: 'كَيْفَ كَانَ آزَرُ يَرُدُّ عَلَى نَصِيحَةِ إِبْرَاهِيمَ؟',
          options: ['كَانَ يَغْضَبُ وَلَا يَفْهَمُ', 'كَانَ يُوَافِقُهُ', 'كَانَ يَضْحَكُ'],
          answer: 0,
          qEn: "How did Āzar respond to Ibrāhīm's advice?",
          optionsEn: ['He would grow angry and not understand', 'He would agree with him', 'He would laugh'],
        },
        {
          q: 'مَاذَا قَالَ إِبْرَاهِيمُ إِنَّهُ سَيَفْعَلُ بِالْأَصْنَامِ؟',
          options: ['سَأُكَسِّرُهَا إِذَا ذَهَبَ النَّاسُ', 'سَأَبِيعُهَا', 'سَأُخْفِيهَا'],
          answer: 0,
          qEn: 'What did Ibrāhīm say he would do to the idols?',
          optionsEn: ['I will smash them once the people are gone', 'I will sell them', 'I will hide them'],
        },
      ],
    },
  ],
  workshop: {
    cloze: [
      {
        type: 'cloze',
        pre: 'يَا أَبِي، لِمَاذَا',
        post: 'هَذِهِ الْأَصْنَامَ؟',
        en: 'O my father, why do you worship these idols?',
        options: ['تَعْبُدُ', 'يَعْبُدُ', 'أَعْبُدُ', 'تَعْبُدِينَ'],
        answer: 0,
        rationales: [
          '2nd masculine singular -- Ibrāhīm is addressing his father directly.',
          '3rd masculine singular -- he.',
          '1st person singular -- I.',
          '2nd feminine singular -- you (f.).',
        ],
      },
      {
        type: 'cloze',
        pre: 'وَيَا أَبِي لِمَاذَا',
        post: 'لِهَذِهِ الْأَصْنَامِ؟',
        en: 'And O my father, why do you prostrate to these idols?',
        options: ['تَسْجُدُ', 'يَسْجُدُ', 'سَجَدْتَ', 'نَسْجُدُ'],
        answer: 0,
        rationales: [
          '2nd masculine singular, present -- direct address.',
          '3rd masculine singular -- he.',
          "That's the perfect -- you prostrated once, not a standing habit being questioned.",
          '1st person plural -- we.',
        ],
      },
      {
        type: 'cloze',
        pre: 'وَإِنَّ هَذِهِ الْأَصْنَامَ لَا تَضُرُّ وَلَا',
        post: '!',
        en: 'And indeed these idols neither harm nor benefit!',
        options: ['تَنْفَعُ', 'يَنْفَعُ', 'نَفَعَتْ', 'تَنْفَعَانِ'],
        answer: 0,
        rationales: [
          '3rd feminine singular -- agrees with the non-human plural الأصنام.',
          '3rd masculine singular -- wrong agreement for a plural of things.',
          'Perfect -- benefited once.',
          'Dual -- the two of them benefit.',
        ],
      },
      {
        type: 'cloze',
        pre: 'قَالَ إِبْرَاهِيمُ: أَنَا',
        post: 'الْأَصْنَامَ إِذَا ذَهَبَ النَّاسُ.',
        en: 'Ibrāhīm said: I will smash the idols once the people are gone.',
        options: ['أُكَسِّرُ', 'يُكَسِّرُ', 'كَسَّرْتُ', 'نُكَسِّرُ'],
        answer: 0,
        rationales: [
          '1st person singular -- matches أَنَا.',
          '3rd masculine singular -- he.',
          "That's the perfect -- I already smashed them.",
          '1st person plural -- we.',
        ],
      },
    ],
    shift: [
      {
        type: 'shift',
        base: 'لِمَاذَا تَعْبُدُ هَذِهِ الْأَصْنَامَ',
        pre: 'لِمَاذَا',
        post: 'هَذِهِ الْأَصْنَامَ',
        targetPerson: 'هُوَ',
        targetEn: 'he',
        options: ['يَعْبُدُ', 'تَعْبُدُ', 'أَعْبُدُ', 'يَعْبُدُونَ'],
        answer: 0,
        rationales: [
          '3rd masculine singular -- matches هُوَ.',
          '2nd masculine singular -- you.',
          '1st person singular -- I.',
          '3rd masculine plural -- they.',
        ],
      },
      {
        type: 'shift',
        base: 'لِمَاذَا تَعْبُدُ هَذِهِ الْأَصْنَامَ',
        pre: 'لِمَاذَا',
        post: 'هَذِهِ الْأَصْنَامَ',
        targetPerson: 'هُمْ',
        targetEn: 'they',
        options: ['يَعْبُدُونَ', 'يَعْبُدُ', 'تَعْبُدُ', 'نَعْبُدُ'],
        answer: 0,
        rationales: [
          '3rd masculine plural -- matches هُمْ.',
          '3rd masculine singular.',
          '2nd masculine or 3rd feminine singular.',
          '1st person plural.',
        ],
      },
      {
        type: 'shift',
        base: 'لِمَاذَا تَسْجُدُ لِهَذِهِ الْأَصْنَامِ',
        pre: 'لِمَاذَا',
        post: 'لِهَذِهِ الْأَصْنَامِ',
        targetPerson: 'أَنْتِ',
        targetEn: 'you (f.)',
        options: ['تَسْجُدِينَ', 'تَسْجُدُ', 'يَسْجُدُ', 'نَسْجُدُ'],
        answer: 0,
        rationales: [
          '2nd feminine singular -- matches أَنْتِ.',
          '2nd masculine singular -- you (m.).',
          '3rd masculine singular -- he.',
          '1st person plural -- we.',
        ],
      },
      {
        type: 'shift',
        base: 'لِمَاذَا تَسْجُدُ لِهَذِهِ الْأَصْنَامِ',
        pre: 'لِمَاذَا',
        post: 'لِهَذِهِ الْأَصْنَامِ',
        targetPerson: 'نَحْنُ',
        targetEn: 'we',
        options: ['نَسْجُدُ', 'تَسْجُدُ', 'يَسْجُدُ', 'يَسْجُدُونَ'],
        answer: 0,
        rationales: [
          '1st person plural -- matches نَحْنُ.',
          '2nd masculine or 3rd feminine singular.',
          '3rd masculine singular.',
          '3rd masculine plural.',
        ],
      },
    ],
  },
};
