// Module 22 — حذف العامل
//
// Source: app-lessons/114-al-tanazu.md, app-lessons/115-hadhf-amil-al-masdar.md,
// app-lessons/116-al-tahdhir.md, app-lessons/117-al-ighra.md,
// app-lessons/118-al-ikhtisas.md, app-lessons/119-al-ishtighal.md, and
// app-lessons/123-hadhf-amil-al-hal.md (الكبرى في النحو), opening
// الخاتِمَة — the book's closing section on العامل — per COURSE-MAP.md's
// Module 22 plan. الخاتمة has two فصول: التنازع (114) and حذف العامل
// (115-119, 123); this module covers both, closing the العامل وغير العامل
// chapter. app-lessons/120-122 (النداء وملحقاته) are COURSE-MAP's separate
// Module 23, not this one, and are skipped here per that plan.
//
// l1 merges 114+115 (both open الخاتمة, and 115's حذف عامل المصدر is the
// first ضرب of حذف العامل). l2 merges 116-118 (التحذير, الإغراء,
// الاختصاص are the first three of حذف عامل المفعول به's خمسة مواضع, and
// read naturally together — التحذير and الإغراء are explicit mirror
// constructions, and الاختصاص is grouped with them in the source itself).
// l3 covers 119 (الاشتغال, the fourth موضع) alone, since it is the
// densest single file in the range. l4 covers 123 (حذف عامل الحال, a
// later فصل in the same الخاتمة) alone. The survey held up once every
// source file was read in full, matching the proposal that stood in
// COURSE-MAP.md before authoring — no lesson-boundary changes were
// needed.
//
// Concept bodies use the lines[]/box/table/tarkeebDiagram shape
// established in module-01.js and used throughout every authored module
// since. Per that convention, a Rule/Careful box whose app-lessons source
// states its point in mixed English/Arabic prose (rather than one clean
// Arabic line) is distilled into a short Arabic box statement matching
// the established register, with the full English explanation kept in
// the surrounding prose — the same treatment Module 02's own header
// comment documents. Bank تركيب items use the flat
// words[]/labels[]/distractors[] schema, matching every prior authored
// module. Every lesson in this module reaches the full 24-item/6-تركيب
// bank norm: 114-119 and 123 are all unusually rich in short, cleanly
// parsed worked examples — several already short enough to serve as
// تركيب chips without adaptation — so none of this module's lessons
// needed the taper several thinner-sourced modules elsewhere in this
// course required.
export default {
  id: '22',
  title: 'حذف العامل',
  heading: 'العامل وغير العامل',
  subheading: 'خاتم',
  blurb: 'التنازع — two governors competing for one معمول — then every قياسي and سماعي pattern where a governor is obligatorily dropped: المفعول المطلق, التحذير والإغراء والاختصاص, الاشتغال, and الحال.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'التنازع وحذف عامل المفعول المطلق',
      subtitle: 'Two Governors, One معمول — التنازع’s إيجاز, then the four قياسي patterns and the سماعي phrases where المفعول المطلق’s governor is obligatorily dropped',
      concepts: [
        {
          heading: 'التنازع: التعريف وأنواع المتنازِعَين',
          lines: [
            { html: `الخاتِمَة, the book's closing section on العامل, opens with <bdi>التَّنازُع</bdi> — what happens when two governors compete for a single shared معمول.`, list: false },
            { box: { title: 'Definition', lines: [`التَّنازُع: تَنازُعُ عامِلَيْنِ في مَعْمولٍ واحِدٍ مُتَأَخِّرٍ`] } },
            { html: `Two words, each independently capable of governing a معمول on its own, both appear before a single shared معمول that comes after both of them. Grammatically only one of the two can actually be assigned as the true عامل — but the meaning works with either, since both would have governed the same word the same way if it had been repeated.`, list: false },
            { box: { title: 'Rule', lines: [`المُتَنازِعانِ: إِمّا فِعْلانِ، وَإِمّا اسْمانِ عامِلانِ`] } },
            { box: { title: 'Example', lines: [`﴿كُلوا واشْرَبوا مِنْ رِزْقِ اللهِ﴾`] } },
            { html: `"Eat and drink from Allah's provision." Both <bdi>كُلوا</bdi> and <bdi>اشْرَبوا</bdi> independently want مِنْ رِزْقِ اللهِ as their own معمول, but it is written only once, after both.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `كُلوا واشْرَبوا مِنْ رِزْقِ اللهِ`,
                translation: `Eat and drink from Allah's provision.`,
                cells: [`كُلوا`, `وَاشْرَبوا`, `مِنْ رِزْقِ اللهِ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `أحد المتنازِعَين` }, { start: 1, end: 1, role: `المتنازِع الثاني` }, { start: 2, end: 2, role: `المعمول المشترك المتأخر` }] },
                ],
              },
            },
            { box: { title: 'Example', lines: [`﴿وَإِنْ أَدْري أَقَريبٌ أَمْ بَعيدٌ ما توعَدونَ﴾`] } },
            { html: `"I do not know whether what you are promised is near or far." <bdi>أَقَريب</bdi> and <bdi>بَعيد</bdi> — each a صفة مشبهة acting as عامل — both compete for ما تُوعَدونَ as their فاعل.`, list: false },
          ],
          exercise: {
            prompt: `﴿كُلوا واشْرَبوا مِنْ رِزْقِ اللهِ﴾ has two verbs, كُلوا and اشْرَبوا, each wanting مِنْ رِزْقِ اللهِ as its own معمول, though it is written only once. What is this phenomenon called?`,
            kind: 'mcq',
            options: [`التنازع (also called الإعمال)`, `الاشتغال`, `الاختصاص`, `حذف عامل المفعول المطلق`],
            correct: 0,
          },
        },
        {
          heading: 'أسباب التنازع، وتسميته الإعمال، وتعدد المتنازِعَين',
          lines: [
            { html: `Three further points round out the picture of التنازع.`, list: false },
            { html: `(1) Both عوامل genuinely carry the same meaning toward the shared معمول — writing it only once is simply <bdi>إيجاز</bdi>, the general Arab preference for saying more with less; nothing in the meaning is lost, only the surface question of which word is the true عامل becomes live. (2) This same phenomenon is also called <bdi>الإعمال</bdi> — grammarians and مفسّرون use the two names interchangeably. (3) Grammarians are divided over whether the first or the second of the two competing words is the true عامل (يَجوزُ أَنْ يَكونَ العامِلُ الأَوَّلَ أَوِ الثّاني); either reading gives the same إعراب outcome, so it makes no practical difference.`, list: false },
            { box: { title: 'Rule', lines: [`قَدْ يَتَنازَعُ أَكْثَرُ مِنِ اثْنَيْنِ`] } },
            { html: `The competition is not limited to exactly two عوامل — three or more can compete for the same shared معمول at once.`, list: false },
            { box: { title: 'Example', lines: [`«تُسَبِّحونَ وَتَحْمَدونَ وَتُكَبِّرونَ دُبُرَ كُلِّ صَلاةٍ ثَلاثًا وَثَلاثينَ مَرَّةً»`] } },
            { html: `"You say سبحان الله, الحمد لله, and الله أكبر after every prayer, thirty-three times [each]." All three verbs — <bdi>تُسَبِّحونَ</bdi>، <bdi>تَحْمَدونَ</bdi>، <bdi>تُكَبِّرونَ</bdi> — compete for the same shared دُبُرَ كُلِّ صَلاةٍ and ثَلاثًا وَثَلاثينَ مَرَّةً.`, list: false },
          ],
          exercise: {
            prompt: `Grammarians disagree over whether the first or the second of two competing عوامل is the true عامل in a case of التنازع. Does this disagreement change the resulting إعراب?`,
            kind: 'mcq',
            options: [`No — either reading gives the same practical outcome`, `Yes — only the first عامل is ever correct`, `Yes — only the second عامل is ever correct`, `Yes — التنازع becomes ungrammatical unless the dispute is resolved`],
            correct: 0,
          },
        },
        {
          heading: 'حذف عامل المفعول المطلق: التعريف والقياسي (الموضعان الأولان)',
          lines: [
            { html: `الخاتِمَة's second فصل is <bdi>حَذْف العامِل</bdi> — situations where a governor is dropped entirely, leaving only its معمول behind. حَذْف splits into قِسْمانِ: <bdi>حَذْف جائِز</bdi> (optional, recoverable from context) and <bdi>حَذْف واجِب</bdi> (obligatory — the عامل is never spoken, by rule). حذف واجب itself has ثلاثة أضرب; this concept opens the first — <bdi>حَذْف عامِل المَفْعول المُطْلَق</bdi>, a مصدر standing entirely alone, its governing فعل permanently unspoken.`, list: false },
            { box: { title: 'Definition', lines: [`حَذْفُ عامِلِ المَفْعولِ المُطْلَقِ الواجِب: قِياسِيّ (أربعة مواضع ثابتة)، وسَماعِيّ (عبارات مسموعة فقط)`] } },
            { html: `<bdi>قياسي</bdi> covers four fixed, generalizable patterns; <bdi>سماعي</bdi> covers a handful of set مصادر attested only in specific transmitted phrases — usable as they stand, but not extendable by analogy to new sentences.`, list: false },
            { box: { title: 'Rule', lines: [`١. الواقِعُ نَهْيًا تابِعًا لِمَصْدَرٍ يُرادُ بِهِ الأَمْرُ. ٢. الواقِعُ بَعْدَ الِاسْتِفْهامِ لِلتَّوْبيخِ.`] } },
            { html: `(1) A مصدر functioning as a نهي (prohibition), paired right after a مصدر functioning as an أمر (command) — both governing أفعال are dropped. (2) A مصدر appearing after an استفهام particle used for تَوْبيخ (rebuke), not genuine information-seeking.`, list: false },
            { box: { title: 'Example', lines: [`صَبْرًا لا جَزَعًا`] } },
            { html: `"[Show] patience, not panic!" — i.e. اُصْبِرْ صَبْرًا وَلا تَجْزَعْ جَزَعًا, with both اُصْبِرْ and لا تَجْزَعْ dropped. <bdi>حَمْدًا وَشُكْرًا لا كُفْرًا</bdi> ("gratitude and thanks, not ingratitude!") and <bdi>اِجْتِهادًا لا كَسَلًا</bdi> ("diligence, not laziness!") follow the same pattern.`, list: false },
            { box: { title: 'Example', lines: [`أَجُرْأَةً على المَعاصي؟`] } },
            { html: `"[Are you showing such] boldness in disobedience?!" — i.e. أَتَجْتَرِئُ جُرْأَةً عَلَى الْمَعاصي, with أَتَجْتَرِئُ dropped. The question is a rebuke, not a real request for information.`, list: false },
          ],
          exercise: {
            prompt: `صَبْرًا لا جَزَعًا drops both governing أفعال (اُصْبِرْ and لا تَجْزَعْ), leaving only the two مصادر. Which pattern of القياسي في حذف عامل المفعول المطلق does this illustrate?`,
            kind: 'mcq',
            options: [`نهي تابع لمصدر يراد به الأمر`, `الواقع بعد استفهام التوبيخ`, `الواقع بعد إمّا تفصيلًا لمجمل`, `المؤكِّد لمضمون الجملة`],
            correct: 0,
          },
        },
        {
          heading: 'القياسي: بعد إمّا تفصيلًا، والمؤكِّد لمضمون الجملة',
          lines: [
            { html: `The remaining two قياسي patterns close out the four.`, list: false },
            { box: { title: 'Rule', lines: [`٣. الواقِعُ بَعْدَ إِمّا تَفْصيلًا لِمُجْمَلٍ قَبْلَهُ. ٤. المُؤَكِّدُ لِمَضْمونِ الجُمْلَةِ.`] } },
            { html: `(3) A مصدر appearing after إمّا, spelling out (تَفْصيل) specifics that were stated only in summary (مُجْمَل) just before. (4) A مصدر that emphasizes the truth of the entire sentence, not just one word within it.`, list: false },
            { box: { title: 'Example', lines: [`﴿فَشُدّوا الْوَثاقَ فَإِمّا مَنًّا بَعْدُ وَإِمّا فِداءً﴾`] } },
            { html: `"So bind [their] fetters firmly; then either grant favor afterward, or [demand] ransom." شُدّوا الْوَثاقَ states the matter in summary; <bdi>مَنًّا</bdi> and <bdi>فِداءً</bdi> then spell out the two specific options, each standing for a dropped verb (تَمُنّونَ مَنًّا / تُفادونَ فِداءً).`, list: false },
            { box: { title: 'Example', lines: [`﴿أولٰئِكَ هُمُ الْمُؤْمِنونَ حَقًّا﴾`] } },
            { html: `"Those are the believers, in truth." <bdi>حَقًّا</bdi> does not emphasize any single word in the sentence — it emphasizes the truth of the whole preceding sentence. A family of مصادر works the same way: <bdi>بَتًّا، بَتاتًا، بَتَّةً، الْبَتَّةَ</bdi> (with هَمْزَة وَصْل), and <bdi>أَلْبَتَّةَ</bdi> (with هَمْزَة قَطْع) — all meaning "absolutely, definitely, at all."`, list: false },
          ],
          exercise: {
            prompt: `In ﴿أولٰئِكَ هُمُ الْمُؤْمِنونَ حَقًّا﴾, does حَقًّا emphasize one particular word in the sentence, or the sentence's truth as a whole?`,
            kind: 'mcq',
            options: [`The sentence's truth as a whole — it is المؤكِّد لمضمون الجملة`, `Only المؤمنون, as its نعت`, `Only أولٰئِكَ, as its توكيد`, `Nothing — حَقًّا here has no emphatic function`],
            correct: 0,
          },
        },
        {
          heading: 'السماعي، ولبيك وأخواتها',
          lines: [
            { html: `Beyond the four قياسي patterns, a handful of set مصادر drop their عامل simply because that is how the Arabs were heard using them — <bdi>سَماعِيّ</bdi>, attested but not a general pattern extendable to new phrases.`, list: false },
            { box: { title: 'Example', lines: [`سُبْحانَ اللهِ، مَعاذَ اللهِ، عَجَبًا لَكَ، وَلَبَّيْكَ وَأَخَواتِها`] } },
            { html: `<bdi>لَبَّيْكَ وَأَخَواتِها</bdi> — <bdi>لَبَّيْكَ، سَعْدَيْكَ، حَنانَيْكَ، دَوالَيْكَ، حَذارَيْكَ</bdi> — round out the سماعي list.`, list: false },
            { box: { title: 'Careful', lines: [`هِيَ مَصادِرُ سُمِعَتْ مُثَنّاةً، لا حَقيقَةُ التَّثْنِيَةِ`] } },
            { html: `لَبَّيْكَ وَأَخَواتِها look like مُثَنّى (dual) forms, and the matn confirms they were heard in dual shape — but the dual here is <bdi>مَجاز</bdi> (figurative), used for <bdi>التَّكْثير</bdi> (repeated, intensified action), not a literal claim of "exactly twice." لَبَّيْكَ does not mean "I am present twice"; it means "I am present, response after response" — repeated, ongoing readiness to answer the call.`, list: false },
          ],
          exercise: {
            prompt: `لَبَّيْكَ looks like a dual (مثنى) form. Does it literally mean "I am present exactly twice"?`,
            kind: 'mcq',
            options: [`No — the dual shape here is مجاز for التكثير, repeated readiness to answer`, `Yes — it is a genuine مثنى`, `No — it is not related to تثنية at all`, `Yes, but only when repeated twice in speech`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `Two verbs, كُلوا and اشْرَبوا, each independently want the same shared معمول, مِنْ رِزْقِ اللهِ, which appears only once after both. What grammatical name does this construction carry?`, options: [`التنازع (or الإعمال)`, `الاشتغال`, `الاختصاص`, `التحذير`], correct: 0 },
        { q: `In ﴿وَإِنْ أَدْري أَقَريبٌ أَمْ بَعيدٌ ما توعَدونَ﴾, أَقَريب and بَعيد are which kind of متنازِعان؟`, options: [`اسمان (عاملان اسميّان competing for the same فاعل)`, `فعلان competing for the same مفعول به`, `حرفان جر competing for the same مجرور`, `They are not متنازِعان at all`], correct: 0 },
        { q: `صَبْرًا لا جَزَعًا drops two governing أفعال — the أمر and the نهي that follows it. Which قياسي pattern of حذف عامل المفعول المطلق is this?`, options: [`نهي تابع لمصدر يراد به الأمر`, `الواقع بعد استفهام التوبيخ`, `الواقع بعد إمّا تفصيلًا لمجمل`, `المؤكِّد لمضمون الجملة`], correct: 0 },
        { q: `أَجُرْأَةً على المَعاصي؟ is a rebuke, not a genuine request for information. Which قياسي pattern does it illustrate?`, options: [`الواقع بعد استفهام التوبيخ`, `نهي تابع لمصدر يراد به الأمر`, `الواقع بعد إمّا تفصيلًا لمجمل`, `المؤكِّد لمضمون الجملة`], correct: 0 },
        { q: `﴿فَشُدّوا الْوَثاقَ فَإِمّا مَنًّا بَعْدُ وَإِمّا فِداءً﴾ states its matter in summary, then مَنًّا and فِداءً spell out the specifics. What is that relationship called؟`, options: [`تفصيل لمجمل قبله`, `توبيخ`, `تأكيد لمضمون الجملة`, `نهي تابع لأمر`], correct: 0 },
        { q: `سُبْحانَ اللهِ and لَبَّيْكَ drop their governing فعل, but not because they follow one of the four قياسي rules. What kind of drop is this?`, options: [`سماعي — attested phrases, not extendable by analogy`, `قياسي الأول`, `قياسي الرابع`, `They do not drop any عامل at all`], correct: 0 },
      ],
      bank: [
        { title: `التنازع: التعريف`, kind: 'mcq', prompt: `Which definition correctly describes التنازع?`, options: [`Two عاملان competing over one معمول that comes after both of them`, `A noun placed before a verb that governs its own pronoun`, `Putting the noun in نصب via an omitted verb expressing تحذير (warning)`, `Putting the noun in نصب via an omitted verb that specifies what a preceding pronoun refers to`], correct: 0 },
        { title: `فعلان أو اسمان`, kind: 'mcq', prompt: `The two متنازِعان in a case of التنازع can be:`, options: [`فعلان، أو اسمان عاملان`, `حرفان جر فقط`, `فعل واسم فقط، لا فعلان ولا اسمان`, `ثلاثة أفعال فقط، لا اسمان أبدًا`], correct: 0 },
        { title: `سبب وقوع التنازع`, kind: 'mcq', prompt: `Why does التنازع happen at all, rather than the shared معمول being repeated once for each عامل؟`, options: [`الإيجاز — the Arabs' preference for saying more with less, with no loss of meaning`, `Because repeating the معمول is grammatically forbidden`, `Because only one of the two عوامل actually carries any meaning`, `Because التنازع only happens in poetry`], correct: 0 },
        { title: `اسم آخر للتنازع`, kind: 'mcq', prompt: `التنازع is also known by which other name?`, options: [`الإعمال`, `الاشتغال`, `الإغراء`, `الاختصاص`], correct: 0 },
        { title: `أي العاملين هو العامل؟`, kind: 'mcq', prompt: `Grammarians disagree over which of the two متنازعان is the true عامل. What is the practical effect of that disagreement on الإعراب؟`, options: [`None — either reading gives the same outcome`, `The جملة becomes ungrammatical until the dispute is resolved`, `Only the first عامل can ever be correct`, `Only the second عامل can ever be correct`], correct: 0 },
        { title: `تنازع أكثر من عاملين`, kind: 'mcq', prompt: `«تُسَبِّحونَ وَتَحْمَدونَ وَتُكَبِّرونَ دُبُرَ كُلِّ صَلاةٍ ثَلاثًا وَثَلاثينَ مَرَّةً» shows how many عوامل competing for the same shared معمول؟`, options: [`Three`, `Exactly two, never more`, `One`, `Four`], correct: 0 },
        { title: `حذف العامل: قسمان`, kind: 'mcq', prompt: `حَذْف العامل divides into which two قسمان؟`, options: [`حذف جائز (recoverable from context) وحذف واجب (never spoken, by rule)`, `حذف قياسي وحذف اصطلاحي`, `حذف لفظي وحذف معنوي فقط`, `حذف تام وحذف ناقص`], correct: 0 },
        { title: `حذف عامل المفعول المطلق: قسماه`, kind: 'mcq', prompt: `حذف عامل المفعول المطلق الواجب itself splits into which two kinds؟`, options: [`قياسي (أربعة مواضع ثابتة) وسماعي (عبارات مسموعة فقط)`, `لفظي وتقديري فقط`, `جائز وممتنع`, `متصل ومنقطع`], correct: 0 },
        { title: `حمدا وشكرا لا كفرا`, kind: 'mcq', prompt: `حَمْدًا وَشُكْرًا لا كُفْرًا drops the same two أفعال (أمر ونهي) that صَبْرًا لا جَزَعًا does. Which قياسي pattern is this؟`, options: [`نهي تابع لمصدر يراد به الأمر`, `الواقع بعد استفهام التوبيخ`, `المؤكِّد لمضمون الجملة`, `الواقع بعد إمّا تفصيلًا`], correct: 0 },
        { title: `اجتهادا لا كسلا`, kind: 'mcq', prompt: `اِجْتِهادًا لا كَسَلًا follows the same pattern as صَبْرًا لا جَزَعًا. What is its dropped أمر verb understood to be؟`, options: [`اِجْتَهِدْ`, `اُصْبِرْ`, `اِعْبُدْ`, `اِذْهَبْ`], correct: 0 },
        { title: `استفهام التوبيخ`, kind: 'mcq', prompt: `أَجُرْأَةً على المَعاصي؟ is not a genuine question. What kind of استفهام is it؟`, options: [`استفهام للتوبيخ — a rebuke, not a real request for information`, `استفهام حقيقي seeking new information`, `استفهام للتصوّر, offering the listener a choice`, `Not استفهام at all — it is a plain statement`], correct: 0 },
        { title: `مجمل ثم تفصيل`, kind: 'mcq', prompt: `﴿فَشُدّوا الْوَثاقَ فَإِمّا مَنًّا بَعْدُ وَإِمّا فِداءً﴾ — شُدّوا الْوَثاقَ states the matter مجملًا. What do مَنًّا and فِداءً do to it؟`, options: [`They spell out (تفصيل) the two specific options it summarizes`, `They repeat the same command a second time`, `They negate the command entirely`, `They introduce a new, unrelated command`], correct: 0 },
        { title: `حقا: مؤكد لأي شيء؟`, kind: 'mcq', prompt: `In ﴿أولٰئِكَ هُمُ الْمُؤْمِنونَ حَقًّا﴾, حَقًّا reaffirms which part of the sentence؟`, options: [`The whole preceding sentence, not one word within it`, `Only المؤمنون`, `Only أولٰئِكَ`, `Only هُمُ`], correct: 0 },
        { title: `بتة وألبتة`, kind: 'mcq', prompt: `بَتًّا، بَتاتًا، بَتَّةً، الْبَتَّةَ، and أَلْبَتَّةَ all belong to which قياسي pattern of حذف عامل المفعول المطلق؟`, options: [`المؤكِّد لمضمون الجملة`, `نهي تابع لمصدر يراد به الأمر`, `الواقع بعد استفهام التوبيخ`, `الواقع بعد إمّا تفصيلًا لمجمل`], correct: 0 },
        { title: `سماعي: ما لا يقاس عليه`, kind: 'mcq', prompt: `سُبْحانَ اللهِ، مَعاذَ اللهِ، and عَجَبًا لَكَ drop their governing فعل. Can a learner build a brand-new phrase on the same pattern by analogy؟`, options: [`No — these are سماعي, attested only in these specific phrases`, `Yes — سماعي phrases are freely extendable to new sentences`, `Yes, but only in poetry`, `No — none of these phrases actually drop a governing فعل`], correct: 0 },
        { title: `لبيك وأخواتها: عددها`, kind: 'mcq', prompt: `لَبَّيْكَ وَأَخَواتِها includes لَبَّيْكَ itself plus how many further مصادر on the same pattern؟`, options: [`Four — سَعْدَيْكَ، حَنانَيْكَ، دَوالَيْكَ، حَذارَيْكَ`, `One only`, `Two — سَعْدَيْكَ وَحَنانَيْكَ`, `Seven`], correct: 0 },
        { title: `لبيك: المعنى الحقيقي`, kind: 'mcq', prompt: `What does لَبَّيْكَ actually convey, given that its dual shape is مجاز rather than a literal count؟`, options: [`Repeated, ongoing readiness to answer the call`, `A literal claim of responding exactly twice`, `A refusal to respond at all`, `A single, one-time response`], correct: 0 },
        { title: `حذف عامل المصدر: أين موضعه في الخاتمة`, kind: 'mcq', prompt: `حَذْف عامِل المَفْعول المُطْلَق is the first of ثلاثة أضرب under which broader فصل of الخاتِمَة؟`, options: [`حذف العامل`, `التنازع`, `الاشتغال`, `النداء`], correct: 0 },
        {
          title: `تركيب: كُلوا واشْرَبوا مِنْ رِزْقِ اللهِ`,
          kind: 'tarkeeb',
          instruction: `Identify the role of each part of ﴿كُلوا واشْرَبوا مِنْ رِزْقِ اللهِ﴾, where two verbs compete for one shared معمول.`,
          source: `كُلوا واشْرَبوا مِنْ رِزْقِ اللهِ`,
          words: [`كُلوا`, `وَاشْرَبوا`, `مِنْ رِزْقِ اللهِ`],
          labels: [`أحد المتنازِعَين (فعل أمر)`, `المتنازِع الثاني (فعل أمر)`, `المعمول المشترك المتنازَع فيه`],
          distractors: [`حال`, `مفعول مطلق`],
        },
        {
          title: `تركيب: أَقَريبٌ أَمْ بَعيدٌ ما توعَدونَ`,
          kind: 'tarkeeb',
          instruction: `Identify the role of each part, where two اسم عامل words compete for one فاعل.`,
          source: `أَقَريبٌ أَمْ بَعيدٌ ما توعَدونَ`,
          words: [`أَقَريبٌ`, `أَمْ بَعيدٌ`, `ما توعَدونَ`],
          labels: [`أحد المتنازِعَين (صفة مشبهة عاملة)`, `المتنازِع الثاني (صفة مشبهة عاملة)`, `الفاعل المتنازَع فيه`],
          distractors: [`خبر`, `مفعول به`],
        },
        {
          title: `تركيب: صَبْرًا لا جَزَعًا`,
          kind: 'tarkeeb',
          instruction: `Identify the role of each مصدر in صَبْرًا لا جَزَعًا, where both governing أفعال are dropped.`,
          source: `صَبْرًا لا جَزَعًا`,
          words: [`صَبْرًا`, `لا جَزَعًا`],
          labels: [`مفعول مطلق لفعل أمر محذوف وجوبًا`, `مفعول مطلق لفعل نهي محذوف وجوبًا`],
          distractors: [`حال`, `مفعول به`],
        },
        {
          title: `تركيب: أَجُرْأَةً على المَعاصي`,
          kind: 'tarkeeb',
          instruction: `Identify the role of جُرْأَةً in أَجُرْأَةً على المَعاصي؟, a rebuke rather than a real question.`,
          source: `أَجُرْأَةً على المَعاصي`,
          words: [`أَ`, `جُرْأَةً`, `على المَعاصي`],
          labels: [`حرف استفهام للتوبيخ`, `مفعول مطلق لفعل محذوف وجوبًا`, `متعلق بالفعل المحذوف`],
          distractors: [`مبتدأ`, `فاعل`],
        },
        {
          title: `تركيب: فَإِمّا مَنًّا بَعْدُ وَإِمّا فِداءً`,
          kind: 'tarkeeb',
          instruction: `Identify the role of each مصدر in فَإِمّا مَنًّا بَعْدُ وَإِمّا فِداءً, where each spells out one option after إمّا.`,
          source: `فَإِمّا مَنًّا بَعْدُ وَإِمّا فِداءً`,
          words: [`مَنًّا`, `فِداءً`],
          labels: [`مفعول مطلق لفعل محذوف تقديره تَمُنّونَ`, `مفعول مطلق لفعل محذوف تقديره تُفادونَ`],
          distractors: [`حال`, `خبر`],
        },
        {
          title: `تركيب: أولٰئِكَ هُمُ الْمُؤْمِنونَ حَقًّا`,
          kind: 'tarkeeb',
          instruction: `Identify the role of حَقًّا in أولٰئِكَ هُمُ الْمُؤْمِنونَ حَقًّا, which reaffirms the whole sentence rather than one word.`,
          source: `أولٰئِكَ هُمُ الْمُؤْمِنونَ حَقًّا`,
          words: [`أولٰئِكَ`, `هُمُ الْمُؤْمِنونَ`, `حَقًّا`],
          labels: [`مبتدأ`, `ضمير فصل مع الخبر`, `مفعول مطلق مؤكِّد لمضمون الجملة`],
          distractors: [`حال`, `تمييز`],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'التحذير والإغراء والاختصاص',
      subtitle: 'Warning, Encouragement, and Pinning Down a Pronoun — three of the خمسة مواضع under حذف عامل المفعول به, each a noun made منصوب by a permanently dropped verb',
      concepts: [
        {
          heading: 'التحذير: تعريفه والفرق بينه وبين التوبيخ',
          lines: [
            { html: `الضَّرْب الثّاني of حَذْف العامِل الواجب is <bdi>حَذْفُ عامِلِ المَفْعولِ بِهِ</bdi>, covering خَمْسَة مَواضِع. The first and richest of them is <bdi>التَّحْذير</bdi> — warning someone away from something.`, list: false },
            { box: { title: 'Definition', lines: [`التَّحْذير: نَصْبُ الاِسْمِ بِفِعْلٍ مَحْذوفٍ يُفيدُ التَّحْذيرَ مِنْ أَمْرٍ مَكْروهٍ لِيَجْتَنِبَهُ المُخاطَبُ`] } },
            { html: `A noun made مَنْصوب by a dropped فعل, conveying a warning about something disliked, so the listener avoids it. التحذير looks toward the future — "don't do this" — which sets it apart from <bdi>تَوْبيخ</bdi> (rebuke): تَوْبيخ scolds someone for something already done, while تحذير warns them away from something not yet done.`, list: false },
          ],
          exercise: {
            prompt: `التحذير and تَوْبيخ can both sound like scolding, but they point in different directions in time. Which one warns about something not yet done؟`,
            kind: 'mcq',
            options: [`التحذير`, `التوبيخ`, `Both point to the past`, `Neither points to a specific time`],
            correct: 0,
          },
        },
        {
          heading: 'أركان التحذير ووجهه الأول: إيّاكَ',
          lines: [
            { box: { title: 'Rule', lines: [`لِلتَّحْذيرِ أَرْبَعَةُ أَرْكانٍ: فِعْلُ التَّحْذيرِ المُقَدَّر، والمُحَذِّر، والمُحَذَّر، والمُحَذَّر مِنْه`] } },
            { html: `(1) <bdi>فِعْلُ التَّحْذيرِ المُقَدَّر</bdi> — the dropped verb itself: اِحْذَرْ، باعِدْ، تَجَنَّبْ، قِ، تَوَقَّ, or any verb of avoidance; (2) <bdi>المُحَذِّر</bdi> — the one warning, المُتَكَلِّم; (3) <bdi>المُحَذَّر</bdi> — the one being warned, المُخاطَب; (4) <bdi>المُحَذَّر مِنْه</bdi> — the thing warned against.`, list: false },
            { html: `Three ways build the first of التحذير's three وجوه — mentioning المحذَّر with the separate pronoun <bdi>إيّاكَ</bdi>.`, list: false },
            { box: { title: 'Rule', lines: [`أ. بِعَطْفِ المُحَذَّرِ مِنْهُ عَلَيْهِ. ب. بِنَصْبِهِ مَعَ تَكْرارِ الضَّميرِ. ج. بِجَرِّهِ بِـ"مِنْ" لَفْظًا أَوْ تَقْديرًا.`] } },
            { box: { title: 'Example', lines: [`إِيّاكَ والْحَسَدَ`] } },
            { html: `"[Beware,] you and envy!" — i.e. "Beware of envy!" — المحذَّر منه (الحسد) is عطف onto إيّاكَ.`, list: false },
            { box: { title: 'Example', lines: [`إِيّاكَ مِنَ الحَسَدِ`] } },
            { html: `"Beware of envy" — المحذَّر منه here is جر بـ"من" لفظًا. The same structure works تقديرًا, with مِن understood rather than spoken: <bdi>إِيّاكَ أَنْ تَحْسُدَ</bdi>, "beware lest you envy."`, list: false },
          ],
          exercise: {
            prompt: `إِيّاكَ والْحَسَدَ builds الوجه الأول of التحذير by joining الحسد onto إيّاكَ. Which of the three ways of building this وجه is that؟`,
            kind: 'mcq',
            options: [`عطف المحذَّر منه على إيّاكَ`, `تكرار الضمير المنفصل مع نصب المحذَّر منه`, `جر المحذَّر منه بمن`, `ذكر المحذَّر باسم ظاهر`],
            correct: 0,
          },
        },
        {
          heading: 'وجها التحذير الثاني والثالث، والتحذير بلا حذف الفعل',
          lines: [
            { html: `الوجه الثاني replaces إيّاكَ with a plain اسم ظاهر — <bdi>نَفْسَكَ</bdi> ("yourself") — built the same three ways: (أ) alone, (ب) repeated, (ج) with المحذَّر منه joined onto it by عطف.`, list: false },
            { box: { title: 'Example', lines: [`نَفْسَكَ والحَسَدَ`] } },
            { html: `"Yourself and envy!" — i.e. "Save yourself from envy!"`, list: false },
            { html: `الوجه الثالث drops both إيّاكَ and any اسم ظاهر subject — only المحذَّر منه itself appears, either (أ) repeated twice, or (ب) joined by عطف to a second thing warned against.`, list: false },
            { box: { title: 'Example', lines: [`اللهَ اللهَ`] } },
            { html: `"[Fear] Allah, [fear] Allah!" — a famous exhortation, المحذَّر منه repeated with nothing else stated.`, list: false },
            { box: { title: 'Careful', lines: [`التَّحْذيرُ لُغَةً لَيْسَ دائِمًا هُوَ التَّحْذيرُ اصْطِلاحًا`] } },
            { html: `﴿قوا أَنْفُسَكُمْ وَأَهْليكُمْ نارًا﴾ genuinely warns the listener in plain meaning (تحذير لُغَةً), but <bdi>قوا</bdi> is a fully spoken command verb, not a dropped one — so this is not تحذير اصْطِلاحًا, the specific grammatical construction covered here, even though it plainly is a warning.`, list: false },
          ],
          exercise: {
            prompt: `﴿قوا أَنْفُسَكُمْ وَأَهْليكُمْ نارًا﴾ genuinely warns the listener. Does it count as التحذير اصطلاحًا, the grammatical construction this lesson defines؟`,
            kind: 'mcq',
            options: [`No — قوا is a fully spoken command verb, not a dropped one`, `Yes — any sentence that warns is تحذير اصطلاحًا`, `Yes, because نارًا is منصوب`, `No, because the sentence contains no warning at all`],
            correct: 0,
          },
        },
        {
          heading: 'الإغراء: تعريفه وأركانه ووجوب حذف عامله',
          lines: [
            { html: `الإغراء is التحذير's mirror image — instead of warning the listener away from something disliked, it encourages them toward something good.`, list: false },
            { box: { title: 'Definition', lines: [`الإِغْراء: نَصْبُ الاسْمِ بِفِعْلٍ مَحْذوفٍ يُفيدُ التَّرْغيبَ والتَّشْويقَ إِلى مَرْغوبٍ لِيَفْعَلَهُ المُخاطَبُ`] } },
            { box: { title: 'Rule', lines: [`أَرْكانُ الإِغْراءِ أَرْبَعَةٌ: فِعْلُ الإِغْراءِ المُقَدَّر، والمُغْري، والمُغْرَى، والمُغْرَى بِه`] } },
            { html: `Its four أركان mirror التحذير's exactly: (1) <bdi>فِعْلُ الإِغْراءِ المُقَدَّر</bdi> — اِلْزَمْ، اُطْلُبْ، خُذْ، اِفْعَلْ; (2) <bdi>المُغْري</bdi> — the encourager, المُتَكَلِّم; (3) <bdi>المُغْرَى</bdi> — the one encouraged, المُخاطَب; (4) <bdi>المُغْرَى بِهِ</bdi> — the good thing urged.`, list: false },
            { box: { title: 'Rule', lines: [`يَجِبُ حَذْفُ فِعْلِ الإِغْراءِ: إِذا تَكَرَّرَ المُغْرَى بِهِ، وَإِذا عُطِفَ عَلَيْهِ`] } },
            { box: { title: 'Example', lines: [`الصَّبْرَ الصَّبْرَ`] } },
            { html: `"Patience, patience!" — تكرار المغرى به.`, list: false },
            { box: { title: 'Example', lines: [`العِلْمَ والْحِلْمَ`] } },
            { html: `"[Pursue] knowledge and forbearance!" — عطف. ﴿يا يَحْيى خُذِ الْكِتابَ بِقُوَّةٍ﴾ genuinely encourages taking the Book, but خُذِ is a fully spoken verb, not dropped — إغراء in plain meaning, not إغراء اصطلاحًا, the same distinction drawn for التحذير.`, list: false },
          ],
          exercise: {
            prompt: `Exactly as with التحذير, فِعْل الإغراء must be dropped in two situations. What are they؟`,
            kind: 'mcq',
            options: [`إذا تكرر المغرى به، أو إذا عُطف عليه`, `إذا كان المغرى به معرفة فقط`, `إذا سبقه حرف جر`, `الحذف هنا جائز، لا واجب أبدًا`],
            correct: 0,
          },
        },
        {
          heading: 'ملحقات بالتحذير والإغراء',
          lines: [
            { html: `A small set of fixed expressions follow the same عامل-محذوف pattern — a noun made منصوب by an unspoken verb — without themselves being a warning or an encouragement. They are simply <bdi>مُلْحَق</bdi> (attached) to this family because they work the same grammatical way.`, list: false },
            { box: { title: 'Example', lines: [`مَرْحَبًا، وَأَهْلًا وَسَهْلًا`] } },
            { html: `بِتَقْديرِ <bdi>أَصَبْتَ</bdi> — "[you have found/attained] a spacious place, a welcoming family, level ground" — the dropped verb is <bdi>أَصَبْتَ</bdi>, "you have attained."`, list: false },
            { box: { title: 'Example', lines: [`وَامْرَءًا وَنَفْسَهُ`] } },
            { html: `بِتَقْديرِ <bdi>دَعْ</bdi> — "leave a man to himself" — the dropped verb is <bdi>دَعْ</bdi>, "leave!"`, list: false },
          ],
          exercise: {
            prompt: `مَرْحَبًا is ملحق بالتحذير والإغراء rather than being either one itself. What dropped verb does it stand for؟`,
            kind: 'mcq',
            options: [`أَصَبْتَ`, `دَعْ`, `اِحْذَرْ`, `اِلْزَمْ`],
            correct: 0,
          },
        },
        {
          heading: 'الاختصاص: تعريفه وغرضه، وبأيّها/أيّتها',
          lines: [
            { html: `The third موضع, <bdi>الاختصاص</bdi>, does a different job than التحذير or الإغراء: it pins down exactly who a pronoun refers to, whenever that pronoun alone could be ambiguous.`, list: false },
            { box: { title: 'Definition', lines: [`الِاخْتِصاص: نَصْبُ الاسْمِ بِفِعْلٍ مَحْذوفٍ يُعَيِّنُ المُرادَ مِنَ الضَّميرِ قَبْلَهُ، مِثْلُ أَخُصُّ أَوْ أَعْني`] } },
            { box: { title: 'Example', lines: [`﴿رَحْمَتُ اللهِ وَبَرَكاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾`] } },
            { html: `"The mercy of Allah and His blessings be upon you, O people of the house." عَلَيْكُمْ alone could refer broadly to الصَّحابة, المُهاجِرون, or الأَنْصار — <bdi>أَهْلَ الْبَيْتِ</bdi> (منصوب) pins the pronoun down: أَعْني أَهْلَ الْبَيْتِ.`, list: false },
            { html: `الاختصاص can also be built with <bdi>أَيُّها/أَيَّتُها</bdi>, but without the يا of نداء — even without يا, it still follows the same إعراب rules as نداء.`, list: false },
            { box: { title: 'Example', lines: [`كَلامِنا أَيُّها الثَّلاثَةُ`] } },
            { html: `From حديث Kaʿb ibn Mālik: "speaking to us, the three [of us]." <bdi>أَيُّها الثَّلاثَةُ</bdi> specifies exactly who كَلامِنا refers to, with no يا present.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿رَحْمَتُ اللهِ وَبَرَكاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾, عَلَيْكُمْ alone could refer broadly to several groups. What does أَهْلَ الْبَيْتِ, by الاختصاص, do to that ambiguity؟`,
            kind: 'mcq',
            options: [`It pins down exactly who عَلَيْكُمْ refers to`, `It negates عَلَيْكُمْ entirely`, `It converts عَلَيْكُمْ into a منادى`, `It has no effect — الاختصاص never resolves ambiguity`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `التحذير warns the listener about something. Which of these best distinguishes it from تَوْبيخ؟`, options: [`التحذير looks to the future; توبيخ scolds for something already done`, `توبيخ looks to the future; التحذير scolds for something already done`, `They are simply two names for the same construction`, `التحذير never involves a dropped فعل, unlike توبيخ`], correct: 0 },
        { q: `إِيّاكَ إِيّاكَ المِراءَ repeats the separate pronoun and then states المحذَّر منه منصوبًا, without عطف. Which of the three ways of building الوجه الأول is that؟`, options: [`تكرار الضمير المنفصل مع نصب المحذَّر منه بلا عطف`, `عطف المحذَّر منه على إيّاكَ`, `جر المحذَّر منه بمن`, `ذكر المحذَّر باسم ظاهر`], correct: 0 },
        { q: `اللهَ اللهَ warns by repeating المحذَّر منه alone, with neither إيّاكَ nor an اسم ظاهر subject mentioned. Which وجه of التحذير is that؟`, options: [`الوجه الثالث`, `الوجه الأول`, `الوجه الثاني`, `It is not one of the three وجوه at all`], correct: 0 },
        { q: `الصَّبْرَ الصَّبْرَ requires فِعْل الإغراء to be dropped, not merely allows it. Why is the drop obligatory here؟`, options: [`Because المغرى به is repeated`, `Because المغرى به is معرفة`, `Because الصبر is مصدر`, `Dropping the فعل is never obligatory in الإغراء`], correct: 0 },
        { q: `مَرْحَبًا and وَامْرَءًا وَنَفْسَهُ both follow the عامل-محذوف pattern of التحذير/الإغراء without themselves being either one. What is this category called؟`, options: [`مُلْحَق بالتحذير والإغراء`, `اختصاص`, `اشتغال`, `تنازع`], correct: 0 },
        { q: `كَلامِنا أَيُّها الثَّلاثَةُ builds الاختصاص with أَيُّها rather than a plain اسم. Does the absence of يا mean النداء's إعراب rules no longer apply؟`, options: [`No — even without يا, أيّها still follows النداء's إعراب rules`, `Yes — أيّها without يا follows entirely different rules`, `Yes — the construction becomes ungrammatical without يا`, `No — أيّها never follows النداء's rules, with or without يا`], correct: 0 },
      ],
      bank: [
        { title: `أركان التحذير`, kind: 'mcq', prompt: `لِلتَّحْذيرِ أَرْبَعَةُ أَرْكانٍ. What are they؟`, options: [`فعل التحذير المقدَّر، المُحَذِّر، المُحَذَّر، المُحَذَّر منه`, `المشغول، المشغول به، المشغول عنه`, `المُغْري، المُغْرَى، المُغْرَى بِه فقط`, `العامل والمعمول فقط`], correct: 0 },
        { title: `المحذِّر والمحذَّر`, kind: 'mcq', prompt: `In التحذير, who is المُحَذِّر, and who is المُحَذَّر؟`, options: [`المُحَذِّر is المُتَكَلِّم; المُحَذَّر is المُخاطَب`, `المُحَذِّر is المُخاطَب; المُحَذَّر is المُتَكَلِّم`, `Both roles are always the same person`, `Neither role is ever a person`], correct: 0 },
        { title: `إياك من الحسد: جر بمن لفظًا`, kind: 'mcq', prompt: `إِيّاكَ مِنَ الحَسَدِ builds الوجه الأول of التحذير. Which of the three sub-patterns is this؟`, options: [`جر المحذَّر منه بمن، لفظًا`, `عطف المحذَّر منه على إيّاكَ`, `تكرار الضمير مع نصب المحذَّر منه`, `ذكر المحذَّر باسم ظاهر`], correct: 0 },
        { title: `إياك أن تحسد: جر بمن تقديرًا`, kind: 'mcq', prompt: `إِيّاكَ أَنْ تَحْسُدَ conveys the same warning as إِيّاكَ مِنَ الحَسَدِ. Is مِن here لفظًا or تقديرًا؟`, options: [`تقديرًا — مِن is understood before أَنْ تَحْسُدَ`, `لفظًا — مِن is spoken outright`, `Neither — no مِن is implied at all here`, `تقديرًا, but only in poetry`], correct: 0 },
        { title: `نفسك: الوجه الثاني وحده`, kind: 'mcq', prompt: `نَفْسَكَ alone, with nothing else stated, is which of the three sub-patterns of الوجه الثاني؟`, options: [`ذكر المحذَّر باسم ظاهر وحده`, `تكرار الضمير المنفصل`, `عطف المحذَّر منه على اسم ظاهر`, `جر المحذَّر منه بمن`], correct: 0 },
        { title: `نفسك نفسك: تكرار الاسم الظاهر`, kind: 'mcq', prompt: `نَفْسَكَ نَفْسَكَ repeats the اسم ظاهر itself rather than إيّاكَ. Which sub-pattern of الوجه الثاني is that؟`, options: [`اسم ظاهر مكرَّر`, `اسم ظاهر وحده`, `اسم ظاهر معطوف عليه المحذَّر منه`, `ضمير منفصل مكرَّر`], correct: 0 },
        { title: `ناقة الله وسقياها: عطف محذَّر منه ثانٍ`, kind: 'mcq', prompt: `﴿ناقَةَ اللهِ وَسُقْياها﴾ warns Thamūd about two things at once — the she-camel and her turn to drink. Which sub-pattern of الوجه الثالث is that؟`, options: [`المحذَّر منه معطوفًا عليه محذَّر منه ثانٍ`, `المحذَّر منه مكرَّرًا`, `عطف المحذَّر منه على إيّاكَ`, `جر المحذَّر منه بمن`], correct: 0 },
        { title: `أركان الإغراء`, kind: 'mcq', prompt: `الإغراء's four أركان mirror التحذير's exactly, but flipped toward the positive. What are they؟`, options: [`فعل الإغراء المقدَّر، المُغْري، المُغْرَى، المُغْرَى بِه`, `فعل التحذير المقدَّر، المُحَذِّر، المُحَذَّر، المُحَذَّر منه`, `المشغول، المشغول به، المشغول عنه`, `العامل والمعمول والإعراب`], correct: 0 },
        { title: `العلم والحلم: عطف في الإغراء`, kind: 'mcq', prompt: `العِلْمَ والْحِلْمَ requires فعل الإغراء to be dropped. Why؟`, options: [`Because something is joined onto المغرى به by عطف`, `Because المغرى به is repeated`, `Because العلم is معرفة`, `The drop here is optional, not obligatory`], correct: 0 },
        { title: `يا يحيى خذ الكتاب: إغراء لغة لا اصطلاحًا`, kind: 'mcq', prompt: `﴿يا يَحْيى خُذِ الْكِتابَ بِقُوَّةٍ﴾ genuinely encourages taking the Book. Does it count as إغراء اصطلاحًا؟`, options: [`No — خُذِ is a fully spoken command verb, not a dropped one`, `Yes — any encouraging sentence is إغراء اصطلاحًا`, `Yes, because الكتاب is منصوب`, `No, because the sentence contains no encouragement at all`], correct: 0 },
        { title: `مرحبا: العامل المحذوف`, kind: 'mcq', prompt: `مَرْحَبًا is ملحق بالتحذير والإغراء. What is its dropped عامل, بتقدير؟`, options: [`أَصَبْتَ`, `دَعْ`, `اِحْذَرْ`, `اِلْزَمْ`], correct: 0 },
        { title: `امرءا ونفسه: العامل المحذوف`, kind: 'mcq', prompt: `وَامْرَءًا وَنَفْسَهُ means "leave a man to himself." What is its dropped عامل, بتقدير؟`, options: [`دَعْ`, `أَصَبْتَ`, `اُطْلُبْ`, `خُذْ`], correct: 0 },
        { title: `الاختصاص: التعريف`, kind: 'mcq', prompt: `Which of the following correctly defines الاختصاص؟`, options: [`Putting the noun in نصب via an omitted verb (like أخصّ or أعني) that specifies what a preceding pronoun refers to`, `Putting the noun in نصب via an omitted verb warning against something disliked`, `Putting the noun in نصب via an omitted verb encouraging something desirable`, `Two عاملان competing over one معمول that comes after both of them`], correct: 0 },
        { title: `الاختصاص: لماذا نحتاجه`, kind: 'mcq', prompt: `Why does a sentence need الاختصاص at all, when a pronoun like نَحْنُ or كُمْ is already grammatically complete on its own؟`, options: [`Because the pronoun alone can leave real ambiguity about exactly who is included`, `Because pronouns are never grammatically complete without it`, `Because الاختصاص is required after every plural pronoun`, `Because pronouns cannot be مسند إليه without it`], correct: 0 },
        { title: `نحن معشر الأنبياء`, kind: 'mcq', prompt: `نَحْنُ مَعْشَرَ الْأَنْبِياءِ specifies exactly who نَحْنُ refers to. What role does مَعْشَرَ الأَنْبِياءِ play؟`, options: [`مختص منصوب بفعل محذوف تقديره أخصّ`, `خبر مرفوع`, `مضاف إليه فقط، بلا نصب`, `فاعل لفعل محذوف`], correct: 0 },
        { title: `أيها الثلاثة: أحكام النداء بلا يا`, kind: 'mcq', prompt: `كَلامِنا أَيُّها الثَّلاثَةُ builds الاختصاص with أَيُّها, with no يا present. What إعراب rules does the phrase after أَيُّها still follow؟`, options: [`أحكام النداء — مرفوع, as if genuinely being called`, `أحكام الاستثناء`, `أحكام التمييز`, `No special rules — it behaves like any ordinary اسم`], correct: 0 },
        { title: `التحذير: الوظيفة`, kind: 'mcq', prompt: `Unlike التنازع, which resolves a competition between two عوامل for one معمول, what does التحذير do؟`, options: [`It warns the listener away from something disliked, using a dropped عامل`, `It resolves a competition between two عوامل`, `It pins down the reference of a pronoun`, `It encourages the listener toward something desirable`], correct: 0 },
        { title: `الإغراء مقابل التحذير: مقارنة الوظيفة`, kind: 'mcq', prompt: `Both التحذير and الإغراء drop their governing فعل and make المعمول منصوبًا, but they point in opposite directions. What does الإغراء do that التحذير does not؟`, options: [`It encourages the listener toward something desirable, rather than warning them away from something disliked`, `It never requires حذف العامل, unlike التحذير`, `It only ever works with اسم ظاهر, never a pronoun`, `It resolves competition between two عوامل`], correct: 0 },
        {
          title: `تركيب: إِيّاكَ والْحَسَدَ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of إِيّاكَ والْحَسَدَ, تحذير built by عطف المحذَّر منه على إيّاكَ.`,
          source: `إِيّاكَ والْحَسَدَ`,
          words: [`إِيّاكَ`, `وَ`, `الْحَسَدَ`],
          labels: [`المحذَّر، ضمير منصوب منفصل`, `حرف عطف`, `المحذَّر منه معطوف على إيّاكَ`],
          distractors: [`مبتدأ`, `فاعل`],
        },
        {
          title: `تركيب: نَفْسَكَ والحَسَدَ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of نَفْسَكَ والحَسَدَ, تحذير built with اسم ظاهر instead of إيّاكَ.`,
          source: `نَفْسَكَ والحَسَدَ`,
          words: [`نَفْسَكَ`, `وَ`, `الحَسَدَ`],
          labels: [`المحذَّر، اسم ظاهر منصوب`, `حرف عطف`, `المحذَّر منه معطوف`],
          distractors: [`خبر`, `حال`],
        },
        {
          title: `تركيب: اللهَ اللهَ`,
          kind: 'tarkeeb',
          instruction: `Identify the two words of اللهَ اللهَ, تحذير built by تكرار المحذَّر منه وحده.`,
          source: `اللهَ اللهَ`,
          words: [`اللهَ`, `اللهَ`],
          labels: [`المحذَّر منه الأول، منصوب بفعل محذوف وجوبًا`, `المحذَّر منه مكرَّرًا`],
          distractors: [`منادى`, `مفعول مطلق`],
        },
        {
          title: `تركيب: الصَّبْرَ الصَّبْرَ`,
          kind: 'tarkeeb',
          instruction: `Identify the two words of الصَّبْرَ الصَّبْرَ, إغراء built by تكرار المغرى به.`,
          source: `الصَّبْرَ الصَّبْرَ`,
          words: [`الصَّبْرَ`, `الصَّبْرَ`],
          labels: [`المغرى به الأول، منصوب بفعل محذوف وجوبًا`, `المغرى به مكرَّرًا`],
          distractors: [`مفعول مطلق`, `منادى`],
        },
        {
          title: `تركيب: العِلْمَ والْحِلْمَ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of العِلْمَ والْحِلْمَ, إغراء built by عطف على المغرى به.`,
          source: `العِلْمَ والْحِلْمَ`,
          words: [`العِلْمَ`, `وَ`, `الْحِلْمَ`],
          labels: [`المغرى به الأول، منصوب بفعل محذوف وجوبًا`, `حرف عطف`, `المغرى به الثاني معطوف`],
          distractors: [`حال`, `خبر`],
        },
        {
          title: `تركيب: نَحْنُ مَعْشَرَ الْأَنْبِياءِ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of نَحْنُ مَعْشَرَ الْأَنْبِياءِ, اختصاص pinning down the reference of نَحْنُ.`,
          source: `نَحْنُ مَعْشَرَ الْأَنْبِياءِ`,
          words: [`نَحْنُ`, `مَعْشَرَ الْأَنْبِياءِ`],
          labels: [`ضمير مبهم يحتاج تخصيصًا`, `مختص، منصوب بفعل محذوف تقديره أخصّ`],
          distractors: [`خبر`, `بدل مرفوع`],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الاشتغال',
      subtitle: 'The Fourth موضع — a fronted noun whose verb governs a pronoun referring back to it instead of the noun itself',
      concepts: [
        {
          heading: 'الاشتغال: التعريف',
          lines: [
            { html: `<bdi>الاشتغال</bdi> ("preoccupation") is the fourth of the خمسة مواضع under حَذْفُ عامِلِ المَفْعولِ بِهِ, and the most structurally involved of the five. A noun comes first in the sentence; a verb follows; but that verb is "busy" governing a pronoun referring back to the noun, instead of governing the noun itself directly.`, list: false },
            { box: { title: 'Definition', lines: [`الِاشْتِغال: أَنْ يَتَقَدَّمَ اسْمٌ على فِعْلٍ عامِلٍ في ضَميرِ ذلِكَ الاسْمِ، بِحَيْثُ لَوْ فُرِّغَ الفِعْلُ مِنَ العَمَلِ في ذلِكَ الضَّميرِ لَنَصَبَ العامِلُ ذلِكَ الاسْمَ المُقَدَّمَ`] } },
            { box: { title: 'Example', lines: [`﴿وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ﴾`] } },
            { html: `"And messengers We have already narrated to you [about]." <bdi>رُسُلًا</bdi> comes first; <bdi>قَصَصْنا</bdi> governs the pronoun <bdi>هُمْ</bdi> (referring back to رُسُلًا), not رُسُلًا itself. Strip away هُمْ, and قَصَصْنا would naturally govern رُسُلًا directly (قَصَصْنا رُسُلًا) — so the فعل is "occupied" (مُشْتَغِل) with the pronoun instead.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ`,
                translation: `And messengers We have already narrated to you about.`,
                cells: [`رُسُلًا`, `قَدْ قَصَصْناهُمْ`, `عَلَيْكَ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `المشغول عنه (منصوب بفعل محذوف يفسِّره المذكور)` }, { start: 1, end: 1, role: `المشغول (فعل) والمشغول به (ضمير هم)` }, { start: 2, end: 2, role: `متعلق بالفعل` }] },
                ],
              },
            },
          ],
          exercise: {
            prompt: `In ﴿وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ﴾, does قَصَصْنا govern رُسُلًا directly, or the pronoun هُمْ؟`,
            kind: 'mcq',
            options: [`The pronoun هُمْ — قَصَصْنا is "occupied" with it instead of رُسُلًا`, `رُسُلًا directly, with no pronoun involved`, `Neither — قَصَصْنا governs nothing here`, `Both رُسُلًا and هُمْ at once`],
            correct: 0,
          },
        },
        {
          heading: 'أركان الاشتغال، وتسميته الأخرى',
          lines: [
            { box: { title: 'Rule', lines: [`لِلِاشْتِغالِ ثَلاثَةُ أَرْكانٍ: المَشْغول، والمَشْغول بِه، والمَشْغول عَنْه`] } },
            { html: `(1) <bdi>المَشْغول</bdi> — the عامل itself (the verb), also called <bdi>المُشْتَغِل</bdi>; (2) <bdi>المَشْغول بِه</bdi> — the pronoun the verb is busy governing; (3) <bdi>المَشْغول عَنْه</bdi> — the fronted noun the verb is distracted away from.`, list: false },
            { html: `الاشتغال is also called <bdi>ما أُضْمِرَ عامِلُهُ على شَريطَةِ التَّفْسير</bdi> — "that whose عامل is hidden, on condition that [the following verb] explains it." When المشغول عنه is treated as منصوب, its true governing verb is a dropped one, recoverable only because the mentioned verb after it explains, or mirrors, what it would have been.`, list: false },
          ],
          exercise: {
            prompt: `الاشتغال is also known by a longer descriptive name. What does that name capture؟`,
            kind: 'mcq',
            options: [`That its عامل is hidden, on condition that the mentioned verb after it explains what it would have been`, `That its عامل is always spoken, never hidden`, `That it never involves a pronoun at all`, `That two عوامل openly compete for one معمول`],
            correct: 0,
          },
        },
        {
          heading: 'حكم المشغول عنه: الأصل هو الجواز',
          lines: [
            { box: { title: 'Rule', lines: [`يَجوزُ في المَشْغولِ عَنْهُ أَنْ يُرْفَعَ بِالِابْتِداءِ وَأَنْ يُنْصَبَ بِفِعْلٍ مَحْذوفٍ`] } },
            { html: `By default, المشغول عنه may be either <bdi>مَرْفوع</bdi> (as مبتدأ, with the rest of the sentence as its خبر) or <bdi>مَنْصوب</bdi> (governed by a dropped verb that the mentioned verb explains).`, list: false },
            { box: { title: 'Example', lines: [`﴿والْمَوْتى يَبْعَثُهُمُ اللهُ﴾`] } },
            { html: `"And the dead, Allah will resurrect them." <bdi>الْمَوْتى</bdi> can be read either way: مرفوع as مبتدأ (والموتى / يبعثهم الله = خبر), or منصوب by a dropped فعل that يَبْعَثُ mirrors (وَيَبْعَثُ المَوْتى يَبْعَثُهُمُ اللهُ).`, list: false },
          ],
          exercise: {
            prompt: `In ﴿والْمَوْتى يَبْعَثُهُمُ اللهُ﴾, is الْمَوْتى required to be مرفوع, required to be منصوب, or can it be either؟`,
            kind: 'mcq',
            options: [`Either — يجوز الرفع بالابتداء ويجوز النصب بفعل محذوف`, `Required مرفوع only`, `Required منصوب only`, `Neither — الموتى has no إعراب of its own here`],
            correct: 0,
          },
        },
        {
          heading: 'وجوب الرفع ووجوب النصب',
          lines: [
            { box: { title: 'Rule', lines: [`يَجِبُ الرَّفْعُ إِذا وَقَعَ المَشْغولُ عَنْهُ بَعْدَ أَداةٍ خاصٍّ بِالِاسْمِ`] } },
            { html: `If المشغول عنه follows a particle that can only be followed by a noun, رفع becomes obligatory — a dropped verb could never fit there.`, list: false },
            { box: { title: 'Example', lines: [`فَإِذا الشَّيْطانُ يَتَّبِعُهُ`] } },
            { html: `"...then, behold, Shayṭān follows him." <bdi>إِذا الفُجائِيَّة</bdi> can only be followed by a noun, so الشَّيْطانُ must be مرفوع.`, list: false },
            { box: { title: 'Rule', lines: [`يَجِبُ النَّصْبُ إِذا وَقَعَ المَشْغولُ عَنْهُ بَعْدَ أَداةٍ خاصَّةٍ بِالفِعْلِ، كَالتَّحْضيضِ والشَّرْطِ`] } },
            { box: { title: 'Example', lines: [`هَلّا الجَنَّةَ طَلَبْتَها`] } },
            { html: `"Why didn't you seek Paradise!" هَلّا can only be followed by a فعل, so الجَنَّةَ must be منصوب (by a dropped طَلَبْتَ that طَلَبْتَها mirrors). إِنِ الجَنَّةَ تُرِدْها فاعْمَلْ صالِحًا works the same way, since إِنْ الشرطية also demands a verb.`, list: false },
          ],
          exercise: {
            prompt: `هَلّا الجَنَّةَ طَلَبْتَها places الجَنَّةَ after هَلّا, a particle that can only be followed by a فعل. Does that make الجَنَّةَ obligatorily مرفوع or منصوب؟`,
            kind: 'mcq',
            options: [`منصوب — a particle special to الفعل forces النصب`, `مرفوع — a particle special to الفعل forces الرفع`, `Either is acceptable here`, `Neither — الجنة has no إعراب at all after هلّا`],
            correct: 0,
          },
        },
        {
          heading: 'رجحان النصب: ثلاث حالات',
          lines: [
            { box: { title: 'Rule', lines: [`يَتَرَجَّحُ النَّصْبُ: إِنْ كانَ العامِلُ فِعْلَ طَلَبٍ؛ أَوْ كانَ قَبْلَ المَعْمولِ جُمْلَةٌ فِعْلِيَّةٌ؛ أَوْ كانَ قَبْلَهُ حَرْفٌ يَغْلِبُ دُخولُهُ على الفِعْلِ`] } },
            { html: `Both رفع and نصب remain grammatically valid in these three situations, but نصب is the better choice: (1) an أمر or نهي naturally pairs with another فعل, not a plain مبتدأ; (2) Arabic favors parallel structure between coordinated clauses, so a فعلية clause pairs more naturally with another فعلية; (3) <bdi>ما النافية</bdi> and <bdi>هَمْزَةُ الِاسْتِفْهام</bdi> most often introduce a فعل.`, list: false },
            { box: { title: 'Example', lines: [`اللهَ اعْبُدْهُ وَرَسولَهُ اتَّبِعْهُ`] } },
            { html: `"Allah, worship Him; and His Messenger, follow him" — نصب preferred, since اعْبُدْ/اتَّبِعْ are imperatives.`, list: false },
            { box: { title: 'Example', lines: [`أَعْبُدُ اللهَ وَرَسولَهُ أَتَّبِعُهُ`] } },
            { html: `"I worship Allah, and His Messenger I follow" — the first clause is فعلية, so نصب keeps the second فعلية too.`, list: false },
            { box: { title: 'Example', lines: [`ما الشَّيْطانَ أَتَّبِعُهُ`] } },
            { html: `"Shayṭān, I do not follow" — ما most often introduces a فعلية sentence, favoring نصب.`, list: false },
          ],
          exercise: {
            prompt: `اللهَ اعْبُدْهُ places اللهَ before a فعل أمر, اعْبُدْهُ. Which reading is preferred, and why؟`,
            kind: 'mcq',
            options: [`النصب — a فعل طلب naturally pairs with another فعل, not a plain مبتدأ`, `الرفع — الأمر always forces رفع`, `النصب, but only because الله is معرفة`, `Neither reading is preferred over the other`],
            correct: 0,
          },
        },
        {
          heading: 'الفعل المحذوف قد يكون مرادفًا لا نفسه',
          lines: [
            { box: { title: 'Careful', lines: [`قَدْ يَكونُ الفِعْلُ المَحْذوفُ في الِاشْتِغالِ فِعْلًا مُرادِفًا لِلْعامِلِ المَشْغولِ، لا نَفْسَهُ`] } },
            { html: `The dropped verb explained by the mentioned verb is not always the very same verb repeated — sometimes it must be a synonym, when the mentioned verb's own grammar wouldn't fit the fronted noun directly.`, list: false },
            { box: { title: 'Example', lines: [`﴿والظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا﴾`] } },
            { html: `"And for the wrongdoers, He has prepared a painful punishment." <bdi>الظّالِمينَ</bdi> is منصوب by اشتغال, but the dropped verb cannot be <bdi>أَعَدَّ</bdi> itself: أَعَدَّ takes its object through the preposition لِـ (أَعَدَّ لَهُمْ), so it could never govern الظّالِمينَ directly without a لام. A genuine synonym that does take its object directly is understood instead — something like <bdi>أَوْعَدَ</bdi>, <bdi>عَدَّ</bdi>, or <bdi>كافَأَ</bdi> الظّالِمينَ.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿والظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا﴾, why can't the dropped عامل explaining الظّالِمينَ be أَعَدَّ itself؟`,
            kind: 'mcq',
            options: [`Because أَعَدَّ only takes its object through لِـ, so it could never govern الظّالِمينَ directly`, `Because أَعَدَّ is فعل ماضٍ, and the dropped فعل must be مضارع`, `Because الظّالِمينَ is جمع, and أَعَدَّ only takes مفرد objects`, `There is no problem — the dropped فعل is genuinely أَعَدَّ itself`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `أركان الاشتغال are three. What are they called؟`, options: [`المشغول، المشغول به، المشغول عنه`, `المحذِّر، المحذَّر، المحذَّر منه`, `المُغْري، المُغْرَى، المُغْرَى بِه`, `العامل والمعمول والإعراب`], correct: 0 },
        { q: `﴿والْمَوْتى يَبْعَثُهُمُ اللهُ﴾ allows الْمَوْتى to be read two ways. What are they؟`, options: [`مرفوع بالابتداء، أو منصوب بفعل محذوف يفسِّره يَبْعَثُ`, `مجرور فقط`, `مبني على الفتح فقط`, `منصوب فقط، بلا خيار آخر`], correct: 0 },
        { q: `فَإِذا الشَّيْطانُ يَتَّبِعُهُ forces الشَّيْطانُ to be مرفوع, with no alternative. Why؟`, options: [`إِذا الفجائية can only be followed by an اسم`, `إِذا الفجائية can only be followed by a فعل`, `الشيطان is always مرفوع regardless of context`, `يتبعه requires its فاعل to be مرفوع separately`], correct: 0 },
        { q: `هَلّا الجَنَّةَ طَلَبْتَها forces الجَنَّةَ to be منصوب. What kind of particle is هَلّا, that produces this obligatory reading؟`, options: [`أداة تحضيض, خاصة بالفعل`, `أداة خاصة بالاسم`, `أداة استفهام للتصوّر`, `أداة جواب`], correct: 0 },
        { q: `اللهَ اعْبُدْهُ prefers النصب over الرفع, though both remain grammatically valid. What tips the preference toward النصب here؟`, options: [`العامل هو فعل طلب (أمر)`, `العامل هو فعل خبري`, `اسم الجلالة لا يقبل الرفع`, `ما قبل الاسم أداة تختص بالاسم`], correct: 0 },
        { q: `In ﴿والظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا﴾, the dropped عامل cannot be أَعَدَّ itself. What must it be instead؟`, options: [`A synonym verb that takes its object directly, without a لام, such as أَوْعَدَ`, `أَعَدَّ itself, repeated exactly`, `There is no dropped عامل at all here`, `A verb of التحذير, such as اِحْذَرْ`], correct: 0 },
      ],
      bank: [
        { title: `الاشتغال: التعريف`, kind: 'mcq', prompt: `Which of the following correctly defines الاشتغال؟`, options: [`A noun placed before a verb that governs a pronoun referring back to it — such that, freed of that pronoun, the verb would instead put the preceding noun itself in نصب`, `Putting the noun in نصب via an omitted verb warning against something disliked`, `Two عاملان competing over one معمول that comes after both of them`, `Putting the noun in نصب via an omitted verb that specifies what a preceding pronoun refers to`], correct: 0 },
        { title: `رسلا قد قصصناهم: ما الذي يحكمه قصصنا؟`, kind: 'mcq', prompt: `In ﴿وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ﴾, what does قَصَصْنا actually govern؟`, options: [`الضمير هُمْ, referring back to رُسُلًا`, `رُسُلًا directly`, `عَلَيْكَ`, `Nothing — قَصَصْنا is مبني ولا يعمل`], correct: 0 },
        { title: `المشغول`, kind: 'mcq', prompt: `In الاشتغال, which term names the عامل itself (the verb)؟`, options: [`المشغول (أو المشتغل)`, `المشغول به`, `المشغول عنه`, `المغرى به`], correct: 0 },
        { title: `المشغول به`, kind: 'mcq', prompt: `In الاشتغال, which term names the pronoun the verb is busy governing؟`, options: [`المشغول به`, `المشغول`, `المشغول عنه`, `المحذَّر منه`], correct: 0 },
        { title: `المشغول عنه`, kind: 'mcq', prompt: `In الاشتغال, which term names the fronted noun the verb is distracted away from؟`, options: [`المشغول عنه`, `المشغول`, `المشغول به`, `المغرى`], correct: 0 },
        { title: `اسم آخر للاشتغال`, kind: 'mcq', prompt: `الاشتغال is also known by a longer name built around شريطة التفسير. What does الفعل المحذوف mean in that name؟`, options: [`Its عامل is hidden, on condition the following verb explains what it would have been`, `Its عامل is always fully spoken`, `It has no عامل at all, hidden or spoken`, `Two عوامل compete for it openly`], correct: 0 },
        { title: `الموتى مرفوعًا: كيف`, kind: 'mcq', prompt: `If الْمَوْتى in ﴿والْمَوْتى يَبْعَثُهُمُ اللهُ﴾ is read مرفوعًا, what role does it play؟`, options: [`مبتدأ, with يَبْعَثُهُمُ اللهُ as its خبر`, `مفعول به لفعل محذوف`, `فاعل لفعل محذوف`, `بدل من الله`], correct: 0 },
        { title: `الموتى منصوبًا: كيف`, kind: 'mcq', prompt: `If الْمَوْتى is instead read منصوبًا, what governs it؟`, options: [`فعل محذوف يفسِّره يَبْعَثُ المذكور`, `يَبْعَثُ المذكور نفسه مباشرة`, `اللهُ, بوصفه فاعلًا`, `حرف جر محذوف`], correct: 0 },
        { title: `إذا الفجائية: أداة خاصة بالاسم`, kind: 'mcq', prompt: `Why must الشَّيْطانُ be مرفوع after إِذا الفجائية, with no alternative reading؟`, options: [`إذا الفجائية is an أداة خاصة بالاسم — a dropped فعل could never fit there`, `إذا الفجائية always forces منصوب, not مرفوع`, `الشيطان is a proper noun and so is always مرفوع`, `يتبعه cannot take a فاعل, forcing رفع elsewhere`], correct: 0 },
        { title: `أدوات خاصة بالفعل`, kind: 'mcq', prompt: `Besides هَلّا (تحضيض), which other kind of particle also forces وجوب النصب in الاشتغال؟`, options: [`أدوات الشرط, such as إِنْ`, `أل التعريف`, `حروف الجر`, `أحرف العطف`], correct: 0 },
        { title: `إن الجنة تردها: وجوب النصب`, kind: 'mcq', prompt: `إِنِ الجَنَّةَ تُرِدْها فاعْمَلْ صالِحًا forces الجَنَّةَ to be منصوب. Why؟`, options: [`إِنْ الشرطية can only be followed by a فعل`, `إِنْ الشرطية can only be followed by an اسم`, `تُرِدْها has no فاعل to assign`, `الجنة is always منصوب regardless of context`], correct: 0 },
        { title: `رجحان النصب: فعل الطلب`, kind: 'mcq', prompt: `Among the three situations that favor النصب without requiring it, which one involves the governing فعل itself being a command or prohibition؟`, options: [`إن كان العامل فعل طلب`, `إن كان قبل المعمول جملة فعلية`, `إن كان قبله حرف يغلب دخوله على الفعل`, `None of the three involve فعل الطلب`], correct: 0 },
        { title: `رجحان النصب: التوازي بين الجمل`, kind: 'mcq', prompt: `أَعْبُدُ اللهَ وَرَسولَهُ أَتَّبِعُهُ favors النصب for رَسولَهُ. Which of the three رجحان situations does this illustrate؟`, options: [`أن يكون قبل المعمول جملة فعلية، طلبًا للتوازي`, `أن يكون العامل فعل طلب`, `أن يسبقه حرف يغلب دخوله على الفعل`, `None — this sentence actually requires الرفع`], correct: 0 },
        { title: `ما وهمزة الاستفهام: حرفان يغلب دخولهما على الفعل`, kind: 'mcq', prompt: `ما الشَّيْطانَ أَتَّبِعُهُ and ﴿أَبَشَرًا مِنّا واحِدًا نَتَّبِعُهُ﴾ both favor النصب. Which particles precede the fronted noun in each؟`, options: [`ما النافية, and هَمْزَةُ الاستفهام`, `إِذا الفجائية, and هَلّا`, `إِنْ الشرطية, and لام الجر`, `أل التعريف, and واو العطف`], correct: 0 },
        { title: `الفعل المحذوف مرادف: متى يحدث هذا`, kind: 'mcq', prompt: `When must the dropped فعل in الاشتغال be a synonym of the mentioned فعل, rather than the same verb repeated؟`, options: [`When the mentioned فعل's own grammar would not let it govern the fronted noun directly`, `Whenever المشغول عنه is معرفة`, `Whenever الجملة الفعلية comes first`, `This never happens — the dropped فعل is always the same verb repeated`], correct: 0 },
        { title: `أعد لهم: لماذا لا تفسر الظالمين مباشرة`, kind: 'mcq', prompt: `أَعَدَّ لَهُمْ takes its object only through لِـ. Why does this block أَعَدَّ from being the dropped عامل governing الظّالِمينَ directly؟`, options: [`Because الظّالِمينَ would need a لام to be governed by أَعَدَّ, but appears without one`, `Because أَعَدَّ is فعل ماضٍ`, `Because الظّالِمينَ is جمع مذكر سالم`, `There is no such block — أَعَدَّ is the dropped عامل itself`], correct: 0 },
        { title: `أوعد وعد وكافأ: مرادفات مقترحة`, kind: 'mcq', prompt: `Which three verbs are proposed as the genuine dropped عامل behind ﴿والظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا﴾؟`, options: [`أَوْعَدَ، عَدَّ، كافَأَ`, `اِحْذَرْ، تَجَنَّبْ، تَوَقَّ`, `اِلْزَمْ، اُطْلُبْ، خُذْ`, `أَخُصُّ، أَعْني، أَقْصِدُ`], correct: 0 },
        { title: `الأصل: الرفع أو النصب`, kind: 'mcq', prompt: `Outside the situations of وجوب or رجحان, what is the default (الأصل) حكم of المشغول عنه؟`, options: [`يجوز فيه الرفع والنصب معًا`, `يجب فيه الرفع فقط`, `يجب فيه النصب فقط`, `لا إعراب له أصلًا`], correct: 0 },
        {
          title: `تركيب: وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of ﴿وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ﴾, where قَصَصْنا governs a pronoun instead of رُسُلًا itself.`,
          source: `وَرُسُلًا قَدْ قَصَصْناهُمْ عَلَيْكَ`,
          words: [`رُسُلًا`, `قَصَصْناهُمْ`, `عَلَيْكَ`],
          labels: [`المشغول عنه، منصوب بفعل محذوف يفسِّره المذكور`, `المشغول (فعل) والمشغول به (ضمير هم)`, `متعلق بالفعل`],
          distractors: [`مبتدأ`, `خبر`],
        },
        {
          title: `تركيب: والْمَوْتى يَبْعَثُهُمُ اللهُ (قراءة النصب)`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of ﴿والْمَوْتى يَبْعَثُهُمُ اللهُ﴾ on the منصوب reading.`,
          source: `والْمَوْتى يَبْعَثُهُمُ اللهُ`,
          words: [`المَوْتى`, `يَبْعَثُهُمُ`, `اللهُ`],
          labels: [`المشغول عنه، منصوب بفعل محذوف`, `المشغول (فعل) والمشغول به (ضمير هم)`, `فاعل يَبْعَثُ`],
          distractors: [`مبتدأ`, `خبر`],
        },
        {
          title: `تركيب: فَإِذا الشَّيْطانُ يَتَّبِعُهُ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of فَإِذا الشَّيْطانُ يَتَّبِعُهُ, where إِذا الفجائية forces رفع.`,
          source: `فَإِذا الشَّيْطانُ يَتَّبِعُهُ`,
          words: [`إِذا`, `الشَّيْطانُ`, `يَتَّبِعُهُ`],
          labels: [`أداة خاصة بالاسم (إذا الفجائية)`, `المشغول عنه، مرفوع مبتدأ وجوبًا`, `خبر (المشغول والمشغول به)`],
          distractors: [`منصوب بفعل محذوف`, `مضاف إليه`],
        },
        {
          title: `تركيب: هَلّا الجَنَّةَ طَلَبْتَها`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of هَلّا الجَنَّةَ طَلَبْتَها, where التحضيض forces نصب.`,
          source: `هَلّا الجَنَّةَ طَلَبْتَها`,
          words: [`هَلّا`, `الجَنَّةَ`, `طَلَبْتَها`],
          labels: [`أداة تحضيض، خاصة بالفعل`, `المشغول عنه، منصوب بفعل محذوف وجوبًا`, `المشغول (فعل) والمشغول به (ضمير ها)`],
          distractors: [`مرفوع بالابتداء`, `مضاف`],
        },
        {
          title: `تركيب: اللهَ اعْبُدْهُ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of اللهَ اعْبُدْهُ, where فعل الطلب يرجّح النصب.`,
          source: `اللهَ اعْبُدْهُ`,
          words: [`اللهَ`, `اعْبُدْهُ`],
          labels: [`المشغول عنه، النصب فيه مرجَّح لأن العامل فعل طلب`, `المشغول (فعل أمر) والمشغول به (ضمير الهاء)`],
          distractors: [`مرفوع بالابتداء وجوبًا`, `مضاف إليه`],
        },
        {
          title: `تركيب: وَالظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of ﴿والظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا﴾, where the dropped عامل must be a synonym of أَعَدَّ.`,
          source: `والظّالِمينَ أَعَدَّ لَهُمْ عَذابًا أَليمًا`,
          words: [`الظّالِمينَ`, `أَعَدَّ لَهُمْ`, `عَذابًا أَليمًا`],
          labels: [`المشغول عنه، منصوب بفعل محذوف مرادف (أوعد/عدّ/كافأ)`, `المشغول (فعل) مع متعلقه`, `مفعول به لأَعَدَّ`],
          distractors: [`فاعل`, `مضاف إليه`],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'حذف عامل الحال',
      subtitle: 'The Third ضرب of حذف العامل المعنوي — four قياسي situations where الحال survives without its governing verb, and a سماعي handful besides',
      concepts: [
        {
          heading: 'حذف عامل الحال: مدخل',
          lines: [
            { html: `الحال is normally governed by a verb or شبه الفعل — the action-word the circumstance describes. But just as المفعول به and المفعول المطلق can lose their governing verb in fixed patterns, الحال too has its own set of situations where the عامل is dropped and only الحال itself remains. This is the third ضرب (الضرب الثالث) of حذف العامل المعنوي.`, list: false },
            { box: { title: 'Rule', lines: [`وَيُحْذَفُ عامِلُ الحالِ قِياسًا وُجوبًا في أَرْبَعِ مَواضِعَ، وَسَماعًا في غَيْرِ ذلِكَ`] } },
            { html: `Four situations drop the عامل by regular, obligatory rule (قياسًا وجوبًا); beyond them, one further pattern is dropped only سَماعًا — by attested usage, not a general rule.`, list: false },
          ],
          exercise: {
            prompt: `حذف عامل الحال is which ضرب of حذف العامل المعنوي؟`,
            kind: 'mcq',
            options: [`الضرب الثالث`, `الضرب الأول`, `الضرب الثاني`, `It is not a ضرب of حذف العامل المعنوي at all`],
            correct: 0,
          },
        },
        {
          heading: 'الأول: أن تسد الحال مسد الخبر',
          lines: [
            { box: { title: 'Definition', lines: [`إِذا سَدَّتِ الحالُ مَسَدَّ الخَبَرِ — لَمْ يُذْكَرْ خَبَرٌ لِلْجُمْلَةِ، وَدَلَّتِ الحالُ عَلَى مَعْناهُ — وَجَبَ حَذْفُ عامِلِ تِلْكَ الحالِ`] } },
            { box: { title: 'Example', lines: [`«أَقْرَبُ ما يَكونُ العَبْدُ مِنْ رَبِّهِ وَهُوَ ساجِدٌ»`] } },
            { html: `"The servant is closest to his Lord while he is prostrating." <bdi>أَقْرَبُ</bdi> is مبتدأ; <bdi>ما</bdi> is مصدرية; <bdi>يَكونُ</bdi> is فعل ناقص whose اسم is العَبْدُ. There is no written خبر for أَقْرَبُ — instead <bdi>وَهُوَ ساجِدٌ</bdi> is حالٌ مِنَ العَبْدِ that سادٌّ مَسَدَّ الخَبَرِ, standing in for the missing خبر. The full sense is: أَيْ أَقْرَبُ حالِ العَبْدِ مِنْ رَبِّهِ حاصِلٌ لَهُ وَهُوَ ساجِدٌ — and it is that dropped <bdi>حاصِلٌ</bdi>, not أَقْرَبُ, that actually governs وَهُوَ ساجِدٌ as its حال.`, list: false },
            { box: { title: 'Careful', lines: [`وَهُوَ ساجِدٌ حالٌ لا خَبَرٌ، وَإِنْ بَدا في المَعْنى كَأَنَّهُ الخَبَرُ`] } },
            { html: `It's tempting to translate وَهُوَ ساجِدٌ as if it were the خبر itself ("the closest a servant can be to his Lord is when he is prostrating"), and that translation reads naturally — but وَهُوَ ساجِدٌ is grammatically a حال, not a خبر. It only reads as if it supplied the خبر's meaning because the true خبر — a dropped حاصِلٌ — has been removed precisely because this حال was doing its job well enough that the sentence stayed clear without it.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `أَقْرَبُ ما يَكونُ العَبْدُ مِنْ رَبِّهِ وَهُوَ ساجِدٌ`,
                translation: `The servant is closest to his Lord while he is prostrating.`,
                cells: [`أَقْرَبُ`, `ما يَكونُ العَبْدُ مِنْ رَبِّهِ`, `وَهُوَ ساجِدٌ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `مبتدأ` }, { start: 1, end: 1, role: `صلة الموصول الحرفي مع متعلقها` }, { start: 2, end: 2, role: `حال سادٌّ مسدَّ الخبر` }] },
                ],
              },
            },
          ],
          exercise: {
            prompt: `In «أَقْرَبُ ما يَكونُ العَبْدُ مِنْ رَبِّهِ وَهُوَ ساجِدٌ», is وَهُوَ ساجِدٌ grammatically الخبر of أَقْرَبُ, or الحال؟`,
            kind: 'mcq',
            options: [`الحال — it stands in for a dropped خبر (حاصِلٌ), even though it reads as if it supplied the خبر's meaning`, `الخبر — it is المسند directly to أَقْرَبُ`, `Neither — أَقْرَبُ has no خبر or حال at all`, `It is both الخبر and الحال at once`],
            correct: 0,
          },
        },
        {
          heading: 'الثاني والثالث: زيادة أو نقص بتدريج، واستفهام التوبيخ',
          lines: [
            { box: { title: 'Rule', lines: [`الثاني: إِذا دَلَّتِ الحالُ بِلَفْظِها عَلَى زِيادَةٍ أَوْ نَقْصٍ بِتَدْريجٍ، مَعَ اقْتِرانِها بِالفاءِ أَوْ ثُمَّ — وَجَبَ حَذْفُ عامِلِها`] } },
            { box: { title: 'Example', lines: [`تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا`] } },
            { html: `"Give a dirham in charity, or more." أَيْ: تصدق، ثم [الأمر] يزيد صاعدا — the dropped عامل is understood as <bdi>يَزيدُ</bdi>, "it increases," with صاعِدًا itself literally meaning "climbing" — the word itself carries the sense of gradual increase that triggers the drop. This حال must be introduced by الفاء or, less commonly, ثُمَّ.`, list: false },
            { box: { title: 'Rule', lines: [`الثالث: إِذا كانَتِ الحالُ مَسْبوقَةً بِاسْتِفْهامٍ يُرادُ بِهِ التَّوْبيخُ — وَجَبَ حَذْفُ عامِلِها`] } },
            { box: { title: 'Example', lines: [`أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ؟`] } },
            { html: `"[Are you still] sitting, while the prayer has already started?!" أَيْ: أَلَمْ تَزَلْ قاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ؟ — this doesn't really ask whether the person is sitting, with the dropped عامل understood as <bdi>بَقِيتَ</bdi>, <bdi>لَبِثْتَ</bdi>, or <bdi>لَمْ تَزَلْ</bdi>; it's a rebuke.`, list: false },
          ],
          exercise: {
            prompt: `تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا drops its حال's عامل because صاعِدًا's own wording carries a specific sense. What sense is that, and what condition must accompany it؟`,
            kind: 'mcq',
            options: [`Gradual increase (بتقدير يزيد), introduced by الفاء or ثمّ`, `Rebuke (توبيخ), preceded by استفهام`, `Reaffirming the sentence's own meaning`, `No condition at all — the drop here is سماعي, not قياسي`],
            correct: 0,
          },
        },
        {
          heading: 'الرابع: المؤكِّدة لمضمون الجملة',
          lines: [
            { box: { title: 'Rule', lines: [`الرابع: إِذا كانَتِ الحالُ مُؤَكِّدَةً لِمَضْمونِ الجُمْلَةِ قَبْلَها — وَجَبَ حَذْفُ عامِلِها، بِشَرْطَيْنِ: أَنْ يَتَّفِقَ مَعْنَى الحالِ وَمَعْنَى الجُمْلَةِ، وَأَنْ يَكونَ المُبْتَدَأُ وَالخَبَرُ مَعْرِفَتَيْنِ جامِدَتَيْنِ`] } },
            { html: `When الحال reaffirms the very meaning already contained in the preceding جملة, restating what the جملة already says, its عامل is dropped — but only if (1) the meaning of الحال genuinely matches the meaning of the جملة before it, and (2) the مبتدأ and خبر of that preceding جملة are both معرفة (definite) and جامد (non-derived nouns).`, list: false },
            { box: { title: 'Example', lines: [`﴿وَهُوَ الحَقُّ مُصَدِّقًا لِما مَعَهُمْ﴾`] } },
            { html: `"And it is the truth, confirming what is with them." <bdi>الحَقُّ</bdi> already implies truthfulness; <bdi>مُصَدِّقًا</bdi> as حال simply reaffirms that same sense — it adds no new information.`, list: false },
            { box: { title: 'Example', lines: [`خالِدٌ أَبوكَ عَطوفًا`] } },
            { html: `"Khālid is your father, [being] affectionate." <bdi>خالِدٌ</bdi> and <bdi>أَبوكَ</bdi> are both معرفة وجامد, satisfying the second شرط; and the fact that خالِد is your father already implies tenderness, so <bdi>عَطوفًا</bdi> as حال simply reaffirms what "being your father" already means.`, list: false },
          ],
          exercise: {
            prompt: `خالِدٌ أَبوكَ عَطوفًا satisfies the second شرط for المؤكِّدة لمضمون الجملة. What does that شرط require of المبتدأ والخبر؟`,
            kind: 'mcq',
            options: [`Both must be معرفة and جامد (non-derived)`, `Both must be نكرة and مشتق`, `Only المبتدأ needs to be معرفة`, `There is no requirement on المبتدأ والخبر at all`],
            correct: 0,
          },
        },
        {
          heading: 'السماعي',
          lines: [
            { box: { title: 'Rule', lines: [`وَقَدْ يُحْذَفُ عامِلُ الحالِ سَماعًا في غَيْرِ الأَرْبَعَةِ القِياسِيَّةِ`] } },
            { html: `Beyond the four قياسي مواضع, الحال's عامل may also be dropped in other expressions, but only because they are attested that way — not because they follow a general, extendable rule.`, list: false },
            { box: { title: 'Example', lines: [`هَنيئًا لَكَ`] } },
            { html: `"[May it be] pleasant/wholesome for you" — a fixed congratulatory expression.`, list: false },
            { box: { title: 'Example', lines: [`سالِمًا غانِمًا`] } },
            { html: `"[Returning] safe and victorious" — said of someone back from a difficult journey unharmed and successful; both سالِمًا and غانِمًا are حال with a dropped عامل, something like <bdi>رَجَعَ</bdi>, "he returned."`, list: false },
          ],
          exercise: {
            prompt: `سالِمًا غانِمًا drops its حال's governing verb without following any of the four قياسي مواضع. What kind of drop is this؟`,
            kind: 'mcq',
            options: [`سماعي — attested usage, not a general rule`, `قياسي الأول`, `قياسي الرابع`, `Neither — no عامل is dropped here at all`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `Beyond الحال's four قياسي مواضع of حذف العامل, is there a further سماعي category؟`, options: [`Yes — a handful of attested expressions beyond the four قياسي rules`, `No — only the four قياسي مواضع exist`, `Yes, but only for المفعول المطلق, not الحال`, `No — الحال's عامل is never dropped at all`], correct: 0 },
        { q: `In «أَقْرَبُ ما يَكونُ العَبْدُ مِنْ رَبِّهِ وَهُوَ ساجِدٌ», what is the dropped خبر of أَقْرَبُ understood to be؟`, options: [`حاصِلٌ`, `كائِنٌ فَقَط`, `مَوْجودٌ حَقيقَةً`, `There is no dropped خبر — أَقْرَبُ needs none`], correct: 0 },
        { q: `تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا requires صاعِدًا's حال to be introduced by which particle(s)؟`, options: [`الفاء، أو ثُمَّ`, `الواو فقط`, `أَمْ فقط`, `No particle is required at all`], correct: 0 },
        { q: `أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ؟ is not a genuine question about whether the listener is sitting. What triggers the drop of its حال's عامل؟`, options: [`استفهام يراد به التوبيخ`, `زيادة أو نقص بتدريج`, `الحال المؤكِّدة لمضمون الجملة`, `الحال السادة مسد الخبر`], correct: 0 },
        { q: `﴿وَهُوَ الحَقُّ مُصَدِّقًا لِما مَعَهُمْ﴾ drops مُصَدِّقًا's عامل because it reaffirms مضمون الجملة. Does مُصَدِّقًا add new information beyond what الحَقُّ already implies؟`, options: [`No — it simply reaffirms the truthfulness already implied by الحَقُّ`, `Yes — it introduces an entirely separate claim`, `Yes, but only about a different subject`, `مُصَدِّقًا has no relation to الحَقُّ's meaning at all`], correct: 0 },
        { q: `هَنيئًا لَكَ drops its حال's عامل without matching any of the four قياسي مواضع. What kind of drop does that make it؟`, options: [`سماعي`, `قياسي الأول`, `قياسي الثاني`, `قياسي الثالث`], correct: 0 },
      ],
      bank: [
        { title: `حذف عامل الحال: أي ضرب`, kind: 'mcq', prompt: `حذف عامل الحال is the third ضرب of which broader category؟`, options: [`حذف العامل المعنوي`, `التنازع`, `الاشتغال`, `حذف عامل المفعول به`], correct: 0 },
        { title: `المواضع القياسية: عددها`, kind: 'mcq', prompt: `How many قياسي مواضع force وجوب حذف عامل الحال؟`, options: [`Four, plus a further سماعي category`, `Three only`, `Five, with no سماعي category`, `Two only`], correct: 0 },
        { title: `أقرب ما يكون العبد: إعراب أقرب`, kind: 'mcq', prompt: `In «أَقْرَبُ ما يَكونُ العَبْدُ مِنْ رَبِّهِ وَهُوَ ساجِدٌ», what role does أَقْرَبُ play؟`, options: [`مبتدأ`, `خبر`, `حال`, `مفعول مطلق`], correct: 0 },
        { title: `أقرب ما يكون العبد: إعراب ما`, kind: 'mcq', prompt: `In the same حديث, what role does ما play؟`, options: [`مصدرية`, `اسم موصول بمعنى الذي`, `نافية`, `استفهامية`], correct: 0 },
        { title: `الحال السادة مسد الخبر: الشرط`, kind: 'mcq', prompt: `For الحال to سدّ مسدّ الخبر and force حذف عاملها, what must be true of the جملة it belongs to؟`, options: [`It must have no visible خبر at all, with الحال supplying its meaning instead`, `It must have two visible أخبار`, `The جملة must be فعلية, not اسمية`, `The حال must precede its صاحب`], correct: 0 },
        { title: `تصدق بدرهم فصاعدا: العامل المحذوف`, kind: 'mcq', prompt: `What is the dropped عامل behind صاعِدًا in تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا, تقديرًا؟`, options: [`يَزيدُ`, `بَقِيتَ`, `حاصِلٌ`, `دَعْ`], correct: 0 },
        { title: `صاعدا: لماذا حذف عامله بالذات`, kind: 'mcq', prompt: `Why does صاعِدًا specifically trigger حذف عاملها, rather than an ordinary حال؟`, options: [`Its own wording expresses a gradual increase, or "climbing"`, `It always follows الفاء regardless of meaning`, `It is معرفة`, `It is مشتق من فعل ثلاثي فقط`], correct: 0 },
        { title: `شرط الحال الثانية: الفاء أو ثم`, kind: 'mcq', prompt: `Which particle(s) must introduce الحال in the second قياسي موضع (زيادة أو نقص بتدريج)؟`, options: [`الفاء، أو ثُمَّ`, `الواو فقط`, `إمّا فقط`, `لا شرط على الإطلاق`], correct: 0 },
        { title: `أقاعدا: العامل المحذوف`, kind: 'mcq', prompt: `What is the dropped عامل behind قاعِدًا in أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ؟, تقديرًا؟`, options: [`بَقِيتَ، أو لَبِثْتَ، أو لَمْ تَزَلْ`, `يَزيدُ`, `حاصِلٌ`, `أَصَبْتَ`], correct: 0 },
        { title: `أقاعدا: نوع الاستفهام`, kind: 'mcq', prompt: `أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ؟ is not asking a genuine question. What kind of استفهام is it؟`, options: [`استفهام للتوبيخ`, `استفهام حقيقي`, `استفهام للتصوّر`, `Not استفهام at all`], correct: 0 },
        { title: `المؤكدة لمضمون الجملة: الشرط الأول`, kind: 'mcq', prompt: `For الحال المؤكِّدة to force حذف عاملها, what must be true of الحال's own meaning؟`, options: [`It must genuinely match the meaning of the جملة before it`, `It must contradict the meaning of the جملة before it`, `It must be مشتق من فعل رباعي`, `It must be نكرة, never معرفة`], correct: 0 },
        { title: `المؤكدة لمضمون الجملة: الشرط الثاني`, kind: 'mcq', prompt: `What is the second شرط for الحال المؤكِّدة لمضمون الجملة؟`, options: [`المبتدأ والخبر of the preceding جملة must both be معرفة وجامد`, `المبتدأ must be نكرة`, `الحال must precede its جملة, not follow it`, `الخبر must be جملة فعلية`], correct: 0 },
        { title: `وهو الحق مصدقا: هل تضيف معلومة جديدة؟`, kind: 'mcq', prompt: `In ﴿وَهُوَ الحَقُّ مُصَدِّقًا لِما مَعَهُمْ﴾, does مُصَدِّقًا add a new claim, or reaffirm one already implied؟`, options: [`It reaffirms the truthfulness already implied by الحَقُّ`, `It adds an entirely new, unrelated claim`, `It negates الحَقُّ's own meaning`, `It has no relation to الحَقُّ at all`], correct: 0 },
        { title: `خالد أبوك: معرفة وجامد`, kind: 'mcq', prompt: `In خالِدٌ أَبوكَ عَطوفًا, are خالِدٌ and أَبوكَ معرفة أم نكرة, and جامدان أم مشتقان؟`, options: [`معرفتان وجامدتان`, `نكرتان ومشتقتان`, `معرفتان ومشتقتان`, `نكرتان وجامدتان`], correct: 0 },
        { title: `السماعي: هل يقاس عليه`, kind: 'mcq', prompt: `هَنيئًا لَكَ and سالِمًا غانِمًا drop their حال's عامل سماعًا. Can a learner build a new phrase on the same pattern by analogy؟`, options: [`No — these are attested only in these specific expressions`, `Yes — سماعي is freely extendable`, `Yes, but only in poetry`, `No — these phrases do not actually drop any عامل`], correct: 0 },
        { title: `سالما غانما: العامل المحذوف`, kind: 'mcq', prompt: `What is the dropped عامل behind سالِمًا غانِمًا, تقديرًا؟`, options: [`رَجَعَ`, `يَزيدُ`, `أَصَبْتَ`, `أَعْني`], correct: 0 },
        { title: `الفرق بين الأول والرابع`, kind: 'mcq', prompt: `Both الموضع الأول (سادة مسد الخبر) and الموضع الرابع (مؤكِّدة لمضمون الجملة) drop الحال's عامل, but for different reasons. What distinguishes الموضع الأول؟`, options: [`The جملة has no visible خبر at all, with الحال standing in for it`, `الحال reaffirms a meaning already stated by a visible خبر`, `الحال must be introduced by الفاء`, `الحال follows استفهام التوبيخ`], correct: 0 },
        { title: `أربعة قياسية وخامس سماعي: الترتيب`, kind: 'mcq', prompt: `Putting all five together, in which order does this lesson present the drop of الحال's عامل؟`, options: [`سادة مسد الخبر ← زيادة أو نقص بتدريج ← استفهام التوبيخ ← مؤكِّدة لمضمون الجملة ← سماعي`, `سماعي ← سادة مسد الخبر ← زيادة أو نقص ← استفهام التوبيخ ← مؤكِّدة`, `مؤكِّدة لمضمون الجملة ← سماعي ← الباقي بلا ترتيب ثابت`, `الترتيب غير مهم؛ لا يوجد ترتيب محدد في الدرس`], correct: 0 },
        {
          title: `تركيب: وَهُوَ ساجِدٌ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of وَهُوَ ساجِدٌ, the حال that سدَّ مسدَّ الخبر in «أَقْرَبُ ما يَكونُ العَبْدُ مِنْ رَبِّهِ وَهُوَ ساجِدٌ».`,
          source: `وَهُوَ ساجِدٌ`,
          words: [`وَ`, `هُوَ`, `ساجِدٌ`],
          labels: [`واو الحال`, `مبتدأ (ضمير)`, `خبر، والجملة كلها حال سادة مسد خبر أَقْرَبُ`],
          distractors: [`حرف عطف`, `فاعل`],
        },
        {
          title: `تركيب: تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا, where صاعِدًا drops its عامل because it expresses gradual increase.`,
          source: `تَصَدَّقْ بِدِرْهَمٍ فَصاعِدًا`,
          words: [`تَصَدَّقْ`, `بِدِرْهَمٍ`, `فَصاعِدًا`],
          labels: [`فعل أمر`, `متعلق بالفعل`, `حال منصوب بفعل محذوف تقديره يَزيدُ`],
          distractors: [`مفعول مطلق`, `مضاف إليه`],
        },
        {
          title: `تركيب: أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ؟, a rebuke rather than a real question.`,
          source: `أَقاعِدًا وَقَدْ أُقيمَتِ الصَّلاةُ`,
          words: [`أَ`, `قاعِدًا`, `وَقَدْ أُقيمَتِ الصَّلاةُ`],
          labels: [`حرف استفهام للتوبيخ`, `حال منصوب بفعل محذوف تقديره بَقِيتَ`, `جملة حالية معترضة`],
          distractors: [`مفعول به`, `خبر`],
        },
        {
          title: `تركيب: وَهُوَ الحَقُّ مُصَدِّقًا لِما مَعَهُمْ`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of ﴿وَهُوَ الحَقُّ مُصَدِّقًا لِما مَعَهُمْ﴾, where مُصَدِّقًا reaffirms مضمون الجملة.`,
          source: `وَهُوَ الحَقُّ مُصَدِّقًا لِما مَعَهُمْ`,
          words: [`هُوَ`, `الحَقُّ`, `مُصَدِّقًا`],
          labels: [`مبتدأ، معرفة جامد`, `خبر، معرفة جامد`, `حال مؤكِّدة، منصوب بفعل محذوف`],
          distractors: [`نعت`, `مفعول به`],
        },
        {
          title: `تركيب: خالِدٌ أَبوكَ عَطوفًا`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of خالِدٌ أَبوكَ عَطوفًا, where عَطوفًا reaffirms what أبوك already implies.`,
          source: `خالِدٌ أَبوكَ عَطوفًا`,
          words: [`خالِدٌ`, `أَبوكَ`, `عَطوفًا`],
          labels: [`مبتدأ، معرفة جامد`, `خبر، معرفة جامد`, `حال مؤكِّدة، منصوب بفعل محذوف`],
          distractors: [`نعت`, `بدل`],
        },
        {
          title: `تركيب: سالِمًا غانِمًا`,
          kind: 'tarkeeb',
          instruction: `Identify the parts of سالِمًا غانِمًا, a سماعي حال pair with a dropped عامل.`,
          source: `سالِمًا غانِمًا`,
          words: [`سالِمًا`, `غانِمًا`],
          labels: [`حال أولى، منصوب بفعل محذوف سماعًا تقديره رَجَعَ`, `حال ثانية معطوفة`],
          distractors: [`مفعول مطلق`, `تمييز`],
        },
      ],
    },
  ],
};
