// Module 02 — الفعل القياسي (The Analogical/Rule-Governed Verb)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__1 الْفِعْلِ__1 القياسي.apkg,
// 36 notes across 2 sub-decks) prepared for this conversion. Definitions and
// examples are kept faithful to the source notes. Concept bodies are short
// by design (a sentence or two, not teaching prose); quiz/bank question text
// is English with Arabic grammatical terms left in Arabic.
//
// The source deck covers only الفعل القياسي (§1 of الفعل, itself §1 of
// العامل وغير العامل) — لازم/متعدٍ, أفعال القلوب, أفعال التحويل, and
// التعليق/الإلغاء. الفعل السماعي (§2 of الفعل) is covered separately in
// Module 03; العامل within الاسم and الحرف could extend this module further.

export default {
  id: '02',
  title: 'الفعل القياسي',
  heading: 'العامل وغير العامل',
  subheading: 'الفعل',
  blurb: 'The قياسي فعل: transitivity (لازم vs متعدٍ), the multi-object أفعال القلوب and أفعال التحويل, and how التعليق and الإلغاء affect their government.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'اللازم والمتعدي',
      subtitle: 'Transitivity — تعريف اللازم والمتعدي, and the two ways a فعل reaches its مفعول',
      concepts: [
        {
          heading: 'عامل الفعل: القياسي والسماعي',
          body: `<bdi>عَامِلُ الْفِعْل</bdi> — how a فعل governs the words around it — divides into two kinds: <bdi>الْقِيَاسِيّ</bdi>, which follows a consistent rule (<bdi>قَاعِدَةٌ مُطَّرِدَة</bdi>), and <bdi>السَّمَاعِيّ</bdi>, which follows no rule and depends purely on how it was transmitted (<bdi>السَّمَاع</bdi>). This module covers القياسي only. Its government runs in two directions: (1) it makes the <bdi>فَاعِل</bdi>, or what substitutes for it (<bdi>نَائِبُهُ</bdi>), <bdi>مَرْفُوع</bdi> (2) it makes the <bdi>مَفَاعِيل</bdi> and the <bdi>حَال</bdi> <bdi>مَنْصُوب</bdi>.`,
          sample: `القياسي — قاعدة مطردة<br>السماعي — لا قاعدة، يُعتمد فيه على السماع<br>القياسي يرفع الفاعل أو نائبه، وينصب المفاعيل والحال`,
          exercise: {
            prompt: `Which of these is NOT something the قياسي فعل governs?`,
            kind: 'mcq',
            options: ['رفع الفاعل', 'نصب المفعول به', 'نصب الحال', 'جر المضاف إليه'],
            correct: 3,
          },
        },
        {
          heading: 'الفعل اللازم',
          body: `<bdi>الفعل اللازم</bdi> — also called <bdi>فِعْلٌ قَاصِر</bdi> or <bdi>فِعْلٌ غَيْرُ مُتَعَدٍّ</bdi> — is one whose effect does not pass beyond its <bdi>فَاعِل</bdi> to a <bdi>مَفْعُولٌ بِهِ</bdi>, as in <bdi>﴿وَلَا هُمْ يَحْزَنُونَ﴾</bdi>. That does not trap its effect entirely inside the فاعل: it can still reach things other than the مفعول به, such as the <bdi>مَفْعُولُ فِيهِ</bdi> and the <bdi>حَال</bdi>, as in <bdi>جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ مُتَأَدِّبًا تَبْجِيلًا لِلْعِلْمِ</bdi>.`,
          sample: `الفعل اللازم = فعل قاصر = فعل غير متعدٍ<br>﴿وَلَا هُمْ يَحْزَنُونَ﴾ — لا مفعول به<br>جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ مُتَأَدِّبًا — أمامَ: مفعول فيه، متأدبًا: حال`,
          exercise: {
            prompt: `جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ has no مفعول به, so جَلَسَ is لازم. Does that mean its effect cannot reach anything beyond الفاعل at all?`,
            kind: 'mcq',
            options: ['Correct — a لازم فعل never governs anything beyond its فاعل', 'No — it can still reach a مفعول فيه or a حال, just not a مفعول به', 'No — it can still take a second فاعل', 'No — الفعل اللازم actually takes a مفعول به whenever it is definite'],
            correct: 1,
          },
        },
        {
          heading: 'طرق التعدي: بنفسه وبحرف الجر',
          body: `<bdi>الفعل المتعدي</bdi> — also called <bdi>فِعْلٌ وَاقِع</bdi> (falling upon the object) or <bdi>فِعْلٌ مُجَاوِز</bdi> (whose effect crosses over) — reaches its مفعول به in one of two ways: (1) <bdi>بِنَفْسِهِ</bdi>, directly, as in <bdi>﴿الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنَّا الْحَزَنَ﴾</bdi> (2) <bdi>بِوَاسِطَةِ حَرْفِ جَرٍّ</bdi>, as in <bdi>﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾</bdi>. In the second case that جار ومجرور is itself called <bdi>مَفْعُولٌ بِهِ بِوَاسِطَةِ حَرْفِ الْجَرِّ</bdi> — or <bdi>مُتَعَلِّقٌ بِمَعْنَى الْمَفْعُولِ بِهِ</bdi>, or <bdi>مَفْعُولٌ بِهِ غَيْرُ صَرِيح</bdi>. Some أفعال take both routes: <bdi>هَدَى</bdi> is متعدٍ بنفسه in <bdi>﴿اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ﴾</bdi> but متعدٍ بحرف الجر in <bdi>﴿وَهَدَاهُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾</bdi>.`,
          sample: `متعدٍ بنفسه — ﴿الحمد لله الذي أذهب عنا الحزن﴾<br>متعدٍ بحرف جر — ﴿ذهب الله بنورهم﴾<br>هدى بالطريقتين — ﴿اهدنا الصراط المستقيم﴾ / ﴿وهداه إلى صراط مستقيم﴾`,
          exercise: {
            prompt: `In ﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾, بِنُورِهِمْ is the مفعول به of ذَهَبَ — but not بنفسه. What is this way of being متعدٍ called?`,
            kind: 'mcq',
            options: ['متعدٍ بنفسه', 'متعدٍ بواسطة حرف الجر', 'متعدٍ إلى مفعولين', 'فعل لازم بحرف جر'],
            correct: 1,
          },
        },
        {
          heading: 'أضرب المتعدي الثلاثة',
          body: `A متعدي فعل falls into one of three <bdi>أَضْرُب</bdi> by how many مفاعيل it takes: (1) <bdi>مُتَعَدٍّ إِلَى مَفْعُولٍ وَاحِد</bdi>, as in <bdi>﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾</bdi> (2) <bdi>مُتَعَدٍّ إِلَى مَفْعُولَيْنِ</bdi> (3) <bdi>مُتَعَدٍّ إِلَى ثَلَاثَةِ مَفَاعِيل</bdi>. The أفعال taking two مفعولين themselves split in two: those whose مفعولان are NOT originally a <bdi>مُبْتَدَأٌ وَخَبَر</bdi> — mostly أفعال of giving like <bdi>أَعْطَى، مَنَحَ، وَهَبَ، كَسَا</bdi>, called <bdi>أَفْعَالُ الْجَارِحَة</bdi> — and those whose مفعولان ARE originally مبتدأ وخبر, called <bdi>أَفْعَالُ الْقَلْبِ</bdi> or <bdi>أَفْعَالُ التَّحْوِيل</bdi>. The next two lessons are built entirely on this second kind.`,
          sample: `مفعول واحد — ﴿خلق السماوات والأرض﴾<br>مفعولان (أفعال الجارحة) — أعطى، منح، وهب، كسا<br>مفعولان أصلهما مبتدأ وخبر (أفعال القلب/التحويل) — ﴿وما أظن الساعة قائمة﴾`,
          exercise: {
            prompt: `أَعْطَى takes two مفاعيل, and so does ظَنَّ. What separates the class أَعْطَى belongs to from the class ظَنَّ belongs to?`,
            kind: 'mcq',
            options: ['Whether the two مفاعيل were originally a مبتدأ وخبر', 'Whether the فعل is ماضٍ or مضارع', 'Whether the فعل is لازم or متعدٍ', 'Whether the مفعولان can ever be deleted'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What are the two types of عامل الفعل?',
          options: ['القياسي والسماعي', 'اللازم والمتعدي', 'الظاهر والمقدر', 'الأصلي والفرعي'],
          correct: 0,
        },
        {
          q: 'الفعل اللازم is defined as:',
          options: ['A فعل whose effect passes to a مفعول به', 'A فعل whose effect does not pass beyond its فاعل to a مفعول به', 'A فعل linked to a specific time', 'A فعل that never takes a فاعل'],
          correct: 1,
        },
        {
          q: 'Which best describes الفعل المتعدي?',
          options: ['فعل قاصر, whose effect stays with its فاعل', 'فعل واقع, whose effect passes to a مفعول به', 'فعل جامد, which cannot be conjugated', 'فعل مبني, which never takes إعراب'],
          correct: 1,
        },
        {
          q: 'In ﴿وَهَدَاهُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾, how is هدى متعدٍ here?',
          options: ['بنفسه', 'بواسطة حرف الجر', 'فهو لازم في هذه الآية', 'بواسطة الفاعل'],
          correct: 1,
        },
        {
          q: 'أَعْطَى and مَنَحَ belong to which class of two-مفعول أفعال؟',
          options: ['أفعال الجارحة', 'أفعال القلب', 'أفعال التحويل', 'أفعال الشروع'],
          correct: 0,
        },
        {
          q: 'Can the مفاعيل of a giving-type فعل (متعدٍ لمفعولين) be deleted?',
          options: ['Yes — one, the other, or both may be deleted', 'No, never', 'Only the first may be deleted', 'Only when the فعل is فعل أمر'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'قياسي أم سماعي؟',
          kind: 'mcq',
          prompt: "A فعل's government follows no consistent rule and depends only on what has been transmitted. That government is:",
          options: ['قياسي', 'سماعي', 'مطرد', 'منسوخ'],
          correct: 1,
        },
        {
          title: 'ماذا يرفع القياسي؟',
          kind: 'mcq',
          prompt: 'الفعل القياسي makes مرفوعًا:',
          options: ['الفاعل أو نائبه', 'المفعول به', 'الحال', 'المضاف إليه'],
          correct: 0,
        },
        {
          title: 'أسماء أخرى للازم',
          kind: 'mcq',
          prompt: 'الفعل اللازم is also known as:',
          options: ['فعل قاصر', 'فعل واقع', 'فعل مجاوز', 'فعل جارحة'],
          correct: 0,
        },
        {
          title: 'أسماء أخرى للمتعدي',
          kind: 'mcq',
          prompt: 'الفعل المتعدي is called فعلاً واقعًا, and is also known as:',
          options: ['فعلاً مجاوزًا', 'فعلاً قاصرًا', 'فعلاً جارحًا', 'فعلاً ناقصًا'],
          correct: 0,
        },
        {
          title: 'مثال على اللازم',
          kind: 'mcq',
          prompt: '﴿وَلَا هُمْ يَحْزَنُونَ﴾ — why is يَحْزَنُونَ considered فعلاً لازمًا?',
          options: ["Because it doesn't reach a مفعول به", 'Because it has no فاعل', 'Because it is مبني للمجهول', "Because it doesn't accept تصريف"],
          correct: 0,
        },
        {
          title: 'هل يتعدى اللازم لغير المفعول به؟',
          kind: 'mcq',
          prompt: 'جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ مُتَأَدِّبًا — أَمَامَ and مُتَأَدِّبًا prove that a لازم فعل can still reach:',
          options: ['المفعول فيه والحال', 'المفعول به فقط', 'المفعول المطلق فقط', 'لا شيء البتة'],
          correct: 0,
        },
        {
          title: 'متعدٍ بنفسه',
          kind: 'mcq',
          prompt: '﴿الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنَّا الْحَزَنَ﴾ — أَذْهَبَ here is متعدٍ:',
          options: ['بنفسه', 'بحرف الجر', 'إلى مفعولين', 'بواسطة الفاعل'],
          correct: 0,
        },
        {
          title: 'متعدٍ بحرف جر',
          kind: 'mcq',
          prompt: '﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾ — how does ذَهَبَ reach its مفعول here?',
          options: ['بواسطة حرف الجر', 'بنفسه مباشرة', 'بالتضعيف', 'لا يتعدى، فهو لازم'],
          correct: 0,
        },
        {
          title: 'اسم آخر للمفعول بواسطة حرف الجر',
          kind: 'mcq',
          prompt: 'A مفعول به reached by way of a حرف جر is also called:',
          options: ['مفعولاً به غير صريح', 'مفعولاً مطلقًا', 'مفعولاً لأجله', 'نائب فاعل'],
          correct: 0,
        },
        {
          title: 'هدى بالطريقتين',
          kind: 'mcq',
          prompt: '﴿اهدنا الصراط المستقيم﴾ and ﴿وهداه إلى صراط مستقيم﴾ together prove that:',
          options: ['فعلاً واحدًا قد يتعدى بنفسه وبحرف الجر معًا', 'هدى فعل لازم دائمًا', 'هدى لا يتعدى إلا بحرف الجر', 'التعدي بحرف الجر مستحيل مع هدى'],
          correct: 0,
        },
        {
          title: 'أضرب المتعدي',
          kind: 'mcq',
          prompt: 'How many أضرب does الفعل المتعدي split into, by number of مفاعيل?',
          options: ['ثلاثة', 'اثنان', 'أربعة', 'خمسة'],
          correct: 0,
        },
        {
          title: 'مفعول واحد',
          kind: 'mcq',
          prompt: '﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾ — خَلَقَ here is متعدٍ to:',
          options: ['مفعول واحد', 'مفعولين', 'ثلاثة مفاعيل', 'لا مفعول له'],
          correct: 0,
        },
        {
          title: 'أفعال الجارحة',
          kind: 'mcq',
          prompt: 'أَعْطَى، مَنَحَ، وَهَبَ، كَسَا take two مفعولين that were NOT originally مبتدأ وخبر. These أفعال are called:',
          options: ['أفعال الجارحة', 'أفعال القلوب', 'أفعال التحويل', 'أفعال الشروع'],
          correct: 0,
        },
        {
          title: 'أصل المفعولين',
          kind: 'mcq',
          prompt: 'What distinguishes the مفعولان of a فعل like ظَنَّ from those of a فعل like أَعْطَى?',
          options: ["That ظَنَّ's two مفعولين were originally مبتدأ وخبر", "That أَعْطَى's two مفعولين were originally مبتدأ وخبر", 'That ظَنَّ can only take one مفعول', "There's no difference between them"],
          correct: 0,
        },
        {
          title: 'حذف مفاعيل أفعال الإعطاء',
          kind: 'mcq',
          prompt: '﴿وَإِنَّكَ لَتَهْدِي إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾ deletes one مفعول of هدى. Can the مفعولان of a giving-type فعل be deleted?',
          options: ['نعم، يجوز حذف أحدهما أو كليهما', 'لا يجوز حذف أي منهما', 'يجوز حذف الأول فقط', 'يجوز حذف الثاني فقط'],
          correct: 0,
        },
        {
          title: 'مثال حذف كلا المفعولين',
          kind: 'mcq',
          prompt: '﴿أَعْطَىٰ كُلَّ شَيْءٍ خَلْقَهُ ثُمَّ هَدَىٰ﴾ — what was deleted from هدى here?',
          options: ['مفعولاه كلاهما', 'فاعله فقط', 'حرف الجر فقط', 'لا شيء حُذف'],
          correct: 0,
        },
        {
          title: 'الفعل القياسي: ماذا ينصب؟',
          kind: 'mcq',
          prompt: 'Besides raising the فاعل, what does الفعل القياسي make منصوبًا?',
          options: ['المفاعيل والحال', 'المضاف إليه', 'الفاعل نفسه', 'التمييز فقط'],
          correct: 0,
        },
        {
          title: 'الفعل الواقع',
          kind: 'mcq',
          prompt: 'Why is الفعل المتعدي also called فعلاً واقعًا?',
          options: ['Because its effect falls (يقع) on the مفعول به', 'Because it falls between two فاعلين', 'Because it only occurs in the ماضي', 'Because it takes the place of an اسم'],
          correct: 0,
        },
        {
          title: 'تركيب: لازم أم متعدٍ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: لازم or متعدٍ?',
          source: 'ولا هم يحزنون / خلق السماوات والأرض / جلس الطالب / أذهب الله عنا الحزن',
          words: ['يحزنون', 'خلق', 'جلس', 'أذهب'],
          labels: ['لازم', 'متعدٍ', 'لازم', 'متعدٍ'],
          distractors: ['فعل قلب'],
        },
        {
          title: 'تركيب: بنفسه أم بحرف جر؟',
          kind: 'tarkeeb',
          instruction: 'Classify how each فعل reaches its مفعول: بنفسه or بحرف جر?',
          source: 'أذهب الله عنا الحزن / ذهب الله بنورهم / اهدنا الصراط المستقيم / وهداه إلى صراط مستقيم',
          words: ['أذهب', 'ذهب', 'اهدنا', 'هداه'],
          labels: ['متعدٍ بنفسه', 'متعدٍ بحرف جر', 'متعدٍ بنفسه', 'متعدٍ بحرف جر'],
          distractors: ['لازم'],
        },
        {
          title: 'تركيب: أفعال الجارحة أم أفعال القلب؟',
          kind: 'tarkeeb',
          instruction: 'Classify each two-مفعول فعل: أفعال الجارحة or أفعال القلب?',
          source: 'وهديناهما الصراط المستقيم / وما أظن الساعة قائمة / أعطى كل شيء خلقه / منحه الأمير مالاً',
          words: ['وهديناهما', 'أظن', 'أعطى', 'منحه'],
          labels: ['أفعال الجارحة', 'أفعال القلب', 'أفعال الجارحة', 'أفعال الجارحة'],
          distractors: ['أفعال ناقصة'],
        },
        {
          title: 'تركيب: ماذا يرفع وينصب القياسي؟',
          kind: 'tarkeeb',
          instruction: "Identify each word's grammatical role under الفعل القياسي's government.",
          source: 'ضَرَبَ الْوَلَدُ الْكَلْبَ مُسْرِعًا',
          words: ['الْوَلَدُ', 'الْكَلْبَ', 'مُسْرِعًا'],
          labels: ['فاعل مرفوع', 'مفعول به منصوب', 'حال منصوب'],
          distractors: ['مضاف إليه مجرور'],
        },
        {
          title: 'تركيب: لازم أم متعدٍ؟ (٢)',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: لازم or متعدٍ?',
          source: 'فَاصْبِرْ صَبْرًا جَمِيلًا / وَاللَّهُ بَصِيرٌ بِمَا تَعْمَلُونَ / خَرَجَ الرَّجُلُ / أَكَلَ الْوَلَدُ التُّفَّاحَةَ',
          words: ['اصْبِرْ', 'تَعْمَلُونَ', 'خَرَجَ', 'أَكَلَ'],
          labels: ['لازم', 'متعدٍ', 'لازم', 'متعدٍ'],
          distractors: ['فعل تحويل'],
        },
        {
          title: 'تركيب: عدد المفاعيل',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل by its number of مفاعيل: مفعول واحد or مفعولان?',
          source: '﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾ / ﴿وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ﴾ / مَنَحَ الْأَمِيرُ الْفَقِيرَ مَالًا / ﴿أَذْهَبَ عَنَّا الْحَزَنَ﴾',
          words: ['خَلَقَ', 'هَدَيْنَاهُمَا', 'مَنَحَ', 'أَذْهَبَ'],
          labels: ['مفعول واحد', 'مفعولان', 'مفعولان', 'مفعول واحد'],
          distractors: ['ثلاثة مفاعيل'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'أفعال القلوب',
      subtitle: 'Verbs of the Heart — اليقين and الظن, and how their two objects behave',
      concepts: [
        {
          heading: 'أفعال القلوب: اليقين والظن',
          body: `<bdi>أَفْعَالُ الْقُلُوب</bdi> — the فعل قلب class introduced last lesson — split into two groups: (1) أفعال of certainty (<bdi>الْيَقِين</bdi>): <bdi>وَجَدَ، أَلْفَى، رَأَى، عَلِمَ، عَرَفَ، دَرَى، تَعَلَّمَ</bdi> (2) أفعال of preponderant opinion (<bdi>الظَّنّ</bdi>), also called <bdi>أَفْعَالُ الرُّجْحَان</bdi>: <bdi>ظَنَّ، حَسِبَ، زَعَمَ، جَعَلَ، حَجَا، عَدَّ، وَهَبَ، خَالَ</bdi>. Every one of them takes two مفاعيل that were originally a <bdi>مُبْتَدَأٌ وَخَبَر</bdi> — that's what makes it a فعل قلب rather than a plain متعدٍ لمفعولين.`,
          sample: `اليقين (٧) — وجد، ألفى، رأى، علم، عرف، درى، تعلَّم<br>الظن/الرجحان (٨) — ظن، حسب، زعم، جعل، حجا، عد، وهب، خال`,
          exercise: {
            prompt: `عَلِمَ and ظَنَّ are both أفعال القلوب, but from different groups. Which group does ظَنَّ belong to?`,
            kind: 'mcq',
            options: ['اليقين', 'الظن (الرجحان)', 'كلاهما معًا', 'لا ينتمي إلى أي منهما'],
            correct: 1,
          },
        },
        {
          heading: 'أمثلة قرآنية على أفعال القلوب',
          body: `﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ — <bdi>وَجَدَ</bdi> here is a فعل قلب of اليقين, taking two مفعولين (<bdi>أَكْثَرَهُمْ</bdi> and <bdi>لَفَاسِقِينَ</bdi>). ﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾ — <bdi>حَسِبَ</bdi> here is a فعل قلب of الظن. ﴿وَجَعَلُوا الْمَلَائِكَةَ الَّذِينَ هُمْ عِبَادُ الرَّحْمَٰنِ إِنَاثًا﴾ — <bdi>جَعَلَ</bdi> here is a فعل قلب of الظن as well: they merely *supposed* the angels female.`,
          sample: `وجد (يقين) — ﴿وإن وجدنا أكثرهم لفاسقين﴾<br>حسب (ظن) — ﴿ويحسبون أنهم مهتدون﴾<br>جعل (ظن) — ﴿وجعلوا الملائكة...إناثا﴾`,
          exercise: {
            prompt: `In ﴿وَجَعَلُوا الْمَلَائِكَةَ...إِنَاثًا﴾, جَعَلَ takes الملائكة and إناثًا as two مفاعيل. What category of أفعال القلوب is this?`,
            kind: 'mcq',
            options: ['فعل قلب من أفعال اليقين', 'فعل قلب من أفعال الظن (الرجحان)', 'ليس فعل قلب، بل فعل جارحة', 'فعل لازم لا يتعدى'],
            correct: 1,
          },
        },
        {
          heading: 'حذف مفاعيل أفعال القلوب: الاختصار والاقتصار',
          body: `The two مفاعيل of a فعل قلب can sometimes drop out of the wording. <bdi>الِاخْتِصَار</bdi> — deleting BOTH مفعولين while other evidence in the جملة still points to what they were — is permitted, as in <bdi>﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾</bdi>, meaning <bdi>تَزْعُمُونَهُمْ شُرَكَائِي</bdi>. <bdi>الِاقْتِصَار</bdi> — deleting only ONE مفعول with nothing in the جملة pointing to what was meant — is not permitted; a bare <bdi>ظَنَنْتُهُ</bdi> with nothing else said cannot stand.`,
          sample: `الاختصار (جائز) — ﴿أين شركائي الذين كنتم تزعمون﴾ = تزعمونهم شركائي<br>الاقتصار (غير جائز) — ظننتُه (بلا قرينة)`,
          exercise: {
            prompt: `﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾ deletes both مفعولا زعم, yet the sentence still stands. What licenses deleting both together?`,
            kind: 'mcq',
            options: ["That there's a قرينة pointing to what's deleted — this is the permitted الاختصار", 'That زعم is a فعل لازم needing no مفعولين', 'That deleting only one مفعول is always the permitted option', 'That أفعال القلوب need no مفعول at all'],
            correct: 0,
          },
        },
        {
          heading: 'معانٍ خاصة: ألم تر وأرأيت وكاف الخطاب',
          body: `A few أفعال قلوب carry idiomatic senses worth knowing on their own. <bdi>أَلَمْ تَرَ</bdi> means <bdi>أَلَمْ تَعْلَمْ</bdi>, with an added sense of <bdi>التَّعَجُّب</bdi> — knowledge is expressed through "seeing" because sight is the strongest cause of knowledge. <bdi>أَرَأَيْتَ</bdi>, as in <bdi>﴿أَرَأَيْتَ مَنِ اتَّخَذَ إِلَٰهَهُ هَوَاهُ﴾</bdi>, means <bdi>أَخْبِرْنِي</bdi> ("tell me") in situations of astonishment; its <bdi>ضَمِيرٌ مَرْفُوع</bdi> changes with the addressee (<bdi>أَرَأَيْتِ، أَرَأَيْتُم</bdi>...). When a <bdi>كَاف</bdi> is added, as in <bdi>أَرَأَيْتَكَ / أَرَأَيْتَكُمْ</bdi>, it is a <bdi>كَافُ الْخِطَاب</bdi> added only to emphasise the address (<bdi>تَوْكِيدُ الْخِطَاب</bdi>) — the ضمير مرفوع stays fixed at <bdi>تَ</bdi>, and only that كاف changes: <bdi>أَرَأَيْتَكِ، أَرَأَيْتَكُمْ</bdi>.`,
          sample: `ألم تر = ألم تعلم (+ تعجب)<br>أرأيت = أخبرني، نحو ﴿أرأيت من اتخذ إلهه هواه﴾<br>كاف الخطاب — أرأيتَك، أرأيتَكم (التاء ثابتة، الكاف هي التي تتغير)`,
          exercise: {
            prompt: `In أَرَأَيْتَكَ, which part is the ضمير مرفوع of رأى, and which part is only there for توكيد الخطاب?`,
            kind: 'mcq',
            options: ['التاء is the ضمير مرفوع; الكاف is a كاف الخطاب for emphasis', 'الكاف is the ضمير مرفوع; التاء is زائدة for emphasis', 'Both together form a repeated ضمير مرفوع', 'There is no ضمير in the word — the فعل is مبني للمجهول'],
            correct: 0,
          },
        },
        {
          heading: 'أفعال القلوب خارج معنى القلب',
          body: `When one of these أفعال is used in a sense OTHER than قلب, it drops back to taking a single مفعول, like any ordinary متعدٍ. <bdi>﴿لَا تَعْلَمُونَ شَيْئًا﴾</bdi> means <bdi>لَا تَعْرِفُونَ</bdi>; <bdi>﴿لَاتَّخَذْتَ عَلَيْهِ أَجْرًا﴾</bdi> means <bdi>طَلَبْتَ</bdi>; <bdi>﴿وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ﴾</bdi> means <bdi>صَادَفَا</bdi>; <bdi>وَجَدْتُ الضَّالَّةَ</bdi> means <bdi>أَصَبْتُهَا</bdi>; <bdi>ظَنَنْتُ زَيْدًا</bdi> means <bdi>اتَّهَمْتُهُ</bdi>; <bdi>رَأَيْتُ زَيْدًا</bdi> means <bdi>أَبْصَرْتُهُ</bdi>.`,
          sample: `وجدت الضالة = أصبتها (مفعول واحد)<br>رأيت زيدًا = أبصرته (مفعول واحد)<br>ظننت زيدًا = اتهمته (مفعول واحد)`,
          exercise: {
            prompt: `رَأَيْتُ زَيْدًا, meaning أَبْصَرْتُهُ, takes only one مفعول. Why does رأى not take two مفاعيل here the way it does as a فعل قلب?`,
            kind: 'mcq',
            options: ['Because it is used in the sense of physical sight (أبصر), not قلبي knowledge', 'Because زيدًا cannot be a مفعول به', 'Because رأى is لازم in this sentence', 'Because it is being used as فعل أمر'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'Which of these four is one of أفعال اليقين, not أفعال الظن؟',
          options: ['حسب', 'زعم', 'علم', 'خال'],
          correct: 2,
        },
        {
          q: 'What does أَرَأَيْتَ mean in ﴿أَرَأَيْتَ مَنِ اتَّخَذَ إِلَٰهَهُ هَوَاهُ﴾?',
          options: ['أخبرني', 'أبصرت', 'اعتقدت', 'اتهمت'],
          correct: 0,
        },
        {
          q: 'الاختصار, in deleting the مفاعيل of أفعال القلوب, means:',
          options: ['حذف المفعولين معًا مع وجود قرينة', 'حذف مفعول واحد بلا قرينة', 'عدم حذف أي مفعول أبدًا', 'تحويل الفعل إلى المبني للمجهول'],
          correct: 0,
        },
        {
          q: 'ظَنَنْتُ زَيْدًا, meaning اتَّهَمْتُهُ, takes how many مفعولاً?',
          options: ['مفعولاً واحدًا', 'مفعولين', 'ثلاثة مفاعيل', 'لا مفعول له'],
          correct: 0,
        },
        {
          q: 'In أَرَأَيْتَكَ, what is the role of the كاف?',
          options: ['كاف خطاب للتوكيد، وليست ضميرًا مرفوعًا', 'ضمير مرفوع فاعل', 'مفعول به', 'حرف جر'],
          correct: 0,
        },
        {
          q: '﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾ — حَسِبَ هنا من:',
          options: ['أفعال اليقين', 'أفعال الظن (الرجحان)', 'أفعال التحويل', 'أفعال الجارحة'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: 'كم عدد أفعال اليقين؟',
          kind: 'mcq',
          prompt: 'How many أفعال اليقين were mentioned?',
          options: ['سبعة', 'ستة', 'ثمانية', 'خمسة'],
          correct: 0,
        },
        {
          title: 'كم عدد أفعال الظن؟',
          kind: 'mcq',
          prompt: 'How many أفعال الظن (الرجحان) were mentioned?',
          options: ['ثمانية', 'سبعة', 'ستة', 'تسعة'],
          correct: 0,
        },
        {
          title: 'اسم آخر لأفعال الظن',
          kind: 'mcq',
          prompt: 'أفعال الظن are also called:',
          options: ['أفعال الرجحان', 'أفعال الجارحة', 'أفعال اليقين', 'أفعال التحويل'],
          correct: 0,
        },
        {
          title: 'وجد في الآية',
          kind: 'mcq',
          prompt: '﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ — وَجَدَ here belongs to:',
          options: ['أفعال اليقين', 'أفعال الظن', 'أفعال التحويل', 'أفعال الجارحة'],
          correct: 0,
        },
        {
          title: 'ما يشترك فيه أفعال القلوب',
          kind: 'mcq',
          prompt: 'What do all أفعال القلوب have in common?',
          options: ['That their two مفعولين were originally مبتدأ وخبر', 'That they are all أفعال أمر', 'That they never تتصرف', 'That they always take the صيغة المبني للمجهول'],
          correct: 0,
        },
        {
          title: 'الاقتصار',
          kind: 'mcq',
          prompt: 'الاقتصار, in deleting one مفعول of أفعال القلوب, is:',
          options: ['Not permitted, because there is no قرينة', 'Always permitted', 'Obligatory in every جملة', 'Specific to أفعال اليقين only'],
          correct: 0,
        },
        {
          title: 'تقدير الاختصار',
          kind: 'mcq',
          prompt: '﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾ — what is the implied wording?',
          options: ['تزعمونهم شركائي', 'تزعمون شركائي أنتم', 'زعمتم أن لا شركاء', 'تزعمون أنكم شركاء'],
          correct: 0,
        },
        {
          title: 'ألم تر',
          kind: 'mcq',
          prompt: 'أَلَمْ تَرَ means:',
          options: ['ألم تعلم (مع تعجب)', 'ألم تسمع', 'ألم تقل', 'ألم تذهب'],
          correct: 0,
        },
        {
          title: 'لماذا الرؤية تعبّر عن العلم؟',
          kind: 'mcq',
          prompt: 'Why is العلم expressed by "الرؤية" in أَلَمْ تَرَ?',
          options: ['Because البصر (sight) is the strongest cause of العلم', 'Because الرؤية and العلم are always synonyms', 'Because ألم تر is a فعل أمر', "Because there's no relation between الرؤية and العلم"],
          correct: 0,
        },
        {
          title: 'أرأيتَ، أرأيتِ، أرأيتم',
          kind: 'mcq',
          prompt: 'أَرَأَيْتَ، أَرَأَيْتِ، أَرَأَيْتُمْ — what changes between them?',
          options: ['The ضمير مرفوع, according to the المخاطَب', 'The فعل itself changes radically', 'The meaning changes completely in each صيغة', 'Nothing changes'],
          correct: 0,
        },
        {
          title: 'لا تعلمون شيئا',
          kind: 'mcq',
          prompt: '﴿لَا تَعْلَمُونَ شَيْئًا﴾ means:',
          options: ['لا تعرفون', 'لا تظنون', 'لا تتهمون', 'لا تتحولون'],
          correct: 0,
        },
        {
          title: 'لاتخذت عليه أجرا',
          kind: 'mcq',
          prompt: '﴿لَاتَّخَذْتَ عَلَيْهِ أَجْرًا﴾ means:',
          options: ['طلبتَ', 'ظننتَ', 'وجدتَ', 'عرفتَ'],
          correct: 0,
        },
        {
          title: 'وألفيا سيدها لدى الباب',
          kind: 'mcq',
          prompt: '﴿وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ﴾ means:',
          options: ['صادفا', 'ظنّا', 'اتهما', 'طلبا'],
          correct: 0,
        },
        {
          title: 'وجدت الضالة',
          kind: 'mcq',
          prompt: 'وَجَدْتُ الضَّالَّةَ means:',
          options: ['أصبتُها', 'ظننتُها', 'عرفتُها بالاسم', 'تحوّلت إليها'],
          correct: 0,
        },
        {
          title: 'رأيت زيدًا',
          kind: 'mcq',
          prompt: 'رَأَيْتُ زَيْدًا, meaning أَبْصَرْتُهُ — how many مفعولاً here?',
          options: ['مفعولاً واحدًا', 'مفعولين', 'ثلاثة', 'لا مفعول'],
          correct: 0,
        },
        {
          title: 'لماذا سُميت أفعال القلوب كذلك؟',
          kind: 'mcq',
          prompt: 'أفعال القلوب are called that because they:',
          options: ['They indicate a قلبي meaning like اليقين or الظن', 'They تُصرَّف from القلب to الجوارح', 'They need no فاعل', 'They are always مبنية للمجهول'],
          correct: 0,
        },
        {
          title: 'جعل في الآية',
          kind: 'mcq',
          prompt: 'جَعَلَ in ﴿وَجَعَلُوا الْمَلَائِكَةَ...إِنَاثًا﴾ belongs to:',
          options: ['أفعال الظن', 'أفعال اليقين', 'أفعال الجارحة', 'أفعال لازمة'],
          correct: 0,
        },
        {
          title: 'الفرق بين الاختصار والاقتصار',
          kind: 'mcq',
          prompt: 'What is the practical difference between الاختصار and الاقتصار?',
          options: ['الاختصار deletes both with a قرينة; الاقتصار deletes one without a قرينة', 'الاختصار deletes one with a قرينة; الاقتصار deletes both without a قرينة', "There's no difference between them", 'الاختصار is specific to the ماضي; الاقتصار to the مضارع'],
          correct: 0,
        },
        {
          title: 'تركيب: اليقين أم الظن؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل قلب: أفعال اليقين or أفعال الظن?',
          source: 'وجد / علم / ظن / حسب',
          words: ['وجد', 'علم', 'ظن', 'حسب'],
          labels: ['اليقين', 'اليقين', 'الظن', 'الظن'],
          distractors: ['التحويل'],
        },
        {
          title: 'تركيب: أمثلة قرآنية',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل قلب in the آيات: اليقين or الظن?',
          source: '﴿وإن وجدنا أكثرهم لفاسقين﴾ / ﴿ويحسبون أنهم مهتدون﴾ / ﴿وجعلوا الملائكة...إناثا﴾',
          words: ['وجدنا', 'يحسبون', 'جعلوا'],
          labels: ['اليقين', 'الظن', 'الظن'],
          distractors: ['التحويل'],
        },
        {
          title: 'تركيب: بمعنى القلب أم خارج معناه؟',
          kind: 'tarkeeb',
          instruction: 'Classify each usage: بمعنى القلب (مفعولان) or خارج معنى القلب (مفعول واحد)?',
          source: 'وجدتُ الضالةَ / وإن وجدنا أكثرهم لفاسقين / رأيتُ زيدًا / ويحسبون أنهم مهتدون',
          words: ['وجدتُ', 'وجدنا', 'رأيتُ', 'يحسبون'],
          labels: ['خارج معنى القلب', 'بمعنى القلب', 'خارج معنى القلب', 'بمعنى القلب'],
          distractors: ['فعل تحويل'],
        },
        {
          title: 'تركيب: الاختصار أم الاقتصار؟',
          kind: 'tarkeeb',
          instruction: 'Classify each deletion: اختصار جائز or اقتصار غير جائز?',
          source: '﴿أين شركائي الذين كنتم تزعمون﴾ / ظننتُه (بلا قرينة)',
          words: ['تزعمون', 'ظننتُه'],
          labels: ['اختصار', 'اقتصار'],
          distractors: ['إلغاء'],
        },
        {
          title: 'تركيب: عدد المفاعيل بعد تغيّر المعنى',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل by its number of مفاعيل in this usage.',
          source: '﴿لا تعلمون شيئا﴾ / ﴿وألفيا سيدها لدى الباب﴾ / ﴿وإن وجدنا أكثرهم لفاسقين﴾ / ﴿ويحسبون أنهم مهتدون﴾',
          words: ['تعلمون', 'ألفيا', 'وجدنا', 'يحسبون'],
          labels: ['مفعول واحد', 'مفعول واحد', 'مفعولان', 'مفعولان'],
          distractors: ['ثلاثة مفاعيل'],
        },
        {
          title: 'تركيب: تصنيف عام لأفعال القلوب',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: أفعال اليقين or أفعال الظن?',
          source: 'درى / تعلَّم / زعم / خال',
          words: ['درى', 'تعلَّم', 'زعم', 'خال'],
          labels: ['اليقين', 'اليقين', 'الظن', 'الظن'],
          distractors: ['الجارحة'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'أفعال التحويل',
      subtitle: 'Verbs of Conversion — التحويل, the three-مفعول فعل, and ما يسد مسد المفعولين',
      concepts: [
        {
          heading: 'أفعال التحويل: تعريفها وأمثلتها',
          body: `<bdi>أَفْعَالُ التَّحْوِيل</bdi> are the other branch of the two-مفعول class from Lesson 1 — أفعال bearing the meaning of <bdi>صَيَّرَ</bdi> (to transform something into something else). There are six: <bdi>صَيَّرَ، رَدَّ، تَرَكَ، تَخِذَ/اتَّخَذَ، جَعَلَ، وَهَبَ</bdi>. In <bdi>﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾</bdi>, <bdi>اتَّخَذَ</bdi> is بمعنى صيّر, and its two مفاعيل are <bdi>إِبْرَاهِيمَ</bdi> and <bdi>خَلِيلًا</bdi>.`,
          sample: `أفعال التحويل (٦) — صيّر، رد، ترك، تخذ/اتخذ، جعل، وهب<br>﴿واتخذ الله إبراهيم خليلا﴾ — إبراهيم وخليلا: مفعولا اتخذ`,
          exercise: {
            prompt: `جَعَلَ and وَهَبَ each appear in TWO different lists across this module. Which two classes do they straddle?`,
            kind: 'mcq',
            options: ['أفعال الظن (القلب) وأفعال التحويل', 'أفعال اليقين وأفعال الجارحة', 'اللازم والمتعدي', 'التعليق والإلغاء'],
            correct: 0,
          },
        },
        {
          heading: 'أفعال التحويل خارج معنى التحويل',
          body: `Just like أفعال القلوب, when one of these أفعال is used OUTSIDE the meaning of تحويل, it takes only a single مفعول. <bdi>﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللَّهِ﴾</bdi> — تَرَكَ here is ordinary "leaving", one مفعول. <bdi>﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾</bdi> means <bdi>يُصَار</bdi> — a plain "return", not transformation. <bdi>﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾</bdi> means <bdi>خَلَقَ</bdi> or <bdi>أَوْجَدَ</bdi> — "created" — again one مفعول (the three coordinated أسماء together, not three separate مفاعيل).`,
          sample: `تركت ملة قوم — مفعول واحد (ليس بمعنى صيّر)<br>يُرد إلى ربه = يُصار — مفعول واحد<br>جعل لكم السمع والأبصار = خلق/أوجد — مفعول واحد`,
          exercise: {
            prompt: `﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾ — جَعَلَ here means خَلَقَ. Does it take one مفعول or two, and why؟`,
            kind: 'mcq',
            options: ["Just one — because it's outside the meaning of التحويل here", "Two — because it's always a فعل تحويل", 'Three — because three أسماء follow it', "No مفعول at all — it's لازم here"],
            correct: 0,
          },
        },
        {
          heading: 'الفعل الآخذ لثلاثة مفاعيل',
          body: `A فعل can take up to three مفاعيل — but only ever a <bdi>فِعْلُ قَلْب</bdi>, such as <bdi>أَرَى</bdi>. Its second and third مفاعيل are, just like a two-object فعل قلب, originally a <bdi>مُبْتَدَأٌ وَخَبَر</bdi>: <bdi>﴿كَذَٰلِكَ يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾</bdi> — <bdi>أَعْمَالَهُمْ</bdi> and <bdi>حَسَرَاتٍ</bdi> are the second and third مفعولان, standing where a مبتدأ وخبر would.`,
          sample: `أرى — فعل قلب يأخذ ثلاثة مفاعيل<br>﴿كذلك يريهم الله أعمالهم حسرات عليهم﴾ — هم: مفعول أول، أعمالهم: مفعول ثانٍ، حسرات: مفعول ثالث`,
          exercise: {
            prompt: `يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ takes three مفاعيل. What class of فعل can ever reach three مفاعيل?`,
            kind: 'mcq',
            options: ['فعل قلب وحده', 'أي فعل متعدٍ', 'فعل تحويل وحده', 'فعل لازم مقترن بحرف جر'],
            correct: 0,
          },
        },
        {
          heading: 'ما يسد مسد مفعولي فعل القلب',
          body: `The two مفاعيل of a فعل قلب don't always show up as two plain أسماء — something else can stand in their place (<bdi>يَسُدُّ مَسَدَّ</bdi> them). Two things can do this: (1) an <bdi>اسْمٌ مُؤَوَّل</bdi>, as in <bdi>﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾</bdi>, where <bdi>أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ</bdi> stands for both مفعولا اعلموا (2) a <bdi>جُمْلَة</bdi>, as in <bdi>﴿وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ﴾</bdi>.`,
          sample: `اسم مؤول يسد مسد المفعولين — ﴿واعلموا أن الله مع المتقين﴾<br>جملة تسد مسد المفعولين — ﴿والله يشهد إن المنافقين لكاذبون﴾`,
          exercise: {
            prompt: `In ﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾, اعلموا is a فعل قلب needing two مفاعيل — yet only one اسم مؤول follows it. How is that possible?`,
            kind: 'mcq',
            options: ['The اسم مؤول alone stands in for both مفعولين together', 'اعلموا here is a فعل لازم needing no مفعولين', 'One of the two مفعولين is deleted without a قرينة', 'أن الله مع المتقين is just one مفعول standing in for nothing'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أفعال التحويل were mentioned?',
          options: ['ستة', 'خمسة', 'سبعة', 'ثمانية'],
          correct: 0,
        },
        {
          q: 'Which two أفعال appear in both أفعال الظن and أفعال التحويل?',
          options: ['جعل ووهب', 'ظن وصيّر', 'رد وترك', 'زعم وتخذ'],
          correct: 0,
        },
        {
          q: '﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾, meaning يُصَار — how many مفعولاً here?',
          options: ['مفعولاً واحدًا', 'مفعولين', 'ثلاثة', 'لا مفعول'],
          correct: 0,
        },
        {
          q: 'A فعل taking three مفاعيل is always:',
          options: ['فعل قلب', 'فعل تحويل فقط', 'فعل جارحة', 'فعلاً لازمًا'],
          correct: 0,
        },
        {
          q: 'What can يسد مسد the two مفعولان of a فعل قلب?',
          options: ['الاسم المؤول أو الجملة', 'الحال أو التمييز', 'المفعول المطلق فقط', 'لا شيء يسد مسدهما'],
          correct: 0,
        },
        {
          q: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ — اتَّخَذَ here is a فعل:',
          options: ['تحويل', 'قلب من أفعال اليقين', 'لازم', 'جارحة'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'معنى أفعال التحويل',
          kind: 'mcq',
          prompt: 'أفعال التحويل carry the meaning of:',
          options: ['صيّر', 'ظن', 'علم', 'وجد'],
          correct: 0,
        },
        {
          title: 'من أفعال التحويل',
          kind: 'mcq',
          prompt: 'صَيَّرَ، رَدَّ، تَرَكَ belong to:',
          options: ['أفعال التحويل', 'أفعال اليقين', 'أفعال الجارحة', 'أفعال الظن فقط'],
          correct: 0,
        },
        {
          title: 'مفعولا اتخذ',
          kind: 'mcq',
          prompt: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ — the two مفعولان of اتَّخَذَ are:',
          options: ['إبراهيم وخليلا', 'الله وإبراهيم', 'خليلا فقط', 'لا مفعول له'],
          correct: 0,
        },
        {
          title: 'ترك خارج معنى التحويل',
          kind: 'mcq',
          prompt: '﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللَّهِ﴾ — تَرَكَ here is:',
          options: ['خارج معنى التحويل، مفعول واحد', 'بمعنى التحويل، مفعولان', 'فعل لازم', 'فعل قلب من اليقين'],
          correct: 0,
        },
        {
          title: 'يُرد إلى ربه',
          kind: 'mcq',
          prompt: '﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾ means:',
          options: ['يُصار', 'يُصيَّر', 'يُترك', 'يُتَّخذ'],
          correct: 0,
        },
        {
          title: 'السمع والأبصار والأفئدة',
          kind: 'mcq',
          prompt: '﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾ — جَعَلَ here means:',
          options: ['خلق أو أوجد', 'صيّر', 'ظن', 'ترك'],
          correct: 0,
        },
        {
          title: 'مثال على ثلاثة مفاعيل',
          kind: 'mcq',
          prompt: 'An example of a فعل taking three مفاعيل is:',
          options: ['أرى', 'رأى', 'وهب', 'صيّر'],
          correct: 0,
        },
        {
          title: 'عدد مفاعيل يُري',
          kind: 'mcq',
          prompt: '﴿كَذَٰلِكَ يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾ — how many مفعولاً for يُرِي here?',
          options: ['ثلاثة', 'اثنان', 'واحد', 'لا مفعول'],
          correct: 0,
        },
        {
          title: 'أصل المفعول الثاني والثالث',
          kind: 'mcq',
          prompt: 'For a three-مفعول فعل, the second and third مفعولان were originally:',
          options: ['مبتدأ وخبر', 'فاعل ونائبه', 'حال وتمييز', 'مضاف ومضاف إليه'],
          correct: 0,
        },
        {
          title: 'الاسم المؤول',
          kind: 'mcq',
          prompt: 'An اسم مؤول can:',
          options: ['يسد مسد مفعولي فعل القلب', 'يحل محل الفاعل فقط', 'يكون حرفًا لا اسمًا', 'لا يقع بعد أفعال القلوب أبدًا'],
          correct: 0,
        },
        {
          title: 'واعلموا أن الله مع المتقين',
          kind: 'mcq',
          prompt: '﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾ — what يسد مسد the two مفعولان of اعْلَمُوا?',
          options: ['أن الله مع المتقين (اسم مؤول)', 'الله وحده', 'المتقين وحده', 'لا شيء يسد مسدهما'],
          correct: 0,
        },
        {
          title: 'والله يشهد إن المنافقين لكاذبون',
          kind: 'mcq',
          prompt: '﴿وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ﴾ — what يسد مسد the two مفعولان of يَشْهَدُ?',
          options: ['الجملة بعده', 'اسم مؤول', 'مفعول مطلق', 'حال منصوب'],
          correct: 0,
        },
        {
          title: 'جعل مشترك',
          kind: 'mcq',
          prompt: 'جَعَلَ appears in both the lists of:',
          options: ['أفعال الظن وأفعال التحويل', 'أفعال اليقين وأفعال التحويل', 'اللازم والمتعدي', 'التعليق والإلغاء'],
          correct: 0,
        },
        {
          title: 'وهب مشترك',
          kind: 'mcq',
          prompt: 'وَهَبَ appears in both the lists of:',
          options: ['أفعال الظن وأفعال التحويل', 'أفعال اليقين والجارحة', 'اللازم والمتعدي', 'التعليق والإلغاء'],
          correct: 0,
        },
        {
          title: 'أفعال التحويل خارج معناها',
          kind: 'mcq',
          prompt: 'أفعال التحويل, outside their original meaning, take:',
          options: ['مفعولاً واحدًا', 'مفعولين دائمًا', 'ثلاثة مفاعيل', 'لا مفعول لها'],
          correct: 0,
        },
        {
          title: 'عدد مفاعيل اتخذ',
          kind: 'mcq',
          prompt: 'The number of مفاعيل of اتَّخَذَ in ﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾:',
          options: ['اثنان', 'واحد', 'ثلاثة', 'لا مفعول له'],
          correct: 0,
        },
        {
          title: 'ما لا يكون فعلاً ذا ثلاثة مفاعيل',
          kind: 'mcq',
          prompt: 'A فعل taking three مفاعيل can never be:',
          options: ['فعل تحويل أو فعل جارحة', 'فعل قلب', 'أرى أو ما شابهه', 'متعديًا'],
          correct: 0,
        },
        {
          title: 'وجه الشبه بين المفعولين',
          kind: 'mcq',
          prompt: 'What do the مفعولان of a فعل قلب share with the second and third مفعولان of a فعل like أَرَى?',
          options: ['Both were originally مبتدأ وخبر', 'Neither can ever be deleted', 'Neither can precede the فعل', 'There is no similarity between them'],
          correct: 0,
        },
        {
          title: 'تركيب: بمعنى التحويل أم لا؟',
          kind: 'tarkeeb',
          instruction: 'Classify: is the فعل here بمعنى التحويل (مفعولان) or not?',
          source: 'واتخذ الله إبراهيم خليلا / إني تركت ملة قوم / ثم يُرد إلى ربه / وجعل لكم السمع والأبصار',
          words: ['اتخذ', 'تركت', 'يُرد', 'جعل'],
          labels: ['بمعنى التحويل', 'خارج معنى التحويل', 'خارج معنى التحويل', 'خارج معنى التحويل'],
          distractors: ['فعل لازم'],
        },
        {
          title: 'تركيب: قائمة أفعال التحويل',
          kind: 'tarkeeb',
          instruction: 'Classify: is it one of أفعال التحويل or not?',
          source: 'صيّر / رد / درى / علم',
          words: ['صيّر', 'رد', 'درى', 'علم'],
          labels: ['من أفعال التحويل', 'من أفعال التحويل', 'ليس من أفعال التحويل', 'ليس من أفعال التحويل'],
          distractors: ['التعليق'],
        },
        {
          title: 'تركيب: كم مفعولاً؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل by its number of مفاعيل in the given context.',
          source: 'واتخذ الله إبراهيم خليلا / يريهم الله أعمالهم حسرات / إني تركت ملة قوم',
          words: ['اتخذ', 'يريهم', 'تركت'],
          labels: ['مفعولان', 'ثلاثة مفاعيل', 'مفعول واحد'],
          distractors: ['لا مفعول له'],
        },
        {
          title: 'تركيب: ما الذي يسد مسد المفعولين؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: اسم مؤول or جملة?',
          source: 'واعلموا أن الله مع المتقين / والله يشهد إن المنافقين لكاذبون',
          words: ['أن الله مع المتقين', 'إن المنافقين لكاذبون'],
          labels: ['اسم مؤول', 'جملة'],
          distractors: ['حال'],
        },
        {
          title: 'تركيب: أفعال مشتركة',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: أفعال الظن, أفعال التحويل, or both?',
          source: 'جعل / وهب / زعم / صيّر',
          words: ['جعل', 'وهب', 'زعم', 'صيّر'],
          labels: ['كلتيهما', 'كلتيهما', 'الظن فقط', 'التحويل فقط'],
          distractors: ['اليقين فقط'],
        },
        {
          title: 'تركيب: فعل قلب أم فعل تحويل؟',
          kind: 'tarkeeb',
          instruction: 'Classify: is the فعل here فعل قلب or فعل تحويل?',
          source: 'يريهم الله أعمالهم حسرات / واتخذ الله إبراهيم خليلا',
          words: ['يريهم', 'اتخذ'],
          labels: ['فعل قلب', 'فعل تحويل'],
          distractors: ['فعل جارحة'],
        },
      ],
    },

    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'التعليق والإلغاء',
      subtitle: 'Suspension and Cancellation — how a قلب فعل loses its لفظي government',
      concepts: [
        {
          heading: 'التعليق: العمل محلاً لا لفظاً',
          body: `When a <bdi>جُمْلَة</bdi> stands in the place of the two مفعولين of a فعل قلب, the فعل still operates on it <bdi>مَحَلًّا</bdi> (in grammatical position) but not <bdi>لَفْظًا</bdi> (in wording) — this suspension of the wording-level operation is called <bdi>التَّعْلِيق</bdi>. The جملة itself is then called a <bdi>جُمْلَةٌ مُعَلَّقٌ عَنْهَا الْعَمَل</bdi> (a جملة from which the operation is suspended).`,
          sample: `التعليق — الفعل يعمل محلاً لا لفظًا في الجملة بعده<br>جملة معلَّق عنها العمل — الجملة التي عُلِّق عنها عمل الفعل`,
          exercise: {
            prompt: `A فعل قلب's مفعولان are replaced by a whole جملة, and التعليق applies. Does the فعل still govern that جملة at all?`,
            kind: 'mcq',
            options: ['نعم، محلاً لا لفظًا', 'لا، لا يعمل فيها بتاتًا', 'نعم، لفظًا ومحلاً معًا', 'لا يُعرف حتى يُعرب الفعل'],
            correct: 0,
          },
        },
        {
          heading: 'ما يقبل التعليق من الأفعال',
          body: `التعليق isn't limited to أفعال القلوب. It's also accepted by every فعل resembling them — any فعل indicating <bdi>إِخْبَار</bdi> (informing) or <bdi>اسْتِفْهَام</bdi> (asking), as in <bdi>﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾</bdi> and <bdi>﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾</bdi>. Even a فعل that normally takes only ONE مفعول can be معلَّق, so long as the جملة after it opens with استفهام: <bdi>﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾</bdi>.`,
          sample: `يبلوكم أيكم أحسن عملا — فعل إخبار يقبل التعليق<br>سلهم أيهم بذلك زعيم — فعل استفهام يقبل التعليق<br>فلينظر أيها أزكى طعاما — فعل بمفعول واحد يُعلَّق لأن الجملة استفهامية`,
          exercise: {
            prompt: `يَنْظُرُ normally takes only one مفعول, yet ﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾ shows it suspended (معلَّق) before a whole جملة. What licenses treating a single-مفعول فعل this way؟`,
            kind: 'mcq',
            options: ['That the جملة after it opens with استفهام', 'That ينظر has permanently become one of أفعال القلوب', 'That the جملة after it is a منسوخة جملة اسمية', "Nothing justifies that — it's an anomalous exception"],
            correct: 0,
          },
        },
        {
          heading: 'المعلِّقات السبع',
          body: `Seven items are known to suspend a فعل قلب's لفظي operation (<bdi>الْمُعَلِّقَات</bdi>): (1) <bdi>إِنْ</bdi> النافية: ﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾ (2) <bdi>مَا</bdi> النافية: ﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ﴾ (3) <bdi>لَامُ الِابْتِدَاء</bdi>: ﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ﴾ (4) <bdi>اللَّامُ الْمُزَحْلَقَة</bdi>: ﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾ (5) <bdi>لَعَلَّ</bdi>: ﴿وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ﴾ (6) حرف/اسم <bdi>الِاسْتِفْهَام</bdi>: ﴿لَنَبْلُوَنَّ أَأَشْكُرُ أَمْ أَكْفُرُ﴾، ﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ (7) <bdi>لَامُ جَوَابِ الْقَسَم</bdi>: وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي.`,
          sample: `المعلقات السبع — إن النافية، ما النافية، لام الابتداء، اللام المزحلقة، لعل، الاستفهام، لام جواب القسم`,
          exercise: {
            prompt: `In ﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾, which معلِّق suspends نَعْلَمُ's لفظي operation؟`,
            kind: 'mcq',
            options: ['اللام المزحلقة', 'إن النافية', 'لعل', 'لام جواب القسم'],
            correct: 0,
          },
        },
        {
          heading: 'لماذا لا يعمل الفعل فيما له صدر الكلام',
          body: `In ﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾, <bdi>أَيَّ مُنْقَلَبٍ</bdi> looks like it could be a <bdi>مَعْمُول</bdi> of <bdi>سَيَعْلَمُ</bdi> — but it isn't. <bdi>الِاسْتِفْهَام</bdi> has <bdi>صَدْرُ الْكَلَام</bdi> (the right to open its own sentence), so nothing before it may govern it; it is <bdi>مَنْصُوب</bdi> instead by the فعل that comes AFTER it, <bdi>يَنْقَلِبُونَ</bdi>.`,
          sample: `أي منقلب — منصوب بينقلبون بعده، لا بسيعلم قبله، لأن للاستفهام صدر الكلام`,
          exercise: {
            prompt: `أَيَّ مُنْقَلَبٍ in ﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ is منصوب by which فعل؟`,
            kind: 'mcq',
            options: ['ينقلبون، الفعل بعده', 'سيعلم، الفعل قبله', 'كلا الفعلين معًا', 'لا ناصب له، فهو مرفوع'],
            correct: 0,
          },
        },
        {
          heading: 'الإلغاء: إعمال أم إلغاء؟',
          body: `<bdi>الْإِلْغَاء</bdi> cancels a فعل قلب's operation both <bdi>لَفْظًا</bdi> AND <bdi>مَحَلًّا</bdi> — unlike التعليق, which only suspends the لفظي side. Between the two, <bdi>الْإِعْمَال</bdi> (letting the فعل operate) is preferred when the فعل sits BETWEEN its مفعولين: <bdi>مُحَمَّدًا عَلِمْتُ صَادِقًا</bdi>. الإلغاء is preferred when the فعل comes AFTER its مفاعيل: <bdi>مُحَمَّدٌ صَادِقٌ عَلِمْتُ</bdi>.`,
          sample: `محمداً علمتُ صادقاً — الإعمال مفضَّل (الفعل بين مفعوليه)<br>محمدٌ صادقٌ علمتُ — الإلغاء مفضَّل (الفعل بعد مفعوليه)`,
          exercise: {
            prompt: `مُحَمَّدٌ صَادِقٌ عَلِمْتُ places عَلِمْتُ AFTER both مفعولين. Which is preferred here, الإعمال or الإلغاء؟`,
            kind: 'mcq',
            options: ['الإلغاء', 'الإعمال', 'التعليق', 'كلاهما ممتنع'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the definition of التعليق?',
          options: ["Suspending the فعل's operation لفظًا but not محلاً, because a معلِّق has entered", "Cancelling the فعل's operation both لفظًا and محلاً", 'Deleting both مفعولي الفعل together', 'Converting the فعل to المبني للمجهول'],
          correct: 0,
        },
        {
          q: 'A جملة from which a فعل\'s operation is suspended is called:',
          options: ['جملة معلَّق عنها العمل', 'جملة مسدودة', 'جملة ملغاة', 'جملة منسوخة'],
          correct: 0,
        },
        {
          q: 'How many المعلِّقات were mentioned?',
          options: ['سبعة', 'ستة', 'ثمانية', 'خمسة'],
          correct: 0,
        },
        {
          q: '﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ — what makes أَيَّ مُنْقَلَبٍ منصوب?',
          options: ['بينقلبون، الفعل بعده', 'بسيعلم، الفعل قبله', 'بالذين، اسم الموصول', 'لا ناصب له'],
          correct: 0,
        },
        {
          q: 'What is the definition of الإلغاء?',
          options: ['إبطال عمل الفعل لفظًا ومحلاً معًا', 'تعليق عمل الفعل لفظًا فقط', 'حذف الفعل من الجملة', 'تقديم المفعول على الفاعل'],
          correct: 0,
        },
        {
          q: 'مُحَمَّدًا عَلِمْتُ صَادِقًا — which of the two is preferred here?',
          options: ['الإعمال', 'الإلغاء', 'التعليق', 'لا شيء منهما'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'ماذا يبطل التعليق؟',
          kind: 'mcq',
          prompt: 'التعليق suspends the operation of the فعل:',
          options: ['لفظًا فقط، لا محلاً', 'محلاً فقط، لا لفظًا', 'لفظًا ومحلاً معًا', 'لا يبطل شيئًا'],
          correct: 0,
        },
        {
          title: 'أفعال شبيهة بأفعال القلوب',
          kind: 'mcq',
          prompt: 'أفعال الإخبار والاستفهام that resemble أفعال القلوب:',
          options: ['تقبل التعليق مثلها', 'لا تقبل التعليق أبدًا', 'لا تكون إلا لازمة', 'لا تقبل إلا الإلغاء'],
          correct: 0,
        },
        {
          title: 'سلهم أيهم بذلك زعيم',
          kind: 'mcq',
          prompt: '﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾ — سَلْ here is a فعل:',
          options: ['استفهام يقبل التعليق', 'قلب من أفعال اليقين', 'تحويل', 'لازم لا يتعدى'],
          correct: 0,
        },
        {
          title: 'فلينظر أيها أزكى طعاما',
          kind: 'mcq',
          prompt: '﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾ — how is يَنْظُرْ عُلِّق even though it takes only one مفعول?',
          options: ['Because the جملة after it is استفهامية', "Because it's actually a فعل قلب", "Because it's a فعل تحويل", 'Because what follows is a منسوخة جملة اسمية'],
          correct: 0,
        },
        {
          title: 'وتظنون إن لبثتم',
          kind: 'mcq',
          prompt: '﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾ — the معلِّق here is:',
          options: ['إن النافية', 'ما النافية', 'لام الابتداء', 'لعل'],
          correct: 0,
        },
        {
          title: 'لقد علمت ما أنزل هؤلاء',
          kind: 'mcq',
          prompt: '﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ﴾ — the معلِّق here is:',
          options: ['ما النافية', 'إن النافية', 'اللام المزحلقة', 'لام جواب القسم'],
          correct: 0,
        },
        {
          title: 'ولقد علموا لمن اشتراه',
          kind: 'mcq',
          prompt: '﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ﴾ — the معلِّق here is:',
          options: ['لام الابتداء', 'اللام المزحلقة', 'لعل', 'الاستفهام'],
          correct: 0,
        },
        {
          title: 'قد نعلم إنه ليحزنك',
          kind: 'mcq',
          prompt: '﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾ — the معلِّق here is:',
          options: ['اللام المزحلقة', 'لام الابتداء', 'ما النافية', 'لام جواب القسم'],
          correct: 0,
        },
        {
          title: 'وإن أدري لعله فتنة',
          kind: 'mcq',
          prompt: '﴿وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ﴾ — the معلِّق here is:',
          options: ['لعل', 'إن النافية', 'الاستفهام', 'لام الابتداء'],
          correct: 0,
        },
        {
          title: 'لنبلونّ أأشكر أم أكفر',
          kind: 'mcq',
          prompt: '﴿لَنَبْلُوَنَّ أَأَشْكُرُ أَمْ أَكْفُرُ﴾ — the معلِّق here is:',
          options: ['حرف الاستفهام', 'لعل', 'ما النافية', 'لام جواب القسم'],
          correct: 0,
        },
        {
          title: 'ولقد علمت لتأتينّ منيتي',
          kind: 'mcq',
          prompt: 'وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي — the معلِّق here is:',
          options: ['لام جواب القسم', 'لام الابتداء', 'اللام المزحلقة', 'ما النافية'],
          correct: 0,
        },
        {
          title: 'صدر الكلام',
          kind: 'mcq',
          prompt: 'Why is أَيَّ مُنْقَلَبٍ not parsed as a معمول of سَيَعْلَمُ?',
          options: ['Because الاستفهام has صدر الكلام', 'Because سيعلم is a فعل لازم', 'Because أي منقلب is مبني, not معرب', 'Because سيعلم is a فعل أمر'],
          correct: 0,
        },
        {
          title: 'الإلغاء يخالف التعليق',
          kind: 'mcq',
          prompt: 'الإلغاء differs from التعليق in that it:',
          options: ['It cancels the عمل both لفظًا and محلاً together, not just لفظًا', 'It does not cancel the عمل at all', 'It is specific to أفعال التحويل only', 'It only enters upon الجملة الاسمية'],
          correct: 0,
        },
        {
          title: 'محمدٌ صادقٌ علمتُ',
          kind: 'mcq',
          prompt: 'مُحَمَّدٌ صَادِقٌ عَلِمْتُ — why is الإلغاء preferred here?',
          options: ['Because the فعل comes after both مفعولين, not between them', 'Because the فعل comes before both مفعولين', 'Because the فعل is مبني للمجهول', 'Because the جملة is استفهامية'],
          correct: 0,
        },
        {
          title: 'محمداً علمتُ صادقاً',
          kind: 'mcq',
          prompt: 'مُحَمَّدًا عَلِمْتُ صَادِقًا — why is الإعمال preferred here?',
          options: ['Because the فعل falls between its two مفعولين', 'Because the فعل falls after its two مفعولين', 'Because the جملة is معلَّقة', 'Because the فعل is a فعل تحويل'],
          correct: 0,
        },
        {
          title: 'تعليق فعل بمفعول واحد',
          kind: 'mcq',
          prompt: 'Can a single-مفعول فعل accept التعليق without being one of أفعال القلوب at all?',
          options: ['Yes, if the جملة after it opens with استفهام', 'No, التعليق is specific to أفعال المفعولين only', 'Yes, but on condition that the فعل be an أمر', 'It never accepts it under any circumstance'],
          correct: 0,
        },
        {
          title: 'ما الأفعال التي تقبل التعليق؟',
          kind: 'mcq',
          prompt: 'Which أفعال accept التعليق alongside أفعال القلوب?',
          options: ['كل فعل يدل على إخبار أو استفهام', 'كل فعل لازم', 'كل فعل تحويل فقط', 'كل فعل ماضٍ'],
          correct: 0,
        },
        {
          title: 'التعليق والإلغاء خاصان بماذا؟',
          kind: 'mcq',
          prompt: 'التعليق and الإلغاء are both specific to:',
          options: ['أفعال القلوب وما شابهها', 'الأفعال اللازمة فقط', 'أفعال الأمر فقط', 'الحروف الناسخة'],
          correct: 0,
        },
        {
          title: 'تركيب: المعلِّقات (١)',
          kind: 'tarkeeb',
          instruction: 'Identify the معلِّق in each تركيب.',
          source: '﴿وتظنون إن لبثتم إلا قليلا﴾ / ﴿قد نعلم إنه ليحزنك الذي يقولون﴾ / ﴿وإن أدري لعله فتنة﴾ / ﴿لنبلونّ أأشكر أم أكفر﴾',
          words: ['إن', 'ليحزنك', 'لعله', 'أأشكر'],
          labels: ['إن النافية', 'اللام المزحلقة', 'لعل', 'حرف الاستفهام'],
          distractors: ['ما النافية'],
        },
        {
          title: 'تركيب: المعلِّقات (٢)',
          kind: 'tarkeeb',
          instruction: 'Identify the معلِّق in each تركيب.',
          source: '﴿لقد علمت ما أنزل هؤلاء إلا رب السماوات والأرض﴾ / ﴿ولقد علموا لمن اشتراه ما له في الآخرة من خلاق﴾ / ولقد علمتُ لتأتينّ منيتي',
          words: ['ما', 'لمن', 'لتأتينّ'],
          labels: ['ما النافية', 'لام الابتداء', 'لام جواب القسم'],
          distractors: ['اللام المزحلقة'],
        },
        {
          title: 'تركيب: أفعال تقبل التعليق',
          kind: 'tarkeeb',
          instruction: 'Classify: an original فعل قلب, or a resembling فعل (إخبار/استفهام)?',
          source: 'يبلوكم أيكم أحسن عملا / سلهم أيهم بذلك زعيم / علمتُ أن الحق ظاهرٌ',
          words: ['يبلوكم', 'سلهم', 'علمتُ'],
          labels: ['فعل إخبار مشابه', 'فعل استفهام مشابه', 'فعل قلب أصلي'],
          distractors: ['فعل تحويل'],
        },
        {
          title: 'تركيب: الإعمال أم الإلغاء؟',
          kind: 'tarkeeb',
          instruction: 'Classify the إعراب of "محمد" in each تركيب: أعمل الفعل or أُلغي?',
          source: 'محمداً علمتُ صادقاً / محمدٌ صادقٌ علمتُ',
          words: ['محمداً', 'محمدٌ'],
          labels: ['الإعمال', 'الإلغاء'],
          distractors: ['التعليق'],
        },
        {
          title: 'تركيب: تعليق أم إلغاء؟',
          kind: 'tarkeeb',
          instruction: 'Classify each case: did تعليق or إلغاء occur?',
          source: '﴿وتظنون إن لبثتم إلا قليلا﴾ / محمدٌ صادقٌ علمتُ',
          words: ['تظنون', 'علمتُ'],
          labels: ['تعليق', 'إلغاء'],
          distractors: ['إعمال'],
        },
        {
          title: 'تركيب: مراجعة عامة',
          kind: 'tarkeeb',
          instruction: 'Classify each example: تعليق, إعمال, إلغاء, or له صدر الكلام?',
          source: '﴿سلهم أيهم بذلك زعيم﴾ / محمداً علمتُ صادقاً / محمدٌ صادقٌ علمتُ / ﴿وسيعلم الذين ظلموا أي منقلب ينقلبون﴾',
          words: ['سلهم', 'صادقاً', 'صادقٌ', 'منقلب'],
          labels: ['تعليق', 'إعمال', 'إلغاء', 'له صدر الكلام'],
          distractors: ['اختصار'],
        },
      ],
    },
  ],
};
