// Module 04 — حروف الجر (The جار Letters)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__2 الْحَرْفِ__1 الْحَرْفِ الْعَامِلِ__1 الحرف الجر.apkg,
// 129 notes) prepared for this conversion. Definitions and examples are kept
// faithful to the source notes. Concept bodies are short by design (a
// sentence or two, not teaching prose); quiz/bank question text is English
// with Arabic grammatical terms left in Arabic.
//
// The source deck covers حروف الجر (§1 of الحرف العامل, itself §2 of
// الحرف, itself §2 of العامل وغير العامل) — its three أضرب (أصلي، شبيه
// بالزائد، زائد), the thirteen أصلية حروف one at a time, أحرف القسم، مذ
// ومنذ، حذف حرف الجر، and تعدد المعمول/التضمين. The other حروف العاملة
// (إلى الفعل) and حروف غير العاملة are covered in later modules.

export default {
  id: '04',
  title: 'حروف الجر',
  heading: 'العامل وغير العامل',
  subheading: 'الحرف العامل',
  blurb: 'The richest class of عامل حروف: حروف الجر\'s three أضرب (أصلي، شبيه بالزائد، زائد), the meaning and وظائف of each of the thirteen أصلية حروف, أحرف القسم, مذ ومنذ, and when a حرف الجر is omitted or added only for emphasis.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'أضرب حروف الجر',
      subtitle: 'Foundations — عامل حروف that govern الاسم and الفعل, and the three أضرب of حروف الجر',
      concepts: [
        {
          heading: 'الحروف العاملة: في الاسم وفي الفعل',
          body: `<bdi>الْحُرُوفُ الْعَامِلَة</bdi> split into two types by what they govern: (1) حروف that عمل في <bdi>الِاسْم</bdi> (2) حروف that عمل في <bdi>الْفِعْل</bdi>. The first type further divides into four categories by what it does to its اسم: (1) حروف that put a single اسم in <bdi>جَرّ</bdi> — <bdi>حُرُوفُ الْجَرّ</bdi> (2) a حرف that puts a single اسم in <bdi>نَصْب</bdi> — <bdi>إِلَّا</bdi> (3) حروف that put the اسم in نصب and the <bdi>خَبَر</bdi> in <bdi>رَفْع</bdi> — <bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِالْفِعْل</bdi> (and <bdi>لَا لِنَفْيِ الْجِنْس</bdi>) (4) حروف that put the اسم in رفع and the خبر in نصب — <bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِلَيْس</bdi>. This module is built entirely on the first of these four — حروف الجر.`,
          sample: `العاملة — تعمل في الاسم أو تعمل في الفعل<br>تعمل في الاسم — حروف الجر، إلا، المشبهة بالفعل، المشبهة بليس`,
          exercise: {
            prompt: `Among the four categories of حروف تعمل في الاسم, which one is this whole module built around؟`,
            kind: 'mcq',
            options: ['حروف الجر', 'إلا', 'الحروف المشبهة بالفعل', 'الحروف المشبهة بليس'],
            correct: 0,
          },
        },
        {
          heading: 'أضرب حروف الجر الثلاثة',
          body: `حروف الجر themselves fall into three <bdi>أَضْرُب</bdi>: (1) <bdi>حَرْفُ الْجَرِّ الْأَصْلِيّ</bdi> — it carries a specific meaning (<bdi>مَعْنًى خَاصّ</bdi>), and together with its <bdi>مَجْرُور</bdi> it occupies a <bdi>مَحَلّ</bdi> as the <bdi>مَعْمُول</bdi> of a <bdi>فِعْل</bdi> or of <bdi>شِبْهِ الْفِعْل</bdi> (2) <bdi>حَرْفُ الْجَرِّ الشَّبِيهُ بِالزَّائِد</bdi> — it also carries a specific meaning, but together with its مجرور it is not the معمول of a فعل or شبه الفعل (3) <bdi>حَرْفُ الْجَرِّ الزَّائِد</bdi> — also called <bdi>حَرْفُ صِلَة</bdi> — it carries no meaning beyond <bdi>تَأْكِيد</bdi> (emphasis), and like الشبيه بالزائد, it is not a معمول either.`,
          sample: `الأصلي — له معنى خاص، وهو معمول لفعل أو شبه فعل<br>الشبيه بالزائد — له معنى خاص، لكنه ليس معمولا<br>الزائد (حرف صلة) — لا معنى له إلا التوكيد، وليس معمولا`,
          exercise: {
            prompt: `What distinguishes حرف الجر الأصلي from the other two أضرب؟`,
            kind: 'mcq',
            options: ['Its جار ومجرور is a معمول occupying a محل governed by a فعل or شبه الفعل', 'It conveys no meaning at all', 'Its مجرور must always be a ضمير', 'It never takes a مجرور'],
            correct: 0,
          },
        },
        {
          heading: 'حرف صلة، والتعلّق',
          body: `<bdi>حَرْفُ صِلَة</bdi> is the alternate name for حرف الجر الزائد. Because حرف الجر الأصلي's جار ومجرور is a معمول — it occupies a محل governed by a فعل or شبه الفعل — its meaning must always relate back to that governing word; this relationship is called <bdi>التَّعَلُّق</bdi>. الشبيه بالزائد and الزائد need no تعلق at all, since neither is ever a معمول.`,
          sample: `حرف صلة = حرف الجر الزائد<br>التعلق — خاص بالأصلي، لأنه معمول لفعل أو شبه فعل`,
          exercise: {
            prompt: `Why must the جار والمجرور of a حرف الجر الأصلي "attach" (تعلّق) to something؟`,
            kind: 'mcq',
            options: ['Because it is a معمول occupying a محل governed by a فعل or شبه الفعل, so its meaning always relates back to that governor', 'Because Arabic grammar requires every حرف to precede a فعل', 'Because التعلق only applies to الحروف الزائدة', "It doesn't need to attach — attachment is optional"],
            correct: 0,
          },
        },
        {
          heading: 'حروف الجر الأصلية الثلاثة عشر',
          body: `The thirteen <bdi>حُرُوفُ الْجَرِّ الْأَصْلِيَّة</bdi> are: <bdi>الْبَاء، مِنْ، إِلَى، عَنْ، عَلَى، اللَّام، فِي، الْكَاف، حَتَّى، وَاوُ الْقَسَم، تَاءُ الْقَسَم، مُذْ، مُنْذُ</bdi>. Every lesson from here on works through this list, group by group.`,
          sample: `الأصلية (١٣) — الباء، من، إلى، عن، على، اللام، في، الكاف، حتى، واو القسم، تاء القسم، مذ، منذ`,
          exercise: {
            prompt: `How many حروف جر أصلية are there؟`,
            kind: 'mcq',
            options: ['ثلاثة عشر', 'أحد عشر', 'عشرة', 'خمسة عشر'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'Into how many أقسام do حروف تعمل في الاسم divide؟',
          options: ['أربعة', 'اثنان', 'ثلاثة', 'خمسة'],
          correct: 0,
        },
        {
          q: 'Which of the four categories of حروف تعمل في الاسم puts a single اسم in نصب؟',
          options: ['إلا', 'حروف الجر', 'الحروف المشبهة بالفعل', 'الحروف المشبهة بليس'],
          correct: 0,
        },
        {
          q: 'حرف الجر الأصلي is defined as a حرف that:',
          options: ['carries a معنى خاص and, with its مجرور, is a معمول of a فعل or شبه الفعل', 'carries no meaning beyond التوكيد', 'carries a معنى خاص but is never a معمول', 'only ever precedes a ضمير'],
          correct: 0,
        },
        {
          q: 'حرف الجر الشبيه بالزائد differs from حرف الجر الزائد in that it:',
          options: ['carries a specific meaning, while الزائد conveys only توكيد', 'is always a معمول, while الزائد never is', 'never takes a مجرور', 'is one of the thirteen أصلية'],
          correct: 0,
        },
        {
          q: 'What is the alternative name for حرف الجر الزائد؟',
          options: ['حرف صلة', 'حرف عطف', 'حرف تنبيه', 'حرف جواب'],
          correct: 0,
        },
        {
          q: 'How many حروف جر أصلية are there؟',
          options: ['ثلاثة عشر', 'أحد عشر', 'عشرة', 'خمسة عشر'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'أقسام العاملة',
          kind: 'mcq',
          prompt: 'What does الحرف العامل govern؟',
          options: ['الاسم or الفعل', 'الاسم only, never الفعل', 'الفعل only, never الاسم', 'Neither — عامل حروف govern nothing'],
          correct: 0,
        },
        {
          title: 'حروف تجر اسما واحدا',
          kind: 'mcq',
          prompt: 'Which category of حروف تعمل في الاسم puts a single اسم in جر؟',
          options: ['حروف الجر', 'إلا', 'الحروف المشبهة بالفعل', 'الحروف المشبهة بليس'],
          correct: 0,
        },
        {
          title: 'إلا في الاستثناء',
          kind: 'mcq',
          prompt: 'Among the four categories of حروف تعمل في الاسم, إلا puts its اسم in:',
          options: ['نصب', 'جر', 'رفع', 'لا شيء'],
          correct: 0,
        },
        {
          title: 'الحروف المشبهة بالفعل',
          kind: 'mcq',
          prompt: 'الحروف المشبهة بالفعل (and لا لنفي الجنس) put the اسم in نصب and the خبر in:',
          options: ['رفع', 'نصب', 'جر', 'لا خبر لها'],
          correct: 0,
        },
        {
          title: 'الحروف المشبهة بليس',
          kind: 'mcq',
          prompt: 'الحروف المشبهة بليس put the اسم in رفع and the خبر in:',
          options: ['نصب', 'رفع', 'جر', 'لا تعمل في الخبر'],
          correct: 0,
        },
        {
          title: 'تعريف الأصلي',
          kind: 'mcq',
          prompt: 'A حرف whose جار ومجرور occupies a محل as معمول of a فعل or شبه الفعل is called:',
          options: ['حرف الجر الأصلي', 'حرف الجر الزائد', 'حرف الجر الشبيه بالزائد', 'حرف عطف'],
          correct: 0,
        },
        {
          title: 'تعريف الشبيه بالزائد',
          kind: 'mcq',
          prompt: 'حرف الجر الشبيه بالزائد carries a specific meaning, but unlike الأصلي, its جار ومجرور:',
          options: ['is not a معمول of a فعل or شبه فعل', 'is always a معمول of a فعل', 'must be omitted', 'has no مجرور at all'],
          correct: 0,
        },
        {
          title: 'تعريف الزائد',
          kind: 'mcq',
          prompt: 'حرف الجر الزائد conveys no meaning beyond:',
          options: ['التوكيد', 'التبعيض', 'التشبيه', 'الظرفية'],
          correct: 0,
        },
        {
          title: 'حرف صلة',
          kind: 'mcq',
          prompt: 'حرف صلة is another name for:',
          options: ['حرف الجر الزائد', 'حرف الجر الأصلي', 'حرف الجر الشبيه بالزائد', 'حرف القسم'],
          correct: 0,
        },
        {
          title: 'عدد الأصلية',
          kind: 'mcq',
          prompt: 'How many حروف جر أصلية exist in total؟',
          options: ['ثلاثة عشر', 'أحد عشر', 'عشرة', 'خمسة عشر'],
          correct: 0,
        },
        {
          title: 'من الأصلية؟ (١)',
          kind: 'mcq',
          prompt: 'Which of these is one of the thirteen حروف الجر الأصلية؟',
          options: ['اللام', 'لن', 'قد', 'لو'],
          correct: 0,
        },
        {
          title: 'من الأصلية؟ (٢)',
          kind: 'mcq',
          prompt: 'Which of these is NOT one of the thirteen حروف الجر الأصلية؟',
          options: ['هل', 'مذ', 'منذ', 'حتى'],
          correct: 0,
        },
        {
          title: 'التعلق',
          kind: 'mcq',
          prompt: "Why must a حرف الجر الأصلي's جار ومجرور تعلّق (attach) to something؟",
          options: ['Because it is a معمول occupying a محل governed by a فعل or شبه الفعل', 'Because every حرف must precede a فعل', 'Because التعلق is only for حروف زائدة', 'There is no grammatical reason'],
          correct: 0,
        },
        {
          title: 'من يحتاج تعلقا؟',
          kind: 'mcq',
          prompt: 'التعلق (needing to attach to a governing فعل or شبه الفعل) applies to which ضرب؟',
          options: ['حرف الجر الأصلي فقط', 'الأضرب الثلاثة كلها', 'حرف الجر الزائد فقط', 'لا شيء منها'],
          correct: 0,
        },
        {
          title: 'محور الوحدة',
          kind: 'mcq',
          prompt: 'This module is built around which one of the four categories of حروف تعمل في الاسم؟',
          options: ['حروف الجر', 'إلا', 'الحروف المشبهة بالفعل', 'الحروف المشبهة بليس'],
          correct: 0,
        },
        {
          title: 'الأضرب الثلاثة',
          kind: 'mcq',
          prompt: 'حروف الجر themselves divide, by their عمل, into:',
          options: ['أصلي، شبيه بالزائد، وزائد', 'قياسي وسماعي', 'مذكر ومؤنث', 'مفرد ومركب'],
          correct: 0,
        },
        {
          title: 'مثال حرف مشبه بالفعل',
          kind: 'mcq',
          prompt: 'إنَّ, as an example of الحروف المشبهة بالفعل, puts its اسم in نصب and its خبر in:',
          options: ['رفع', 'نصب', 'جر', 'لا تعمل'],
          correct: 0,
        },
        {
          title: 'مثال حرف مشبه بليس',
          kind: 'mcq',
          prompt: 'ليس, as an example of الحروف المشبهة بليس, puts its اسم in رفع and its خبر in:',
          options: ['نصب', 'رفع', 'جر', 'لا تعمل'],
          correct: 0,
        },
        {
          title: 'الفرق الجوهري في المعمولية',
          kind: 'mcq',
          prompt: 'What single fact makes حرف الجر الأصلي different in kind from the other two أضرب — not just in how much meaning it carries؟',
          options: ['Only it is ever a معمول of a فعل or شبه فعل', 'Only it can be omitted', 'Only it takes a مجرور', 'Only it is one of the thirteen أصلية'],
          correct: 0,
        },
        {
          title: 'وجه الشبه بين الشبيه بالزائد والزائد',
          kind: 'mcq',
          prompt: 'What do حرف الجر الشبيه بالزائد and حرف الجر الزائد have in common؟',
          options: ['Neither is a معمول of a فعل or شبه فعل', 'Both convey no meaning at all', 'Both are among the thirteen أصلية', 'Both require تعلق'],
          correct: 0,
        },
        {
          title: 'تركيب: أقسام الحروف العاملة في الاسم',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف by which of the four categories of حروف تعمل في الاسم it belongs to.',
          source: 'الباء / إلا / إنَّ / ليس',
          words: ['الباء', 'إلا', 'إنَّ', 'ليس'],
          labels: ['حروف الجر', 'إلا', 'الحروف المشبهة بالفعل', 'الحروف المشبهة بليس'],
          distractors: ['حروف تعمل في الفعل'],
        },
        {
          title: 'تركيب: من حروف الجر الأصلية؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف: is it one of the thirteen حروف الجر الأصلية?',
          source: 'الكاف / حتى / لن / هل',
          words: ['الكاف', 'حتى', 'لن', 'هل'],
          labels: ['من الأصلية', 'من الأصلية', 'ليست حرف جر', 'ليست حرف جر'],
          distractors: ['من الزائدة'],
        },
        {
          title: 'تركيب: تعريف كل ضرب',
          kind: 'tarkeeb',
          instruction: 'Match each ضرب of حرف الجر to its defining trait.',
          source: 'حرف الجر الأصلي / حرف الجر الشبيه بالزائد / حرف الجر الزائد',
          words: ['حرف الجر الأصلي', 'حرف الجر الشبيه بالزائد', 'حرف الجر الزائد'],
          labels: ['معمول لفعل أو شبه فعل، وله معنى خاص', 'غير معمول، لكن له معنى خاص', 'غير معمول، ولا معنى له سوى التوكيد'],
          distractors: ['حرف عطف'],
        },
        {
          title: 'تركيب: عمل كل قسم في الاسم',
          kind: 'tarkeeb',
          instruction: 'Classify what each category of حروف تعمل في الاسم does to its اسم.',
          source: 'حروف الجر / إلا / الحروف المشبهة بالفعل / الحروف المشبهة بليس',
          words: ['حروف الجر', 'إلا', 'الحروف المشبهة بالفعل', 'الحروف المشبهة بليس'],
          labels: ['جر الاسم', 'نصب الاسم', 'نصب الاسم ورفع الخبر', 'رفع الاسم ونصب الخبر'],
          distractors: ['جزم الفعل'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'الباء ومِن',
      subtitle: 'The Two Most Frequent حروف — معنى ووظائف الباء ومِن across the Quran',
      concepts: [
        {
          heading: 'الباء: معناها الأصلي ووظائفها',
          body: `The core meaning of <bdi>الْبَاء</bdi> is <bdi>الْإِلْصَاق</bdi> — attachment, the joining of one thing to another. With its مجرور it can take on nine different وظائف (as a <bdi>شِبْهُ جُمْلَة</bdi>): (1) <bdi>الْمَفْعُولُ الْمُطْلَق</bdi> (2) <bdi>الْمَفْعُولُ بِهِ</bdi> (3) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (4) <bdi>الْمَفْعُولُ لَهُ</bdi> (5) <bdi>الْمَفْعُولُ مَعَهُ</bdi> (6) <bdi>الْحَال</bdi> (7) <bdi>التَّمْيِيز</bdi> (8) <bdi>الْآلَة</bdi> (9) <bdi>الْعِوَض</bdi>.`,
          sample: `الإلصاق — attachment<br>وظائف الباء التسع — المطلق، به، فيه، له، معه، الحال، التمييز، الآلة، العوض`,
          exercise: {
            prompt: `الإلصاق (attachment/adhesion) is the core meaning of which حرف جر؟`,
            kind: 'mcq',
            options: ['الباء', 'من', 'في', 'اللام'],
            correct: 0,
          },
        },
        {
          heading: 'الباء: أمثلة من القرآن',
          body: `A few of الباء's nine وظائف, worked through: in <bdi>﴿خُذِ الْكِتَابَ بِقُوَّةٍ﴾</bdi>, بقوة is <bdi>الْمَفْعُولُ الْمُطْلَق</bdi> — "take it with a strong taking". In <bdi>﴿فَلَمَّا ذَهَبُوا بِهِ﴾</bdi>, به is <bdi>الْمَفْعُولُ بِهِ</bdi> (<bdi>غَيْرُ صَرِيح</bdi>). In <bdi>﴿وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ﴾</bdi>, ببدر is <bdi>الْمَفْعُولُ فِيهِ</bdi> — <bdi>لِلْمَكَان</bdi>. In <bdi>﴿ادْخُلُوهَا بِسَلَامٍ آمِنِينَ﴾</bdi>, بسلام is <bdi>الْحَال</bdi> — "enter it in a state of peace".`,
          sample: `بقوة — المفعول المطلق<br>به — المفعول به<br>ببدر — المفعول فيه (مكان)<br>بسلام — الحال`,
          exercise: {
            prompt: `In ﴿خذ الكتاب بقوة﴾, بقوة functions as:`,
            kind: 'mcq',
            options: ['المفعول المطلق', 'المفعول به', 'الحال', 'التمييز'],
            correct: 0,
          },
        },
        {
          heading: 'مِن: معناها الأصلي ووظائفها',
          body: `The core meaning of <bdi>مِنْ</bdi> is <bdi>ابْتِدَاءُ الْغَايَة</bdi> — the starting point of an extent. With its مجرور it can take six of the same وظائف الباء takes: (1) <bdi>الْمَفْعُولُ بِهِ</bdi> (2) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (3) <bdi>الْمَفْعُولُ لَهُ</bdi> (4) <bdi>التَّمْيِيز</bdi> (5) <bdi>الْعِوَض</bdi> (6) <bdi>الْآلَة</bdi>.`,
          sample: `ابتداء الغاية — starting point<br>وظائف من الست — به، فيه، له، التمييز، العوض، الآلة`,
          exercise: {
            prompt: `ابتداء الغاية (the starting point of an extent) is the core meaning of:`,
            kind: 'mcq',
            options: ['مِن', 'إلى', 'عن', 'حتى'],
            correct: 0,
          },
        },
        {
          heading: 'مِن: أمثلة من القرآن',
          body: `In <bdi>﴿مِنَ الْمَسْجِدِ الْحَرَامِ﴾</bdi>, من المسجد is <bdi>الْمَفْعُولُ فِيهِ</bdi> — <bdi>لِلْمَكَان</bdi>. In <bdi>﴿تَرَىٰ أَعْيُنَهُمْ تَفِيضُ مِنَ الدَّمْعِ﴾</bdi>, من الدمع is <bdi>التَّمْيِيز</bdi> — specifying what overflows. In <bdi>﴿أَرَضِيتُم بِالْحَيَاةِ الدُّنْيَا مِنَ الْآخِرَةِ﴾</bdi>, من الآخرة is <bdi>الْعِوَض</bdi> — in exchange for the Hereafter. In <bdi>﴿يَنظُرُونَ مِن طَرْفٍ خَفِيٍّ﴾</bdi>, من طرف is <bdi>الْآلَة</bdi> — the furtive glance as instrument.`,
          sample: `من المسجد — المفعول فيه (مكان)<br>من الدمع — التمييز<br>من الآخرة — العوض<br>من طرف — الآلة`,
          exercise: {
            prompt: `In ﴿ترى أعينهم تفيض من الدمع﴾, من الدمع functions as:`,
            kind: 'mcq',
            options: ['التمييز', 'المفعول به', 'الحال', 'المفعول المطلق'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the core meaning of الباء؟',
          options: ['الإلصاق', 'ابتداء الغاية', 'انتهاء الغاية', 'المجاوزة'],
          correct: 0,
        },
        {
          q: 'In ﴿ولقد نصركم الله ببدر﴾, what is the function of الباء with its مجرور؟',
          options: ['المفعول فيه (مكان)', 'المفعول به', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          q: 'In ﴿يكتبون الكتاب بأيديهم﴾, بأيديهم is:',
          options: ['الآلة', 'العوض', 'الحال', 'المفعول له'],
          correct: 0,
        },
        {
          q: 'What is the core meaning of مِن؟',
          options: ['ابتداء الغاية', 'الإلصاق', 'الاستعلاء', 'التشبيه'],
          correct: 0,
        },
        {
          q: 'In ﴿يجعلون أصابعهم في آذانهم من الصواعق﴾, من الصواعق functions as:',
          options: ['المفعول له', 'المفعول به', 'الآلة', 'العوض'],
          correct: 0,
        },
        {
          q: 'In ﴿أرضيتم بالحياة الدنيا من الآخرة﴾, من الآخرة functions as:',
          options: ['العوض', 'التمييز', 'المفعول فيه', 'الحال'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الباء والإلصاق',
          kind: 'mcq',
          prompt: 'الإلصاق means:',
          options: ['attachment/adhesion — joining one thing to another', 'the starting point of an extent', 'being above/upon', 'likening or comparison'],
          correct: 0,
        },
        {
          title: 'عدد وظائف الباء',
          kind: 'mcq',
          prompt: 'How many distinct وظائف can الباء with its مجرور take؟',
          options: ['تسعة', 'ستة', 'سبعة', 'خمسة'],
          correct: 0,
        },
        {
          title: 'الباء: المفعول به',
          kind: 'mcq',
          prompt: 'In ﴿فلما ذهبوا به﴾, به functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول المطلق', 'الحال', 'الآلة'],
          correct: 0,
        },
        {
          title: 'الباء: المفعول فيه للزمان',
          kind: 'mcq',
          prompt: 'In ﴿يسبحون له بالليل والنهار﴾, بالليل والنهار is:',
          options: ['المفعول فيه (زمان)', 'المفعول فيه (مكان)', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          title: 'الباء: المفعول له',
          kind: 'mcq',
          prompt: 'In ﴿فأهلكناهم بذنوبهم﴾, بذنوبهم functions as:',
          options: ['المفعول له', 'المفعول به', 'العوض', 'الآلة'],
          correct: 0,
        },
        {
          title: 'الباء: المفعول معه',
          kind: 'mcq',
          prompt: 'In ﴿وقد دخلوا بالكفر﴾, بالكفر functions as:',
          options: ['المفعول معه', 'الحال', 'التمييز', 'المفعول المطلق'],
          correct: 0,
        },
        {
          title: 'الباء: التمييز',
          kind: 'mcq',
          prompt: 'In يملأ الميزان بالحسنات, بالحسنات functions as:',
          options: ['التمييز', 'الحال', 'الآلة', 'العوض'],
          correct: 0,
        },
        {
          title: 'الباء: العوض',
          kind: 'mcq',
          prompt: 'In ﴿اشتروا الضلالة بالهدى﴾, بالهدى functions as:',
          options: ['العوض', 'المفعول له', 'الحال', 'الآلة'],
          correct: 0,
        },
        {
          title: 'مِن: المفعول به',
          kind: 'mcq',
          prompt: 'In أنا تائب من كل ذنب, من كل ذنب functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول فيه', 'التمييز', 'العوض'],
          correct: 0,
        },
        {
          title: 'مِن: المفعول فيه للزمان',
          kind: 'mcq',
          prompt: 'In ﴿أسس على التقوى من أول يوم﴾, من أول يوم functions as:',
          options: ['المفعول فيه (زمان)', 'المفعول فيه (مكان)', 'الحال', 'الآلة'],
          correct: 0,
        },
        {
          title: 'وظائف مِن',
          kind: 'mcq',
          prompt: 'Which of these is NOT one of the six وظائف مِن can take with its مجرور؟',
          options: ['الحال', 'المفعول به', 'التمييز', 'العوض'],
          correct: 0,
        },
        {
          title: 'وظائف الباء',
          kind: 'mcq',
          prompt: 'Which of these is NOT one of the nine وظائف الباء can take with its مجرور؟',
          options: ['انتهاء الغاية', 'المفعول المطلق', 'الحال', 'الآلة'],
          correct: 0,
        },
        {
          title: 'الباء والوظائف المشتركة مع مِن',
          kind: 'mcq',
          prompt: 'Both الباء and مِن can put their مجرور in the role of:',
          options: ['المفعول به، المفعول فيه، المفعول له، والآلة', 'التمييز فقط', 'الحال فقط', 'لا وظيفة مشتركة بينهما'],
          correct: 0,
        },
        {
          title: 'الفرق بين معنى الباء ومِن',
          kind: 'mcq',
          prompt: 'How does الإلصاق (الباء) differ from ابتداء الغاية (مِن) as core meanings؟',
          options: ['الإلصاق indicates joining between two things, while ابتداء الغاية indicates a starting point', "There's no difference between them", 'Both indicate الاستعلاء', 'Both indicate التشبيه'],
          correct: 0,
        },
        {
          title: 'مثال آخر على المفعول فيه بالباء',
          kind: 'mcq',
          prompt: 'ببدر in ﴿ولقد نصركم الله ببدر﴾ specifies:',
          options: ['المكان (place)', 'الزمان (time)', 'السبب (cause)', 'الأداة (instrument)'],
          correct: 0,
        },
        {
          title: 'مثال آخر على التمييز بمن',
          kind: 'mcq',
          prompt: 'من الدمع in ﴿ترى أعينهم تفيض من الدمع﴾ specifies:',
          options: ['what overflows (تمييز)', 'the place (مفعول فيه)', 'the instrument (آلة)', 'the exchange (عوض)'],
          correct: 0,
        },
        {
          title: 'شبه الجملة',
          kind: 'mcq',
          prompt: 'الباء (or مِن) plus its مجرور is together called:',
          options: ['شبه جملة', 'جملة اسمية', 'جملة فعلية', 'مفرد'],
          correct: 0,
        },
        {
          title: 'الآلة بالباء',
          kind: 'mcq',
          prompt: 'In ﴿يكتبون الكتاب بأيديهم﴾, what does الآلة mean here؟',
          options: ['the instrument used — their hands', 'the place written', 'the time of writing', 'the reason for writing'],
          correct: 0,
        },
        {
          title: 'تركيب: وظائف الباء (١)',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each بـ + مجرور.',
          source: '﴿خذ الكتاب بقوة﴾ / ﴿فلما ذهبوا به﴾ / ﴿ولقد نصركم الله ببدر﴾ / ﴿يسبحون له بالليل والنهار﴾',
          words: ['بقوة', 'به', 'ببدر', 'بالليل'],
          labels: ['المفعول المطلق', 'المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)'],
          distractors: ['الحال'],
        },
        {
          title: 'تركيب: وظائف الباء (٢)',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each بـ + مجرور.',
          source: '﴿فأهلكناهم بذنوبهم﴾ / ﴿وقد دخلوا بالكفر﴾ / ﴿ادخلوها بسلام آمنين﴾ / ﴿يكتبون الكتاب بأيديهم﴾',
          words: ['بذنوبهم', 'بالكفر', 'بسلام', 'بأيديهم'],
          labels: ['المفعول له', 'المفعول معه', 'الحال', 'الآلة'],
          distractors: ['التمييز'],
        },
        {
          title: 'تركيب: وظائف مِن (١)',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each مِن + مجرور.',
          source: 'أنا تائب من كل ذنب / ﴿من المسجد الحرام﴾ / ﴿أسس على التقوى من أول يوم﴾ / ﴿يجعلون أصابعهم في آذانهم من الصواعق﴾',
          words: ['من كل ذنب', 'من المسجد', 'من أول يوم', 'من الصواعق'],
          labels: ['المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول له'],
          distractors: ['الآلة'],
        },
        {
          title: 'تركيب: وظائف مِن (٢)',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each مِن + مجرور.',
          source: '﴿ترى أعينهم تفيض من الدمع﴾ / ﴿أرضيتم بالحياة الدنيا من الآخرة﴾ / ﴿ينظرون من طرف خفي﴾',
          words: ['من الدمع', 'من الآخرة', 'من طرف'],
          labels: ['التمييز', 'العوض', 'الآلة'],
          distractors: ['المفعول به'],
        },
        {
          title: 'تركيب: الباء أم مِن؟',
          kind: 'tarkeeb',
          instruction: 'Classify which حرف جر appears: الباء or مِن?',
          source: 'بقوة / من المسجد / بأيديهم / من الدمع',
          words: ['بقوة', 'من المسجد', 'بأيديهم', 'من الدمع'],
          labels: ['الباء', 'مِن', 'الباء', 'مِن'],
          distractors: ['اللام'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'إلى وعن وعلى',
      subtitle: 'Extent and Elevation — معنى ووظائف إلى، عن، and على',
      concepts: [
        {
          heading: 'إلى: معناها ووظائفها',
          body: `The core meaning of <bdi>إِلَى</bdi> is <bdi>انْتِهَاءُ الْغَايَة</bdi> — the end point of an extent, the counterpart of مِن's ابتداء الغاية. With its مجرور it takes three وظائف: (1) <bdi>الْمَفْعُولُ بِهِ</bdi> (2) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (3) <bdi>الْمَفْعُولُ مَعَهُ</bdi>. In <bdi>﴿ثُمَّ أَتِمُّوا الصِّيَامَ إِلَى اللَّيْلِ﴾</bdi>, إلى الليل is <bdi>الْمَفْعُولُ فِيهِ</bdi> — <bdi>لِلزَّمَان</bdi> — "until night". In <bdi>﴿وَلَا تَأْكُلُوا أَمْوَالَهُمْ إِلَىٰ أَمْوَالِكُمْ﴾</bdi>, إلى أموالكم is <bdi>الْمَفْعُولُ مَعَهُ</bdi> — "together with your own wealth".`,
          sample: `انتهاء الغاية — end point<br>وظائف إلى — به، فيه، معه<br>﴿أتموا الصيام إلى الليل﴾ — فيه (زمان)`,
          exercise: {
            prompt: `انتهاء الغاية (the end point of an extent) is the core meaning of:`,
            kind: 'mcq',
            options: ['إلى', 'مِن', 'عن', 'على'],
            correct: 0,
          },
        },
        {
          heading: 'عن: معناها ووظائفها، وعن الاسمية',
          body: `The core meaning of <bdi>عَنْ</bdi> is <bdi>الْمُجَاوَزَة</bdi> — passing beyond or moving away from. With its مجرور it takes four وظائف: (1) <bdi>الْمَفْعُولُ بِهِ</bdi> (2) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (3) <bdi>الْمَفْعُولُ لَهُ</bdi> (4) <bdi>الْعِوَض</bdi>, as in the ḥadīth <bdi>«حُجَّ عَنْ أَبِيكَ»</bdi> — "on behalf of your father". When عن is preceded by مِن, it stops being a حرف جر and becomes an <bdi>اسم</bdi> meaning <bdi>جَانِب</bdi> (side), as in <bdi>جِئْتُ مِنْ عَنْ يَمِينِهِ</bdi> — "I came from his right side".`,
          sample: `المجاوزة — passing beyond<br>وظائف عن — به، فيه، له، العوض<br>«حج عن أبيك» — العوض<br>من عن يمينه — عن اسم بمعنى جانب`,
          exercise: {
            prompt: `When is عن an اسم, and what does it then mean؟`,
            kind: 'mcq',
            options: ['When preceded by مِن, meaning جانب (side)', 'When preceded by على, meaning استعلاء', 'عن is always a حرف, never an اسم', 'When it ends a جملة, meaning انتهاء'],
            correct: 0,
          },
        },
        {
          heading: 'على: معناها ووظائفها',
          body: `The core meaning of <bdi>عَلَى</bdi> is <bdi>الِاسْتِعْلَاء</bdi> — being above or upon. With its مجرور it takes five وظائف: (1) <bdi>الْمَفْعُولُ بِهِ</bdi> (2) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (3) <bdi>الْمَفْعُولُ لَهُ</bdi> (4) <bdi>الْمَفْعُولُ مَعَهُ</bdi> (5) <bdi>الْحَال</bdi>. In <bdi>﴿وَدَخَلَ الْمَدِينَةَ عَلَىٰ حِينِ غَفْلَةٍ مِّنْ أَهْلِهَا﴾</bdi>, على حين غفلة is <bdi>الْمَفْعُولُ فِيهِ</bdi> — <bdi>لِلزَّمَان</bdi>. In <bdi>﴿فَمَا آمَنَ لِمُوسَىٰ إِلَّا ذُرِّيَّةٌ مِّن قَوْمِهِ عَلَىٰ خَوْفٍ مِّن فِرْعَوْنَ﴾</bdi>, على خوف is <bdi>الْحَال</bdi> — they believed while being in a state of fear.`,
          sample: `الاستعلاء — being above<br>وظائف على — به، فيه، له، معه، الحال<br>على حين غفلة — فيه (زمان)<br>على خوف — الحال`,
          exercise: {
            prompt: `الاستعلاء (being above/upon) is the core meaning of:`,
            kind: 'mcq',
            options: ['على', 'عن', 'إلى', 'حتى'],
            correct: 0,
          },
        },
        {
          heading: 'إلى وعن وعلى: مقارنة الوظائف',
          body: `إلى، عن، and على all share the ability to put their مجرور in the role of <bdi>الْمَفْعُولُ بِهِ</bdi> (<bdi>غَيْرُ صَرِيح</bdi>) and <bdi>الْمَفْعُولُ فِيهِ</bdi> (مكانا وزمانا) — but only عن and على can also mark <bdi>الْمَفْعُولُ لَهُ</bdi>, and only إلى and على can mark <bdi>الْمَفْعُولُ مَعَهُ</bdi>. الحال is unique to على among these three; العوض is unique to عن.`,
          sample: `المشترك — المفعول به والمفعول فيه<br>له — عن وعلى فقط<br>معه — إلى وعلى فقط<br>الحال — على وحدها<br>العوض — عن وحدها`,
          exercise: {
            prompt: `Which وظيفة can على mark that neither إلى nor عن can؟`,
            kind: 'mcq',
            options: ['الحال', 'المفعول به', 'المفعول فيه', 'التمييز'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the core meaning of إلى؟',
          options: ['انتهاء الغاية', 'ابتداء الغاية', 'المجاوزة', 'الاستعلاء'],
          correct: 0,
        },
        {
          q: 'In ﴿ولا تأكلوا أموالهم إلى أموالكم﴾, إلى أموالكم functions as:',
          options: ['المفعول معه', 'المفعول به', 'التمييز', 'العوض'],
          correct: 0,
        },
        {
          q: 'What is the core meaning of عن؟',
          options: ['المجاوزة', 'الاستعلاء', 'التشبيه', 'الظرفية'],
          correct: 0,
        },
        {
          q: 'In the ḥadīth «حج عن أبيك», عن أبيك functions as:',
          options: ['العوض', 'المفعول به', 'الحال', 'الآلة'],
          correct: 0,
        },
        {
          q: 'What is the core meaning of على؟',
          options: ['الاستعلاء', 'انتهاء الغاية', 'المجاوزة', 'الإلصاق'],
          correct: 0,
        },
        {
          q: 'In ﴿فما آمن لموسى إلا ذرية من قومه على خوف من فرعون﴾, على خوف functions as:',
          options: ['الحال', 'المفعول به', 'المفعول له', 'العوض'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'إلى: المفعول به',
          kind: 'mcq',
          prompt: 'In ﴿حبب إليكم الإيمان﴾, إليكم functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول فيه', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'إلى: المفعول فيه للمكان',
          kind: 'mcq',
          prompt: 'In ﴿إلى المسجد الأقصى﴾, إلى المسجد functions as:',
          options: ['المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول معه', 'الحال'],
          correct: 0,
        },
        {
          title: 'عدد وظائف إلى',
          kind: 'mcq',
          prompt: 'How many وظائف can إلى with its مجرور take؟',
          options: ['ثلاثة', 'أربعة', 'خمسة', 'ستة'],
          correct: 0,
        },
        {
          title: 'عن: المفعول به',
          kind: 'mcq',
          prompt: 'In ﴿وينهون عن المنكر﴾, عن المنكر functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول فيه', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'عن: المفعول فيه للمكان',
          kind: 'mcq',
          prompt: 'In ﴿هو يقبل التوبة عن عباده﴾, عن عباده functions as:',
          options: ['المفعول فيه (مكان)', 'المفعول به', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'عن: المفعول فيه للزمان',
          kind: 'mcq',
          prompt: 'In ﴿عما قليل ليصبحن نادمين﴾, عن قليل functions as:',
          options: ['المفعول فيه (زمان)', 'المفعول فيه (مكان)', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'عن: المفعول له',
          kind: 'mcq',
          prompt: 'In ﴿وما نحن بتاركي آلهتنا عن قولك﴾, عن قولك functions as:',
          options: ['المفعول له', 'المفعول به', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          title: 'عدد وظائف عن',
          kind: 'mcq',
          prompt: 'How many وظائف can عن with its مجرور take؟',
          options: ['أربعة', 'ثلاثة', 'خمسة', 'ستة'],
          correct: 0,
        },
        {
          title: 'على: المفعول به',
          kind: 'mcq',
          prompt: 'In ﴿أنعمت عليهم﴾, عليهم functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول فيه', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'على: المفعول فيه للمكان',
          kind: 'mcq',
          prompt: 'In ﴿وعليها وعلى الفلك تحملون﴾, على الفلك functions as:',
          options: ['المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول له', 'الحال'],
          correct: 0,
        },
        {
          title: 'على: المفعول له',
          kind: 'mcq',
          prompt: 'In ﴿سخرها لكم لتكبروا الله على ما هداكم﴾, على ما هداكم functions as:',
          options: ['المفعول له', 'المفعول به', 'الحال', 'المفعول معه'],
          correct: 0,
        },
        {
          title: 'على: المفعول معه',
          kind: 'mcq',
          prompt: 'In ﴿ويطعمون الطعام على حبه مسكينا﴾, على حبه functions as:',
          options: ['المفعول معه', 'الحال', 'المفعول له', 'العوض'],
          correct: 0,
        },
        {
          title: 'عدد وظائف على',
          kind: 'mcq',
          prompt: 'How many وظائف can على with its مجرور take؟',
          options: ['خمسة', 'أربعة', 'ثلاثة', 'ستة'],
          correct: 0,
        },
        {
          title: 'عن الاسمية',
          kind: 'mcq',
          prompt: 'جئت من عن يمينه — here عن is:',
          options: ['اسم بمعنى جانب', 'حرف جر بمعنى المجاوزة', 'فعل ماضٍ', 'ظرف زمان'],
          correct: 0,
        },
        {
          title: 'المشترك بين الثلاثة',
          kind: 'mcq',
          prompt: 'Which وظيفة do إلى، عن، and على all three share the ability to mark؟',
          options: ['المفعول به والمفعول فيه', 'الحال فقط', 'العوض فقط', 'التمييز فقط'],
          correct: 0,
        },
        {
          title: 'العوض بين عن وعلى',
          kind: 'mcq',
          prompt: 'العوض, among إلى، عن، and على, belongs uniquely to:',
          options: ['عن', 'على', 'إلى', 'لا واحد منها'],
          correct: 0,
        },
        {
          title: 'المفعول معه بين الثلاثة',
          kind: 'mcq',
          prompt: 'المفعول معه, among إلى، عن، and على, can be marked by:',
          options: ['إلى وعلى فقط', 'عن وعلى فقط', 'الثلاثة جميعا', 'إلى وحدها'],
          correct: 0,
        },
        {
          title: 'انتهاء الغاية وابتداؤها',
          kind: 'mcq',
          prompt: 'انتهاء الغاية (إلى) is the direct counterpart of the meaning of which حرف؟',
          options: ['مِن (ابتداء الغاية)', 'عن (المجاوزة)', 'على (الاستعلاء)', 'الباء (الإلصاق)'],
          correct: 0,
        },
        {
          title: 'تركيب: وظائف إلى',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each إلى + مجرور.',
          source: '﴿حبب إليكم الإيمان﴾ / ﴿إلى المسجد الأقصى﴾ / ﴿ثم أتموا الصيام إلى الليل﴾ / ﴿ولا تأكلوا أموالهم إلى أموالكم﴾',
          words: ['إليكم', 'إلى المسجد', 'إلى الليل', 'إلى أموالكم'],
          labels: ['المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول معه'],
          distractors: ['الحال'],
        },
        {
          title: 'تركيب: وظائف عن',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each عن + مجرور.',
          source: '﴿وينهون عن المنكر﴾ / ﴿هو يقبل التوبة عن عباده﴾ / ﴿عما قليل ليصبحن نادمين﴾ / ﴿وما نحن بتاركي آلهتنا عن قولك﴾',
          words: ['عن المنكر', 'عن عباده', 'عن قليل', 'عن قولك'],
          labels: ['المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول له'],
          distractors: ['العوض'],
        },
        {
          title: 'تركيب: وظائف على (١)',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each على + مجرور.',
          source: '﴿أنعمت عليهم﴾ / ﴿وعليها وعلى الفلك تحملون﴾ / ﴿ودخل المدينة على حين غفلة من أهلها﴾',
          words: ['عليهم', 'على الفلك', 'على حين غفلة'],
          labels: ['المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)'],
          distractors: ['الحال'],
        },
        {
          title: 'تركيب: وظائف على (٢)',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each على + مجرور.',
          source: '﴿سخرها لكم لتكبروا الله على ما هداكم﴾ / ﴿ويطعمون الطعام على حبه مسكينا﴾ / ﴿فما آمن لموسى إلا ذرية من قومه على خوف من فرعون﴾',
          words: ['على ما هداكم', 'على حبه', 'على خوف'],
          labels: ['المفعول له', 'المفعول معه', 'الحال'],
          distractors: ['العوض'],
        },
        {
          title: 'تركيب: إلى أم عن أم على؟',
          kind: 'tarkeeb',
          instruction: 'Classify which حرف جر appears in each phrase: إلى، عن، or على?',
          source: 'إلى المسجد الأقصى / عن المنكر / على حين غفلة / حج عن أبيك',
          words: ['إلى المسجد', 'عن المنكر', 'على حين غفلة', 'عن أبيك'],
          labels: ['إلى', 'عن', 'على', 'عن'],
          distractors: ['من'],
        },
      ],
    },

    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'اللام وفي والكاف وحتى',
      subtitle: 'Ownership, Containment, and Comparison — اللام، في، الكاف، and حتى',
      concepts: [
        {
          heading: 'اللام: معانيها الثلاثة',
          body: `<bdi>اللَّام</bdi> carries three core meanings: (1) <bdi>التَّخْصِيص</bdi> — also called <bdi>الِاسْتِحْقَاق</bdi> — as in <bdi>﴿الْحَمْدُ لِلَّهِ﴾</bdi> (2) <bdi>الْمِلْك</bdi>, as in <bdi>﴿لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ﴾</bdi> (3) <bdi>شِبْهُ الْمِلْك</bdi> — also called <bdi>النِّسْبَة</bdi> — as in <bdi>﴿لَآيَاتٍ لِّلْمُؤْمِنِينَ﴾</bdi>. التخصيص and الملك differ in what they connect: التخصيص holds between a <b>meaning</b> and an <b>entity</b> (الحمد لله), while الملك holds between an <b>entity</b> and an <b>entity</b> (له ما في السماوات).`,
          sample: `التخصيص/الاستحقاق — ﴿الحمد لله﴾<br>الملك — ﴿له ما في السماوات وما في الأرض﴾<br>شبه الملك/النسبة — ﴿لآيات للمؤمنين﴾`,
          exercise: {
            prompt: `التخصيص and الملك, two of the three core meanings of اللام, differ in that:`,
            kind: 'mcq',
            options: ['التخصيص holds between a meaning and an entity, الملك between two entities', 'التخصيص is only Quranic, الملك is not', 'الملك always precedes a ضمير', 'There is no real difference between them'],
            correct: 0,
          },
        },
        {
          heading: 'اللام: وظائفها، ولام التعليل والعاقبة',
          body: `With its مجرور, اللام takes three وظائف: (1) <bdi>الْمَفْعُولُ بِهِ</bdi> (2) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (3) <bdi>الْمَفْعُولُ لَهُ</bdi>. When اللام + مجرور is a مفعول له, the outcome is usually intended by the agent (<bdi>عَنْ قَصْدِ الْفَاعِل</bdi>), as in <bdi>﴿لِيَكُونَ لِلْعَالَمِينَ نَذِيرًا﴾</bdi> — this is called <bdi>لَامُ التَّعْلِيل</bdi> (also <bdi>وَالْحِكْمَة</bdi>). When the outcome is instead a result the agent never intended (<bdi>نَتِيجَةٌ عَنْ غَيْرِ قَصْد</bdi>), it is called <bdi>لَامُ الْعَاقِبَة</bdi> — also <bdi>لَامُ الصَّيْرُورَة</bdi> and <bdi>لَامُ الْمَآل</bdi> — as in <bdi>﴿فَالْتَقَطَهُ آلُ فِرْعَوْنَ لِيَكُونَ لَهُمْ عَدُوًّا وَحَزَنًا﴾</bdi>.`,
          sample: `وظائف اللام — به، فيه، له<br>لام التعليل — ﴿ليكون للعالمين نذيرا﴾ (مقصود)<br>لام العاقبة — ﴿فالتقطه آل فرعون ليكون لهم عدوا وحزنا﴾ (غير مقصود)`,
          exercise: {
            prompt: `What is لام العاقبة؟`,
            kind: 'mcq',
            options: ['A لام marking a result the agent never intended, unlike لام التعليل', 'A لام that only appears with أفعال الأمر', 'Another name for لام الجحود', 'A لام that never takes a مجرور'],
            correct: 0,
          },
        },
        {
          heading: 'في: معناها ووظائفها',
          body: `The core meaning of <bdi>فِي</bdi> is <bdi>الظَّرْفِيَّة</bdi> — containment, one thing occurring within another. With its مجرور it takes four وظائف: (1) <bdi>الْمَفْعُولُ بِهِ</bdi> (2) <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا أو زمانا (3) <bdi>الْمَفْعُولُ لَهُ</bdi> (4) <bdi>الْمَفْعُولُ مَعَهُ</bdi>. In <bdi>﴿شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ﴾</bdi>, فيه is <bdi>الْمَفْعُولُ فِيهِ</bdi> — <bdi>لِلزَّمَان</bdi>. In <bdi>﴿فَادْخُلِي فِي عِبَادِي﴾</bdi>, في عبادي is <bdi>الْمَفْعُولُ مَعَهُ</bdi>.`,
          sample: `الظرفية — containment<br>وظائف في — به، فيه، له، معه<br>﴿أنزل فيه القرآن﴾ — فيه (زمان)<br>﴿فادخلي في عبادي﴾ — معه`,
          exercise: {
            prompt: `الظرفية (containment) is the core meaning of:`,
            kind: 'mcq',
            options: ['في', 'على', 'حتى', 'الكاف'],
            correct: 0,
          },
        },
        {
          heading: 'الكاف: معناها وقيدها',
          body: `The core meaning of <bdi>الْكَاف</bdi> is <bdi>التَّشْبِيه</bdi> — likening or comparison. With its مجرور it can mark <bdi>الْمَفْعُولُ الْمُطْلَق</bdi>, as in <bdi>﴿رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا﴾</bdi>, or <bdi>الْمَفْعُولُ لَهُ</bdi>, as in <bdi>﴿وَاذْكُرُوهُ كَمَا هَدَاكُمْ﴾</bdi>. A restriction unique to الكاف: its مجرور can only be an <bdi>اسم ظاهر</bdi> — an overt noun — never a <bdi>ضمير</bdi>.`,
          sample: `التشبيه — likening<br>﴿كما ربياني صغيرا﴾ — المفعول المطلق<br>﴿كما هداكم﴾ — المفعول له<br>مجرور الكاف — اسم ظاهر فقط، لا ضمير`,
          exercise: {
            prompt: `What restriction applies to the مجرور of الكاف؟`,
            kind: 'mcq',
            options: ['It can only be an اسم ظاهر, never a ضمير', 'It must always be مؤنث', 'It must always be جمع', 'There is no restriction'],
            correct: 0,
          },
        },
        {
          heading: 'حتى: معناها وقيدها، والفرق بينها وبين إلى',
          body: `Like إلى, the core meaning of <bdi>حَتَّى</bdi> (as a جر حرف) is <bdi>انْتِهَاءُ الْغَايَة</bdi>. With its مجرور it can mark <bdi>الْمَفْعُولُ فِيهِ</bdi> — مكانا (سِرْنَا حَتَّى مَكَّة) or زمانا (<bdi>﴿سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ﴾</bdi>) — or <bdi>الْمَفْعُولُ لَهُ</bdi>, as in <bdi>﴿وَقَاتِلُوهُمْ حَتَّىٰ لَا تَكُونَ فِتْنَةٌ﴾</bdi>. Its مجرور, like الكاف's, can only be an <bdi>اسم ظاهر</bdi>. حتى differs from إلى in what may follow it: what comes after حتى must be either the <b>final part</b> of what precedes it (<bdi>قُمْتُ اللَّيْلَ حَتَّى آخِرِهِ</bdi> — not <bdi>حَتَّى نِصْفِهِ</bdi>) or <b>connected to its end</b> (<bdi>قُمْتُ اللَّيْلَ حَتَّى الصَّبَاحِ</bdi>); إلى carries no such restriction.`,
          sample: `انتهاء الغاية — مثل إلى<br>سرنا حتى مكة — فيه (مكان)<br>﴿سلام هي حتى مطلع الفجر﴾ — فيه (زمان)<br>﴿وقاتلوهم حتى لا تكون فتنة﴾ — له<br>حتى تشترط اتصال ما بعدها بآخر ما قبلها؛ إلى لا`,
          exercise: {
            prompt: `What is the difference between حتى and إلى regarding what follows them؟`,
            kind: 'mcq',
            options: ['حتى requires what follows to be the final part of, or connected to the end of, what precedes it — إلى has no such restriction', 'إلى is stricter than حتى', 'حتى never takes a مجرور at all', 'They are identical in every respect'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'اللام carries three core meanings. Which of these is one of them؟',
          options: ['شبه الملك (النسبة)', 'الإلصاق', 'الاستعلاء', 'التشبيه'],
          correct: 0,
        },
        {
          q: 'لام العاقبة, unlike لام التعليل, marks a result that is:',
          options: ['not intended by the agent (غير مقصود)', 'always intended by the agent', 'impossible to express in Arabic', 'only found with أفعال الأمر'],
          correct: 0,
        },
        {
          q: 'What is the core meaning of في؟',
          options: ['الظرفية', 'الاستعلاء', 'التشبيه', 'المجاوزة'],
          correct: 0,
        },
        {
          q: 'In ﴿فادخلي في عبادي﴾, في عبادي functions as:',
          options: ['المفعول معه', 'المفعول به', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          q: 'What restriction applies to the مجرور of both الكاف and حتى؟',
          options: ['It must be an اسم ظاهر, never a ضمير', 'It must be مرفوع', 'It must be نكرة', 'It must be a فعل'],
          correct: 0,
        },
        {
          q: 'حتى differs from إلى in that what follows حتى must be:',
          options: ['the final part of, or connected to the end of, what precedes it', 'always a زمان, never a مكان', 'always negated', 'always a جملة فعلية'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'التخصيص',
          kind: 'mcq',
          prompt: '﴿الحمد لله﴾ illustrates which meaning of اللام؟',
          options: ['التخصيص (الاستحقاق)', 'الملك', 'شبه الملك (النسبة)', 'التشبيه'],
          correct: 0,
        },
        {
          title: 'الملك',
          kind: 'mcq',
          prompt: '﴿له ما في السماوات وما في الأرض﴾ illustrates which meaning of اللام؟',
          options: ['الملك', 'التخصيص', 'شبه الملك', 'الظرفية'],
          correct: 0,
        },
        {
          title: 'شبه الملك',
          kind: 'mcq',
          prompt: '﴿لآيات للمؤمنين﴾ illustrates which meaning of اللام؟',
          options: ['شبه الملك (النسبة)', 'الملك', 'التخصيص', 'الاستعلاء'],
          correct: 0,
        },
        {
          title: 'اللام: المفعول به',
          kind: 'mcq',
          prompt: 'In ﴿ووهبنا له إسحاق ويعقوب﴾, له functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول فيه', 'المفعول له', 'الحال'],
          correct: 0,
        },
        {
          title: 'اللام: المفعول فيه للمكان',
          kind: 'mcq',
          prompt: 'In ﴿دعانا لجنبه أو قاعدا أو قائما﴾, لجنبه functions as:',
          options: ['المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول له', 'الحال'],
          correct: 0,
        },
        {
          title: 'اللام: المفعول فيه للزمان',
          kind: 'mcq',
          prompt: 'In ﴿ونضع الموازين القسط ليوم القيامة﴾, ليوم القيامة functions as:',
          options: ['المفعول فيه (زمان)', 'المفعول فيه (مكان)', 'المفعول له', 'المفعول معه'],
          correct: 0,
        },
        {
          title: 'لام التعليل',
          kind: 'mcq',
          prompt: '﴿ليكون للعالمين نذيرا﴾ illustrates:',
          options: ['لام التعليل — an outcome intended by the agent', 'لام العاقبة — an unintended outcome', 'لام الجحود', 'لام التقوية'],
          correct: 0,
        },
        {
          title: 'أسماء أخرى للام العاقبة',
          kind: 'mcq',
          prompt: 'لام العاقبة is also called:',
          options: ['لام الصيرورة أو لام المآل', 'لام التعليل أو لام الحكمة', 'لام الجحود', 'لام التبيين'],
          correct: 0,
        },
        {
          title: 'في: المفعول به',
          kind: 'mcq',
          prompt: 'In ﴿ويسارعون في الخيرات﴾, في الخيرات functions as:',
          options: ['المفعول به (غير صريح)', 'المفعول فيه', 'الحال', 'المفعول له'],
          correct: 0,
        },
        {
          title: 'في: المفعول له',
          kind: 'mcq',
          prompt: 'In ﴿قالت فذلكن الذي لمتنني فيه﴾, فيه functions as:',
          options: ['المفعول له', 'المفعول به', 'الحال', 'المفعول معه'],
          correct: 0,
        },
        {
          title: 'عدد وظائف في',
          kind: 'mcq',
          prompt: 'How many وظائف can في with its مجرور take؟',
          options: ['أربعة', 'ثلاثة', 'خمسة', 'ستة'],
          correct: 0,
        },
        {
          title: 'الكاف: المفعول المطلق',
          kind: 'mcq',
          prompt: 'In ﴿رب ارحمهما كما ربياني صغيرا﴾, كما functions as:',
          options: ['المفعول المطلق', 'المفعول له', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          title: 'الكاف: المفعول له',
          kind: 'mcq',
          prompt: 'In ﴿واذكروه كما هداكم﴾, كما functions as:',
          options: ['المفعول له', 'المفعول المطلق', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'حتى: المفعول فيه للمكان',
          kind: 'mcq',
          prompt: 'سرنا حتى مكة — حتى مكة functions as:',
          options: ['المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول له', 'الحال'],
          correct: 0,
        },
        {
          title: 'حتى: المفعول له',
          kind: 'mcq',
          prompt: 'In ﴿وقاتلوهم حتى لا تكون فتنة﴾, حتى لا تكون فتنة functions as:',
          options: ['المفعول له', 'المفعول فيه', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          title: 'حتى الصحيح والخاطئ',
          kind: 'mcq',
          prompt: 'Which of these is a valid use of حتى, given its restriction on what follows it؟',
          options: ['قمت الليل حتى الصباح', 'قمت الليل حتى نصفه', 'قمت الليل حتى وسطه', 'قمت الليل حتى بعضه'],
          correct: 0,
        },
        {
          title: 'الظرفية أم معاني اللام؟',
          kind: 'mcq',
          prompt: 'Which حرف has الظرفية as its core meaning — distinct from any of the three meanings of اللام؟',
          options: ['في', 'اللام', 'الكاف', 'حتى'],
          correct: 0,
        },
        {
          title: 'قيد مشترك',
          kind: 'mcq',
          prompt: 'الكاف and حتى share which restriction on their مجرور؟',
          options: ['It must be an اسم ظاهر', 'It must be مؤنث', 'It must be a ضمير', 'It must be جمع'],
          correct: 0,
        },
        {
          title: 'تركيب: معاني اللام الثلاثة',
          kind: 'tarkeeb',
          instruction: 'Classify which meaning of اللام each example illustrates.',
          source: '﴿الحمد لله﴾ / ﴿له ما في السماوات وما في الأرض﴾ / ﴿لآيات للمؤمنين﴾',
          words: ['لله', 'له', 'للمؤمنين'],
          labels: ['التخصيص', 'الملك', 'شبه الملك'],
          distractors: ['التشبيه'],
        },
        {
          title: 'تركيب: وظائف اللام',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each لام + مجرور.',
          source: '﴿ووهبنا له إسحاق ويعقوب﴾ / ﴿دعانا لجنبه أو قاعدا أو قائما﴾ / ﴿ونضع الموازين القسط ليوم القيامة﴾',
          words: ['له', 'لجنبه', 'ليوم القيامة'],
          labels: ['المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)'],
          distractors: ['المفعول له'],
        },
        {
          title: 'تركيب: لام التعليل أم لام العاقبة؟',
          kind: 'tarkeeb',
          instruction: 'Classify each لام: لام التعليل (intended) or لام العاقبة (unintended)?',
          source: '﴿ليكون للعالمين نذيرا﴾ / ﴿فالتقطه آل فرعون ليكون لهم عدوا وحزنا﴾',
          words: ['ليكون للعالمين نذيرا', 'ليكون لهم عدوا'],
          labels: ['لام التعليل', 'لام العاقبة'],
          distractors: ['لام الجحود'],
        },
        {
          title: 'تركيب: وظائف في',
          kind: 'tarkeeb',
          instruction: 'Classify the وظيفة of each في + مجرور.',
          source: '﴿ويسارعون في الخيرات﴾ / ﴿ربنا آتنا في الدنيا حسنة﴾ / ﴿شهر رمضان الذي أنزل فيه القرآن﴾ / ﴿فادخلي في عبادي﴾',
          words: ['في الخيرات', 'في الدنيا', 'فيه', 'في عبادي'],
          labels: ['المفعول به', 'المفعول فيه (مكان)', 'المفعول فيه (زمان)', 'المفعول معه'],
          distractors: ['الحال'],
        },
        {
          title: 'تركيب: اللام أم في أم الكاف أم حتى؟',
          kind: 'tarkeeb',
          instruction: 'Classify which حرف جر appears in each phrase.',
          source: 'له ما في السماوات / في الخيرات / كما هداكم / حتى مطلع الفجر',
          words: ['له', 'في الخيرات', 'كما', 'حتى مطلع الفجر'],
          labels: ['اللام', 'في', 'الكاف', 'حتى'],
          distractors: ['على'],
        },
      ],
    },

    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'أحرف القسم ومذ ومنذ',
      subtitle: 'Oaths and Duration — the three أحرف القسم, and مذ/منذ for elapsed time',
      concepts: [
        {
          heading: 'أحرف القسم الثلاثة، وإعرابها',
          body: `The three <bdi>أَحْرُفُ الْقَسَم</bdi> are <bdi>الْوَاو</bdi>, <bdi>التَّاء</bdi>, and <bdi>الْبَاء</bdi> — the original one (<bdi>أَصْلُ أَحْرُفِ الْقَسَم</bdi>) being <bdi>بَاءُ الْقَسَم</bdi>. <bdi>وَاوُ الْقَسَم</bdi>: <bdi>﴿وَالْعَصْرِ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ﴾</bdi>. <bdi>تَاءُ الْقَسَم</bdi>: <bdi>﴿تَاللَّهِ تَفْتَأُ تَذْكُرُ يُوسُفَ﴾</bdi>. Whichever حرف is used, the حرف plus its مجرور stands as the <bdi>الْمَفْعُولُ بِهِ</bdi> of an omitted <bdi>فِعْل</bdi> whose <bdi>تَقْدِير</bdi> is <bdi>أُقْسِمُ</bdi>.`,
          sample: `أحرف القسم — الواو، التاء، الباء (الأصل)<br>﴿والعصر﴾ — واو القسم<br>﴿تالله﴾ — تاء القسم<br>إعرابها — مفعول به لفعل محذوف تقديره أقسم`,
          exercise: {
            prompt: `Which حرف قسم is the "original" (أصل) of the أحرف القسم؟`,
            kind: 'mcq',
            options: ['باء القسم', 'واو القسم', 'تاء القسم', 'لام القسم'],
            correct: 0,
          },
        },
        {
          heading: 'قيود أحرف القسم الثلاثة',
          body: `Each حرف قسم carries its own restrictions. <bdi>تَاءُ الْقَسَم</bdi> is restricted to <bdi>لَفْظُ الْجَلَالَة</bdi> — <bdi>تَاللَّهِ</bdi> is valid, but not <bdi>تَالْعَصْرِ</bdi> or <bdi>تَالرَّحْمَٰنِ</bdi>. The مجرور of <bdi>وَاوُ الْقَسَم</bdi> and <bdi>تَاءُ الْقَسَم</bdi> can only be an <bdi>اسم ظاهر</bdi>, never a <bdi>ضَمِير</bdi>. With <bdi>بَاءُ الْقَسَم</bdi> the <bdi>فِعْلُ الْقَسَم</bdi> (أُقْسِمُ) may be either mentioned — <bdi>﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾</bdi> — or omitted — <bdi>﴿فَبِعِزَّتِكَ لَأُغْوِيَنَّهُمْ أَجْمَعِينَ﴾</bdi>; with الواو and التاء it is never mentioned. Unlike الواو and التاء, الباء can also attach to a <bdi>ضَمِير</bdi>, not only an اسم ظاهر — as in <bdi>بِكَ لَأَفْعَلَنَّ</bdi>.`,
          sample: `تاء القسم — لفظ الجلالة فقط<br>مجرور الواو والتاء — اسم ظاهر فقط<br>فعل القسم — يجوز ذكره مع الباء، ويمتنع مع الواو والتاء<br>الباء — تتصل بالظاهر والمضمر`,
          exercise: {
            prompt: `Can the فعل القسم be mentioned with واو القسم or تاء القسم؟`,
            kind: 'mcq',
            options: ['No — with الواو and التاء the فعل القسم is always omitted', 'Yes, always mentioned with both', 'Only with واو القسم', 'Only with تاء القسم'],
            correct: 0,
          },
        },
        {
          heading: 'مذ ومنذ: وظيفتهما وشرط الفعل قبلهما',
          body: `<bdi>مُذْ</bdi> and <bdi>مُنْذُ</bdi> with their مجرور mark <bdi>الْمَفْعُولُ فِيهِ</bdi>, as in <bdi>مَا تَرَكْتُ صَلَاةً مُذْ يَوْمِ الْبُلُوغِ</bdi> and <bdi>تَجِبُ الصَّلَاةُ مُنْذُ يَوْمِ الْبُلُوغِ</bdi>. The فعل before them must be <bdi>فِعْلًا مَاضِيًا</bdi> that is either <b>negated</b> (<bdi>مَا رَأَيْتُهُ مُنْذُ يَوْمِ الْجُمُعَةِ</bdi>) or <b>affirmative and extended in duration</b> (<bdi>نِمْتُ مُنْذُ بَعْدِ الْعِشَاءِ</bdi>) — not a momentary affirmative like <bdi>سَقَطْتُ مُنْذُ طُلُوعِ الشَّمْسِ</bdi>. Their مجرور, in turn, can only be an <bdi>اسم ظاهر</bdi> denoting <b>past or present time</b>.`,
          sample: `مذ/منذ — المفعول فيه<br>الفعل قبلهما — ماضٍ، منفي أو مثبت ممتد (لا مثبت لحظي)<br>مجرورهما — اسم ظاهر يدل على ماضٍ أو حاضر`,
          exercise: {
            prompt: `What condition applies to the فعل preceding مذ and منذ؟`,
            kind: 'mcq',
            options: ['It must be فعلا ماضيا, either negated or affirmative-and-extended', 'It must always be فعل أمر', 'It must always be فعل مضارع', 'There is no condition on it'],
            correct: 0,
          },
        },
        {
          heading: 'مذ ومنذ: التعريف والإضافة إلى جملة',
          body: `Definiteness of the مجرور maps onto an English distinction: definite (<bdi>مَعْرِفَة</bdi>) reads as "since" — <bdi>مُنْذُ الْجُمُعَةِ</bdi> = since Friday — while indefinite (<bdi>نَكِرَة</bdi>) reads as "for" — <bdi>مُنْذُ يَوْمَيْنِ</bdi> = for two days. The same split governs meaning: مذ/منذ carry the sense of <bdi>فِي</bdi> when the مجرور is a definite اسم denoting the <b>present</b> (<bdi>مَا رَأَيْتُهُ مُنْذُ الْيَوْمِ</bdi>), and the sense of <bdi>مِنْ وَإِلَى</bdi> when it denotes the <b>past</b>. Their إعراب follows the same logic: <bdi>مَجْرُور</bdi> obligatorily (<bdi>وُجُوبًا</bdi>) with a present-time اسم, and — for منذ — preferably (<bdi>تَرْجِيحًا</bdi>) with a past-time اسم, though for مذ a past-time اسم prefers <bdi>مَرْفُوع</bdi> instead (<bdi>مُذْ يَوْمَانِ</bdi>). When a full <bdi>جُمْلَة</bdi> follows مذ/منذ, they are treated as <b>أسماء in <bdi>إِضَافَة</bdi></b> to it — because a جر حرف cannot enter upon a جملة, only an اسم مضاف can.`,
          sample: `معرفة → since (منذ الجمعة)؛ نكرة → for (منذ يومين)<br>معنى في — مع حاضر معرفة؛ معنى من وإلى — مع ماضٍ<br>إعراب بعد منذ — وجوبا مجرور مع حاضر، ترجيحا مع ماضٍ<br>إعراب بعد مذ — وجوبا مجرور مع حاضر، لكن مرفوع مفضل مع ماضٍ<br>جملة بعدهما — مذ/منذ اسمان مضافان إليها`,
          exercise: {
            prompt: `Why must مذ/منذ be أسماء when followed by a جملة؟`,
            kind: 'mcq',
            options: ['Because a جر حرف cannot enter upon a جملة, and only an اسم can be مضاف to one', 'Because جمل are always مبنية', 'Because مذ/منذ are never حروف at all', 'There is no real reason — it is arbitrary'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the إعراب of واو القسم / تاء القسم with their مجرور؟',
          options: ['المفعول به of an omitted فعل تقديره أقسم', 'المفعول المطلق', 'الفاعل', 'الحال'],
          correct: 0,
        },
        {
          q: 'What restriction applies to تاء القسم specifically؟',
          options: ['It is restricted to لفظ الجلالة', 'It can attach to any اسم', 'It can attach to a ضمير', 'It requires a negated فعل'],
          correct: 0,
        },
        {
          q: 'What can باء القسم attach to that الواو and التاء cannot؟',
          options: ['A ضمير (مضمر), as well as an اسم ظاهر', 'A جملة فعلية', 'A فعل مضارع', 'Nothing — all three behave identically'],
          correct: 0,
        },
        {
          q: 'What function do مذ and منذ with their مجرور take؟',
          options: ['المفعول فيه', 'المفعول به', 'المفعول له', 'الحال'],
          correct: 0,
        },
        {
          q: 'How does definiteness of the مجرور of منذ map onto English؟',
          options: ['معرفة → since; نكرة → for', 'معرفة → for; نكرة → since', 'Both always mean since', 'Definiteness has no effect on meaning'],
          correct: 0,
        },
        {
          q: 'What is the إعراب of the اسم after مذ with a past-time meaning؟',
          options: ['مرفوع is preferred (though مجرور is also possible)', 'مجرور وجوبا, no alternative', 'منصوب دائما', 'It cannot follow a past-time اسم at all'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'مثال واو القسم',
          kind: 'mcq',
          prompt: '﴿والعصر إن الإنسان لفي خسر﴾ illustrates:',
          options: ['واو القسم', 'تاء القسم', 'باء القسم', 'لام القسم'],
          correct: 0,
        },
        {
          title: 'مثال تاء القسم',
          kind: 'mcq',
          prompt: '﴿تالله تفتأ تذكر يوسف﴾ illustrates:',
          options: ['تاء القسم', 'واو القسم', 'باء القسم', 'كاف القسم'],
          correct: 0,
        },
        {
          title: 'تالله لا تالعصر',
          kind: 'mcq',
          prompt: 'Why is تَالْعَصْرِ not valid Arabic, unlike تَاللَّهِ؟',
          options: ['تاء القسم is restricted to لفظ الجلالة alone', 'العصر cannot ever be مجرورا', 'تاء القسم does not exist', 'العصر is not a اسم'],
          correct: 0,
        },
        {
          title: 'مجرور الواو والتاء',
          kind: 'mcq',
          prompt: 'The مجرور of واو القسم and تاء القسم must be:',
          options: ['اسم ظاهر, never a ضمير', 'ضمير فقط', 'فعل مضارع', 'جملة فعلية'],
          correct: 0,
        },
        {
          title: 'ذكر فعل القسم مع الباء',
          kind: 'mcq',
          prompt: '﴿لا أقسم بيوم القيامة﴾ shows فعل القسم:',
          options: ['mentioned, since الباء allows either mentioning or omitting it', 'omitted, since الباء never allows mentioning it', 'replaced by a ضمير', 'impossible with الباء'],
          correct: 0,
        },
        {
          title: 'حذف فعل القسم مع الباء',
          kind: 'mcq',
          prompt: '﴿فبعزتك لأغوينهم أجمعين﴾ shows فعل القسم:',
          options: ['omitted — one of the two options الباء allows', 'mentioned explicitly', 'replaced by واو القسم', 'ungrammatical'],
          correct: 0,
        },
        {
          title: 'الباء تتصل بالمضمر',
          kind: 'mcq',
          prompt: 'بِكَ لَأَفْعَلَنَّ shows باء القسم attaching to:',
          options: ['a ضمير (مضمر)', 'only an اسم ظاهر', 'a جملة فعلية', 'nothing — this phrase is invalid'],
          correct: 0,
        },
        {
          title: 'مذ ومنذ: المثال',
          kind: 'mcq',
          prompt: 'ما تركت صلاة مذ يوم البلوغ — مذ يوم البلوغ functions as:',
          options: ['المفعول فيه', 'المفعول به', 'الحال', 'التمييز'],
          correct: 0,
        },
        {
          title: 'شرط الفعل: منفي',
          kind: 'mcq',
          prompt: 'ما رأيته منذ يوم الجمعة is valid because the فعل before منذ is:',
          options: ['ماضٍ منفي', 'ماضٍ مثبت لحظي', 'مضارع', 'فعل أمر'],
          correct: 0,
        },
        {
          title: 'شرط الفعل: مثبت ممتد',
          kind: 'mcq',
          prompt: 'نمت منذ بعد العشاء is valid because نام here is:',
          options: ['ماضٍ مثبت ممتد (extended in duration)', 'ماضٍ مثبت لحظي (momentary)', 'مضارع', 'منفي'],
          correct: 0,
        },
        {
          title: 'شرط الفعل: ما لا يصح',
          kind: 'mcq',
          prompt: 'سقطت منذ طلوع الشمس is NOT valid usage because سقط here is:',
          options: ['ماضٍ مثبت لحظي — momentary, not extended', 'ماضٍ منفي', 'مضارع', 'فعل أمر'],
          correct: 0,
        },
        {
          title: 'مذ/منذ بمعنى في',
          kind: 'mcq',
          prompt: 'مذ/منذ carry the meaning of في when the مجرور is:',
          options: ['a definite اسم denoting the present', 'an indefinite اسم denoting the past', 'any ضمير', 'a فعل مضارع'],
          correct: 0,
        },
        {
          title: 'since أم for؟',
          kind: 'mcq',
          prompt: 'منذ يومين, with an indefinite مجرور, translates into English as:',
          options: ['for two days', 'since two days', 'two days ago exactly', 'never'],
          correct: 0,
        },
        {
          title: 'إعراب بعد منذ مع الماضي',
          kind: 'mcq',
          prompt: 'منذ يومين — the إعراب of the اسم after منذ here is:',
          options: ['مجرور, preferred (ترجيحا) with past-time أسماء', 'مرفوع وجوبا', 'منصوب وجوبا', 'لا إعراب له'],
          correct: 0,
        },
        {
          title: 'إعراب بعد مذ مع الماضي',
          kind: 'mcq',
          prompt: 'مذ يومان — the إعراب of the اسم after مذ here is:',
          options: ['مرفوع, preferred with past-time أسماء', 'مجرور وجوبا, لا بديل', 'منصوب وجوبا', 'لا إعراب له'],
          correct: 0,
        },
        {
          title: 'جملة بعد مذ',
          kind: 'mcq',
          prompt: 'ما اغتبت أحدا مذ علمت الغيبة محرمة — here مذ is treated as:',
          options: ['an اسم مضاف to the جملة after it', 'a حرف جر عادي', 'فعل ماضٍ', 'ضمير منفصل'],
          correct: 0,
        },
        {
          title: 'المفعول فيه بمذ ومنذ',
          kind: 'mcq',
          prompt: 'تجب الصلاة منذ يوم البلوغ — منذ يوم البلوغ functions as:',
          options: ['المفعول فيه', 'المفعول به', 'الحال', 'العوض'],
          correct: 0,
        },
        {
          title: 'أصل أحرف القسم',
          kind: 'mcq',
          prompt: 'باء القسم is called the أصل of the أحرف القسم because:',
          options: ['الواو and التاء are treated as substitutes branching from it', 'it is the only one mentioned in the Quran', 'it is the newest of the three', 'it never attaches to a ضمير'],
          correct: 0,
        },
        {
          title: 'تركيب: واو أم تاء أم باء القسم؟',
          kind: 'tarkeeb',
          instruction: 'Classify which حرف قسم appears in each phrase.',
          source: '﴿والعصر إن الإنسان لفي خسر﴾ / ﴿تالله تفتأ تذكر يوسف﴾ / ﴿لا أقسم بيوم القيامة﴾',
          words: ['والعصر', 'تالله', 'بيوم القيامة'],
          labels: ['واو القسم', 'تاء القسم', 'باء القسم'],
          distractors: ['لام القسم'],
        },
        {
          title: 'تركيب: قيود أحرف القسم',
          kind: 'tarkeeb',
          instruction: 'Match each restriction to the حرف قسم it applies to.',
          source: 'تاء القسم / واو القسم وتاء القسم / باء القسم',
          words: ['تاء القسم', 'واو القسم وتاء القسم', 'باء القسم'],
          labels: ['مقصورة على لفظ الجلالة', 'مجرورهما اسم ظاهر فقط، وفعل القسم لا يُذكر معهما', 'فعل القسم قد يُذكر أو يُحذف، وتتصل بالظاهر والمضمر'],
          distractors: ['لام القسم'],
        },
        {
          title: 'تركيب: شرط الفعل قبل مذ/منذ',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل before مذ/منذ: ماضٍ منفي, ماضٍ مثبت ممتد, or ماضٍ مثبت لحظي (غير صحيح)?',
          source: 'ما رأيته منذ يوم الجمعة / نمت منذ بعد العشاء / سقطت منذ طلوع الشمس',
          words: ['رأيته', 'نمت', 'سقطت'],
          labels: ['ماضٍ منفي', 'ماضٍ مثبت ممتد', 'ماضٍ مثبت لحظي'],
          distractors: ['مضارع'],
        },
        {
          title: 'تركيب: since أم for؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مذ/منذ phrase by whether it reads as "since" or "for" in English.',
          source: 'منذ الجمعة / منذ يومين / مذ الليلة / مذ يومان',
          words: ['منذ الجمعة', 'منذ يومين', 'مذ الليلة', 'مذ يومان'],
          labels: ['since', 'for', 'since', 'for'],
          distractors: ['until'],
        },
        {
          title: 'تركيب: مجرور أم مرفوع بعد مذ/منذ؟',
          kind: 'tarkeeb',
          instruction: 'Classify the إعراب of the اسم after مذ/منذ in each phrase.',
          source: 'منذ الليلة / منذ يومين / مذ الليلة / مذ يومان',
          words: ['منذ الليلة', 'منذ يومين', 'مذ الليلة', 'مذ يومان'],
          labels: ['مجرور وجوبا', 'مجرور ترجيحا', 'مجرور وجوبا', 'مرفوع مفضل'],
          distractors: ['منصوب'],
        },
      ],
    },

    // ---------------------------------------------------------------- L6
    {
      id: 'l6',
      title: 'الشبيه بالزائد والزائد',
      subtitle: 'Beyond the Thirteen — حروف شبيهة بالزائد, حروف زائدة, and when a حرف الجر disappears',
      concepts: [
        {
          heading: 'حروف الشبيه بالزائد الثلاثة: رُبَّ',
          body: `Three حروف make up <bdi>الشَّبِيهُ بِالزَّائِد</bdi>: <bdi>رُبَّ</bdi>, <bdi>مِنِ التَّبْعِيضِيَّة</bdi>, and <bdi>حَاشَا</bdi>. <bdi>رُبَّ</bdi> expresses either <bdi>تَكْثِير</bdi> (abundance) or <bdi>تَقْلِيل</bdi> (scarcity) of its مجرور — context (<bdi>الْقَرِينَة</bdi>) decides which, as in <bdi>رُبَّ شَهْوَةٍ تُورِثُ حُزْنًا طَوِيلًا</bdi>. It must appear at the <bdi>صَدْرُ الْكَلَام</bdi> — the very start of the utterance — though a vocative حرف may precede it, as in <bdi>«يَا رُبَّ كَاسِيَاتٍ فِي الدُّنْيَا عَارِيَاتٍ فِي الْآخِرَةِ»</bdi>. Its مجرور can only be (1) an indefinite overt اسم (<bdi>اسم ظاهر نكرة</bdi>) or (2) an ambiguous ضمير clarified by a تمييز, as in <bdi>رُبَّهُ رَجُلًا كَرِيمًا لَقِيتُهُ</bdi> — and it is usually <bdi>مَوْصُوف</bdi> as well, by a single word or by a جملة.`,
          sample: `رب — تكثير أو تقليل، حسب القرينة<br>موضعها — صدر الكلام (إلا بعد حرف نداء)<br>مجرورها — اسم ظاهر نكرة، أو ضمير مبهم يفسره تمييز<br>عادة موصوف — بكلمة أو بجملة`,
          exercise: {
            prompt: `Where must رُبَّ appear in the جملة? Any exception؟`,
            kind: 'mcq',
            options: ['Only at the صدر الكلام — with the exception that a vocative حرف may precede it', 'It may appear anywhere in the جملة freely', 'Only at the very end of the جملة', 'It can never begin a جملة'],
            correct: 0,
          },
        },
        {
          heading: 'رُبَّ: ما الكافة، والتخفيف، والحذف؛ ومِن التبعيضية وحاشا',
          body: `Adding <bdi>مَا الْكَافَّة</bdi> to رُبَّ stops it from operating (<bdi>كَفَّتْهَا عَنِ الْعَمَل</bdi>), shifts the تكثير/تقليل onto the <b>فعل</b> instead, and lets it enter upon <bdi>جُمَل فِعْلِيَّة</bdi> (<bdi>رُبَّمَا يَصُومُ زَيْدٌ</bdi>) and definite أسماء (<bdi>رُبَّمَا زَيْدٌ يَصُومُ</bdi>). رُبَّمَا can also be lightened (<bdi>تَخْفِيف</bdi>) to <bdi>رُبَمَا</bdi>, as in <bdi>﴿رُبَمَا يَوَدُّ الَّذِينَ كَفَرُوا لَوْ كَانُوا مُسْلِمِينَ﴾</bdi>; رُبَّ itself can be omitted while its عمل remains — frequently after <bdi>الْوَاو</bdi>, rarely after <bdi>الْفَاء</bdi> — as in <bdi>وَلَيْلٍ كَمَوْجِ الْبَحْرِ أَرْخَىٰ سُدُولَهُ</bdi>. مِنْ can also carry رُبَّ's meaning when <bdi>مَا</bdi> follows it (<bdi>مِمَّا</bdi>). <bdi>مِنِ التَّبْعِيضِيَّة</bdi> ("some of") appears in <bdi>﴿وَلَقَدْ جَاءَكَ مِن نَّبَإِ الْمُرْسَلِينَ﴾</bdi> and <bdi>عِنْدِي مِنْ مَاءٍ</bdi>; <bdi>حَاشَا</bdi> appears in <bdi>هَلَكَ النَّاسُ حَاشَا الْعَالِمِ</bdi>. All three are called شبيه بالزائد because — like الزائد — neither هي nor its مجرور is ever a معمول of a فعل or شبه فعل, but unlike الزائد, each still carries a real meaning of its own.`,
          sample: `ما الكافة + رب — تكفها عن العمل، تدخل على جمل فعلية وأسماء معرفة<br>ربما → رُبَما (تخفيف)<br>حذف رب — بعد الواو كثيرا، بعد الفاء نادرا<br>من بمعنى رب — مما<br>من التبعيضية — ﴿ولقد جاءك من نبإ المرسلين﴾<br>حاشا — هلك الناس حاشا العالم`,
          exercise: {
            prompt: `Understanding: why are رب، من التبعيضية، حاشا called "similar to the redundant" (شبيه بالزائد)؟`,
            kind: 'mcq',
            options: ['Neither they nor their مجرور is ever a معمول of a فعل or شبه فعل, yet each still carries a real meaning', 'Because they can all be omitted freely', 'Because they only appear in poetry', 'Because they never take a مجرور at all'],
            correct: 0,
          },
        },
        {
          heading: 'حروف الجر الزائدة الأربعة: الباء الزائدة قياسا',
          body: `Four حروف make up <bdi>حُرُوفُ الْجَرِّ الزَّائِدَة</bdi>: <bdi>الْبَاءُ الزَّائِدَة</bdi>, <bdi>مِنِ الزَّائِدَة</bdi>, <bdi>اللَّامُ الزَّائِدَة</bdi>, and <bdi>الْكَافُ الزَّائِدَة</bdi>. الباء الزائدة occurs by regular rule (<bdi>قِيَاسًا</bdi>) in five places: (1) the <bdi>خَبَر</bdi> of <bdi>نَفْي</bdi> with <bdi>لَيْسَ</bdi> and <bdi>مَا</bdi> — <bdi>﴿وَأَنَّ اللَّهَ لَيْسَ بِظَلَّامٍ لِّلْعَبِيدِ﴾</bdi> / <bdi>﴿وَمَا رَبُّكَ بِظَلَّامٍ لِّلْعَبِيدِ﴾</bdi> (2) the خبر of <bdi>اسْتِفْهَام</bdi> with <bdi>هَلْ</bdi> — <bdi>هَلْ زَيْدٌ بِقَائِمٍ؟</bdi> (3) <bdi>التَّأْكِيدُ الْمَعْنَوِيّ</bdi> with <bdi>نَفْس</bdi> — <bdi>نَظَّفَ الْأَمِيرُ الْمَسْجِدَ بِنَفْسِهِ</bdi> (4) the <bdi>فَاعِل</bdi> of <bdi>أَفْعِلْ بِهِ</bdi> (<bdi>تَعَجُّب</bdi>) — <bdi>﴿أَسْمِعْ بِهِمْ وَأَبْصِرْ﴾</bdi> (5) the <bdi>مُبْتَدَأ</bdi> after <bdi>إِذَا الْفُجَائِيَّة</bdi> — <bdi>دَخَلَ الرَّجُلُ فَإِذَا بِابْنِهِ يُصَلِّي</bdi>.`,
          sample: `أربعة زائدة — الباء، من، اللام، الكاف<br>الباء قياسا — خبر نفي، خبر استفهام بهل، تأكيد معنوي بنفس، فاعل أفعِل به، مبتدأ بعد إذا الفجائية`,
          exercise: {
            prompt: `Where does الباء الزائدة occur by regular rule (قياسا)? (5 places)`,
            kind: 'mcq',
            options: ['خبر نفي (ليس/ما)، خبر استفهام (هل)، تأكيد معنوي (نفس)، فاعل أفعِل به، مبتدأ بعد إذا الفجائية', 'Only in the خبر of نفي', 'Only in poetry, never in prose', 'Only with أفعال القلوب'],
            correct: 0,
          },
        },
        {
          heading: 'الباء الزائدة سماعا؛ ومِن الزائدة',
          body: `الباء الزائدة also occurs by transmission alone (<bdi>سَمَاعًا</bdi>) in three places: (1) on the <bdi>مُبْتَدَأ</bdi> with the word <bdi>حَسْب</bdi> — <bdi>«بِحَسْبِكَ أَن تَصُومَ كُلَّ شَهْرٍ ثَلَاثَةَ أَيَّامٍ»</bdi> (2) on the <bdi>خَبَر</bdi> of حسب — <bdi>حَسْبُكَ بِزَيْدٍ</bdi> (3) on the <bdi>فَاعِل</bdi> of <bdi>كَفَى</bdi> when it means حسب — <bdi>﴿كَفَى بِاللَّهِ شَهِيدًا﴾</bdi>; كفى does NOT take this زائدة باء when it instead means <bdi>وَقَى</bdi> (to protect), as in <bdi>﴿وَكَفَى اللَّهُ الْمُؤْمِنِينَ الْقِتَالَ﴾</bdi>. <bdi>مِنِ الزَّائِدَة</bdi> occurs (1) on the <bdi>تَمْيِيز</bdi> of <bdi>كَمِ الْخَبَرِيَّة</bdi> — <bdi>﴿كَمْ آتَيْنَاهُم مِّنْ آيَةٍ بَيِّنَةٍ﴾</bdi> (2) in non-affirmative speech (<bdi>كَلَام غَيْرُ مُوجَب</bdi>): <bdi>نَفْي</bdi> (<bdi>﴿مَا جَاءَنَا مِن بَشِيرٍ وَلَا نَذِيرٍ﴾</bdi>), <bdi>اسْتِفْهَام</bdi> meaning نفي (<bdi>﴿هَلْ مِنْ خَالِقٍ غَيْرُ اللَّهِ﴾</bdi>), or plain استفهام with هل (<bdi>﴿هَلْ مِن مَّزِيدٍ﴾</bdi>).`,
          sample: `الباء سماعا — مبتدأ حسب، خبر حسب، فاعل كفى (بمعنى حسب)<br>كفى بمعنى وقى — لا تأخذ الباء الزائدة<br>من الزائدة — تمييز كم الخبرية، وكلام غير موجب (نفي، استفهام بمعنى نفي، استفهام بهل)`,
          exercise: {
            prompt: `When does كفى NOT take الباء الزائدة on its فاعل؟`,
            kind: 'mcq',
            options: ['When كفى means وقى (to protect), not حسب', 'كفى always takes it, with no exception', 'When the فاعل is a ضمير', 'When كفى is فعل أمر'],
            correct: 0,
          },
        },
        {
          heading: 'اللام الزائدة والكاف الزائدة',
          body: `اللام الزائدة occurs in four places: (1) on the <bdi>خَبَر</bdi> of a negated <bdi>كَانَ</bdi> — called <bdi>لَامُ الْجُحُود</bdi> — <bdi>﴿فَمَا كَانَ اللَّهُ لِيَظْلِمَهُمْ﴾</bdi> (2) on the <bdi>فَاعِل</bdi> — <bdi>لَامُ التَّبْيِين</bdi> — <bdi>﴿هَيْتَ لَكَ﴾</bdi> (3) on the fronted <bdi>مَعْمُول</bdi> of a فعل — <bdi>﴿إِن كُنتُمْ لِلرُّؤْيَا تَعْبُرُونَ﴾</bdi> (4) on the معمول of <bdi>شِبْهِ الْفِعْل</bdi> — called <bdi>لَامُ التَّقْوِيَة</bdi>, strengthening the weak government of a non-فعل — <bdi>﴿فَعَّالٌ لِّمَا يُرِيدُ﴾</bdi>. <bdi>الْكَافُ الزَّائِدَة</bdi> appears in <bdi>﴿لَيْسَ كَمِثْلِهِ شَيْءٌ﴾</bdi>: were الكاف not زائدة here, the phrase would mean "there is nothing like His like" — implying He has a like — so the زائدة reading avoids this and simply emphasises the نفي of any similarity.`,
          sample: `اللام الزائدة (٤) — لام الجحود (خبر كان المنفية)، لام التبيين (الفاعل)، معمول الفعل المقدَّم، لام التقوية (معمول شبه الفعل)<br>الكاف الزائدة — ﴿ليس كمثله شيء﴾؛ لو لم تكن زائدة للزم أن له مثلا`,
          exercise: {
            prompt: `What would ﴿ليس كمثله شيء﴾ imply if the كاف were NOT redundant؟`,
            kind: 'mcq',
            options: ['That He has a "like" — "nothing is like His like" — which the زائدة reading avoids', 'Nothing would change in meaning at all', 'The آية would become grammatically invalid', 'It would mean the exact opposite'],
            correct: 0,
          },
        },
        {
          heading: 'حروف عند البعض، وحذف حرف الجر، والتضمين',
          body: `Four حروف are treated as جر حروف only <bdi>عِنْدَ الْبَعْض</bdi>: <bdi>لَعَلَّ</bdi> in the dialect of <bdi>عُقَيْل</bdi> (<bdi>لَعَلَّ اللَّهِ فَضَّلَكُمْ عَلَيْنَا</bdi>); <bdi>خَلَا</bdi> and <bdi>عَدَا</bdi> in <bdi>اسْتِثْنَاء</bdi>, though most grammarians treat them as <bdi>أَفْعَال</bdi>; <bdi>مَتَى</bdi> meaning مِن in the dialect of <bdi>هُذَيْل</bdi>; and <bdi>كَيْ</bdi> meaning اللام of reason before <bdi>مَا الِاسْتِفْهَامِيَّة</bdi> — <bdi>كَيْمَهْ عَصَيْتَ اللَّهَ؟</bdi> (= لِمَهْ). A حرف الجر may also be omitted (<bdi>حُذِفَ وَإِيصَال</bdi>, also <bdi>اتِّسَاع</bdi>): by regular rule (<bdi>قِيَاسًا</bdi>) before <bdi>أَنْ</bdi> and <bdi>أَنَّ</bdi> — <bdi>﴿يَأْمُرُكُمْ أَن تُؤَدُّوا الْأَمَانَاتِ﴾</bdi> (أصل: بأن) — or by transmission (<bdi>سَمَاعًا</bdi>) — <bdi>﴿إِنَّ عَادًا كَفَرُوا رَبَّهُمْ﴾</bdi> (أصل: بربهم); the اسم left behind is called <bdi>مَنْصُوبٌ بِنَزْعِ الْخَافِض</bdi>. Separately: a single <bdi>عَامِل</bdi> cannot take two معمولات from the same aspect (<bdi>جِهَة</bdi>) except by <bdi>تَبَعِيَّة</bdi> — <bdi>سَافَرْتُ صَبَاحًا وَمَسَاءً</bdi>, not <bdi>سَافَرْتُ صَبَاحًا مَسَاءً</bdi> — though it CAN take two ظرفان from two different جهتين, as in <bdi>﴿يَتَوَارَىٰ مِنَ الْقَوْمِ مِن سُوءِ مَا بُشِّرَ بِهِ﴾</bdi>. <bdi>التَّضْمِين</bdi> is when a <bdi>ظَرْفُ اللَّغْو</bdi> is made the معمول of a <b>different, omitted</b> فعل: <bdi>﴿وَلَا تَأْكُلُوا أَمْوَالَهُمْ إِلَىٰ أَمْوَالِكُمْ﴾</bdi> = <bdi>لَا تَأْكُلُوا أَمْوَالَهُمْ وَلَا تَضُمُّوهَا إِلَىٰ أَمْوَالِكُمْ</bdi>.`,
          sample: `عند البعض (٤) — لعل (عقيل)، خلا وعدا (أفعال عند الأكثر)، متى (هذيل)، كي بمعنى اللام<br>حذف حرف الجر — قياسا قبل أن/أنّ، سماعا في مواضع أخرى؛ الاسم بعده منصوب بنزع الخافض<br>تعدد المعمول — لا معمولان من جهة واحدة إلا بالتبعية؛ يجوز من جهتين<br>التضمين — الظرف معمول لفعل آخر محذوف`,
          exercise: {
            prompt: `What is the omission of حرف الجر called, and what is the resulting اسم called؟`,
            kind: 'mcq',
            options: ['حذف وإيصال (or اتساع); the اسم left behind is منصوب بنزع الخافض', 'التضمين; the اسم is مجرور بالمجاورة', 'القلب; the اسم is مرفوع بنزع الخافض', 'الحذف has no name in النحو'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'رُبَّ expresses either تكثير or تقليل. What decides which one is meant؟',
          options: ['Context (القرينة)', 'The gender of its مجرور', 'Whether ما follows it', 'It always means تكثير, never تقليل'],
          correct: 0,
        },
        {
          q: 'What can the مجرور of رُبَّ be؟',
          options: ['An indefinite اسم ظاهر, or an ambiguous ضمير clarified by a تمييز', 'Any definite اسم', 'Only a ضمير', 'Only a جملة فعلية'],
          correct: 0,
        },
        {
          q: 'What does ما الكافة do when added to رُبَّ؟',
          options: ['Stops it from operating, and lets it enter جمل فعلية and definite أسماء', 'Makes it operate more strongly', 'Turns it into a فعل', 'Restricts it to poetry only'],
          correct: 0,
        },
        {
          q: 'Where does اللام الزائدة occur? (4 places)',
          options: ['خبر كان المنفية، الفاعل، معمول الفعل المقدَّم، معمول شبه الفعل', 'Only on the فاعل', 'Only in الاستثناء', 'Only with أفعال القلوب'],
          correct: 0,
        },
        {
          q: 'خلا and عدا, used in الاستثناء, are treated by most grammarians as:',
          options: ['أفعال, not جر حروف', 'جر حروف only', 'أسماء', 'ظروف زمان'],
          correct: 0,
        },
        {
          q: 'A single عامل can take two ظرفان at once when:',
          options: ['they come from two different جهتين', 'they come from the same جهة', 'one of them is محذوف', 'it is never possible at all'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الحروف الثلاثة الشبيهة بالزائد',
          kind: 'mcq',
          prompt: 'رُبَّ، من التبعيضية، and حاشا together make up:',
          options: ['حروف الجر الشبيهة بالزائد', 'حروف الجر الزائدة', 'حروف الجر الأصلية', 'أحرف القسم'],
          correct: 0,
        },
        {
          title: 'موضع رُبَّ',
          kind: 'mcq',
          prompt: '«يا رب كاسيات في الدنيا عاريات في الآخرة» shows رُبَّ preceded by:',
          options: ['a vocative حرف, the one exception to its صدر الكلام rule', 'a حرف جر آخر', 'a فعل ماضٍ', 'nothing — this is invalid Arabic'],
          correct: 0,
        },
        {
          title: 'مجرور رب موصوف',
          kind: 'mcq',
          prompt: 'The مجرور of رُبَّ is usually موصوف — described — by:',
          options: ['a single word or a جملة', 'a تمييز only, never anything else', 'a حال only', 'it is never described'],
          correct: 0,
        },
        {
          title: 'تخفيف ربما',
          kind: 'mcq',
          prompt: '﴿ربما يود الذين كفروا لو كانوا مسلمين﴾ shows رُبَّمَا:',
          options: ['lightened (تخفيف) to رُبَمَا', 'used with its full تشديد', 'replaced by مِن', 'used without ما الكافة'],
          correct: 0,
        },
        {
          title: 'حذف رب',
          kind: 'mcq',
          prompt: 'وليل كموج البحر أرخى سدوله — the جر here comes from:',
          options: ['an omitted رُبَّ whose عمل remains', 'a stated رُبَّ', 'الباء الزائدة', 'اللام الزائدة'],
          correct: 0,
        },
        {
          title: 'من بمعنى رب',
          kind: 'mcq',
          prompt: '«كان صلى الله عليه وسلم مما يحرك شفتيه» — من here carries the meaning of:',
          options: ['رُبَّ, because ما follows it (مما)', 'التبعيض', 'ابتداء الغاية, its usual meaning', 'الزائدة'],
          correct: 0,
        },
        {
          title: 'مثال حاشا',
          kind: 'mcq',
          prompt: 'هلك الناس حاشا العالمِ illustrates:',
          options: ['حاشا as حرف جر شبيه بالزائد', 'حاشا as فعل استثناء', 'حاشا as اسم', 'حاشا as ظرف'],
          correct: 0,
        },
        {
          title: 'الباء الزائدة: خبر نفي',
          kind: 'mcq',
          prompt: '﴿وما ربك بظلام للعبيد﴾ — بظلام illustrates الباء الزائدة in:',
          options: ['خبر نفي with ما', 'خبر استفهام with هل', 'التأكيد المعنوي', 'فاعل أفعِل به'],
          correct: 0,
        },
        {
          title: 'الباء الزائدة: التأكيد المعنوي',
          kind: 'mcq',
          prompt: 'نظف الأمير المسجد بنفسه illustrates الباء الزائدة in:',
          options: ['التأكيد المعنوي with نفس', 'خبر نفي', 'فاعل أفعِل به', 'مبتدأ بعد إذا الفجائية'],
          correct: 0,
        },
        {
          title: 'الباء الزائدة: فاعل أفعِل به',
          kind: 'mcq',
          prompt: '﴿أسمع بهم وأبصر﴾ illustrates الباء الزائدة on:',
          options: ['the فاعل of أفعِل به (تعجب)', 'the خبر of نفي', 'the مبتدأ after إذا الفجائية', 'the تمييز of كم'],
          correct: 0,
        },
        {
          title: 'الباء الزائدة سماعا: فاعل كفى',
          kind: 'mcq',
          prompt: '﴿كفى بالله شهيدا﴾ illustrates الباء الزائدة on:',
          options: ['the فاعل of كفى (meaning حسب)', 'the خبر of كفى', 'the مفعول به of كفى', 'nothing — الباء here is أصلية'],
          correct: 0,
        },
        {
          title: 'كفى بمعنى وقى',
          kind: 'mcq',
          prompt: '﴿وكفى الله المؤمنين القتال﴾ — كفى here does NOT take الباء الزائدة because it means:',
          options: ['وقى (to protect), not حسب', 'حسب, its usual meaning here', 'ظن', 'ترك'],
          correct: 0,
        },
        {
          title: 'من الزائدة: تمييز كم',
          kind: 'mcq',
          prompt: '﴿كم آتيناهم من آية بينة﴾ illustrates مِن الزائدة on:',
          options: ['the تمييز of كم الخبرية', 'the فاعل', 'the مبتدأ', 'the حال'],
          correct: 0,
        },
        {
          title: 'من الزائدة: كلام غير موجب',
          kind: 'mcq',
          prompt: '﴿ما جاءنا من بشير ولا نذير﴾ illustrates مِن الزائدة in:',
          options: ['نفي, one of the three كلام غير موجب contexts', 'كلام موجب مثبت', 'الاستثناء', 'القسم'],
          correct: 0,
        },
        {
          title: 'لام الجحود',
          kind: 'mcq',
          prompt: '﴿فما كان الله ليظلمهم﴾ illustrates:',
          options: ['لام الجحود — the زائدة لام on the خبر of a negated كان', 'لام التبيين', 'لام التقوية', 'لام الأمر'],
          correct: 0,
        },
        {
          title: 'لام التقوية',
          kind: 'mcq',
          prompt: '﴿فعال لما يريد﴾ illustrates:',
          options: ['لام التقوية — strengthening the weak government of شبه الفعل', 'لام الجحود', 'لام التبيين', 'لام العاقبة'],
          correct: 0,
        },
        {
          title: 'لعل عند عقيل',
          kind: 'mcq',
          prompt: 'لعل اللهِ فضلكم علينا, treating لعل as a حرف جر, reflects the dialect of:',
          options: ['عقيل', 'هذيل', 'قريش', 'تميم'],
          correct: 0,
        },
        {
          title: 'التضمين',
          kind: 'mcq',
          prompt: 'التضمين, with a ظرف اللغو, means the ظرف is made the معمول of:',
          options: ['a different, omitted فعل', 'the same فعل it already belongs to', 'no فعل at all — it becomes مبتدأ', 'a حرف جر instead of a فعل'],
          correct: 0,
        },
        {
          title: 'تركيب: الشبيه بالزائد أم الزائد؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف: شبيه بالزائد or زائد?',
          source: 'رُبَّ / حاشا / الباء في ﴿ليس بظلام﴾ / اللام في ﴿فعال لما يريد﴾',
          words: ['رُبَّ', 'حاشا', 'الباء', 'اللام'],
          labels: ['شبيه بالزائد', 'شبيه بالزائد', 'زائد', 'زائد'],
          distractors: ['أصلي'],
        },
        {
          title: 'تركيب: مواضع الباء الزائدة',
          kind: 'tarkeeb',
          instruction: 'Classify each example of الباء الزائدة by its موضع.',
          source: '﴿وما ربك بظلام للعبيد﴾ / نظف الأمير المسجد بنفسه / ﴿أسمع بهم وأبصر﴾ / دخل الرجل فإذا بابنه يصلي',
          words: ['بظلام', 'بنفسه', 'بهم', 'بابنه'],
          labels: ['خبر نفي', 'التأكيد المعنوي', 'فاعل أفعِل به', 'مبتدأ بعد إذا الفجائية'],
          distractors: ['خبر استفهام'],
        },
        {
          title: 'تركيب: مواضع اللام الزائدة',
          kind: 'tarkeeb',
          instruction: 'Classify each example of اللام الزائدة by its اسم.',
          source: '﴿فما كان الله ليظلمهم﴾ / ﴿هيت لك﴾ / ﴿فعال لما يريد﴾',
          words: ['ليظلمهم', 'لك', 'لما يريد'],
          labels: ['لام الجحود', 'لام التبيين', 'لام التقوية'],
          distractors: ['لام الأمر'],
        },
        {
          title: 'تركيب: حروف عند البعض',
          kind: 'tarkeeb',
          instruction: 'Match each حرف عند البعض to the dialect or condition that makes it a جر حرف.',
          source: 'لعل / متى بمعنى مِن / كي بمعنى اللام',
          words: ['لعل', 'متى', 'كي'],
          labels: ['لغة عقيل', 'لغة هذيل', 'قبل ما الاستفهامية'],
          distractors: ['لغة تميم'],
        },
        {
          title: 'تركيب: قياسا أم سماعا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حذف حرف جر: قياسا or سماعا?',
          source: '﴿يأمركم أن تؤدوا الأمانات﴾ / ﴿واشهدوا أني بريء﴾ / ﴿إن عادا كفروا ربهم﴾',
          words: ['أن تؤدوا', 'أني بريء', 'كفروا ربهم'],
          labels: ['قياسا', 'قياسا', 'سماعا'],
          distractors: ['ممتنع'],
        },
      ],
    },
  ],
};
