// Module 05 — النواسخ الحرفية (The Particle Cancelling-Governors)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__2 الْحَرْفِ__1 الْحَرْفِ الْعَامِلِ__2 الحرف الأخرى.apkg,
// 62 notes) prepared for this conversion. Definitions and examples are kept
// faithful to the source notes. Concept bodies are short by design (a
// sentence or two, not teaching prose); quiz/bank question text is English
// with Arabic grammatical terms left in Arabic.
//
// The source deck covers the other عامل حروف beyond حروف الجر (§2 of
// الحرف العامل, itself §2 of الحرف, itself §2 of العامل وغير العامل):
// إنّ وأخواتها (الحروف المشبهة بالفعل) and their mواضع, التخفيف (lightening)
// and ما الكافة, لا لنفي الجنس, and الحروف المشبهة بليس. Together with
// أفعال القلوب and الأفعال الناقصة (Modules 02–03), these five families are
// the whole of النواسخ — عوامل entering upon مبتدأ + خبر.

export default {
  id: '05',
  title: 'النواسخ الحرفية',
  heading: 'العامل وغير العامل',
  subheading: 'الحرف العامل',
  blurb: 'إنّ وأخواتها (الحروف المشبهة بالفعل) and the eleven/ten مواضع of إنّ and أنّ, كأن ولكن ولعل وليت, التخفيف (lightening) and ما الكافة, and لا لنفي الجنس with the حروف المشبهة بليس.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'إلا وإنّ',
      subtitle: 'The Verb-Like Letters — الحروف المشبهة بالفعل, إنّ, and where المكسورة occurs',
      concepts: [
        {
          heading: 'إلا، ومدخل الحروف المشبهة بالفعل',
          body: `<bdi>إِلَّا</bdi> is the second of the four categories of <bdi>حُرُوف تَعْمَل فِي الِاسْم</bdi> — a حرف putting one اسم in <bdi>نَصْب</bdi>, as in <bdi>﴿فَسَجَدُوا إِلَّا إِبْلِيسَ﴾</bdi>. This module turns to the third category: <bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِالْفِعْل</bdi>, six of them — <bdi>إِنَّ، أَنَّ، كَأَنَّ، لَكِنَّ، لَعَلَّ، لَيْتَ</bdi> — which put the first اسم in <b>نصب</b> (called their اسم) and the second in <b>رفع</b> (called their خبر).`,
          sample: `إلا (استثناء) — ﴿فسجدوا إلا إبليس﴾، نصب<br>الحروف المشبهة بالفعل (٦) — إن، أن، كأن، لكن، لعل، ليت<br>عملها — نصب الاسم، رفع الخبر`,
          exercise: {
            prompt: `What do الحروف المشبهة بالفعل do grammatically؟`,
            kind: 'mcq',
            options: ['They put the first اسم in نصب (their اسم) and the second in رفع (their خبر)', 'They put the first اسم in رفع and the second in نصب', 'They put both أسماء in جر', 'They govern only أفعال, never أسماء'],
            correct: 0,
          },
        },
        {
          heading: 'معنى إنّ وموضعها',
          body: `<bdi>إِنَّ</bdi> carries the meaning of <bdi>التَّأْكِيد</bdi> (also called <bdi>التَّحْقِيق</bdi>), as in <bdi>﴿إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ﴾</bdi>. With its كسرة, إِنَّ occurs specifically in the position of a <b>جُمْلَة</b> (<bdi>مَوْضِعُ الْجُمْلَة</bdi>) — unlike أَنَّ, which will occupy the position of a single word.`,
          sample: `إنّ — التأكيد/التحقيق، ﴿إن الله غفور رحيم﴾<br>موضع إنّ المكسورة — موضع الجملة`,
          exercise: {
            prompt: `In what kind of position does إنّ (with كسرة) occur؟`,
            kind: 'mcq',
            options: ['In the position of a جملة', 'In the position of a single مفرد word', 'In the position of a حرف', 'It occupies no position at all'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع إنّ المكسورة الأحد عشر',
          body: `إِنَّ المكسورة is required in eleven مواضع: (1) at the <bdi>ابْتِدَاء</bdi>, real or effectively so after a <bdi>حَرْفُ تَنْبِيه</bdi> or <bdi>حَرْفُ زَجْر</bdi> (2) after <bdi>الْقَسَم</bdi> (3) after <bdi>الْقَوْل</bdi> (4) after <bdi>وَاوُ الْحَال</bdi> (5) after <bdi>حَتَّى الِابْتِدَائِيَّة</bdi> (6) in the <bdi>صِلَة</bdi> (7) in the <bdi>نَعْت</bdi> (8) before the <bdi>لَامُ الْمُعَلِّقَة</bdi> (9) after إِلَّا of <bdi>حَصْر</bdi> (10) after <bdi>حَيْثُ</bdi> (11) in the خبر of an <bdi>اسْمُ عَيْن</bdi>. In <bdi>﴿أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ﴾</bdi>, the حرف تنبيه <bdi>أَلَا</bdi> makes what follows count as ابتداء <bdi>حُكْمًا</bdi>, which is why إنّ (not أنّ) is used.`,
          sample: `مواضع إنّ المكسورة (١١) — الابتداء (حقيقة أو حكما)، بعد القسم، بعد القول، بعد واو الحال، بعد حتى الابتدائية، في الصلة، في النعت، قبل اللام المعلقة، بعد إلا الحصر، بعد حيث، في خبر اسم عين<br>﴿ألا إنهم هم المفسدون﴾ — بعد حرف تنبيه، ابتداء حكما`,
          exercise: {
            prompt: `Why is إنّ (not أنّ) used in ﴿أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ﴾؟`,
            kind: 'mcq',
            options: ['Because after a حرف تنبيه the position counts as ابتداء حكما, which requires the كسرة of إنّ', 'Because أنّ can never follow a حرف تنبيه under any circumstance', 'Because ألا is itself a form of إنّ', 'There is no rule — both readings are equally valid here'],
            correct: 0,
          },
        },
        {
          heading: 'إلا مع إنّ أو أنّ، وحيث',
          body: `Which of إنّ or أنّ follows إِلَّا depends on which sense of إلا it is: إلا of <b>حَصْر</b> takes إنّ, as in <bdi>﴿وَمَا أَرْسَلْنَا قَبْلَكَ مِنَ الْمُرْسَلِينَ إِلَّا إِنَّهُمْ لَيَأْكُلُونَ الطَّعَامَ﴾</bdi>; إلا of <b>اسْتِثْنَاء</b> takes أنّ, as in <bdi>هُوَ شُجَاعٌ إِلَّا أَنَّهُ لَيْسَ بِكَرِيمٍ</bdi>. After <bdi>حَيْثُ</bdi>, إنّ is used, as in <bdi>جَلَسْتُ حَيْثُ إِنَّ عَلِيًّا جَالِسٌ</bdi> — though some disagree, since حيث is مضاف to a جملة.`,
          sample: `إلا الحصر + إنّ — ﴿وما أرسلنا قبلك من المرسلين إلا إنهم ليأكلون الطعام﴾<br>إلا الاستثناء + أنّ — هو شجاع إلا أنه ليس بكريم<br>حيث + إنّ — جلست حيث إن عليا جالس`,
          exercise: {
            prompt: `When does إلا take إنّ after it, and when أنّ؟`,
            kind: 'mcq',
            options: ['إلا of حصر takes إنّ; إلا of استثناء takes أنّ', 'إلا of حصر takes أنّ; إلا of استثناء takes إنّ', 'إلا always takes إنّ, regardless of sense', 'إلا never takes either إنّ or أنّ after it'],
            correct: 0,
          },
        },
        {
          heading: 'إنّ أم أنّ في الخبر',
          body: `The choice between إنّ and أنّ in a خبر tracks what kind of اسم it describes: إنّ appears in the خبر of an <b>اسم عين</b> (a concrete entity), as in <bdi>﴿إِنَّ الَّذِينَ آمَنُوا</bdi>... <bdi>إِنَّ اللَّهَ يَفْصِلُ بَيْنَهُمْ﴾</bdi>; أنّ appears in the خبر of an <b>اسم معنى</b>, as in <bdi>الْمَرْجُو أَنَّهُ مَغْفُورٌ</bdi>.`,
          sample: `إنّ في خبر اسم عين — ﴿إن الذين آمنوا...إن الله يفصل بينهم﴾<br>أنّ في خبر اسم معنى — المرجو أنه مغفور`,
          exercise: {
            prompt: `When is إنّ used in a خبر, and when أنّ؟`,
            kind: 'mcq',
            options: ['إنّ in the خبر of an اسم عين; أنّ in the خبر of an اسم معنى', 'إنّ in the خبر of an اسم معنى; أنّ in the خبر of an اسم عين', 'Both are used interchangeably with no distinction', 'Neither can occur inside a خبر'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many الحروف المشبهة بالفعل are there؟',
          options: ['ستة', 'خمسة', 'سبعة', 'أربعة'],
          correct: 0,
        },
        {
          q: 'الحروف المشبهة بالفعل put the first اسم in نصب and the second in:',
          options: ['رفع', 'نصب', 'جر', 'لا خبر لها'],
          correct: 0,
        },
        {
          q: 'إنّ carries the meaning of:',
          options: ['التأكيد (التحقيق)', 'التشبيه', 'التمني', 'الاستدراك'],
          correct: 0,
        },
        {
          q: 'Why is إنّ used in ﴿وَالْقُرْآنِ الْحَكِيمِ إِنَّكَ لَمِنَ الْمُرْسَلِينَ﴾؟',
          options: ['It follows القسم — one of the مواضع of إنّ المكسورة', 'It follows القول', 'It occurs in a نعت', 'It follows إلا of حصر'],
          correct: 0,
        },
        {
          q: 'Why is إنّ used in ﴿قَالَ إِنِّي عَبْدُ اللَّهِ﴾؟',
          options: ['It follows القول', 'It follows القسم', 'It follows حتى الابتدائية', 'It occurs before اللام المعلقة'],
          correct: 0,
        },
        {
          q: 'Why is إنّ used in ﴿وَاللَّهُ يَعْلَمُ إِنَّكَ لَرَسُولُهُ﴾؟',
          options: ['Because of اللام المعلقة, which suspends يعلم and lets the جملة begin afresh with إنّ', 'Because يعلم is itself a حرف مشبه بالفعل', 'Because الله is an اسم نكرة here', 'Because إنّ here means التمني'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'إلا: أي فئة؟',
          kind: 'mcq',
          prompt: 'إلا belongs to which category of حروف تعمل في الاسم؟',
          options: ['a حرف that puts one اسم in نصب', 'a حرف that puts one اسم in جر', 'a حرف that puts اسم in نصب and خبر in رفع', 'a حرف that puts اسم in رفع and خبر in نصب'],
          correct: 0,
        },
        {
          title: 'الستة بالاسم',
          kind: 'mcq',
          prompt: 'List the six الحروف المشبهة بالفعل.',
          options: ['إنّ، أنّ، كأنّ، لكنّ، لعلّ، ليت', 'إنّ، أنّ، لن، لم، لا، ما', 'كان، أصبح، ظل، بات، صار، ليس', 'الباء، من، إلى، عن، على، في'],
          correct: 0,
        },
        {
          title: 'موضع إنّ المكسورة',
          kind: 'mcq',
          prompt: 'إنّ المكسورة occurs in the position of:',
          options: ['جملة', 'مفرد', 'حرف', 'ظرف'],
          correct: 0,
        },
        {
          title: 'موضع أول: الابتداء',
          kind: 'mcq',
          prompt: 'One of the eleven مواضع of إنّ المكسورة is:',
          options: ['الابتداء، حقيقة أو حكما', 'بعد أفعال القلوب', 'بعد أفعال المقاربة', 'بعد التمييز'],
          correct: 0,
        },
        {
          title: 'إنّ بعد القسم',
          kind: 'mcq',
          prompt: '﴿وَالْقُرْآنِ الْحَكِيمِ إِنَّكَ لَمِنَ الْمُرْسَلِينَ﴾ illustrates إنّ المكسورة:',
          options: ['بعد القسم', 'بعد القول', 'في الصلة', 'في النعت'],
          correct: 0,
        },
        {
          title: 'إنّ بعد القول',
          kind: 'mcq',
          prompt: '﴿قَالَ إِنِّي عَبْدُ اللَّهِ﴾ illustrates إنّ المكسورة:',
          options: ['بعد القول', 'بعد القسم', 'بعد واو الحال', 'بعد حيث'],
          correct: 0,
        },
        {
          title: 'إنّ في الصلة',
          kind: 'mcq',
          prompt: 'مَا إِنْ مَفَاتِحَهُ لَتَنُوءُ بِالْعُصْبَةِ illustrates إنّ المكسورة:',
          options: ['في الصلة (صلة الموصول)', 'في النعت', 'بعد إلا الحصر', 'قبل اللام المعلقة'],
          correct: 0,
        },
        {
          title: 'إنّ في النعت',
          kind: 'mcq',
          prompt: 'نَظَرْتُ إِلَى رَجُلٍ إِنَّهُ صَالِحٌ illustrates إنّ المكسورة:',
          options: ['في النعت (تصف رجل)', 'في الصلة', 'بعد حيث', 'في خبر اسم عين'],
          correct: 0,
        },
        {
          title: 'إنّ قبل اللام المعلقة',
          kind: 'mcq',
          prompt: '﴿وَاللَّهُ يَعْلَمُ إِنَّكَ لَرَسُولُهُ﴾ — why إنّ, not أنّ?',
          options: ['اللام المعلقة suspends يعلم, so the جملة begins afresh with إنّ', 'يعلم is a فعل قلب of الظن', 'الرسول is an اسم نكرة', 'There is no rule involved'],
          correct: 0,
        },
        {
          title: 'إلا الحصر',
          kind: 'mcq',
          prompt: '﴿وَمَا أَرْسَلْنَا قَبْلَكَ مِنَ الْمُرْسَلِينَ إِلَّا إِنَّهُمْ لَيَأْكُلُونَ الطَّعَامَ﴾ — إلا here is:',
          options: ['إلا الحصر, which takes إنّ', 'إلا الاستثناء, which takes أنّ', 'إلا التي لا معنى لها', 'a حرف عطف, not إلا at all'],
          correct: 0,
        },
        {
          title: 'إلا الاستثناء',
          kind: 'mcq',
          prompt: 'هُوَ شُجَاعٌ إِلَّا أَنَّهُ لَيْسَ بِكَرِيمٍ — إلا here is:',
          options: ['إلا الاستثناء, which takes أنّ', 'إلا الحصر, which takes إنّ', 'إلا زائدة بلا معنى', 'إلا للتوكيد'],
          correct: 0,
        },
        {
          title: 'حيث وإنّ',
          kind: 'mcq',
          prompt: 'جَلَسْتُ حَيْثُ إِنَّ عَلِيًّا جَالِسٌ — what follows حيث?',
          options: ['إنّ, one of the مواضع of إنّ المكسورة', 'أنّ, since حيث is مضاف إلى مفرد', 'لعل, for التوقع', 'كأن, for التشبيه'],
          correct: 0,
        },
        {
          title: 'إنّ في خبر اسم عين',
          kind: 'mcq',
          prompt: '﴿إِنَّ الَّذِينَ آمَنُوا...إِنَّ اللَّهَ يَفْصِلُ بَيْنَهُمْ﴾ — this is إنّ in the خبر of:',
          options: ['اسم عين (كيان محسوس)', 'اسم معنى', 'اسم إشارة', 'اسم موصول فقط'],
          correct: 0,
        },
        {
          title: 'أنّ في خبر اسم معنى',
          kind: 'mcq',
          prompt: 'الْمَرْجُو أَنَّهُ مَغْفُورٌ — this is أنّ in the خبر of:',
          options: ['اسم معنى (المرجو)', 'اسم عين', 'اسم فاعل', 'اسم مفعول فقط'],
          correct: 0,
        },
        {
          title: 'عدد المواضع',
          kind: 'mcq',
          prompt: 'How many مواضع does إنّ المكسورة have؟',
          options: ['أحد عشر', 'عشرة', 'تسعة', 'اثنا عشر'],
          correct: 0,
        },
        {
          title: 'عمل المشبهة بالفعل',
          kind: 'mcq',
          prompt: 'الحروف المشبهة بالفعل resemble which part of speech in their government?',
          options: ['الفعل', 'الاسم', 'الظرف', 'حروف الجر'],
          correct: 0,
        },
        {
          title: 'واو الحال وإنّ',
          kind: 'mcq',
          prompt: 'One of the eleven مواضع of إنّ المكسورة is after:',
          options: ['واو الحال', 'واو العطف فقط', 'واو القسم', 'واو الجماعة'],
          correct: 0,
        },
        {
          title: 'حتى الابتدائية وإنّ',
          kind: 'mcq',
          prompt: 'إنّ المكسورة also occurs after:',
          options: ['حتى الابتدائية', 'حتى الجارة', 'حتى العاطفة', 'حتى الناصبة'],
          correct: 0,
        },
        {
          title: 'تركيب: مواضع إنّ من الأمثلة',
          kind: 'tarkeeb',
          instruction: 'Match each example to the موضع of إنّ المكسورة it illustrates.',
          source: '﴿ألا إنهم هم المفسدون﴾ / ﴿والقرآن الحكيم إنك لمن المرسلين﴾ / ﴿قال إني عبد الله﴾ / نظرت إلى رجل إنه صالح',
          words: ['ألا إنهم', 'والقرآن الحكيم إنك', 'قال إني', 'إنه صالح'],
          labels: ['بعد حرف تنبيه (ابتداء حكما)', 'بعد القسم', 'بعد القول', 'في النعت'],
          distractors: ['في الصلة'],
        },
        {
          title: 'تركيب: إلا وما بعدها',
          kind: 'tarkeeb',
          instruction: 'Classify each إلا by sense, and what follows it.',
          source: 'وما أرسلنا قبلك من المرسلين إلا إنهم ليأكلون الطعام / هو شجاع إلا أنه ليس بكريم',
          words: ['إلا إنهم', 'إلا أنه'],
          labels: ['إلا الحصر، تأخذ إنّ', 'إلا الاستثناء، تأخذ أنّ'],
          distractors: ['إلا الزائدة'],
        },
        {
          title: 'تركيب: إنّ أم أنّ في الخبر',
          kind: 'tarkeeb',
          instruction: 'Classify each خبر: does it call for إنّ (اسم عين) or أنّ (اسم معنى)?',
          source: '﴿إن الذين آمنوا...إن الله يفصل بينهم﴾ / المرجو أنه مغفور',
          words: ['إن الله (خبر الذين)', 'أنه مغفور (خبر المرجو)'],
          labels: ['إنّ، اسم عين', 'أنّ، اسم معنى'],
          distractors: ['كلاهما اسم معنى'],
        },
        {
          title: 'تركيب: الحروف المشبهة بالفعل الستة',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف: من الحروف المشبهة بالفعل or not?',
          source: 'إنّ / لكنّ / إلا / كأنّ',
          words: ['إنّ', 'لكنّ', 'إلا', 'كأنّ'],
          labels: ['من الستة', 'من الستة', 'ليس منها', 'من الستة'],
          distractors: ['من الحروف المشبهة بليس'],
        },
        {
          title: 'تركيب: عمل الحروف المشبهة بالفعل',
          kind: 'tarkeeb',
          instruction: "Classify what الحروف المشبهة بالفعل do to each اسم position.",
          source: 'الاسم الأول / الاسم الثاني (الخبر)',
          words: ['الاسم الأول', 'الاسم الثاني'],
          labels: ['نصب', 'رفع'],
          distractors: ['جر'],
        },
        {
          title: 'تركيب: حيث والصلة',
          kind: 'tarkeeb',
          instruction: 'Classify what follows each of these: إنّ or أنّ.',
          source: 'جلست حيث إن عليا جالس / ما إن مفاتحه لتنوء بالعصبة',
          words: ['حيث', 'صلة الموصول'],
          labels: ['إنّ', 'إنّ'],
          distractors: ['أنّ'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'أنّ والقواعد المشتركة',
      subtitle: "أnna's Positions — أنّ المفتوحة's ten مواضع, and rules إنّ and أنّ share",
      concepts: [
        {
          heading: 'أنّ: تعريفها وطبيعتها',
          body: `<bdi>أَنَّ</bdi> is a <bdi>حَرْفُ مَصْدَرٍ لِلتَّأْكِيد</bdi>; unlike إنّ, it occurs in the position of a <b>single word</b> (<bdi>مَوْضِعُ الْمُفْرَد</bdi>) — أنّ together with its جملة is interpreted as a <bdi>مَصْدَر</bdi>. In fact, of all six الحروف المشبهة بالفعل, every one forms a <bdi>جُمْلَة</bdi> with its اسم وخبر <b>except</b> أنّ, which alone (with what follows) stands in the <bdi>تَأْوِيل</bdi> of a مصدر.`,
          sample: `أنّ — حرف مصدر للتأكيد، موضع المفرد<br>الاستثناء — كل الستة جمل إلا أنّ، فهي مع ما بعدها مصدر`,
          exercise: {
            prompt: `Which of the الحروف المشبهة بالفعل forms a جملة with its اسم وخبر, and which does not؟`,
            kind: 'mcq',
            options: ['All of them do except أنّ — it and what follows is a مصدر instead', 'All six of them do, without exception', 'None of them form a جملة at all', 'Only إنّ and أنّ form a جملة'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع أنّ المفتوحة العشرة',
          body: `أنّ المفتوحة occurs in ten مواضع: (1) <bdi>فَاعِل</bdi>, as in <bdi>﴿حَتَّى يَتَبَيَّنَ لَهُمْ أَنَّهُ الْحَقُّ﴾</bdi> (2) <bdi>نَائِبُ فَاعِل</bdi>, as in <bdi>﴿قُلْ أُوحِيَ إِلَيَّ أَنَّهُ اسْتَمَعَ نَفَرٌ مِنَ الْجِنِّ﴾</bdi> (3) <bdi>مَفْعُول</bdi> (4) <bdi>مُبْتَدَأ</bdi> (5) خبر of an اسم معنى (6) after a <bdi>جَرّ حَرْف</bdi> (7) <bdi>مُضَافٌ إِلَيْه</bdi> (8) after <bdi>مُذْ/مُنْذُ</bdi> (9) after <bdi>مَا الْمَصْدَرِيَّةُ الظَّرْفِيَّة</bdi> (10) as a <bdi>تَابِع</bdi> (عطف on a مفرد, or بدل from a مفرد).`,
          sample: `مواضع أنّ المفتوحة (١٠) — فاعل، نائب فاعل، مفعول، مبتدأ، خبر اسم معنى، بعد جر، مضاف إليه، بعد مذ/منذ، بعد ما المصدرية الظرفية، تابع (عطف/بدل)<br>فاعل — ﴿حتى يتبين لهم أنه الحق﴾<br>نائب فاعل — ﴿قل أوحي إلي أنه استمع نفر من الجن﴾`,
          exercise: {
            prompt: `﴿حَتَّى يَتَبَيَّنَ لَهُمْ أَنَّهُ الْحَقُّ﴾ shows أنّ in which موضع؟`,
            kind: 'mcq',
            options: ['فاعل', 'نائب فاعل', 'مفعول', 'مبتدأ'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع يشترك فيها إنّ وأنّ',
          body: `Five مواضع allow BOTH إنّ and أنّ: (1) as the reason (<bdi>عِلَّة</bdi>) for a preceding جملة, as in <bdi>اسْتَغْفِرُوا اللَّهَ إِنَّهُ</bdi>/<bdi>أَنَّهُ غَفُورٌ رَحِيمٌ</bdi> (2) after <bdi>فَاءُ الْجَزَاء</bdi> (3) after <bdi>لَا جَرَمَ</bdi> (فتح predominant) (4) after a <bdi>وَاو</bdi> preceded by a جملة and a مفرد both suitable for عطف (5) after <bdi>إِذَا الْفُجَائِيَّة</bdi>. The choice still carries a nuance: with إنّ the جملة is a new, independent one giving the reason (<bdi>اسْتِئْنَافِيَّة لِلتَّعْلِيل</bdi>); with أنّ a لام is implied (<bdi>لِأَنَّهُ</bdi>) and the whole thing is a مصدر.`,
          sample: `المواضع المشتركة (٥) — علة لجملة سابقة، بعد فاء الجزاء، بعد لا جرم، بعد واو عطف جملة+مفرد، بعد إذا الفجائية<br>استغفروا الله إنه/أنه غفور رحيم — إنّ: استئنافية للتعليل، أنّ: لام مقدرة (لأنه) + مصدر`,
          exercise: {
            prompt: `What determines the choice between إنّ and أنّ in اسْتَغْفِرُوا اللَّهَ إِنَّهُ غَفُورٌ رَحِيمٌ؟`,
            kind: 'mcq',
            options: ['With إنّ the جملة is a new independent one giving the reason; with أنّ a لام is implied and it is a مصدر', 'إنّ is only for Qurʾānic Arabic, أنّ for everyday speech', 'There is no real difference between the two readings', 'أنّ is only valid when the فعل قلب precedes it'],
            correct: 0,
          },
        },
        {
          heading: 'شرط الاسم، وموضع الخبر شبه الجملة',
          body: `The اسم of إنّ/أنّ may not be an اسم that requires <bdi>صَدْرُ الْكَلَام</bdi> — so <bdi>إِنَّ مَنْ صَمَتَ نَجَا</bdi> is invalid. Separately, when the خبر of إنّ is a <bdi>شِبْهُ جُمْلَة</bdi>, its placement between إنّ and its اسم depends on the اسم's definiteness: if the اسم is <b>definite</b>, placing the خبر in the middle is <b>allowed</b>, as in <bdi>﴿إِنَّ إِلَيْنَا إِيَابَهُمْ﴾</bdi>; if the اسم is <b>indefinite</b>, that placement is <b>obligatory</b>, as in <bdi>﴿إِنَّ فِي ذَٰلِكَ لَعِبْرَةً لِأُولِي الْأَبْصَارِ﴾</bdi>.`,
          sample: `شرط الاسم — لا يكون له صدر الكلام، فلا يصح: إن من صمت نجا<br>خبر شبه جملة، اسم معرفة — يجوز التوسط: ﴿إن إلينا إيابهم﴾<br>خبر شبه جملة، اسم نكرة — يجب التوسط: ﴿إن في ذلك لعبرة لأولي الأبصار﴾`,
          exercise: {
            prompt: `When the خبر of إنّ is a شبه جملة, when must it come between إنّ and its اسم rather than after it؟`,
            kind: 'mcq',
            options: ['When the اسم is indefinite (نكرة) — placement in the middle is then obligatory', 'When the اسم is definite (معرفة) — placement in the middle is then obligatory', 'It is always obligatory, regardless of the اسم', 'It is never allowed in the middle, regardless of the اسم'],
            correct: 0,
          },
        },
        {
          heading: 'أحكام إضافية: العطف، الباء، ومعنى لعل',
          body: `A تابع on the اسم of إنّ has two عطف options, whether the خبر is already complete or not: عطف on the <b>لَفْظ</b> (نصب), as in <bdi>﴿إِنَّ وَعْدَ اللَّهِ حَقٌّ وَالسَّاعَةَ لَا رَيْبَ فِيهَا﴾</bdi>, or عطف on the <b>ابْتِدَاء</b> (رفع), as in <bdi>﴿أَئِنَّا لَمَبْعُوثُونَ أَوَآبَاؤُنَا الْأَوَّلُونَ﴾</bdi>. A <bdi>بَاء</bdi> may enter on the خبر of أنّ, as in <bdi>﴿أَوَلَمْ يَرَوْا أَنَّ اللَّهَ</bdi>...<bdi>بِقَادِرٍ عَلَى أَنْ يُحْيِيَ الْمَوْتَىٰ﴾</bdi>. أنّ can also carry the meaning of <bdi>لَعَلَّ</bdi>, as in <bdi>﴿وَمَا يُشْعِرُكُمْ أَنَّهَا إِذَا جَاءَتْ لَا يُؤْمِنُونَ﴾</bdi> (أنّها = لعلّها).`,
          sample: `عطف على اللفظ (نصب) — ﴿إن وعد الله حق والساعةَ لا ريب فيها﴾<br>عطف على الابتداء (رفع) — ﴿أئنا لمبعوثون أوآباؤنا الأولون﴾<br>الباء في خبر أنّ — ﴿أولم يروا أن الله...بقادر على أن يحيي الموتى﴾<br>أنّ بمعنى لعل — ﴿وما يشعركم أنها إذا جاءت لا يؤمنون﴾`,
          exercise: {
            prompt: `Can أنّ carry the meaning of لعل؟`,
            kind: 'mcq',
            options: ['Yes, as in ﴿وَمَا يُشْعِرُكُمْ أَنَّهَا إِذَا جَاءَتْ لَا يُؤْمِنُونَ﴾', 'No, أنّ can never carry that meaning', 'Only كأنّ can carry the meaning of لعل', 'Yes, but only in poetry, never in the Qurʾān'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'أنّ occurs in the position of:',
          options: ['a single مفرد word', 'a whole جملة', 'a حرف', 'a ظرف only'],
          correct: 0,
        },
        {
          q: '﴿قُلْ أُوحِيَ إِلَيَّ أَنَّهُ اسْتَمَعَ نَفَرٌ مِنَ الْجِنِّ﴾ shows أنّ in which موضع؟',
          options: ['نائب فاعل', 'فاعل', 'مبتدأ', 'مضاف إليه'],
          correct: 0,
        },
        {
          q: 'How many شared مواضع allow both إنّ and أنّ؟',
          options: ['خمسة', 'ثلاثة', 'سبعة', 'اثنان'],
          correct: 0,
        },
        {
          q: 'What condition applies to the اسم of إنّ and أنّ؟',
          options: ['It may not require صدر الكلام', 'It must always be نكرة', 'It must always be معرفة', 'It must be a ضمير'],
          correct: 0,
        },
        {
          q: '﴿إِنَّ فِي ذَٰلِكَ لَعِبْرَةً لِأُولِي الْأَبْصَارِ﴾ — the خبر شبه جملة comes between إنّ and its (نكرة) اسم because that placement is here:',
          options: ['واجب (obligatory)', 'ممتنع (forbidden)', 'جائز فقط (merely permitted)', 'نادر جدا (extremely rare)'],
          correct: 0,
        },
        {
          q: '﴿أَوَلَمْ يَرَوْا أَنَّ اللَّهَ...بِقَادِرٍ عَلَى أَنْ يُحْيِيَ الْمَوْتَىٰ﴾ shows which حرف entering the خبر of أنّ؟',
          options: ['الباء', 'اللام', 'الكاف', 'الواو'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'تعريف أنّ',
          kind: 'mcq',
          prompt: 'أنّ is defined as:',
          options: ['حرف مصدر للتأكيد', 'حرف تشبيه', 'حرف استدراك', 'حرف تمني'],
          correct: 0,
        },
        {
          title: 'أنّ: مفعول',
          kind: 'mcq',
          prompt: '﴿فَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِنْ رَبِّهِمْ﴾ shows أنّ in which موضع؟',
          options: ['مفعول', 'فاعل', 'نائب فاعل', 'خبر'],
          correct: 0,
        },
        {
          title: 'أنّ: مبتدأ',
          kind: 'mcq',
          prompt: '﴿وَمِنْ آيَاتِهِ أَنَّكَ تَرَى الْأَرْضَ خَاشِعَةً﴾ shows أنّ in which موضع؟',
          options: ['مبتدأ', 'فاعل', 'مفعول', 'خبر'],
          correct: 0,
        },
        {
          title: 'أنّ: بعد حرف جر',
          kind: 'mcq',
          prompt: '﴿وَاشْهَدْ بِأَنَّا مُسْلِمُونَ﴾ shows أنّ:',
          options: ['after a جر حرف (بـ)', 'as فاعل', 'as مضاف إليه', 'after مذ'],
          correct: 0,
        },
        {
          title: 'أنّ: مضاف إليه',
          kind: 'mcq',
          prompt: '﴿إِنَّهُ لَحَقٌّ مِثْلَ مَا أَنَّكُمْ تَنْطِقُونَ﴾ shows أنّ as:',
          options: ['مضاف إليه', 'فاعل', 'خبر', 'بعد مذ'],
          correct: 0,
        },
        {
          title: 'أنّ: بعد مذ',
          kind: 'mcq',
          prompt: 'مَا تَرَكَ الصَّلَاةَ مُذْ أَنَّهُ رَجَعَ مِنَ الْحَجِّ shows أنّ:',
          options: ['بعد مذ', 'بعد منذ فقط', 'بعد جر حرف آخر', 'كمضاف إليه'],
          correct: 0,
        },
        {
          title: 'أنّ: بعد ما المصدرية الظرفية',
          kind: 'mcq',
          prompt: 'صُمْ مَا أَنَّكَ تَسْتَطِيعُ shows أنّ:',
          options: ['بعد ما المصدرية الظرفية', 'بعد مذ/منذ', 'بعد جر حرف', 'كفاعل'],
          correct: 0,
        },
        {
          title: 'أنّ: تابع بالعطف',
          kind: 'mcq',
          prompt: '﴿اذْكُرُوا نِعْمَتِي الَّتِي أَنْعَمْتُ عَلَيْكُمْ وَأَنْ فَضَّلْتُكُمْ عَلَى الْعَالَمِينَ﴾ shows أنّ as:',
          options: ['تابع، عطف على مفرد', 'تابع، بدل', 'فاعل', 'مبتدأ'],
          correct: 0,
        },
        {
          title: 'أنّ: تابع بالبدل',
          kind: 'mcq',
          prompt: '﴿وَإِذْ يَعِدُكُمُ اللَّهُ إِحْدَى الطَّائِفَتَيْنِ أَنَّهَا لَكُمْ﴾ shows أنّ as:',
          options: ['تابع، بدل', 'تابع، عطف', 'فاعل', 'نائب فاعل'],
          correct: 0,
        },
        {
          title: 'علة لجملة سابقة',
          kind: 'mcq',
          prompt: 'اسْتَغْفِرُوا اللَّهَ إِنَّهُ/أَنَّهُ غَفُورٌ رَحِيمٌ illustrates which shared موضع?',
          options: ['علة (reason) لجملة سابقة', 'بعد فاء الجزاء', 'بعد لا جرم', 'بعد إذا الفجائية'],
          correct: 0,
        },
        {
          title: 'بعد فاء الجزاء',
          kind: 'mcq',
          prompt: '﴿فَإِنَّهُ غَفُورٌ رَحِيمٌ﴾ illustrates إنّ/أنّ:',
          options: ['بعد فاء الجزاء', 'بعد لا جرم', 'بعد واو عاطفة', 'بعد إذا الفجائية'],
          correct: 0,
        },
        {
          title: 'بعد لا جرم',
          kind: 'mcq',
          prompt: '﴿لَا جَرَمَ أَنَّ اللَّهَ يَعْلَمُ﴾ illustrates إنّ/أنّ:',
          options: ['بعد لا جرم (والفتح هو الغالب)', 'بعد فاء الجزاء', 'علة لجملة سابقة', 'بعد إذا الفجائية'],
          correct: 0,
        },
        {
          title: 'بعد إذا الفجائية',
          kind: 'mcq',
          prompt: 'خَرَجْتُ فَإِذَا إِنَّ/أَنَّ سَعِيدًا وَاقِفٌ illustrates إنّ/أنّ:',
          options: ['بعد إذا الفجائية', 'بعد لا جرم', 'بعد فاء الجزاء', 'بعد واو عاطفة'],
          correct: 0,
        },
        {
          title: 'شرط اسم إنّ/أنّ',
          kind: 'mcq',
          prompt: 'Why is إِنَّ مَنْ صَمَتَ نَجَا invalid?',
          options: ['من here requires صدر الكلام, which the اسم of إنّ may not', 'إنّ can never take a اسم موصول', 'صمت is مبني, not معرب', 'نجا is a فعل ناقص'],
          correct: 0,
        },
        {
          title: 'توسط الخبر مع معرفة',
          kind: 'mcq',
          prompt: '﴿إِنَّ إِلَيْنَا إِيَابَهُمْ﴾ — the شبه جملة خبر comes between إنّ and its (معرفة) اسم. This placement here is:',
          options: ['جائز (permitted, not obligatory)', 'واجب (obligatory)', 'ممتنع (forbidden)', 'شاذ (anomalous)'],
          correct: 0,
        },
        {
          title: 'عطف على اللفظ',
          kind: 'mcq',
          prompt: '﴿إِنَّ وَعْدَ اللَّهِ حَقٌّ وَالسَّاعَةَ لَا رَيْبَ فِيهَا﴾ — والساعةَ is عطف على:',
          options: ['اللفظ (منصوب)', 'الابتداء (مرفوع)', 'الخبر', 'المضاف إليه'],
          correct: 0,
        },
        {
          title: 'عطف على الابتداء',
          kind: 'mcq',
          prompt: '﴿أَئِنَّا لَمَبْعُوثُونَ أَوَآبَاؤُنَا الْأَوَّلُونَ﴾ — آباؤنا is عطف على:',
          options: ['الابتداء (مرفوع)', 'اللفظ (منصوب)', 'الخبر المنصوب', 'اسم إنّ مباشرة'],
          correct: 0,
        },
        {
          title: 'أنّ بمعنى لعل',
          kind: 'mcq',
          prompt: '﴿وَمَا يُشْعِرُكُمْ أَنَّهَا إِذَا جَاءَتْ لَا يُؤْمِنُونَ﴾ — أنّها here means:',
          options: ['لعلها', 'كأنها', 'إنها', 'لكنها'],
          correct: 0,
        },
        {
          title: 'الاستثناء بين الستة',
          kind: 'mcq',
          prompt: 'Among the six الحروف المشبهة بالفعل, the one that does NOT form a جملة with its اسم وخبر is:',
          options: ['أنّ', 'إنّ', 'كأنّ', 'ليت'],
          correct: 0,
        },
        {
          title: 'تركيب: مواضع أنّ من الأمثلة',
          kind: 'tarkeeb',
          instruction: 'Match each example to the موضع of أنّ المفتوحة it illustrates.',
          source: '﴿حتى يتبين لهم أنه الحق﴾ / ﴿قل أوحي إلي أنه استمع نفر من الجن﴾ / ﴿فيعلمون أنه الحق من ربهم﴾ / ﴿ومن آياته أنك ترى الأرض خاشعة﴾',
          words: ['يتبين...أنه الحق', 'أوحي...أنه استمع', 'فيعلمون أنه', 'ومن آياته أنك'],
          labels: ['فاعل', 'نائب فاعل', 'مفعول', 'مبتدأ'],
          distractors: ['خبر'],
        },
        {
          title: 'تركيب: مواضع مشتركة أم خاصة بأنّ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each موضع: مشترك بين إنّ وأنّ, or خاص بأنّ المفتوحة فقط؟',
          source: 'علة لجملة سابقة / بعد فاء الجزاء / فاعل / مضاف إليه',
          words: ['علة لجملة سابقة', 'بعد فاء الجزاء', 'فاعل', 'مضاف إليه'],
          labels: ['مشترك', 'مشترك', 'خاص بأنّ', 'خاص بأنّ'],
          distractors: ['خاص بإنّ فقط'],
        },
        {
          title: 'تركيب: توسط خبر إنّ الشبه جملة',
          kind: 'tarkeeb',
          instruction: 'Classify: is توسط الخبر جائز أم واجب given the اسم؟',
          source: '﴿إن إلينا إيابهم﴾ (اسم معرفة) / ﴿إن في ذلك لعبرة لأولي الأبصار﴾ (اسم نكرة)',
          words: ['اسم معرفة', 'اسم نكرة'],
          labels: ['جائز', 'واجب'],
          distractors: ['ممتنع'],
        },
        {
          title: 'تركيب: أحكام العطف والباء ومعنى لعل',
          kind: 'tarkeeb',
          instruction: 'Match each example to what it illustrates.',
          source: '﴿إن وعد الله حق والساعةَ لا ريب فيها﴾ / ﴿أولم يروا أن الله...بقادر﴾ / ﴿وما يشعركم أنها...لا يؤمنون﴾',
          words: ['والساعةَ', 'بقادر', 'أنها'],
          labels: ['عطف على اللفظ', 'الباء في خبر أنّ', 'أنّ بمعنى لعل'],
          distractors: ['عطف على الابتداء'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'كأنّ ولكنّ ولعلّ وليت',
      subtitle: 'Comparison, Contrast, Expectation, and Wishing — the last four أخوات إنّ',
      concepts: [
        {
          heading: 'كأنّ ولكنّ',
          body: `<bdi>كَأَنَّ</bdi> carries the meaning of <bdi>التَّشْبِيه</bdi> (comparison), as in <bdi>﴿الزُّجَاجَةُ كَأَنَّهَا كَوْكَبٌ دُرِّيٌّ﴾</bdi>. <bdi>لَكِنَّ</bdi> carries <bdi>الِاسْتِدْرَاك</bdi> — following an initial statement with speech that removes a mistaken inference (of affirmation or نفي) it might suggest, as in <bdi>مَا زَيْدٌ قَوِيًّا</bdi> (might suggest he's not brave) → <bdi>لَكِنَّهُ شُجَاعٌ</bdi>. In the Qurʾān, لكنّ is usually preceded by a <bdi>وَاو</bdi>, as in <bdi>﴿وَمَا كَفَرَ سُلَيْمَانُ وَلَٰكِنَّ الشَّيَاطِينَ كَفَرُوا﴾</bdi>.`,
          sample: `كأنّ — التشبيه، ﴿الزجاجة كأنها كوكب دري﴾<br>لكنّ — الاستدراك، ما زيد قويا لكنه شجاع<br>لكنّ + واو — ﴿وما كفر سليمان ولكن الشياطين كفروا﴾`,
          exercise: {
            prompt: `What does لكنّ mean, and what is الاستدراك؟`,
            kind: 'mcq',
            options: ['Following an initial statement with speech removing a mistaken inference it might suggest', 'Comparing one thing to another', 'Expressing hope for something desired', 'Wishing for something with no realistic hope'],
            correct: 0,
          },
        },
        {
          heading: 'لعلّ: التوقع وأحكامها الأخرى',
          body: `<bdi>لَعَلَّ</bdi> carries <bdi>التَّوَقُّع</bdi> (expectation), in two named senses: (1) <b>الترجي</b>, for something desired, as in <bdi>﴿وَاتَّقُوا لَعَلَّكُمْ تُرْحَمُونَ﴾</bdi> (2) <b>الإشفاق</b>, for something feared, as in <bdi>﴿فَلَعَلَّكَ بَاخِعٌ نَفْسَكَ عَلَىٰ آثَارِهِمْ﴾</bdi>. لعلّ can also carry <b>التعليل</b>, as in <bdi>﴿وَافْعَلُوا الْخَيْرَ لَعَلَّكُمْ تُفْلِحُونَ﴾</bdi>, or the meaning of <b>كأنّ</b>, as in <bdi>﴿وَتَتَّخِذُونَ مَصَانِعَ لَعَلَّكُمْ تَخْلُدُونَ﴾</bdi>. A جملة لعلّ can also be عطف on a <bdi>مَفْعُولٌ لَه</bdi> (explicit or implicit), as in <bdi>﴿وَأَنْزَلْنَا إِلَيْكَ الذِّكْرَ لِتُبَيِّنَ لِلنَّاسِ مَا نُزِّلَ إِلَيْهِمْ وَلَعَلَّهُمْ يَتَفَكَّرُونَ﴾</bdi>. Its lightened form is <bdi>عَلّ</bdi>.`,
          sample: `لعلّ التوقع — الترجي: ﴿واتقوا لعلكم ترحمون﴾، الإشفاق: ﴿فلعلك باخع نفسك على آثارهم﴾<br>لعلّ التعليل — ﴿وافعلوا الخير لعلكم تفلحون﴾<br>لعلّ بمعنى كأنّ — ﴿وتتخذون مصانع لعلكم تخلدون﴾<br>لعلّ عطف على مفعول له — ﴿وأنزلنا إليك الذكر لتبين...ولعلهم يتفكرون﴾<br>مخففة لعلّ — عَلّ`,
          exercise: {
            prompt: `What is the meaning of لعلّ, and what are its two named uses؟`,
            kind: 'mcq',
            options: ['التوقع, in two senses: الترجي (desired) and الإشفاق (feared)', 'التشبيه, comparing two things', 'الاستدراك, correcting a mistaken inference', 'التمني, wishing for something unrealistic'],
            correct: 0,
          },
        },
        {
          heading: 'ليت: التمني',
          body: `<bdi>لَيْتَ</bdi> carries <bdi>التَّمَنِّي</bdi> — requesting that in which there is no realistic hope (<bdi>طَلَبُ مَا لَا طَمَعَ فِيهِ</bdi>), as in <bdi>لَيْتَ الشَّبَابَ يَعُودُ يَوْمًا</bdi>. In the Qurʾān, ليت is usually preceded by <bdi>يَا</bdi>, as in <bdi>﴿يَا لَيْتَنِي لَمْ أُوتَ كِتَابِيَهْ﴾</bdi>.`,
          sample: `ليت — التمني، ليت الشباب يعود يوما<br>ليت + يا — ﴿يا ليتني لم أوت كتابيه﴾`,
          exercise: {
            prompt: `What is التمني, the meaning carried by ليت؟`,
            kind: 'mcq',
            options: ['Requesting something in which there is no realistic hope', 'Requesting something entirely achievable', 'Comparing two things to each other', 'Correcting a mistaken inference'],
            correct: 0,
          },
        },
        {
          heading: 'لماذا سُمّيت مشبهة بالفعل؟',
          body: `These six حروف — <bdi>إِنّ أَنّ كَأَنّ لَكِنّ لَعَلّ لَيْت</bdi> — are called مشبهة بالفعل because they resemble the فعل in two ways: each carries a verbal meaning within it (<bdi>أُؤَكِّدُ، أَسْتَدْرِكُ، أَتَمَنَّى، أَرْجُو، أُشَبِّهُ</bdi>), and each governs like أفعال do (نصب + رفع). Matched up: إنّ/أنّ → <bdi>أُؤَكِّدُ</bdi>; لكنّ → <bdi>أَسْتَدْرِكُ</bdi>; ليت → <bdi>أَتَمَنَّى</bdi>; لعلّ → <bdi>أَرْجُو</bdi>; كأنّ → <bdi>أُشَبِّهُ</bdi>.`,
          sample: `سبب التسمية — تحمل معنى فعل (أؤكد، أستدرك، أتمنى، أرجو، أشبه) وتعمل عمل الفعل (نصب+رفع)<br>إنّ/أنّ→أؤكد، لكنّ→أستدرك، ليت→أتمنى، لعلّ→أرجو، كأنّ→أشبه`,
          exercise: {
            prompt: `Why are these six حروف called مشبهة بالفعل؟`,
            kind: 'mcq',
            options: ['They contain verbal meanings within them, and they govern like أفعال (نصب + رفع)', 'They are historically derived from real أفعال', 'They can be conjugated exactly like a فعل ماضٍ', 'They always appear immediately after a فعل'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'كأنّ carries the meaning of:',
          options: ['التشبيه', 'الاستدراك', 'التوقع', 'التمني'],
          correct: 0,
        },
        {
          q: 'What usually precedes لكنّ in the Qurʾān?',
          options: ['الواو', 'الفاء', 'يا', 'ثم'],
          correct: 0,
        },
        {
          q: '﴿فَلَعَلَّكَ بَاخِعٌ نَفْسَكَ عَلَىٰ آثَارِهِمْ﴾ — this sense of لعلّ is:',
          options: ['الإشفاق (something feared)', 'الترجي (something desired)', 'التعليل', 'معنى كأنّ'],
          correct: 0,
        },
        {
          q: 'What is the lightened form of لعلّ?',
          options: ['عَلّ', 'إنْ', 'أنْ', 'كأنْ'],
          correct: 0,
        },
        {
          q: 'What usually precedes ليت in the Qurʾān?',
          options: ['يا', 'الواو', 'إنّ', 'الفاء'],
          correct: 0,
        },
        {
          q: 'لكنّ matches which فعل-meaning of the six?',
          options: ['أستدرك', 'أؤكد', 'أتمنى', 'أرجو'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'كأنّ: مثال',
          kind: 'mcq',
          prompt: '﴿الزُّجَاجَةُ كَأَنَّهَا كَوْكَبٌ دُرِّيٌّ﴾ illustrates:',
          options: ['التشبيه', 'الاستدراك', 'التوقع', 'التمني'],
          correct: 0,
        },
        {
          title: 'لكنّ: تعريف الاستدراك',
          kind: 'mcq',
          prompt: 'الاستدراك is defined as:',
          options: ['following an initial statement with speech removing a mistaken inference from it', 'wishing for something unrealistic', 'comparing two things directly', 'expressing hope for a desired outcome'],
          correct: 0,
        },
        {
          title: 'لكنّ بالواو',
          kind: 'mcq',
          prompt: '﴿وَمَا كَفَرَ سُلَيْمَانُ وَلَٰكِنَّ الشَّيَاطِينَ كَفَرُوا﴾ shows لكنّ preceded by:',
          options: ['الواو', 'الفاء', 'ثم', 'يا'],
          correct: 0,
        },
        {
          title: 'لعلّ: الترجي',
          kind: 'mcq',
          prompt: "﴿وَاتَّقُوا لَعَلَّكُمْ تُرْحَمُونَ﴾ illustrates لعلّ's sense of:",
          options: ['الترجي (something desired)', 'الإشفاق (something feared)', 'التعليل', 'معنى كأنّ'],
          correct: 0,
        },
        {
          title: 'لعلّ: التعليل',
          kind: 'mcq',
          prompt: '﴿وَافْعَلُوا الْخَيْرَ لَعَلَّكُمْ تُفْلِحُونَ﴾ illustrates لعلّ carrying the meaning of:',
          options: ['التعليل', 'الترجي', 'الإشفاق', 'التشبيه المحض'],
          correct: 0,
        },
        {
          title: 'لعلّ: معنى كأنّ',
          kind: 'mcq',
          prompt: '﴿وَتَتَّخِذُونَ مَصَانِعَ لَعَلَّكُمْ تَخْلُدُونَ﴾ — لعلّ here carries the meaning of:',
          options: ['كأنّ (التشبيه)', 'التمني', 'الاستدراك', 'إنّ (التأكيد)'],
          correct: 0,
        },
        {
          title: 'لعلّ عطف على مفعول له',
          kind: 'mcq',
          prompt: '﴿وَأَنْزَلْنَا إِلَيْكَ الذِّكْرَ لِتُبَيِّنَ لِلنَّاسِ مَا نُزِّلَ إِلَيْهِمْ وَلَعَلَّهُمْ يَتَفَكَّرُونَ﴾ — the جملة لعلّهم is عطف on:',
          options: ['مفعول له (لتبين)', 'فاعل', 'مبتدأ', 'خبر'],
          correct: 0,
        },
        {
          title: 'ليت: مثال',
          kind: 'mcq',
          prompt: 'لَيْتَ الشَّبَابَ يَعُودُ يَوْمًا illustrates:',
          options: ['التمني', 'التوقع', 'الاستدراك', 'التشبيه'],
          correct: 0,
        },
        {
          title: 'ليت بيا',
          kind: 'mcq',
          prompt: '﴿يَا لَيْتَنِي لَمْ أُوتَ كِتَابِيَهْ﴾ shows ليت preceded by:',
          options: ['يا', 'الواو', 'إنّ', 'أنّ'],
          correct: 0,
        },
        {
          title: 'الأخوات الستة بالمعنى الفعلي',
          kind: 'mcq',
          prompt: 'إنّ/أنّ match which فعل-meaning of the six?',
          options: ['أؤكد', 'أستدرك', 'أتمنى', 'أرجو'],
          correct: 0,
        },
        {
          title: 'كأنّ بالمعنى الفعلي',
          kind: 'mcq',
          prompt: 'كأنّ matches which فعل-meaning of the six?',
          options: ['أشبه', 'أؤكد', 'أرجو', 'أستدرك'],
          correct: 0,
        },
        {
          title: 'ليت بالمعنى الفعلي',
          kind: 'mcq',
          prompt: 'ليت matches which فعل-meaning of the six?',
          options: ['أتمنى', 'أؤكد', 'أستدرك', 'أشبه'],
          correct: 0,
        },
        {
          title: 'لعلّ بالمعنى الفعلي',
          kind: 'mcq',
          prompt: 'لعلّ matches which فعل-meaning of the six?',
          options: ['أرجو', 'أؤكد', 'أتمنى', 'أشبه'],
          correct: 0,
        },
        {
          title: 'تخفيف لعلّ',
          kind: 'mcq',
          prompt: 'The lightened (مخفف) form of لعلّ is:',
          options: ['عَلّ', 'إنْ', 'لعْ', 'عَنْ'],
          correct: 0,
        },
        {
          title: 'كم معنى للعلّ؟',
          kind: 'mcq',
          prompt: 'How many distinct senses of لعلّ were named (التوقع\'s two, plus two more)?',
          options: ['أربعة', 'اثنان', 'ثلاثة', 'خمسة'],
          correct: 0,
        },
        {
          title: 'أساس التسمية: مشبهة بالفعل',
          kind: 'mcq',
          prompt: 'الحروف المشبهة بالفعل resemble الفعل in two ways: carrying a verbal meaning, and:',
          options: ['governing like أفعال (نصب + رفع)', 'being conjugated for tense', 'taking a فاعل of their own', 'accepting تنوين'],
          correct: 0,
        },
        {
          title: 'ما زيد قويا',
          kind: 'mcq',
          prompt: 'مَا زَيْدٌ قَوِيًّا لَكِنَّهُ شُجَاعٌ — لكنّ here corrects the possible inference that زيد is:',
          options: ['not brave (شجاع)', 'not present', 'not known', 'not truthful'],
          correct: 0,
        },
        {
          title: 'تركيب: معاني الأربعة الأخيرة',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف by its core meaning.',
          source: 'كأنّ / لكنّ / لعلّ / ليت',
          words: ['كأنّ', 'لكنّ', 'لعلّ', 'ليت'],
          labels: ['التشبيه', 'الاستدراك', 'التوقع', 'التمني'],
          distractors: ['التأكيد'],
        },
        {
          title: 'تركيب: معاني لعلّ الأربعة',
          kind: 'tarkeeb',
          instruction: 'Match each example to the sense of لعلّ it illustrates.',
          source: '﴿واتقوا لعلكم ترحمون﴾ / ﴿فلعلك باخع نفسك﴾ / ﴿وافعلوا الخير لعلكم تفلحون﴾ / ﴿وتتخذون مصانع لعلكم تخلدون﴾',
          words: ['لعلكم ترحمون', 'باخع نفسك', 'لعلكم تفلحون', 'لعلكم تخلدون'],
          labels: ['الترجي', 'الإشفاق', 'التعليل', 'معنى كأنّ'],
          distractors: ['التمني'],
        },
        {
          title: 'تركيب: كل حرف ومعناه الفعلي',
          kind: 'tarkeeb',
          instruction: 'Match each حرف to the فعل-meaning it contains.',
          source: 'إنّ / لكنّ / ليت / لعلّ / كأنّ',
          words: ['إنّ', 'لكنّ', 'ليت', 'لعلّ', 'كأنّ'],
          labels: ['أؤكد', 'أستدرك', 'أتمنى', 'أرجو', 'أشبه'],
          distractors: ['أصير'],
        },
        {
          title: 'تركيب: ما يسبق كل حرف في القرآن',
          kind: 'tarkeeb',
          instruction: 'Classify what typically precedes each حرف in the Qurʾān.',
          source: 'لكنّ / ليت',
          words: ['لكنّ', 'ليت'],
          labels: ['الواو', 'يا'],
          distractors: ['الفاء'],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'التخفيف وما الكافة',
      subtitle: 'Lightening the Load — إنْ, أنْ, and كأنْ once lightened, and ما الكافة',
      concepts: [
        {
          heading: 'تخفيف إنّ إلى إنْ',
          body: `When إنّ is lightened to <bdi>إِنْ</bdi>, its operation is predominantly <b>suspended</b> (<bdi>الْإِهْمَال هُوَ الْغَالِب</bdi>), though operation remains permitted, as in one reading of <bdi>﴿وَإِنْ كُلًّا لَمَّا لَيُوَفِّيَنَّهُمْ رَبُّكَ أَعْمَالَهُمْ﴾</bdi>. A <bdi>لَامٌ فَارِقَة</bdi> is frequent in the خبر after a non-operating lightened إنْ, distinguishing it from <bdi>إِنِ النَّافِيَة</bdi>, as in <bdi>﴿وَإِنْ نَظُنُّكَ لَمِنَ الْكَاذِبِينَ﴾</bdi>. Lightened إنْ can enter a <bdi>الْجُمْلَةُ الِاسْمِيَّة</bdi> whether unmodified — <bdi>﴿وَإِنْ كُلٌّ لَمَّا جَمِيعٌ لَدَيْنَا مُحْضَرُونَ﴾</bdi> — or already governed by a <bdi>نَاسِخ</bdi> — as in the same ﴿وإن نظنك﴾ example.`,
          sample: `إنّ مخففة إنْ — الإهمال غالب، والإعمال جائز: ﴿وإن كلا لما ليوفينهم ربك أعمالهم﴾<br>اللام الفارقة — ﴿وإن نظنك لمن الكاذبين﴾، تفرق بين إن المخففة وإن النافية<br>تدخل على الجملة الاسمية — منسوخة أو غير منسوخة`,
          exercise: {
            prompt: `When إنّ is lightened to إنْ, what happens to its operation؟`,
            kind: 'mcq',
            options: ['It is predominantly suspended, though operation remains permitted', 'It always keeps operating exactly as before', 'It is permanently and completely disabled, with no exception', 'It converts into a حرف جر instead'],
            correct: 0,
          },
        },
        {
          heading: 'تخفيف أنّ إلى أنْ',
          body: `When أنّ is lightened to <bdi>أَنْ</bdi>, it still <b>operates</b> after lightening — its اسم is an omitted <bdi>ضَمِيرُ الشَّأْن</bdi>. Its خبر is a جملة, either <bdi>اسْمِيَّة</bdi> or <bdi>فِعْلِيَّة</bdi>, with rules governing whether a separator (<bdi>الْفَصْل</bdi>) comes between أنْ and that خبر depending on the type of فعل involved.`,
          sample: `أنّ مخففة أنْ — تعمل بعد التخفيف، اسمها ضمير الشأن محذوف<br>خبرها — جملة اسمية أو فعلية، بأحكام فصل تختلف بحسب الفعل`,
          exercise: {
            prompt: `When أنّ is lightened to أنْ, does it still operate? What is its اسم؟`,
            kind: 'mcq',
            options: ['Yes, it operates; its اسم is an omitted ضمير الشأن', 'No, its operation is fully suspended like إنْ', 'Yes, but its اسم becomes an explicit ضمير متصل', 'It stops being a حرف مصدر altogether'],
            correct: 0,
          },
        },
        {
          heading: 'الفصل بين أنْ المخففة وخبرها',
          body: `No separator comes between lightened أنْ and its خبر in three cases: (1) a <bdi>جُمْلَة اسْمِيَّة</bdi>, as in <bdi>﴿وَآخِرُ دَعْوَاهُمْ أَنِ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ﴾</bdi> (2) a <bdi>جُمْلَة فِعْلِيَّة</bdi> with a <bdi>فِعْل جَامِد</bdi>, as in <bdi>﴿وَأَنْ لَيْسَ لِلْإِنْسَانِ إِلَّا مَا سَعَىٰ﴾</bdi> (3) a جملة فعلية with a <bdi>فِعْل مُتَصَرِّف</bdi> of <bdi>دُعَاء</bdi>, as in <bdi>﴿وَالْخَامِسَةَ أَنْ غَضِبَ اللَّهُ عَلَيْهَا﴾</bdi> (Nāfiʿ's reading). Otherwise, before a (non-دعاء) خبر فعلي, a separator does appear: <bdi>قَدْ</bdi>, a <bdi>حَرْفُ تَنْفِيس</bdi>, <bdi>لَوْ</bdi>, or a نفي حرف such as <bdi>لَمْ، لَا، لَنْ</bdi>.`,
          sample: `بلا فصل (٣) — جملة اسمية: ﴿وآخر دعواهم أن الحمد لله﴾؛ فعل جامد: ﴿وأن ليس للإنسان إلا ما سعى﴾؛ فعل متصرف دعاء: ﴿والخامسة أن غضب الله عليها﴾<br>بفصل — قد، حرف تنفيس، لو، نفي (لم/لا/لن)`,
          exercise: {
            prompt: `When does NO separator come between lightened أنْ and its خبر؟`,
            kind: 'mcq',
            options: ['With a جملة اسمية, a فعل جامد, or a فعل متصرف of دعاء', 'Only ever with a جملة اسمية', 'Only when the فعل is مضارع', 'A separator is always required, with no exception'],
            correct: 0,
          },
        },
        {
          heading: 'تخفيف كأنّ، وما الكافة',
          body: `When كأنّ is lightened to <bdi>كَأَنْ</bdi>, it still operates; its اسم is likewise an omitted ضمير الشأن, and it is usually separated from a following فعل by <bdi>لَمْ</bdi> or <bdi>قَدْ</bdi>, as in <bdi>﴿كَأَنْ لَمْ يَلْبَثُوا إِلَّا سَاعَةً﴾</bdi>. Separately, <bdi>مَا الْكَافَّة</bdi> has two effects on الحروف المشبهة بالفعل: it <b>stops their operation</b>, as in <bdi>﴿إِنَّمَا إِلَٰهُكُمُ اللَّهُ﴾</bdi>, and it <b>licenses them to enter upon أفعال</b>, as in <bdi>﴿إِنَّمَا يَتَقَبَّلُ اللَّهُ مِنَ الْمُتَّقِينَ﴾</bdi>.`,
          sample: `كأنّ مخففة كأنْ — تعمل، اسمها ضمير الشأن محذوف، يفصلها عن الفعل غالبا لم أو قد: ﴿كأن لم يلبثوا إلا ساعة﴾<br>ما الكافة — توقف العمل: ﴿إنما إلهكم الله﴾؛ وتبيح الدخول على الأفعال: ﴿إنما يتقبل الله من المتقين﴾`,
          exercise: {
            prompt: `What two effects does ما الكافة have on الحروف المشبهة بالفعل؟`,
            kind: 'mcq',
            options: ['It stops their operation, and licenses them to enter upon أفعال', 'It doubles their operation and forces two أسماء at once', 'It converts them permanently into حروف جر', 'It has no grammatical effect at all'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'When إنّ is lightened to إنْ, its operation is:',
          options: ['predominantly suspended, though still permitted', 'always fully maintained', 'converted into a فعل', 'permanently forbidden with no exception'],
          correct: 0,
        },
        {
          q: 'What is اللام الفارقة for?',
          options: ['Distinguishing non-operating lightened إنْ from إن النافية', 'Marking the فاعل of a lightened حرف', 'Introducing a جملة شرطية', 'Negating a فعل ماضٍ'],
          correct: 0,
        },
        {
          q: 'The اسم of lightened أنْ is:',
          options: ['an omitted ضمير الشأن', 'always an اسم ظاهر', 'always a ضمير متصل', 'never present at all'],
          correct: 0,
        },
        {
          q: '﴿وَأَنْ لَيْسَ لِلْإِنْسَانِ إِلَّا مَا سَعَىٰ﴾ — no separator appears here between أنْ and its خبر because the فعل (ليس) is:',
          options: ['جامد', 'متصرف', 'أمر', 'مضارع مرفوع'],
          correct: 0,
        },
        {
          q: 'What usually separates lightened كأنْ from a following فعل?',
          options: ['لم or قد', 'إلا or غير', 'لن or لم يكن', 'هل or أم'],
          correct: 0,
        },
        {
          q: '﴿إِنَّمَا يَتَقَبَّلُ اللَّهُ مِنَ الْمُتَّقِينَ﴾ illustrates which effect of ما الكافة?',
          options: ['Licensing إنّ to enter upon a فعل', 'Stopping إنّ from operating', 'Turning إنّ into a حرف جر', 'Negating the whole جملة'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الإهمال هو الغالب',
          kind: 'mcq',
          prompt: 'For lightened إنْ, which is the more common state?',
          options: ['الإهمال (suspension)', 'الإعمال (operation)', 'both equally common', 'neither — إنْ cannot occur at all'],
          correct: 0,
        },
        {
          title: 'مثال إعمال إنْ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ كُلًّا لَمَّا لَيُوَفِّيَنَّهُمْ رَبُّكَ أَعْمَالَهُمْ﴾ (in one reading) shows lightened إنْ:',
          options: ['still operating (الإعمال)', 'fully suspended with no exception', 'converted to a فعل', 'acting as حرف عطف'],
          correct: 0,
        },
        {
          title: 'موضع اللام الفارقة',
          kind: 'mcq',
          prompt: 'اللام الفارقة is frequent in the:',
          options: ['خبر after non-operating lightened إنْ', 'اسم of إنّ المشددة', 'صلة الموصول', 'مضاف إليه'],
          correct: 0,
        },
        {
          title: 'مثال اللام الفارقة',
          kind: 'mcq',
          prompt: '﴿وَإِنْ نَظُنُّكَ لَمِنَ الْكَاذِبِينَ﴾ illustrates:',
          options: ['اللام الفارقة after lightened إنْ', 'اللام المعلقة', 'لام الأمر', 'لام القسم'],
          correct: 0,
        },
        {
          title: 'إنْ على جملة منسوخة',
          kind: 'mcq',
          prompt: 'Lightened إنْ can enter a جملة اسمية that is already governed by a:',
          options: ['ناسخ', 'حرف جر', 'اسم فاعل', 'مصدر مؤول'],
          correct: 0,
        },
        {
          title: 'أنْ تعمل بعد التخفيف',
          kind: 'mcq',
          prompt: 'After lightening, does أنْ still operate?',
          options: ['Yes, it still operates', 'No, its operation is fully suspended', 'Only in poetry', 'Only when preceded by لا'],
          correct: 0,
        },
        {
          title: 'خبر أنْ المخففة',
          kind: 'mcq',
          prompt: "The خبر of lightened أنْ is:",
          options: ['a جملة, اسمية or فعلية', 'always a مفرد اسم', 'always محذوف', 'a ظرف only'],
          correct: 0,
        },
        {
          title: 'بلا فصل: جملة اسمية',
          kind: 'mcq',
          prompt: '﴿وَآخِرُ دَعْوَاهُمْ أَنِ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ﴾ shows lightened أنْ with:',
          options: ['no separator, because the خبر is جملة اسمية', 'the separator قد', 'the separator لو', 'the separator لم'],
          correct: 0,
        },
        {
          title: 'بلا فصل: فعل جامد',
          kind: 'mcq',
          prompt: '﴿وَأَنْ لَيْسَ لِلْإِنْسَانِ إِلَّا مَا سَعَىٰ﴾ shows lightened أنْ with:',
          options: ['no separator, because the فعل (ليس) is جامد', 'the separator قد', 'the separator لو', 'a حرف تنفيس'],
          correct: 0,
        },
        {
          title: 'بلا فصل: فعل دعاء متصرف',
          kind: 'mcq',
          prompt: '﴿وَالْخَامِسَةَ أَنْ غَضِبَ اللَّهُ عَلَيْهَا﴾ (Nāfiʿ\'s reading) shows lightened أنْ with:',
          options: ['no separator, because غضب here is فعل متصرف of دعاء', 'the separator لو', 'the separator قد', 'a نفي حرف'],
          correct: 0,
        },
        {
          title: 'فصل بقد',
          kind: 'mcq',
          prompt: '﴿وَنَعْلَمَ أَنْ قَدْ صَدَقْتَنَا﴾ shows lightened أنْ separated from its خبر by:',
          options: ['قد', 'لو', 'لم', 'حرف تنفيس'],
          correct: 0,
        },
        {
          title: 'فصل بحرف تنفيس',
          kind: 'mcq',
          prompt: '﴿عَلِمَ أَنْ سَيَكُونُ مِنْكُمْ مَرْضَىٰ﴾ shows lightened أنْ separated from its خبر by:',
          options: ['a حرف تنفيس (سيكون)', 'قد', 'لو', 'لم'],
          correct: 0,
        },
        {
          title: 'فصل بلو',
          kind: 'mcq',
          prompt: '﴿أَنْ لَوْ نَشَاءُ أَصَبْنَاهُمْ بِذُنُوبِهِمْ﴾ shows lightened أنْ separated by:',
          options: ['لو', 'قد', 'لم', 'حرف تنفيس'],
          correct: 0,
        },
        {
          title: 'فصل بحروف النفي',
          kind: 'mcq',
          prompt: '﴿أَيَحْسَبُ أَنْ لَمْ يَرَهُ أَحَدٌ﴾ shows lightened أنْ separated from its خبر by a:',
          options: ['نفي حرف (لم)', 'حرف تنفيس', 'لو', 'قد'],
          correct: 0,
        },
        {
          title: 'اسم كأنْ المخففة',
          kind: 'mcq',
          prompt: "Once lightened, كأنْ's اسم is:",
          options: ['an omitted ضمير الشأن', 'an اسم ظاهر مرفوع', 'a ضمير متصل بالفعل', 'never present'],
          correct: 0,
        },
        {
          title: 'كأنْ ولم/قد',
          kind: 'mcq',
          prompt: '﴿كَأَنْ لَمْ يَلْبَثُوا إِلَّا سَاعَةً﴾ shows lightened كأنْ separated from the following فعل by:',
          options: ['لم', 'قد فقط', 'لو', 'حرف تنفيس'],
          correct: 0,
        },
        {
          title: 'ما الكافة توقف العمل',
          kind: 'mcq',
          prompt: '﴿إِنَّمَا إِلَٰهُكُمُ اللَّهُ﴾ illustrates ما الكافة:',
          options: ['stopping إنّ from operating', 'licensing إنّ onto a فعل', 'turning إنّ into a اسم', 'negating التوكيد entirely'],
          correct: 0,
        },
        {
          title: 'تركيب: تخفيف كل حرف',
          kind: 'tarkeeb',
          instruction: 'Match each lightened حرف to whether it still operates.',
          source: 'إنْ (من إنّ) / أنْ (من أنّ) / كأنْ (من كأنّ)',
          words: ['إنْ', 'أنْ', 'كأنْ'],
          labels: ['الإهمال غالب، الإعمال جائز', 'تعمل بعد التخفيف', 'تعمل بعد التخفيف'],
          distractors: ['ممتنعة كليا'],
        },
        {
          title: 'تركيب: الفصل بين أنْ وخبرها',
          kind: 'tarkeeb',
          instruction: 'Classify each example: بلا فصل, or بفصل؟',
          source: '﴿وآخر دعواهم أن الحمد لله﴾ / ﴿وأن ليس للإنسان إلا ما سعى﴾ / ﴿ونعلم أن قد صدقتنا﴾',
          words: ['أن الحمد لله', 'أن ليس للإنسان', 'أن قد صدقتنا'],
          labels: ['بلا فصل (جملة اسمية)', 'بلا فصل (فعل جامد)', 'بفصل (قد)'],
          distractors: ['بفصل (لو)'],
        },
        {
          title: 'تركيب: أثر ما الكافة',
          kind: 'tarkeeb',
          instruction: 'Match each example to the effect of ما الكافة it shows.',
          source: '﴿إنما إلهكم الله﴾ / ﴿إنما يتقبل الله من المتقين﴾',
          words: ['إنما إلهكم الله', 'إنما يتقبل الله'],
          labels: ['توقف العمل', 'تبيح الدخول على فعل'],
          distractors: ['تبطل المعنى'],
        },
        {
          title: 'تركيب: اسم الحرف بعد التخفيف',
          kind: 'tarkeeb',
          instruction: 'Classify what the اسم of each lightened حرف is.',
          source: 'أنْ (من أنّ) / كأنْ (من كأنّ)',
          words: ['أنْ', 'كأنْ'],
          labels: ['ضمير الشأن محذوف', 'ضمير الشأن محذوف'],
          distractors: ['اسم ظاهر مرفوع'],
        },
      ],
    },
    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'لا لنفي الجنس والمشبهات بليس',
      subtitle: "Two More نواسخ Families — لا التبرئة, and the three حروف مشبهة بليس",
      concepts: [
        {
          heading: 'لا لنفي الجنس',
          body: `<bdi>لَا لِنَفْيِ الْجِنْس</bdi> — also called <bdi>لَا التَّبْرِئَة</bdi> — negates the <b>entire genus</b> of its اسم, as in <bdi>لَا فَاعِلَ شَرٍّ فَائِزٌ</bdi>. It does NOT operate, however, when it falls between a <bdi>جَرّ حَرْف</bdi> and its مجرور, as in <bdi>اللَّهُمَّ أَدْخِلْنَا الْجَنَّةَ بِلَا حِسَابٍ</bdi>.`,
          sample: `لا لنفي الجنس = لا التبرئة — لا فاعل شر فائز<br>لا تعمل بين حرف الجر ومجروره — اللهم أدخلنا الجنة بلا حسابٍ`,
          exercise: {
            prompt: `What does لا لنفي الجنس do, and what is its other name؟`,
            kind: 'mcq',
            options: ['It negates the entire genus of its اسم; also called لا التبرئة', 'It negates only a single unit of its اسم; also called لا العاطفة', 'It affirms the genus of its اسم; also called لا الزائدة', 'It has no meaning of its own at all'],
            correct: 0,
          },
        },
        {
          heading: 'شروط عمل لا، وحكم تكرارها',
          body: `لا لنفي الجنس operates on two conditions: (1) the نفي must be of the <b>genus</b> — if it negates a single unit (<bdi>الْوَحْدَة</bdi>) instead, it operates like ليس, as in <bdi>لَا رَجُلٌ قَائِمًا بَلْ رَجُلَانِ</bdi> (2) its اسم must be <b>directly attached</b> to it — otherwise it is <bdi>مُهْمَلَة</bdi> and must be repeated, as in <bdi>﴿لَا فِيهَا غَوْلٌ وَلَا هُمْ عَنْهَا يُنْزَفُونَ﴾</bdi>. When لا is repeated without separation, both <b>عمل</b> — as in <bdi>﴿فَلَا رَفَثَ وَلَا فُسُوقَ وَلَا جِدَالَ فِي الْحَجِّ﴾</bdi> — and <b>إهمال</b> — as in <bdi>﴿فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ﴾</bdi> — are possible.`,
          sample: `شرط١ — النفي للجنس لا للوحدة: لا رجل قائما بل رجلان<br>شرط٢ — الاسم مباشر لها<br>لا مكررة بلا فصل — الإعمال: ﴿فلا رفث ولا فسوق ولا جدال في الحج﴾؛ الإهمال: ﴿فلا خوفٌ عليهم ولا هم يحزنون﴾`,
          exercise: {
            prompt: `What are the two conditions for لا لنفي الجنس to operate؟`,
            kind: 'mcq',
            options: ['The نفي must be of the genus, and its اسم must be directly attached to it', 'It must always be repeated twice, and its اسم must be نكرة', 'It must be preceded by a واو, and its خبر must be محذوف', 'It must occur only in poetry, and its اسم must be معرفة'],
            correct: 0,
          },
        },
        {
          heading: 'الخمسة نواسخ',
          body: `Five families of عوامل enter upon مبتدأ وخبر — the <bdi>نَوَاسِخ</bdi>: (1) <bdi>أَفْعَالُ الْقُلُوب</bdi> (2) <bdi>الْأَفْعَالُ النَّاقِصَة</bdi> (3) <bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِالْفِعْل</bdi> (4) <bdi>لَا لِنَفْيِ الْجِنْس</bdi> (5) <bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِلَيْس</bdi>.`,
          sample: `النواسخ الخمسة — أفعال القلوب، الأفعال الناقصة، الحروف المشبهة بالفعل، لا لنفي الجنس، الحروف المشبهة بليس`,
          exercise: {
            prompt: `List the five نواسخ — عوامل entering upon مبتدأ وخبر.`,
            kind: 'mcq',
            options: ['أفعال القلوب، الأفعال الناقصة، الحروف المشبهة بالفعل، لا لنفي الجنس، الحروف المشبهة بليس', 'حروف الجر، إلا، الحروف المشبهة بالفعل، الحروف المشبهة بليس، حروف العطف', 'كان، أصبح، ظل، بات، صار', 'إنّ، أنّ، كأنّ، لكنّ، لعلّ'],
            correct: 0,
          },
        },
        {
          heading: 'الحروف المشبهة بليس',
          body: `<bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِلَيْس</bdi> put the first اسم in <b>رفع</b> (their اسم) and the second in <b>نصب</b> (their خبر) — resembling ليس both in <bdi>النَّفْي</bdi> and in entering upon the مبتدأ وخبر. There are three: <bdi>مَا، لَا، لَاتَ</bdi>.`,
          sample: `الحروف المشبهة بليس — رفع الاسم، نصب الخبر، تشبه ليس في النفي وفي الدخول على المبتدأ والخبر<br>الثلاثة — ما، لا، لات`,
          exercise: {
            prompt: `What do الحروف المشبهة بليس do, and in what do they resemble ليس؟`,
            kind: 'mcq',
            options: ['They put the first اسم in رفع and the second in نصب; they resemble ليس in النفي and entering upon مبتدأ وخبر', 'They put the first اسم in نصب and the second in رفع; they resemble كان in التحول', 'They put both أسماء in جر; they resemble حروف الجر', 'They govern nothing at all; they merely resemble ليس in spelling'],
            correct: 0,
          },
        },
        {
          heading: 'ما الحجازية، ولا ولات المشبهتان بليس',
          body: `<bdi>مَا الْحِجَازِيَّة</bdi> operates on three conditions: (1) the اسم precedes the خبر — not <bdi>مَا مُسِيءٌ مَنْ أَعْتَبَ</bdi> (2) it is not joined with the redundant <bdi>إِنْ</bdi> — not <bdi>مَا إِنْ أَنْتُمْ قَائِمُونَ</bdi> (3) its خبر is not accompanied by <bdi>إِلَّا</bdi> — not <bdi>﴿وَمَا مُحَمَّدٌ إِلَّا رَسُولٌ﴾</bdi>. It is called حجازية because the people of الحجاز operate it (given these conditions), while <bdi>بَنُو تَمِيم</bdi> never operate it at all. <bdi>لَا الْمُشَبَّهَةُ بِلَيْس</bdi> predominantly operates only in poetry, as in <bdi>تَعَزَّ فَلَا شَيْءٌ عَلَى الْأَرْضِ بَاقِيًا</bdi>. <bdi>لَاتَ</bdi> is restricted to the word <bdi>حِين</bdi>, with its اسم usually omitted (تقدير: الحين), as in <bdi>﴿وَلَاتَ حِينَ مَنَاصٍ﴾</bdi>.`,
          sample: `شروط ما الحجازية — تقدم الاسم، عدم اقترانها بإن الزائدة، عدم اقتران خبرها بإلا<br>سبب التسمية حجازية — أهل الحجاز يُعملونها، بنو تميم لا يُعملونها أبدا<br>لا المشبهة بليس — الغالب إعمالها في الشعر: تعز فلا شيء على الأرض باقيا<br>لات — خاصة بحين، اسمها محذوف غالبا: ﴿ولات حين مناص﴾`,
          exercise: {
            prompt: `Why is ما الحجازية called by that name؟`,
            kind: 'mcq',
            options: ['Because the people of الحجاز operate it, while بنو تميم never operate it at all', 'Because it was first used by a poet from الحجاز', 'Because it only appears in Meccan verses of the Qurʾān', 'There is no real reason — the name is arbitrary'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'لا لنفي الجنس does NOT operate when it falls:',
          options: ['between a جر حرف and its مجرور', 'at the very start of a جملة', 'before a فعل ماضٍ', 'after واو العطف'],
          correct: 0,
        },
        {
          q: 'If لا negates a single unit (الوحدة) rather than the whole genus, it operates like:',
          options: ['ليس', 'كان', 'إنّ', 'ما النافية'],
          correct: 0,
        },
        {
          q: 'How many نواسخ families are there in total?',
          options: ['خمسة', 'أربعة', 'ثلاثة', 'ستة'],
          correct: 0,
        },
        {
          q: 'List the three الحروف المشبهة بليس.',
          options: ['ما، لا، لات', 'ما، لا، ليس', 'لا، لات، لعل', 'ما، ليت، لات'],
          correct: 0,
        },
        {
          q: '﴿وَمَا مُحَمَّدٌ إِلَّا رَسُولٌ﴾ shows ما الحجازية NOT operating because:',
          options: ['its خبر is accompanied by إلا', 'the اسم follows the خبر', 'it is joined with الواو', 'محمد is a اسم علم'],
          correct: 0,
        },
        {
          q: 'لات is restricted to the word:',
          options: ['حين', 'يوم', 'ساعة', 'وقت'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'لا التبرئة',
          kind: 'mcq',
          prompt: 'لا لنفي الجنس is also known as:',
          options: ['لا التبرئة', 'لا العاطفة', 'لا الناهية', 'لا الزائدة'],
          correct: 0,
        },
        {
          title: 'لا فاعل شر فائز',
          kind: 'mcq',
          prompt: 'لَا فَاعِلَ شَرٍّ فَائِزٌ illustrates:',
          options: ['لا لنفي الجنس, negating the whole genus', 'لا العاطفة', 'لا الناهية على الفعل', 'لا النافية للوحدة فقط'],
          correct: 0,
        },
        {
          title: 'لا بين الجار والمجرور',
          kind: 'mcq',
          prompt: 'اللَّهُمَّ أَدْخِلْنَا الْجَنَّةَ بِلَا حِسَابٍ shows لا لنفي الجنس:',
          options: ['not operating, since it falls between a جر حرف and its مجرور', 'operating normally on حساب', 'acting as لا الناهية', 'acting as حرف عطف'],
          correct: 0,
        },
        {
          title: 'نفي الوحدة',
          kind: 'mcq',
          prompt: 'لَا رَجُلٌ قَائِمًا بَلْ رَجُلَانِ — لا here negates:',
          options: ['a single unit (الوحدة), so it operates like ليس', 'the whole genus, so it operates like لنفي الجنس', 'nothing at all — it is زائدة', 'the فعل قائما directly'],
          correct: 0,
        },
        {
          title: 'مباشرة الاسم',
          kind: 'mcq',
          prompt: 'For لا لنفي الجنس to operate, its اسم must be:',
          options: ['directly attached to it (مباشر)', 'separated by at least one word', 'a ضمير متصل only', 'always نكرة موصوفة'],
          correct: 0,
        },
        {
          title: 'لا مكررة: الإعمال',
          kind: 'mcq',
          prompt: '﴿فَلَا رَفَثَ وَلَا فُسُوقَ وَلَا جِدَالَ فِي الْحَجِّ﴾ shows repeated لا with:',
          options: ['الإعمال (all three منصوبة)', 'الإهمال', 'حذف الاسم كليا', 'تحويلها إلى إنّ'],
          correct: 0,
        },
        {
          title: 'لا مكررة: الإهمال',
          kind: 'mcq',
          prompt: '﴿فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ﴾ shows repeated لا with:',
          options: ['الإهمال (لا تعمل)', 'الإعمال', 'حذف الخبر كليا', 'تحويلها إلى ليس'],
          correct: 0,
        },
        {
          title: 'أفعال القلوب من النواسخ',
          kind: 'mcq',
          prompt: 'Which of these is one of the five نواسخ؟',
          options: ['أفعال القلوب', 'أفعال الشروع', 'أفعال المقاربة', 'أفعال المدح والذم'],
          correct: 0,
        },
        {
          title: 'عمل المشبهة بليس',
          kind: 'mcq',
          prompt: 'الحروف المشبهة بليس put the first اسم in رفع and the second in:',
          options: ['نصب', 'رفع أيضا', 'جر', 'لا خبر لها'],
          correct: 0,
        },
        {
          title: 'الثلاثة المشبهة بليس',
          kind: 'mcq',
          prompt: 'List the three الحروف المشبهة بليس.',
          options: ['ما، لا، لات', 'ما، إن، لات', 'لا، لكن، لات', 'ما، لا، ليس'],
          correct: 0,
        },
        {
          title: 'شرط ما الحجازية: تقدم الاسم',
          kind: 'mcq',
          prompt: 'مَا مُسِيءٌ مَنْ أَعْتَبَ is invalid for ما الحجازية because:',
          options: ['the اسم does not precede the خبر', 'إن الزائدة is joined to it', 'the خبر is joined with إلا', 'مسيء is معرفة'],
          correct: 0,
        },
        {
          title: 'شرط ما الحجازية: بلا إن',
          kind: 'mcq',
          prompt: 'مَا إِنْ أَنْتُمْ قَائِمُونَ is invalid for ما الحجازية because:',
          options: ['it is joined with the redundant إن', 'the اسم follows the خبر', 'its خبر is joined with إلا', 'أنتم is a ضمير منفصل'],
          correct: 0,
        },
        {
          title: 'شرط ما الحجازية: بلا إلا',
          kind: 'mcq',
          prompt: '﴿وَمَا مُحَمَّدٌ إِلَّا رَسُولٌ﴾ shows ما الحجازية not operating because its خبر:',
          options: ['is accompanied by إلا', 'precedes its اسم', 'is a شبه جملة', 'is a جملة فعلية'],
          correct: 0,
        },
        {
          title: 'بنو تميم وما',
          kind: 'mcq',
          prompt: 'Which tribe never operates ما الحجازية at all?',
          options: ['بنو تميم', 'أهل الحجاز', 'قريش', 'هذيل'],
          correct: 0,
        },
        {
          title: 'لا المشبهة بليس',
          kind: 'mcq',
          prompt: 'لا المشبهة بليس predominantly operates in:',
          options: ['الشعر (poetry)', 'القرآن فقط', 'النثر اليومي', 'الخطابة الرسمية'],
          correct: 0,
        },
        {
          title: 'لات وحين',
          kind: 'mcq',
          prompt: 'لات is restricted to which word?',
          options: ['حين', 'يوم', 'وقت', 'ساعة'],
          correct: 0,
        },
        {
          title: 'اسم لات',
          kind: 'mcq',
          prompt: '﴿وَلَاتَ حِينَ مَنَاصٍ﴾ — the اسم of لات here is usually:',
          options: ['محذوف, تقديره الحين', 'مذكور، وهو حين', 'مذكور، وهو مناص', 'لا اسم لها أصلا'],
          correct: 0,
        },
        {
          title: 'تركيب: شروط عمل لا لنفي الجنس',
          kind: 'tarkeeb',
          instruction: 'Classify each example: does لا لنفي الجنس operate here or not?',
          source: 'لا فاعلَ شرٍّ فائز / بلا حسابٍ (بين حرف جر ومجروره) / لا رجلٌ قائما (نفي وحدة)',
          words: ['لا فاعلَ شر', 'بلا حساب', 'لا رجلٌ قائما'],
          labels: ['تعمل (نفي جنس، اسم مباشر)', 'لا تعمل (بين جار ومجرور)', 'لا تعمل (نفي وحدة، كليس)'],
          distractors: ['تعمل عمل كان'],
        },
        {
          title: 'تركيب: النواسخ الخمسة',
          kind: 'tarkeeb',
          instruction: 'Classify each عامل: من النواسخ الخمسة or not?',
          source: 'أفعال القلوب / لا لنفي الجنس / حروف الجر / الحروف المشبهة بليس',
          words: ['أفعال القلوب', 'لا لنفي الجنس', 'حروف الجر', 'الحروف المشبهة بليس'],
          labels: ['من النواسخ', 'من النواسخ', 'ليست من النواسخ', 'من النواسخ'],
          distractors: ['أفعال الشروع'],
        },
        {
          title: 'تركيب: شروط ما الحجازية',
          kind: 'tarkeeb',
          instruction: 'Classify each example: does it satisfy ما الحجازية\'s conditions or violate them?',
          source: 'ما مسيء من أعتب (تأخر الاسم) / ما إن أنتم قائمون (بإن الزائدة) / ﴿وما محمد إلا رسول﴾ (بإلا)',
          words: ['ما مسيء', 'ما إن أنتم', 'وما محمد إلا رسول'],
          labels: ['مخالف (تأخر الاسم)', 'مخالف (اقتران بإن)', 'مخالف (خبر بإلا)'],
          distractors: ['مستوفي الشروط'],
        },
        {
          title: 'تركيب: الحروف المشبهة بليس الثلاثة',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف by its typical domain of operation.',
          source: 'ما الحجازية / لا المشبهة بليس / لات',
          words: ['ما الحجازية', 'لا المشبهة بليس', 'لات'],
          labels: ['أهل الحجاز، بشروط', 'الشعر غالبا', 'خاصة بحين'],
          distractors: ['بنو تميم دائما'],
        },
      ],
    },
  ],
};
