// Module 03 — العامل والمعمول والإعراب: تمهيد
//
// Source: app-lessons/016-amil-and-non-amil.md, app-lessons/017-mamul-and-non-mamul.md,
// app-lessons/018-irab.md. Per COURSE-MAP.md's Module 03 plan: l1 merges 016+017
// (عامل and معمول are a matched pair — most of 017 only makes sense against 016's
// definitions), l2 covers 018's opening sections through الإعراب اللفظي, l3 covers
// التقديري and المحلي in full plus their contrast.
export default {
  id: '03',
  title: 'العامل والإعراب',
  heading: 'العامل وغير العامل',
  subheading: 'تمهيد',
  blurb: 'العامل والمعمول defined as a matched pair — what causes a grammatical state and what receives it — then الإعراب: its three لغوي senses and its three types, لفظي, تقديري, and محلي.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'العامل والمعمول',
      subtitle: 'The Governor and the Governed — العامل, المعمول, غير العامل, and غير المعمول',
      concepts: [
        {
          heading: 'العامل والمعمول والإعراب: ثلاثة مصطلحات مترابطة',
          lines: [
            { html: `Three terms recur constantly once grammar moves past the single كلمة: <bdi>العامل</bdi>, <bdi>المعمول</bdi>, and <bdi>الإعراب</bdi>.`, list: false },
            { table: { title: 'المصطلحات الثلاثة', headers: ['Term', 'Meaning'], rows: [
              [`العامل`, `what causes a grammatical state`],
              [`المعمول`, `what receives that grammatical state`],
              [`الإعراب`, `the grammatical state or change itself`],
            ] } },
            { html: `The three always appear together: an عامل acts on a معمول, and the result of that action is called إعراب. This lesson defines the first two; إعراب itself is the next lesson's subject.`, list: false },
          ],
          exercise: {
            prompt: `العامل, المعمول, and الإعراب are three linked terms. Which one names the word that CAUSES a grammatical state, rather than the word that receives it or the state itself?`,
            kind: 'mcq',
            options: [`العامل`, `المعمول`, `الإعراب`, `غير العامل`],
            correct: 0,
          },
        },
        {
          heading: 'تعريف العامل ومثاله',
          lines: [
            { box: { title: 'Definition', lines: [`العَامِلُ مَا يُوجِبُ حَالَةً`] } },
            { html: `An <bdi>عامل</bdi> brings about a grammatical state in another word.`, list: false },
            { box: { title: 'Example', lines: [`وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا`] } },
            { html: `"And we will never associate anyone with our Lord." <bdi>لن</bdi> affects the فعل after it and makes it منصوب.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `وَلَنْ نُشْرِكَ`,
                translation: `And we will never associate...`,
                cells: [`وَ`, `لَنْ`, `نُشْرِكَ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `حرف عطف` }, { start: 1, end: 1, role: `عامل ناصب` }, { start: 2, end: 2, role: `فعل مضارع منصوب` }] },
                ],
              },
            },
          ],
          exercise: {
            prompt: `In وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا, لن makes the فعل after it منصوب. Given العَامِلُ مَا يُوجِبُ حَالَةً, what does that make لن?`,
            kind: 'mcq',
            options: [`عامل`, `معمول`, `غير عامل`, `إعراب`],
            correct: 0,
          },
        },
        {
          heading: 'ما يكون عاملا: الأفعال، الحروف، الأسماء، الجملة، وشبه الجملة',
          lines: [
            { html: `Not every word class works the same way as an عامل.`, list: false },
            { table: { title: 'ما يكون عاملا؟', headers: ['Category', 'Status'], rows: [
              [`الأفعال`, `all of them are عوامل`],
              [`الحروف`, `some are عوامل, some are not`],
              [`الأسماء`, `some are عوامل, but most are not`],
              [`الجملة`, `never an عامل`],
              [`شبه الجملة`, `never an عامل`],
            ] } },
            { html: `Every فعل governs something connected to it — a فاعل, نائب فاعل, مفعول به, or another element, depending on the structure. Some حروف govern, such as <bdi>لن</bdi>; other حروف carry meaning but cause no grammatical state, and the two groups are roughly balanced. Some أسماء also govern, when they have the right form and conditions — certain مشتقات and مصدر constructions — but governing أسماء are the small minority; most أسماء perform no عمل at all.`, list: false },
            { html: `A <bdi>جملة</bdi> never performs عمل — this holds for the جملة كبرى and the جملة صغرى alike. <bdi>شبه الجملة</bdi> is the same: there is always an عامل working upon the شبه الجملة, and that عامل is what produces the جار ومجرور or الظرف, but the شبه الجملة itself governs nothing. It is always معمول, never عامل.`, list: false },
          ],
          exercise: {
            prompt: `الجملة and شبه الجملة share one thing in common when it comes to العمل. What is it?`,
            kind: 'mcq',
            options: [`Neither one is ever an عامل — a جملة never governs, and a شبه الجملة is always معمول, never عامل`, `Both are always عامل, never معمول`, `الجملة is always عامل, while شبه الجملة never is`, `Both are عامل only in poetry`],
            correct: 0,
          },
        },
        {
          heading: 'غير العامل: عاطل ومهمل',
          lines: [
            { box: { title: 'Definition', lines: [`غَيْرُ العَامِلِ مَا لا يُوجِبُ حَالَةً`] } },
            { html: `<bdi>غير العامل</bdi> does not cause a grammatical state, even if it still carries meaning.`, list: false },
            { box: { title: 'Example', lines: [`مَا أَشْرَكْنَا`] } },
            { html: `"We did not associate partners." Here <bdi>ما</bdi> gives نفي but does not change the grammatical state of أشركنا.`, list: false },
            { html: `A حرف غير عامل may be called by either of two names:`, list: false },
            { table: { title: 'عاطل ومهمل', headers: ['Term', 'Sense of the word', 'Intended meaning'], rows: [
              [`عاطل`, `idle, out of work, doing nothing`, `it performs no grammatical عمل`],
              [`مهمل`, `null and void, left with no effect`, `it performs no grammatical عمل`],
            ] } },
            { html: `Neither term means the حرف has no meaning — a حرف always has meaning. Calling it <bdi>مهمل</bdi> or <bdi>عاطل</bdi> only speaks about grammatical عمل, not about whether it contributes meaning.`, list: false },
          ],
          exercise: {
            prompt: `ما in مَا أَشْرَكْنَا is called عاطل or مهمل because it performs no grammatical عمل. Does that mean ما is meaningless?`,
            kind: 'mcq',
            options: [`No — ما still gives نفي; عاطل/مهمل only means it doesn't govern another word`, `Yes — عاطل and مهمل both mean the word carries no meaning at all`, `Yes, but only when it precedes a فعل ماضٍ`, `No — عاطل means meaningless, but مهمل does not`],
            correct: 0,
          },
        },
        {
          heading: 'تعريف المعمول ومثاله، وتلازمه بالعامل',
          lines: [
            { box: { title: 'Definition', lines: [`المَعْمُولُ مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ`] } },
            { html: `<bdi>المعمول</bdi> is what accepts a grammatical state from an عامل and has إعراب.`, list: false },
            { box: { title: 'Example', lines: [`مَا ضَلَّ صَاحِبُكُمْ`] } },
            { html: `"Your companion has not gone astray." صاحب is affected by the فعل ضل, so it is معمول.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `مَا ضَلَّ صَاحِبُكُمْ`,
                translation: `Your companion has not gone astray`,
                cells: [`مَا`, `ضَلَّ`, `صَاحِبُكُمْ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `حرف نفي غير عامل` }, { start: 1, end: 1, role: `عامل / فعل` }, { start: 2, end: 2, role: `معمول / فاعل مرفوع` }] },
                ],
              },
            },
            { html: `The relationship is always two-sided. In <bdi>قَامَ زَيْدٌ</bdi>, قام is the عامل and زيد is the معمول, because زيد receives رفع as the فاعل — every عامل needs something it acts on, and every معمول needs something acting on it.`, list: false },
          ],
          exercise: {
            prompt: `In قَامَ زَيْدٌ, زيد receives رفع because it is the فاعل of قام. Given المَعْمُولُ مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ, what role does زيد play?`,
            kind: 'mcq',
            options: [`المعمول`, `العامل`, `غير العامل`, `غير المعمول`],
            correct: 0,
          },
        },
        {
          heading: 'ما يكون معمولا وما لا يكون',
          lines: [
            { html: `Just as not every word class can be an عامل, not every word class can be a معمول either.`, list: false },
            { table: { title: 'ما يكون معمولا؟', headers: ['Category', 'Can be معمول', 'Cannot be معمول'], rows: [
              [`الاسم`, `all of them`, `except أسماء الأفعال`],
              [`الفعل`, `the مضارع, and the ماضي entered upon by a ناصب or جازم`, `the أمر, and the ماضي with no ناصب or جازم`],
              [`الحرف`, `none`, `all of them`],
              [`الجملة`, `some of them`, `some of them`],
              [`شبه الجملة`, `all of them`, `none`],
            ] } },
            { html: `Most أسماء are معمول because they accept states such as رفع, نصب, and جر: <bdi>جَاءَ زَيْدٌ</bdi> gives زيد رفع, <bdi>رَأَيْتُ زَيْدًا</bdi> gives it نصب, and <bdi>مَرَرْتُ بِزَيْدٍ</bdi> gives it جر. <bdi>اسم الفعل</bdi> is set aside from this rule because it resembles a فعل, and a فعل of that kind is not معمول.`, list: false },
            { html: `The <bdi>مضارع</bdi> becomes معمول when a ناصب or جازم enters upon it — <bdi>لَنْ نُشْرِكَ</bdi> is made منصوب, and <bdi>لَمْ يَفْعَلْ</bdi> is made مجزوم. The <bdi>ماضي</bdi> is normally مبني, but if a ناصب or جازم enters upon its structure, it may be described as منصوب محلا or مجزوم محلا — as in <bdi>بَعْدَ أَنْ نَزَغَ الشَّيْطَانُ</bdi> (منصوب محلا after أن) and <bdi>إِنْ فَعَلْتَ</bdi> (مجزوم محلا after إن الشرطية).`, list: false },
            { box: { title: 'Careful', lines: [`لَفْظُ المَاضِي يَبْقَى مَبْنِيًّا، وَالنَّصْبُ أَوِ الجَزْمُ فِي مَحَلِّهِ`] } },
            { html: `A question worth sitting with: if grammarians describe a ماضي after a ناصب or جازم as منصوب or مجزوم محلا, why do they not describe a plain ماضي with no such entry as مرفوع محلا? The point is raised here as a reflection on the terminology, not answered with a rule of its own.`, list: false },
          ],
          exercise: {
            prompt: `بَعْدَ أَنْ نَزَغَ الشَّيْطَانُ has أن entering upon the ماضي نَزَغَ. The ماضي itself stays مبني in wording. How is its grammatical state described?`,
            kind: 'mcq',
            options: [`منصوب محلا — the نصب belongs to its محل, not to a visible ending`, `منصوب لفظا — the ending itself changes to show نصب`, `مرفوع محلا, since every ماضي defaults to رفع`, `The ماضي has no grammatical state here at all`],
            correct: 0,
          },
        },
        {
          heading: 'غير المعمول: أسماء الأفعال، المبني، الحروف، والجمل',
          lines: [
            { box: { title: 'Definition', lines: [`غَيْرُ المَعْمُولِ مَا لا يَقْبَلُ حَالَةً وَلا يَكُونُ لَهُ إِعْرَابٌ`] } },
            { html: `<bdi>غير المعمول</bdi> does not accept a grammatical state and does not have إعراب. Four things fall under it.`, list: false },
            { table: { title: 'غير المعمول', headers: ['Category', 'Why it is غير معمول'], rows: [
              [`أسماء الأفعال`, `they behave like أفعال, not like ordinary أسماء`],
              [`الماضي بلا ناصب أو جازم، والأمر`, `they are مبني, so they take no إعراب on the ending`],
              [`كل الحروف`, `a حرف never becomes مرفوع, منصوب, مجرور, or مجزوم`],
              [`بعض الجمل`, `a جملة with no grammatical position to fill`],
            ] } },
            { html: `A حرف may be عامل, like لن, or غير عامل, like some uses of ما — but either way it is not معمول, because it does not itself receive إعراب. Some جمل are معمول because they occupy grammatical positions, such as خبر, حال, صفة, or مفعول به; other جمل occupy no such position and are غير معمول. Every شبه الجملة, by contrast, is معمول, because it connects to an عامل and occupies a grammatical position through that connection.`, list: false },
          ],
          exercise: {
            prompt: `لن is a حرف that is عامل. Does being عامل make لن a معمول as well?`,
            kind: 'mcq',
            options: [`No — every حرف is غير معمول, whether or not it is itself عامل, because a حرف never receives إعراب`, `Yes — any عامل حرف automatically becomes معمول too`, `No, because لن is غير عامل, not عامل`, `Yes, but only when it enters upon an اسم`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `العامل, المعمول, and الإعراب are three linked terms. Which one names what RECEIVES a grammatical state?`, options: [`المعمول`, `العامل`, `الإعراب`, `غير العامل`], correct: 0 },
        { q: `In وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا, لن makes the فعل after it منصوب. What does that make لن?`, options: [`عامل`, `معمول`, `غير عامل`, `مهمل`], correct: 0 },
        { q: `Which of these is true of الجملة and شبه الجملة regarding العمل?`, options: [`Neither is ever an عامل`, `Both are always عامل`, `الجملة is عامل; شبه الجملة is not`, `شبه الجملة is عامل; الجملة is not`], correct: 0 },
        { q: `ما in مَا أَشْرَكْنَا is called عاطل or مهمل. What does that actually mean?`, options: [`It performs no grammatical عمل — it can still carry meaning`, `It has no meaning at all`, `It is always مبني`, `It can never appear before a فعل`], correct: 0 },
        { q: `In قَامَ زَيْدٌ, زيد receives رفع as the فاعل of قام. What role does زيد play in the عامل/معمول pair?`, options: [`المعمول`, `العامل`, `غير العامل`, `غير المعمول`], correct: 0 },
        { q: `Which of the following is NOT one of the four categories of غير المعمول?`, options: [`المضارع entered upon by a ناصب`, `أسماء الأفعال`, `الأمر`, `كل الحروف`], correct: 0 },
      ],
      bank: [
        { title: `تعريف العامل`, kind: 'mcq', prompt: `Which of the following correctly defines العامل?`, options: [`مَا يُوجِبُ حَالَةً`, `مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ`, `مَا لا يُوجِبُ حَالَةً`, `مَا لا يَقْبَلُ حَالَةً وَلا يَكُونُ لَهُ إِعْرَابٌ`], correct: 0 },
        { title: `تعريف المعمول`, kind: 'mcq', prompt: `Which of the following correctly defines المعمول?`, options: [`مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ`, `مَا يُوجِبُ حَالَةً`, `مَا لا يُوجِبُ حَالَةً`, `مَا لا يَقْبَلُ حَالَةً`], correct: 0 },
        { title: `الأفعال: كلها عوامل؟`, kind: 'mcq', prompt: `Among الأفعال, الحروف, and الأسماء, which category is entirely made of عوامل, with no exceptions?`, options: [`الأفعال`, `الحروف`, `الأسماء`, `none of them entirely`], correct: 0 },
        { title: `الحروف: منقسمة`, kind: 'mcq', prompt: `Are الحروف uniformly عوامل, uniformly غير عوامل, or a mix?`, options: [`A mix — some حروف govern, some do not, roughly balanced`, `All حروف are عوامل`, `No حرف is ever عامل`, `Only حروف الجر are عوامل; every other حرف is غير عامل`], correct: 0 },
        { title: `الأسماء العاملة`, kind: 'mcq', prompt: `Governing أسماء exist, such as certain مشتقات and مصدر constructions. Are they the majority or the minority of أسماء?`, options: [`The minority — most أسماء perform no عمل`, `The majority — most أسماء govern something`, `Exactly half`, `أسماء never govern anything`], correct: 0 },
        { title: `الجملة الكبرى والصغرى`, kind: 'mcq', prompt: `Does a جملة صغرى behave any differently from a جملة كبرى when it comes to being an عامل?`, options: [`No — neither one ever performs عمل`, `Yes — الجملة الكبرى can be عامل but الصغرى cannot`, `Yes — الجملة الصغرى can be عامل but الكبرى cannot`, `Both can be عامل under certain conditions`], correct: 0 },
        { title: `شبه الجملة: عامل أم معمول؟`, kind: 'mcq', prompt: `A شبه الجملة (جار ومجرور or ظرف) always sits under the influence of some عامل. Is the شبه الجملة itself ever the عامل?`, options: [`No — it is always معمول, never عامل`, `Yes — it is always عامل`, `Only when it is a ظرف, not a جار ومجرور`, `Only in a جملة اسمية`], correct: 0 },
        { title: `عاطل ومهمل: نفس المعنى`, kind: 'mcq', prompt: `عاطل and مهمل are two different words applied to a حرف غير عامل. Do they point to two different grammatical facts, or the same one?`, options: [`The same one — both mean the حرف performs no grammatical عمل`, `عاطل means no meaning; مهمل means no عمل`, `مهمل means no meaning; عاطل means no عمل`, `They describe two unrelated grammatical categories`], correct: 0 },
        { title: `العامل والمعمول: علاقة متلازمة`, kind: 'mcq', prompt: `Can a sentence have an عامل acting with no معمول at all, or a معمول with no عامل acting on it?`, options: [`No — the relationship is two-sided: every عامل needs a معمول, and every معمول needs an عامل`, `Yes — عامل and معمول can each occur independently`, `Only معمول can occur without عامل`, `Only عامل can occur without معمول`], correct: 0 },
        { title: `اسم الفعل: استثناء`, kind: 'mcq', prompt: `Almost every اسم is معمول, but اسم الفعل is set aside from that rule. Why?`, options: [`Because it resembles a فعل, and a فعل of its kind is not معمول`, `Because it never appears with تنوين`, `Because it is always مركب`, `Because it always carries أل`], correct: 0 },
        { title: `جاء زيد، رأيت زيدا، مررت بزيد`, kind: 'mcq', prompt: `جَاءَ زَيْدٌ, رَأَيْتُ زَيْدًا, and مَرَرْتُ بِزَيْدٍ each give زيد a different grammatical state. What do the three states show about الاسم as a category?`, options: [`Most أسماء are معمول, since they can accept رفع, نصب, or جر`, `الاسم never accepts more than one state across different sentences`, `زيد is مبني in all three examples`, `Only رفع counts as a real grammatical state for الاسم`], correct: 0 },
        { title: `لن نشرك ولم يفعل`, kind: 'mcq', prompt: `لَنْ نُشْرِكَ makes its مضارع منصوب, and لَمْ يَفْعَلْ makes its مضارع مجزوم. What do both examples show about المضارع؟`, options: [`It becomes معمول once a ناصب or جازم enters upon it`, `It is always مبني, regardless of what enters upon it`, `It can never be معمول under any condition`, `Only لن can affect a مضارع; لم cannot`], correct: 0 },
        { title: `ماضي بلا ناصب أو جازم`, kind: 'mcq', prompt: `A plain ماضي with no ناصب or جازم entering upon it — is it معمول?`, options: [`No — it is مبني and falls under غير المعمول`, `Yes — every ماضي is معمول by default`, `Only if it follows a حرف جر`, `Only if its فاعل is مذكور`], correct: 0 },
        { title: `منصوب محلا أو مجزوم محلا`, kind: 'mcq', prompt: `When a ناصب or جازم enters upon a ماضي's structure, its لفظ stays مبني. How is its grammatical state then described?`, options: [`منصوب محلا or مجزوم محلا, depending on what entered upon it`, `منصوب لفظا, since the ending visibly changes`, `مرفوع لفظا, since ماضي defaults to رفع`, `It has no describable grammatical state at all`], correct: 0 },
        { title: `أسماء الأفعال: لماذا غير معمول`, kind: 'mcq', prompt: `أسماء الأفعال are placed under غير المعمول even though they are grammatically أسماء. Why?`, options: [`Because they behave like أفعال, not like ordinary أسماء`, `Because they never carry a meaning`, `Because they are always مبني على الفتح`, `Because they cannot appear at the start of a جملة`], correct: 0 },
        { title: `الحرف والإعراب`, kind: 'mcq', prompt: `Can a حرف ever become مرفوع, منصوب, مجرور, or مجزوم?`, options: [`No — a حرف never receives إعراب, so it is always غير معمول`, `Yes, if it is عامل`, `Yes, if it enters upon an اسم`, `Only حروف الجر can become مجرور`], correct: 0 },
        { title: `الحرف العامل ليس معمولا`, kind: 'mcq', prompt: `لن is a حرف عامل — it governs the فعل after it. Does being عامل make لن itself معمول?`, options: [`No — every حرف is غير معمول whether or not it is عامل`, `Yes — an عامل حرف is automatically معمول as well`, `Only when لن enters upon an اسم rather than a فعل`, `Only in poetry`], correct: 0 },
        { title: `الجملة: بعضها معمول`, kind: 'mcq', prompt: `Is every جملة غير معمول, or can a جملة be معمول?`, options: [`A جملة can be معمول when it occupies a position such as خبر, حال, صفة, or مفعول به; otherwise it is غير معمول`, `No جملة is ever معمول`, `Every جملة is معمول without exception`, `Only الجملة الكبرى can be معمول`],  correct: 0 },
        { title: `شبه الجملة: دائما معمول`, kind: 'mcq', prompt: `Unlike a جملة, is a شبه الجملة ever غير معمول?`, options: [`No — every شبه الجملة is معمول, because it connects to an عامل and occupies a grammatical position through that connection`, `Yes — a ظرف can be غير معمول while جار ومجرور cannot`, `Yes — most شبه الجملة constructions are غير معمول`, `A شبه الجملة is معمول only when it follows a فعل`], correct: 0 },
        {
          title: `تركيب: وَلَنْ نُشْرِكَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in وَلَنْ نُشْرِكَ.`,
          source: `وَلَنْ نُشْرِكَ`,
          words: [`وَ`, `لَنْ`, `نُشْرِكَ`],
          labels: [`حرف عطف`, `عامل ناصب`, `فعل مضارع منصوب`],
          distractors: [`مبتدأ`, `حرف جر`, `عامل جازم`, `فعل مضارع مجزوم`],
        },
        {
          title: `تركيب: مَا ضَلَّ صَاحِبُكُمْ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in مَا ضَلَّ صَاحِبُكُمْ.`,
          source: `مَا ضَلَّ صَاحِبُكُمْ`,
          words: [`مَا`, `ضَلَّ`, `صَاحِبُكُمْ`],
          labels: [`حرف نفي غير عامل`, `عامل / فعل`, `معمول / فاعل مرفوع`],
          distractors: [`مضاف إليه`, `حرف جر`, `عامل ناصب`, `مفعول به منصوب`],
        },
        {
          title: `تركيب: قَامَ زَيْدٌ`,
          kind: 'tarkeeb',
          instruction: `Identify which word is the عامل and which is the معمول in قَامَ زَيْدٌ.`,
          source: `قَامَ زَيْدٌ`,
          words: [`قَامَ`, `زَيْدٌ`],
          labels: [`فعل، وهو العامل`, `فاعل مرفوع، وهو المعمول`],
          distractors: [`مفعول به`, `حرف عطف`, `مبتدأ`, `حرف نفي غير عامل`],
        },
        {
          title: `تركيب: جَاءَ زَيْدٌ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in جَاءَ زَيْدٌ.`,
          source: `جَاءَ زَيْدٌ`,
          words: [`جَاءَ`, `زَيْدٌ`],
          labels: [`فعل`, `فاعل مرفوع، وهو معمول الفعل`],
          distractors: [`مبتدأ`, `مفعول به منصوب`, `عامل ناصب`, `حرف عطف`],
        },
        {
          title: `تركيب: رَأَيْتُ زَيْدًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of رَأَيْتُ زَيْدًا.`,
          source: `رَأَيْتُ زَيْدًا`,
          words: [`رَأَيْتُ`, `زَيْدًا`],
          labels: [`فعل وفاعله (تاء الفاعل)، وهو العامل`, `مفعول به منصوب، وهو المعمول`],
          distractors: [`فاعل مرفوع`, `حرف جر`, `مبتدأ مرفوع`, `عامل جازم`],
        },
        {
          title: `تركيب: لَمْ يَفْعَلْ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in لَمْ يَفْعَلْ.`,
          source: `لَمْ يَفْعَلْ`,
          words: [`لَمْ`, `يَفْعَلْ`],
          labels: [`عامل جازم`, `فعل مضارع مجزوم، وهو معمول لم`],
          distractors: [`حرف نفي غير عامل`, `فاعل مرفوع`, `عامل ناصب`, `فعل مضارع منصوب`],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'الإعراب',
      subtitle: 'الإعراب Defined — its three لغوي senses, its three أقسام, and الإعراب اللفظي',
      concepts: [
        {
          heading: 'تعريف الإعراب: أثر العامل',
          lines: [
            { box: { title: 'Definition', lines: [`الإِعْرَابُ أَثَرٌ يَجْلِبُهُ العَامِلُ فِي آخِرِ الكَلِمَةِ`] } },
            { html: `<bdi>الإعراب</bdi> is the effect brought by an عامل at the end of a كلمة. The عامل causes a grammatical state, and the أثر of that state is called إعراب. This أثر may appear as signs such as ضمة, فتحة, كسرة, or سكون, depending on the word and the grammatical position.`, list: false },
            { html: `This connects the three terms from the previous lesson into one chain.`, list: false },
            { table: { title: 'العامل والمعمول والإعراب', headers: ['Term', 'Meaning'], rows: [
              [`العامل`, `what brings about the grammatical state`],
              [`المعمول`, `what receives the grammatical state`],
              [`الإعراب`, `the أثر that appears, is estimated, or belongs to the محل`],
            ] } },
          ],
          exercise: {
            prompt: `الإعراب is defined as أَثَرٌ يَجْلِبُهُ العَامِلُ فِي آخِرِ الكَلِمَةِ. What actually produces that أثر?`,
            kind: 'mcq',
            options: [`The العامل, acting on a معمول`, `The معمول, acting on itself`, `The تنوين alone`, `The جملة as a whole, regardless of any عامل`],
            correct: 0,
          },
        },
        {
          heading: 'المعاني اللغوية الثلاثة للإعراب',
          lines: [
            { html: `The word إعراب has three لغوي (linguistic, not grammatical-technical) meanings, and these three senses explain what الإعراب is actually doing in a sentence.`, list: false },
            { table: { title: 'المعاني اللغوية للإعراب', headers: ['Linguistic meaning', 'Explanation'], rows: [
              [`الإظهار`, `إعراب makes the meanings of the words clear`],
              [`إزالة الفساد`, `إعراب removes the confusion caused by ambiguity`],
              [`التحسين`, `إعراب improves the wording`],
            ] } },
          ],
          exercise: {
            prompt: `إعراب has three لغوي senses. Which one names its role in preventing a sentence from being read ambiguously?`,
            kind: 'mcq',
            options: [`إزالة الفساد`, `الإظهار`, `التحسين`, `التقدير`],
            correct: 0,
          },
        },
        {
          heading: 'أقسام الإعراب الثلاثة',
          lines: [
            { html: `الإعراب itself divides into three types, depending on how the grammatical state actually shows up on the word.`, list: false },
            { table: { title: 'أقسام الإعراب', headers: ['Category', 'Definition'], rows: [
              [`الإعراب اللفظي`, `what appears in the pronounced wording`],
              [`الإعراب التقديري`, `what does not appear in the wording because of a مانع`],
              [`الإعراب المحلي`, `what does not appear because the word cannot carry an إعراب sign`],
            ] } },
            { html: `اللفظي is covered for the rest of this lesson. التقديري and المحلي, the two types where the sign does not surface in the لفظ, are covered together in the next lesson, where their difference is worked out in detail.`, list: false },
          ],
          exercise: {
            prompt: `Of the three أقسام الإعراب, which one is defined as the sign that actually appears in the pronounced wording?`,
            kind: 'mcq',
            options: [`الإعراب اللفظي`, `الإعراب التقديري`, `الإعراب المحلي`, `none of the three — all signs are silent`],
            correct: 0,
          },
        },
        {
          heading: 'الإعراب اللفظي: تعريفه ومثاله',
          lines: [
            { box: { title: 'Definition', lines: [`الإِعْرَابُ اللَّفْظِيُّ: مَا يَظْهَرُ فِي اللَّفْظِ`] } },
            { html: `<bdi>الإعراب اللفظي</bdi> is the إعراب that appears in the actual لفظ — the sign can be heard or seen on the end of the word.`, list: false },
            { box: { title: 'Example', lines: [`يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ`] } },
            {
              tarkeebDiagram: {
                sentence: `يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ`,
                cells: [`يَجْتَهِدُ`, `المُؤْمِنُ`, `فِي`, `الخَيْرِ`],
                rows: [
                  { position: 'above', labels: [
                    { start: 0, end: 0, role: `فعل مضارع مرفوع، وعلامة رفعه الضمة الظاهرة` },
                    { start: 1, end: 1, role: `فاعل مرفوع، وعلامة رفعه الضمة الظاهرة` },
                    { start: 2, end: 2, role: `حرف جر` },
                    { start: 3, end: 3, role: `اسم مجرور، وعلامة جره الكسرة الظاهرة` },
                  ] },
                ],
              },
            },
            { html: `The ضمة on يجتهد and المؤمن, and the كسرة on الخير, are all visible in the لفظ. That is why this is إعراب لفظي.`, list: false },
          ],
          exercise: {
            prompt: `In يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ, the ضمة on يجتهد and المؤمن and the كسرة on الخير can all be heard on the word itself. What type of إعراب does that make this?`,
            kind: 'mcq',
            options: [`الإعراب اللفظي`, `الإعراب التقديري`, `الإعراب المحلي`, `الإعراب الظاهري المقدر`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `الإعراب is defined as أَثَرٌ يَجْلِبُهُ العَامِلُ فِي آخِرِ الكَلِمَةِ. What brings about that أثر?`, options: [`العامل`, `المعمول`, `التنوين`, `الجملة, regardless of any عامل`], correct: 0 },
        { q: `Which لغوي meaning of إعراب describes its role in removing the confusion caused by ambiguity?`, options: [`إزالة الفساد`, `الإظهار`, `التحسين`, `الإسناد`], correct: 0 },
        { q: `Which لغوي meaning of إعراب describes it making the meanings of words clear?`, options: [`الإظهار`, `إزالة الفساد`, `التحسين`, `التقدير`], correct: 0 },
        { q: `الإعراب اللفظي is defined as:`, options: [`مَا يَظْهَرُ فِي اللَّفْظِ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`, `مَا يُوجِبُ حَالَةً`], correct: 0 },
        { q: `In يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ, the كسرة on الخير can be heard directly on the word. What does that make this إعراب?`, options: [`لفظي`, `تقديري`, `محلي`, `منصوب محلا`], correct: 0 },
        { q: `أقسام الإعراب are three. Which pair correctly lists two of them?`, options: [`الإعراب اللفظي and الإعراب التقديري`, `الإعراب الظاهر and الإعراب الباطن`, `الإعراب الأصلي and الإعراب الفرعي`, `الإعراب القوي and الإعراب الضعيف`], correct: 0 },
      ],
      bank: [
        { title: `تعريف الإعراب`, kind: 'mcq', prompt: `Which of the following correctly defines الإعراب?`, options: [`أَثَرٌ يَجْلِبُهُ العَامِلُ فِي آخِرِ الكَلِمَةِ`, `مَا يُوجِبُ حَالَةً`, `مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ`, `قَوْلٌ مُفْرَدٌ`], correct: 0 },
        { title: `إشارات الإعراب`, kind: 'mcq', prompt: `الإعراب's أثر may appear on a word as one of several signs. Which of the following is one of them?`, options: [`الضمة`, `التنوين وحده دومًا`, `الهمزة`, `الألف اللينة`], correct: 0 },
        { title: `العامل والمعمول والإعراب: ثلاثتها معًا`, kind: 'mcq', prompt: `Given العامل, المعمول, and الإعراب as a linked chain, which correctly matches the three?`, options: [`العامل brings the state about; المعمول receives it; الإعراب is the أثر that results`, `المعمول brings the state about; العامل receives it`, `الإعراب causes the state; العامل receives it`, `All three are just different names for the same thing`], correct: 0 },
        { title: `الإظهار`, kind: 'mcq', prompt: `الإظهار, one of إعراب's three لغوي senses, refers to what?`, options: [`إعراب making the meanings of words clear`, `إعراب removing ambiguity between two possible readings`, `إعراب making the wording sound better`, `إعراب being estimated rather than pronounced`], correct: 0 },
        { title: `إزالة الفساد`, kind: 'mcq', prompt: `إزالة الفساد, one of إعراب's three لغوي senses, refers to what?`, options: [`إعراب removing the confusion caused by ambiguity`, `إعراب improving how a word sounds`, `إعراب making a word's meaning clear`, `إعراب eliminating تنوين`], correct: 0 },
        { title: `التحسين`, kind: 'mcq', prompt: `التحسين, one of إعراب's three لغوي senses, refers to what?`, options: [`إعراب improving the wording`, `إعراب clarifying a word's meaning`, `إعراب removing ambiguity`, `إعراب marking a word as مبني`], correct: 0 },
        { title: `أقسام الإعراب: العدد`, kind: 'mcq', prompt: `How many أقسام does الإعراب divide into?`, options: [`Three: لفظي, تقديري, محلي`, `Two: ظاهر and مقدر`, `Four, including محذوف`, `Five, one for each إعراب sign`], correct: 0 },
        { title: `الإعراب اللفظي: تعريفه`, kind: 'mcq', prompt: `Which of the following correctly defines الإعراب اللفظي؟`, options: [`مَا يَظْهَرُ فِي اللَّفْظِ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`, `أَثَرٌ يَجْلِبُهُ العَامِلُ`], correct: 0 },
        { title: `يجتهد المؤمن: الفعل`, kind: 'mcq', prompt: `In يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ, يجتهد carries a visible ضمة. What is its grammatical state and إعراب type?`, options: [`فعل مضارع مرفوع، والإعراب لفظي`, `فعل مضارع منصوب، والإعراب تقديري`, `فعل مضارع مجزوم، والإعراب محلي`, `فعل ماضٍ مبني`], correct: 0 },
        { title: `يجتهد المؤمن: المؤمن`, kind: 'mcq', prompt: `In يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ, what is المؤمن's grammatical role, and what sign shows it?`, options: [`فاعل مرفوع، وعلامة رفعه الضمة الظاهرة`, `مفعول به منصوب، وعلامة نصبه الفتحة الظاهرة`, `مبتدأ مرفوع، وعلامة رفعه الضمة المقدرة`, `اسم مجرور بحرف الجر`], correct: 0 },
        { title: `يجتهد المؤمن: الخير`, kind: 'mcq', prompt: `In يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ, why is الخير مجرور, and what sign shows it?`, options: [`Because في enters upon it, and its علامة جره is a visible كسرة`, `Because it is مضاف إليه, with a مقدرة كسرة`, `Because it is فاعل, with a ظاهرة ضمة`, `It is not مجرور at all — في is غير عامل here`], correct: 0 },
        { title: `التمييز بين اللفظي والتقديري`, kind: 'mcq', prompt: `Both الإعراب اللفظي and الإعراب التقديري apply to a معرب word. What actually separates the two?`, options: [`Whether the sign is visible in the لفظ or only estimated because of a مانع`, `Whether the word is اسم or فعل`, `Whether the sign is رفع or نصب`, `They are two names for the same thing`], correct: 0 },
        { title: `الإعراب والمعنى: الرابط بينهما`, kind: 'mcq', prompt: `إعراب's three لغوي senses (الإظهار, إزالة الفساد, التحسين) all point to what الإعراب does. What is that, broadly?`, options: [`It clarifies a sentence's meaning by marking each word's grammatical role`, `It changes a word's root meaning entirely`, `It removes تنوين from every اسم`, `It converts every فعل into an اسم`], correct: 0 },
        { title: `أثر العامل: أين يظهر؟`, kind: 'mcq', prompt: `الإعراب is described as an أثر that appears specifically where?`, options: [`In آخر الكلمة — the end of the word`, `At the start of the جملة`, `Only on حروف الجر`, `Only on الفعل الماضي`], correct: 0 },
        { title: `العامل يجلب الأثر، لا العكس`, kind: 'mcq', prompt: `Does المعمول ever cause إعراب on the العامل, or is the direction fixed?`, options: [`The direction is fixed: the عامل brings about the أثر on the معمول, never the reverse`, `Either can cause إعراب on the other, depending on the sentence`, `المعمول always causes إعراب on the عامل`, `Neither one causes إعراب; إعراب is random`], correct: 0 },
        { title: `أقسام الإعراب: ما الذي يبقى للدرس القادم؟`, kind: 'mcq', prompt: `Of the three أقسام الإعراب, which two share the fact that their sign does not appear in the لفظ, though for different reasons?`, options: [`الإعراب التقديري and الإعراب المحلي`, `الإعراب اللفظي and الإعراب التقديري`, `الإعراب اللفظي and الإعراب المحلي`, `None of them share that trait`], correct: 0 },
        {
          title: `تركيب: يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role and إعراب sign of each word in يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ.`,
          source: `يَجْتَهِدُ المُؤْمِنُ فِي الخَيْرِ`,
          words: [`يَجْتَهِدُ`, `المُؤْمِنُ`, `فِي`, `الخَيْرِ`],
          labels: [`فعل مضارع مرفوع، وعلامة رفعه الضمة الظاهرة`, `فاعل مرفوع، وعلامة رفعه الضمة الظاهرة`, `حرف جر`, `اسم مجرور، وعلامة جره الكسرة الظاهرة`],
          distractors: [`مفعول به منصوب`, `مبتدأ مرفوع بضمة مقدرة`, `اسم مجرور، وعلامة جره الكسرة المقدرة`, `حرف عطف`],
        },
        {
          title: `تركيب: العامل والمعمول والإعراب`,
          kind: 'tarkeeb',
          instruction: `Match each term to its role: العامل, المعمول, الإعراب.`,
          source: `العامل — المعمول — الإعراب`,
          words: [`العامل`, `المعمول`, `الإعراب`],
          labels: [`ما يجلب الحالة`, `ما يقبل الحالة`, `الأثر الناتج في آخر الكلمة`],
          distractors: [`ما لا يوجب حالة`, `ما لا يقبل حالة`, `ما يظهر في اللفظ`, `ما لا يظهر في اللفظ لمانع`],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'التقديري والمحلي',
      subtitle: 'الإعراب التقديري and المحلي — where the sign is estimated, and where it belongs only to the محل',
      concepts: [
        {
          heading: 'الإعراب التقديري: تعريفه ومثاله',
          lines: [
            { box: { title: 'Definition', lines: [`الإِعْرَابُ التَّقْدِيرِيُّ: مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`] } },
            { html: `<bdi>الإعراب التقديري</bdi> is إعراب that does not appear in the لفظ because something prevents it from appearing.`, list: false },
            { box: { title: 'Example', lines: [`يَسْعَى الفَتَى إِلَى الهُدَى`] } },
            {
              tarkeebDiagram: {
                sentence: `يَسْعَى الفَتَى إِلَى الهُدَى`,
                cells: [`يَسْعَى`, `الفَتَى`, `إِلَى`, `الهُدَى`],
                rows: [
                  { position: 'above', labels: [
                    { start: 0, end: 0, role: `فعل مضارع مرفوع، وعلامة رفعه الضمة المقدرة` },
                    { start: 1, end: 1, role: `فاعل مرفوع، وعلامة رفعه الضمة المقدرة` },
                    { start: 2, end: 2, role: `حرف جر` },
                    { start: 3, end: 3, role: `اسم مجرور، وعلامة جره الكسرة المقدرة` },
                  ] },
                ],
              },
            },
            { html: `The signs do not appear clearly because these words end with an ألف مقصورة. The مانع prevents the visible pronunciation of the علامة.`, list: false },
          ],
          exercise: {
            prompt: `In يَسْعَى الفَتَى إِلَى الهُدَى, the words end with an ألف مقصورة, so the expected ضمة and كسرة cannot be pronounced. What kind of إعراب is that?`,
            kind: 'mcq',
            options: [`الإعراب التقديري`, `الإعراب اللفظي`, `الإعراب المحلي`, `no إعراب at all`],
            correct: 0,
          },
        },
        {
          heading: 'احتراز في الإعراب التقديري: الكلمة معربة رغم اختفاء العلامة',
          lines: [
            { box: { title: 'Careful', lines: [`فِي الإِعْرَابِ التَّقْدِيرِيِّ، الكَلِمَةُ تَقْبَلُ الإِعْرَابَ، وَإِنَّمَا العَلَامَةُ لا تَظْهَرُ فِي اللَّفْظِ`] } },
            { html: `The word in الإعراب التقديري is still <bdi>معرب</bdi> — it fully accepts a grammatical state. The علامة exists in grammatical judgement; it is only مقدرة (estimated) rather than pronounced, because the مانع blocks its actual sound, not the word's capacity to carry it.`, list: false },
            { html: `This is what separates التقديري from a word that genuinely cannot take إعراب at all — the difference matters enough that the next concept and the one after it work it out fully against المحلي.`, list: false },
          ],
          exercise: {
            prompt: `In الإعراب التقديري, a مانع stops the علامة from being pronounced. Does that mean the word itself cannot carry إعراب?`,
            kind: 'mcq',
            options: [`No — the word is fully معرب; only the pronunciation of its علامة is blocked`, `Yes — a مانع always means the word is مبني`, `Yes, but only for الفعل المضارع, not for الاسم`, `No, but only if the مانع is a حرف علة other than الألف`],
            correct: 0,
          },
        },
        {
          heading: 'الإعراب المحلي: تعريفه ومثاله',
          lines: [
            { box: { title: 'Definition', lines: [`الإِعْرَابُ المَحَلِّيُّ: مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`] } },
            { html: `<bdi>الإعراب المحلي</bdi> is إعراب that does not appear because the word itself cannot carry an علامة الإعراب at all. This applies to مبني words and structures that occupy a grammatical محل.`, list: false },
            { box: { title: 'Example', lines: [`تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ`] } },
            {
              tarkeebDiagram: {
                sentence: `تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ`,
                cells: [`تَسْعَيْنَ`, `أَنْتُنَّ`, `إِلَيْهِ`],
                rows: [
                  { position: 'above', labels: [
                    { start: 0, end: 0, role: `فعل مضارع مبني على السكون لاتصاله بنون النسوة` },
                    { start: 1, end: 1, role: `ضمير منفصل مبني في محل رفع` },
                    { start: 2, end: 2, role: `جار ومجرور، والهاء ضمير مبني في محل جر` },
                  ] },
                ],
              },
            },
            { html: `تسعين is a مضارع connected to نون النسوة, so it is مبني على السكون.`, list: false },
            { html: `أنتن is also مبني. The هاء in إليه is مبني too. These words do not show إعراب by changing their endings, but they occupy grammatical positions — their إعراب is therefore described by محل.`, list: false },
          ],
          exercise: {
            prompt: `In تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ, none of the three words changes its ending to show a grammatical state, yet each occupies a real grammatical position. What kind of إعراب is that?`,
            kind: 'mcq',
            options: [`الإعراب المحلي`, `الإعراب اللفظي`, `الإعراب التقديري`, `no إعراب at all, since none of the words is معرب`],
            correct: 0,
          },
        },
        {
          heading: 'لماذا لا تظهر العلامة في المحلي: البناء',
          lines: [
            { html: `The reason الإعراب المحلي's sign never appears is different in kind from التقديري's reason. In التقديري, the word is معرب, and a مانع only blocks the pronunciation. In المحلي, the word is <bdi>مبني</bdi> — its ending is fixed by its own structure, not by any عامل, so there was never a changeable علامة الإعراب to begin with.`, list: false },
            { html: `تسعين is مبني على السكون specifically because of its اتصال بنون النسوة, not because of any مانع.`, list: false },
            { html: `أنتن, a ضمير منفصل, is مبني by its very nature as a pronoun. The هاء in إليه is a ضمير متصل, also مبني by nature. None of the three could ever show a changing إعراب sign, with or without an عامل acting on it.`, list: false },
          ],
          exercise: {
            prompt: `تسعين is مبني على السكون. What causes that بناء specifically?`,
            kind: 'mcq',
            options: [`Its اتصال بنون النسوة`, `A مانع blocking its ضمة from appearing`, `Its position as فاعل`, `The حرف جر before it`],
            correct: 0,
          },
        },
        {
          heading: 'الفرق بين التقديري والمحلي',
          lines: [
            { html: `التقديري and المحلي both leave no visible sign in the لفظ, which is exactly why they are easy to confuse. The difference is in what the word itself can do.`, list: false },
            { table: { title: 'التقديري والمحلي', headers: ['Type', 'Can the word carry an علامة الإعراب?', 'What happens?'], rows: [
              [`الإعراب التقديري`, `yes`, `the sign is estimated because of a مانع`],
              [`الإعراب المحلي`, `no`, `the word is مبني, but it has an إعرابي محل`],
            ] } },
            { html: `In الإعراب التقديري, the word is معرب, but its علامة is hidden. In الإعراب المحلي, the word is مبني — or the structure cannot show إعراب directly — so the grammatical judgement belongs to its محل instead of to any ending on the word.`, list: false },
          ],
          exercise: {
            prompt: `يَسْعَى (in يَسْعَى الفَتَى) and تَسْعَيْنَ (in تَسْعَيْنَ أَنْتُنَّ) both fail to show a visible إعراب sign. What actually separates them?`,
            kind: 'mcq',
            options: [`يَسْعَى is معرب with a مانع blocking its sign (تقديري); تَسْعَيْنَ is مبني and was never going to show one (محلي)`, `They are the same case, both تقديري`, `They are the same case, both محلي`, `يَسْعَى is مبني and تَسْعَيْنَ is معرب — the reverse of the real distinction`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `الإعراب التقديري is defined as:`, options: [`مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`, `مَا يَظْهَرُ فِي اللَّفْظِ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`, `أَثَرٌ يَجْلِبُهُ العَامِلُ`], correct: 0 },
        { q: `In يَسْعَى الفَتَى إِلَى الهُدَى, why do the expected إعراب signs not appear?`, options: [`Because the words end in ألف مقصورة, which blocks their pronunciation`, `Because الفتى and الهدى are مبني`, `Because يسعى has no فاعل`, `Because في is a حرف غير عامل`], correct: 0 },
        { q: `In الإعراب التقديري, is the word معرب or مبني?`, options: [`معرب — only the pronunciation of its علامة is blocked`, `مبني — it never had a changeable ending`, `Neither — it has no grammatical state at all`, `It depends on whether it is اسم or فعل`], correct: 0 },
        { q: `الإعراب المحلي is defined as:`, options: [`مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`, `مَا يَظْهَرُ فِي اللَّفْظِ`, `مَا يَقْبَلُ حَالَةً`], correct: 0 },
        { q: `In تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ, تسعين is مبني على السكون. What causes that بناء?`, options: [`Its اتصال بنون النسوة`, `A مانع from an ألف مقصورة`, `Its position as مفعول به`, `The جار ومجرور after it`], correct: 0 },
        { q: `What is the core difference between الإعراب التقديري and الإعراب المحلي?`, options: [`In التقديري the word is معرب with a hidden sign; in المحلي the word is مبني and was never going to show one`, `التقديري applies only to الفعل; المحلي applies only to الاسم`, `They are two names for the same phenomenon`, `التقديري shows the sign audibly; المحلي shows it in writing only`], correct: 0 },
      ],
      bank: [
        { title: `تعريف الإعراب التقديري`, kind: 'mcq', prompt: `Which of the following correctly defines الإعراب التقديري؟`, options: [`مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`, `مَا يَظْهَرُ فِي اللَّفْظِ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`, `مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ`], correct: 0 },
        { title: `تعريف الإعراب المحلي`, kind: 'mcq', prompt: `Which of the following correctly defines الإعراب المحلي؟`, options: [`مَا لا يَظْهَرُ فِي اللَّفْظِ لِعَدَمِ تَحَمُّلِ الكَلِمَةِ عَلامَةَ الإِعْرَابِ`, `مَا لا يَظْهَرُ فِي اللَّفْظِ لِمَانِعٍ`, `أَثَرٌ يَجْلِبُهُ العَامِلُ`, `مَا يُوجِبُ حَالَةً`], correct: 0 },
        { title: `يسعى الفتى: سبب اختفاء العلامة`, kind: 'mcq', prompt: `In يَسْعَى الفَتَى إِلَى الهُدَى, what specifically blocks the إعراب signs from appearing?`, options: [`The ألف المقصورة each word ends in`, `The fact that الفتى is مبني`, `The absence of a عامل altogether`, `في being a حرف عامل غير مؤثر`], correct: 0 },
        { title: `يسعى: نوع الإعراب`, kind: 'mcq', prompt: `يَسْعَى in يَسْعَى الفَتَى إِلَى الهُدَى is فعل مضارع مرفوع, but its ضمة does not sound. What type of إعراب is this?`, options: [`تقديري`, `لفظي`, `محلي`, `no إعراب at all`], correct: 0 },
        { title: `الفتى: نوع الإعراب`, kind: 'mcq', prompt: `الفتى in يَسْعَى الفَتَى إِلَى الهُدَى is فاعل مرفوع. Why doesn't its ضمة appear?`, options: [`Because a مانع — the ألف المقصورة — blocks it, even though الفتى is fully معرب`, `Because الفتى is مبني على الضم`, `Because فاعل never takes a visible علامة`, `Because الفتى has no إعراب at all here`], correct: 0 },
        { title: `الهدى: نوع الإعراب`, kind: 'mcq', prompt: `الهدى in يَسْعَى الفَتَى إِلَى الهُدَى is اسم مجرور. Why is its كسرة تقديرية rather than ظاهرة?`, options: [`Because it ends in ألف مقصورة, which blocks the كسرة from sounding`, `Because في is غير عامل`, `Because الهدى is مبني`, `Because مجرور words never take a visible sign`], correct: 0 },
        { title: `الكلمة المعربة رغم اختفاء العلامة`, kind: 'mcq', prompt: `In الإعراب التقديري, a word's علامة does not sound, yet the word is still described as معرب. What does معرب mean here?`, options: [`The word is capable of accepting a grammatical state — a مانع only blocks the sign's pronunciation`, `The word has no grammatical state of any kind`, `The word is مبني but occupies a محل`, `The word's ending physically changes even though nobody can hear it`], correct: 0 },
        { title: `تسعين: سبب البناء`, kind: 'mcq', prompt: `تَسْعَيْنَ in تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ is مبني على السكون. Why?`, options: [`Because of its اتصال بنون النسوة`, `Because it ends in ألف مقصورة`, `Because a حرف جر precedes it`, `Because every فعل مضارع is مبني`], correct: 0 },
        { title: `أنتن: نوعها`, kind: 'mcq', prompt: `أنتن in تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ is ضمير منفصل مبني في محل رفع. What does في محل رفع mean here?`, options: [`أنتن occupies the grammatical position of فاعل, even though it shows no visible رفع sign, because it is مبني`, `أنتن is actually مرفوع لفظا with a hidden ضمة`, `أنتن has no grammatical role in this جملة`, `أنتن is مجرور, not مرفوع, despite the label`], correct: 0 },
        { title: `الهاء في إليه`, kind: 'mcq', prompt: `In تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ, the هاء of إليه is ضمير مبني في محل جر. Why is it described as في محل rather than simply مجرور؟`, options: [`Because الهاء, as a ضمير متصل, cannot carry a visible علامة الإعراب at all — it is مبني`, `Because the جار ومجرور construction blocks all إعراب`, `Because الهاء is تقديرية, like a word ending in ألف مقصورة`, `Because إليه has no grammatical role`], correct: 0 },
        { title: `المانع مقابل عدم التحمل`, kind: 'mcq', prompt: `What is the key structural difference between why تقديري's sign is hidden and why محلي's sign is hidden?`, options: [`تقديري: a مانع blocks a sign the word CAN carry. محلي: the word can never carry a sign at all, being مبني`, `Both are hidden for exactly the same reason`, `تقديري: the word is مبني; محلي: a مانع blocks the sign`, `Neither type ever has a real cause — both are arbitrary`], correct: 0 },
        { title: `المحلي والبناء`, kind: 'mcq', prompt: `Every case of الإعراب المحلي involves a word or structure that is:`, options: [`مبني, or otherwise unable to show إعراب directly on its ending`, `معرب, with a مانع hiding its sign`, `Always a فعل, never an اسم`, `Always a حرف جر`], correct: 0 },
        { title: `متى تُستخدم عبارة "في محل"؟`, kind: 'mcq', prompt: `Grammar books describe a مبني word as being "في محل رفع" or "في محل نصب." What does that phrasing capture?`, options: [`That the word occupies a grammatical position even though its own ending cannot show the sign for it`, `That the word's ending visibly shows the sign, just weakly`, `That the word is تقديرية, like a defective-ending اسم`, `That the position is optional and could be omitted`], correct: 0 },
        { title: `تمييز عملي: مانع أم عدم تحمل؟`, kind: 'mcq', prompt: `A given اسم ends in a regular consonant and shows no visible إعراب because it is a ضمير. Is that التقديري or المحلي؟`, options: [`المحلي — a ضمير is مبني by nature, so it was never going to carry a sign`, `التقديري — some مانع must be blocking its sign`, `Neither — ضمائر are outside الإعراب altogether`, `اللفظي — its sign is simply invisible to the eye but present in speech`], correct: 0 },
        { title: `تمييز عملي: علامة ظاهرة أم مقدرة أم محلية؟`, kind: 'mcq', prompt: `An اسم ends in ألف مقصورة and is مرفوع. Its expected ضمة cannot be pronounced on that ending. Which إعراب type is this?`, options: [`تقديري`, `لفظي`, `محلي`, `it has no إعراب at all`], correct: 0 },
        {
          title: `تركيب: يَسْعَى الفَتَى إِلَى الهُدَى`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role and إعراب type of each word in يَسْعَى الفَتَى إِلَى الهُدَى.`,
          source: `يَسْعَى الفَتَى إِلَى الهُدَى`,
          words: [`يَسْعَى`, `الفَتَى`, `إِلَى`, `الهُدَى`],
          labels: [`فعل مضارع مرفوع، وعلامة رفعه الضمة المقدرة`, `فاعل مرفوع، وعلامة رفعه الضمة المقدرة`, `حرف جر`, `اسم مجرور، وعلامة جره الكسرة المقدرة`],
          distractors: [`مفعول به منصوب بفتحة ظاهرة`, `مبتدأ مرفوع بضمة ظاهرة`, `فاعل مرفوع، وعلامة رفعه الضمة الظاهرة`, `حرف عطف`],
        },
        {
          title: `تركيب: تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role and إعراب type of each part of تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ.`,
          source: `تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ`,
          words: [`تَسْعَيْنَ`, `أَنْتُنَّ`, `إِلَيْهِ`],
          labels: [`فعل مضارع مبني على السكون لاتصاله بنون النسوة`, `ضمير منفصل مبني في محل رفع`, `جار ومجرور، والهاء ضمير مبني في محل جر`],
          distractors: [`فعل مضارع معرب بضمة ظاهرة`, `فاعل مرفوع بضمة مقدرة`, `مبتدأ مرفوع`, `اسم مجرور، وعلامة جره الكسرة الظاهرة`],
        },
      ],
    },
  ],
};
