// Module 16 — الرسم والوصل والوقف: أول ثلاثة أبواب من خاتمة النحو
//
// Content is adapted from the first three sub-decks of النَحْوُ__5
// الخاتمة__3 الحرف.apkg (36 notes: 08 Orthography 12, 09 Wasl 14, 10 Waqf
// 10). The fourth sub-topic of this deck, وجوه الكلمات (140 notes across
// four further sub-decks), is large enough on its own to form Module 17 —
// this module covers only the three "mechanics of the written/spoken
// word" topics: رسم الحروف (where writing and pronunciation of a word
// diverge), الوصل (connecting speech: همزة الوصل and التقاء الساكنين),
// and الوقف (how to stop correctly on a word).

export default {
  id: '16',
  title: 'الرسم والوصل والوقف',
  heading: 'الخاتمة',
  blurb: 'How to write, join, and pause on a word correctly: الرسم, الوصل, and الوقف.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'رسم الحروف',
      subtitle: 'Orthography — where the Uthmanic script writes a letter that isn’t pronounced, or drops one that is',
      concepts: [
        {
          heading: 'موضوع خاتمة النحو، ومجالا الرسم',
          lines: [
            { html: `The <bdi>خَاتِمَة</bdi> that closes An-Nahw covers four topics: <bdi>رَسْمُ الْحُرُوف</bdi> — orthography, <bdi>الْوَصْل</bdi> — joining in speech, <bdi>الْوَقْف</bdi> — stopping on a word, and <bdi>وُجُوهُ الْكَلِمَات</bdi> — the multiple usages of individual words.`, list: false },
            { html: `الرسم itself studies two things: <bdi>مَا يُكْتَبُ وَلَا يُلْفَظ</bdi> — what is written but not pronounced, and <bdi>مَا يُلْفَظُ وَلَا يُكْتَب</bdi> — what is pronounced but not written.`, list: false },
          ],
          exercise: {
            prompt: `الرسم chapter studies two things. What are they?`,
            kind: 'mcq',
            options: ['What is written but not pronounced, and what is pronounced but not written', 'الوصل, and الوقف', 'همزة الوصل, and التقاء الساكنين', 'رسم الحروف, and وجوه الكلمات'],
            correct: 0,
          },
        },
        {
          heading: 'الألف التي تُكتب ولا تُلفظ',
          lines: [
            { html: `Two cases write an alif that is never pronounced:`, list: false },
            { html: `after the <bdi>وَاوُ الْجَمَاعَةِ</bdi> of the raised attached pronoun, as in <bdi>أَطَاعُوا</bdi>`, list: true, bullet: true },
            { html: `in the word <bdi>مِائَة</bdi>`, list: true, bullet: true },
            { html: `In both, the extra alif is a pure feature of the Uthmanic script, silent in speech.`, list: false },
          ],
          exercise: {
            prompt: `Which alif is written but never pronounced?`,
            kind: 'mcq',
            options: ['The alif after وَاوُ الْجَمَاعَةِ in أَطَاعُوا', 'The alif of the sound masculine plural ﴿الْعٰلَمِينَ﴾', 'The alif of the pronoun نَا before هَاءُ وَأَخَوَاتُهَا', 'The alif of the اسم منقوص at the end of a verse'],
            correct: 0,
          },
        },
        {
          heading: 'الألف التي تُلفظ ولا تُكتب (الرسم العثماني)',
          lines: [
            { html: `In الرسم العثماني, an underlying alif is dropped from the writing (though still pronounced) in four cases:`, list: false },
            { table: { headers: ['الحالة', 'Example'], rows: [
              ['the sound masculine plural', '﴿الْعٰلَمِينَ﴾'],
              ['the sound feminine plural', '﴿كَلِمٰتٍ﴾'],
              ['a foreign proper name exceeding three letters', '﴿إِبْرٰهِمَ وَإِسْمٰعِيلَ وَإِسْحٰقَ﴾'],
              ['the pronoun نَا before الْهَاءُ وَأَخَوَاتُهَا', '﴿زِدْنٰهُمْ﴾'],
            ] } },
          ],
          exercise: {
            prompt: `﴿زِدْنٰهُمْ﴾ drops the alif of the pronoun نَا from the writing. Which of these three also drops a pronounced alif in الرسم العثماني?`,
            kind: 'mcq',
            options: ['﴿كَلِمٰتٍ﴾ — the sound feminine plural', 'أَطَاعُوا — the alif after واو الجماعة', 'مِائَة', 'الوقف على تاء التأنيث المربوطة'],
            correct: 0,
          },
        },
        {
          heading: 'حذف الياء والواو رسمًا',
          lines: [
            { html: `The yāʾ is dropped from the writing in five cases:`, list: false },
            { table: { headers: ['الحالة', 'Example'], rows: [
              ['mid-word when two yāʾs meet', '﴿الْأُمِّيّٖنَ﴾'],
              ['at the end of a word when two yāʾs meet', '﴿يُحْيٖ﴾'],
              ['when followed by a sākin', '﴿يُنَادِ الْمُنَادِ﴾'],
              ['at the end of a verse', '﴿الْكَبِيرُ الْمُتَعَالِ﴾'],
              ['when mudāf to the speaker’s yāʾ in a vocative', '﴿رَبِّ اجْعَلْنِي مُقِيمَ الصَّلٰوةِ﴾'],
            ] } },
            { html: `The wāw is dropped in one case: when it meets a sākin wāw after a dammah, e.g. ﴿يَسْتَوٗنَ﴾ (i.e. يستوون).`, list: false },
          ],
          exercise: {
            prompt: `Why is the yāʾ of ﴿الْكَبِيرُ الْمُتَعَالِ﴾ dropped from the writing?`,
            kind: 'mcq',
            options: ['It falls at the end of a verse', 'Two yāʾs meet mid-word', 'It is followed by a sākin', 'It is mudāf to the speaker’s yāʾ'],
            correct: 0,
          },
        },
        {
          heading: 'الألف المتطرفة: في الثلاثي وما زاد عليه',
          lines: [
            { html: `A final alif in a three-letter word (<bdi>الْأَلِفُ الْمُتَطَرِّفَةُ فِي الثُّلَاثِيّ</bdi>) is written as <bdi>ى</bdi> (dotless yāʾ shape) when its origin is a yāʾ, as in <bdi>سَعَى الفَتَى إلَى الهُدَى</bdi>, and as a plain <bdi>ا</bdi> when its origin is a wāw, as in <bdi>دَعا النَّبِيُّ ﷺ بِالْخُلُقِ لا بِالْعَصا</bdi>.`, list: false },
            { html: `In a word of four letters or more, the final alif is always written <bdi>ى</bdi>, regardless of origin, as in <bdi>الْمُصْطَفَى</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `عَصا is written with a plain alif (ا) while هُدَى is written with ى. What explains the difference?`,
            kind: 'mcq',
            options: ['عصا’s origin is a wāw (عَصَوَانِ); هدى’s origin is a yāʾ', 'عصا is four letters; هدى is three', 'عصا is مبني; هدى is معرب', 'There is no rule — the spelling is arbitrary'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What are the two areas of study within رسم الحروف?',
          options: ['ما يُكتب ولا يُلفظ, and ما يُلفظ ولا يُكتب', 'الوصل, and الوقف', 'همزة الوصل, and التقاء الساكنين', 'الاسم, and الفعل'],
          correct: 0,
        },
        {
          q: 'Which two cases write an alif that is never pronounced?',
          options: ['The alif after واو الجماعة in أَطَاعُوا, and the alif of مِائَة', 'The alif of ﴿الْعٰلَمِينَ﴾, and the alif of ﴿كَلِمٰتٍ﴾', 'The alif of foreign names, and نَا before الهاء', 'None — every alif in Arabic is pronounced'],
          correct: 0,
        },
        {
          q: 'In الرسم العثماني, in how many cases is a pronounced alif omitted from the writing?',
          options: ['Two', 'Three', 'Four', 'Five'],
          correct: 2,
        },
        {
          q: '﴿يُنَادِ الْمُنَادِ﴾ drops the yāʾ of يُنَادِ. Why?',
          options: ['Because a sākin follows it', 'Because two yāʾs meet mid-word', 'Because it falls at the end of a verse', 'Because it is mudāf to the speaker’s yāʾ'],
          correct: 0,
        },
        {
          q: 'When is the wāw dropped from the writing?',
          options: ['When it meets a sākin wāw after a dammah, as in ﴿يَسْتَوٗنَ﴾', 'When it meets a sākin wāw after a kasrah', 'At the end of every verse', 'When mudāf to the speaker’s yāʾ'],
          correct: 0,
        },
        {
          q: 'الْمُصْطَفَى (four letters or more) writes its final alif as:',
          options: ['ى, regardless of the alif’s origin', 'ا, regardless of the alif’s origin', 'ى if the origin is wāw, ا if yāʾ', 'Whichever the reciter prefers'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'أربعة أبواب الخاتمة',
          kind: 'mcq',
          prompt: 'The خاتمة that closes An-Nahw is built from how many chapters, and what are they?',
          options: ['Four: رسم الحروف, الوصل, الوقف, وجوه الكلمات', 'Three: الاسم, الفعل, الحرف', 'Two: ما يُكتب, وما يُلفظ', 'Five, adding التركيب'],
          correct: 0,
        },
        {
          title: 'أَطاعُوا',
          kind: 'mcq',
          prompt: 'Identify the rasm rule in أَطاعُوا.',
          options: ['An alif after واو الجماعة, written but not pronounced', 'An alif of the sound masculine plural, pronounced but not written', 'A yāʾ dropped because a sākin follows', 'A wāw dropped after a dammah'],
          correct: 0,
        },
        {
          title: 'مِائَة',
          kind: 'mcq',
          prompt: 'مِائَة carries a silent alif in its spelling. What licenses it?',
          options: ['It is one of only two words/contexts where an unpronounced alif is written', 'It is a foreign proper name exceeding three letters', 'It is the sound feminine plural', 'It is mudāf to the speaker’s yāʾ'],
          correct: 0,
        },
        {
          title: '﴿الْعٰلَمِينَ﴾',
          kind: 'mcq',
          prompt: 'Which rasm rule explains the missing alif in ﴿الْعٰلَمِينَ﴾?',
          options: ['The sound masculine plural drops its pronounced alif in writing', 'The sound feminine plural drops its pronounced alif', 'A foreign name exceeding three letters drops its alif', 'نَا before هاء وأخواتها drops its alif'],
          correct: 0,
        },
        {
          title: '﴿كَلِمٰتٍ﴾',
          kind: 'mcq',
          prompt: 'Which case of alif-omission does ﴿كَلِمٰتٍ﴾ illustrate?',
          options: ['The sound feminine plural', 'The sound masculine plural', 'A foreign proper name', 'نَا before الهاء وأخواتها'],
          correct: 0,
        },
        {
          title: '﴿إِبْرٰهِمَ وَإِسْمٰعِيلَ وَإِسْحٰقَ﴾',
          kind: 'mcq',
          prompt: 'These three names all drop a pronounced alif from the writing. What is the condition?',
          options: ['Being a foreign proper name of more than three letters', 'Being a sound masculine plural', 'Being مضاف to نا', 'Being a اسم منقوص at the end of a verse'],
          correct: 0,
        },
        {
          title: '﴿زِدْنٰهُمْ﴾ revisited',
          kind: 'mcq',
          prompt: 'What exactly is omitted from ﴿زِدْنٰهُمْ﴾’s spelling?',
          options: ['The alif of the pronoun نَا, before الهاء وأخواتها', 'The yāʾ of the اسم منقوص', 'The wāw of الجماعة', 'The alif of the sound masculine plural'],
          correct: 0,
        },
        {
          title: '﴿الْأُمِّيّٖنَ﴾',
          kind: 'mcq',
          prompt: 'Why does ﴿الْأُمِّيّٖنَ﴾ drop one of its yāʾs in writing?',
          options: ['Two yāʾs meet mid-word', 'Two yāʾs meet at the end of the word', 'A sākin follows the yāʾ', 'The word ends a verse'],
          correct: 0,
        },
        {
          title: '﴿يُحْيٖ﴾',
          kind: 'mcq',
          prompt: 'Why does ﴿يُحْيٖ﴾ drop its final yāʾ in writing?',
          options: ['Two yāʾs meet at the end of the word', 'Two yāʾs meet mid-word', 'It is mudāf to the speaker’s yāʾ', 'It falls at the end of a verse'],
          correct: 0,
        },
        {
          title: '﴿رَبِّ اجْعَلْنِي مُقِيمَ الصَّلٰوةِ﴾',
          kind: 'mcq',
          prompt: '﴿رَبِّ﴾ here drops its yāʾ in writing. Why?',
          options: ['It is mudāf to the speaker’s yāʾ in a vocative', 'A sākin follows it', 'It falls at the end of a verse', 'Two yāʾs meet mid-word'],
          correct: 0,
        },
        {
          title: '﴿يَسْتَوٗنَ﴾',
          kind: 'mcq',
          prompt: 'What is dropped from the writing of ﴿يَسْتَوٗنَ﴾ (originally يستوون), and under what condition?',
          options: ['A wāw, when a sākin wāw meets a dammah before it', 'A yāʾ, when two yāʾs meet', 'An alif, after واو الجماعة', 'A hamzah, at the start of the word'],
          correct: 0,
        },
        {
          title: 'سَعَى vs دَعا',
          kind: 'mcq',
          prompt: 'Why is the final alif of سَعَى written ى while the final alif of دَعا is written ا?',
          options: ['سَعَى’s alif originates from a yāʾ; دَعا’s originates from a wāw', 'سَعَى is four letters; دَعا is three', 'سَعَى is a فعل; دَعا is an اسم', 'There is no rule distinguishing them'],
          correct: 0,
        },
        {
          title: 'إلَى الهُدَى',
          kind: 'mcq',
          prompt: 'الهُدَى ends in a final alif written as ى. What does that spelling reveal about the alif’s origin?',
          options: ['That it originates from a yāʾ (هَدَيَ)', 'That it originates from a wāw', 'That the word is رباعي', 'That the alif is زائدة, not أصلية'],
          correct: 0,
        },
        {
          title: 'الْمُصْطَفَى',
          kind: 'mcq',
          prompt: 'الْمُصْطَفَى has more than three letters. How is its final alif written, regardless of origin?',
          options: ['ى, dotless', 'ا, plain', 'Either ى or ا, freely', 'It is dropped entirely'],
          correct: 0,
        },
        {
          title: 'لا بِالْعَصا',
          kind: 'mcq',
          prompt: 'العصا traces back to عَصَوان. What does that origin tell us about how its final alif is spelled?',
          options: ['A plain ا, because the alif’s origin is a wāw', 'A dotless ى, because the alif’s origin is a yāʾ', 'Either spelling, since عصا is only three letters', 'ى, because it is mudāf'],
          correct: 0,
        },
        {
          title: 'رسم الحروف: التعريف',
          kind: 'mcq',
          prompt: 'الرسم as a topic studies:',
          options: ['Where writing and pronunciation of a word diverge', 'Where to stop when reading aloud', 'How to connect one word to the next in recitation', 'The multiple grammatical uses of a single word'],
          correct: 0,
        },
        {
          title: 'ما يُكتب ولا يُلفظ',
          kind: 'mcq',
          prompt: 'Which of these is an example of ما يُكتب ولا يُلفظ?',
          options: ['The alif of أَطَاعُوا', 'The alif of ﴿الْعٰلَمِينَ﴾', 'The yāʾ of ﴿يُحْيٖ﴾', 'The wāw of ﴿يَسْتَوٗنَ﴾'],
          correct: 0,
        },
        {
          title: 'ما يُلفظ ولا يُكتب',
          kind: 'mcq',
          prompt: 'Which of these is an example of ما يُلفظ ولا يُكتب?',
          options: ['The alif of ﴿كَلِمٰتٍ﴾', 'The alif of أَطَاعُوا', 'The alif of مِائَة', 'None — everything pronounced is also written'],
          correct: 0,
        },
        {
          title: 'تركيب: الرِّجَالُ أَطَاعُوا رَبَّهُمْ',
          kind: 'tarkeeb',
          instruction: 'Classify the alif after واو الجماعة here.',
          sentence: 'الرِّجَالُ أَطَاعُوا رَبَّهُمْ',
          cells: ['الرِّجَالُ', 'أَطَاعُوا', 'رَبَّهُمْ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'تُكتب ولا تُلفظ' }] }],
          distractors: ['تُلفظ ولا تُكتب'],
        },
        {
          title: 'تركيب: عِنْدِي مِائَةُ كِتَابٍ',
          kind: 'tarkeeb',
          instruction: 'Classify the alif of مائة here.',
          sentence: 'عِنْدِي مِائَةُ كِتَابٍ',
          cells: ['عِنْدِي', 'مِائَةُ', 'كِتَابٍ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'تُكتب ولا تُلفظ' }] }],
          distractors: ['تُلفظ ولا تُكتب'],
        },
        {
          title: 'تركيب: ﴿رَبِّ الْعَالَمِينَ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify the alif of العالمين in الرسم العثماني.',
          sentence: 'رَبِّ الْعَالَمِينَ',
          cells: ['رَبِّ', 'الْعَالَمِينَ'],
          rows: [
            { position: 'above', label: 'الرسم', labels: [{ start: 1, end: 1, role: 'تُلفظ ولا تُكتب' }] },
            { position: 'below', label: 'السبب', labels: [{ start: 1, end: 1, role: 'جمع مذكر سالم' }] },
          ],
          distractors: ['تُكتب ولا تُلفظ', 'جمع مؤنث سالم'],
        },
        {
          title: 'تركيب: ﴿رَبَّنَا زِدْنَاهُمْ عَذَابًا﴾',
          kind: 'tarkeeb',
          instruction: 'Classify the alif of نا in الرسم العثماني.',
          sentence: 'رَبَّنَا زِدْنَاهُمْ عَذَابًا',
          cells: ['رَبَّنَا', 'زِدْنَاهُمْ', 'عَذَابًا'],
          rows: [
            { position: 'above', label: 'الرسم', labels: [{ start: 1, end: 1, role: 'تُلفظ ولا تُكتب' }] },
            { position: 'below', label: 'السبب', labels: [{ start: 1, end: 1, role: 'نا قبل الهاء وأخواتها' }] },
          ],
          distractors: ['تُكتب ولا تُلفظ', 'اسم أعجمي فوق ثلاثة أحرف'],
        },
        {
          title: 'تركيب: ﴿قَالَتِ الْأَعْرَابُ كَلِمَاتٍ﴾',
          kind: 'tarkeeb',
          instruction: 'Why is the alif of كلمات dropped from الرسم العثماني؟',
          sentence: 'قَالَتِ الْأَعْرَابُ كَلِمَاتٍ',
          cells: ['قَالَتِ', 'الْأَعْرَابُ', 'كَلِمَاتٍ'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'جمع مؤنث سالم' }] }],
          distractors: ['جمع مذكر سالم', 'اسم أعجمي فوق ثلاثة أحرف'],
        },
        {
          title: 'تركيب: ﴿وَإِبْرَاهِيمَ وَإِسْمَاعِيلَ وَإِسْحَاقَ﴾',
          kind: 'tarkeeb',
          instruction: 'Why is the alif of these names dropped from الرسم العثماني؟',
          sentence: 'وَإِبْرَاهِيمَ وَإِسْمَاعِيلَ وَإِسْحَاقَ',
          cells: ['وَإِبْرَاهِيمَ', 'وَإِسْمَاعِيلَ', 'وَإِسْحَاقَ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'اسم أعجمي فوق ثلاثة أحرف' }] }],
          distractors: ['جمع مذكر سالم', 'نا قبل الهاء وأخواتها'],
        },
        {
          title: 'تركيب: ﴿فِي أُمِّهَا الْأُمِّيِّينَ﴾',
          kind: 'tarkeeb',
          instruction: 'Why is one ياء of الأميين dropped in writing؟',
          sentence: 'فِي أُمِّهَا الْأُمِّيِّينَ',
          cells: ['فِي', 'أُمِّهَا', 'الْأُمِّيِّينَ'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'التقاء يائين وسط الكلمة' }] }],
          distractors: ['التقاء يائين آخر الكلمة', 'مجيء ساكن بعدها'],
        },
        {
          title: 'تركيب: ﴿إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ فَلَمَّا يُحْيِ﴾',
          kind: 'tarkeeb',
          instruction: 'Why is the final ياء of يُحيِ dropped in writing؟',
          sentence: 'فَلَمَّا يُحْيِ',
          cells: ['فَلَمَّا', 'يُحْيِ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'التقاء يائين آخر الكلمة' }] }],
          distractors: ['التقاء يائين وسط الكلمة', 'مجيء ساكن بعدها'],
        },
        {
          title: 'تركيب: ﴿يُنَادِ الْمُنَادِ لِيَوْمٍ﴾',
          kind: 'tarkeeb',
          instruction: 'Why is the ياء of يُنَادِ dropped in writing؟',
          sentence: 'يُنَادِ الْمُنَادِ لِيَوْمٍ',
          cells: ['يُنَادِ', 'الْمُنَادِ', 'لِيَوْمٍ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'مجيء ساكن بعدها' }] }],
          distractors: ['التقاء يائين وسط الكلمة', 'آخر آية'],
        },
        {
          title: 'تركيب: ﴿ذُو الْجَلَالِ وَالْإِكْرَامِ الْكَبِيرُ الْمُتَعَالِ﴾',
          kind: 'tarkeeb',
          instruction: 'Why is the ياء of المتعالي dropped in writing؟',
          sentence: 'ذُو الْجَلَالِ وَالْإِكْرَامِ الْكَبِيرُ الْمُتَعَالِ',
          cells: ['ذُو', 'الْجَلَالِ', 'وَالْإِكْرَامِ', 'الْكَبِيرُ', 'الْمُتَعَالِ'],
          rows: [{ position: 'above', labels: [{ start: 4, end: 4, role: 'آخر آية' }] }],
          distractors: ['مجيء ساكن بعدها', 'التقاء يائين وسط الكلمة'],
        },
        {
          title: 'تركيب: سَعَى الْفَتَى إِلَى الْهُدَى',
          kind: 'tarkeeb',
          instruction: 'Classify أصل الألف المتطرفة في سعى.',
          sentence: 'سَعَى الْفَتَى إِلَى الْهُدَى',
          cells: ['سَعَى', 'الْفَتَى', 'إِلَى', 'الْهُدَى'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'أصلها ياء (ثلاثي)' }] }],
          distractors: ['أصلها واو (ثلاثي)'],
        },
        {
          title: 'تركيب: دَعَا النَّبِيُّ ﷺ لَا بِالْعَصَا',
          kind: 'tarkeeb',
          instruction: 'Classify أصل الألف المتطرفة في دعا.',
          sentence: 'دَعَا النَّبِيُّ لَا بِالْعَصَا',
          cells: ['دَعَا', 'النَّبِيُّ', 'لَا', 'بِالْعَصَا'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'أصلها واو (ثلاثي)' }] }],
          distractors: ['أصلها ياء (ثلاثي)'],
        },
        {
          title: 'تركيب: هَٰذَا الْمُصْطَفَى',
          kind: 'tarkeeb',
          instruction: 'Classify قاعدة الألف المتطرفة في المصطفى (رباعي فأكثر).',
          sentence: 'هَٰذَا الْمُصْطَفَى',
          cells: ['هَٰذَا', 'الْمُصْطَفَى'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'رباعي فأكثر: ى دائمًا' }] }],
          distractors: ['ثلاثي: أصلها ياء', 'ثلاثي: أصلها واو'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'الوصل',
      subtitle: 'Connected Speech — همزة الوصل and how to resolve two sākins meeting',
      concepts: [
        {
          heading: 'الوصل: تعريفه ومجالا دراسته',
          lines: [
            { html: `<bdi>الْوَصْل</bdi> means not cutting off the sound at the end of a word, continuing it into the next — the default in speech, e.g. reading <bdi>الدِّينُ النَّصِيحَةْ</bdi> connectedly.`, list: false },
            { html: `Its chapter studies two things: <bdi>هَمْزَةُ الْوَصْل</bdi> and <bdi>الْتِقَاءُ سَاكِنَيْنِ</bdi> — the meeting of two sākins.`, list: false },
          ],
          exercise: {
            prompt: `الوصل is defined as:`,
            kind: 'mcq',
            options: ['Not cutting off the sound at the end of a word, in connected speech', 'Cutting off the sound at the end of a word', 'Writing a letter that is not pronounced', 'Dropping the vowel at the end of a word'],
            correct: 0,
          },
        },
        {
          heading: 'همزة الوصل: تعريفها ومواضعها',
          lines: [
            { html: `<bdi>هَمْزَةُ الْوَصْل</bdi> is a hamzah written at the start of a word: pronounced when beginning with the word (<bdi>ابْتِدَاءً</bdi>), dropped in connected speech (<bdi>وَصْلًا</bdi>), e.g. <bdi>اِقْرَأِ الْقُرْآنَ وَاعْمَلْ بِهِ</bdi>. It has four positions:`, list: false },
            { table: { headers: ['#', 'الموضع', 'Example'], rows: [
              ['1', 'the noun defined by أل', 'الرَّبُّ'],
              ['2', 'the nouns اسم، است، ابن، ابنُم، ابنة، امرئ، امرأة, their duals, اثنين واثنتين, and ايْمُنُ اللهِ', '—'],
              ['3', 'the أمر of the three-letter verb', 'اعْرِفْ رَبَّكَ واعْبُدْهُ'],
              ['4', 'the ماضي exceeding four letters, its أمر, and its مصدر', 'اسْتَغْفَرَ، اسْتَغْفِرْ، اسْتِغْفارٌ'],
            ] } },
            { html: `Within case 2, the alif of <bdi>ابن</bdi> is dropped when ابن is a بدل sitting between a name and the name of the person’s actual father, e.g. <bdi>مُحَمَّدُ بْنُ عَبْدِ اللهِ ﷺ</bdi>, but kept otherwise, e.g. <bdi>عَبْدِ اللهِ بْنِ أُبَيٍّ ابْنِ سَلُولَ</bdi> (Salūl was not his father).`, list: false },
          ],
          exercise: {
            prompt: `In مُحَمَّدُ بْنُ عَبْدِ اللهِ ﷺ, the alif of ابن is dropped. Why, when عَبْدِ اللهِ بْنِ أُبَيٍّ ابْنِ سَلُولَ keeps it?`,
            kind: 'mcq',
            options: ['Here ابن is a بدل sitting between a name and the name of the person’s real father', 'Here ابن begins a new sentence', 'Here ابن is مرفوع, not مجرور', 'There is no rule — spelling of ابن is free'],
            correct: 0,
          },
        },
        {
          heading: 'أثر دخول أل على همزة الوصل',
          lines: [
            { html: `When <bdi>أل</bdi> enters upon a word that itself begins with a همزة وصل, the <bdi>لام</bdi> of أل takes a <bdi>كسرة</bdi> and the word’s own همزة الوصل is dropped: one says <bdi>الِاجْتِنابُ مِنَ المَعاصي خَيْرٌ مِنَ الِاسْتِغْفارِ لَهُ</bdi> — never <bdi>الِائْتِجناب</bdi> nor <bdi>الِائْستغفار</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `أل enters upon اجتناب (whose own first letter carries a همزة وصل). What happens?`,
            kind: 'mcq',
            options: ['The لام of أل takes a كسرة, and اجتناب’s own همزة الوصل drops', 'Both hamzahs are kept and pronounced', 'The لام of أل is dropped instead', 'The word becomes الائتجناب'],
            correct: 0,
          },
        },
        {
          heading: 'التقاء الساكنين: تعريفه وما يقع منه على حَدِّه',
          lines: [
            { html: `<bdi>الْتِقَاءُ سَاكِنَيْنِ</bdi> (also <bdi>اجْتِمَاعُ سَاكِنَيْنِ</bdi>) splits into two: <bdi>عَلَى حَدِّهِ</bdi> — within its proper limit, tolerated as-is — and <bdi>عَلَى غَيْرِ حَدِّهِ</bdi> — outside its limit, which must be resolved.`, list: false },
            { html: `على حده occurs in two cases: at <bdi>الوَقْف</bdi>, e.g. ﴿بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيمْ﴾, and when a <bdi>حرف مد</bdi> is followed by an assimilated (<bdi>مُدْغَم</bdi>) letter, e.g. ﴿الضَّالِّينَ﴾.`, list: false },
          ],
          exercise: {
            prompt: `Two sākins meeting على حده are tolerated as-is. In which two cases does this happen?`,
            kind: 'mcq',
            options: ['At الوقف, and when a حرف مد is followed by a مدغم letter', 'At الابتداء, and before every همزة وصل', 'In every ماضي verb, and every مضارع verb', 'Only in the Qur’an, never in ordinary speech'],
            correct: 0,
          },
        },
        {
          heading: 'التقاء الساكنين على غير حَدِّه: الحذف والحركات الثلاث',
          lines: [
            { html: `When two sākins meet outside the proper limit, the clash must be resolved:`, list: false },
            { table: { headers: ['الحل', 'When', 'Example'], rows: [
              ['حذف الأول', 'if it is a حرف مد', 'written النَّجاةُ في الصِّدْقِ but pronounced النَّجاةُ فِ الصِّدْقِ'],
              ['ضَمَّة على الأول', 'if it is المِيمُ الجَمْعِ or the plural verb’s soft wāw', 'هُمُ النّاصِحونَ؛ دَعَوُا اللهَ (originally دَعَوْا)'],
              ['فَتْحَة على الأول', 'if it is the nūn of مِنْ', 'الإِخْلاصُ مِنَ النَّصيحَةِ'],
              ['كَسْرَة على الأول', 'a sound letter, the nūn of tanwīn, or a soft (لِين) letter', 'نَصَحَتِ الأُمُّ؛ خَديجَةُ ناصِحَةٌنِ الصَّدِّيقاتِ؛ صُمْ يَوْمَيِ التّاسوعاءِ'],
            ] } },
          ],
          exercise: {
            prompt: `دَعَوُا اللهَ carries a dammah on the wāw. Why?`,
            kind: 'mcq',
            options: ['The first of two meeting sākins is the plural verb’s soft wāw, so it takes a dammah', 'It is the nūn of مِنْ, so it takes a fathah', 'It is a حرف مد, so it is deleted', 'It is a sound letter, so it takes a kasrah'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is الوصل?',
          options: ['Not cutting off the sound at the end of a word — the default in speech', 'Cutting off the sound at the end of a word', 'A hamzah pronounced only at the start of speech', 'The meeting of two sākins'],
          correct: 0,
        },
        {
          q: 'همزة الوصل is dropped:',
          options: ['In connected speech (وصلًا), though pronounced when beginning with the word', 'Always, in every context', 'Only in the Qur’an', 'Only after أل التعريف'],
          correct: 0,
        },
        {
          q: 'In how many positions does همزة الوصل occur?',
          options: ['Two', 'Three', 'Four', 'Five'],
          correct: 2,
        },
        {
          q: 'When أل enters a word whose first letter carries همزة الوصل, what happens to that همزة?',
          options: ['It is dropped, and the لام of أل takes a كسرة', 'It is kept, and pronounced fully', 'It turns into همزة قطع', 'Nothing changes at all'],
          correct: 0,
        },
        {
          q: 'التقاء ساكنين على حَدِّه is tolerated in which two cases?',
          options: ['At الوقف, and a حرف مد before a مدغم letter', 'Before every همزة وصل, and after every تنوين', 'Only in poetry, never in the Qur’an', 'At الابتداء, and before the نون الوقاية'],
          correct: 0,
        },
        {
          q: 'When two sākins meet outside their proper limit and the first is a حرف مد, what happens to it?',
          options: ['It is deleted from pronunciation', 'It takes a dammah', 'It takes a fathah', 'It is written but not pronounced, like همزة الوصل'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الأصل في الكلام',
          kind: 'mcq',
          prompt: 'What is the default (الأصل) way of reading connected speech?',
          options: ['وصلاً — continuing the sound into the next word', 'وقفًا — cutting the sound off after every word', 'بالتنوين دائمًا', 'بهمزة القطع دائمًا'],
          correct: 0,
        },
        {
          title: 'اِقْرَأِ الْقُرْآنَ',
          kind: 'mcq',
          prompt: 'The همزة at the start of اِقْرَأِ is a همزة وصل. What happens to it when this phrase is read after another word (وصلًا)?',
          options: ['It is dropped from pronunciation', 'It is pronounced with a فتحة', 'It turns into همزة قطع', 'It is written but never pronounced, even at the start'],
          correct: 0,
        },
        {
          title: 'الرَّبُّ',
          kind: 'mcq',
          prompt: 'Which موضع of همزة الوصل does الرَّبُّ illustrate?',
          options: ['الاسم المعرف بأل', 'اسم من الأسماء الستة المسموعة (اسم، ابن...)', 'أمر الثلاثي', 'ماضي فوق أربعة أحرف'],
          correct: 0,
        },
        {
          title: 'اعْرِفْ رَبَّكَ',
          kind: 'mcq',
          prompt: 'اعْرِفْ opens with a همزة وصل. Which موضع does it illustrate?',
          options: ['أمر الفعل الثلاثي', 'الاسم المعرف بأل', 'ماضي فوق أربعة أحرف ومصدره', 'الأسماء الستة المسموعة'],
          correct: 0,
        },
        {
          title: 'اسْتَغْفَرَ، اسْتَغْفِرْ، اسْتِغْفارٌ',
          kind: 'mcq',
          prompt: 'These three words all open with همزة وصل. What do they have in common?',
          options: ['A ماضي of more than four letters, its أمر, and its مصدر', 'All three are أسماء معرفة بأل', 'All three are من الأسماء الستة المسموعة', 'All three are أفعال ثلاثية'],
          correct: 0,
        },
        {
          title: 'ابن بين علمين',
          kind: 'mcq',
          prompt: 'مُحَمَّدُ بْنُ عَبْدِ اللهِ drops the alif of ابن. What condition allows that?',
          options: ['ابن is a بدل sitting between a name and the name of the actual father', 'ابن is مرفوع here', 'ابن begins the sentence', 'ابن is مثنى here'],
          correct: 0,
        },
        {
          title: 'ابن ليس بدلاً',
          kind: 'mcq',
          prompt: 'عَبْدِ اللهِ بْنِ أُبَيٍّ ابْنِ سَلُولَ keeps the alif of the second ابن. Why?',
          options: ['Salūl was not the actual father, so ابن here is not a بدل between the two names', 'It is مرفوع, unlike the first ابن', 'It follows a اسم معرف بأل', 'There is no rule — spelling of ابن is arbitrary'],
          correct: 0,
        },
        {
          title: 'الِاجْتِنابُ',
          kind: 'mcq',
          prompt: 'Why is الِاجْتِنابُ correct, rather than الِائْتِجناب?',
          options: ['The word’s own همزة الوصل drops once أل enters, and the لام of أل takes a كسرة', 'اجتناب has no همزة وصل to begin with', 'أل never combines with a همزة وصل at all', 'Both spellings are accepted interchangeably'],
          correct: 0,
        },
        {
          title: 'اجتماع ساكنين',
          kind: 'mcq',
          prompt: 'التقاء ساكنين is also known by which other name?',
          options: ['اجتماع ساكنين', 'همزة الوصل', 'الرسم العثماني', 'لام الجواب'],
          correct: 0,
        },
        {
          title: '﴿الرَّحِيمْ﴾ at a stop',
          kind: 'mcq',
          prompt: 'Stopping on ﴿…الرَّحِيمْ﴾ leaves two sākins in a row. Why is this tolerated rather than resolved?',
          options: ['Because it occurs at الوقف, one of the two cases عَلَى حَدِّهِ', 'Because a حرف مد always resolves itself', 'Because الوقف never produces سواكن', 'Because the reciter must add a vowel here'],
          correct: 0,
        },
        {
          title: '﴿الضَّالِّينَ﴾',
          kind: 'mcq',
          prompt: 'A حرف مد is followed by a مُدْغَم (assimilated) letter in ﴿الضَّالِّينَ﴾. Is this التقاء ساكنين resolved or tolerated?',
          options: ['Tolerated — على حَدِّه', 'Resolved by deleting the حرف مد', 'Resolved by adding a كسرة', 'Resolved by adding a فتحة'],
          correct: 0,
        },
        {
          title: 'النَّجاةُ فِ الصِّدْقِ',
          kind: 'mcq',
          prompt: 'Why is the wāw of فِي dropped in pronunciation before الصِّدْقِ?',
          options: ['It is a حرف مد meeting a following sākin outside its proper limit, so it is deleted', 'It is the ميم الجمع', 'It is the nūn of مِنْ', 'It is a soft (لين) letter'],
          correct: 0,
        },
        {
          title: 'هُمُ النّاصِحونَ',
          kind: 'mcq',
          prompt: 'Why does the ميم of هُمْ take a dammah before النّاصِحونَ?',
          options: ['It is the ميم الجمع, the first of two meeting sākins', 'It is the nūن of مِنْ', 'It is a حرف مد', 'It is a soft (لين) letter'],
          correct: 0,
        },
        {
          title: 'مِنَ النَّصيحَةِ',
          kind: 'mcq',
          prompt: 'مِنْ takes a fathah on its nūn before النَّصيحَةِ. Why a fathah rather than a kasrah?',
          options: ['Because it is specifically the nūn of مِنْ', 'Because it is a sound (صحيح) letter', 'Because it is the nūn of tanwīn', 'Because it is a soft (لين) letter'],
          correct: 0,
        },
        {
          title: 'نَصَحَتِ الأُمُّ',
          kind: 'mcq',
          prompt: 'The تاء of نَصَحَتْ takes a kasrah before الأُمُّ. Why?',
          options: ['It is a sound (صحيح) letter, one of the three kasrah cases', 'It is the ميم الجمع', 'It is the nūn of مِنْ', 'It is a حرف مد'],
          correct: 0,
        },
        {
          title: 'خَديجَةُ ناصِحَةٌنِ الصَّدِّيقاتِ',
          kind: 'mcq',
          prompt: 'The kasrah appearing here belongs to which of the three كسرة cases?',
          options: ['نون التنوين', 'ميم الجمع', 'نون مِنْ', 'حرف لين'],
          correct: 0,
        },
        {
          title: 'يَوْمَيِ التّاسوعاءِ',
          kind: 'mcq',
          prompt: 'The dual’s soft yāʾ takes a kasrah before التّاسوعاءِ. Which of the three كسرة cases is this?',
          options: ['A soft (لين) letter', 'A sound (صحيح) letter', 'نون التنوين', 'ميم الجمع'],
          correct: 0,
        },
        {
          title: 'دَعَوُا اللهَ',
          kind: 'mcq',
          prompt: 'The wāw of دَعَوْا (originally) takes a dammah before اللهَ. Which case is this?',
          options: ['The plural verb’s soft wāw, one of the two dammah cases', 'The nūn of مِنْ', 'A sound letter, one of the three kasrah cases', 'A حرف مد, deleted outright'],
          correct: 0,
        },
        {
          title: 'تركيب: هَٰذَا الرَّبُّ',
          kind: 'tarkeeb',
          instruction: 'Classify موضع همزة الوصل هنا.',
          sentence: 'هَٰذَا الرَّبُّ',
          cells: ['هَٰذَا', 'الرَّبُّ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'الاسم المعرف بأل' }] }],
          distractors: ['أمر الثلاثي', 'ماضي فوق أربعة أحرف'],
        },
        {
          title: 'تركيب: اعْرِفْ رَبَّكَ وَاعْبُدْهُ',
          kind: 'tarkeeb',
          instruction: 'Classify موضع همزة الوصل هنا.',
          sentence: 'اعْرِفْ رَبَّكَ وَاعْبُدْهُ',
          cells: ['اعْرِفْ', 'رَبَّكَ', 'وَاعْبُدْهُ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'أمر الثلاثي' }] }],
          distractors: ['الاسم المعرف بأل', 'ماضي فوق أربعة أحرف'],
        },
        {
          title: 'تركيب: اسْتَغْفَرَ الرَّجُلُ رَبَّهُ',
          kind: 'tarkeeb',
          instruction: 'Classify موضع همزة الوصل هنا.',
          sentence: 'اسْتَغْفَرَ الرَّجُلُ رَبَّهُ',
          cells: ['اسْتَغْفَرَ', 'الرَّجُلُ', 'رَبَّهُ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'ماضي فوق أربعة أحرف' }] }],
          distractors: ['الاسم المعرف بأل', 'أمر الثلاثي'],
        },
        {
          title: 'تركيب: هَٰذَا اسْمٌ جَمِيلٌ',
          kind: 'tarkeeb',
          instruction: 'Classify موضع همزة الوصل هنا.',
          sentence: 'هَٰذَا اسْمٌ جَمِيلٌ',
          cells: ['هَٰذَا', 'اسْمٌ', 'جَمِيلٌ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'من الأسماء الستة المسموعة' }] }],
          distractors: ['الاسم المعرف بأل', 'أمر الثلاثي'],
        },
        {
          title: 'تركيب: ﴿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمْ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify التقاء الساكنين هنا عند الوقف.',
          sentence: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمْ',
          cells: ['بِسْمِ', 'اللَّهِ', 'الرَّحْمَٰنِ', 'الرَّحِيمْ'],
          rows: [{ position: 'above', labels: [{ start: 3, end: 3, role: 'على حَدِّه' }] }],
          distractors: ['على غير حَدِّه'],
        },
        {
          title: 'تركيب: ﴿غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify التقاء الساكنين هنا (حرف مد قبل مدغم).',
          sentence: 'غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
          cells: ['غَيْرِ', 'الْمَغْضُوبِ', 'عَلَيْهِمْ', 'وَلَا', 'الضَّالِّينَ'],
          rows: [{ position: 'above', labels: [{ start: 4, end: 4, role: 'على حَدِّه' }] }],
          distractors: ['على غير حَدِّه'],
        },
        {
          title: 'تركيب: النَّجَاةُ فِي الصِّدْقِ',
          kind: 'tarkeeb',
          instruction: 'Classify هذا الالتقاء, ثم كيف يُحل.',
          sentence: 'النَّجَاةُ فِي الصِّدْقِ',
          cells: ['النَّجَاةُ', 'فِي', 'الصِّدْقِ'],
          rows: [
            { position: 'above', label: 'الحكم', labels: [{ start: 1, end: 1, role: 'على غير حَدِّه' }] },
            { position: 'below', label: 'الحل', labels: [{ start: 1, end: 1, role: 'حذف (حرف مد)' }] },
          ],
          distractors: ['على حَدِّه', 'ضمة (ميم الجمع)'],
        },
        {
          title: 'تركيب: هُمُ النَّاصِحُونَ',
          kind: 'tarkeeb',
          instruction: 'Classify هذا الالتقاء, ثم كيف يُحل.',
          sentence: 'هُمُ النَّاصِحُونَ',
          cells: ['هُمُ', 'النَّاصِحُونَ'],
          rows: [
            { position: 'above', label: 'الحكم', labels: [{ start: 0, end: 0, role: 'على غير حَدِّه' }] },
            { position: 'below', label: 'الحل', labels: [{ start: 0, end: 0, role: 'ضمة (ميم الجمع)' }] },
          ],
          distractors: ['على حَدِّه', 'حذف (حرف مد)'],
        },
        {
          title: 'تركيب: الْإِخْلَاصُ مِنَ النَّصِيحَةِ',
          kind: 'tarkeeb',
          instruction: 'Which vowel does the first sākin take here؟',
          sentence: 'الْإِخْلَاصُ مِنَ النَّصِيحَةِ',
          cells: ['الْإِخْلَاصُ', 'مِنَ', 'النَّصِيحَةِ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'فتحة (نون مِنْ)' }] }],
          distractors: ['كسرة (حرف صحيح)', 'ضمة (ميم الجمع)'],
        },
        {
          title: 'تركيب: نَصَحَتِ الْأُمُّ',
          kind: 'tarkeeb',
          instruction: 'Which vowel does the first sākin take here؟',
          sentence: 'نَصَحَتِ الْأُمُّ',
          cells: ['نَصَحَتِ', 'الْأُمُّ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'كسرة (حرف صحيح)' }] }],
          distractors: ['فتحة (نون مِنْ)', 'ضمة (ميم الجمع)'],
        },
        {
          title: 'تركيب: خَدِيجَةُ نَاصِحَةٌ نِ الصِّدِّيقَاتِ',
          kind: 'tarkeeb',
          instruction: 'Which vowel does the first sākin take here؟',
          sentence: 'خَدِيجَةُ نَاصِحَةٌ نِ الصِّدِّيقَاتِ',
          cells: ['خَدِيجَةُ', 'نَاصِحَةٌ', 'نِ', 'الصِّدِّيقَاتِ'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'كسرة (نون التنوين)' }] }],
          distractors: ['فتحة (نون مِنْ)', 'ضمة (ميم الجمع)'],
        },
        {
          title: 'تركيب: صُمْ يَوْمَيِ التَّاسُوعَاءِ',
          kind: 'tarkeeb',
          instruction: 'Which vowel does the first sākin take here؟',
          sentence: 'صُمْ يَوْمَيِ التَّاسُوعَاءِ',
          cells: ['صُمْ', 'يَوْمَيِ', 'التَّاسُوعَاءِ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'كسرة (حرف لين)' }] }],
          distractors: ['فتحة (نون مِنْ)', 'ضمة (ميم الجمع)'],
        },
        {
          title: 'تركيب: دَعَوُا اللَّهَ',
          kind: 'tarkeeb',
          instruction: 'Which vowel does the first sākin take here؟',
          sentence: 'دَعَوُا اللَّهَ',
          cells: ['دَعَوُا', 'اللَّهَ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'ضمة (واو الجماعة)' }] }],
          distractors: ['كسرة (حرف صحيح)', 'فتحة (نون مِنْ)'],
        },
        {
          title: 'تركيب: اقْرَأِ الْقُرْآنَ وَاعْمَلْ بِهِ',
          kind: 'tarkeeb',
          instruction: 'Classify ما يحدث لهمزة اقرأ في الوصل.',
          sentence: 'اقْرَأِ الْقُرْآنَ وَاعْمَلْ بِهِ',
          cells: ['اقْرَأِ', 'الْقُرْآنَ', 'وَاعْمَلْ', 'بِهِ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'همزة وصل تُحذف وصلًا' }] }],
          distractors: ['أل تُسقط همزة الوصل التي تليها'],
        },
        {
          title: 'تركيب: الِاجْتِنَابُ مِنَ الْمَعَاصِي خَيْرٌ',
          kind: 'tarkeeb',
          instruction: 'Classify ما حدث لهمزة اجتناب هنا.',
          sentence: 'الِاجْتِنَابُ مِنَ الْمَعَاصِي خَيْرٌ',
          cells: ['الِاجْتِنَابُ', 'مِنَ', 'الْمَعَاصِي', 'خَيْرٌ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'أل تُسقط همزة الوصل التي تليها' }] }],
          distractors: ['همزة وصل تُحذف وصلًا'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الوقف',
      subtitle: 'Stopping — how to correctly stop on a word ending in a سكون, تاء مربوطة, منقوص, or تنوين',
      concepts: [
        {
          heading: 'تعريف الوقف، والوقف على الساكن والمتحرك',
          lines: [
            { html: `<bdi>الْوَقْف</bdi> is <bdi>قَطْعُ الصَّوْتِ عِنْدَ آخِرِ الْكَلِمَةِ</bdi> — cutting off the sound at the end of a word.`, list: false },
            { html: `A word already ending in a sākin is stopped on with <bdi>سُكُون</bdi>, e.g. <bdi>رَحْمَةَ اللهِ نَرْجو، وَلَمْ نَيْأَسْ</bdi>.`, list: false },
            { html: `A word ending in a vowelled letter is stopped on by deleting its vowel, e.g. <bdi>أَنْزَلَ اللهُ القُرْآنْ، وَآمَنّا بِهْ</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `How does one stop on a word already ending in a sākin?`,
            kind: 'mcq',
            options: ['With سكون — no change is needed', 'By deleting the final vowel', 'By restoring a dropped letter', 'By adding an alif'],
            correct: 0,
          },
        },
        {
          heading: 'الوقف على تاء التأنيث المربوطة والاسم المقصور',
          lines: [
            { html: `<bdi>تَاءُ التَّأْنِيثِ المَرْبُوطَة</bdi> is stopped on with a sākin <bdi>هَاء</bdi>, e.g. <bdi>اسْتُشْهِدَ حَمْزَةْ ڤ</bdi>.`, list: false },
            { html: `The <bdi>اِسْمُ مَقْصُور</bdi> is stopped on by retaining its alif, e.g. <bdi>الهُدَى</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `How is تاء التأنيث المربوطة handled at الوقف?`,
            kind: 'mcq',
            options: ['It turns into a sākin هاء', 'It is deleted entirely', 'It keeps its own vowel', 'It turns into a تاء مفتوحة'],
            correct: 0,
          },
        },
        {
          heading: 'الوقف على الاسم المنقوص المنوَّن، وعلى التنوين عمومًا',
          lines: [
            { html: `The <bdi>اِسْمٌ مَنْقُوصٌ مُنَوَّن</bdi> is stopped on either with سكون, e.g. <bdi>جاءَنا هادْ</bdi>, or by restoring its yāʾ, e.g. <bdi>جاءَنا هادي</bdi> — and the yāʾ of a منقوص may likewise be dropped in the Qur’an, as in ﴿الْكَبِيرُ الْمُتَعَالْ﴾.`, list: false },
            { html: `Beyond the منقوص, stopping on <bdi>تَنْوِين</bdi> generally follows the vowel it carries: if the tanwīn is a <bdi>دَمَّة</bdi> or <bdi>كَسْرَة</bdi>, it is simply deleted, e.g. <bdi>صَدَقَ مُحَمَّدْ ﷺ</bdi>; if it is a <bdi>فَتْحَة</bdi>, the stop is made with an alif instead, e.g. <bdi>وَكَذَّبَ الفاسِقونَ مُحَمَّدا ﷺ</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `Stopping on a word carrying تنوين الفتح, one adds:`,
            kind: 'mcq',
            options: ['An alif', 'A sākin هاء', 'Nothing — the tanwīn is simply deleted', 'A restored yāʾ'],
            correct: 0,
          },
        },
        {
          heading: 'الوقف على نون التوكيد الخفيفة وعلى إِذَنْ',
          lines: [
            { html: `The <bdi>نُونُ التَّوْكِيدِ الخَفِيفَة</bdi> is stopped on with an alif, e.g. ﴿لَنَسْفَعًا﴾.`, list: false },
            { html: `<bdi>إِذَنْ</bdi> is stopped on by turning its nūn into an alif, <bdi>إِذًا</bdi>, e.g. <bdi>فَيُقْبَلُ مِنْكُمْ إِذًا</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `How is إِذَنْ stopped on?`,
            kind: 'mcq',
            options: ['Its nūn turns into an alif: إِذًا', 'Its nūn is simply deleted', 'It keeps its nūn with سكون', 'It turns into إِذِي'],
            correct: 0,
          },
        },
        {
          heading: 'تطبيق: أمثلة على الوقف',
          lines: [
            { html: `Putting the rules together:`, list: false },
            { table: { headers: ['Word', 'Stopped as', 'Why'], rows: [
              ['السّاعَة (تاء مربوطة)', 'السّاعَهْ', 'the تاء becomes a sākin هاء'],
              ['هادٍ (اسم منقوص منوَّن)', 'هادْ or هادي', 'سكون, or restoring the yāʾ'],
              ['مُحَمَّدًا (تنوين فتح)', 'مُحَمَّدا', 'the tanwīn becomes an alif'],
            ] } },
          ],
          exercise: {
            prompt: `Stopping on هَادٍ (اسم منقوص منوَّن), which two outcomes are both correct?`,
            kind: 'mcq',
            options: ['هادْ (سكون), or هادي (restoring the yāʾ)', 'هادا only, never هادْ', 'هادٍ stays exactly as it is', 'هادهْ, turning the tanwīn into a هاء'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'الوقف is defined as:',
          options: ['قطع الصوت عند آخر الكلمة', 'عدم قطع الصوت عند آخر الكلمة', 'همزة تُحذف في درج الكلام', 'التقاء ساكنين على حَدِّه'],
          correct: 0,
        },
        {
          q: 'How does one stop on a word ending in a vowelled (متحرك) letter?',
          options: ['By deleting its vowel', 'By adding a سكون فقط بلا حذف', 'By restoring a dropped letter', 'By turning the vowel into تنوين'],
          correct: 0,
        },
        {
          q: 'تاء التأنيث المربوطة at الوقف becomes:',
          options: ['A sākin هاء', 'A sākin تاء', 'An alif', 'Nothing — it is deleted'],
          correct: 0,
        },
        {
          q: 'الاسم المنقوص at الوقف keeps or restores which letter?',
          options: ['Its yāʾ (or drops it, as sometimes happens in the Qur’an)', 'Its wāw', 'Its alif', 'Its hamzah'],
          correct: 0,
        },
        {
          q: 'Stopping on تنوين الفتح, e.g. مُحَمَّدًا, one adds:',
          options: ['An alif', 'A sākin هاء', 'Nothing at all', 'A restored yāʾ'],
          correct: 0,
        },
        {
          q: 'نون التوكيد الخفيفة at الوقف turns into:',
          options: ['An alif', 'A sākin نون', 'A هاء', 'It is deleted entirely'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'رَحْمَةَ اللهِ نَرْجو',
          kind: 'mcq',
          prompt: 'نَرْجو already ends in a sākin واو. How is it stopped on?',
          options: ['With سكون, unchanged', 'By deleting the واو', 'By adding an alif', 'By restoring a hidden یاء'],
          correct: 0,
        },
        {
          title: 'أَنْزَلَ اللهُ القُرْآنْ',
          kind: 'mcq',
          prompt: 'القُرْآنَ (originally vowelled) is stopped on as القُرْآنْ. What happened?',
          options: ['Its final vowel was deleted', 'A سكون letter was added', 'Its تنوين became an alif', 'Its final letter was replaced'],
          correct: 0,
        },
        {
          title: 'اسْتُشْهِدَ حَمْزَةْ',
          kind: 'mcq',
          prompt: 'حَمْزَة ends in تاء التأنيث المربوطة. What does it become at الوقف?',
          options: ['A sākin هاء: حَمْزَةْ', 'A sākin تاء', 'An alif', 'It is dropped entirely'],
          correct: 0,
        },
        {
          title: 'الهُدَى at a stop',
          kind: 'mcq',
          prompt: 'الهُدَى (اسم مقصور) is stopped on by:',
          options: ['Retaining its alif, unchanged', 'Deleting its alif', 'Turning its alif into a yāʾ', 'Adding a سكون هاء'],
          correct: 0,
        },
        {
          title: 'جاءَنا هادْ',
          kind: 'mcq',
          prompt: 'هادٍ (منقوص منوَّن) is stopped on here with سكون, giving هادْ. What is the other valid way to stop on it?',
          options: ['Restoring the yāʾ: هادي', 'Adding an alif: هادا', 'Turning the dāl into a هاء', 'Keeping the تنوين as-is'],
          correct: 0,
        },
        {
          title: '﴿الْكَبِيرُ الْمُتَعَالْ﴾',
          kind: 'mcq',
          prompt: 'المُتَعَالِ drops its yāʾ here at the end of a verse. What kind of noun is المتعالي?',
          options: ['اسم منقوص', 'اسم مقصور', 'اسم ممدود', 'مصدر ميمي'],
          correct: 0,
        },
        {
          title: 'صَدَقَ مُحَمَّدْ ﷺ',
          kind: 'mcq',
          prompt: 'مُحَمَّدٌ carries تنوين ضم. How is it stopped on?',
          options: ['The tanwīn (and its vowel) is simply deleted', 'The tanwīn becomes an alif', 'The tanwīn becomes a سكون هاء', 'The tanwīn is kept in full'],
          correct: 0,
        },
        {
          title: 'آمَنَ المُؤْمِنونَ بِمُحَمَّدْ ﷺ',
          kind: 'mcq',
          prompt: 'مُحَمَّدٍ here carries تنوين كسر. Stopping on it, the tanwīn is:',
          options: ['Deleted, exactly as with تنوين ضم', 'Turned into an alif', 'Turned into a sākin هاء', 'Kept in full'],
          correct: 0,
        },
        {
          title: 'وَكَذَّبَ الفاسِقونَ مُحَمَّدا ﷺ',
          kind: 'mcq',
          prompt: 'مُحَمَّدًا carries تنوين فتح. Why is the stop مُحَمَّدا rather than مُحَمَّدْ?',
          options: ['تنوين الفتح alone is replaced by an alif at الوقف, unlike ضم and كسر', 'فتحة tanwīn is never dropped at all', 'فتحة tanwīn always keeps its ن sound', 'This word is مبني, not معرب'],
          correct: 0,
        },
        {
          title: '﴿لَنَسْفَعًا﴾',
          kind: 'mcq',
          prompt: 'This ends in نون التوكيد الخفيفة. At الوقف, that نون:',
          options: ['Becomes an alif', 'Is deleted outright', 'Becomes a سكون نون', 'Becomes a هاء'],
          correct: 0,
        },
        {
          title: 'إِذًا',
          kind: 'mcq',
          prompt: 'إِذَنْ becomes إِذًا at الوقف. What happened to its نون?',
          options: ['It turned into an alif', 'It was deleted entirely', 'It kept its سكون unchanged', 'It turned into a هاء'],
          correct: 0,
        },
        {
          title: 'وَآمَنّا بِهْ',
          kind: 'mcq',
          prompt: 'بِهِ (originally vowelled) is stopped on as بِهْ. Which rule applies?',
          options: ['Stopping on a متحرك letter by deleting its vowel', 'Stopping on تاء التأنيث المربوطة', 'Stopping on تنوين الفتح', 'Stopping on نون التوكيد الخفيفة'],
          correct: 0,
        },
        {
          title: 'وَلَمْ نَيْأَسْ',
          kind: 'mcq',
          prompt: 'نَيْأَسْ already ends in a sākin. At الوقف, this word:',
          options: ['Needs no change at all', 'Must add an alif regardless', 'Must restore a dropped letter', 'Must turn its final letter into a هاء'],
          correct: 0,
        },
        {
          title: 'Two options for هادٍ',
          kind: 'mcq',
          prompt: 'Both هادْ and هادي are accepted stops on هادٍ. What do these two options represent?',
          options: ['سكون on the منقوص, or restoring its yāʾ', 'Two entirely different words', 'ضم then فتح tanwīn', 'A wrong option and a right one'],
          correct: 0,
        },
        {
          title: 'السّاعَهْ',
          kind: 'mcq',
          prompt: 'السّاعَة is stopped on as السّاعَهْ. Which letter changed, and into what?',
          options: ['The تاء المربوطة became a sākin هاء', 'The عين became a hamzah', 'The سين became a صاد', 'The لام of أل was dropped'],
          correct: 0,
        },
        {
          title: 'درجة التنوين عند الوقف',
          kind: 'mcq',
          prompt: 'Which vowel of تنوين is the ONLY one replaced by an alif rather than simply deleted, at الوقف?',
          options: ['فتحة (تنوين النصب)', 'ضمة (تنوين الرفع)', 'كسرة (تنوين الجر)', 'كلها تُحذف بلا استثناء'],
          correct: 0,
        },
        {
          title: 'قطع الصوت',
          kind: 'mcq',
          prompt: 'الوقف, defined as قطع الصوت عند آخر الكلمة, is the opposite of:',
          options: ['الوصل', 'الرسم', 'التنوين', 'الإعراب'],
          correct: 0,
        },
        {
          title: 'مقارنة: الوقف على الساكن',
          kind: 'mcq',
          prompt: 'Comparing نَرْجو (already sākin) and القُرْآنَ (vowelled): which one needs a change at الوقف?',
          options: ['القُرْآنَ alone — its vowel is deleted', 'نَرْجو alone — a letter is added', 'Both need the same treatment', 'Neither needs any change'],
          correct: 0,
        },
        {
          title: 'تركيب: رَحْمَةَ اللَّهِ نَرْجُو',
          kind: 'tarkeeb',
          instruction: 'How is نرجو stopped on?',
          sentence: 'رَحْمَةَ اللَّهِ نَرْجُو',
          cells: ['رَحْمَةَ', 'اللَّهِ', 'نَرْجُو'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'سكون (بلا تغيير)' }] }],
          distractors: ['حذف الحركة', 'إثبات الألف'],
        },
        {
          title: 'تركيب: أَنْزَلَ اللَّهُ الْقُرْآنَ',
          kind: 'tarkeeb',
          instruction: 'How is القرآن stopped on?',
          sentence: 'أَنْزَلَ اللَّهُ الْقُرْآنَ',
          cells: ['أَنْزَلَ', 'اللَّهُ', 'الْقُرْآنَ'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'حذف الحركة' }] }],
          distractors: ['سكون (بلا تغيير)', 'هاء ساكنة بدل التاء'],
        },
        {
          title: 'تركيب: اسْتُشْهِدَ حَمْزَةُ',
          kind: 'tarkeeb',
          instruction: 'How is حمزة stopped on?',
          sentence: 'اسْتُشْهِدَ حَمْزَةُ',
          cells: ['اسْتُشْهِدَ', 'حَمْزَةُ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'هاء ساكنة بدل التاء' }] }],
          distractors: ['حذف الحركة', 'إثبات الألف'],
        },
        {
          title: 'تركيب: هَٰذَا الْهُدَى',
          kind: 'tarkeeb',
          instruction: 'How is الهدى stopped on?',
          sentence: 'هَٰذَا الْهُدَى',
          cells: ['هَٰذَا', 'الْهُدَى'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'إثبات الألف' }] }],
          distractors: ['حذف الحركة', 'هاء ساكنة بدل التاء'],
        },
        {
          title: 'تركيب: صَدَقَ مُحَمَّدٌ رَسُولُ اللَّهِ',
          kind: 'tarkeeb',
          instruction: 'What happens to تنوين الضم here at الوقف?',
          sentence: 'صَدَقَ مُحَمَّدٌ رَسُولُ اللَّهِ',
          cells: ['صَدَقَ', 'مُحَمَّدٌ', 'رَسُولُ', 'اللَّهِ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'يُحذف' }] }],
          distractors: ['يصير ألفًا'],
        },
        {
          title: 'تركيب: آمَنَ الْمُؤْمِنُونَ بِمُحَمَّدٍ رَسُولًا',
          kind: 'tarkeeb',
          instruction: 'What happens to تنوين الكسر here at الوقف?',
          sentence: 'آمَنَ الْمُؤْمِنُونَ بِمُحَمَّدٍ رَسُولًا',
          cells: ['آمَنَ', 'الْمُؤْمِنُونَ', 'بِمُحَمَّدٍ', 'رَسُولًا'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'يُحذف' }] }],
          distractors: ['يصير ألفًا'],
        },
        {
          title: 'تركيب: وَكَذَّبَ الْفَاسِقُونَ مُحَمَّدًا رَسُولًا',
          kind: 'tarkeeb',
          instruction: 'What happens to تنوين الفتح here at الوقف?',
          sentence: 'وَكَذَّبَ الْفَاسِقُونَ مُحَمَّدًا رَسُولًا',
          cells: ['وَكَذَّبَ', 'الْفَاسِقُونَ', 'مُحَمَّدًا', 'رَسُولًا'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'يصير ألفًا' }] }],
          distractors: ['يُحذف'],
        },
        {
          title: 'تركيب: جَاءَنَا هَادٍ',
          kind: 'tarkeeb',
          instruction: 'How is هادٍ (اسم منقوص منوَّن) stopped on?',
          sentence: 'جَاءَنَا هَادٍ',
          cells: ['جَاءَنَا', 'هَادٍ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'يُحذف أو تُثبت الياء' }] }],
          distractors: ['يصير ألفًا', 'هاء ساكنة بدل التاء'],
        },
        {
          title: 'تركيب: فَيُقْبَلُ مِنْكُمْ إِذَنْ',
          kind: 'tarkeeb',
          instruction: 'What happens to إذن at الوقف?',
          sentence: 'فَيُقْبَلُ مِنْكُمْ إِذَنْ',
          cells: ['فَيُقْبَلُ', 'مِنْكُمْ', 'إِذَنْ'],
          rows: [{ position: 'above', labels: [{ start: 2, end: 2, role: 'النون تصير ألفًا: إذًا' }] }],
          distractors: ['نون التوكيد الخفيفة تصير ألفًا'],
        },
        {
          title: 'تركيب: ﴿لَنَسْفَعًا بِالنَّاصِيَةِ﴾',
          kind: 'tarkeeb',
          instruction: 'What happens to نون التوكيد الخفيفة at الوقف?',
          sentence: 'لَنَسْفَعًا بِالنَّاصِيَةِ',
          cells: ['لَنَسْفَعًا', 'بِالنَّاصِيَةِ'],
          rows: [{ position: 'above', labels: [{ start: 0, end: 0, role: 'نون التوكيد الخفيفة تصير ألفًا' }] }],
          distractors: ['النون تصير ألفًا: إذًا'],
        },
        {
          title: 'تركيب: وَلَمْ نَيْأَسْ',
          kind: 'tarkeeb',
          instruction: 'Does نيأس need a change at الوقف?',
          sentence: 'وَلَمْ نَيْأَسْ',
          cells: ['وَلَمْ', 'نَيْأَسْ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'لا تغيير (ساكن أصلاً)' }] }],
          distractors: ['حذف الحركة'],
        },
        {
          title: 'تركيب: وَآمَنَّا بِهِ',
          kind: 'tarkeeb',
          instruction: 'How is به stopped on?',
          sentence: 'وَآمَنَّا بِهِ',
          cells: ['وَآمَنَّا', 'بِهِ'],
          rows: [{ position: 'above', labels: [{ start: 1, end: 1, role: 'حذف الحركة' }] }],
          distractors: ['لا تغيير (ساكن أصلاً)'],
        },
      ],
    },
  ],
};
