// Module 09 — حذف العامل
//
// Content is adapted from the closing ("خاتم") deck of the العامل وغير
// العامل chapter (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__4 خاتم.apkg,
// 73 notes, all of them here). This module ties off the whole العامل وغير
// العامل chapter (modules 2-8) with: التنازع (two عوامل contending over
// one معمول), the جائز/واجب divide in حذف العامل, and the concrete places
// where deletion of the عامل is obligatory — عامل المفعول المطلق (سماعي
// وقياسي), عامل المفعول به (its five places: التحذير، الإغراء، الاختصاص،
// الاشتغال، النداء — with النداء's own حروف, إعراب, ياء المتكلم, الترخيم,
// الاستغاثة, نداء التعجب, and الندبة all folded in as its extensions), and
// عامل الحال.

export default {
  id: '09',
  title: 'حذف العامل',
  heading: 'العامل وغير العامل',
  subheading: 'خاتم',
  blurb: 'حذف العامل: when a governor is dropped, plus النداء and its extensions like الاستغاثة and الندبة.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'التنازع وحذف العامل',
      subtitle: "Contending Governors and the Two Kinds of Deletion — التنازع, الحذف الجائز, and الحذف الواجب's three أضرب",
      concepts: [
        {
          heading: 'التنازع: تعريفه ومن يتولى العمل',
          lines: [
            { html: `<bdi>التَّنَازُع</bdi> is when two <bdi>عَامِلَانِ</bdi> (governors) both compete to govern a single <bdi>مَعْمُول</bdi> that comes after both of them — its other name is <bdi>الْإِعْمَال</bdi>.`, list: false },
            { html: `Either governor may be the one that actually governs the معمول: it is permissible for the first or the second عامل to take the credit, so the choice is not fixed to one side.`, list: false },
          ],
          exercise: {
            prompt: `What is التنازع, and which of the two contending عاملان is allowed to govern the معمول؟`,
            kind: 'mcq',
            options: ['Two عاملان competing over one معمول after both of them; either one may govern it', 'One عامل governing two معمولات at once', 'A معمول that has no عامل at all', 'Two معمولات competing over a single عامل before both of them'],
            correct: 0,
          },
        },
        {
          heading: 'أمثلة التنازع: فعلان، اسمان، وأكثر من عاملين',
          lines: [
            { html: `التنازع happens between two <bdi>أَفْعَال</bdi>, as in ﴿كُلُوا وَاشْرَبُوا مِنْ رِزْقِ اللَّهِ﴾, or between two <bdi>أَسْمَاء</bdi>, as in ﴿وَإِنْ أَدْرِي أَقَرِيبٌ أَمْ بَعِيدٌ مَا تُوعَدُونَ﴾.`, list: false },
            { html: `More than two عوامل can even contend over the same معمول — a hadith has three verbs contending over <bdi>ثَلَاثًا وَثَلَاثِينَ</bdi>: «تُسَبِّحُونَ وَتَحْمَدُونَ وَتُكَبِّرُونَ دُبُرَ كُلِّ صَلَاةٍ ثَلَاثًا وَثَلَاثِينَ مَرَّةً».`, list: false },
          ],
          exercise: {
            prompt: `Can more than two عوامل contend over a single معمول? Which example shows this؟`,
            kind: 'mcq',
            options: ['Yes — a hadith has three verbs (تسبحون وتحمدون وتكبرون) contending over one معمول', 'No, التنازع is strictly limited to exactly two عوامل', 'Only two أسماء can contend, never أفعال', 'Only in poetry, never in hadith or Qur’an'],
            correct: 0,
          },
        },
        {
          heading: 'حذف العامل: الجائز',
          lines: [
            { html: `<bdi>حَذْفُ الْعَامِل</bdi> (deleting the governor while keeping its معمول) falls into two categories: <bdi>الْحَذْفُ الْجَائِز</bdi> and <bdi>الْحَذْفُ الْوَاجِب</bdi>.`, list: false },
            { html: `Deletion is permissible when a <bdi>قَرِينَةُ السِّيَاق</bdi> (contextual clue) makes the deleted عامل recoverable, as in ﴿مَاذَا أَنْزَلَ رَبُّكُمْ قَالُوا خَيْرًا﴾ — the answer implies <bdi>أَنْزَلَ خَيْرًا</bdi>, so <bdi>خَيْرًا</bdi> is منصوب as the مفعول به of that understood, deleted verb.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿قَالُوا خَيْرًا﴾, why is خيرا منصوب, and what kind of deletion does this illustrate؟`,
            kind: 'mcq',
            options: ['It’s مفعول به of a permissibly (جوازا) deleted verb أنزل, recoverable from context', 'It’s مفعول به of an obligatorily deleted verb', 'It’s حال منصوبة with no deleted عامل at all', 'It’s منصوب because it follows إنّ'],
            correct: 0,
          },
        },
        {
          heading: 'الحذف الواجب: أضربه الثلاثة',
          lines: [
            { html: `<bdi>الْحَذْفُ الْوَاجِب</bdi> (obligatory deletion) of the عامل occurs in three <bdi>أَضْرُب</bdi> (types): the عامل of <bdi>الْمَفْعُول الْمُطْلَق</bdi>, of <bdi>الْمَفْعُول بِهِ</bdi>, and of <bdi>الْحَال</bdi>.`, list: false },
            { html: `Deletion of عامل المفعول به specifically is obligatory in five places:`, list: false },
            { html: `<bdi>التَّحْذِير</bdi>، <bdi>الْإِغْرَاء</bdi>، <bdi>الِاخْتِصَاص</bdi>، <bdi>الِاشْتِغَال</bdi>، <bdi>النِّدَاء</bdi>`, list: true, bullet: true },
            { html: `The rest of this module works through each of these three أضرب in turn.`, list: false },
          ],
          exercise: {
            prompt: `الحذف الواجب of the عامل occurs in three أضرب. What are they؟`,
            kind: 'mcq',
            options: ['عامل المفعول المطلق, عامل المفعول به, and عامل الحال', 'عامل الفاعل, عامل المبتدأ, and عامل الخبر', 'عامل الحال فقط, with no other ضرب', 'عامل الجار والمجرور فقط'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'What is the other name for التنازع؟', options: ['الإعمال', 'الإهمال', 'الإغراء', 'الاختصاص'], correct: 0 },
        { q: '﴿كُلُوا وَاشْرَبُوا مِنْ رِزْقِ اللَّهِ﴾ illustrates التنازع between:', options: ['two أفعال', 'two أسماء', 'a فعل and an اسم', 'two حروف'], correct: 0 },
        { q: 'In التنازع, which عامل is permitted to govern the معمول؟', options: ['Either the first or the second, freely', 'Only the first, never the second', 'Only the second, never the first', 'Neither — the معمول is left without إعراب'], correct: 0 },
        { q: 'حذف العامل falls into two categories:', options: ['الحذف الجائز and الحذف الواجب', 'الحذف السماعي and الحذف القياسي only', 'التنازع and الإعمال', 'الحذف اللفظي and الحذف المحلي'], correct: 0 },
        { q: 'In ﴿مَاذَا أَنْزَلَ رَبُّكُمْ قَالُوا خَيْرًا﴾, خيرا is منصوب as:', options: ['مفعول به of the permissibly deleted فعل أنزل', 'فاعل of a deleted فعل', 'حال منصوبة with no deleted عامل', 'مفعول مطلق مؤكد'], correct: 0 },
        { q: 'الحذف الواجب of the عامل has three أضرب: عامل المفعول المطلق, عامل الحال, and:', options: ['عامل المفعول به', 'عامل الفاعل', 'عامل المبتدأ', 'عامل الجار والمجرور'], correct: 0 },
      ],
      bank: [
        { title: 'تعريف التنازع', kind: 'mcq', prompt: 'التنازع is defined as:', options: ['Two عاملان contending over one معمول that follows both of them', 'One عامل governing two معمولات', 'A معمول with two متعلقات', 'A عامل that governs nothing at all'], correct: 0 },
        { title: 'اسم آخر للتنازع', kind: 'mcq', prompt: 'التنازع is also known by the name:', options: ['الإعمال', 'الإهمال', 'التوكيد', 'الاستثناء'], correct: 0 },
        { title: 'تنازع اسمين', kind: 'mcq', prompt: '﴿وَإِنْ أَدْرِي أَقَرِيبٌ أَمْ بَعِيدٌ مَا تُوعَدُونَ﴾ shows التنازع between:', options: ['two أسماء', 'two أفعال', 'a حرف and an اسم', 'three أفعال'], correct: 0 },
        { title: 'تنازع أكثر من عاملين', kind: 'mcq', prompt: 'The hadith «تُسَبِّحُونَ وَتَحْمَدُونَ وَتُكَبِّرُونَ... ثَلَاثًا وَثَلَاثِينَ» shows how many عوامل contending over ثلاثا وثلاثين؟', options: ['Three', 'Two', 'Four', 'Only one, with no real تنازع'], correct: 0 },
        { title: 'حرية اختيار العامل', kind: 'mcq', prompt: 'When two عاملان contend in التنازع, the rule is that:', options: ['governing by the first or the second is equally permissible', 'only the nearer عامل is ever allowed to govern', 'only the farther عامل is ever allowed to govern', 'neither عامل is allowed to govern — the معمول stays without إعراب'], correct: 0 },
        { title: 'قرينة السياق في الحذف الجائز', kind: 'mcq', prompt: 'What licenses الحذف الجائز of an عامل؟', options: ['A قرينة السياق (contextual clue) that makes it recoverable', 'The عامل being a فعل أمر specifically', 'The معمول being a مصدر specifically', 'Nothing licenses it — الحذف الجائز never actually happens'], correct: 0 },
        { title: 'إعراب خيرا', kind: 'mcq', prompt: 'In ﴿قَالُوا خَيْرًا﴾, خيرا is:', options: ['مفعول به of a جوازا-deleted فعل (أنزل)', 'فاعل of a stated فعل', 'حال with no deleted عامل', 'مبتدأ خبره محذوف'], correct: 0 },
        { title: 'أضرب الحذف الواجب الثلاثة', kind: 'mcq', prompt: 'Which three أضرب does الحذف الواجب of the عامل fall into?', options: ['عامل المفعول المطلق, عامل المفعول به, عامل الحال', 'عامل الفاعل, عامل النائب عن الفاعل, عامل الحال', 'عامل المبتدأ, عامل الخبر, عامل الحال', 'عامل التمييز, عامل المستثنى, عامل البدل'], correct: 0 },
        { title: 'مواضع المفعول به الخمسة', kind: 'mcq', prompt: 'Deletion of عامل المفعول به is obligatory in how many places, and what are they؟', options: ['Five: التحذير، الإغراء، الاختصاص، الاشتغال، النداء', 'Three: التحذير، الإغراء، النداء', 'Five, but النداء is not one of them', 'Two: الاختصاص والاشتغال only'], correct: 0 },
        { title: 'الفرق بين الجائز والواجب', kind: 'mcq', prompt: 'What distinguishes الحذف الواجب from الحذف الجائز؟', options: ['الواجب must be deleted in its fixed places; الجائز is only optionally deleted when context allows it', 'الجائز only ever applies to أفعال, الواجب only to أسماء', 'الواجب applies only to حروف الجر', 'There is no real difference between them'], correct: 0 },
        {
          title: 'تركيب: ﴿مَاذَا أَنْزَلَ رَبُّكُمْ قَالُوا خَيْرًا﴾',
          kind: 'tarkeeb',
          instruction: 'Classify this حذف العامل: الجائز or الواجب؟',
          sentence: 'مَاذَا أَنْزَلَ رَبُّكُمْ قَالُوا خَيْرًا',
          translation: '"What has your Lord sent down?" They said, "Good."',
          cells: ['مَاذَا', 'أَنْزَلَ', 'رَبُّكُمْ', 'قَالُوا', 'خَيْرًا'],
          rows: [
            { position: 'above', labels: [{ start: 4, end: 4, role: 'الحذف الجائز' }] },
          ],
          distractors: ['الحذف الواجب'],
        },
        {
          title: 'تركيب: صَبْرًا لَا جَزَعًا',
          kind: 'tarkeeb',
          instruction: 'Which ضرب of الحذف الواجب does this عامل المحذوف belong to؟',
          sentence: 'صَبْرًا لَا جَزَعًا',
          translation: 'Be patient, not distressed! (lit. patience, not distress)',
          cells: ['صَبْرًا', 'لَا', 'جَزَعًا'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 2, role: 'عامل المفعول المطلق' }] },
          ],
          distractors: ['عامل المفعول به', 'عامل الحال'],
        },
        {
          title: 'تركيب: إِيَّاكَ وَالْحَسَدَ',
          kind: 'tarkeeb',
          instruction: 'Which ضرب of الحذف الواجب does this عامل المحذوف belong to؟',
          sentence: 'إِيَّاكَ وَالْحَسَدَ',
          translation: 'Beware of envy!',
          cells: ['إِيَّاكَ', 'وَالْحَسَدَ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 1, role: 'عامل المفعول به' }] },
          ],
          distractors: ['عامل المفعول المطلق', 'عامل الحال'],
        },
        {
          title: 'تركيب: دُعَائِي رَبِّي مُسْتَيْقِنًا',
          kind: 'tarkeeb',
          instruction: 'Which ضرب of الحذف الواجب does this عامل المحذوف belong to؟',
          sentence: 'دُعَائِي رَبِّي مُسْتَيْقِنًا',
          translation: 'My prayer to my Lord, [being] certain.',
          cells: ['دُعَائِي', 'رَبِّي', 'مُسْتَيْقِنًا'],
          rows: [
            { position: 'above', labels: [{ start: 2, end: 2, role: 'عامل الحال' }] },
          ],
          distractors: ['عامل المفعول المطلق', 'عامل المفعول به'],
        },
        {
          title: 'تركيب: ﴿كُلُوا وَاشْرَبُوا مِنْ رِزْقِ اللَّهِ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify this مثال of التنازع.',
          sentence: 'كُلُوا وَاشْرَبُوا مِنْ رِزْقِ اللَّهِ',
          translation: "Eat and drink from Allah's provision.",
          cells: ['كُلُوا', 'وَاشْرَبُوا', 'مِنْ', 'رِزْقِ', 'اللَّهِ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 1, role: 'تنازع فعلين' }] },
          ],
          distractors: ['تنازع اسمين'],
        },
        {
          title: 'تركيب: ﴿وَإِنْ أَدْرِي أَقَرِيبٌ أَمْ بَعِيدٌ مَا تُوعَدُونَ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify this مثال of التنازع.',
          sentence: 'وَإِنْ أَدْرِي أَقَرِيبٌ أَمْ بَعِيدٌ مَا تُوعَدُونَ',
          translation: 'And I do not know whether what you are promised is near or far.',
          cells: ['وَإِنْ', 'أَدْرِي', 'أَقَرِيبٌ', 'أَمْ', 'بَعِيدٌ', 'مَا', 'تُوعَدُونَ'],
          rows: [
            { position: 'above', labels: [{ start: 2, end: 4, role: 'تنازع اسمين' }] },
          ],
          distractors: ['تنازع فعلين'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'حذف عامل المفعول المطلق',
      subtitle: 'Deleting the Governor of the Absolute Object — سماعي and قياسي deletion, and قياسي’s four places',
      concepts: [
        {
          heading: 'نوعا حذف عامل المفعول المطلق: سماعي وقياسي',
          lines: [
            { html: `Obligatory deletion of عامل المفعول المطلق comes in two kinds:`, list: false },
            { html: `<bdi>سَمَاعِيّ</bdi> — attested by hearing, memorized as fixed expressions, not extendable by rule to new cases`, list: true, bullet: true },
            { html: `<bdi>قِيَاسِيّ</bdi> — extendable by analogy to any case matching one of its defined places`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Obligatory deletion of عامل المفعول المطلق comes in which two kinds؟`,
            kind: 'mcq',
            options: ['سماعي and قياسي', 'جائز and واجب only', 'لفظي and محلي', 'مفرد and مركب'],
            correct: 0,
          },
        },
        {
          heading: 'القياسي: أربعة مواضع',
          lines: [
            { html: `The قياسي obligatory deletion occurs in four places:`, list: false },
            { html: `a مَصْدَر functioning as a نَهْي following a مصدر intended as an أَمْر`, list: true, bullet: true },
            { html: `after an اسْتِفْهَام intended as تَوْبِيخ (rebuke)`, list: true, bullet: true },
            { html: `after إِمَّا giving تَفْصِيل of a preceding مُجْمَل`, list: true, bullet: true },
            { html: `a مصدر confirming the content of the sentence (مُؤَكِّدٌ لِمَضْمُونِ الْجُمْلَة)`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `List the four قياسي places where عامل المفعول المطلق is obligatorily deleted.`,
            kind: 'mcq',
            options: ['نهي بعد أمر, استفهام توبيخ, إما تفصيلا لمجمل, مؤكد لمضمون الجملة', 'نداء, تحذير, إغراء, اختصاص', 'شرط, جواب شرط, قسم, جواب قسم', 'حال, تمييز, مستثنى, بدل'],
            correct: 0,
          },
        },
        {
          heading: 'مثالا الأمر والنهي، والتوبيخ',
          lines: [
            { html: `<bdi>صَبْرًا لَا جَزَعًا</bdi> means اِصْبِرْ صَبْرًا وَلَا تَجْزَعْ جَزَعًا — a نهي مصدر paired with the preceding أمر مصدر it echoes.`, list: false },
            { html: `For استفهام التوبيخ: أَجُرْأَةً عَلَى الْمَعَاصِي؟ ("Such audacity toward sins?!") — the استفهام here is not a real question, it is rebuke.`, list: false },
          ],
          exercise: {
            prompt: `صَبْرًا لَا جَزَعًا illustrates which قياسي موضع؟`,
            kind: 'mcq',
            options: ['A نهي مصدر following an أمر مصدر', 'استفهام intended as توبيخ', 'إما giving تفصيل لمجمل', 'A مصدر مؤكد لمضمون الجملة'],
            correct: 0,
          },
        },
        {
          heading: 'إما تفصيلا لمجمل، والمؤكد لمضمون الجملة',
          lines: [
            { html: `﴿فَشُدُّوا الْوَثَاقَ فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾ — <bdi>مَنًّا</bdi> and <bdi>فِدَاءً</bdi> detail the preceding مجمل.`, list: false },
            { html: `And <bdi>حَقًّا</bdi> in ﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾ is a مصدر مؤكد لمضمون الجملة, whose عامل is obligatorily (قياسا) deleted.`, list: false },
          ],
          exercise: {
            prompt: `Why is حقا منصوب in ﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾؟`,
            kind: 'mcq',
            options: ['It’s a مفعول مطلق مؤكد لمضمون الجملة with an obligatorily deleted عامل', 'It’s a حال with a deleted عامل', 'It’s a تمييز with no deleted عامل', 'It’s a مفعول به of a stated verb'],
            correct: 0,
          },
        },
        {
          heading: 'أمثلة سماعية لحذف عامل المفعول المطلق',
          lines: [
            { html: `Examples of the سماعي deletion include <bdi>سُبْحَانَ اللَّهِ</bdi>, <bdi>مَعَاذَ اللَّهِ</bdi>, <bdi>عَجَبًا لَكَ</bdi>, <bdi>حَمْدًا وَشُكْرًا لَا كُفْرًا</bdi>, and <bdi>لَبَّيْكَ</bdi> and its sisters.`, list: false },
            { html: `Because these are سماعي rather than قياسي, they are memorized as fixed expressions rather than extended to new, unattested cases.`, list: false },
          ],
          exercise: {
            prompt: `سُبْحَانَ اللَّهِ and مَعَاذَ اللَّهِ are examples of which kind of عامل deletion؟`,
            kind: 'mcq',
            options: ['سماعي — attested and not extended by rule to new cases', 'قياسي — extended by rule to any matching case', 'الحذف الجائز, not الواجب', 'A case where the عامل is not actually deleted'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'Obligatory deletion of عامل المفعول المطلق comes in which two kinds؟', options: ['سماعي and قياسي', 'جائز and واجب only', 'لفظي and محلي', 'مفرد and مركب'], correct: 0 },
        { q: 'How many قياسي places does obligatory deletion of عامل المفعول المطلق occur in؟', options: ['Four', 'Two', 'Six', 'Three'], correct: 0 },
        { q: 'صَبْرًا لَا جَزَعًا illustrates:', options: ['A نهي مصدر following an أمر مصدر', 'استفهام intended as توبيخ', 'إما giving تفصيل لمجمل', 'A مصدر مؤكد لمضمون الجملة'], correct: 0 },
        { q: '﴿فَشُدُّوا الْوَثَاقَ فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾ illustrates a مصدر:', options: ['giving إما تفصيلا لمجمل', 'confirming مضمون الجملة', 'following a نهي', 'after استفهام التوبيخ'], correct: 0 },
        { q: 'حقا in ﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾ is:', options: ['مصدر مؤكد لمضمون الجملة', 'حال', 'تمييز', 'مفعول به'], correct: 0 },
        { q: 'سُبْحَانَ اللَّهِ is an example of the ___ deletion of عامل المفعول المطلق.', options: ['سماعي', 'قياسي', 'الجائز غير الواجب', 'no deletion at all'], correct: 0 },
      ],
      bank: [
        { title: 'نوعا الحذف الواجب لعامل المفعول المطلق', kind: 'mcq', prompt: 'نوعا الحذف الواجب لعامل المفعول المطلق هما:', options: ['سماعي وقياسي', 'جائز وواجب فقط', 'مفرد ومركب', 'لفظي ومحلي'], correct: 0 },
        { title: 'أجرأة على المعاصي', kind: 'mcq', prompt: 'أَجُرْأَةً عَلَى الْمَعَاصِي؟ illustrates:', options: ['استفهام intended as توبيخ', 'نهي following an أمر', 'إما giving تفصيلا لمجمل', 'مصدر مؤكد لمضمون الجملة'], correct: 0 },
        { title: 'حمدا وشكرا لا كفرا', kind: 'mcq', prompt: 'حَمْدًا وَشُكْرًا لَا كُفْرًا is:', options: ['سماعي', 'قياسي', 'مثال على الحذف الجائز', 'مثال لا يتضمن حذف عامل أصلا'], correct: 0 },
        { title: 'عجبا لك', kind: 'mcq', prompt: 'عَجَبًا لَكَ is:', options: ['سماعي', 'قياسي', 'إما تفصيلا لمجمل', 'مؤكد لمضمون الجملة'], correct: 0 },
        { title: 'لبيك وأخواتها', kind: 'mcq', prompt: 'لَبَّيْكَ وَأَخَوَاتُهَا belong to which kind of حذف عامل المفعول المطلق؟', options: ['السماعي', 'القياسي', 'الجائز فقط', 'لا يوجد حذف فيها'], correct: 0 },
        { title: 'الأصل غير المحذوف', kind: 'mcq', prompt: 'صَبْرًا لَا جَزَعًا, once its deleted عامل is restored, reads:', options: ['اصبر صبرا ولا تجزع جزعا', 'أجرأة على المعاصي', 'أولئك هم المؤمنون حقا', 'فشدوا الوثاق'], correct: 0 },
        { title: 'معاذ الله', kind: 'mcq', prompt: 'مَعَاذَ اللَّهِ is:', options: ['سماعي', 'قياسي', 'مثال على استفهام التوبيخ', 'مثال على إما تفصيلا لمجمل'], correct: 0 },
        { title: 'منّا وفداء', kind: 'mcq', prompt: '﴿فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾ — منّا وفداء are:', options: ['مفعولان مطلقان بعاملين محذوفين قياسا, giving تفصيلا لمجمل', 'حالان منصوبان', 'مفعولان به', 'تمييزان'], correct: 0 },
        { title: 'الفرق العملي بين السماعي والقياسي', kind: 'mcq', prompt: 'Unlike السماعي, the قياسي deletion can be:', options: ['extended by rule to any new case matching its defined مواضع', 'only memorized, never extended', 'applied to الفاعل rather than المفعول المطلق', 'applied only within Qur’anic Arabic'], correct: 0 },
        { title: 'التمييز بين مواضع القياسي', kind: 'mcq', prompt: 'Which of these is NOT one of the four قياسي مواضع of عامل المفعول المطلق؟', options: ['التحذير', 'نهي بعد أمر', 'استفهام التوبيخ', 'إما تفصيلا لمجمل'], correct: 0 },
        {
          title: 'تركيب: سُبْحَانَ اللَّهِ',
          kind: 'tarkeeb',
          instruction: 'Classify this حذف: السماعي or القياسي؟',
          sentence: 'سُبْحَانَ اللَّهِ',
          translation: 'Glory be to Allah.',
          cells: ['سُبْحَانَ', 'اللَّهِ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 1, role: 'السماعي' }] },
          ],
          distractors: ['القياسي'],
        },
        {
          title: 'تركيب: حَمْدًا وَشُكْرًا لَا كُفْرًا',
          kind: 'tarkeeb',
          instruction: 'Classify this حذف: السماعي or القياسي؟',
          sentence: 'حَمْدًا وَشُكْرًا لَا كُفْرًا',
          translation: 'Praise and thanks, not ingratitude.',
          cells: ['حَمْدًا', 'وَشُكْرًا', 'لَا', 'كُفْرًا'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 3, role: 'السماعي' }] },
          ],
          distractors: ['القياسي'],
        },
        {
          title: 'تركيب: صَبْرًا لَا جَزَعًا (القياسي)',
          kind: 'tarkeeb',
          instruction: 'Classify this حذف, then its قياسي موضع.',
          sentence: 'صَبْرًا لَا جَزَعًا',
          translation: 'Be patient, not distressed!',
          cells: ['صَبْرًا', 'لَا', 'جَزَعًا'],
          rows: [
            { position: 'above', label: 'النوع', labels: [{ start: 0, end: 2, role: 'القياسي' }] },
            { position: 'below', label: 'الموضع', labels: [{ start: 0, end: 2, role: 'نهي بعد أمر' }] },
          ],
          distractors: ['السماعي', 'استفهام توبيخ'],
        },
        {
          title: 'تركيب: أَجُرْأَةً عَلَى الْمَعَاصِي؟',
          kind: 'tarkeeb',
          instruction: 'Classify this حذف, then its قياسي موضع.',
          sentence: 'أَجُرْأَةً عَلَى الْمَعَاصِي؟',
          translation: 'Such audacity toward sins?!',
          cells: ['أَجُرْأَةً', 'عَلَى', 'الْمَعَاصِي'],
          rows: [
            { position: 'above', label: 'النوع', labels: [{ start: 0, end: 2, role: 'القياسي' }] },
            { position: 'below', label: 'الموضع', labels: [{ start: 0, end: 2, role: 'استفهام توبيخ' }] },
          ],
          distractors: ['السماعي', 'نهي بعد أمر'],
        },
        {
          title: 'تركيب: ﴿فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾',
          kind: 'tarkeeb',
          instruction: 'Which قياسي موضع does this illustrate؟',
          sentence: 'فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً',
          translation: 'Then either [confer] favor afterwards, or ransom.',
          cells: ['فَإِمَّا', 'مَنًّا', 'بَعْدُ', 'وَإِمَّا', 'فِدَاءً'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 4, role: 'إما تفصيلا لمجمل' }] },
          ],
          distractors: ['نهي بعد أمر', 'استفهام توبيخ', 'مؤكد لمضمون الجملة'],
        },
        {
          title: 'تركيب: ﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾',
          kind: 'tarkeeb',
          instruction: 'Which قياسي موضع does this illustrate؟',
          sentence: 'أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا',
          translation: 'Those are the believers, truly.',
          cells: ['أُولَٰئِكَ', 'هُمُ', 'الْمُؤْمِنُونَ', 'حَقًّا'],
          rows: [
            { position: 'above', labels: [{ start: 3, end: 3, role: 'مؤكد لمضمون الجملة' }] },
          ],
          distractors: ['نهي بعد أمر', 'استفهام توبيخ', 'إما تفصيلا لمجمل'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'التحذير والإغراء',
      subtitle: 'Warning and Urging — التحذير and الإغراء, their أركان, and how the عامل is dropped',
      concepts: [
        {
          heading: 'التحذير: تعريفه وأركانه',
          lines: [
            { html: `<bdi>التَّحْذِير</bdi> is the نصب of a noun by a deleted verb conveying a warning against something disliked, so that the addressee avoids it.`, list: false },
            { html: `It has four أَرْكَان:`, list: false },
            { html: `the implied verb of warning — اِحْذَرْ، بَاعِدْ، تَجَنَّبْ، قِ، تَوَقَّ or similar`, list: true, bullet: true },
            { html: `<bdi>الْمُحَذِّر</bdi> — the warner, the speaker`, list: true, bullet: true },
            { html: `<bdi>الْمُحَذَّر</bdi> — the one warned, the addressee`, list: true, bullet: true },
            { html: `<bdi>الْمُحَذَّرُ مِنْهُ</bdi> — the thing warned against`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Define التحذير and name its four أركان.`,
            kind: 'mcq',
            options: ['The نصب of a noun by a deleted verb conveying تحذير; its أركان are the implied verb, المحذِّر, المحذَّر, and المحذَّر منه', 'The رفع of a noun by a stated verb conveying ترغيب; its أركان are المغري, المغرَى, and المغرَى به only', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated, non-deleted governing حرف'],
            correct: 0,
          },
        },
        {
          heading: 'وجوه التحذير: بالضمير المنفصل إياك',
          lines: [
            { html: `التحذير has three <bdi>وُجُوه</bdi> (forms). One mentions المحذَّر with the detached منصوب pronoun <bdi>إِيَّاكَ</bdi>, in three ways:`, list: false },
            { html: `with عطف of المحذَّر منه, as in إِيَّاكَ وَالْحَسَدَ`, list: true, bullet: true },
            { html: `without عطف, repeating the pronoun, as in إِيَّاكَ إِيَّاكَ الْمِرَاءَ`, list: true, bullet: true },
            { html: `with جر by مِنْ, overt as in إِيَّاكَ مِنَ الْحَسَدِ or implied as in إِيَّاكَ أَنْ تَحْسُدَ`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Parse إِيَّاكَ وَالْحَسَدَ.`,
            kind: 'mcq',
            options: ['إياك: المحذَّر, a detached pronoun منصوب by an obligatorily-deleted verb; والحسد: المحذَّر منه معطوف عليه', 'إياك: المحذِّر, the speaker; والحسد: the implied verb', 'إياك: مبتدأ; والحسد: خبره', 'إياك: فاعل a stated verb; والحسد: مفعول به ثانٍ'],
            correct: 0,
          },
        },
        {
          heading: 'وجوه التحذير: بالاسم الظاهر، وبذكر المحذَّر منه وحده',
          lines: [
            { html: `The second وجه mentions المحذَّر with an overt noun (اسْمٌ ظَاهِر): alone (نَفْسَكَ), repeated (نَفْسَكَ نَفْسَكَ), or with المحذَّر منه conjoined (نَفْسَكَ وَالْحَسَدَ).`, list: false },
            { html: `The third وجه mentions only المحذَّر منه, either repeated (اللَّهَ اللَّهَ) or with a second item conjoined, as in ﴿نَاقَةَ اللَّهِ وَسُقْيَاهَا﴾.`, list: false },
            { html: `التحذير can also occur without deleting the verb of warning at all: ﴿قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا﴾ states قوا outright.`, list: false },
          ],
          exercise: {
            prompt: `Can التحذير occur without deletion of the verb of warning? Give the Qur’anic example.`,
            kind: 'mcq',
            options: ['Yes: ﴿قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا﴾, where قوا is stated outright', 'No, deletion of the verb is always obligatory in التحذير', 'Only in poetry, never in the Qur’an', 'Only when المحذَّر منه is repeated'],
            correct: 0,
          },
        },
        {
          heading: 'الإغراء: تعريفه وأركانه',
          lines: [
            { html: `<bdi>الْإِغْرَاء</bdi> is the نصب of a noun by a deleted verb conveying encouragement and enticement (التَّرْغِيبُ وَالتَّشْوِيق) toward something desirable, so that the addressee does it.`, list: false },
            { html: `Its four أركان:`, list: false },
            { html: `the implied verb of urging — الْزَمْ، اطْلُبْ، خُذْ، افْعَلْ or similar`, list: true, bullet: true },
            { html: `<bdi>الْمُغْرِي</bdi> — the urger, the speaker`, list: true, bullet: true },
            { html: `<bdi>الْمُغْرَى</bdi> — the one urged, the addressee`, list: true, bullet: true },
            { html: `<bdi>الْمُغْرَى بِهِ</bdi> — the thing urged toward`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Define الإغراء and name its four أركان.`,
            kind: 'mcq',
            options: ['The نصب of a noun by a deleted verb conveying ترغيب وتشويق; its أركان are the implied verb, المغري, المغرَى, and المغرَى به', 'The نصب of a noun by a deleted verb conveying تحذير من مكروه', 'The رفع of a noun by a stated verb', 'The جر of a noun by a deleted حرف جر'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع وجوب الحذف في الإغراء، وعدم الحذف',
          lines: [
            { html: `Deletion of the عامل is obligatory in الإغراء in two cases: when المغرى به is repeated, as in الصَّبْرَ الصَّبْرَ, or when something is conjoined to it, as in الْعِلْمَ وَالْحِلْمَ.`, list: false },
            { html: `Like التحذير, الإغراء can also occur without deleting the verb: ﴿يَا يَحْيَىٰ خُذِ الْكِتَابَ بِقُوَّةٍ﴾ states خذ.`, list: false },
          ],
          exercise: {
            prompt: `When is deletion of the عامل obligatory in الإغراء؟`,
            kind: 'mcq',
            options: ['When المغرى به is repeated, or when something is conjoined to it', 'Only when the verb is a فعل أمر', 'Only in Qur’anic examples', 'Deletion is never obligatory in الإغراء'],
            correct: 0,
          },
        },
        {
          heading: 'الملحقات بالتحذير والإغراء',
          lines: [
            { html: `Two expressions are attached (<bdi>يُلْحَقُ</bdi>) to التحذير والإغراء with their own implied verbs: <bdi>مَرْحَبًا</bdi> and <bdi>أَهْلًا وَسَهْلًا</bdi> — with the implied verb <bdi>أَصَبْتَ</bdi> — and <bdi>امْرَأً وَنَفْسَهُ</bdi> — with the implied verb <bdi>دَعْ</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `مَرْحَبًا and أَهْلًا وَسَهْلًا are attached to التحذير والإغراء with which implied verb؟`,
            kind: 'mcq',
            options: ['أصبتَ', 'احذر', 'الزم', 'دعْ'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'التحذير is defined as:', options: ['The نصب of a noun by a deleted verb conveying a warning against something disliked, so the addressee avoids it', 'The رفع of a noun by a stated verb conveying ترغيب', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated governing حرف'], correct: 0 },
        { q: 'إِيَّاكَ وَالْحَسَدَ shows المحذَّر expressed with:', options: ['a detached pronoun (إياك), معطوفا عليه المحذر منه', 'an overt noun repeated', 'only the المحذَّر منه, without إياك', 'a stated verb, without any حذف'], correct: 0 },
        { q: '﴿قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا﴾ shows that التحذير:', options: ['can occur without deleting the verb of warning', 'always requires deletion of the verb', 'is only ever expressed by إياك', 'never takes a stated فعل'], correct: 0 },
        { q: 'الإغراء is defined as:', options: ['The نصب of a noun by a deleted verb conveying encouragement and enticement toward something desirable', 'The نصب of a noun by a deleted verb conveying a warning against something disliked', 'The جر of a noun by a governing حرف', 'The رفع of a noun by a stated verb'], correct: 0 },
        { q: 'الصَّبْرَ الصَّبْرَ illustrates obligatory deletion in الإغراء because:', options: ['المغرى به is repeated', 'a حرف جر precedes it', 'it is a Qur’anic example', 'the verb خُذْ is stated'], correct: 0 },
        { q: 'مَرْحَبًا and أَهْلًا وَسَهْلًا are ملحقات attached with the implied verb:', options: ['أصبتَ', 'احذر', 'الزم', 'دعْ'], correct: 0 },
      ],
      bank: [
        { title: 'أركان التحذير الأربعة', kind: 'mcq', prompt: 'List the four أركان of التحذير.', options: ['الفعل المحذوف, المحذِّر, المحذَّر, المحذَّر منه', 'الفعل المذكور, المغري, المغرَى, المغرَى به', 'الفعل المحذوف, الفاعل, المفعول به, الحال', 'المحذِّر, المحذَّر, الفاعل, النائب عن الفاعل'], correct: 0 },
        { title: 'وجوه التحذير الثلاثة', kind: 'mcq', prompt: 'How many وجوه does التحذير have, and what are they؟', options: ['Three: بالضمير المنفصل, بالاسم الظاهر, وبذكر المحذر منه وحده', 'Two: بالضمير فقط وبالاسم الظاهر فقط', 'Four, matching its four أركان', 'One only: بالضمير المنفصل إياك'], correct: 0 },
        { title: 'التكرار دون عطف', kind: 'mcq', prompt: 'إِيَّاكَ إِيَّاكَ الْمِرَاءَ illustrates التحذير expressed by:', options: ['repeating إياك without عطف', 'عطف المحذر منه على إياك', 'جر المحذر منه بمن', 'ذكر المحذر منه وحده'], correct: 0 },
        { title: 'إياك من الحسد', kind: 'mcq', prompt: 'إِيَّاكَ مِنَ الْحَسَدِ illustrates التحذير by إياك expressed with:', options: ['جر المحذر منه بمن (ظاهرة)', 'عطف المحذر منه على إياك', 'تكرار إياك دون عطف', 'ذكر المحذر منه وحده'], correct: 0 },
        { title: 'نفسَك نفسَك', kind: 'mcq', prompt: 'نَفْسَكَ نَفْسَكَ illustrates التحذير expressed by:', options: ['اسم ظاهر مكرر', 'ضمير منفصل معطوف عليه', 'ذكر المحذر منه فقط', 'فعل مذكور غير محذوف'], correct: 0 },
        { title: 'اللهَ اللهَ', kind: 'mcq', prompt: 'اللَّهَ اللَّهَ illustrates التحذير expressed by:', options: ['ذكر المحذَّر منه وحده, مكررا', 'ضمير منفصل إياك', 'اسم ظاهر معطوف عليه المحذر منه', 'فعل مذكور غير محذوف'], correct: 0 },
        { title: 'ناقة الله وسقياها', kind: 'mcq', prompt: '﴿نَاقَةَ اللَّهِ وَسُقْيَاهَا﴾ illustrates التحذير by mentioning المحذَّر منه:', options: ['with a second item conjoined to it', 'repeated with no عطف', 'preceded by إياك', 'preceded by a stated verb of warning'], correct: 0 },
        { title: 'أركان الإغراء الأربعة', kind: 'mcq', prompt: 'List the four أركان of الإغراء.', options: ['الفعل المحذوف, المغري, المغرَى, المغرَى به', 'الفعل المحذوف, المحذِّر, المحذَّر, المحذَّر منه', 'الفاعل, المفعول به, الحال, التمييز', 'المغري, المغرَى, الفاعل, النائب عن الفاعل'], correct: 0 },
        { title: 'العلمَ والحلمَ', kind: 'mcq', prompt: 'الْعِلْمَ وَالْحِلْمَ illustrates obligatory deletion in الإغراء because:', options: ['something is conjoined to المغرى به', 'المغرى به is repeated', 'the verb الزم is stated outright', 'a حرف جر precedes المغرى به'], correct: 0 },
        { title: 'الإغراء بلا حذف', kind: 'mcq', prompt: '﴿يَا يَحْيَىٰ خُذِ الْكِتَابَ بِقُوَّةٍ﴾ shows that الإغراء:', options: ['can occur with the verb خذ stated, not deleted', 'always requires the verb to be deleted', 'is only ever expressed by تكرار المغرى به', 'never occurs in Qur’anic Arabic'], correct: 0 },
        { title: 'ملحق امرأ ونفسه', kind: 'mcq', prompt: 'امْرَأً وَنَفْسَهُ is a ملحق attached with the implied verb:', options: ['دعْ', 'أصبتَ', 'احذر', 'الزم'], correct: 0 },
        {
          title: 'تركيب: إِيَّاكَ وَالْحَسَدَ',
          kind: 'tarkeeb',
          instruction: 'Identify each ركن, then classify the whole example.',
          sentence: 'إِيَّاكَ وَالْحَسَدَ',
          translation: 'Beware of envy!',
          cells: ['إِيَّاكَ', 'وَالْحَسَدَ'],
          rows: [
            { position: 'above', label: 'الأركان', labels: [
              { start: 0, end: 0, role: 'المحذَّر' },
              { start: 1, end: 1, role: 'المحذَّر منه' },
            ] },
            { position: 'below', label: 'النوع', labels: [{ start: 0, end: 1, role: 'التحذير' }] },
          ],
          distractors: ['المحذِّر', 'الإغراء'],
        },
        {
          title: 'تركيب: نَفْسَكَ نَفْسَكَ',
          kind: 'tarkeeb',
          instruction: 'Identify the وجه of التحذير here, then classify the whole example.',
          sentence: 'نَفْسَكَ نَفْسَكَ',
          translation: 'Yourself, yourself! (watch out)',
          cells: ['نَفْسَكَ', 'نَفْسَكَ'],
          rows: [
            { position: 'above', label: 'الوجه', labels: [{ start: 0, end: 1, role: 'بالاسم الظاهر مكررا' }] },
            { position: 'below', label: 'النوع', labels: [{ start: 0, end: 1, role: 'التحذير' }] },
          ],
          distractors: ['بالضمير المنفصل', 'الإغراء'],
        },
        {
          title: 'تركيب: اللَّهَ اللَّهَ',
          kind: 'tarkeeb',
          instruction: 'Identify the وجه of التحذير here, then classify the whole example.',
          sentence: 'اللَّهَ اللَّهَ',
          translation: 'Fear Allah, fear Allah!',
          cells: ['اللَّهَ', 'اللَّهَ'],
          rows: [
            { position: 'above', label: 'الوجه', labels: [{ start: 0, end: 1, role: 'بذكر المحذر منه وحده' }] },
            { position: 'below', label: 'النوع', labels: [{ start: 0, end: 1, role: 'التحذير' }] },
          ],
          distractors: ['بالضمير المنفصل', 'الإغراء'],
        },
        {
          title: 'تركيب: الصَّبْرَ الصَّبْرَ',
          kind: 'tarkeeb',
          instruction: 'Identify each ركن, then classify the whole example.',
          sentence: 'الصَّبْرَ الصَّبْرَ',
          translation: 'Patience, patience!',
          cells: ['الصَّبْرَ', 'الصَّبْرَ'],
          rows: [
            { position: 'above', label: 'الأركان', labels: [{ start: 0, end: 1, role: 'المغرَى به مكرر' }] },
            { position: 'below', label: 'النوع', labels: [{ start: 0, end: 1, role: 'الإغراء' }] },
          ],
          distractors: ['المغري', 'التحذير'],
        },
        {
          title: 'تركيب: الْعِلْمَ وَالْحِلْمَ',
          kind: 'tarkeeb',
          instruction: 'Classify this example: التحذير or الإغراء؟',
          sentence: 'الْعِلْمَ وَالْحِلْمَ',
          translation: 'Knowledge and forbearance! (pursue them)',
          cells: ['الْعِلْمَ', 'وَالْحِلْمَ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 1, role: 'الإغراء' }] },
          ],
          distractors: ['التحذير'],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'الاختصاص والاشتغال',
      subtitle: 'Specification and Preoccupation — الاختصاص and الاشتغال, and how المشغول عنه is declined',
      concepts: [
        {
          heading: 'الاختصاص: تعريفه ومثاله',
          lines: [
            { html: `<bdi>الِاخْتِصَاص</bdi> is the نصب of a noun by a deleted verb — such as <bdi>أَخُصُّ</bdi> or <bdi>أَعْنِي</bdi> — which specifies the intended referent of a pronoun mentioned before it.`, list: false },
            { html: `In ﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾, <bdi>أَهْلَ الْبَيْتِ</bdi> is منصوب by an implied أخص/أعني, specifying who كُمْ refers to.`, list: false },
          ],
          exercise: {
            prompt: `Define الاختصاص and explain what أَهْلَ الْبَيْتِ does in ﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾.`,
            kind: 'mcq',
            options: ['The نصب of a noun by a deleted verb (أخص/أعني) specifying the referent of a preceding ضمير — here, specifying كُمْ', 'The رفع of a noun by a deleted verb specifying the فاعل', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated, non-deleted verb like أعني'],
            correct: 0,
          },
        },
        {
          heading: 'الاختصاص بأيها وأيتها',
          lines: [
            { html: `الاختصاص can also be expressed with <bdi>أَيُّهَا</bdi>/<bdi>أَيَّتُهَا</bdi> without <bdi>يَا</bdi>, following the same rules as <bdi>النِّدَاء</bdi>. Example: «وَنَهَى رَسُولُ اللَّهِ ﷺ الْمُسْلِمِينَ عَنْ كَلَامِنَا أَيُّهَا الثَّلَاثَةُ».`, list: false },
          ],
          exercise: {
            prompt: `Can الاختصاص be expressed with أَيُّهَا and أَيَّتُهَا? What rules apply؟`,
            kind: 'mcq',
            options: ['Yes, without يا, and it follows the rules of النداء', 'No, أيها/أيتها are exclusive to النداء', 'Yes, but only when preceded by يا', 'Yes, but it follows the rules of الاشتغال instead'],
            correct: 0,
          },
        },
        {
          heading: 'الاشتغال: تعريفه وأركانه',
          lines: [
            { html: `<bdi>الِاشْتِغَال</bdi> is when a noun precedes a verb which governs a pronoun referring back to that noun, such that if the verb were freed from governing that pronoun, it would place the fronted noun in نصب — as in ﴿وَرُسُلًا قَدْ قَصَصْنَاهُمْ عَلَيْكَ﴾.`, list: false },
            { html: `Its three أركان:`, list: false },
            { html: `<bdi>الْمَشْغُول</bdi> — the عامل itself, also called <bdi>الْمُشْتَغِل</bdi>`, list: true, bullet: true },
            { html: `<bdi>الْمَشْغُولُ بِهِ</bdi> — the pronoun referring back to the fronted noun`, list: true, bullet: true },
            { html: `<bdi>الْمَشْغُولُ عَنْهُ</bdi> — the fronted noun itself`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Define الاشتغال and name its three أركان.`,
            kind: 'mcq',
            options: ['A fronted noun preceding a verb that governs a pronoun referring back to it; its أركان are المشغول, المشغول به, and المشغول عنه', 'A fronted verb preceding a noun; its أركان are الفاعل والمفعول به فقط', 'A pronoun preceding its own antecedent noun', 'A noun preceded by a deleted فعل, with no pronoun involved'],
            correct: 0,
          },
        },
        {
          heading: 'الاسم الوصفي للاشتغال، وإعراب المشغول عنه',
          lines: [
            { html: `الاشتغال's traditional descriptive name is <bdi>مَا أُضْمِرَ عَامِلُهُ عَلَىٰ شَرِيطَةِ التَّفْسِير</bdi> — "that whose governor is concealed on condition of interpretation."`, list: false },
            { html: `المشغول عنه generally has two possible إعراب options: <bdi>رَفْع</bdi> (as مبتدأ) or <bdi>نَصْب</bdi> (by a deleted verb), as in ﴿وَالْمَوْتَىٰ يَبْعَثُهُمُ اللَّهُ﴾, which allows either reading.`, list: false },
          ],
          exercise: {
            prompt: `What two إعراب options exist in general for المشغول عنه? Give the Qur’anic example.`,
            kind: 'mcq',
            options: ['رفع (as مبتدأ) or نصب (by a deleted verb): ﴿وَالْمَوْتَىٰ يَبْعَثُهُمُ اللَّهُ﴾', 'جر only, never رفع or نصب', 'رفع only, never نصب', 'نصب only, never رفع'],
            correct: 0,
          },
        },
        {
          heading: 'وجوب الرفع أو النصب في المشغول عنه',
          lines: [
            { html: `رفع of المشغول عنه is obligatory when it falls after a particle specific to nouns, such as <bdi>إِذَا الْفُجَائِيَّة</bdi>: خَلَقَ اللَّهُ الْإِنْسَانَ وَأَنْعَمَ عَلَيْهِ فَإِذَا الشَّيْطَانُ يَتْبَعُهُ.`, list: false },
            { html: `نصب is obligatory when it falls after a particle specific to verbs, such as <bdi>التَّحْضِيض</bdi> (هَلَّا الْجَنَّةَ طَلَبْتَهَا) or <bdi>الشَّرْط</bdi> (إِنِ الْجَنَّةَ تُرِدْهَا فَاعْمَلْ صَالِحًا).`, list: false },
          ],
          exercise: {
            prompt: `When is رفع of المشغول عنه obligatory, and when is نصب obligatory؟`,
            kind: 'mcq',
            options: ['رفع is obligatory after a particle specific to nouns (إذا الفجائية); نصب is obligatory after a particle specific to verbs (التحضيض, الشرط)', 'رفع is always obligatory, نصب is never used', 'نصب is always obligatory, رفع is never used', 'Both are obligatory simultaneously in every case'],
            correct: 0,
          },
        },
        {
          heading: 'ترجيح النصب، والفعل المرادف',
          lines: [
            { html: `نصب of المشغول عنه is preferred (يُتَرَجَّح) in three cases:`, list: false },
            { html: `the عامل is a verb of طَلَب, as in اللَّهَ اعْبُدْهُ وَرَسُولَهُ اتَّبِعْهُ`, list: true, bullet: true },
            { html: `a جملة فعلية precedes the معمول, as in أَعْبُدُ اللَّهَ وَرَسُولَهُ أَتَّبِعُهُ`, list: true, bullet: true },
            { html: `a particle that mostly precedes verbs comes first, e.g. مَا النَّافِيَة or هَمْزَةُ الِاسْتِفْهَام: ﴿أَبَشَرًا مِنَّا وَاحِدًا نَتَّبِعُهُ﴾`, list: true, bullet: true },
            { html: `The deleted verb in الاشتغال need not be the same word as the stated one — it may be a <bdi>مُرَادِف</bdi> (synonym), as in ﴿وَالظَّالِمِينَ أَعَدَّ لَهُمْ عَذَابًا أَلِيمًا﴾, where the implied verb is like <bdi>أَوْعَدَ</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `Can the deleted verb in الاشتغال be a synonym rather than the exact stated verb? Give the example.`,
            kind: 'mcq',
            options: ['Yes — a verb مرادف to the stated عامل: ﴿وَالظَّالِمِينَ أَعَدَّ لَهُمْ عَذَابًا أَلِيمًا﴾, implying أوعد', 'No, the deleted verb must always be identical to the stated one', 'Only when the stated verb is a فعل أمر', 'Only in the three cases where نصب is obligatory'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'الاختصاص is defined as:', options: ['The نصب of a noun by a deleted verb (أخص/أعني) specifying the intended referent of a preceding ضمير', 'The رفع of a noun by a deleted verb specifying the فاعل', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated verb, always'], correct: 0 },
        { q: 'الاختصاص can be expressed with أيها/أيتها:', options: ['without يا, following the rules of النداء', 'only with يا preceding them', 'only inside الاشتغال', 'never — أيها/أيتها belong only to النداء'], correct: 0 },
        { q: 'الاشتغال’s three أركان are:', options: ['المشغول, المشغول به, المشغول عنه', 'المغري, المغرَى, المغرَى به', 'المحذِّر, المحذَّر, المحذَّر منه', 'الفاعل, المفعول به, الحال'], correct: 0 },
        { q: 'The descriptive name of الاشتغال is:', options: ['ما أضمر عامله على شريطة التفسير', 'ما دل على معنى في نفسه مقترن بزمن', 'كل لفظ دل على معنى مفرد', 'ما نصب المفعول به بفعل محذوف دائما'], correct: 0 },
        { q: 'رفع of المشغول عنه is obligatory when it falls after:', options: ['a particle specific to nouns, such as إذا الفجائية', 'a particle specific to verbs, such as الشرط', 'any حرف جر at all', 'a فعل أمر specifically'], correct: 0 },
        { q: 'نصب of المشغول عنه is preferred (يترجح) when:', options: ['the عامل is a verb of طلب', 'the عامل is a اسم فاعل', 'المشغول عنه is مبني', 'no جملة فعلية precedes it'], correct: 0 },
      ],
      bank: [
        { title: 'الفعل المقدر في الاختصاص', kind: 'mcq', prompt: 'The deleted verb in الاختصاص is typically:', options: ['أخص or أعني', 'احذر or باعد', 'اعبدْ or اتبعْ', 'أدعو'], correct: 0 },
        { title: 'أهل البيت في مثال الاختصاص', kind: 'mcq', prompt: 'In ﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾, أهل البيت specifies the referent of:', options: ['the ضمير كُمْ', 'the ضمير هُ in بركاته', 'the اسم الله', 'nothing — it specifies no ضمير at all'], correct: 0 },
        { title: 'أيها الثلاثة', kind: 'mcq', prompt: '«...عَنْ كَلَامِنَا أَيُّهَا الثَّلَاثَةُ» illustrates الاختصاص expressed:', options: ['with أيها, following rules of النداء, without يا', 'with أخص stated outright', 'with أعني stated outright', 'with a حرف جر, not a فعل محذوف'], correct: 0 },
        { title: 'المشغول والمشغول به', kind: 'mcq', prompt: 'In الاشتغال, المشغول به refers to:', options: ['the pronoun that refers back to the fronted noun', 'the fronted noun itself', 'the عامل / المشتغِل itself', 'a completely unrelated noun'], correct: 0 },
        { title: 'المشغول عنه', kind: 'mcq', prompt: 'In الاشتغال, المشغول عنه refers to:', options: ['the fronted noun itself', 'the pronoun referring back to it', 'the عامل / المشتغِل itself', 'a deleted verb with no fronted noun'], correct: 0 },
        { title: 'شريطة التفسير', kind: 'mcq', prompt: 'ما أضمر عامله على شريطة التفسير is the traditional descriptive name for:', options: ['الاشتغال', 'الاختصاص', 'التحذير', 'الإغراء'], correct: 0 },
        { title: 'رفع بعد إذا الفجائية', kind: 'mcq', prompt: 'خَلَقَ اللَّهُ الْإِنْسَانَ وَأَنْعَمَ عَلَيْهِ فَإِذَا الشَّيْطَانُ يَتْبَعُهُ shows المشغول عنه obligatorily رفوع because it follows:', options: ['إذا الفجائية, a particle specific to nouns', 'التحضيض, a particle specific to verbs', 'الشرط, a particle specific to verbs', 'a حرف جر'], correct: 0 },
        { title: 'نصب بعد التحضيض', kind: 'mcq', prompt: 'هَلَّا الْجَنَّةَ طَلَبْتَهَا shows المشغول عنه obligatorily منصوب because it follows:', options: ['حرف تحضيض, specific to verbs', 'حرف اختصاص, specific to nouns', 'إذا الفجائية', 'ما النافية'], correct: 0 },
        { title: 'ترجيح النصب بعامل الطلب', kind: 'mcq', prompt: 'اللَّهَ اعْبُدْهُ وَرَسُولَهُ اتَّبِعْهُ shows نصب preferred because:', options: ['the عامل is a verb of طلب', 'a جملة اسمية precedes it', 'إذا الفجائية precedes it', 'a حرف جر governs it'], correct: 0 },
        { title: 'ترجيح النصب بجملة فعلية سابقة', kind: 'mcq', prompt: 'أَعْبُدُ اللَّهَ وَرَسُولَهُ أَتَّبِعُهُ shows نصب preferred because:', options: ['a جملة فعلية precedes the معمول', 'the عامل is a اسم فاعل', 'إذا الفجائية precedes it', 'the sentence has no ضمير at all'], correct: 0 },
        { title: 'الفعل المرادف في الاشتغال', kind: 'mcq', prompt: '﴿وَالظَّالِمِينَ أَعَدَّ لَهُمْ عَذَابًا أَلِيمًا﴾ shows the implied deleted verb as:', options: ['a مرادف (synonym) to the stated verb, like أوعد', 'the exact same word أعدّ, repeated', 'a فعل أمر', 'a فعل مضارع'], correct: 0 },
        {
          title: 'تركيب: ﴿وَرُسُلًا قَدْ قَصَصْنَاهُمْ عَلَيْكَ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify each ركن of الاشتغال, then classify the whole example.',
          sentence: 'وَرُسُلًا قَدْ قَصَصْنَاهُمْ عَلَيْكَ',
          translation: 'And [We sent] messengers We have told you about before.',
          cells: ['وَرُسُلًا', 'قَدْ', 'قَصَصْنَا', 'هُمْ', 'عَلَيْكَ'],
          rows: [
            { position: 'above', label: 'الأركان', labels: [
              { start: 0, end: 0, role: 'المشغول عنه' },
              { start: 2, end: 2, role: 'المشغول' },
              { start: 3, end: 3, role: 'المشغول به' },
            ] },
            { position: 'below', label: 'النوع', labels: [{ start: 0, end: 4, role: 'الاشتغال' }] },
          ],
          distractors: ['المحذَّر منه', 'الاختصاص'],
        },
        {
          title: 'تركيب: ﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify this example: الاختصاص or الاشتغال؟',
          sentence: 'رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ',
          translation: "The mercy of Allah and His blessings be upon you, people of the house.",
          cells: ['رَحْمَتُ', 'اللَّهِ', 'وَبَرَكَاتُهُ', 'عَلَيْكُمْ', 'أَهْلَ', 'الْبَيْتِ'],
          rows: [
            { position: 'above', labels: [{ start: 4, end: 5, role: 'الاختصاص' }] },
          ],
          distractors: ['الاشتغال'],
        },
        {
          title: 'تركيب: خَلَقَ اللَّهُ الْإِنْسَانَ وَأَنْعَمَ عَلَيْهِ فَإِذَا الشَّيْطَانُ يَتْبَعُهُ',
          kind: 'tarkeeb',
          instruction: 'Classify the required إعراب of المشغول عنه here.',
          sentence: 'خَلَقَ اللَّهُ الْإِنْسَانَ وَأَنْعَمَ عَلَيْهِ فَإِذَا الشَّيْطَانُ يَتْبَعُهُ',
          translation: 'Allah created man and blessed him, and behold, Satan follows him.',
          cells: ['خَلَقَ', 'اللَّهُ', 'الْإِنْسَانَ', 'وَأَنْعَمَ', 'عَلَيْهِ', 'فَإِذَا', 'الشَّيْطَانُ', 'يَتْبَعُهُ'],
          rows: [
            { position: 'above', labels: [{ start: 6, end: 6, role: 'رفع واجب (بعد إذا الفجائية)' }] },
          ],
          distractors: ['نصب واجب (بعد حرف التحضيض)', 'نصب واجب (بعد حرف الشرط)'],
        },
        {
          title: 'تركيب: هَلَّا الْجَنَّةَ طَلَبْتَهَا',
          kind: 'tarkeeb',
          instruction: 'Classify the required إعراب of المشغول عنه here.',
          sentence: 'هَلَّا الْجَنَّةَ طَلَبْتَهَا',
          translation: 'Why did you not seek Paradise?',
          cells: ['هَلَّا', 'الْجَنَّةَ', 'طَلَبْتَهَا'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'نصب واجب (بعد حرف التحضيض)' }] },
          ],
          distractors: ['رفع واجب (بعد إذا الفجائية)', 'نصب واجب (بعد حرف الشرط)'],
        },
        {
          title: 'تركيب: إِنِ الْجَنَّةَ تُرِدْهَا فَاعْمَلْ صَالِحًا',
          kind: 'tarkeeb',
          instruction: 'Classify the required إعراب of المشغول عنه here.',
          sentence: 'إِنِ الْجَنَّةَ تُرِدْهَا فَاعْمَلْ صَالِحًا',
          translation: 'If you want Paradise, then do righteous deeds.',
          cells: ['إِنِ', 'الْجَنَّةَ', 'تُرِدْهَا', 'فَاعْمَلْ', 'صَالِحًا'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'نصب واجب (بعد حرف الشرط)' }] },
          ],
          distractors: ['رفع واجب (بعد إذا الفجائية)', 'نصب واجب (بعد حرف التحضيض)'],
        },
      ],
    },
    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'النداء: أركانه وأحكامه',
      subtitle: 'The Vocative — النداء’s أركان, its seven particles, when they’re deleted, and how المنادى is declined',
      concepts: [
        {
          heading: 'تعريف النداء وأركانه',
          lines: [
            { html: `<bdi>النِّدَاء</bdi> is calling out with a particle that stands in the place of the verb <bdi>أَدْعُو</bdi>, as in يَا زَيْدُ.`, list: false },
            { html: `Its three أركان:`, list: false },
            { html: `the deleted verb of calling — أَدْعُو or similar`, list: true, bullet: true },
            { html: `the particle of النداء standing in its place, e.g. يَا`, list: true, bullet: true },
            { html: `<bdi>الْمُنَادَى</bdi> — the one called, e.g. زَيْد`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Define النداء and name its three أركان.`,
            kind: 'mcq',
            options: ['Calling out with a particle standing in for أدعو; its أركان are the deleted verb, the particle, and المنادى', 'Calling out with a stated verb only, never a particle', 'A form of التحذير expressed with يا', 'A form of الاشتغال with a fronted noun'],
            correct: 0,
          },
        },
        {
          heading: 'حروف النداء السبعة',
          lines: [
            { html: `The seven particles of النداء and their uses:`, list: false },
            { table: { headers: ['Group', 'حروف', 'Example'], rows: [
              ['للقريب', 'الْهَمْزَة، أَيْ', 'أَعَبْدَ اللَّهِ، أَيْ عَبْدَ اللَّهِ'],
              ['للبعيد', 'يَا، آ، أَيَا، هَيَا', 'يَا عَبْدَ اللَّهِ'],
              ['للندبة', 'وَا', '—'],
            ] } },
          ],
          exercise: {
            prompt: `List the seven particles of النداء and what each group is used for.`,
            kind: 'mcq',
            options: ['الهمزة وأي (للقريب), يا وآ وأيا وهيا (للبعيد), وا (للندبة)', 'ما ولا وإنْ (نافية فقط)', 'الفاء والواو وثم (عاطفة فقط)', 'كي وأنْ وأنَّ (مصدرية فقط)'],
            correct: 0,
          },
        },
        {
          heading: 'حذف حرف النداء: متى يجوز ومتى يمتنع',
          lines: [
            { html: `The particle of النداء may be deleted when المنادى is <bdi>مُضَاف</bdi> (﴿اعْمَلُوا آلَ دَاوُودَ شُكْرًا﴾) or a <bdi>عَلَم</bdi> (﴿يُوسُفُ أَعْرِضْ عَنْ هَٰذَا﴾).`, list: false },
            { html: `It may NOT be deleted with <bdi>لَفْظُ الْجَلَالَة</bdi> (الله) or with a <bdi>نَكِرَة مَقْصُودَة</bdi>, as in يَا رَجُلُ.`, list: false },
          ],
          exercise: {
            prompt: `With which منادى may the particle of النداء NOT be deleted؟`,
            kind: 'mcq',
            options: ['With لفظ الجلالة (الله) and with a نكرة مقصودة', 'With any مضاف منادى', 'With any علم منادى', 'The particle can always be deleted, with no exception'],
            correct: 0,
          },
        },
        {
          heading: 'إعراب المنادى: أصله، ومتى ينصب لفظا',
          lines: [
            { html: `The underlying إعراب of المنادى is that of a مفعول به of the deleted أدعو — منصوب either <bdi>لَفْظًا</bdi> (overtly) or <bdi>مَحَلًّا</bdi> (in position).`, list: false },
            { html: `It is منصوب لفظا in three cases:`, list: false },
            { table: { headers: ['Case', 'Example'], rows: [
              ['مُضَاف', 'يَا عَبْدَ اللَّهِ'],
              ['شَبِيهٌ بِالْمُضَاف — a noun governing what follows it', 'يَا غَافِرًا ذُنُوبَنَا'],
              ['غَيْرُ مُعَيَّن (unspecified)', 'يَا غَافِلًا وَالْمَوْتُ يَطْلُبُهُ'],
            ] } },
          ],
          exercise: {
            prompt: `When is the منادى منصوب لفظا? Give the three cases.`,
            kind: 'mcq',
            options: ['مضاف, شبيه بالمضاف, and غير معين', 'مفرد معرفة, مفرد نكرة مقصودة, and مثنى فقط', 'Only ever when it is مضاف', 'Only ever when preceded by لفظ الجلالة'],
            correct: 0,
          },
        },
        {
          heading: 'المنادى المبني: متى ولماذا',
          lines: [
            { html: `The <bdi>مُفْرَد</bdi> منادى (non-مضاف and non-شبيه بالمضاف) that is <bdi>مَعْرِفَة</bdi> or <bdi>نَكِرَة مَقْصُودَة</bdi> is <bdi>مَبْنِيّ</bdi> (منصوب محلا) — it is built on the sign it would take in رفع, as in يَا زَيْدُ، يَا رَجُلُ، يَا رَجُلَانِ، يَا مُسْلِمُونَ.`, list: false },
            { html: `That is why one says <bdi>يَا مُسْلِمُونَ</bdi> rather than <bdi>يَا مُسْلِمِينَ</bdi>: a مفرد definite منادى is built on its رفع sign — here الواو — even though it is منصوب محلا.`, list: false },
          ],
          exercise: {
            prompt: `Why do we say يَا مُسْلِمُونَ and not يَا مُسْلِمِينَ؟`,
            kind: 'mcq',
            options: ['A مفرد definite منادى is built on the sign it takes in رفع — here الواو — though it is منصوب محلا', 'مسلمين is simply ungrammatical Arabic in any context', 'Because النداء always requires رفع, never نصب', 'Because مسلمون is مضاف here'],
            correct: 0,
          },
        },
        {
          heading: 'المنادى المضاف إلى ياء المتكلم',
          lines: [
            { html: `Four forms are permitted for a منادى annexed to <bdi>يَاءُ الْمُتَكَلِّم</bdi>:`, list: false },
            { table: { headers: ['#', 'Form', 'Example'], rows: [
              ['1', 'deleting the ياء, sufficing with the كسرة', '﴿يَا عِبَادِ فَاتَّقُونِ﴾'],
              ['2', 'retaining the ياء quiescent', '﴿يَا عِبَادِيَ لَا خَوْفٌ عَلَيْكُمُ الْيَوْمَ﴾'],
              ['3', 'retaining the ياء with فتحة', '﴿يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ﴾'],
              ['4', 'turning the كسرة into فتحة and the ياء into ألف', '﴿يَا حَسْرَتَىٰ﴾'],
            ] } },
          ],
          exercise: {
            prompt: `What are the four permitted forms for a منادى annexed to ياء المتكلم؟`,
            kind: 'mcq',
            options: ['Deleting the ياء (كسرة alone), retaining it ساكنة, retaining it بفتحة, or turning كسرة+ياء into فتحة+ألف', 'Only ever deleting the ياء, with no alternative', 'Only ever retaining the ياء ساكنة', 'Turning the ياء into واو in every case'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'النداء is defined as:', options: ['Calling out with a particle standing in the place of the verb أدعو', 'Calling out with أدعو stated outright, never a particle', 'A نصب construction unrelated to any deleted فعل', 'A form exclusive to لفظ الجلالة'], correct: 0 },
        { q: 'الهمزة and أَيْ are used for:', options: ['النداء للقريب', 'النداء للبعيد', 'الندبة فقط', 'الاستغاثة فقط'], correct: 0 },
        { q: 'With which منادى may the particle of النداء NOT be deleted؟', options: ['لفظ الجلالة and النكرة المقصودة', 'Any مضاف منادى', 'Any علم منادى', 'It may always be deleted, without exception'], correct: 0 },
        { q: 'يَا غَافِرًا ذُنُوبَنَا shows المنادى منصوب لفظا because it is:', options: ['شبيه بالمضاف', 'مضاف', 'غير معين', 'معرفة مفردة'], correct: 0 },
        { q: 'A مفرد معرفة منادى (like زيد) is:', options: ['مبني, built on the sign of its رفع', 'منصوب لفظا always', 'مجرور always', 'مرفوع لفظا, not محلا'], correct: 0 },
        { q: '﴿يَا عِبَادِ فَاتَّقُونِ﴾ shows a منادى annexed to ياء المتكلم with:', options: ['the ياء deleted, sufficing with الكسرة', 'the ياء retained ساكنة', 'the ياء retained مفتوحة', 'the كسرة turned into فتحة and ياء into ألف'], correct: 0 },
      ],
      bank: [
        { title: 'أركان النداء الثلاثة', kind: 'mcq', prompt: 'List the three أركان of النداء.', options: ['الفعل المحذوف (أدعو), حرف النداء, المنادى', 'المحذِّر, المحذَّر, المحذَّر منه', 'المغري, المغرَى, المغرَى به', 'المشغول, المشغول به, المشغول عنه'], correct: 0 },
        { title: 'حروف البعيد', kind: 'mcq', prompt: 'يَا، آ، أَيَا، هَيَا are used for:', options: ['النداء للبعيد', 'النداء للقريب', 'الندبة فقط', 'الاستغاثة فقط'], correct: 0 },
        { title: 'حرف الندبة', kind: 'mcq', prompt: 'Which حرف نداء is used specifically for الندبة؟', options: ['وا', 'يا', 'الهمزة', 'أي'], correct: 0 },
        { title: 'حذف الحرف مع المضاف', kind: 'mcq', prompt: '﴿اعْمَلُوا آلَ دَاوُودَ شُكْرًا﴾ shows the particle of النداء deleted because المنادى is:', options: ['مضاف', 'نكرة مقصودة', 'لفظ الجلالة', 'شبيه بالمضاف'], correct: 0 },
        { title: 'حذف الحرف مع العلم', kind: 'mcq', prompt: '﴿يُوسُفُ أَعْرِضْ عَنْ هَٰذَا﴾ shows the particle of النداء deleted because المنادى is:', options: ['a علم', 'a نكرة مقصودة', 'لفظ الجلالة', 'مضاف'], correct: 0 },
        { title: 'أصل إعراب المنادى', kind: 'mcq', prompt: 'What is the underlying إعراب of المنادى؟', options: ['مفعول به of the deleted فعل أدعو', 'فاعل of the deleted فعل أدعو', 'مبتدأ with a deleted خبر', 'مضاف إليه of a deleted مضاف'], correct: 0 },
        { title: 'يا عبد الله: مضاف', kind: 'mcq', prompt: 'يَا عَبْدَ اللَّهِ shows المنادى منصوب لفظا because it is:', options: ['مضاف', 'شبيه بالمضاف', 'غير معين', 'مفرد معرفة'], correct: 0 },
        { title: 'يا غافلا: غير معين', kind: 'mcq', prompt: 'يَا غَافِلًا وَالْمَوْتُ يَطْلُبُهُ shows المنادى منصوب لفظا because it is:', options: ['غير معين', 'مضاف', 'شبيه بالمضاف', 'نكرة مقصودة'], correct: 0 },
        { title: 'يا رجلان: البناء', kind: 'mcq', prompt: 'يَا رَجُلَانِ shows a مبني منادى built on:', options: ['علامة رفعه (الألف)', 'الفتحة, like a normal منصوب', 'الكسرة, as if مجرور', 'السكون دائما'], correct: 0 },
        { title: 'الفرق بين المضاف وشبيه المضاف', kind: 'mcq', prompt: 'What distinguishes شبيه بالمضاف from مضاف in المنادى?', options: ['شبيه بالمضاف governs what follows it without being formally مضاف إليه to it', 'There is no real difference; they are the same category', 'شبيه بالمضاف is always مبني, unlike مضاف', 'مضاف never occurs with النداء at all'], correct: 0 },
        { title: 'يا عباديَ: إثبات الياء مفتوحة', kind: 'mcq', prompt: '﴿يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ﴾ shows ياء المتكلم:', options: ['retained with فتحة', 'deleted entirely', 'retained ساكنة', 'turned into ألف'], correct: 0 },
        { title: 'يا حسرتى: قلب الياء ألفا', kind: 'mcq', prompt: '﴿يَا حَسْرَتَىٰ﴾ shows which treatment of ياء المتكلم؟', options: ['كسرة turned into فتحة and ياء into ألف', 'الياء retained ساكنة', 'الياء deleted, كسرة alone kept', 'الياء retained مفتوحة without change'], correct: 0 },
        {
          title: 'تركيب: أَعَبْدَ اللَّهِ',
          kind: 'tarkeeb',
          instruction: 'Classify this حرف نداء: للقريب or للبعيد؟',
          sentence: 'أَعَبْدَ اللَّهِ',
          translation: 'O Abdullah (calling one nearby)',
          cells: ['أَ', 'عَبْدَ', 'اللَّهِ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 0, role: 'للقريب' }] },
          ],
          distractors: ['للبعيد'],
        },
        {
          title: 'تركيب: أَيْ عَبْدَ اللَّهِ',
          kind: 'tarkeeb',
          instruction: 'Classify this حرف نداء: للقريب or للبعيد؟',
          sentence: 'أَيْ عَبْدَ اللَّهِ',
          translation: 'O Abdullah (calling one nearby)',
          cells: ['أَيْ', 'عَبْدَ', 'اللَّهِ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 0, role: 'للقريب' }] },
          ],
          distractors: ['للبعيد'],
        },
        {
          title: 'تركيب: يَا عَبْدَ اللَّهِ',
          kind: 'tarkeeb',
          instruction: 'Classify this حرف نداء, then the نصب of المنادى.',
          sentence: 'يَا عَبْدَ اللَّهِ',
          translation: 'O Abdullah (calling one far)',
          cells: ['يَا', 'عَبْدَ', 'اللَّهِ'],
          rows: [
            { position: 'above', label: 'الحرف', labels: [{ start: 0, end: 0, role: 'للبعيد' }] },
            { position: 'below', label: 'الإعراب', labels: [{ start: 1, end: 2, role: 'منصوب لفظا (مضاف)' }] },
          ],
          distractors: ['للقريب', 'منصوب محلا'],
        },
        {
          title: 'تركيب: يَا زَيْدُ',
          kind: 'tarkeeb',
          instruction: 'Classify the نصب of المنادى here.',
          sentence: 'يَا زَيْدُ',
          translation: 'O Zayd!',
          cells: ['يَا', 'زَيْدُ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'منصوب محلا (مفرد معرفة)' }] },
          ],
          distractors: ['منصوب لفظا'],
        },
        {
          title: 'تركيب: ﴿يَا عِبَادِ فَاتَّقُونِ﴾',
          kind: 'tarkeeb',
          instruction: 'What treatment of ياء المتكلم does this show؟',
          sentence: 'يَا عِبَادِ فَاتَّقُونِ',
          translation: 'O My servants, fear Me.',
          cells: ['يَا', 'عِبَادِ', 'فَاتَّقُونِ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'حذف الياء والاكتفاء بالكسرة' }] },
          ],
          distractors: ['إثبات الياء مفتوحة', 'قلب الكسرة فتحة والياء ألفا'],
        },
        {
          title: 'تركيب: ﴿يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ﴾',
          kind: 'tarkeeb',
          instruction: 'What treatment of ياء المتكلم does this show؟',
          sentence: 'يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ',
          translation: 'O My servants who have transgressed against themselves.',
          cells: ['يَا', 'عِبَادِيَ', 'الَّذِينَ', 'أَسْرَفُوا', 'عَلَىٰ', 'أَنْفُسِهِمْ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'إثبات الياء مفتوحة' }] },
          ],
          distractors: ['حذف الياء والاكتفاء بالكسرة', 'قلب الكسرة فتحة والياء ألفا'],
        },
        {
          title: 'تركيب: ﴿يَا حَسْرَتَىٰ﴾',
          kind: 'tarkeeb',
          instruction: 'What treatment of ياء المتكلم does this show؟',
          sentence: 'يَا حَسْرَتَىٰ',
          translation: 'Oh, my grief!',
          cells: ['يَا', 'حَسْرَتَىٰ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'قلب الكسرة فتحة والياء ألفا' }] },
          ],
          distractors: ['حذف الياء والاكتفاء بالكسرة', 'إثبات الياء مفتوحة'],
        },
      ],
    },
    // ---------------------------------------------------------------- L6
    {
      id: 'l6',
      title: 'ملحقات النداء',
      subtitle: 'Truncation, Appeals, and Lament — الترخيم, الاستغاثة, نداء التعجب, الندبة, and deleting عامل الحال',
      concepts: [
        {
          heading: 'الترخيم: تعريفه وما يجوز ترخيمه',
          lines: [
            { html: `<bdi>التَّرْخِيم</bdi> is deleting the end of المنادى for lightness (التَّخْفِيف), as in يَا فَاطِمَ (for فَاطِمَة).`, list: false },
            { html: `Only two kinds of nouns may undergo it: nouns ending in the تَاء, as in يَا عَائِشَ, and a masculine عَلَم of more than three letters that is not compound, as in يَا جَعْفَ (for جَعْفَر) — unlike زَيْنَب، زَيْد، عَبْدُ اللَّه.`, list: false },
          ],
          exercise: {
            prompt: `Which nouns may undergo الترخيم؟`,
            kind: 'mcq',
            options: ['Nouns ending in تاء, and a masculine علم of more than three letters that is not compound', 'Any منادى whatsoever, with no restriction', 'Only أسماء ending in ألف', 'Only compound أعلام like عبد الله'],
            correct: 0,
          },
        },
        {
          heading: 'الترخيم: الوزنان الجائزان في آخر المرخَّم',
          lines: [
            { html: `Two vowelings are permitted on the end of the <bdi>مُرَخَّم</bdi> منادى: keeping the original vowel it had before truncation, as in يَا حَارِ (for حَارِث), or giving it the ضَمَّة, as in يَا حَارُ.`, list: false },
          ],
          exercise: {
            prompt: `What two vowelings are permitted on the end of the مرخَّم منادى؟`,
            kind: 'mcq',
            options: ['Keeping the original vowel, or giving it the ضمة', 'Only the فتحة, with no alternative', 'Only the كسرة, with no alternative', 'The سكون only, in every case'],
            correct: 0,
          },
        },
        {
          heading: 'اللهم ودلالتها',
          lines: [
            { html: `<bdi>اللَّهُمَّ</bdi> is a vocative form (صِيغَةُ نِدَاء) for لفظ الجلالة.`, list: false },
            { html: `Before <bdi>إِلَّا</bdi>, it signals the rarity (نُدْرَة) of the مستثنى, as in اللَّهُمَّ إِلَّا أَنْ يَكُونَ كَذَا.`, list: false },
            { html: `Before <bdi>نَعَمْ</bdi>, it signals the responder's certainty (تَيَقُّن) of the answer, as in اللَّهُمَّ نَعَمْ.`, list: false },
          ],
          exercise: {
            prompt: `What does اللَّهُمَّ signify before إِلَّا, and what does it signify before نَعَمْ؟`,
            kind: 'mcq',
            options: ['Before إلا, the rarity (ندرة) of the مستثنى; before نعم, the responder’s certainty (تيقن)', 'Before إلا, certainty; before نعم, rarity', 'It signifies exactly the same thing in both positions', 'It has no distinct meaning in either position'],
            correct: 0,
          },
        },
        {
          heading: 'الاستغاثة: تعريفها وأركانها',
          lines: [
            { html: `<bdi>الِاسْتِغَاثَة</bdi> is a type of نداء: the caller calls a منادى to come to the aid of another.`, list: false },
            { html: `Its three أركان:`, list: false },
            { html: `the particle of الاستغاثة — which is يَا only`, list: true, bullet: true },
            { html: `<bdi>الْمُسْتَغَاث</bdi> — the one called for help, i.e. المنادى`, list: true, bullet: true },
            { html: `<bdi>الْمُسْتَغَاثُ لَهُ</bdi> / <bdi>لِأَجْلِهِ</bdi> — the one for whose sake help is sought`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Define الاستغاثة and name its three أركان.`,
            kind: 'mcq',
            options: ['A نداء calling المستغاث to come to another’s aid; its أركان are حرف الاستغاثة (يا), المستغاث, and المستغاث له', 'A نداء expressing grief with no أركان of its own', 'A form of التحذير calling for help', 'A form of الترخيم shortening المستغاث'],
            correct: 0,
          },
        },
        {
          heading: 'أحكام اللام في الاستغاثة',
          lines: [
            { html: `A <bdi>لَام جَارَّة</bdi> with <bdi>فَتْحَة</bdi> attaches to المستغاث, as in يَا لَلَّهِ; an <bdi>أَلِف</bdi> may substitute for it at the end, as in يَا زَيْدَا، يَا زَيْدَاهْ.`, list: false },
            { html: `When a second مستغاث is conjoined without repeating يا, its لام takes <bdi>كَسْرَة</bdi>, as in يَا لَلْأَمِيرِ وَلِلْمُسْلِمِينَ لِلْمَظْلُومِينَ.`, list: false },
            { html: `A لام جارة with كسرة also attaches to المستغاث له, as in يَا لَلَّهِ لِلْمُسْلِمِينَ.`, list: false },
          ],
          exercise: {
            prompt: `What لام attaches to المستغاث, and what may substitute for it?`,
            kind: 'mcq',
            options: ['A لام جارة with فتحة; an ألف at its end may substitute for it', 'A لام جارة with كسرة only, with no substitute', 'No لام attaches to المستغاث at all', 'A لام جارة with ضمة'],
            correct: 0,
          },
        },
        {
          heading: 'نداء التعجب والندبة',
          lines: [
            { html: `<bdi>نِدَاءُ التَّعَجُّب</bdi> is calling out to that which one marvels at; it is treated like الاستغاثة, with المتعجب منه taking the place of المستغاث, as in يَا لَلْقُرْآنِ، يَا قُرْآنَاهْ, or the place of المستغاث له with المستغاث deleted, as in يَا لِلْقُرْآنِ.`, list: false },
            { html: `<bdi>الْنَّدْبَة</bdi> is a type of نداء expressing grief (إِظْهَارُ الْحُزْن), expressed with <bdi>وَا</bdi> (وَا أَبَتَاهْ) or with <bdi>يَا</bdi> when confusion with plain نداء is not feared, as in يَا زَيْدُ.`, list: false },
            { html: `المنادى in الندبة is parsed exactly as in ordinary نداء — وَا زَيْدُ، وَا عَبْدَ اللَّهِ — and may take <bdi>أَلِفُ النَّدْبَة</bdi> at its end, as in وَا زَيْدَا, or <bdi>هَاءُ السَّكْت</bdi> after that ألف when pausing, as in وَا رَأْسَاهْ، وَا وَيْلَاهْ.`, list: false },
          ],
          exercise: {
            prompt: `Define الندبة, and what may be attached to its منادى؟`,
            kind: 'mcq',
            options: ['نداء expressing grief; its منادى may take ألف الندبة at its end, and هاء السكت after that ألف when pausing', 'نداء calling for help against an enemy; its منادى takes لام الاستغاثة', 'A form of الترخيم exclusive to أعلام ending in تاء', 'A silent form of نداء with no particle at all'],
            correct: 0,
          },
        },
        {
          heading: 'حذف عامل الحال: أربعة مواضع قياسية',
          lines: [
            { html: `Deletion of the عامل of الحال is obligatory by rule (قِيَاسًا وُجُوبًا) in four places:`, list: false },
            { table: { headers: ['#', 'Place', 'Example'], rows: [
              ['1', 'الحال stands in for the خبر', 'دُعَائِي رَبِّي مُسْتَيْقِنًا'],
              ['2', 'الحال indicates gradual increase or decrease', 'تَصَدَّقْ بِدِرْهَمٍ فَصَاعِدًا'],
              ['3', 'preceded by an استفهام of توبيخ', 'أَقَاعِدًا وَقَدْ أُقِيمَتِ الصَّلَاةُ؟'],
              ['4', 'الحال confirms the content of the sentence', '﴿وَهُوَ الْحَقُّ مُصَدِّقًا لِمَا مَعَهُمْ﴾'],
            ] } },
            { html: `سماعي examples also occur, like هَنِيئًا لَكَ and سَالِمًا غَانِمًا.`, list: false },
          ],
          exercise: {
            prompt: `In which four places is deletion of the عامل of الحال obligatory by rule (قياسا وجوبا)؟`,
            kind: 'mcq',
            options: ['الحال سادة مسد الخبر, الحال للتدرج, بعد استفهام التوبيخ, والحال المؤكدة لمضمون الجملة', 'التحذير, الإغراء, الاختصاص, الاشتغال', 'مضاف, شبيه بالمضاف, غير معين, ونكرة مقصودة', 'قبل القسم, بعد أنْ المصدرية, مع الواو بعد نفي, وقبل الاستفهام'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'الترخيم is defined as:', options: ['حذف آخر المنادى تخفيفا (deleting the end of المنادى for lightness)', 'حذف حرف النداء تخفيفا (deleting the particle of النداء for lightness)', 'حذف المستغاث له بالكامل (deleting المستغاث له entirely)', 'إثبات آخر المنادى ساكنا دائما (always keeping the end of المنادى quiescent)'], correct: 0 },
        { q: 'يَا حَارِ (for حارث) illustrates one of the two permitted vowelings on a مرخَّم’s end, namely:', options: ['keeping the original vowel it had before truncation', 'the ضمة', 'the تنوين', 'the سكون always'], correct: 0 },
        { q: 'اللَّهُمَّ before إِلَّا signals:', options: ['ندرة المستثنى', 'تيقن المجيب', 'التعجب', 'الندبة'], correct: 0 },
        { q: 'الاستغاثة’s particle is:', options: ['يا only', 'أيا only', 'وا only', 'any of the seven حروف النداء'], correct: 0 },
        { q: 'الندبة is defined as a type of نداء that expresses:', options: ['إظهار الحزن (grief)', 'الترغيب (encouragement)', 'التحذير (warning)', 'الاستفهام (a question)'], correct: 0 },
        { q: 'Deletion of عامل الحال is obligatory by rule when الحال:', options: ['stands in for the خبر', 'is a حال مؤكدة for something not yet mentioned', 'follows a فعل أمر', 'is مجرور by a حرف جر'], correct: 0 },
      ],
      bank: [
        { title: 'ترخيم عائشة', kind: 'mcq', prompt: 'يَا عَائِشَ (for عائشة) illustrates الترخيم applied to a noun ending in:', options: ['التاء', 'الألف', 'الياء', 'الواو'], correct: 0 },
        { title: 'ما لا يجوز ترخيمه', kind: 'mcq', prompt: 'Why can زَيْنَب not undergo الترخيم the way جعفر can?', options: ['الترخيم of a masculine علم requires more than three letters and no compounding, conditions زينب doesn’t meet the same way', 'الترخيم is banned for all female names outright', 'زينب already ends in a تاء, which blocks it', 'الترخيم only applies to الأسماء الموصولة'], correct: 0 },
        { title: 'اللهم قبل نعم', kind: 'mcq', prompt: 'اللَّهُمَّ نَعَمْ illustrates اللهم signaling:', options: ['the responder’s تيقن (certainty) of the answer', 'the rarity (ندرة) of a مستثنى', 'grief (الحزن)', 'a request for aid (استغاثة)'], correct: 0 },
        { title: 'حرف الاستغاثة الوحيد', kind: 'mcq', prompt: 'The particle used for الاستغاثة is:', options: ['يا, and no other حرف نداء', 'أي, and no other حرف نداء', 'وا, and no other حرف نداء', 'any of the seven حروف النداء equally'], correct: 0 },
        { title: 'يا للّه: لام المستغاث', kind: 'mcq', prompt: 'يَا لَلَّهِ shows the لام attached to المستغاث with:', options: ['فتحة', 'كسرة', 'ضمة', 'سكون'], correct: 0 },
        { title: 'الألف بدل اللام', kind: 'mcq', prompt: 'يَا زَيْدَا shows what substituting for the لام of المستغاث؟', options: ['An ألف at its end', 'A هاء السكت', 'A ياء', 'Nothing — the لام is simply dropped with no substitute'], correct: 0 },
        { title: 'لام المستغاث الثاني', kind: 'mcq', prompt: 'يَا لَلْأَمِيرِ وَلِلْمُسْلِمِينَ لِلْمَظْلُومِينَ shows the لام of a second, conjoined مستغاث taking:', options: ['كسرة', 'فتحة', 'ضمة', 'سكون'], correct: 0 },
        { title: 'نداء التعجب كالاستغاثة', kind: 'mcq', prompt: 'يَا لَلْقُرْآنِ illustrates نداء التعجب treating المتعجب منه like:', options: ['المستغاث', 'المستغاث له, with المستغاث stated', 'المحذَّر منه', 'المشغول عنه'], correct: 0 },
        { title: 'الندبة بيا', kind: 'mcq', prompt: 'الندبة may be expressed with يا instead of وا when:', options: ['confusion with plain نداء is not feared', 'the منادى is لفظ الجلالة', 'the منادى undergoes الترخيم', 'never — الندبة is always with وا'], correct: 0 },
        { title: 'ألف الندبة وهاء السكت', kind: 'mcq', prompt: 'وَا رَأْسَاهْ shows الندبة’s منادى taking:', options: ['ألف الندبة followed by هاء السكت when pausing', 'لام الاستغاثة', 'ياء المتكلم', 'الترخيم, dropping its final letter'], correct: 0 },
        { title: 'الحال سادة مسد الخبر', kind: 'mcq', prompt: 'دُعَائِي رَبِّي مُسْتَيْقِنًا shows مستيقنا منصوب because it is:', options: ['a حال سادة مسد الخبر, with its عامل obligatorily deleted', 'a حال مؤكدة لمضمون الجملة', 'a تمييز, not a حال at all', 'a حال preceded by استفهام التوبيخ'], correct: 0 },
        { title: 'الحال للتدرج', kind: 'mcq', prompt: 'تَصَدَّقْ بِدِرْهَمٍ فَصَاعِدًا shows فصاعدا منصوب because it indicates:', options: ['gradual increase (زيادة بتدريج)', 'confirmation of the sentence’s content', 'a استفهام توبيخ', 'a سماعي case with no rule behind it'], correct: 0 },
        { title: 'الحال بعد استفهام التوبيخ', kind: 'mcq', prompt: 'أَقَاعِدًا وَقَدْ أُقِيمَتِ الصَّلَاةُ؟ shows قاعدا منصوب because it follows:', options: ['an استفهام intended as توبيخ', 'a حرف تحضيض', 'a حرف عرض', 'a حرف تنبيه'], correct: 0 },
        { title: 'الحال المؤكدة لمضمون الجملة', kind: 'mcq', prompt: '﴿وَهُوَ الْحَقُّ مُصَدِّقًا لِمَا مَعَهُمْ﴾ shows مصدقا منصوب because it is:', options: ['a حال مؤكدة لمضمون الجملة, with an obligatorily deleted عامل', 'a حال سادة مسد الخبر', 'a حال indicating تدرج', 'a مفعول به of a stated فعل'], correct: 0 },
        { title: 'أمثلة سماعية لحذف عامل الحال', kind: 'mcq', prompt: 'هَنِيئًا لَكَ and سَالِمًا غَانِمًا are examples of حذف عامل الحال that is:', options: ['سماعي, not extended by rule', 'قياسي, extended to any matching case', 'واحد من مواضع الاستغاثة', 'غير صحيح نحويا'], correct: 0 },
        {
          title: 'تركيب: يَا عَائِشَ',
          kind: 'tarkeeb',
          instruction: 'Can this منادى undergo الترخيم؟',
          sentence: 'يَا عَائِشَ',
          translation: 'O Aisha! (truncated from عائشة)',
          cells: ['يَا', 'عَائِشَ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'يجوز ترخيمه (منتهية بتاء)' }] },
          ],
          distractors: ['لا يجوز ترخيمه'],
        },
        {
          title: 'تركيب: يَا جَعْفَ',
          kind: 'tarkeeb',
          instruction: 'Can this منادى undergo الترخيم؟',
          sentence: 'يَا جَعْفَ',
          translation: 'O Ja’far! (truncated from جعفر)',
          cells: ['يَا', 'جَعْفَ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'يجوز ترخيمه (علم مذكر فوق ثلاثة أحرف)' }] },
          ],
          distractors: ['لا يجوز ترخيمه'],
        },
        {
          title: 'تركيب: يَا زَيْدُ',
          kind: 'tarkeeb',
          instruction: 'Can this منادى undergo الترخيم؟',
          sentence: 'يَا زَيْدُ',
          translation: 'O Zayd! (kept whole, unlike جعفر)',
          cells: ['يَا', 'زَيْدُ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'لا يجوز ترخيمه (ثلاثة أحرف فقط)' }] },
          ],
          distractors: ['يجوز ترخيمه'],
        },
        {
          title: 'تركيب: يَا لَلَّهِ لِلْمُسْلِمِينَ',
          kind: 'tarkeeb',
          instruction: 'Identify each ركن of الاستغاثة, then classify the whole example.',
          sentence: 'يَا لَلَّهِ لِلْمُسْلِمِينَ',
          translation: 'O Allah, [come to the aid] of the Muslims!',
          cells: ['يَا', 'لَلَّهِ', 'لِلْمُسْلِمِينَ'],
          rows: [
            { position: 'above', label: 'الأركان', labels: [
              { start: 0, end: 0, role: 'حرف الاستغاثة' },
              { start: 1, end: 1, role: 'المستغاث' },
              { start: 2, end: 2, role: 'المستغاث له' },
            ] },
            { position: 'below', label: 'النوع', labels: [{ start: 0, end: 2, role: 'الاستغاثة' }] },
          ],
          distractors: ['المستغيث', 'الترخيم'],
        },
        {
          title: 'تركيب: دُعَائِي رَبِّي مُسْتَيْقِنًا',
          kind: 'tarkeeb',
          instruction: 'Which قياسي موضع of حذف عامل الحال does this illustrate؟',
          sentence: 'دُعَائِي رَبِّي مُسْتَيْقِنًا',
          translation: 'My prayer to my Lord, [being] certain.',
          cells: ['دُعَائِي', 'رَبِّي', 'مُسْتَيْقِنًا'],
          rows: [
            { position: 'above', labels: [{ start: 2, end: 2, role: 'سادة مسد الخبر' }] },
          ],
          distractors: ['للتدرج', 'بعد استفهام التوبيخ', 'مؤكدة لمضمون الجملة'],
        },
        {
          title: 'تركيب: تَصَدَّقْ بِدِرْهَمٍ فَصَاعِدًا',
          kind: 'tarkeeb',
          instruction: 'Which قياسي موضع of حذف عامل الحال does this illustrate؟',
          sentence: 'تَصَدَّقْ بِدِرْهَمٍ فَصَاعِدًا',
          translation: 'Give charity of a dirham or more.',
          cells: ['تَصَدَّقْ', 'بِدِرْهَمٍ', 'فَصَاعِدًا'],
          rows: [
            { position: 'above', labels: [{ start: 2, end: 2, role: 'للتدرج' }] },
          ],
          distractors: ['سادة مسد الخبر', 'بعد استفهام التوبيخ', 'مؤكدة لمضمون الجملة'],
        },
        {
          title: 'تركيب: أَقَاعِدًا وَقَدْ أُقِيمَتِ الصَّلَاةُ؟',
          kind: 'tarkeeb',
          instruction: 'Which قياسي موضع of حذف عامل الحال does this illustrate؟',
          sentence: 'أَقَاعِدًا وَقَدْ أُقِيمَتِ الصَّلَاةُ؟',
          translation: 'Sitting, while the prayer has been called?!',
          cells: ['أَقَاعِدًا', 'وَقَدْ', 'أُقِيمَتِ', 'الصَّلَاةُ'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 0, role: 'بعد استفهام التوبيخ' }] },
          ],
          distractors: ['سادة مسد الخبر', 'للتدرج', 'مؤكدة لمضمون الجملة'],
        },
        {
          title: 'تركيب: ﴿وَهُوَ الْحَقُّ مُصَدِّقًا لِمَا مَعَهُمْ﴾',
          kind: 'tarkeeb',
          instruction: 'Which قياسي موضع of حذف عامل الحال does this illustrate؟',
          sentence: 'وَهُوَ الْحَقُّ مُصَدِّقًا لِمَا مَعَهُمْ',
          translation: 'And it is the truth, confirming what is with them.',
          cells: ['وَهُوَ', 'الْحَقُّ', 'مُصَدِّقًا', 'لِمَا', 'مَعَهُمْ'],
          rows: [
            { position: 'above', labels: [{ start: 2, end: 2, role: 'مؤكدة لمضمون الجملة' }] },
          ],
          distractors: ['سادة مسد الخبر', 'للتدرج', 'بعد استفهام التوبيخ'],
        },
        {
          title: 'تركيب: يَا فَاطِمَ',
          kind: 'tarkeeb',
          instruction: 'Classify this example.',
          sentence: 'يَا فَاطِمَ',
          translation: 'O Fatima! (truncated from فاطمة)',
          cells: ['يَا', 'فَاطِمَ'],
          rows: [
            { position: 'above', labels: [{ start: 1, end: 1, role: 'الترخيم' }] },
          ],
          distractors: ['الاستغاثة', 'الندبة'],
        },
        {
          title: 'تركيب: وَا زَيْدَا',
          kind: 'tarkeeb',
          instruction: 'Classify this example.',
          sentence: 'وَا زَيْدَا',
          translation: 'Alas, Zayd!',
          cells: ['وَا', 'زَيْدَا'],
          rows: [
            { position: 'above', labels: [{ start: 0, end: 1, role: 'الندبة' }] },
          ],
          distractors: ['الاستغاثة', 'الترخيم'],
        },
      ],
    },
  ],
};
