// Module 06 — النواصب والجوازم (Subjunctive- and Jussive-Forcing Letters)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__2 الْحَرْفِ__1 الْحَرْفِ الْعَامِلِ__3 الحرف العامل الى الفعل.apkg,
// 28 notes) prepared for this conversion. Definitions and examples are kept
// faithful to the source notes. Concept bodies are short by design (a
// sentence or two, not teaching prose); quiz/bank question text is English
// with Arabic grammatical terms left in Arabic. This is a noticeably
// smaller source deck than Modules 04–05 (28 notes vs. 62–129), so it
// naturally divides into 3 lessons rather than 4–6 — the topic itself
// (عامل حروف that reach into الفعل, not الاسم) is simply narrower.
//
// The source deck covers الحرف العامل الى الفعل (§3 of الحرف العامل, itself
// §2 of الحرف, itself §2 of العامل وغير العامل): the four نواصب المضارع
// (أنْ، كي، لن، إذن) with the rules for إضمار أنْ, and جوازم المضارع — the
// four جازمة لفعل واحد (لم، لما، لام الأمر، لا الناهية) and the two جازمة
// لفعلين (إنْ، إذما) governing a شرط + جواب.

export default {
  id: '06',
  title: 'النواصب والجوازم',
  heading: 'العامل وغير العامل',
  subheading: 'الحرف العامل',
  blurb: 'The عامل حروف that reach into الفعل rather than الاسم: the four نواصب المضارع (أنْ، كي، لن، إذن) with the rules for إضمار أنْ, and the جوازم — لم ولما ولام الأمر ولا الناهية, plus إنْ وإذما governing a شرط + جواب pair.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'نواصب المضارع: تمهيد، أنْ، وكي',
      subtitle: 'Subjunctive Particles — the two categories of حروف تعمل في الفعل, أنْ الناصبة, and كي',
      concepts: [
        {
          heading: 'حروف تعمل في الفعل: نواصب وجوازم',
          body: `<bdi>حُرُوف</bdi> operating on the <bdi>فِعْل</bdi> (specifically the مضارع) split into two categories: (1) حروف putting المضارع in <bdi>نَصْب</bdi> — the <bdi>نَوَاصِب</bdi> (2) حروف putting المضارع in <bdi>جَزْم</bdi> — the <bdi>جَوَازِم</bdi>. Four حروف make up the نواصب: <bdi>أَنْ، كَيْ، لَنْ، إِذَنْ</bdi>.`,
          sample: `نواصب — تنصب المضارع<br>جوازم — تجزم المضارع<br>النواصب الأربعة — أنْ، كي، لن، إذن`,
          exercise: {
            prompt: `What are the two categories of حروف operating on the فعل؟`,
            kind: 'mcq',
            options: ['حروف تنصب المضارع (نواصب), and حروف تجزم المضارع (جوازم)', 'حروف تنصب الاسم, and حروف تجره', 'حروف تعمل في الماضي فقط, and حروف تعمل في الأمر فقط', 'حروف زائدة, and حروف أصلية'],
            correct: 0,
          },
        },
        {
          heading: 'أنْ الناصبة (المصدرية)',
          body: `<bdi>أَنْ الناصبة</bdi> is a <bdi>حَرْفُ مَصْدَر</bdi>, as in <bdi>﴿أَلَا تُحِبُّونَ أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾</bdi>. After a فعل قلب, it must be told apart from أنْ المخففة (the lightened form of أنّ, covered last module): after a فعل of <b>certainty</b> (يقين) it is مخففة, as in <bdi>﴿عَلِمَ أَنْ سَيَكُونُ مِنْكُمْ مَرْضَىٰ﴾</bdi>; after a فعل of <b>supposition</b> (ظن) both readings are possible, as in <bdi>﴿وَحَسِبُوا أَلَّا تَكُونَ فِتْنَةٌ﴾</bdi>; when there is no فعل قلب at all, it is مصدرية, as in <bdi>﴿نَطْمَعُ أَنْ يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا﴾</bdi>.`,
          sample: `أنْ الناصبة — حرف مصدر: ﴿ألا تحبون أن يغفر الله لكم﴾<br>بعد فعل يقين — أنْ مخففة: ﴿علم أن سيكون منكم مرضى﴾<br>بعد فعل ظن — كلا الوجهين: ﴿وحسبوا ألا تكون فتنة﴾<br>بلا فعل قلب — أنْ مصدرية: ﴿نطمع أن يغفر لنا ربنا خطايانا﴾`,
          exercise: {
            prompt: `How do you distinguish أنْ الناصبة (المصدرية) from أنْ المخففة after a فعل قلب؟`,
            kind: 'mcq',
            options: ['After a فعل يقين it is مخففة; after a فعل ظن both are possible; with no فعل قلب it is مصدرية', 'أنْ is always مصدرية, regardless of what precedes it', 'أنْ is always مخففة whenever a فعل قلب precedes it, with no exception', 'The distinction only matters in poetry, never in the Qurʾān'],
            correct: 0,
          },
        },
        {
          heading: 'كي',
          body: `<bdi>كَيْ</bdi> is a <bdi>حَرْفُ مَصْدَرٍ لِلتَّعْلِيل</bdi> (purpose), as in <bdi>﴿فَرَجَعْنَاكَ إِلَىٰ أُمِّكَ كَيْ تَقَرَّ عَيْنُهَا﴾</bdi>. It is preceded by the <bdi>لَامُ الْجَرّ</bdi>, whether explicit — <bdi>﴿لِكَيْلَا يَعْلَمَ بَعْدَ عِلْمٍ شَيْئًا﴾</bdi> — or implied (<bdi>تُقَدَّر</bdi>), as in <bdi>﴿كَيْ تَقَرَّ عَيْنُهَا﴾</bdi> (i.e. <bdi>لِكَيْ</bdi>).`,
          sample: `كي — حرف مصدر للتعليل: ﴿فرجعناك إلى أمك كي تقر عينها﴾<br>لام الجر قبلها — صريحة: ﴿لكيلا يعلم بعد علم شيئا﴾؛ مقدرة: ﴿كي تقر عينها﴾ أي لكي`,
          exercise: {
            prompt: `What precedes كي؟`,
            kind: 'mcq',
            options: ['اللام الجارة, whether explicit or implied', 'واو القسم always', 'حرف تنبيه', 'Nothing ever precedes it'],
            correct: 0,
          },
        },
        {
          heading: 'لن',
          body: `<bdi>لَنْ</bdi> emphasises the <bdi>نَفْي</bdi> of the <b>future</b>, as in <bdi>﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾</bdi>. It only indicates <bdi>التَّأْبِيد</bdi> (perpetuity) when contextual evidence (<bdi>قَرِينَة</bdi>) supports that, as in <bdi>﴿لَنْ يَخْلُقُوا ذُبَابًا﴾</bdi> — لن on its own does not mean "never."`,
          sample: `لن — تأكيد نفي المستقبل: ﴿فلن أكلم اليوم إنسيا﴾<br>التأبيد — بقرينة فقط: ﴿لن يخلقوا ذبابا﴾، لا من لن نفسها`,
          exercise: {
            prompt: `Does لن by itself imply eternity (that something will NEVER happen)؟`,
            kind: 'mcq',
            options: ['No — it emphasises negation of the future; تأبيد only comes from contextual قرينة', 'Yes, لن always and only means eternal negation', 'No, لن only ever negates the past', "Yes, but only when it precedes a فعل أمر"],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many نواصب المضارع are there؟',
          options: ['أربعة', 'ثلاثة', 'خمسة', 'اثنان'],
          correct: 0,
        },
        {
          q: 'List the four نواصب المضارع.',
          options: ['أنْ، كي، لن، إذن', 'لم، لما، لا، لام الأمر', 'إنْ، إذما، لو، لولا', 'هل، ما، لا، أم'],
          correct: 0,
        },
        {
          q: '﴿نَطْمَعُ أَنْ يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا﴾ — أنْ here, with no فعل قلب preceding it, is:',
          options: ['مصدرية', 'مخففة من أنّ', 'زائدة', 'شرطية'],
          correct: 0,
        },
        {
          q: 'كي carries the meaning of:',
          options: ['التعليل (purpose)', 'التوقع', 'الاستدراك', 'التمني'],
          correct: 0,
        },
        {
          q: '﴿لِكَيْلَا يَعْلَمَ بَعْدَ عِلْمٍ شَيْئًا﴾ shows كي preceded by an explicit:',
          options: ['لام الجر', 'لام الأمر', 'لام القسم', 'لام الابتداء'],
          correct: 0,
        },
        {
          q: '﴿لَنْ يَخْلُقُوا ذُبَابًا﴾ carries a sense of تأبيد (perpetuity) because of:',
          options: ['a contextual قرينة, not لن itself', 'لن always meaning perpetual negation', 'the فعل خلق being جامد', 'the plural فاعل واو الجماعة'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'نواصب أم جوازم؟',
          kind: 'mcq',
          prompt: 'حروف that put المضارع in نصب are called:',
          options: ['النواصب', 'الجوازم', 'العوامل الجازمة', 'حروف العطف'],
          correct: 0,
        },
        {
          title: 'جوازم أم نواصب؟',
          kind: 'mcq',
          prompt: 'حروف that put المضارع in جزم are called:',
          options: ['الجوازم', 'النواصب', 'حروف التوكيد', 'حروف الاستثناء'],
          correct: 0,
        },
        {
          title: 'أنْ حرف مصدر',
          kind: 'mcq',
          prompt: '﴿أَلَا تُحِبُّونَ أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾ — أنْ here is:',
          options: ['حرف مصدر (الناصبة)', 'حرف نفي', 'حرف جواب', 'حرف تنبيه'],
          correct: 0,
        },
        {
          title: 'أنْ بعد فعل يقين',
          kind: 'mcq',
          prompt: '﴿عَلِمَ أَنْ سَيَكُونُ مِنْكُمْ مَرْضَىٰ﴾ — أنْ here, after a فعل يقين, is:',
          options: ['مخففة من أنّ', 'مصدرية ناصبة', 'زائدة', 'شرطية جازمة'],
          correct: 0,
        },
        {
          title: 'أنْ بعد فعل ظن',
          kind: 'mcq',
          prompt: '﴿وَحَسِبُوا أَلَّا تَكُونَ فِتْنَةٌ﴾ — after this فعل ظن, أنْ can be read as:',
          options: ['both مخففة and مصدرية', 'مخففة only, never مصدرية', 'مصدرية only, never مخففة', 'neither reading is valid here'],
          correct: 0,
        },
        {
          title: 'كي للتعليل',
          kind: 'mcq',
          prompt: "﴿فَرَجَعْنَاكَ إِلَىٰ أُمِّكَ كَيْ تَقَرَّ عَيْنُهَا﴾ illustrates كي's meaning of:",
          options: ['التعليل (purpose)', 'التوقع', 'الاستدراك', 'التمني'],
          correct: 0,
        },
        {
          title: 'لام مقدرة قبل كي',
          kind: 'mcq',
          prompt: 'In ﴿كَيْ تَقَرَّ عَيْنُهَا﴾, the لام before كي is:',
          options: ['implied (مقدرة), i.e. لكي', 'explicit and written out', 'impossible — لام never precedes كي', 'a لام القسم'],
          correct: 0,
        },
        {
          title: 'لن ونفي المستقبل',
          kind: 'mcq',
          prompt: '﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾ illustrates لن:',
          options: ['emphasising negation of the future', 'negating the past', 'negating a command', 'expressing hope'],
          correct: 0,
        },
        {
          title: 'لن والتأبيد',
          kind: 'mcq',
          prompt: 'لن indicates تأبيد (perpetuity) only when:',
          options: ['a contextual قرينة supports that reading', 'it is repeated twice in a row', 'it precedes a فعل أمر', 'it is followed by لا الزائدة'],
          correct: 0,
        },
        {
          title: 'عدد النواصب',
          kind: 'mcq',
          prompt: 'How many نواصب المضارع are there in total؟',
          options: ['أربعة', 'ثلاثة', 'خمسة', 'ستة'],
          correct: 0,
        },
        {
          title: 'أنْ الناصبة تنصب',
          kind: 'mcq',
          prompt: 'أنْ الناصبة puts the مضارع in:',
          options: ['نصب', 'جزم', 'رفع', 'جر'],
          correct: 0,
        },
        {
          title: 'الفعل بعد لا يقين ولا ظن',
          kind: 'mcq',
          prompt: 'When no فعل قلب at all precedes أنْ, it is read as:',
          options: ['مصدرية', 'مخففة من أنّ', 'زائدة بلا معنى', 'نافية'],
          correct: 0,
        },
        {
          title: 'كي بلا لام',
          kind: 'mcq',
          prompt: 'Can كي occur with the لام before it only implied, not written?',
          options: ['Yes, as in ﴿كَيْ تَقَرَّ عَيْنُهَا﴾', 'No, the لام must always be written out', 'No, كي never takes a لام at all', 'Yes, but only in poetry'],
          correct: 0,
        },
        {
          title: 'تركيب: تصنيف النواصب الأربعة',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف by its core meaning/function.',
          source: 'أنْ / كي / لن / إذن',
          words: ['أنْ', 'كي', 'لن', 'إذن'],
          labels: ['حرف مصدر', 'حرف تعليل', 'تأكيد نفي المستقبل', 'حرف جواب'],
          distractors: ['حرف جزم'],
        },
        {
          title: 'تركيب: أنْ بعد أفعال القلوب',
          kind: 'tarkeeb',
          instruction: 'Classify how أنْ is read after each type of فعل.',
          source: '﴿علم أن سيكون منكم مرضى﴾ / ﴿وحسبوا ألا تكون فتنة﴾ / ﴿نطمع أن يغفر لنا ربنا خطايانا﴾',
          words: ['بعد علم (يقين)', 'بعد حسبوا (ظن)', 'بلا فعل قلب'],
          labels: ['مخففة من أنّ', 'كلا الوجهين', 'مصدرية'],
          distractors: ['زائدة'],
        },
        {
          title: 'تركيب: نواصب المضارع أم لا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف: من نواصب المضارع أم لا؟',
          source: 'أنْ / لم / كي / هل',
          words: ['أنْ', 'لم', 'كي', 'هل'],
          labels: ['من النواصب', 'ليست من النواصب', 'من النواصب', 'ليست من النواصب'],
          distractors: ['من الجوازم'],
        },
        {
          title: 'تركيب: معاني كي ولن',
          kind: 'tarkeeb',
          instruction: 'Match each حرف to what it does.',
          source: 'كي / لن',
          words: ['كي', 'لن'],
          labels: ['حرف مصدر للتعليل', 'تأكيد نفي المستقبل'],
          distractors: ['حرف جواب بثلاثة شروط'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'إذن، وإضمار أنْ',
      subtitle: "Iḏan, and Hidden أنْ — إذن's three conditions, and where أنْ is implied جوازا or وجوبا",
      concepts: [
        {
          heading: 'إذن: تعريفها وشروطها',
          body: `<bdi>إِذَنْ</bdi> is the حرف of response (<bdi>لِلْجَوَاب</bdi>), as in <bdi>إِذَنْ تَدْخُلَ الْجَنَّةَ</bdi> (said to one who says <bdi>أُطِيعُ اللَّهَ</bdi>). It operates on three conditions: (1) it stands at <bdi>صَدْرُ الْكَلَام</bdi> (2) a future-tense فعل follows it (3) nothing separates it from the فعل — except a <bdi>قَسَم</bdi>, as in <bdi>إِذَنْ وَاللَّهِ أُكْرِمَكَ</bdi>. After a <bdi>وَاو</bdi> or <bdi>فَاء</bdi>, both عمل and إهمال are allowed, with إهمال predominant, as in <bdi>﴿فَإِذًا لَا يُؤْتُونَ النَّاسَ نَقِيرًا﴾</bdi>. In the muṣḥaf it is written with an <bdi>أَلِف</bdi>: <bdi>﴿فَإِذًا﴾</bdi>.`,
          sample: `إذن — حرف جواب: إذن تدخل الجنة<br>شروطها الثلاثة — صدر الكلام، فعل مستقبل بعدها، عدم الفصل إلا بقسم<br>بعد واو/فاء — الإهمال هو الغالب: ﴿فإذا لا يؤتون الناس نقيرا﴾<br>رسمها في المصحف — بألف: فإذا`,
          exercise: {
            prompt: `What are the three conditions for إذن to operate؟`,
            kind: 'mcq',
            options: ["It stands at صدر الكلام, a future فعل follows it, and nothing separates it from that فعل except a قسم", 'It must always be preceded by واو or فاء', 'It must always be followed by a فعل ماضٍ', 'It must be repeated twice in the same جملة'],
            correct: 0,
          },
        },
        {
          heading: 'إضمار أنْ جوازا',
          body: `أنْ is implied optionally (<bdi>جَوَازًا</bdi>) in two places: (1) after the <bdi>لَامُ الْجَرّ</bdi>, so long as it is not joined with <bdi>لَا النَّافِيَة</bdi> — as in <bdi>﴿لِيَغْفِرَ لَكَ اللَّهُ﴾</bdi>, but NOT after <bdi>لِئَلَّا</bdi>, where أن must appear explicitly, as in <bdi>﴿لِئَلَّا يَكُونَ لِلنَّاسِ عَلَيْكُمْ حُجَّةٌ﴾</bdi> (2) after a <bdi>حَرْفُ عَطْف</bdi> preceded by an explicit (<bdi>غَيْرُ مُؤَوَّل</bdi>) اسم, as in <bdi>﴿وَمَا كَانَ لِبَشَرٍ أَنْ يُكَلِّمَهُ اللَّهُ إِلَّا وَحْيًا أَوْ مِنْ وَرَاءِ حِجَابٍ أَوْ يُرْسِلَ رَسُولًا﴾</bdi>.`,
          sample: `إضمار أنْ جوازا (٢) — بعد لام الجر غير المقترنة بلا: ﴿ليغفر لك الله﴾؛ بعد حرف عطف مسبوق باسم غير مؤول: ﴿وما كان لبشر...أو يرسل رسولا﴾<br>استثناء — بعد لئلا يجب ذكر أن: ﴿لئلا يكون للناس عليكم حجة﴾`,
          exercise: {
            prompt: `Where is أنْ implied OPTIONALLY (جوازا)؟`,
            kind: 'mcq',
            options: ['After لام الجر not joined with لا النافية, and after a حرف عطف preceded by an explicit اسم', 'Only ever after حتى', 'Only ever after واو الصرف', 'It is never implied optionally — always either obligatory or forbidden'],
            correct: 0,
          },
        },
        {
          heading: 'إضمار أنْ وجوبا',
          body: `أنْ is implied OBLIGATORILY (<bdi>وُجُوبًا</bdi>) in five places: (1) after <bdi>حَتَّى</bdi>, as in <bdi>﴿لَنْ تَنَالُوا الْبِرَّ حَتَّىٰ تُنْفِقُوا مِمَّا تُحِبُّونَ﴾</bdi> (2) after <bdi>لَامُ الْجُحُود</bdi>, as in <bdi>﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾</bdi> (3) after <bdi>أَوْ</bdi> meaning <bdi>إِلَىٰ أَنْ</bdi> or <bdi>إِلَّا أَنْ</bdi> (4) after <bdi>وَاوُ الصَّرْف</bdi> (المعية) preceded by نفي or a verbal request (5) after <bdi>فَاءُ السَّبَبِيَّة</bdi> preceded by نفي or a verbal request.`,
          sample: `إضمار أنْ وجوبا (٥) — بعد حتى: ﴿لن تنالوا البر حتى تنفقوا مما تحبون﴾<br>بعد لام الجحود: ﴿وما كان الله ليضيع إيمانكم﴾<br>بعد أو (إلى أن/إلا أن)، بعد واو الصرف (بعد نفي أو طلب)، بعد فاء السببية (بعد نفي أو طلب)`,
          exercise: {
            prompt: `After how many things is أنْ implied OBLIGATORILY before a مضارع منصوب؟`,
            kind: 'mcq',
            options: ['خمسة', 'ثلاثة', 'سبعة', 'اثنان'],
            correct: 0,
          },
        },
        {
          heading: 'أو (إلى أن / إلا أن)، وواو الصرف',
          body: `<bdi>أَوْ</bdi> before a مضارع منصوب carries one of two meanings: <b>إلى أن</b>, as in <bdi>لَأَسْتَسْهِلَنَّ الصَّعْبَ أَوْ أُدْرِكَ الْمُنَى</bdi>, or <b>إلا أن</b>, as in <bdi>كَسَرْتُ كُعُوبَهَا أَوْ تَسْتَقِيمَا</bdi>. <bdi>وَاوُ الصَّرْف</bdi> (المعية) is the واو that, with an implied أن, puts the فعل in نصب; it must be preceded by <b>نفي</b>, as in <bdi>﴿وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ جَاهَدُوا مِنْكُمْ وَيَعْلَمَ الصَّابِرِينَ﴾</bdi>, or by a <b>verbal request</b>, as in <bdi>﴿يَا لَيْتَنَا نُرَدُّ وَلَا نُكَذِّبَ بِآيَاتِ رَبِّنَا وَنَكُونَ مِنَ الْمُؤْمِنِينَ﴾</bdi>.`,
          sample: `أو (إلى أن) — لأستسهلن الصعب أو أدرك المنى<br>أو (إلا أن) — كسرت كعوبها أو تستقيما<br>واو الصرف بعد نفي — ﴿ولما يعلم الله الذين جاهدوا منكم ويعلم الصابرين﴾<br>واو الصرف بعد طلب — ﴿يا ليتنا نرد ولا نكذب بآيات ربنا ونكون من المؤمنين﴾`,
          exercise: {
            prompt: `What must precede واو الصرف (المعية) for it to put the following فعل in نصب؟`,
            kind: 'mcq',
            options: ['نفي or a verbal request', 'a فعل أمر only', 'a حرف جر only', 'Nothing — it always operates regardless of context'],
            correct: 0,
          },
        },
        {
          heading: 'فاء السببية، وأمثلة سماعية',
          body: `Like واو الصرف, <bdi>فَاءُ السَّبَبِيَّة</bdi> licenses نصب on the following فعل when preceded by <bdi>نَفْي</bdi> or a verbal request — <bdi>الْأَمْر، النَّهْي، الِاسْتِفْهَام، التَّمَنِّي، التَّرَجِّي، الْعَرْض،</bdi> or <bdi>التَّحْضِيض</bdi>, as in <bdi>أَسْلِمْ فَتَدْخُلَ الْجَنَّةَ</bdi>. Separately, a handful of نصب-by-implied-أنْ examples are <bdi>سَمَاعِيّ</bdi> — heard but not extended by analogy — such as <bdi>مُرْهُ يَحْفِرَهَا</bdi> and <bdi>خُذِ اللِّصَّ قَبْلَ يَأْخُذَكَ</bdi>.`,
          sample: `فاء السببية بعد طلب — أسلم فتدخل الجنة<br>أنواع الطلب المرخصة — الأمر، النهي، الاستفهام، التمني، الترجي، العرض، التحضيض (وأيضا النفي)<br>سماعي لا قياسي — مره يحفرها؛ خذ اللص قبل يأخذك`,
          exercise: {
            prompt: `List the request-types that license نصب after فاء السببية.`,
            kind: 'mcq',
            options: ['الأمر، النهي، الاستفهام، التمني، الترجي، العرض، والتحضيض (plus نفي)', 'الأمر والنهي فقط, nothing else', 'Only الاستفهام licenses it', 'None — فاء السببية never licenses نصب'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'إذن is the حرف of:',
          options: ['الجواب (response)', 'الشرط', 'الاستثناء', 'التعليل'],
          correct: 0,
        },
        {
          q: 'How is إذن written in the muṣḥaf?',
          options: ['With an alif: فإذا', 'Exactly as إذن', 'With a تنوين only', "It never appears in the muṣḥaf"],
          correct: 0,
        },
        {
          q: '﴿لِئَلَّا يَكُونَ لِلنَّاسِ عَلَيْكُمْ حُجَّةٌ﴾ — here أن must:',
          options: ['appear explicitly, not be implied', 'be implied, never written', 'be dropped along with لا', 'convert into أنّ المشددة'],
          correct: 0,
        },
        {
          q: '﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾ shows أنْ implied obligatorily after:',
          options: ['لام الجحود', 'حتى', 'أو', 'فاء السببية'],
          correct: 0,
        },
        {
          q: 'كَسَرْتُ كُعُوبَهَا أَوْ تَسْتَقِيمَا — أو here means:',
          options: ['إلا أن', 'إلى أن', 'إذ ذاك', 'حتى أن'],
          correct: 0,
        },
        {
          q: 'مُرْهُ يَحْفِرَهَا, with implied أنْ, is an example that is:',
          options: ['سماعي, not extended by analogy', 'قياسي, freely extendable', 'شرطية، تفيد الجزم', 'من مواضع الوجوب الخمسة'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'شروط إذن الثلاثة',
          kind: 'mcq',
          prompt: 'إذن operates on three conditions. One of them is that:',
          options: ['it stands at صدر الكلام', 'it must be preceded by واو', 'it must be followed by فعل ماضٍ', 'nothing may ever separate it from anything'],
          correct: 0,
        },
        {
          title: 'الفصل بقسم',
          kind: 'mcq',
          prompt: 'إِذَنْ وَاللَّهِ أُكْرِمَكَ shows إذن separated from its فعل by:',
          options: ['a قسم', 'a نفي حرف', 'a حرف جر', 'a ضمير منفصل'],
          correct: 0,
        },
        {
          title: 'إذن بعد فاء',
          kind: 'mcq',
          prompt: '﴿فَإِذًا لَا يُؤْتُونَ النَّاسَ نَقِيرًا﴾ — after الفاء, إذن here shows:',
          options: ['الإهمال (the predominant option after و/ف)', 'الإعمال only', 'both are equally rare', 'إذن cannot follow فاء at all'],
          correct: 0,
        },
        {
          title: 'إضمار أنْ جوازا: لام الجر',
          kind: 'mcq',
          prompt: '﴿لِيَغْفِرَ لَكَ اللَّهُ﴾ shows أنْ implied:',
          options: ['جوازا, after لام الجر', 'وجوبا, after حتى', 'وجوبا, after لام الجحود', 'جوازا, after فاء السببية'],
          correct: 0,
        },
        {
          title: 'إضمار أنْ جوازا: بعد عطف',
          kind: 'mcq',
          prompt: '﴿وَمَا كَانَ لِبَشَرٍ أَنْ يُكَلِّمَهُ اللَّهُ إِلَّا وَحْيًا أَوْ مِنْ وَرَاءِ حِجَابٍ أَوْ يُرْسِلَ رَسُولًا﴾ shows أنْ implied جوازا after a حرف عطف preceded by:',
          options: ['an explicit (غير مؤول) اسم', 'a فعل أمر', 'a حرف نفي', 'a قسم'],
          correct: 0,
        },
        {
          title: 'إضمار أنْ وجوبا: حتى',
          kind: 'mcq',
          prompt: '﴿لَنْ تَنَالُوا الْبِرَّ حَتَّىٰ تُنْفِقُوا مِمَّا تُحِبُّونَ﴾ shows أنْ implied وجوبا after:',
          options: ['حتى', 'لام الجحود', 'أو', 'واو الصرف'],
          correct: 0,
        },
        {
          title: 'إضمار أنْ وجوبا: لام الجحود',
          kind: 'mcq',
          prompt: '﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾ shows أنْ implied وجوبا after:',
          options: ['لام الجحود', 'حتى', 'فاء السببية', 'أو'],
          correct: 0,
        },
        {
          title: 'أو بمعنى إلى أن',
          kind: 'mcq',
          prompt: 'لَأَسْتَسْهِلَنَّ الصَّعْبَ أَوْ أُدْرِكَ الْمُنَى — أو here means:',
          options: ['إلى أن', 'إلا أن', 'أم', 'ثم'],
          correct: 0,
        },
        {
          title: 'واو الصرف بعد نفي',
          kind: 'mcq',
          prompt: '﴿وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ جَاهَدُوا مِنْكُمْ وَيَعْلَمَ الصَّابِرِينَ﴾ shows واو الصرف preceded by:',
          options: ['نفي (لما)', 'طلب', 'قسم', 'استفهام'],
          correct: 0,
        },
        {
          title: 'واو الصرف بعد طلب',
          kind: 'mcq',
          prompt: '﴿يَا لَيْتَنَا نُرَدُّ وَلَا نُكَذِّبَ بِآيَاتِ رَبِّنَا وَنَكُونَ مِنَ الْمُؤْمِنِينَ﴾ shows واو الصرف preceded by which kind of طلب?',
          options: ['التمني (يا ليتنا)', 'الأمر', 'النهي', 'الاستفهام'],
          correct: 0,
        },
        {
          title: 'فاء السببية بعد أمر',
          kind: 'mcq',
          prompt: 'أَسْلِمْ فَتَدْخُلَ الْجَنَّةَ shows فاء السببية licensing نصب after:',
          options: ['الأمر', 'النهي', 'الاستفهام', 'العرض'],
          correct: 0,
        },
        {
          title: 'فاء السببية بعد نهي',
          kind: 'mcq',
          prompt: '﴿وَلَا تَطْغَوْا فِيهِ فَيَحِلَّ عَلَيْكُمْ غَضَبِي﴾ shows فاء السببية licensing نصب after:',
          options: ['النهي', 'الأمر', 'الترجي', 'التحضيض'],
          correct: 0,
        },
        {
          title: 'فاء السببية بعد استفهام',
          kind: 'mcq',
          prompt: '﴿مَنْ ذَا الَّذِي يُقْرِضُ اللَّهَ قَرْضًا حَسَنًا فَيُضَاعِفَهُ لَهُ﴾ shows فاء السببية licensing نصب after:',
          options: ['الاستفهام', 'الأمر', 'النهي', 'التمني'],
          correct: 0,
        },
        {
          title: 'مثال سماعي',
          kind: 'mcq',
          prompt: 'خُذِ اللِّصَّ قَبْلَ يَأْخُذَكَ, with implied أنْ, is:',
          options: ['سماعي, heard but not extended by analogy', 'قياسي, freely productive', 'a case of وجوب إضمار', 'invalid Arabic entirely'],
          correct: 0,
        },
        {
          title: 'عدد مواضع الوجوب',
          kind: 'mcq',
          prompt: 'How many مواضع require إضمار أنْ وجوبا؟',
          options: ['خمسة', 'اثنان', 'ثلاثة', 'سبعة'],
          correct: 0,
        },
        {
          title: 'عدد مواضع الجواز',
          kind: 'mcq',
          prompt: 'How many مواضع allow إضمار أنْ جوازا?',
          options: ['اثنان', 'خمسة', 'ثلاثة', 'واحد'],
          correct: 0,
        },
        {
          title: 'تركيب: إضمار أنْ جوازا أم وجوبا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: إضمار أنْ جوازا or وجوبا?',
          source: '﴿ليغفر لك الله﴾ / ﴿لن تنالوا البر حتى تنفقوا مما تحبون﴾ / ﴿وما كان الله ليضيع إيمانكم﴾',
          words: ['ليغفر لك الله', 'حتى تنفقوا', 'ليضيع إيمانكم'],
          labels: ['جوازا (لام الجر)', 'وجوبا (حتى)', 'وجوبا (لام الجحود)'],
          distractors: ['جوازا (بعد عطف)'],
        },
        {
          title: 'تركيب: شروط إذن',
          kind: 'tarkeeb',
          instruction: "Classify each requirement of إذن's three conditions.",
          source: 'صدر الكلام / فعل مستقبل بعدها / لا فاصل إلا القسم',
          words: ['صدر الكلام', 'فعل مستقبل', 'لا فاصل إلا القسم'],
          labels: ['شرط أول', 'شرط ثانٍ', 'شرط ثالث'],
          distractors: ['شرط رابع'],
        },
        {
          title: 'تركيب: ما يسبق واو الصرف وفاء السببية',
          kind: 'tarkeeb',
          instruction: 'Classify what precedes واو الصرف / فاء السببية in each example.',
          source: '﴿ولما يعلم الله...ويعلم الصابرين﴾ / أسلم فتدخل الجنة',
          words: ['ولما يعلم...ويعلم', 'أسلم فتدخل'],
          labels: ['نفي', 'طلب (أمر)'],
          distractors: ['استفهام'],
        },
        {
          title: 'تركيب: قياسي أم سماعي؟',
          kind: 'tarkeeb',
          instruction: 'Classify each نصب-by-implied-أنْ example: قياسي or سماعي?',
          source: '﴿ليغفر لك الله﴾ / مره يحفرها',
          words: ['ليغفر لك الله', 'مره يحفرها'],
          labels: ['قياسي (لام الجر)', 'سماعي'],
          distractors: ['ممتنع كليا'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'جوازم المضارع',
      subtitle: 'Jussive Particles — لم ولما ولام الأمر ولا الناهية, and إنْ وإذما governing a شرط',
      concepts: [
        {
          heading: 'ضربا جوازم المضارع',
          body: `جزم حروف split into two subtypes: (1) حروف putting <b>one</b> فعل in جزم — four of them: <bdi>لَمْ، لَمَّا، لَامُ الْأَمْر، لَا النَّاهِيَة</bdi> (2) حروف putting <b>two</b> أفعال in جزم — two of them: <bdi>إِنْ، إِذْمَا</bdi>.`,
          sample: `جوازم فعل واحد (٤) — لم، لما، لام الأمر، لا الناهية<br>جوازم فعلين (٢) — إنْ، إذما`,
          exercise: {
            prompt: `What are the two subtypes of جزم حروف؟`,
            kind: 'mcq',
            options: ['حروف تجزم فعلا واحدا (أربعة), and حروف تجزم فعلين (اثنان)', 'حروف تجزم الاسم, and حروف تجزم الفعل', 'حروف قياسية, and حروف سماعية', 'حروف أصلية, and حروف زائدة'],
            correct: 0,
          },
        },
        {
          heading: 'لم ولما',
          body: `<bdi>لَمْ</bdi> negates the مضارع and converts its meaning to the past, as in <bdi>﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾</bdi>. <bdi>لَمَّا</bdi> does the same but adds an <b>expectation that it will yet occur</b> (<bdi>مَعَ تَوَقُّعِ الْحُصُول</bdi>), as in <bdi>﴿وَلَمَّا يَدْخُلِ الْإِيمَانُ فِي قُلُوبِكُمْ﴾</bdi>. An example combining <bdi>لَامُ الْأَمْر</bdi> and <bdi>لَا النَّاهِيَة</bdi> together is <bdi>﴿فَمَنْ كَانَ يَرْجُو لِقَاءَ رَبِّهِ فَلْيَعْمَلْ عَمَلًا صَالِحًا وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا﴾</bdi>.`,
          sample: `لم — تنفي المضارع وتقلبه ماضيا: ﴿لم يلد ولم يولد﴾<br>لما — كذلك، مع توقع الحصول: ﴿ولما يدخل الإيمان في قلوبكم﴾<br>لام الأمر + لا الناهية معا — ﴿فمن كان يرجو لقاء ربه فليعمل عملا صالحا ولا يشرك بعبادة ربه أحدا﴾`,
          exercise: {
            prompt: `How does لما differ from لم؟`,
            kind: 'mcq',
            options: ['لما adds an expectation that the negated act will yet occur (توقع الحصول)', 'لما negates the future, while لم negates the past', 'لما only ever negates a فعل أمر', 'There is no difference between them at all'],
            correct: 0,
          },
        },
        {
          heading: 'شرط بفعلين: التسمية والمثال',
          body: `In a <bdi>شَرْط</bdi> governing two أفعال, the first فعل is called the <bdi>شَرْط</bdi> (condition) and the second is the <bdi>جَوَابُ الشَّرْط</bdi>, also called <bdi>الْجَزَاء</bdi>. <bdi>إِنِ الشَّرْطِيَّة</bdi> governs exactly this pair, as in <bdi>﴿إِنْ تَجْتَنِبُوا كَبَائِرَ مَا تُنْهَوْنَ عَنْهُ نُكَفِّرْ عَنْكُمْ سَيِّئَاتِكُمْ وَنُدْخِلْكُمْ مُدْخَلًا كَرِيمًا﴾</bdi>.`,
          sample: `شرط بفعلين — الأول: الشرط، الثاني: جواب الشرط (الجزاء)<br>إنْ الشرطية — ﴿إن تجتنبوا كبائر ما تنهون عنه نكفر عنكم سيئاتكم وندخلكم مدخلا كريما﴾`,
          exercise: {
            prompt: `In a شرط governing two أفعال, what are the two أفعال called؟`,
            kind: 'mcq',
            options: ['The first is الشرط; the second is جواب الشرط (also called الجزاء)', 'Both are simply called أفعال الشرط with no distinction', 'The first is الجزاء; the second is الشرط', 'The first is المسند; the second is المسند إليه'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع إضمار إنْ',
          body: `إِنْ الشرطية is implied (<bdi>مُقَدَّرَة</bdi>) before a مضارع مجزوم after four things: (1) <bdi>طَلَب</bdi>, as in <bdi>﴿تَعَالَوْا أَتْلُ﴾</bdi> (= <bdi>إِنْ تَتَعَالَوْا أَتْلُ</bdi>) (2) <bdi>اسْتِفْهَام</bdi>, as in <bdi>هَلْ تَزُورُنَا نُكْرِمْكَ</bdi> (3) <bdi>تَمَنٍّ</bdi>, as in <bdi>لَيْتَكَ عِنْدِي أَخْدِمْكَ</bdi> (4) <bdi>عَرْض</bdi>, as in <bdi>أَلَا تَنْزِلُ بِنَا تُصِبْ خَيْرًا</bdi>.`,
          sample: `إضمار إنْ بعد أربعة — طلب: ﴿تعالوا أتل﴾ = إن تتعالوا أتل؛ استفهام: هل تزورنا نكرمك؛ تمنٍّ: ليتك عندي أخدمك؛ عرض: ألا تنزل بنا تصب خيرا`,
          exercise: {
            prompt: `After how many things is إنْ implied (مقدرة) before a مضارع مجزوم؟`,
            kind: 'mcq',
            options: ['أربعة', 'اثنان', 'ثلاثة', 'خمسة'],
            correct: 0,
          },
        },
        {
          heading: 'ما الزائدة، وتوافق الأزمنة',
          body: `When redundant <bdi>مَا</bdi> is added after إنْ, it adds <bdi>تَوْكِيد</bdi>, and the condition فعل then takes the <bdi>نُونُ التَّوْكِيد</bdi>, as in <bdi>﴿وَإِمَّا يَنْزَغَنَّكَ مِنَ الشَّيْطَانِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ﴾</bdi>. The two أفعال after إنْ may combine tenses freely: (1) both مضارع, as in <bdi>﴿وَإِنْ تَعُودُوا نَعُدْ﴾</bdi> (2) both ماضٍ, as in <bdi>﴿وَإِنْ عُدْتُمْ عُدْنَا﴾</bdi> (3) مضارع then ماضٍ, as in <bdi>مَنْ يَقُمْ لَيْلَةَ الْقَدْرِ</bdi>...<bdi>غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ</bdi> (4) ماضٍ then مضارع — جزم or رفع both allowed, as in <bdi>﴿مَنْ كَانَ يُرِيدُ حَرْثَ الْآخِرَةِ نَزِدْ لَهُ فِي حَرْثِهِ﴾</bdi>.`,
          sample: `ما الزائدة بعد إنْ — توكيد + نون التوكيد: ﴿وإما ينزغنك من الشيطان نزغ فاستعذ بالله﴾<br>تراكيب الأزمنة (٤) — مضارع+مضارع، ماضٍ+ماضٍ، مضارع+ماضٍ، ماضٍ+مضارع (جزم أو رفع)`,
          exercise: {
            prompt: `What happens when redundant ما is added after إنْ؟`,
            kind: 'mcq',
            options: ['It emphasises, and the condition فعل then takes the نون التوكيد', 'It cancels the شرط meaning entirely', 'It converts إنْ into إنّ المشددة', 'It forces both أفعال into the ماضي tense'],
            correct: 0,
          },
        },
        {
          heading: 'الفاء قبل الجواب، وإذما',
          body: `When <bdi>الْفَاء</bdi> is added before جواب الشرط, إنْ then does <b>not</b> operate on that جواب, as in <bdi>﴿وَإِنْ يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ﴾</bdi>. <bdi>إِذْمَا</bdi> is a جزم حرف carrying the meaning of إنْ, as in <bdi>إِذْمَا تَتُبْ تُقْبَلْ تَوْبَتُكَ</bdi>.`,
          sample: `الفاء قبل الجواب — إنْ لا تعمل فيه: ﴿وإن يمسسك الله بضر فلا كاشف له إلا هو﴾<br>إذما — بمعنى إنْ: إذما تتب تقبل توبتك`,
          exercise: {
            prompt: `What happens to إنْ's government of جواب الشرط when الفاء is added before it؟`,
            kind: 'mcq',
            options: ['إنْ no longer operates on that جواب', 'إنْ operates even more strongly on it', 'The whole جملة becomes اسمية', 'إذن replaces إنْ automatically'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the four جوازم تجزم فعلا واحدا.',
          options: ['لم، لما، لام الأمر، لا الناهية', 'إنْ، إذما، لو، لولا', 'أنْ، كي، لن، إذن', 'هل، ما، لا، أم'],
          correct: 0,
        },
        {
          q: 'لم negates the مضارع and converts its meaning to:',
          options: ['الماضي', 'المستقبل', 'الحال المستمر', 'الأمر'],
          correct: 0,
        },
        {
          q: 'In a شرط بفعلين, the second فعل is called جواب الشرط, also known as:',
          options: ['الجزاء', 'العلة', 'التعليل', 'التوكيد'],
          correct: 0,
        },
        {
          q: 'هَلْ تَزُورُنَا نُكْرِمْكَ shows إنْ implied after:',
          options: ['استفهام', 'طلب', 'تمنٍّ', 'عرض'],
          correct: 0,
        },
        {
          q: 'When redundant ما follows إنْ, the شرط فعل takes:',
          options: ['نون التوكيد', 'تاء التأنيث', 'ياء المخاطبة', 'واو الجماعة'],
          correct: 0,
        },
        {
          q: 'إذما carries the meaning of:',
          options: ['إنْ', 'لو', 'لولا', 'لعل'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'جوازم فعل واحد',
          kind: 'mcq',
          prompt: 'Which of these جوازم puts only ONE فعل in جزم?',
          options: ['لم', 'إنْ', 'إذما', 'both إنْ and إذما'],
          correct: 0,
        },
        {
          title: 'جوازم فعلين',
          kind: 'mcq',
          prompt: 'Which two جوازم put TWO أفعال in جزم?',
          options: ['إنْ وإذما', 'لم ولما', 'لام الأمر ولا الناهية', 'لن وكي'],
          correct: 0,
        },
        {
          title: 'لم يلد ولم يولد',
          kind: 'mcq',
          prompt: '﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾ illustrates لم:',
          options: ['negating the مضارع, converting it to past meaning', 'negating a فعل أمر', 'negating a فعل ماضٍ directly', 'requesting something'],
          correct: 0,
        },
        {
          title: 'لما وتوقع الحصول',
          kind: 'mcq',
          prompt: '﴿وَلَمَّا يَدْخُلِ الْإِيمَانُ فِي قُلُوبِكُمْ﴾ — لما here adds a sense of:',
          options: ['توقع الحصول (expectation it will yet occur)', 'استحالة الحصول (impossibility)', 'تكرار الحصول (repetition)', 'نفي التوقع كليا'],
          correct: 0,
        },
        {
          title: 'لام الأمر ولا الناهية معا',
          kind: 'mcq',
          prompt: '﴿فَمَنْ كَانَ يَرْجُو لِقَاءَ رَبِّهِ فَلْيَعْمَلْ عَمَلًا صَالِحًا وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا﴾ contains both:',
          options: ['لام الأمر ولا الناهية', 'لم ولما', 'إنْ وإذما', 'كي ولن'],
          correct: 0,
        },
        {
          title: 'الشرط والجزاء',
          kind: 'mcq',
          prompt: 'In ﴿إِنْ تَجْتَنِبُوا كَبَائِرَ مَا تُنْهَوْنَ عَنْهُ نُكَفِّرْ عَنْكُمْ سَيِّئَاتِكُمْ﴾, تجتنبوا is the:',
          options: ['شرط', 'جواب الشرط (الجزاء)', 'مبتدأ', 'حال'],
          correct: 0,
        },
        {
          title: 'إنْ مقدرة بعد طلب',
          kind: 'mcq',
          prompt: '﴿تَعَالَوْا أَتْلُ﴾ (= إن تتعالوا أتل) shows إنْ implied after:',
          options: ['طلب', 'استفهام', 'تمنٍّ', 'عرض'],
          correct: 0,
        },
        {
          title: 'إنْ مقدرة بعد تمنٍّ',
          kind: 'mcq',
          prompt: 'لَيْتَكَ عِنْدِي أَخْدِمْكَ shows إنْ implied after:',
          options: ['تمنٍّ', 'طلب', 'استفهام', 'عرض'],
          correct: 0,
        },
        {
          title: 'إنْ مقدرة بعد عرض',
          kind: 'mcq',
          prompt: 'أَلَا تَنْزِلُ بِنَا تُصِبْ خَيْرًا shows إنْ implied after:',
          options: ['عرض', 'استفهام', 'تمنٍّ', 'طلب'],
          correct: 0,
        },
        {
          title: 'إما وتوكيد الجزم',
          kind: 'mcq',
          prompt: '﴿وَإِمَّا يَنْزَغَنَّكَ مِنَ الشَّيْطَانِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ﴾ shows إنْ with redundant ما, and the فعل taking:',
          options: ['نون التوكيد', 'تاء التأنيث الساكنة', 'ياء المخاطبة', 'واو الجماعة'],
          correct: 0,
        },
        {
          title: 'كلا الفعلين مضارع',
          kind: 'mcq',
          prompt: '﴿وَإِنْ تَعُودُوا نَعُدْ﴾ shows the شرط and جواب as:',
          options: ['both مضارع', 'both ماضٍ', 'مضارع then ماضٍ', 'ماضٍ then مضارع'],
          correct: 0,
        },
        {
          title: 'كلا الفعلين ماضٍ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ عُدْتُمْ عُدْنَا﴾ shows the شرط and جواب as:',
          options: ['both ماضٍ', 'both مضارع', 'مضارع then ماضٍ', 'ماضٍ then مضارع'],
          correct: 0,
        },
        {
          title: 'الفاء تمنع عمل إنْ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ﴾ — إنْ does NOT operate on the جواب here because of:',
          options: ['الفاء preceding the جواب', 'the جواب being جملة اسمية', 'the شرط being فعل ماضٍ', 'the presence of إلا'],
          correct: 0,
        },
        {
          title: 'إذما بمعنى إنْ',
          kind: 'mcq',
          prompt: 'إِذْمَا تَتُبْ تُقْبَلْ تَوْبَتُكَ — إذما here carries the meaning of:',
          options: ['إنْ', 'لو', 'كي', 'لن'],
          correct: 0,
        },
        {
          title: 'تركيب: تصنيف الجوازم الستة',
          kind: 'tarkeeb',
          instruction: 'Classify each جازم: تجزم فعلا واحدا, or فعلين؟',
          source: 'لم / لا الناهية / إنْ / إذما',
          words: ['لم', 'لا الناهية', 'إنْ', 'إذما'],
          labels: ['فعلا واحدا', 'فعلا واحدا', 'فعلين', 'فعلين'],
          distractors: ['ثلاثة أفعال'],
        },
        {
          title: 'تركيب: لم ولما، والفرق',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف by what it adds beyond plain نفي.',
          source: 'لم / لما',
          words: ['لم', 'لما'],
          labels: ['نفي وقلب للماضي فقط', 'نفي وقلب للماضي مع توقع الحصول'],
          distractors: ['نفي المستقبل'],
        },
        {
          title: 'تركيب: مواضع إضمار إنْ الأربعة',
          kind: 'tarkeeb',
          instruction: 'Match each example to the موضع of إضمار إنْ it illustrates.',
          source: '﴿تعالوا أتل﴾ / هل تزورنا نكرمك / ليتك عندي أخدمك / ألا تنزل بنا تصب خيرا',
          words: ['تعالوا أتل', 'هل تزورنا', 'ليتك عندي', 'ألا تنزل'],
          labels: ['طلب', 'استفهام', 'تمنٍّ', 'عرض'],
          distractors: ['نهي'],
        },
        {
          title: 'تركيب: تراكيب الأزمنة بعد إنْ',
          kind: 'tarkeeb',
          instruction: 'Classify the tense combination of شرط + جواب in each example.',
          source: '﴿وإن تعودوا نعد﴾ / ﴿وإن عدتم عدنا﴾',
          words: ['وإن تعودوا نعد', 'وإن عدتم عدنا'],
          labels: ['مضارع ثم مضارع', 'ماضٍ ثم ماضٍ'],
          distractors: ['مضارع ثم ماضٍ'],
        },
      ],
    },
  ],
};
