// Module 08 — التوبيخ والتنبيه والمصدر والنفي والاستفهام واللواحق
//
// Content is adapted from the second half of a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__2 الْحَرْفِ__2 الحرف غير العامل.apkg,
// 109 notes total, 55 of them here) prepared for this conversion — see the
// note at the top of Module 07 for how the single source deck was split in
// two. Concept bodies are short by design (a sentence or two, not teaching
// prose); quiz/bank question text is English with Arabic grammatical terms
// left in Arabic.
//
// This module covers the last six of ten حروف غير عاملة families (§2 of
// الحرف, itself §2 of العامل وغير العامل): حروف التوبيخ والتحضيض والعرض,
// أحرف التنبيه, أحرف المصدر والتفسير, أحرف النفي والزيادة, حروف الاستفهام
// والتمني والاستقبال, and a final lesson gathering the remaining
// "housekeeping" حروف — فاء/لام جواب الشرط, تاء التأنيث الساكنة, هاء
// السكت, and the five kinds of تنوين.

export default {
  id: '08',
  title: 'التوبيخ والتنبيه وما بعدهما',
  heading: 'العامل وغير العامل',
  subheading: 'الحرف غير العامل',
  blurb: 'حروف التوبيخ والتحضيض والعرض, أحرف التنبيه (ألا، أما، ها), أحرف المصدر والتفسير, أحرف النفي والزيادة, حروف الاستفهام والتمني والاستقبال (السين وسوف), and فاء/لام الجواب with تاء التأنيث، هاء السكت، and the five kinds of تنوين.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'التوبيخ والتحضيض والعرض',
      subtitle: 'Rebuke, Insistence, and Gentle Request — هلّا، ألا، لولا، لوما، ألّا, and the three حروف العرض',
      concepts: [
        {
          heading: 'التوبيخ والتحضيض: تعريفهما وحروفهما',
          body: `<bdi>التَّوْبِيخ</bdi> is blame for a fault (<bdi>لَوْمٌ عَلَى الْخَطَأ</bdi>) — its حروف come before a فعل past in both form and meaning. <bdi>التَّحْضِيض</bdi> is an insistent request (<bdi>طَلَبٌ بِشِدَّة</bdi>) — its حروف come before المضارع. The same five حروف serve both: <bdi>هَلَّا، أَلَا، لَوْلَا، لَوْمَا، أَلَّا</bdi> — which of the two meanings applies is told apart by whether a ماضٍ or مضارع follows.`,
          sample: `التوبيخ — لوم على الخطأ، قبل الماضي<br>التحضيض — طلب بشدة، قبل المضارع<br>الحروف الخمسة (نفسها لكليهما) — هلّا، ألا، لولا، لوما، ألّا`,
          exercise: {
            prompt: `How do you tell التوبيخ apart from التحضيض, given that the same حروف serve both؟`,
            kind: 'mcq',
            options: ['التوبيخ precedes a فعل ماضٍ; التحضيض precedes المضارع', 'التوبيخ precedes المضارع; التحضيض precedes الماضي', 'They are told apart only by context, never by the following فعل', 'التوبيخ never occurs with any of these five حروف'],
            correct: 0,
          },
        },
        {
          heading: 'هلّا: أمثلتها وأصلها',
          body: `<bdi>هَلَّا</bdi> serves both meanings: rebuke before the past — <bdi>هَلَّا صَلَّيْتَ</bdi> — and exhortation before the present — <bdi>هَلَّا تُصَلِّي</bdi>. Its origin is <bdi>هَلِ الِاسْتِفْهَامِيَّة</bdi> plus the نفي حرف <bdi>لَا</bdi>.`,
          sample: `هلّا (توبيخ) — هلّا صليتَ<br>هلّا (تحضيض) — هلّا تصلي<br>أصلها — هل الاستفهامية + لا (نفي)`,
          exercise: {
            prompt: `What is the origin of هلّا؟`,
            kind: 'mcq',
            options: ['هل الاستفهامية + حرف نفي (لا)', 'هل الاستفهامية وحدها, without anything added', 'لو الشرطية + لا', 'أداة شرط جازمة أصلا'],
            correct: 0,
          },
        },
        {
          heading: 'لولا ولوما: أصلهما، والتمييز عن الشرط',
          body: `In this usage, <bdi>لَوْلَا</bdi> comes from <bdi>لَوِ الشَّرْطِيَّة</bdi> plus the نفي حرف <bdi>لَا</bdi>, and <bdi>لَوْمَا</bdi> from لو الشرطية plus the نفي حرف <bdi>مَا</bdi> — as in <bdi>لَوْلَا صُمْتَ</bdi> / <bdi>لَوْلَا تَصُومُ</bdi> and <bdi>لَوْمَا صَدَقْتَ</bdi> / <bdi>﴿لَوْمَا تَأْتِينَا بِالْمَلَائِكَةِ﴾</bdi>. Since لولا/لوما can ALSO be plain أحرف الشرط (Module 07), the two readings are told apart <bdi>بِالسِّيَاق</bdi> (by context) — they serve both الشرط and التوبيخ والتحضيض.`,
          sample: `لولا (توبيخ/تحضيض) — أصلها لو + لا: لولا صمتَ / لولا تصوم<br>لوما (توبيخ/تحضيض) — أصلها لو + ما: لوما صدقتَ / ﴿لوما تأتينا بالملائكة﴾<br>التمييز عن لولا/لوما الشرطية — بالسياق`,
          exercise: {
            prompt: `How do you tell whether لولا / لوما is شرط or for rebuke/exhortation؟`,
            kind: 'mcq',
            options: ['By context (بالسياق) — they serve both meanings', 'لولا is always شرط; لوما is always تحضيض', 'By the vowel on the final letter alone', 'They can never mean rebuke or exhortation at all'],
            correct: 0,
          },
        },
        {
          heading: 'ألّا: اختصاصها وأصلها',
          body: `<bdi>أَلَّا</bdi> is distinctive among these five حروف: it is restricted to المضارع and never precedes the past, as in <bdi>﴿أَلَا تُحِبُّونَ أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾</bdi>. Its origin is <bdi>هَمْزَةُ اسْتِفْهَام</bdi> plus the نفي حرف <bdi>لَا</bdi>.`,
          sample: `ألّا — مختصة بالمضارع، لا تسبق الماضي أبدا: ﴿ألا تحبون أن يغفر الله لكم﴾<br>أصلها — همزة استفهام + لا`,
          exercise: {
            prompt: `What is distinctive about ألّا among these five حروف؟`,
            kind: 'mcq',
            options: ['It is restricted to المضارع and never precedes the past', 'It is restricted to الماضي and never precedes المضارع', 'It can never be used for either توبيخ or تحضيض', 'It is identical in every respect to هلّا'],
            correct: 0,
          },
        },
        {
          heading: 'العرض: تعريفه وحروفه',
          body: `<bdi>الْعَرْض</bdi> is a gentle request (<bdi>طَلَبٌ بِلِين</bdi>). Its three حروف are <bdi>أَلَا، أَمَا، لَوْ</bdi>, as in <bdi>أَلَا تَقُومُ بِاللَّيْلِ؟</bdi>, <bdi>أَمَا تَصُومُ يَوْمَ الِاثْنَيْنِ وَالْخَمِيسِ</bdi>, and <bdi>لَوْ تَتَصَدَّقُ عَلَى الْفُقَرَاءِ</bdi>. <bdi>أَمَا</bdi> (of العرض) comes from <bdi>هَمْزَةُ اسْتِفْهَام</bdi> plus the نفي حرف <bdi>مَا</bdi>; <bdi>أَلَا</bdi> here serves both التحضيض and العرض, and is known only by context.`,
          sample: `العرض — طلب بلين، حروفه الثلاثة: ألا، أما، لو<br>أمثلة — ألا تقوم بالليل؟ أما تصوم يوم الاثنين والخميس؟ لو تتصدق على الفقراء<br>أصل أما (العرض) — همزة استفهام + ما<br>ألا مشتركة بين التحضيض والعرض — تُعرف بالسياق`,
          exercise: {
            prompt: `Define العرض and name its three حروف.`,
            kind: 'mcq',
            options: ['طلب بلين (a gentle request); its حروف are ألا، أما، لو', 'لوم على الخطأ; its حروف are هلّا، ألا، لولا', 'طلب بشدة; its حروف are لوما، ألّا، هلّا', 'A form of الاستفهام المحض with no request implied'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the five حروف serving both التوبيخ والتحضيض.',
          options: ['هلّا، ألا، لولا، لوما، ألّا', 'ألا، أما، لو، لولا، لوما', 'نعم، بلى، إي، أجل، كلا', 'الواو، الفاء، ثم، حتى، لكن'],
          correct: 0,
        },
        {
          q: 'هَلَّا صَلَّيْتَ, with a فعل ماضٍ following, illustrates:',
          options: ['التوبيخ (rebuke)', 'التحضيض (insistent request)', 'العرض (gentle request)', 'الاستفهام المحض'],
          correct: 0,
        },
        {
          q: 'The origin of لوما (in this usage) is:',
          options: ['لو الشرطية + ما النافية', 'همزة استفهام + ما', 'لو الشرطية + لا', 'هل الاستفهامية + ما'],
          correct: 0,
        },
        {
          q: 'Which of the five حروف is restricted to المضارع and never precedes الماضي?',
          options: ['ألّا', 'هلّا', 'لولا', 'لوما'],
          correct: 0,
        },
        {
          q: 'List the three حروف العرض.',
          options: ['ألا، أما، لو', 'هلّا، ألا، لولا', 'نعم، بلى، إي', 'الواو، الفاء، ثم'],
          correct: 0,
        },
        {
          q: 'أَمَا تَصُومُ يَوْمَ الِاثْنَيْنِ وَالْخَمِيسِ illustrates:',
          options: ['العرض (a gentle request)', 'التوبيخ (rebuke)', 'الاستدراك', 'التسوية'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'تعريف التوبيخ',
          kind: 'mcq',
          prompt: 'التوبيخ is defined as:',
          options: ['لوم على الخطأ (blame for a fault)', 'طلب بشدة (an insistent request)', 'طلب بلين (a gentle request)', 'تصديق ما سبق'],
          correct: 0,
        },
        {
          title: 'تعريف التحضيض',
          kind: 'mcq',
          prompt: 'التحضيض is defined as:',
          options: ['طلب بشدة (an insistent request)', 'لوم على الخطأ', 'طلب بلين', 'تصديق ما سبق'],
          correct: 0,
        },
        {
          title: 'التمييز بالفعل التالي',
          kind: 'mcq',
          prompt: 'The same five حروف serve both التوبيخ والتحضيض; the difference is told apart by:',
          options: ['whether a فعل ماضٍ or مضارع follows', 'the vowel on the حرف itself', 'whether الواو precedes it', 'the speaker\'s tone alone, with no grammatical marker'],
          correct: 0,
        },
        {
          title: 'هلّا للتحضيض',
          kind: 'mcq',
          prompt: 'هَلَّا تُصَلِّي illustrates:',
          options: ['التحضيض (insistent request)', 'التوبيخ (rebuke)', 'العرض', 'الاستفهام المحض'],
          correct: 0,
        },
        {
          title: 'لولا للتوبيخ',
          kind: 'mcq',
          prompt: 'لَوْلَا صُمْتَ illustrates:',
          options: ['التوبيخ, since a فعل ماضٍ follows', 'التحضيض, since a فعل مضارع follows', 'العرض فقط', 'الشرط المحض فقط'],
          correct: 0,
        },
        {
          title: 'لوما القرآنية',
          kind: 'mcq',
          prompt: '﴿لَوْمَا تَأْتِينَا بِالْمَلَائِكَةِ﴾ illustrates:',
          options: ['التحضيض, since a فعل مضارع follows', 'التوبيخ, since a فعل ماضٍ follows', 'العرض المحض', 'الاستفهام المحض'],
          correct: 0,
        },
        {
          title: 'أصل هلّا',
          kind: 'mcq',
          prompt: 'هلّا originates from:',
          options: ['هل الاستفهامية + لا', 'همزة استفهام + لا', 'لو الشرطية + لا', 'لو الشرطية + ما'],
          correct: 0,
        },
        {
          title: 'أصل لولا',
          kind: 'mcq',
          prompt: 'لولا (in this usage) originates from:',
          options: ['لو الشرطية + لا', 'هل الاستفهامية + لا', 'همزة استفهام + لا', 'همزة استفهام + ما'],
          correct: 0,
        },
        {
          title: 'ألّا مثالها القرآني',
          kind: 'mcq',
          prompt: '﴿أَلَا تُحِبُّونَ أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾ shows ألّا preceding:',
          options: ['a فعل مضارع (تحبون)', 'a فعل ماضٍ', 'an اسم مجرد', 'a حرف جر'],
          correct: 0,
        },
        {
          title: 'أصل ألّا',
          kind: 'mcq',
          prompt: 'ألّا originates from:',
          options: ['همزة استفهام + لا', 'هل الاستفهامية + لا', 'لو الشرطية + ما', 'أنْ المصدرية + لا'],
          correct: 0,
        },
        {
          title: 'حروف العرض الثلاثة',
          kind: 'mcq',
          prompt: 'List the three حروف العرض.',
          options: ['ألا، أما، لو', 'هلّا، ألا، لولا', 'لوما، ألّا، هلّا', 'نعم، بلى، إي'],
          correct: 0,
        },
        {
          title: 'أصل أما العرض',
          kind: 'mcq',
          prompt: 'أما (of العرض) originates from:',
          options: ['همزة استفهام + ما', 'هل الاستفهامية + ما', 'لو الشرطية + ما', 'همزة استفهام + لا'],
          correct: 0,
        },
        {
          title: 'ألا مشتركة',
          kind: 'mcq',
          prompt: 'ألا serves both which two meanings, distinguished only by context?',
          options: ['التحضيض والعرض', 'التوبيخ والاستفهام', 'الشرط والتمني', 'العطف والاستدراك'],
          correct: 0,
        },
        {
          title: 'تركيب: توبيخ أم تحضيض؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: التوبيخ (before ماضٍ) or التحضيض (before مضارع)؟',
          source: 'هلّا صليتَ / هلّا تصلي / لولا صمتَ / لوما تأتينا بالملائكة',
          words: ['هلّا صليتَ', 'هلّا تصلي', 'لولا صمتَ', 'لوما تأتينا'],
          labels: ['التوبيخ', 'التحضيض', 'التوبيخ', 'التحضيض'],
          distractors: ['العرض'],
        },
        {
          title: 'تركيب: أصول الحروف الخمسة',
          kind: 'tarkeeb',
          instruction: 'Classify the origin of each حرف.',
          source: 'هلّا / لولا / ألّا',
          words: ['هلّا', 'لولا', 'ألّا'],
          labels: ['هل + لا', 'لو + لا', 'همزة + لا'],
          distractors: ['لو + ما'],
        },
        {
          title: 'تركيب: حروف العرض وأصولها',
          kind: 'tarkeeb',
          instruction: 'Classify the origin of each حرف العرض.',
          source: 'أما (العرض) / ألا (العرض)',
          words: ['أما', 'ألا'],
          labels: ['همزة + ما', 'همزة + لا'],
          distractors: ['لو + ما'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'أحرف التنبيه',
      subtitle: 'Alerting Particles — ألا, أما, and the four things ها enters upon',
      concepts: [
        {
          heading: 'الثلاثة، وألا التنبيه',
          body: `There are three <bdi>أَحْرُفُ التَّنْبِيه</bdi>: <bdi>أَلَا، أَمَا، هَا</bdi>. The جملة after <bdi>أَلَا التَّنْبِيه</bdi> usually carries some emphasis, as in <bdi>﴿أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ﴾</bdi>; it enters both nominal and جمل فعلية, as in <bdi>﴿أَلَا حِينَ يَسْتَغْشُونَ ثِيَابَهُمْ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ﴾</bdi>.`,
          sample: `أحرف التنبيه الثلاثة — ألا، أما، ها<br>ألا التنبيه — جملة بعدها فيها تأكيد غالبا: ﴿ألا إنهم هم المفسدون﴾، تدخل الاسمية والفعلية`,
          exercise: {
            prompt: `What are the three أحرف التنبيه؟`,
            kind: 'mcq',
            options: ['ألا، أما، ها', 'هلّا، لولا، لوما', 'نعم، بلى، إي', 'الواو، الفاء، ثم'],
            correct: 0,
          },
        },
        {
          heading: 'تمييز ألا التنبيه عن التحضيض والعرض',
          body: `ألا التنبيه is told apart from ألا of التحضيض/العرض by a simple test: the speech remains grammatically valid if <bdi>أَلَا التَّنْبِيه</bdi> is dropped — <bdi>﴿أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ﴾</bdi> still stands without it — unlike ألا of التحضيض or العرض, as in <bdi>﴿أَلَا تَأْكُلُونَ﴾</bdi>, where dropping it changes the sentence's force.`,
          sample: `اختبار ألا التنبيه — يصح الكلام لو حُذفت: ﴿ألا إنهم هم المفسدون﴾<br>بخلاف ألا التحضيض/العرض — ﴿ألا تأكلون﴾، حذفها يغير قوة الجملة`,
          exercise: {
            prompt: `How do you distinguish ألا of التنبيه from ألا of التحضيض/العرض؟`,
            kind: 'mcq',
            options: ['The speech remains valid if ألا التنبيه is dropped, unlike the other two', 'ألا التنبيه only ever precedes الماضي', 'They cannot be distinguished at all', 'ألا التنبيه is always followed by a قسم'],
            correct: 0,
          },
        },
        {
          heading: 'أما التنبيه',
          body: `<bdi>أَمَا التَّنْبِيه</bdi> is usually followed by a قسم, as in <bdi>أَمَا وَالَّذِي أَبْكَى وَأَضْحَكَ</bdi>...; its همزة may also be dropped, as in <bdi>مَا تَرَى الدَّهْرَ قَدْ أَبَادَ مَعَدًّا</bdi>...`,
          sample: `أما التنبيه — يليها قسم غالبا: أما والذي أبكى وأضحك...<br>حذف همزتها — جائز: ما ترى الدهر قد أباد معدا...`,
          exercise: {
            prompt: `What usually follows أما التنبيه, and may its همزة be dropped؟`,
            kind: 'mcq',
            options: ['A قسم usually follows, and yes, the همزة may be dropped', 'A فعل أمر usually follows, and the همزة may never be dropped', 'Nothing may follow it at all', 'A حرف جر usually follows'],
            correct: 0,
          },
        },
        {
          heading: 'ها التنبيه: أربعة مواضع',
          body: `<bdi>هَا التَّنْبِيه</bdi> enters upon four things: (1) an <bdi>اسْمُ إِشَارَةٍ لِلْقَرِيب</bdi>, as in <bdi>﴿هَٰؤُلَاءِ قَوْمُنَا﴾</bdi> (2) a <bdi>ضَمِيرُ رَفْع</bdi>, as in <bdi>﴿هَا أَنْتُمْ هَٰؤُلَاءِ﴾</bdi> (3) a <bdi>فِعْلٌ مَاضٍ</bdi> accompanied by <bdi>قَدْ</bdi>, as in <bdi>هَا قَدْ غَفَرَ اللَّهُ لِلتَّائِبِينَ</bdi> (4) <bdi>أَيّ</bdi>/<bdi>أَيَّة</bdi> before a word bearing <bdi>أَل</bdi>, as in <bdi>﴿يَا أَيُّهَا النَّاسُ﴾</bdi> and <bdi>﴿يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ﴾</bdi>.`,
          sample: `ها التنبيه (٤ مواضع) — اسم إشارة للقريب: ﴿هؤلاء قومنا﴾؛ ضمير رفع: ﴿ها أنتم هؤلاء﴾؛ فعل ماضٍ مع قد: ها قد غفر الله للتائبين؛ أي/أية قبل ما فيه أل: ﴿يا أيها الناس﴾`,
          exercise: {
            prompt: `Upon what four things does ها التنبيه enter؟`,
            kind: 'mcq',
            options: ['اسم إشارة للقريب, ضمير رفع, فعل ماضٍ مع قد, and أيّ/أية before a word bearing أل', 'Only ever upon a فعل مضارع', 'Only ever upon a حرف جر', 'Upon nothing — ها is always meaningless filler'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the three أحرف التنبيه.',
          options: ['ألا، أما، ها', 'ألا، أما، لو', 'هلّا، لولا، لوما', 'نعم، بلى، كلا'],
          correct: 0,
        },
        {
          q: 'The test for ألا التنبيه is that the speech:',
          options: ['remains valid if ألا is dropped', 'becomes invalid if ألا is dropped', 'must always end in a قسم', 'must always be a جملة فعلية'],
          correct: 0,
        },
        {
          q: 'أما التنبيه is usually followed by:',
          options: ['a قسم', 'a فعل أمر', 'a حرف جر', 'nothing at all'],
          correct: 0,
        },
        {
          q: '﴿هَٰؤُلَاءِ قَوْمُنَا﴾ shows ها التنبيه entering upon:',
          options: ['اسم إشارة للقريب', 'ضمير رفع', 'فعل ماضٍ مع قد', 'أيّ قبل أل'],
          correct: 0,
        },
        {
          q: '﴿هَا أَنْتُمْ هَٰؤُلَاءِ﴾ shows ها التنبيه entering upon:',
          options: ['ضمير رفع', 'اسم إشارة للقريب', 'فعل ماضٍ مع قد', 'أيّ قبل أل'],
          correct: 0,
        },
        {
          q: '﴿يَا أَيُّهَا النَّاسُ﴾ shows ها التنبيه entering (via أيّ) upon:',
          options: ['a word bearing أل', 'a فعل ماضٍ', 'a ضمير منفصل', 'a حرف جر'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الثلاثة بالاسم',
          kind: 'mcq',
          prompt: 'List the three أحرف التنبيه.',
          options: ['ألا، أما، ها', 'إي، أجل، جير', 'هلّا، ألا، لولا', 'الواو، ثم، حتى'],
          correct: 0,
        },
        {
          title: 'ألا التنبيه ودخولها على الفعلية',
          kind: 'mcq',
          prompt: '﴿أَلَا حِينَ يَسْتَغْشُونَ ثِيَابَهُمْ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ﴾ shows ألا التنبيه entering a جملة:',
          options: ['فعلية', 'اسمية فقط', 'شرطية فقط', 'استفهامية'],
          correct: 0,
        },
        {
          title: 'حذف ألا التنبيه',
          kind: 'mcq',
          prompt: 'If ألا التنبيه is dropped from ﴿أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ﴾, the sentence:',
          options: ['remains grammatically valid', 'becomes invalid Arabic', 'converts into a question', 'loses its فاعل entirely'],
          correct: 0,
        },
        {
          title: 'أما مع القسم',
          kind: 'mcq',
          prompt: 'أَمَا وَالَّذِي أَبْكَى وَأَضْحَكَ shows أما التنبيه followed by:',
          options: ['a قسم', 'a شرط جملة', 'a نداء', 'a استفهام'],
          correct: 0,
        },
        {
          title: 'حذف همزة أما',
          kind: 'mcq',
          prompt: 'Can the همزة of أما التنبيه be dropped?',
          options: ['Yes, as in ما ترى الدهر قد أباد معدا', 'No, never under any circumstance', 'Only when followed by ها', 'Only in modern Arabic, never classical'],
          correct: 0,
        },
        {
          title: 'ها على اسم الإشارة',
          kind: 'mcq',
          prompt: '﴿هَٰؤُلَاءِ قَوْمُنَا﴾ shows ها entering upon:',
          options: ['اسم إشارة للقريب', 'ضمير رفع', 'فعل ماضٍ', 'حرف جر'],
          correct: 0,
        },
        {
          title: 'ها على الفعل الماضي مع قد',
          kind: 'mcq',
          prompt: 'هَا قَدْ غَفَرَ اللَّهُ لِلتَّائِبِينَ shows ها entering upon:',
          options: ['فعل ماضٍ مصحوب بقد', 'اسم إشارة', 'ضمير رفع', 'أيّ قبل أل'],
          correct: 0,
        },
        {
          title: 'ها على أيتها',
          kind: 'mcq',
          prompt: '﴿يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ﴾ shows ها entering (via أية) upon a word bearing:',
          options: ['أل', 'تنوين', 'ياء النداء وحدها', 'كاف الخطاب'],
          correct: 0,
        },
        {
          title: 'تركيب: مواضع ها التنبيه الأربعة',
          kind: 'tarkeeb',
          instruction: 'Match each example to the موضع of ها التنبيه it illustrates.',
          source: '﴿هؤلاء قومنا﴾ / ﴿ها أنتم هؤلاء﴾ / ها قد غفر الله للتائبين / ﴿يا أيها الناس﴾',
          words: ['هؤلاء قومنا', 'ها أنتم', 'ها قد غفر', 'يا أيها الناس'],
          labels: ['اسم إشارة للقريب', 'ضمير رفع', 'فعل ماضٍ مع قد', 'أيّ قبل أل'],
          distractors: ['فعل مضارع'],
        },
        {
          title: 'تركيب: تنبيه أم تحضيض/عرض؟',
          kind: 'tarkeeb',
          instruction: 'Classify each ألا: للتنبيه (يصح حذفها) or للتحضيض/العرض (لا يصح حذفها)؟',
          source: '﴿ألا إنهم هم المفسدون﴾ / ﴿ألا تأكلون﴾',
          words: ['ألا إنهم', 'ألا تأكلون'],
          labels: ['للتنبيه', 'للتحضيض/العرض'],
          distractors: ['للعطف'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'أحرف المصدر والتفسير',
      subtitle: "Nominalizers and Explanatory Particles — ما, أي, and أنْ التفسيرية's own conditions",
      concepts: [
        {
          heading: 'أحرف المصدر: أسماؤها البديلة، وغير العاملة منها',
          body: `<bdi>أَحْرُفُ الْمَصْدَر</bdi> are also called <bdi>مَوْصُولَاتٌ حَرْفِيَّة</bdi> or <bdi>حُرُوفٌ مَوْصُولَة</bdi>. Three are غير عاملة: (1) <bdi>مَا</bdi> — both <bdi>الْمَصْدَرِيَّةُ الظَّرْفِيَّة</bdi>, as in <bdi>﴿وَأَوْصَانِي بِالصَّلَاةِ وَالزَّكَاةِ مَا دُمْتُ حَيًّا﴾</bdi>, and غير الظرفية, as in <bdi>﴿فَصَبَرُوا عَلَىٰ مَا كُذِّبُوا﴾</bdi> (2) <bdi>لَوْ</bdi> after <bdi>وَدَّ</bdi>, as in <bdi>﴿وَدُّوا لَوْ تَكْفُرُونَ كَمَا كَفَرُوا﴾</bdi> (3) <bdi>هَمْزَةُ التَّسْوِيَة</bdi>, as in <bdi>﴿وَسَوَاءٌ عَلَيْهِمْ أَأَنْذَرْتَهُمْ أَمْ لَمْ تُنْذِرْهُمْ﴾</bdi>.`,
          sample: `أحرف المصدر = موصولات حرفية = حروف موصولة<br>غير العاملة الثلاثة — ما (ظرفية أو لا): ﴿وأوصاني بالصلاة والزكاة ما دمت حيا﴾؛ لو بعد ودّ: ﴿ودوا لو تكفرون كما كفروا﴾؛ همزة التسوية: ﴿وسواء عليهم أأنذرتهم أم لم تنذرهم﴾`,
          exercise: {
            prompt: `What alternative names are given to أحرف المصدر؟`,
            kind: 'mcq',
            options: ['موصولات حرفية and حروف موصولة', 'أحرف الصلة and أحرف الزيادة', 'نواسخ and عوامل', 'أحرف التنبيه and أحرف الجواب'],
            correct: 0,
          },
        },
        {
          heading: 'العاملة منها، وموقع همزة التسوية',
          body: `The governing (<bdi>عَامِلَة</bdi>) أحرف مصدرية are <bdi>كَيْ، أَنْ، أَنَّ</bdi>. <bdi>هَمْزَةُ التَّسْوِيَة</bdi> occurs after <bdi>سَوَاء</bdi>, <bdi>مَا أُبَالِي</bdi>, <bdi>مَا أَدْرِي</bdi>, <bdi>لَيْتَ شِعْرِي</bdi>, and the like.`,
          sample: `العاملة — كي، أنْ، أنَّ<br>مواقع همزة التسوية — بعد سواء، ما أبالي، ما أدري، ليت شعري، وما شابهها`,
          exercise: {
            prompt: `Which أحرف مصدرية are governing (عاملة)؟`,
            kind: 'mcq',
            options: ['كي، أنْ، أنَّ', 'ما، لو، الهمزة', 'الواو، الفاء، ثم', 'نعم، بلى، إي'],
            correct: 0,
          },
        },
        {
          heading: 'حرفا التفسير: أي وأنْ',
          body: `There are two <bdi>أَحْرُفُ التَّفْسِير</bdi> (explanatory particles): <bdi>أَيْ</bdi> can interpret both a single word, as in <bdi>أَسْأَلُ اللَّهَ الْفِرْدَوْسَ أَيِ الْجَنَّةَ</bdi>, and a جملة, as in <bdi>اسْتَغْفَرْتُ اللَّهَ أَيْ سَأَلْتُ اللَّهَ أَنْ يَغْفِرَ لِي</bdi>; <bdi>أَنْ</bdi> interprets only a جملة, as in <bdi>﴿وَنَادَيْنَاهُ أَنْ يَا إِبْرَاهِيمُ﴾</bdi>.`,
          sample: `أي — تفسر مفردا أو جملة: أسأل الله الفردوس أي الجنة<br>أنْ — تفسر جملة فقط: ﴿وناديناه أن يا إبراهيم﴾`,
          exercise: {
            prompt: `What can أي interpret, versus what أنْ can interpret؟`,
            kind: 'mcq',
            options: ['أي can interpret a single word or a جملة; أنْ can interpret only a جملة', 'أي can only interpret a جملة; أنْ can interpret either', 'Both interpret only single words, never a جملة', 'Neither can interpret anything without a قرينة'],
            correct: 0,
          },
        },
        {
          heading: 'شرطا أنْ التفسيرية',
          body: `أنْ التفسيرية requires two conditions: (1) it must be preceded by something carrying the <b>meaning</b> of speech without its wording (<bdi>لَفْظُ الْقَوْل</bdi>) — calling, as in <bdi>﴿وَنَادَيْنَاهُ أَنْ يَا إِبْرَاهِيمُ﴾</bdi>, revelation, as in <bdi>﴿وَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنْ أَلْقِ عَصَاكَ﴾</bdi>, covenant, as in <bdi>﴿وَعَهِدْنَا إِلَىٰ إِبْرَاهِيمَ وَإِسْمَاعِيلَ أَنْ طَهِّرَا بَيْتِيَ﴾</bdi>, or writing (2) no حرف جر, explicit or implied, before it — <bdi>﴿إِنَّ اللَّهَ يَأْمُرُكُمْ أَنْ تَذْبَحُوا بَقَرَةً﴾</bdi> is مصدرية instead, because الباء is implied there. Even when both conditions are met, أنْ is not necessarily تفسيرية — <bdi>﴿وَنَادَاهُمَا رَبُّهُمَا أَلَمْ أَنْهَكُمَا عَنْ تِلْكُمَا الشَّجَرَةِ﴾</bdi> meets them yet is not read that way.`,
          sample: `شرطا أنْ التفسيرية — مسبوقة بما فيه معنى القول لا لفظه (نداء، وحي، عهد، كتابة)؛ لا حرف جر قبلها ظاهرا أو مقدرا<br>استيفاء الشرطين لا يلزم التفسيرية — ﴿وناداهما ربهما ألم أنهكما عن تلكما الشجرة﴾`,
          exercise: {
            prompt: `If both conditions of أنْ التفسيرية are met, must it be read as تفسيرية؟`,
            kind: 'mcq',
            options: ['No — meeting the conditions does not force that reading', 'Yes, it is always forced once both conditions hold', 'Only one condition is ever needed, not both', 'أنْ التفسيرية has no conditions at all'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'أحرف المصدر are also called:',
          options: ['موصولات حرفية', 'أحرف الصلة', 'نواسخ حرفية', 'أحرف الزيادة'],
          correct: 0,
        },
        {
          q: '﴿وَدُّوا لَوْ تَكْفُرُونَ كَمَا كَفَرُوا﴾ shows لو functioning as:',
          options: ['حرف مصدر غير عامل', 'حرف شرط عامل', 'حرف عطف', 'حرف تنبيه'],
          correct: 0,
        },
        {
          q: 'Which of these أحرف مصدرية is governing (عاملة)?',
          options: ['أنَّ', 'ما', 'لو', 'همزة التسوية'],
          correct: 0,
        },
        {
          q: 'أنْ (as حرف تفسير) can interpret:',
          options: ['a جملة only', 'a single مفرد word only', 'both equally', 'neither — it never interprets anything'],
          correct: 0,
        },
        {
          q: '﴿إِنَّ اللَّهَ يَأْمُرُكُمْ أَنْ تَذْبَحُوا بَقَرَةً﴾ — أنْ here is مصدرية (not تفسيرية) because:',
          options: ['a حرف جر (الباء) is implied before it', 'no verbal meaning precedes it', 'it is followed by a single word, not a جملة', 'it occurs at the start of the جملة'],
          correct: 0,
        },
        {
          q: 'أنْ can have four overall roles: مصدرية، مخففة، زائدة، and:',
          options: ['تفسيرية', 'شرطية', 'ناصبة فقط', 'جازمة فقط'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'اسم بديل لأحرف المصدر',
          kind: 'mcq',
          prompt: 'أحرف المصدر are alternatively named:',
          options: ['موصولات حرفية', 'أحرف الصلة', 'أحرف الجواب', 'أحرف الشرط'],
          correct: 0,
        },
        {
          title: 'ما المصدرية الظرفية',
          kind: 'mcq',
          prompt: '﴿وَأَوْصَانِي بِالصَّلَاةِ وَالزَّكَاةِ مَا دُمْتُ حَيًّا﴾ shows ما as:',
          options: ['مصدرية ظرفية', 'مصدرية غير ظرفية', 'موصولة اسمية', 'نافية'],
          correct: 0,
        },
        {
          title: 'ما المصدرية غير الظرفية',
          kind: 'mcq',
          prompt: '﴿فَصَبَرُوا عَلَىٰ مَا كُذِّبُوا﴾ shows ما as:',
          options: ['مصدرية غير ظرفية', 'مصدرية ظرفية', 'نافية', 'زائدة'],
          correct: 0,
        },
        {
          title: 'همزة التسوية',
          kind: 'mcq',
          prompt: '﴿وَسَوَاءٌ عَلَيْهِمْ أَأَنْذَرْتَهُمْ أَمْ لَمْ تُنْذِرْهُمْ﴾ shows the همزة functioning as:',
          options: ['همزة تسوية, a حرف مصدر غير عامل', 'همزة استفهام محض', 'همزة قطع لا معنى لها', 'همزة وصل'],
          correct: 0,
        },
        {
          title: 'العاملة الثلاثة',
          kind: 'mcq',
          prompt: 'List the three governing (عاملة) أحرف مصدرية.',
          options: ['كي، أنْ، أنَّ', 'ما، لو، الهمزة', 'إنْ، إذما، لو', 'لام الابتداء، اللام المزحلقة، قد'],
          correct: 0,
        },
        {
          title: 'أي تفسر مفردا',
          kind: 'mcq',
          prompt: 'أَسْأَلُ اللَّهَ الْفِرْدَوْسَ أَيِ الْجَنَّةَ shows أي interpreting:',
          options: ['a single مفرد word', 'a whole جملة', 'a حرف جر', 'nothing at all'],
          correct: 0,
        },
        {
          title: 'أي تفسر جملة',
          kind: 'mcq',
          prompt: 'اسْتَغْفَرْتُ اللَّهَ أَيْ سَأَلْتُ اللَّهَ أَنْ يَغْفِرَ لِي shows أي interpreting:',
          options: ['a whole جملة', 'a single مفرد word only', 'a حرف جر', 'a ضمير منفصل'],
          correct: 0,
        },
        {
          title: 'أنْ التفسيرية بالنداء',
          kind: 'mcq',
          prompt: '﴿وَنَادَيْنَاهُ أَنْ يَا إِبْرَاهِيمُ﴾ shows أنْ preceded by something carrying the meaning of:',
          options: ['نداء (calling)', 'وحي (revelation)', 'عهد (covenant)', 'كتابة (writing)'],
          correct: 0,
        },
        {
          title: 'أنْ التفسيرية بالوحي',
          kind: 'mcq',
          prompt: '﴿وَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنْ أَلْقِ عَصَاكَ﴾ shows أنْ preceded by something carrying the meaning of:',
          options: ['وحي (revelation)', 'نداء (calling)', 'عهد (covenant)', 'كتابة (writing)'],
          correct: 0,
        },
        {
          title: 'شرط أنْ التفسيرية: لا حرف جر',
          kind: 'mcq',
          prompt: 'For أنْ to be تفسيرية, what must NOT precede it?',
          options: ['a حرف جر, explicit or implied', 'a لفظ القول proper', 'a جملة of any kind', 'a اسم موصول'],
          correct: 0,
        },
        {
          title: 'عدم لزوم التفسيرية',
          kind: 'mcq',
          prompt: '﴿وَنَادَاهُمَا رَبُّهُمَا أَلَمْ أَنْهَكُمَا عَنْ تِلْكُمَا الشَّجَرَةِ﴾ meets أنْ التفسيرية\'s two conditions, yet is:',
          options: ['not read as تفسيرية here', 'necessarily read as تفسيرية', 'invalid Arabic altogether', 'read as حرف عطف instead'],
          correct: 0,
        },
        {
          title: 'أدوار أنْ الأربعة',
          kind: 'mcq',
          prompt: 'List the four overall roles أنْ can have.',
          options: ['مصدرية، مخففة، زائدة، تفسيرية', 'شرطية، جازمة، ناصبة، جارة', 'عاطفة، جوابية، تنبيهية، تعجبية', 'مؤكدة، منفية، مثبتة، مستفهمة'],
          correct: 0,
        },
        {
          title: 'تركيب: أحرف مصدرية عاملة أم لا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف مصدر: عاملة or غير عاملة؟',
          source: 'كي / ما / أنَّ / لو (بعد ودّ)',
          words: ['كي', 'ما', 'أنَّ', 'لو'],
          labels: ['عاملة', 'غير عاملة', 'عاملة', 'غير عاملة'],
          distractors: ['جازمة'],
        },
        {
          title: 'تركيب: أي أم أنْ التفسيرية؟',
          kind: 'tarkeeb',
          instruction: 'Classify what each حرف تفسير can interpret.',
          source: 'أي / أنْ',
          words: ['أي', 'أنْ'],
          labels: ['مفرد أو جملة', 'جملة فقط'],
          distractors: ['حرف جر فقط'],
        },
        {
          title: 'تركيب: شروط أنْ التفسيرية',
          kind: 'tarkeeb',
          instruction: 'Classify each requirement of أنْ التفسيرية.',
          source: 'سبقها بما فيه معنى القول / خلوها من حرف جر قبلها',
          words: ['معنى القول قبلها', 'لا حرف جر قبلها'],
          labels: ['الشرط الأول', 'الشرط الثاني'],
          distractors: ['الشرط الثالث'],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'أحرف النفي والزيادة',
      subtitle: 'Negation and Extra Particles — ما، لا، إنْ النافية, and where extra letters attach',
      concepts: [
        {
          heading: 'أحرف النفي الثلاثة غير العاملة',
          body: `Three <bdi>نَفْي حُرُوف</bdi> are غير عاملة: (1) <bdi>مَا</bdi> — on the past, as in <bdi>﴿وَمَا قَتَلُوهُ﴾</bdi>, and the present, as in <bdi>﴿وَمَا يَشْعُرُونَ﴾</bdi> (2) <bdi>لَا</bdi> — on the present فعل, as in <bdi>﴿وَهُمْ لَا يُؤْمِنُونَ﴾</bdi> (3) <bdi>إِنْ</bdi>, as in <bdi>﴿إِنْ أَنْتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ﴾</bdi>. لا النافية can enter a فعل ماضٍ only when repeated, as in <bdi>﴿فَلَا صَدَّقَ وَلَا صَلَّىٰ﴾</bdi>, or when the meaning is future-oriented, like supplication — <bdi>لَا قَدَّرَ اللَّهُ</bdi>. The خبر after negating إنْ is usually accompanied by <bdi>إِلَّا</bdi>, as in the example above.`,
          sample: `أحرف النفي الثلاثة غير العاملة — ما (ماضٍ ومضارع)، لا (مضارع)، إنْ<br>لا على الماضي — بالتكرار: ﴿فلا صدّق ولا صلى﴾؛ أو بمعنى الدعاء: لا قدّر الله<br>خبر إنْ النافية — يصحبه إلا غالبا: ﴿إن أنتم إلا في ضلال كبير﴾`,
          exercise: {
            prompt: `When may negating لا enter upon a فعل ماضٍ؟`,
            kind: 'mcq',
            options: ['When repeated, or when the meaning is future-oriented like supplication', 'Never — لا can only ever negate المضارع', 'Only when preceded by a قسم', 'Only inside a شرط جملة'],
            correct: 0,
          },
        },
        {
          heading: 'أحرف النفي العاملة (تذكير)',
          body: `Besides these three, several أحرف نفي already met ARE governing (<bdi>عَامِلَة</bdi>): <bdi>لَا لِنَفْيِ الْجِنْس</bdi> and الحروف المشبهة بليس (Module 05), <bdi>لَنْ</bdi> (Module 06), <bdi>لَمْ</bdi> and <bdi>لَمَّا</bdi> (Module 06), and <bdi>لَا النَّهْي</bdi> (Module 06).`,
          sample: `النفي العاملة — لا لنفي الجنس، الحروف المشبهة بليس، لن، لم، لما، لا الناهية`,
          exercise: {
            prompt: `Which of these نفي حروف is governing (عاملة)؟`,
            kind: 'mcq',
            options: ['لا لنفي الجنس', 'ما النافية غير العاملة', 'لا النافية للمضارع فقط', 'إنْ النافية'],
            correct: 0,
          },
        },
        {
          heading: 'أحرف الزيادة: اسمها البديل، وإنْ الزائدة',
          body: `<bdi>أَحْرُفُ الزِّيَادَة</bdi> are alternatively called <bdi>أَحْرُفُ الصِّلَة</bdi>. Extra <bdi>إِنْ</bdi> usually occurs added with negating <bdi>مَا</bdi>, as in <bdi>مَا إِنْ أَتَيْتَ بِشَيْءٍ أَنْتَ تَكْرَهُهُ</bdi>; overall, إنْ can be <bdi>مُخَفَّفَة</bdi> (of إنّ), <bdi>شَرْطِيَّة</bdi>, <bdi>نَافِيَة</bdi>, or <bdi>زَائِدَة</bdi> — known by context.`,
          sample: `أحرف الزيادة = أحرف الصلة<br>إنْ الزائدة — تكثر مع ما النافية: ما إنْ أتيت بشيء أنت تكرهه<br>أدوار إنْ الأربعة — مخففة، شرطية، نافية، زائدة`,
          exercise: {
            prompt: `What alternative name do أحرف الزيادة have؟`,
            kind: 'mcq',
            options: ['أحرف الصلة', 'أحرف التوكيد', 'أحرف التفسير', 'أحرف الجواب'],
            correct: 0,
          },
        },
        {
          heading: 'أنْ الزائدة وما الزائدة',
          body: `Extra <bdi>أَنْ</bdi> usually occurs (1) after <bdi>لَمَّا الْحِينِيَّة</bdi>, as in <bdi>﴿فَلَمَّا أَنْ جَاءَ الْبَشِيرُ﴾</bdi> (2) between <bdi>لَوْ</bdi> and a preceding قسم-واو, as in <bdi>وَاللَّهِ أَنْ لَوْ قُمْتَ قُمْتُ</bdi>. Extra <bdi>مَا</bdi> may be inserted after أدوات الشرط — <bdi>إِذَا، مَتَىٰ، أَيّ، أَيْنَ، إِنْ</bdi> — as in <bdi>﴿وَإِذَا مَا غَضِبُوا هُمْ يَغْفِرُونَ﴾</bdi>, and after حروف الجر — <bdi>مِنْ، عَنْ، الْبَاء</bdi> — as in <bdi>﴿مِمَّا خَطِيئَاتِهِمْ أُغْرِقُوا﴾</bdi>. Extra ما does <b>not</b> block (<bdi>لَا تَكُفُّ عَنِ</bdi>) the governing action of what it attaches to.`,
          sample: `أنْ الزائدة — بعد لمّا الحينية: ﴿فلما أن جاء البشير﴾؛ بين لو وواو القسم قبلها: والله أنْ لو قمت قمت<br>ما الزائدة بعد أدوات الشرط — إذا، متى، أي، أين، إن: ﴿وإذا ما غضبوا هم يغفرون﴾<br>ما الزائدة بعد حروف الجر — من، عن، الباء: ﴿مما خطيئاتهم أغرقوا﴾<br>ما الزائدة لا تكفّ عن العمل`,
          exercise: {
            prompt: `Does extra ما block the governing action of what it attaches to؟`,
            kind: 'mcq',
            options: ['No — ما الزائدة لا تكفّ عن العمل', 'Yes, it always cancels that governing action', 'Only when it follows a حرف جر', 'Only when it follows إذا specifically'],
            correct: 0,
          },
        },
        {
          heading: 'لا الزائدة، والحروف الزائدة العاملة',
          body: `Extra <bdi>لَا</bdi> is added in three positions: (1) with الواو after نفي, as in <bdi>مَا جَاءَ زَيْدٌ وَلَا عَمْرٌو</bdi> (2) after <bdi>أَنْ الْمَصْدَرِيَّة</bdi>, as in <bdi>﴿مَا مَنَعَكَ أَلَّا تَسْجُدَ إِذْ أَمَرْتُكَ﴾</bdi> (3) before a قسم, as in <bdi>﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾</bdi>. Some extra حروف ARE governing: <bdi>الْبَاء، مِنْ،</bdi> and <bdi>اللَّامُ الْجَارَّة</bdi>.`,
          sample: `مواضع لا الزائدة (٣) — مع الواو بعد نفي: ما جاء زيد ولا عمرو؛ بعد أنْ المصدرية: ﴿ما منعك ألا تسجد إذ أمرتك﴾؛ قبل القسم: ﴿لا أقسم بيوم القيامة﴾<br>الزائدة العاملة — الباء، من، اللام الجارة`,
          exercise: {
            prompt: `In what three positions is extra لا added؟`,
            kind: 'mcq',
            options: ['With الواو after نفي, after أنْ المصدرية, and before a قسم', 'Only ever at the very start of a جملة', 'Only ever after a فعل أمر', 'Only ever inside a شرط جملة'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the three أحرف نفي غير عاملة.',
          options: ['ما، لا، إنْ', 'لن، لم، لما', 'لا لنفي الجنس، ما، لات', 'إنْ، إذما، لو'],
          correct: 0,
        },
        {
          q: '﴿فَلَا صَدَّقَ وَلَا صَلَّىٰ﴾ shows لا entering الماضي because it is:',
          options: ['repeated', 'preceded by a قسم', 'followed by إلا', 'inside a شرط جملة'],
          correct: 0,
        },
        {
          q: 'أحرف الزيادة are alternatively named:',
          options: ['أحرف الصلة', 'أحرف التوكيد', 'أحرف العطف', 'أحرف الشرط'],
          correct: 0,
        },
        {
          q: '﴿فَلَمَّا أَنْ جَاءَ الْبَشِيرُ﴾ shows extra أنْ occurring after:',
          options: ['لمّا الحينية', 'لو الشرطية', 'حتى', 'إنْ الشرطية'],
          correct: 0,
        },
        {
          q: 'Does extra ما block the governing action of what it attaches to?',
          options: ['No', 'Yes, always', 'Only after حروف الجر', 'Only after أدوات الشرط'],
          correct: 0,
        },
        {
          q: '﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾ shows extra لا occurring:',
          options: ['before a قسم', 'after a نفي', 'after أنْ المصدرية', 'after a شرط جملة'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'ما تنفي الماضي والمضارع',
          kind: 'mcq',
          prompt: '﴿وَمَا قَتَلُوهُ﴾ and ﴿وَمَا يَشْعُرُونَ﴾ together show ما negating:',
          options: ['both الماضي and المضارع', 'الماضي only', 'المضارع only', 'neither — ما never negates a فعل'],
          correct: 0,
        },
        {
          title: 'لا تنفي المضارع',
          kind: 'mcq',
          prompt: '﴿وَهُمْ لَا يُؤْمِنُونَ﴾ shows لا negating:',
          options: ['a فعل مضارع', 'a فعل ماضٍ', 'an اسم مجرد', 'a حرف'],
          correct: 0,
        },
        {
          title: 'إنْ النافية وخبرها',
          kind: 'mcq',
          prompt: '﴿إِنْ أَنْتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ﴾ shows the خبر after إنْ النافية accompanied by:',
          options: ['إلا', 'الواو', 'الفاء', 'أل'],
          correct: 0,
        },
        {
          title: 'لا بالتكرار على الماضي',
          kind: 'mcq',
          prompt: '﴿فَلَا صَدَّقَ وَلَا صَلَّىٰ﴾ shows لا entering الماضي because:',
          options: ['it is repeated', 'it means دعاء', 'it follows إنْ', 'it follows a قسم'],
          correct: 0,
        },
        {
          title: 'لا بمعنى الدعاء',
          kind: 'mcq',
          prompt: 'لَا قَدَّرَ اللَّهُ shows لا entering الماضي because the meaning is:',
          options: ['future-oriented, like supplication (دعاء)', 'purely reporting a past event', 'a repeated نفي', 'a شرط جملة'],
          correct: 0,
        },
        {
          title: 'العاملة من أحرف النفي',
          kind: 'mcq',
          prompt: 'Which of these نفي حروف is عاملة, unlike ما، لا، إنْ in this lesson?',
          options: ['لن', 'ما', 'لا (المضارع فقط)', 'إنْ'],
          correct: 0,
        },
        {
          title: 'إنْ الزائدة مع ما',
          kind: 'mcq',
          prompt: 'مَا إِنْ أَتَيْتَ بِشَيْءٍ أَنْتَ تَكْرَهُهُ shows إنْ الزائدة typically added with:',
          options: ['ما النافية', 'لا الناهية', 'لن', 'لام الابتداء'],
          correct: 0,
        },
        {
          title: 'أنْ الزائدة بين لو والقسم',
          kind: 'mcq',
          prompt: 'وَاللَّهِ أَنْ لَوْ قُمْتَ قُمْتُ shows extra أنْ occurring:',
          options: ['between لو and a preceding قسم-واو', 'after لمّا الحينية', 'after حتى', 'after فاء السببية'],
          correct: 0,
        },
        {
          title: 'ما الزائدة بعد إذا',
          kind: 'mcq',
          prompt: '﴿وَإِذَا مَا غَضِبُوا هُمْ يَغْفِرُونَ﴾ shows extra ما added after:',
          options: ['إذا, an أداة شرط', 'a حرف جر', 'a فعل ماضٍ', 'a قسم'],
          correct: 0,
        },
        {
          title: 'ما الزائدة بعد حرف جر',
          kind: 'mcq',
          prompt: '﴿مِمَّا خَطِيئَاتِهِمْ أُغْرِقُوا﴾ shows extra ما added after:',
          options: ['a حرف جر (من)', 'an أداة شرط', 'a فعل ناقص', 'a قسم'],
          correct: 0,
        },
        {
          title: 'لا الزائدة مع الواو',
          kind: 'mcq',
          prompt: 'مَا جَاءَ زَيْدٌ وَلَا عَمْرٌو shows extra لا occurring:',
          options: ['with الواو after a نفي', 'before a قسم', 'after أنْ المصدرية', 'after إنْ الشرطية'],
          correct: 0,
        },
        {
          title: 'لا الزائدة بعد أنْ المصدرية',
          kind: 'mcq',
          prompt: '﴿مَا مَنَعَكَ أَلَّا تَسْجُدَ إِذْ أَمَرْتُكَ﴾ shows extra لا occurring:',
          options: ['after أنْ المصدرية', 'before a قسم', 'with الواو after نفي', 'after حتى'],
          correct: 0,
        },
        {
          title: 'الحروف الزائدة العاملة',
          kind: 'mcq',
          prompt: 'Which extra حروف are governing (عاملة)?',
          options: ['الباء، من، اللام الجارة', 'ما، لا، إنْ', 'الواو، الفاء، ثم', 'هلّا، ألا، لولا'],
          correct: 0,
        },
        {
          title: 'تركيب: عاملة أم غير عاملة من النفي؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف نفي: عاملة or غير عاملة؟',
          source: 'ما (النافية) / لا لنفي الجنس / لن / إنْ (النافية)',
          words: ['ما', 'لا لنفي الجنس', 'لن', 'إنْ'],
          labels: ['غير عاملة', 'عاملة', 'عاملة', 'غير عاملة'],
          distractors: ['شرطية'],
        },
        {
          title: 'تركيب: مواضع الزيادة',
          kind: 'tarkeeb',
          instruction: 'Classify what follows/precedes each extra حرف.',
          source: 'إنْ الزائدة (بعد ما النافية) / أنْ الزائدة (بعد لمّا الحينية) / لا الزائدة (قبل قسم)',
          words: ['إنْ الزائدة', 'أنْ الزائدة', 'لا الزائدة'],
          labels: ['بعد ما النافية', 'بعد لمّا الحينية', 'قبل القسم'],
          distractors: ['بعد حتى'],
        },
        {
          title: 'تركيب: زائدة عاملة أم لا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each extra حرف: عاملة or غير عاملة؟',
          source: 'الباء (زائدة) / إنْ (زائدة) / اللام الجارة (زائدة)',
          words: ['الباء', 'إنْ', 'اللام الجارة'],
          labels: ['عاملة', 'غير عاملة', 'عاملة'],
          distractors: ['جازمة'],
        },
      ],
    },
    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'الاستفهام والتمني والاستقبال',
      subtitle: 'Interrogatives, Wishing, and the Future — الهمزة وهل, لو للتمني, and السين وسوف',
      concepts: [
        {
          heading: 'حرفا الاستفهام: الهمزة وهل',
          body: `There are two <bdi>حَرْفَا اسْتِفْهَام</bdi>: <bdi>الْهَمْزَة</bdi>, as in <bdi>﴿أَأَنْتُمْ أَعْلَمُ أَمِ اللَّهُ﴾</bdi> and <bdi>﴿أَكَفَرْتُمْ بَعْدَ إِيمَانِكُمْ﴾</bdi>, and <bdi>هَلْ</bdi>, as in <bdi>﴿فَهَلْ أَنْتُمْ مُنْتَهُونَ﴾</bdi> — both enter nominal and جمل فعلية. They differ in three ways: (1) الهمزة serves both <bdi>التَّصْدِيق</bdi> (yes/no) and <bdi>التَّصَوُّر</bdi> (specification), as in <bdi>﴿أَأَرْبَابٌ مُتَفَرِّقُونَ خَيْرٌ أَمِ اللَّهُ الْوَاحِدُ الْقَهَّارُ﴾</bdi>, while هل serves تصديق only (2) الهمزة enters both affirmation and نفي, as in <bdi>﴿أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ﴾</bdi>, while هل enters affirmation only (3) الهمزة precedes a following عطف, as in <bdi>﴿أَوَمَنْ كَانَ مَيْتًا﴾</bdi>, while هل follows it, as in <bdi>﴿وَهَلْ أَتَاكَ حَدِيثُ مُوسَىٰ﴾</bdi>.`,
          sample: `حرفا الاستفهام — الهمزة، هل؛ يدخلان الاسمية والفعلية<br>الفرق ١ (تصديق/تصور) — الهمزة تفيدهما معا؛ هل تصديق فقط<br>الفرق ٢ (النفي) — الهمزة تدخل المثبت والمنفي؛ هل المثبت فقط<br>الفرق ٣ (موقع العطف) — الهمزة تتقدم عليه؛ هل تتأخر عنه`,
          exercise: {
            prompt: `What is the difference between الهمزة and هل in terms of التصديق والتصور؟`,
            kind: 'mcq',
            options: ['الهمزة serves both; هل serves التصديق only', 'هل serves both; الهمزة serves التصديق only', 'Neither ever serves التصور', 'Both serve التصور only, never التصديق'],
            correct: 0,
          },
        },
        {
          heading: 'حرفا التمني غير العاملين، والحرف العامل',
          body: `Two غير عاملة حروف of wishing (<bdi>التَّمَنِّي</bdi>) are <bdi>لَوْ</bdi>, as in <bdi>﴿لَوْ أَنَّ لَنَا كَرَّةً﴾</bdi>, and <bdi>هَلْ</bdi>, as in <bdi>﴿هَلْ لَنَا مِنْ شُفَعَاءَ﴾</bdi>. The one حرف of wishing that IS governing is <bdi>لَيْتَ</bdi> (Module 05).`,
          sample: `حرفا التمني غير العاملين — لو: ﴿لو أن لنا كرة﴾؛ هل: ﴿هل لنا من شفعاء﴾<br>الحرف العامل — ليت`,
          exercise: {
            prompt: `Which حرف of wishing (التمني) is governing (عامل)؟`,
            kind: 'mcq',
            options: ['ليت', 'لو', 'هل', 'لولا'],
            correct: 0,
          },
        },
        {
          heading: 'لو: أربعة استعمالات وكيف تُعرف',
          body: `لو can be <bdi>شَرْط</bdi>, <bdi>تَمَنٍّ</bdi>, <bdi>عَرْض</bdi>, or <bdi>مَصْدَر</bdi> — identified by position: at the start of a جملة, with a جواب present it is شرط, as in <bdi>لَوْ صَدَقَ لَنَجَا</bdi>; without a جواب, before something whose occurrence was missed, it is تمنٍّ, as in <bdi>لَوْ صَدَقَ</bdi>; before something whose occurrence is anticipated, it is عرض. Mid-sentence after <bdi>وَدّ</bdi>, it is مصدر, as in <bdi>أَوَدُّ لَوْ تَصْدُقُ</bdi>.`,
          sample: `لو (٤ استعمالات) — شرط (بجواب): لو صدق لنجا؛ تمنٍّ (بلا جواب، فائت): لو صدقَ؛ عرض (بلا جواب، مرجو)؛ مصدر (بعد ودّ): أودّ لو تصدق`,
          exercise: {
            prompt: `How do you tell whether لو is شرط or تمنٍّ, when both occur at the start of a جملة؟`,
            kind: 'mcq',
            options: ['شرط has a جواب present; تمنٍّ has none, and concerns something whose occurrence was missed', 'شرط always precedes a فعل أمر; تمنٍّ never does', 'There is no way to tell them apart at all', 'تمنٍّ always occurs mid-sentence, never at the start'],
            correct: 0,
          },
        },
        {
          heading: 'حرفا الاستقبال: السين وسوف',
          body: `The two future حروف are <bdi>السِّين</bdi>, which affirms the NEAR future — the counterpart of لا — as in <bdi>﴿سَيَقُولُ السُّفَهَاءُ مِنَ النَّاسِ﴾</bdi>, and <bdi>سَوْفَ</bdi>, which affirms the DISTANT future — the counterpart of لن — as in <bdi>﴿سَوْفَ تَعْلَمُونَ﴾</bdi>. السين is nicknamed <bdi>حَرْفُ تَنْفِيس</bdi>; سوف is nicknamed <bdi>حَرْفُ تَسْوِيف</bdi>. سوف spans a longer time, as in <bdi>سَيَشِبُّ الْغُلَامُ وَسَوْفَ يَشِيخُ الْفَتَىٰ</bdi>.`,
          sample: `السين — المستقبل القريب، نقيض لا: ﴿سيقول السفهاء من الناس﴾، لقبها حرف تنفيس<br>سوف — المستقبل البعيد، نقيض لن: ﴿سوف تعلمون﴾، لقبها حرف تسويف؛ أطول مدى من السين`,
          exercise: {
            prompt: `What are السين and سوف each nicknamed, and which covers a longer span of time؟`,
            kind: 'mcq',
            options: ['السين is حرف تنفيس; سوف is حرف تسويف — سوف spans a longer time', 'السين is حرف تسويف; سوف is حرف تنفيس — السين spans a longer time', 'Both are nicknamed identically, with no difference in span', 'Neither has a nickname at all'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the two حرفا الاستفهام.',
          options: ['الهمزة، هل', 'ما، من', 'أي، كيف', 'متى، أين'],
          correct: 0,
        },
        {
          q: 'هل, unlike الهمزة, serves only:',
          options: ['التصديق', 'التصور', 'both equally', 'neither'],
          correct: 0,
        },
        {
          q: '﴿أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ﴾ shows الهمزة entering a جملة that is:',
          options: ['منفية (negated)', 'مثبتة فقط', 'استفهامية فقط بلا نفي', 'شرطية'],
          correct: 0,
        },
        {
          q: 'ليت is the one حرف of wishing that is:',
          options: ['governing (عامل)', 'non-governing, like لو and هل', 'restricted to poetry', 'identical to لو in every respect'],
          correct: 0,
        },
        {
          q: 'أَوَدُّ لَوْ تَصْدُقُ — لو here (mid-sentence, after ودّ) is:',
          options: ['مصدر', 'شرط', 'تمنٍّ', 'عرض'],
          correct: 0,
        },
        {
          q: 'سوف affirms the:',
          options: ['distant future, counterpart of لن', 'near future, counterpart of لا', 'immediate past', 'ongoing present'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الهمزة وهل يدخلان الجملتين',
          kind: 'mcq',
          prompt: 'الهمزة وهل can both enter:',
          options: ['nominal and فعلية جمل alike', 'nominal جمل only', 'فعلية جمل only', 'neither type of جملة'],
          correct: 0,
        },
        {
          title: 'الهمزة للتصور',
          kind: 'mcq',
          prompt: '﴿أَأَرْبَابٌ مُتَفَرِّقُونَ خَيْرٌ أَمِ اللَّهُ الْوَاحِدُ الْقَهَّارُ﴾ illustrates الهمزة serving:',
          options: ['التصور (specification)', 'التصديق فقط', 'الشرط', 'العرض'],
          correct: 0,
        },
        {
          title: 'هل للتصديق فقط',
          kind: 'mcq',
          prompt: '﴿هَلْ أُنَبِّئُكُمْ بِشَرٍّ مِنْ ذَٰلِكَ مَثُوبَةً﴾ illustrates هل serving:',
          options: ['التصديق only', 'التصور only', 'both equally', 'neither'],
          correct: 0,
        },
        {
          title: 'موقع الهمزة من العطف',
          kind: 'mcq',
          prompt: '﴿أَوَمَنْ كَانَ مَيْتًا﴾ shows الهمزة positioned:',
          options: ['before the عطف', 'after the عطف', 'nowhere near any عطف', 'replacing the عطف entirely'],
          correct: 0,
        },
        {
          title: 'موقع هل من العطف',
          kind: 'mcq',
          prompt: '﴿وَهَلْ أَتَاكَ حَدِيثُ مُوسَىٰ﴾ shows هل positioned:',
          options: ['after the عطف', 'before the عطف', 'nowhere near any عطف', 'replacing the عطف entirely'],
          correct: 0,
        },
        {
          title: 'لو للتمني',
          kind: 'mcq',
          prompt: '﴿لَوْ أَنَّ لَنَا كَرَّةً﴾ shows لو functioning as a حرف of:',
          options: ['التمني, غير عامل', 'الشرط, عامل', 'العرض المحض', 'الاستفهام المحض'],
          correct: 0,
        },
        {
          title: 'هل للتمني',
          kind: 'mcq',
          prompt: '﴿هَلْ لَنَا مِنْ شُفَعَاءَ﴾ shows هل functioning as a حرف of:',
          options: ['التمني', 'الاستفهام المحض فقط', 'العرض', 'الشرط'],
          correct: 0,
        },
        {
          title: 'لو شرطا',
          kind: 'mcq',
          prompt: 'لَوْ صَدَقَ لَنَجَا — with a جواب present, لو here is:',
          options: ['شرط', 'تمنٍّ', 'عرض', 'مصدر'],
          correct: 0,
        },
        {
          title: 'لو تمنيا',
          kind: 'mcq',
          prompt: 'لَوْ صَدَقَ, with no جواب, about something whose occurrence was missed, is:',
          options: ['تمنٍّ', 'شرط', 'عرض', 'مصدر'],
          correct: 0,
        },
        {
          title: 'السين للمستقبل القريب',
          kind: 'mcq',
          prompt: '﴿سَيَقُولُ السُّفَهَاءُ مِنَ النَّاسِ﴾ shows السين affirming:',
          options: ['المستقبل القريب', 'المستقبل البعيد', 'الماضي القريب', 'الحال المستمر'],
          correct: 0,
        },
        {
          title: 'سوف للمستقبل البعيد',
          kind: 'mcq',
          prompt: '﴿سَوْفَ تَعْلَمُونَ﴾ shows سوف affirming:',
          options: ['المستقبل البعيد', 'المستقبل القريب', 'الحال', 'الماضي'],
          correct: 0,
        },
        {
          title: 'لقب السين',
          kind: 'mcq',
          prompt: 'السين is nicknamed:',
          options: ['حرف تنفيس', 'حرف تسويف', 'حرف تحقيق', 'حرف تعليق'],
          correct: 0,
        },
        {
          title: 'لقب سوف',
          kind: 'mcq',
          prompt: 'سوف is nicknamed:',
          options: ['حرف تسويف', 'حرف تنفيس', 'حرف تحقيق', 'حرف تشبيه'],
          correct: 0,
        },
        {
          title: 'تركيب: فروق الهمزة وهل',
          kind: 'tarkeeb',
          instruction: 'Classify each trait: خاص بالهمزة, خاص بهل, or مشترك بينهما؟',
          source: 'التصور / دخول النفي / تدخل الاسمية والفعلية',
          words: ['التصور', 'دخول النفي', 'تدخل الاسمية والفعلية'],
          labels: ['خاص بالهمزة', 'خاص بالهمزة', 'مشترك بينهما'],
          distractors: ['خاص بهل'],
        },
        {
          title: 'تركيب: استعمالات لو الأربعة',
          kind: 'tarkeeb',
          instruction: 'Classify each لو by its usage.',
          source: 'لو صدق لنجا (بجواب) / أودّ لو تصدق (بعد ودّ)',
          words: ['لو صدق لنجا', 'أودّ لو تصدق'],
          labels: ['شرط', 'مصدر'],
          distractors: ['تمنٍّ'],
        },
        {
          title: 'تركيب: السين وسوف',
          kind: 'tarkeeb',
          instruction: 'Match each حرف استقبال to its scope and nickname.',
          source: 'السين / سوف',
          words: ['السين', 'سوف'],
          labels: ['المستقبل القريب، حرف تنفيس', 'المستقبل البعيد، حرف تسويف'],
          distractors: ['المستقبل المطلق'],
        },
      ],
    },
    // ---------------------------------------------------------------- L6
    {
      id: 'l6',
      title: 'روابط الجواب، والتاء والهاء والتنوين',
      subtitle: 'Loose Ends — فاء/لام الجواب, تاء التأنيث الساكنة, هاء السكت, and the five kinds of تنوين',
      concepts: [
        {
          heading: 'حرفا ربط الجواب',
          body: `Two حروف link a جواب to what precedes it (<bdi>حَرْفَا الرَّبْطِ لِلْجَوَاب</bdi>): <bdi>الْفَاء</bdi>, as in <bdi>﴿مَنْ جَاءَ بِالْحَسَنَةِ فَلَهُ عَشْرُ أَمْثَالِهَا﴾</bdi>, and <bdi>اللَّام</bdi>, as in <bdi>﴿وَلَوْلَا رَهْطُكَ لَرَجَمْنَاكَ﴾</bdi>.`,
          sample: `حرفا ربط الجواب — الفاء: ﴿من جاء بالحسنة فله عشر أمثالها﴾؛ اللام: ﴿ولولا رهطك لرجمناك﴾`,
          exercise: {
            prompt: `What are the two حروف linking a جواب to what precedes it؟`,
            kind: 'mcq',
            options: ['الفاء واللام', 'الواو والثم', 'ما ولا', 'إنْ وإذما'],
            correct: 0,
          },
        },
        {
          heading: 'تاء التأنيث الساكنة، وهاء السكت',
          body: `<bdi>تَاءُ التَّأْنِيثِ السَّاكِنَة</bdi> is a ساكن تاء entering the فعل ماضٍ to show its فاعل is feminine, as in <bdi>﴿قَالَتْ﴾</bdi>. It only takes a vowel for an incidental reason, such as avoiding <bdi>الْتِقَاءَ السَّاكِنَيْن</bdi>, as in <bdi>﴿قَالَتِ امْرَأَةُ فِرْعَوْنَ﴾</bdi> and <bdi>﴿قَالَتَا أَتَيْنَا طَائِعِينَ﴾</bdi>. <bdi>هَاءُ السَّكْت</bdi> is a ساكن هاء attached to words at pause (<bdi>الْوَقْف</bdi>), as in <bdi>﴿مَا أَغْنَىٰ عَنِّي مَالِيَهْ﴾</bdi>.`,
          sample: `تاء التأنيث الساكنة — تدخل الماضي لتأنيث فاعله: ﴿قالتْ﴾؛ تتحرك لعارض كالتقاء الساكنين: ﴿قالتِ امرأة فرعون﴾<br>هاء السكت — هاء ساكنة تلحق الكلمات عند الوقف: ﴿ما أغنى عني ماليهْ﴾`,
          exercise: {
            prompt: `When does تاء التأنيث الساكنة take a vowel rather than staying ساكنة؟`,
            kind: 'mcq',
            options: ['For an incidental reason, e.g. avoiding التقاء الساكنين', 'Only ever with a plural فاعل', 'Only ever in the Qurʾān, never elsewhere', 'It always stays ساكنة, with no exception'],
            correct: 0,
          },
        },
        {
          heading: 'أصل التنوين، وتنوينا التمكين والتنكير',
          body: `<bdi>التَّنْوِين</bdi> originates as a ساكن نون at the end of a word — <bdi>أَحَدٌ</bdi> is in origin <bdi>أَحَدُنْ</bdi>. <bdi>تَنْوِينُ التَّمْكِين</bdi> — also called <bdi>تَنْوِينُ الصَّرْف</bdi> or <bdi>تَنْوِينُ الْأَمْكَنِيَّة</bdi> — attaches to fully declinable (<bdi>مُعْرَبَة مُنْصَرِفَة</bdi>) أسماء, as in <bdi>زَيْدٌ، رَجُلٌ</bdi>. <bdi>تَنْوِينُ التَّنْكِير</bdi> attaches to أسماء الأفعال and some indeclinable أسماء (e.g. proper names ending in <bdi>ـوَيْه</bdi>) to mark indefiniteness — <bdi>صَهٍ</bdi> (be silent about anything) vs <bdi>صَهْ</bdi> (about this specific talk).`,
          sample: `أصل التنوين — نون ساكنة: أحدٌ أصلها أحدُنْ<br>تنوين التمكين (= الصرف = الأمكنية) — يلحق المعربة المنصرفة: زيدٌ، رجلٌ<br>تنوين التنكير — يلحق أسماء الأفعال وبعض الممنوع من الصرف: صهٍ (أي صوت) مقابل صهْ (هذا الصوت)`,
          exercise: {
            prompt: `What is تنوين التمكين, and what other names does it have؟`,
            kind: 'mcq',
            options: ['The تنوين attaching to fully declinable أسماء; also called تنوين الصرف and تنوين الأمكنية', 'The تنوين marking indefiniteness on أسماء الأفعال; also called تنوين التنكير', 'The تنوين compensating for a dropped letter; also called تنوين التعويض', 'A rare fifth تنوين used only in poetry'],
            correct: 0,
          },
        },
        {
          heading: 'تنوين المقابلة والتعويض',
          body: `<bdi>تَنْوِينُ الْمُقَابَلَة</bdi> attaches to the sound feminine plural, as in <bdi>مُسْلِمَاتٍ</bdi> — it "corresponds" to the نون of the sound masculine plural. <bdi>تَنْوِينُ التَّعْوِيض</bdi> compensates for something omitted, in three varieties: for a letter, as in <bdi>﴿غَوَاشٍ﴾</bdi> (origin: <bdi>غَوَاشِي</bdi>); for a word, as in <bdi>﴿وَكُلٌّ آمَنَ﴾</bdi> (= <bdi>كُلُّ أَحَدٍ</bdi>); for a جملة, as in <bdi>﴿وَيَوْمَئِذٍ يَفْرَحُ الْمُؤْمِنُونَ﴾</bdi>.`,
          sample: `تنوين المقابلة — يقابل نون جمع المذكر السالم: مسلماتٍ<br>تنوين التعويض (٣ أنواع) — عن حرف: ﴿غواشٍ﴾ (أصلها غواشي)؛ عن كلمة: ﴿وكلٌّ آمن﴾ (= كل أحد)؛ عن جملة: ﴿ويومئذٍ يفرح المؤمنون﴾`,
          exercise: {
            prompt: `What is تنوين التعويض, and how many varieties does it have؟`,
            kind: 'mcq',
            options: ['Compensation تنوين, in three varieties: for a letter, a word, or a جملة', 'A تنوين marking indefiniteness only, with one variety', 'The same thing as تنوين التمكين, with no distinct varieties', 'A تنوين exclusive to the sound feminine plural'],
            correct: 0,
          },
        },
        {
          heading: 'تنوين الترنم، وحروف صدر الكلام',
          body: `Some grammarians add a fifth تنوين, <bdi>تَنْوِينُ التَّرَنُّم</bdi> — attached to "open" rhyme-endings (<bdi>الْقَوَافِي الْمُطْلَقَة</bdi>, ending in a madd letter); it can attach to اسم, فعل, or حرف alike, as in <bdi>أَقِلِّي اللَّوْمَ عَاذِلَ وَالْعِتَابَنْ</bdi>. Separately: several حرف families may only occur at <bdi>صَدْرُ الْكَلَام</bdi> (the very start of the utterance) — <bdi>حُرُوفُ النَّفْي، التَّنْبِيه، الِاسْتِفْهَام، الشَّرْط، التَّحْضِيض</bdi>, and <bdi>الْحُرُوفُ الْمُشَبَّهَةُ بِالْفِعْل</bdi> — except <bdi>أَنَّ</bdi>.`,
          sample: `تنوين الترنم — خامس عند بعضهم، يلحق القوافي المطلقة، ويدخل الاسم والفعل والحرف: أقلي اللوم عاذل والعتابنْ<br>حروف صدر الكلام — النفي، التنبيه، الاستفهام، الشرط، التحضيض، المشبهة بالفعل (إلا أنّ)`,
          exercise: {
            prompt: `Which حرف families may only occur at صدر الكلام؟`,
            kind: 'mcq',
            options: ['حروف النفي، التنبيه، الاستفهام، الشرط، التحضيض, and الحروف المشبهة بالفعل (except أنّ)', 'Only حروف الجر, with no exception', 'Only أحرف العطف, with no exception', 'No حرف family is ever restricted to صدر الكلام'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the two حرفا ربط الجواب.',
          options: ['الفاء واللام', 'الواو والثم', 'ما ولا', 'أنْ وإنْ'],
          correct: 0,
        },
        {
          q: '﴿قَالَتِ امْرَأَةُ فِرْعَوْنَ﴾ shows تاء التأنيث الساكنة taking a vowel to avoid:',
          options: ['التقاء الساكنين', 'التنوين', 'الإدغام', 'القلب'],
          correct: 0,
        },
        {
          q: 'هاء السكت is attached to words:',
          options: ['at pause (الوقف)', 'only at the start of a جملة', 'only before a قسم', 'only after النفي'],
          correct: 0,
        },
        {
          q: 'تنوين التمكين attaches to:',
          options: ['fully declinable (معربة منصرفة) أسماء', 'أسماء الأفعال only', 'the sound feminine plural only', 'indeclinable proper names only'],
          correct: 0,
        },
        {
          q: '﴿وَكُلٌّ آمَنَ﴾ (= كل أحد) illustrates تنوين التعويض compensating for:',
          options: ['a word', 'a letter', 'a جملة', 'nothing at all'],
          correct: 0,
        },
        {
          q: 'الحروف المشبهة بالفعل must occur at صدر الكلام, except:',
          options: ['أنّ', 'إنّ', 'كأنّ', 'لعلّ'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الفاء رابطة للجواب',
          kind: 'mcq',
          prompt: '﴿مَنْ جَاءَ بِالْحَسَنَةِ فَلَهُ عَشْرُ أَمْثَالِهَا﴾ shows الفاء functioning as:',
          options: ['رابط للجواب', 'حرف جر', 'حرف تفسير', 'حرف تنبيه'],
          correct: 0,
        },
        {
          title: 'اللام رابطة للجواب',
          kind: 'mcq',
          prompt: '﴿وَلَوْلَا رَهْطُكَ لَرَجَمْنَاكَ﴾ shows اللام functioning as:',
          options: ['رابط للجواب', 'لام الأمر', 'لام التعليل', 'لام الجحود'],
          correct: 0,
        },
        {
          title: 'تاء التأنيث الساكنة تعريفها',
          kind: 'mcq',
          prompt: 'تاء التأنيث الساكنة enters the فعل ماضٍ to show:',
          options: ['its فاعل is feminine', 'its فاعل is plural', 'its مفعول is definite', 'its زمن is مستقبل'],
          correct: 0,
        },
        {
          title: 'هاء السكت مثالها',
          kind: 'mcq',
          prompt: '﴿مَا أَغْنَىٰ عَنِّي مَالِيَهْ﴾ shows هاء السكت attached at:',
          options: ['الوقف (pause)', 'الابتداء', 'الوصل', 'القسم'],
          correct: 0,
        },
        {
          title: 'أصل التنوين',
          kind: 'mcq',
          prompt: 'أَحَدٌ is, in origin:',
          options: ['أَحَدُنْ, with a ساكن نون', 'أَحَدَتْ, with a تاء', 'أَحَدَهْ, with a هاء', 'unrelated to any original نون'],
          correct: 0,
        },
        {
          title: 'أسماء تنوين التمكين',
          kind: 'mcq',
          prompt: 'تنوين التمكين is also called:',
          options: ['تنوين الصرف and تنوين الأمكنية', 'تنوين التنكير and تنوين المقابلة', 'تنوين التعويض and تنوين الترنم', 'تنوين النكرة المحضة'],
          correct: 0,
        },
        {
          title: 'تنوين التنكير مثاله',
          kind: 'mcq',
          prompt: 'صَهٍ (be silent about anything, versus صَهْ about this specific talk) illustrates:',
          options: ['تنوين التنكير', 'تنوين التمكين', 'تنوين المقابلة', 'تنوين التعويض'],
          correct: 0,
        },
        {
          title: 'تنوين المقابلة مثاله',
          kind: 'mcq',
          prompt: 'مُسْلِمَاتٍ illustrates:',
          options: ['تنوين المقابلة', 'تنوين التمكين', 'تنوين التنكير', 'تنوين الترنم'],
          correct: 0,
        },
        {
          title: 'تنوين التعويض عن حرف',
          kind: 'mcq',
          prompt: '﴿غَوَاشٍ﴾ (origin: غواشي) illustrates تنوين التعويض compensating for:',
          options: ['a letter', 'a word', 'a جملة', 'nothing'],
          correct: 0,
        },
        {
          title: 'تنوين التعويض عن جملة',
          kind: 'mcq',
          prompt: '﴿وَيَوْمَئِذٍ يَفْرَحُ الْمُؤْمِنُونَ﴾ illustrates تنوين التعويض compensating for:',
          options: ['a جملة', 'a letter', 'a word', 'nothing'],
          correct: 0,
        },
        {
          title: 'تنوين الترنم',
          kind: 'mcq',
          prompt: 'تنوين الترنم attaches to رhyme-endings and can enter:',
          options: ['اسم, فعل, and حرف alike', 'اسم only', 'فعل only', 'حرف only'],
          correct: 0,
        },
        {
          title: 'الاستثناء من صدر الكلام',
          kind: 'mcq',
          prompt: 'Among الحروف المشبهة بالفعل, which one is exempt from requiring صدر الكلام؟',
          options: ['أنّ', 'إنّ', 'ليت', 'لكنّ'],
          correct: 0,
        },
        {
          title: 'تركيب: أنواع التنوين الخمسة',
          kind: 'tarkeeb',
          instruction: 'Classify each example by which تنوين it illustrates.',
          source: 'زيدٌ / صهٍ (أي صوت) / مسلماتٍ / ﴿وكلٌّ آمن﴾',
          words: ['زيدٌ', 'صهٍ', 'مسلماتٍ', 'وكلٌّ آمن'],
          labels: ['تنوين التمكين', 'تنوين التنكير', 'تنوين المقابلة', 'تنوين التعويض'],
          distractors: ['تنوين الترنم'],
        },
        {
          title: 'تركيب: حرفا الربط',
          kind: 'tarkeeb',
          instruction: 'Classify which رابط each example uses.',
          source: '﴿من جاء بالحسنة فله عشر أمثالها﴾ / ﴿ولولا رهطك لرجمناك﴾',
          words: ['فله', 'لرجمناك'],
          labels: ['الفاء', 'اللام'],
          distractors: ['الواو'],
        },
        {
          title: 'تركيب: تاء التأنيث أم هاء السكت؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: تاء التأنيث الساكنة or هاء السكت؟',
          source: '﴿قالتْ﴾ / ﴿ما أغنى عني ماليهْ﴾',
          words: ['قالتْ', 'ماليهْ'],
          labels: ['تاء التأنيث الساكنة', 'هاء السكت'],
          distractors: ['تنوين التعويض'],
        },
      ],
    },
  ],
};
