// Module 26 — بقية المفعولات (The Remaining Objects)
//
// Source: app-lessons/129-al-mafool-bihi-taqdim.md through
// app-lessons/132-al-mafool-maahu.md. Covers the four remaining منصوبات
// after المفعول المطلق (already Module 25): المفعول به's تقديم/تأخير rules,
// المفعول فيه (الظرف), المفعول له, and المفعول معه. Authored out of order,
// following the same 2026-08-12 precedent used throughout this course
// (Modules 04/06/07/08/09/10/11/13/15/16/17/18/19) — Modules 20-25 are not
// yet authored, but 129-132 stand on their own regardless of what precedes
// them in app-lessons. NOT YET registered in content/annahw.js: that
// registry is shared with concurrent sessions authoring earlier modules,
// so wiring it in is left for a later merge pass.
//
// Chapter: المعمول وغير المعمول — الاسم والفعل (per COURSE-MAP.md), covering
// app-lessons/124-140, الفاعل through النعت. This module picks up right
// after Module 25's المفعول المطلق.
//
// Concept bodies use the lines[]/box/table/tarkeebDiagram shape established
// by Module 01 and every module since. Bank تركيب items use the flat
// words[]/labels[]/distractors[] schema, matching this course's convention.
// Each lesson's bank draws only on the ayat, hadith, and constructed
// examples app-lessons itself supplies for these four objects — no invented
// grammar rules or examples.
export default {
  id: '26',
  title: 'بقية المفعولات',
  heading: 'المعمول وغير المعمول',
  subheading: 'الاسم والفعل',
  blurb: 'المفعول به\'s جوازًا and وجوبًا fronting rules, المفعول فيه (الظرف) split by زمان/مكان and مبهم/محدود, المفعول له and the four شروط that let it take direct نصب, and المفعول معه\'s واو المعية — four منصوبات closing out the family that opened with المفعول المطلق.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'تقديم المفعول',
      subtitle: 'The Direct Object\'s Word Order — إياك نعبد\'s جوازًا fronting, and the وجوبًا fronting that صدارة الكلام forces',
      concepts: [
        {
          heading: 'تعريف المفعول به',
          lines: [
            { html: `المفعول به is the second of المنصوبات, right after المفعول المطلق, and one of the most common of all منصوبات — so common that it has already turned up repeatedly as an illustrative example in other chapters, such as الفاعل ونائبه.`, list: false },
            { box: { title: 'Definition', lines: [`المَفْعولُ بِهِ: ما وَقَعَ عَلَيْهِ فِعْلُ الفاعِلِ`] } },
            { html: `A مفعول به is the noun that the doer's action falls upon.`, list: false },
            { box: { title: 'Example', lines: [`اُعْبُدوا رَبَّكُمْ`] } },
            { html: `In ﴿اُعْبُدوا رَبَّكُمْ﴾, <bdi>رَبَّكُمْ</bdi> is مفعول به: the action of عبادة falls on it.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿اُعْبُدوا رَبَّكُمْ﴾, which word is المفعول به, and why؟`,
            kind: 'mcq',
            options: [`رَبَّكُمْ — the action of عبادة falls upon it`, `اُعْبُدوا — it names the action itself`, `الكاف alone — it is the addressee`, `There is no مفعول به in this ayah`],
            correct: 0,
          },
        },
        {
          heading: 'الأصل في ترتيب المفعول به',
          lines: [
            { box: { title: 'Rule', lines: [`الأَصْلُ في المَفْعولِ بِهِ أَنْ يَكونَ بَعْدَ الفِعْلِ وَالفاعِلِ`] } },
            { html: `The default (الأصل) word order for a جملة فعلية is فعل, then فاعل, then مفعول به — as in <bdi>يَعبُدُ العبدُ ربَّه</bdi>.`, list: false },
            { html: `المفعول به may — and in some cases must — front ahead of this order, moving before الفعل and so before الفاعل as well. The rest of this lesson covers exactly when.`, list: false },
          ],
          exercise: {
            prompt: `يَعبُدُ العبدُ ربَّه follows الترتيب الأصلي for a جملة فعلية containing a مفعول به. What is that order؟`,
            kind: 'mcq',
            options: [`فعل، ثم فاعل، ثم مفعول به`, `مفعول به، ثم فعل، ثم فاعل`, `فاعل، ثم مفعول به، ثم فعل`, `مفعول به، ثم فاعل، ثم فعل`],
            correct: 0,
          },
        },
        {
          heading: 'تقديمه جوازًا: التوكيد والاختصاص',
          lines: [
            { html: `المفعول به may front ahead of الفعل والفاعل جوازًا (optionally), for a rhetorical purpose, without anything in the sentence's own structure requiring it.`, list: false },
            { html: `Two purposes commonly explain such fronting: (1) <bdi>توكيد</bdi> — emphasis, (2) <bdi>اختصاص</bdi> — restricting the action to that one object, to the exclusion of others.`, list: false },
            { box: { title: 'Example', lines: [`إِيَّاكَ نَعْبُدُ`] } },
            { html: `In ﴿إِيَّاكَ نَعْبُدُ﴾, <bdi>إِيَّاكَ</bdi> fronts ahead of <bdi>نَعْبُدُ</bdi> and its hidden فاعل, <bdi>نحن</bdi>, meaning: we worship You, and You alone — no one else.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `إِيَّاكَ نَعْبُدُ`,
                translation: `You [alone] we worship.`,
                cells: [`إِيَّاكَ`, `نَعْبُدُ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `مفعول به مقدم` }, { start: 1, end: 1, role: `فعل مضارع مرفوع وفاعله المستتر (نحن)` }] },
                ],
              },
            },
          ],
          exercise: {
            prompt: `إِيَّاكَ fronts ahead of نَعْبُدُ in ﴿إِيَّاكَ نَعْبُدُ﴾ without anything in the sentence's structure forcing it. What kind of fronting is this, and for what purpose؟`,
            kind: 'mcq',
            options: [`تقديم جوازًا, for توكيد واختصاص`, `تقديم وجوبًا, because إياك is اسم شرط`, `تقديم وجوبًا, because إياك is اسم استفهام`, `لا تقديم هنا أصلًا`],
            correct: 0,
          },
        },
        {
          heading: 'تقديمه وجوبًا: صدارة الكلام',
          lines: [
            { html: `Fronting المفعول به becomes obligatory (وجوبًا) whenever it belongs to a class of words carrying <bdi>صَدارَةُ الكَلامِ</bdi> — the inherent right to open the sentence, a position they can never be pushed back from.`, list: false },
            { box: { title: 'Rule', lines: [`١) اسم الشرط؛ ٢) اسم الاستفهام`] } },
            { box: { title: 'Example', lines: [`أَيًّا مَّا تَدْعُوا`] } },
            { html: `In ﴿أَيًّا مَّا تَدْعُوا﴾, <bdi>أَيّا</bdi> is مفعول به مقدم for <bdi>تَدْعُوا</bdi>, fronted precisely because, as اسم شرط, it carries صدارة الكلام.`, list: false },
            { box: { title: 'Example', lines: [`فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ`] } },
            { html: `In ﴿فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ﴾, <bdi>أَيَّ</bdi> is مفعول به مقدم for <bdi>تُنْكِرونَ</bdi>, fronted because, as استفهام, it too carries صدارة الكلام — it would not be valid to instead say تُنكِرون أَيَّ آياتِ اللهِ, leaving أَيَّ in the "normal" post-verbal position.`, list: false },
          ],
          exercise: {
            prompt: `Why must أَيَّ front in ﴿فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ﴾, rather than staying after تُنكِرُونَ the way an ordinary مفعول به would؟`,
            kind: 'mcq',
            options: [`It is اسم استفهام, and اسم الاستفهام carries صدارة الكلام, which can never be pushed back from the sentence's opening`, `آيات الله must always come first in any جملة`, `تنكرون requires two مفعولات`, `فأي is actually الفاعل here, not المفعول به`],
            correct: 0,
          },
        },
        {
          heading: 'كم الخبرية: مُلحَقة بالاستفهام في الصدارة',
          lines: [
            { box: { title: 'Careful', lines: [`كَمِ الخَبَرِيَّةِ تُلْحَقُ بِالاسْتِفْهامِ في وُجوبِ التَّقْديمِ`] } },
            { html: `<bdi>كم الخبرية</bdi> — كم used to mean "how many!", expressing abundance, not a real question — is attached to الاستفهام for this same obligatory-fronting rule.`, list: false },
            { box: { title: 'Example', lines: [`وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ`] } },
            { html: `In ﴿وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ﴾, كم is not a genuine question — the meaning is roughly "and We sent many a prophet..." Even so, because كم originates as one of أدوات الاستفهام, it still retains صدارة الكلام, so whatever depends on it must front exactly as it does with a true استفهام.`, list: false },
          ],
          exercise: {
            prompt: `كم in ﴿وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ﴾ is خبرية, not a real question. Does it still have to front ahead of أَرْسَلْنَا؟`,
            kind: 'mcq',
            options: [`Yes — because it originates as one of أدوات الاستفهام, it keeps صدارة الكلام`, `No — only a genuine question forces fronting`, `No — كم الخبرية never behaves like الاستفهام`, `Yes, but only in Qur'anic Arabic`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `What is the correct definition of المفعول به؟`, options: [`That upon which the doer's action falls`, `The reason behind the doer's action`, `That in which the action takes place`, `That which occurred together with the doer`], correct: 0 },
        { q: `What is the default (الأصل) word order for a جملة فعلية containing a مفعول به؟`, options: [`فعل ثم فاعل ثم مفعول به`, `مفعول به ثم فعل ثم فاعل`, `فاعل ثم مفعول به ثم فعل`, `مفعول به ثم فاعل ثم فعل`], correct: 0 },
        { q: `In ﴿إِيَّاكَ نَعْبُدُ﴾, المفعول به إِيَّاكَ fronts ahead of الفعل and its hidden فاعل. Why does this fronting happen, given that nothing in the sentence structurally forces it؟`, options: [`جوازًا, for توكيد and اختصاص`, `وجوبًا, because إياك is اسم شرط`, `وجوبًا, because إياك is اسم استفهام`, `جوازًا, to avoid ambiguity with الفاعل`], correct: 0 },
        { q: `﴿أَيًّا مَّا تَدْعُوا﴾ fronts أَيًّا ahead of the فعل تَدْعُوا. Why is this fronting obligatory (وجوبًا)؟`, options: [`أَيًّا is اسم شرط, and اسم الشرط carries صدارة الكلام`, `أَيًّا is صفة for تَدْعُوا`, `أَيًّا is مفعول مطلق`, `It is not actually obligatory here`], correct: 0 },
        { q: `In ﴿فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ﴾, it would not be valid to instead say تُنكِرون أَيَّ آياتِ اللهِ, leaving أَيَّ after the فعل. What forces أَيَّ to the front؟`, options: [`It is اسم استفهام, and اسم الاستفهام carries صدارة الكلام`, `It is مفعول مطلق`, `It is فاعل`, `الآيات must always precede its فعل`], correct: 0 },
        { q: `﴿وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ﴾ uses كم to mean "how many!" rather than as a real question. Does this كم still have to front ahead of أَرْسَلْنَا؟`, options: [`Yes — كم الخبرية is attached to الاستفهام for the same صدارة الكلام rule`, `No — only a genuine question forces fronting`, `No — كم الخبرية never carries صدارة الكلام`, `Yes, but only when كم means a real question`], correct: 0 },
      ],
      bank: [
        { title: `تعريف المفعول به`, kind: 'mcq', prompt: `Which of the following correctly defines المفعول به؟`, options: [`ما وقع عليه فعل الفاعل`, `ما وقع لأجله الفعل`, `ما وقع فيه الفعل من المكان أو الزمان`, `ما وقع معه الفعل`], correct: 0 },
        { title: `اعبدوا ربكم: تحديد المفعول به`, kind: 'mcq', prompt: `In ﴿اُعْبُدوا رَبَّكُمْ﴾, which word is المفعول به؟`, options: [`رَبَّكُمْ`, `اُعْبُدوا`, `الكاف وحدها`, `لا يوجد مفعول به هنا`], correct: 0 },
        { title: `الترتيب الأصلي`, kind: 'mcq', prompt: `What is الأصل (default order) for المفعول به relative to الفعل والفاعل؟`, options: [`It comes after both الفعل and الفاعل`, `It comes before الفعل`, `It comes between الفعل and الفاعل`, `Its position is entirely free`], correct: 0 },
        { title: `إياك نعبد: غرض التقديم`, kind: 'mcq', prompt: `إِيَّاكَ fronts in ﴿إِيَّاكَ نَعْبُدُ﴾ for two rhetorical purposes. What are they؟`, options: [`توكيد واختصاص`, `تعليل وتفسير`, `تحذير وإغراء`, `تصديق وتصوّر`], correct: 0 },
        { title: `جوازًا لا وجوبًا`, kind: 'mcq', prompt: `Is the fronting of إِيَّاكَ in ﴿إِيَّاكَ نَعْبُدُ﴾ required by the sentence's structure, or optional؟`, options: [`Optional (جوازًا) — nothing in the structure requires it`, `Obligatory (وجوبًا) — إياك has صدارة الكلام`, `Obligatory, because إياك is اسم شرط`, `Obligatory, because إياك is اسم استفهام`], correct: 0 },
        { title: `صدارة الكلام`, kind: 'mcq', prompt: `What does it mean for a word to have صدارة الكلام؟`, options: [`It has the inherent right to open the sentence and can never be pushed back from that position`, `It must always be مرفوع`, `It can only appear after a حرف جر`, `It is always the مفعول المطلق of its جملة`], correct: 0 },
        { title: `أيا ما تدعوا: سبب التقديم`, kind: 'mcq', prompt: `In ﴿أَيًّا مَّا تَدْعُوا﴾, أَيًّا is مفعول به مقدم. Why must it front ahead of تَدْعُوا؟`, options: [`Because it is اسم شرط, which carries صدارة الكلام`, `Because every مفعول به must front in a جملة شرطية`, `Because ما after it is زائدة`, `Because تدعوا is مجزوم`], correct: 0 },
        { title: `أي آيات الله: سبب التقديم`, kind: 'mcq', prompt: `In ﴿فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ﴾, أَيَّ is مفعول به مقدم. Why must it front ahead of تُنكِرُونَ؟`, options: [`Because it is اسم استفهام, which carries صدارة الكلام`, `Because آيات is مضاف إليه`, `Because الفعل هنا مضارع`, `Because فأي always follows الفاء`], correct: 0 },
        { title: `لا يجوز تأخيره`, kind: 'mcq', prompt: `Why is it invalid to say تُنكِرون أَيَّ آياتِ اللهِ, keeping أَيَّ after الفعل؟`, options: [`Because اسم الاستفهام has صدارة الكلام and can never be pushed back from the sentence's opening`, `Because آيات الله must always be الفاعل`, `Because تنكرون requires a مفعول به مقدم regardless of meaning`, `It is not actually invalid`], correct: 0 },
        { title: `كم الخبرية: طبيعتها`, kind: 'mcq', prompt: `In ﴿وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ﴾, is كم here a genuine question؟`, options: [`No — it is كم الخبرية, expressing abundance, not a real question`, `Yes — it asks how many prophets were sent`, `No — it is كم الاستفهامية asking for a number`, `Yes, but only in poetry`], correct: 0 },
        { title: `كم الخبرية وصدارة الكلام`, kind: 'mcq', prompt: `Even though كم in ﴿وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ﴾ is خبرية and not a real question, why does it still have to front؟`, options: [`Because it originates as one of أدوات الاستفهام, it keeps صدارة الكلام`, `Because every عدد must front`, `Because من نبي is مجرور`, `It does not have to front — the fronting here is only stylistic`], correct: 0 },
        { title: `اسم الشرط واسم الاستفهام: ما يجمعهما`, kind: 'mcq', prompt: `اسم الشرط and اسم الاستفهام both force وجوبًا fronting of المفعول به when they fill that role. What do they share that causes this؟`, options: [`Both carry صدارة الكلام`, `Both are always مبنية`, `Both require a حرف جر before them`, `Both can only appear with أفعال ماضية`], correct: 0 },
        { title: `الفرق بين تقديم جوازًا ووجوبًا`, kind: 'mcq', prompt: `What distinguishes تقديم المفعول به جوازًا from تقديمه وجوبًا؟`, options: [`جوازًا serves a rhetorical purpose without being structurally required; وجوبًا is forced by صدارة الكلام`, `جوازًا only happens with اسم الشرط; وجوبًا only happens with اسم الاستفهام`, `جوازًا happens only in الشعر; وجوبًا happens only in النثر`, `There is no real difference between them`], correct: 0 },
        { title: `يعبد العبد ربه: الترتيب الأصلي`, kind: 'mcq', prompt: `In يَعبُدُ العبدُ ربَّه, which order does this sentence follow؟`, options: [`الترتيب الأصلي: فعل + فاعل + مفعول به`, `تقديم المفعول به جوازًا`, `تقديم المفعول به وجوبًا لأنه اسم شرط`, `تقديم المفعول به وجوبًا لأنه اسم استفهام`], correct: 0 },
        { title: `أدوات تلزم الصدارة`, kind: 'mcq', prompt: `Which of the following, when it is المفعول به of its جملة, must front وجوبًا rather than staying in its default post-verbal position؟`, options: [`اسم استفهام`, `اسم ذات عادي بلا أل`, `مصدر صريح`, `ظرف مبهم`], correct: 0 },
        { title: `اختصاص`, kind: 'mcq', prompt: `اختصاص, one of the rhetorical purposes behind fronting المفعول به جوازًا, is best described as:`, options: [`Restricting the action to that one object alone, to the exclusion of others`, `Asking a genuine question about the object`, `Expressing abundance rather than a real count`, `Marking the object as غير معرفة`], correct: 0 },
        { title: `لماذا لا نقول نعبد إياك`, kind: 'mcq', prompt: `﴿إِيَّاكَ نَعْبُدُ﴾ could grammatically also be phrased نَعْبُدُ إِيَّاكَ. What is lost if the fronting is dropped؟`, options: [`The rhetorical force of توكيد and اختصاص that the fronting conveys`, `The sentence becomes grammatically invalid`, `إياك would no longer be مفعول به`, `نعبد would lose its فاعل`], correct: 0 },
        { title: `استثناء الالتحاق بالاستفهام`, kind: 'mcq', prompt: `كم الخبرية is not itself a question, yet it is treated as if it were, for the purpose of one specific rule. Which rule؟`, options: [`صدارة الكلام, which forces وجوبًا fronting of whatever depends on it`, `علامة الجر`, `شروط الإضافة`, `قاعدة العدد والمعدود`], correct: 0 },
        {
          title: `تركيب: اُعْبُدوا رَبَّكُمْ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿اُعْبُدوا رَبَّكُمْ﴾.`,
          source: `اُعْبُدوا رَبَّكُمْ`,
          words: [`اُعْبُدوا`, `رَبَّ`, `كُمْ`],
          labels: [`فعل أمر وفاعله`, `مفعول به منصوب`, `مضاف إليه`],
          distractors: [`فاعل مرفوع`, `خبر`],
        },
        {
          title: `تركيب: يَعبُدُ العبدُ ربَّه (الترتيب الأصلي)`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in the default-order example يَعبُدُ العبدُ ربَّه.`,
          source: `يَعبُدُ العبدُ ربَّه`,
          words: [`يَعبُدُ`, `العبدُ`, `ربَّه`],
          labels: [`فعل مضارع مرفوع`, `فاعل مرفوع`, `مفعول به منصوب`],
          distractors: [`مبتدأ`, `خبر`],
        },
        {
          title: `تركيب: إِيَّاكَ نَعْبُدُ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in ﴿إِيَّاكَ نَعْبُدُ﴾.`,
          source: `إِيَّاكَ نَعْبُدُ`,
          words: [`إِيَّاكَ`, `نَعْبُدُ`],
          labels: [`مفعول به مقدم`, `فعل مضارع مرفوع وفاعله المستتر`],
          distractors: [`مبتدأ`, `فاعل ظاهر`],
        },
        {
          title: `تركيب: أَيًّا مَّا تَدْعُوا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿أَيًّا مَّا تَدْعُوا﴾.`,
          source: `أَيًّا مَّا تَدْعُوا`,
          words: [`أَيًّا`, `مَّا`, `تَدْعُوا`],
          labels: [`اسم شرط مفعول به مقدم`, `زائدة`, `فعل الشرط`],
          distractors: [`حرف جر`, `فاعل`],
        },
        {
          title: `تركيب: فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ﴾.`,
          source: `فَأَيَّ آيَاتِ اللَّهِ تُنكِرُونَ`,
          words: [`أَيَّ`, `آيَاتِ`, `اللَّهِ`, `تُنكِرُونَ`],
          labels: [`اسم استفهام مفعول به مقدم`, `مضاف`, `مضاف إليه`, `فعل مضارع مرفوع وفاعله`],
          distractors: [`فاعل ظاهر`, `خبر`],
        },
        {
          title: `تركيب: وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ﴾.`,
          source: `وَكَمْ أَرْسَلْنَا مِنْ نَبِيٍّ فِي الْأَوَّلِينَ`,
          words: [`كَمْ`, `أَرْسَلْنَا`, `مِنْ نَبِيٍّ`, `فِي الْأَوَّلِينَ`],
          labels: [`كم الخبرية مفعول به مقدم`, `فعل ماضٍ وفاعله`, `تمييز كم مجرور`, `جار ومجرور`],
          distractors: [`اسم استفهام حقيقي`, `حال`],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'الظرف',
      subtitle: 'The Locative and Temporal Object — ظرف زمان vs مكان, each مبهم or محدود, and what stands in for a ظرف',
      concepts: [
        {
          heading: 'تعريف المفعول فيه (الظرف)',
          lines: [
            { html: `المفعول فيه — "that in which the action takes place" — is the third of the twelve منصوبات, right after المفعول به. It carries two names: <bdi>المفعول فيه</bdi> and <bdi>الظرف</bdi> are simply one formal and one popular label for the same إعراب category.`, list: false },
            { box: { title: 'Definition', lines: [`المفعول فيه (الظرف): هُوَ ما وَقَعَ فيهِ الفِعْلُ مِنَ المَكانِ أَوِ الزَّمانِ`] } },
            { box: { title: 'Example', lines: [`أَحْسِني إِلَى أُمِّكِ أَبَدًا فَإِنَّ الجَنَّةَ تَحْتَ قَدَمَيْها`] } },
            { html: `"Be good to your mother always, for Paradise lies beneath her feet." Here <bdi>تَحْتَ</bdi> is ظرف مكان: the place in which الجنة "exists."`, list: false },
          ],
          exercise: {
            prompt: `In فَإِنَّ الجَنَّةَ تَحْتَ قَدَمَيْها, what role does تَحْتَ play؟`,
            kind: 'mcq',
            options: [`ظرف مكان — the place in which الجنة "exists"`, `مفعول به`, `مضاف إليه`, `فاعل`],
            correct: 0,
          },
        },
        {
          heading: 'أقسام الظرف: زمان ومكان، مبهم ومحدود',
          lines: [
            { box: { title: 'Rule', lines: [`الظرف قِسْمانِ: ظرف زمان وظرف مكان، وكُلُّ واحدٍ منهما نوعانِ: مُبْهَم ومَحْدود`] } },
            { html: `<bdi>ظرف زمان</bdi> denotes الوقت; <bdi>ظرف مكان</bdi> denotes المحل. Each of the two further splits: <bdi>مبهم</bdi> — indefinite, unbounded, broad in reference — versus <bdi>محدود</bdi> — specific, delimited, fixed.`, list: false },
          ],
          exercise: {
            prompt: `الظرف قِسْمانِ at the top level, and each قسم further splits into two. What is that four-way grid؟`,
            kind: 'mcq',
            options: [`ظرف زمان (مبهم/محدود) وظرف مكان (مبهم/محدود)`, `ظرف قياسي وظرف سماعي فقط`, `ظرف أصلي وظرف زائد فقط`, `ظرف لازم وظرف متعدٍ فقط`],
            correct: 0,
          },
        },
        {
          heading: 'ظرف الزمان: المبهم والمحدود',
          lines: [
            { html: `<bdi>المُبْهَم</bdi> is a زمان not specifically defined, such as <bdi>أَبَد، حِين، وَقْت، زَمان</bdi>.`, list: false },
            { table: { title: 'ظرف الزمان المبهم', headers: ['مثال', 'نصب أم جر', 'الآية'], rows: [
              [`حِين`, `نصب بحرف جر مقدَّر`, `﴿يَرَاكَ حِينَ تَقُومُ﴾`],
              [`حِين`, `جر بحرف جر ظاهر`, `﴿وَمَتَّعْنَاهُمْ إِلَىٰ حِينٍ﴾`],
            ] } },
            { html: `<bdi>المَحْدود</bdi> is a زمان specifically defined, such as <bdi>ساعة، يوم، ليلة، أسبوع، شهر، سنة، عام</bdi>.`, list: false },
            { table: { title: 'ظرف الزمان المحدود', headers: ['مثال', 'نصب أم جر', 'الآية'], rows: [
              [`يوم القيامة`, `نصب بحرف جر مقدَّر`, `﴿وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ﴾`],
              [`يوم القيامة`, `جر بحرف جر ظاهر`, `﴿يَجْمَعُكُمْ إِلَىٰ يَوْمِ الْقِيَامَةِ﴾`],
            ] } },
          ],
          exercise: {
            prompt: `حِين and يوم القيامة can each appear either نصبًا بحرف جر مقدَّر or جرًّا بحرف جر ظاهر, depending on the sentence. What does this show about ظرف الزمان — both مبهم ومحدود؟`,
            kind: 'mcq',
            options: [`Both مبهم and محدود ظرف الزمان can take نصب بحرف جر مقدَّر, unlike ظرف المكان المحدود`, `Only المبهم can ever take نصب`, `Only المحدود can ever take نصب`, `Neither can ever take نصب — both are always مجرورة`],
            correct: 0,
          },
        },
        {
          heading: 'ظرف المكان: المبهم والمحدود',
          lines: [
            { html: `<bdi>المُبْهَم</bdi> in ظرف المكان covers <bdi>الجهات الست</bdi> — فوق، تحت، يمين، شمال، أمام، خلف — and <bdi>المقادير</bdi>, measures of distance such as <bdi>ميل</bdi> and <bdi>فرسخ</bdi>.`, list: false },
            { table: { title: 'ظرف المكان المبهم', headers: ['مثال', 'نصب أم جر', 'الآية'], rows: [
              [`خَلْفَ`, `نصب`, `﴿لِتَكُونَ لِمَن خَلْفَكَ آيَةً﴾`],
              [`خَلْفَ`, `جر`, `﴿لَوْ تَرَكُوا مِنْ خَلْفِهِمْ ذُرِّيَّةً ضِعَافًا﴾`],
            ] } },
            { html: `<bdi>المَحْدود</bdi> in ظرف المكان is a place specifically defined, such as <bdi>الأرض</bdi>.`, list: false },
            { box: { title: 'Example', lines: [`لَا تُفْسِدُوا فِي الْأَرْضِ`] } },
            { html: `Unlike ظرف الزمان المحدود, ظرف المكان المحدود is, in الأصل, جر بحرف جر ظاهر فقط — it cannot take نصب بحرف جر مقدَّر.`, list: false },
          ],
          exercise: {
            prompt: `﴿لَا تُفْسِدُوا فِي الْأَرْضِ﴾ keeps الأرض جرًّا بحرف جر ظاهر rather than نصبًا. Why, given that الأرض is a ظرف مكان؟`,
            kind: 'mcq',
            options: [`الأرض is ظرف مكان محدود, and المحدود من المكان normally cannot take نصب بحرف جر مقدَّر`, `الأرض is ظرف زمان, not ظرف مكان`, `الأرض is not really الظرف here`, `في here is زائدة`],
            correct: 0,
          },
        },
        {
          heading: 'الاستثناءان في نصب ظرف المكان المحدود',
          lines: [
            { box: { title: 'Careful', lines: [`ظرف المكان المَحْدود لا يُنْصَبُ بحرف جر مقدَّر إلا في موضعين استثنائيين`] } },
            { html: `The first exception: (1) الظرف مشتقّ من لفظ الفعل نفسه.`, list: false },
            { box: { title: 'Example', lines: [`كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ`] } },
            { html: `<bdi>مَقَاعِد</bdi> shares its root with <bdi>نَقْعُد</bdi>, so it can take نصب despite being محدود.`, list: false },
            { html: `The second exception: (2) a handful of particular verbs heard this way from the Arabs and not to be generalized by analogy — <bdi>الدخول</bdi> (﴿فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ﴾), <bdi>السكون</bdi> (﴿اسْكُنْ أَنتَ وَزَوْجُكَ الْجَنَّةَ﴾), و<bdi>النزول</bdi> (نزل المدينةَ).`, list: false },
            { html: `In every other verb, ظرف المكان المحدود must stay جر بحرف جر ظاهر — because القواعد describe how the Arabs actually spoke; they do not legislate how speech ought to be constructed.`, list: false },
          ],
          exercise: {
            prompt: `فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ places الجنة into النصب, even though it is ظرف مكان محدود and not derived from يَدْخُلُونَ's own root. What licenses this؟`,
            kind: 'mcq',
            options: [`دَخَلَ is one of a handful of specific verbs heard this way from the Arabs, an exception not to be generalized to any other فعل`, `الجنة is secretly ظرف زمان here`, `الجنة functions as مفعول به, not الظرف`, `Every فعل لازم allows this نصب`],
            correct: 0,
          },
        },
        {
          heading: 'ما يقوم مقام المفعول فيه',
          lines: [
            { html: `Several things that are not ظرف in their own essence may stand in for it, as long as they convey الظرفية through their own إضافة or context.`, list: false },
            { box: { title: 'Example', lines: [`وَمِنَ اللَّيْلِ فَسَبِّحْهُ وَإِدْبَارَ النُّجُومِ`] } },
            { html: `Meaning <bdi>سَبِّحْهُ وَقْتَ إِدْبارِ النُّجومِ</bdi> — <bdi>إِدْبَار</bdi> is a مصدر, not itself a زمان, but it denotes the timing of the verb's action, so it is إعراب as مفعول فيه.`, list: false },
            { box: { title: 'Example', lines: [`قَالَ لَبِثْتُ يَوْمًا أَوْ بَعْضَ يَوْمٍ`] } },
            { html: `<bdi>بَعْض</bdi> is not itself زمانًا, but having been مضاف to <bdi>يوم</bdi>, it takes on يوم's ruling.`, list: false },
            { box: { title: 'Example', lines: [`أَيَّتُكَ أَلَّا تُكَلِّمَ النَّاسَ ثَلَاثَ لَيَالٍ`] } },
            { html: `<bdi>ثَلَاث</bdi> is a number, مضاف إلى <bdi>ليال</bdi>, so الإضافة itself stands in for an explicit ظرف.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿وَمِنَ اللَّيْلِ فَسَبِّحْهُ وَإِدْبَارَ النُّجُومِ﴾, إِدْبَارَ is a مصدر, not a زمان in itself. Why is it إعراب as المفعول فيه anyway؟`,
            kind: 'mcq',
            options: [`It conveys the meaning of time (وقت إدبار النجوم) through its context`, `Every مصدر is automatically إعراب as ظرف`, `النجوم is مضاف إليه, which forces إدبار into النصب regardless of meaning`, `إدبار is actually مفعول به here`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `المفعول فيه goes by a second, more common name. What is it؟`, options: [`الظرف`, `الحال`, `التمييز`, `المستثنى`], correct: 0 },
        { q: `What is the correct definition of المفعول فيه (الظرف)؟`, options: [`That noun which denotes the place or time in which the verb's action occurred`, `That noun upon which the doer's action falls`, `That noun which the verb's action was performed for`, `That noun signaling accompaniment with what precedes it`], correct: 0 },
        { q: `﴿يَرَاكَ حِينَ تَقُومُ﴾ and ﴿وَمَتَّعْنَاهُمْ إِلَىٰ حِينٍ﴾ both use حِين, a ظرف زمان مبهم. What differs in how حين is إعراب-ed between the two؟`, options: [`In the first it takes نصب بحرف جر مقدر; in the second it takes جر بحرف جر ظاهر`, `In the first it is مرفوع; in the second it is منصوب`, `In the first it is محدود; in the second it is مبهم`, `There is no difference — both are identical`], correct: 0 },
        { q: `الجهات الست (فوق، تحت، يمين، شمال، أمام، خلف) fall under which category of الظرف؟`, options: [`ظرف مكان مبهم`, `ظرف مكان محدود`, `ظرف زمان مبهم`, `ظرف زمان محدود`], correct: 0 },
        { q: `As a general rule, ظرف المكان المحدود (such as الأرض) cannot take نصب by an implied حرف جر — it must be جر بحرف جر ظاهر. In ﴿كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ﴾, مَقَاعِدَ is نصب despite being محدود. What licenses this exception؟`, options: [`مَقَاعِدَ is derived from the very root of its governing فعل, نَقْعُدُ`, `مَقَاعِدَ is actually ظرف مبهم, not محدود`, `السماع here overrides every rule of النحو`, `مَقَاعِدَ is not really الظرف at all — it is مفعول به`], correct: 0 },
        { q: `﴿وَمِنَ اللَّيْلِ فَسَبِّحْهُ وَإِدْبَارَ النُّجُومِ﴾ uses إِدْبَارَ, a مصدر, in the sense of سَبِّحْهُ وَقْتَ إِدْبَارِ النُّجُومِ. What role is إِدْبَارَ playing here, even though it is not itself a زمان؟`, options: [`It stands in for المفعول فيه, since it conveys the meaning of time through its context`, `It is مفعول به for فَسَبِّحْهُ`, `It is حال for النجوم`, `It is تمييز for الليل`], correct: 0 },
      ],
      bank: [
        { title: `اسما المفعول فيه`, kind: 'mcq', prompt: `المفعول فيه and الظرف are:`, options: [`Two names for the same إعراب category`, `Two entirely different إعراب categories`, `المفعول فيه for المكان only, الظرف for الزمان only`, `الظرف for المكان only, المفعول فيه for الزمان only`], correct: 0 },
        { title: `تحت قدميها: تحديد الظرف`, kind: 'mcq', prompt: `In فَإِنَّ الجَنَّةَ تَحْتَ قَدَمَيْها, what role does تَحْتَ play؟`, options: [`ظرف مكان — the place in which الجنة "exists"`, `مفعول به`, `مضاف إليه`, `فاعل`], correct: 0 },
        { title: `قسما الظرف`, kind: 'mcq', prompt: `الظرف قسمان at the top level. What are they؟`, options: [`ظرف زمان وظرف مكان`, `ظرف مبهم وظرف مصدر`, `ظرف قياسي وظرف سماعي`, `ظرف مفرد وظرف مركب`], correct: 0 },
        { title: `نوعا كل قسم`, kind: 'mcq', prompt: `Each of ظرف الزمان and ظرف المكان further divides into two types. What are they؟`, options: [`مبهم ومحدود`, `أصلي وزائد`, `مقدر وظاهر`, `لازم ومتعدٍ`], correct: 0 },
        { title: `أمثلة الزمان المبهم`, kind: 'mcq', prompt: `Which of the following is a ظرف زمان مبهم, unbounded rather than specifically defined؟`, options: [`حِين`, `يوم`, `ساعة`, `أسبوع`], correct: 0 },
        { title: `أمثلة الزمان المحدود`, kind: 'mcq', prompt: `Which of the following is a ظرف زمان محدود, specifically defined rather than unbounded؟`, options: [`يوم القيامة`, `حِين`, `وقت`, `أبد`], correct: 0 },
        { title: `يوم القيامة: نصب أم جر`, kind: 'mcq', prompt: `﴿وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ﴾ puts يَوْمَ into النصب. What licenses this نصب, given that يوم is محدود؟`, options: [`ظرف الزمان المحدود can still take نصب بحرف جر مقدر — unlike ظرف المكان المحدود`, `يوم here is actually ظرف مكان`, `يوم is مبهم here, not محدود`, `يوم is مفعول به here, not ظرف`], correct: 0 },
        { title: `الجهات الست`, kind: 'mcq', prompt: `فوق، تحت، يمين، شمال، أمام، خلف together are known as:`, options: [`الجهات الست`, `المقادير الست`, `أحرف الجر الست`, `أسماء الإشارة الست`], correct: 0 },
        { title: `المقادير`, kind: 'mcq', prompt: `ميل and فرسخ, used as measures of distance, count as which kind of ظرف؟`, options: [`ظرف مكان مبهم`, `ظرف مكان محدود`, `ظرف زمان مبهم`, `ظرف زمان محدود`], correct: 0 },
        { title: `الأرض: لماذا لا تُنصب`, kind: 'mcq', prompt: `﴿لَا تُفْسِدُوا فِي الْأَرْضِ﴾ keeps الأرض جر بحرف جر ظاهر rather than نصب. Why, given الأرض is ظرف مكان؟`, options: [`الأرض is ظرف مكان محدود, and المحدود من المكان normally cannot take نصب بحرف جر مقدر`, `الأرض is ظرف زمان, not ظرف مكان`, `الأرض is not really الظرف here at all`, `في here is زائدة, so الأرض defaults to الجر`], correct: 0 },
        { title: `الاستثناء الأول`, kind: 'mcq', prompt: `مَقَاعِدَ takes نصب in ﴿كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ﴾ even though it is ظرف مكان محدود. What is the first of the two exceptional conditions that allows this؟`, options: [`The ظرف is derived from the very root of its governing فعل`, `The ظرف follows a حرف جر ظاهر`, `The فعل is فعل أمر`, `The ظرف is إضافة إلى ضمير`], correct: 0 },
        { title: `الاستثناء الثاني`, kind: 'mcq', prompt: `فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ puts الْجَنَّةَ into النصب even though it is ظرف مكان محدود and not derived from يَدْخُلُونَ's root. What licenses this؟`, options: [`دَخَلَ is one of a handful of specific verbs heard this way from the Arabs, not to be generalized by analogy`, `الجنة is secretly ظرف زمان`, `الجنة is المفعول به here, not الظرف`, `Every فعل لازم allows this نصب`], correct: 0 },
        { title: `أفعال سماعية أخرى`, kind: 'mcq', prompt: `Besides دَخَلَ, which other verbs are recorded as allowing direct نصب of a ظرف مكان محدود, purely by سماع rather than by a general rule؟`, options: [`سَكَنَ ونَزَلَ`, `ذَهَبَ وَجَاءَ`, `قَامَ وَقَعَدَ`, `عَلِمَ وَظَنَّ`], correct: 0 },
        { title: `لماذا لا يُقاس عليها`, kind: 'mcq', prompt: `Why can't the نصب seen in دخل الجنة, سكن الجنة, and نزل المدينة be generalized to any other فعل + مكان محدود pairing؟`, options: [`Because القواعد describe how the Arabs actually spoke — they do not legislate new speech`, `Because those three verbs are the only أفعال ماضية that exist`, `Because الجنة والمدينة are the only أسماء أماكن in Arabic`, `It actually can be generalized to any verb`], correct: 0 },
        { title: `المصدر قائمًا مقام الظرف`, kind: 'mcq', prompt: `In ﴿وَمِنَ اللَّيْلِ فَسَبِّحْهُ وَإِدْبَارَ النُّجُومِ﴾, إِدْبَارَ is a مصدر, not a ظرف in its own essence. What makes it able to stand in for المفعول فيه here؟`, options: [`It conveys the meaning of time (وقت إدبار النجوم) through its context`, `It is مضاف إلى ضمير`, `It carries تنوين`, `It follows a حرف عطف`], correct: 0 },
        { title: `المضاف إلى الزمان`, kind: 'mcq', prompt: `In ﴿قَالَ لَبِثْتُ يَوْمًا أَوْ بَعْضَ يَوْمٍ﴾, بَعْضَ is not itself a زمان. Why does it still take the ruling of a ظرف؟`, options: [`It is مضاف to يوم, a زمان, and so takes on يوم's ruling`, `It is مصدر قلبي`, `It is عدد صريح`, `أو before it forces the ظرف reading`], correct: 0 },
        { title: `العدد قائمًا مقام الظرف`, kind: 'mcq', prompt: `In ﴿أَلَّا تُكَلِّمَ النَّاسَ ثَلَاثَ لَيَالٍ﴾, ثَلَاثَ is a number, مضاف إلى ليال. What does this إضافة accomplish؟`, options: [`The إضافة itself stands in for an explicit ظرف`, `It turns ثلاث into اسم عين`, `It makes ليال ظرف مكان rather than زمان`, `It has no effect on the إعراب of ليال`], correct: 0 },
        { title: `مراجعة: نوعا كل مثال`, kind: 'mcq', prompt: `Sorting these into their correct pair — حِين (ظرف زمان مبهم) and يوم القيامة (ظرف زمان محدود) — what is the shared test that separates مبهم from محدود؟`, options: [`Whether the ظرف names a time or place specifically defined, or one left broad and unbounded`, `Whether the ظرف carries تنوين`, `Whether the ظرف is مذكر or مؤنث`, `Whether the ظرف follows a فعل ماض or فعل مضارع`], correct: 0 },
        {
          title: `تركيب: أَحْسِنِي إِلَى أُمِّكِ أَبَدًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of أَحْسِنِي إِلَى أُمِّكِ أَبَدًا.`,
          source: `أَحْسِنِي إِلَى أُمِّكِ أَبَدًا`,
          words: [`أَحْسِنِي`, `إِلَى أُمِّكِ`, `أَبَدًا`],
          labels: [`فعل أمر وفاعله`, `جار ومجرور`, `ظرف زمان مبهم منصوب`],
          distractors: [`مفعول به`, `حال`],
        },
        {
          title: `تركيب: يَرَاكَ حِينَ تَقُومُ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿يَرَاكَ حِينَ تَقُومُ﴾.`,
          source: `يَرَاكَ حِينَ تَقُومُ`,
          words: [`يَرَاكَ`, `حِينَ`, `تَقُومُ`],
          labels: [`فعل مضارع ومفعوله`, `ظرف زمان مبهم منصوب`, `فعل مضارع (الجملة مضاف إليه)`],
          distractors: [`مفعول مطلق`, `حال`],
        },
        {
          title: `تركيب: وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ﴾.`,
          source: `وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ`,
          words: [`تُخْزِنَا`, `يَوْمَ`, `الْقِيَامَةِ`],
          labels: [`فعل مضارع ومفعوله`, `ظرف زمان محدود منصوب`, `مضاف إليه مجرور`],
          distractors: [`حال`, `تمييز`],
        },
        {
          title: `تركيب: لَا تُفْسِدُوا فِي الْأَرْضِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿لَا تُفْسِدُوا فِي الْأَرْضِ﴾.`,
          source: `لَا تُفْسِدُوا فِي الْأَرْضِ`,
          words: [`تُفْسِدُوا`, `فِي الْأَرْضِ`],
          labels: [`فعل مضارع وفاعله`, `جار ومجرور (ظرف مكان محدود)`],
          distractors: [`مفعول به`, `حال`],
        },
        {
          title: `تركيب: كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ﴾.`,
          source: `كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ`,
          words: [`نَقْعُدُ`, `مِنْهَا`, `مَقَاعِدَ`, `لِلسَّمْعِ`],
          labels: [`فعل مضارع وفاعله`, `جار ومجرور`, `ظرف مكان محدود منصوب استثناءً`, `جار ومجرور`],
          distractors: [`مفعول به`, `حال`],
        },
        {
          title: `تركيب: فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ﴾.`,
          source: `فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ`,
          words: [`يَدْخُلُونَ`, `الْجَنَّةَ`],
          labels: [`فعل مضارع وفاعله`, `ظرف مكان محدود منصوب سماعًا`],
          distractors: [`مفعول به`, `حال`],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'المفعول له',
      subtitle: 'The Object of Reason — مفعول لأجله, and the four شروط that let it take نصب without a لام',
      concepts: [
        {
          heading: 'تعريف المفعول له (مفعول لأجله)',
          lines: [
            { html: `المفعول له — "the object of reason" — is the fourth of المنصوبات, right after المفعول فيه. Where المفعول فيه answers when or where, المفعول له answers why, and it goes by a second name, <bdi>مفعول لأجله</bdi>, used interchangeably throughout books of تفسير وإعراب.`, list: false },
            { box: { title: 'Definition', lines: [`المفعول له: هو ما وقع لأجله الفعل`] } },
            { box: { title: 'Example', lines: [`وَالَّذِينَ صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ`] } },
            { html: `Here <bdi>ابتغاء</bdi> is the reason صَبَروا happened — the motive behind the patience, not the patience itself.`, list: false },
            {
              tarkeebDiagram: {
                sentence: `صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ`,
                translation: `They were patient, seeking the countenance of their Lord.`,
                cells: [`صَبَرُوا`, `ابْتِغَاءَ`, `وَجْهِ`, `رَبِّهِمْ`],
                rows: [
                  { position: 'above', labels: [{ start: 0, end: 0, role: `فعل ماضٍ وفاعله` }, { start: 1, end: 1, role: `مفعول له منصوب` }, { start: 2, end: 2, role: `مضاف إليه` }, { start: 3, end: 3, role: `مضاف إليه` }] },
                ],
              },
            },
          ],
          exercise: {
            prompt: `In ﴿وَالَّذِينَ صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ﴾, what does ابْتِغَاءَ name؟`,
            kind: 'mcq',
            options: [`The reason صَبَروا happened — the motive behind the patience, not the patience itself`, `The place where صَبَروا happened`, `The one صَبَروا happened alongside`, `The time صَبَروا happened`],
            correct: 0,
          },
        },
        {
          heading: 'الشرط الأول: أن يكون مصدرًا',
          lines: [
            { html: `Not every noun expressing a reason automatically takes نصب. Direct نصب — without لام or another حرف جر standing in the way — carries specific شروط; if even one breaks down, the noun still carries the meaning of المفعول له, but it must be جُرَّ باللام أو نحوها instead.`, list: false },
            { box: { title: 'Rule', lines: [`الشرط الأول: أن يكون مصدرًا`] } },
            { box: { title: 'Example', lines: [`وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ`] } },
            { html: `<bdi>الأنام</bdi> is اسم ذات — a noun naming created beings — not a مصدر, so it had to be جُرّ باللام, and could not be نُصِب.`, list: false },
          ],
          exercise: {
            prompt: `﴿وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ﴾ keeps الأنام جر باللام. Which شرط of direct نصب does it fail؟`,
            kind: 'mcq',
            options: [`It must be مصدرًا — الأنام is اسم ذات, not مصدر`, `It must share the فاعل of the main فعل`, `It must share the زمن of the main فعل`, `It must be مصدرًا قلبيًّا`],
            correct: 0,
          },
        },
        {
          heading: 'الشرط الثاني: أن يكون مصدرًا قلبيًّا',
          lines: [
            { box: { title: 'Rule', lines: [`الشرط الثاني: أن يكون مصدرًا قلبيًّا`] } },
            { html: `The مصدر must come from <bdi>أفعال القلوب</bdi> — verbs of the heart, such as will, desire, and fear — rather than <bdi>أفعال الجوارح</bdi>, verbs of the physical limbs.`, list: false },
            { box: { title: 'Example', lines: [`سافرتُ إلى مكة للحجِّ`] } },
            { html: `<bdi>الحج</bdi> is indeed a مصدر, but it names a فعل جارحة, not a فعل قلب — so even though it connects to the meaning of المفعول له, it does not take نصب.`, list: false },
          ],
          exercise: {
            prompt: `سافرتُ إلى مكة للحجِّ keeps الحج جر باللام even though الحج is a genuine مصدر. Which شرط does it fail؟`,
            kind: 'mcq',
            options: [`It must be مصدرًا قلبيًّا — الحج is a مصدر from a فعل جارحة, not a فعل قلب`, `It must be مصدرًا at all — الحج is not a مصدر`, `It must share the فاعل of السفر`, `It must be نكرة`],
            correct: 0,
          },
        },
        {
          heading: 'الشرطان الثالث والرابع: اتحاد الفاعل واتحاد الزمن',
          lines: [
            { box: { title: 'Rule', lines: [`الشرط الثالث: أن يتحد فاعل الفعل وفاعل المصدر`] } },
            { box: { title: 'Example', lines: [`وَالْأَنْعَامَ خَلَقَهَا لَكُمْ ۖ ... وَالْخَيْلَ وَالْبِغَالَ وَالْحَمِيرَ لِتَرْكَبُوهَا وَزِينَةً`] } },
            { html: `<bdi>لكم</bdi> isn't even a مصدر to begin with, so اللام was required regardless — but this is also where اتحاد الفاعل would be tested, had لكم been a مصدر.`, list: false },
            { box: { title: 'Rule', lines: [`الشرط الرابع: أن يتحد زمن الفعل وزمن المصدر`] } },
            { box: { title: 'Example', lines: [`أرحمُ والدي كبيرًا لرحمتِه إيّايَ صغيرًا`] } },
            { html: `"I show mercy to my father in his old age, because of his mercy toward me when I was young." Here the فاعل of <bdi>أرحم</bdi> (I) and the فاعل of <bdi>رحمته</bdi> (he) are different persons, and the زمن of الفعل (present) doesn't match the زمن of المصدر (past). With both broken at once, <bdi>رحمته</bdi> cannot be نُصِب as مفعول له.`, list: false },
          ],
          exercise: {
            prompt: `In أرحمُ والدي كبيرًا لرحمتِه إيّايَ صغيرًا, why can't رحمته be نُصب as مفعول له؟`,
            kind: 'mcq',
            options: [`Both اتحاد الفاعل واتحاد الزمن break at once: the فاعل differs (أنا / هو), and the زمن differs (الحاضر / الماضي)`, `رحمته is not a مصدر at all`, `رحمته is a مصدر من فعل جارحة`, `لرحمته already carries اللام, so نصب was never possible regardless`],
            correct: 0,
          },
        },
        {
          heading: 'مصدر مؤول بعد أنْ: مفعول له بتقدير مضاف محذوف',
          lines: [
            { html: `A مصدر مؤول can occur after <bdi>أنْ</bdi> and be إعراب as مفعول له, on the assumption of a dropped مضاف standing before it — usually a word like <bdi>كراهة</bdi> (aversion to).`, list: false },
            { box: { title: 'Example', lines: [`وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ`] } },
            { html: `Meaning <bdi>كراهةَ أن تميدَ بكم</bdi>: Allah set the firmly-anchored mountains into the earth so that it would not shake with its people.`, list: false },
            { box: { title: 'Careful', lines: [`اللَّفْظُ المُقَدَّرُ مُسْتَنْبَطٌ مِنَ السِّياقِ وَتَفْسيرِ السَّلَفِ، لا مِنَ اجْتِهادٍ شَخْصِيٍّ`] } },
            { html: `The supplied word here is not wording the ayah itself contains — it is a conclusion أهل اللغة drew from context and from تفسير السلف, not free reasoning about the meaning.`, list: false },
          ],
          exercise: {
            prompt: `﴿وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ﴾ places أَن تَمِيدَ بِكُمْ directly as مفعول له. What is understood as dropped before it؟`,
            kind: 'mcq',
            options: [`مضاف محذوف, تقديره كراهةَ`, `فعل محذوف تقديره أراد`, `حرف جر ظاهر`, `لا شيء محذوف هنا`],
            correct: 0,
          },
        },
        {
          heading: 'مثال تعدد الإعراب: وزينة في لتركبوها وزينة',
          lines: [
            { html: `On ﴿لِتَرْكَبُوهَا وَزِينَةً﴾, أهل العلم record two ways of إعراب زينة.`, list: false },
            { box: { title: 'Careful', lines: [`زِينَةً: مَفْعولٌ لَهُ مَعْطوفَةٌ عَلى المَحَلِّ، أَوْ مَفْعولٌ مُطْلَقٌ لِفِعْلٍ مَحْذوفٍ`] } },
            { html: `Either it is مفعول له, معطوفة على محل لتركبوها (أي: خلقها لتركبوها ولزينتكم), or it is مفعول مطلق لفعل محذوف, تقديره: وتتزيَّنوا بها زينةً. This is one example of how a single ayah can rightly bear more than one correct إعراب.`, list: false },
          ],
          exercise: {
            prompt: `زينة in ﴿لِتَرْكَبُوهَا وَزِينَةً﴾ admits two different valid إعراب readings. What are they؟`,
            kind: 'mcq',
            options: [`مفعول له معطوفة على محل لتركبوها, أو مفعول مطلق لفعل محذوف`, `فاعل أو مفعول به فقط`, `حال أو تمييز فقط`, `مبتدأ أو خبر فقط`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `المفعول له is also known by a second name. What is it؟`, options: [`مفعول لأجله`, `مفعول فيه`, `مفعول مطلق`, `مفعول معه`], correct: 0 },
        { q: `What is the correct definition of المفعول له؟`, options: [`That which the verb's action was performed for — the reason or motive behind it`, `That noun upon which the doer's action falls`, `That noun which denotes the place or time of the action`, `That which occurred together with the doer`], correct: 0 },
        { q: `﴿وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ﴾ keeps الأنام جر باللام instead of نصب, even though it names the beneficiary/reason. Which شرط of direct نصب does الأنام fail؟`, options: [`It must be مصدرًا — الأنام is اسم ذات, not مصدر`, `It must share the فاعل of the main فعل`, `It must share the زمن of the main فعل`, `It must be مصدرًا قلبيًّا`], correct: 0 },
        { q: `سافرتُ إلى مكة للحجِّ keeps الحج جر باللام even though الحج is a genuine مصدر. Which شرط does it fail؟`, options: [`It must be مصدرًا قلبيًّا (from أفعال القلوب) — الحج is a فعل جارحة, not a فعل قلب`, `It must be مصدرًا at all — الحج is not a مصدر`, `It must share the فاعل of the main فعل`, `It must be نكرة`], correct: 0 },
        { q: `In أرحمُ والدي كبيرًا لرحمتِه إيّايَ صغيرًا, رحمته cannot be نُصب as مفعول له. Which two شروط does it break at once؟`, options: [`اتحاد الفاعل واتحاد الزمن`, `كونه مصدرًا وكونه مصدرًا قلبيًّا`, `اتحاد الفاعل وكونه مصدرًا`, `اتحاد الزمن وكونه مصدرًا قلبيًّا`], correct: 0 },
        { q: `﴿وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ﴾ places a مصدر مؤول (أَن تَمِيدَ بِكُمْ) directly as مفعول له, without a stated لام or مضاف. What is understood as elided before it؟`, options: [`كراهةَ`, `إرادةَ`, `محبةَ`, `قصدَ`], correct: 0 },
      ],
      bank: [
        { title: `تعريف المفعول له`, kind: 'mcq', prompt: `Which of the following correctly defines المفعول له؟`, options: [`ما وقع لأجله الفعل`, `ما وقع عليه فعل الفاعل`, `ما وقع فيه الفعل من المكان أو الزمان`, `ما وقع معه الفعل`], correct: 0 },
        { title: `الاسم الثاني`, kind: 'mcq', prompt: `ما وقع لأجله الفعل is also commonly called:`, options: [`مفعول لأجله`, `مفعول فيه`, `مفعول مطلق`, `مفعول معه`], correct: 0 },
        { title: `ابتغاء وجه ربهم: السبب`, kind: 'mcq', prompt: `In ﴿وَالَّذِينَ صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ﴾, ابْتِغَاءَ is المفعول له. What role does it play relative to صَبَرُوا؟`, options: [`It names the reason or motive behind صَبَرُوا, not the patience itself`, `It is the doer of صَبَرُوا`, `It is the place where صَبَرُوا occurred`, `It is what صَبَرُوا happened alongside`], correct: 0 },
        { title: `الشرط الأول: أن يكون مصدرًا`, kind: 'mcq', prompt: `What is the first شرط for direct نصب of المفعول له without a واسطة such as اللام؟`, options: [`That it be مصدرًا`, `That it be نكرة`, `That it be مفردًا`, `That it be مذكرًا`], correct: 0 },
        { title: `الأنام: ليست مصدرًا`, kind: 'mcq', prompt: `Why isn't الأنام put in نصب in ﴿وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ﴾؟`, options: [`Because الأنام is an اسم ذات — a name for creatures — not a مصدر`, `Because الأنام is معرفة with أل`, `Because the فاعل differs from الأرض's فاعل`, `Because the tense doesn't match`], correct: 0 },
        { title: `الشرط الثاني: مصدر قلبي`, kind: 'mcq', prompt: `What is the second شرط, beyond simply being a مصدر؟`, options: [`That the مصدر come from أفعال القلوب, not أفعال الجوارح`, `That the مصدر be مذكرًا`, `That the مصدر be جمعًا`, `That the مصدر follow اللام`], correct: 0 },
        { title: `الحج: فعل جارحة لا فعل قلب`, kind: 'mcq', prompt: `In سافرتُ إلى مكة للحجِّ, الحج is genuinely a مصدر, yet it cannot take direct نصب. Why؟`, options: [`الحج is a مصدر from a فعل جارحة (a bodily act), not from أفعال القلوب`, `الحج is not مصدر at all`, `السفر and الحج share different الزمن`, `السفر and الحج have different الفاعل`], correct: 0 },
        { title: `فعل القلب وفعل الجارحة`, kind: 'mcq', prompt: `أفعال القلوب, as used in the شروط of المفعول له, refers to verbs of:`, options: [`will, desire, and fear — inner acts, not physical ones`, `the physical limbs, like walking and eating`, `speech alone`, `vision alone`], correct: 0 },
        { title: `الشرط الثالث: اتحاد الفاعل`, kind: 'mcq', prompt: `What is the third شرط for direct نصب of المفعول له؟`, options: [`That the doer of the main فعل and the doer of the مصدر be one and the same`, `That the مصدر be مؤنثًا`, `That the مصدر follow الفعل immediately`, `That the مصدر be نكرة`], correct: 0 },
        { title: `لكم: ليست مصدرًا أصلًا`, kind: 'mcq', prompt: `In ﴿وَالْأَنْعَامَ خَلَقَهَا لَكُمْ﴾, لكم requires اللام regardless of اتحاد الفاعل. Why؟`, options: [`لكم is not even a مصدر to begin with`, `لكم has different الزمن من خَلَقَ`, `لكم has different الفاعل من خَلَقَ`, `لكم is مصدر قلبي only`], correct: 0 },
        { title: `الشرط الرابع: اتحاد الزمن`, kind: 'mcq', prompt: `What is the fourth شرط for direct نصب of المفعول له؟`, options: [`That the time of the main فعل and the time of the مصدر match`, `That the مصدر be إضافة`, `That the مصدر carry تنوين`, `That الفعل be فعل أمر`], correct: 0 },
        { title: `أرحم والدي: الشرطان المكسوران معًا`, kind: 'mcq', prompt: `In أرحمُ والدي كبيرًا لرحمتِه إيّايَ صغيرًا, both اتحاد الفاعل and اتحاد الزمن break at once. What specifically breaks each one؟`, options: [`الفاعل يختلف (أنا / هو), والزمن يختلف (الحاضر / الماضي)`, `الفاعل واحد, لكن الزمن يختلف فقط`, `الزمن واحد, لكن الفاعل يختلف فقط`, `كلاهما متحد, والمشكلة أن رحمته ليست مصدرًا`], correct: 0 },
        { title: `مصدر مؤول بعد أنْ: مفعول له بتقدير مضاف`, kind: 'mcq', prompt: `﴿وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ﴾ places أَن تَمِيدَ بِكُمْ directly as مفعول له. What is assumed dropped before it؟`, options: [`مضاف محذوف, تقديره كراهةَ`, `حرف جر ظاهر`, `فعل محذوف تقديره أراد`, `لا شيء محذوف هنا`], correct: 0 },
        { title: `مصدر السلف وليس رأي شخصي`, kind: 'mcq', prompt: `The word كراهة, supplied before أَن تَمِيدَ بِكُمْ, is not wording the ayah itself contains. Where does it come from؟`, options: [`A conclusion أهل اللغة drew from context and from تفسير السلف, not free reasoning from oneself`, `A direct quotation from a different ayah`, `The reader's own preferred interpretation`, `A grammatical rule that always supplies كراهة after أنْ`], correct: 0 },
        { title: `لتركبوها وزينة: وجها الإعراب`, kind: 'mcq', prompt: `﴿لِتَرْكَبُوهَا وَزِينَةً﴾ admits two different valid إعراب readings for زينة. What are they؟`, options: [`مفعول له معطوفة على محل لتركبوها, أو مفعول مطلق لفعل محذوف`, `فاعل أو مفعول به فقط`, `حال أو تمييز فقط`, `مبتدأ أو خبر فقط`], correct: 0 },
        { title: `تعدد الإعراب في آية واحدة`, kind: 'mcq', prompt: `What does the two valid readings of زينة in ﴿لِتَرْكَبُوهَا وَزِينَةً﴾ illustrate about تفسير القرآن؟`, options: [`A single ayah can rightly bear more than one correct إعراب`, `Every ayah has exactly one correct إعراب, and disagreement is always an error`, `زينة can never be مفعول مطلق under any reading`, `اللام before تركبوها makes both readings identical`], correct: 0 },
        { title: `الشروط الأربعة مجتمعة`, kind: 'mcq', prompt: `For direct نصب of المفعول له بلا واسطة اللام, all four شروط must hold together. Which of the following completes the set correctly؟`, options: [`مصدر، مصدر قلبي، اتحاد الفاعل، اتحاد الزمن`, `مصدر، نكرة، اتحاد الفاعل، اتحاد المكان`, `مصدر قلبي، معرفة، اتحاد الزمن، اتحاد المكان`, `نكرة، معرفة، اتحاد الفاعل، اتحاد الزمن`], correct: 0 },
        { title: `ماذا يحدث إذا اختل شرط`, kind: 'mcq', prompt: `If even one of the four شروط for direct نصب breaks down, what happens to the noun expressing the reason؟`, options: [`It still carries the meaning of المفعول له, but it must be جُرّ باللام أو نحوها instead of نُصب`, `It becomes مفعول مطلق instead`, `It drops out of the sentence entirely`, `It becomes الفاعل instead`], correct: 0 },
        {
          title: `تركيب: صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ.`,
          source: `صَبَرُوا ابْتِغَاءَ وَجْهِ رَبِّهِمْ`,
          words: [`صَبَرُوا`, `ابْتِغَاءَ`, `وَجْهِ`, `رَبِّهِمْ`],
          labels: [`فعل ماضٍ وفاعله`, `مفعول له منصوب`, `مضاف إليه`, `مضاف إليه`],
          distractors: [`حال`, `مفعول مطلق`],
        },
        {
          title: `تركيب: وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ﴾.`,
          source: `وَالْأَرْضَ وَضَعَهَا لِلْأَنَامِ`,
          words: [`الْأَرْضَ`, `وَضَعَهَا`, `لِلْأَنَامِ`],
          labels: [`مفعول به مقدم`, `فعل ماضٍ وفاعله ومفعوله`, `جار ومجرور (بدل النصب، لأنه ليس مصدرًا)`],
          distractors: [`مفعول له منصوب`, `حال`],
        },
        {
          title: `تركيب: سَافَرْتُ إِلَى مَكَّةَ لِلْحَجِّ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of سَافَرْتُ إِلَى مَكَّةَ لِلْحَجِّ.`,
          source: `سَافَرْتُ إِلَى مَكَّةَ لِلْحَجِّ`,
          words: [`سَافَرْتُ`, `إِلَى مَكَّةَ`, `لِلْحَجِّ`],
          labels: [`فعل ماضٍ وفاعله`, `جار ومجرور`, `جار ومجرور (بدل النصب، لأنه مصدر فعل جارحة)`],
          distractors: [`مفعول له منصوب`, `حال`],
        },
        {
          title: `تركيب: أَرْحَمُ وَالِدِي كَبِيرًا لِرَحْمَتِهِ إِيَّايَ صَغِيرًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of أَرْحَمُ وَالِدِي كَبِيرًا لِرَحْمَتِهِ إِيَّايَ صَغِيرًا.`,
          source: `أَرْحَمُ وَالِدِي كَبِيرًا لِرَحْمَتِهِ إِيَّايَ صَغِيرًا`,
          words: [`أَرْحَمُ`, `وَالِدِي`, `كَبِيرًا`, `لِرَحْمَتِهِ`],
          labels: [`فعل مضارع وفاعله`, `مفعول به`, `حال`, `جار ومجرور (بدل النصب، لاختلاف الفاعل والزمن)`],
          distractors: [`مفعول له منصوب`, `مفعول مطلق`],
        },
        {
          title: `تركيب: وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of ﴿وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ﴾.`,
          source: `وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ`,
          words: [`أَلْقَىٰ`, `فِي الْأَرْضِ`, `رَوَاسِيَ`, `أَن تَمِيدَ بِكُمْ`],
          labels: [`فعل ماضٍ وفاعله`, `جار ومجرور`, `مفعول به`, `مفعول له (مصدر مؤول بتقدير مضاف)`],
          distractors: [`حال`, `مفعول مطلق`],
        },
        {
          title: `تركيب: وَالْخَيْلَ لِتَرْكَبُوهَا وَزِينَةً`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of وَالْخَيْلَ لِتَرْكَبُوهَا وَزِينَةً.`,
          source: `وَالْخَيْلَ لِتَرْكَبُوهَا وَزِينَةً`,
          words: [`الْخَيْلَ`, `لِتَرْكَبُوهَا`, `وَزِينَةً`],
          labels: [`مفعول به`, `جار ومجرور (مصدر مؤول)`, `مفعول له معطوف على المحل (أو مفعول مطلق لفعل محذوف)`],
          distractors: [`حال`, `مفعول به ثانٍ`],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'المفعول معه',
      subtitle: 'The Object of Accompaniment — واو المعية after a فعل or شبه فعل, and when النصب becomes the only option',
      concepts: [
        {
          heading: 'تعريف المفعول معه',
          lines: [
            { html: `المفعول معه — "the object of accompaniment" — is the fifth of المنصوبات, right after المفعول له. It's distinctive: this noun isn't really the target of the verb's action at all — it's whatever the doer's action happened alongside, put into النصب purely to mark that companionship, once واو المعية sits between it and what precedes it.`, list: false },
            { box: { title: 'Definition', lines: [`المفعول معه: هو ما وقع معه الفعل`] } },
            { box: { title: 'Example', lines: [`يَفْنَى الْمَالُ وَيَبْقَى ابْنُ آدَمَ وَعَمَلَهُ`] } },
            { html: `"Wealth perishes, and the son of Adam remains, along with his deed." <bdi>عَمَله</bdi> occurred together with <bdi>ابن آدم</bdi> in البقاء, so it is نُصب as مفعول معه, rather than مرفوعًا معطوفًا على ابن آدم.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿وَيَبْقَى ابْنُ آدَمَ وَعَمَلَهُ﴾, why is عَمَلَهُ منصوب rather than معطوفًا مرفوعًا على ابن آدم؟`,
            kind: 'mcq',
            options: [`عمله's بقاء happens together with ابن آدم's, so it takes نصب على المعية instead of عطف`, `عمله is معرفة, and عطف here would require a نكرة`, `يبقى is a ماضٍ verb that blocks عطف`, `ابن آدم is ممنوع من الصرف`],
            correct: 0,
          },
        },
        {
          heading: 'شرط المفعول معه: جملة فيها فعل أو شبه فعل',
          lines: [
            { box: { title: 'Rule', lines: [`يُشترط لوجود المفعول معه أن تكون قبله جملة فيها فعل أو شبه فعل`] } },
            { html: `<bdi>شبه فعل</bdi> here means something functioning like a فعل — such as اسم فاعل — without being one. There must always be some عامل expressing a حدث for the accompaniment to attach itself to.`, list: false },
            { box: { title: 'Example', lines: [`أنا سائرٌ والنهرَ`] } },
            { html: `<bdi>سائر</bdi> is اسم فاعل — a شبه فعل — sitting right before الواو, so النهر can correctly be نُصب على المعية: <bdi>أنا أسير مصاحبًا للنهر</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `سائر in أنا سائرٌ والنهرَ is not a true فعل. What is it, and why does it license نصب النهر؟`,
            kind: 'mcq',
            options: [`اسم فاعل — a شبه فعل that expresses a حدث, the same way a true فعل would`, `مصدر — it names the event without expressing it`, `ظرف — it fixes the time of the sentence`, `حرف — it carries no independent meaning`],
            correct: 0,
          },
        },
        {
          heading: 'متى يمتنع النصب: لا فعل ولا شبه فعل',
          lines: [
            { box: { title: 'Example', lines: [`كلُّ امرئٍ وشأنُه`] } },
            { html: `"Every man and his affair." There is neither فعل ولا شبه فعل قبل الواو here, so <bdi>شأنُه</bdi> cannot be مفعول معه at all in this sentence; it must instead be مرفوعًا معطوفًا: <bdi>كل امرئ وشأنُه مقترنان</bdi>. النصب is simply not an option.`, list: false },
          ],
          exercise: {
            prompt: `Why can't شأنه be نُصب as مفعول معه in كلُّ امرئٍ وشأنُه؟`,
            kind: 'mcq',
            options: [`There is neither a فعل nor a شبه فعل before الواو for the accompaniment to attach to`, `شأنه is مضاف إلى ضمير, which blocks المعية`, `كل is اسم شرط, which blocks المعية`, `الواو here is واو الحال, not واو المعية`],
            correct: 0,
          },
        },
        {
          heading: 'وجوب النصب حين يتعذر العطف',
          lines: [
            { html: `Normally, once واو المعية follows a clause containing فعل, two paths stand open together: العطف (بالرفع, إن جاز) or النصب على المعية.`, list: false },
            { html: `لكن النصب يجب إذا تعذّر العطف.`, list: false },
            { box: { title: 'Example', lines: [`بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ`] } },
            { html: `"I have been sent, and the Hour, like these two [fingers]." <bdi>الساعة</bdi> must be نصب as مفعول معه, لأنه لا يجوز عطفها على تاء الفاعل المتصلة في <bdi>بُعِثْتُ</bdi> without first separating الضمير — which is not how الحديث has come down.`, list: false },
          ],
          exercise: {
            prompt: `Why is النصب the only valid reading for الساعة in «بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ», with no alternative رفع reading available؟`,
            kind: 'mcq',
            options: [`الساعة cannot be coordinated onto the attached تاء الفاعل in بُعِثْتُ without first separating الضمير`, `الساعة is معرفة, which blocks العطف`, `كهاتين blocks any reading but النصب`, `بعثت has no فاعل at all`],
            correct: 0,
          },
        },
        {
          heading: 'جواز الوجهين حين يصح العطف',
          lines: [
            { html: `Once العطف is grammatically possible, both options stand open together: النصب على المعية, أو الرفع بالعطف.`, list: false },
            { box: { title: 'Example', lines: [`حَضَرَ الأبُ وولدُه / حَضَرَ الأبُ وولدَه`] } },
            { html: `<bdi>حضر الأبُ وولدُه</bdi> (بالرفع): a coordination — the father and the son both came, together. <bdi>حضر الأبُ وولدَه</bdi> (بالنصب): مفعول معه — the father came, accompanied by his son.`, list: false },
          ],
          exercise: {
            prompt: `حَضَرَ الأبُ وولدُه and حَضَرَ الأبُ وولدَه are both valid readings of the same sentence. What does each one mean؟`,
            kind: 'mcq',
            options: [`وولدُه (بالرفع): both father and son came; وولدَه (بالنصب): the father came, accompanied by his son`, `Both readings mean exactly the same thing`, `وولدُه (بالرفع) means the son alone came`, `وولدَه (بالنصب) means only the father exists`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `What is the correct definition of المفعول معه؟`, options: [`That which the action occurred together with — signaling accompaniment with what precedes it`, `That upon which the doer's action falls`, `That which the action was performed for`, `That which denotes the place or time of the action`], correct: 0 },
        { q: `For المفعول معه to occur at all, what must precede واو المعية؟`, options: [`A clause containing a فعل or a شبه فعل`, `A clause containing only أسماء`, `A حرف جر`, `A مبتدأ بلا خبر`], correct: 0 },
        { q: `In أنا سائرٌ والنهرَ, سائر licenses النصب of النهر even though it isn't a true فعل. What is سائر؟`, options: [`اسم فاعل — a شبه فعل`, `مصدر`, `اسم مفعول`, `ظرف`], correct: 0 },
        { q: `In كلُّ امرئٍ وشأنُه, why must شأنه be رفوعًا rather than منصوبًا؟`, options: [`There is neither a فعل nor a شبه فعل before الواو, so المفعول معه cannot occur`, `شأنه is معرفة, and المفعول معه must be نكرة`, `كل امرئ is مبني`, `الواو here is واو القسم, not واو المعية`], correct: 0 },
        { q: `«بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ» requires النصب of الساعة, with no alternative رفع reading available. Why؟`, options: [`الساعة cannot be coordinated onto the attached تاء الفاعل in بُعِثْتُ without first separating الضمير`, `الساعة is معرفة, which blocks العطف`, `كهاتين blocks any reading but النصب`, `بعثت has no فاعل at all`], correct: 0 },
        { q: `حَضَرَ الأبُ وولدُه and حَضَرَ الأبُ وولدَه are both valid readings of the same sentence. What does each one mean؟`, options: [`وولدُه (رفع): both father and son came; وولدَه (نصب): the father came, accompanied by his son`, `Both readings mean exactly the same thing`, `وولدُه (رفع) means the son alone came`, `وولدَه (نصب) means only the father exists`], correct: 0 },
      ],
      bank: [
        { title: `تعريف المفعول معه`, kind: 'mcq', prompt: `Which of the following correctly defines المفعول معه؟`, options: [`ما وقع معه الفعل`, `ما وقع عليه فعل الفاعل`, `ما وقع لأجله الفعل`, `ما وقع فيه الفعل من المكان أو الزمان`], correct: 0 },
        { title: `يبقى ابن آدم وعمله: تحديد المفعول معه`, kind: 'mcq', prompt: `In ﴿وَيَبْقَى ابْنُ آدَمَ وَعَمَلَهُ﴾, why is عَمَلَهُ منصوب rather than معطوفًا مرفوعًا على ابن آدم؟`, options: [`Because عمله's بقاء happens together with ابن آدم's, so it takes نصب على المعية instead of عطف`, `Because عمله is معرفة, and عطف here would require a نكرة`, `Because يبقى is a ماضٍ verb`, `Because آدم is ممنوع من الصرف`], correct: 0 },
        { title: `شرط وجود المفعول معه`, kind: 'mcq', prompt: `What must exist in the clause before واو المعية, for المفعول معه to be possible at all؟`, options: [`عامل يدل على حدث — فعل أو شبه فعل`, `اسم معرفة بأل`, `حرف جر ظاهر`, `ضمير متصل مرفوع`], correct: 0 },
        { title: `أنا سائر والنهر: شبه الفعل`, kind: 'mcq', prompt: `سائر in أنا سائرٌ والنهرَ is not a true فعل. What kind of word is it, and why does it still license نصب النهر؟`, options: [`اسم فاعل — it functions as a شبه فعل, expressing a حدث`, `مصدر — it names an event without expressing it`, `ظرف — it fixes the time of the sentence`, `حرف — it has no meaning of its own`], correct: 0 },
        { title: `كل امرئ وشأنه: امتناع النصب`, kind: 'mcq', prompt: `Why can't شأنه be نُصب as مفعول معه في كلُّ امرئٍ وشأنُه؟`, options: [`There is neither a فعل nor a شبه فعل before الواو for the accompaniment to attach to`, `شأنه is مضاف إلى ضمير, which blocks المعية`, `كل is اسم شرط, which blocks المعية`, `الواو here is واو الحال, not واو المعية`], correct: 0 },
        { title: `كل امرئ وشأنه: الإعراب الصحيح`, kind: 'mcq', prompt: `Since النصب is not an option in كلُّ امرئٍ وشأنُه, what must شأنه be إعراب-ed as instead؟`, options: [`معطوف مرفوع على امرئ`, `مفعول به منصوب`, `حال منصوب`, `مفعول مطلق منصوب`], correct: 0 },
        { title: `الأصل عند إمكان العطف`, kind: 'mcq', prompt: `When واو المعية follows a clause containing فعل, and العطف is grammatically possible, how many valid readings normally stand open؟`, options: [`اثنان: العطف بالرفع، أو النصب على المعية`, `واحد فقط: النصب على المعية دائمًا`, `واحد فقط: العطف بالرفع دائمًا`, `ثلاثة: الرفع والنصب والجر`], correct: 0 },
        { title: `متى يجب النصب`, kind: 'mcq', prompt: `النصب على المعية becomes obligatory, rather than merely one of two options, whenever:`, options: [`العطف يتعذر`, `الفعل مضارع`, `المعطوف عليه نكرة`, `الواو تسبق اسم إشارة`], correct: 0 },
        { title: `بعثت والساعة: سبب تعذر العطف`, kind: 'mcq', prompt: `In «بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ», why can't الساعة be coordinated (بالرفع) onto فاعل بُعِثْتُ؟`, options: [`The معطوف عليه is an attached مرفوع pronoun with no separator, and عطف directly onto it isn't valid`, `الساعة is معرفة, and عطف here would require a نكرة`, `بعثت has no فاعل at all`, `كهاتين blocks any عطف`], correct: 0 },
        { title: `لو أردنا العطف`, kind: 'mcq', prompt: `If one wanted to coordinate (العطف بالرفع) rather than use النصب في «بُعِثْتُ وَالسَّاعَةَ», what would first need to happen, and why does الحديث avoid it؟`, options: [`The attached pronoun would first need to be separated (بُعِثْتُ أنا والساعةُ), which differs from what الحديث actually says`, `Nothing — عطف is possible directly`, `بعثت would need to be dropped entirely`, `الساعة would need to be repeated twice`], correct: 0 },
        { title: `حضر الأب وولده: الوجه الأول`, kind: 'mcq', prompt: `In حَضَرَ الأبُ وولدُه (بالرفع), what does وولدُه mean, and what is its إعراب؟`, options: [`معطوف مرفوع على الأب — الأب والولد حضرا معًا`, `مفعول معه منصوب — الأب حضر مصاحبًا لولده`, `مبتدأ محذوف الخبر`, `حال منصوب`], correct: 0 },
        { title: `حضر الأب وولده: الوجه الثاني`, kind: 'mcq', prompt: `In حَضَرَ الأبُ وولدَه (بالنصب), what does وولدَه mean, and what is its إعراب؟`, options: [`مفعول معه منصوب — حضر الأب مصاحبًا لولده`, `معطوف مرفوع على الأب`, `فاعل ثانٍ`, `خبر لمبتدأ محذوف`], correct: 0 },
        { title: `الفرق بين الوجهين`, kind: 'mcq', prompt: `Between حَضَرَ الأبُ وولدُه and حَضَرَ الأبُ وولدَه, what is the actual difference in meaning؟`, options: [`With رفع: both arrived together. With نصب: only الأب arrived, accompanied by ولده`, `There is no difference in meaning between the two readings`, `With رفع: only الولد arrived. With نصب: only الأب arrived`, `Only the نصب reading indicates arrival at all — the رفع reading doesn't`], correct: 0 },
        { title: `العامل اللازم للمعية`, kind: 'mcq', prompt: `Why can't المفعول معه occur in a pure جملة اسمية with no فعل or شبه فعل anywhere in it, even if واو appears between two أسماء؟`, options: [`There must be a عامل indicating an event that the accompaniment (المصاحبة) happens alongside`, `Because a جملة اسمية can't carry a واو at all`, `Because المفعول معه must be معرفة`, `Because a واو in a جملة اسمية is always واو الحال`], correct: 0 },
        { title: `شبه الفعل: أمثلة`, kind: 'mcq', prompt: `Besides اسم الفاعل, what else counts as شبه فعل for the purpose of licensing المفعول معه؟`, options: [`Anything functioning like a فعل in expressing a حدث, even without being one`, `Only اسم المفعول, nothing else`, `Only الفعل الماضي`, `Nothing besides the true فعل itself`], correct: 0 },
        { title: `لماذا لا يُعامل معه كمعطوف دائمًا`, kind: 'mcq', prompt: `Why isn't the noun after واو المعية simply treated as معطوف every time, instead of ever being مفعول معه؟`, options: [`Because in some positions عطف is simply impossible, making نصب obligatory`, `Because عطف is always forbidden after واو المعية`, `Because the معطوف عليه is always a نكرة noun`, `Because the فعل blocks عطف in every case`], correct: 0 },
        { title: `المفعول معه ليس معمولًا حقيقيًّا للفعل`, kind: 'mcq', prompt: `What makes المفعول معه distinctive compared to المفعول به أو المفعول له؟`, options: [`It isn't genuinely the target of the فاعل's action — it's put in نصب only to show accompaniment`, `It's the only one that always comes before the فعل`, `It's the only one that's never a صريح noun`, `It's the only one that can always be dropped`], correct: 0 },
        { title: `مراجعة: مواضع وجوب النصب`, kind: 'mcq', prompt: `Of the following, which correctly describes when النصب على المعية becomes وجوبًا rather than merely جائزًا؟`, options: [`When العطف is grammatically impossible, such as onto an attached ضمير مرفوع with nothing separating it`, `Whenever the sentence contains a فعل ماضٍ`, `Whenever the noun after الواو is معرفة`, `النصب is never obligatory — it is always optional`], correct: 0 },
        {
          title: `تركيب: يَبْقَى ابْنُ آدَمَ وَعَمَلَهُ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of وَيَبْقَى ابْنُ آدَمَ وَعَمَلَهُ.`,
          source: `يَبْقَى ابْنُ آدَمَ وَعَمَلَهُ`,
          words: [`يَبْقَى`, `ابْنُ آدَمَ`, `وَعَمَلَهُ`],
          labels: [`فعل مضارع`, `فاعل`, `مفعول معه منصوب`],
          distractors: [`معطوف مرفوع`, `مبتدأ`],
        },
        {
          title: `تركيب: أَنَا سَائِرٌ وَالنَّهْرَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of أَنَا سَائِرٌ وَالنَّهْرَ.`,
          source: `أَنَا سَائِرٌ وَالنَّهْرَ`,
          words: [`سَائِرٌ`, `وَالنَّهْرَ`],
          labels: [`خبر (شبه فعل: اسم فاعل)`, `مفعول معه منصوب`],
          distractors: [`معطوف مرفوع`, `حال`],
        },
        {
          title: `تركيب: كُلُّ امْرِئٍ وَشَأْنُهُ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of كُلُّ امْرِئٍ وَشَأْنُهُ.`,
          source: `كُلُّ امْرِئٍ وَشَأْنُهُ`,
          words: [`كُلُّ امْرِئٍ`, `وَشَأْنُهُ`],
          labels: [`مبتدأ`, `معطوف مرفوع`],
          distractors: [`مفعول معه منصوب`, `خبر`],
        },
        {
          title: `تركيب: بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ.`,
          source: `بُعِثْتُ وَالسَّاعَةَ كَهَاتَيْنِ`,
          words: [`بُعِثْتُ`, `وَالسَّاعَةَ`, `كَهَاتَيْنِ`],
          labels: [`فعل ونائب فاعله (تاء متصلة)`, `مفعول معه منصوب وجوبًا`, `جار ومجرور (تشبيه)`],
          distractors: [`معطوف مرفوع`, `حال`],
        },
        {
          title: `تركيب: حَضَرَ الأَبُ وَوَلَدَهُ (النصب)`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of حَضَرَ الأَبُ وَوَلَدَهُ, reading وَلَدَهُ as منصوب.`,
          source: `حَضَرَ الأَبُ وَوَلَدَهُ`,
          words: [`حَضَرَ`, `الأَبُ`, `وَوَلَدَهُ`],
          labels: [`فعل ماضٍ`, `فاعل`, `مفعول معه منصوب`],
          distractors: [`معطوف مرفوع`, `مبتدأ`],
        },
        {
          title: `تركيب: حَضَرَ الأَبُ وَوَلَدُهُ (الرفع)`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of حَضَرَ الأَبُ وَوَلَدُهُ, reading وَلَدُهُ as مرفوع.`,
          source: `حَضَرَ الأَبُ وَوَلَدُهُ`,
          words: [`حَضَرَ`, `الأَبُ`, `وَوَلَدُهُ`],
          labels: [`فعل ماضٍ`, `فاعل`, `معطوف مرفوع`],
          distractors: [`مفعول معه منصوب`, `خبر`],
        },
      ],
    },
  ],
};
