// Module 03 — الفعل السماعي (The Heard Verb)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__1 الْفِعْلِ__2 السماعي.apkg,
// 68 notes across 4 sub-decks) prepared for this conversion. Definitions and
// examples are kept faithful to the source notes. Concept bodies are short
// by design (a sentence or two, not teaching prose); quiz/bank question text
// is English with Arabic grammatical terms left in Arabic.
//
// The source deck covers السماعي — the other branch of عامل الفعل from
// Module 02's القياسي, whose government follows no consistent rule and
// depends purely on السماع. Its three أقسام are الأفعال الناقصة (split here
// into two lessons: كان ومعانيها, then its twelve أخوات), أفعال الرجاء
// والمقاربة والشروع, أفعال المدح والذم, and صيغ التعجب.

export default {
  id: '03',
  title: 'الفعل السماعي',
  heading: 'العامل وغير العامل',
  subheading: 'الفعل',
  blurb: 'The سماعي فعل: كان وأخواتها and its meanings, أفعال الرجاء والمقاربة والشروع, أفعال المدح والذم, and صيغ التعجب.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'كان ومعانيها',
      subtitle: 'Kāna and Its Meanings — the ناقص فعل, كان\'s six senses, and حذف النون / حذف كان واسمها',
      concepts: [
        {
          heading: 'السماعي، والفعل الناقص',
          body: `<bdi>عَامِلُ الْفِعْل</bdi> السَّمَاعِيّ is the branch that follows no consistent rule (<bdi>لَا قَاعِدَة</bdi>) and depends purely on <bdi>السَّمَاع</bdi> — what has been transmitted. It has three <bdi>أَقْسَام</bdi>: (1) <bdi>الْأَفْعَالُ النَّاقِصَة</bdi> (2) <bdi>أَفْعَالُ الْمَدْحِ وَالذَّمّ</bdi> (3) <bdi>صِيَغُ التَّعَجُّب</bdi>. This lesson opens the first: الأفعال الناقصة enter upon a <bdi>مُبْتَدَأ</bdi> and <bdi>خَبَر</bdi>, making the first <bdi>مَرْفُوع</bdi> (called <bdi>اِسْمُهَا</bdi>) and the second <bdi>مَنْصُوب</bdi> (called <bdi>خَبَرُهَا</bdi>). A فعل is called <bdi>نَاقِص</bdi> because its meaning stays incomplete without that خبر — unlike a <bdi>فِعْلٌ تَامّ</bdi>, whose فاعل alone is enough to complete the meaning.`,
          sample: `السماعي — لا قاعدة، أقسامه الثلاثة: الأفعال الناقصة، أفعال المدح والذم، صيغ التعجب<br>الفعل الناقص — يرفع اسمه وينصب خبره<br>الفعل التام — يكتفي بفاعله عن الخبر`,
          exercise: {
            prompt: `Which of these is NOT one of the three أقسام of السماعي?`,
            kind: 'mcq',
            options: ['الأفعال الناقصة', 'أفعال المدح والذم', 'صيغ التعجب', 'أفعال القلوب'],
            correct: 3,
          },
        },
        {
          heading: 'أضرب الأفعال الناقصة، وكان وأخواتها',
          body: `الأفعال الناقصة fall into four <bdi>أَضْرُب</bdi>: (1) <bdi>كَانَ وَأَخَوَاتُهَا</bdi> (2) <bdi>أَفْعَالُ الرَّجَاء</bdi> (3) <bdi>أَفْعَالُ الْمُقَارَبَة</bdi> (4) <bdi>أَفْعَالُ الشُّرُوع</bdi>. This lesson and the next cover the first: thirteen verbs sharing كان's government — <bdi>كَانَ، أَصْبَحَ، أَضْحَى، أَمْسَى، ظَلَّ، بَاتَ، صَارَ، مَا بَرِحَ، مَا انْفَكَّ، مَا زَالَ، مَا فَتِئَ، مَا دَامَ، لَيْسَ</bdi>.`,
          sample: `أضرب الناقصة (٤) — كان وأخواتها، أفعال الرجاء، أفعال المقاربة، أفعال الشروع<br>كان وأخواتها (١٣) — كان، أصبح، أضحى، أمسى، ظل، بات، صار، ما برح، ما انفك، ما زال، ما فتئ، ما دام، ليس`,
          exercise: {
            prompt: `How many أضرب does الأفعال الناقصة split into?`,
            kind: 'mcq',
            options: ['اثنان', 'ثلاثة', 'أربعة', 'خمسة'],
            correct: 2,
          },
        },
        {
          heading: 'معاني كان الستة',
          body: `<bdi>كَانَ</bdi> itself carries a wide range of time-meanings. Linked to the past, it can indicate: (1) <bdi>الْمَاضِي الْمُنْقَطِع</bdi>, a fixed fact or a finished event, as in <bdi>﴿وَكَانُوا عَلَيْهِ شُهَدَاءَ﴾</bdi> (2) <bdi>الْمَاضِي الْمُتَجَدِّد</bdi>, continuous or habitual, as in <bdi>كَانَا يَأْكُلَانِ الطَّعَامَ</bdi> (3) <bdi>الْحَال بِمَعْنَى مَا زَالَ</bdi>, as in <bdi>﴿وَكَانَ الْإِنْسَانُ عَجُولًا﴾</bdi> (4) <bdi>الِاسْتِقْبَال</bdi>, as in <bdi>﴿كَانَتْ لَهُمْ جَنَّاتُ الْفِرْدَوْسِ نُزُلًا﴾</bdi>. Two further senses go beyond time altogether: (5) <bdi>الِانْبِغَاء</bdi>, what is fitting, as in <bdi>﴿مَا كَانَ لَنَا أَنْ نُشْرِكَ بِاللَّهِ مِنْ شَيْءٍ﴾</bdi> (6) <bdi>الْقُدْرَة</bdi>, as in <bdi>﴿وَمَا كَانَ لِنَفْسٍ أَنْ تَمُوتَ إِلَّا بِإِذْنِ اللَّهِ﴾</bdi>.`,
          sample: `الماضي المنقطع — ﴿وكانوا عليه شهداء﴾<br>الماضي المتجدد — كانا يأكلان الطعام<br>الحال بمعنى ما زال — ﴿وكان الإنسان عجولا﴾<br>الاستقبال — ﴿كانت لهم جنات الفردوس نزلا﴾<br>الانبغاء — ﴿ما كان لنا أن نشرك بالله من شيء﴾<br>القدرة — ﴿وما كان لنفس أن تموت إلا بإذن الله﴾`,
          exercise: {
            prompt: `﴿وَمَا كَانَ لِنَفْسٍ أَنْ تَمُوتَ إِلَّا بِإِذْنِ اللَّهِ﴾ — كان here carries which of the six meanings?`,
            kind: 'mcq',
            options: ['القدرة', 'الماضي المنقطع', 'الاستقبال', 'الحال بمعنى ما زال'],
            correct: 0,
          },
        },
        {
          heading: 'أحكام الحذف: نون يكن، وكان مع اسمها',
          body: `Two deletions are permitted around كان. The <bdi>نُون</bdi> of <bdi>يَكُن</bdi> may drop when it is <bdi>مَجْزُوم</bdi>, not followed by a <bdi>سَاكِن</bdi>, and carries no attached <bdi>ضَمِيرُ نَصْبٍ</bdi>, as in <bdi>﴿لَمْ نَكُ مِنَ الْمُصَلِّينَ﴾</bdi> — but not <bdi>﴿لَمْ يَكُنِ الَّذِينَ كَفَرُوا﴾</bdi> (followed by a ساكن) nor <bdi>لَمْ أَكُنْهُ</bdi> (an attached ضمير). Dropping it adds a nuance of <bdi>تَقْلِيل</bdi> (diminution), as in <bdi>﴿وَلَمْ يَكُ شَيْئًا﴾</bdi>. Separately, <bdi>كَانَ</bdi> together with its whole <bdi>اسْم</bdi> may be deleted after the <bdi>شَرْط إِنْ</bdi> and <bdi>لَوْ</bdi>, as in <bdi>الْتَمِسْ وَلَوْ خَاتَمًا مِنْ حَدِيدٍ</bdi> and <bdi>إِنْ خَيْرًا فَخَيْرٌ وَإِنْ شَرًّا فَشَرٌّ</bdi>, and occasionally elsewhere, as in <bdi>﴿فَآمَنُوا خَيْرًا لَكُمْ﴾</bdi>.`,
          sample: `حذف نون يكن — ﴿لم نكُ من المصلين﴾ (مجزوم، لا ساكن بعده، لا ضمير متصل)<br>عدم الحذف — ﴿لم يكن الذين كفروا﴾ (ساكن بعده)<br>حذف كان واسمها بعد الشرط — التمس ولو خاتماً من حديد`,
          exercise: {
            prompt: `Why is the نون of يكن kept in ﴿لَمْ يَكُنِ الَّذِينَ كَفَرُوا﴾ but dropped in ﴿لَمْ نَكُ مِنَ الْمُصَلِّينَ﴾?`,
            kind: 'mcq',
            options: ["Because the first is followed by a ساكن, and the second isn't", 'Because the first is مجزوم and the second is مرفوع', 'Because the first has an attached ضمير نصب only', 'No difference — deletion is allowed in both'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أقسام does السماعي split into?',
          options: ['اثنان', 'ثلاثة', 'أربعة', 'خمسة'],
          correct: 1,
        },
        {
          q: 'الفعل الناقص makes its اسم مرفوعًا. What does it make منصوبًا?',
          options: ['خبره', 'فاعله', 'مفعوله المطلق', 'حاله'],
          correct: 0,
        },
        {
          q: 'How many verbs make up كان وأخواتها?',
          options: ['عشرة', 'اثنا عشر', 'ثلاثة عشر', 'أربعة عشر'],
          correct: 2,
        },
        {
          q: '﴿وَكَانَ الْإِنْسَانُ عَجُولًا﴾ — كان here carries the meaning of:',
          options: ['ما زال (الحال)', 'الاستقبال', 'الانبغاء', 'القدرة'],
          correct: 0,
        },
        {
          q: 'The نون of يكن may be dropped on condition that:',
          options: ['That it be مجزومة, not followed by a ساكن, and carry no attached ضمير نصب', 'That it always be مرفوعة', 'That a حرف جر precede it', 'That the فعل be an أمر'],
          correct: 0,
        },
        {
          q: 'كان together with its اسم may both be deleted after:',
          options: ['الشرط إن ولو', 'الاستفهام', 'النداء', 'التمييز'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'تعريف السماعي',
          kind: 'mcq',
          prompt: 'A عامل فعل that follows no consistent rule and depends on transmission alone is called:',
          options: ['السماعي', 'القياسي', 'المطرد', 'المنسوخ'],
          correct: 0,
        },
        {
          title: 'أقسام السماعي',
          kind: 'mcq',
          prompt: 'The three أقسام of عامل الفعل السماعي are:',
          options: ['الأفعال الناقصة، أفعال المدح والذم، صيغ التعجب', 'اللازم، المتعدي، القلب', 'القياسي، المطرد، الشاذ', 'التعليق، الإلغاء، الاختصار'],
          correct: 0,
        },
        {
          title: 'عمل الفعل الناقص',
          kind: 'mcq',
          prompt: 'الفعل الناقص enters upon the مبتدأ and خبر, making the first:',
          options: ['مرفوعا (اسمها)', 'منصوبا (خبرها)', 'مجرورا', 'مبنيا'],
          correct: 0,
        },
        {
          title: 'سبب تسمية الناقص',
          kind: 'mcq',
          prompt: 'الفعل الناقص is called ناقص because:',
          options: ['Its meaning is only complete with its خبر', 'It has no فاعل', 'It does not تُصرَّف', 'It does not enter upon الجملة الاسمية'],
          correct: 0,
        },
        {
          title: 'أضرب الأفعال الناقصة',
          kind: 'mcq',
          prompt: 'The four أضرب of الأفعال الناقصة are:',
          options: ['كان وأخواتها، أفعال الرجاء، أفعال المقاربة، أفعال الشروع', 'اليقين والظن والتحويل والجارحة', 'التام والناقص والمتصرف وغير المتصرف', 'القياسي والسماعي والمطرد والشاذ'],
          correct: 0,
        },
        {
          title: 'عدد أخوات كان',
          kind: 'mcq',
          prompt: 'كان وأخواتها number:',
          options: ['ثلاثة عشر', 'عشرة', 'اثنا عشر', 'خمسة عشر'],
          correct: 0,
        },
        {
          title: 'كان — الماضي المنقطع',
          kind: 'mcq',
          prompt: '﴿وَكَانُوا عَلَيْهِ شُهَدَاءَ﴾ — كان here indicates:',
          options: ['الماضي المنقطع', 'الاستقبال', 'القدرة', 'الانبغاء'],
          correct: 0,
        },
        {
          title: 'كان — الماضي المتجدد',
          kind: 'mcq',
          prompt: 'كَانَا يَأْكُلَانِ الطَّعَامَ — كان here indicates:',
          options: ['الماضي المتجدد (الاستمرار/التكرار)', 'الماضي المنقطع', 'الاستقبال', 'الانبغاء'],
          correct: 0,
        },
        {
          title: 'كان — الاستقبال',
          kind: 'mcq',
          prompt: '﴿كَانَتْ لَهُمْ جَنَّاتُ الْفِرْدَوْسِ نُزُلًا﴾ — كان here indicates:',
          options: ['الاستقبال', 'الماضي المنقطع', 'الحال', 'القدرة'],
          correct: 0,
        },
        {
          title: 'كان — الانبغاء',
          kind: 'mcq',
          prompt: '﴿مَا كَانَ لَنَا أَنْ نُشْرِكَ بِاللَّهِ مِنْ شَيْءٍ﴾ — كان here indicates:',
          options: ['الانبغاء (ما ينبغي)', 'القدرة', 'الماضي المتجدد', 'الاستقبال'],
          correct: 0,
        },
        {
          title: 'معنى تقليل حذف النون',
          kind: 'mcq',
          prompt: 'Deleting the نون of يكن adds a nuance of:',
          options: ['التقليل', 'التوكيد', 'التعظيم', 'الاستمرار'],
          correct: 0,
        },
        {
          title: 'مثال عدم جواز حذف النون',
          kind: 'mcq',
          prompt: 'Why is the نون NOT dropped in ﴿لَمْ يَكُنِ الَّذِينَ كَفَرُوا﴾?',
          options: ['Because it is followed by a ساكن', "Because it's مرفوعة", 'Because it is in a فعل أمر', 'Because it is at the start of الكلام'],
          correct: 0,
        },
        {
          title: 'حذف كان واسمها',
          kind: 'mcq',
          prompt: 'كان together with its اسم may both be deleted after:',
          options: ['شرط إن ولو', 'النفي', 'الاستفهام', 'التعجب'],
          correct: 0,
        },
        {
          title: 'الفعل التام',
          kind: 'mcq',
          prompt: 'الفعل التام is sufficient with only its:',
          options: ['فاعله فقط دون خبر', 'خبره فقط دون فاعل', 'مفعوله المطلق', 'حاله فقط'],
          correct: 0,
        },
        {
          title: 'اسم الفعل الناقص',
          kind: 'mcq',
          prompt: 'The اسم that الأفعال الناقصة make مرفوعًا is called:',
          options: ['اسمها', 'خبرها', 'فاعلها', 'نائب فاعلها'],
          correct: 0,
        },
        {
          title: 'خبر الفعل الناقص',
          kind: 'mcq',
          prompt: 'The word that الأفعال الناقصة make منصوبًا is called:',
          options: ['خبرها', 'اسمها', 'حالها', 'تمييزها'],
          correct: 0,
        },
        {
          title: 'شروط حذف نون يكن (١)',
          kind: 'mcq',
          prompt: 'One condition for dropping the نون of يكن is that it be:',
          options: ['مجزومة', 'منصوبة', 'مرفوعة', 'مبنية للمجهول'],
          correct: 0,
        },
        {
          title: 'شروط حذف نون يكن (٢)',
          kind: 'mcq',
          prompt: 'Another condition for dropping the نون of يكن is that it carry no attached:',
          options: ['ضمير نصب', 'تاء التأنيث', 'واو الجماعة', 'ياء المخاطبة'],
          correct: 0,
        },
        {
          title: 'تركيب: اسم كان وخبرها',
          kind: 'tarkeeb',
          instruction: 'Identify the اسم and خبر of the ناقص فعل.',
          source: 'كَانَ الْجَوُّ صَحْوًا',
          words: ['الْجَوُّ', 'صَحْوًا'],
          labels: ['اسم كان مرفوع', 'خبر كان منصوب'],
          distractors: ['فاعل'],
        },
        {
          title: 'تركيب: معاني كان',
          kind: 'tarkeeb',
          instruction: 'Classify the meaning of كان in each example.',
          source: '﴿وكانوا عليه شهداء﴾ / كانا يأكلان الطعام / ﴿كانت لهم جنات الفردوس نزلا﴾ / ﴿ما كان لنا أن نشرك بالله من شيء﴾',
          words: ['كانوا', 'كانا', 'كانت', 'كان'],
          labels: ['الماضي المنقطع', 'الماضي المتجدد', 'الاستقبال', 'الانبغاء'],
          distractors: ['القدرة'],
        },
        {
          title: 'تركيب: حذف النون',
          kind: 'tarkeeb',
          instruction: 'Classify: is dropping the نون of يكن allowed here or not?',
          source: '﴿لم نكُ من المصلين﴾ / ﴿لم يكن الذين كفروا﴾',
          words: ['نكُ', 'يكن'],
          labels: ['يجوز الحذف', 'لا يجوز الحذف'],
          distractors: ['واجب الحذف'],
        },
        {
          title: 'تركيب: أقسام السماعي',
          kind: 'tarkeeb',
          instruction: 'Classify each: is it one of أقسام السماعي or not?',
          source: 'الأفعال الناقصة / صيغ التعجب / اللازم والمتعدي',
          words: ['الأفعال الناقصة', 'صيغ التعجب', 'اللازم والمتعدي'],
          labels: ['من أقسام السماعي', 'من أقسام السماعي', 'ليس من أقسام السماعي'],
          distractors: ['أفعال القلوب'],
        },
        {
          title: 'تركيب: أضرب الأفعال الناقصة',
          kind: 'tarkeeb',
          instruction: 'Classify: is it one of the four أضرب of الأفعال الناقصة or not?',
          source: 'كان وأخواتها / أفعال الرجاء / أفعال القلوب',
          words: ['كان وأخواتها', 'أفعال الرجاء', 'أفعال القلوب'],
          labels: ['من الأضرب الأربعة', 'من الأضرب الأربعة', 'ليس من الأضرب الأربعة'],
          distractors: ['أفعال الشروع'],
        },
        {
          title: 'تركيب: ناقص أم تام؟',
          kind: 'tarkeeb',
          instruction: 'Classify the فعل: ناقص (needs a خبر) or تام here?',
          source: 'كَانَ الْجَوُّ صَحْوًا / كَانَتْ حَرْبٌ',
          words: ['كَانَ', 'كَانَتْ'],
          labels: ['ناقص', 'تام'],
          distractors: ['لازم'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'أخوات كان',
      subtitle: 'Kāna\'s Sisters — أصبح، ظل، وصار for time and transformation, ما زال for continuation, and ما دام / ليس',
      concepts: [
        {
          heading: 'أصبح وأضحى وأمسى وظل وبات: أخوات الوقت',
          body: `Five of كان's sisters attribute the خبر to the اسم at a specific time of day. <bdi>أَصْبَحَ</bdi> — morning, as in <bdi>﴿فَأَصْبَحَ فِي الْمَدِينَةِ خَائِفًا يَتَرَقَّبُ﴾</bdi> (<bdi>غَدَا</bdi> can carry the same sense: <bdi>﴿وَغَدَوْا عَلَىٰ حَرْدٍ قَادِرِينَ﴾</bdi>); <bdi>أَضْحَى</bdi> — mid-morning (<bdi>الضُّحَى</bdi>); <bdi>أَمْسَى</bdi> — evening; <bdi>ظَلَّ</bdi> — daytime; <bdi>بَاتَ</bdi> — night, as in <bdi>﴿وَالَّذِينَ يَبِيتُونَ لِرَبِّهِمْ سُجَّدًا وَقِيَامًا﴾</bdi>. ظَلَّ can also contract, dropping one of its two <bdi>لَام</bdi>s, as in <bdi>﴿ظَلْتَ عَلَيْهِ عَاكِفًا﴾</bdi> from <bdi>ظَلِلْتَ</bdi>.`,
          sample: `أصبح — الصباح، ﴿فأصبح في المدينة خائفا يترقب﴾<br>أضحى — الضحى<br>أمسى — المساء<br>ظل — النهار<br>بات — الليل، ﴿والذين يبيتون لربهم سجدا وقياما﴾<br>ظلت (تخفيف ظللت) — ﴿ظلت عليه عاكفا﴾`,
          exercise: {
            prompt: `Which of the five time-sisters can drop one of its two لامات, as in ﴿ظَلْتَ عَلَيْهِ عَاكِفًا﴾?`,
            kind: 'mcq',
            options: ['ظَلَّ', 'أَصْبَحَ', 'أَمْسَى', 'بَاتَ'],
            correct: 0,
          },
        },
        {
          heading: 'صار وما يشاركها معنى التحول',
          body: `<bdi>صَارَ</bdi> indicates transformation, of two kinds: (1) <bdi>تَحَوُّلُ الذَّات</bdi> itself, as in <bdi>صَارَ الْخَمْرُ خَلًّا</bdi> (2) <bdi>تَحَوُّلُ الصِّفَات</bdi> alone, as in <bdi>صَارَ الْمُذْنِبُ مُتَّقِيًا</bdi>. كَانَ and the time-sisters can also carry this same بمعنى صار sense: <bdi>﴿وَكَانَ مِنَ الْكَافِرِينَ﴾</bdi>, <bdi>﴿فَأَصْبَحْتُمْ بِنِعْمَتِهِ إِخْوَانًا﴾</bdi>, <bdi>ظَلَّ وَجْهُهُ مُسْوَدًّا وَهُوَ كَظِيمٌ</bdi>. A few أفعال outside كان's family carry it too: <bdi>ارْتَدَّ</bdi> (<bdi>﴿فَارْتَدَّ بَصِيرًا﴾</bdi>), <bdi>عَادَ</bdi> (<bdi>﴿أَوْ لَتَعُودُنَّ فِي مِلَّتِنَا﴾</bdi>), and <bdi>اسْتَحَالَ</bdi>.`,
          sample: `تحول الذات — صار الخمرُ خلاً<br>تحول الصفات — صار المذنبُ متقياً<br>كان بمعنى صار — ﴿وكان من الكافرين﴾<br>أصبح بمعنى صار — ﴿فأصبحتم بنعمته إخوانا﴾<br>ارتد بمعنى صار — ﴿فارتد بصيرا﴾`,
          exercise: {
            prompt: `صَارَ الْمُذْنِبُ مُتَّقِيًا shows تحول الصفات, not تحول الذات. What is the difference between the two?`,
            kind: 'mcq',
            options: ["The first is the اسم's صفة changing alone, without its ذات; the second is the ذات itself changing", "There's no difference between them", 'The first is specific to الجماد and the second to الإنسان', 'The second only occurs with صار alone'],
            correct: 0,
          },
        },
        {
          heading: 'ما زال وأخواتها: الاستمرار',
          body: `<bdi>مَا بَرِحَ، مَا انْفَكَّ، مَا زَالَ، مَا فَتِئَ</bdi> indicate <bdi>الِاسْتِمْرَار</bdi>, as in <bdi>﴿لَنْ نَبْرَحَ عَلَيْهِ عَاكِفِينَ﴾</bdi> and <bdi>﴿فَمَا زِلْتُمْ فِي شَكٍّ﴾</bdi>. Two restrictions apply to this group: (1) they are <bdi>نَاقِصُ التَّصَرُّف</bdi> — only a <bdi>مَاضٍ</bdi> and <bdi>مُضَارِع</bdi> occur, no أمر (2) they operate as ناقص only when preceded by <bdi>نَهْي</bdi>, <bdi>نَفْي</bdi>, or <bdi>دُعَاء</bdi> — hence the <bdi>مَا</bdi> in each of their names. That نفي can itself drop after a <bdi>قَسَم</bdi>, when the فعل is a مضارع negated by <bdi>لَا</bdi>, as in <bdi>يَمِينُ اللَّهِ أَبْرَحُ قَاعِدًا</bdi> (i.e. <bdi>لَا أَبْرَحُ</bdi>). Note the difference between <bdi>زَالَ يَزَالُ</bdi> — this ناقص فعل — and <bdi>زَالَ يَزُولُ</bdi>, an ordinary <bdi>فِعْلٌ تَامّ</bdi> meaning <bdi>زَوَال</bdi>, as in <bdi>﴿أَنْ تَزُولَا﴾</bdi>.`,
          sample: `الاستمرار — ﴿لن نبرح عليه عاكفين﴾، ﴿فما زلتم في شك﴾<br>حذف النفي بعد القسم — يمين الله أبرح قاعداً (= لا أبرح)<br>زال يزال (ناقص) مقابل زال يزول (تام، بمعنى زوال) — ﴿أن تزولا﴾`,
          exercise: {
            prompt: `Why does مَا زَالَ and its three sisters carry a مَا in their very names?`,
            kind: 'mcq',
            options: ['Because they only operate as ناقص when preceded by نفي, نهي, or دعاء', "Because ما is an original part of the فعل's structure and can't be separated from it", 'Because they are only used in the صيغة الأمر', 'Because ما here is an اسم موصول, not نافية'],
            correct: 0,
          },
        },
        {
          heading: 'ما دام وليس',
          body: `<bdi>مَا دَامَ</bdi> delimits what precedes it by the duration of the اسم's being described by the خبر, as in <bdi>﴿وَأَوْصَانِي بِالصَّلَاةِ وَالزَّكَاةِ مَا دُمْتُ حَيًّا﴾</bdi>. <bdi>مَا</bdi> alone can sometimes stand in its place, as in <bdi>وَاللَّهُ فِي عَوْنِ الْعَبْدِ مَا كَانَ الْعَبْدُ فِي عَوْنِ أَخِيهِ</bdi>, frequently before <bdi>لَمْ</bdi>: <bdi>يُسْتَجَابُ لِأَحَدِكُمْ مَا لَمْ يَعْجَلْ</bdi>. <bdi>لَيْسَ</bdi> indicates <bdi>نَفْيُ الْحَال</bdi>, as in <bdi>﴿لَيْسَ عَلَيْكَ هُدَاهُمْ﴾</bdi>. Both مَا دَامَ and لَيْسَ are completely <bdi>غَيْرُ مُتَصَرِّف</bdi> — only the ماضي form of either ever occurs.`,
          sample: `ما دام — ﴿وأوصاني بالصلاة والزكاة ما دمت حيا﴾<br>ما وحدها بمعنى ما دام — والله في عون العبد ما كان العبد في عون أخيه<br>ليس — نفي الحال، ﴿ليس عليك هداهم﴾`,
          exercise: {
            prompt: `What do مَا دَامَ and لَيْسَ share, unlike ما زال and its sisters?`,
            kind: 'mcq',
            options: ['That both are completely غير متصرفين — only the ماضي form of either ever occurs', 'That neither needs a خبر at all', 'That both carry the meaning of التحول', 'That both accept dropping the نون like يكن'],
            correct: 0,
          },
        },
        {
          heading: 'التام والناقص، وتقديم الخبر ومعموله',
          body: `Almost every one of the thirteen sisters can also work as a <bdi>فِعْلٌ تَامّ</bdi>, sufficing with its فاعل alone and needing no خبر — all except <bdi>مَا زَالَ، مَا فَتِئَ، لَيْسَ</bdi>, as in <bdi>﴿وَإِنْ كَانَ ذُو عُسْرَةٍ فَنَظِرَةٌ إِلَىٰ مَيْسَرَةٍ﴾</bdi> and <bdi>﴿خَالِدِينَ فِيهَا مَا دَامَتِ السَّمَاوَاتُ وَالْأَرْضُ﴾</bdi>. Word order is also flexible: the خبر of a ناقص فعل may come between the فعل and its اسم, as in <bdi>﴿كَانَ حَقًّا عَلَيْنَا نَصْرُ الْمُؤْمِنِينَ﴾</bdi>, and the <bdi>مَعْمُول</bdi> of the خبر may even precede the فعل itself, as in <bdi>﴿أَهَٰؤُلَاءِ إِيَّاكُمْ كَانُوا يَعْبُدُونَ﴾</bdi>. A few more أفعال — <bdi>آضَ، عَادَ، غَدَا، رَاحَ</bdi> — are counted among الأفعال الناقصة by some grammarians as well.`,
          sample: `كانت حرب — كان تامة (فاعل فقط)<br>كان حقاً علينا نصرُ المؤمنين — الخبر بين الفعل والاسم<br>أهؤلاء إياكم كانوا يعبدون — معمول الخبر تقدّم على الفعل`,
          exercise: {
            prompt: `Which three sisters can NEVER work as فعل تام, always needing a خبر?`,
            kind: 'mcq',
            options: ['ما زال، ما فتئ، ليس', 'كان، أصبح، صار', 'ظل، بات، أضحى', 'ما دام، ما برح، ما انفك'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'أصبح attributes the خبر to the اسم at what time?',
          options: ['الصباح', 'الضحى', 'الليل', 'النهار'],
          correct: 0,
        },
        {
          q: 'بات indicates what time of day?',
          options: ['الليل', 'الصباح', 'الضحى', 'المساء'],
          correct: 0,
        },
        {
          q: 'صَارَ الْخَمْرُ خَلًّا — which kind of تحول is this?',
          options: ['تحول الذات', 'تحول الصفات', 'لا تحول هنا', 'الاستقبال'],
          correct: 0,
        },
        {
          q: 'ما زال وأخواتها only operate as ناقص when preceded by:',
          options: ['نفي أو نهي أو دعاء', 'استفهام', 'نداء', 'قسم فقط'],
          correct: 0,
        },
        {
          q: 'زَالَ يَزُولُ (meaning زوال) is a فعل:',
          options: ['تام', 'ناقص', 'ناسخ', 'جامد'],
          correct: 0,
        },
        {
          q: 'Which two of the thirteen sisters are completely غير متصرف (ماضٍ only)?',
          options: ['ما دام وليس', 'كان وأصبح', 'ظل وبات', 'صار وأمسى'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'أضحى',
          kind: 'mcq',
          prompt: 'أضحى attributes the خبر to the اسم at what time?',
          options: ['الضحى', 'المساء', 'الليل', 'الصباح'],
          correct: 0,
        },
        {
          title: 'أمسى',
          kind: 'mcq',
          prompt: 'أمسى indicates what time of day?',
          options: ['المساء', 'الصباح', 'الضحى', 'النهار'],
          correct: 0,
        },
        {
          title: 'ظل',
          kind: 'mcq',
          prompt: 'ظل indicates what time of day?',
          options: ['النهار', 'الليل', 'الصباح', 'الضحى'],
          correct: 0,
        },
        {
          title: 'تخفيف ظل',
          kind: 'mcq',
          prompt: '﴿ظَلْتَ عَلَيْهِ عَاكِفًا﴾ — its original form is:',
          options: ['ظللت', 'ظليت', 'ظلوت', 'ظلات'],
          correct: 0,
        },
        {
          title: 'غدا بمعنى أصبح',
          kind: 'mcq',
          prompt: 'Which فعل can carry the same sense as أصبح?',
          options: ['غدا', 'راح', 'آض', 'باد'],
          correct: 0,
        },
        {
          title: 'تحول الصفات',
          kind: 'mcq',
          prompt: 'صَارَ الْمُذْنِبُ مُتَّقِيًا — which kind of تحول is this?',
          options: ['تحول الصفات', 'تحول الذات', 'لا تحول', 'الانبغاء'],
          correct: 0,
        },
        {
          title: 'كان بمعنى صار',
          kind: 'mcq',
          prompt: '﴿وَكَانَ مِنَ الْكَافِرِينَ﴾ — كان here means:',
          options: ['صار', 'ما زال', 'ليس', 'عسى'],
          correct: 0,
        },
        {
          title: 'أفعال أخرى بمعنى صار',
          kind: 'mcq',
          prompt: 'Which أفعال, outside كان وأخواتها, can also carry the meaning of صار?',
          options: ['ارتد، عاد، استحال', 'وجد، علم، ظن', 'أعطى، منح، وهب', 'صيّر، ترك، جعل'],
          correct: 0,
        },
        {
          title: 'لن نبرح عليه عاكفين',
          kind: 'mcq',
          prompt: '﴿لَنْ نَبْرَحَ عَلَيْهِ عَاكِفِينَ﴾ indicates:',
          options: ['الاستمرار', 'الانبغاء', 'القدرة', 'التحول'],
          correct: 0,
        },
        {
          title: 'شرط عمل ما زال الناقص',
          kind: 'mcq',
          prompt: 'ما زال وأخواتها only operate as ناقص when preceded by:',
          options: ['نفي أو نهي أو دعاء', 'استفهام أو نداء', 'قسم فقط', 'شرط فقط'],
          correct: 0,
        },
        {
          title: 'تصرف ما زال',
          kind: 'mcq',
          prompt: 'ما زال and its three sisters (ما برح، ما انفك، ما فتئ), in terms of تصرف, are:',
          options: ['ناقصة التصرف: ماضٍ ومضارع فقط', 'تامة التصرف: كل الصيغ ترد', 'جامدة: الماضي فقط', 'لا تتصرف إطلاقا'],
          correct: 0,
        },
        {
          title: 'حذف النفي بعد القسم',
          kind: 'mcq',
          prompt: 'يَمِينُ اللَّهِ أَبْرَحُ قَاعِدًا — its implied meaning is:',
          options: ['والله لا أبرح قاعداً', 'والله أبرح قاعداً بمعنى أزول', 'والله كنت قاعداً', 'لا تقدير هنا'],
          correct: 0,
        },
        {
          title: 'ما دام',
          kind: 'mcq',
          prompt: 'ما دام indicates:',
          options: ['تحديد المدة بدوام الوصف', 'الاستمرار المطلق بلا قيد', 'نفي الحال', 'التحول من حال إلى حال'],
          correct: 0,
        },
        {
          title: 'ما وحدها بمعنى ما دام',
          kind: 'mcq',
          prompt: 'When ما alone stands in place of ما دام, it frequently precedes:',
          options: ['لم', 'لن', 'إن', 'هل'],
          correct: 0,
        },
        {
          title: 'ليس',
          kind: 'mcq',
          prompt: 'ليس indicates:',
          options: ['نفي الحال', 'نفي الماضي', 'نفي الاستقبال', 'التحول'],
          correct: 0,
        },
        {
          title: 'غير المتصرفتين بالكلية',
          kind: 'mcq',
          prompt: 'Which two sisters of كان are completely غير متصرف (ماضٍ only)?',
          options: ['ما دام وليس', 'كان وأصبح', 'ظل وبات', 'صار وأمسى'],
          correct: 0,
        },
        {
          title: 'تقديم الخبر',
          kind: 'mcq',
          prompt: '﴿كَانَ حَقًّا عَلَيْنَا نَصْرُ الْمُؤْمِنِينَ﴾ proves that the خبر of a ناقص فعل can:',
          options: ['يقع بين الفعل واسمه', 'يُحذف دائما', 'يتقدم على الفعل نفسه', 'يكون جملة فعلية فقط'],
          correct: 0,
        },
        {
          title: 'تقدم معمول الخبر',
          kind: 'mcq',
          prompt: '﴿أَهَٰؤُلَاءِ إِيَّاكُمْ كَانُوا يَعْبُدُونَ﴾ proves that the معمول of the خبر can:',
          options: ['يتقدم على الفعل الناقص نفسه', 'لا يتقدم أبدا', 'يُحذف مع الفعل', 'يصبح اسما لكان'],
          correct: 0,
        },
        {
          title: 'تركيب: أخوات الوقت',
          kind: 'tarkeeb',
          instruction: "Classify each of كان's sisters by its time of day.",
          source: 'أصبح / أضحى / أمسى / بات',
          words: ['أصبح', 'أضحى', 'أمسى', 'بات'],
          labels: ['الصباح', 'الضحى', 'المساء', 'الليل'],
          distractors: ['النهار'],
        },
        {
          title: 'تركيب: تحول الذات أم الصفات؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example of صار.',
          source: 'صار الخمرُ خلاً / صار المذنبُ متقياً',
          words: ['الخمرُ خلاً', 'المذنبُ متقياً'],
          labels: ['تحول الذات', 'تحول الصفات'],
          distractors: ['لا تحول'],
        },
        {
          title: 'تركيب: بمعنى صار',
          kind: 'tarkeeb',
          instruction: 'Classify: is the فعل here بمعنى صار, or its original meaning?',
          source: '﴿وكان من الكافرين﴾ / ﴿وكانوا عليه شهداء﴾',
          words: ['كان (من الكافرين)', 'كانوا (شهداء)'],
          labels: ['بمعنى صار', 'على معناه الأصلي'],
          distractors: ['بمعنى ليس'],
        },
        {
          title: 'تركيب: ما زال وأخواتها',
          kind: 'tarkeeb',
          instruction: 'Classify: is it one of أخوات ما زال or not?',
          source: 'ما برح / ما انفك / ما دام',
          words: ['ما برح', 'ما انفك', 'ما دام'],
          labels: ['من أخوات ما زال', 'من أخوات ما زال', 'ليس من أخوات ما زال'],
          distractors: ['ما فتئ'],
        },
        {
          title: 'تركيب: زال يزال أم زال يزول؟',
          kind: 'tarkeeb',
          instruction: 'Classify: ناقص (زال يزال) or تام (زال يزول)?',
          source: 'ما زلتم في شك / أن تزولا',
          words: ['زلتم', 'تزولا'],
          labels: ['ناقص (زال يزال)', 'تام (زال يزول)'],
          distractors: ['فعل قلب'],
        },
        {
          title: 'تركيب: تام أم ناقص؟',
          kind: 'tarkeeb',
          instruction: 'Classify the فعل: تام or ناقص here?',
          source: 'كانت حربٌ / كان حقاً علينا نصرُ المؤمنين',
          words: ['كانت', 'كان'],
          labels: ['تام', 'ناقص'],
          distractors: ['محذوف'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الرجاء والمقاربة والشروع',
      subtitle: 'Hope, Nearness, and Onset — عسى وكاد وطفق, and how أنّ behaves in each خبر',
      concepts: [
        {
          heading: 'أفعال الرجاء: عسى وأخواتها',
          body: `<bdi>عَسَى، اخْلَوْلَقَ، حَرَى</bdi> are established to indicate <bdi>الرَّجَاء</bdi> (hope), as in <bdi>﴿عَسَىٰ أَنْ يَنْفَعَنَا أَوْ نَتَّخِذَهُ وَلَدًا﴾</bdi>. عَسَى itself carries three senses: (1) <bdi>التَّرَجِّي</bdi> in something loved, as in <bdi>﴿عَسَى اللَّهُ أَنْ يَعْفُوَ عَنْهُمْ﴾</bdi> (2) <bdi>الْإِشْفَاق</bdi>, apprehension of something disliked, as in <bdi>﴿فَهَلْ عَسَيْتُمْ إِنْ تَوَلَّيْتُمْ أَنْ تُفْسِدُوا فِي الْأَرْضِ﴾</bdi> (3) <bdi>التَّعْلِيل</bdi>, as in <bdi>﴿عَسَىٰ أَنْ يَبْعَثَكَ رَبُّكَ مَقَامًا مَحْمُودًا﴾</bdi>.`,
          sample: `أفعال الرجاء (٣) — عسى، اخلولق، حرى<br>الترجي — ﴿عسى الله أن يعفو عنهم﴾<br>الإشفاق — ﴿فهل عسيتم إن توليتم أن تفسدوا في الأرض﴾<br>التعليل — ﴿عسى أن يبعثك ربك مقاما محمودا﴾`,
          exercise: {
            prompt: `﴿فَهَلْ عَسَيْتُمْ إِنْ تَوَلَّيْتُمْ أَنْ تُفْسِدُوا فِي الْأَرْضِ﴾ warns of something disliked. Which of عسى's three senses is this?`,
            kind: 'mcq',
            options: ['الإشفاق', 'الترجي', 'التعليل', 'اليقين'],
            correct: 0,
          },
        },
        {
          heading: 'عسى مقابل لعل، ومعنى اخلولق وحرى',
          body: `عَسَى carries <bdi>الْمُقَارَبَة</bdi> (nearness of occurrence) — <bdi>لَعَلَّ</bdi> does not, which is what separates the two. When عسى is attributed to Allah, its predominant sense flips to certainty (<bdi>الْيَقِين</bdi>) rather than hope, since الرجاء properly belongs to the addressee, not to Allah: <bdi>﴿عَسَىٰ أَنْ يَبْعَثَكَ رَبُّكَ مَقَامًا مَحْمُودًا﴾</bdi>. <bdi>اخْلَوْلَقَ</bdi> means <bdi>صَارَ خَلِيقًا</bdi> (became apt), as in <bdi>اخْلَوْلَقَ الْمُسْلِمُونَ أَنْ يُحَافِظُوا عَلَى الصَّلَاةِ</bdi>; <bdi>حَرَى</bdi> means <bdi>صَارَ حَرِيًّا</bdi> (became worthy), as in <bdi>حَرَى الْمُذْنِبُ أَنْ يَتُوبَ</bdi>.`,
          sample: `عسى تفيد المقاربة، لعل لا تفيدها<br>عسى منسوبة إلى الله — الغالب اليقين<br>اخلولق = صار خليقا<br>حرى = صار حريا`,
          exercise: {
            prompt: `What distinguishes عسى from لعل, even though both can express hope?`,
            kind: 'mcq',
            options: ["That عسى carries المقاربة and لعل doesn't", 'That لعل only enters upon الفعل الماضي', 'That عسى is a حرف and لعل is a فعل', "There's no difference between them at all"],
            correct: 0,
          },
        },
        {
          heading: 'أن في خبر أفعال الرجاء، وكونها تامة',
          body: `<bdi>أَنْ</bdi> is common (<bdi>يَكْثُرُ</bdi>) in the خبر of عسى, and obligatory (<bdi>يَجِبُ</bdi>) in the خبر of اخلولق and حرى. Like الأفعال الناقصة generally, أفعال الرجاء can also work as <bdi>تَامَّة</bdi> — sufficing with an <bdi>اسْمٌ مُؤَوَّل</bdi> standing as their فاعل, as in <bdi>﴿عَسَىٰ أَنْ يَبْعَثَكَ رَبُّكَ مَقَامًا مَحْمُودًا﴾</bdi>, where <bdi>أَنْ يَبْعَثَكَ</bdi> is itself the فاعل of عسى.`,
          sample: `أن يكثر في خبر عسى، ويجب في خبر اخلولق وحرى<br>عسى تامة — ﴿عسى أن يبعثك ربك مقاما محمودا﴾ (أن يبعثك: فاعل عسى)`,
          exercise: {
            prompt: `In ﴿عَسَىٰ أَنْ يَبْعَثَكَ رَبُّكَ مَقَامًا مَحْمُودًا﴾ read as عسى تامة, what is أَنْ يَبْعَثَكَ?`,
            kind: 'mcq',
            options: ['اسم مؤول هو فاعل عسى', 'خبر عسى الناقصة', 'مفعول به لعسى', 'اسم عسى الناقصة'],
            correct: 0,
          },
        },
        {
          heading: 'أفعال المقاربة: كاد وكرب وأوشك',
          body: `<bdi>كَادَ، كَرَبَ، أَوْشَكَ</bdi> indicate the nearness of the خبر's occurrence, as in <bdi>﴿وَكَادُوا يَقْتُلُونَنِي﴾</bdi>. عسى and كاد both carry مقاربة, but differently: عسى by way of hope (<bdi>عَلَى سَبِيلِ الرَّجَاء</bdi>), كاد and its sisters by way of actual closeness to occurrence (<bdi>عَلَى سَبِيلِ الْحُصُول</bdi>). Affirmed كاد (<bdi>الْمُثْبَت</bdi>) indicates the act did NOT happen, but came close, as in <bdi>﴿وَكَادُوا يَقْتُلُونَنِي﴾</bdi>; negated كاد (<bdi>الْمَنْفِيّ</bdi>) is a stronger نفي, denying even the nearness itself, as in <bdi>﴿وَلَا يَكَادُ يُسِيغُهُ﴾</bdi>.`,
          sample: `أفعال المقاربة (٣) — كاد، كرب، أوشك<br>عسى: مقاربة بالرجاء / كاد: مقاربة بالحصول<br>كاد مثبتا — ﴿وكادوا يقتلونني﴾ (لم يقع الفعل، لكن قارب)<br>كاد منفيا — ﴿ولا يكاد يسيغه﴾ (نفي أقوى، نفي القرب نفسه)`,
          exercise: {
            prompt: `﴿وَلَا يَكَادُ يُسِيغُهُ﴾ negates كاد. Does this negate only the ACT, or the nearness of the act too?`,
            kind: 'mcq',
            options: ['It negates the nearness of the فعل — a stronger negation than merely negating its occurrence', 'It negates only the occurrence of the فعل, and the nearness remains', 'It negates nothing — it is actually توكيد', 'It negates the فاعل, not the فعل'],
            correct: 0,
          },
        },
        {
          heading: 'أن في خبر المقاربة، وحذف الخبر، وتصرف المجموعتين',
          body: `<bdi>أَنْ</bdi> is common in the خبر of <bdi>أَوْشَكَ</bdi> but rare (<bdi>يَقِلّ</bdi>) in the خبر of كاد وكرب — because أن indicates <bdi>الِاسْتِقْبَال</bdi> (the future), and أفعال الرجاء and أوشك sit far from actual occurrence, while كاد وكرب sit close to it, so أن does not suit them as well. The خبر of أفعال المقاربة may also be deleted when known from context, as in <bdi>مَنْ عَجِلَ أَخْطَأَ أَوْ كَادَ</bdi> (i.e. <bdi>أَوْ كَادَ يُخْطِئُ</bdi>). Both أفعال الرجاء والمقاربة are <bdi>نَاقِصُ التَّصَرُّف</bdi>, restricted to the ماضي — except <bdi>كَادَ</bdi> (<bdi>﴿يَكَادُ الْبَرْقُ يَخْطَفُ أَبْصَارَهُمْ﴾</bdi>) and <bdi>أَوْشَكَ</bdi> (<bdi>يُوشِكُ أَنْ يَعُمَّهُمُ اللَّهُ بِعِقَابٍ</bdi>), which also have a مضارع.`,
          sample: `أن يكثر في خبر أوشك، ويقل في خبر كاد وكرب<br>حذف الخبر — من عجل أخطأ أو كاد (= أو كاد يخطئ)<br>كاد وأوشك — لهما مضارع؛ الباقي ماضٍ فقط`,
          exercise: {
            prompt: `Why does أن suit the خبر of أوشك more than it suits كاد?`,
            kind: 'mcq',
            options: ['Because أن indicates الاستقبال, and أوشك is farther from actual occurrence than كاد', "Because أوشك is a فعل قلب and كاد isn't", 'Because كاد never accepts أن at all', 'There is no difference between them in accepting أن'],
            correct: 0,
          },
        },
        {
          heading: 'أفعال الشروع',
          body: `<bdi>جَعَلَ، أَخَذَ، طَفِقَ، عَلِقَ، أَنْشَأَ</bdi> indicate commencement of the act, as in <bdi>﴿وَطَفِقَا يَخْصِفَانِ عَلَيْهِمَا مِنْ وَرَقِ الْجَنَّةِ﴾</bdi>. Despite being grouped with السماعي here, they are actually <bdi>قِيَاسِيَّة</bdi> — mentioned alongside الأفعال الناقصة only because they resemble them in government. Two restrictions apply: (1) they occur only in the ماضي (2) their خبر must be a <bdi>جُمْلَةٌ فِعْلِيَّة</bdi> built on a مضارع, stripped of أن. An umbrella name, <bdi>أَفْعَالُ الْمُقَارَبَة</bdi>, is sometimes applied loosely to all three groups of this lesson together — عسى وأخواتها, كاد وأخواتها, and طفق وأخواتها.`,
          sample: `أفعال الشروع — جعل، أخذ، طفق، علق، أنشأ<br>﴿وطفقا يخصفان عليهما من ورق الجنة﴾<br>أفعال الشروع قياسية، لا سماعية حقيقة<br>خبرها: جملة فعلية مضارعة بلا أن`,
          exercise: {
            prompt: `Why are أفعال الشروع covered in this السماعي lesson if they are actually قياسية, not سماعية?`,
            kind: 'mcq',
            options: ['Because they only resemble الأفعال الناقصة in government, so they are mentioned alongside them', "Because their rule actually isn't مطردة", 'Because scholars disagreed on classifying them, so they were placed here as a precaution', 'Because they do not fit into any other category'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أفعال الرجاء are there?',
          options: ['ثلاثة', 'اثنان', 'أربعة', 'خمسة'],
          correct: 0,
        },
        {
          q: 'عسى indicates المقاربة, unlike:',
          options: ['لعل', 'كاد', 'أوشك', 'حرى'],
          correct: 0,
        },
        {
          q: 'أن is obligatory in the خبر of:',
          options: ['اخلولق وحرى', 'عسى وكاد', 'أوشك وكرب', 'كان وأصبح'],
          correct: 0,
        },
        {
          q: 'Negated كاد (as in ﴿وَلَا يَكَادُ يُسِيغُهُ﴾) negates:',
          options: ['وقوع الفعل وقربه معا', 'وقوع الفعل فقط دون قربه', 'الفاعل لا الفعل', 'لا ينفي شيئا'],
          correct: 0,
        },
        {
          q: 'Which two verbs of أفعال الرجاء والمقاربة have a مضارع form?',
          options: ['كاد وأوشك', 'عسى وكرب', 'اخلولق وحرى', 'جعل وأخذ'],
          correct: 0,
        },
        {
          q: 'The خبر of أفعال الشروع must be:',
          options: ['جملة فعلية مضارعة بلا أن', 'جملة اسمية', 'مصدرا مؤولا بأن', 'اسما مفردا'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'أفعال الرجاء',
          kind: 'mcq',
          prompt: 'The three أفعال الرجاء are:',
          options: ['عسى، اخلولق، حرى', 'كاد، كرب، أوشك', 'جعل، أخذ، طفق', 'عسى، كاد، جعل'],
          correct: 0,
        },
        {
          title: 'الترجي',
          kind: 'mcq',
          prompt: '﴿عَسَى اللَّهُ أَنْ يَعْفُوَ عَنْهُمْ﴾ — which sense of عسى is this?',
          options: ['الترجي', 'الإشفاق', 'التعليل', 'اليقين المحض'],
          correct: 0,
        },
        {
          title: 'الإشفاق',
          kind: 'mcq',
          prompt: '﴿فَهَلْ عَسَيْتُمْ إِنْ تَوَلَّيْتُمْ أَنْ تُفْسِدُوا فِي الْأَرْضِ﴾ — which sense of عسى is this?',
          options: ['الإشفاق', 'الترجي', 'التعليل', 'المقاربة المجردة'],
          correct: 0,
        },
        {
          title: 'التعليل',
          kind: 'mcq',
          prompt: "Among عسى's senses are الترجي and الإشفاق, and also:",
          options: ['التعليل', 'التوكيد', 'الاستفهام', 'التمني'],
          correct: 0,
        },
        {
          title: 'عسى منسوبة إلى الله',
          kind: 'mcq',
          prompt: 'When عسى is attributed to Allah, its predominant sense is:',
          options: ['اليقين', 'الإشفاق', 'الشك', 'التمني'],
          correct: 0,
        },
        {
          title: 'معنى اخلولق',
          kind: 'mcq',
          prompt: 'اخلولق means:',
          options: ['صار خليقا', 'صار حريا', 'قارب الوقوع', 'صار مؤكدا'],
          correct: 0,
        },
        {
          title: 'معنى حرى',
          kind: 'mcq',
          prompt: 'حرى means:',
          options: ['صار حريا', 'صار خليقا', 'رجا', 'أشفق'],
          correct: 0,
        },
        {
          title: 'عسى تامة',
          kind: 'mcq',
          prompt: '﴿عَسَىٰ أَنْ يَبْعَثَكَ رَبُّكَ مَقَامًا مَحْمُودًا﴾ — read as عسى تامة, أَنْ يَبْعَثَكَ is:',
          options: ['فاعل عسى (اسم مؤول)', 'خبر عسى', 'مفعول به', 'اسم عسى'],
          correct: 0,
        },
        {
          title: 'أفعال المقاربة',
          kind: 'mcq',
          prompt: 'The three أفعال المقاربة are:',
          options: ['كاد، كرب، أوشك', 'عسى، اخلولق، حرى', 'جعل، أخذ، طفق', 'كاد، عسى، حرى'],
          correct: 0,
        },
        {
          title: 'الفرق بين عسى وكاد',
          kind: 'mcq',
          prompt: 'كاد indicates المقاربة by way of:',
          options: ['Actual nearness of occurrence, unlike عسى, which is by way of hope', 'Hope, exactly like عسى', 'Sheer doubt', 'Wishing'],
          correct: 0,
        },
        {
          title: 'كاد مثبتا',
          kind: 'mcq',
          prompt: '﴿وَكَادُوا يَقْتُلُونَنِي﴾ — كاد here is مثبتة, so it means:',
          options: ["The killing didn't happen, but it came close", 'The killing actually happened', 'The فعل has no relation to nearness of occurrence', 'An emphatic negation of the killing'],
          correct: 0,
        },
        {
          title: 'كاد منفيا',
          kind: 'mcq',
          prompt: '﴿وَلَا يَكَادُ يُسِيغُهُ﴾ — the نفي here is:',
          options: ['Stronger than negating mere occurrence — it negates even the nearness itself', 'Weaker than affirmation', 'Does not convey real negation', 'Specific to أوشك only'],
          correct: 0,
        },
        {
          title: 'أن في خبر أوشك',
          kind: 'mcq',
          prompt: 'أن in the خبر of أوشك:',
          options: ['يكثر ورودها', 'يجب ورودها دائما', 'تمتنع', 'لا تدخل على أوشك أصلا'],
          correct: 0,
        },
        {
          title: 'أن في خبر كاد',
          kind: 'mcq',
          prompt: 'أن in the خبر of كاد:',
          options: ['يقل ورودها', 'يكثر ورودها', 'تجب دائما', 'ممتنعة كليا'],
          correct: 0,
        },
        {
          title: 'حذف خبر المقاربة',
          kind: 'mcq',
          prompt: 'مَنْ عَجِلَ أَخْطَأَ أَوْ كَادَ — the deleted خبر is understood as:',
          options: ['أو كاد يخطئ', 'أو كاد يعجل', 'أو كاد يندم', 'لا شيء محذوف'],
          correct: 0,
        },
        {
          title: 'تصرف الرجاء والمقاربة',
          kind: 'mcq',
          prompt: 'أفعال الرجاء والمقاربة, in terms of تصرف and excepting كاد وأوشك, are:',
          options: ['ناقصة التصرف، تلزم الماضي', 'تامة التصرف', 'جامدة بالكلية', 'تلزم المضارع فقط'],
          correct: 0,
        },
        {
          title: 'أفعال الشروع',
          kind: 'mcq',
          prompt: 'The five أفعال الشروع are:',
          options: ['جعل، أخذ، طفق، علق، أنشأ', 'عسى، كاد، أوشك، كرب، حرى', 'كان، أصبح، ظل، بات، صار', 'وجد، علم، ظن، حسب، رأى'],
          correct: 0,
        },
        {
          title: 'أفعال الشروع قياسية',
          kind: 'mcq',
          prompt: 'أفعال الشروع, in terms of origin, are actually:',
          options: ['قياسية, but mentioned alongside السماعي because they resemble الأفعال الناقصة', 'Purely سماعية, like the rest of this قسم', 'Not classified under الناقصة at all', 'Disputed between قياسية and سماعية'],
          correct: 0,
        },
        {
          title: 'تركيب: معاني عسى',
          kind: 'tarkeeb',
          instruction: 'Classify the meaning of عسى in each example.',
          source: '﴿عسى الله أن يعفو عنهم﴾ / ﴿فهل عسيتم إن توليتم أن تفسدوا في الأرض﴾ / ﴿عسى أن يبعثك ربك مقاما محمودا﴾',
          words: ['عسى (يعفو)', 'عسيتم', 'عسى (يبعثك)'],
          labels: ['الترجي', 'الإشفاق', 'التعليل'],
          distractors: ['اليقين المحض'],
        },
        {
          title: 'تركيب: أفعال الرجاء والمقاربة والشروع',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: which group does it belong to?',
          source: 'عسى / كاد / طفق',
          words: ['عسى', 'كاد', 'طفق'],
          labels: ['أفعال الرجاء', 'أفعال المقاربة', 'أفعال الشروع'],
          distractors: ['أفعال المدح'],
        },
        {
          title: 'تركيب: كاد مثبتا أم منفيا؟',
          kind: 'tarkeeb',
          instruction: 'Classify كاد in each example: مثبت or منفي?',
          source: '﴿وكادوا يقتلونني﴾ / ﴿ولا يكاد يسيغه﴾',
          words: ['كادوا', 'يكاد'],
          labels: ['مثبت', 'منفي'],
          distractors: ['مجزوم'],
        },
        {
          title: 'تركيب: أن يكثر أم يقل أم يجب؟',
          kind: 'tarkeeb',
          instruction: "Classify the ruling on أن in each verb's خبر.",
          source: 'عسى / اخلولق / أوشك / كاد',
          words: ['عسى', 'اخلولق', 'أوشك', 'كاد'],
          labels: ['يكثر', 'يجب', 'يكثر', 'يقل'],
          distractors: ['يمتنع'],
        },
        {
          title: 'تركيب: لها مضارع أم تلزم الماضي؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل by its تصرف.',
          source: 'كاد / أوشك / عسى / طفق',
          words: ['كاد', 'أوشك', 'عسى', 'طفق'],
          labels: ['لها مضارع', 'لها مضارع', 'تلزم الماضي', 'تلزم الماضي'],
          distractors: ['لها أمر'],
        },
        {
          title: 'تركيب: مراجعة عامة',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: رجاء, مقاربة, or شروع?',
          source: 'حرى / كرب / أخذ / اخلولق',
          words: ['حرى', 'كرب', 'أخذ', 'اخلولق'],
          labels: ['رجاء', 'مقاربة', 'شروع', 'رجاء'],
          distractors: ['ناقصة زمنية'],
        },
      ],
    },

    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'أفعال المدح والذم',
      subtitle: 'Praise and Blame — نعم وبئس وحبذا, their فاعل, and the مخصوص',
      concepts: [
        {
          heading: 'تعريف أفعال المدح والذم، والقائمة الخمسة',
          body: `<bdi>أَفْعَالُ الْمَدْحِ وَالذَّمّ</bdi> — the second قسم of السماعي — indicate praise or blame, and put both their <bdi>فَاعِل</bdi> and their <bdi>مَخْصُوص</bdi> (the specified subject actually being praised or blamed) in the <bdi>مَرْفُوع</bdi>. There are five: (1) <bdi>نِعْمَ</bdi>, as in <bdi>﴿وَلَنِعْمَ دَارُ الْمُتَّقِينَ﴾</bdi> (2) <bdi>حَبَّذَا</bdi>, as in <bdi>حَبَّذَا خَالِدٌ</bdi> (3) <bdi>بِئْسَ</bdi>, as in <bdi>﴿بِئْسَ الشَّرَابُ﴾</bdi> (4) <bdi>سَاءَ</bdi>, as in <bdi>﴿وَسَاءَتْ مُرْتَفَقًا﴾</bdi> (5) <bdi>لَا حَبَّذَا</bdi>, as in <bdi>لَا حَبَّذَا الْكِبْرُ</bdi>.`,
          sample: `أفعال المدح والذم (٥) — نعم، حبذا، بئس، ساء، لا حبذا<br>﴿ولنعم دار المتقين﴾<br>﴿بئس الشراب﴾<br>﴿وساءت مرتفقا﴾`,
          exercise: {
            prompt: `Which of these five أفعال is for المدح (praise), not الذم (blame)?`,
            kind: 'mcq',
            options: ['حبذا', 'بئس', 'ساء', 'لا حبذا'],
            correct: 0,
          },
        },
        {
          heading: 'التصرف، والإلحاق، والتأنيث',
          body: `أفعال المدح والذم are <bdi>غَيْرُ مُتَصَرِّفَة</bdi> — only the <bdi>تَاء</bdi> (of تأنيث) may attach to them, as in <bdi>نِعِمَتْ، سَاءَتْ</bdi>. Any فعل on the pattern <bdi>فَعُلَ</bdi> is <bdi>مُلْحَق</bdi> (annexed) to this class, whether the pattern is original, as in <bdi>﴿وَحَسُنَتْ مُرْتَفَقًا﴾</bdi>, or converted to it, as in <bdi>كَتُبَ زَيْدٌ</bdi> ("what a writer Zayd is!"). The <bdi>تَأْنِيث</bdi> of these أفعال is permitted when either the فاعل is feminine — <bdi>نِعْمَ الْمَرْأَةُ فَاطِمَةُ</bdi> / <bdi>نِعِمَتِ الْمَرْأَةُ فَاطِمَةُ</bdi> — or when the مخصوص is feminine — <bdi>نِعِمَتْ جَزَاءَ الْمُتَّقِينَ الْجَنَّةُ</bdi>.`,
          sample: `غير متصرفة — لا يلحقها إلا تاء التأنيث: نِعِمَتْ، سَاءَتْ<br>الملحق بها — فعُل، أصلا أو تحويلا: ﴿وحسنت مرتفقا﴾، كتُب زيدٌ<br>تأنيث لتأنيث الفاعل — نعمت المرأة فاطمة<br>تأنيث لتأنيث المخصوص — نعمت جزاء المتقين الجنه`,
          exercise: {
            prompt: `كَتُبَ زَيْدٌ ("what a writer Zayd is!") uses a فعل converted to the فَعُلَ pattern. What is this called relative to أفعال المدح والذم?`,
            kind: 'mcq',
            options: ['ملحق بأفعال المدح والذم', 'فعل قلب مشابه لها', 'فعل ناقص من أخواتها', 'فعل تحويل بمعناها'],
            correct: 0,
          },
        },
        {
          heading: 'صور فاعل نعم وبئس، ونعما',
          body: `The فاعل of نعم and بئس takes one of three permitted forms: (1) an اسم carrying <bdi>لَامُ الْجِنْس</bdi>, as in <bdi>﴿نِعْمَ الْعَبْدُ﴾</bdi> (2) an اسم <bdi>مُضَاف</bdi> to such a noun, as in <bdi>﴿نِعْمَ أَجْرُ الْعَامِلِينَ﴾</bdi> (3) a <bdi>ضَمِيرٌ مُسْتَتِر</bdi>, explained by a <bdi>تَمْيِيز</bdi> converted from the فاعل, as in <bdi>﴿وَسَاءَتْ مَصِيرًا﴾</bdi>. The word <bdi>مَا</bdi> can also occur immediately after نعم and بئس in place of the usual فاعل, as in <bdi>﴿فَنِعِمَّا هِيَ﴾</bdi>.`,
          sample: `لام الجنس — ﴿نعم العبد﴾<br>مضاف إلى ما فيه لام الجنس — ﴿نعم أجر العاملين﴾<br>ضمير مستتر + تمييز — ﴿وساءت مصيرا﴾<br>ما مكان الفاعل — ﴿فنعما هي﴾`,
          exercise: {
            prompt: `In ﴿وَسَاءَتْ مَصِيرًا﴾, what is the فاعل of سَاءَتْ, and what is مَصِيرًا?`,
            kind: 'mcq',
            options: ['الفاعل ضمير مستتر، ومصيرا تمييز يفسره', 'الفاعل مصيرا نفسه', 'لا فاعل لساءت هنا', 'الفاعل محذوف بلا تمييز'],
            correct: 0,
          },
        },
        {
          heading: 'حذف المخصوص',
          body: `The <bdi>مَخْصُوص</bdi> — the noun actually being praised or blamed — may be deleted when context makes it clear, as in <bdi>﴿نِعْمَ الْمَوْلَىٰ وَنِعْمَ النَّصِيرُ﴾</bdi>, meaning <bdi>هُوَ</bdi> in both places.`,
          sample: `حذف المخصوص — ﴿نعم المولى ونعم النصير﴾ (أي: هو)`,
          exercise: {
            prompt: `﴿نِعْمَ الْمَوْلَىٰ وَنِعْمَ النَّصِيرُ﴾ has no مخصوص written out. What licenses that omission?`,
            kind: 'mcq',
            options: ["That the context points to it, so it's deleted", 'That نعم here is a فعل تام needing no مخصوص', 'That المولى and النصير are themselves the مخصوص', 'Deleting the مخصوص is never permitted'],
            correct: 0,
          },
        },
        {
          heading: 'أحكام حبذا: الحال والتمييز، ومن، ويا، وثبات ذا',
          body: `A <bdi>مَنْصُوب</bdi> may appear before or after the مخصوص of حبذا / لا حبذا, parsed two ways: as <bdi>حَال</bdi> if it is <bdi>مُشْتَقّ</bdi> — <bdi>حَبَّذَا رَاكِبًا زَيْدٌ</bdi> / <bdi>حَبَّذَا زَيْدٌ رَاكِبًا</bdi> — or as <bdi>تَمْيِيز</bdi> if it is <bdi>جَامِد</bdi> — <bdi>حَبَّذَا رَجُلًا زَيْدٌ</bdi> / <bdi>حَبَّذَا زَيْدٌ رَجُلًا</bdi>. That تمييز can also be expressed with <bdi>حَرْفُ الْجَرِّ مِنْ</bdi>, as in <bdi>حَبَّذَا زَيْنَبُ مِنْ مُعَلِّمَةٍ</bdi>. <bdi>يَا</bdi> may enter on the <bdi>حَبّ</bdi> part, as in <bdi>يَا حَبَّذَا مُحَمَّدٌ مِنْ جَارٍ</bdi>. Finally, <bdi>ذَا</bdi> after حَبّ stays fixed in the singular masculine (<bdi>الْإِفْرَاد وَالتَّذْكِير</bdi>) no matter what the مخصوص is, as in <bdi>حَبَّذَا رِجَالًا الْأَنْصَارُ</bdi> and <bdi>حَبَّذَا بِنْتًا فَاطِمَةُ</bdi>.`,
          sample: `حال (مشتق) — حبذا راكباً زيدٌ<br>تمييز (جامد) — حبذا رجلاً زيدٌ<br>تمييز بـمن — حبذا زينب من معلمة<br>يا على حبّ — يا حبذا محمد من جار<br>ذا ثابتة الإفراد والتذكير — حبذا رجالاً الأنصار، حبذا بنتاً فاطمة`,
          exercise: {
            prompt: `حَبَّذَا رِجَالًا الْأَنْصَارُ keeps ذَا singular masculine even though المخصوص (الأنصار) is plural. What rule explains that?`,
            kind: 'mcq',
            options: ['ذا after حبّ always stays الإفراد والتذكير, whatever المخصوص is', 'الأنصار here is مؤنث, so ذا must take التأنيث', 'ذا here is a ضمير matching الفاعل, not المخصوص', 'This is a common linguistic mistake with no rule behind it'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أفعال المدح والذم are there?',
          options: ['خمسة', 'ثلاثة', 'أربعة', 'ستة'],
          correct: 0,
        },
        {
          q: 'أفعال المدح والذم, in terms of تصرف, are:',
          options: ['غير متصرفة، يلحقها تاء التأنيث فقط', 'تامة التصرف', 'ناقصة التصرف: ماضٍ ومضارع', 'تلزم المضارع فقط'],
          correct: 0,
        },
        {
          q: 'كَتُبَ زَيْدٌ (meaning "what a writer Zayd is!") — this فعل is:',
          options: ['ملحق بأفعال المدح والذم', 'من أفعال الشروع', 'من أفعال المقاربة', 'فعل ناقص'],
          correct: 0,
        },
        {
          q: 'The third permitted form of the فاعل of نعم and بئس is:',
          options: ['ضمير مستتر يفسره تمييز', 'اسم بلام الجنس', 'اسم مضاف', 'مصدر مؤول'],
          correct: 0,
        },
        {
          q: '﴿نِعْمَ الْمَوْلَىٰ وَنِعْمَ النَّصِيرُ﴾ — the مخصوص in both is:',
          options: ['محذوف تقديره هو', 'مذكور وهو المولى', 'مذكور وهو النصير', 'لا مخصوص لهما'],
          correct: 0,
        },
        {
          q: 'ذَا after حَبّ:',
          options: ['تلزم الإفراد والتذكير دائما', 'تطابق المخصوص عددا ونوعا', 'تُحذف دائما', 'تصير مؤنثة إذا كان المخصوص مؤنثا'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'رفع الفاعل والمخصوص',
          kind: 'mcq',
          prompt: 'أفعال المدح والذم make مرفوعًا:',
          options: ['الفاعل والمخصوص معا', 'الفاعل فقط', 'المخصوص فقط', 'المفعول به'],
          correct: 0,
        },
        {
          title: 'نعم',
          kind: 'mcq',
          prompt: '﴿وَلَنِعْمَ دَارُ الْمُتَّقِينَ﴾ — نعم here belongs to أفعال:',
          options: ['المدح', 'الذم', 'التعجب', 'المقاربة'],
          correct: 0,
        },
        {
          title: 'بئس',
          kind: 'mcq',
          prompt: '﴿بِئْسَ الشَّرَابُ﴾ — بئس belongs to أفعال:',
          options: ['الذم', 'المدح', 'الرجاء', 'الشروع'],
          correct: 0,
        },
        {
          title: 'ساء',
          kind: 'mcq',
          prompt: '﴿وَسَاءَتْ مُرْتَفَقًا﴾ — ساء belongs to أفعال:',
          options: ['الذم', 'المدح', 'التحويل', 'المقاربة'],
          correct: 0,
        },
        {
          title: 'حبذا ولا حبذا',
          kind: 'mcq',
          prompt: 'حبذا is for المدح, and لا حبذا is:',
          options: ['للذم', 'للمدح أيضا', 'للرجاء', 'للتعجب'],
          correct: 0,
        },
        {
          title: 'ما يلحقها من التاء',
          kind: 'mcq',
          prompt: 'Being غير متصرفة, أفعال المدح والذم accept only:',
          options: ['تاء التأنيث', 'ياء المخاطبة', 'نون التوكيد', 'واو الجماعة'],
          correct: 0,
        },
        {
          title: 'حسنت مرتفقا',
          kind: 'mcq',
          prompt: '﴿وَحَسُنَتْ مُرْتَفَقًا﴾ — حَسُنَ here, on the وزن فعُل, is ملحق بـ:',
          options: ['أفعال المدح والذم', 'أفعال الشروع', 'أفعال المقاربة', 'أفعال التحويل'],
          correct: 0,
        },
        {
          title: 'تأنيث لتأنيث الفاعل',
          kind: 'mcq',
          prompt: 'نِعِمَتِ الْمَرْأَةُ فَاطِمَةُ — the reason for the تاء here is:',
          options: ['To agree in تأنيث with the فاعل (المرأة)', 'To agree in تأنيث with the مخصوص', 'Just phonetic lightening, with no real reason', 'A common mistake'],
          correct: 0,
        },
        {
          title: 'تأنيث لتأنيث المخصوص',
          kind: 'mcq',
          prompt: 'نِعِمَتْ جَزَاءَ الْمُتَّقِينَ الْجَنَّةُ — the reason for the تاء here is:',
          options: ['To agree in تأنيث with the مخصوص (الجنة)', 'To agree in تأنيث with the فاعل', 'Because the فاعل is تثنية (dual)', 'There is no grammatical reason for it'],
          correct: 0,
        },
        {
          title: 'لام الجنس',
          kind: 'mcq',
          prompt: '﴿نِعْمَ الْعَبْدُ﴾ — the فاعل of نعم here is:',
          options: ['اسم بلام الجنس', 'ضمير مستتر', 'اسم مضاف', 'مصدر مؤول'],
          correct: 0,
        },
        {
          title: 'مضاف إلى ما فيه لام الجنس',
          kind: 'mcq',
          prompt: '﴿نِعْمَ أَجْرُ الْعَامِلِينَ﴾ — the فاعل of نعم here is:',
          options: ['اسم مضاف إلى ما فيه لام الجنس', 'ضمير مستتر', 'اسم نكرة مجرد', 'جملة فعلية'],
          correct: 0,
        },
        {
          title: 'ضمير مستتر وتمييز',
          kind: 'mcq',
          prompt: '﴿وَسَاءَتْ مَصِيرًا﴾ — the فاعل of سَاءَتْ here is:',
          options: ['ضمير مستتر يفسره التمييز (مصيرا)', 'مصيرا نفسه بلا تفسير', 'اسم ظاهر مرفوع', 'لا فاعل له'],
          correct: 0,
        },
        {
          title: 'نعما',
          kind: 'mcq',
          prompt: '﴿فَنِعِمَّا هِيَ﴾ — ما here stands in place of:',
          options: ['فاعل نعم', 'مخصوص نعم', 'تمييز نعم', 'مفعول نعم'],
          correct: 0,
        },
        {
          title: 'حبذا: الحال',
          kind: 'mcq',
          prompt: 'حَبَّذَا رَاكِبًا زَيْدٌ — رَاكِبًا is parsed as:',
          options: ['حال, because it is مشتق', 'تمييز, because it is جامد', 'مخصوص', 'فاعل'],
          correct: 0,
        },
        {
          title: 'حبذا: التمييز',
          kind: 'mcq',
          prompt: 'حَبَّذَا رَجُلًا زَيْدٌ — رَجُلًا is parsed as:',
          options: ['تمييز, because it is جامد', 'حال, because it is مشتق', 'مخصوص', 'خبر'],
          correct: 0,
        },
        {
          title: 'تمييز حبذا بمن',
          kind: 'mcq',
          prompt: 'حَبَّذَا زَيْنَبُ مِنْ مُعَلِّمَةٍ — مِنْ مُعَلِّمَةٍ here is:',
          options: ['تمييز مجرور بمن', 'فاعل حبذا', 'مخصوص حبذا', 'حال منصوب'],
          correct: 0,
        },
        {
          title: 'يا حبذا',
          kind: 'mcq',
          prompt: 'يَا حَبَّذَا مُحَمَّدٌ مِنْ جَارٍ — يَا here enters upon:',
          options: ['حبّ', 'ذا', 'المخصوص', 'التمييز'],
          correct: 0,
        },
        {
          title: 'إفراد ذا وتذكيرها',
          kind: 'mcq',
          prompt: 'حَبَّذَا بِنْتًا فَاطِمَةُ keeps ذَا singular masculine even though فاطمة is feminine. Why?',
          options: ['Because ذا after حبّ always stays الإفراد والتذكير', 'Because فاطمة is an اسم علم that cannot take تأنيث', 'Because التمييز blocks تأنيث', 'This is a mistake in the language'],
          correct: 0,
        },
        {
          title: 'تركيب: مدح أم ذم؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فعل: مدح or ذم?',
          source: 'نعم / حبذا / بئس / ساء',
          words: ['نعم', 'حبذا', 'بئس', 'ساء'],
          labels: ['مدح', 'مدح', 'ذم', 'ذم'],
          distractors: ['تعجب'],
        },
        {
          title: 'تركيب: صور فاعل نعم وبئس',
          kind: 'tarkeeb',
          instruction: 'Classify the form of the فاعل in each example.',
          source: '﴿نعم العبد﴾ / ﴿نعم أجر العاملين﴾ / ﴿وساءت مصيرا﴾',
          words: ['العبد', 'أجر العاملين', 'ضمير في ساءت'],
          labels: ['اسم بلام الجنس', 'مضاف إلى ما فيه لام الجنس', 'ضمير مستتر يفسره تمييز'],
          distractors: ['مصدر مؤول'],
        },
        {
          title: 'تركيب: حال أم تمييز في حبذا؟',
          kind: 'tarkeeb',
          instruction: 'Classify the منصوب after حبذا: حال or تمييز?',
          source: 'حبذا راكباً زيدٌ / حبذا رجلاً زيدٌ',
          words: ['راكباً', 'رجلاً'],
          labels: ['حال', 'تمييز'],
          distractors: ['مخصوص'],
        },
        {
          title: 'تركيب: سبب التاء في التأنيث',
          kind: 'tarkeeb',
          instruction: 'Classify the reason for the تاء التأنيث in each example.',
          source: 'نعمت المرأة فاطمة / نعمت جزاء المتقين الجنه',
          words: ['نعمت (المرأة)', 'نعمت (جزاء)'],
          labels: ['تأنيث الفاعل', 'تأنيث المخصوص'],
          distractors: ['تأنيث التمييز'],
        },
        {
          title: 'تركيب: مذكور أم محذوف؟',
          kind: 'tarkeeb',
          instruction: 'Classify the مخصوص: مذكور or محذوف?',
          source: '﴿بئس الشراب﴾ / ﴿نعم المولى ونعم النصير﴾',
          words: ['الشراب', '(بعد نعم المولى)'],
          labels: ['مذكور', 'محذوف'],
          distractors: ['ممتنع الحذف'],
        },
        {
          title: 'تركيب: أحكام حبذا',
          kind: 'tarkeeb',
          instruction: "Classify each of حبذا's rulings.",
          source: 'يا حبذا محمد من جار / حبذا زينب من معلمة / حبذا بنتاً فاطمة',
          words: ['يا', 'من معلمة', 'بنتاً'],
          labels: ['دخول يا على حبّ', 'تمييز بحرف الجر من', 'ثبات الإفراد والتذكير في ذا'],
          distractors: ['حذف المخصوص'],
        },
      ],
    },

    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'صيغ التعجب',
      subtitle: 'Forms of Wonder — ما أفعله وأفعل به, the قياسي forms, and what\'s سماعي among them',
      concepts: [
        {
          heading: 'صيغ التعجب: ضرباها والصيغ القياسية الثلاث',
          body: `<bdi>صِيَغُ التَّعَجُّب</bdi> — the third قسم of السماعي — are forms established to indicate wonder (<bdi>التَّعَجُّب</bdi>), and split into two أضرب: (1) <bdi>قِيَاسِيّ</bdi> (2) <bdi>سَمَاعِيّ</bdi>. The قياسي forms are three: (1) <bdi>مَا أَفْعَلَهُ</bdi>, as in <bdi>﴿فَمَا أَصْبَرَهُمْ عَلَى النَّارِ﴾</bdi> (2) <bdi>أَفْعِلْ بِهِ</bdi>, as in <bdi>﴿أَسْمِعْ بِهِمْ وَأَبْصِرْ﴾</bdi> (3) the <bdi>فَعُلَ</bdi> pattern, original or converted, as in <bdi>﴿كَبُرَتْ كَلِمَةً تَخْرُجُ مِنْ أَفْوَاهِهِمْ﴾</bdi>.`,
          sample: `صيغ التعجب — قياسي وسماعي<br>ما أفعله — ﴿فما أصبرهم على النار﴾<br>أفعل به — ﴿أسمع بهم وأبصر﴾<br>فعُل — ﴿كبرت كلمة تخرج من أفواههم﴾`,
          exercise: {
            prompt: `﴿فَمَا أَصْبَرَهُمْ عَلَى النَّارِ﴾ uses which of the three قياسي forms of التعجب?`,
            kind: 'mcq',
            options: ['ما أفعله', 'أفعل به', 'فعُل', 'لا شيء منها'],
            correct: 0,
          },
        },
        {
          heading: 'الخلاف في ما، واشتقاق أفعِل به',
          body: `Grammarians differ on <bdi>مَا</bdi> in <bdi>مَا أَفْعَلَهُ</bdi>: (1) it is <bdi>اسْتِفْهَام</bdi> (2) it is a <bdi>نَكِرَةٌ مَوْصُوفَة</bdi> meaning <bdi>شَيْءٌ عَظِيم</bdi> ("something tremendous [made him patient]..."). The form <bdi>أَفْعِلْ بِهِ</bdi> is itself derived: its origin is the <bdi>مَاضِي أَفْعَلَ</bdi>, changed into the <bdi>أَمْر</bdi> form; a <bdi>بَاء</bdi> is then added to the فاعل, because attaching a فعل أمر directly to an <bdi>اسْمٌ ظَاهِر</bdi> فاعل would be unseemly (<bdi>قَبِيح</bdi>).`,
          sample: `ما استفهامية أو نكرة موصوفة بمعنى شيء عظيم<br>أفعل به — أصله ماضي أفعَلَ، حُوّل إلى الأمر، وزيدت الباء على الفاعل لقبح اتصال الأمر باسم ظاهر مباشرة`,
          exercise: {
            prompt: `Why is a زائدة باء added to the فاعل in أَفْعِلْ بِهِ, rather than the فاعل standing bare?`,
            kind: 'mcq',
            options: ['Because attaching a فعل أمر directly to an اسم ظاهر فاعل is قبيح', "Because الباء is أصلية in the فعل's structure", 'Because the فاعل here is actually a مفعول به', "There's no grammatical reason — it's a random addition"],
            correct: 0,
          },
        },
        {
          heading: 'تشرب معنى التعجب، والباء مع فعُل',
          body: `When a فعل's فاعل carries a زائدة باء like the one in أفعل به, the meaning of التعجب can seep into (<bdi>يَتَشَرَّب</bdi>) أفعال outside the three forms too, as in <bdi>﴿وَكَفَىٰ بِنَا حَاسِبِينَ﴾</bdi> and <bdi>بِحَسْبِكَ زَيْدٌ</bdi>. The same باء may also enter the فاعل of the فعُل pattern of wonder, as in <bdi>حَسُنَ بِزَيْدٍ</bdi>.`,
          sample: `تشرب معنى التعجب — ﴿وكفى بنا حاسبين﴾، بحسبك زيد<br>الباء مع فعُل — حسُن بزيد`,
          exercise: {
            prompt: `﴿وَكَفَىٰ بِنَا حَاسِبِينَ﴾ is not one of the three قياسي forms of التعجب, yet carries a sense of it. Why?`,
            kind: 'mcq',
            options: ['Because the meaning of التعجب seeps into any فعل whose فاعل carries a زائدة باء', 'Because it is a فعل ناقص operating like كان', 'Because it is one of أفعال المدح والذم', 'Because it converted to the فعُل pattern'],
            correct: 0,
          },
        },
        {
          heading: 'شروط صياغة التعجب القياسي',
          body: `صيغ التعجب القياسي — ما أفعله and أفعل به — can only be formed from the <bdi>فِعْلٌ ثُلَاثِيٌّ مُجَرَّد</bdi> (an unaugmented three-letter فعل). Two further restrictions govern their shape: (1) <bdi>الْإِعْلَال</bdi> of the <bdi>عَيْن</bdi> is not permitted — <bdi>مَا أَطْوَلَهُ وَأَطْوِلْ بِهِ</bdi>, not <bdi>مَا أَطَالَهُ وَلَا أَطِلْ بِهِ</bdi> (2) <bdi>الْإِدْغَام</bdi> does not occur in أفعل به — <bdi>أَبْرِرْ بِهِ</bdi>, unlike ما أفعله, which does allow it: <bdi>مَا أَبَرَّهُ</bdi>.`,
          sample: `يُشتق التعجب القياسي من الثلاثي المجرد فقط<br>منع إعلال العين — ما أطوله وأطول به، لا ما أطاله<br>منع الإدغام في أفعل به — أبرِرْ به (لا يُدغم)، بخلاف ما أفعله — ما أبرّه (يُدغم)`,
          exercise: {
            prompt: `ما أطوله avoids إعلال of its عين — the form is أَطْوَلَ, not أَطَالَ. What does this show about the two قياسي forms of التعجب?`,
            kind: 'mcq',
            options: ["That both block إعلال of the عين, whatever the فعل's original form", 'That both require إعلال always', 'That إعلال is permitted in one but not the other', 'إعلال has nothing to do with صيغ التعجب'],
            correct: 0,
          },
        },
        {
          heading: 'صيغ التعجب السماعية',
          body: `Alongside the قياسي forms, a handful of expressions have been transmitted (<bdi>سُمِعَ</bdi>) as صيغ سماعية of التعجب, without following the قياسي pattern: (1) <bdi>سُبْحَانَ اللَّهِ</bdi>, as in <bdi>﴿قَالَ سُبْحَانَكَ مَا يَكُونُ لِي أَنْ أَقُولَ مَا لَيْسَ لِي بِحَقٍّ﴾</bdi> (2) <bdi>الِاسْتِفْهَام</bdi>, as in <bdi>﴿كَيْفَ تَكْفُرُونَ بِاللَّهِ وَكُنْتُمْ أَمْوَاتًا فَأَحْيَاكُمْ﴾</bdi> (3) <bdi>النِّدَاء</bdi>, as in <bdi>﴿يَا بُشْرَىٰ هَٰذَا غُلَامٌ﴾</bdi>.`,
          sample: `سبحان الله — ﴿قال سبحانك ما يكون لي أن أقول ما ليس لي بحق﴾<br>الاستفهام — ﴿كيف تكفرون بالله وكنتم أمواتا فأحياكم﴾<br>النداء — ﴿يا بشرى هذا غلام﴾`,
          exercise: {
            prompt: `﴿يَا بُشْرَىٰ هَٰذَا غُلَامٌ﴾ expresses wonder through which grammatical device, used here as a سماعي form of التعجب?`,
            kind: 'mcq',
            options: ['النداء', 'الاستفهام', 'سبحان الله', 'ما أفعله'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'صيغ التعجب split into:',
          options: ['قياسي وسماعي', 'لازم ومتعد', 'تام وناقص', 'مؤكد وغير مؤكد'],
          correct: 0,
        },
        {
          q: 'The three قياسي forms of التعجب are:',
          options: ['ما أفعله، أفعل به، فعُل', 'نعم، بئس، حبذا', 'كاد، عسى، أوشك', 'كان، صار، ظل'],
          correct: 0,
        },
        {
          q: 'One of the two views on "ما" in ما أفعله is that it is:',
          options: ['نكرة موصوفة بمعنى شيء عظيم', 'حرف جر زائد', 'اسم موصول بمعنى الذي', 'ضمير مستتر'],
          correct: 0,
        },
        {
          q: 'The origin of أَفْعِلْ بِهِ is:',
          options: ['ماضي أفعَلَ حُوّل إلى الأمر وزيدت الباء', 'مضارع أفعَلَ مجزوما', 'مصدر أفعَلَ', 'اسم فاعل من أفعَلَ'],
          correct: 0,
        },
        {
          q: 'صيغ التعجب القياسي can only be formed from:',
          options: ['الفعل الثلاثي المجرد فقط', 'أي فعل مهما كانت أحرفه', 'الفعل الرباعي فقط', 'الفعل المزيد فقط'],
          correct: 0,
        },
        {
          q: 'Among the سماعي forms of التعجب are:',
          options: ['سبحان الله، الاستفهام، النداء', 'ما أفعله وأفعل به', 'فعُل الأصلي والمحوّل', 'نعم وبئس'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'ضربا صيغ التعجب',
          kind: 'mcq',
          prompt: 'صيغ التعجب split into two أضرب:',
          options: ['قياسي وسماعي', 'مطرد وشاذ', 'ماضٍ ومضارع', 'مثبت ومنفي'],
          correct: 0,
        },
        {
          title: 'ما أفعله',
          kind: 'mcq',
          prompt: 'Which صيغة of التعجب is ﴿فَمَا أَصْبَرَهُمْ عَلَى النَّارِ﴾?',
          options: ['ما أفعله', 'أفعل به', 'فعُل', 'سماعية'],
          correct: 0,
        },
        {
          title: 'أفعل به',
          kind: 'mcq',
          prompt: 'Which صيغة of التعجب is ﴿أَسْمِعْ بِهِمْ وَأَبْصِرْ﴾?',
          options: ['أفعل به', 'ما أفعله', 'فعُل', 'النداء'],
          correct: 0,
        },
        {
          title: 'فعُل',
          kind: 'mcq',
          prompt: 'Which صيغة of التعجب is ﴿كَبُرَتْ كَلِمَةً تَخْرُجُ مِنْ أَفْوَاهِهِمْ﴾?',
          options: ['فعُل (وزن التعجب)', 'ما أفعله', 'أفعل به', 'سبحان الله'],
          correct: 0,
        },
        {
          title: 'ما استفهامية',
          kind: 'mcq',
          prompt: 'One of the two views on "ما" in ما أفعله is that it is:',
          options: ['استفهامية', 'حرف نفي', 'حرف جر', 'اسم شرط'],
          correct: 0,
        },
        {
          title: 'اشتقاق أفعل به',
          kind: 'mcq',
          prompt: 'أَفْعِلْ بِهِ is derived from:',
          options: ['ماضي أفعَلَ المحوّل إلى الأمر', 'مضارع أفعَلَ', 'اسم الفاعل', 'اسم المفعول'],
          correct: 0,
        },
        {
          title: 'سبب زيادة الباء',
          kind: 'mcq',
          prompt: 'A زائدة باء was added to the فاعل of أَفْعِلْ بِهِ because:',
          options: ['Attaching a فعل أمر directly to an اسم ظاهر فاعل is قبيح', 'The فعل is لازم, so it needed a حرف جر', 'The فاعل here is originally a مفعول به', 'There is no grammatical reason for it'],
          correct: 0,
        },
        {
          title: 'كفى بنا حاسبين',
          kind: 'mcq',
          prompt: '﴿وَكَفَىٰ بِنَا حَاسِبِينَ﴾ is an example of:',
          options: ['تشرب معنى التعجب في فعل خارج الصيغ الثلاث', 'أفعل به مباشرة', 'ما أفعله', 'فعُل الأصلي'],
          correct: 0,
        },
        {
          title: 'حسُن بزيد',
          kind: 'mcq',
          prompt: 'حَسُنَ بِزَيْدٍ — the باء here entered on the فاعل of the وزن:',
          options: ['فعُل', 'أفعل', 'ما أفعل', 'التفضيل'],
          correct: 0,
        },
        {
          title: 'الاشتقاق من الثلاثي',
          kind: 'mcq',
          prompt: 'صيغ التعجب القياسي can only be formed from:',
          options: ['الفعل الثلاثي المجرد فقط', 'أي فعل ثلاثي أو رباعي', 'الفعل المزيد بحرف فقط', 'لا يُشترط عدد أحرف معين'],
          correct: 0,
        },
        {
          title: 'منع إعلال العين',
          kind: 'mcq',
          prompt: 'مَا أَطْوَلَهُ, not مَا أَطَالَهُ, proves that صيغ التعجب:',
          options: ['تمنع إعلال العين', 'توجب إعلال العين', 'لا علاقة لها بالإعلال', 'تُعل العين في ما أفعله دون أفعل به'],
          correct: 0,
        },
        {
          title: 'منع الإدغام في أفعل به',
          kind: 'mcq',
          prompt: 'أَبْرِرْ بِهِ (without إدغام), unlike مَا أَبَرَّهُ (with إدغام), proves that:',
          options: ['أفعل به blocks الإدغام, unlike ما أفعله', 'Both forms block الإدغام', 'Both forms require الإدغام', 'الإدغام never occurs in صيغ التعجب'],
          correct: 0,
        },
        {
          title: 'سبحان الله',
          kind: 'mcq',
          prompt: '﴿قَالَ سُبْحَانَكَ مَا يَكُونُ لِي أَنْ أَقُولَ مَا لَيْسَ لِي بِحَقٍّ﴾ — سُبْحَانَكَ here is a صيغة تعجب that is:',
          options: ['سماعية', 'قياسية على وزن ما أفعله', 'قياسية على وزن أفعل به', 'ملحقة بفعُل'],
          correct: 0,
        },
        {
          title: 'الاستفهام تعجبا',
          kind: 'mcq',
          prompt: '﴿كَيْفَ تَكْفُرُونَ بِاللَّهِ وَكُنْتُمْ أَمْوَاتًا فَأَحْيَاكُمْ﴾ expresses التعجب by way of:',
          options: ['الاستفهام', 'النداء', 'سبحان الله', 'فعُل'],
          correct: 0,
        },
        {
          title: 'النداء تعجبا',
          kind: 'mcq',
          prompt: '﴿يَا بُشْرَىٰ هَٰذَا غُلَامٌ﴾ expresses التعجب by way of:',
          options: ['النداء', 'الاستفهام', 'سبحان الله', 'أفعل به'],
          correct: 0,
        },
        {
          title: 'صيغ سماعية أم قياسية',
          kind: 'mcq',
          prompt: 'سبحان الله, الاستفهام, and النداء, as forms of التعجب, are considered:',
          options: ['سماعية، لا تتبع قاعدة مطردة', 'قياسية مثل ما أفعله', 'ملحقة بأفعال المدح والذم', 'من أفعال الشروع'],
          correct: 0,
        },
        {
          title: 'عدد الصيغ القياسية',
          kind: 'mcq',
          prompt: 'The number of قياسي forms of التعجب is:',
          options: ['ثلاثة', 'اثنان', 'أربعة', 'خمسة'],
          correct: 0,
        },
        {
          title: 'الرأي الآخر في ما',
          kind: 'mcq',
          prompt: 'The other view on "ما" in ما أفعله (besides استفهام) is that it is:',
          options: ['نكرة موصوفة بمعنى شيء عظيم', 'حرف عطف', 'اسم إشارة', 'ضمير متصل'],
          correct: 0,
        },
        {
          title: 'تركيب: الصيغ القياسية الثلاث',
          kind: 'tarkeeb',
          instruction: 'Classify each example by its قياسي صيغة.',
          source: '﴿فما أصبرهم على النار﴾ / ﴿أسمع بهم وأبصر﴾ / ﴿كبرت كلمة تخرج من أفواههم﴾',
          words: ['أصبرهم', 'أسمع', 'كبرت'],
          labels: ['ما أفعله', 'أفعل به', 'فعُل'],
          distractors: ['سماعي'],
        },
        {
          title: 'تركيب: قياسي أم سماعي؟',
          kind: 'tarkeeb',
          instruction: 'Classify each صيغة: قياسي or سماعي?',
          source: 'ما أفعله / سبحان الله / أفعل به / الاستفهام',
          words: ['ما أفعله', 'سبحان الله', 'أفعل به', 'الاستفهام'],
          labels: ['قياسي', 'سماعي', 'قياسي', 'سماعي'],
          distractors: ['ملحق'],
        },
        {
          title: 'تركيب: صيغ التعجب السماعية',
          kind: 'tarkeeb',
          instruction: 'Identify the device of التعجب in each example.',
          source: '﴿قال سبحانك ما يكون لي...﴾ / ﴿كيف تكفرون بالله...﴾ / ﴿يا بشرى هذا غلام﴾',
          words: ['سبحانك', 'كيف', 'يا بشرى'],
          labels: ['سبحان الله', 'الاستفهام', 'النداء'],
          distractors: ['فعُل'],
        },
        {
          title: 'تركيب: أحكام الاشتقاق',
          kind: 'tarkeeb',
          instruction: 'Classify: is this restriction true or false for صيغ التعجب القياسي?',
          source: 'يُشتق من الثلاثي المجرد / يُشتق من أي فعل مهما كثرت أحرفه',
          words: ['الثلاثي المجرد', 'أي فعل'],
          labels: ['صحيح', 'خاطئ'],
          distractors: ['مختلف فيه'],
        },
        {
          title: 'تركيب: الإعلال والإدغام',
          kind: 'tarkeeb',
          instruction: 'Classify: does this occur in صيغ التعجب, or is it forbidden?',
          source: 'إعلال العين (ما أطاله) / الإدغام في ما أفعله (ما أبرّه)',
          words: ['إعلال العين', 'الإدغام في ما أفعله'],
          labels: ['يمتنع', 'يقع'],
          distractors: ['واجب دائما'],
        },
        {
          title: 'تركيب: تشرب معنى التعجب',
          kind: 'tarkeeb',
          instruction: 'Classify: is this فعل directly one of the three صيغ, or from تشرب?',
          source: '﴿فما أصبرهم على النار﴾ / ﴿وكفى بنا حاسبين﴾',
          words: ['أصبرهم', 'كفى'],
          labels: ['من الصيغ الثلاث مباشرة', 'من التشرب'],
          distractors: ['سماعي محض'],
        },
      ],
    },
  ],
};
