// Module 06 — أفعال التحويل والتعليق والإلغاء
//
// Source: app-lessons/026-afal-al-tahweel.md (l1) and
// app-lessons/027-taleeq-and-ilgha.md (l2-l3). Authored 2026-08-12 as new
// authorship, matching Module 01's process. Authored out of order per
// explicit user instruction: Modules 04 and 05 (the قياسي لزوم/تعدي family
// and أفعال القلوب, app-lessons/019-025) are still only proposals in
// COURSE-MAP.md, not yet written. This module keeps the id '06' from the
// course map's forward plan even though it currently sits at MODULES[3]
// (array position, not id) in content/annahw.js — when 04 and 05 are
// authored later they slot in before this one in that array, and this
// module moves later in unlock order without any change to its own file.
//
// أفعال التحويل complete the two-object verb family that Module 05 will
// introduce via أفعال القلوب (صيّر وأخواتها take two objects that were
// originally مبتدأ وخبر, exactly like عَلِمَ and ظَنَّ) — l1 covers them on
// their own, without presuming the learner has already met أفعال القلوب in
// this app, since that module doesn't exist yet. l2-l3 then close out the
// أفعال القلوب topic proper: the three-object family, what a جملة sadding
// مسد the two مفعولين does to the فعل's عمل (التعليق), every trigger that
// forces it, and الإلغاء, which cancels that عمل outright.
//
// L2's بنية bank تركيب count is 4, not the usual 6 — app-lessons/027's own
// worked examples for the اسم مؤول/جملة/الفعل الشبيه material (يريهم,
// اعلموا أن الله, يبلوكم, سلهم) run out at four genuinely parseable
// sentences; the شهد example is explicitly flagged in the source itself as
// illustrating its point "less cleanly" and was left out of the bank rather
// than forced in. L1 and L3 each hit six.
export default {
  id: '06',
  title: 'التحويل والتعليق',
  heading: 'العامل وغير العامل',
  subheading: 'الفعل',
  blurb: 'أفعال التحويل completing the two-object verb family, then التعليق and الإلغاء that decide whether a فعل قلب governs the جملة after it.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'أفعال التحويل',
      subtitle: 'Verbs of Transformation — صيّر، ردّ، ترك، تخذ/اتخذ، وهب، and the two faces of جعل',
      concepts: [
        {
          heading: 'تعريف أفعال التحويل',
          lines: [
            { html: `Some verbs carry the meaning of transformation: changing one thing from one state into another. These verbs take two objects that were originally a <bdi>مبتدأ</bdi> and a <bdi>خبر</bdi>, which is why they are often treated as a branch of the family that includes <bdi>ظَنَّ</bdi> and <bdi>عَلِمَ</bdi> — sharing the same two-object structure, even though the sense here is transformation rather than mental perception.`, list: false },
            { box: { title: 'Core Text', lines: [`أَفْعَالُ التَّحْوِيلِ: مَا تَكُونُ بِمَعْنَى صَيَّرَ، أَيْ حَوَّلَ الشَّيْءَ مِنْ حَالٍ إِلَى حَالٍ`] } },
            { html: `The first مفعول is the thing being transformed; the second names the new state it is put into. The change may be an actual one, or only a change in judgement, role, or status.`, list: false },
          ],
          exercise: {
            prompt: `أفعال التحويل take two objects that were originally a مبتدأ and خبر. What does the second object represent?`,
            kind: 'mcq',
            options: [`The new state the first object is put into`, `The thing being transformed`, `The فاعل of the sentence`, `The حال of the فاعل`],
            correct: 0,
          },
        },
        {
          heading: 'صيّر: التحويل الصريح',
          lines: [
            { html: `<bdi>صَيَّرَ</bdi> is the base transformation verb, from <bdi>بَاب تَفْعِيل</bdi>. It changes its first object into the condition named by its second object.`, list: false },
            { box: { title: 'Core Text', lines: [`صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا وَزَادَ ضِيقَ الْحَيَاةِ ضِيقًا`] } },
            { table: { title: 'صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا', headers: ['Word', 'Role'], rows: [
              [`صَيَّرَ`, `فعل تحويل`],
              [`عَذْبَ الشَّرَابِ`, `مفعول به أول`],
              [`مُرًّا`, `مفعول به ثاني`],
            ] } },
            { html: `"It turned the sweetness of drink into bitterness, and it made the constraints of life tighter still." This line is a poetic <bdi>شَاهِد</bdi>; the فاعل of صيّر is a هو referring back to what the poem describes.`, list: false },
          ],
          exercise: {
            prompt: `In صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا, عَذْبَ الشَّرَابِ is turned into مُرًّا. What roles do the two carry?`,
            kind: 'mcq',
            options: [`عَذْبَ الشَّرَابِ = مفعول به أول, مُرًّا = مفعول به ثاني`, `مُرًّا = مفعول به أول, عَذْبَ الشَّرَابِ = مفعول به ثاني`, `عَذْبَ الشَّرَابِ = فاعل, مُرًّا = مفعول به`, `عَذْبَ الشَّرَابِ = مبتدأ, مُرًّا = خبر`],
            correct: 0,
          },
        },
        {
          heading: 'ردّ: العودة إلى حال سابقة',
          lines: [
            { html: `<bdi>رَدَّ</bdi> means to change back: to return something to a state it was in before. Some short grammar texts simply gloss ردّ as بمعنى صيّر, but the two are not identical — ردّ carries a connotation صيّر lacks: that the second state is one the object already held.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿وَدَّ كَثِيرٌ مِّنْ أَهْلِ الْكِتَابِ لَوْ يَرُدُّونَكُمْ مِنْ بَعْدِ إِيمَانِكُمْ كُفَّارًا﴾`] } },
            { html: `"Many of the People of the Book wished they could return you, after your belief, to disbelief." Most of those addressed had been in disbelief before accepting Islam — ردّ here says: take them back to what they were. Had the verse said <bdi>لَوْ يُصَيِّرُونَكُمْ</bdi> or <bdi>لَوْ يَجْعَلُونَكُمْ</bdi>, that sense of returning to a prior state would be absent.`, list: false },
          ],
          exercise: {
            prompt: `﴿وَدَّ كَثِيرٌ مِّنْ أَهْلِ الْكِتَابِ لَوْ يَرُدُّونَكُمْ مِنْ بَعْدِ إِيمَانِكُمْ كُفَّارًا﴾ uses ردّ rather than صيّر. What connotation does ردّ add that صيّر lacks?`,
            kind: 'mcq',
            options: [`That the new state, كفر, is one the addressees already held before their إيمان`, `That the change described never actually happens`, `That the change is only a change in judgement, never a real one`, `That the فاعل of the verb is unknown`],
            correct: 0,
          },
        },
        {
          heading: 'ترك: الترك على حال بعد تأثير',
          lines: [
            { html: `<bdi>تَرَكَ</bdi>, when it functions as a فعل تحويل, means to leave something in a particular condition — the implication is that something acted on the first object, changed it, and departed, leaving it in the new state the second object names.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿فَأَصَابَهُ وَابِلٌ فَتَرَكَهُ صَلْدًا﴾`] } },
            { table: { title: 'فَتَرَكَهُ صَلْدًا', headers: ['Word', 'Role'], rows: [
              [`فَتَرَكَهُ`, `فعل ومفعوله الأول`],
              [`صَلْدًا`, `مفعول به ثاني`],
            ] } },
            { html: `"Heavy rain struck it and left it completely barren." The image is of soil sitting on a boulder: greenery grows while the soil stays, but the heavy rain washes the soil off and leaves the rock exposed. <bdi>صَلْدًا</bdi> means bare, with nothing left on top of it.`, list: false },
            { table: { title: 'العلاقة بالحال الجديدة', headers: ['Verb', 'Relation to the new state'], rows: [
              [`صيّر`, `changes something into a state`],
              [`ردّ`, `takes it back to a state it held before`],
              [`ترك`, `leaves it in a state after something has acted on it`],
            ] } },
          ],
          exercise: {
            prompt: `صيّر, ردّ, and ترك all mark a change of state but frame the relation to the new state differently. Which best describes ترك?`,
            kind: 'mcq',
            options: [`It leaves something in a state after something else has acted on it and departed`, `It changes something into a new state directly, with no prior involvement implied`, `It takes something back to a state it held before`, `It merely raises the possibility that a change occurred`],
            correct: 0,
          },
        },
        {
          heading: 'تخذ واتّخذ، ووهب: اتخاذ الشيء شيئا آخر',
          lines: [
            { html: `<bdi>تَخِذَ</bdi> and <bdi>اتَّخَذَ</bdi> share the meaning "to take one thing as another."`, list: false },
            { box: { title: 'Core Text', lines: [`﴿وَاتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا﴾`] } },
            { table: { title: 'وَاتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا', headers: ['Word', 'Role'], rows: [
              [`اتَّخَذَ`, `فعل تحويل`],
              [`اللهُ`, `فاعل`],
              [`إِبْرَاهِيمَ`, `مفعول به أول`],
              [`خَلِيلًا`, `مفعول به ثاني`],
            ] } },
            { html: `"And Allah took Ibrahim as a close friend." <bdi>وَهَبَ</bdi> and <bdi>جَعَلَ</bdi> both carry this same transformation meaning when they take two objects.`, list: false },
            { box: { title: 'Example', lines: [`وَهَبَنِي اللهُ فِدَاءً لِلْعِلْمِ`] } },
            { html: `"May Allah make me a ransom for knowledge, one who gives himself up for it." لَفْظُ الجَلالَةِ is الفاعل; the attached ـني is المفعول به الأول; فِدَاءً is المفعول به الثاني.`, list: false },
          ],
          exercise: {
            prompt: `In وَهَبَنِي اللهُ فِدَاءً لِلْعِلْمِ, who is الفاعل, and what is المفعول به الأول?`,
            kind: 'mcq',
            options: [`لَفْظُ الجَلالَةِ is الفاعل; the attached ـني is المفعول به الأول`, `لَفْظُ الجَلالَةِ is المفعول به الأول; the attached ـني is الفاعل`, `فِدَاءً is الفاعل`, `لِلْعِلْمِ is المفعول به الأول`],
            correct: 0,
          },
        },
        {
          heading: 'جعل: بين التحويل والإيجاد، وضابط العدّ',
          lines: [
            { html: `<bdi>جَعَلَ</bdi> needs particular care: it carries two distinct uses, and what decides between them is how many مفاعيل follow it.`, list: false },
            { box: { title: 'Careful', lines: [`فعل تحويل: مفعولان، بمعنى تحويل الشيء إلى الآخر`, `بمعنى خَلَقَ أَوْ أَوْجَدَ: مفعول واحد، بمعنى الإيجاد من العدم`] } },
            { box: { title: 'Core Text', lines: [`﴿فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا﴾`] } },
            { html: `"So We made it scattered dust." The mountains are reduced to dust, with nothing of their former state remaining — two مفاعيل appear (the attached pronoun, and هَبَاءً مَنْثُورًا), so this is جَعَلَ as فعل تحويل.`, list: false },
            { box: { title: 'Example', lines: [`﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾`] } },
            { html: `Here only one مفعول به appears — hearing, sight, and hearts, joined by و — with no second مفعول naming a state. This is جَعَلَ بمعنى خَلَقَ أَوْ أَوْجَدَ, not the تحويل sense; some مفسّرون explicitly gloss this جَعَلَ as أَوْجَدَ, to signal that the two-object تحويل reading is not what is meant.`, list: false },
            { html: `The same test applies to the whole family when they appear with only one مفعول: <bdi>تَرَكَ</bdi> in <bdi>إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللهِ</bdi> means to abandon, بمعنى هَجَرَ, not to leave in a transformed state; <bdi>رَدَّ</bdi> in <bdi>ثُمَّ يُرَدُّ إِلَى رَبِّهِ</bdi> means to be brought back, بمعنى يُصَارُ, not to change something into a state.`, list: false },
            { box: { title: 'Rule', lines: [`يُعَدُّ عَدَدُ المَفَاعِيلِ: مَفْعُولٌ وَاحِدٌ لِلْمَعْنَى الأَصْلِيِّ، وَمَفْعُولَانِ لِمَعْنَى التَّحْوِيلِ`] } },
          ],
          exercise: {
            prompt: `﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾ names hearing, sight, and hearts as a single مفعول به, with no second مفعول naming a new state. Which sense of جَعَلَ is this?`,
            kind: 'mcq',
            options: [`بمعنى خَلَقَ أَوْ أَوْجَدَ — one object, no تحويل`, `فعل تحويل — two objects`, `فعل قلب من أفعال الظن`, `فعل ناقص من أخوات كان`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `أفعال التحويل are said to carry which core meaning?`, options: [`بمعنى صيّر: تحويل الشيء من حال إلى حال`, `بمعنى ظنّ: توقع وقوع الشيء`, `بمعنى كان: اقتران الحدث بالزمان الماضي`, `بمعنى ليس: نفي الخبر عن الاسم`], correct: 0 },
        { q: `In صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا, مُرًّا carries which role?`, options: [`مفعول به ثاني`, `مفعول به أول`, `فاعل`, `خبر`], correct: 0 },
        { q: `﴿وَدَّ كَثِيرٌ مِّنْ أَهْلِ الْكِتَابِ لَوْ يَرُدُّونَكُمْ مِنْ بَعْدِ إِيمَانِكُمْ كُفَّارًا﴾ chooses ردّ rather than صيّر. Why?`, options: [`Because كفرا was the addressees' own state before إيمان`, `Because ردّ cannot express تحويل at all`, `Because ردّ is فعل لازم`, `Because ردّ needs only one مفعول`], correct: 0 },
        { q: `In ﴿فَأَصَابَهُ وَابِلٌ فَتَرَكَهُ صَلْدًا﴾, what does صَلْدًا describe?`, options: [`The rock left bare once the rain washes the soil away`, `The rain itself`, `The soil before the rain fell`, `The person struck by the rain`], correct: 0 },
        { q: `﴿وَاتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا﴾: what role does خَلِيلًا carry?`, options: [`مفعول به ثاني`, `مفعول به أول`, `فاعل`, `خبر`], correct: 0 },
        { q: `جَعَلَ carries two distinct uses. What settles which one applies in a given جملة?`, options: [`Whether one or two مفاعيل follow it`, `Whether the فعل is مبني للمعلوم or المجهول`, `Whether it is preceded by a حرف جر`, `Whether the فاعل is ظاهر or مضمر`], correct: 0 },
      ],
      bank: [
        { title: `تعريف أفعال التحويل`, kind: 'mcq', prompt: `Which of the following correctly captures the core meaning of أفعال التحويل?`, options: [`بمعنى صيّر: تحويل الشيء من حال إلى حال`, `بمعنى ظنّ: توقع وقوع الشيء`, `بمعنى كان: اقتران الحدث بالزمان الماضي`, `بمعنى ليس: نفي الخبر عن الاسم`], correct: 0 },
        { title: `أصل مشترك مع أفعال القلوب`, kind: 'mcq', prompt: `أفعال التحويل are often treated as a branch of the family that includes ظَنَّ and عَلِمَ. What do the two families share?`, options: [`Both take two objects that were originally a مبتدأ and خبر`, `Both are مبني على الفتح دائما`, `Both require the second object to be محذوف`, `Neither can ever take a single object`], correct: 0 },
        { title: `صيّر: تحديد المفعولين`, kind: 'mcq', prompt: `In صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا, which of the two مفعولين names the new state the first is put into?`, options: [`مُرًّا`, `عَذْبَ الشَّرَابِ`, `Both together`, `Neither — صيّر takes only one مفعول`], correct: 0 },
        { title: `صيّر: بابه`, kind: 'mcq', prompt: `صَيَّرَ, the base transformation verb, comes from which باب of الفعل المزيد؟`, options: [`باب تفعيل`, `الفعل المجرد`, `باب المفاعلة`, `باب الإفعال`], correct: 0 },
        { title: `ردّ: لماذا لا صيّر`, kind: 'mcq', prompt: `﴿وَدَّ كَثِيرٌ مِّنْ أَهْلِ الْكِتَابِ لَوْ يَرُدُّونَكُمْ مِنْ بَعْدِ إِيمَانِكُمْ كُفَّارًا﴾ uses ردّ rather than صيّر. What connotation does ردّ add?`, options: [`That the new state, كفر, is one the addressees already held before their إيمان`, `That the change is only a change in judgement, not a real one`, `That the change never actually occurs`, `That the فاعل is unknown`], correct: 0 },
        { title: `ردّ: تعريفه كفعل تحويل`, kind: 'mcq', prompt: `Which of the following best defines ردّ when it functions as فعل تحويل؟`, options: [`To return something to a state it held before`, `To leave something in a state after acting on it`, `To create something from nothing`, `To take one thing as another`], correct: 0 },
        { title: `ترك: صورة المطر والصخرة`, kind: 'mcq', prompt: `﴿فَأَصَابَهُ وَابِلٌ فَتَرَكَهُ صَلْدًا﴾ pictures soil sitting on a boulder. What does صَلْدًا describe once the rain washes the soil away?`, options: [`The rock left bare, with nothing left on top of it`, `The soil after it is soaked`, `The rain itself`, `The plant that used to grow there`], correct: 0 },
        { title: `ترك vs صيّر vs ردّ`, kind: 'mcq', prompt: `صيّر, ردّ, and ترك all mark a change of state but frame the relation to the new state differently. Which pairing is correct?`, options: [`صيّر changes something into a state; ردّ takes it back to a former state; ترك leaves it in a state after something acted on it`, `صيّر leaves something in a state; ردّ changes it into a state; ترك takes it back to a former state`, `All three mean exactly the same thing`, `ترك and ردّ both mean "to create"`], correct: 0 },
        { title: `فتركه صلدا: الإعراب`, kind: 'mcq', prompt: `In فَتَرَكَهُ صَلْدًا, what are the grammatical roles of تَرَكَهُ and صَلْدًا?`, options: [`تَرَكَهُ = فعل مع مفعوله الأول (الهاء), صَلْدًا = مفعول به ثاني`, `تَرَكَهُ = فعل مع فاعله, صَلْدًا = حال`, `تَرَكَهُ = مبتدأ, صَلْدًا = خبر`, `تَرَكَهُ = فعل لازم, صَلْدًا = تمييز`], correct: 0 },
        { title: `اتخذ: المعنى المشترك`, kind: 'mcq', prompt: `تَخِذَ and اتَّخَذَ share which core meaning?`, options: [`To take one thing as another`, `To leave something in a state`, `To return something to a former state`, `To ask about a state`], correct: 0 },
        { title: `واتخذ الله إبراهيم خليلا: ترتيب المفعولين`, kind: 'mcq', prompt: `﴿وَاتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا﴾ names two مفعولين besides الفاعل. What are they, in order?`, options: [`إِبْرَاهِيمَ (مفعول به أول), خَلِيلًا (مفعول به ثاني)`, `خَلِيلًا (مفعول به أول), إِبْرَاهِيمَ (مفعول به ثاني)`, `إِبْرَاهِيمَ (فاعل), خَلِيلًا (مفعول به)`, `لَفْظُ الجَلالَةِ (مفعول به أول), إِبْرَاهِيمَ (مفعول به ثاني)`], correct: 0 },
        { title: `وهبني الله فداء للعلم`, kind: 'mcq', prompt: `In وَهَبَنِي اللهُ فِدَاءً لِلْعِلْمِ, who is الفاعل, and what is المفعول به الأول؟`, options: [`لَفْظُ الجَلالَةِ is الفاعل; the attached ـني is المفعول به الأول`, `لَفْظُ الجَلالَةِ is المفعول به الأول; ـني is الفاعل`, `فِدَاءً is الفاعل`, `لِلْعِلْمِ is المفعول به الأول`], correct: 0 },
        { title: `جعل: الفرق بين الاستعمالين`, kind: 'mcq', prompt: `جَعَلَ needs particular care because it carries two distinct uses. What decides which use is meant in a given جملة؟`, options: [`How many مفاعيل follow it — two for فعل تحويل, one for بمعنى خَلَقَ أَوْ أَوْجَدَ`, `Whether the فاعل is مذكر or مؤنث`, `Whether the فعل is ماضي or مضارع`, `Whether it is preceded by a حرف جر`], correct: 0 },
        { title: `فجعلناه هباء منثورا: عدد المفاعيل`, kind: 'mcq', prompt: `﴿فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا﴾ takes two مفاعيل — the attached pronoun and هَبَاءً مَنْثُورًا. Which sense of جَعَلَ does that show?`, options: [`فعل تحويل`, `بمعنى خَلَقَ أَوْ أَوْجَدَ`, `فعل قلب من أفعال الظن`, `فعل ناقص من أخوات كان`], correct: 0 },
        { title: `وجعل لكم السمع والأبصار والأفئدة: مفعول واحد`, kind: 'mcq', prompt: `﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾ names hearing, sight, and hearts as a single مفعول به, with no second مفعول naming a new state. What sense of جَعَلَ is this, and how do some مفسّرون gloss it؟`, options: [`بمعنى خَلَقَ أَوْ أَوْجَدَ — some مفسّرون explicitly gloss it as أَوْجَدَ`, `فعل تحويل — glossed as صيّر`, `فعل قلب — glossed as ظنّ`, `فعل ناقص — glossed as كان`], correct: 0 },
        { title: `ترك بمعنى هجر`, kind: 'mcq', prompt: `﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللهِ﴾ has تَرَكَ taking only one مفعول به. What does تَرَكَ mean here, and is this the فعل تحويل sense؟`, options: [`بمعنى هَجَرَ (to abandon) — not the فعل تحويل sense, since only one object appears`, `بمعنى صَيَّرَ — the فعل تحويل sense, since two objects appear`, `بمعنى خَلَقَ — an ordinary creation sense`, `بمعنى رَدَّ — a return-to-state sense`], correct: 0 },
        { title: `رد بمعنى يصار`, kind: 'mcq', prompt: `﴿ثُمَّ يُرَدُّ إِلَى رَبِّهِ﴾ uses رَدَّ in its ordinary sense rather than as فعل تحويل. Which translation fits this ordinary sense؟`, options: [`to be brought back`, `to change into a new state`, `to leave in a condition`, `to take as something else`], correct: 0 },
        { title: `ضابط العدّ: مفعول واحد أم اثنان`, kind: 'mcq', prompt: `The rule for أفعال التحويل mirrors the same signal used for أفعال القلوب. What is that signal؟`, options: [`Count the مفاعيل: one object means the ordinary sense; two objects, the second naming a state the first is put into, signal فعل تحويل`, `Check whether the فعل is ماضي or مضارع`, `Check whether the فاعل is ظاهر or مضمر`, `Check whether تنوين appears on the last word`], correct: 0 },
        {
          title: `تركيب: صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا.`,
          source: `صَيَّرَ عَذْبَ الشَّرَابِ مُرًّا`,
          words: [`صَيَّرَ`, `عَذْبَ`, `الشَّرَابِ`, `مُرًّا`],
          labels: [`فعل تحويل`, `مفعول به أول`, `مضاف إليه`, `مفعول به ثاني`],
          distractors: [`فاعل`, `خبر`, `فعل قلب`, `مفعول به ثالث`],
        },
        {
          title: `تركيب: فَتَرَكَهُ صَلْدًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of فَتَرَكَهُ صَلْدًا.`,
          source: `فَتَرَكَهُ صَلْدًا`,
          words: [`فَتَرَكَهُ`, `صَلْدًا`],
          labels: [`فعل ومفعوله الأول`, `مفعول به ثاني`],
          distractors: [`فاعل`, `مبتدأ`, `خبر`, `حال`],
        },
        {
          title: `تركيب: اتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in اتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا.`,
          source: `اتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا`,
          words: [`اتَّخَذَ`, `اللهُ`, `إِبْرَاهِيمَ`, `خَلِيلًا`],
          labels: [`فعل تحويل`, `فاعل`, `مفعول به أول`, `مفعول به ثاني`],
          distractors: [`خبر`, `مبتدأ`, `فعل قلب`, `مفعول به ثالث`],
        },
        {
          title: `تركيب: فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا.`,
          source: `فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا`,
          words: [`جَعَلْنَاهُ`, `هَبَاءً مَنْثُورًا`],
          labels: [`فعل تحويل ومفعوله الأول`, `مفعول به ثاني`],
          distractors: [`فاعل`, `حال`, `فعل ومفعوله الأول`, `مفعول به`],
        },
        {
          title: `تركيب: تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللهِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللهِ, where تَرَكْتُ carries its ordinary meaning, not فعل تحويل.`,
          source: `تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللهِ`,
          words: [`تَرَكْتُ`, `مِلَّةَ`, `قَوْمٍ`],
          labels: [`فعل (بمعنى هَجَرَ) وفاعله`, `مفعول به`, `مضاف إليه`],
          distractors: [`مفعول به ثاني`, `فعل تحويل`, `فعل ومفعوله الأول`, `مضاف`],
        },
        {
          title: `تركيب: وَهَبَنِي اللهُ فِدَاءً لِلْعِلْمِ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in وَهَبَنِي اللهُ فِدَاءً لِلْعِلْمِ.`,
          source: `وَهَبَنِي اللهُ فِدَاءً لِلْعِلْمِ`,
          words: [`وَهَبَنِي`, `اللهُ`, `فِدَاءً`, `لِلْعِلْمِ`],
          labels: [`فعل ومفعوله الأول`, `فاعل`, `مفعول به ثاني`, `جار ومجرور`],
          distractors: [`مبتدأ`, `خبر`, `حال`, `مفعول به ثالث`],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'التعليق',
      subtitle: 'Three-Object قلب Verbs and Suspension — how a جملة can fill both مفعولي فعل القلب, and what التعليق does to its عمل',
      concepts: [
        {
          heading: 'الفعل الواصل إلى ثلاثة مفاعيل',
          lines: [
            { html: `A verb reaching three مفاعيل is always a <bdi>فعل قلب</bdi> — nothing else takes three.`, list: false },
            { box: { title: 'Core Text', lines: [`وَلَا يَكُونُ إِلَّا فِعْلَ قَلْبٍ، وَالمَفْعُولُ الثَّانِي وَالثَّالِثُ يَكُونَانِ مُبْتَدَأً وَخَبَرًا فِي الأَصْلِ`] } },
            { html: `The second and third مفعولان were originally a مبتدأ and a خبر — the same relationship underlying the two مفعولان of an ordinary فعل قلب.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿كَذَٰلِكَ يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾`] } },
            { table: { title: 'كَذَٰلِكَ يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ', headers: ['Word', 'Role'], rows: [
              [`يُرِيهِمُ`, `فعل ومفعوله الأول`],
              [`اللهُ`, `فاعل`],
              [`أَعْمَالَهُمْ`, `مفعول به ثاني`],
              [`حَسَرَاتٍ`, `مفعول به ثالث`],
            ] } },
            { html: `"Allah will show them their deeds as regrets against them." The قلب سits between أَعْمَالَهُمْ and حَسَرَاتٍ — those two were the مبتدأ and the خبر before يُرِي entered and made them both منصوبين.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿كَذَٰلِكَ يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾, which two مفاعيل were originally مبتدأ وخبر before يُرِي entered؟`,
            kind: 'mcq',
            options: [`أَعْمَالَهُمْ and حَسَرَاتٍ`, `هِمْ (in يُرِيهِمُ) and أَعْمَالَهُمْ`, `اللهُ and أَعْمَالَهُمْ`, `حَسَرَاتٍ and عَلَيْهِمْ`],
            correct: 0,
          },
        },
        {
          heading: 'ما يسدّ مسدّ المفعولين: الاسم المؤول والجملة',
          lines: [
            { html: `أفعال القلوب take two مفعولين. Two things can occupy the place of that pair at once.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ﴾`] } },
            { html: `<bdi>أَنَّ اللهَ مَعَ المُتَّقِينَ</bdi> is an اسم مؤول amounting to <bdi>مَعِيَّةَ اللهِ</bdi>, filling the position of both مفعولي اعلموا at once. Why أنّ rather than a plain مصدر؟ Because أنّ carries توكيد — the sense is not merely "know Allah's being with the God-fearing," but "know for certain" that He is with them.`, list: false },
            { html: `A full جملة can also stand in that place.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿وَاللهُ يَشْهَدُ إِنَّ المُنَافِقِينَ لَكَاذِبُونَ﴾`] } },
            { box: { title: 'Careful', lines: [`شَهِدَ يَشْهَدُ لَيْسَ فِعْلَ قَلْبٍ بِالمَعْنَى الدَّقِيقِ، فَالمِثَالُ أَقَلُّ وُضُوحًا مِنْ غَيْرِهِ`] } },
            { html: `شَهِدَ يَشْهَدُ is not strictly a فعل قلب, so this verse illustrates the point less cleanly than a verb such as يَعْلَمُ would.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ﴾, the اسم مؤول أَنَّ اللهَ مَعَ المُتَّقِينَ fills the place of both مفعولي اعلموا. Why أنّ specifically, rather than a plain مصدر؟`,
            kind: 'mcq',
            options: [`Because أنّ carries توكيد — the sense is "know for certain," not merely "know"`, `Because أنّ is the only حرف مصدر that exists`, `Because a plain مصدر cannot follow اعلم at all`, `Because أنّ turns the جملة into جملة إنشائية`],
            correct: 0,
          },
        },
        {
          heading: 'التعليق: تعريفه وأثره',
          lines: [
            { box: { title: 'Rule', lines: [`إِذَا سَدَّتِ الجُمْلَةُ مَسَدَّ مَفْعُولَيْ فِعْلِ القَلْبِ لَا يَعْمَلُ فِيهِ فِعْلُ القَلْبِ لَفْظًا بَلْ مَحَلًّا`] } },
            { html: `Once a جملة occupies the place of the two مفعولين, the فعل قلب stops governing the individual words inside it — its عمل لفظي is suspended. Its عمل محلي is not: the جملة as a whole sits في محل نصب, سادة مسد مفعولي فعل القلب. That suspension is called <bdi>تعليق</bdi>, and the جملة is called جملة معلقًا عنها العمل.`, list: false },
            { table: { title: 'عمل لفظي، عمل محلي، وتعليق', headers: ['Term', 'Meaning'], rows: [
              [`عمل لفظي`, `The فعل changes the actual endings of the words after it`],
              [`عمل محلي`, `The فعل governs the unit as a whole, without changing any individual ending`],
              [`تعليق`, `العمل اللفظي is suspended; العمل المحلي stays`],
            ] } },
            { box: { title: 'Careful', lines: [`الاسْمُ الأَدَقُّ: جُمْلَةٌ مُعَلَّقٌ عَنْهَا العَمَلُ اللَّفْظِيُّ، لَا العَمَلُ مُطْلَقًا`] } },
            { html: `The common label جملة معلقًا عنها العمل is looser than it should be. Saying only العمل suggests every kind of عمل has been suspended, when only العمل اللفظي has — جملة معلقًا عنها العمل اللفظي would state it exactly, even though the books do not use that fuller wording.`, list: false },
          ],
          exercise: {
            prompt: `Once a جملة occupies the place of the two مفعولي فعل القلب, what happens to that فعل's عمل؟`,
            kind: 'mcq',
            options: [`Its عمل لفظي is suspended, but its عمل محلي remains`, `Both its عمل لفظي and عمل محلي are cancelled outright`, `Nothing changes; it governs the جملة exactly as it would two single words`, `Its عمل محلي is suspended, but its عمل لفظي remains`],
            correct: 0,
          },
        },
        {
          heading: 'الفعل الشبيه بفعل القلب: تعريفه ومثاله',
          lines: [
            { html: `تعليق is not restricted to أفعال القلوب. Some verbs the books of نحو do not list as أفعال القلوب behave like them, and their إعراب shows تعليق plainly.`, list: false },
            { box: { title: 'Definition', lines: [`الفعل الشبيه بفعل القلب: كُلُّ فِعْلٍ يَدُلُّ عَلَى إِخْبَارٍ أَوِ اسْتِفْهَامٍ وَغَيْرِهِمَا`] } },
            { box: { title: 'Core Text', lines: [`﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾`] } },
            { table: { title: 'لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا', headers: ['Word', 'Role'], rows: [
              [`لِيَبْلُوَ`, `فعل شبيه بفعل القلب`],
              [`كُمْ`, `مفعول به أول`],
              [`أَيُّكُمْ`, `مبتدأ`],
              [`أَحْسَنُ عَمَلًا`, `خبر`],
            ] } },
            { html: `"That He may test you as to which of you is best in deed." <bdi>بَلَا يَبْلُو</bdi> means to test, to draw information out — the sense that makes it شبيه بفعل القلب.`, list: false },
            { html: `أَيُّكُمْ is مرفوع, not أَيَّكُمْ: it is مبتدأ, and أَحْسَنُ عَمَلًا is its خبر. The pair form a جملة سادة مسد المفعولين, and because that جملة is معلقة, يَبْلُو does no عمل on its parts.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾, أَيُّكُمْ is مرفوع rather than منصوبا. Why؟`,
            kind: 'mcq',
            options: [`أَيُّكُمْ is مبتدأ, and the جملة أَيُّكُمْ أَحْسَنُ عَمَلًا is معلقة, so يَبْلُو's عمل لفظي does not reach it`, `Because يَبْلُوَ is فعل لازم`, `Because أَيُّكُمْ is بدل من كُمْ`, `Because the فعل here is مبني للمجهول`],
            correct: 0,
          },
        },
        {
          heading: 'سلهم أيهم بذلك زعيم: مثال آخر للفعل الشبيه',
          lines: [
            { box: { title: 'Core Text', lines: [`﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾`] } },
            { table: { title: 'سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ', headers: ['Word', 'Role'], rows: [
              [`سَلْ`, `فعل شبيه بفعل القلب`],
              [`هُمْ`, `مفعول به`],
              [`أَيُّهُمْ`, `مبتدأ`],
              [`بِذَٰلِكَ`, `جار ومجرور`],
              [`زَعِيمٌ`, `خبر`],
            ] } },
            { html: `"Ask them which of them will vouch for that." <bdi>سَأَلَ يَسْأَلُ</bdi> is likewise شبيه بفعل القلب, so its عمل is معلق لفظًا and أَيُّهُمْ stays مرفوع — even though سأل is not itself classified as one of أفعال القلوب.`, list: false },
          ],
          exercise: {
            prompt: `Is سَأَلَ يَسْأَلُ itself classified as a فعل قلب, and does it still trigger تعليق in ﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾؟`,
            kind: 'mcq',
            options: [`No, it is not a فعل قلب, but it is شبيه بفعل القلب and still triggers تعليق`, `Yes, it is a full فعل قلب exactly like عَلِمَ and ظَنَّ`, `No, and it never triggers تعليق under any wording`, `Yes, but only when it appears في صيغة الأمر`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `A verb governs three مفاعيل. Which class of فعل must this be؟`, options: [`فعل قلب, and nothing else`, `Any فعل متعدٍ`, `فعل ناقص`, `فعل تحويل only`], correct: 0 },
        { q: `In a three-object فعل قلب, what were the second and third مفعولان originally؟`, options: [`مبتدأ وخبر`, `فاعل ونائب فاعل`, `حال وصاحبها`, `مضاف ومضاف إليه`], correct: 0 },
        { q: `﴿وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ﴾ uses أنّ rather than a plain مصدر. What does that choice add to the meaning؟`, options: [`توكيد — "know for certain," not merely "know"`, `نفي — denying the fact`, `استفهام — turning it into a question`, `تمنٍّ — expressing a wish`], correct: 0 },
        { q: `When تعليق occurs, which of the فعل القلب's two kinds of عمل survives؟`, options: [`عمل محلي — the جملة stays في محل نصب`, `عمل لفظي — the word endings still change`, `Neither survives`, `Both survive unchanged`], correct: 0 },
        { q: `In ﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾, why is أَيُّكُمْ مرفوع rather than منصوبا؟`, options: [`It is مبتدأ in a جملة معلقة, so بَلَا's عمل لفظي does not reach it`, `Because يَبْلُوَ never takes a مفعول به`, `Because أَيُّكُمْ is بدل من كُمْ`, `Because the فعل is مبني للمجهول`], correct: 0 },
        { q: `Is سَأَلَ يَسْأَلُ itself a فعل قلب, and does it still trigger تعليق in سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ؟`, options: [`No, but it is شبيه بفعل القلب and still triggers تعليق`, `Yes, it is a full فعل قلب`, `No, and it never triggers تعليق`, `Yes, but only في صيغة الأمر`], correct: 0 },
      ],
      bank: [
        { title: `ثلاثة مفاعيل: أي فعل فقط`, kind: 'mcq', prompt: `A verb governs three مفاعيل. Which class of فعل can this be؟`, options: [`فعل قلب فقط`, `Any فعل متعدٍ`, `فعل ناقص`, `فعل تحويل فقط`], correct: 0 },
        { title: `أصل المفعول الثاني والثالث`, kind: 'mcq', prompt: `In a three-object فعل قلب, what were the second and third مفعولان originally؟`, options: [`مبتدأ وخبر`, `فاعل ونائب فاعل`, `حال وصاحبها`, `مضاف ومضاف إليه`], correct: 0 },
        { title: `يريهم الله: موقع القلب`, kind: 'mcq', prompt: `In ﴿كَذَٰلِكَ يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾, where does يُري sit relative to أَعْمَالَهُمْ and حَسَرَاتٍ؟`, options: [`It sits between the two, which were originally مبتدأ وخبر before it entered`, `It comes after both of them`, `It replaces both of them entirely`, `It has no relation to either one`], correct: 0 },
        { title: `اسم مؤول ساد مسد المفعولين`, kind: 'mcq', prompt: `What does it mean for an اسم مؤول to sit في محل نصب مفعولي فعل قلب؟`, options: [`It fills the position of both مفعولين at once, rather than being just one of them`, `It fills only the first مفعول, leaving the second محذوف`, `It becomes الفاعل of the فعل القلب`, `It becomes خبر لفعل القلب`], correct: 0 },
        { title: `أنّ بدل مصدر: التوكيد`, kind: 'mcq', prompt: `﴿وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ﴾ uses أنّ rather than a plain مصدر. What does that choice add to the meaning؟`, options: [`توكيد — "know for certain," not merely "know"`, `نفي — denying the fact`, `استفهام — turning it into a question`, `تمنٍّ — expressing a wish`], correct: 0 },
        { title: `الجملة الاسمية سادة مسد المفعولين`, kind: 'mcq', prompt: `Besides الاسم المؤول, what else can occupy the place of the two مفعولي فعل القلب together؟`, options: [`A full جملة`, `A single مفرد اسم only`, `A حرف جر`, `A ظرف`], correct: 0 },
        { title: `متى يعلَّق الفعل`, kind: 'mcq', prompt: `According to إِذَا سَدَّتِ الجُمْلَةُ مَسَدَّ مَفْعُولَيْ فِعْلِ القَلْبِ, what triggers تعليق؟`, options: [`A جملة occupying the place of the فعل القلب's two مفعولين`, `Any جملة following any فعل at all`, `A مصدر مؤول appearing anywhere in the sentence`, `The فعل القلب being في صيغة الأمر`], correct: 0 },
        { title: `عمل لفظي vs عمل محلي: التعريف`, kind: 'mcq', prompt: `Which pairing correctly matches the two kinds of عمل؟`, options: [`عمل لفظي changes the actual word endings; عمل محلي governs the unit as a whole without changing any ending`, `عمل لفظي governs the unit as a whole; عمل محلي changes word endings`, `Both mean exactly the same thing`, `عمل محلي only applies to الأفعال الناسخة`], correct: 0 },
        { title: `أثر التعليق: أي عمل يبقى`, kind: 'mcq', prompt: `When تعليق occurs, which of the فعل القلب's two kinds of عمل survives؟`, options: [`عمل محلي — the جملة stays في محل نصب`, `عمل لفظي — the word endings still change`, `Neither survives`, `Both survive unchanged`], correct: 0 },
        { title: `تسمية "جملة معلق عنها العمل"`, kind: 'mcq', prompt: `Why is the common label جملة معلقًا عنها العمل looser than it should be؟`, options: [`It suggests every kind of عمل is suspended, when only العمل اللفظي is`, `It suggests no عمل at all remains, which is false in every case`, `It implies the فعل قلب becomes لازم`, `It implies the جملة becomes مبنية`], correct: 0 },
        { title: `الفعل الشبيه بفعل القلب: تعريفه`, kind: 'mcq', prompt: `Which of the following correctly defines الفعل الشبيه بفعل القلب؟`, options: [`Any فعل carrying the sense of conveying information, asking, or something along those lines`, `Any فعل that always takes three مفاعيل`, `Any فعل مبني للمجهول`, `Any فعل that is never متعدٍ`], correct: 0 },
        { title: `يبلوكم: معنى بلا يبلو`, kind: 'mcq', prompt: `بَلَا يَبْلُو in ﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾ carries which sense؟`, options: [`To test, to draw out information`, `To create`, `To return to a former state`, `To leave in a condition`], correct: 0 },
        { title: `أيكم أحسن عملا: الإعراب`, kind: 'mcq', prompt: `In ﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾, what roles do أَيُّكُمْ and أَحْسَنُ عَمَلًا carry؟`, options: [`أَيُّكُمْ = مبتدأ, أَحْسَنُ عَمَلًا = خبر`, `أَيُّكُمْ = مفعول به ثانٍ, أَحْسَنُ عَمَلًا = مفعول به ثالث`, `أَيُّكُمْ = فاعل, أَحْسَنُ عَمَلًا = مفعول به`, `أَيُّكُمْ = حال, أَحْسَنُ عَمَلًا = صفة`], correct: 0 },
        { title: `سلهم أيهم: هل سأل فعل قلب`, kind: 'mcq', prompt: `Is سَأَلَ يَسْأَلُ itself classified as a فعل قلب, and does it still trigger تعليق؟`, options: [`No, it is not a فعل قلب, but it is شبيه بفعل القلب and still triggers تعليق`, `Yes, it is a full فعل قلب like علم and ظن`, `No, and it never triggers تعليق`, `Yes, but only في صيغة الأمر`], correct: 0 },
        { title: `أيهم بذلك زعيم: الإعراب`, kind: 'mcq', prompt: `In سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ, what roles do أَيُّهُمْ and زَعِيمٌ carry؟`, options: [`أَيُّهُمْ = مبتدأ, زَعِيمٌ = خبر`, `أَيُّهُمْ = مفعول به, زَعِيمٌ = فاعل`, `أَيُّهُمْ = فاعل, زَعِيمٌ = مفعول به`, `أَيُّهُمْ = خبر, زَعِيمٌ = مبتدأ`], correct: 0 },
        { title: `التعليق ليس خاصا بأفعال القلوب`, kind: 'mcq', prompt: `Is تعليق restricted only to أفعال القلوب؟`, options: [`No — some verbs that are not فعل قلب but behave like one (الفعل الشبيه بفعل القلب) also show تعليق`, `Yes — only عَلِمَ and ظَنَّ can be معلق`, `No — every متعدٍ فعل shows تعليق`, `Yes — only الأفعال الناقصة show تعليق`], correct: 0 },
        { title: `شهد: هل هو فعل قلب`, kind: 'mcq', prompt: `﴿وَاللهُ يَشْهَدُ إِنَّ المُنَافِقِينَ لَكَاذِبُونَ﴾ illustrates a جملة سادة مسد مفعولي فعل قلب, but with a caveat. What is it؟`, options: [`شَهِدَ يَشْهَدُ is not strictly a فعل قلب, so the example illustrates the point less cleanly`, `شهد never takes a جملة after it`, `شهد is always مبني للمجهول`, `إنّ cannot follow شهد at all`], correct: 0 },
        { title: `وجود المفعولين قبل دخول الفعل`, kind: 'mcq', prompt: `Before a فعل قلب enters a sentence like مُحَمَّدٌ صَادِقٌ, what relation do the eventual two مفعولان hold؟`, options: [`مبتدأ وخبر of an ordinary جملة اسمية`, `فاعل ونائب فاعل`, `حال وصاحب الحال`, `مضاف ومضاف إليه`], correct: 0 },
        { title: `اسم مؤول أم جملة: مثالان مختلفان`, kind: 'mcq', prompt: `وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ and وَاللهُ يَشْهَدُ إِنَّ المُنَافِقِينَ لَكَاذِبُونَ each show a different construction filling the place of the two مفعولين. Which pairing is correct؟`, options: [`اعلموا: اسم مؤول (أنّ + الجملة); يشهد: جملة اسمية كاملة (إنّ...)`, `اعلموا: جملة; يشهد: اسم مؤول`, `Both use اسم مؤول`, `Both use جملة فعلية`], correct: 0 },
        { title: `فائدة التعليق: بقاء المعنى النحوي`, kind: 'mcq', prompt: `Even though a معلق فعل قلب stops changing the endings of the words after it, what keeps the جملة grammatically tied to it؟`, options: [`Its عمل محلي — the جملة still sits في محل نصب مفعولي الفعل`, `Nothing — the جملة becomes fully independent of the فعل`, `Its عمل لفظي, which continues normally`, `A حرف عطف connecting them`], correct: 0 },
        {
          title: `تركيب: كَذَٰلِكَ يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ.`,
          source: `يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ`,
          words: [`يُرِيهِمُ`, `اللهُ`, `أَعْمَالَهُمْ`, `حَسَرَاتٍ`],
          labels: [`فعل ومفعوله الأول`, `فاعل`, `مفعول به ثانٍ`, `مفعول به ثالث`],
          distractors: [`خبر`, `حال`, `مفعول به أول`, `مبتدأ`],
        },
        {
          title: `تركيب: وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of اعْلَمُوا and of the اسم مؤول that follows it in وَاعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ.`,
          source: `اعْلَمُوا أَنَّ اللهَ مَعَ المُتَّقِينَ`,
          words: [`اعْلَمُوا`, `أَنَّ اللهَ مَعَ المُتَّقِينَ`],
          labels: [`فعل قلب وفاعله`, `اسم مؤول سادّ مسدّ مفعولي اعلموا`],
          distractors: [`مفعول به ثالث`, `خبر`, `جملة سادة مسد المفعولين`, `فعل شبيه بفعل القلب`],
        },
        {
          title: `تركيب: لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا.`,
          source: `لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا`,
          words: [`لِيَبْلُوَ`, `كُمْ`, `أَيُّكُمْ`, `أَحْسَنُ عَمَلًا`],
          labels: [`فعل شبيه بفعل القلب`, `مفعول به أول`, `مبتدأ`, `خبر`],
          distractors: [`مفعول به ثانٍ`, `حال`, `فعل قلب`, `مفعول به ثالث`],
        },
        {
          title: `تركيب: سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ.`,
          source: `سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ`,
          words: [`سَلْ`, `هُمْ`, `أَيُّهُمْ`, `بِذَٰلِكَ`, `زَعِيمٌ`],
          labels: [`فعل شبيه بفعل القلب`, `مفعول به`, `مبتدأ`, `جار ومجرور`, `خبر`],
          distractors: [`مفعول به ثانٍ`, `حال`, `فعل قلب`],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الإلغاء والترجيح',
      subtitle: 'What Triggers التعليق, and الإلغاء — the full list of صدارة particles, then when to cancel a فعل قلب\'s عمل entirely',
      concepts: [
        {
          heading: 'تعليق الفعل المتعدي لمفعول واحد',
          lines: [
            { box: { title: 'Rule', lines: [`قَدْ يُعَلَّقُ الفِعْلُ المُتَعَدِّي لِمَفْعُولٍ وَاحِدٍ عَنِ العَمَلِ إِذَا تَصَدَّرَتِ الجُمْلَةُ بِاسْتِفْهَامٍ`] } },
            { html: `Even a verb taking a single مفعول can be معلق, provided that مفعول is a جملة opening with استفهام.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾`] } },
            { html: `"Let him look at which of it is purest as food." <bdi>نَظَرَ يَنْظُرُ</bdi> takes one مفعول; because that مفعول is a جملة beginning with استفهام, تعليق applies, and the reading is أَيُّهَا, not أَيَّهَا.`, list: false },
            { box: { title: 'Careful', lines: [`لَا يُقَالُ هُنَا سَادَّةٌ مَسَدَّ المَفْعُولَيْنِ، إِذْ لَمْ يَكُنْ ثَمَّ مَفْعُولَانِ أَصْلًا`] } },
            { html: `The label سادة مسد المفعولين does not fit this case, because there was never a pair of مفعولين to stand in for — only one. What produces the تعليق here is الاستفهام itself, not a substitution for two objects.`, list: false },
          ],
          exercise: {
            prompt: `﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾ has نَظَرَ, a verb that ordinarily takes only one مفعول. Why does أَيُّهَا read مرفوع rather than منصوبا؟`,
            kind: 'mcq',
            options: [`Because the جملة أَيُّهَا أَزْكَىٰ طَعَامًا opens with استفهام, and تعليق applies even to a single-object verb here`, `Because نظر never takes a مفعول به at all`, `Because أَيُّهَا is بدل من طَعَامًا`, `Because نظر here is فعل أمر مبني`],
            correct: 0,
          },
        },
        {
          heading: 'المعلقات: صدارة الكلام، وإن وما النافيتان',
          lines: [
            { box: { title: 'Rule', lines: [`يُعَلَّقُ عَمَلُ فِعْلِ القَلْبِ اللَّفْظِيُّ عَنِ الجُمْلَةِ بَعْدَهَا إِنْ صَدَرَتْ بِمَا لَهُ صَدْرُ الكَلَامِ`] } },
            { html: `<bdi>صدر الكلام</bdi> means a word that must stand at the head of its clause and cannot be governed by anything before it. When such a word opens the جملة following a فعل قلب, its عمل اللفظي is suspended and the جملة carries its own إعراب as a unit.`, list: false },
            { table: { title: 'أدوات التعليق', headers: ['Trigger', 'Example'], rows: [
              [`إن النافية`, `﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾`],
              [`ما النافية`, `﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالأَرْضِ بَصَائِرَ﴾`],
              [`لام الابتداء`, `﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ﴾`],
              [`اللام المزحلقة`, `﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾`],
              [`لعل`, `﴿وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ﴾`],
              [`حرف الاستفهام أو اسم الاستفهام`, `﴿لِيَبْلُوَنِي أَأَشْكُرُ أَمْ أَكْفُرُ﴾`],
              [`لام جواب القسم`, `وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي`],
            ] } },
            { html: `<bdi>إن النافية</bdi> and <bdi>ما النافية</bdi> must both stand first in their clause, which is exactly what gives them صدر الكلام. In ﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ...﴾, عَلِمْتَ is a فعل قلب and ما follows it directly, so the جملة after it is معلقًا عنها العمل and عَلِمْتَ governs it محلًّا only.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالأَرْضِ بَصَائِرَ﴾, ما directly follows عَلِمْتَ. What does that do to عَلِمْتَ's عمل؟`,
            kind: 'mcq',
            options: [`The جملة after ما becomes معلقًا عنها العمل, and عَلِمْتَ governs it محلا only`, `عَلِمْتَ governs ما as its مفعول به directly`, `ما cancels عَلِمْتَ's عمل entirely, as in الإلغاء`, `ما has no effect since it is not صدر الكلام`],
            correct: 0,
          },
        },
        {
          heading: 'لام الابتداء واللام المزحلقة',
          lines: [
            { box: { title: 'Core Text', lines: [`﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ﴾`] } },
            { table: { title: 'لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ', headers: ['Part', 'Role'], rows: [
              [`لَمَنِ اشْتَرَاهُ`, `مبتدأ`],
              [`مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ`, `خبر`],
            ] } },
            { html: `Remove the لام and مَنِ اشْتَرَاهُ would be مفعول به أول of عَلِمُوا — the لام is what suspends the عمل, and from that point the جملة takes its own إعراب.`, list: false },
            { html: `<bdi>اللام المزحلقة</bdi> works exactly like لام الابتداء where تعليق is concerned.`, list: false },
            { box: { title: 'Core Text', lines: [`﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾`] } },
            { html: `After a verb such as نَعْلَمُ you would ordinarily expect أنّ — نَعْلَمُ أَنَّهُ.`, list: false },
            { html: `اللام المزحلقة is present, so the reading is إنّ, and the جملة is معلقًا عنها العمل.`, list: false },
          ],
          exercise: {
            prompt: `Remove the لام from وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ. What role would مَنِ اشْتَرَاهُ then take؟`,
            kind: 'mcq',
            options: [`مفعول به أول of عَلِمُوا`, `The same خبر role it holds now`, `فاعل عَلِمُوا`, `حال من فاعل عَلِمُوا`],
            correct: 0,
          },
        },
        {
          heading: 'حرف الاستفهام واسم الاستفهام',
          lines: [
            { box: { title: 'Core Text', lines: [`﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾`] } },
            { html: `"And those who did wrong will come to know to what return they will be returned."`, list: false },
            { box: { title: 'Careful', lines: [`أَيَّ مَنْصُوبَةٌ بِيَنْقَلِبُونَ لَا بِسَيَعْلَمُ`] } },
            { html: `أَيَّ is منصوب here, and it is easy to assume سَيَعْلَمُ put it there. It did not — أَيَّ is the معمول of يَنْقَلِبُونَ, the فعل after it (either مفعول مطلق or مفعول فيه, depending on how مُنْقَلَب is read). Either way, the جملة is معلقًا عنها العمل, so يَعْلَمُ's عمل does not reach the individual parts of what follows.`, list: false },
            { box: { title: 'Rule', lines: [`لَا يَدْخُلُ فِعْلٌ عَلَى اسْتِفْهَامٍ إِلَّا فِعْلَ قَلْبٍ أَوْ فِعْلًا شَبِيهًا بِفِعْلِ القَلْبِ`] } },
            { html: `الاستفهام holds صدارة الكلام, so nothing may come before it — with one exception: a فعل قلب or a فعل شبيه بفعل القلب may precede it. <bdi>ضَرَبْتُ أَتَشْكُرُ</bdi> is not said; <bdi>سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ</bdi> is, because سأل is شبيه بفعل القلب.`, list: false },
            { box: { title: 'Careful', lines: [`لَا يُرَادُ مِنَ الِاسْتِفْهَامِ بَعْدَ فِعْلِ القَلْبِ طَلَبُ العِلْمِ`] } },
            { html: `استفهام ordinarily means طلب العلم — asking in order to find out. After a فعل قلب, that purpose drops away: in ﴿لِيَبْلُوَنِي أَأَشْكُرُ أَمْ أَكْفُرُ﴾ the sense is "to test me whether I am grateful or ungrateful," not a real question. The استفهام here functions closer to a حرف مصدر.`, list: false },
          ],
          exercise: {
            prompt: `﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾: أَيَّ is منصوب. What actually governs it؟`,
            kind: 'mcq',
            options: [`يَنْقَلِبُونَ, the فعل after it — not سَيَعْلَمُ`, `سَيَعْلَمُ directly`, `الَّذِينَ ظَلَمُوا`, `It has no عامل at all`],
            correct: 0,
          },
        },
        {
          heading: 'لام جواب القسم',
          lines: [
            { box: { title: 'Core Text', lines: [`وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي ... إِنَّ المَنَايَا لَا تَطِيشُ سِهَامُهَا`] } },
            { html: `عَلِمْتُ is a فعل قلب. The قسم itself — وَلَفْظِ الجَلالَةِ — is محذوف, and what follows is its جواب carrying اللام. That لام makes لَتَأْتِيَنَّ مَنِيَّتِي a جملة معلقًا عنها العمل.`, list: false },
            { html: `"I know for certain that my death will come to me, for the arrows of death do not go astray." <bdi>سِهَام</bdi> are arrows: death is pictured loosing arrows at people, and these arrows do not wander left or right — when one is released it finds its target. Everyone must pass away.`, list: false },
          ],
          exercise: {
            prompt: `In وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي, the قسم itself (وَلَفْظِ الجَلالَةِ) does not appear in the wording. What is لَتَأْتِيَنَّ مَنِيَّتِي, and what does its لام do to عَلِمْتُ's عمل؟`,
            kind: 'mcq',
            options: [`It is جواب القسم المحذوف, and its لام makes the جملة معلقًا عنها العمل`, `It is مفعول به مباشر of عَلِمْتُ`, `It is بدل من مَنِيَّتِي`, `It has no grammatical relation to عَلِمْتُ at all`],
            correct: 0,
          },
        },
        {
          heading: 'الإلغاء، والترجيح بين الإعمال والإلغاء',
          lines: [
            { box: { title: 'Definition', lines: [`الإِلْغَاءُ: إِبْطَالُ عَمَلِ فِعْلِ القَلْبِ اللَّفْظِيِّ وَالمَحَلِّيِّ`] } },
            { html: `The word comes from <bdi>لَغْو</bdi> — null, void, futile. Applied to a فعل قلب, إلغاء cancels its عمل outright, unlike تعليق, which suspends only the عمل اللفظي.`, list: false },
            { table: { title: 'التعليق مقابل الإلغاء', headers: ['', 'تعليق', 'إلغاء'], rows: [
              [`عمل لفظي`, `Suspended`, `Cancelled`],
              [`عمل محلي`, `Remains — الجملة في محل نصب`, `Cancelled`],
              [`ما يصير إليه ما بعد الفعل`, `A جملة governed as a unit`, `An independent مبتدأ وخبر`],
            ] } },
            { html: `Both الإعمال and الإلغاء are permitted with أفعال القلوب. Which one is preferred depends on where the فعل sits relative to its two معمولين.`, list: false },
            { box: { title: 'Rule', lines: [`يَتَرَجَّحُ إِعْمَالُ فِعْلِ القَلْبِ إِذَا تَوَسَّطَ بَيْنَ مَفْعُولَيْهِ`] } },
            { box: { title: 'Core Text', lines: [`مُحَمَّدًا عَلِمْتُ صَادِقًا`] } },
            { table: { title: 'مُحَمَّدًا عَلِمْتُ صَادِقًا', headers: ['Word', 'Role'], rows: [
              [`مُحَمَّدًا`, `مفعول به أول`],
              [`عَلِمْتُ`, `فعل قلب`],
              [`صَادِقًا`, `مفعول به ثاني`],
            ] } },
            { html: `"I knew Muhammad to be truthful." The فعل has come between its two معمولين, so الإعمال is the stronger reading here — الإلغاء remains available (مُحَمَّدٌ عَلِمْتُ صَادِقٌ, with مُحَمَّدٌ as مبتدأ, صَادِقٌ as خبر, and عَلِمْتُ governing nothing), but it is the weaker of the two.`, list: false },
            { box: { title: 'Rule', lines: [`وَيَتَرَجَّحُ إِلْغَاءُ فِعْلِ القَلْبِ إِذَا تَأَخَّرَ عَنْ مَعْمُولَيْهِ`] } },
            { box: { title: 'Core Text', lines: [`مُحَمَّدٌ صَادِقٌ عَلِمْتُ`] } },
            { table: { title: 'مُحَمَّدٌ صَادِقٌ عَلِمْتُ', headers: ['Word', 'Role'], rows: [
              [`مُحَمَّدٌ`, `مبتدأ`],
              [`صَادِقٌ`, `خبر`],
              [`عَلِمْتُ`, `فعل قلب ملغى`],
            ] } },
            { html: `Here the فعل has fallen to the end, behind both its معمولين. Now الإلغاء is the stronger reading: no عمل لفظي and no عمل محلي, and مُحَمَّدٌ صَادِقٌ stands as an ordinary جملة اسمية.`, list: false },
          ],
          exercise: {
            prompt: `مُحَمَّدًا عَلِمْتُ صَادِقًا has عَلِمْتُ sitting between its two معمولين. Which reading is stronger here، الإعمال أم الإلغاء؟`,
            kind: 'mcq',
            options: [`الإعمال — since the فعل قلب comes between its two معمولين`, `الإلغاء — since the فعل قلب comes between its two معمولين`, `Neither reading is possible in this word order`, `Both readings are equally impossible`],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: `قَدْ يُعَلَّقُ الفِعْلُ المُتَعَدِّي لِمَفْعُولٍ وَاحِدٍ عَنِ العَمَلِ in which case؟`, options: [`إذا تصدرت الجملة بعده باستفهام`, `إذا كان الفعل أمرا`, `إذا تأخر الفعل عن فاعله`, `إذا كان المفعول ضميرا`], correct: 0 },
        { q: `What gives إن النافية and ما النافية the power to trigger تعليق؟`, options: [`Both are صدر الكلام`, `Both are أفعال قلب`, `Both are حروف جر`, `Both are ضمائر`], correct: 0 },
        { q: `In وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ, removing اللام changes مَنِ اشْتَرَاهُ's role from what to what؟`, options: [`from مبتدأ (under تعليق) to مفعول به أول of عَلِمُوا`, `from فاعل to مفعول به`, `from خبر to مبتدأ`, `from حال to تمييز`], correct: 0 },
        { q: `﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾: what actually governs أَيَّ؟`, options: [`يَنْقَلِبُونَ, not سَيَعْلَمُ`, `سَيَعْلَمُ directly`, `It has no عامل`, `الَّذِينَ`], correct: 0 },
        { q: `What is the essential difference between التعليق and الإلغاء؟`, options: [`تعليق suspends only العمل اللفظي; إلغاء cancels both العمل اللفظي والمحلي`, `تعليق cancels both; إلغاء suspends only العمل اللفظي`, `They are two names for the exact same rule`, `تعليق applies only to الأفعال الناقصة`], correct: 0 },
        { q: `مُحَمَّدٌ صَادِقٌ عَلِمْتُ has the فعل قلب positioned after both معمولين. Which reading is preferred here؟`, options: [`الإلغاء`, `الإعمال`, `Neither reading is grammatically valid`, `Both are equally weak`], correct: 0 },
      ],
      bank: [
        { title: `تعليق الفعل المتعدي لمفعول واحد: الشرط`, kind: 'mcq', prompt: `A فعل متعدٍ لمفعول واحد can still be معلق. What single condition triggers that؟`, options: [`Its مفعول is a جملة opening with استفهام`, `Its مفعول is مذكور صراحة`, `Its فاعل is ضمير مستتر`, `It is في صيغة الأمر`], correct: 0 },
        { title: `أيها أزكى طعاما: لماذا الرفع`, kind: 'mcq', prompt: `﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾ reads أَيُّهَا, not أَيَّهَا. Why؟`, options: [`التعليق blocks نَظَرَ from working لفظا on the استفهام clause after it`, `Because نظر is لازم, not transitive`, `Because أَيُّهَا is بدل from the منصوب طَعَامًا`, `Because أَيُّهَا is always مبني on النصب`], correct: 0 },
        { title: `سادة مسد المفعولين: لماذا لا تنطبق هنا`, kind: 'mcq', prompt: `Why does the label سادة مسد المفعولين not properly fit ﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾؟`, options: [`نظر takes only one مفعول, so there was never a pair of مفعولين to begin with`, `Because نظر is not a transitive verb`, `Because the clause is not استفهام`, `Because أيها is a non-declinable اسم`], correct: 0 },
        { title: `صدر الكلام: التعريف`, kind: 'mcq', prompt: `What does صدر الكلام mean?`, options: [`A word that must stand at the head of its clause and cannot be governed by anything before it`, `A word that always ends its clause`, `Any حرف جر`, `Any اسم معرب`], correct: 0 },
        { title: `أدوات المعلقات: تحديد إحداها`, kind: 'mcq', prompt: `Which of the following is one of the recognised triggers of تعليق named in the full list؟`, options: [`لام جواب القسم`, `تنوين التمكين`, `همزة الوصل`, `تاء التأنيث الساكنة`], correct: 0 },
        { title: `ما النافية ولقد علمت ما أنزل هؤلاء`, kind: 'mcq', prompt: `In ﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالأَرْضِ بَصَائِرَ﴾, what does ما directly following عَلِمْتَ do to its عمل؟`, options: [`It suspends its لفظي عمل over the clause after it (تعليق)`, `It cancels its عمل entirely (إلغاء)`, `It changes nothing about its عمل`, `It turns it into a لازم verb`], correct: 0 },
        { title: `لام الابتداء: أثرها في الإعراب`, kind: 'mcq', prompt: `In وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ, what does removing اللام do to مَنِ اشْتَرَاهُ's role؟`, options: [`It becomes the first مفعول به of علموا instead of مبتدأ`, `It stays مبتدأ as it is`, `It becomes the فاعل of علموا`, `It becomes حال`], correct: 0 },
        { title: `اللام المزحلقة بدل أنّ`, kind: 'mcq', prompt: `After نَعْلَمُ you would ordinarily expect أنّ. In ﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾, why does إنّ appear instead؟`, options: [`Because of اللام المزحلقة entering upon إنّ's خبر`, `Because نعلم is a لازم verb`, `Because the clause is استفهام`, `Because إنّ here is a حرف عطف`], correct: 0 },
        { title: `أي منقلب ينقلبون: عامل أيّ`, kind: 'mcq', prompt: `﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ has أَيَّ منصوبا. Is سَيَعْلَمُ what put it there؟`, options: [`No — the عامل governing it is يَنْقَلِبُونَ`, `Yes — سيعلم is the عامل`, `It has no عامل`, `The عامل is الَّذِينَ ظَلَمُوا`], correct: 0 },
        { title: `قاعدة دخول الفعل على الاستفهام`, kind: 'mcq', prompt: `Which rule governs what kind of فعل may precede استفهام, given that الاستفهام itself holds صدارة الكلام؟`, options: [`Only a فعل قلب or a verb resembling a فعل قلب may enter upon استفهام`, `No فعل at all may enter upon استفهام`, `Any transitive فعل may enter upon it`, `Only الأفعال الناقصة may enter upon it`], correct: 0 },
        { title: `ضربت أتشكر: لماذا لا يقال`, kind: 'mcq', prompt: `Why is ضَرَبْتُ أَتَشْكُرُ not something said in Arabic؟`, options: [`Because ضرب is neither a فعل قلب nor resembles one, so it cannot enter upon استفهام`, `Because أتشكر is not a valid clause`, `Because ضرب is a لازم verb`, `Because استفهام cannot follow a ماضي verb`], correct: 0 },
        { title: `الاستفهام بعد فعل القلب: ليس طلب علم`, kind: 'mcq', prompt: `﴿لِيَبْلُوَنِي أَأَشْكُرُ أَمْ أَكْفُرُ﴾ uses استفهام after a فعل قلب. Is a real question being asked؟`, options: [`No — this استفهام doesn't seek knowledge; it functions almost like a حرف مصدر`, `Yes — it is a genuine, full question`, `No — because the verb here is مبني للمجهول`, `Yes, but it is a question addressed only to الله`], correct: 0 },
        { title: `لام جواب القسم: القسم المحذوف`, kind: 'mcq', prompt: `In وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي, what has been omitted from the wording, and how do we know it is there؟`, options: [`The oath itself (وَلَفْظِ الجَلالَةِ), indicated by the لام in جواب القسم`, `The فاعل, indicated by the verb being مبني للمجهول`, `The مفعول به, indicated by context`, `Nothing is omitted here`], correct: 0 },
        { title: `الإلغاء: التعريف`, kind: 'mcq', prompt: `Which of the following correctly defines الإلغاء؟`, options: [`Cancelling the فعل قلب's عمل, both لفظي and محلي, together`, `Suspending only the فعل قلب's لفظي عمل`, `Turning the فعل قلب into a فعل تام`, `Moving the فعل قلب into a different باب`], correct: 0 },
        { title: `الفرق بين التعليق والإلغاء`, kind: 'mcq', prompt: `What distinguishes الإلغاء from التعليق؟`, options: [`التعليق cancels only the لفظي عمل and keeps the محلي; الإلغاء cancels both`, `التعليق cancels both; الإلغاء cancels only the لفظي`, `There is no difference between them`, `التعليق applies only to أفعال القلوب; الإلغاء applies only to الأفعال الناقصة`], correct: 0 },
        { title: `محمدا علمت صادقا: أي القراءتين أرجح`, kind: 'mcq', prompt: `مُحَمَّدًا عَلِمْتُ صَادِقًا has عَلِمْتُ positioned between its two معمولين. Which reading is stronger here؟`, options: [`الإعمال, with الإلغاء still permitted though weaker`, `الإلغاء only — الإعمال is disallowed`, `Neither is permitted`, `الإعمال is entirely disallowed`], correct: 0 },
        { title: `محمد صادق علمت: أي القراءتين أرجح`, kind: 'mcq', prompt: `مُحَمَّدٌ صَادِقٌ عَلِمْتُ has عَلِمْتُ falling after both معمولين. Which reading is stronger here؟`, options: [`الإلغاء — مُحَمَّدٌ صَادِقٌ becomes an ordinary جملة اسمية`, `الإعمال — علمت keeps working لفظا`, `Both are disallowed`, `الإعمال — علمت works محلا only`], correct: 0 },
        { title: `ما يبقى بعد الإلغاء`, kind: 'mcq', prompt: `Once إلغاء applies to مُحَمَّدٌ صَادِقٌ عَلِمْتُ, what do مُحَمَّدٌ and صَادِقٌ become؟`, options: [`مبتدأ and خبر of an ordinary جملة اسمية, no longer governed by علمت`, `Still two مفعول به of علمت despite الإلغاء`, `حال and صاحب الحال`, `They take no إعراب at all`], correct: 0 },
        {
          title: `تركيب: فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا.`,
          source: `فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا`,
          words: [`فَلْيَنْظُرْ`, `أَيُّهَا`, `أَزْكَىٰ طَعَامًا`],
          labels: [`فعل معلق عن العمل`, `مبتدأ`, `خبر`],
          distractors: [`مفعول به`, `فاعل`, `فعل شبيه بفعل القلب`, `مفعول به ثانٍ`],
        },
        {
          title: `تركيب: وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of علِمُوا and of the two halves of the جملة معلقة after it.`,
          source: `عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ`,
          words: [`عَلِمُوا`, `لَمَنِ اشْتَرَاهُ`, `مَا لَهُ فِي الآخِرَةِ مِنْ خَلَاقٍ`],
          labels: [`فعل قلب معلق عن العمل`, `مبتدأ`, `خبر`],
          distractors: [`مفعول به ثانٍ`, `حال`, `فعل شبيه بفعل القلب`, `مفعول به أول`],
        },
        {
          title: `تركيب: مُحَمَّدًا عَلِمْتُ صَادِقًا`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in مُحَمَّدًا عَلِمْتُ صَادِقًا.`,
          source: `مُحَمَّدًا عَلِمْتُ صَادِقًا`,
          words: [`مُحَمَّدًا`, `عَلِمْتُ`, `صَادِقًا`],
          labels: [`مفعول به أول`, `فعل قلب`, `مفعول به ثانٍ`],
          distractors: [`مبتدأ`, `خبر`, `فعل قلب ملغى`, `حال`],
        },
        {
          title: `تركيب: مُحَمَّدٌ صَادِقٌ عَلِمْتُ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each word in مُحَمَّدٌ صَادِقٌ عَلِمْتُ, where عَلِمْتُ is ملغى.`,
          source: `مُحَمَّدٌ صَادِقٌ عَلِمْتُ`,
          words: [`مُحَمَّدٌ`, `صَادِقٌ`, `عَلِمْتُ`],
          labels: [`مبتدأ`, `خبر`, `فعل قلب ملغى`],
          distractors: [`مفعول به أول`, `مفعول به ثانٍ`, `فعل قلب`, `فعل معلق عن العمل`],
        },
        {
          title: `تركيب: وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of عَلِمْتُ and of the جملة after it in عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي.`,
          source: `عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي`,
          words: [`عَلِمْتُ`, `لَتَأْتِيَنَّ مَنِيَّتِي`],
          labels: [`فعل قلب وفاعله`, `جملة جواب القسم معلق عنها العمل`],
          distractors: [`مفعول به مباشر`, `خبر`, `جملة سادة مسد المفعولين`, `فعل قلب ملغى`],
        },
        {
          title: `تركيب: وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ`,
          kind: 'tarkeeb',
          instruction: `Identify the grammatical role of each part of سَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ.`,
          source: `سَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ`,
          words: [`سَيَعْلَمُ`, `الَّذِينَ ظَلَمُوا`, `أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ`],
          labels: [`فعل قلب معلق عن العمل`, `فاعل`, `جملة استفهامية سادة مسد المفعولين`],
          distractors: [`مفعول به أول`, `خبر`, `جملة معلق عنها العمل`, `مفعول به ثانٍ`],
        },
      ],
    },
  ],
};
