// Module 01 — المقدمة (The Introduction)
//
// Content is adapted from a bilingual Anki deck (النَحْوُ__1 الْمُقَدِّمَةُ.apkg,
// 86 notes across 5 sub-decks) prepared for this conversion. Definitions and
// examples are kept faithful to the source notes. Concept bodies are short
// by design (a sentence or two, not teaching prose); quiz/drill/bank
// question text is English with Arabic grammatical terms left in Arabic.

export default {
  id: '01',
  title: 'المقدمة',
  heading: 'المقدمة',
  blurb: 'The foundations of An-Nahw: the word, the sentence, and the governor/governed relationship.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'الكلمة',
      subtitle: 'The Word — utterance, meaning, and the three divisions of speech',
      concepts: [
        {
          heading: 'اللفظ، القول، والكلمة',
          lines: [
            { html: `Four terms build on each other, each one narrower than the last.`, list: false },
            { html: `<bdi>اللَّفْظ</bdi> — any sound that comes out of the mouth, whether or not it means anything.`, list: true, bullet: true },
            { html: `<bdi>الْقَوْل</bdi> — a لفظ that does mean something, e.g. <bdi>زَيْدٌ</bdi>.`, list: true, bullet: true },
            { html: `<bdi>الْكَلِمَة</bdi> — a single (<bdi>مُفْرَد</bdi>) meaningful قول, one whose own parts carry no meaning on their own, like <bdi>رَجُل</bdi> (ر + ج + ل mean nothing separately).`, list: true, bullet: true },
            { html: `<bdi>الْمُرَكَّب</bdi> — a meaningful قول whose parts each mean something on their own, like <bdi>كِتَابُ الْوَلَدِ</bdi> (كتاب means something, الولد means something) — so this counts as two كلمات, not one.`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Three of these four terms apply to both كِتَابُ الْوَلَدِ and رَجُلٌ. Which one applies to كِتَابُ الْوَلَدِ alone?`,
            kind: 'mcq',
            options: ['اللفظ', 'القول', 'المركب', 'المفرد'],
            correct: 2,
          },
        },
        {
          heading: 'أقسام الكلمة الثلاثة، والاسم',
          lines: [
            { html: `الكلمة splits into three types: <bdi>الِاسْم</bdi>, <bdi>الْفِعْل</bdi>, and <bdi>الْحَرْف</bdi>.`, list: false },
            { html: `الاسم is a كلمة whose meaning is not tied to a time.`, list: false },
            { table: { title: 'Two Forms of الاسم', headers: ['Form', 'What it is', 'Example'], rows: [
              ['اسْمٌ صَرِيح', 'a plain word', 'الصَّوْمُ'],
              ['اسْمٌ مُؤَوَّل', 'a حرف مصدر + جملة acting as one اسم', 'أَنْ تَصُومُوا (= صَوْمُكُمْ) في ﴿وَأَنْ تَصُومُوا خَيْرٌ﴾'],
            ] } },
            { html: `Within الاسم, a described thing is called <bdi>الْمَوْصُوف</bdi> and its description is <bdi>الصِّفَة</bdi> (e.g. <bdi>صَالِحٌ، عَالِمٌ</bdi>).`, list: false },
            { table: { title: 'Two Kinds of الموصوف', headers: ['Kind', 'What it means', 'Example'], rows: [
              ['اسْمُ عَيْنٍ', 'subsists by itself', 'رَجُلٌ'],
              ['اسْمُ مَعْنًى', 'subsists only through another', 'عِلْمٌ'],
            ] } },
          ],
          exercise: {
            prompt: `All four of these are أسماء. Which one is the اسم المؤول rather than an اسم صريح?`,
            kind: 'mcq',
            options: ['أَنْ تَصُومُوا', 'الصَّوْمُ', 'الصَّائِمُونَ', 'صِيَامُ الْوَلَدِ'],
            correct: 0,
          },
        },
        {
          heading: 'الفعل والحرف',
          lines: [
            { html: `الفعل adds one thing to the definition of الاسم: its meaning IS tied to time, e.g. <bdi>عَبَدَ، يَعْبُدُ، اُعْبُدْ</bdi>.`, list: false },
            { html: `الحرف indicates a meaning only in something else, like <bdi>فِي</bdi> or <bdi>إِنَّ</bdi>.`, list: false },
            { table: { title: 'Two Senses of the Word حرف', headers: ['Sense', 'What it means', 'Examples'], rows: [
              ['حُرُوفُ الْمَعَانِي (grammatical)', 'a particle whose meaning appears only in another word', 'فِي، إِنَّ، بَلْ، لَا'],
              ['حُرُوفُ الْمَبَانِي (spelling)', 'the letters of the alphabet itself', 'ف، ع، ل'],
            ] } },
            { html: `Don't confuse the two senses — the grammatical حرف is one of the three أقسام الكلمة; حروف المباني just means "letters" in the ordinary sense.`, list: false },
          ],
          exercise: {
            prompt: `Neither إِنَّ nor رَجُلٌ carries any attachment to time. What then separates إِنَّ from رَجُلٌ?`,
            kind: 'mcq',
            options: ['إِنَّ indicates its meaning only in another word', 'إِنَّ indicates an event fixed to a time', 'إِنَّ is مركب, while رَجُلٌ is مفرد', 'إِنَّ is a letter of spelling, not a word'],
            correct: 0,
          },
        },
        {
          heading: 'حرف المد وحرف اللين',
          lines: [
            { html: `Both are a weak, vowelless letter — <bdi>و ي ا</bdi>. What separates them is the vowel that comes right before.`, list: false },
            { table: { headers: ['Term', 'Condition', 'Example'], rows: [
              ['حَرْفُ الْمَدِّ', 'preceded by the vowel that matches it', 'الصَّادِقِينَ (الياء ساكنة بعد كسرة تطابقها)'],
              ['حَرْفُ اللِّينِ', 'a و or ي preceded by a فتحة that does NOT match it', 'الْخَيْر (الياء ساكنة بعد فتحة لا تطابقها)'],
            ] } },
          ],
          exercise: {
            prompt: `The ياء of الْخَيْر and the ياء of الصَّادِقِينَ are both ساكنة. Which of them is حرف اللين, and on what grounds?`,
            kind: 'mcq',
            options: ['الْخَيْر — the vowel before it does not match it', 'الصَّادِقِينَ — the vowel before it does not match it', 'الْخَيْر — it sits at the very end of the word', 'الصَّادِقِينَ — the vowel before it is a long one'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the definition of اللفظ؟',
          options: ['An utterance that indicates a meaning', 'Every sound that exits a person’s mouth', 'A single meaningful utterance', 'A meaning tied to time'],
          correct: 1,
        },
        {
          q: 'الكلمة splits into three categories. What are they?',
          options: ['الاسم، الفعل، الحرف', 'المفرد، المركب، الجملة', 'الصريح، المؤول، الموصوف', 'الجار، المجرور، الظرف'],
          correct: 0,
        },
        {
          q: 'In ﴿وَأَنْ تَصُومُوا خَيْرٌ﴾, أَنْ تَصُومُوا is best classified as:',
          options: ['اسم صريح', 'اسم مؤول', 'فعل مضارع منصوب', 'جملة فعلية'],
          correct: 1,
        },
        {
          q: 'Which definition matches الفعل?',
          options: ['A meaning in itself, not tied to time', 'A meaning in itself, tied to time', 'A meaning that only appears in another word', 'A single meaningful utterance'],
          correct: 1,
        },
        {
          q: 'فَاء، عَيْن، لَام (the spelling letters) are examples of:',
          options: ['حروف المعاني', 'حروف المباني', 'حروف الجر', 'حروف المد واللين'],
          correct: 1,
        },
        {
          q: 'Why is رَجُلٌ called مفرد؟',
          options: ['Its parts indicate no meaning on their own', 'Its parts each indicate a meaning', 'It is built from two separate words', 'Its meaning carries no attachment to time'],
          correct: 0,
        },
      ],
      drills: [
        {
          title: 'اسم عين or اسم معنى؟',
          prompt: `عِلْمٌ cannot subsist by itself — it exists only through a knower. Given the classification taught (الموصوف → اسم عين / اسم معنى), how is عِلْمٌ classified?`,
          kind: 'mcq',
          options: ['اسم معنى, under الموصوف', 'اسم عين, under الموصوف', 'صفة, not موصوف', 'اسم مؤول'],
          correct: 0,
        },
        {
          title: 'The بِ in بِسْمِ اللَّهِ',
          prompt: `بِسْمِ اللَّهِ opens with the particle بِ. Considering the three-way division of الكلمة, what is بِ itself?`,
          kind: 'mcq',
          options: ['اسم, because it is مجرور by what precedes it', 'فعل, because it indicates an event in time', 'حرف, because its meaning appears only in what follows', 'اسم مؤول, because it stands in place of a مصدر'],
          correct: 2,
        },
        {
          title: 'حرف مد or حرف لين؟',
          prompt: `In ﴿الصَّادِقِينَ﴾, the ياء is ساكن after a matching كسرة. Is this the same kind of letter as the ياء in الْخَيْر?`,
          kind: 'mcq',
          options: ['حرف مد — the ياء of الخير is different, that one is حرف لين', 'حرف لين — the same as the ياء of الخير in every way', 'حرف مبنى — a spelling letter, unrelated to مد or لين', 'اسم معنى — a noun subsisting through another'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'مفرد or مركب؟',
          kind: 'mcq',
          prompt: 'Which of the following counts as two كلمات rather than one?',
          options: ['قَلَمٌ', 'بَيْتُ الطَّالِبِ', 'مُسْتَقِيمٌ', 'اسْتَغْفَرَ'],
          correct: 1,
        },
        {
          title: 'اسم مؤول',
          kind: 'mcq',
          prompt: 'In ﴿وَأَنْ تَصُومُوا خَيْرٌ﴾, أَنْ تَصُومُوا (equal to صَوْمُكُمْ) is:',
          options: ['اسم صريح', 'اسم مؤول', 'فعل مضارع منصوب', 'جملة فعلية'],
          correct: 1,
        },
        {
          title: 'Match term to example',
          kind: 'mcq',
          prompt: 'Which pair (term → example) is correct?',
          options: ['الفعل → عَبَدَ', 'الحرف → رَجُلٌ', 'الاسم → إِنَّ', 'اسم عين → عِلْمٌ'],
          correct: 0,
        },
        {
          title: 'حروف المعاني',
          kind: 'mcq',
          prompt: 'لَا (as in لَا تُشْرِكْ) belongs to which category of حرف?',
          options: ['حروف المباني', 'حروف المعاني', 'حروف المد', 'حروف اللين'],
          correct: 1,
        },
        {
          title: 'تركيب: خَرَجَ الرَّجُلُ مِنَ الْبَيْتِ',
          kind: 'tarkeeb',
          instruction: 'Label the word class of each word; then classify الرَّجُلُ as اسم عين or اسم معنى.',
          sentence: 'خَرَجَ الرَّجُلُ مِنَ الْبَيْتِ',
          translation: 'The man left the house.',
          cells: ['خَرَجَ', 'الرَّجُلُ', 'مِنَ', 'الْبَيْتِ'],
          rows: [
            { position: 'above', label: 'Word class', labels: [
              { start: 0, end: 0, role: 'فعل' },
              { start: 1, end: 1, role: 'اسم' },
              { start: 2, end: 2, role: 'حرف' },
              { start: 3, end: 3, role: 'اسم' },
            ] },
            { position: 'below', label: 'Meaning of الاسم', labels: [
              { start: 1, end: 1, role: 'اسم عين' },
            ] },
          ],
          distractors: ['اسم معنى', 'صفة'],
        },
        {
          title: 'تركيب: وَيَعْبُدُ الْمُؤْمِنُ رَبَّهُ',
          kind: 'tarkeeb',
          instruction: 'Label the word class of each word; then classify الْمُؤْمِنُ and رَبَّهُ as مفرد or مركب.',
          sentence: 'وَيَعْبُدُ الْمُؤْمِنُ رَبَّهُ',
          translation: 'And the believer worships his Lord.',
          cells: ['وَ', 'يَعْبُدُ', 'الْمُؤْمِنُ', 'رَبَّهُ'],
          rows: [
            { position: 'above', label: 'Word class', labels: [
              { start: 0, end: 0, role: 'حرف' },
              { start: 1, end: 1, role: 'فعل' },
              { start: 2, end: 2, role: 'اسم' },
              { start: 3, end: 3, role: 'اسم' },
            ] },
            { position: 'below', label: 'مفرد or مركب', labels: [
              { start: 2, end: 2, role: 'مفرد' },
              { start: 3, end: 3, role: 'مركب' },
            ] },
          ],
          distractors: ['اسم عين', 'اسم معنى'],
        },
        {
          title: 'Is a meaningless sound a لفظ؟',
          kind: 'mcq',
          prompt: 'A sound leaves the mouth carrying no meaning whatsoever. Is it still اللفظ?',
          options: ['Yes — اللفظ is every sound that exits the mouth', 'No — a لفظ must indicate some meaning to count', 'Only if the speaker intended a meaning by it', 'Only if it is a single, uncompounded sound'],
          correct: 0,
        },
        {
          title: 'From لفظ to قول',
          kind: 'mcq',
          prompt: 'What has to be added to اللفظ before it can be called القول?',
          options: ['That it be مركب', 'That it indicate a meaning', 'That it be tied to time', 'That it carry تنوين'],
          correct: 1,
        },
        {
          title: 'الكلمة in one phrase',
          kind: 'mcq',
          prompt: 'الكلمة is defined as:',
          options: ['قول مفرد', 'لفظ غير دال على معنى', 'قول مركب', 'كل صوت خرج من الفم'],
          correct: 0,
        },
        {
          title: 'Why قَلَمٌ is مفرد',
          kind: 'mcq',
          prompt: 'قَلَمٌ is مفرد. What makes it so?',
          options: ['Its letters ق، ل، م indicate no meaning individually', 'Its letters each indicate a meaning individually', 'Its meaning is tied to a particular time', 'Its letters are حروف مبانٍ, not حروف معانٍ'],
          correct: 0,
        },
        {
          title: 'How many كلمات؟',
          kind: 'mcq',
          prompt: 'كِتَابُ الْوَلَدِ — how many كلمات is it, and why?',
          options: ['One, because it names a single thing', 'Two, because each part indicates a meaning', 'One, because its parts mean nothing alone', 'Three, counting أل as a word of its own'],
          correct: 1,
        },
        {
          title: 'What makes an اسم مؤول',
          kind: 'mcq',
          prompt: 'An اسم مؤول is formed from:',
          options: ['A حرف مصدر together with the جملة after it', 'أل التعريف joined to the front of an اسم', 'A فعل together with its فاعل', 'Two أسماء joined to each other in إضافة'],
          correct: 0,
        },
        {
          title: 'موصوف or صفة؟',
          kind: 'mcq',
          prompt: 'Dividing الاسم by its meaning, which label does صَالِحٌ take?',
          options: ['الموصوف', 'الصفة', 'اسم عين', 'اسم معنى'],
          correct: 1,
        },
        {
          title: 'اسم عين',
          kind: 'mcq',
          prompt: 'Which one of these four أسماء is an اسم عين?',
          options: ['عِلْمٌ', 'رَجُلٌ', 'صَالِحٌ', 'الصَّوْمُ'],
          correct: 1,
        },
        {
          title: 'عِلْمٌ vs عَالِمٌ',
          kind: 'mcq',
          prompt: 'عِلْمٌ is an اسم معنى. What is عَالِمٌ, by contrast?',
          options: ['اسم عين', 'صفة', 'اسم معنى as well', 'موصوف'],
          correct: 1,
        },
        {
          title: 'What الفعل adds',
          kind: 'mcq',
          prompt: 'الاسم and الفعل share "indicating a meaning in itself". What does الفعل add on top of that?',
          options: ['Being linked to time', 'Carrying تنوين at its end', 'Indicating a meaning in something else', 'Indicating a meaning free of time'],
          correct: 0,
        },
        {
          title: 'الحرف defined',
          kind: 'mcq',
          prompt: 'الحرف indicates a meaning:',
          options: ['in itself, not tied to time', 'in itself, tied to time', 'in something other than itself', 'in itself, with or without time'],
          correct: 2,
        },
        {
          title: 'Two senses of حرف',
          kind: 'mcq',
          prompt: 'The word حرف is applied to two different things. Which pair names them?',
          options: ['حروف المباني and حروف المعاني', 'حروف المد and حروف اللين', 'حروف الجر and حروف النصب', 'حروف المضارعة and نونا التوكيد'],
          correct: 0,
        },
        {
          title: 'Why الصَّادِقِينَ has حرف مد',
          kind: 'mcq',
          prompt: 'In ﴿الصَّادِقِينَ﴾ the ياء is ساكن, preceded by a كسرة. Why does that make it حرف مد?',
          options: ['Because the vowel before it matches it', 'Because the vowel before it does not match it', 'Because it is ساكن, carrying no vowel itself', 'Because the ص before it carries a شدة'],
          correct: 0,
        },
        {
          title: 'The condition for حرف لين',
          kind: 'mcq',
          prompt: 'حرف اللين is a و or ي that is ساكن and preceded by:',
          options: ['a فتحة', 'a vowel of its own kind', 'a ضمة, when the letter is و', 'a كسرة, when the letter is ي'],
          correct: 0,
        },
        {
          title: 'تركيب: ﴿إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify الموصوف and each صفة describing it.',
          sentence: 'إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ',
          translation: 'Indeed, Allah is Forgiving, Merciful.',
          cells: ['إِنَّ', 'اللَّهَ', 'غَفُورٌ', 'رَحِيمٌ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'موصوف' },
              { start: 2, end: 2, role: 'صفة' },
              { start: 3, end: 3, role: 'صفة' },
            ] },
          ],
          distractors: ['مفرد', 'اسم مؤول'],
        },
        {
          title: 'تركيب: طَلَبَ الرَّجُلُ الصَّالِحُ الْعِلْمَ',
          kind: 'tarkeeb',
          instruction: 'Classify each اسم as اسم عين, صفة, or اسم معنى.',
          sentence: 'طَلَبَ الرَّجُلُ الصَّالِحُ الْعِلْمَ',
          translation: 'The righteous man sought knowledge.',
          cells: ['طَلَبَ', 'الرَّجُلُ', 'الصَّالِحُ', 'الْعِلْمَ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'اسم عين' },
              { start: 2, end: 2, role: 'صفة' },
              { start: 3, end: 3, role: 'اسم معنى' },
            ] },
          ],
          distractors: ['موصوف', 'مركب'],
        },
        {
          title: 'تركيب: قَرَأَ زَيْدٌ كِتَابَ الْوَلَدِ',
          kind: 'tarkeeb',
          instruction: 'Classify زَيْدٌ and كِتَابَ الْوَلَدِ as مفرد or مركب.',
          sentence: 'قَرَأَ زَيْدٌ كِتَابَ الْوَلَدِ',
          translation: 'Zayd read the boy’s book.',
          cells: ['قَرَأَ', 'زَيْدٌ', 'كِتَابَ', 'الْوَلَدِ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'مفرد' },
              { start: 2, end: 3, role: 'مركب' },
            ] },
          ],
          distractors: ['اسم عين', 'اسم معنى'],
        },
        {
          title: 'تركيب: قَالُوا هَذَا يَوْمُ الْخَيْرِ',
          kind: 'tarkeeb',
          instruction: 'Identify which word contains a حرف مد and which contains a حرف لين.',
          sentence: 'قَالُوا هَذَا يَوْمُ الْخَيْرِ',
          translation: 'They said, "This is the day of goodness."',
          cells: ['قَالُوا', 'هَذَا', 'يَوْمُ', 'الْخَيْرِ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'حرف مد' },
              { start: 2, end: 2, role: 'حرف لين' },
            ] },
          ],
          distractors: ['حرف مبنى', 'اسم مؤول'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'علامات الكلمة',
      subtitle: 'Signs of the Word — how to tell اسم, فعل, and حرف apart in practice',
      concepts: [
        {
          heading: 'علامات الاسم الست',
          lines: [
            { html: `Any ONE of six signs proves a word is اسم. Neither الفعل nor الحرف can ever show these signs — even where a جار seems to enter upon a فعل, it's really governing a hidden اسم مؤول, not the فعل itself (see the Clarification below).`, list: false },
            { table: { title: 'The Six Signs of الاسم', headers: ['#', 'Sign', 'Example'], rows: [
              ['1', 'مَجْرُور', '﴿بِسْمِ اللَّهِ﴾'],
              ['2', 'أَلْ التعريف', '﴿الرَّحْمَٰنِ الرَّحِيمِ﴾'],
              ['3', 'التَّنْوِين', '﴿هُدًى لِلْمُتَّقِينَ﴾'],
              ['4', 'مُسْنَدٌ إِلَيْهِ', '﴿إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ﴾'],
              ['5', 'مُنَادًى', '﴿يَا نُوحُ﴾'],
              ['6', 'مُضَاف', '﴿رَبِّ الْعَالَمِينَ﴾'],
            ] } },
          ],
          clarification: `What actually happens when a جار seems to precede a فعل, as in لِأَكُونَ لِلْعَالَمِينَ نَذِيرًا؟ It isn't governing أَكُونَ itself — أَنْ plus the جملة after it (أَنْ أَكُونَ) forms one اسم مؤول (a حرف مصدر + جملة acting as a single اسم, just like أَنْ تَصُومُوا). It's that اسم مؤول that's مجرور, never the bare فعل. So the rule holds without any real exception — only an اسم, whether صريح or مؤول, is ever مجرور.`,
          exercise: {
            prompt: `Three of these four are among the six signs of الاسم. Which one is not?`,
            kind: 'mcq',
            options: ['كونه مجرورًا', 'كونه منادى', 'كونه مضافًا', 'قبوله تاء التأنيث الساكنة'],
            correct: 3,
          },
        },
        {
          heading: 'علامتا الفعل العامتان، وعلامة الماضي',
          lines: [
            { html: `Every فعل shares two signs, no matter which type it is:`, list: false },
            { table: { headers: ['Sign', 'Example'], rows: [
              ['التَّصْرِيف — conjugating into ماضٍ / مضارع / أمر / نهي', 'عَبَدَ / يَعْبُدُ / اُعْبُدْ / لَا تَعْبُدْ'],
              ['قبول الضَّمَائِرُ الْبَارِزَةُ الْمَرْفُوعَة', 'آمَنْتُ، آمَنُوا'],
            ] } },
            { html: `الفعل الماضي alone also accepts a third sign: <bdi>تَاءُ التَّأْنِيثِ السَّاكِنَة</bdi>, as in ﴿آمَنَتْ﴾.`, list: false },
          ],
          exercise: {
            prompt: `Which class of الفعل does تاء التأنيث الساكنة, as in ﴿آمَنَتْ﴾, single out?`,
            kind: 'mcq',
            options: ['الماضي وحده', 'المضارع وحده', 'الأمر وحده', 'الماضي والمضارع معًا'],
            correct: 0,
          },
        },
        {
          heading: 'علامات المضارع الخاصة وحروف المضارعة',
          lines: [
            { html: `المضارع has three signs that belong to it alone:`, list: false },
            { html: `<bdi>لَمْ</bdi> and <bdi>لَنْ</bdi>`, list: true, bullet: true },
            { html: `<bdi>السِّين</bdi> and <bdi>سَوْفَ</bdi>`, list: true, bullet: true },
            { html: `the <bdi>نُونَا التَّوْكِيدِ</bdi>`, list: true, bullet: true },
            { html: `It's also recognized by opening with one of the <bdi>حُرُوفُ الْمُضَارَعَةِ</bdi> — <bdi>ن، أ، ي، ت</bdi>, remembered by the word <bdi>نَأَيْتُ</bdi>, as in <bdi>يُحْيِي وَيُمِيتُ</bdi>.`, list: false },
            { html: `<bdi>قَدْ</bdi>, by contrast, is not specific to المضارع — it's shared with الماضي.`, list: false },
          ],
          exercise: {
            prompt: `تُؤْمِنُونَ begins with a تاء. What is that تاء, and what does it establish?`,
            kind: 'mcq',
            options: ['حرف مضارعة — the word is a فعل مضارع', 'تاء التأنيث الساكنة — the word is a فعل ماضٍ', 'تاء الفاعل — the word is a فعل ماضٍ', 'حرف مبنى — it establishes nothing at all'],
            correct: 0,
          },
        },
        {
          heading: 'علامة الأمر، وكيف يُعرف الحرف',
          lines: [
            { html: `الأمر is known by indicating <bdi>طَلَب</bdi> while accepting <bdi>يَاءِ الْمُخَاطَبَةِ</bdi>, as in ﴿وَادْخُلِي جَنَّتِي﴾.`, list: false },
            { html: `الحرف has no positive sign of its own. It's recognized only by process of elimination — the absence of every sign of both الاسم and الفعل, as with <bdi>هَلْ</bdi> and <bdi>بَلْ</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `Only one of these four displays no sign of الاسم and no sign of الفعل. Which one is the حرف?`,
            kind: 'mcq',
            options: ['الْيَوْمَ', 'يَقُومُ', 'بَلْ', 'قَامَتْ'],
            correct: 2,
          },
        },
      ],
      quiz: [
        {
          q: 'Which sign of الاسم appears in ﴿يَا نُوحُ﴾?',
          options: ['التنوين', 'أل التعريف', 'كونه منادى', 'كونه مضافًا'],
          correct: 2,
        },
        {
          q: 'Can الفعل or الحرف ever be مجرور?',
          options: ['Yes — a جار makes whatever follows it مجرور', 'No — the مجرور is the اسم مؤول, not the فعل', 'Yes, but only after لام الجر specifically', 'Only الحرف can, since it bears no إعراب'],
          correct: 1,
        },
        {
          q: 'What two signs are shared by every فعل regardless of tense?',
          options: ['التصريف, and accepting الضمائر البارزة المرفوعة', 'الدلالة على الطلب, and accepting ياء المخاطبة', 'قبول لَمْ, and accepting السين وسوف', 'قبول أل التعريف, and accepting التنوين'],
          correct: 0,
        },
        {
          q: 'Three of these four open with a حرف مضارعة. Which one does not?',
          options: ['يُحْيِي', 'تَعْبُدُونَ', 'اسْتَغْفَرَ', 'نَعْبُدُ'],
          correct: 2,
        },
        {
          q: 'قَدْ is a sign shared between which two classes?',
          options: ['الماضي and المضارع', 'المضارع and الأمر', 'الماضي and الأمر', 'الأمر and النهي'],
          correct: 0,
        },
        {
          q: 'How is الحرف recognized?',
          options: ['By accepting ياء المخاطبة after a طلب', 'By carrying التنوين at its end', 'By the absence of every sign of الاسم or الفعل', 'By التصريف into ماضٍ, مضارع and أمر'],
          correct: 2,
        },
      ],
      drills: [
        {
          title: '﴿يَا لَيْتَ قَوْمِي يَعْلَمُونَ﴾',
          prompt: `يَا here precedes لَيْتَ, not a منادى. Does a حرف نداء like يَا always prove sign (5), كونه منادى, is present?`,
          kind: 'mcq',
          options: ['Yes — a حرف نداء always marks a منادى', 'No — يَا can precede something other than a منادى', 'يَا here is itself an اسم, not a حرف', 'يَا here is a فعل أمر with a hidden فاعل'],
          correct: 1,
        },
        {
          title: '﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾',
          prompt: `These verbs end with a نون التوكيد. Which class of الفعل does that sign point to?`,
          kind: 'mcq',
          options: ['الماضي', 'المضارع', 'الأمر only', 'every class of فعل'],
          correct: 1,
        },
        {
          title: 'Testing هَلْ and بَلْ',
          prompt: `Neither هَلْ nor بَلْ can be conjugated, take subject pronouns, أل, تنوين, or مجرور. What does that total absence prove?`,
          kind: 'mcq',
          options: ['They are نكرة أسماء', 'They are جامد أفعال', 'They are حروف', "They can't be classified"],
          correct: 2,
        },
      ],
      bank: [
        {
          title: 'Sign in ﴿رَبِّ الْعَالَمِينَ﴾',
          kind: 'mcq',
          prompt: 'Which sign of الاسم does رَبِّ display in ﴿رَبِّ الْعَالَمِينَ﴾?',
          options: ['التنوين', 'كونه مضافًا', 'كونه منادى', 'أل التعريف'],
          correct: 1,
        },
        {
          title: 'تاء التأنيث الساكنة',
          kind: 'mcq',
          prompt: '﴿آمَنَتْ﴾ accepts تاء التأنيث الساكنة. Can المضارع accept it too?',
          options: ['Yes — it is shared by both, like قَدْ', 'No — it belongs to الماضي alone', 'Yes, but only when the مضارع is مجزوم', 'No — it belongs to الأمر alone'],
          correct: 1,
        },
        {
          title: 'قَدْ in two places',
          kind: 'mcq',
          prompt: '﴿لَقَدْ سَمِعَ اللَّهُ﴾ and ﴿قَدْ يَعْلَمُ اللَّهُ﴾ — what does قَدْ prove in both?',
          options: ['قَدْ is a sign of الاسم, so both are أسماء', 'قَدْ is shared by الماضي and المضارع, so both are فعل', 'قَدْ is specific to الماضي, so both are ماضٍ', 'قَدْ is specific to المضارع, so both are مضارع'],
          correct: 1,
        },
        {
          title: 'حروف المضارعة in يَعْبُدُ',
          kind: 'mcq',
          prompt: 'يَعْبُدُ and يَاسِرٌ both open with a ي. Which observation shows that only the first is a فعل مضارع?',
          options: ['يَاسِرٌ carries التنوين, a sign of الاسم', 'يَعْبُدُ carries التنوين, a sign of الفعل', 'يَاسِرٌ accepts لَمْ, a sign of الاسم', 'يَعْبُدُ accepts أل, a sign of الفعل'],
          correct: 0,
        },
        {
          title: 'تركيب: ﴿إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ أَوَّاهٌ مُنِيبٌ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify the sign of الاسم each اسم displays.',
          sentence: 'إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ أَوَّاهٌ مُنِيبٌ',
          translation: 'Indeed, Abraham was truly forbearing, imploring, penitent.',
          cells: ['إِنَّ', 'إِبْرَاهِيمَ', 'حَلِيمٌ', 'أَوَّاهٌ', 'مُنِيبٌ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'مسند إليه' },
              { start: 2, end: 2, role: 'التنوين' },
              { start: 3, end: 3, role: 'التنوين' },
              { start: 4, end: 4, role: 'التنوين' },
            ] },
          ],
          distractors: ['مجرور', 'منادى'],
        },
        {
          title: 'تركيب: ﴿أُولَٰئِكَ سَيَرْحَمُهُمُ اللَّهُ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify the sign of المضارع the verb displays.',
          sentence: 'أُولَٰئِكَ سَيَرْحَمُهُمُ اللَّهُ',
          translation: 'Those — Allah will have mercy upon them.',
          cells: ['أُولَٰئِكَ', 'سَيَرْحَمُهُمُ', 'اللَّهُ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'السين' },
            ] },
          ],
          distractors: ['سوف', 'لن'],
        },
        {
          title: 'تركيب: ﴿سَوْفَ أَسْتَغْفِرُ لَكُمْ رَبِّي﴾',
          kind: 'tarkeeb',
          instruction: 'Which sign of المضارع does the verb display here?',
          sentence: 'سَوْفَ أَسْتَغْفِرُ لَكُمْ رَبِّي',
          translation: '[Yaqub] said, "I will ask my Lord to forgive you."',
          cells: ['سَوْفَ', 'أَسْتَغْفِرُ', 'لَكُمْ', 'رَبِّي'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'سوف' },
            ] },
          ],
          distractors: ['السين', 'لن'],
        },
        {
          title: 'Sign in ﴿بِسْمِ اللَّهِ﴾',
          kind: 'mcq',
          prompt: 'Which sign of الاسم does اسم display in ﴿بِسْمِ اللَّهِ﴾?',
          options: ['كونه مجرورًا', 'التنوين', 'كونه منادى', 'أل التعريف'],
          correct: 0,
        },
        {
          title: 'Sign in ﴿الرَّحْمَٰنِ الرَّحِيمِ﴾',
          kind: 'mcq',
          prompt: 'Which sign of الاسم do الرَّحْمَٰنِ and الرَّحِيمِ display?',
          options: ['التنوين', 'أل التعريف', 'كونه مضافًا', 'كونه منادى'],
          correct: 1,
        },
        {
          title: 'Sign in ﴿يَا نُوحُ﴾',
          kind: 'mcq',
          prompt: 'Which sign of الاسم does نُوحُ display in ﴿يَا نُوحُ﴾?',
          options: ['التنوين', 'كونه مضافًا', 'كونه منادى', 'كونه مجرورًا'],
          correct: 2,
        },
        {
          title: 'Sign in ﴿إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ﴾',
          kind: 'mcq',
          prompt: 'إِبْرَاهِيمَ is the one being spoken about here. Which sign of الاسم does that show?',
          options: ['كونه منونًا بالتنوين', 'كونه مسندًا إليه', 'كونه منادى بحرف نداء', 'كونه معرفًا بأل'],
          correct: 1,
        },
        {
          title: 'Can a فعل be مجرور؟',
          kind: 'mcq',
          prompt: 'In ﴿لِأَكُونَ لِلْعَالَمِينَ نَذِيرًا﴾ a جار enters upon أَكُونَ. Is the فعل itself مجرور?',
          options: ['Yes — a جار makes whatever follows it مجرور', 'No — the مجرور is the اسم مؤول, not the فعل', 'Yes, but only when the جار is the لام', 'Only when the فعل is مضارع, not ماضٍ'],
          correct: 1,
        },
        {
          title: 'يَا before something that is not a منادى',
          kind: 'mcq',
          prompt: 'In ﴿يَا لَيْتَ قَوْمِي يَعْلَمُونَ﴾, يا comes before لَيْتَ. What does that establish?',
          options: ['لَيْتَ is itself the منادى here', 'حروف النداء may enter upon what is not a منادى', 'قَوْمِي, further along, is the real منادى', 'يَا is a sign of الفعل here, not of الاسم'],
          correct: 1,
        },
        {
          title: 'The two general signs of الفعل',
          kind: 'mcq',
          prompt: 'Which pair are the two signs shared by every فعل?',
          options: ['التصريف, and accepting الضمائر البارزة المرفوعة', 'قبول لَمْ, and accepting نونا التوكيد', 'الدلالة على الطلب, and accepting ياء المخاطبة', 'قبول أل التعريف, and accepting التنوين'],
          correct: 0,
        },
        {
          title: 'التصريف as a sign',
          kind: 'mcq',
          prompt: 'A word can be conjugated into ماضٍ, مضارع, أمر and نهي. Which sign is that, and what does it prove?',
          options: ['التصريف — it is a فعل', 'التنوين — it is an اسم', 'الإسناد — it is a مسند إليه', 'التعريف — it is an اسم'],
          correct: 0,
        },
        {
          title: 'الضمائر البارزة المرفوعة',
          kind: 'mcq',
          prompt: 'آمَنْتُ and آمَنُوا carry attached subject pronouns. Which sign is that, and what does it prove?',
          options: ['الضمائر البارزة المرفوعة — they are أفعال', 'تاء التأنيث الساكنة — they are أفعال ماضية', 'حروف المضارعة — they are أفعال مضارعة', 'كونه مسندًا إليه — they are أسماء'],
          correct: 0,
        },
        {
          title: 'لَمْ and لَنْ',
          kind: 'mcq',
          prompt: '﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾ and ﴿لَنْ يُصِيبَنَا﴾ — لم and لن are signs specific to:',
          options: ['الفعل الماضي', 'الفعل المضارع', 'الفعل الأمر', 'الماضي والمضارع معًا'],
          correct: 1,
        },
        {
          title: 'نُونَا التَّوْكِيدِ',
          kind: 'mcq',
          prompt: 'In ﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾, the نونا التوكيد are a sign specific to:',
          options: ['الماضي', 'المضارع', 'الأمر', 'الماضي والمضارع معًا'],
          correct: 1,
        },
        {
          title: 'علامة الأمر',
          kind: 'mcq',
          prompt: '﴿وَادْخُلِي جَنَّتِي﴾ — which two things together mark فعل الأمر?',
          options: ['Indicating طلب, and accepting ياء المخاطبة', 'Carrying أل التعريف, and accepting التنوين', 'Accepting قَدْ, and accepting السين', 'Accepting لَمْ, and accepting لَنْ'],
          correct: 0,
        },
        {
          title: 'How الحرف is recognised',
          kind: 'mcq',
          prompt: 'هَلْ and بَلْ carry no sign of الاسم and no sign of الفعل. How is a حرف known?',
          options: ['By a positive sign belonging to it alone', 'By the absence of every sign of الاسم and الفعل', 'By carrying تنوين at the end of the word', 'By التصريف into ماضٍ, مضارع and أمر'],
          correct: 1,
        },
        {
          title: 'تركيب: ﴿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify one sign of الاسم each word displays.',
          sentence: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
          translation: 'In the name of Allah, the Most Gracious, the Most Merciful.',
          cells: ['بِسْمِ', 'اللَّهِ', 'الرَّحْمَٰنِ', 'الرَّحِيمِ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'مضاف' },
              { start: 1, end: 1, role: 'مجرور' },
              { start: 2, end: 2, role: 'أل التعريف' },
              { start: 3, end: 3, role: 'أل التعريف' },
            ] },
          ],
          distractors: ['مسند إليه', 'منادى', 'التنوين'],
        },
        {
          title: 'تركيب: هَلْ آمَنَتِ الْمَرْأَةُ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each word by its signs; then name the specific sign that proves آمَنَتِ and الْمَرْأَةُ.',
          sentence: 'هَلْ آمَنَتِ الْمَرْأَةُ؟',
          translation: 'Has the woman believed?',
          cells: ['هَلْ', 'آمَنَتِ', 'الْمَرْأَةُ'],
          rows: [
            { position: 'above', label: 'Word class', labels: [
              { start: 0, end: 0, role: 'حرف' },
              { start: 1, end: 1, role: 'فعل' },
              { start: 2, end: 2, role: 'اسم' },
            ] },
            { position: 'below', label: 'Sign proving it', labels: [
              { start: 1, end: 1, role: 'تاء التأنيث الساكنة' },
              { start: 2, end: 2, role: 'أل التعريف' },
            ] },
          ],
          distractors: ['منادى', 'مسند إليه'],
        },
        {
          title: 'تركيب: نَحْنُ نَذْهَبُ وَهُوَ يَذْهَبُ وَأَنَا أَذْهَبُ وَأَنْتَ تَذْهَبُ',
          kind: 'tarkeeb',
          instruction: 'Identify the حرف مضارعة that opens each verb.',
          sentence: 'نَحْنُ نَذْهَبُ وَهُوَ يَذْهَبُ وَأَنَا أَذْهَبُ وَأَنْتَ تَذْهَبُ',
          translation: 'We go, and he goes, and I go, and you go.',
          cells: ['نَحْنُ', 'نَذْهَبُ', 'وَ', 'هُوَ', 'يَذْهَبُ', 'وَ', 'أَنَا', 'أَذْهَبُ', 'وَ', 'أَنْتَ', 'تَذْهَبُ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 1, role: 'ن' },
              { start: 4, end: 4, role: 'ي' },
              { start: 7, end: 7, role: 'أ' },
              { start: 10, end: 10, role: 'ت' },
            ] },
          ],
          distractors: ['س', 'و'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الجملة والكلام',
      subtitle: 'The Sentence and Speech — from a bare predication to a complete, useful utterance',
      concepts: [
        {
          heading: 'تعريف الجملة: المسند والمسند إليه',
          lines: [
            { html: `الجملة is built from two parts: a <bdi>مُسْنَد</bdi> and a <bdi>مُسْنَدٌ إِلَيْهِ</bdi>.`, list: false },
            { html: `<bdi>الْمُسْنَدُ إِلَيْهِ</bdi> (= مبتدأ or فاعل) is what's spoken about — also called <bdi>الْمَحْكُومُ عَلَيْهِ</bdi>.`, list: false },
            { html: `<bdi>الْمُسْنَد</bdi> (= خبر or فعل) is what's said about it — also called <bdi>الْمَحْكُومُ بِهِ</bdi>.`, list: false },
            { tarkeebDiagram: { sentence: 'اللَّهُ غَفُورٌ', translation: 'Allah is Forgiving.', cells: ['اللَّهُ', 'غَفُورٌ'], rows: [
              { position: 'above', labels: [ { start: 0, end: 0, role: 'مسند إليه' }, { start: 1, end: 1, role: 'مسند' } ] },
            ] } },
            { html: `Together المسند and المسند إليه are called <bdi>عُمْدَة</bdi> — the جملة can't stand without them. Everything else added on top, like the five مفاعيل, is <bdi>فَضْلَة</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `Which pair of labels belongs to the five مفاعيل, as against the two the جملة cannot do without?`,
            kind: 'mcq',
            options: ['الفضلة والقيد', 'العمدة والركن', 'المسند والمسند إليه', 'المحكوم عليه والمحكوم به'],
            correct: 0,
          },
        },
        {
          heading: 'اسمية أو فعلية',
          lines: [
            { html: `By form, a جملة is either <bdi>اسْمِيَّة</bdi> (starts with اسم) or <bdi>فِعْلِيَّة</bdi> (starts with فعل).`, list: false },
            { table: { headers: ['Type', 'Condition', 'Example'], rows: [
              ['اسمية غير منسوخة', 'starts with اسم, no ناسخ', '﴿وَاللَّهُ غَفُورٌ رَحِيمٌ﴾'],
              ['اسمية منسوخة', 'starts with اسم, after a ناسخ', '﴿إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ﴾'],
              ['فعلية', 'starts with فعل', '﴿وَخَلَقَ كُلَّ شَيْءٍ﴾'],
            ] } },
            { html: `A ناسخ or a fronted فضلة never changes this classification: ﴿إِيَّاكَ نَعْبُدُ﴾ is فعلية, because إِيَّاكَ is a فضلة (الأصل: نَعْبُدُ إِيَّاكَ) — classification goes by original word order, not by whatever visibly stands first.`, list: false },
          ],
          clarification: `How can إِيَّاكَ نَعْبُدُ be فعلية when إِيَّاكَ visibly stands first؟ Classification goes by the sentence's original word order before a فضلة gets fronted for emphasis — not by whatever happens to stand first on the surface. Undo the fronting and the أصل is نَعْبُدُ إِيَّاكَ: a فعل standing first, with إِيَّاكَ (the فضلة, here the مفعول به) simply moved ahead of it for emphasis.`,
          exercise: {
            prompt: `Classifying a جملة by form goes by what stands first — but one thing standing first is passed over. What is it?`,
            kind: 'mcq',
            options: ['A fronted فضلة, such as a مفعول به', 'A ناسخ entering upon the جملة', 'The مسند, when it happens to be a فعل', 'The مسند إليه, when it is a ضمير'],
            correct: 0,
          },
        },
        {
          heading: 'الجملة الشرطية: فعلية دائمًا',
          lines: [
            { html: `Only أفعال occur right after <bdi>أَدَاةُ الشَّرْطِ</bdi>, so <bdi>الْجُمْلَةُ الشَّرْطِيَّة</bdi> is always فعلية.`, list: false },
            { html: `﴿إِنْ تُخْفُوا مَا فِي صُدُورِكُمْ أَوْ تُبْدُوهُ يَعْلَمْهُ اللَّهُ﴾ — a فعل sits right after إِنْ.`, list: true, bullet: true },
            { html: `﴿وَإِنْ أَحَدٌ مِنَ الْمُشْرِكِينَ اسْتَجَارَكَ﴾ — أَحَدٌ looks like it comes first, but a فعل is implied before it: التقدير هو وَإِنِ اسْتَجَارَكَ أَحَدٌ.`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `Why is الجملة الشرطية always فعلية, even when an اسم appears to sit right after the شرط particle?`,
            kind: 'mcq',
            options: [
              'Because only أفعال can occur right after the أداة الشرط',
              'Because the أداة الشرط is itself an اسم, not a حرف',
              'Because a جملة شرطية has no مسند إليه in it',
              'Because the جواب الشرط can only ever be an اسم',
            ],
            correct: 0,
          },
        },
        {
          heading: 'خبرية أو إنشائية، وأنواع الإنشاء',
          lines: [
            { html: `By meaning, a جملة is <bdi>خَبَرِيَّة</bdi> (its speaker can be truthful or lying, e.g. ﴿إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ﴾) or <bdi>إِنْشَائِيَّة</bdi> (it cannot).`, list: false },
            { html: `الإنشاء has eleven types:`, list: false },
            { table: { headers: ['Type', 'Example'], rows: [
              ['الِاسْتِفْهَام', '—'],
              ['التَّمَنِّي', '﴿يَا لَيْتَ قَوْمِي يَعْلَمُونَ﴾'],
              ['النِّدَاء', '—'],
              ['التَّحْذِير', 'نَاقَةَ اللَّهِ وَسُقْيَاهَا'],
              ['الْإِغْرَاء', 'الْعِلْمَ الْعِلْمَ'],
              ['الْأَمْر', '—'],
              ['النَّهْي', '—'],
              ['الدُّعَاء', '—'],
              ['صيغ المدح والذم', '—'],
              ['صيغ التوجع والتفجع', '﴿يَا حَسْرَتَىٰ عَلَىٰ مَا فَرَّطْتُ فِي جَنْبِ اللَّهِ﴾'],
              ['الْقَسَم', '﴿وَالْعَصْرِ﴾'],
            ] } },
          ],
          exercise: {
            prompt: `﴿سَلَامٌ عَلَيْكُمْ﴾, said in greeting someone, is which of the eleven types of الجملة الإنشائية?`,
            kind: 'mcq',
            options: ['الدعاء', 'النداء', 'الإغراء', 'التمني'],
            correct: 0,
          },
        },
        {
          heading: 'خبر بلفظ إنشاء وعكسه؛ الكبرى والصغرى',
          lines: [
            { html: `Form and meaning can split apart:`, list: false },
            { table: { headers: ['Case', 'Example'], rows: [
              ['خبر in wording, إنشاء in meaning', '﴿الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ﴾'],
              ['إنشاء in wording, خبر in meaning (= سَيَتَبَوَّأُ)', '«مَنْ كَذَبَ عَلَيَّ مُتَعَمِّدًا فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ»'],
            ] } },
            { html: `Separately: a جملة containing another جملة is called <bdi>كُبْرَى</bdi>; the جملة inside it, sitting in the position of a مفرد, is <bdi>صُغْرَى</bdi>.`, list: false },
            { tarkeebDiagram: { sentence: 'وَاللَّهُ يَعْلَمُ', translation: 'And Allah knows.', cells: ['اللَّهُ', 'يَعْلَمُ'], rows: [
              { position: 'above', labels: [ { start: 0, end: 1, role: 'الكل = جملة كبرى' } ] },
              { position: 'below', labels: [ { start: 1, end: 1, role: 'يَعْلَمُ = جملة صغرى (خبر)' } ] },
            ] } },
          ],
          clarification: `What does "sitting in the position of a مفرد" mean? It means the inner جملة is doing the job a single word would normally do in that slot. In ﴿وَاللَّهُ يَعْلَمُ﴾, the خبر of اللَّه would normally be one word — here a whole جملة, يَعْلَمُ, fills that خبر slot instead. So الكل (the whole thing) is كُبْرَى, and يَعْلَمُ is صُغْرَى, sitting where a مفرد خبر would otherwise sit.`,
          exercise: {
            prompt: `﴿وَاللَّهُ يَعْلَمُ﴾ holds one جملة inside another. Which label goes to which?`,
            kind: 'mcq',
            options: ['الكل كبرى، ويَعْلَمُ صغرى', 'الكل صغرى، ويَعْلَمُ كبرى', 'الكل عمدة، ويَعْلَمُ فضلة', 'الكل خبرية، ويَعْلَمُ إنشائية'],
            correct: 0,
          },
        },
        {
          heading: 'الكلام: المفيد، وموجب/غير موجب',
          lines: [
            { html: `الكلام is <bdi>قَوْلٌ مُفِيد</bdi> — a meaningful utterance complete enough to stop at. Every كلام is جملة, but not every جملة is كلام.`, list: false },
            { table: { headers: ['Case', 'Example'], rows: [
              ['مفيد (يحسن السكوت عليه)', 'صَدَقْتَ'],
              ['غير مفيد (ناقص، معلَّق بجوابه)', 'إِنْ تَصْدُقْ'],
            ] } },
            { html: `الكلام is also <bdi>مُوجَب</bdi> (contains no نفي, نهي, or استفهام) or <bdi>غَيْرُ مُوجَب</bdi> (contains one of them).`, list: false },
            { table: { headers: ['Type', 'Example'], rows: [
              ['موجب', '﴿اُعْبُدِ اللَّهَ الَّذِي يَتَوَفَّاكُمْ﴾'],
              ['غير موجب (نفي)', '﴿فَلَا أَعْبُدُ الَّذِينَ تَعْبُدُونَ مِنْ دُونِ اللَّهِ﴾'],
              ['غير موجب (نهي)', '﴿لَا تُشْرِكْ بِاللَّهِ﴾'],
              ['غير موجب (استفهام)', '﴿أَأَتَّخِذُ مِنْ دُونِهِ آلِهَةً﴾'],
            ] } },
          ],
          exercise: {
            prompt: `Only one of these four is كلام موجب. Which one?`,
            kind: 'mcq',
            options: ['﴿لَا تُشْرِكْ بِاللَّهِ﴾', '﴿مَا هَٰذَا بَشَرًا﴾', '﴿اُعْبُدِ اللَّهَ﴾', '﴿أَأَتَّخِذُ مِنْ دُونِهِ آلِهَةً﴾'],
            correct: 2,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the definition of الجملة?',
          options: ['That which contains a مسند and a مسند إليه', 'Any قول مفيد fit to be stopped at', 'Any لفظ that indicates a meaning', 'Any قول composed of two كلمتين'],
          correct: 0,
        },
        {
          q: 'Is ﴿إِيَّاكَ نَعْبُدُ﴾ اسمية or فعلية, and why?',
          options: ['اسمية, because it opens with the اسم إِيَّاكَ', 'فعلية, because the fronted إِيَّاكَ is a فضلة', 'اسمية منسوخة, because a ناسخ governs it', 'فعلية, because نَعْبُدُ is the مسند إليه'],
          correct: 1,
        },
        {
          q: 'Why is الجملة الشرطية always فعلية?',
          options: ['Because أداة الشرط is itself an اسم', 'Because only أفعال occur after أداة الشرط', 'Because it never contains a مسند إليه', 'Because its جواب is always an اسم'],
          correct: 1,
        },
        {
          q: 'الجملة الإنشائية is defined as:',
          options: ['One whose speaker may be truthful or lying', 'One whose speaker can be neither truthful nor lying', 'One that contains a مسند and a مسند إليه', 'One that begins with a فعل rather than an اسم'],
          correct: 1,
        },
        {
          q: '«مَنْ كَذَبَ عَلَيَّ...فَلْيَتَبَوَّأْ» is أمر in wording — but in meaning it is:',
          options: ['إنشاء — a real command', 'خبر — the report سَيَتَبَوَّأُ', 'استفهام — a question in form', 'قسم — an oath in form'],
          correct: 1,
        },
        {
          q: 'Every كلام is جملة, but not every جملة is كلام. Why?',
          options: ['كلام requires الإفادة; a جملة need not have it', 'جملة requires الإفادة; a كلام need not have it', 'كلام is always اسمية; a جملة may be فعلية', 'كلام is one جملة; a جملة may be several'],
          correct: 0,
        },
      ],
      drills: [
        {
          title: '﴿مَا هَٰذَا بَشَرًا﴾',
          prompt: `A ناسخ has entered here, but the جملة still opens with an اسم (هَذَا). What is it classified as by form?`,
          kind: 'mcq',
          options: ['اسمية منسوخة', 'فعلية', 'cannot be classified', 'اسمية غير منسوخة, since a ناسخ doesn’t change form-classification'],
          correct: 0,
        },
        {
          title: 'A صغرى with no إفادة',
          prompt: `يَعْلَمُ in ﴿وَاللَّهُ يَعْلَمُ﴾ is a جملة صغرى in the position of الخبر. Can it stand alone as كلام?`,
          kind: 'mcq',
          options: ['Yes — every جملة counts as كلام', 'No — كلام needs الإفادة, which this lacks', 'Yes, because it is a complete فعلية', 'No, because it is not a جملة at all'],
          correct: 1,
        },
        {
          title: 'موجب or غير موجب؟',
          prompt: `﴿أَأَتَّخِذُ مِنْ دُونِهِ آلِهَةً﴾ contains استفهام. Classify this كلام.`,
          kind: 'mcq',
          options: ['موجب', 'غير موجب', 'إنشائي لا خبري', 'خبري لا إنشائي'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: "المسند إليه's other name",
          kind: 'mcq',
          prompt: 'المسند إليه is also called:',
          options: ['المحكوم به', 'المحكوم عليه', 'الفضلة', 'القيد'],
          correct: 1,
        },
        {
          title: 'اسمية despite the ناسخ',
          kind: 'mcq',
          prompt: '﴿وَكَانَ اللَّهُ عَلِيمًا حَكِيمًا﴾ — classify by form.',
          options: ['اسمية منسوخة', 'اسمية غير منسوخة', 'فعلية', 'شرطية'],
          correct: 0,
        },
        {
          title: 'Types of الإنشاء',
          kind: 'mcq',
          prompt: 'الْعِلْمَ الْعِلْمَ (meaning: hold fast to العلم) is which type of إنشاء?',
          options: ['التمني', 'التحذير', 'الإغراء', 'القسم'],
          correct: 2,
        },
        {
          title: 'المفيد',
          kind: 'mcq',
          prompt: 'إِنْ تَصْدُقْ alone (with no جواب) is not كلام because it is:',
          options: ['Not a جملة at all, merely two words', 'غير مفيد — silence upon it is improper', 'إنشائية rather than خبرية in meaning', 'فعلية rather than اسمية in form'],
          correct: 1,
        },
        {
          title: 'تركيب: ﴿إِيَّاكَ نَعْبُدُ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify إِيَّاكَ and نَعْبُدُ as عمدة or فضلة; then classify the whole جملة by form; then by meaning.',
          sentence: 'إِيَّاكَ نَعْبُدُ',
          translation: 'You alone we worship.',
          cells: ['إِيَّاكَ', 'نَعْبُدُ'],
          rows: [
            { position: 'above', label: 'عمدة or فضلة', labels: [
              { start: 0, end: 0, role: 'فضلة' },
              { start: 1, end: 1, role: 'عمدة' },
            ] },
            { position: 'below', label: 'Form', labels: [
              { start: 0, end: 1, role: 'فعلية' },
            ] },
            { position: 'below', label: 'Meaning', labels: [
              { start: 0, end: 1, role: 'خبرية' },
            ] },
          ],
          distractors: ['اسمية غير منسوخة', 'إنشائية'],
        },
        {
          title: 'تركيب: ﴿وَاللَّهُ غَفُورٌ رَحِيمٌ﴾',
          kind: 'tarkeeb',
          instruction: 'Label المسند and المسند إليه; then classify the whole جملة by form.',
          sentence: 'وَاللَّهُ غَفُورٌ رَحِيمٌ',
          translation: 'And Allah is Forgiving, Merciful.',
          cells: ['اللَّهُ', 'غَفُورٌ', 'رَحِيمٌ'],
          rows: [
            { position: 'above', label: 'المسند / المسند إليه', labels: [
              { start: 0, end: 0, role: 'مسند إليه' },
              { start: 1, end: 2, role: 'مسند' },
            ] },
            { position: 'below', label: 'Form', labels: [
              { start: 0, end: 2, role: 'اسمية غير منسوخة' },
            ] },
          ],
          distractors: ['اسمية منسوخة', 'فعلية'],
        },
        {
          title: 'تركيب: ﴿وَخَلَقَ كُلَّ شَيْءٍ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify the whole جملة by form.',
          sentence: 'وَخَلَقَ كُلَّ شَيْءٍ',
          translation: 'And He created all things.',
          cells: ['خَلَقَ', 'كُلَّ', 'شَيْءٍ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 2, role: 'فعلية' },
            ] },
          ],
          distractors: ['اسمية غير منسوخة', 'اسمية منسوخة'],
        },
        {
          title: 'تركيب: ﴿يَا لَيْتَ قَوْمِي يَعْلَمُونَ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which type of الإنشاء this whole جملة represents.',
          sentence: 'يَا لَيْتَ قَوْمِي يَعْلَمُونَ',
          translation: 'If only my people knew!',
          cells: ['يَا', 'لَيْتَ', 'قَوْمِي', 'يَعْلَمُونَ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 3, role: 'التمني' },
            ] },
          ],
          distractors: ['الاستفهام', 'النداء'],
        },
        {
          title: 'تركيب: ﴿وَالْعَصْرِ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which type of الإنشاء this represents.',
          sentence: 'وَالْعَصْرِ',
          translation: 'By Time.',
          cells: ['وَ', 'الْعَصْرِ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 1, role: 'القسم' },
            ] },
          ],
          distractors: ['التمني', 'الدعاء'],
        },
        {
          title: 'تركيب: ﴿أَأَتَّخِذُ مِنْ دُونِهِ آلِهَةً﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which type of الإنشاء this represents.',
          sentence: 'أَأَتَّخِذُ مِنْ دُونِهِ آلِهَةً',
          translation: 'Should I take gods besides Him?',
          cells: ['أَأَتَّخِذُ', 'مِنْ', 'دُونِهِ', 'آلِهَةً'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 3, role: 'الاستفهام' },
            ] },
          ],
          distractors: ['التمني', 'القسم'],
        },
        {
          title: 'تركيب: الْعِلْمَ الْعِلْمَ',
          kind: 'tarkeeb',
          instruction: 'Identify which type of الإنشاء this represents.',
          sentence: 'الْعِلْمَ الْعِلْمَ',
          translation: '[Hold fast to] knowledge, knowledge!',
          cells: ['الْعِلْمَ', 'الْعِلْمَ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 1, role: 'الإغراء' },
            ] },
          ],
          distractors: ['التحذير', 'النداء'],
        },
        {
          title: 'Definition of الجملة',
          kind: 'mcq',
          prompt: 'الجملة is defined as:',
          options: ['That which contains a مسند and a مسند إليه', 'Any قول مفيد fit to be stopped at', 'Any مركب built from two كلمات', 'Any لفظ that indicates a meaning'],
          correct: 0,
        },
        {
          title: "المسند's other name",
          kind: 'mcq',
          prompt: 'The مسند — the خبر or the فعل — is also called:',
          options: ['المحكوم عليه', 'المحكوم به', 'الفضلة', 'القيد'],
          correct: 1,
        },
        {
          title: 'عمدة and فضلة',
          kind: 'mcq',
          prompt: 'The five مفاعيل, in relation to the جملة, are:',
          options: ['العمدة', 'الفضلة', 'المسند', 'المسند إليه'],
          correct: 1,
        },
        {
          title: 'اسمية غير منسوخة',
          kind: 'mcq',
          prompt: '﴿وَاللَّهُ غَفُورٌ رَحِيمٌ﴾ — classify it by form.',
          options: ['اسمية غير منسوخة', 'اسمية منسوخة', 'فعلية', 'شرطية'],
          correct: 0,
        },
        {
          title: '﴿إِيَّاكَ نَعْبُدُ﴾',
          kind: 'mcq',
          prompt: 'Why is ﴿إِيَّاكَ نَعْبُدُ﴾ classified فعلية rather than اسمية?',
          options: ['Because it opens with the اسم إِيَّاكَ', 'Because the fronted إِيَّاكَ is only a فضلة', 'Because إِيَّاكَ is itself a kind of فعل', 'Because نَعْبُدُ is the مسند إليه here'],
          correct: 1,
        },
        {
          title: '﴿مَا هَٰذَا بَشَرًا﴾',
          kind: 'mcq',
          prompt: 'Classify ﴿مَا هَٰذَا بَشَرًا﴾ by form.',
          options: ['فعلية', 'اسمية', 'اسمية منسوخة', 'شرطية'],
          correct: 1,
        },
        {
          title: 'Why الشرطية is always فعلية',
          kind: 'mcq',
          prompt: 'الجملة الشرطية is always classified فعلية because:',
          options: ['Only أفعال occur after the أداة الشرط', 'أداة الشرط is itself an اسم', 'It always lacks a مسند إليه', 'جواب الشرط is always اسمي'],
          correct: 0,
        },
        {
          title: 'An اسم right after إِنْ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ أَحَدٌ مِنَ الْمُشْرِكِينَ اسْتَجَارَكَ﴾ — an اسم follows the أداة الشرط. Is the جملة still فعلية?',
          options: ['No — a visible اسم makes it اسمية', 'Yes — a فعل is implied before أَحَدٌ', 'No — it is neither اسمية nor فعلية', 'Yes, but only because إِنْ is a حرف'],
          correct: 1,
        },
        {
          title: 'الجملة الخبرية defined',
          kind: 'mcq',
          prompt: 'الجملة الخبرية is one whose speaker:',
          options: ['may be truthful or lying in what he says', 'can never be described as truthful or lying', 'is describing one of the eleven types of طلب', 'must open with a فعل rather than an اسم'],
          correct: 0,
        },
        {
          title: '﴿وَالْعَصْرِ﴾',
          kind: 'mcq',
          prompt: '﴿وَالْعَصْرِ﴾ is which type of إنشاء?',
          options: ['الدعاء', 'القسم', 'التمني', 'النداء'],
          correct: 1,
        },
        {
          title: '﴿يَا حَسْرَتَىٰ﴾',
          kind: 'mcq',
          prompt: '﴿يَا حَسْرَتَىٰ عَلَىٰ مَا فَرَّطْتُ فِي جَنْبِ اللَّهِ﴾ is which type of إنشاء?',
          options: ['صيغ التوجع والتفجع', 'صيغ المدح والذم', 'الإغراء والتحذير', 'النداء والتمني'],
          correct: 0,
        },
        {
          title: 'خبر in wording, إنشاء in meaning',
          kind: 'mcq',
          prompt: '﴿الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ﴾ is cited as an example of a جملة that is:',
          options: ['خبر in both wording and meaning', 'خبر in wording but إنشاء (praise) in meaning', 'إنشاء in wording but خبر in meaning', 'neither خبر nor إنشاء'],
          correct: 1,
        },
        {
          title: 'إنشاء in wording, خبر in meaning',
          kind: 'mcq',
          prompt: 'The hadith «مَنْ كَذَبَ عَلَيَّ … فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ» is أمر in form. What is it in meaning?',
          options: ['أمر — a genuine command', 'خبر — the report سَيَتَبَوَّأُ', 'تمنٍّ — wishing for something', 'استفهام — asking a question'],
          correct: 1,
        },
        {
          title: 'الكبرى and الصغرى',
          kind: 'mcq',
          prompt: 'In ﴿وَاللَّهُ يَعْلَمُ﴾, both يَعْلَمُ and the جملة as a whole carry one of these two labels each. What is يَعْلَمُ, specifically?',
          options: ['الجملة الصغرى, sitting in the position of الخبر', 'الجملة الكبرى, containing يَعْلَمُ inside it', 'الفضلة, since it is not the مسند إليه', 'شبه الجملة, since it is not a جملة تامة'],
          correct: 0,
        },
        {
          title: 'كلام and جملة',
          kind: 'mcq',
          prompt: 'Which statement about كلام and جملة is correct?',
          options: ['Every جملة is كلام, but not every كلام is a جملة', 'Every كلام is a جملة, but not every جملة is كلام', 'They are two names for the same thing', 'Neither one implies the other at all'],
          correct: 1,
        },
        {
          title: 'موجب or غير موجب؟',
          kind: 'mcq',
          prompt: '﴿لَا تُشْرِكْ بِاللَّهِ﴾ contains a نهي. Is it موجب or غير موجب?',
          options: ['موجب', 'غير موجب', 'خبري لا إنشائي', 'إنشائي لا خبري'],
          correct: 1,
        },
        {
          title: 'تركيب: يَغْفِرُ اللَّهُ الذُّنُوبَ',
          kind: 'tarkeeb',
          instruction: 'Label المسند and المسند إليه; then classify each part as عمدة or فضلة.',
          sentence: 'يَغْفِرُ اللَّهُ الذُّنُوبَ',
          translation: 'Allah forgives sins.',
          cells: ['يَغْفِرُ', 'اللَّهُ', 'الذُّنُوبَ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'مسند' },
              { start: 1, end: 1, role: 'مسند إليه' },
            ] },
            { position: 'below', labels: [
              { start: 0, end: 1, role: 'عمدة' },
              { start: 2, end: 2, role: 'فضلة' },
            ] },
          ],
          distractors: ['ناسخ', 'شرطية'],
        },
        {
          title: 'تركيب: ﴿وَاللَّهُ يَعْلَمُ﴾',
          kind: 'tarkeeb',
          instruction: 'Label the whole جملة; then identify the جملة sitting inside it.',
          sentence: 'وَاللَّهُ يَعْلَمُ',
          translation: 'And Allah knows.',
          cells: ['اللَّهُ', 'يَعْلَمُ'],
          rows: [
            { position: 'above', label: 'الكل', labels: [
              { start: 0, end: 1, role: 'جملة كبرى' },
            ] },
            { position: 'below', label: 'الجزء', labels: [
              { start: 1, end: 1, role: 'جملة صغرى' },
            ] },
          ],
          distractors: ['خبرية', 'إنشائية'],
        },
      ],
    },

    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'شبه الجملة',
      subtitle: 'The Quasi-Sentence — the جار والمجرور and الظرف that hang inside a جملة',
      concepts: [
        {
          heading: 'تعريف شبه الجملة ومعاني الظرف',
          lines: [
            { html: `شبه الجملة is also called <bdi>الظَّرْف</bdi> — a word used for three separate things:`, list: false },
            { table: { headers: ['Meaning of ظرف', 'What it refers to'], rows: [
              ['الْمَفْعُولُ فِيهِ', 'the time/place object of a فعل'],
              ['فَوْقَ / تَحْتَ / عِنْدَ وأخواتها', 'a fixed set of location words'],
              ['شبه الجملة نفسه', 'شبه الجملة itself'],
            ] } },
            { html: `By form, شبه الجملة takes one of two shapes:`, list: false },
            { table: { headers: ['Shape', 'Example'], rows: [
              ['الْجَارُّ وَالْمَجْرُور', 'فِي مَكَّةَ'],
              ['الظَّرْفُ وَالْمُضَافُ إِلَيْهِ', 'عِنْدَ الْكَعْبَةِ'],
            ] } },
          ],
          exercise: {
            prompt: `فِي مَكَّةَ and عِنْدَ الْكَعْبَةِ are the two shapes شبه الجملة can take. Which shape does عِنْدَ الْكَعْبَةِ represent?`,
            kind: 'mcq',
            options: ['الجار والمجرور, like فِي مَكَّةَ', 'الظرف والمضاف إليه', 'كلا الشكلين معًا', 'لا ينتمي لأي منهما'],
            correct: 1,
          },
        },
        {
          heading: 'المتعلَّق والمتعلِّق، والظرف اللغو',
          lines: [
            { html: `The عامل of a شبه جملة is called its <bdi>مُتَعَلَّق</bdi>; the شبه جملة itself is the <bdi>مُتَعَلِّق</bdi>.`, list: false },
            { html: `By its عامل, شبه الجملة is <bdi>الظَّرْفُ اللَّغْو</bdi> when the عامل is either mentioned outright or deleted-but-known:`, list: false },
            { table: { headers: ['Case', 'Example'], rows: [
              ['عامل مذكور', '﴿لَقَدْ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ﴾'],
              ['عامل محذوف معروف (أي أَرْسَلْنَا)', '﴿وَإِلَىٰ عَادٍ أَخَاهُمْ هُودًا﴾'],
            ] } },
            { html: `It's called لغو ("idle") because it holds no hidden pronoun linking back to a مبتدأ, ذو حال, منعوت, or موصول.`, list: false },
            { html: `Four contexts force its عامل to be deleted:`, list: false },
            { html: `<bdi>الْأَمْثَال</bdi> — set proverbs`, list: true, bullet: true },
            { html: `a transmitted expression`, list: true, bullet: true },
            { html: `<bdi>قَسَم</bdi> sworn by other than الباء`, list: true, bullet: true },
            { html: `<bdi>خَبَرُ كَانَ</bdi> after <bdi>لَامِ الْجُحُود</bdi>`, list: true, bullet: true },
          ],
          clarification: `The simplest test for لغو vs. مستقر (covered next): delete the شبه جملة and see what's left standing. In لَقَدْ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ, drop إِلَىٰ قَوْمِهِ and أَرْسَلْنَا نُوحًا is already a complete جملة on its own (فعل + فاعل + مفعول) — so إِلَىٰ قَوْمِهِ is only extra detail, which is what makes it لغو ("idle"). Now contrast إِنَّكَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ (the example for مستقر, next concept): drop عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ and إِنَّكَ is left with no خبر at all — there, the شبه جملة is standing in for the missing خبر itself, so it can't be removed. That's why الظرف اللغو carries no ضمير مستتر pointing back to a مبتدأ, حال, نعت, or صلة still waiting to be completed — its عامل (a complete فعل, stated or deleted-but-known) never needed one in the first place.`,
          exercise: {
            prompt: `In ﴿لَقَدْ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ﴾ the عامل is mentioned outright; in ﴿وَإِلَىٰ عَادٍ أَخَاهُمْ هُودًا﴾ it is deleted but still specifically known. What do both شبه جملة count as?`,
            kind: 'mcq',
            options: ['الظرف اللغو, in both cases', 'الظرف المستقر, since the عامل is known', 'الأول لغو والثاني مستقر', 'الأول مستقر والثاني لغو'],
            correct: 0,
          },
        },
        {
          heading: 'الظرف المستقر',
          lines: [
            { html: `<bdi>الظَّرْفُ الْمُسْتَقِرّ</bdi> has a عامل that is BOTH deleted and general — as in ﴿إِنَّكَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾ (أي: تَثْبُتُ).`, list: false },
            { html: `Only words of existence can fill that deleted slot:`, list: false },
            { html: `as أفعال — <bdi>اسْتَقَرَّ / ثَبَتَ / وُجِدَ / يَكُونُ</bdi>`, list: true, bullet: true },
            { html: `or as أسماء — <bdi>مُسْتَقِرّ / ثَابِت / مَوْجُود / كَائِن</bdi>`, list: true, bullet: true },
            { html: `Inside <bdi>الصِّلَة</bdi> specifically, that deleted عامل must be a فعل, since الصلة must itself be a جملة, as in الَّذِي فِي مَكَّةَ (أي: الَّذِي اسْتَقَرَّ فِي مَكَّةَ).`, list: false },
          ],
          clarification: `Why must it be a فعل, not the matching اسم (مُسْتَقِرّ)? Because الصلة has to be a full جملة, and a جملة needs a مُسْنَد paired with a مُسْنَدٌ إِلَيْهِ (recall: خبر أو فعل, paired with مبتدأ أو فاعل). A فعل already comes with its own فاعل built in, so استقر في مكة is by itself a complete جملة. مُسْتَقِرّ is just a single اسم (a مفرد) — with no فاعل or مسند إليه of its own, it can't be a جملة at all. That's why only the فعل-form works inside الصلة.`,
          exercise: {
            prompt: `In الَّذِي فِي مَكَّةَ, the deleted general عامل must specifically be a فعل (استقر), never an اسم like مستقر. Why?`,
            kind: 'mcq',
            options: [
              'Because الصلة must be a جملة, and only a فعل can supply that here',
              'Because an اسم doesn’t indicate existence at all',
              'Because the ظرف لغو requires it',
              'There’s no reason — either would work the same',
            ],
            correct: 0,
          },
        },
        {
          heading: 'مواضع الظرف المستقر الخمسة',
          lines: [
            { html: `الظرف المستقر occurs in exactly five positions:`, list: false },
            { table: { headers: ['#', 'Position', 'Example'], rows: [
              ['1', 'الْخَبَر', '﴿وَهُوَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾'],
              ['2', 'الْحَال', '﴿فَخَرَجَ عَلَىٰ قَوْمِهِ فِي زِينَتِهِ﴾'],
              ['3', 'النَّعْت', '﴿أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ﴾'],
              ['4', 'الصِّلَة', '﴿وَلَهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ﴾'],
              ['5', 'الِاعْتِمَاد', '﴿أَفِي اللَّهِ شَكٌّ﴾'],
            ] } },
            { html: `One naming note: <bdi>مُسْتَقَرّ</bdi> is the deleted عامل itself; <bdi>ظَرْفٌ مُسْتَقِرّ</bdi> is the whole شبه جملة.`, list: false },
          ],
          exercise: {
            prompt: `﴿فَخَرَجَ عَلَىٰ قَوْمِهِ فِي زِينَتِهِ﴾ — في زينته occupies which of the five positions of الظرف المستقر?`,
            kind: 'mcq',
            options: ['الخبر', 'الحال', 'النعت', 'الاعتماد'],
            correct: 1,
          },
        },
      ],
      quiz: [
        {
          q: 'The word ظرف is applied to three things. Which of these is NOT one of them?',
          options: ['المفعول فيه', 'شبه الجملة', 'فوق، تحت، عند وأخواتها', 'المضاف إليه'],
          correct: 3,
        },
        {
          q: 'الجار والمجرور and الظرف والمضاف إليه are the two types of شبه الجملة, classified by:',
          options: ['form (شكل اللفظ)', 'the state of its عامل (لغو أم مستقر)', 'its position in the جملة', 'whether it is معمول or غير معمول'],
          correct: 0,
        },
        {
          q: 'Why is الظرف اللغو called لغوا?',
          options: ['Because its عامل is always mentioned outright', 'Because it holds no ضمير مستتر linking back', 'Because it always sits inside a صلة', 'Because its عامل is deleted and general'],
          correct: 1,
        },
        {
          q: 'What’s the core difference between اللغو’s deleted عامل and المستقر’s?',
          options: ['There is no difference between them', 'اللغو’s is specific; المستقر’s is general', 'المستقر’s عامل is always mentioned outright', 'اللغو has no عامل at all, stated or implied'],
          correct: 1,
        },
        {
          q: 'Where must the deleted عامل of a ظرف مستقر be a فعل, never an اسم?',
          options: ['In الخبر', 'In الحال', 'In الصلة', 'In النعت'],
          correct: 2,
        },
        {
          q: 'مستقَر vs ظرف مستقر:',
          options: ['They are simply two names for one thing', 'مستقَر is the عامل; ظرف مستقر is the شبه جملة', 'مستقَر applies only to الجار والمجرور', 'ظرف مستقر never has its عامل deleted'],
          correct: 1,
        },
      ],
      drills: [
        {
          title: '﴿أَفِي اللَّهِ شَكٌّ﴾',
          prompt: `في اللهِ here has a general, deleted عامل tied to the استفهام itself, not one specific mentioned فعل. Which of the five positions does this represent?`,
          kind: 'mcq',
          options: ['الخبر', 'الحال', 'الصلة', 'الاعتماد'],
          correct: 3,
        },
        {
          title: 'قسم بغير الباء',
          prompt: `﴿تَاللَّهِ تَفْتَأُ تَذْكُرُ يُوسُفَ﴾ swears by التاء, not الباء. What happens to the عامل of تَاللَّهِ?`,
          kind: 'mcq',
          options: ['It must be mentioned', 'It must delete, obligatorily', 'There is no شبه جملة here', 'The عامل is an اسم, not a فعل'],
          correct: 1,
        },
        {
          title: 'الَّذِي فِي مَكَّةَ outside الصلة',
          prompt: `If فِي مَكَّةَ were a خبر instead of a صلة, would its deleted عامل still have to be a فعل (استقر) rather than an اسم (مستقر)?`,
          kind: 'mcq',
          options: ['Yes — the عامل must be a فعل everywhere', 'No — that requirement is specific to الصلة', 'Deletion is not allowed outside الصلة', 'الخبر cannot take a ظرف مستقر at all'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: 'متعلَّق',
          kind: 'mcq',
          prompt: 'The عامل that a شبه جملة is tied to is called:',
          options: ['متعلِّقًا', 'متعلَّقًا', 'مستقَرًا always', 'الظرف اللغو always'],
          correct: 1,
        },
        {
          title: 'الأمثال and forced deletion',
          kind: 'mcq',
          prompt: 'الْكِلَابَ عَلَى الْبَقَرِ (a proverb, = سَلِّطْ) — why is the عامل deleted obligatorily here?',
          options: ['It’s a ظرف مستقر', 'It’s one of الأمثال', 'It’s just الجار والمجرور', 'It has no عامل at all'],
          correct: 1,
        },
        {
          title: 'النعت or الحال؟',
          kind: 'mcq',
          prompt: '﴿أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ﴾ — على هدى sits in the position of:',
          options: ['الحال', 'النعت', 'الاعتماد', 'الصلة'],
          correct: 1,
        },
        {
          title: 'الجار والمجرور or الظرف والمضاف إليه؟',
          kind: 'mcq',
          prompt: 'فِي مَكَّةَ is which type of شبه الجملة by form?',
          options: ['الجار والمجرور', 'الظرف والمضاف إليه, like عِنْدَ الْكَعْبَةِ', 'both types at once', 'neither type'],
          correct: 0,
        },
        {
          title: 'تركيب: ﴿وَهُوَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾',
          kind: 'tarkeeb',
          instruction: 'Label المسند إليه; then identify which of the five مواضع الظرف المستقر the شبه جملة occupies.',
          sentence: 'وَهُوَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ',
          translation: 'And he is on a straight path.',
          cells: ['هُوَ', 'عَلَىٰ', 'صِرَاطٍ', 'مُسْتَقِيمٍ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'مسند إليه' },
            ] },
            { position: 'below', labels: [
              { start: 1, end: 3, role: 'الخبر' },
            ] },
          ],
          distractors: ['الحال', 'النعت'],
        },
        {
          title: 'تركيب: ﴿فَخَرَجَ عَلَىٰ قَوْمِهِ فِي زِينَتِهِ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which of the five مواضع the شبه جملة فِي زِينَتِهِ occupies.',
          sentence: 'فَخَرَجَ عَلَىٰ قَوْمِهِ فِي زِينَتِهِ',
          translation: 'So he went out before his people in his adornment.',
          cells: ['خَرَجَ', 'عَلَىٰ', 'قَوْمِهِ', 'فِي', 'زِينَتِهِ'],
          rows: [
            { position: 'above', labels: [
              { start: 3, end: 4, role: 'الحال' },
            ] },
          ],
          distractors: ['الخبر', 'الصلة'],
        },
        {
          title: 'تركيب: ﴿أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which of the five مواضع عَلَىٰ هُدًى occupies.',
          sentence: 'أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ',
          translation: 'Those are upon guidance from their Lord.',
          cells: ['أُولَٰئِكَ', 'عَلَىٰ', 'هُدًى', 'مِنْ', 'رَبِّهِمْ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 2, role: 'النعت' },
            ] },
          ],
          distractors: ['الاعتماد', 'الخبر'],
        },
        {
          title: 'تركيب: ﴿وَلَهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which of the five مواضع the شبه جملة فِي السَّمَاوَاتِ وَالْأَرْضِ occupies.',
          sentence: 'وَلَهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ',
          translation: 'And to Him belongs whoever is in the heavens and the earth.',
          cells: ['لَهُ', 'مَنْ', 'فِي', 'السَّمَاوَاتِ', 'وَالْأَرْضِ'],
          rows: [
            { position: 'above', labels: [
              { start: 2, end: 4, role: 'الصلة' },
            ] },
          ],
          distractors: ['الحال', 'الاعتماد'],
        },
        {
          title: 'تركيب: ﴿أَفِي اللَّهِ شَكٌّ﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which of the five مواضع أَفِي اللَّهِ occupies.',
          sentence: 'أَفِي اللَّهِ شَكٌّ',
          translation: 'Is there any doubt about Allah?',
          cells: ['أَفِي', 'اللَّهِ', 'شَكٌّ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 1, role: 'الاعتماد' },
            ] },
          ],
          distractors: ['الخبر', 'النعت'],
        },
        {
          title: 'تركيب: ﴿لَقَدْ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify إِلَىٰ قَوْمِهِ as الظرف اللغو or الظرف المستقر.',
          sentence: 'لَقَدْ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ',
          translation: 'We sent Noah to his people.',
          cells: ['لَقَدْ', 'أَرْسَلْنَا', 'نُوحًا', 'إِلَىٰ', 'قَوْمِهِ'],
          rows: [
            { position: 'above', labels: [
              { start: 3, end: 4, role: 'الظرف اللغو' },
            ] },
          ],
          distractors: ['الظرف المستقر', 'مضاف'],
        },
        {
          title: 'تركيب: ﴿إِنَّكَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ as الظرف اللغو or الظرف المستقر.',
          sentence: 'إِنَّكَ عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ',
          translation: 'Indeed, you are on a straight path.',
          cells: ['إِنَّكَ', 'عَلَىٰ', 'صِرَاطٍ', 'مُسْتَقِيمٍ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 3, role: 'الظرف المستقر' },
            ] },
          ],
          distractors: ['الظرف اللغو', 'متعلَّق'],
        },
        {
          title: 'Not one of the three senses of ظرف',
          kind: 'mcq',
          prompt: 'Which of these is NOT one of the three things the word ظرف is applied to?',
          options: ['المفعول فيه', 'فَوْقَ، تَحْتَ، عِنْدَ and their sisters', 'شبه الجملة', 'المضاف إليه'],
          correct: 3,
        },
        {
          title: 'Three meanings of ظرف',
          kind: 'mcq',
          prompt: 'The word ظرف is applied to three things. Which set is correct?',
          options: ['المفعول فيه; فوق، تحت، عند; شبه الجملة', 'الجار; المجرور; المضاف إليه معًا', 'الاسم; الفعل; الحرف الثلاثة', 'الظرف اللغو; المستقر; المتعلَّق'],
          correct: 0,
        },
        {
          title: 'عِنْدَ الْكَعْبَةِ',
          kind: 'mcq',
          prompt: 'عِنْدَ الْكَعْبَةِ is which type of شبه الجملة by form?',
          options: ['الجار والمجرور, like فِي مَكَّةَ', 'الظرف والمضاف إليه', 'both types at once', 'neither type'],
          correct: 1,
        },
        {
          title: 'متعلِّق',
          kind: 'mcq',
          prompt: 'The شبه جملة sitting inside a جملة is itself called:',
          options: ['متعلَّقًا', 'متعلِّقًا', 'مستقَرًا', 'عاملًا'],
          correct: 1,
        },
        {
          title: 'Why اللغو is called لغو',
          kind: 'mcq',
          prompt: 'Why is الظرف اللغو given that name?',
          options: ['Because it holds no ضمير مستتر returning to a مبتدأ', 'Because it carries no meaning of its own at all', 'Because its عامل is always deleted and general', 'Because it is always a جار ومجرور, never a ظرف'],
          correct: 0,
        },
        {
          title: 'عامل mentioned outright',
          kind: 'mcq',
          prompt: '﴿لَقَدْ أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ﴾ — إلى قومه has its عامل (أرسلنا) stated. It is therefore:',
          options: ['ظرف لغو', 'ظرف مستقر', 'متعلَّق فقط، لا ظرف', 'معمول فقط، لا ظرف'],
          correct: 0,
        },
        {
          title: 'Deleted but specific',
          kind: 'mcq',
          prompt: '﴿وَإِلَىٰ عَادٍ أَخَاهُمْ هُودًا﴾ — the عامل أرسلنا is deleted but known exactly. Which type is this?',
          options: ['ظرف مستقر', 'ظرف لغو', 'متعلَّق', 'معمول'],
          correct: 1,
        },
        {
          title: 'قسم without الباء',
          kind: 'mcq',
          prompt: '﴿تَاللَّهِ تَفْتَأُ تَذْكُرُ يُوسُفَ﴾ — which of the four contexts forces the عامل to be deleted here?',
          options: ['قسم with other than الباء', 'الأمثال', 'خبر كان with لام الجحود', 'A transmitted expression'],
          correct: 0,
        },
        {
          title: 'لام الجحود',
          kind: 'mcq',
          prompt: '﴿مَا كَانَ اللَّهُ لِيُعَذِّبَهُمْ وَأَنْتَ فِيهِمْ﴾ falls under which context of obligatory deletion?',
          options: ['خبر كان with لام الجحود', 'الأمثال', 'A transmitted expression', 'قسم without الباء'],
          correct: 0,
        },
        {
          title: 'بِأَبِي أَنْتَ وَأُمِّي',
          kind: 'mcq',
          prompt: 'بِأَبِي أَنْتَ وَأُمِّي (= أنت مفدى بأبي وأمي) is an instance of:',
          options: ['a transmitted expression', 'a proverb (مثل)', 'قسم without الباء', 'خبر كان with لام الجحود'],
          correct: 0,
        },
        {
          title: 'The general deleted عامل',
          kind: 'mcq',
          prompt: 'Which sort of words fill the deleted, general عامل of a ظرف مستقر?',
          options: ['Words of existence, like استقر and مستقر', 'Words of motion, like ذهب and ذاهب', 'Only حروف الجر, like في and على', 'Only أسماء الفعل, like صَهْ and مَهْ'],
          correct: 0,
        },
        {
          title: 'The عامل inside a صلة',
          kind: 'mcq',
          prompt: 'الَّذِي فِي مَكَّةَ — inside a صلة, the deleted عامل must be a فعل and not an اسم. Why?',
          options: ['Because the صلة must itself be a جملة', 'Because أسماء cannot be deleted', 'Because في is a حرف جر', 'Because the صلة is a فضلة'],
          correct: 0,
        },
        {
          title: 'الاعتماد',
          kind: 'mcq',
          prompt: '﴿أَفِي اللَّهِ شَكٌّ﴾ — في الله occupies which of the five positions?',
          options: ['الخبر', 'الحال', 'الاعتماد', 'النعت'],
          correct: 2,
        },
        {
          title: 'مستقَر vs ظرف مستقر',
          kind: 'mcq',
          prompt: 'Which of these four terms names the deleted عامل itself, rather than the شبه جملة it governs?',
          options: ['مستقَر', 'ظرف مستقر', 'الظرف اللغو', 'المتعلِّق'],
          correct: 0,
        },
        {
          title: 'تركيب: صَلَّيْتُ فِي مَكَّةَ عِنْدَ الْكَعْبَةِ',
          kind: 'tarkeeb',
          instruction: 'Classify فِي مَكَّةَ and عِنْدَ الْكَعْبَةِ by form.',
          sentence: 'صَلَّيْتُ فِي مَكَّةَ عِنْدَ الْكَعْبَةِ',
          translation: 'I prayed in Mecca, by the Kaaba.',
          cells: ['صَلَّيْتُ', 'فِي', 'مَكَّةَ', 'عِنْدَ', 'الْكَعْبَةِ'],
          rows: [
            { position: 'above', labels: [
              { start: 1, end: 2, role: 'الجار والمجرور' },
              { start: 3, end: 4, role: 'الظرف والمضاف إليه' },
            ] },
          ],
          distractors: ['الظرف اللغو', 'الظرف المستقر'],
        },
        {
          title: 'تركيب: يَجْلِسُ الْوَلَدُ عِنْدَ الْمُعَلِّمِ',
          kind: 'tarkeeb',
          instruction: 'Identify المتعلَّق (العامل) and المتعلِّق (شبه الجملة).',
          sentence: 'يَجْلِسُ الْوَلَدُ عِنْدَ الْمُعَلِّمِ',
          translation: 'The boy sits by the teacher.',
          cells: ['يَجْلِسُ', 'الْوَلَدُ', 'عِنْدَ', 'الْمُعَلِّمِ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'متعلَّق' },
              { start: 2, end: 3, role: 'متعلِّق' },
            ] },
          ],
          distractors: ['الظرف اللغو', 'الظرف المستقر'],
        },
      ],
    },

    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'العامل والمعمول والإعراب',
      subtitle: 'The Governor, the Governed, and the Grammatical Inflection they produce',
      concepts: [
        {
          heading: 'العامل وغير العامل',
          lines: [
            { html: `<bdi>الْعَامِل</bdi> is anything that necessitates a grammatical state — <bdi>لَنْ</bdi> in ﴿وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا﴾ forces نصب.`, list: false },
            { html: `<bdi>غَيْرُ الْعَامِل</bdi> necessitates nothing, like <bdi>مَا</bdi> in ﴿مَا أَشْرَكْنَا﴾.`, list: false },
            { table: { headers: ['Category', 'عامل or not?'], rows: [
              ['كل الأفعال', 'عاملة دائمًا'],
              ['كل الجمل', 'غير عاملة دائمًا'],
              ['كل أشباه الجمل', 'غير عاملة دائمًا'],
              ['الحروف والأسماء', 'بعضها عامل، وبعضها لا'],
            ] } },
          ],
          exercise: {
            prompt: `Which of the following is true without exception, for every single member of its category?`,
            kind: 'mcq',
            options: ['كل الحروف عاملة', 'كل الأسماء عاملة', 'كل الأفعال عاملة', 'كل الأسماء غير عاملة'],
            correct: 2,
          },
        },
        {
          heading: 'المبادئ الخمسة',
          lines: [
            { table: { title: 'المبادئ الخمسة', headers: ['#', 'Principle'], rows: [
              ['1', 'كل الأفعال عاملة'],
              ['2', 'بعض الحروف عاملة، وبعضها لا'],
              ['3', 'بعض الأسماء عاملة، وبعضها لا'],
              ['4', 'كل الجمل غير عاملة'],
              ['5', 'كل أشباه الجمل غير عاملة'],
            ] } },
            { html: `غير العامل is also called <bdi>عَاطِل</bdi> or <bdi>مُهْمَل</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `According to the five principles, are أفعال and جمل treated the same way (partly عاملة, partly not) or differently?`,
            kind: 'mcq',
            options: [
              'The same treatment: both split into two categories',
              'Different: every فعل is always عاملة, and every جملة is always غير عاملة',
              'Every فعل is غير عاملة, and every جملة is عاملة',
              'أفعال have no relation to العمل at all',
            ],
            correct: 1,
          },
        },
        {
          heading: 'المعمول وغير المعمول',
          lines: [
            { html: `<bdi>الْمَعْمُول</bdi> is anything that accepts a state and has إعراب — <bdi>صَاحِب</bdi> in ﴿مَا ضَلَّ صَاحِبُكُمْ﴾.`, list: false },
            { html: `Five things count as معمول:`, list: false },
            { html: `every اسم except أسماء الفعل`, list: true, bullet: true },
            { html: `المضارع`, list: true, bullet: true },
            { html: `a ماضٍ once a ناصب or جازم enters upon it`, list: true, bullet: true },
            { html: `some جمل`, list: true, bullet: true },
            { html: `every شبه جملة`, list: true, bullet: true },
            { html: `Three things are <bdi>غَيْرُ مَعْمُول</bdi> instead:`, list: false },
            { html: `every حرف`, list: true, bullet: true },
            { html: `أسماء الفعل`, list: true, bullet: true },
            { html: `a plain ماضٍ with no ناصب or جازم`, list: true, bullet: true },
          ],
          exercise: {
            prompt: `أشباه الجمل are always غير عامل. Are they معمول or غير معمول?`,
            kind: 'mcq',
            options: ['غير معمول دائمًا، تمامًا كأسماء الفعل', 'معمول دائمًا، دون استثناء', 'معمول أحيانًا فقط', 'لا ينطبق عليها هذا التقسيم أصلًا'],
            correct: 1,
          },
        },
        {
          heading: 'الإعراب وأنواعه',
          lines: [
            { html: `الإعراب is the effect a عامل brings about at a word's end.`, list: false },
            { table: { headers: ['Type', 'Condition', 'Example'], rows: [
              ['لَفْظِيّ', 'appears in pronunciation', 'يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ'],
              ['تَقْدِيرِيّ', 'blocked from appearing by a phonetic مَانِع', 'يَسْعَى الْفَتَى إِلَى الْهُدَى'],
              ['مَحَلِّيّ', "never appears — the word itself can't bear a marking", 'تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ'],
            ] } },
          ],
          exercise: {
            prompt: `In يَسْعَى الْفَتَى إِلَى الْهُدَى, the ضمة and كسرة are understood but blocked from appearing by the nature of the ending. Which type of إعراب is this?`,
            kind: 'mcq',
            options: ['الإعراب اللفظي', 'الإعراب التقديري', 'الإعراب المحلي', 'ليس إعرابًا أصلًا'],
            correct: 1,
          },
        },
      ],
      quiz: [
        {
          q: 'Which of these four is the definition of العامل specifically?',
          options: ['Necessitates a state in another word', 'Accepts a state and carries it', 'The effect a عامل brings at a word’s end', 'Necessitates nothing at all'],
          correct: 0,
        },
        {
          q: 'Which is true under the five principles?',
          options: ['All أفعال are عاملة; every جملة is غير عاملة', 'All أفعال are غير عاملة; every جملة is عاملة', 'All حروف are عاملة; all أسماء are غير عاملة', 'All أسماء are عاملة; all حروف are غير عاملة'],
          correct: 0,
        },
        {
          q: 'غير العامل is also called:',
          options: ['معمولًا وعمدةً', 'عاطلًا ومهملًا', 'متعلَّقًا ومستقَرًا', 'كبرى وصغرى'],
          correct: 1,
        },
        {
          q: 'Which is always معمول without exception?',
          options: ['أسماء الفعل', 'every حرف', 'every شبه جملة', 'a plain ماضٍ (no ناصب/جازم)'],
          correct: 2,
        },
        {
          q: 'What is the definition of الإعراب?',
          options: ['What necessitates a state in another word', 'What accepts a state and carries it', 'The effect a عامل brings at a word’s end', 'A قول مفيد upon which silence is proper'],
          correct: 2,
        },
        {
          q: 'Difference between إعراب تقديري and محلي:',
          options: ['There is no difference between them', 'تقديري is blocked by a مانع; محلي cannot be borne', 'محلي applies only to أفعال, تقديري only to أسماء', 'تقديري applies only to حروف, محلي only to أفعال'],
          correct: 1,
        },
      ],
      drills: [
        {
          title: 'أسماء الفعل: عامل or not?',
          prompt: `أسماء الفعل (like صَهْ, meaning "be quiet") take no إعراب — they're غير معمول. Does that also make them غير عامل?`,
          kind: 'mcq',
          options: [
            'Not necessarily — being معمول and being عامل are separate questions (they act like أفعال, and all أفعال are عاملة)',
            'Yes, always both',
            'They are معمول, not غير معمول',
            'Irrelevant — أسماء الفعل aren’t classified this way',
          ],
          correct: 0,
        },
        {
          title: 'الماضي before and after ناصب/جازم',
          prompt: `A plain الماضي is غير معمول. When does it become معمول?`,
          kind: 'mcq',
          options: ['Never — the ماضي is always غير معمول', 'Once a ناصب or جازم enters upon it', 'Once a حرف جر precedes it directly', 'Only inside a جملة اسمية منسوخة'],
          correct: 1,
        },
        {
          title: 'الضمائر and إعراب محلي',
          prompt: `In تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ, the ضمائر never change form by position. Why doesn’t that mean they have no إعراب at all?`,
          kind: 'mcq',
          options: ['They really have no إعراب at all', 'They carry إعراب محلي, set by position', 'They carry إعراب لفظي, visible in speech', 'They are حروف, and حروف take no إعراب'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: 'العامل in ﴿ولن نشرك﴾',
          kind: 'mcq',
          prompt: 'لَنْ in ﴿وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا﴾ forces which state?',
          options: ['الرفع', 'النصب', 'الجزم', 'الجر'],
          correct: 1,
        },
        {
          title: 'جملة and شبه جملة: عاملة or not?',
          kind: 'mcq',
          prompt: 'Every جملة and every شبه جملة, regarding being عاملة, is:',
          options: ['both always عاملة, like every فعل', 'both always غير عاملة', 'sometimes عاملة, like بعض الحروف', 'عاملة, but never معمولة'],
          correct: 1,
        },
        {
          title: 'صَاحِبُكُمْ is معمول',
          kind: 'mcq',
          prompt: '﴿مَا ضَلَّ صَاحِبُكُمْ﴾ — صَاحِبُ is معمول because it:',
          options: ['forces a state on another word', 'accepts a state and has إعراب', 'is a غير عامل حرف', 'is a whole جملة'],
          correct: 1,
        },
        {
          title: 'إعراب لفظي',
          kind: 'mcq',
          prompt: 'يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ — the ضمة and كسرة are visible in pronunciation. Which type of إعراب is this?',
          options: ['التقديري', 'اللفظي', 'المحلي', 'not إعراب at all'],
          correct: 1,
        },
        {
          title: 'تركيب: ﴿وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا﴾',
          kind: 'tarkeeb',
          instruction: 'Identify which word is العامل and which is المعمول.',
          sentence: 'وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا',
          translation: 'And we will never associate with our Lord anyone.',
          cells: ['لَنْ', 'نُشْرِكَ', 'بِرَبِّنَا', 'أَحَدًا'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'عامل' },
              { start: 1, end: 1, role: 'معمول' },
            ] },
          ],
          distractors: ['غير عامل', 'غير معمول'],
        },
        {
          title: 'تركيب: يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ',
          kind: 'tarkeeb',
          instruction: 'Label the word class of each word; then identify the type of إعراب shown.',
          sentence: 'يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ',
          translation: 'The believer strives in [doing] good.',
          cells: ['يَجْتَهِدُ', 'الْمُؤْمِنُ', 'فِي', 'الْخَيْرِ'],
          rows: [
            { position: 'above', label: 'Word class', labels: [
              { start: 0, end: 0, role: 'فعل' },
              { start: 1, end: 1, role: 'اسم' },
              { start: 2, end: 2, role: 'حرف' },
              { start: 3, end: 3, role: 'اسم' },
            ] },
            { position: 'below', label: 'الإعراب', labels: [
              { start: 0, end: 3, role: 'الإعراب اللفظي' },
            ] },
          ],
          distractors: ['الإعراب التقديري', 'الإعراب المحلي'],
        },
        {
          title: 'تركيب: يَسْعَى الْفَتَى إِلَى الْهُدَى',
          kind: 'tarkeeb',
          instruction: 'Identify the type of إعراب shown.',
          sentence: 'يَسْعَى الْفَتَى إِلَى الْهُدَى',
          translation: 'The young man strives toward guidance.',
          cells: ['يَسْعَى', 'الْفَتَى', 'إِلَى', 'الْهُدَى'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 3, role: 'الإعراب التقديري' },
            ] },
          ],
          distractors: ['الإعراب اللفظي', 'الإعراب المحلي'],
        },
        {
          title: 'تركيب: تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ',
          kind: 'tarkeeb',
          instruction: 'Identify the type of إعراب shown.',
          sentence: 'تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ',
          translation: 'You (fem. pl.) strive toward him.',
          cells: ['تَسْعَيْنَ', 'أَنْتُنَّ', 'إِلَيْهِ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 2, role: 'الإعراب المحلي' },
            ] },
          ],
          distractors: ['الإعراب اللفظي', 'الإعراب التقديري'],
        },
        {
          title: 'Definition of العامل',
          kind: 'mcq',
          prompt: 'العامل is defined as:',
          options: ['That which necessitates a grammatical state', 'That which accepts a grammatical state and carries it', 'The effect brought about at a word’s end', 'Something always غير عاملة, like الجملة'],
          correct: 0,
        },
        {
          title: 'Which categories are عامل',
          kind: 'mcq',
          prompt: 'Which statement matches the categories that can be عامل?',
          options: ['All أفعال, some حروف, and some أسماء', 'All حروف and nothing else', 'All أسماء and nothing else', 'الجمل and أشباه الجمل'],
          correct: 0,
        },
        {
          title: 'What عاطل and مهمل describe',
          kind: 'mcq',
          prompt: 'A word described as عاطل or مهمل is one that:',
          options: ['necessitates no grammatical state in another word (= غير عامل)', 'accepts a grammatical state and carries إعراب (= معمول)', 'is a عامل under a different name', 'is a معمول under a different name'],
          correct: 0,
        },
        {
          title: 'مَا in ﴿مَا أَشْرَكْنَا﴾',
          kind: 'mcq',
          prompt: 'مَا in ﴿مَا أَشْرَكْنَا﴾ is cited as an example of:',
          options: ['عامل, forcing الجزم on what follows', 'غير عامل, forcing no state at all', 'معمول, accepting a state from another', 'شبه جملة, made of جار and مجرور'],
          correct: 1,
        },
        {
          title: 'The five مبادئ',
          kind: 'mcq',
          prompt: 'Which of these is one of the five مبادئ on the عامل?',
          options: ['All أفعال are عاملة', 'All حروف are عاملة', 'All جمل are عاملة', 'All أسماء are عاملة'],
          correct: 0,
        },
        {
          title: 'Definition of المعمول',
          kind: 'mcq',
          prompt: 'المعمول is defined as:',
          options: ['That which accepts a grammatical state and has إعراب', 'That which necessitates a state in another word', 'The effect a عامل brings at a word’s end', 'Something always غير عاملة itself'],
          correct: 0,
        },
        {
          title: 'Which أسماء are معمول',
          kind: 'mcq',
          prompt: 'Regarding أسماء and being معمول:',
          options: ['All أسماء are معمول except أسماء الفعل', 'Only أسماء الفعل are معمول', 'No اسم is ever معمول', 'Only a مضاف اسم is معمول'],
          correct: 0,
        },
        {
          title: 'The ماضي as معمول',
          kind: 'mcq',
          prompt: 'When is الفعل الماضي counted among the معمولات?',
          options: ['When a ناصب or جازم has entered upon it', 'Always, without condition', 'Never, under any condition', 'Only when it carries تنوين'],
          correct: 0,
        },
        {
          title: 'غير معمول',
          kind: 'mcq',
          prompt: 'Which category is listed as غير معمول?',
          options: ['All حروف', 'All أسماء', 'The فعل المضارع', 'All أشباه الجمل'],
          correct: 0,
        },
        {
          title: 'أسماء الفعل',
          kind: 'mcq',
          prompt: 'أسماء الفعل are the one group of أسماء that are:',
          options: ['غير معمول', 'معمول like every other اسم', 'always عامل', 'a kind of حرف'],
          correct: 0,
        },
        {
          title: 'Definition of الإعراب',
          kind: 'mcq',
          prompt: 'الإعراب is defined as:',
          options: ['An effect the عامل brings about at the end of a word', 'A state a word necessitates in another word', 'A state a word merely accepts, without being caused', 'A sign specific to الاسم alone'],
          correct: 0,
        },
        {
          title: 'الإعراب التقديري',
          kind: 'mcq',
          prompt: 'يَسْعَى الْفَتَى إِلَى الْهُدَى — the markings do not appear, blocked by a مانع. Which type of إعراب?',
          options: ['اللفظي', 'التقديري', 'المحلي', 'No إعراب at all'],
          correct: 1,
        },
        {
          title: 'الإعراب المحلي',
          kind: 'mcq',
          prompt: 'تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ — the ضمائر cannot carry a marking at all. Which type of إعراب?',
          options: ['المحلي', 'اللفظي', 'التقديري', 'No إعراب at all'],
          correct: 0,
        },
        {
          title: 'شبه الجملة: عامل or معمول?',
          kind: 'mcq',
          prompt: 'Taking the two lists together, every شبه جملة is:',
          options: ['غير عاملة, and معمولة', 'عاملة, and غير معمولة', 'both عاملة and معمولة', 'neither عاملة nor معمولة'],
          correct: 0,
        },
        {
          title: 'تركيب: ﴿مَا ضَلَّ صَاحِبُكُمْ﴾',
          kind: 'tarkeeb',
          instruction: 'Classify each word: عامل, غير عامل, معمول, or غير معمول.',
          sentence: 'مَا ضَلَّ صَاحِبُكُمْ',
          translation: 'Your companion has not strayed.',
          cells: ['مَا', 'ضَلَّ', 'صَاحِبُكُمْ'],
          rows: [
            { position: 'above', labels: [
              { start: 0, end: 0, role: 'غير عامل' },
              { start: 1, end: 1, role: 'غير معمول' },
              { start: 2, end: 2, role: 'معمول' },
            ] },
          ],
          distractors: ['عامل', 'الإعراب اللفظي'],
        },
      ],
    },
  ],
};
