// قَصَصُ النَّبِيِّينَ, volume two -- «أَحْسَنُ الْقَصَصِ» (Yūsuf). The book
// shell the Library screen reads.
//
// Chapter numbering restarts at 1 in every Qaṣaṣ volume (see
// QASAS_AGENT_BRIEF.md §1), so each volume gets its own book id/shell rather
// than sharing one -- ch1 here is a different chapter from qasas-v1's ch1.
// Volume 2 begins printed page 27, immediately after volume 1's closing
// divider on page 26 (see qasas-v1/chapter-16.js's header comment).
//
// Chapter BODIES are lazy: only `load()` pulls in a chapter-NN.js, so the
// shells here stay cheap enough to import eagerly from content-lit/index.js.
//
// Adding a chapter: transcribe the printed page (see ../CHAPTER-FORMAT.md
// and QASAS_AGENT_BRIEF.md), write chapter-NN.js, then add one entry here,
// in reading order -- order is what gates progression, chapter N unlocks
// when chapter N-1 is finished.
export const BOOK = {
  id: 'qasas-v2',
  title: { ar: 'أَحْسَنُ الْقَصَصِ', en: 'The Best of Stories' },
  volumeLabel: 'Volume Two',
  author: { ar: 'أَبُو الْحَسَنِ عَلِيٌّ النَّدْوِيُّ', en: 'Abū al-Ḥasan ʿAlī an-Nadwī' },
  blurb: "The story of Yūsuf ﷺ, told in short vowelled pages of graded classical prose -- the dream of eleven stars, the brothers' envy, the well, Egypt, and the reunion of a scattered family.",
  chapters: [
    {
      id: 'ch1',
      number: 1,
      title: { ar: 'رُؤْيَا عَجِيبَةٌ', en: 'An Amazing Dream' },
      pages: [27, 28],
      blurb: "Yūsuf dreams of eleven stars, the sun, and the moon bowing to him -- and Yaʿqūb warns him not to tell his brothers.",
      load: () => import('./chapter-01.js'),
    },
    {
      id: 'ch2',
      number: 2,
      title: { ar: 'حَسَدُ الإِخْوَةِ', en: "The Brothers' Envy" },
      pages: [28, 29],
      blurb: "The brothers' envy hardens into a plot -- kill Yūsuf, or cast him where a stranger will carry him away.",
      load: () => import('./chapter-02.js'),
    },
    {
      id: 'ch3',
      number: 3,
      title: { ar: 'وَفْدٌ إِلَى يَعْقُوبَ', en: 'A Delegation to Yaʿqūb' },
      pages: [30, 31],
      blurb: 'The brothers settle on a plan and put it to Yaʿqūb -- send Yūsuf out with us tomorrow, and we will guard him well.',
      load: () => import('./chapter-03.js'),
    },
    {
      id: 'ch4',
      number: 4,
      title: { ar: 'إِلَى الْغَابَةِ', en: 'To the Forest' },
      pages: [31, 32],
      blurb: "The brothers cast Yūsuf into a well, but Allah comforts him from within it -- then they stain his shirt with a ram's blood to fool Yaʿqūb.",
      load: () => import('./chapter-04.js'),
    },
    {
      id: 'ch5',
      number: 5,
      title: { ar: 'أَمَامَ يَعْقُوبَ', en: 'Before Yaʿqūb' },
      pages: [32, 33],
      blurb: "The brothers bring Yaʿqūb Yūsuf's blood-stained shirt, but the untorn cloth gives their lie away -- and Yaʿqūb bears his grief with beautiful patience.",
      load: () => import('./chapter-05.js'),
    },
    {
      id: 'ch6',
      number: 6,
      title: { ar: 'يُوسُفُ فِي الْبِئْرِ', en: 'Yūsuf in the Well' },
      pages: [33, 34],
      blurb: "The brothers go home, eat, and forget -- but alone in the well, Yūsuf does not sleep, and does not forget his father either.",
      load: () => import('./chapter-06.js'),
    },
    {
      id: 'ch7',
      number: 7,
      title: { ar: 'مِنَ الْبِئْرِ إِلَى الْقَصْرِ', en: 'From the Well to the Palace' },
      pages: [34, 35],
      blurb: 'A caravan draws Yūsuf up from the well and sells him in the market of Egypt -- and al-ʿAzīz brings him home to his palace.',
      load: () => import('./chapter-07.js'),
    },
    {
      id: 'ch8',
      number: 8,
      title: { ar: 'الْوَفَاءُ وَالأَمَانَةُ', en: 'Faithfulness and Trustworthiness' },
      pages: [35, 36],
      blurb: "Al-ʿAzīz's wife tempts Yūsuf, he refuses out of fear of Allah, and when her lie comes out he chooses prison over dishonor.",
      load: () => import('./chapter-08.js'),
    },
    {
      id: 'ch9',
      number: 9,
      title: { ar: 'مَوْعِظَةُ السِّجْنِ', en: 'The Sermon of the Prison' },
      pages: [36, 38],
      blurb: "Two fellow prisoners bring Yūsuf their dreams to interpret, and the sight of idol-worship around him stirs him to a sermon: do not the people of the prison deserve mercy? Are they not sons of Adam?",
      load: () => import('./chapter-09.js'),
    },
    {
      id: 'ch10',
      number: 10,
      title: { ar: 'حِكْمَةُ يُوسُفَ', en: 'The Wisdom of Yūsuf' },
      pages: [38, 39],
      blurb: 'Yūsuf deliberately delays interpreting the two men\'s dreams until they have sat and calmed down, then reveals it is a gift his Lord taught him -- turning the moment into an opening for dawah.',
      load: () => import('./chapter-10.js'),
    },
    {
      id: 'ch11',
      number: 11,
      title: { ar: 'مَوْعِظَةُ التَّوْحِيدِ', en: 'The Sermon of Monotheism' },
      pages: [39, 41],
      blurb: 'Yūsuf\'s sermon proper: why scattered lords cannot compare to Allah, the One, the All-Compelling -- and why judgment, dominion, and command belong to Him alone.',
      load: () => import('./chapter-11.js'),
    },
    {
      id: 'ch12',
      number: 12,
      title: { ar: 'تَأْوِيلُ الرُّؤْيَا', en: 'The Interpretation of the Dream' },
      pages: [41, 42],
      blurb: "Yūsuf gives the two men their interpretation and asks the future cupbearer to remember him to the king -- who forgets anyway, leaving Yūsuf in prison for years.",
      load: () => import('./chapter-12.js'),
    },
    {
      id: 'ch13',
      number: 13,
      title: { ar: 'رُؤْيَا الْمَلِكِ', en: "The King's Dream" },
      pages: [42, 43],
      blurb: 'The king dreams of seven fat cows eaten by seven lean ones -- and only the forgotten prisoner Yūsuf can explain what it means.',
      load: () => import('./chapter-13.js'),
    },
    {
      id: 'ch14',
      number: 14,
      title: { ar: 'الْمَلِكُ يُرْسِلُ إِلَى يُوسُفَ', en: 'The King Sends for Yūsuf' },
      pages: [44, 44],
      blurb: "The cupbearer finally remembers Yūsuf and tells the king who he is -- and the king, longing to meet him, sends for him at once.",
      load: () => import('./chapter-14.js'),
    },
    {
      id: 'ch15',
      number: 15,
      title: { ar: 'يُوسُفُ يَسْأَلُ التَّفْتِيشَ', en: 'Yūsuf Asks for an Investigation' },
      pages: [44, 45],
      blurb: "Summoned by the king, Yūsuf refuses to rush out of prison unproven -- he insists on a proper investigation into his case first, and is vindicated and honored once the truth comes out.",
      load: () => import('./chapter-15.js'),
    },
    {
      id: 'ch16',
      number: 16,
      title: { ar: 'عَلَى خَزَائِنِ الأَرْضِ', en: 'Over the Treasuries of the Land' },
      pages: [45, 47],
      blurb: "Yūsuf sees a land of neglected treasuries and starving people while the powerful feast -- and asks the king to put him in charge, trusting no one else to be both watchful and knowledgeable enough for the task.",
      load: () => import('./chapter-16.js'),
    },
    {
      id: 'ch17',
      number: 17,
      title: { ar: 'جَاءَ إِخْوَةُ يُوسُفَ', en: "Yūsuf's Brothers Came" },
      pages: [47, 48],
      blurb: "Famine drives Yaʿqūb's sons to Egypt for grain, straight to the storehouse keeper who is really their long-lost brother -- he recognizes them at once, though they have no idea who he is, and he says nothing.",
      load: () => import('./chapter-17.js'),
    },
    {
      id: 'ch18',
      number: 18,
      title: { ar: 'بَيْنَ يُوسُفَ وَإِخْوَتِهِ', en: 'Between Yūsuf and His Brothers' },
      pages: [49, 50],
      blurb: "Yūsuf questions his brothers gently about their family, learns of the young brother left behind with their father, then secretly returns their goods and tells them to bring that brother back with them next time.",
      load: () => import('./chapter-18.js'),
    },
    {
      id: 'ch19',
      number: 19,
      title: { ar: 'بَيْنَ يَعْقُوبَ وَأَبْنَائِهِ', en: 'Between Yaʿqūb and His Sons' },
      pages: [50, 51],
      blurb: "The brothers beg Yaʿqūb to send Binyāmīn, swearing by Allah to guard him -- and when their returned money proves al-ʿAzīz's generosity, Yaʿqūb agrees, sending them off with one last piece of fatherly caution.",
      load: () => import('./chapter-19.js'),
    },
    {
      id: 'ch20',
      number: 20,
      title: { ar: 'بِنْيَامِينُ عِنْدَ يُوسُفَ', en: 'Binyāmīn with Yūsuf' },
      pages: [51, 54],
      blurb: "Longing to keep Binyāmīn near him, Yūsuf hides his own cup in his bag and has him accused of theft -- and when the brothers beg for mercy on their old father's account, he stays silent and forbearing, refusing to take anyone but Binyāmīn himself.",
      load: () => import('./chapter-20.js'),
    },
    {
      id: 'ch21',
      number: 21,
      title: { ar: 'إِلَى يَعْقُوبَ', en: 'Back to Yaʿqūb' },
      pages: [54, 55],
      blurb: "The brothers dread facing Yaʿqūb again, and the eldest refuses to return at all -- but when Yaʿqūb hears the news, he senses Allah's hidden hand in it and answers only with patient hope that Allah, the All-Knowing and All-Wise, will return all his sons to him.",
      load: () => import('./chapter-21.js'),
    },
    {
      id: 'ch22',
      number: 22,
      title: { ar: 'يَظْهَرُ السِّرُّ', en: 'The Secret Comes Out' },
      pages: [56, 58],
      blurb: "Grief renewed, Yaʿqūb sends his sons to Egypt a third time -- and when they beg Yūsuf for relief from their poverty, he can hold back no longer, asking them outright what they did to him and his brother in their ignorance, then revealing himself and forgiving them completely.",
      load: () => import('./chapter-22.js'),
    },
    {
      id: 'ch23',
      number: 23,
      title: { ar: 'يُوسُفُ يُرْسِلُ إِلَى يَعْقُوبَ', en: 'Yūsuf Sends Word to Yaʿqūb' },
      pages: [58, 59],
      blurb: "Yūsuf's longing for his father grows unbearable now that the secret is out -- so he sends his own shirt back with the brothers, to be cast over Yaʿqūb's blind eyes so he may see again, with word to bring the whole family to Egypt.",
      load: () => import('./chapter-23.js'),
    },
    {
      id: 'ch24',
      number: 24,
      title: { ar: 'يَعْقُوبُ عِنْدَ يُوسُفَ', en: 'Yaʿqūb with Yūsuf' },
      pages: [59, 60],
      blurb: "Yaʿqūb senses Yūsuf's scent before the news even arrives, his shirt restores his sight, and the whole family reaches Egypt at last -- Yūsuf seats his parents on the throne, and the entire family bows before him, the literal fulfillment of the dream that opened his story.",
      load: () => import('./chapter-24.js'),
    },
    {
      id: 'ch25',
      number: 25,
      title: { ar: 'حُسْنُ الْعَاقِبَةِ', en: 'The Good Ending' },
      pages: [60, 61],
      blurb: "Kingship never changes Yūsuf -- he would rather die a humble servant gathered with the righteous than a king gathered with kings. His own prayer to Allah closes the story: to die submitting to Him and be joined with the righteous, a prayer the narrator answers in the very last line.",
      load: () => import('./chapter-25.js'),
    },
  ],
};
