import { card as c, rows as r, labelled as l, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '04/l1': plan(14, 'The Intransitive Verb', [
    [c('Verbs govern other elements', l(0, 'The verb’s grammatical work'), 1, 2),
      c('A regular rule applies across verbs', 3, 4, 5)],
    [c('The action stays with its doer', 0, 1, 2, l(3, 'Grieving needs no direct object'))],
    [c('Direct objects and prepositions differ', 0, 1, 2), c('Compare the two connections', 7),
      c('استمع reaches a meaning through a preposition', 3, 4, 5, 6)],
    [c('Purely intransitive qualities', 0, 1, 2),
      c('غضب connects through على', 3, 4, 5)],
    [c('Three names for the same category', 0, 1, 2)],
    [c('Other منصوب complements remain possible', 0, 1),
      c('Place, state and reason around جلس', 2, 3, 5), c('Analyse the complements of جلس', 4)],
  ], [
    ['لازم', 'Its effect does not pass to a direct مفعول به.'],
    ['Names', 'قاصر and غير متعدي describe the same category.'],
    ['Prepositions', 'استمع and غضب reach meanings indirectly. كرم، حسن، فقه are لازم صرف.'],
    ['Complements', 'A لازم verb can still have مفعول فيه، حال and مفعول له.'],
  ], { copy: {
    '0:0': 'A فعل governs: it raises فاعل or نائب فاعل, and may give نصب to complements such as مفاعيل and حال.',
    '0:4': 'قياسي follows a repeatable rule across verbs, such as the أبواب and conjugations. These lessons cover it; سماعي is a separate topic.',
    '1:1': 'A لازم verb’s effect stays with its فاعل. It needs no direct مفعول به to complete its structure.',
    '1:3': '“Nor will they grieve.” يحزنون is لازم: grieving stays with its doers.',
    '2:0': 'A مفعول به صريح is reached directly, without a حرف جر. A لازم verb does not take one.',
    '2:1': 'It may reach an object-like meaning through a preposition: التعدي بواسطة حرف الجر. This is not direct grammatical transitivity.',
    '2:4': 'استمع reaches the meaning through لام, without a direct object.',
    '2:6': 'Here it uses إلى. استمع remains لازم in direct إعراب, never taking a مفعول به صريح, while reaching an object-like meaning indirectly.',
    '3:0': 'Some لازم verbs describe intrinsic qualities or states. They do not naturally reach even an indirect object-like meaning.',
    '3:2': 'Their meanings stay with the فاعل, without passing to a مفعول به even through a حرف جر.',
    '3:3': 'غضب, “to be angry”, takes no direct مفعول به but connects to another element through a preposition.',
    '3:5': 'على carries the connection in عليهم, also in المغضوب عليهم. غضب is لازم in structure and transitive in meaning through على.',
    '4:2': 'Like لازم, both names deny a direct مفعول به.',
    '5:3': 'جلس is لازم. Three منصوب complements accompany it without becoming direct objects.',
    '5:5': 'أمام المعلم gives place; متأدبا gives the student’s state; تبجيلا للعلم gives the reason for sitting that way.',
  }, analysisItemLabels: { 'bank-18': {
    'خبر: فعل مضارع لازم وفاعله المستتر': 'خبر: مضارع لازم، وواو الجماعة فاعله',
    'خبر: فعل مضارع لازم وفاعله واو الجماعة': 'خبر: مضارع لازم، ونون النسوة فاعله',
    'مبتدأ مرفوع': 'مفعول به منصوب',
  } } }),
  '04/l2': plan(15, 'The Transitive Verb', [
    [c('The effect reaches an object', 0, 1, 2, 3), c('Locate the effect of حفظ', 4),
      c('واقع and مجاوز name the same effect', 5, 6)],
    [c('Directly, without a preposition', 0, 1, 2, 3)],
    [c('Through a preposition', 0, 1, 2),
      c('Three names for the indirect object', 3)],
    [c('Structure and meaning give different descriptions', 0, 1),
      c('Two patterns within لازم', 2, 3)],
  ], [
    ['متعدي', 'Its effect reaches a مفعول به. It is also واقع or مجاوز.'],
    ['بنفسه', 'أذهب عنّا الحزن reaches الحزن directly.'],
    ['بواسطة حرف الجر', 'ذهب الله بنورهم reaches نورهم through باء.'],
    ['Two perspectives', 'A verb can be لازم in direct إعراب and transitive in meaning through a preposition.'],
  ], { copy: {
    '0:1': 'A متعدي verb’s effect passes beyond the doer to a مفعول به.',
    '0:3': '“The student memorised the lesson.” حفظ passes from الطالب to الدرس, its مفعول به.',
    '1:0': 'متعدي بنفسه reaches the object directly, without a حرف جر.',
    '1:2': '“All praise is for Allah, who removed grief from us.” الحزن is the direct مفعول به of أذهب.',
    '2:0': 'متعدي بواسطة حرف الجر reaches an object-like meaning through a preposition.',
    '2:2': '“Allah took away their light.” ذهب reaches نورهم through باء. It is not a direct مفعول به صريح.',
    '3:0': 'لازم and متعدي can describe the same verb from different perspectives, without contradiction.',
  }, visuals: {
    '2:1': v('The same indirect connection', ['بِنُورِهِمْ', 'The preposition mediates the object-like meaning']),
  } }),
  '04/l3': plan(16, 'Patterns of Transitivity', [
    [c('هدى can reach two objects directly', 0, 1, 2), c('Identify the two direct objects', 3)],
    [c('The same verb can use إلى', 0, 1, 2),
      c('Compare the two constructions', 3)],
    [c('A possible difference in nuance', l(0, 'Direct guidance'), l(1, 'Guidance toward an endpoint'), 2),
      c('Supplication and showing the path', l(3, 'The request in دعاء'), l(4, 'The Prophet’s guidance'))],
    [c('Does the endpoint belong to the action?', l(0, 'انتهاء الغاية'), l(1, 'Why context matters'))],
    [c('Count object positions', 0, 1),
      c('Coordination does not add an object position', 2, 3, 4), c('Analyse the coordinated object', 5)],
  ], [
    ['One verb, two patterns', 'هدى can take a direct second object or reach it through إلى.'],
    ['Nuance', 'The direct prayer asks to be placed on the path. This interpretation is a reflection.'],
    ['إلى', 'It marks an endpoint; context decides whether that endpoint is included.'],
    ['Object count', 'متعدي takes one, two or three objects. عطف alone adds no separate object position.'],
  ], { analysisLabels: {
    'جار ومجرور، في معنى المفعول به الثاني (غير صريح)': 'جار ومجرور؛ مفعول ثان غير صريح',
    'جار ومجرور، في معنى المفعول به الأول (غير صريح)': 'جار ومجرور؛ مفعول أول غير صريح',
    'مفعول به ثانٍ، متصل بالفعل مباشرة': 'مفعول ثان متصل مباشرة بالفعل',
  }, copy: {
    '0:2': '“Guide us to the straight path.” اهد is أمر from هدى يهدي هداية. نا is the first object; الصراط المستقيم is the second. Both connect directly.',
    '1:1': '“And He guided him to a straight path.” ه is still the direct first object; صراط مستقيم is reached through إلى, as مفعول به غير صريح.',
    '2:0': 'اهْدِنَا الصِّرَاطَ المُسْتَقِيمَ asks to be placed firmly upon the path itself.',
    '2:1': 'وَهَدَاهُ إِلَى صِرَاطٍ مُسْتَقِيمٍ can express direction toward an endpoint. إلى marks انتهاء الغاية; context determines whether the endpoint is included.',
    '2:3': 'دعاء uses اهدنا الصراط المستقيم, rather than اهدنا إلى الصراط المستقيم. Asking to be placed on the path carries more تضرع and leaves no doubt about reaching the objective.',
    '2:4': 'وَإِنَّكَ لَتَهْدِي إِلَى صِرَاطٍ مُسْتَقِيمٍ describes the Prophet ﷺ showing people the path and bringing them to it. They choose whether to step onto it.',
    '3:1': '“Up to the elbows” raises whether the elbows are included. Direct government without إلى would make inclusion more direct. A preposition can therefore affect meaning.',
    '4:2': 'A متعدي إلى مفعول واحد takes one object position.',
    '4:4': '“He created the heavens and the earth.” السماوات and الأرض are joined by عطف in one object category. They are not two independent مفاعيل.',
  }, boxCopy: {
    '2:2': ['These constructions can differ in nuance. This reading is a reflection from the language’s قواعد, not a settled ruling. والله أعلم بالصواب.'],
  }, visuals: {
    '2:1': v('The distinction under discussion', ['اهْدِنَا الصِّرَاطَ', 'A request to be placed upon it'], ['تَهْدِي إِلَى صِرَاطٍ', 'Showing people the way']),
    '3:0': v('An endpoint raises a contextual question', ['إِلَى المَرَافِقِ', 'Are the elbows included?']),
  } }),
  '04/l4': plan(17, 'Verbs with Two Objects', [
    [c('A verb can take two objects', 0, 1, 2), c('Ask what the objects were originally', 3)],
    [c('Two objects that were not مبتدأ and خبر', 0, 1, 2), c('Locate the receiver and the guidance', 3),
      c('A receiver and something given', 4, r(5, 0, 1, 2, 3)),
      c('Giving can mean clothing, naming or teaching', r(5, 4, 5, 6, 7))],
    [c('Context can supply an omitted object', 0, 1, r(2, 0), 4),
      c('Omit the second object or both', r(2, 1, 2), 3)],
    [c('Direct and indirect second objects', 0, 1),
      c('إلى and the endpoint in washing', 2, 3, 4)],
    [c('ظن changes a مبتدأ and خبر into objects', 0, 1, 2), c('Analyse the two objects of ظن', 3),
      c('Find the original statement', 4, 5)],
    [c('Sensory action, judgement or change', 0, 1),
      c('Three names follow the verb’s meaning', 2, 3),
      c('Why رأى needs an explicit label', 4, 5, 6)],
  ], [
    ['Two categories', 'Ask whether the objects were originally مبتدأ and خبر.'],
    ['Giving', 'One object receives the other. Context can supply either or both omitted objects.'],
    ['Judgement', 'ظن turns خالد صادق into خالدًا صادقًا.'],
    ['Meaning decides', 'جارحة is sensory; قلب is judgement; تحويل is change. رأى needs its intended sense stated.'],
  ], { copy: {
    '0:0': 'Of verbs taking one, two or three objects, this lesson concerns the second type.',
    '0:2': 'A two-object verb belongs to one of two categories.',
    '1:2': '“And We guided them both to the straight path.” These objects were not مبتدأ and خبر. Guidance is given and directed to the path: هديناهم بمعنى أعطيناهم الهداية.',
    '1:4': 'Giving, granting, clothing, teaching, naming, providing or directing can follow this pattern: a receiver and the thing given.',
    '2:0': 'Context may supply either object, or both.',
    '2:4': 'The full sense is وَإِنَّكَ لَتَهْدِي النَّاسَ إِلَى صِرَاطٍ مُسْتَقِيمٍ. الناس is omitted; إلى صراط مستقيم reaches the second object indirectly.',
    '3:1': 'An object reached through a preposition is غير صريح, also called مفعول بواسطة حرف الجر.',
    '3:2': 'The question of including an endpoint also appears in the آية of وضوء.',
    '3:4': '“And your arms up to the elbows.” Most scholars include washing the elbows as فرض. A small minority disagrees because إلى need not include its endpoint.',
    '4:2': '“Ahmad thought Khalid truthful.” خالد صادق was مبتدأ and خبر; ظن turns them into two objects.',
    '4:5': '“And I do not think the Hour will be established.” الساعة قائمة was مبتدأ and خبر. After أظن, الساعة is first object and قائمة second.',
    '5:1': 'جرح يجرح جرحا means “to wound”. جوارح are bodily limbs; فعل الجارحة describes sensory acts performed through them.',
    '5:4': 'جارحة is the default for sensory verbs such as سمع، مشى، أكل and شم. Its label is usually omitted unless the verb has another reading.',
    '5:6': 'رأى can mean either seeing or inner judgement, so its intended reading must be labelled.',
  }, boxCopy: {
    '5:0': ['فعل الجارحة: ليس مفعولاه مبتدأ وخبرًا في الأصل؛ يزاول بالجوارح من الأفعال الحسية.', 'فعل القلب أو التحويل: مفعولاه مبتدأ وخبر في الأصل.'],
  }, visuals: {
    '4:2': v('Before and after أظن', ['السَّاعَةُ قَائِمَةٌ', 'مبتدأ وخبر'], ['السَّاعَةَ قَائِمَةً', 'Two objects']),
  }, analysisLabels: {
    'جار ومجرور، في معنى المفعول به الثاني (غير صريح)': 'جار ومجرور؛ مفعول ثان غير صريح',
  } }),
};

export const checks = {
  '04/l1': [
    q('What does مطردة mean in قاعدة مطردة?', ['A repeatable rule across many verbs.', 'A rule for only one verb.', 'A rule only valid in poetry.', 'A rule only for أمر.'], 'Think of shared أبواب and conjugations.'),
    q('Does يحزنون in ولا هم يحزنون reach a direct object?', ['No; grief stays with the doers: لازم.', 'Yes; هم is its direct object.', 'Yes; ون always marks transitivity.', 'No; it has no فاعل.'], 'Follow the effect of grieving.'),
    q('استمع uses لام or إلى. Is it directly متعدي?', ['No; it is لازم in direct إعراب.', 'Yes; any following اسم is an object.', 'Yes; لام and إلى always make it متعدي.', 'No; it has no فاعل.'], 'A direct object has no mediating preposition.'),
    q('كرم، حسن، فقه do not reach even an indirect object. What are they?', ['لازم صرف', 'متعدي بنفسه', 'متعدي بواسطة حرف الجر', 'أفعال ناقصة'], 'Compare them with غضب عليهم.'),
    q('قاصر and غير متعدي are names for which category?', null, 'Both deny a direct مفعول به.'),
    q('Can جلس have منصوب complements while remaining لازم?', ['Yes: مفعول فيه، حال and مفعول له.', 'No منصوب complement is possible.', 'Only حال is possible.', 'Only مفعول فيه is possible.'], 'Only the direct مفعول به is excluded.'),
  ],
  '04/l2': [q('What does حفظ reach in حفظ الطالب الدرس?', null, 'Identify what receives the effect.'),
    q('أذهب reaches الحزن without a preposition. Which type?', null, 'Direct connection needs no حرف جر.'),
    q('ذهب الله بنورهم reaches نورهم through باء. Which object?', ['مفعول به غير صريح', 'مفعول به صريح', 'فاعل', 'حال'], 'The preposition mediates the connection.'),
    q('What is استمع called by meaning when it reaches through لام or إلى?', null, 'Structure and meaning are different perspectives.')],
  '04/l3': [
    q('Does الصراط المستقيم in اهدنا الصراط المستقيم need a حرف جر?', ['No; it is a direct second object.', 'Yes; only إلى can reach it.', 'No; it is the فاعل.', 'Yes; it is مضاف إليه.'], 'Identify the connection after اهد.'),
    q('How does the second object differ in اهدنا الصراط and هداه إلى صراط?', ['Direct in the first; through إلى in the second.', 'Only the first reaches any object.', 'Neither reaches a second object.', 'Both connect in exactly the same way.'], 'Compare صريح with غير صريح.'),
    q('What nuance is proposed for اهدنا الصراط compared with تهدي إلى صراط?', ['Placement on the path versus direction toward it.', 'No difference in meaning.', 'A change from ماضي to أمر only.', 'إلى is a حرف عطف here.'], 'The lesson presents this as a reflection, not a settled ruling.'),
    q('Does إلى alone settle whether its endpoint is included?', ['No; context can decide.', 'Yes; it always excludes it.', 'Yes; it always includes it.', 'إلى never marks an endpoint.'], 'Distinguish marking an endpoint from including it.'),
    q('Does خلق السماوات والأرض have two independent objects?', ['No; the nouns share one object position by عطف.', 'Yes; و always adds an independent object.', 'No; الأرض is the فاعل.', 'Yes; الأرض is another فعل.'], 'Count grammatical positions, not joined nouns.'),
  ],
  '04/l4': [
    q('What separates the two categories of two-object verbs?', ['Were the objects originally مبتدأ and خبر?', 'Is the verb ماضي or مضارع?', 'Does the verb take a حرف جر?', 'Is the فاعل masculine or feminine?'], 'Recover the objects’ original relationship.'),
    q('Were هما and الصراط in هديناهما الصراط originally مبتدأ and خبر?', ['No; the sense is أعطيناهم الهداية.', 'Yes; هما was مبتدأ and الصراط خبر.', 'Yes; الصراط was مبتدأ and هما خبر.', 'There are no objects here.'], 'This follows the giving pattern.'),
    q('هدَاهم الله mentions who was guided, but no destination. What is omitted?', ['The second object.', 'The first object.', 'Both objects.', 'Neither object.'], 'هم already names the people guided.'),
    q('What grammatical question arises from إلى المرافق?', ['Does إلى include the endpoint?', 'Is أيديكم singular or plural?', 'Is المرافق masculine or feminine?', 'Is the verb passive?'], 'The issue concerns انتهاء الغاية.'),
    q('What were خالدًا and صادقًا before ظن entered?', ['مبتدأ وخبر: خالد صادق.', 'مضاف ومضاف إليه.', 'فاعل ومفعول به.', 'Entirely unrelated words.'], 'Restore the original statement.'),
    q('Why label رأى when سمع، مشى، أكل and شم need no label?', ['رأى can be sensory or an inner judgement.', 'رأى is the only sensory verb.', 'رأى is never a sensory verb.', 'The other words are not verbs.'], 'The label identifies the intended meaning.'),
  ],
};

export const quizzes = {
  '04/l1': [q('What defines فعل لازم?', ['No effect passes to a direct مفعول به.', 'Its effect passes to a مفعول به.', 'Its government must be memorised individually.', 'It always takes two objects.']), q('يحزنون in ولا هم يحزنون keeps grief with its doers. Which type?'), q('What is the indirect connection in فاستمعوا له called?'), q('What are كرم، حسن and فقه called when they reach no indirect object?'), q('قاصر and غير متعدي name which category?'), q('جلس الطالب أمام المعلم متأدبا تبجيلا للعلم has which three complements?')],
  '04/l2': [q('What defines فعل متعدي?', ['Its effect reaches a مفعول به.', 'Its effect reaches no مفعول به.', 'It always needs a حرف جر.', 'It appears only as أمر.']), q('Which is the object in حفظ الطالب الدرس?'), q('واقع and مجاوز name which verb category?'), q('أذهب reaches الحزن directly in أذهب عنا الحزن. Which type?'), q('Which object type is reached through باء in ذهب الله بنورهم?'), q('What is استمع called by meaning when it connects through a preposition?')],
  '04/l3': [q('Which wording reaches the second object directly?'), q('Which object type occurs through إلى in وهداه إلى صراط مستقيم?'), q('What nuance does direct اهدنا الصراط add in this reflection?', ['More تضرع; reaching the objective is explicit.', 'A weaker request, leaving arrival uncertain.', 'A shift from أمر to ماضي.', 'No nuance; the constructions are identical.']), q('What does انتهاء الغاية mean?'), q('What are the three object counts for متعدي?', ['One, two or three مفاعيل.', 'لازم، بنفسه، بواسطة حرف الجر.', 'واقع، مجاوز، قاصر.', 'ماضي، مضارع، أمر.']), q('Does عطف in خلق السماوات والأرض make two object positions?', ['No; both share one object position.', 'Yes; عطف always adds a separate object.', 'No; خلق is لازم here.', 'Yes; الأرض is a second independent object.'])],
  '04/l4': [q('What divides two-object verbs into two categories?', ['Whether the objects were مبتدأ and خبر.', 'Whether the verb is سماعي or قياسي.', 'Whether it takes three objects.', 'Whether its فاعل is stated or hidden.']), q('Which category includes وهديناهما الصراط المستقيم?'), q('Which object is omitted in أولئك الذين هداهم الله?', ['The second: where they were guided.', 'The first: who was guided.', 'Both people and destination.', 'Neither; both are explicit.']), q('What grammatical question arises from إلى المرافق?', ['Whether إلى includes its endpoint.', 'Whether أيديكم is singular.', 'Whether المرافق takes تنوين.', 'Whether the verb is أمر.']), q('What were خالدًا صادقًا before ظن in ظن أحمد خالدًا صادقًا?'), q('Which labels distinguish the two meanings of رأى?')],
};
