import { card as c, rows as r, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '20/l1': plan(97, 'How a مصدر Governs', [
    [c('Nouns that work like verbs', 0, 1, 2)],
    [c('A مصدر in إضافة', 0, 1, 2), c('Added to the doer', 3, 4), c('Added to the object', 5, 6), c('Added to the time', 7, 8)],
    [c('A nunated مصدر can govern', 0, 1, 2, 3), c('A مصدر with أل', 4, 5, 6, 7)],
    [c('The مصدر can omit its doer', 0, 1, 2), c('No doer is encoded in حجّ البيت', 3, 4)],
    [c('The normal order and its exception', 0, 1, 2), c('The disputed analysis of معه', 3, 4)],
  ], [
    ['شبه الفعل', 'مصدر, verbal derivatives, and nouns with a verb’s meaning.'],
    ['إضافة', 'The genitive may represent a doer, object or circumstance.'],
    ['Other forms', 'A nunated مصدر can govern; government with أل is less common and disputed.'],
    ['Doer and order', 'The doer can be omitted; fronted circumstances require the stated qualification.'],
  ], { copy: {
    '0:0': 'The source now studies الاسم العامل: nouns governing other words. Its branch of nouns governing nouns includes شبه الفعل, which works like a verb.',
    '0:2': 'Three groups: المصدر, naming an event without tense; verbal derivatives such as اسم الفاعل, اسم المفعول, الصفة المشبهة and اسم التفضيل; and nouns with verbal meaning, chiefly اسم الفعل. Each has its own conditions.',
    '1:0': 'The common construction is إضافة to a معمول.',
    '1:2': 'The following word is genuinely مجرور as مضاف إليه. In meaning it may supply the event’s doer, object or another role, such as a time circumstance. Surface case and semantic role are distinct.',
    '1:4': '“Like your remembrance of your forefathers.” ذكر is the مصدر; كم supplies the remembering people through إضافة. آباءكم is its منصوب object.',
    '1:6': '“Due to Allah from the people is pilgrimage to the House.” حجّ is the مصدر; البيت is its semantic object, not the pilgrim doing the action.',
    '1:8': '“Scheming by night and day.” الليل والنهار give the time of scheming: ظرف in meaning. They are neither the schemers nor their victims.',
    '2:0': 'إضافة is not required for government.',
    '2:3': '“Feeding a related orphan on a day of hunger.” Nunated إطعام governs يتيمًا as object. في يوم ذي مسغبة is a prepositional time phrase attached to it, not a bare منصوب مفعول فيه.',
    '2:4': 'The source calls government with أل شاذّ; other accounts permit it but describe it as uncommon. Avoid treating the claims “no Quran example” and “only one poem” as an exhaustive inventory.',
    '2:7': '“How can one guard against the back of what one rides?” التوقّي carries أل and governs ظهرَ as object. This is the poetic example used for the less common construction.',
    '3:0': 'Verbal derivatives normally retain a grammatical subject, overt or hidden. Passive derivatives take نائب فاعل instead of فاعل.',
    '3:2': 'The مصدر differs: its doer can be omitted without appointing a replacement. This rule concerns the verbal nouns compared here, not every possible governing noun.',
    '3:4': 'حجّ البيت does not grammatically encode the pilgrim as a hidden pronoun. البيت is the object in meaning. Compare حاجّ, whose verbal use includes a subject, even when hidden.',
    '4:0': 'The ordinary rule places the مصدر before its معمول.',
    '4:2': 'The source allows a fronted ظرف and attributes this to the majority. Grammarians differ over extending the usual flexibility of circumstances and prepositional phrases to this construction.',
    '4:4': '“When he reached the age of striving with him.” The source attaches معه to السعي, despite preceding it; السعي is itself governed by بلغ. Another account supplies an omitted verb explaining “striving with whom”, avoiding a fronted معمول of the مصدر. Practice uses the source’s stated analysis.',
  }, boxCopy: {
    '0:1': ['شبه الفعل: مصدر، ومشتقات بمعنى الفعل، وأسماء فيها معنى الفعل.'],
    '1:1': ['يضاف المصدر إلى فاعله أو مفعوله أو غيرهما.'],
    '3:1': ['يجوز حذف فاعل المصدر بلا نائب.'],
    '4:1': ['الأصل تأخير المعمول؛ وفي تقديم الظرف خلاف.'],
  }, analysisItemLabels: { 'bank-15': { 'مفعول به منصوب': 'مفعول مطلق منصوب' } } }),
  '20/l2': plan(98, 'Active and Passive Participles', [
    [c('Five verbal derivatives', 0, 1, 2), c('An overt subject of الظالم', 3, 4), c('A hidden subject of خالق', 5, 6)],
    [c('اسم الفاعل follows the active verb', 0, 1, 2, 3)],
    [c('Government with أل', 0, 1, 2), c('An overt subject with أل', 3, 4), c('An object with أل', 5, 6)],
    [c('Government without أل', 0, 1), c('Reliance on a nominal subject', r(2, 0), 3), c('Reliance after a ناسخ', r(2, 1), 4), c('حال, question and negation', r(2, 2, 3, 4))],
    [c('Case depends on the role', 0, 1), c('A quality expressed through إضافة', 2, 3), c('An object after a separating phrase', 4, 5)],
    [c('Passive government', 0, 1, 2, 3), c('Keep فاعل and نائب فاعل distinct', 4, 5)],
  ], [
    ['اسم الفاعل', 'Works like its active verb, with a doer and any objects that verb permits.'],
    ['With أل', 'The ordinary time and reliance restrictions do not apply.'],
    ['Without أل', 'Present/future meaning and reliance are required for the government studied.'],
    ['اسم المفعول', 'Works like the passive verb and raises a نائب فاعل.'],
  ], { copy: {
    '0:0': 'The five derivatives here are اسم الفاعل, اسم المفعول, صيغة المبالغة, الصفة المشبهة and اسم التفضيل. Derived time/place and instrument nouns do not automatically govern in this way.',
    '0:2': 'A verbal derivative normally includes an overt or hidden subject. اسم المفعول has a نائب فاعل, correcting the source’s blanket use of فاعل for all five.',
    '0:4': '“Take us out of this city whose people oppress.” الظالم is اسم فاعل; أهلها is its overt فاعل.',
    '0:6': '“I am going to create a human being.” خالق includes the hidden subject أنا, referring to the speaker.',
    '1:1': 'The active participle has its active verb’s governing pattern, when the conditions are met.',
    '1:3': 'خلق يخلق takes an object; خالق therefore governs بشرًا as object in إنّي خالق بشرا.',
    '2:0': 'First distinguish the participle with أل from one without it.',
    '2:2': 'With the relevant أل, government is not restricted by the present/future and reliance conditions taught for the bare participle. It can govern an overt or hidden subject and the objects its verb allows.',
    '2:4': 'الظالم carries أل, so أهلها can appear as its overt subject without the bare-participle conditions.',
    '2:6': '“Those reciting the message.” التاليات carries أل and governs ذكرًا as object.',
    '3:1': 'A bare participle can retain a hidden subject. For an overt subject or object in this account, it needs present/future meaning and reliance: on a subject, its equivalent after a ناسخ, a حال’s owner, a question or negation. These are the five environments illustrated.',
    '3:3': 'باسط relies on the subject كلبهم and governs ذراعيه. Though the story is past, حكاية الحال presents the dog’s posture vividly as current, satisfying the intended-time condition.',
    '3:4': 'آثم relies on اسم إنّ, treated like the earlier مبتدأ before the ناسخ. قلبه is its overt subject.',
    '4:1': 'رفع, نصب and إضافة are not free choices for the same ordinary object. A subject has رفع; a direct object takes نصب or, where permitted, إضافة. Separation can block that إضافة, but does not force every separated subject into نصب.',
    '4:3': '“Your Lord is vast in forgiveness.” واسع المغفرة is a stable-quality use, handled like الصفة المشبهة. المغفرة is genitive through إضافة and the bearer of vastness in meaning: “His forgiveness is vast”.',
    '4:5': '“I will place a successor on earth.” جاعلٌ retains tanwin and في الأرض intervenes. خليفةً is the object in نصب; it is not a مضاف إليه in this construction.',
    '5:1': 'The passive participle follows its passive verb’s government. It raises a نائب فاعل, with comparable time and reliance conditions where relevant.',
    '5:3': '“A Day for which the people are gathered.” مجموع derives from جُمع; الناس is its نائب فاعل. The intervening له does not make الناس an accusative object.',
    '5:5': 'اسم الفاعل has a doer; اسم المفعول has a نائب فاعل. Their conditions are comparable, but the grammatical roles must not be collapsed into one indiscriminate رفع/نصب/إضافة choice.',
  }, boxCopy: {
    '0:1': ['للمشتق العامل فاعل ظاهر أو مستتر؛ وللمفعول نائب فاعل.'],
    '2:1': ['مع أل يعمل دون شرطي الزمن والاعتماد الآتيين.'],
    '3:0': ['بلا أل: للحال أو الاستقبال، مع الاعتماد، في العمل المذكور.'],
    '4:0': ['رفع الفاعل؛ ونصب المفعول أو إضافته حيث تصح الإضافة.'],
  }, analysisItemLabels: { 'bank-20': { 'مفعول به منصوب': 'مفعول مطلق منصوب' } } }),
  '20/l3': plan(99, 'The Resembling Adjective', [
    [c('A stable quality from an intransitive verb', 0, 1, 2), c('Intensity and stable quality', 3, 4), c('Compare المطيع and الحسن', 5, 6, 7, 8)],
    [c('Four treatments of the related noun', 0, 1, 2), c('The related noun as فاعل', 3, 4), c('A definite noun in نصب', 5, 6)],
    [c('An indefinite noun as تمييز', 0, 1, 2, 3), c('The related noun in إضافة', 4, 5)],
    [c('A change of construction for emphasis', 0, 1), c('نصب on praise', 2, 3, 4)],
  ], [
    ['صفة مشبهة', 'Typically an intransitive quality presented as stable.'],
    ['رفع / نصب', 'فاعل in رفع; a definite شبه مفعول or indefinite تمييز in نصب.'],
    ['جر', 'إضافة is another permitted construction, with its own restrictions.'],
    ['Meaning and syntax', 'A semantic doer is not automatically a grammatical فاعل in every construction.'],
  ], { copy: {
    '0:0': 'الصفة المشبهة باسم الفاعل typically derives from a لازم verb and presents a quality as stable.',
    '0:3': 'صيغة المبالغة foregrounds intensity or frequency; many transitive examples take a genuine object. It is not restricted absolutely to transitive roots.',
    '0:4': 'A stable intransitive quality normally describes its bearer. The related noun may nevertheless appear in نصب resembling an object construction. That governing resemblance explains the name; stability does not mean literal permanence in every context.',
    '0:6': 'المطيع أباه is the active-participle comparison: أطاع is transitive, and أباه is its real object. المطيع is not the صفة مشبهة in this pair.',
    '0:8': 'الحسن الوجهَ instead comes from a quality of being handsome. الوجهَ is منصوب as شبيه بالمفعول به, while remaining the bearer of beauty in meaning.',
    '1:0': 'The same underlying quality relation permits several distinct constructions, subject to their rules.',
    '1:2': 'Two are illustrated first: رفع as a grammatical subject, and نصب of a definite related noun as شبيه بالمفعول به. The remaining two are تمييز and إضافة.',
    '1:4': '“Allah is swift in His reckoning.” حسابُه is the grammatical فاعل of سريع.',
    '1:6': 'حسابَه is definite through ـه and منصوب as شبيه بالمفعول به. It is a doer in meaning, not a noun simultaneously منصوب لفظا ومرفوع محلا. The source connects the construction with emphasis.',
    '2:0': 'Now compare the indefinite منصوب and the genitive construction.',
    '2:1': 'A bare indefinite related noun can be منصوب as تمييز. إضافة instead gives the related noun جر, with its connection to the bearer understood.',
    '2:3': 'حسابًا is indefinite, so its نصب is classified as تمييز in this pattern.',
    '2:5': 'الحسابِ is مجرور through إضافة in سريع الحساب. The source interprets أل as supplying the link expressed by ـه in حسابه. The semantic bearer remains reckoning; this does not make its actual genitive syntax رفع.',
    '3:1': 'Established constructions can alter case to convey praise or emphasis while preserving an intelligible relation. This is not permission to change endings freely whenever the reader can guess the meaning.',
    '3:3': 'والصابرين في البأساء والضراء is منصوب على المدح: a cut to praise, conventionally supplying أمدح or أخص. The absence of a visible nearby governor does not mean no governor is analyzed.',
    '3:4': 'The source compares this with recognized تابع and صفة مشبهة patterns. Simply reversing ordinary subject and object endings would instead change who did what; it is not the same construction.',
  }, boxCopy: {
    '0:1': ['الصفة المشبهة تشبه اسم الفاعل المتعدي في بعض العمل.'],
    '0:2': ['أصلها وصف لازم يفيد الثبوت النسبي.'],
    '1:1': ['رفع فاعل، أو نصب شبه مفعول أو تمييز، أو جر بالإضافة.'],
    '3:0': ['للمدح والمبالغة تراكيب مقيدة، لا تغيير حر للإعراب.'],
  }, analysisItemLabels: { 'bank-15': { 'صفة مشبهة': 'اسم فاعل من أطاع', 'فاعل منصوب لفظًا لتأكيد المبالغة': 'مفعول به منصوب', 'اسم فاعل': 'صفة مشبهة من فعل لازم', 'مفعول به': 'نائب فاعل مرفوع' } } }),
  '20/l4': plan(100, 'Comparison with اسم التفضيل', [
    [c('Three parts of a comparison', 0, 1, 2, 3), c('Zayd and Amr in the comparison', 4, 5)],
    [c('A hidden subject is usual', 0, 1), c('The مسألة الكحل pattern', 2, 3)],
    [c('Kohl compared in two settings', 0, 1, 2)],
    [c('With comparative مِن', 0, 1, 2), c('A compound compared subject', 3, 4), c('A feminine compared subject', 5, 6)],
    [c('Two kinds of إضافة', 0, 1), c('Added to an indefinite noun', 2, 3), c('Added to a definite noun: singular', 4, 5), c('Added to a definite noun: agreement', 6, 7)],
    [c('With أل: agreement', 0, 1, 2, 3), c('Compare the agreement rules', 4, 5)],
  ], [
    ['Three parts', 'Comparison word, preferred entity, and comparison standard.'],
    ['Subject', 'Usually hidden; the الكحل pattern permits an overt subject.'],
    ['مِن / indefinite إضافة', 'Singular masculine in the ordinary comparative patterns.'],
    ['Definite إضافة / أل', 'Two options with comparative definite إضافة; agreement with أل.'],
  ], { copy: {
    '0:0': 'اسم التفضيل includes أحسن، أكبر and أفضل. It has restricted verbal government, not every freedom of an ordinary verb.',
    '0:3': 'Identify the quality word, المفضّل, and المفضّل عليه. A usually hidden subject represents the compared entity; a preceding named noun may itself be مبتدأ.',
    '0:5': '“Zayd is better than Amr.” أفضل is اسم التفضيل, with hidden هو referring to Zayd. Zayd is المفضّل; Amr after مِن is المفضّل عليه.',
    '1:1': 'A hidden subject is usual. مسألة الكحل names an exceptional construction, not just one memorized sentence; comparable examples follow the pattern.',
    '1:3': 'The pattern taught has negation, then a generic noun described by اسم التفضيل, then an entity compared with itself in two settings. Related interrogative and prohibitive forms are discussed by grammarians too.',
    '2:1': '“I have seen no man in whose eye kohl is more beautiful than in Zayd’s.” ما negates; رجلًا is the generic noun described by أحسن; الكحلُ is the latter’s overt subject.',
    '2:2': 'Kohl is compared in the man’s eye and in Zayd’s. It appears once as الكحل and again through ـه in منه, not as the same explicit noun written twice. This self-comparison across settings licenses the pattern.',
    '3:0': 'Compare three main forms: bare with مِن, إضافة, and أل.',
    '3:2': 'In the bare comparative construction with مِن, اسم التفضيل stays singular masculine despite the compared noun’s gender or number.',
    '3:4': '“Yusuf and his brother are more beloved to our father than we are.” أحب stays singular masculine although two people are compared.',
    '3:6': '“Every sign We show is greater than its sister.” أكبر stays singular masculine despite feminine آية, because of the bare comparative construction with مِن.',
    '4:1': 'Added to an indefinite noun: singular masculine. Added to a definite noun while retaining comparative meaning: singular masculine or agreement. The meaning must still support the chosen construction.',
    '4:3': 'أول كافر به addresses a plural audience but keeps أول singular masculine because كافر is indefinite.',
    '4:5': 'أحرص الناس على حياة uses singular masculine أحرص for plural هم, a permitted option with definite الناس.',
    '4:7': 'هم أراذلنا uses plural أراذل with هم: the agreement option in this definite إضافة.',
    '5:1': 'When اسم التفضيل carries أل in the pattern taught, it agrees in gender and number.',
    '5:3': '“He enters the greatest Fire.” Feminine الكبرى matches النار; الكبرى itself carries أل.',
    '5:5': 'With مِن or indefinite إضافة, keep singular masculine. Definite إضافة in comparative meaning permits the two options. With أل, use agreement. A non-comparative descriptive use may have further constraints.',
  }, boxCopy: {
    '0:1': ['اسم التفضيل: نحو أحسن، أكبر، أفضل.'],
    '0:2': ['أركانه: اسم التفضيل، والمفضّل، والمفضّل عليه.'],
    '1:0': ['فاعله غالبا مستتر، ويظهر في نمط مسألة الكحل.'],
    '1:2': ['نفي، ثم اسم جنس موصوف بالتفضيل، ثم تفضيل الشيء على نفسه باعتبارين.'],
    '4:0': ['إضافة لنكرة: إفراد وتذكير. لمعرفة مع التفضيل: ذلك أو المطابقة.'],
    '5:4': ['مِن أو إضافة لنكرة: مفرد مذكر. معرفة: خياران. أل: مطابقة.'],
  }, analysisPrompt: 'Identify the comparison roles.', analysisItemLabels: { 'bank-14': { 'مبتدأ': 'مفعول به' }, 'bank-15': { 'مبتدأ': 'مفعول به' } } }),
  '20/l5': plan(101, 'Words That Act as Verbs', [
    [c('اسم الفعل takes a verb’s meaning', 0, 1, 2)],
    [c('Government follows the meaning', 0, 1), c('هيهات has an intransitive meaning', 2, 3), c('بله has a transitive meaning', 4, 5)],
    [c('Past, present and command meanings', 0, r(1, 0, 1, 2), 2)],
    [c('مرتجل is learned from attested usage', 0, 1, 2), c('Distance, respite and calling', r(3, 0, 1, 2)), c('Responding, stopping and silence', r(3, 3, 4, 5, 6)), c('Notice the construction in each example', 4, 5)],
    [c('منقول has another grammatical origin', 0, 1), c('From a prepositional phrase or ظرف', r(2, 0, 1)), c('From a مصدر or attention word', r(2, 2, 3)), c('Forms addressed to different people', 3, 4, 5)],
  ], [
    ['اسم الفعل', 'Governs according to its verb meaning.'],
    ['Meaning', 'Can represent past, present or command: هيهات، أفّ، آمين.'],
    ['Origin', 'مرتجل is attested as such; منقول has another grammatical origin.'],
    ['Address', 'Some forms vary with the addressee, but origin alone does not decide this.'],
  ], { copy: {
    '0:0': 'The third شبه الفعل group includes nouns with verbal meaning, chiefly اسم الفعل: هيهات، صه and آمين.',
    '0:2': 'It acts with the meaning of a particular verb. That verb is a gloss, not necessarily an additional omitted governor: اسم الفعل itself governs in this analysis.',
    '1:1': 'An intransitive meaning raises a subject. A transitive meaning can also govern an object, following its corresponding verb.',
    '1:3': 'هيهات means بَعُد: “Far is what you are promised.” In the زائد-لام analysis, ما is the subject, with لام giving outward جر. Calling لام زائد does not mean the whole phrase is an ordinary direct object or that جر disappears.',
    '1:5': 'بله الشرّ means “Leave evil aside”. The gloss اترك is transitive, so الشرّ is an object.',
    '2:2': 'هيهات means past بَعُد. In فلا تقل لهما أفّ, أفّ expresses أتضجّر, “I am annoyed”. آمين means استجب, a request to respond.',
    '3:0': 'The next distinction concerns origin: مرتجل or منقول.',
    '3:2': 'مرتجل forms are learned from attested speech, not freely invented by analogy. The source’s list also includes رويد, commonly analyzed as transferred from a مصدر; learn that qualification with the example.',
    '3:5': 'أمهلهم رويدًا means “Give them a little respite”; nunated رويدًا has a مصدر-related analysis, developed next lesson. هلم شهداءكم means “Bring your witnesses”, with شهداءكم as object. Hijazi هلم stays fixed; Tamimi هلم is treated as an inflecting imperative.',
    '4:1': 'A transferred form has a different earlier grammatical use. The origin does not guarantee one uniform pattern of variation.',
    '4:3': 'عليك، عليكِ، عليكما، عليكم، عليكن vary the address ending. Compare دونكَ and دونكِ for direct commands. The source’s دونه ودونهم are third-person forms, not equivalent addressee endings in “take!”.',
    '4:5': 'بله الشر يا زينب and بله الشر يا أحمد keep بله fixed. It is nevertheless commonly analyzed as transferred from a مصدر, as the table says. Variation of كاف الخطاب is not ordinary verb conjugation, and “منقول always varies” is not a valid rule.',
  }, boxCopy: {
    '0:1': ['اسم الفعل يعمل عمل الفعل الذي يدل على معناه.'],
    '1:0': ['يرفع فاعلا، وينصب مفعولا إن كان معناه متعديا.'],
    '3:1': ['المرتجل موضوع لاسم الفعل، والمنقول له أصل آخر.'],
    '4:0': ['من أصول المنقول: جار ومجرور، ظرف، مصدر، تنبيه.'],
    '4:4': ['قد تختلف علامة الخطاب، نحو عليكما؛ وتبقى صيغ أخرى ثابتة.'],
  }, tableCopy: { '3:3': { 1: ['رويدَ', 'أمهل؛ يعدّه كثيرون منقولا من مصدر.'] } }, analysisItemLabels: { 'bank-15': { 'فاعل لاسم الفعل': 'اللام زائدة؛ ما في محل رفع فاعل' } } }),
  '20/l6': plan(102, 'Further Rules of اسم الفعل', [
    [c('Tanwin can distinguish a مصدر use', 0, 1, 2), c('The مصدر account of رويدًا', 3, 4)],
    [c('Two accounts of هلم إلينا', 0, 1)],
    [c('The productive pattern فَعَالِ', 0, 1, 2), c('نزالِ means انزل', 3, 4)],
    [c('Keep the معمول after اسم الفعل', 0, 1, 2, 3), c('لام التقوية is not a workaround', 4, 5)],
  ], [
    ['بله / رويد', 'Read tanwin and the following noun together.'],
    ['هلم إلينا', '“Come”, or “bring yourself” with an understood object.'],
    ['فَعَالِ', 'An analogical command pattern from eligible triliteral verbs.'],
    ['Order', 'Keep the معمول after اسم الفعل; لام does not license fronting here.'],
  ], { copy: {
    '0:0': 'Tanwin can mark a different construction, not merely a sound change.',
    '0:2': 'بله الشرّ and رويد لمفلس are treated as command-like اسم فعل examples. In بلهًا أخاك and رويدًا المفلسَ, the source adopts a مصدر منصوب by an omitted verb. Absence of tanwin alone is insufficient: a مصدر in إضافة also lacks it.',
    '0:4': 'The مصدر account calls رويدًا a مفعول مطلق related in meaning to أمهل, like جلست قعودًا. It connects رويد with diminutive رود or إرواد. Other analyses include a modifier of understood إمهالا or حال; practice explicitly asks for the مصدر account.',
    '1:1': 'هلم شهداءكم has a visible object. هلم إلينا can mean intransitive تعال, “come”, or transitive أحضر with understood نفسك, “bring yourself to us”. Neither requires inventing a visible object in إلينا.',
    '2:0': 'Most forms are learned from usage; the common analogical pattern is فَعَالِ.',
    '2:2': 'The standard productive account forms command-like فَعَالِ from an eligible complete, conjugating triliteral verb. It does not license conversion of every Arabic imperative regardless of its root or type.',
    '2:4': 'نزالِ glosses انزل, “get down”, classically calling a rider to dismount for single combat.',
    '3:1': 'The standard rule adopted here bars a preceding معمول, because this governor is weaker than the verb. Grammarians discuss other accounts; exercises follow this rule.',
    '3:3': 'Use عليك زيدًا or تراكِ ذنبًا. The intended اسم الفعل constructions زيدًا عليك and ذنبًا تراكِ violate the adopted order.',
    '3:5': 'فعّال لما يريد illustrates لام التقوية with a verbal derivative, not a fronted object in that sentence. Such derivatives may have strengthened government, but this does not license لزيدٍ عليك or لضربٍ تراكِ as fronted-object اسم الفعل constructions. The source ranks verbs strongest, verbal derivatives next, and اسم الفعل weaker.',
  }, boxCopy: {
    '0:1': ['بله الشرّ: اسم فعل. بلهًا أخاك: مصدر منصوب في التحليل المعتمد.'],
    '1:0': ['هلم إلينا: تعال، أو أحضر نفسك مع حذف المفعول.'],
    '2:1': ['فَعَالِ بمعنى الأمر من الثلاثي التام المتصرف في القياس المشهور.'],
    '3:0': ['في القاعدة المعتمدة: لا يتقدم معمول اسم الفعل.'],
    '3:4': ['لا تقدم معمول اسم الفعل بحيلة لام التقوية.'],
  }, analysisPrompt: 'Use the مصدر analysis.', analysisItemLabels: { 'bank-13': { 'مفعول مطلق من غير لفظ الفعل': 'تمييز منصوب' } } }),
};

export const checks = {
  '20/l1': [q('Which شبه الفعل group begins this section?', ['المصدر.', 'اسم الفاعل.', 'اسم الفعل.', 'الصفة المشبهة.'], 'It names an event without tense.'),
    q('What does كم supply in كذكركم آباءكم?', ['The doer of remembering.', 'The object remembered.', 'The time of remembering.', 'An adjective of ذكر.'], 'The pronoun is genitive through إضافة, but who remembers?'),
    q('Can nunated إطعام govern يتيمًا?', ['Yes; a مصدر need not be in إضافة to govern.', 'No; only إضافة permits government.', 'No; tanwin always blocks government.', 'Only circumstances, never objects, are possible.'], 'يتيمًا is the object of feeding.'),
    q('What does حجّ البيت show about the مصدر’s doer?', ['It can be omitted without a replacement.', 'A مصدر can never have a doer.', 'An overt doer is always required.', 'The House itself performs the pilgrimage.'], 'Compare the hidden subject of حاجّ.'),
    q('In the source’s analysis, why may معه precede السعي?', ['It allows fronting this ظرف as an exception.', 'السعي is in إضافة.', 'بلغ is fixed in form.', 'Every معمول can freely precede a مصدر.'], 'The attachment is disputed; use the stated account.')],
  '20/l2': [q('Does خالق in إنّي خالق بشرا lack a subject?', ['No; it has hidden أنا.', 'Yes; no subject is needed.', 'بشرًا is the subject.', 'Yes; خالق is passive.'], 'The speaker is the creator.'),
    q('What governing pattern does خالق follow?', ['Its active verb خلق.', 'It can only govern a subject.', 'Its passive verb.', 'It cannot govern without أل.'], 'خلق can take an object.'),
    q('What does مطلقا mean for the participle with أل here?', ['The bare form’s time and reliance restrictions do not apply.', 'It can only have a hidden subject.', 'أل stops all government.', 'It must always rely on a preceding مبتدأ.'], 'Its verb still determines the permitted roles.'),
    q('What does a bare participle need for the government studied?', ['Present/future meaning and reliance.', 'أل and past meaning.', 'إضافة after a preposition.', 'A fixed form and future meaning only.'], 'Recall subject, ناسخ, حال, question or negation.'),
    q('What case has خليفة in إنّي جاعل في الأرض خليفة?', ['نصب as the object in this construction.', 'جر through إضافة to جاعل.', 'رفع as the subject.', 'Any case freely.'], 'جاعلٌ has tanwin and the phrase intervenes.'),
    q('What is الناس after مجموع in ذلك يوم مجموع له الناس?', ['نائب فاعل.', 'An active فاعل.', 'A direct object.', 'A genitive مضاف إليه.'], 'مجموع follows the passive verb جُمع.')],
  '20/l3': [q('Why is the adjective called مشبهة باسم الفاعل?', ['Its governing behaviour resembles the transitive participle pattern.', 'It must derive from a transitive verb.', 'It always requires أل.', 'It cannot govern a related noun.'], 'The stable quality comes from a لازم verb.'),
    q('What is حسابَه in الله سريع حسابَه?', ['A definite منصوب شبيه بالمفعول, with a semantic subject relation.', 'A genuine object of a transitive سريع verb.', 'Evidence that سريع is passive.', 'Simply a copying error.'], 'Semantic doer and syntactic case must be distinguished.'),
    q('Why is حسابًا a تمييز unlike definite حسابَه in this pattern?', ['It is indefinite.', 'There is no difference at all.', 'حسابًا is genitive.', 'حسابَه is the indefinite form.'], 'Compare the pronoun with tanwin.'),
    q('What explains والصابرين in the praise construction?', ['نصب على المدح, with understood أمدح or أخص.', 'An unrelated omitted preposition.', 'An object of a visible verb immediately before it.', 'A scribal mistake.'], 'This is a licensed change of construction, not arbitrary case switching.')],
  '20/l4': [q('What role has Amr in زيد أفضل من عمرو?', ['المفضّل عليه.', 'المفضّل.', 'اسم التفضيل.', 'The hidden subject of أفضل.'], 'He supplies the comparison standard.'),
    q('What pattern of مسألة الكحل is taught?', ['Negation, a generic described noun, then self-comparison across two settings.', 'أل, مِن, then a definite genitive.', 'Any visible noun after أفعل.', 'Only a مصدر مؤول as subject.'], 'The name identifies a construction, not just one sentence.'),
    q('Why can الكحل be an overt subject in the example?', ['The same kohl is compared in two settings.', 'أحسن carries أل.', 'رجلًا is definite.', 'مِن always forces an overt subject.'], 'منه refers back to الكحل.'),
    q('Why is أكبر singular masculine with feminine آية?', ['The bare comparative uses مِن.', 'أكبر never has a feminine form.', 'آية is masculine.', 'مِن stops all government.'], 'Apply the construction’s agreement rule.'),
    q('Why is أول singular in ولا تكونوا أول كافر به?', ['It is added to indefinite كافر.', 'It is added to a definite noun.', 'It is followed by comparative مِن.', 'Number never matters for comparison words.'], 'Distinguish the two kinds of إضافة.'),
    q('Which form requires الكبرى to agree with النار?', ['The comparison word carries أل.', 'It is bare with مِن.', 'It is added to an indefinite noun.', 'It is added to a definite noun.'], 'الكبرى itself is marked by أل.')],
  '20/l5': [q('What determines an اسم الفعل’s government?', ['The verb meaning it represents.', 'Only its noun shape.', 'Only tanwin.', 'Only sentence position.'], 'Its corresponding verb supplies the model.'),
    q('Why can بله govern الشرّ as an object?', ['It means transitive اترك; هيهات means intransitive بَعُد.', 'بله carries أل.', 'Only transferred forms take objects.', 'Both meanings are grammatically identical.'], 'Distinguish transitive and intransitive meanings.'),
    q('Which time class does أفّ represent in فلا تقل لهما أفّ?', ['Present: أتضجّر.', 'Past.', 'Command.', 'No verb meaning.'], 'It expresses annoyance.'),
    q('Can a new مرتجل form be freely coined by analogy?', ['No; learn those forms from attested usage.', 'Yes, without restrictions.', 'Only by adding tanwin.', 'All مرتجل forms are productive patterns.'], 'A separate القياسي pattern follows next lesson.'),
    q('Why does عليك change for the addressee while بله stays fixed?', ['عليك varies its address ending; origin alone is not a universal test.', 'عليك is necessarily مرتجل and بله necessarily changes.', 'All transferred forms must change.', 'No grammatical distinction is possible.'], 'بله is commonly classed as transferred too.')],
  '20/l6': [q('What is بلهًا in بلهًا أخاك under the adopted analysis?', ['A مصدر as مفعول مطلق of an omitted verb.', 'An active participle.', 'Unchanged اسم فعل in this example.', 'A مصدر in إضافة to أخاك.'], 'The example contrasts it with بله الشرّ.'),
    q('What accounts for هلم إلينا without a visible object?', ['“Come”, or “bring” with understood نفسك.', 'It is only a vocative particle.', 'The sentence contains a copying omission.', 'It needs a hidden subject instead of any account of transitivity.'], 'Compare هلم شهداءكم.'),
    q('What productive اسم الفعل pattern is taught?', ['فَعَالِ from an eligible triliteral verb: نزالِ.', 'Tanwin added to every مصدر.', 'ها prefixed to every past verb.', 'Any ظرف combined with any pronoun.'], 'This is the standard analogical command pattern.'),
    q('Does لام التقوية license a preceding اسم الفعل object under this rule?', ['No; retain the prescribed order.', 'Yes, exactly like every verbal derivative.', 'Yes, automatically in poetry.', 'اسم الفعل has no معمول at all.'], 'Do not use لام as a workaround.')],
};

export const quizzes = {
  '20/l1': [q('Which group commonly governs through إضافة or tanwin?', ['المصدر.', 'اسم الفاعل.', 'الصفة المشبهة.', 'اسم التفضيل.']),
    q('What is البيت in حجّ البيت in meaning?', ['The object of pilgrimage.', 'The pilgrim doing it.', 'The time of pilgrimage.', 'An adjective of حجّ.']),
    q('What does إطعامٌ...يتيما demonstrate?', ['A مصدر can govern without إضافة.', 'Tanwin prevents its government.', 'أل is compulsory.', 'All nunated nouns lose government.']),
    q('Which مصدر use does the source call شاذّ, though accounts differ?', ['Government with أل.', 'Government with tanwin.', 'إضافة to the doer.', 'إضافة to the object.']),
    q('What does حجّ البيت demonstrate about its doer?', ['A مصدر may omit it without replacement.', 'Every governing noun must hide a doer.', 'حجّ cannot be a مصدر.', 'The House is the hidden pilgrim.']),
    q('Which fronted معمول does the source’s stated exception allow?', ['الظرف.', 'A direct subject.', 'An ordinary direct object.', 'A non-circumstantial مضاف إليه.'])],
  '20/l2': [q('Which five verbal derivatives are studied?', ['Active/passive participles, intensive form, resembling adjective and comparative.', 'Active/passive participles, place noun, instrument noun and comparative.', 'Only active and passive participles.', 'مصدر, active/passive participles, اسم الفعل and instrument noun.']),
    q('What verb does اسم الفاعل follow in government?', ['Its active verb.', 'Its passive verb.', 'No verb; it never governs.', 'Only an imperative.']),
    q('What is true of government with the relevant أل?', ['The bare-participle time and reliance restrictions do not apply.', 'Only a hidden subject is possible.', 'A preceding مبتدأ is always compulsory.', 'No object is possible.']),
    q('Which reliance environments are illustrated for the bare participle?', ['Subject or its equivalent, حال’s owner, question or negation.', 'Only a past verb.', 'Only أل.', 'Only a following مضاف إليه.']),
    q('Why is خليفةً an object rather than a genitive in إنّي جاعل في الأرض خليفة?', ['جاعلٌ is not in إضافة here; the phrase intervenes.', 'جاعل has أل.', 'Participles never allow إضافة.', 'خليفة must be a proper name.']),
    q('What does اسم المفعول raise?', ['نائب فاعل.', 'Only a direct object.', 'Only a genitive.', 'An active doer just like اسم الفاعل.'])],
  '20/l3': [q('What is the typical source of الصفة المشبهة?', ['An intransitive verb.', 'A verb transitive to one object.', 'A verb transitive to two objects.', 'Only a passive verb.']),
    q('What resemblance explains its name in this lesson?', ['The object-like governing pattern.', 'Only an identical meaning.', 'Every aspect of both meaning and government is identical.', 'No grammatical resemblance exists.']),
    q('What is definite حسابَه in الله سريع حسابَه?', ['منصوب شبيه بالمفعول به.', 'An indefinite تمييز.', 'A genitive through إضافة.', 'Necessarily an error.']),
    q('Which treatment is used for a bare indefinite منصوب related noun?', ['تمييز.', 'فاعل مرفوع.', 'A definite شبه مفعول.', 'Genitive إضافة.']),
    q('What link does the source attribute to أل in سريع الحساب?', ['The possessive relation illustrated by حسابه.', 'An omitted preposition.', 'Tanwin.', 'No relation to the bearer at all.']),
    q('Which contexts does the source compare for licensed expressive case changes?', ['Recognized تابع and صفة مشبهة constructions.', 'Freely swapping a real subject and object.', 'Every syntactic position without conditions.', 'Only fixed nouns.'])],
  '20/l4': [q('Name the three ordinary comparison components.', ['اسم التفضيل، المفضّل، المفضّل عليه.', 'مصدر، فاعل، مفعول.', 'Only مضاف and مضاف إليه.', 'Indefinite, definite and genitive.']),
    q('What subject does اسم التفضيل usually contain?', ['A hidden pronoun.', 'An overt noun.', 'A نائب فاعل.', 'No subject at all.']),
    q('Which مسألة الكحل pattern is taught?', ['Negation, generic described noun, and self-comparison in two settings.', 'أل, مِن and definite إضافة.', 'A transitive verb and two objects.', 'A question, negation and مصدر only.']),
    q('What is required in the bare comparative with مِن?', ['Singular masculine form.', 'Full agreement.', 'Indefinite إضافة.', 'أل.']),
    q('With definite إضافة retaining comparison, what is allowed?', ['Singular masculine or agreement.', 'Only agreement.', 'Only singular masculine.', 'Neither; omit the comparative.']),
    q('Which form requires agreement in النار الكبرى?', ['The comparative with أل.', 'Bare with مِن.', 'Indefinite إضافة.', 'Every form equally.'])],
  '20/l5': [q('What does اسم الفعل’s government follow?', ['The verb meaning it represents.', 'Only noun morphology.', 'Only tanwin.', 'It never governs.']),
    q('What does بله الشرّ show about بله?', ['It represents transitive اترك.', 'It has only an intransitive meaning.', 'It has no verbal meaning.', 'It only represents the past.']),
    q('What class includes آمين?', ['Command/request: استجب.', 'Past.', 'Present.', 'No verbal time or function.']),
    q('Why learn مرتجل forms from attested speech?', ['They are سماعي rather than freely coined by analogy.', 'Every one is a productive pattern.', 'No اسم الفعل can ever be analogical.', 'Tanwin is compulsory.']),
    q('What is عليك when transferred from a prepositional phrase?', ['منقول.', 'مرتجل.', 'The فَعَالِ pattern.', 'Necessarily an unvarying form.']),
    q('How do the illustrated forms عليك and بله differ?', ['عليك varies its address ending; بله stays fixed, despite transferred analyses.', 'بله varies while عليك is fixed.', 'Both must vary identically.', 'Neither ever changes for the addressee.'])],
  '20/l6': [q('Under the adopted account, what is nunated بلهًا أخاك?', ['A مفعول مطلق of an omitted verb.', 'An active participle.', 'An إضافة with أخاك genitive.', 'An unchanged اسم فعل here.']),
    q('Which is one account of هلم إلينا?', ['It means intransitive تعال.', 'It is necessarily incomplete.', 'It is only an attention particle.', 'إلينا is an accusative direct object.']),
    q('Which analogical command pattern is taught?', ['فَعَالِ, as نزالِ from انزل.', 'Comparative أفعل from every triliteral.', 'Active-participle مُفعِل.', 'Adjectival فعيل.']),
    q('Why keep the معمول after اسم الفعل in the adopted rule?', ['Its weaker government does not license fronting.', 'It never takes a معمول.', 'Only المصدر has a word-order rule.', 'اسم الفعل always has tanwin.']),
    q('Can لام التقوية license fronting here under that rule?', ['No.', 'Yes, in every case.', 'Yes, for every transferred form.', 'The word has no government at all.']),
    q('Under the مصدر account, what is رويدًا in أمهلهم رويدًا?', ['مفعول مطلق related in meaning to the verb.', 'An unnunated اسم فعل.', 'The doer of أمهل.', 'A حال instead of the account specified.'])],
};
