import { card as c, rows as r, labelled as l, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '10/l1': plan(44, 'Containment and Comparison in فِي', [
    [c('One thing contained within another', 0, 1, 2)],
    [c('Already within good deeds', 0, 1, 2, 3, 4), c('Analyse the object reached through في', 5)],
    [c('The settings in which good is sought', 0, 1, 2), c('The time containing revelation', 3, 4)],
    [c('A reason expressed with في', 0, 1, 2, 3), c('Entering with righteous company', 4, 5)],
    [c('Comparison: the lesser before the greater', 0, 1, 2, 3), c('The drop and the ocean', 4)],
  ], [
    ['ظرفية', 'Every use retains containment, one thing within another.'],
    ['في الخيرات', 'The subjects are already doing good and hasten toward more.'],
    ['Roles', 'Object, time or place, reason, and accompaniment.'],
    ['مقايسة', 'The lesser stands before في and the greater after it.'],
  ], { copy: {
    '0:0': 'في is the seventh of the thirteen prepositions.',
    '0:2': 'ظرفية is containment: a ظرف holds something within it. This image remains even beyond literal containers.',
    '1:0': 'في with its noun can serve as مفعول به.',
    '1:2': '“They hasten to good deeds.” Compare يسارعون إلى الخيرات.',
    '1:4': 'إلى pictures approaching from outside. في pictures believers already doing good and hastening toward its highest degree, the proposed point of the choice.',
    '2:0': 'في can also give مفعول فيه, for place or time.',
    '2:2': '“Our Lord, give us good in this world and the Hereafter.” The course reads الدنيا and الآخرة as the two settings, مكان.',
    '2:4': '“Ramadan, in which the Quran was revealed.” The month contains the event in time, زمان.',
    '3:0': 'في can give a reason or accompanying company.',
    '3:3': 'The wife of Egypt’s Aziz points to Yusuf: “The one about whom you blamed me.” فيه gives the reason, مفعول له غير صريح. Likewise دخلت امرأة النار في هرة, “A woman entered the Fire because of a cat”: reason, not location.',
    '3:5': '“Enter among My servants” addresses النفس المطمئنة returning to Allah. Some read في as مع: entering Paradise with the righteous, giving مفعول معه rather than merely a place among them.',
    '4:0': 'Another use is comparison, not a time or place.',
    '4:3': '“This life’s enjoyment compared with the Hereafter is little.” متاع الدنيا is the lesser, مفضول, before في; الآخرة is the greater, فاضل, after it.',
    '4:4': 'A hadith compares human knowledge with Allah’s knowledge through a bird taking one drop from an ocean. The drop pictures all human knowledge; the remaining ocean conveys the immeasurable difference.',
  }, boxCopy: { '1:3': ['إلى الخيرات: من خارجها. في الخيرات: هم فيها ويسارعون إلى أعلاها.'],
    '3:2': ['فيه للتعليل: بسببه لمتنّني؛ مفعول له غير صريح.'] },
    visuals: { '4:1': v('The scale of the comparison', ['قطرة', 'What the bird carries'], ['البحر', 'What remains beyond it']) } }),
  '10/l2': plan(45, 'Likeness and the Limits of حتّى', [
    [c('كاف compares the manner of an action', 0, 1, 2, 3)],
    [c('A reason for remembrance or its manner', 0, 1, 2, 3)],
    [c('With pronouns, مثل replaces كاف', 0, 1, 2), c('حتى also takes a visible noun', 3, 4)],
    [c('An endpoint of time, place or rank', 0, 1, 2, 3), c('The highest and lowest extremes', 4, 5, 6, 7)],
    [c('An endpoint in space or time', r(0, 0, 1)), c('The objective, beyond a time limit', r(0, 2), 1)],
    [c('The last part or what directly adjoins it', 0, 1), c('The end of night and the following morning', 2, 3, 4, 5),
      c('Halfway does not satisfy this condition', 6, 7)],
  ], [
    ['كاف', 'تشبيه can specify manner; context may also support a reason reading.'],
    ['Visible nouns', 'كاف and حتى do not normally take pronouns. Use مثلي or مثله for likeness.'],
    ['حتى', 'An endpoint, including high or low rank, and sometimes an objective.'],
    ['Its limit', 'The last part or what adjoins it; a midpoint fails the stated condition.'],
  ], { copy: {
    '0:0': 'كاف is the eighth preposition. Its root is تشبيه, likeness.',
    '0:3': '“Have mercy on them as they raised me small.” كما ربياني specifies mercy’s kind and measure: مفعول مطلق غير صريح للنوع. Compare رب ارحمهما رحمتهما إياي صغيرا.',
    '1:3': 'As مفعول له, كما هداكم means “because He guided you”. As تشبيه, it describes remembrance mirroring His guidance. Their outcomes are close; deciding which is intended can need deeper بلاغة analysis.',
    '2:0': 'كاف and حتى share a restriction.',
    '2:2': 'كاف takes اسم ظاهر, not pronouns: not كي، كه or كنا in this use. For likeness with a pronoun, use مثل: مثلي، مثله.',
    '2:4': 'حتى likewise takes اسم ظاهر, not حتاه. Apparent poetic counterexamples are treated as شاذ.',
    '3:0': 'حتى, the ninth particle, shares إلى’s ending-point sense.',
    '3:3': 'A single noun that is neither place nor time marks an extreme of rank, highest or lowest.',
    '3:5': '“People died, even prophets.” The highest rank marks تعظيم: if prophets cannot escape death, nobody can.',
    '3:7': '“Allah provides even for wrongdoers.” The lowest rank marks تحقير: provision reaches even them.',
    '4:1': 'In this reading, removing فتنة is the objective, beyond a time limit. The phrase is مفعول له غير صريح.',
    '5:1': 'إلى allows a broader range of endpoints. حتى requires the actual last part of what precedes it, or what directly adjoins that end.',
    '5:3': '“I prayed through the night until its end.” آخره is the night’s own last part.',
    '5:5': '“Until morning.” Morning is not part of night, but directly adjoins its final moment, متصل بآخره.',
    '5:7': '“Until half of it” gives a midpoint, neither the last part nor something adjoining the end. Even a substantial half fails this stated condition.',
  } }),
};

Object.assign(plans, {
  '10/l3': plan(46, 'Particles of Oath', [
    [c('Three particles introduce what is sworn by', 0)],
    [c('واو القسم takes a visible noun', 0, 1, 2, 3)],
    [c('The narrower rule for تاء القسم', 0, 1, 2, 3)],
    [c('An understood أقسم behind واو and تاء', 0, 1, 2, 3)],
    [c('باء is the original oath particle', 0, 1, 2), c('With باء, أقسم may be spoken', 3, 4),
      c('With باء, أقسم may be omitted', 5, 6), c('Only باء allows a pronoun', 7, 8)],
  ], [
    ['The three', 'باء، واو، تاء introduce the oath’s object. باء is the original.'],
    ['What follows', 'باء: noun or pronoun. واو: visible noun. تاء: لفظ الجلالة in the rule taught here.'],
    ['The oath verb', 'واو and تاء require omitted أقسم; باء allows stating or omitting it.'],
    ['Government', 'The phrase is the understood oath verb’s indirect object.'],
  ], { copy: {
    '0:0': 'واو القسم is the tenth particle; تاء القسم the eleventh. باء القسم reuses the first particle, باء. All introduce what is sworn by, with different restrictions.',
    '1:3': 'Like كاف and حتى, oath واو takes اسم ظاهر, not a pronoun. وَهُ، وَهِيَ and وِيهِ do not serve this oath function.',
    '2:3': 'The regular rule here restricts تاء to الله: تالله. الرحمن and العصر take واو; they do not follow this تاء pattern.',
    '3:1': 'والله and تالله imply أقسم بالله, “I swear by Allah”. The phrase is the omitted verb’s مفعول به.',
    '3:3': 'The omission is required with these two particles: والله or تالله, not أقسم والله.',
    '4:0': 'باء has this further use for oath and is treated as the أصل from which the other two derive.',
    '4:4': '“I swear by the Day of Resurrection.” أقسم is stated with باء.',
    '4:6': 'Iblis says, “By Your might, I will mislead them all.” باء permits omission here, even though it could accompany a stated أقسم.',
    '4:8': 'بك لأفعلن, “By you, I will do it.” باء takes a pronoun as freely as a noun; واو and تاء do not.',
  }, visuals: { '0:0': v('Three oath openings', ['وَاللهِ', 'واو'], ['تَاللهِ', 'تاء'], ['بِاللهِ', 'باء']) } }),
  '10/l4': plan(47, 'Time with مُذ and مُنذ', [
    [c('Time with مُذ and مُنذ', 0, 1, 2, 3)],
    [c('The negated past covers the interval', 0, 1, 2, 3), c('An affirmative action must extend', 4, 5),
      c('A momentary fall does not span the interval', 6, 7)],
    [c('A visible noun of past or present time', 0, 1), c('Today remains present despite a past verb', 2, 3, 4)],
    [c('Today: the present interval', 0, r(1, 0)), c('Since a day or for a duration', r(1, 1, 2), 2)],
    [c('Where مُذ and مُنذ differ in إعراب', 0, 1, 2), c('The understood structure behind رفع', 3, 4)],
    [c('The noun use before a clause', 0, 1, 2, 3, 4)],
  ], [
    ['Time', 'مفعول فيه with a visible noun of past or present time.'],
    ['The action', 'Past: negated, or affirmative and extended.'],
    ['Meaning', 'Present: في. Definite past: مِن. Indefinite duration: إلى.'],
    ['Case and clauses', 'Present: جر. Past: منذ prefers جر, مذ رفع. Before a clause: اسم مضاف.'],
  ], { copy: {
    '0:0': 'مذ and منذ complete the thirteen. Meaning and restrictions agree; one إعراب point differs.',
    '0:3': 'Both anchor the action to time.',
    '1:1': 'The following rule concerns a past verb, either negated or affirmative and extended.',
    '1:3': '“I have not seen him since Friday.” Negation covers the interval. The affirmative alternative must itself extend across the span: مثبت ممتد.',
    '1:5': 'Sleeping since after Isha and praying since midnight both continue through the named period.',
    '1:7': '“I fell since sunrise” gives only a moment inside the span. Affirmative past alone is insufficient; the action must extend throughout the interval.',
    '2:1': 'Only اسم ظاهر, never a pronoun, and only past or present time. Future مذ غدا is excluded.',
    '2:3': 'اليوم and الليلة count as present time even after a past verb.',
    '2:4': 'ما رأيته منذ اليوم means “I have not seen him today”. اليوم، الليلة، الشهر and السنة can denote the current unit occupied by the speaker, regardless of the verb’s tense.',
    '3:2': 'For past time, English “since” names the definite start; “for” measures the indefinite duration.',
    '4:1': 'For the present, both require جر. For the past, منذ prefers جر and مذ prefers رفع.',
    '4:4': 'ما رأيته مذ يومان implies مذ كان يومان, with يومان read as اسم of omitted كان, or مذ مضى يومان, with it as فاعل of omitted مضى. Under this account, مذ introduces the implied clause as a ظرف, rather than directly governing جر.',
    '5:2': '“I have not backbitten anyone since learning it is forbidden.” A whole clause follows مذ.',
    '5:4': 'Both are اسم مضاف here, with the clause as مضاف إليه. No preposition governs it.',
  }, boxCopy: { '3:0': ['للحاضر معنى في؛ وللماضي معنى مِن أو إلى.'],
    '4:0': ['الحاضر: الجر واجب بعدهما. الماضي: الجر أرجح بعد منذ، والرفع أرجح بعد مذ.'],
    '5:0': ['قبل الجملة، مذ ومنذ اسمان مضافان.'],
    '5:3': ['لا يجرّ الحرف جملةً.'] },
    tableCopy: { '4:2': { 0: ['مُنذ', 'يومينِ: جر', 'الجمعةِ: جر أرجح', 'اليومِ: جر واجب'],
      1: ['مُذ', 'يومانِ: رفع', 'الجمعةُ: رفع أرجح', 'اليومِ: جر واجب'] } } }),
});

Object.assign(plans, {
  '10/l5': plan(48, 'Many or Few with رُبّ', [
    [c('A meaning without the usual attachment', 0, 1, 2)],
    [c('Context decides many or few', 0, 1, 2), c('Many a desire brings lasting grief', 3, 4), c('Analyse the described desire', 5)],
    [c('رُبّ opens the statement', 0, 1, 2, 3), c('يا draws attention with lament', 4, 5)],
    [c('An indefinite noun or a clarified pronoun', 0, 1, 2, 3), c('Basri and Kufi pronoun agreement', 4),
      c('A word or clause can describe the noun', 5, 6)],
    [c('ما الكافة stops government and changes the target', 0, 1), c('After ربما: a verb clause or a definite subject', 2, 3, 4, 5),
      c('Three readings of the apparent frequency puzzle', 6, 7)],
    [c('A single ب instead of a doubled بّ', 0, 1), c('Omit رُبّ while retaining its جر', 2, 3, 4, 5),
      c('Two explanations of the جر after واو', 6, 7), c('مِمّا can also convey “often”', 8, 9)],
  ], [
    ['شبيه بالزائد', 'Meaning without verb attachment: رب، مِن التبعيضية، حاشا.'],
    ['رُبّ', 'Opens the statement; context decides many or few.'],
    ['Its noun', 'Indefinite, usually described; or مبهم pronoun with تمييز.'],
    ['Other forms', 'ما stops government and targets frequency. Omitted رب can retain جر.'],
  ], { copy: {
    '0:0': 'The thirteen so far are أصلي, with meanings and attachment to فعل or شبه فعل. A second class is شبيه بالزائد.',
    '0:2': 'Like أصلي, it has specific meaning. Like زائد, its noun needs no ordinary verb attachment. The three are رب، مِن التبعيضية and حاشا; pure زائد contributes emphasis rather than this distinct meaning.',
    '1:1': 'رُبّ allows opposite senses, تكثير and تقليل.',
    '1:4': 'Here the reading leans toward تكثير: many desires bring lasting grief.',
    '2:1': 'رُبّ has صدر الكلام. يا may precede it.',
    '2:3': '“Many a woman clothed in this world is naked in the Hereafter.”',
    '2:5': 'No person is summoned. يا is تنبيه carrying تحسّر, lament or warning, beyond a plain report.',
    '3:1': 'The ordinary noun is visible and indefinite. The pronoun exception is مبهم, without an antecedent, and needs a following تمييز.',
    '3:3': '“Many a generous man I met.” Attached ه has no prior مرجع; رجلا explains it as تمييز.',
    '3:6': 'The noun usually has a description: رب رجل كريم لقيته uses a word; رب رجل يفعل الخير لقيته uses the clause يفعل الخير. Both describe the man met.',
    '4:1': 'كفّ means restrain. ما stops رب’s government over a following noun. Many/few now concerns how often an action occurs, not how many things.',
    '4:3': '“Zayd often fasts.” ما permits a whole verb clause after ربما, unlike bare رب.',
    '4:5': 'The same meaning can begin with definite زيد as مبتدأ and يصوم as خبر. Bare رب requires an indefinite noun.',
    '4:7': 'ربما often leans toward تقليل, but ربّما يود الذين كفروا لو كانوا مسلمين seems frequent.<br><b>Context:</b> تكثير remains possible.<br><b>Scattered moments:</b> punishment leaves little time for regret.<br><b>تهكم:</b> “Perhaps you will regret it” warns that a wise person avoids even possible regret, without doubting the eventual regret.',
    '5:1': 'The ب may be light, رُبَ, rather than doubled رُبَّ, as in the cited reading ربَما يود الذين كفروا.',
    '5:3': 'رب can disappear while its جر remains, often after واو and rarely after فاء.',
    '5:5': '“Many a night like the sea’s waves let down its curtains over me...” ليل is مجرور with no visible رب.',
    '5:7': 'One analysis makes واو itself a حرف جر meaning رب. Another retains hidden رب as governor and treats واو as connective. The resulting جر is the same.',
    '5:9': 'مما is normally مِن plus موصول ما. In كان ﷺ مما يحرك شفتيه it means “often”: he repeated revelation fearing to forget, until لا تحرك به لسانك. Alternatively, مِن itself means رب and ما is كافة, like ربما. Both convey frequency.',
  } }),
  '10/l6': plan(49, 'Partitive مِن and Exception with حاشا', [
    [c('Part of something, rather than the whole', 0, 1, 2, 3, 4)],
    [c('An exception declaring freedom from blame', 0, 1, 2, 3, 4), c('Compare حاشا with plain إلا', 5)],
    [c('Ruination in knowledge, not physical death', 0, 1, 2), c('The root image: setting at a distance', 3)],
    [c('Is كاف أصلي or شبيه بالزائد?', 0, 1, 2, 3), c('Two analyses with the same meaning', 4, 5)],
  ], [
    ['مِن التبعيضية', 'Some of a whole, as in عندي من ماء.'],
    ['حاشا', 'Exception plus تنزيه: free of the fault attributed to the group.'],
    ['حاشية', 'The margin supplies the image of setting apart.'],
    ['كاف', 'أصلي attaches to an understood عامل; شبيه بالزائد can fill خبر directly.'],
  ], { copy: {
    '0:0': 'Partitive مِن is the second شبيه بالزائد particle.',
    '0:2': '“Some of the messengers’ news has reached you.”',
    '0:4': '“I have some water.” مِن التبعيضية marks a part: some news or water. It does not give the earlier starting-point sense.',
    '1:0': 'حاشا is the third شبيه بالزائد particle.',
    '1:4': 'Like إلا it makes an exception, with an added nuance.',
    '2:1': 'هلك here means spiritual ruin through lack of true معرفة of Allah, rather than bodily death.',
    '2:2': 'حاشا affirms that the scholar is free of that very lack, beyond simply excluding him.',
    '2:3': 'حاشية is a page’s edge or margin. Its root picture, setting at a distance, matches حاشا’s exemption from the fault.',
    '3:1': 'The classification of كاف, taught earlier as أصلي for likeness, is disputed.',
    '3:5': 'Both yield “Knowledge is like light”. They differ in whether an omitted عامل is required.',
  }, boxCopy: { '1:1': ['هَلَكَ النَّاسُ حَاشَا العَالِمِ'] }, tableCopy: {
    '1:5': { 0: ['Function', 'Plain exception.', 'Exception plus freedom from the fault.'],
      1: ['جاء الناس إلا زيدا', 'Zayd did not come; no judgement.', 'No added judgement is expressed.'],
      2: ['هلك الناس حاشا العالمِ', 'Compare a plain exception.', 'The scholar is free of the stated ruin.'] },
    '3:4': { 0: ['أصلي', 'Preposition with attachment.', 'متعلق بظرف مستقر محذوف: العلم ثابت كالنور'],
      1: ['شبيه بالزائد', 'Carries the sense مثل.', 'في محل خبر مباشرة'] },
  }, visuals: { '2:1': v('A shared image of separation', ['حاشية', 'The margin'], ['حاشا', 'Set apart from the fault']) } }),
});

export const checks = {
  '10/l1': [q('What root meaning belongs to في?', ['Containment, ظرفية.', 'Attachment, إلصاق.', 'Likeness, تشبيه.', 'Endpoint, انتهاء الغاية.'], 'Picture a container and what it holds.'),
    q('What does في الخيرات picture beyond إلى الخيرات?', ['Already doing good and hastening toward more.', 'Not yet reaching good deeds.', 'Good deeds they can never reach.', 'No difference in the picture.'], 'Are they inside or outside the good already?'),
    q('How does the course read في الدنيا and في الآخرة in ربنا آتنا...?', ['Place: two settings where good is sought.', 'Time: two points only.', 'Neither has a ظرف role.', 'No distinction between time and place exists.'], 'Recall the two settings of the prayer.'),
    q('What role is فيه in الذي لمتنني فيه?', null, 'It gives the reason for blame.'),
    q('Which is greater in متاع الحياة الدنيا في الآخرة?', ['الآخرة, after في.', 'متاع الدنيا, before في.', 'Both are the lesser.', 'There is no fixed comparison order.'], 'The فاضل follows في للمقايسة.')],
  '10/l2': [q('What role does كما ربياني صغيرا play after ارحمهما?', ['Indirect مفعول مطلق للنوع, specifying mercy’s manner.', 'A second direct object.', 'حال of the parents.', 'Time of the mercy.'], 'Compare رحمتهما إياي صغيرا.'),
    q('Which readings fit كما هداكم after واذكروه?', ['Reason, مفعول له, or likeness describing manner.', 'Object only.', 'حال only.', 'فاعل or مبتدأ.'], 'Because He guided you, or in a way mirroring His guidance.'),
    q('What replaces كاف for likeness with a pronoun?', ['مثل: مثلي، مثله.', 'نفس: نفسي، نفسه.', 'ذات: ذاتي، ذاته.', 'عين: عيني، عينه.'], 'كاف itself requires اسم ظاهر.'),
    q('What do حتى الأنبياء and حتى الظالمين mark respectively?', null, 'Compare highest and lowest rank.'),
    q('What role does حتى give under the objective reading حتى لا تكون فتنة?', null, 'Distinguish the intended objective from a time limit.'),
    q('Why does حتى نصفه fail the stated night example?', ['Half is neither the end nor adjoining it.', 'نصف is masculine, unlike الليل.', 'نصف cannot take تنوين.', 'حتى cannot precede any إضافة.'], 'Locate the halfway point relative to the endpoint.')],
  '10/l3': [q('Which oath particle reuses the first preposition studied?', ['باء القسم.', 'واو القسم.', 'تاء القسم.', 'None; all three are new.'], 'Recall باء’s additional oath use.'),
    q('What must follow واو القسم?', null, 'It does not take a pronoun.'),
    q('Do الرحمن and العصر follow the تاء oath pattern taught here?', ['No; the rule restricts it to الله.', 'Yes; every divine name qualifies.', 'Only العصر, not الرحمن.', 'Only after واو.'], 'Its regular scope is narrower than واو.'),
    q('Can أقسم be stated with oath واو or تاء?', ['No; it is omitted with both.', 'Yes; it is the standard واو form.', 'Yes, only in poetry.', 'Only with تاء.'], 'Compare them with باء.'),
    q('Can واو or تاء attach to the pronoun in بك لأفعلن?', ['No; only باء allows it.', 'All three freely take pronouns.', 'Only تاء can.', 'Only واو can.'], 'The other two require visible nouns.')],
  '10/l4': [q('Which role belongs to مُذ or مُنذ with its time noun?', ['مفعول فيه.', 'مفعول به.', 'مفعول له.', 'مفعول مطلق.'], 'It locates the action in time.'),
    q('Why does سقطت منذ طلوع الشمس fail the stated rule?', ['A fall is momentary, not extended through the span.', 'سقطت is not past.', 'الشمس can never occur after منذ.', 'Only a negated verb is ever allowed.'], 'An affirmative action must be ممتد.'),
    q('Why is اليوم present in ما رأيته منذ اليوم?', ['It names the speaker’s current unit of time.', 'اليوم is always future.', 'اليوم is a pronoun.', 'منذ never takes time nouns.'], 'The verb’s past tense does not change what “today” names.'),
    q('Which meaning is given for منذ يومين, an indefinite duration?', ['إلى: “for”, measuring a span.', 'مِن: “since”, a fixed start.', 'في: present time.', 'على: height.'], 'Distinguish duration from a named starting point.'),
    q('What explains رفع after مذ in the offered analysis?', ['Omitted كان or مضى supplies اسم or فاعل.', 'مذ can never govern جر.', 'الجمعة becomes مبني.', 'مذ and منذ have identical case behaviour.'], 'Restore the implied structure.'),
    q('What is مذ before علمت الغيبة محرمة?', ['اسم مضاف; the clause occupies مضاف إليه.', 'A past verb.', 'A conjunction.', 'A time expression with no grammatical position.'], 'A preposition cannot govern the clause directly.')],
  '10/l5': [q('What makes a particle شبيها بالزائد?', ['Specific meaning without required verb attachment.', 'No meaning, with obligatory attachment.', 'No shared trait with either type.', 'It is identical to أصلي.'], 'It combines one trait of each neighbouring class.'),
    q('On the third view, what decides whether رُبّ means many or few?', null, 'Its meaning is مشترك on this view.'),
    q('Is يا before رب كاسيات a real call to someone?', ['No; تنبيه with تحسر, not a summoned addressee.', 'Yes; it addresses the women.', 'Yes; it addresses the particle رب.', 'No; it is a conjunction.'], 'Listen for lament rather than a person being called.'),
    q('What explains the مبهم ه in ربه رجلا كريما لقيته?', ['رجلا as تمييز.', 'رجلا as بدل.', 'رجلا as نعت of the pronoun.', 'Nothing explains it.'], 'The pronoun has no earlier antecedent.'),
    q('What changes with ما الكافة after رب?', ['Government stops; many/few targets action frequency.', 'It becomes أصلي and takes definite nouns only.', 'It loses all meaning and cannot open a sentence.', 'Nothing; ما is decorative.'], 'Compare many people with frequent action.'),
    q('How does وليل كموج البحر retain جر?', ['رب is omitted after واو while its عمل remains.', 'كاف replaces رب as governor of ليل.', 'ليل is actually مرفوع.', 'واو must be an oath.'], 'Use the omission analysis presented here.')],
  '10/l6': [q('What does partitive مِن mark in عندي من ماء?', ['Some of the thing, rather than the whole.', 'None of the water.', 'A journey’s starting point.', 'A comparison of likeness.'], 'Distinguish تبعيض from the earlier أصلي meanings.'),
    q('What does حاشا add beyond a plain exception?', ['Freedom from the fault attributed to the group.', 'An optional, uncertain exclusion.', 'Inclusion instead of exclusion.', 'No extra meaning.'], 'Recall تنزيه المستثنى.'),
    q('What image does حاشية contribute to حاشا?', ['Setting apart at a distance.', 'Joining the exempted person back in.', 'Repeating the preceding action.', 'No relation to its use.'], 'A margin is set apart from the main area.'),
    q('Which two analyses fit العلم كالنور?', ['Attachment to an omitted عامل, or direct خبر position.', 'فاعل or نائب فاعل.', 'مبتدأ or بدل.', 'Only one analysis exists.'], 'Distinguish أصلي from شبيه بالزائد كاف.')],
};
export const quizzes = {
  '10/l1': [q('What root meaning belongs to في?', ['Containment, ظرفية.', 'Attachment, إلصاق.', 'Likeness, تشبيه.', 'Endpoint, انتهاء الغاية.']),
    q('What does في الخيرات picture?', ['Already within good and hastening toward more.', 'Not yet reaching good.', 'Hastening away from good.', 'Exactly the same picture as إلى.']),
    q('What kind of ظرف is فيه referring to Ramadan?', ['Time of revelation.', 'Place of revelation.', 'Reason for revelation.', 'Time and place cannot be distinguished.']),
    q('What do لمتنني فيه and دخلت النار في هرة share?', ['Indirect مفعول له: reason, not location.', 'مفعول فيه: location.', 'مفعول معه: company.', 'مفعول به: object.']),
    q('What role has في عبادي under the مع reading?'), q('Which is the lesser in متاع الحياة الدنيا في الآخرة?', ['متاع الدنيا, before في.', 'الآخرة, after في.', 'قليل, after إلا.', 'Neither; both are identical.'])],
  '10/l2': [q('What root meaning belongs to كاف?'), q('Which two readings fit كما هداكم?'), q('What expresses likeness with a pronoun instead of كاف?'),
    q('What does حتى الأنبياء mark in مات الناس حتى الأنبياء?'), q('What role does حتى give under the objective reading حتى لا تكون فتنة?'),
    q('Why does حتى نصفه fail the stated condition?', ['A midpoint is neither the end nor adjoining it.', 'حتى requires an indefinite noun.', 'الليل cannot name time.', 'حتى rejects all إضافة.'])],
  '10/l3': [q('Which oath particle reuses the first preposition?'), q('What follows واو القسم?'), q('What does the regular تاء oath rule restrict it to?'),
    q('Can أقسم accompany oath واو or تاء?', ['No; both require its omission.', 'Yes; it is standard.', 'Only واو allows it.', 'Only تاء allows it.']),
    q('Which oath particle can take a pronoun?'), q('What does لا أقسم بيوم القيامة demonstrate?', ['باء permits stating or omitting أقسم.', 'باء never allows stated أقسم.', 'باء and واو always omit it.', 'باء requires it to be stated.'])],
  '10/l4': [q('What role belongs to مذ or منذ with its time noun?'), q('Why does the momentary سقطت fail with منذ here?', ['It does not extend through the named span.', 'It cannot be past tense.', 'الشمس cannot name time.', 'منذ allows only negation.']),
    q('Why is اليوم present despite رأيته being past?', ['It names the current unit occupied by the speaker.', 'It is always future.', 'It is a pronoun.', 'These particles reject time nouns.']),
    q('Which meaning fits indefinite duration منذ يومين?', ['إلى: “for”.', 'مِن: “since”.', 'في: present time.', 'على: height.']),
    q('What explains رفع after مذ in the given account?', ['An omitted كان or مضى supplies اسم or فاعل.', 'مذ can never give جر.', 'الجمعة becomes مبني.', 'The two particles never differ.']),
    q('What is مذ before an entire clause?', ['اسم مضاف, with the clause as مضاف إليه.', 'A conjunction.', 'A verb taking an object clause.', 'It has no grammatical position.'])],
  '10/l5': [q('What traits define شبيه بالزائد?', ['Specific meaning; no required verb attachment.', 'No meaning; obligatory attachment.', 'No shared traits with the other types.', 'It is another name for أصلي.']),
    q('Which reading fits رب شهوة تورث حزنا طويلا?', ['تكثير: many desires.', 'تقليل: few desires.', 'Only تنبيه.', 'Both equally with no lean.']),
    q('What is يا before رب كاسيات?', ['تنبيه with تحسر, not a real call.', 'A call to the women.', 'A call to رب itself.', 'An addition without any function.']),
    q('What clarifies the مبهم pronoun in ربه رجلا كريما لقيته?'), q('What changes with ما الكافة?', ['Government stops; meaning targets action frequency.', 'رب becomes أصلي and requires definite nouns.', 'رب loses صدر الكلام.', 'Nothing changes.']),
    q('What happened to رب in وليل كموج البحر?', ['Omitted after واو, retaining جر.', 'Replaced by كاف as ليل’s governor.', 'ليل became مرفوع.', 'It was never part of this construction.'])],
  '10/l6': [q('What does مِن التبعيضية mark in من نبإ المرسلين?', ['Some of the messengers’ news.', 'A journey’s starting point.', 'Likeness.', 'A reason.']),
    q('Which مِن appears in عندي من ماء?'), q('What does حاشا add beyond exception?', ['Freedom from the group’s stated fault.', 'An optional exception.', 'Inclusion instead of exclusion.', 'No distinction from إلا.']),
    q('What does هلك mean in the scholar example?', ['Spiritual ruin through lack of معرفة.', 'Literal death.', 'Death of the scholar alone.', 'It has no meaning.']),
    q('What root image belongs to حاشا?', ['Setting apart, like a margin.', 'Joining back into the group.', 'Repeating an action.', 'No relevant image.']),
    q('Which analyses fit العلم كالنور?', ['Omitted عامل with أصلي; direct خبر with شبيه بالزائد.', 'فاعل or مفعول به.', 'مضاف إليه or بدل.', 'Only one analysis exists.'])],
};
