import { card as c, rows as r, labelled as l, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '06/l1': plan(23, 'Verbs of Transformation', [
    [c('A thing and the state it becomes', 0, 1, 2)],
    [c('صيّر explicitly changes a state', 0, 1, 2, 3)],
    [c('ردّ returns something to an earlier state', 0, 1, 2)],
    [c('ترك leaves a changed condition behind', 0, 1, 2, 3),
      c('Compare change, return and leaving', 4)],
    [c('تخذ and اتخذ take one thing as another', 0, 1, 3), c('Analyse the two objects of اتخذ', 2),
      c('وهب can also express transformation', 4, 5)],
    [c('جعل has creation and transformation readings', 0, 1),
      c('Two objects: a changed state', 2, 3),
      c('One object: bringing into existence', 4, 5),
      c('Check the same distinction in ترك and ردّ', 6, 7)],
  ], [
    ['Two objects', 'The first is transformed; the second names its new state.'],
    ['صيّر، ردّ، ترك', 'Change a state, return to an earlier state, or leave a changed state behind.'],
    ['Taking as', 'تخذ، اتخذ، وهب and جعل can express transformation of role or status.'],
    ['Meaning and count', 'جعل with one object can mean خلق or أوجد; with two, it can express transformation.'],
  ], { copy: {
    '0:0': 'أفعال التحويل share the two-object pattern of ظن and علم: their objects were مبتدأ and خبر. Their meaning is transformation, rather than inner perception.',
    '0:2': 'The first object is the thing transformed; the second its new state. The change may be actual, or a change in judgement, role or status.',
    '1:0': 'صيّر, from باب تفعيل, changes its first object into the condition named by its second.',
    '1:3': '“It turned sweet drink bitter and tightened life’s constraints.” This poetic شاهد has a hidden هو as فاعل, referring to what the poem describes.',
    '2:0': 'ردّ returns something to a state it held before. A gloss of “صيّر” misses this added sense of returning.',
    '2:2': '“Many People of the Book wished to return you, after belief, to disbelief.” Most addressees had disbelieved before Islam. لو يصيرونكم or لو يجعلونكم would lack the sense of return.',
    '3:0': 'ترك as فعل تحويل leaves its first object in a changed condition after something has acted on it and departed.',
    '3:3': '“Heavy rain struck it and left it bare.” Soil on a boulder supports greenery; rain washes it away. صلدا names the exposed rock, with nothing left on top.',
    '4:3': '“Allah took Ibrahim as a close friend.” وهب and جعل can share this transformation meaning with two objects.',
    '4:5': '“May Allah make me a ransom for knowledge, giving myself for it.” الله is فاعل, attached ني first object and فداء second.',
    '5:0': 'Distinguish two uses of جعل by the object structure.',
    '5:3': '“So We made it scattered dust.” The former state disappears. The attached pronoun is first object and هباء منثورا second, giving the transformation reading.',
    '5:5': 'Hearing, sight and hearts are joined by و in one object position. No second object names a new state. جعل means خلق or أوجد, creation from nothing; some commentaries explicitly choose أوجد to mark this distinction.',
    '5:6': 'إني تركت ملة قوم لا يؤمنون بالله uses ترك بمعنى هجر, abandoning rather than transforming. ثم يرد إلى ربه uses رد بمعنى يصار, being brought back rather than changed into a state. Examine object count throughout this family.',
  } }),
  '06/l2': plan(24, 'Suspended Government', [
    [c('Three objects retain an underlying judgement', 0, 1, 2),
      c('Locate all three objects of يري', 3, 4, 5)],
    [c('An interpreted noun can fill both positions', 0, 1, 2),
      c('A whole clause can stand in their place', 3, 4, 5, 6)],
    [c('تعليق suspends the effect on individual endings', 0, 1),
      c('Distinguish لفظي from محلي government', 2),
      c('Name precisely what is suspended', 3, 4)],
    [c('Related verbs can also trigger تعليق', 0, 1, 2, 4),
      c('Why أيكم keeps رفع', 3, 5)],
    [c('سأل behaves like a verb of the heart', 0, 2), c('The suspended question keeps its own roles', 1)],
  ], [
    ['Three objects', 'A قلب verb’s second and third objects were مبتدأ and خبر.'],
    ['Replacing the pair', 'An اسم مؤول or whole جملة can fill the pair’s position.'],
    ['تعليق', 'The verb’s عمل لفظي stops; its عمل محلي remains.'],
    ['Related verbs', 'Testing and asking can behave like قلب verbs: بلا and سأل illustrate this.'],
  ], { copy: {
    '0:0': 'A verb governing three objects belongs to أفعال القلوب.',
    '0:2': 'Its second and third objects were مبتدأ and خبر, like the pair in an ordinary two-object فعل قلب.',
    '0:5': '“Allah will show them their deeds as regrets against them.” أعمالهم and حسرات were the underlying مبتدأ and خبر; يري makes both منصوب.',
    '1:0': 'Two kinds of expression can fill both object positions together.',
    '1:2': 'أن الله مع المتقين is an اسم مؤول, equivalent to معية الله, filling both objects of اعلموا. أنّ adds توكيد: “Know for certain”, beyond a plain مصدر.',
    '1:6': 'شهد يشهد is not strictly فعل قلب. It therefore illustrates the point less clearly than a verb such as يعلم.',
    '2:1': 'The verb stops changing individual endings, but governs the whole clause في محل نصب, سادة مسد مفعوليه. This تعليق gives the clause its name: جملة معلق عنها العمل.',
    '2:4': 'The common name omits لفظي. It can misleadingly suggest all government stops. The fuller جملة معلق عنها العمل اللفظي is exact, though books use the shorter label.',
    '3:0': 'Some verbs outside the listed أفعال القلوب behave like them and show تعليق.',
    '3:4': '“That He may test you as to which is best in deed.” بلا يبلو tests to draw out information, making it شبيه بفعل القلب.',
    '3:5': 'أيكم is مبتدأ مرفوع, not أيَّكم; أحسن عملا is خبر. The pair is a suspended clause filling the object positions, so يبلو does not govern its individual parts.',
    '4:2': '“Ask them which will vouch for that.” سأل يسأل is شبيه بفعل القلب, not a listed قلب verb. Its عمل is معلق لفظا, leaving أيهم مرفوع.',
  } }),
  '06/l3': plan(25, 'Cancellation and Preferred Readings', [
    [c('A question can suspend a one-object verb', 0, 1, 2, 3),
      c('Do not invent a second object position', 4, 5)],
    [c('صدر الكلام prevents earlier لفظي government', 0, 1),
      c('Negative إن and ما trigger تعليق', r(2, 0, 1), 3),
      c('لام الابتداء and اللام المزحلقة', r(2, 2, 3)),
      c('لعل, questioning and an oath response', r(2, 4, 5, 6))],
    [c('لام protects the clause’s own structure', 0, 1, 2),
      c('اللام المزحلقة keeps إنّ after نعلم', 3, 4, 5, 6)],
    [c('A منصوب interrogative need not be governed by يعلم', 0, 1, 2, 3),
      c('Which verbs can precede a question?', 4, 5),
      c('The form need not request new information', 6, 7)],
    [c('An oath response can trigger تعليق', 0, 1, 2)],
    [c('إلغاء cancels both kinds of government', 0, 1),
      c('Compare تعليق with إلغاء', 2, 3),
      c('Between the objects: إعمال is preferred', 4, 5, 7), c('Read the endings with إعمال', 6),
      c('After both objects: إلغاء is preferred', 8, 9, 11), c('Read the independent statement under إلغاء', 10)],
  ], [
    ['Triggers', 'A clause beginning with what holds صدر الكلام can suspend لفظي government.'],
    ['Question words', 'Their إعراب can come from inside the clause, as with أيَّ and ينقلبون.'],
    ['تعليق and إلغاء', 'تعليق keeps عمل محلي; إلغاء cancels both لفظي and محلي.'],
    ['Verb position', 'Between the objects favours إعمال; after both favours إلغاء.'],
  ], { copy: {
    '0:1': 'Even a single-object verb can be معلق when its object is a clause opening with استفهام.',
    '0:3': '“Let him see which is purest as food.” نظر takes one object. Its interrogative object clause triggers تعليق, so أيُّها stays مرفوع.',
    '0:5': 'There was one object, not a pair. استفهام causes the تعليق; calling the clause سادة مسد المفعولين would give it two positions it never had.',
    '1:1': 'صدر الكلام must stand at its clause’s head and cannot be governed by what precedes it. A following clause with this opening suspends the قلب verb’s عمل لفظي and retains its own إعراب.',
    '1:3': 'Negative إن and ما must lead their clauses. After علمت in لقد علمت ما أنزل, ما triggers تعليق: the verb governs the whole clause محلا only.',
    '2:2': 'Without لام, من اشتراه would be علموا’s first object. With it, لفظي government is suspended and the clause has its own إعراب.',
    '2:3': 'اللام المزحلقة triggers تعليق like لام الابتداء.',
    '2:5': 'After نعلم, the ordinary expectation would be نعلم أنّه.',
    '2:6': 'The present لام مزحلقة instead gives إنّه and a clause معلق عنها العمل.',
    '3:3': 'ينقلبون, not سيعلم, governs أيَّ. It is مفعول مطلق or مفعول فيه, depending on منقلب’s reading. The whole clause is suspended, so يعلم does not change its parts.',
    '3:5': 'استفهام holds صدارة. A preceding verb must be قلب or شبيه بفعل القلب: سلهم أيهم بذلك زعيم is valid, whereas ضربت أتشكر is not.',
    '3:7': 'Ordinary استفهام seeks knowledge. After فعل قلب, ليبلوني أأشكر أم أكفر means testing whether I am grateful or ungrateful, without asking a real question. Its role approaches حرف مصدر.',
    '4:1': 'علمت is فعل قلب. An oath using لفظ الجلالة is understood. لتأتين منيتي is its جواب; the لام makes that clause معلقا عنها العمل.',
    '4:2': '“I know my death will come; death’s arrows do not go astray.” سهام are arrows. Death is pictured shooting without missing left or right: everyone must die.',
    '5:1': 'إلغاء comes from لغو, null or futile. It cancels the verb’s government outright, unlike تعليق which stops only the لفظي effect.',
    '5:3': 'إعمال and إلغاء are both permitted. Position relative to the two معمولين determines preference.',
    '5:7': '“I knew Muhammad truthful.” Between the objects, إعمال is stronger. إلغاء remains possible but weaker: محمدٌ علمت صادقٌ, with مبتدأ and خبر and no government by علمت.',
    '5:11': 'After both معمولين, إلغاء is stronger. Neither لفظي nor محلي government remains; محمد صادق is an ordinary nominal sentence.',
  }, visuals: {
    '0:1': v('The object was always one clause', ['أَيُّهَا أَزْكَى طَعَامًا', 'One object position, not two']),
    '5:0': v('What remains?', ['تعليق', 'عمل محلي remains'], ['إلغاء', 'Both kinds are cancelled']),
  } }),
};

export const checks = {
  '06/l1': [q('What does the second object of a transformation verb name?', null, 'It completes the new state.'),
    q('What are عذب الشراب and مرّا in صيّر عذب الشراب مرّا?', ['First object, then second object.', 'Second object, then first object.', 'فاعل, then object.', 'مبتدأ, then خبر.'], 'Find what changes and what it becomes.'),
    q('What does ردّ add in يردونكم من بعد إيمانكم كفارا?', ['Returning to a state held before إيمان.', 'A change that never happens.', 'Only a change in judgement, never reality.', 'An unknown فاعل.'], 'Compare return with a general change.'),
    q('What specifically distinguishes ترك as a transformation verb?', ['Leaving a state after acting on something and departing.', 'A change without any prior involvement.', 'Returning to a state held before.', 'Only raising the possibility of change.'], 'Think of rain leaving the boulder bare.'),
    q('In وهبني الله فداء للعلم, identify فاعل then first object.', ['الله, then attached ني.', 'Attached ني, then الله.', 'فداء, then الله.', 'فداء, then للعلم.'], 'Find the agent and the thing whose role changes.'),
    q('جعل لكم السمع والأبصار والأفئدة has one coordinated object. Which meaning?', ['خلق or أوجد: creation, not transformation.', 'تحويل with two objects.', 'ظن, with second and third objects.', 'A ناقص verb of the كان family.'], 'No second object names a new state.')],
  '06/l2': [q('Which pair was مبتدأ and خبر in يريهم الله أعمالهم حسرات عليهم?', null, 'Look for the judgement within the three objects.'),
    q('Why أنّ instead of a plain مصدر in واعلموا أن الله مع المتقين?', ['It adds توكيد: know for certain.', 'It is the only حرف مصدر.', 'A مصدر can never follow اعلم.', 'It makes the clause إنشائية.'], 'Consider the strength of the statement.'),
    q('What government remains under تعليق?', ['محلي remains; لفظي is suspended.', 'Both are cancelled.', 'Both continue unchanged.', 'لفظي remains; محلي is suspended.'], 'Separate the clause’s position from its word endings.'),
    q('Why is أيكم مرفوع in ليبلوكم أيكم أحسن عملا?', ['It is مبتدأ inside the suspended clause.', 'يبلو is لازم and takes no object.', 'It is بدل from كم.', 'The verb is passive.'], 'The earlier verb does not reach the clause’s parts.'),
    q('How does سأل behave in سلهم أيهم بذلك زعيم?', ['It is شبيه بفعل القلب and triggers تعليق.', 'It is a full قلب verb like علم.', 'It is not قلب, so تعليق is impossible.', 'It is قلب only as أمر.'], 'Asking draws out information.')],
  '06/l3': [q('Why is أيها مرفوع in فلينظر أيها أزكى طعاما?', ['The interrogative object clause triggers تعليق.', 'نظر never takes any object.', 'It is a منصوب بدل of طعاما.', 'An أمر verb cannot govern an object.'], 'تعليق can affect a single-object verb.'),
    q('What does negative ما do in لقد علمت ما أنزل هؤلاء...?', ['Suspends لفظي government; محلي remains.', 'Becomes علمت’s direct object.', 'Cancels both kinds, as إلغاء.', 'Nothing; ما has no صدارة.'], 'ما must lead its clause.'),
    q('Without لام in علموا لمن اشتراه..., what would من اشتراه become?', ['علموا’s first object.', 'The same خبر as now.', 'علموا’s فاعل.', 'حال of علموا’s فاعل.'], 'Remove the trigger of تعليق.'),
    q('What governs أيَّ in سيعلم... أيَّ منقلب ينقلبون?', ['ينقلبون, the following verb.', 'سيعلم directly.', 'الذين ظلموا.', 'It has no عامل.'], 'Its منصوب state comes from inside the clause.'),
    q('What is لتأتين منيتي after علمت?', ['An omitted oath’s جواب; its لام triggers تعليق.', 'A direct object with no تعليق.', 'A بدل of منيتي.', 'Unrelated grammatically to علمت.'], 'An oath is understood from context.'),
    q('Which reading is preferred in محمدًا علمت صادقًا?', ['إعمال, with the verb between its objects.', 'إلغاء, because it is between the objects.', 'Neither reading is possible.', 'Both readings are impossible.'], 'Position changes preference, not the existence of both readings.')],
};

export const quizzes = {
  '06/l1': [q('What core meaning defines أفعال التحويل?'), q('What role is مرّا in صيّر عذب الشراب مرّا?'), q('Why ردّ rather than صيّر in يردونكم من بعد إيمانكم كفارا?'), q('What does صلدا describe in فأصابه وابل فتركه صلدا?'), q('What is خليلا in واتخذ الله إبراهيم خليلا?'), q('What distinguishes the two uses of جعل?')],
  '06/l2': [q('Which verb class governs three objects?'), q('What were its second and third objects originally?'), q('What does أنّ add in واعلموا أن الله مع المتقين?'), q('Which government survives تعليق?', ['محلي: the clause remains في محل نصب.', 'لفظي: individual endings still change.', 'Neither survives.', 'Both survive unchanged.']), q('Why is أيكم مرفوع in ليبلوكم أيكم أحسن عملا?', ['It is مبتدأ in the suspended clause.', 'يبلو can never take an object.', 'It is بدل of كم.', 'The verb is passive.']), q('Does سأل trigger تعليق in سلهم أيهم بذلك زعيم?')],
  '06/l3': [q('When can a single-object verb undergo تعليق?'), q('What gives negative إن and ما the ability to trigger تعليق?'), q('Removing لام in علموا لمن اشتراه... changes which role?', ['مبتدأ becomes علموا’s first object.', 'فاعل becomes object.', 'خبر becomes مبتدأ.', 'حال becomes تمييز.']), q('What governs أيَّ in وسيعلم... أيَّ منقلب ينقلبون?'), q('What separates تعليق from إلغاء?', ['تعليق stops لفظي only; إلغاء cancels both kinds.', 'تعليق cancels both; إلغاء stops لفظي only.', 'They name the same rule.', 'تعليق is only for ناقص verbs.']), q('Which is preferred when علمت follows محمد صادق?')],
};
