import { card as c, rows as r, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '29/l1': plan(132, 'The Parts and Kinds of Exception', [
    [c('Excluding something from a ruling', 0, 1, 2)],
    [c('Three parts of an exception', 0, 1, 2), c('Read the complete construction', 3)],
    [c('Is the source group stated?', 0, 1, 2), c('Restriction with a predicate', 3, 4, 5, 6), c('Restriction with a direct object', 7, 8)],
    [c('An exception within the group', 0, 1, 2, 3, 4)],
    [c('A corrective exception', 0, 1, 2, 3)],
  ], [
    ['Parts', 'مستثنى منه, أداة الاستثناء and مستثنى.'],
    ['Completeness', 'تام states the source group; مفرغ leaves it unstated.'],
    ['Membership', 'متصل belongs to the group; منقطع gives a related corrective aside.'],
    ['Restriction', 'After إلا in مفرغ, syntax assigns the required sentence role.'],
  ], { copy:{
    '0:0':'المستثنى is the eighth منصوب in this sequence. Its chapter, الاستثناء, has several constructions and case rules.',
    '0:2':'An exception removes its referent from the preceding ruling. إلا is the central marker; other markers and disconnected exceptions need additional distinctions.',
    '1:0':'جاء القوم إلا زيدا means “the people came, except Zayd”.',
    '1:2':'القوم is المستثنى منه, the source group. إلا is the marker. زيدا is المستثنى, the excluded person. These describe exception roles alongside ordinary syntax such as فاعل.',
    '2:0':'First ask whether المستثنى منه is expressed.',
    '2:2':'تام, also غير مفرغ, states it: جاء القوم إلا زيدا. غير تام, also مفرغ, leaves it unstated and normally follows نفي or شبه نفي, such as prohibition or a question carrying negation.',
    '2:3':'In مفرغ, إلا marks restriction and does not itself require exception نصب. The following part fills the role needed by the surrounding construction.',
    '2:5':'ما محمد إلا رسول means “Muhammad is only a messenger”.',
    '2:6':'رسولٌ is the predicate, خبر مرفوع, as in the underlying predication محمد رسول.',
    '2:8':'لا نعبد إلا الله means “we worship none but Allah”. اللهَ is the direct object of نعبد. It has نصب because it is مفعول به, not merely because it follows إلا.',
    '3:0':'متصل is a complete exception within its group.',
    '3:2':'The excluded referent belongs to المستثنى منه, not merely to the same broad kind.',
    '3:4':'The few in ثم توليتم إلا قليلا منكم belong to the addressed group. They did not turn away; their membership concerns the people addressed, not who actually turned away.',
    '4:1':'منقطع adds a related استدراك, like لكن, outside the preceding category, correcting a possible misleading inference.',
    '4:3':'Here Iblis is a jinn, unlike the angels, yet included in the command. This category distinction supports منقطع. Another account makes the shared addressed group the basis for متصل.',
  }, boxCopy:{'1:1':['المستثنى منه؛ الأداة؛ المستثنى.'],'2:1':['تام: ذكر المستثنى منه؛ مفرغ: لم يذكر.'],'3:1':['المتصل: المستثنى داخل في جماعة المستثنى منه.'],'4:0':['المنقطع: المستثنى خارج عن جنس المستثنى منه.']}, visuals:{'1:0':v('Identify the three exception parts',['القوم','The source group'],['إلا','The marker'],['زيدا','The excluded person'])}, analysisItemLabels:{'bank-19':{'فاعل مرفوع':'نائب فاعل مرفوع','مستثنى منه':'مستثنى منه مجرور'}} }),
  '29/l2': plan(133, 'Exception Markers and Case Choices', [
    [c('A useful source group', 0, 1, 2), c('An unrestricted indefinite group', 3, 4)],
    [c('Particles', 0, r(1,0)), c('Verbs and nouns', r(1,1,2)), c('ليس in an exception', 2, 3), c('خلا and عدا with or without ما', 4, 5)],
    [c('A specified excluded referent', 0, 1, 2), c('Usefulness of an indefinite exception', 3, 4)],
    [c('An affirmative exception', 0, 1, 2, 3, 4)],
    [c('Two cases after non-affirmative speech', 0, 1, 2), c('The accusative reading', 3, 4), c('Following the source group as بدل', 5, 6)],
    [c('Fronting the exception', 0, 1, 2, 3)],
  ], [
    ['Referents', 'The source requires useful or specified reference in both exception nouns.'],
    ['Markers', 'Particles, verbs and nouns have different government.'],
    ['إلا', 'Complete affirmative: نصب. Non-affirmative connected: نصب or بدل.'],
    ['Fronting', 'The taught rule uses نصب; other reported patterns require a different account.'],
  ], { copy:{
    '0:0':'The source requires a definite or useful indefinite المستثنى منه.',
    '0:2':'جاء القوم إلا أحمد has definite القوم. ما جاء أحد إلا أحمد has indefinite أحد made general by negation. مفيدة means the exception conveys a useful distinction, not that every indefinite must become definite.',
    '0:4':'The source rejects جاء قوم إلا خالدا without a useful restriction on قوم. A specified group can work, as in رجال كانوا عندك. The condition concerns meaning and context; it is not a universal ban on the word قوم without أل.',
    '1:0':'Exception markers belong to three grammatical categories.',
    '1:3':'The hadith excludes the tooth and claw from the described slaughtering instruments. ليس is a verb used for exception. In the accusative reading, السنَّ is its خبر, not its direct object; الظفرَ is coordinated with it.',
    '1:5':'خلا and عدا can be verbs with نصب or prepositions with جر. With ما المصدرية the standard analysis is verbal and requires نصب. The source’s unanimity claim is too strong: rare جر reports treat ما differently. Nor does this construction prove that every مصدرية ما in Arabic has only one possible clause type.',
    '2:0':'The source also asks for a definite or usefully specified مستثنى.',
    '2:2':'جاء القوم إلا زيدا names a definite referent. إلا رجلا مريضا specifies a sick man by an adjective; إلا رجل سوء specifies an evil man by إضافة.',
    '2:4':'The source rejects bare رجلا in جاء القوم إلا رجلا for lack of specification. This is its usefulness-based convention. A general ban is too strong: broader grammatical treatments admit indefinite exceptions when the intended distinction is useful.',
    '3:0':'With complete connected إلا, first check affirmation.',
    '3:2':'The standard كلام موجب rule requires نصب here. Descriptive إلا is a separate construction.',
    '3:4':'“They drank from it, except a few of them.” قليلا has نصب in this complete affirmative exception.',
    '4:0':'A complete connected exception after non-affirmative speech admits two standard choices.',
    '4:2':'غير موجب includes negation and relevant شبه النفي, such as prohibition. Use نصب on exception, or بدل from المستثنى منه with its case. A بدل need not always be nominative.',
    '4:4':'ولا يلتفت منكم أحد إلا امرأتك contains prohibitive لا, not simple negation. The source reads امرأتَك as an accusative exception. The verse has additional readings and antecedent analyses; this card follows the stated one.',
    '4:6':'ما فعلوه إلا قليل منهم gives قليلٌ as بدل from the attached واو الجماعة in فعلوه. That pronoun is visibly written and in the subject’s رفع position. It is not a hidden pronoun.',
    '5:1':'The taught fronting rule chooses نصب; ordinary بدل cannot precede its متبوع.',
    '5:3':'“I have no partisans except the family of Ahmad.” آل precedes شيعة and takes نصب. The source calls this obligatory; other grammarians report رفع under a different ordering analysis.',
  }, boxCopy:{'0:3':['جاء قوم إلا خالدا: يمنعه المصدر عند عدم الفائدة.'],'1:4':['خلا وعدا: نصب مع الفعل، وجر مع الحرف؛ ومع ما المصدرية فعلان.'],'2:3':['جاء القوم إلا رجلا: يطلب المصدر تخصيصا مفيدا.'],'3:1':['التام الموجب بإلا: نصب المستثنى.'],'4:1':['التام غير الموجب المتصل: نصب أو بدل.'],'5:0':['المستثنى المقدم: النصب في القاعدة المتبعة.']}, tableCopy:{'1:1':{0:['حرف','إلا، وحاشا في تحليل الجر'],1:['فعل','خلا، عدا، ما خلا، ما عدا، ليس، لا يكون'],2:['اسم','غير، سوى']}}, visuals:{'4:0':v('Two standard choices',['النصب','Exception case'],['البدل','Follow the source group’s case'])}, analysisLabels:{'فعل ومستثنى منه (فاعل مرفوع)':'فعل، وفاعل مستثنى منه','فعل ومستثنى منه (فاعل منصوب)':'فعل، وفاعل منصوب'} }),
  '29/l3': plan(134, 'Government and Meaning of Exception', [
    [c('Exception with a verb', 0, 1, 2, 3)],
    [c('The case of غير and its complement', 0, 1, 2, 3)],
    [c('The disconnected exception rule', 0, 1), c('Additional accounts in the source', 2, p(3,0)), c('The reported Tamim pattern', p(3,1))],
    [c('حاشا as a preposition', 0, 1, 2, 3)],
    [c('غير as description or exception', 0, 1, p(2,0)), c('إلا with a descriptive sense', p(2,1)), c('Several analyses of لا إله إلا الله', 3, 4)],
    [c('A rare exception with اللهم إلا', 0, 1)],
  ], [
    ['Verbs', 'خلا and عدا take objects; ليس and لا يكون have predicates.'],
    ['غير', 'Takes the exception’s case; its complement has جر by إضافة.'],
    ['Variation', 'حاشا and منقطع have recorded alternatives beyond the source’s main rule.'],
    ['Meaning', 'Distinguish exception, restriction, description and a rare qualification.'],
  ], { copy:{
    '0:1':'Verbal خلا and عدا take a direct object in نصب. With ليس or لا يكون, the accusative exception is خبر instead.',
    '0:3':'“Everything, save Allah, is vain.” Here ما is مصدرية, خلا is a past verb, and اللهَ is its object.',
    '1:1':'غير takes the corresponding إلا exception’s case; its complement has إضافة جر. Exception سوى follows this noun pattern too.',
    '1:3':'جاء الأولاد غيرَ زيدٍ is complete and affirmative: غيرَ takes exception نصب, while زيدٍ has إضافة جر.',
    '2:1':'The source’s main rule uses نصب in منقطع and disallows بدل. This matches the Hijazi pattern. It is not universal across Arabic varieties: the source itself then records a Tamim alternative.',
    '3:1':'حاشا adds تنزيه, clearing the excluded referent. Prepositional حاشا governs جر; verbal حاشا with نصب is also recorded.',
    '3:3':'This is the source’s تنزيه illustration. Its extended wording is not an authenticated hadith quotation. Here الأنبياءِ has جر after prepositional حاشا.',
    '4:0':'غير and إلا can express both difference and exclusion.',
    '4:4':'The source offers a descriptive غير reading and calls another reading مفرغ with omitted موجود. These accounts must stay distinct. A common analysis instead treats the expression as تام منفي, with اللهُ as بدل and an understood predicate such as حق. A مفرغ account can make الله the predicate; omitting a predicate alone does not prove تفريغ.',
    '5:1':'The example says this man does not miss the first prayer row, except in the rare case of illness. اللهم before إلا signals ندرة المستثنى. It has an invocatory origin; its discourse function here is introducing the unlikely qualification, not a request for illness.',
  }, copyParts:{'2:3':[
    'لست عليهم بمصيطر إلا من تولى وكفر is read with إلا as لكن in the source’s disconnected account: “but whoever turns away and disbelieves…” The discussion extends beyond the main متن; other contextual analyses also exist.',
    'وربة ليس بها أنيس إلا اليعافير وإلا العيس describes a deserted place with wild asses and camels rather than human company. The raised اليعافير and العيس illustrate the reported Tamim following pattern in منقطع after negation, beyond the source’s main rule.',
  ],'4:2':[
    'لا تدخلوا بيوتا غير بيوتكم uses غير descriptively: houses other than your own. جاء الأولاد غير زيد uses it for exception. These have different relations despite sharing the idea of difference.',
    'The source gives الناس هلكى إلا العالمون، والعالمون هلكى إلا العاملون، والعاملون هلكى إلا المخلصون for descriptive إلا with رفع. This is a teaching maxim, not an authenticated hadith claim. لو كان فيهما آلهة إلا الله لفسدتا likewise uses the taught غير sense: gods other than Allah.',
  ]}, boxCopy:{'0:0':['بعد خلا وعدا الفعليتين: نصب المفعول به.'],'1:0':['غير تعرب كالمستثنى بإلا؛ وما بعدها مضاف إليه.'],'2:0':['المنقطع: النصب في القاعدة الحجازية المتبعة.'],'2:2':['زيادتان: معنى لكن؛ والإتباع عند بني تميم.'],'3:0':['حاشا للتنزيه؛ تجر في التحليل الحرفي.'],'4:1':['غير أصلها الوصف؛ وإلا أصلها الاستثناء؛ وقد يتبادلان المعنى.'],'4:3':['لا إله إلا الله: للعلماء فيها تحليلات متعددة.']}, visuals:{'2:0':v('A related corrective aside',['المنقطع','A different category'],['النصب','The main rule taught']),'2:2':v('Company in the deserted place',['أنيس','Human company'],['اليعافير / العيس','Wild asses and camels'])}, analysisLabels:{'فعل ومستثنى منه (فاعل مرفوع)':'فعل، وفاعل مستثنى منه','فعل ومستثنى منه (فاعل منصوب)':'فعل، وفاعل منصوب'}, analysisItemLabels:{'bank-15':{'مستثنى منصوب':'مستثنى منصوب بإلا'}} }),
};

export const checks = {
  '29/l1':[
    q('What is المستثنى?', ['A referent excluded from the preceding ruling','A noun always in جر','Any noun after a preposition','A noun that cannot be مبني'], 'Identify what is excluded.'),
    q('What is زيدا in جاء القوم إلا زيدا?', ['المستثنى','المستثنى منه','أداة الاستثناء','الموصوف'], 'Zayd is the excluded person.'),
    q('Why is رسولٌ raised in ما محمد إلا رسول?', ['It is خبر; إلا does not impose نصب here','Its tanwin conceals نصب','إلا makes it genitive','Its first letter requires رفع'], 'This is a restricted predication.'),
    q('What is the exception in توليتم إلا قليلا منكم?', ['متصل','منقطع','غير تام','مفرغ'], 'The few belong to the addressed group.'),
    q('In the disconnected Iblis account, what sense does إلا carry?', ['استدراك, like لكن','Ordinary within-group exclusion','Restriction without a source group','Description, like غير'], 'The account distinguishes jinn from angels.'),
  ],
  '29/l2':[
    q('Why does the source reject جاء قوم إلا خالدا without further context?', ['Its group is an uninformative indefinite','The excluded noun lacks an adjective','Only nouns with أل can be source groups','Every source group needs إضافة'], 'The source requires معرفة or نكرة مفيدة.'),
    q('Why is خلا verbal in the standard ما المصدرية خلا analysis?', ['This مصدرية construction requires a verb','ما always introduces prepositions','ما turns خلا into a noun','ما removes all government'], 'Keep the specified analysis in view.'),
    q('What does مريضا add in إلا رجلا مريضا?', ['A description specifying the man','Previously missing tanwin','A change from نصب to رفع','Repetition of the source group'], 'The source calls this نكرة مخصوصة.'),
    q('What does the standard affirmative exception rule require of قليلا?', ['نصب','رفع','جر','A choice of نصب or بدل'], 'فشربوا منه إلا قليلا منهم is complete and affirmative.'),
    q('Why is قليلٌ raised in ما فعلوه إلا قليل منهم?', ['It is بدل from the attached subject واو','It is raised in every construction','إلا always governs رفع after negation','فعلوه has no subject'], 'The written واو الجماعة is in محل رفع.'),
    q('Which case does the taught fronting rule give آلَ أحمد?', ['نصب','رفع','Unrestricted نصب or بدل','جر'], 'It precedes شيعة in وما لي إلا آل أحمد شيعة.'),
  ],
  '29/l3':[
    q('What is اللهَ after verbal خلا in ما خلا الله?', ['مفعول به منصوب','مستثنى منصوب بإلا','حال','بدل من كل شيء'], 'Use the verb’s government.'),
    q('Why are غيرَ and زيدٍ different in جاء الأولاد غير زيد?', ['Exception نصب for غير; إضافة جر for زيد','Both must be منصوب','غير always has جر and زيد نصب','Only tanwin determines their cases'], 'Identify which noun carries the exception case.'),
    q('Does the main Hijazi rule taught allow بدل in منقطع?', ['No; it uses نصب','Yes, in every case','Only with an indefinite group','بدل is obligatory'], 'The Tamim account is a separately recorded alternative.'),
    q('What governs الأنبياءِ in the selected حاشا construction?', ['Prepositional حاشا gives جر','حاشا always gives نصب','Affirmation alone gives جر','حاشا has no government'], 'This question specifies the prepositional analysis.'),
    q('What is the taught إلا sense in آلهة إلا الله?', ['Descriptive غير','غير used for exception','Disconnected لكن','مفرغ restriction'], 'It describes the proposed gods as other than Allah.'),
    q('What does اللهم إلا introduce in the illness example?', ['A rare qualification','A request that the man become ill','A disconnected source group','A descriptive substitute for غير'], 'Its discourse function marks an unlikely exception.'),
  ],
};

export const quizzes = {
  '29/l1':[
    q('What is المستثنى?', ['Excluded from a preceding ruling','Always nominative','Any coordinated noun','Never indefinite']),
    q('What are the three exception parts?', ['Source group, marker, excluded referent','Verb, subject, direct object','Subject, predicate, marker','Exception, بدل, disconnected kind']),
    q('What normally precedes the مفرغ construction?', ['Negation or relevant شبه نفي','Every unrestricted command','Every possible question','Any affirmative statement']),
    q('What is رسولٌ in ما محمد إلا رسول?', ['A predicate; إلا marks restriction','An accusative exception','A genitive after إلا','A word without a grammatical role']),
    q('What kind is توليتم إلا قليلا منكم?', ['متصل','منقطع','غير تام','مفرغ']),
    q('Why use منقطع in the source’s Iblis account?', ['A corrective aside about the command’s wider scope','Only because Iblis is definite','Only because سجدوا is plural','Because إلا always means لكن']),
  ],
  '29/l2':[
    q('Which source-group requirement does the source state?', ['معرفة أو نكرة مفيدة','معرفة أو نكرة مخصوصة','مذكر أو مؤنث','Only singular or plural']),
    q('Which word class is غير?', ['اسم','حرف','فعل','Always ظرف']),
    q('Which excluded-referent requirement does the source state?', ['معرفة أو نكرة مخصوصة','معرفة أو نكرة مفيدة','Only مبني or معرب','مذكر أو مؤنث']),
    q('What is the standard complete affirmative إلا exception case?', ['نصب','رفع','نصب أو بدل','جر']),
    q('What are the standard non-affirmative connected choices?', ['نصب أو بدل','رفع أو جر only','نصب only','بدل only']),
    q('Which case does the source’s fronting rule choose?', ['نصب','رفع','نصب أو بدل without qualification','جر']),
  ],
  '29/l3':[
    q('What follows verbal خلا or عدا?', ['An accusative direct object','A genitive إضافة complement','A nominative بدل','An invariably indeclinable noun']),
    q('How does exception غير govern its complement?', ['غير takes the exception case; its complement has إضافة جر','غير always has نصب; its complement رفع','غير always has جر; its complement نصب','Both always have نصب']),
    q('Does the main Hijazi منقطع rule allow بدل?', ['No, it uses نصب','Yes, always','Only in Quran examples','It requires بدل']),
    q('What case follows prepositional حاشا?', ['جر','نصب','رفع','It varies merely with affirmation']),
    q('How do غير and إلا exchange functions?', ['غير can mark exception; إلا can carry a descriptive sense','Both have only their original function','Both only describe','Both only except']),
    q('What does اللهم إلا signal in the illness example?', ['A rare qualification','A request for illness','Negation of the entire sentence','Automatic conversion to مفرغ']),
  ],
};
