import { card as c, rows as r, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '14/l4': plan(71, 'Answering with إذن', [
    [c('A response and its consequence', 0, 1, 2)],
    [c('A particle, according to the majority', 0, 1, 2)],
    [c('Three conditions for government', 0, 1), c('A preceding و or ف permits either use', 2, 3),
      c('An oath may intervene', 4), c('An attested non-governing usage', 5)],
    [c('The Quranic spelling إذًا', 0, 1), c('Compare the two source particles', r(2, 0, 1)), c('Negation and response particles', r(2, 2, 3))],
  ], [
    ['إذن', 'Answers what precedes and expresses its consequence.'],
    ['Three conditions', 'Initial position, a future verb, and no intervening separator.'],
    ['Exceptions', 'An oath may intervene; after و or ف, either إعمال or إهمال.'],
    ['Quranic إذًا', 'Written with ألف; its attested Quranic uses are non-governing.'],
  ], { copy: {
    '0:0': 'إذن is the fourth particle giving المضارع نصب under specified conditions. It connects an answer to what precedes.',
    '0:2': 'One says أطيع الله, “I will obey Allah”. The response إذن تدخلَ الجنة means “Then you will enter Paradise”: answer and consequence.',
    '1:1': 'A minority derives إذن from nominal إذ with a following condition omitted and compensating tanwin added. The sense expands to إذا تطع الله تدخل الجنة, “If you obey Allah, you will enter Paradise”. This is a proposed derivation, not the majority classification.',
    '1:2': 'The majority treats إذن as a particle in its own right. The alternative explains why some books call it an اسم.',
    '2:1': 'أنت إذن تدخلُ الجنة keeps تدخلُ raised. أنت places إذن inside the sentence, outside صدر الكلام.',
    '2:3': 'فإذًا لا يؤتون الناس نقيرا retains نون, so يؤتون is مرفوع. After only و or ف, either government choice is possible; إهمال is common and occurs in the Quran.',
    '2:4': '<b>Future reference:</b> the verb refers to a coming action.<br><b>No separator:</b> إذن أنا أكرمُك stays raised because أنا intervenes.<br><b>Oath exception:</b> إذن والله أكرمَك permits نصب.',
    '2:5': 'A reported Arabic usage leaves إذن non-governing even when the three conditions hold. The usual governing rule and this transmitted alternative must be distinguished; it is not an unrestricted rule agreed on by all grammarians.',
    '3:1': 'The muṣḥaf writes إذًا with ألف. It has the same final n sound in connected speech as إذن; that sound is not proof of nounhood. Quranic usage is non-governing. Spelling and grammatical government are separate questions.',
  }, tableCopy: { '3:2': {
    0: ['أنْ', 'General source particle', 'مصدرية gives نصب; certainty instead requires lightened أنّ, supposition permits either.'],
    1: ['كي', 'Source particle in a purpose construction', 'Gives نصب, with written or understood لام.'],
    2: ['لن', 'Future negation', 'Gives نصب; emphasis is the account followed here.'],
    3: ['إذن', 'Answer and consequence', 'Three conditions, with the stated exceptions.'],
  } }, visuals: { '0:0': v('A reply follows a statement', ['أطيع الله', 'The statement'], ['إذن تدخلَ الجنة', 'The consequence']),
    '2:2': v('Compare the intervening words', ['إذن أنا أكرمُك', 'أنا blocks government'], ['إذن والله أكرمَك', 'An oath permits government']),
    '2:3': v('A usage distinction', ['إعمال', 'The usual three-condition rule'], ['إهمال', 'Also transmitted with the conditions met']) } }),
  '14/l5': plan(72, 'Particles Governing One Verb', [
    [c('Four particles give one verb جزم', 0, 1)],
    [c('لم negates a past event', 0, 1, 2, 3)],
    [c('لمّا adds “not yet”', 0, 1, 2), c('An expectation of fuller faith', 3, 4), c('Same government, different expectation', 5, 6)],
    [c('لام الأمر issues a command', 0, 1, 2, 3)],
    [c('لا الناهية issues a prohibition', 0, 1, 2, 3)],
  ], [
    ['One verb', 'لم، لمّا، لام الأمر، لا الناهية.'],
    ['لم', 'Negation and past reference; the verb remains مضارع in form.'],
    ['لمّا', '“Not yet”: negation continues to now, with an anticipated occurrence.'],
    ['Request', 'لام الأمر: do it. لا الناهية: do not do it. Both give جزم.'],
  ], { copy: {
    '0:0': 'After نصب, we turn to جزم. One group governs a single verb; another governs a condition and its answer. Begin with the single-verb group.',
    '1:1': 'لم negates an event and gives it past reference, while the verb’s form remains مضارع.',
    '1:3': '“He has neither begotten nor been begotten.” يلدْ and يولدْ are مضارع مجزوم بلم. The verse’s context expresses perpetual negation. Allah is الأول: ليس قبله شيء, nothing precedes Him.',
    '2:1': 'لمّا shares negation, جزم and past reference with لم, adding “not yet”: the event is still anticipated.',
    '2:2': 'لم يحجّ زيد: Zayd did not perform Hajj, with no expectation specified. لمّا يحجّ عبد الله: Abdullah has not yet performed it; it remains anticipated.',
    '2:4': 'In the interpretation followed here, the new Muslims have accepted Islam but full faith has not yet settled in their hearts. لمّا leaves fuller faith anticipated as they learn the religion and spend time with the Messenger ﷺ.',
    '2:6': 'Both govern المضارع with جزم. Here the key semantic contrast is expectation: لم is silent about later occurrence; لمّا presents it as not yet attained. This does not deny other syntactic differences between the particles.',
    '3:1': 'A bare imperative افعل addresses the listener. لام الأمر also allows a command about someone absent: “let him do”.',
    '3:3': '“Whoever hopes to meet his Lord, let him do righteous deeds.” لام gives يعملْ جزم and expresses a command about that person.',
    '4:1': 'لا الناهية gives المضارع جزم and prohibits an action, complementing positive لام الأمر.',
    '4:3': '“Let him associate no one in worship of his Lord.” يشركْ is مجزوم بلا الناهية. The verse joins what to do, فليعمل, and what to avoid, ولا يشرك.',
  }, boxCopy: { '2:5': ['لم ولمّا تجزمان المضارع. والفرق المعنوي هنا توقّع الحصول مع لمّا.'] },
    visuals: { '2:0': v('The expectation changes', ['لم يحجّ زيد', 'Did not; no forecast'], ['لمّا يحجّ عبد الله', 'Has not yet; still anticipated']) } }),
  '14/l6': plan(73, 'The Condition and Its Answer', [
    [c('A condition and its answer', 0, 1, 2, 3)],
    [c('A request can imply a condition', 0, 1, r(2, 0)), c('A result after a question or wish', r(2, 1, 2)), c('A result after an invitation', r(2, 3))],
    [c('إنْ plus emphatic ما becomes إمّا', 0, 1, 2), c('Two present or two past verbs', 3, r(4, 0, 1)), c('Mixing the verb forms', r(4, 2, 3))],
    [c('Verb form can shape the presentation', 0, 1), c('A complete occurrence in context', r(2, 0, 1)), c('Repeated or gradual action', r(2, 2, 3))],
    [c('إنْ and إذا present different expectations', 0, 1), c('A possible or uncertain condition', r(2, 0, 1)),
      c('A hypothetical or impossible premise', r(2, 2, 3)), c('The expected case and the rarer case', r(2, 4), 3)],
    [c('فاء links a nominal answer', 0, 1, 2, 3), c('Other answers needing فاء', 4, 5), c('إذما also governs a condition and answer', 6, 7, 8)],
  ], [
    ['Two parts', 'شرط and جواب/جزاء, with جزم in form or grammatical position.'],
    ['After a request', 'An intended result may be مجزوم through an implied condition.'],
    ['إنْ and إذا', 'Usually an open or hypothetical case versus an expected one; context matters.'],
    ['فاء الجواب', 'Links answers such as nominal clauses, commands and clauses with قد.'],
  ], { copy: {
    '0:0': 'إنْ and إذما govern two verbs.',
    '0:3': 'Avoid major sins: Allah removes lesser sins and admits you nobly. تجتنبوا is شرط, مجزوم بحذف النون; نكفّرْ is جواب. ندخلْ follows by عطف: جزم بالتبعية, not بالأصالة.',
    '1:0': 'After a request, a مضارع intended as its result can have جزم through an understood condition and answer.',
    '2:2': '“If Satan incites you, seek refuge in Allah.” إمّا combines إنْ with emphatic ما. ينزغنّك carries heavy نون التوكيد, common with this construction; its verb is مبني في محل جزم.',
    '3:1': 'Past forms can present an event as a single complete occurrence or a bundled lapse. Present forms can portray repetition or gradual action. These are contextual rhetorical effects, not rules that every past means once or every present means repeatedly.',
    '4:0': 'Compare how the condition is presented.',
    '4:3': 'إذا قمتم إلى الصلاة uses إذا for the regular prayer situation; وإن كنتم جنبا uses إنْ for the less frequent state. إنْ can suggest relative rarity even where eventual occurrence is expected.',
    '5:0': 'Some answers need a linking فاء.',
    '5:3': 'يمسسك is the مجزوم condition. فلا كاشف له إلا هو is a nominal answer: فاء links it, and the whole clause occupies محل جزم. Its internal words keep their own government.',
    '5:5': 'Compare من يشرك بالله فقد ضل ضلالا بعيدا, with قد and a stated result, and إن كنتم تحبون الله فاتبعوني, with an imperative. Both require فاء. A bare past answer, however, can connect directly: وإن عدتم عدنا. Lack of a visible جزم ending alone is not the test.',
    '5:8': '“If you repent, your repentance will be accepted.” إذما gives two verbs جزم like إنْ. It is absent from the Quran but appears in other Arabic, including transmitted usage. The condition/answer forms and linking فاء apply; the implied particle after requests is conventionally إنْ.',
  }, analysisLabels: {
    'حرف شرط جازم لفعلين': 'شرط جازم لفعلين',
    'فعل الشرط، مجزوم بحذف النون': 'شرط؛ جزم بحذف نون',
    'جواب الشرط، مجزوم': 'جواب مجزوم',
    'جار ومجرور ومفعول به': 'جرّ ومفعول به',
    'فعل الشرط، مجزوم بالسكون': 'شرط؛ جزم بالسكون',
    'جواب الشرط، مجزوم بالتبعية لا بالأصالة': 'جواب مجزوم بالتبعية',
    'مفعول به منصوب': 'مفعول مطلق منصوب',
    'فعل أمر وفاعله (طلب يقدَّر بعده إنْ الشرطية)': 'أمر وفاعل؛ شرط مقدّر بإنْ',
    'فعل مضارع مجزوم بإنْ مقدرة، جواب الشرط': 'جواب مجزوم بإنْ مقدّرة',
    'فعل أمر وفاعله (طلب يقدَّر بعده إذما)': 'أمر وفاعل؛ شرط مقدّر بإذما',
    'فعل مضارع مجزوم بإنْ الشرطية المذكورة صراحةً، لا المقدرة': 'جواب مجزوم بإنْ صريحة',
    'فعل أمر': 'اسم فعل أمر',
  }, boxCopy: { '0:1': ['إنْ: شرط وجواب أو جزاء، كلاهما مجزوم.'],
    '2:0': ['إمّا = إنْ الشرطية + ما الزائدة للتوكيد، ويكثر بعدها توكيد الفعل بالنون.'],
    '3:0': ['اختيار الماضي والمضارع قد يحمل دلالة بلاغية بحسب السياق.'],
    '4:1': ['الأصل في إنْ فرض الشرط، وفي إذا توقّع وقوعه. وقد تفيد إنْ التقليل بحسب السياق.'],
    '5:1': ['فاء الجواب تربط جملة في محل جزم، دون جزم ألفاظها بإنْ.'],
    '5:4': ['تجب الفاء إذا لم يصلح الجواب شرطا، كالجملة الاسمية والطلبية والمصدّرة بقد.'],
  }, tableCopy: {
    '1:2': { 0: ['أمر', 'تعالوا أتلُ ما حرّم ربكم عليكم', 'إن تأتوا أتلُ: a condition is understood.'],
      1: ['استفهام', 'هل تزورنا نكرمْك', 'إن تزرْنا نكرمْك.'], 2: ['تمنٍّ', 'ليتك عندي أخدمْك', 'إن كنت عندي أخدمْك.'],
      3: ['عرض', 'ألا تنزل بنا تصبْ خيرا', 'إن تنزلْ بنا تصبْ خيرا.'] },
    '2:4': { 0: ['مضارع ثم مضارع', 'وإن تعودوا نعدْ: both visibly مجزوم.'],
      1: ['ماضٍ ثم ماضٍ', 'وإن عدتم عدنا: both مبني في محل جزم.'],
      2: ['مضارع ثم ماضٍ', 'من يقم ليلة القدر إيمانا واحتسابا غفر له ما تقدم من ذنبه.'],
      3: ['ماضٍ ثم مضارع', 'من كان يريد حرث الآخرة نزدْ له في حرثه. After a past condition, a present answer can generally have جزم or رفع.'] },
    '3:2': { 0: ['ماضٍ', 'A single further request', 'إن سألتك عن شيء بعدها فلا تصاحبني.'],
      1: ['ماضٍ', 'A lapse viewed as a whole', 'ربنا لا تؤاخذنا إن نسينا أو أخطأنا. The form alone does not exclude repeated lapses.'],
      2: ['مضارع', 'Repeated, insistent asking', 'ولا يسألكم أموالكم إن يسألكموها فيحفكم تبخلوا.'],
      3: ['مضارع', 'Counting progressively', 'وإن تعدّوا نعمة الله لا تحصوها: the task cannot be exhausted.'] },
    '4:2': { 0: ['Possible', 'وإن كنتم جنبا فاطّهّروا: a state that may arise.'],
      1: ['Uncertain to the addressee', 'فإن استقرّ مكانه فسوف تراني: the mountain’s remaining in place.'],
      2: ['Hypothetical', 'أرأيتم إن جعل الله عليكم الليل سرمدا: “what if?”'],
      3: ['Impossible premise', 'إن كان للرحمن ولد فأنا أول العابدين: the conditional interpretation considered here.'],
      4: ['Expected occurrence with إذا', 'إذا جاء أجلهم فلا يستأخرون ساعة: the appointed time will come.'] },
  }, visuals: { '3:0': v('A contextual contrast', ['ماضٍ', 'A complete occurrence'], ['مضارع', 'Repetition or progression']) } }),
  '14/l2': plan(69, 'When أنْ Must Be Understood', [
    [c('Five contexts for implied أنْ', 0, 1), c('حتى points to a future event', 2, 3, 4), c('A future within a past narrative', 5, 6)],
    [c('لام الجحود after a negative كان', 0, 1), c('أو meaning “until”', 2, 3, 4), c('أو meaning “unless”', 5, 6)],
    [c('واو المعية combines the actions', 0, 1, 2), c('A wish for a combined outcome', 3, 4), c('Eternal knowledge and manifest action', 5, 6)],
    [c('فاء connects cause and result', 0, 1), c('After negation or a command', r(2, 0, 1)), c('After prohibition or a question', r(2, 2, 3)),
      c('After a wish or hope', r(2, 4, 5)), c('After an invitation or urging', r(2, 6, 7))],
    [c('Some omissions are transmitted exceptions', 0, 1, r(2, 0)), c('Two more attested expressions', r(2, 1, 2), 3, 4)],
  ], [
    ['Implied أنْ', 'After حتى, لام الجحود, qualifying أو, واو المعية and causal فاء.'],
    ['حتى', 'Future at speaking time requires نصب; a narrated past allows another perspective.'],
    ['واو and فاء', 'The relevant معية or سببية follows negation or a request.'],
    ['سماع', 'Exceptional omissions are attested; they do not establish a general rule.'],
  ], { copy: {
    '0:0': 'Five further contexts require implied أنْ when used in the senses and conditions taught here.',
    '0:2': 'With حتى, ask when the following event occurs.',
    '0:4': '“You will not attain righteousness until you spend what you love.” Spending is future at the time of speaking, so تنفقوا requires نصب.',
    '0:6': 'The familiar يقولَ treats the saying as future relative to the earlier shaking. Nafi’s يقولُ presents that past scene as unfolding now. This reported present permits رفع; the saying is not in the speaker’s actual future.',
    '1:1': '“Allah would not let your faith go to waste.” لام الجحود follows negative كان and requires implied أنْ before يضيعَ. Its fuller treatment appeared earlier.',
    '1:2': 'أو requires implied أنْ when it means إلى أن or إلا.',
    '1:4': '“I will face hardship until I reach my goal; hopes yield only to the patient.” أو means إلى أن, giving أدركَ نصب.',
    '1:6': 'The reed metaphor describes breaking a people’s resistance unless they straighten themselves. أو means إلا أن, giving تستقيمَ نصب. The source paraphrases this as رمت لينهم أو يستقيموا, “I sought to soften them unless they set themselves right”.',
    '2:2': 'ويعلمَ has نصب after واو المعية and negation. A reported ويعلمُ has رفع as a separate clause, “and He knows”; it is not simple coordination with the preceding مجزوم verb.',
    '2:4': 'The disbelievers wish to return while not denying the signs and while being believers. The واو joins these into one wished-for outcome, after تمنّي.',
    '2:6': 'Allah’s knowledge is eternal and is not preceded by ignorance. The verse concerns the actual occurrence and manifestation of جهاد, distinguishing its people outwardly, not Allah acquiring previously absent knowledge.',
    '3:1': 'After negation or request, a causal فاء introduces a result. The following مضارع has نصب from obligatorily implied أنْ.',
    '4:0': 'Some expressions omit أنْ outside the regular rules. They are learned from transmission.',
    '4:4': 'These sayings are سماعي: preserve their transmitted usage without inventing new omissions of أنْ.',
  }, analysisLabels: {
    'فعل مضارع منصوب وفاعله': 'مضارع منصوب وفاعل',
    'فعل مضارع منصوب بأن مضمرة وجوبا': 'مضارع منصوب بأنْ وجوبا',
    'فعل مضارع منصوب بأن مضمرة وجوبا بعد واو المعية': 'نصب بأنْ بعد واو معية',
    'فعل مضارع منصوب بأن مضمرة جوازًا': 'نصب بأنْ جوازا',
    'مفعول به منصوب': 'مفعول مطلق منصوب',
  }, boxCopy: {
    '0:1': ['تضمر أنْ وجوبا بعد حتى، ولام الجحود، وأو بمعنى إلى أن أو إلا، وواو المعية وفاء السببية بعد نفي أو طلب.'],
    '1:3': ['لأستسهلنّ الصعب أو أدركَ المنى، فما انقادت الآمال إلا لصابر.'],
    '1:5': ['وكنت إذا غمزت قناة قوم، كسرت كعوبها أو تستقيما.'],
    '2:0': ['واو المعية بمعنى مع. بعد نفي أو طلب، ينصب المضارع بأنْ مضمرة.'],
    '3:0': ['فاء السببية: ما قبلها سبب، وما بعدها نتيجة.'],
  }, tableCopy: { '4:2': {
    0: ['مُرْهُ يَحْفِرَها', 'Command him to dig it: مُرْهُ أن يحفرَها.'],
    1: ['خُذِ اللصَّ قبلَ يأخذَك', 'Seize the thief before he seizes you: قبل أن يأخذك.'],
    2: ['تسمعَ بالمُعَيْديّ خير من أن تراه', 'Hearing of al-Muʿaydi is better than seeing him. First أنْ implied; second explicit.'],
  } } }),
  '14/l3': plan(70, 'Purpose with كي, Negation with لن', [
    [c('كي explains the purpose', 0, 1, 2, 3)],
    [c('A written or understood لام', 0, 1, 2)],
    [c('كي can govern a noun or a verb', 0, 1, 2), c('Purpose and eventual outcome', 3, 4)],
    [c('لن negates a future action', 0, 1, 2, 3)],
    [c('Emphasis does not mean eternity', 0, 1, 2, 3)],
  ], [
    ['كي', 'A source particle used to express purpose; the verb has نصب.'],
    ['لام', 'Explicit or understood with مصدرية كي; absent with prepositional كي.'],
    ['لن', 'Future negation; the emphatic account is used here.'],
    ['Permanence', 'Comes from context, not automatically from لن.'],
  ], { copy: {
    '0:0': 'Like أنْ, مصدرية كي turns a clause into a noun-equivalent. Its construction also gives a purpose, تعليل.',
    '0:3': 'Musa was returned to his mother to comfort her. كي تقرّ explains why; تقرَّ has نصب.',
    '1:0': 'كي may follow an explicit لام الجر.',
    '1:2': 'In فرجعناك إلى أمك كي تقر عينها, the مصدرية analysis understands لكي. Compare فرددناه إلى أمه كي تقر عينها. The purpose relation remains even when لام is unspoken.',
    '2:0': 'كي can instead be a preposition: كيمه, “for what?”, resembles لِمَ or لماذا.',
    '2:2': 'With مصدرية كي, لام is explicit or understood. With prepositional كي, no second لام is supplied. Before a verb, prepositional كي instead implies أنْ. An unwritten لام is therefore an analysis, not a visible spelling test.',
    '2:4': 'This course contrasts genuine purpose with لام’s wider causal and outcome uses. لام العاقبة can mark an unintended result; كي and لام are not automatically interchangeable in context.',
    '3:0': 'لن gives a present-tense verb نصب and negates a future event.',
    '3:3': 'Maryam vows silence for today. On the emphatic analysis followed here, لن states that resolve more firmly than لا أكلم اليوم إنسيا. Grammarians debate whether emphasis belongs to لن itself; لا can also negate the future.',
    '4:0': 'The strength of لن is debated.',
    '4:2': 'In the emphatic account used here, تأكيد does not itself mean تأبيد, “forever”. Permanent negation needs a contextual قرينة.',
    '4:3': 'لن يخلقوا ذبابا denies the idols’ power to create even a fly, even together. That context supports “never”. Maryam’s اليوم instead limits her silence to today.',
  }, analysisLabels: {
    'فعل ماضٍ وفاعله ومفعوله': 'ماضٍ وفاعل ومفعول',
    'حرف مصدر للتعليل ناصب': 'مصدرية للتعليل والنصب',
    'حرف مصدر وناصب': 'مصدرية بلا تعليل',
    'حرف جر': 'جرّ بلا أنْ مضمرة',
    'فاعل مرفوع': 'نائب فاعل مرفوع',
    'حرف مصدر للتعليل، ولا يحتاج إلى لام مقدرة قبله': 'مصدرية دون لام مقدّرة',
    'مفعول به منصوب': 'مفعول مطلق منصوب',
  }, boxCopy: { '3:1': ['لن لنفي المستقبل ونصب المضارع.'] },
    visuals: { '4:0': v('Read the contextual limit', ['لن يخلقوا ذبابا', 'Inability to create'], ['فلن أكلم اليوم إنسيا', 'Silence for this day']) } }),
  '14/l1': plan(68, 'أنْ and the Subjunctive Verb', [
    [c('A verbal clause becomes a noun-equivalent', 0, 1, 2, 3)],
    [c('After certainty', 0, 1, 2, 3, 4), c('Choosing a full or lightened expression', 5, 6)],
    [c('After supposition, the verb may have نصب', 0, 1, 2), c('An attested raised verb after حسب', 3, 4), c('A mental meaning is not enough', 5, 6, 7)],
    [c('Optional أنْ after a prepositional لام', 0, 1, 2), c('أنْ must remain in لئلّا', 3, 4)],
    [c('A verb coordinated with a noun', 0, 1, 2), c('A contented life over fine clothes', 3, 4),
      c('Lut’s wish: two coordination analyses', p(5, 0)), c('A fresh assertion of true support', p(5, 1))],
  ], [
    ['أنْ المصدرية', 'Gives المضارع نصب and makes a مصدر مؤول.'],
    ['What precedes', 'Certainty: lightened أنّ. Supposition: either. Other verbs here: مصدرية.'],
    ['Optional omission', 'After لام, or coordinating with a plain noun.'],
    ['لئلّا', 'أنْ remains explicit inside لِأَنْ لا.'],
  ], { copy: {
    '0:0': 'Four particles give المضارع نصب: أنْ، لن، إذن، كي. We begin with أنْ.',
    '0:3': '“Do you not love for Allah to forgive you?” أن يغفر الله لكم equals مغفرة الله لكم. أنْ turns the verbal clause into a source-equivalent noun.',
    '1:0': 'First, verbs of certainty.',
    '1:2': 'After علم, أنْ is lightened أنّ: its اسم is an omitted ضمير الشأن; its خبر is the following clause.',
    '1:4': 'سيكونُ has رفع; سيكونَ is not an alternative here.',
    '1:6': 'After certainty, compare أنه سيكون with أنْ سيكون. Both structures are grammatical; choosing between them involves بلاغة and context, treated in علم المعاني and tafsir.',
    '2:0': 'After a supposition verb such as حسب, both lightened and subjunctive مصدرية analyses are possible.',
    '2:2': '“Does man think he will be left neglected?” يُتركَ has نصب from مصدرية أنْ, the common choice after supposition verbs.',
    '2:4': 'An alternative recitation has أنْ لا تكونُ فتنة. أنْ is lightened; لا تكون فتنة is its clause-predicate, with the verb مرفوع.',
    '2:5': 'A mental meaning alone does not make a technical فعل قلب. أراد، كره and طمع lack the relevant two-object pattern.',
    '2:7': 'In “We hope our Lord forgives our sins”, أنْ is مصدرية and gives يغفرَ نصب.',
    '3:0': 'An understood أنْ can still give the verb نصب.',
    '3:2': 'Compare ليغفر لك الله and لأن يغفر لك الله: after prepositional لام, أنْ may be stated or omitted. With لا, however, the form لئلا retains أنْ explicitly.',
    '3:4': 'لئلا = لأن لا: “So people have no argument against you.” The أنْ remains inside this combined form.',
    '4:0': 'After a conjunction following a plain noun, an understood أنْ lets a verb match it as a noun-equivalent.',
    '4:2': 'Revelation, from behind a veil, or sending a messenger: (أن) يرسل رسولا coordinates with وحيا and من وراء حجاب. The implied أنْ supplies the noun-equivalent.',
    '4:4': '“Wearing a coarse cloak with contentment is dearer than fine silks.” لبس, a plain noun, joins (أن) تقر عيني. The speaker values a humble, happy marriage.',
  }, boxCopy: { '1:1': ['بعد اليقين: أنْ مخففة، لا تنصب المضارع.'],
    '3:1': ['تضمر أنْ جوازا بعد اللام دون لا، وبعد عاطف مسبوق باسم صريح.'],
    '4:3': ['ولبس عباءة و(أن) تقر عيني أحب إليّ من لبس الشفوف.'] }, copyParts: {
    '4:5': [
      'لو أن لي بكم قوة أو آوي إلى ركن شديد: Lut wishes for strength or support. آوي has رفع in the familiar recitation. One analysis coordinates with أن لي بكم قوة, with an omitted جواب لو. Another coordinates with قوة, supplying an omitted, non-governing أنْ; compare ومن آياته يريكم البرق خوفا وطمعا. Both read ركن شديد as a supporting tribe.',
      'A third account takes أو as بل and starts a fresh clause: Lut turns from wished-for personal strength to Allah as his support. The hadith says يرحم الله لوطا، لقد كان يأوي إلى ركن شديد. With the first two accounts, it recalls divine support while he sought human protection. With the third, it reinforces that he had not forgotten Allah, even in distress.',
    ],
  }, visuals: { '4:2': v('Two coordination targets', ['أنّ لي بكم قوّة', 'The noun-equivalent'], ['قوّة', 'The plain noun']),
    '4:3': v('A change of direction in the third account', ['قوّة', 'Personal strength wished for'], ['ركن شديد', 'Allah as true support']) } }),
};

export const checks = {
  '14/l4': [q('What does إذن contribute to إذن تدخلَ الجنة?', ['A response drawing out the preceding statement’s consequence.', 'An unrelated topic.', 'Negation of the statement.', 'A question.'], 'Connect the response to أطيع الله.'),
    q('How is إذن classified in the two accounts?', ['Majority: particle. Minority: nominal إذ plus compensating tanwin.', 'Majority: noun. Minority: particle.', 'Both call it a verb.', 'There is no disagreement.'], 'The derivation is a minority proposal.'),
    q('Why is أكرمُ raised in إذن أنا أكرمُك?', ['أنا separates إذن from the verb.', 'إذن can never govern.', 'أكرم is always مبني.', 'إذن is not initial here.'], 'Find the intervening word.'),
    q('What should we distinguish in Quranic فإذًا?', ['Its ألف spelling, final n sound in connected speech, and non-governing use.', 'Its complete absence from the Quran.', 'Spelling always reproducing every sound exactly.', 'An arbitrary pronunciation in every occurrence.'], 'Spelling and government are separate questions.')],
  '14/l5': [q('Which four particles govern one verb with جزم?', ['لم، لمّا، لام الأمر، لا الناهية.', 'إن، إذما، لن، إذن.', 'أن، كي، لم، لمّا.', 'حتى، فاء، واو، أو.'], 'Separate negative statements from commands and prohibitions.'),
    q('What does لم do to يلدْ and يولدْ?', ['Negates with past reference while the form remains مضارع.', 'Keeps an exclusively future meaning.', 'Turns them into imperatives.', 'Only makes them passive.'], 'Form and time reference need not match.'),
    q('What expectation distinguishes لمّا from لم here?', ['لمّا means “not yet”; لم specifies no later expectation.', 'لمّا governs nouns, لم verbs.', 'لمّا only follows heart verbs.', 'لم only negates imperatives.'], 'Does the particle anticipate later occurrence?'),
    q('What makes فليعملْ a command about الغائب?', ['لام الأمر.', 'لا الناهية.', 'لمّا.', 'Implied أنْ.'], 'The request is directed to “whoever hopes”.'),
    q('What do فليعمل and ولا يشرك cover together?', ['What to do and what to avoid.', 'Two prohibitions.', 'Two positive commands.', 'One command repeated.'], 'Compare command with prohibition.')],
  '14/l6': [q('Why is وندخلْكم مجزوم after نكفّرْ?', ['Coordination: it follows the answer in جزم.', 'إن directly governs three parts equally.', 'It is actually مرفوع.', 'All coordinated verbs have نصب.'], 'Distinguish الأصالة from التبعية.'),
    q('Why is أتلُ مجزوم in تعالوا أتلُ...?', ['An implied condition after the command: if you come, I will recite.', 'An implied لم.', 'It is actually مرفوع.', 'تعالوا is itself a particle.'], 'The second action is the intended result.'),
    q('What combines in إمّا ينزغنّك?', ['إنْ plus emphatic ما, accompanied here by heavy نون.', 'إن plus negative لا.', 'أن plus source ما.', 'إذا plus restraining ما.'], 'Look at the emphatic conditional construction.'),
    q('What effect does تعدّوا convey in this context?', ['Counting gradually, without exhausting the favors.', 'A single finished tally.', 'One bundled lapse.', 'No contextual effect.'], 'Consider the process of counting.'),
    q('On its conditional reading, إن كان للرحمن ولد supposes what?', null, 'The premise does not become possible merely because it is stated.'),
    q('Why use فاء before فلا كاشف له إلا هو?', ['The nominal answer needs a link and occupies محل جزم.', 'إن never permits any answer beginning with لا.', 'يمسسك has no جزم.', 'Every conditional answer needs فاء.'], 'Identify the answer’s structure.')],
  '14/l2': [q('Why can Nafi’s يقولُ have رفع after حتى here?', ['It presents the past saying as unfolding, not as the speaker’s actual future.', 'حتى never permits نصب.', 'الرسول blocks نصب.', 'زلزلوا is منصوب.'], 'Distinguish the narrated timeline from speaking time.'),
    q('Which senses of أو require implied أنْ?', ['إلى أن, “until”, and إلا, “unless”.', 'و and أم.', 'بل and لكن.', 'لعل and ليت.'], 'Both set a limit or exception.'),
    q('What does ولما يعلم الله mean here?', ['The action becomes manifest; Allah’s knowledge is eternal.', 'Allah previously lacked the knowledge.', 'علم means only public praise.', 'Allah has no knowledge of جهاد.'], 'Distinguish knowledge from the event’s occurrence.'),
    q('What precedes فاء in من ذا الذي يقرض الله... فيضاعفه?', null, 'من asks a question.'),
    q('Does attested مُره يحفرَها license new omissions of أنْ?', ['No; it is transmitted usage, not a general rule.', 'Yes, after every imperative.', 'Yes; حفر never takes أنْ.', 'No; no أنْ is understood here.'], 'سماعي describes the basis of the example.')],
  '14/l3': [q('What meaning does the كي construction express?', ['تعليل: purpose or reason.', 'Emphatic negation.', 'An answer to someone.', 'A wish.'], 'Ask why the earlier action happened.'),
    q('In the مصدرية analysis of كي تقرّ, where is لام?', ['Understood, though unwritten.', 'Absent even from the analysis.', 'Impossible because كي must be prepositional.', 'Written in every Quranic use.'], 'Expand كي to لكي.'),
    q('Which analysis distinguishes the two uses of كي?', ['لام is explicit or understood with مصدرية كي, absent with prepositional كي.', 'كي takes tanwin in only one use.', 'كي agrees in gender.', 'Only sentence position matters.'], 'Follow the government of the construction.'),
    q('On the emphatic account, what does لن add in فلن أكلم اليوم إنسيا?', ['A firmer negation than plain لا.', 'No difference at all.', 'Permission to negate المضارع, which لا cannot do.', 'Future reference, which لا never has.'], 'This lesson notes the disagreement about emphasis.'),
    q('Why does لن يخلقوا ذبابا suggest permanent inability?', ['Context supports permanence; لن alone does not require it.', 'لن always means forever.', 'لن can never express permanent negation.', 'اليوم makes silence eternal.'], 'Look for the contextual قرينة.')],
  '14/l1': [q('Which مصدر matches أن يغفر الله لكم?', null, 'Keep the same relation expressed by لكم.'),
    q('Why is سيكونُ raised in علم أن سيكون...?', ['Certainty makes أنْ lightened, with no government of the verb.', 'Every preceding verb makes أنْ lightened.', 'سيكون can never have نصب in any context.', 'علم is not a heart verb.'], 'Identify the kind of knowledge expressed by علم.'),
    q('What is أنْ after نطمع in the given example?', ['مصدرية ناصبة; it governs يغفرَ.', 'Obligatorily lightened.', 'Either use, as after حسب.', 'Impossible after طمع.'], 'طمع lacks the technical heart-verb pattern.'),
    q('What changes from ليغفر / لأن يغفر to لئلّا?', ['أنْ must remain explicit.', 'أنْ is omitted more readily.', 'The verb loses نصب.', 'لئلا becomes an independent preposition.'], 'Expand لئلا to لأن لا.'),
    q('Why is أنْ understood before أو يرسل رسولا?', ['To coordinate a noun-equivalent with وحيا.', 'A conjunction requires written أنْ.', 'يرسل is مجزوم.', 'وحيا itself is an incomplete مصدر مؤول.'], 'Match the grammatical form on both sides of the conjunction.')],
};
export const quizzes = {
  '14/l4': [q('What is إذن used for?', ['Answer and consequence.', 'Purpose.', 'Emphatic negation.', 'Calling an addressee.']),
    q('What derivation does the minority nominal account propose?', ['إذ with an omitted condition and compensating tanwin.', 'Lightened إنّ.', 'Reinterpreted أين.', 'Reinterpreted كيف.']),
    q('Which conditions permit إذن to govern, with the stated exceptions?', ['Initial position, a future verb, and no intervening separator.', 'Negation, a noun, and repetition.', 'Coordination, a question, and doubling.', 'Final position after a past verb.']),
    q('What prevents government in أنت إذن تدخلُ الجنة?', ['إذن is no longer initial.', 'The verb cannot refer to the future.', 'A word separates إذن from its verb.', 'إذن becomes a noun.']),
    q('Why is إذن والله أكرمَك allowed?', ['An oath is an allowed separator.', 'An oath never counts as intervening words.', 'There is no separation condition.', 'إذن does not govern أكرمَ.']),
    q('How do Quranic spelling and usage relate?', ['إذًا has ألف spelling and a final n sound in connected speech; its Quranic uses are non-governing.', 'It is always spelled إذن in the muṣḥaf.', 'It never occurs in the Quran.', 'A doubled ن marks its government.'])],
  '14/l5': [q('Which four give a single verb جزم?', ['لم، لمّا، لام الأمر، لا الناهية.', 'إن، إذما، حتى، فاء.', 'أن، كي، لن، إذن.', 'واو، أو، بل، لكن.']),
    q('What does لم يلد ولم يولد illustrate about لم?', ['Past-reference negation with مضارع verb forms.', 'Changing the form to a past-tense verb.', 'Future reference alone.', 'Changing both verbs into imperatives.']),
    q('What would لمّا add to لم يحجّ زيد?', ['“Not yet”: Hajj remains anticipated.', 'A question.', 'Only present negation.', 'No change.']),
    q('In the interpretation taught, what does ولمّا يدخل الإيمان... anticipate?', ['Fuller faith may yet settle in their hearts.', 'Faith can never come.', 'The particle itself proves all faith is absent.', 'Negation of the present alone.']),
    q('What can لام الأمر express in فليعمل?', ['A command about someone absent.', 'Negation alone.', 'A question.', 'رفع instead of جزم.']),
    q('How do فليعمل and ولا يشرك complement each other?', ['What to do and what to avoid.', 'Two unrelated prohibitions.', 'One positive command repeated.', 'Only a condition and answer.'])],
  '14/l6': [q('What are تجتنبوا and نكفّرْ in إن تجتنبوا... نكفّرْ...?', null),
    q('What is implied in تعالوا أتلُ...?', ['A conditional إنْ construction after the command.', 'Negative لم.', 'Prohibitive لا.', 'Command لام.']),
    q('What accompanies the heavy نون in إمّا ينزغنّك?', ['Emphatic ما added to conditional إنْ.', 'A past-tense form.', 'A necessarily مرفوع verb.', 'An interrogative clause.']),
    q('What does تعدّوا portray in وإن تعدّوا نعمة الله...?', ['A gradual, ongoing process.', 'A finished one-off tally.', 'Only one bundled lapse.', 'An inherently impossible event.']),
    q('How does the conditional إن كان للرحمن ولد contrast with usual إذا?', ['An impossible supposition versus an expected occurrence.', 'They always mean exactly the same.', 'إن is certain and إذا impossible.', 'Neither relates to expectation.']),
    q('Why does فلا كاشف له إلا هو need the linking فاء?', ['It is a nominal answer occupying محل جزم.', 'The condition here is a past verb.', 'A nominal clause can never be an answer.', 'Every answer always needs فاء.'])],
  '14/l2': [q('Which are the five contexts, with their stated conditions?', ['حتى، لام الجحود، qualifying أو، واو المعية، causal فاء.', 'Every preposition.', 'Only heart verbs.', 'Only prepositional لام.']),
    q('After حتى, تنفقوا is future at speaking time. Which case is required?', ['نصب.', 'Either نصب or رفع.', 'No government is possible.', 'رفع.']),
    q('أو means “until” in أو أدركَ المنى. What is أدركَ?', ['منصوب through implied أنْ.', 'مرفوع through plain coordination.', 'مجزوم through a condition.', 'مبني على السكون.']),
    q('What gives ويعلمَ الصابرين نصب?', ['واو المعية after negation, with implied أنْ.', 'Ordinary coordination alone.', 'واو الحال.', 'واو القسم.']),
    q('What type of request precedes فيضاعفه in من ذا الذي يقرض الله...?', null),
    q('Can مُره يحفرَها establish a general omission rule?', ['No; this نصب with omitted أنْ is سماعي.', 'Yes, after every imperative.', 'Yes, in all poetry.', 'No; يحفرَ is neither منصوب nor relevant.'])],
  '14/l3': [q('What meaning characterizes the كي construction?', null),
    q('Must the لام before مصدرية كي be written?', ['No; it may be understood.', 'Yes, always.', 'No; لام can never accompany كي.', 'Yes, but only in poetry.']),
    q('How do the two analyses of كي differ?', ['لام is supplied with مصدرية كي, not prepositional كي.', 'Only by past versus present tense.', 'كي receives tanwin.', 'Only by statement versus request.']),
    q('On the emphatic analysis, why use لن in فلن أكلم اليوم إنسيا?', ['To give a firmer negation than plain لا.', 'لا cannot precede المضارع.', 'Only the spelling differs.', 'لن refers to the past.']),
    q('What supports “never” in لن يخلقوا ذبابا?', ['The context denies the idols any power to create life.', 'لن always means forever by itself.', 'The noun ذبابا forces permanence grammatically.', 'Every present-tense verb means forever.']),
    q('In the emphatic account used here, is permanence automatic?', ['No; تأكيد is distinguished from contextual تأبيد.', 'Yes; emphasis is only contextual.', 'لن does not negate at all.', 'Both are equally automatic.'])],
  '14/l1': [q('What does مصدرية أنْ do?', ['Turns the verbal clause into a noun-equivalent.', 'Makes the verb imperative.', 'Negates the verb.', 'Makes the verb مبني.']),
    q('What is أنْ after علم in أن سيكون?', ['Lightened أنّ, with an omitted اسم; no عمل on the verb.', 'مصدرية giving سيكون نصب.', 'An added particle with no function.', 'A conditional particle giving جزم.']),
    q('Why can يتركَ have نصب after أيحسب?', ['Supposition permits either use of أنْ.', 'حسب is not a heart verb.', 'يترك always has نصب.', 'حسب forces only the lightened use.']),
    q('What is أنْ after نطمع here?', ['مصدرية ناصبة.', 'Lightened, as after علم.', 'Either, as after حسب.', 'A preposition.']),
    q('What changes with لئلّا?', ['أنْ must remain explicit.', 'The verb loses نصب.', 'It becomes bare non-governing negation.', 'لام itself is omitted.']),
    q('What licenses implied أنْ before أو يرسل?', ['Matching the coordinated verb to the noun وحيا.', 'يرسل is already a plain noun.', 'Every أو must always imply أنْ.', 'حجاب requires a second مصدر مؤول.'])],
};
