import { card as c, rows as r, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '23/l3': plan(115, 'Calling for Help and in Amazement', [
    [c('Calling specifically for help', 0, 1, 2), c('The three roles in الاستغاثة', 3, 4)],
    [c('Mark the person asked for help', 0, 3), c('An ألف can replace the لام', 1, 2)],
    [c('Coordinating two helpers', 0, 1, 2), c('Compare the repeated يا', 3)],
    [c('Mark the beneficiary', 0, 1), c('A helper and a beneficiary', 2, 3), c('Read all three roles', 4)],
    [c('A call expressing amazement', 0, 1, 2), c('Two accounts of the amazed call', 3, 4, 5)],
  ], [
    ['يا', 'The calling particle used for الاستغاثة.'],
    ['المستغاث', 'The helper normally has لَ; an ending ألف can replace it.'],
    ['المستغاث له', 'The beneficiary normally has لِ before an overt noun.'],
    ['تعجب', 'Similar forms express amazement; context and construction establish the reading.'],
  ], { copy:{
    '0:0':'الاستغاثة and نداء التعجب adapt calling to different purposes.',
    '0:2':'الاستغاثة asks for aid, whether for oneself or another. Ordinary يا عبد الحميد may simply summon someone; the special construction identifies the call as a request for help.',
    '0:4':'حرف الاستغاثة is يا alone. المستغاث is the person asked for help. المستغاث له is the person or cause for which help is sought.',
    '1:1':'An ending ألف can replace the helper’s لام: يا زيدا. At a pause, هاء السكت may follow: يا زيداهْ. The هاء is pronounced without a following vowel.',
    '1:3':'In the لام form, the helper is outwardly مجرور by لام. The account taught assigns the vocative position نصب. Do not confuse the preposition’s فتحة with the noun’s case ending.',
    '2:0':'Two helpers can be coordinated.',
    '2:2':'Repeat يا and the second helper also takes لَ. Without a new يا, its لام returns to ordinary kasrah. Context and coordination identify its helper role. Kasrah cannot distinguish it from the beneficiary’s لام, which also has kasrah.',
    '3:1':'Before an overt beneficiary noun, لام has kasrah. With pronouns its usual forms apply, including open لَ in لنا and لكم, but kasrah in لي. The source’s “always kasrah” needs this qualification.',
    '3:3':'يا لله للمسلمين asks Allah to help the Muslims. يا لزيد لخالد asks Zayd to help Khalid. The first noun is the helper; the second is the beneficiary.',
    '4:1':'نداء التعجب calls out something as an object of wonder. Its purpose is amazement, not a real appeal for rescue.',
    '4:3':'One account places المتعجب منه in the helper’s slot with لَ or an ending ألف. Another uses the beneficiary’s لِ, with the helper understood. These are two analyses, not an unexplained exchange of identical roles.',
    '4:5':'The three Quran examples express wonder at the Quran. They need not name a real person receiving help; their emotional purpose explains the transferred construction.',
  }, boxCopy:{
    '0:1':['الاستغاثة: نداء لطلب العون.'],'0:3':['حرف الاستغاثة، والمستغاث، والمستغاث له.'],
    '1:2':['يا لَلَّهِ','يا زَيْدا، يا زَيْداهْ'],
    '2:1':['مع تكرار يا: لَ؛ وبدونه: لِ.'],
    '2:3':['يا لَلْأَميرِ وَيا لَلْمُسْلِمينَ لِلْمَظْلومينَ','يا لَلْأَميرِ وَلِلْمُسْلِمينَ لِلْمَظْلومينَ'],
    '3:0':['لام المستغاث له مكسورة مع الاسم الظاهر.'],
    '3:2':['يا لَلَّهِ لِلْمُسْلِمينَ','يا لَزَيْدٍ لِخالِدٍ'],
    '4:2':['نداء التعجب يستعمل صور الاستغاثة.'],
    '4:4':['يا لَلْقُرْآنِ، يا قُرْآناهْ','يا لِلْقُرْآنِ'],
  }, visuals:{'2:0':v('The second helper’s لام',['ويا لَـ','Repeat يا: fatḥah'],['ولِـ','No new يا: kasrah'])}, analysisLabels:{'حرف نداء':'حرف استفهام'} }),
  '23/l4': plan(116, 'Calling in Grief', [
    [c('Give voice to grief', 0, 1, 2), c('وا or an unambiguous يا', 3, 4), c('A father or a teacher mourned', 5, 6)],
    [c('The ordinary case distinction', 0, 1), c('A name and an إضافة vocative', 2, 3, 4)],
    [c('Lengthen the cry at a pause', 0, 1, 2), c('With ألف, or ألف and هاء', 3, 4)],
    [c('One calling structure, four purposes', 0, 1), c('Attention and help', p(2,0)), c('Amazement and grief', p(2,1))],
  ], [
    ['الندبة', 'A calling construction expressing grief or pain.'],
    ['وا / يا', 'وا marks lament; يا requires an unambiguous context.'],
    ['Case', 'Eligible names follow the ordinary vocative case distinction.'],
    ['Ending', 'Optional ألف lengthens the cry; هاء السكت follows at a pause.'],
  ], { copy:{
    '0:0':'الندبة completes this section on calling.',
    '0:2':'It expresses sorrow by calling to someone mourned, or crying out over pain or loss. It differs in purpose from seeking help or expressing wonder.',
    '0:4':'وا is the dedicated lament particle. يا can also introduce lament إذا أمن اللبس بالمنادى المحض: when context rules out confusion with an ordinary call.',
    '0:6':'وا أبتاهْ, “Oh, my father!”, voices grief for a father who has died or is gravely unwell. وا marks lament. يا أستاذُ after a teacher’s death depends on that context to be understood as mourning.',
    '1:1':'For eligible vocatives, the ordinary case distinction applies: a simple proper name is مبني in نصب position; a مضاف shows نصب. Eligibility is narrower than ordinary calling: the mourned referent must be known, not an unspecified نكرة غير مقصودة as the source suggests.',
    '1:3':'وا زيدُ has the same case account as يا زيدُ: مبني على الضم في محل نصب.',
    '1:4':'In وا عبدَ اللهِ, عبد shows نصب because it is مضاف, just as it does after يا.',
    '2:0':'Two optional ending letters can round off the cry.',
    '2:2':'ألف الندبة lengthens the ending. هاء السكت may follow it عند الوقف, when pausing. “Pause هاء” means a pronounced h without a following vowel, not an unpronounced letter.',
    '2:4':'وا زيدا adds only ألف. وارأساهْ, “Oh, my head!”, and واويلاهْ, “Oh, my ruin!”, add ألف then هاء. The Prophet ﷺ used وارأساه in the final-illness report discussed earlier.',
    '3:1':'All four forms share حرف نداء + منادى, explained through an understood أدعو. Their aims differ, and their surface forms can differ too, including لام and special endings.',
  }, copyParts:{'3:2':[
    'Ordinary نداء draws attention using ordinary calling particles. وا belongs specifically to lament. الاستغاثة uses يا and marks the helper with لَ or an ending ألف, and an overt beneficiary noun with لِ. Aid can be sought for oneself or someone else.',
    'نداء التعجب adapts the aid-calling forms to express wonder. الندبة uses وا, or unambiguous يا, to express grief; it can add ألف then pause هاء. Purpose helps identify these constructions alongside their actual grammatical form.',
  ]}, boxCopy:{'0:5':['وا أَبَتاهْ'],'1:0':['للمندوب المؤهل حكم المنادى في الإعراب.'],'2:3':['وا زَيْدا','وارَأْساهْ، واوَيْلاهْ'],'3:0':['نداء عادي، واستغاثة، وتعجب، وندبة.']}, visuals:{'3:1':v('Calling for attention or aid',['نداء','Draw someone’s attention'],['استغاثة','Ask for help']),'3:2':v('Calling with emotion',['تعجب','Express wonder'],['ندبة','Express grief'])}, analysisLabels:{'حرف نداء':'حرف استفهام'}, analysisItemLabels:{'bank-14':{'منادى مضاف لياء المتكلم (مع ألف الندبة)':'منادى، مع ألف الندبة وهاء السكت؛ التاء عوض الياء','منادى مضاف لياء المتكلم (مع ألف الندبة وهاء السكت)':'منادى مضاف مع ألف الاستغاثة'}}, analysisText:{'bank-14':{'وا أَبَتاهُ':'وا أَبَتاهْ','أَبَتاهُ':'أَبَتاهْ'}} }),
  '23/l1': plan(113, 'The Parts of a Call', [
    [c('A call with an understood verb', 0, 1, 2)],
    [c('Three grammatical parts', 0, 1, 2), c('Two spoken words', 3, 4)],
    [c('Particles for calling', 0, r(1,0,1)), c('A cry of grief', r(1,2), 2)],
    [c('When يا is understood', 0, 1, 2), c('Addressing a family', 3, 4), c('Addressing Joseph', 5, 6)],
    [c('Keep يا in the ordinary patterns', 0, 1, 2, 3)],
  ], [
    ['النداء', 'A particle stands in for an understood أدعو.'],
    ['Three parts', 'The omitted verb, calling particle and person or thing called.'],
    ['Particles', 'يا is general; وا specifically introduces lament.'],
    ['Omission', 'Context licenses familiar مضاف and proper-name cases; restrictions and exceptions matter.'],
  ], { copy:{
    '0:0':'The fifth and final omitted-object-governor position in this source is النداء, calling out.',
    '0:2':'يا زيدُ means “O Zayd!” Its grammatical explanation supplies أدعو زيدا, “I call Zayd.” The verb is understood rather than spoken.',
    '1:0':'The construction has three grammatical parts, although only two need be spoken.',
    '1:2':'فعل النداء المحذوف is أدعو or a similar verb. حرف النداء, such as يا, stands in its place. المنادى is the person or thing called, functioning as the understood verb’s object.',
    '1:4':'يا is the calling particle; زيد is the person called. أدعو is the third, unspoken part.',
    '2:0':'This source lists seven particles. يا is the common general particle for both near and far addressees. Other inventories differ; the near/far grouping describes ordinary use, with rhetorical extensions.',
    '2:2':'وا introduces ندبة, a cry of grief rather than a literal summons. Other calling particles can also have rhetorical uses. وارأساهْ, “Oh, my head!”, expresses pain. In the final-illness report, Aisha says it and the Prophet ﷺ replies بل أنا وارأساه.',
    '3:0':'يا can be omitted when the context still makes the address clear.',
    '3:2':'Two common cases are a مضاف and a proper name. These are the source’s focus, not an exhaustive account of all attested omissions.',
    '3:4':'“Work, O family of David, in gratitude.” آل is مضاف to داود. Context identifies the address; إضافة alone does not prove an omitted يا. The exercise adopts مفعول لأجله for شكرا; other analyses are also recorded.',
    '3:6':'“Joseph, turn away from this.” يوسف is a proper name addressed directly. The sentence’s context supplies the missing يا; a name in isolation need not be a call.',
    '4:0':'Use يا in these ordinary calling patterns.',
    '4:2':'The source prohibits omission before الله and نكرة مقصودة. The latter is a specific person addressed by a common noun, whether their name is known or unknown. Rare omissions with نكرة مقصودة are admitted by other grammarians.',
    '4:3':'Say يا الله اغفر لي and يا رجلُ in the ordinary patterns, rather than bare الله اغفر لي or رجلُ. The special compensating form اللهم follows in the next lesson.',
  }, boxCopy:{'0:1':['النداء بحرف يقوم مقام أدعو.'],'1:1':['فعل محذوف، وحرف نداء، ومنادى.'],'3:1':['قد يحذف حرف النداء مع المضاف والعلم.'],'4:1':['الأصل إبقاء يا مع الله والنكرة المقصودة.']}, tableCopy:{'2:1':{
    0:['القريب','أَ، أيْ','أَعَبْدَ اللهِ'],1:['البعيد','يا، آ، أيا، هيا','يا عَبْدَ اللهِ'],2:['الندبة','وا','وا رَأْساهْ'],
  }}, analysisPrompt:'Use the lesson’s displayed analysis.', analysisItemLabels:{'bank-17':{'مضاف':'نعت'},'bank-18':{'مضاف إلى اسم آخر':'نعت'}} }),
  '23/l2': plan(114, 'The Case of the Person Called', [
    [c('An object, visibly or in position', 0, 1, 2)],
    [c('A مضاف shows نصب', 0, r(1,0)), c('A complement without إضافة', r(1,1), p(2,0)), c('No particular person intended', r(1,2), p(2,1))],
    [c('Built on its رفع form', 0, 1), c('The position remains نصب', 2, 3)],
    [c('Omit or retain a quiet ياء', 0, r(1,0,1)), c('Open ياء or replace it with ألف', r(1,2,3), 2)],
    [c('Shorten a name when calling', 0, 1), c('Which names allow ترخيم?', 2), c('Two vowels after shortening', 3, 4)],
    [c('The special form اللهم', 0, 1, 2, 3), c('Two idiomatic uses', 4)],
  ], [
    ['منصوب', 'مضاف, شبيه بالمضاف and نكرة غير مقصودة show نصب.'],
    ['مبني', 'A simple proper name or intended common noun is built on its رفع form, in نصب position.'],
    ['ياء المتكلم', 'The lesson compares four treatments.'],
    ['ترخيم / اللهم', 'Shortening has conditions; اللهم compensates for يا with ميم.'],
  ], { copy:{
    '0:0':'المنادى is the object of understood أدعو in the account taught.',
    '0:2':'Its case is نصب, either on the word itself, لفظا, or in its grammatical position, محلا, when the word is مبني.',
    '1:0':'Three categories show نصب on the word itself. In يا عبدَ اللهِ, عبد is the first member of إضافة.',
    '2:0':'مفرد here means neither مضاف nor شبيه بالمضاف. It does not mean numerically singular.',
    '2:1':'A simple proper name or نكرة مقصودة is مبني على ما يرفع به: built on its normal رفع marker, while occupying a نصب position.',
    '2:3':'زيدُ is built on ضمة. The intended dual in يا رجلانِ is built on ألف; يا مسلمونَ is built on واو. All remain في محل نصب.',
    '3:0':'With a vocative added to “my” ياء, this lesson compares four treatments. The wider grammatical account records additional forms.',
    '3:2':'Grief expressions include يا حسرتا and يا ويلتا with ألف replacing ياء. Compare يا حسرتي and يا ويلتي, which retain ياء. All four are emotional calls; only the first two illustrate the ألف replacement.',
    '4:1':'الترخيم removes the final letter or letters to ease the call. فاطمة becomes يا فاطمَ by dropping تاء مربوطة.',
    '4:2':'Names ending in تاء مربوطة allow forms such as عائشة → يا عائشُ. Without that ending, a proper name normally needs more than three letters: جعفر → يا جعفُ, and زينب → يا زينَ or يا زينُ. زينب has four letters; its ب is not removed to count roots. زيد fails the length condition; عبد الله is an excluded إضافة compound.',
    '4:4':'One account retains the remaining final letter’s own vowel, as رِ in يا حارِ from حارث. The source prefers this treatment. The other treats the shortened name as complete and gives it ضمة: يا حارُ. It is not the dropped letter’s vowel that is retained.',
    '5:1':'اللهم is the special calling form used to address Allah.',
    '5:3':'In the compensatory account, the final doubled ميم replaces يا from يا الله. This is a special substitution, not unrestricted omission before الله.',
    '5:4':'اللهم إلا أن يكون كذا introduces a rare exception: “unless, exceptionally, that is so.” اللهم نعم reinforces certainty: “yes, absolutely.” Further branches of calling are الاستغاثة, نداء التعجب and الندبة, studied next.',
  }, copyParts:{'1:2':[
    'غافرا in يا غافرا ذنوبنا, “O forgiver of our sins”, governs ذنوبنا as its object. A completing expression makes it شبيه بالمضاف, without turning that object into a genitive مضاف إليه.',
    'يا غافلا والموت يطلبه addresses any heedless person, “O heedless one, while death pursues him.” It is نكرة غير مقصودة. Contrast يا رجلُ directed to a particular man.',
  ]}, boxCopy:{'0:1':['المنادى منصوب لفظًا أو محلًّا.'],'4:3':['حارِث: يا حارِ أو يا حارُ.']}, tableCopy:{'1:1':{
    0:['مضاف','First member of إضافة','يا عَبْدَ اللهِ'],1:['شبيه بالمضاف','Completed by a related expression','يا غافِرًا ذُنوبَنا'],2:['غير مقصودة','No particular person intended','يا غافِلًا وَالْمَوْتُ يَطْلُبُهُ'],
  },'3:1':{0:['حذف الياء','Keep the kasrah','يا عِبادِ فَاتَّقونِ'],1:['ياء ساكنة','Retain ياء with سكون; Nafi’s reading','يا عِبادِيْ لا خَوْفٌ عَلَيْكُمُ'],2:['ياء مفتوحة','Retain ياء with فتحة','يا عِبادِيَ الَّذينَ أَسْرَفوا'],3:['قلبها ألفًا','Change kasrah to fatḥah and ياء to ألف','يا حَسْرَتَى']}}, visuals:{'2:0':v('Form and grammatical position',['مبني','Built on its رفع marker'],['محل نصب','The object position remains'])}, analysisItemLabels:{'bank-19':{'مفعول به':'مفعول مطلق'}} }),
};

export const checks = {
  '23/l3':[
    q('Which particle is used for الاستغاثة?', ['يا alone','يا and آ','يا, وا and آ','All seven particles'], 'The aid-calling form restricts the particle.'),
    q('What does the ending ألف replace in يا زيدا?', ['The helper’s لام','The beneficiary’s لام','يا itself','نون التوكيد'], 'Compare يا لزيد.'),
    q('A second helper follows و without a new يا. Its لام takes…', ['Kasrah','Fatḥah','No sound; it disappears','Hamzah'], 'The special fatḥah accompanies a repeated يا.'),
    q('In يا لَلَّهِ لِلْمُسْلِمينَ, whose لام has kasrah?', ['المسلمين, the beneficiary','الله, the helper','Both have kasrah','Neither has a vowel'], 'Separate who is asked from who needs help.'),
    q('How is يا لِلْقُرْآنِ explained as amazement?', ['The object of wonder fills the beneficiary slot, with a helper understood','القرآن must always be a beneficiary','Kasrah occurs only in amazed calls','A helper can never appear in amazed calls'], 'Identify which of the two taught accounts uses لِ.'),
  ],
  '23/l4':[
    q('Why does وا mark lament more clearly than يا?', ['It is the dedicated lament particle','It is easier to pronounce','يا can never precede a proper name','وا always takes tanwin'], 'يا also introduces an ordinary call.'),
    q('Why is عبدَ منصوب in وا عبدَ اللهِ?', ['It is مضاف, using the ordinary vocative case distinction','Lament changes the case of every مضاف','All lamented names are مبني','وا makes every name مرفوع'], 'Compare يا عبدَ اللهِ.'),
    q('What follows رأس in وارأساهْ?', ['ألف الندبة, then هاء السكت','هاء السكت, then ألف الندبة','Tanwin, then ألف','Only ألف'], 'Read the two ending letters in order.'),
    q('Which structure underlies the four kinds of calling?', ['حرف نداء + منادى, with أدعو understood','Past verb + subject','Only مبتدأ + خبر','Only preposition + genitive'], 'The communicative purpose changes within a calling construction.'),
  ],
  '23/l1':[
    q('Which verb is understood in يا زيدُ?', ['أدعو','يا','زيد','No verb is understood'], 'The particle stands in for the calling verb.'),
    q('Which part of يا زيدُ is unspoken?', ['فعل النداء المحذوف','حرف النداء','المنادى','حرف الجر'], 'Two words express a construction with three grammatical parts.'),
    q('Which particle is dedicated to lament?', ['وا','يا','أَ','أيْ'], 'Recall وارأساهْ.'),
    q('Why is آل داود an eligible vocative without يا here?', ['It is مضاف','It is a simple proper name','It is نكرة مقصودة','It is لفظ الجلالة'], 'Identify the relation between آل and داود.'),
    q('In the source’s ordinary rule, may رجلُ replace يا رجلُ?', ['No; keep يا before نكرة مقصودة','No; رجل is لفظ الجلالة','Yes; any indefinite allows omission','Yes; omission is always required'], 'Use the ordinary rule, allowing for the rare usages discussed.'),
  ],
  '23/l2':[
    q('What is the case of المنادى, visibly or in position?', ['منصوب','مرفوع','مجرور','مجزوم'], 'It is the understood calling verb’s object.'),
    q('Why does يا غافرا ذنوبنا use غافرا with نصب?', ['شبيه بالمضاف; ذنوبنا completes its meaning as object','مضاف; ذنوبنا is its genitive complement','نكرة غير مقصودة with no complement','It is the special name الله'], 'A completing expression need not be إضافة.'),
    q('What is رجلُ in يا رجلُ, addressing a specific man?', ['مبني على الضم في محل نصب','منصوب لفظا لأنه شبيه بالمضاف','منصوب لفظا لأنه مضاف','مرفوع لأنه نكرة'], 'Separate its fixed form from its grammatical position.'),
    q('Which ياء treatment appears in يا عبادِ فاتقونِ?', ['Omit ياء and retain kasrah','Retain ياء with سكون','Retain ياء with فتحة','Replace ياء with ألف'], 'Compare the full form عبادي.'),
    q('Which statement about ترخيم is correct?', ['زينب has four letters and allows shortening; عبد الله is an إضافة compound','زينب has only three letters','Every feminine name is excluded','عبد الله is excluded because it ends in تاء مربوطة'], 'Count written letters, not a proposed root after discarding ب.'),
    q('What compensates for يا in اللهم?', ['A doubled final ميم','A new أيا','Tanwin','ألف الاستغاثة'], 'Compare يا الله with اللهم.'),
  ],
};

export const quizzes = {
  '23/l3':[
    q('Which particle introduces الاستغاثة?', ['يا','وا','أَ','أيْ']),
    q('Which role identifies the beneficiary of help?', ['المستغاث له','المستغاث','حرف الاستغاثة','لام الاستغاثة']),
    q('What replaces the helper’s لام in يا زيدا?', ['An ending ألف','An ending kasrah','Tanwin','A second يا']),
    q('With overt nouns after يا, how do the two لام forms normally differ?', ['Helper: لَ; beneficiary: لِ','Helper: لِ; beneficiary: لَ','Both have the same vowel','Neither has a vowel']),
    q('Without repeated يا, what happens to a coordinated helper’s لام?', ['It takes ordinary kasrah','It retains special fatḥah','It takes سكون','It takes ضمة']),
    q('In the helper-slot account of an amazed call, what occupies that slot?', ['المتعجب منه','المستغاث له','حرف الاستغاثة','المنادى المضاف']),
  ],
  '23/l4':[
    q('Which is the dedicated lament particle?', ['وا','يا','آ','أيا']),
    q('When can يا introduce lament?', ['When context rules out an ordinary call','Only before a feminine name','Only before a مضاف','Never']),
    q('What is زيدُ in وا زيدُ?', ['مبني على الضم في محل نصب','منصوب لفظا','مرفوع لفظا','مجرور محلا']),
    q('Which optional endings occur in this order?', ['ألف الندبة ثم هاء السكت','هاء السكت ثم ألف الندبة','Tanwin then ألف','ياء then هاء']),
    q('When is هاء السكت added after ألف الندبة?', ['At a pause','Only in continuous speech','At the word’s beginning','Only after a preposition']),
    q('What structure do the four kinds of calling share?', ['حرف نداء + منادى, with أدعو understood','Verb + subject + object, with no omission','Only مبتدأ + خبر, with no omission','Only a prepositional phrase']),
  ],
  '23/l1':[
    q('What is the grammatical explanation of يا زيدُ?', ['أدعو زيدا','أنادي إلى زيد','أطلب زيدا','أسأل زيدا']),
    q('Which is not one of النداء’s three parts?', ['حرف الجر','فعل النداء المحذوف','حرف النداء','المنادى']),
    q('Which particle is grouped with أيْ for near address?', ['أَ','يا','وا','هيا']),
    q('How does وا function in ندبة?', ['It voices grief through a figurative call','It only addresses someone nearby','It cannot begin an utterance','It requires tanwin on the vocative']),
    q('Why may يوسف appear without يا in يوسف أعرض عن هذا?', ['It is a proper name addressed in context','It is مضاف','It is نكرة مقصودة','It is لفظ الجلالة']),
    q('Where does the source’s ordinary rule retain يا?', ['Before الله and نكرة مقصودة','Before every مضاف and proper name','Before every مبني vocative','Before every masculine vocative']),
  ],
  '23/l2':[
    q('What is المنادى’s case, visibly or in position?', ['منصوب','مرفوع','مجرور','مجزوم']),
    q('Why is عبدَ منصوب in يا عبدَ اللهِ?', ['مضاف','شبيه بالمضاف','نكرة غير مقصودة','علم مفرد']),
    q('What is زيدُ in يا زيدُ?', ['مبني على الضم في محل نصب','منصوب لفظا','مرفوع محلا','مجرور لفظا']),
    q('Nafi’s يا عباديْ لا خوف عليكم shows which treatment?', ['ياء retained with سكون','ياء omitted','ياء retained with فتحة','ياء replaced by ألف']),
    q('Why does زيد fail the ordinary ترخيم length condition?', ['It has only three letters','It ends in تاء مربوطة','It is a compound','All masculine names are excluded']),
    q('What does اللهم نعم reinforce?', ['Certainty: yes, absolutely','Doubt without commitment','A rare exception','A polite refusal']),
  ],
};
