import { card as c, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '24/l1': plan(117, 'The Subject and Word Order', [
    [c('What receives the active predication?', 0, 1, 2), c('A verb and a governing adjective', 3, 4)],
    [c('A genitive form and a subject role', 0, 1, 2), c('Compare the three constructions', 3, 4), c('An extra preposition before the subject', 5)],
    [c('The default order', 0, 1, 2, 3), c('A noun before its verb', 4, 5, 6)],
    [c('When the subject must come first', 0, 1, 2), c('Attachment and ambiguity', 3, 4)],
    [c('Clues permit a later subject', 0, 1, 2, 3), c('A parallel issue with كان', 4, 5, 6, 7)],
    [c('A permitted object-first order', 0, 1, 2, 3, 4)],
    [c('When the object must come first', 0, 1, 2), c('Three reasons in examples', 3, 4), c('Keep the object pronoun attached', 5)],
  ], [
    ['فاعل', 'A complete active verb or its equivalent predicates meaning of it.'],
    ['Default order', 'Verb, subject, then object. A fronted noun has competing analyses.'],
    ['Required subject first', 'Keep an attached pronoun attached; avoid unresolved ambiguity.'],
    ['Required object first', 'A returning pronoun, object attachment or interrogative precedence can require it.'],
  ], { copy:{
    '0:0':'The source now opens المقصد الثاني: المعمول وغير المعمول. Its survey of governed nouns starts with الفاعل.',
    '0:2':'The predicate must be complete, تام, and active, معلوم, or carry that verbal meaning. ناقص كان has an اسم; a passive verb has a نائب فاعل. “Active” describes the form, not whether the doer is actually known to the listener.',
    '0:4':'In فقست قلوبهم, “their hearts hardened”, قلوب is subject of the active verb قست. In والقاسية قلوبهم, القاسية carries the verbal meaning as اسم فاعل and likewise raises قلوب.',
    '1:0':'The ordinary subject has رفع. Two constructions put the relevant noun in a genitive form.',
    '1:2':'A مصدر may be added to its semantic subject, making that noun مضاف إليه. An extra من or باء may precede a grammatical subject. The source groups both as جر لفظا with رفع محلا; distinguish their actual constructions.',
    '1:4':'In كذكركم آباءكم, كم is مضاف إليه in a جر position and denotes the rememberers, like أن تذكروا; the source also calls this semantic role رفع محلا. With extra من in ما جاءنا من بشير and باء in وكفى بالله وكيلا, the subject is explicitly مجرور لفظا مرفوع محلا.',
    '2:1':'The default verbal order is verb, subject, then direct object.',
    '2:3':'“Solomon inherited from David.” سليمانُ is subject after ورث; داودَ is object.',
    '2:5':'In زيد قام, the Basran account makes زيد مبتدأ. قام contains a hidden هو as subject; the verbal clause is خبر.',
    '2:6':'The Kufan account permits زيد as a fronted فاعل, called مفصول in the source. The analyses preserve the meaning while assigning different structures.',
    '3:0':'Two taught conditions require subject-before-object order within the construction.',
    '3:2':'An obligatorily attached subject pronoun stays with its verb. Where neither visible case, agreement nor meaning distinguishes two nouns, the first must be interpreted as subject under the ordinary rule.',
    '3:4':'ضربت زيدا cannot simply detach تُ as ضرب زيدا أنا. In زار موسى عيسى, hidden case endings make order decisive: Moses visits Jesus. زارت هذه تلك has the same issue, because both demonstratives are feminine. These rules concern order within the verbal construction, not every possible fronting of an entire object phrase.',
    '4:1':'A clear clue can allow the object before the subject.',
    '4:3':'أكل الكمثرى موسى means “Moses ate the pear.” Ordinary meaning identifies the eater; الكمثرى is a pear, not guava. In نصرت موسى سلمى, feminine نصرت identifies سلمى as the helper despite the later position. These are semantic and spoken-form clues respectively.',
    '4:5':'The same ambiguity concern extends to اسم كان and its خبر.',
    '4:7':'In فما زالت تلك دعواهم, “that remained their cry”, the source makes تلك the اسم and دعواهم the خبر because case endings do not distinguish them. Some commentators permit the reverse analysis; the lesson adopts the source’s ordering account.',
    '5:0':'Object-first order can be optional.',
    '5:2':'جوازا permits a rhetorical choice.',
    '5:4':'آل فرعون is object; النذر is subject. Case distinguishes them, so this order is not required. Fronting serves discourse and the verse ending. Quranic endings are فواصل; the source’s وزن should not imply poetic metre.',
    '6:0':'Three source reasons can require the object to precede the subject.',
    '6:2':'A pronoun inside the subject may refer to the object; the object must then come first under the ordinary rule against a referent later both in wording and rank. An attached object pronoun must stay attached. An interrogative object has precedence in its own clause.',
    '6:4':'ابتلى إبراهيمَ ربُّه puts إبراهيم before the subject’s returning ـه. لعنهم الله keeps object هم attached, rather than لعن الله إياهم in this ordinary pattern. فأي آيات الله تنكرون fronts interrogative أي. The subject of تنكرون is visible واو الجماعة, not a hidden أنتم.',
  }, boxCopy:{'0:1':['الفاعل: ما أسند إليه فعل تام معلوم، أو ما بمعناه.'],'1:1':['إضافة المصدر إلى فاعله؛ أو حرف جر زائد.'],'2:4':['زيد قام: زيد مبتدأ عند البصريين، أو فاعل مقدم عند الكوفيين.'],'3:1':['لزوم اتصال الضمير؛ أو خشية الالتباس.'],'4:0':['قرينة تزيل الالتباس تجيز التقديم.'],'5:1':['قد يتقدم المفعول جوازًا للبلاغة.'],'6:1':['مرجع الضمير، واتصال المفعول، وصدارة الاستفهام.']}, analysisItemLabels:{'bank-21':{'فاعل مرفوع':'نائب فاعل مرفوع'}} }),
  '24/l2': plan(118, 'Passive and Nominal Subjects', [
    [c('The passive counterpart', 0, 1, 2), c('A passive verb and participle', 3, 4)],
    [c('A prepositional phrase as deputy subject', 0, 1), c('The passive form جيء', 2, 3)],
    [c('Two kinds of مبتدأ', 0, 1, 2), c('A topic and a governing adjective', 3, 4), c('A raised noun suffices', 5, 6)],
    [c('Emphasis with لام', 0, 1, 2, 3), c('Emphasis beyond nominal subjects', 4, 5)],
    [c('An informative indefinite subject', 0, 1, 2), c('Four kinds of specification', 3, 4), c('Generality after negation or a question', 5, 6, 7)],
    [c('Three further licenses', 0, 1, 2), c('Four informative contexts', 3, 4, 5), c('An understood مبتدأ', 6, 7, 8, 9)],
  ], [
    ['نائب الفاعل', 'Raised with a complete passive verb or its equivalent.'],
    ['مبتدأ', 'An ordinary topic, or an adjective completed by what it raises.'],
    ['نكرة', 'Allowed when informative, with the specific licenses taught.'],
    ['حذف', 'Context can recover an omitted مبتدأ, often after response فاء or speech.'],
  ], { copy:{
    '0:0':'نائب الفاعل is the second of the source’s eight مرفوعات.',
    '0:2':'A complete passive verb or its equivalent attributes meaning to the deputy subject. مجهول here names passive construction; the actual agent need not be unknown. Compare the active subject’s definition: both have رفع, but the verbal voice differs.',
    '0:4':'In وجمع الشمس والقمر, الشمس is deputy subject and القمر coordinated with it. In ذلك يوم مجموع له الناس, passive participle مجموع raises الناس as deputy subject. Compare the active participle القاسية قلوبهم from the previous lesson.',
    '1:1':'When the active construction reaches its complement through a preposition and no direct object is available for promotion, the prepositional phrase can supply نائب الفاعل in the account taught. Other accounts locate the deputy role in the noun or an understood مصدر.',
    '1:3':'“On that day Hell is brought forth.” The source’s active explanation is جاءت الملائكة بجهنم. Bringing something with جاء به uses باء; this does not mean جاء never has a direct object in other uses. بجهنم keeps an original preposition, unlike the extra باء studied with كفى.',
    '2:0':'المبتدأ is the third مرفوع category.',
    '2:2':'The familiar type is a noun freed from a governing لفظي element, with something predicated of it. The second is a governing adjective after negation or a question, completed by the overt noun or detached pronoun it raises.',
    '2:4':'محمد is topic in محمد رسول الله. In أراغب أنت عن آلهتي, راغب can govern أنت as its subject: “Are you turning away from my gods?” Here the raised expression is a detached pronoun, not an overt noun as the source definition narrowly states.',
    '2:6':'On one valid reading, راغب is مبتدأ and أنت its فاعل ساد مسد الخبر, completing the predication without a separate خبر. Another makes أنت مبتدأ مؤخرا and راغب خبرا مقدما. Both are legitimate for this example.',
    '3:1':'Emphatic لام may enter on a مبتدأ, or on a fronted predicate in the account taught.',
    '3:3':'ولعبد مؤمن خير من مشرك emphasizes subject عبد. لكاذب أنت emphasizes fronted predicate كاذب, with أنت as the later subject.',
    '3:5':'Compare مضارع لأقول الحق, fixed verb لبئس ما كانوا يعملون, and قد with a past verb: لقد جاءت رسل ربنا بالحق. The source groups these under emphatic لام. Standard accounts distinguish لام الابتداء from لام جواب القسم, especially لقد. An oath may be understood: والله لقد جاءت...',
    '4:1':'A مبتدأ is normally definite. An indefinite is allowed when the predication is informative. The source groups several licenses as specification, مخصوصة, or generality, عامة; the whole utterance must be useful.',
    '4:2':'Specification may use إضافة or description, expressed or understood.',
    '4:4':'خمس is specified by صلوات in expressed إضافة. كل implies كل أحد in the source’s account of understood إضافة. عبد is explicitly described by مؤمن. طائفة is understood as طائفة منهم in the source’s supplied-description account.',
    '4:5':'Negation or questioning can make a general indefinite informative.',
    '4:7':'ما أحد خير من أحد إلا بالتقوى uses أحد generally under negation. Read خيرٌ with non-operating ما for this مبتدأ example. The source’s خيرًا instead suggests a different, operating ما analysis. In أإله مع الله, the question licenses indefinite إله.',
    '5:0':'Three more useful contexts license an indefinite subject.',
    '5:2':'A fronted prepositional or adverbial predicate can prepare for it. Sudden إذا can introduce it. A prayer or imprecation can also make the predication informative.',
    '5:4':'وفوق كل ذي علم عليم puts the adverbial predicate before indefinite عليم. The ascent report says علونا السماء الدنيا فإذا رجل قاعد: sudden إذا licenses رجل as the newly encountered subject.',
    '5:5':'سلام عليكم is a blessing; ويل لكل همزة لمزة is an imprecation against scorners and slanderers. Both use an indefinite nominal subject in the invocation account.',
    '5:7':'Context can supply a subject, often after response فاء or saying.',
    '5:9':'فلنفسه supplies فعمله لنفسه: the deed benefits its doer. وقالوا أساطير الأولين supplies هي أساطير الأولين. The unspoken subjects are عمله and هي; the remaining phrases are predicates.',
  }, boxCopy:{
    '0:1':['نائب الفاعل: ما أسند إليه فعل تام مبني للمجهول، أو ما بمعناه.'],
    '1:0':['قد ينوب الجار والمجرور عن الفاعل.'],
    '2:1':['اسم مجرد مسند إليه؛ أو وصف مكتفٍ بما يرفعه.'],
    '2:5':['المبتدأ المكتفي بمرفوعه لا يحتاج إلى خبر منفصل.'],
    '3:4':['التوكيد باللام: ميّز الابتداء من جواب القسم.'],
    '4:3':['خمس صلوات كتبهن الله؛ كل يعمل على شاكلته','ولعبد مؤمن خير من مشرك؛ وطائفة قد أهمتهم أنفسهم'],
    '4:6':['ما أَحَدٌ خَيْرٌ مِنْ أَحَدٍ إِلّا بِالتَّقْوَى','أَإِلٰهٌ مَعَ اللهِ'],
    '5:1':['خبر متقدم شبه جملة؛ أو إذا الفجائية؛ أو دعاء.'],
    '5:6':['يجوز حذف المبتدأ إذا دلّت عليه قرينة.'],
  } }),
  '24/l3': plan(119, 'When the Nominal Subject Is Omitted', [
    [c('Required omission in a construction', 0, 1)],
    [c('A description cut to رفع', 0, 1, 2), c('A comparison: cutting to نصب', 3, 4, 5)],
    [c('An understood undertaking', 0, 1, 2, 3)],
    [c('A مصدر replaces verbal expression', 0, 1, 2, 3)],
    [c('The person singled out for praise or blame', 0, 1), c('Two analyses of the مخصوص', 2, 3), c('The omitted-subject analysis', 4)],
  ], [
    ['قطع', 'A raised description can be خبر of an understood هو.'],
    ['قسم', 'في ذمتي supplies an undertaking identified by the oath response.'],
    ['مصدر', 'The verbal-substitution account of فصبر جميل omits its مبتدأ.'],
    ['مخصوص', 'An omitted subject or a later مبتدأ are distinct accounts.'],
  ], { copy:{
    '0:1':'Optional omission relies on a clear context. Required omission belongs to a specified construction: stating the omitted word changes that construction. This source groups four positions here, while recording disagreement over the fourth. It is not saying every expanded explanatory sentence is ungrammatical.',
    '1:0':'A description normally matches the noun it describes. قطع إلى الرفع interrupts that agreement for emphasis and makes the description خبر of an omitted هو.',
    '1:2':'الحمد لله الحميدُ means “Praise belongs to Allah, the Praiseworthy.” الله is genitive by لام, not by إضافة. Matching description would be الحميدِ; raised الحميدُ instead supplies a separate assertion, هو الحميد.',
    '1:3':'Cutting to نصب is a related emphatic construction, with an omitted verb rather than مبتدأ.',
    '1:5':'حمالةَ الحطب has نصب for condemnation in the reading taught: أذم حمالةَ الحطب. The account makes امرأته coordinated with the subject of تبّ. This phrase occurs later in Surat al-Masad; the source’s excerpt skips intervening verses. Other readings and analyses are recorded.',
    '2:1':'The oath response reveals an unspoken undertaking.',
    '2:3':'“Upon my honour, I will speak the truth.” Supply عهد, وعد or قسم: في ذمتي عهد. لأقولن signals that undertaking. The response explains why the subject can remain unspoken; it is not itself that subject.',
    '3:0':'Here a مصدر replaces verbal expression and is خبر of an omitted مبتدأ.',
    '3:2':'“Then beautiful patience”: supply صبري or أمري صبر جميل.',
    '3:3':'Compare اصبر صبرا جميلا. The nominal version can suggest settled resolve or constancy. That contextual effect does not make every verb a one-off event. Another analysis makes صبر the subject of an omitted predicate.',
    '4:1':'نعم الطالب المجتهد praises the diligent student; بئس الطالب الكسول blames the lazy one. On the omitted-subject reading, المجتهد and الكسول are خبر of understood هو, identifying the person singled out.',
    '4:3':'Some grammarians require omission in that reading; others permit it. Another well-known reading makes المجتهد or الكسول a later مبتدأ, with the whole نعم الطالب or بئس الطالب clause as its earlier خبر. It does not also insert a second hidden هو inside this latter account.',
  }, boxCopy:{'0:0':['أربعة مواضع في عرض المصدر، مع خلاف في الرابع.'],'1:4':['تبت يدا أبي لهب وتبّ','… وامرأته حمالةَ الحطب'],'2:0':['جواب القسم يدل على المبتدأ المحذوف.']}, visuals:{'4:1':v('Keep the two analyses distinct',['هو المجتهد','خبر of an omitted subject'],['المجتهد','Later مبتدأ; نعم الطالب is its خبر'])}, analysisPrompt:'Use the omitted-subject analysis.', analysisItemLabels:{'bank-17':{'مبتدأ مؤخّر':'مبتدأ منصوب'}} }),
};

export const checks = {
  '24/l1':[
    q('Which role belongs with a complete passive verb?', ['نائب الفاعل','اسم كان','المبتدأ','المفعول المطلق'], 'Contrast active and passive construction.'),
    q('What does كم denote in كذكركم آباءكم?', ['The rememberers, in إضافة to the مصدر','The fathers remembered','A new nominal subject opening the sentence','The predicate of ذكر'], 'Separate the semantic subject from its genitive construction.'),
    q('How does the Kufan account analyze زيد in زيد قام?', ['A subject preceding its verb','A fronted object','A predicate of قام as subject','Only a مبتدأ, with no other account'], 'Compare the Basran hidden-subject analysis.'),
    q('Why does feminine زارت not distinguish هذه from تلك?', ['Both demonstratives are feminine','Verb gender never provides a clue','Both are masculine','Demonstratives cannot be subjects'], 'A clue must distinguish the two candidates.'),
    q('What identifies the eater in أكل الكمثرى موسى?', ['Meaning: Moses eats the pear','A visible case ending','Both meaning and visible case endings','No clue; the pear must be the subject'], 'The ordinary meaning excludes a pear eating Moses.'),
    q('Must the object precede the subject in جاء آل فرعون النذر?', ['No; the order is grammatically permitted','Yes; النذر is an attached pronoun','Yes; neither noun has visible case','Yes; آل is interrogative'], 'Case endings distinguish the roles.'),
    q('Why is أي آيات الله fronted in فأي آيات الله تنكرون?', ['Interrogative precedence','A pronoun inside the object needs a later subject','An attached subject must detach','Only optional rhetorical choice'], 'أي asks which signs.'),
  ],
  '24/l2':[
    q('What changes between the فاعل and نائب الفاعل definitions?', ['Active معلوم becomes passive مجهول','Complete becomes incomplete','رفع becomes نصب','Noun becomes particle'], 'These terms describe verbal voice.'),
    q('Why can بجهنم supply نائب الفاعل after جيء?', ['This bringing construction uses a preposition, with no direct object to promote','A phrase always outranks a direct object','جهنم is مبني','A passive verb needs no deputy subject'], 'Preserve the original preposition.'),
    q('Which two readings are possible for أراغب أنت?', ['Governing راغب with subject أنت; or fronted predicate راغب with topic أنت','Only a fronted-predicate reading','راغب is a past verb in both','Neither is grammatical'], 'The adjective can be completed by what it raises.'),
    q('Which account explains the emphatic لام in لقد جاء?', ['An oath response, with an oath possibly understood','لام الجر','لام الأمر','لام التعليل'], 'Compare والله لقد جاء.'),
    q('How does the source explain specification of كل in كل يعمل?', ['An understood إضافة: كل أحد','A preceding question','A preceding negation','كل can never be indefinite'], 'The complement need not be spoken.'),
    q('What subject is supplied in من عمل صالحا فلنفسه?', ['عمله, after response فاء','هو, after a vocative','None; لنفسه is the subject','الرجل, after a question'], 'The deed’s benefit returns to its doer.'),
  ],
  '24/l3':[
    q('What distinguishes required from optional omission?', ['The specified construction requires the omission','Required means omission is forbidden','There is no distinction','It concerns only اسم كان'], 'Adding the explanatory word changes the construction.'),
    q('Why is الحميدُ raised in الحمد لله الحميدُ?', ['A cut description becomes خبر of understood هو','It is an overlooked error','It is another مضاف إليه','The phrase is entirely مبني'], 'An ordinary matching adjective would have جر.'),
    q('What does في ذمتي لأقولن الصدق leave understood?', ['An undertaking such as عهد, signalled by the oath response','هو, because في always omits a subject','الصدق moved out of its object role','أنا, because every مضارع omits مبتدأ'], 'Distinguish the undertaking from its promised action.'),
    q('What can nominal فصبر جميل convey in the account taught?', ['Settled resolve and constancy','No possible rhetorical effect','A change from singular to plural','A question replacing the command'], 'Compare a lasting commitment with the verbal explanation.'),
    q('What is the alternative to the omitted-subject reading of المجتهد?', ['Later مبتدأ, with نعم الطالب as its earlier خبر','Subject of نعم, replacing الطالب','No valid analysis','Object of نعم'], 'Keep the two parses separate.'),
  ],
};

export const quizzes = {
  '24/l1':[
    q('Which noun role belongs with a passive verb?', ['نائب الفاعل','اسم كان','الخبر','المبتدأ']),
    q('What is بشيرٍ in ما جاءنا من بشير?', ['Subject with رفع position despite visible جر','Object with نصب position','Nominal subject مبتدأ','Only a genitive إضافة complement']),
    q('Which is the default verbal order?', ['Verb, subject, object','Verb, object, subject','Subject, verb, object','Object, verb, subject']),
    q('Why can تُ not simply detach in ضربت زيدا?', ['The subject pronoun must remain attached','The two names are ambiguous','An interrogative must lead','An object’s referent is unspoken']),
    q('What identifies سلمى as subject in نصرت موسى سلمى?', ['Feminine agreement on the verb','The reverse meaning is impossible','سلمى is an interrogative','Nothing; the sentence is ambiguous']),
    q('Why does إبراهيم precede ربّه in ابتلى إبراهيم ربّه?', ['The subject contains a pronoun referring to the object','ربه is itself an attached verb pronoun','إبراهيم is interrogative','This order has no grammatical motivation']),
  ],
  '24/l2':[
    q('Which definition contrast separates فاعل and نائب الفاعل?', ['Active معلوم versus passive مجهول','رفع versus نصب','Complete versus incomplete','Noun versus particle']),
    q('What matters in the construction جيء بجهنم?', ['Bringing with جاء به uses a prepositional complement','Only present verbs allow phrase deputies','Phrases always replace any direct object','The active verb never has a subject']),
    q('What does مكتفٍ بمرفوعه mean for راغب in one reading?', ['What it raises completes predication without a separate خبر','It needs two predicates','It cannot govern a subject','It must be definite']),
    q('Why may لام emphasize كاذب in لكاذب أنت?', ['كاذب is a fronted predicate in this account','لام never enters on مبتدأ','أنت already contains a hidden لام','كاذب is a past verb']),
    q('How is كل specified in the source’s account of كل يعمل?', ['By understood إضافة: كل أحد','By a preceding question','By a preceding negation','The sentence is ungrammatical']),
    q('What licenses رجل in فإذا رجل قاعد?', ['Sudden إذا','An invocation','A fronted prepositional predicate','Negation']),
  ],
  '24/l3':[
    q('What does وجوب حذف المبتدأ mean in the specified account?', ['The construction requires omission','Omission is forbidden','It is simply optional','It concerns only اسم كان']),
    q('Which pattern explains الحمد لله الحميدُ?', ['قطع النعت إلى الرفع','A مصدر replacing a verb','An oath response','A مخصوص after نعم or بئس']),
    q('What reveals the undertaking in في ذمتي لأقولن الصدق?', ['The following oath response','A cut adjective','A مصدر replacing its verb','A praise construction']),
    q('Why is the subject omitted in the taught verbal-substitution account of فصبر جميل?', ['Its predicate is a مصدر standing for verbal expression','صبر is مبني','An imperative can never be explained by a nominal sentence','This account has no omitted subject']),
    q('In the omitted-subject account, what is المجتهد after نعم الطالب?', ['The مخصوص, as خبر of understood هو','The subject of نعم','A direct object','An إضافة complement']),
    q('What is the other well-known account of المجتهد?', ['Later مبتدأ; نعم الطالب is its earlier خبر','Subject of نعم instead of الطالب','An accusative حال','There is no competing analysis']),
  ],
};
