import { card as c, rows as r, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '13/l1': plan(62, 'Wishing with ليت', [
    [c('Wishing beyond hope', 0, 1, 2, 3, 4)],
    [c('يا intensifies the wish', 0, 1, 2, 3)],
    [c('Two accounts of يا before ليت', 0, 1, 2)],
    [c('Five ways these particles resemble verbs', 0, 1), c('Verb-like meanings inside the particles', 2, 3, 4)],
    [c('A final fatḥah like the past verb', 0, 1), c('Attached pronouns and نون الوقاية', 2, 3)],
    [c('Government of رفع and نصب', 0, 1), c('At least three letters', 2, 3), c('Keep the governed parts after the particle', 4, 5)],
  ], [
    ['ليت', 'تمنّي: a wish with no realistic hope of attainment.'],
    ['يا ليتني', 'Emotional emphasis; يا is analysed as تنبيه or a call with omitted منادى.'],
    ['Five resemblances', 'Verbal meaning, final fatḥah, attached pronouns, government, word length.'],
    ['Ordering', 'Their معمول stays after the particle, including with non-initial أنّ.'],
  ], { copy: {
    '0:0': 'ليت is sixth; genus لا is seventh.',
    '0:2': 'تمنّي seeks what lies beyond realistic hope.',
    '0:4': 'The poet personifies youth: it cannot return to hear what old age has done.',
    '1:1': 'Quranic ليت is commonly introduced by يا, often in يا ليتني.',
    '1:3': 'The wrongdoer cries over the record of deeds on Judgement Day. يا and the lengthened sound heighten وجد, the emotional force of the wish.',
    '2:0': 'No visible addressee follows يا: ليت is a particle.',
    '2:2': 'One account takes يا as an attention particle. Another restores an omitted addressee, such as يا هؤلاء ليتني. Both explain its role in heightening the wish, though their grammatical analyses differ.',
    '3:0': 'The six are إنّ، أنّ، كأنّ، لكنّ، ليت، لعلّ.',
    '3:2': 'Each carries a verb’s meaning.',
    '3:4': 'A verbal paraphrase keeps the basic meaning.',
    '4:1': 'Their original final fatḥah resembles the default بناء of a past verb: إنّ، أنّ، كأنّ، ليت، لعلّ، لكنّ.',
    '4:3': 'Verbs attach object pronouns: خلقني، ضربتك. Compare إنك، أنك. نون الوقاية protects the ending before ياء: إنني، لكنني، ليتني. The usual لعل form is لعلّي. Some other particles also allow omission, as in إني.',
    '5:1': 'A transitive verb governs فاعل with رفع and مفعول with نصب. These particles likewise govern both cases, but as اسم منصوب and خبر مرفوع.',
    '5:3': 'Like verb patterns, these particles have at least three pronounced letters. Count a doubled consonant twice: إنّ، أنّ، ليت have three; كأنّ and لعلّ have four. لكنّ also contains a pronounced, unwritten ألف.',
    '5:5': 'Their اسم and خبر cannot move before the particle. أنّ itself occupies a noun-equivalent position rather than opening a fresh sentence, but this restriction on its معمول remains.',
  }, boxCopy: { '3:1': ['Five points of resemblance: verbal meaning, final fatḥah, attached pronouns, government of cases, and word length.'],
    '3:3': ['إنّ زيدا قائم: أؤكد قيام زيد. وكذلك أنّ.', 'لكنّ هذا مني: أستدرك ذلك.', 'ليت الشباب يعود: أتمنى عود الشباب.', 'لعلّ: أرجو. كأنّ زيدا أسد: أشبّه زيدا بالأسد.'] },
    visuals: { '5:2': v('The same ordering restriction', ['إنّ زيدًا قائم', 'A clause opening'], ['علمت أنّ زيدًا قائم', 'A noun-equivalent inside a larger clause']) } }),
  '13/l2': plan(63, 'Lightening إنّ and أنّ', [
    [c('Four particles can lose the doubled ن', 0, 1, 2)],
    [c('One meaning across different recitations', 0, 1, 2), c('Recitations retaining strong إنّ', r(3, 0, 1)), c('Recitations with lightened إنْ', r(3, 2, 3)),
      c('A non-canonical negative reading', r(3, 4), 4, 5)],
    [c('لام distinguishes affirmation from negation', 0, 1, 2, 3), c('Different accounts of the distinguishing لام', 4, 5, 6)],
    [c('Lightened أنّ keeps its government', 0, 1, 2)],
    [c('An understood ضمير الشأن', 0, 1), c('Why Ibn Ashur disputed this analysis', 2, 3, 4)],
    [c('What determines the separator?', 0, 1), c('Three clauses follow directly', r(2, 0, 1, 2)), c('Separating with قد or a future marker', r(2, 3, 4)), c('Separating with لو or negation', r(2, 5, 6))],
  ], [
    ['إنْ', 'Usually مهملة after lightening; إعمال remains possible.'],
    ['لام فارقة', 'Distinguishes affirmation from possible negative إنْ.'],
    ['أنْ', 'The usual analysis retains عمل, with an omitted ضمير الشأن.'],
    ['Its خبر', 'A clause. Other than nominal, fixed-verb or prayer clauses, a separator is used.'],
  ], { copy: {
    '0:0': 'إنّ، أنّ، كأنّ and لكنّ can lose the doubled ن. ليت and لعلّ are outside this pattern; لعلّ does have a doubled ل.',
    '0:2': 'Lightened إنْ usually loses government, إهمال. Retaining government, إعمال, is also allowed.',
    '1:0': 'This verse illustrates several transmitted forms and their analyses.',
    '1:2': 'All convey that each person receives full recompense.',
    '1:5': 'The لَمّا analyses differ: proposed لَمِنْ ما; لام plus emphatic ما; or, in the non-canonical negative reading, “except”. Another proposed analysis supplies an omitted verb governing كلّا. Recitation and grammatical explanation must be distinguished.',
    '2:1': 'With neglected إنْ, لام distinguishes “indeed” from negative إنْ, “not”.',
    '2:3': 'Without لام, the example could suggest “We do not think you among the liars”. The intended reading is affirmative.',
    '2:5': 'Baghdad’s school calls it لام الابتداء. الكوفيون instead analyse إنْ as negative and لام as “except”. The distinguishing role is especially needed with إهمال, where case no longer identifies emphatic إنْ.',
    '2:6': 'Lightened إنْ also enters nominal clauses, not only verbal ones.',
    '3:0': 'Lightening أنّ has a different usual result from إنّ.',
    '3:2': 'أنْ retains its اسم-and-خبر government in the standard analysis, although the اسم is unspoken.',
    '4:1': 'The usual analysis supplies an omitted ضمير الشأن: “It is the case that...” The following clause explains that matter.',
    '4:3': 'Ibn Ashur instead reads lightened أنّ as a non-governing clause introducer. He questions both assumed continuing government and the permanently omitted subject.',
    '4:4': 'He calls this توهم على توهم, “supposition upon supposition”: why supply an invisible emphatic pronoun? This course uses the common omitted-pronoun analysis while retaining his objection.',
    '5:1': 'The خبر is a clause. Nominal clauses, fixed verbs and conjugatable verbs used for prayer need no separator. Other verbal clauses use the devices on the next cards.',
  }, boxCopy: { '0:1': ['إنْ المخففة: الإهمال غالب، والإعمال جائز.'],
    '1:1': ['وَإِنَّ كُلًّا لَمَّا لَيُوَفِّيَنَّهُمْ رَبُّكَ أَعْمَالَهُمْ', 'Your Lord will repay each one fully for their deeds.'],
    '2:0': ['اللام الفارقة تميّز إنْ المخففة من إنْ النافية.'],
    '5:0': ['خبر أنْ المخففة جملة، وقد يفصل بينها وبينه قد أو تنفيس أو لو أو نفي.'] }, tableCopy: {
    '1:3': { 0: ['حفص', 'إنّ مشددة عاملة', 'كلّا اسمها', 'لمّا: لَمِنْ ما في التوجيه المعروض.'],
      1: ['أبو عمرو', 'إنّ مشددة عاملة', 'كلّا اسمها', 'لَمَا: لام وما زائدة.'],
      2: ['شعبة', 'إنْ مخففة عاملة', 'كلّا اسمها', 'لمّا: لَمِنْ ما في التوجيه المعروض.'],
      3: ['نافع وابن كثير', 'إنْ مخففة عاملة', 'كلّا اسمها', 'لَمَا: لام وما زائدة.'],
      4: ['شاذة', 'إنْ نافية', 'كلّ مبتدأ', 'لمّا بمعنى إلا.'] },
    '5:2': { 0: ['Nominal clause', 'وآخر دعواهم أنِ الحمد لله رب العالمين'],
      1: ['Fixed verb', 'وأنْ ليس للإنسان إلا ما سعى'],
      2: ['Prayer verb', 'والخامسةُ أنْ غَضِبَ اللهُ عليها، قراءة نافع'],
      3: ['قد', 'ونعلم أنْ قد صدقتنا'], 4: ['Future سـ', 'علم أنْ سيكون منكم مرضى'],
      5: ['لو', 'أنْ لو نشاء أصبناهم بذنوبهم'], 6: ['Negation', 'أيحسب أنْ لم يره أحد'] },
  } }),
  '13/l3': plan(64, 'Lightening كأنّ and Adding ما', [
    [c('Lightened كأنْ before a verb', 0, 1, 2), c('A competing non-governing analysis', 3, 4)],
    [c('ما الكافة restrains government', 0, 1, 2, 3)],
    [c('An ordinary مبتدأ and خبر after إنما', 0, 1, 2), c('A verb can directly follow إنما', 3, 4)],
    [c('ليتما permits either government choice', 0, 1)],
    [c('Two changes with different effects', 0), c('إنّ and أنّ: compare the two changes', r(1, 0, 1)), c('كأنّ and لكنّ diverge when lightened', r(1, 2, 3)),
      c('ليت and لعلّ are outside ن-lightening', r(1, 4, 5))],
  ], [
    ['كأنْ', 'Usually retains عمل; omitted اسم and a clause often separated by لم or قد.'],
    ['ما الكافة', 'Stops government; forms such as إنما can precede a verb.'],
    ['ليتما', 'Either إعمال or إهمال; it keeps its nominal construction.'],
    ['لكنْ', 'Lightening makes it مهملة; compare retained عمل with أنّ and كأنّ.'],
  ], { copy: {
    '0:1': 'Like أنّ, lightened كأنْ retains government in the common analysis. An omitted ضمير الشأن is its اسم; لم or قد usually separates a verbal predicate.',
    '0:4': 'Some grammarians instead treat كأنْ as entirely non-governing, against the majority account used here.',
    '1:0': 'A separate change adds ما الكافة, “restraining ما”.',
    '1:3': 'Compare إنما، أنما، كأنما، لكنما، لعلما and ليتما. ما normally stops نصب/رفع government; forms such as إنما can then precede a verb directly. ليْتما has a special rule below.',
    '2:1': 'إلهكم and الله are simply مبتدأ and خبر. إنما does not govern their case: “Your God is only Allah.”',
    '2:4': '“Allah accepts only from the God-fearing.” يتقبل directly follows إنما. Plain governing إنّ requires its اسم first.',
    '3:1': 'ليتما permits either إعمال or إهمال, unlike the usual result with the other five. It retains its nominal construction; the general permission to introduce a verb does not extend to it.',
    '4:0': 'Lightening ن and adding ما are separate operations. إنْ may govern or not; أنْ and كأنْ retain government in the usual account; لكنْ does not. ما normally stops government, except that ليتما allows both.',
  }, boxCopy: { '0:0': ['كأنْ تبقى عاملة في الإعراب المشهور، ويفصلها عن الفعل غالبا لم أو قد.'],
    '1:2': ['ما تكفّ العمل، وتسوّغ الدخول على الفعل في مثل إنما.'] }, tableCopy: {
    '4:1': { 0: ['إنّ', 'Emphasis.', 'Alone: governs.', 'With ما: stops.', 'Lightened: either.'],
      1: ['أنّ', 'Emphasis.', 'Alone: governs.', 'With ما: stops.', 'Lightened: retained.'],
      2: ['كأنّ', 'Likeness.', 'Alone: governs.', 'With ما: stops.', 'Lightened: retained.'],
      3: ['لكنّ', 'Correction.', 'Alone: governs.', 'With ما: stops.', 'Lightened: stops.'],
      4: ['لعلّ', 'Hope, expectation or purpose.', 'Alone: governs.', 'With ما: stops.', 'Outside ن-lightening.'],
      5: ['ليت', 'Wishing.', 'Alone: governs.', 'With ما: either.', 'Outside ن-lightening.'] },
  }, visuals: { '4:0': v('Change the consonant or add a particle', ['إنّ ← إنْ', 'Lighten ن'], ['إنّ ← إنما', 'Add ما']) } }),
};

export const checks = {
  '13/l1': [q('What distinguishes تمنّي from an ordinary request?', ['No realistic hope of attaining what is wished for.', 'It occurs only in poetry.', 'It always requires a past predicate.', 'It is simply another name for نداء.'], 'Think of the wish for youth to return.'),
    q('What do يا and vocal length add to يا ليتني?', ['Emotional force, وجد.', 'A named person being called.', 'Two direct objects.', 'Negation instead of wishing.'], 'Listen for the weight of regret.'),
    q('Which two accounts explain يا in يا ليتني?', ['تنبيه, or نداء with omitted منادى.', 'جر or عطف.', 'Question or negation.', 'Urging or explanation.'], 'There is no visible addressee.'),
    q('What does لكنّ = أستدرك illustrate?', ['A verb’s meaning inside the particle.', 'A required vocative noun.', 'Exactly three letters in every particle.', 'Its predicate becomes a verb’s subject.'], 'This is the first resemblance to verbs.'),
    q('Which particle normally gives لعلّي without نون الوقاية?', ['لعلّ.', 'أنّ never permits نون.', 'كأنّ never accepts ياء.', 'لكنّ must double an extra نون.'], 'Compare the usual form with ليتني.'),
    q('Can أنّ’s معمول precede it because أنّ is not sentence-initial?', ['No; the ordering restriction remains.', 'Yes; both parts may freely move before it.', 'No; أنّ alone must be sentence-initial.', 'Yes, but only after lightening.'], 'The whole noun-equivalent and its internal parts have different positions.')],
  '13/l2': [q('What usually happens to إنّ’s government when lightened?', ['إهمال, with إعمال also permitted.', 'It must always keep government.', 'It becomes a noun.', 'It cannot be lightened.'], 'Distinguish usual from obligatory.'),
    q('What remains across the compared recitations?', ['The overall meaning.', 'كلّا’s exact إعراب.', 'The strength of إنّ.', 'The analysis of لمّا.'], 'Different transmitted forms can express the same promise.'),
    q('What does لام الفارقة distinguish?', ['Affirming إنْ from negative إنْ.', 'A return to required government.', 'A question.', 'A fronted predicate.'], 'Without it, “indeed” might be heard as “not”.'),
    q('How does lightened أنّ compare with usually neglected إنْ?', ['It retains عمل in the standard account.', 'Both usually lose عمل.', 'أنّ cannot be lightened.', 'It loses عمل only after يا.'], 'Its اسم is supplied in the analysis even when unspoken.'),
    q('What اسم does the usual analysis supply after lightening أنّ?', null, 'Ibn Ashur disputes this assumption.'),
    q('What separates أنْ from سيكون in علم أن سيكون...?', null, 'Identify the future marker.')],
  '13/l3': [q('What commonly separates كأنْ from its verbal predicate?', null, 'Compare كأن لم يلبثوا.'),
    q('What does ما الكافة do with إنّ?', ['Stops government and permits a following verb.', 'Doubles the consonant and raises the اسم.', 'Turns it into a past verb.', 'Nothing; it is decorative.'], 'These are two linked changes.'),
    q('Why can يتقبل directly follow إنما?', ['ما has stopped إنّ’s case government.', 'إنما is unrelated to إنّ.', 'Every governing particle can directly precede a verb.', 'يتقبل is really a noun.'], 'Compare plain إنّ with its required اسم.'),
    q('Which form with ما keeps both إعمال and إهمال possible?', ['ليتما.', 'إنما must always govern.', 'أنما becomes negative.', 'لكنما takes two direct objects.'], 'This is the special exception.'),
    q('Which two retain government when lightened, in the usual account?', null, 'Compare them with لكنْ.')],
};
export const quizzes = {
  '13/l1': [q('ليت is sixth in a category of how many particles?'), q('What commonly precedes ليت in Quranic usage?'),
    q('Which analyses explain يا in يا ليتني?', ['تنبيه, or نداء with omitted منادى.', 'جر or عطف.', 'Question or urging.', 'Explanation or negation.']),
    q('Which resemblance is shown by كأنّ زيدا أسد = أشبه زيدا بالأسد?'), q('Which normally uses the form لعلّي without نون الوقاية?'),
    q('What is special about أنّ and the initial-position rule?', ['It occupies a noun position, but its معمول still cannot precede it.', 'Its معمول may freely precede it.', 'It is outside the six verb-like particles.', 'It alone permits a predicate before its noun.'])],
  '13/l2': [q('Which four particles undergo the ن-lightening described here?'), q('What remains across the compared recitations?'), q('What does لام الفارقة distinguish?'),
    q('Which retains عمل after lightening, unlike إنّ’s usual result?'), q('Which اسم is supplied by the usual analysis of lightened أنّ?'),
    q('Does a nominal-clause خبر need a separator after أنْ?', ['No; it follows directly in this pattern.', 'Always قد.', 'Always a future marker.', 'Every clause needs a separator.'])],
  '13/l3': [q('What commonly separates كأنْ from its verbal predicate?'), q('What changes when ما الكافة attaches in forms such as إنما?', ['Government stops; a verb may follow directly.', 'Doubling and compulsory predicate-fronting.', 'The particle becomes a noun.', 'Its entire meaning disappears.']),
    q('Can plain governing إنّ directly precede يتقبل like إنما?', ['No; it requires its اسم.', 'Yes, always.', 'Only in poetry.', 'No; إنما is unrelated to إنّ.']),
    q('Which form keeps both government choices after ما?'), q('What happens to لكنّ when lightened?'),
    q('Why are لعلّ and ليت outside this lightening rule?', ['They are outside the doubled-ن pattern being taught.', 'They are not verb-like particles.', 'Only poetry permits the change.', 'Their اسم must always be visible.'])],
};

Object.assign(plans, {
  '13/l4': plan(65, 'Negating the Whole Genus with لا', [
    [c('No member of the category qualifies', 0, 1, 2, 3)],
    [c('Two names for the sweeping denial', 0, 1, 2)],
    [c('لا inside a prepositional phrase', 0, 1, 2, 3), c('Two accounts of لا in بلا', 4, 5)],
    [c('Genus-wide negation and an adjacent noun', 0, 1, 2), c('Denying one, while affirming two', 3, 4)],
    [c('A separator stops government', 0, 1, 2)],
    [c('Repeated لا: two patterns', 0, 1, 2, 3, 4), c('Alternative readings confirm the choice', 5, 6)],
  ], [
    ['نفي الجنس', 'An explicit denial covering every member of a category.'],
    ['Government', 'An adjacent indefinite اسم; the negation covers the whole genus.'],
    ['No operation', 'A prepositional phrase or a separator prevents this government.'],
    ['Repetition', 'Without separation, إعمال and إهمال are both permitted.'],
  ], { copy: {
    '0:0': 'After the six verb-like particles, لا لنفي الجنس completes this seven-member category.',
    '0:3': 'The denial covers every doer of evil, not just one. فاعلَ is منصوب and مضاف to شرّ; فائز is the مرفوع predicate.',
    '1:0': 'Each name highlights a different aspect.',
    '1:2': 'لا لنفي الجنس names explicit, exhaustive negation: تنصيص الاستغراق. لا التبرئة, from برّأ, describes freeing the subject from the predicate’s description entirely.',
    '2:0': 'This government does not apply inside جار ومجرور.',
    '2:3': 'باء governs حسابٍ. لا retains its negative meaning without heading an اسم-and-خبر construction.',
    '2:5': 'The disputed word is لا itself. الكوفيون analyse it as a noun like غير, with حساب as مضاف إليه. Others call it an added particle, with باء governing حساب. Neither analysis gives it اسم-and-خبر government here.',
    '3:0': 'For this use, the negation must cover the genus and its indefinite اسم must be adjacent.',
    '3:2': 'If the intended denial is only of one unit, لا can instead work like ليس: اسم مرفوع and خبر منصوب.',
    '3:4': 'Two men are standing, so the genus is not denied. رجلٌ stays مرفوع and قائما is منصوب: لا المشبهة بليس denies the unit “one”.',
    '4:0': 'Separation blocks government. In this pattern لا must repeat.',
    '4:2': 'فيها separates لا from غولٌ, so غول is an ordinary مبتدأ مرفوع. لا repeats in the second clause; it does not govern the first noun.',
    '5:0': 'Repetition permits two patterns.',
    '5:2': 'Both are valid without separation.',
    '5:4': 'بناء على الفتح: رفث، فسوق، جدال. رفع: خوف.',
    '5:6': 'Abu Jaʿfar’s reading has رفع with tanwin on all three Hajj nouns. The phrase لا حول ولا قوة إلا بالله likewise permits governing and non-governing analyses: repetition makes both available.',
  }, boxCopy: { '1:1': ['لا لنفي الجنس: نفي كل الأفراد. لا التبرئة: نفي اتصاف الاسم بالخبر.'],
    '2:4': ['لا في بلا: اسم كغير عند الكوفيين، وحرف زائد عند غيرهم.'],
    '3:1': ['تنفي الجنس، ويكون اسمها نكرة متصلا بها.'],
    '5:1': ['مع التكرار بلا فصل يجوز الإعمال والإهمال.'] } }),
  '13/l5': plan(66, 'Particles Working Like ليس', [
    [c('A مرفوع اسم and a منصوب خبر', 0, 1, 2, 3)],
    [c('The case underneath added باء', 0, 1), c('A fronted predicate blocks ما’s government', 2, 3, 4, 5), c('Added إنْ also blocks ما’s government', 6, 7)],
    [c('إلا blocks ما’s operation', 0, 1, 2, 3, 4), c('Hijazi government and Tamimi non-government', 5, 6)],
    [c('لا working like ليس in poetry', 0, 1, 2, 3), c('لات is restricted to time', 4, 5, 6, 7)],
    [c('Negative إنْ in the dialect of العالية', 0, 1, 2, 3), c('إنْ before a verbal restriction', 4, 5)],
  ], [
    ['Shared pattern', 'Negation; اسم مرفوع and خبر منصوب.'],
    ['ما الحجازية', 'اسم first; no added إنْ; no إلا before the predicate.'],
    ['لا / لات', 'لا chiefly in poetry; لات for time, usually with an omitted اسم.'],
    ['إنْ', 'Operates in العالية’s usage; restriction with إلا remains non-governing.'],
  ], { copy: {
    '0:0': 'This family reverses إنّ’s pattern: اسم مرفوع and خبر منصوب, like ليس.',
    '0:3': 'Compare زيد ليس قائما: negation inside a subject-predicate construction. Three core particles are studied, plus a fourth associated here with a particular dialect.',
    '1:1': 'ربك is اسم ما مرفوع. ظلامٍ is خبرها with نصب in position, despite جر in form from added باء. ما is the most frequent of these particles.',
    '1:3': 'The first condition requires اسم before خبر.',
    '1:5': 'من أعتب is the subject; مسيء is خبر مقدم. Fronting that predicate stops ما’s operation, leaving مسيء مرفوع.',
    '1:6': 'The second condition excludes added إنْ after ما.',
    '1:7': 'ما إن أنتم قائمون: added إنْ blocks government, so قائمون remains مرفوع.',
    '2:0': 'Third: إلا must not introduce the predicate.',
    '2:2': 'رسولٌ remains مرفوع.',
    '2:4': 'The construction affirms Muhammad’s messengership. Restriction with إلا breaks the negative pattern required for ما’s ليس-like government.',
    '2:6': 'أهل الحجاز allow this government under its conditions; بني تميم leave ما non-governing. Quranic examples attest the Hijazi pattern; the label describes dialectal usage.',
    '3:1': 'لا’s ليس-like operation is chiefly attested in poetry.',
    '3:3': 'شيءٌ is اسم لا; باقيا is its منصوب خبر. The second half similarly pairs وزرٌ with واقيا.',
    '3:5': 'لات concerns time, not لات زيد قائما.',
    '3:7': 'In ولات حين مناص, an understood الحين is اسم لات; حينَ مناص is its خبر. Some treat لات as simple, others as لا with an added تاء of emphasis or feminisation. The analysis of its form does not alter the rule.',
    '4:1': 'أهل العالية allow negative إنْ to work like ليس.',
    '4:3': 'أحدٌ is اسم إنْ, and خيرا its منصوب خبر. إلا بالعافية restricts the qualifying circumstance, not the predicate itself.',
    '4:5': 'The usual non-governing pattern is إنْ زيدٌ قائمٌ. In إن يقولون إلا كذبا, إنْ is negative and non-governing; the following verb governs its own construction. Restriction does not make إنْ govern like ليس.',
  }, boxCopy: { '0:1': ['تدخل على المبتدأ والخبر، فترفع الاسم وتنصب الخبر.'],
    '1:2': ['عمل ما: الاسم أولا، ولا إنْ زائدة، ولا إلا قبل الخبر.'],
    '2:3': ['لا تعمل ما إذا انتقض النفي بإلا.'],
    '3:4': ['لات مختصة بالحين، وغالبا يحذف اسمها ويفهم الحين.'],
    '4:0': ['إنْ النافية تعمل عمل ليس عند أهل العالية.'],
    '4:4': ['إنْ في إنْ يقولون إلا كذبا نافية غير عاملة.'] } }),
  '13/l6': plan(67, 'Comparing the Five Families of نواسخ', [
    [c('A governor changes the nominal pattern', 0, 1, 2)],
    [c('Two verb families, two case patterns', 0, 1)],
    [c('Three particle families', 0)],
    [c('Both objects, or the predicate alone?', 0, 1, r(4, 0, 1)), c('Two families changing the اسم', 2, r(4, 2, 3)), c('The mirrored particle pattern', 3, r(4, 4))],
  ], [
    ['نواسخ', 'Governors entering a مبتدأ-خبر construction and changing its إعراب.'],
    ['Heart verbs', 'Two مفعولان, both منصوب.'],
    ['Incomplete / ليس-like', 'اسم مرفوع; خبر منصوب.'],
    ['إنّ family / genus لا', 'اسم منصوب; خبر مرفوع.'],
  ], { copy: {
    '0:0': 'The families from أفعال القلوب through the ليس-like particles share a name: نواسخ.',
    '0:2': 'نسخ means erase or replace. A ناسخ replaces the ordinary مبتدأ مرفوع + خبر مرفوع pattern with its own government. The resulting construction is called جملة منسوخة.',
    '1:1': 'أفعال القلوب, such as ظنّ and علم, take two منصوب objects. الأفعال الناقصة, such as كان and أصبح, give اسم مرفوع and خبر منصوب. These are two of the five families.',
    '2:0': '<b>Verb-like particles</b>: إنّ، أنّ، كأنّ، لكنّ، لعلّ، ليت, with اسم منصوب and خبر مرفوع.<br><b>Genus لا</b>: the same direction of change.<br><b>ليس-like particles</b>: ما، لا، لات and إنْ in العالية’s usage, with اسم مرفوع and خبر منصوب.',
    '3:1': 'Heart verbs make both objects منصوب. Incomplete verbs change the predicate to نصب, the reverse of the إنّ family’s change to the اسم.',
    '3:2': 'لا لنفي الجنس follows the same case direction as the إنّ family.',
    '3:3': 'ليس-like particles mirror the إنّ family. Identify the family first to decide which element takes نصب.',
  }, tableHeaders: { '3:4': ['Family', 'Examples', 'Case pattern', 'Roles'] },
    tableCopy: { '3:4': { 0: ['أفعال القلوب', 'ظنّ، علم', 'Both objects منصوب.', 'مفعولان'],
      1: ['أفعال ناقصة', 'كان، أصبح', 'اسم مرفوع; خبر منصوب.', 'اسم وخبر'],
      2: ['إنّ family', 'إنّ، أنّ، كأنّ، لكنّ، لعلّ، ليت', 'اسم منصوب; خبر مرفوع.', 'اسم وخبر'],
      3: ['لا لنفي الجنس', 'لا', 'اسم منصوب; خبر مرفوع.', 'اسم وخبر'],
      4: ['ليس-like', 'ما، لا، لات، إنْ in العالية', 'اسم مرفوع; خبر منصوب.', 'اسم وخبر'] } },
    visuals: { '1:0': v('Compare the two verb families', ['ظننت زيدًا قائمًا', 'Two objects'], ['كان زيدٌ قائمًا', 'اسم and خبر']),
      '2:0': v('Opposite case patterns', ['إنّ زيدًا قائمٌ', 'نصب then رفع'], ['ما زيدٌ قائمًا', 'رفع then نصب']) } }),
});
Object.assign(checks, {
  '13/l4': [q('What does لا فاعل شر فائز deny?', ['Success for every member of the category.', 'Success only for a particular enemy.', 'Only past success, never future.', 'Nothing; it is purely structural.'], 'نفي الجنس covers all أفراد.'),
    q('What do the two names highlight?', ['نفي الجنس: sweeping denial. التبرئة: freedom from the predicate.', 'Two identical labels with no distinction.', 'The reverse of those meanings.', 'التبرئة only with a built noun.'], 'One highlights scope, the other the predicative relationship.'),
    q('Why is لا non-governing in بلا حساب?', ['It is inside a prepositional phrase.', 'حساب is مبني.', 'Prayers always block government.', 'It has been repeated.'], 'باء governs the phrase.'),
    q('Why is رجلٌ raised in لا رجل قائما بل رجلان?', ['Only one is denied, so لا works like ليس.', 'رجل is مضاف إليه.', 'There is no predicate.', 'لا has no noun.'], 'The speaker affirms that two are standing.'),
    q('Why is غولٌ raised in لا فيها غول?', ['فيها separates لا from the noun.', 'Only one member is negated.', 'لا works only in poetry.', 'غول is definite with أل.'], 'Look for the separator.'),
    q('What permits إعمال or إهمال in the repeated patterns shown?', ['Repetition with no separator before the eligible noun.', 'Negating only one unit.', 'A preposition before every لا.', 'There is no repetition.'], 'Compare لا رفثَ with لا خوفٌ.')],
  '13/l5': [q('In what two ways do these particles resemble ليس?', ['Negation and entry on a nominal subject-predicate pair.', 'Final fatḥah and جر government.', 'Two objects without negation.', 'Government of present verbs only.'], 'Their case pattern follows the same construction.'),
    q('Why does ما not govern مسيء in ما مسيء من أعتب?', ['The predicate precedes the subject.', 'Added إنْ follows ما.', 'إلا introduces the predicate.', 'A preposition precedes ما.'], 'من أعتب is the subject.'),
    q('Why does رسولٌ stay raised after ما محمد إلا...?', ['إلا creates restriction, breaking the required negative pattern.', 'إلا fronts the predicate.', 'إلا is an added إنْ.', 'إلا occurs only in Tamimi usage.'], 'Messengership is affirmed within the restriction.'),
    q('Why is the اسم of لات omitted in ولات حين مناص?', ['Its time reference supplies the understood الحين.', 'لات cannot have an اسم.', 'All poetic subjects must be omitted.', 'إلا forces the omission.'], 'Its restriction makes the omitted time expression recoverable.'),
    q('What happens to إنْ in restriction such as إن يقولون إلا كذبا?', ['It is non-governing; the following verb has its own عمل.', 'يا makes its government obligatory.', 'Starting poetry always makes it govern.', 'Every dialect unanimously rejects all governing uses.'], 'Do not confuse negative إنْ with a governor of the following verb.')],
  '13/l6': [q('What is a nominal construction called after a ناسخ enters?'),
    q('How do heart verbs and incomplete verbs differ?', ['Two منصوب objects versus اسم مرفوع / خبر منصوب.', 'Both always take two منصوب objects.', 'Heart verbs keep the predicate raised; incomplete verbs lower both.', 'Neither changes case.'], 'Compare ظننت زيدا قائما with كان زيد قائما.'),
    q('What case pattern do the إنّ family and genus لا share?', null, 'They change the اسم to نصب.'),
    q('A particle gives اسم مرفوع and خبر منصوب. Which family is it?', null, 'The question asks for a particle family, not a verb family.')],
});
Object.assign(quizzes, {
  '13/l4': [q('Which family contains genus-negating لا?'), q('What defines لا لنفي الجنس?', ['اسم منصوب, خبر مرفوع, and denial of every member.', 'Government inside جار ومجرور.', 'Prohibition with a jussive verb.', 'Conjunction for correction.']),
    q('Why is it also called لا التبرئة?', ['It frees the subject from the predicate’s description.', 'An extra لام always precedes it.', 'It occurs only in formal acquittals.', 'It denies only one member.']),
    q('Why does لا not govern in بلا حساب?'), q('Why the ليس pattern in لا رجل قائما بل رجلان?', ['Only the unit “one” is denied.', 'A separator precedes رجل.', 'لا has been repeated.', 'There is no predicate.']),
    q('What is allowed with repeated لا and no separator before its eligible noun?')],
  '13/l5': [q('What case pattern do ليس-like particles govern?'), q('What is the first condition for ما الحجازية?'),
    q('Why does إلا block ما’s operation here?', ['Restriction breaks the required negative pattern.', 'إلا fronts the predicate.', 'إلا is an added إنْ.', 'إلا occurs only in poetry.']),
    q('Where is ليس-like لا chiefly attested?'), q('What does لات negate?'), q('Which fourth particle is associated here with العالية’s dialect?')],
  '13/l6': [q('What does نواسخ mean in this discussion?', ['Governors changing a nominal pair; نسخ means erase/replace.', 'Verbs restricted to one form.', 'Particles making present verbs jussive.', 'Nouns barred from tanwin.']),
    q('Which family takes two منصوب objects?'), q('What does كان’s family do?', ['اسم مرفوع; خبر منصوب.', 'اسم منصوب; خبر مرفوع.', 'Both منصوب.', 'Both unchanged.']),
    q('Which family shares genus لا’s case direction?'), q('Which family is mirrored by the ليس-like particles?'), q('How many ناسخ families are compared?')],
});
