import { card as c, rows as r, labelled as l, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '08/l1': plan(32, 'Verbs of Hope', [
    [c('Hope expressed through a ناقص verb', 0, 1, 2, 3)],
    [c('Hoping for good or fearing harm', 0, r(1, 0, 1), 2), c('عسى can give a reason', r(1, 2))],
    [c('Nearness distinguishes عسى from لعلّ', 0, 1, 2)],
    [c('Certainty and the addressee’s hope', 0, 1, 2)],
    [c('اخلولق: hope for what is fitting', 0, 1, 2, 3), c('حرى: becoming worthy', 4, 5, 6, 7)],
    [c('Why أن fits an outcome still hoped for', 0, 1, 2), c('Hope verbs can also be تامة', 3, 4, 5)],
  ], [
    ['The three verbs', 'عسى، اخلولق، حرى express hope. The last two concern what is fitting.'],
    ['عسى', 'Hope, apprehension or a reason, with nearness beyond لعلّ.'],
    ['Attribution to Allah', 'Usually certainty; the مخاطب carries the hope and encouragement.'],
    ['أن and government', 'أن is frequent with عسى, required with the other two. Complete uses have فاعل.'],
  ], { copy: {
    '0:0': 'The ناقص families continue beyond كان وأخواتها. عسى، اخلولق and حرى express رجاء, hope or expectation.',
    '0:3': '“Perhaps he will benefit us, or we may adopt him.” Asiya, Pharaoh’s wife, speaks of the infant Musa drawn from the river.',
    '1:0': 'عسى adds مقاربة: the outcome is near. It has three senses.',
    '2:1': 'Both عسى and لعلّ carry ترجي, or إشفاق for a disliked outcome.',
    '2:2': 'عسى also marks nearness. لعلّ alone says nothing about timing.',
    '3:2': 'When attributed to Allah, عسى usually names a certain outcome. His knowledge does not await events. The رجاء belongs to the مخاطب: the Prophet ﷺ is encouraged to persevere toward the promised مقام.',
    '4:1': '“The Muslims became worthy to maintain prayer.” Recorded in grammar books, اخلولق has no Quranic occurrence and is rare in literature.',
    '4:3': 'خليق means fitting or worthy of one’s character. اخلولق hopes for what befits; it never conveys إشفاق.',
    '4:7': 'حرى, from صار حريا, is close to اخلولق in meaning and likewise rare.',
    '5:1': 'A bare مضارع allows present or future. أن fixes futurity, with a delay before occurrence: one does not hope for what already holds.',
    '5:3': 'Like كان, these verbs can be تامة: a single فاعل suffices, without separate اسم and خبر.',
    '5:4': 'Compare عسى ربك أن يبعثك with عسى أن يبعثك ربك. The meaning remains; the analysis differs.',
  }, boxCopy: { '1:2': ['A disliked outcome gives إشفاق, apprehension, rather than a wish for it.'] }, tableCopy: {
    '1:1': { 0: ['الترجي في المحبوب', 'Hope for good.', '﴿عَسَى اللهُ أَنْ يَعْفُوَ عَنْهُمْ﴾: perhaps Allah will pardon them.'],
      1: ['الإشفاق من المكروه', 'Concern about harm.', '﴿فَهَلْ عَسَيْتُمْ إِنْ تَوَلَّيْتُمْ أَنْ تُفْسِدُوا فِي الْأَرْضِ﴾: would you corrupt the earth if you turned away?'] },
    '5:5': { 0: ['ناقصة', 'فعل ناقص', 'رَبُّكَ: اسم عسى', 'أَنْ يَبْعَثَكَ مَقَامًا مَحْمُودًا: مؤول في محل نصب خبر'],
      1: ['تامة', 'فعل تام', 'أن-clause: فاعل', 'أَنْ يَبْعَثَكَ رَبُّكَ مَقَامًا مَحْمُودًا: مؤول في محل رفع'] },
  }, visuals: { '2:0': v('What does the word add?', ['عسى', 'Hope or fear, with nearness'], ['لعلّ', 'Hope or fear, without timing']) } }),
  '08/l2': plan(33, 'Verbs of Nearness', [
    [c('An action close to happening', 0, 1, 2, 3)],
    [c('Actual nearness differs from hope', 0, 1), c('Compare كاد, عسى and لعلّ', 2)],
    [c('Affirmative كاد: near, but not done', 0, 1, 2, 3)],
    [c('Negated كاد: not even near', 0, 1, 2, 3), c('Initial inability and eventual action', 4, 5, 6),
      c('The beginning need not be the ending', 7, 8)],
    [c('Two further verbs of nearness', 0, 1, 2, 3)],
    [c('أن marks distance from occurrence', 0, 1, 2), c('Compare four degrees of nearness', 3),
      c('Omit خبر when context supplies it', 4, 5, 6), c('Which verbs form a مضارع?', 7, 8), c('See يكاد working in a sentence', 9, 10)],
  ], [
    ['The three verbs', 'كاد، كرب، أوشك report actual nearness; عسى expresses hope.'],
    ['Affirmative and negative', 'كاد: near but not done. Negated كاد: not even near at first.'],
    ['Read the surrounding words', 'Other wording can establish eventual action or supply an omitted خبر.'],
    ['أن and tense', 'أن is frequent with أوشك, rare with كاد and كرب. Only كاد and أوشك form مضارع.'],
  ], { copy: {
    '0:0': 'كاد، كرب and أوشك form the third ناقص family, أفعال المقاربة.',
    '0:3': '“They were about to kill me.” Harun عليه السلام speaks to his brother Musa.',
    '1:1': 'Both point toward a near outcome. عسى expresses hope and leaves fulfilment open. كاد reports the actual nearness as fact, whether or not the act eventually follows.',
    '2:1': 'Affirmative كاد shows non-occurrence alongside nearness.',
    '2:3': 'Harun was not killed, but his people came close to killing him.',
    '3:1': 'لا يكاد and لم يكد deny both occurrence and nearness. This is stronger than simply denying the act.',
    '3:3': '“He could hardly see it.” In ظلمات بعضها فوق بعض إذا أخرج يده لم يكد يراها, the darkness of disbelief leaves him not even close to seeing his outstretched hand.',
    '3:5': '“Given pus to drink, gulping it, hardly able to swallow.” At first he cannot come close to swallowing. يتجرعه establishes that severe thirst eventually drives him to gulp it.',
    '3:8': '“They slaughtered it, though they nearly had not.” Banu Israel began with repeated objections. ما كادوا describes that beginning; فذبحوها establishes their eventual action.',
    '5:1': 'أن marks future and adds بُعد. كاد is very close to occurrence, so its خبر usually lacks أن.',
    '5:2': 'أوشك is less immediate and more often takes أن. Hope is further from occurrence, so أفعال الرجاء take it most consistently.',
    '5:6': '“Who hastens errs, or comes close.” Restore أو كاد أن يخطئ: أخطأ supplies the omitted خبر.',
    '5:10': '“Lightning almost snatches their sight.” يكاد is a functioning مضارع, unlike the verbs fixed to ماضي.',
  }, visuals: { '1:0': v('Different assertions', ['عسى', 'A hope left open'], ['كاد', 'Nearness reported as fact']) } }),
};

Object.assign(plans, {
  '08/l3': plan(34, 'Beginning an Action', [
    [c('The action starts now', 0, 1, 2, 3)],
    [c('A productive group, not a closed list', 0, 1)],
    [c('Past verb, present-tense خبر, no أن', 0, 1, 2)],
    [c('Three groups under one name', 0, 1, 2)],
    [c('An omitted verb leaves its مصدر', 0, 1, 2, 3), c('Analyse طفق مسحا', 4), c('The مصدر strengthens immediacy', 5)],
  ], [
    ['شروع', 'جعل، أخذ، طفق، علق، أنشأ mark an action’s beginning.'],
    ['قياسي', 'Verbs meaning “begin” can share this عمل; membership is not a closed list.'],
    ['Forms', 'Past verb; a مضارع clause as خبر, without future-marking أن.'],
    ['Ellipsis', 'In طفق مسحا, understand يمسح; مسحا is its مفعول مطلق.'],
  ], { copy: {
    '0:0': 'The fourth and last ناقص family marks beginning: جعل، أخذ، طفق، علق and أنشأ.',
    '0:3': 'Adam and Hawwa عليهما السلام began covering themselves with Paradise’s leaves.',
    '1:1': 'رجاء and مقاربة have attested, fixed membership. شروع is قياسي: any verb meaning “begin doing” can work this way. It accompanies السماعي because it shares the اسم-and-خبر عمل, not a fixed list.',
    '2:1': 'The verb itself is past, not يجعل or يطفق in this sense. Its خبر is a مضارع clause without أن.',
    '3:1': 'The umbrella label varies by book; the three groups and their rules remain the same.',
    '4:3': 'The hidden اسم, هو, refers to Sulayman. Restore طفق يمسح مسحا: the omitted يمسح governs مسحا as مفعول مطلق.',
  }, boxCopy: { '2:2': ['أن marks future. شروع begins at the moment named by the past verb; أن would contradict that immediacy.'],
    '3:0': ['قد تُجمع عسى وكاد وطفق وأخواتها باسم أفعال المقاربة.'],
    '4:5': ['يمسح allows present or future. مسحا is a مصدر without tense.', 'Omitting the verb removes its possible future reading and stresses an immediate beginning.'] },
    visuals: { '4:2': v('What the ellipsis leaves', ['يَمْسَحُ', 'A possible future reading'], ['مَسْحًا', 'A مصدر, without tense']) } }),
  '08/l4': plan(35, 'Praise and Blame', [
    [c('Praise or blame with فاعل and مخصوص', 0, 1, 2), c('مخصوص is its function, مبتدأ its analysis', 3)],
    [c('The general category and the singled-out example', 0, 1, 2), c('The root of نعم and the form نعمّا', 3, 4)],
    [c('حبذا expresses praise', 0, 1), c('Hardship behind the blame in بئس', 2, 3, 4, 5), c('Harm behind the blame in ساء', 6, 7), c('لا حبذا expresses blame', 8, 9)],
    [c('Fixed verbs with possible feminine تاء', 0, 1), c('Praise through the pattern فَعُلَ', 2, 3, 4)],
    [c('Feminine فاعل allows either verb form', 0, 1, 2, 3), c('A feminine مخصوص also allows تاء', 4, 5)],
    [c('Two ways to use لام الجنس', 0, r(1, 0, 1), 2), c('A hidden فاعل explained by تمييز', r(1, 2), 3, 4)],
  ], [
    ['Five forms', 'نعم، حبذا praise; بئس، ساء، لا حبذا blame.'],
    ['Raised terms', 'فاعل and مخصوص; the latter is analysed as مبتدأ مؤخر.'],
    ['Verb forms', 'Fixed verbs, with optional تاء if فاعل or مخصوص is feminine. فَعُلَ also carries praise.'],
    ['فاعل', 'With لام الجنس, added to such a noun, or hidden and explained by تمييز.'],
  ], { copy: {
    '0:0': 'The سماعي verbs of praise and blame raise فاعل and مخصوص, the particular thing praised or blamed, rather than a ناقص اسم-and-خبر pair.',
    '0:2': 'Five forms: نعم، حبذا، بئس، ساء and لا حبذا.',
    '1:4': 'نعم comes from نعم, receiving a نعمة. The same root also gives نِعِمَ, often joined to ما by إدغام: ﴿فَنِعِمَّا هِيَ﴾.',
    '2:3': 'بئس comes from بئس: falling into poverty, hardship and severe need.',
    '2:7': 'ساء comes from ساءه شيء, something causing harm or displeasure.',
    '3:1': 'These five do not conjugate through tenses. Only feminine تاء attaches.',
    '3:4': 'حسن يحسن already belongs to باب كرم. كتب يكتب is باب نصر, “write”; converting it to كَتُبَ turns writing into praise.',
    '4:1': 'Either a feminine فاعل or a feminine مخصوص allows تاء to be added or omitted.',
    '4:3': 'Both say Fatima is an excellent woman.',
    '4:5': '“Excellent as a reward is Paradise.” جزاء, the فاعل, is masculine; الجنة, the مخصوص, is feminine. Either feminine term permits تاء. If both are masculine, omit it.',
    '5:2': 'العبد bears لام الجنس itself. أجر has no لام but is مضاف to العاملين, which does.',
    '5:4': 'Begin with ساءت المصير جهنم: المصير is فاعل and جهنم مخصوص. Convert المصير to منصوب تمييز, مصيرا, and put hidden مبهم هي in the فاعل’s place.',
  }, boxCopy: { '0:3': ['مخصوص names the second مرفوع’s function, but standard المرفوعات lists call it مبتدأ مؤخر.', 'The books treat the praise/blame verb as عامل for both. This naming inconsistency does not alter the analysis.'] },
    tableCopy: { '1:2': { 0: ['نعم: فعل المدح', 'دار المتقين: فاعل', 'جنات عدن: مخصوص'] } },
    visuals: { '0:1': v('Two names, different purposes', ['مخصوص', 'The thing singled out'], ['مبتدأ مؤخر', 'Its syntactic analysis']) } }),
});

Object.assign(plans, {
  '08/l5': plan(36, 'Further Patterns of Praise', [
    [c('ما after نعم or بئس is a noun', 0, 1, 3, 4), c('Definite فاعل or indefinite تمييز', 2)],
    [c('When a clause follows ما', 0, 1, 2, 3)],
    [c('Context can supply the مخصوص', 0, 1, 2, 3)],
    [c('Derived حال or plain-noun تمييز', 0, 1, 2), c('تمييز introduced with مِن', 3, 4, 5)],
    [c('يا adds force to حبذا', 0, 1, 2), c('The fixed form of ذا', 3, 4, 5, 6)],
  ], [
    ['ما', 'A noun, never negative here: فاعل or تمييز according to its reading.'],
    ['A following clause', 'صلة after موصول ما; نعت after نكرة ما. مخصوص can be omitted.'],
    ['منصوب with حبذا', 'مشتق gives حال; جامد gives تمييز. It may precede or follow مخصوص.'],
    ['Other forms', 'تمييز can take مِن; يا adds force. ذا stays مفرد مذكر.'],
  ], { copy: {
    '0:1': 'ما after نعم or بئس is always اسم here, never negative. Its analysis depends on what follows.',
    '0:4': '“How excellent a thing it is!” Definite ما means الشيء and is فاعل. تامة means complete without a صلة, unlike موصولة. هي refers to الصدقات and is مخصوص in both readings.',
    '2:2': '“Excellent Protector and Helper!” لفظ الجلالة is the understood مخصوص in both clauses. Earlier context identifies Him; omission avoids repetition and gives Quranic brevity.',
    '3:1': 'A منصوب can precede or follow مخصوص حبذا or لا حبذا. Its type determines its role.',
    '3:5': '“What a good teacher Zaynab is!” مِن introduces the تمييز معلمة instead of a plain منصوب form.',
    '4:2': '“We are neighbouring girls of Banu al-Najjar; what a good neighbour Muhammad ﷺ is!” Prefixing يا intensifies حبذا’s sense of wonder.',
    '4:5': '“Excellent men, the Ansar!” “An excellent daughter, Fatima!”',
  }, boxCopy: { '4:6': ['ذا does not agree with the following تمييز or مخصوص: masculine or feminine, singular or plural.'] },
    tableCopy: { '3:2': {
      0: ['مشتق', 'حال', 'حبذا راكبا زيد / حبذا زيد راكبا: good while riding.'],
      1: ['جامد', 'تمييز', 'حبذا رجلا زيد / حبذا زيد رجلا: a good man.'],
    } } }),
  '08/l6': plan(37, 'Patterns of Exclamation', [
    [c('Two ways to express wonder', 0, 1, 2)],
    [c('Two readings of ما أفعله', 0, 1, 2, 3)],
    [c('Why أفعل به adds باء', 0, 1, 2, 3)],
    [c('Exclamatory force from added باء', 0, 1, 2, 3)],
    [c('Exclamation through فَعُلَ', 0, 1), c('باء can also enter this فاعل', 2, 3, 4), c('A plain three-letter source verb', 5, 6)],
    [c('Keep the middle weak letter unchanged', 0, 1), c('Different إدغام rules in the two forms', 2, 3),
      c('سماعي wonder comes from context', 4, r(5, 0, 1)), c('Calling out to glad tidings', r(5, 2), 6)],
  ], [
    ['قياسي and سماعي', 'Productive patterns express wonder directly; attested expressions gain it from context.'],
    ['Patterns', 'ما أفعله، أفعل به and فَعُلَ. Added باء can strengthen the exclamation.'],
    ['Root and weak letter', 'Use ثلاثي مجرد; do not apply إعلال to the middle root letter.'],
    ['إدغام', 'أبرر به keeps both letters; ما أبرّه merges them.'],
  ], { copy: {
    '0:0': 'After hope, nearness, beginning, praise and blame, the survey ends with wonder: صيغ التعجب.',
    '0:2': 'قياسي gives productive fixed patterns; سماعي gives established expressions.',
    '1:3': 'Interrogative ما is مبتدأ with أصبرهم as خبر: “What made them so patient?” As نكرة موصوفة, it means شيء عظيم: “Something immense made them patient.” Both yield “How patient they are!”',
    '2:1': '“How well they hear and see!” أبصر shares أسمع’s بهم without repeating it.',
    '2:3': 'The original أفعل, باب إفعال, takes an أمر shape. Ordinary أمر takes a pronoun as subject: اضرب يا زيد, not اضرب زيدٌ. Added باء allows the visible subject here: أفعل + بِ الزائدة + هم الفاعل.',
    '3:1': 'This added باء can bring تعجب beyond أفعل به.',
    '3:3': '“How sufficient We are as reckoners!” “Zayd is quite sufficient for you!” باء adds emphasis approaching تعجب to plain sufficiency.',
    '4:1': '“What a monstrous word leaves their mouths!” كبر is genuinely فَعُلَ, “be great or serious”. As in praise and blame, the pattern may be original or reached by conversion.',
    '4:4': '“How excellent Zayd is!” Added باء may enter the فاعل of this third pattern too.',
    '4:6': 'Direct formation requires ثلاثي مجرد: three root letters, no added letters, not four or more roots.',
    '5:1': 'Ordinary إعلال would turn و into ا: أطول becomes أطال. Exclamation blocks it: ما أطوله and أطول به, not ما أطاله or أطل به.',
    '5:3': 'أبرر به keeps the two ر letters apart. ما أبرّه allows normal إدغام.',
    '5:4': 'The سماعي expressions are established usages. Their wonder is بالقرينة, contextual, not coined into a special form.',
  }, boxCopy: { '2:2': ['أفعل به أصله أفعلَ، حُوّل إلى الأمر، وزيدت الباء في الفاعل؛ لا يُسند الأمر إلى اسم ظاهر.'],
    '5:6': ['سبحان الله is a مصدر of glorification. كيف normally asks manner; here it expresses astonishment, not طلب العلم.', 'يا بشرى addresses “glad tidings” like a person. In all three, wonder comes بالقرينة, not بالوضع.'] } }),
});

export const checks = {
  '08/l1': [q('Which three verbs express رجاء?', null, 'Recall the family after كان وأخواتها.'),
    q('Which sense of عسى fits the disliked outcome أن تفسدوا في الأرض?', null, 'Is the speaker wishing for corruption, or apprehensive about it?'),
    q('What does عسى add beyond لعلّ?', ['مقاربة: the outcome is near.', 'تعليل: a reason.', 'Absolute certainty in every use.', 'Only a distant future.'], 'Compare their timing.'),
    q('Whose hope is expressed in عسى أن يبعثك ربك مقاما محمودا?', ['The مخاطب’s; the promised outcome is certain.', 'Allah’s uncertainty about what will happen.', 'Nobody’s; there is no رجاء.', 'Asiya’s hope for infant Musa.'], 'The wording encourages the addressee.'),
    q('Which sense belongs to both اخلولق and حرى?', ['Hope for what is fitting, never إشفاق.', 'Only apprehension, never hope.', 'Only giving a reason.', 'Neither carries hope.'], 'Recall خليق and حريّ.'),
    q('Do the ناقص and تام analyses of عسى change the intended meaning?', ['No; the grammatical analysis differs.', 'Yes; only ناقص is correct.', 'Yes; تام denies the outcome.', 'No, but only when attributed to Allah.'], 'Compare the complete أن-clause with separate اسم and خبر.')],
  '08/l2': [q('Which three verbs report nearness?', null, 'Distinguish مقاربة from رجاء and شروع.'),
    q('What does على سبيل الحصول mean for كاد?', ['It reports actual nearness as fact.', 'It expresses uncertain hope like عسى.', 'It only names disliked outcomes.', 'It never concerns an act that later happened.'], 'The assertion concerns nearness itself.'),
    q('What happened in وكادوا يقتلونني?', ['They did not kill him, but came close.', 'They killed him.', 'They never came close.', 'Nothing is known, as with open hope.'], 'The كاد is affirmative.'),
    q('How can فذبحوها and وما كادوا يفعلون both be true?', ['Negated كاد describes the beginning, not the ending.', 'The verse contradicts itself.', 'Negated كاد never denies occurrence.', 'فذبحوها is unrelated to the event.'], 'Track their initial objections and eventual act.'),
    q('What does كرب المؤذن يقيم mean?', ['He was about to begin the إقامة.', 'He had finished the إقامة.', 'He refused the إقامة.', 'He hoped to give the إقامة.'], 'كرب reports nearness.'),
    q('Which hope or nearness verbs have working مضارع forms?', ['كاد and أوشك: يكاد and يوشك.', 'عسى and اخلولق.', 'كرب and حرى.', 'All of them.'], 'Most remain fixed to the past.')],
  '08/l3': [q('Which verb marks beginning an action?', null, 'Find the شروع family member.'),
    q('What does قياسية mean for أفعال الشروع?', ['Any verb meaning “begin doing” can function this way.', 'Another fixed, memorised list.', 'They cannot have ناقص government.', 'They are borrowed from praise and blame.'], 'Membership follows meaning rather than a closed list.'),
    q('Why does a شروع verb’s مضارع خبر exclude أن?', ['Future marking contradicts immediate beginning.', 'أن cannot follow any ناقص verb.', 'شروع never takes a مضارع clause.', 'أن is optional, just like عسى.'], 'Relate أن to time.'),
    q('Does grouping hope, nearness and beginning as أفعال المقاربة change their rules?', ['No; only the umbrella label differs.', 'Yes; طفق loses its beginning sense.', 'Yes; عسى becomes قياسي.', 'No, but every book rejects that label.'], 'A shared heading need not erase distinctions.'),
    q('What is مسحا when يمسح is omitted in فطفق مسحا?', null, 'Restore طفق يمسح مسحا.')],
  '08/l4': [q('Which two terms do praise and blame verbs raise?', null, 'Distinguish these from ناقص اسم and خبر.'),
    q('What is جنات عدن in ولنعم دار المتقين جنات عدن?', null, 'دار المتقين supplies the general category.'),
    q('Which pair expresses blame in بئس الشراب وساءت مرتفقا?', null, 'Identify the two verbs in the example.'),
    q('What does changing كَتَبَ to كَتُبَ do?', null, 'Compare an act of writing with a fine writer.'),
    q('Why is تاء allowed in نعمت جزاء المتقين الجنة?', ['الجنة, the مخصوص, is feminine.', 'نعم always requires تاء.', 'جزاء is secretly feminine.', 'This تاء is unrelated to gender.'], 'Either raised term can license feminine agreement.'),
    q('What underlies وساءت مصيرا in the given analysis?', ['ساءت المصير جهنم; فاعل becomes تمييز.', 'ساء المصير only, with no مخصوص.', 'جهنم is فاعل throughout.', 'There is no underlying analysis.'], 'A hidden هي replaces المصير as فاعل.')],
  '08/l5': [q('What is the second reading of ما in فنعمّا هي?', ['Indefinite تمييز; فاعل is hidden.', 'Negative ما, denying praise.', 'مخصوص, leaving هي without a role.', 'ما is omitted entirely.'], 'Compare الشيء with شيء.'),
    q('What happens to مخصوص in both readings of نعمّا يعظكم به?', null, 'The readings differ in ما and the following clause.'),
    q('Is omitting مخصوص common in Quranic praise constructions?', ['More common than stating it.', 'A rare exception.', 'Never permitted.', 'Only permitted for feminine مخصوص.'], 'Context often supplies the referent.'),
    q('What is derived راكبا in حبذا راكبا زيد?', null, 'Distinguish مشتق from جامد.'),
    q('What form does ذا retain with الأنصار and فاطمة?', ['Singular masculine in both.', 'It agrees in number and gender.', 'Always plural masculine.', 'Dual when the مخصوص is plural.'], 'This part of حبذا is fixed.')],
  '08/l6': [q('What are the two kinds of exclamation expression?', ['Productive قياسي and attested سماعي.', 'فاعل and مفعول.', 'مدح and ذم.', 'رجاء and مقاربة.'], 'Distinguish a pattern from a contextual expression.'),
    q('What does ما mean on the نكرة موصوفة reading of ما أصبرهم?', ['شيء عظيم, something immense.', 'An interrogative “what”.', 'The مخصوص of exclamation.', 'A meaningless question particle.'], 'Compare the two readings of ما.'),
    q('What allows the visible subject after the أمر-shaped أفعل?', null, 'Notice the extra element in أفعل به.'),
    q('What does added باء contribute in وكفى بنا حاسبين?', ['Stronger emphasis approaching تعجب.', 'Negation of sufficiency.', 'A shift from wonder to negation.', 'No contribution.'], 'Compare it with plain sufficiency.'),
    q('What source verb allows direct صيغة التعجب formation?', null, 'Count root letters and exclude additions.'),
    q('Where does wonder come from in سبحان الله and كيف?', ['Context, بالقرينة.', 'Their coined primary purpose, بالوضع.', 'They never express wonder.', 'Only كيف can express it.'], 'Their ordinary grammatical purposes remain distinct.')],
};
export const quizzes = {
  '08/l1': [q('Which verbs form أفعال الرجاء?'), q('Which sense appears in عسى الله أن يعفو عنهم?'),
    q('What does عسى add beyond لعلّ?', ['Nearness of the outcome.', 'Certainty in every use.', 'A reason, which لعلّ lacks.', 'Calling an addressee.']),
    q('When عسى is attributed to Allah, what usually follows?', ['Certain outcome; hope belongs to the مخاطب.', 'Uncertainty in Allah’s knowledge.', 'It cannot be attributed to Allah.', 'Certainty only for disliked outcomes.']),
    q('What does اخلولق المسلمون أن يحافظوا على الصلاة mean?'), q('How does أن occur with the three hope verbs?')],
  '08/l2': [q('Which verbs form أفعال المقاربة?'), q('What distinguishes كاد from عسى?', ['كاد reports actual nearness; عسى expresses hope.', 'Both always express identical certainty.', 'كاد never concerns the past.', 'عسى always expresses certainty.']),
    q('What does affirmative وكادوا يقتلونني report?', ['They did not kill him, but came close.', 'They killed him.', 'They never came close.', 'No implication about the event.']),
    q('What does لم يكد يراها add beyond لم يرها?', ['Stronger negation: not even close to seeing.', 'A weaker negation.', 'He saw it immediately.', 'No added force.']),
    q('Why can من عجل أخطأ أو كاد omit خبر?', ['أخطأ makes أن يخطئ understood.', 'خبر can never be omitted.', 'كاد never needs خبر.', 'Only affirmative كاد allows omission.']),
    q('Which pair has مضارع forms?', ['كاد and أوشك.', 'عسى and كرب.', 'اخلولق and حرى.', 'All of them.'])],
  '08/l3': [q('Which is NOT a verb of beginning?'), q('What makes أفعال الشروع قياسية?', ['Any verb meaning “begin” can serve this function.', 'Membership is a fixed attested list.', 'They cannot have ناقص government.', 'They occur only in مضارع.']),
    q('Why is أن excluded from their خبر?', ['Future marking contradicts immediate beginning.', 'أن cannot follow any ناقص verb.', 'Their خبر is never a verb clause.', 'It is optional but rare.']),
    q('What kind of قرب does طفق contribute under the umbrella heading?'),
    q('What is مسحا after omitted يمسح?', ['The omitted verb’s مفعول مطلق.', 'طفق’s فاعل.', 'مضاف إليه.', 'تمييز converted from فاعل.']),
    q('What does وطفقا يخصفان describe about Adam and Hawwa?')],
  '08/l4': [q('Which two raised terms belong to praise and blame?'), q('Which five forms make up the group?', ['نعم، حبذا، بئس، ساء، لا حبذا.', 'نعم، بئس، ساء only.', 'عسى، اخلولق، حرى، كاد، كرب.', 'نعم، حبذا، بئس، حرى.']),
    q('What is دار المتقين in ولنعم دار المتقين جنات عدن?'), q('What does كَتُبَ زيد express?'),
    q('When may feminine تاء be added?'), q('Which forms can the فاعل take?', ['لام الجنس, إضافة to it, or hidden pronoun with تمييز.', 'Always a visible pronoun.', 'Always مضاف إليه of the مخصوص.', 'Always indefinite without لام.'])],
  '08/l5': [q('Can ما after نعم or بئس be negative here?', ['No; it is a noun.', 'Yes; always negative.', 'Only before a مفرد.', 'Only before a clause.']),
    q('If ما in فنعمّا هي means الشيء, what is its role?'), q('If ما is موصول in نعمّا يعظكم به, what is its role?'),
    q('Why omit مخصوص in نعم المولى ونعم النصير?', ['Context identifies Him; omission avoids repetition.', 'It can never be stated in the Quran.', 'Omission changes the meaning.', 'نعم never takes مخصوص.']),
    q('What is جامد رجلا in حبذا رجلا زيد?'), q('What form does ذا retain with plural or feminine مخصوص?', ['Singular masculine.', 'It agrees with each مخصوص.', 'Dual masculine.', 'It disappears entirely.'])],
  '08/l6': [q('What distinguishes قياسي from سماعي exclamations?', ['A productive pattern versus attested expressions.', 'قياسي is closed; سماعي is productive.', 'They are identical in every respect.', 'قياسي applies only to imperative forms.']),
    q('What is interrogative ما in فما أصبرهم?', ['مبتدأ; أصبرهم is its خبر.', 'فاعل.', 'مخصوص.', 'تمييز explaining a hidden pronoun.']),
    q('Why insert باء before the subject of أفعل به?', ['The imperative shape does not normally take a visible noun subject.', 'Every exclamatory subject needs a preposition.', 'أسمع is ناقص and needs خبر.', 'بهم was already the original verb form.']),
    q('What would كفى state without added باء?', ['Plain sufficiency, without the added emphasis.', 'Exactly the same emphasis.', 'Negation instead of affirmation.', 'A question instead of a statement.']),
    q('What source verb permits direct صيغة التعجب formation?'), q('Where does wonder in سبحان الله or يا come from?', ['Context, بالقرينة.', 'Their coined primary purpose.', 'Neither can express wonder.', 'Formal وضع alone.'])],
};
