import { card as c, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '18/l1': plan(89, 'Reproach and Urging', [
    [c('A missed act or an act still possible?', 0, 1, 2, 3)],
    [c('Compare هلا with past and present', 0, 1, 2), c('The traditional analysis of هلا', 3, p(4, 0)), c('ألّا also reproaches or urges', p(4, 1))],
    [c('A different use of لولا', 0), c('From urging to a challenge', 1, 2, 3, 4)],
    [c('Read the speaker’s relationship', 0, 1, 2), c('Three rhetorical readings', 3, p(4, 0)), c('Keep the two verse contexts distinct', p(4, 1))],
    [c('Condition or reproach?', 0, 1, 2), c('Compare complete constructions', 3)],
    [c('The unfulfilled act is understood', 0, 1, 2)],
  ], [
    ['توبيخ / تحضيض', 'Reproach for a missed act; forceful urging toward action.'],
    ['Time and context', 'Intended time, speaker and audience guide the reading.'],
    ['لولا', 'Conditional use: an existing cause prevents the answer.'],
    ['Other senses', 'Challenge, wishing and astonishment depend on context.'],
  ], { copy: {
    '0:0': 'This particle family can rebuke a missed action or urge someone to act.',
    '0:2': 'توبيخ blames a past mistake. تحضيض presses for an action still possible. Past and present verb forms are useful clues to the intended time.',
    '0:3': 'The source groups five forms together. Context remains essential: a past form can express a request about the future, so written tense alone is not an absolute test.',
    '1:0': 'هلا and ألّا illustrate the same contrast.',
    '1:2': 'هلا صليت: “Why did you not pray?”, reproaching a missed prayer. هلا تصلي: “Why do you not pray?”, urging prayer now or later.',
    '2:0': 'Compare لولا صمت, reproaching a missed fast, with لولا تصوم, urging fasting. This is not conditional لولا in لولا فضل الله عليكم: the spelling is shared, the construction differs.',
    '2:2': 'The basic urging can become تعجيز: a demand intended to expose supposed inability rather than sincerely seek action.',
    '2:4': '“Why does Allah not speak to us, or a sign come to us?” In the challenging interpretation taught, the disbelievers expect failure. Their assumption does not establish that Allah cannot send a sign.',
    '3:0': 'For a missed act, the source distinguishes three rhetorical situations.',
    '3:2': 'A superior may rebuke: توبيخ, also التغليط والتنديم. A speaker who cannot appropriately rebuke may wish: تمنّ. Speech to a third party may express astonishment: تعجب. These are contextual readings, not fixed rules about social rank.',
    '4:0': 'Use construction and meaning together to distinguish the two uses.',
    '4:3': 'لولا القرآنُ لما اهتدينا: the Quran exists and prevents lack of guidance, so this is conditional. The source also gives لولا قرأت لفشلت as a reproach, but that wording is not a reliable contrast: لفشلت looks like an answer. Use لولا قرأتَ, “Why did you not read?”, for the reproach. A conditional answer may be understood rather than written, so mere absence of an explicit answer is not decisive.',
    '5:1': '“Why was there no town whose belief benefited it, except Yunus’s people?” The reproach implies failure to believe in time among the towns under discussion. Yunus’s people are the exception. Addressing later listeners adds astonishment at those earlier communities.',
    '5:2': 'كانت has no explicit negator, yet this reproaching use of لولا conveys an unfulfilled act. The negative implication comes from the construction and context.',
  }, copyParts: { '1:4': [
    'The traditional analysis joins interrogative هل to negative لا. A question about an omitted act develops the reproaching or urging force of هلا.',
    'ألّا أنفقت على الفقراء: “Why did you not spend on the poor?” ألّا تنفق على الفقراء: “Why do you not spend on the poor?” The source relates this form to an interrogative hamzah, with the same contrast in intended time.',
  ], '3:4': [
    'The first verse rebukes believers over the slander of Aisha. The second requests a delay. The third expresses astonishment to listeners about past nations that did not humble themselves when punishment came.',
    'لولا أخرتنا إلى أجل قريب belongs to the request concerning fighting in 4:77. The deathbed plea in 63:10 is رب لولا أخرتني إلى أجل قريب, addressed to Allah, not the angel of death. The source combines these contexts; the wishing interpretation must not be used to repeat that confusion.',
  ] }, boxCopy: {
    '0:1': ['التوبيخ لوم على فائت؛ والتحضيض طلب الفعل بشدة.'],
    '2:1': ['التحضيض طلب، وقد يستعمل للتعجيز.'],
    '3:1': ['بحسب المقام: توبيخ، أو تمنّ، أو تعجب.'],
    '4:1': ['الشرطية: وجود يمنع الجواب. التوبيخ: لوم على فعل لم يقع.'],
    '4:2': ['الجواب قرينة للشرط، وقد يحذف لدليل.'],
  }, visuals: { '1:2': v('Same form, different intended time', ['ألّا أنفقت', 'Reproach'], ['ألّا تنفق', 'Urging']) } }),
  '18/l2': plan(90, 'Drawing Attention', [
    [c('Three attention particles', 0, 1, 2)],
    [c('ألا opens an emphatic statement', 0, 1), c('Emphasis inside the statement', 2, 3), c('ألا before a verbal clause', 4, 5)],
    [c('Attention or invitation?', 0, 1, 2), c('The invitation in ألا تأكلون', 3, 4)],
    [c('أما often precedes an oath', 0, 1, 2, 3), c('أما can lose its initial hamzah', 4, 5)],
    [c('Four positions for ها', 0, 1), c('ها with demonstratives and pronouns', 2, 3)],
    [c('ها with قد and يا', 0, 1, 2, 3)],
  ], [
    ['ألا / أما / ها', 'Draw the listener’s attention. Notice the absence of shaddah in ألا and أما.'],
    ['ألا', 'Can open nominal or verbal clauses; distinguish it from invitation or urging.'],
    ['أما', 'Often before an oath; its hamzah may be omitted.'],
    ['ها', 'With near demonstratives, raised pronouns, قد + past, and vocative أيّ or أيّة.'],
  ], { copy: {
    '0:0': 'These particles alert the listener before a statement.',
    '0:2': 'ألا differs from doubled ألّا; أما differs from conditional أمّا. The third form is ها. Each has characteristic constructions.',
    '1:1': 'ألا إن نصر الله قريب calls attention: “Surely Allah’s help is near.” The following إنّ supplies its own emphasis.',
    '1:3': 'إنّ emphasizes the statement. In the analysis shown, هم is ضمير فصل, distinguishing and emphasizing the predicate المفسدون. Another analysis of هم as a second مبتدأ is possible; use the displayed analysis for practice.',
    '1:5': 'ألا حين يستغشون ثيابهم يعلم ما يسرون وما يعلنون: “When they cover themselves with clothing, He knows what they conceal and reveal.” ألا introduces the verbal clause يعلم, as well as nominal clauses.',
    '2:0': 'ألا also offers or urges: عرض is gentle, تحضيض forceful.',
    '2:2': 'Removing attention-giving ألا preserves the core assertion but loses emphasis. Removing inviting ألا can leave a grammatical assertion while losing the invitation. This is a meaning test, not a claim that تأكلون is ungrammatical.',
    '2:4': 'إنهم هم المفسدون remains an assertion without ألا. In ألا تأكلون, “Will you not eat?”, removing ألا leaves “you eat”. The words remain grammatical; the intended invitation disappears.',
    '3:1': 'Unstressed أما, unlike conditional أمّا, commonly introduces an oath.',
    '3:3': '“Now, by the One who makes weep and laugh, gives death and life, whose command is the command...” أما draws attention to the chain of oaths.',
    '3:5': 'In the cited poetic analysis, ما ترى الدهر قد أباد معدّا وأباد السراة من عدنان is understood as أما ترى: “Do you not see how time destroyed Maadd and Adnan’s nobles?” Context supports an omitted hamzah, rather than treating ما as an ordinary negative or relative.',
    '4:1': 'Learn the four environments together, then recognize them in examples.',
    '4:3': 'هؤلاء قومنا: “These are our people.” ها precedes the near demonstrative أولاء. ها أنتم هؤلاء: “Here you are...” ها precedes the raised pronoun أنتم.',
    '5:0': 'The final two positions complete the comparison.',
    '5:2': 'ها draws attention to confirmed forgiveness; قد with the past adds تحقيق.',
    '5:3': 'The ordinary vocative bridges يا and an أل-noun with أيّ or feminine أيّة, adding ها. Compare يا أيها and يا أيتها. Exceptions such as يا الله have separate rules.',
  }, boxCopy: { '0:1': ['أحرف التنبيه: ألا، أما، ها.'], '2:1': ['حذف ألا يبقي أصل الخبر، لكنه يزيل معنى العرض في ألا تأكلون.'], '4:0': ['ها مع الإشارة، والضمير المرفوع، وقد والماضي، وأيّ أو أيّة في النداء.'] }, analysisPrompt: 'Use the displayed analysis.', analysisItemLabels: {
    'bank-19': { 'حرف تحضيض': 'حرف جر' },
  } }),
  '18/l3': plan(91, 'Particles That Form a مصدر مؤول', [
    [c('A clause fills a noun’s position', 0, 1, 2)],
    [c('Two kinds of ما', 0, 1, 2, 3), c('Distinguish relative ما', 4, 5)],
    [c('لو after ودّ', 0, 1, 2, 3)],
    [c('Equal alternatives, not a question', 0, 1, 2), c('Other مصدر particles govern', 3, 4)],
  ], [
    ['موصول حرفي', 'Particle plus clause is interpreted as a مصدر مؤول.'],
    ['ما المصدرية', 'ظرفية includes duration; غير ظرفية gives an ordinary verbal-noun meaning.'],
    ['لو / همزة التسوية', 'The source adopts their مصدر analyses in the examples.'],
    ['كي، أنْ، أنّ', 'These also form sources but govern mood or case.'],
  ], { copy: {
    '0:0': 'A مصدر particle lets a complete following clause occupy a noun’s grammatical position.',
    '0:2': 'حرف مصدري, موصول حرفي and حرف موصول name this function. Unlike the noun الذي, the connector itself is a particle. This section studies non-governing ما and the adopted مصدر analyses of لو and همزة التسوية.',
    '1:1': 'Does the expression include duration?',
    '1:3': 'ما دمت حيّا = مدّة حياتي, “for my lifetime”: ظرفية, familiar with دام. على ما كذّبوا = على تكذيبهم, “despite their being denied”: غير ظرفية, without duration.',
    '1:5': 'Relative ما needs a عائد, expressed or legitimately omitted, referring back to it. The مصدر reading of ما كذّبوا converts the clause directly into “their being denied”; it does not require a pronoun referring to ما. Mere absence of a visible pronoun is not a universal test.',
    '2:1': 'After ودّ, لو commonly has a مصدر analysis. Conditional analyses are also discussed; practice uses the مصدر account.',
    '2:3': '“They wished you would disbelieve as they did.” كفركم fills ودّوا’s object position; كما كفروا is not a conditional answer here.',
    '3:1': 'همزة التسوية looks like a question marker, but presents alternatives without seeking an answer.',
    '3:2': '“It is the same to them whether you warn them or not.” The مصدر interpretation is إنذارك وعدمه: the coordinated alternatives form the delayed subject of سواء, the fronted predicate. This is the grammatical account adopted here.',
    '3:4': 'كي and أنْ govern a following مضارع in نصب; أنّ gives its اسم نصب and خبر رفع. These governing مصدر particles were studied separately. This section collects the non-governing uses.',
  }, boxCopy: { '0:1': ['أحرف المصدر: موصولات حرفية، أو حروف موصولة.'], '2:2': ['ودّوا لو تكفرون = ودّوا كفركم.'] } }),
  '18/l4': plan(92, 'Negation Without Government', [
    [c('Meaning without case or mood government', 0, 1, 2)],
    [c('ما with past or present verbs', 0, 1), c('The usual present reading of ما', 2, 3)],
    [c('لا normally negates the present', 0, 1), c('لا with past verbs', 2, 3, 4, 5)],
    [c('Negative إنْ with إلا', 0, 1, 2), c('Similar forms can govern elsewhere', 3, 4)],
  ], [
    ['ما، لا، إنْ', 'Non-governing in the uses taught here.'],
    ['ما', 'Negates past or present verbs; الحال is the usual present reading taught.'],
    ['لا + past', 'Repeated negation or a future-oriented supplication are the patterns illustrated.'],
    ['إنْ ... إلا', 'A negative restriction: “nothing but” or “only”.'],
  ], { copy: {
    '0:0': 'These particles negate a statement without assigning case or mood.',
    '0:2': 'Do not confuse them with governing لا النافية للجنس, ما or لا working like ليس, or jussive لمّا. Prohibitive لا is also studied separately: it directs someone not to act, rather than merely reporting a negative fact.',
    '1:1': 'ما قتلوه: “They did not kill him”, past. وما يشعرون: “They do not perceive”, present. ما assigns neither verb جزم nor نصب.',
    '1:3': 'The traditional account gives ما with المضارع a present-time reading here. Treat الحال as the normal reading taught, not an absolute ban on other time references when the wider context supplies them.',
    '2:1': 'وهم لا يؤمنون illustrates the ordinary present-verb construction. Past-form uses follow in two common patterns.',
    '2:3': 'Repeat negation across past verbs, or use a past form for a future-oriented supplication.',
    '2:5': '“He neither believed nor prayed” repeats لا with different verbs. “May Allah not decree it” is a supplication, like لا شلّت يمينه: “May his right hand not be paralysed”.',
    '3:1': 'Negative إنْ differs from conditional إنْ. With إلا it restricts the assertion: “nothing but” or “only”. إلا is frequent, not obligatory with every negative إنْ.',
    '3:2': 'إن أنتم إلا في ضلال كبير: “You are only in great error.” Compare إن أنتم إلا تكذبون and إن أنتم إلا في ضلال مبين. All show negative restriction.',
    '3:4': 'لا النافية للجنس gives its اسم نصب. ما and لا in the ليس pattern raise the subject and give the predicate نصب. لمّا and prohibitive لا give المضارع جزم. Recognize the construction, not just the written particle.',
  }, boxCopy: { '0:1': ['من النفي غير العامل: ما، لا، إنْ.'], '1:2': ['ما مع المضارع للحال في القراءة المعتادة هنا.'], '2:2': ['مع الماضي: تكرار النفي، أو الدعاء ونحوه.'], '3:3': ['هذه الاستعمالات غير عاملة؛ وللنفي والنهي أدوات عاملة.'] }, analysisLabels: { 'ما النافية، تخصص المضارع بالحال': 'ما النافية للحال هنا' } }),
  '18/l5': plan(93, 'Emphatic Particles Called زائدة', [
    [c('زائد does not mean meaningless', 0, 1, 2, 3), c('The alternative name صلة', 4, 5)],
    [c('Emphatic إنْ beside negative ما', 0, 1), c('Four uses of إنْ', 2, 3)],
    [c('أنْ after temporal لمّا', 0, 1, 2, 3), c('Musa: read the actual wording', 4), c('أنْ between an oath and لو', 5, 6)],
    [c('ما after conditions and prepositions', 0, 1), c('Three emphatic ما examples', 2, 3), c('ما need not stop government', 4, 5)],
    [c('لا beside و and after أنْ', 0, 1, 2), c('Repeated negation with و', 3), c('ما منعك ألا تسجد', 4), c('Do not count negatives mechanically', 5, p(6, 0)), c('Return: identify the intended sense', p(6, 1))],
    [c('Two accounts of لا أقسم', 0, 1), c('Both accounts convey emphasis', 2, 3)],
  ], [
    ['زائد / صلة', 'Not required by the core syntax; still contributes to expression and emphasis.'],
    ['إنْ / أنْ', 'إنْ often beside negative ما; أنْ after temporal لمّا or before لو following an oath.'],
    ['ما', 'Can strengthen conditional scope and preserve a preposition’s government.'],
    ['لا', 'Its emphatic and negative analyses depend on the particular construction.'],
  ], { copy: {
    '0:0': 'Study emphatic إنْ، أنْ، ما and لا. Lacking an إعراب position alone does not define زيادة; other particles lack one too.',
    '0:3': 'Core syntax does not require the particle, but removing it can lose emphasis or another expressive contribution. زائد never means purposeless.',
    '0:5': 'The source associates صلة with the Kufans and زائدة with the Basrans. صلة highlights the contribution to eloquence and avoids implying that Quranic wording is purposeless. Treat these as associated terminologies, not an absolute claim about every scholar’s vocabulary.',
    '1:1': 'ما إن أتيت بشيء أنت تكرهه: “I have not at all done anything you dislike.” إنْ reinforces ما’s negation without governing the past verb.',
    '1:3': 'إنْ may be lightened إنّ, conditional, negative, or emphatic زائد. Context and construction distinguish the four; spelling alone does not.',
    '2:1': 'Temporal لمّا means “when”; negative لمّا means “not yet”. The source’s time-gap reading of added أنْ is contextual, not compulsory.',
    '2:3': '“When the bearer of good news arrived.” The source connects أنْ with time passing during the journey.',
    '2:4': 'The first fight in 28:15 says فوكزه موسى فقضى عليه, not لما أراد. The next day’s 28:19 says فلما أن أراد أن يبطش بالذي هو عدو لهما. The source reads hesitation into this added أنْ after the previous day’s death. Keep that as a proposed rhetorical interpretation, not a contrast between two Quran quotations that both say لما أراد.',
    '2:6': 'والله أن لو قمت قمت: “By Allah, had you stood, I would have stood.” أنْ occurs after the oath and before لو, with an emphatic analysis.',
    '3:1': 'With conditional tools, added ما can reinforce general scope, such as “whenever” or “wherever”. With the prepositions listed, it adds emphasis. The underlying tool may already express generality.',
    '3:3': 'إذا ما غضبوا: “When they grow angry, they forgive.” أينما تكونوا: “Wherever you are, death will reach you.” فبما رحمة من الله لنت لهم: “By Allah’s mercy you were gentle with them.”',
    '3:5': 'In فبما رحمة, الباء still gives رحمةٍ جر. This non-cancelling ما differs from الكافّة ما in constructions such as إنّما. Do not extend the rule to every particle called ما.',
    '4:1': 'The first two constructions are illustrated here; oath usage follows.',
    '4:3': 'In ما جاء زيد ولا عمرو, و coordinates and لا reinforces separate negation: neither came. The source contrasts ما جاء زيد وعمرو as allowing a joint reading. That unrepeated wording does not automatically guarantee that either came; context still matters.',
    '4:4': '“What prevented you from prostrating when I commanded you?” In the زائد analysis of ألا, منع already contains prevention, and لا reinforces rather than reverses the intended reproach. Other grammatical accounts exist; do not calculate this by counting two negatives.',
    '5:1': 'لا أقسم بيوم القيامة and ولا أقسم بالنفس اللوامة introduce the Resurrection Day and self-reproaching soul. One analysis calls لا emphatic زائد: “I swear”. Another understands a refusal to need an oath because the matter is evident. These are two interpretations, not an exhaustive list.',
    '5:3': 'On either account discussed, the rhetoric stresses certainty. Even declining an oath as unnecessary can emphasize the point. Neither reading denies the Day of Resurrection.',
  }, copyParts: { '4:6': [
    'There is no universal “two negatives” formula in Arabic, or in every variety of English. In لئلا يعلم أهل الكتاب ألا يقدرون على شيء, one common analysis makes the first لا زائد: “so the People of the Book know they have no power over Allah’s bounty”. The second negation remains real.',
    'In وحرام على قرية أهلكناها أنهم لا يرجعون, a resurrection reading denies non-return and thus affirms their return. Other readings understand الرجوع as returning to faith or to worldly life and analyze لا differently. State which interpretation is intended before applying a rule.',
  ] }, boxCopy: {
    '0:1': ['من أحرف الزيادة أو الصلة: إنْ، أنْ، ما، ولا.'],
    '0:2': ['زائد في أصل التركيب، لا عديم الفائدة.'],
    '0:4': ['الصلة تسمية تبرز وظيفة الحرف في البيان.'],
    '2:0': ['تأتي أنْ بعد لمّا الحينية؛ وفروق المعنى تدرس في السياق.'],
    '3:0': ['بعد إذا، متى، أيّ، أين، إنْ؛ وبعد مِن، عن، والباء.'],
    '3:4': ['ما هنا غير كافّة: تبقى رحمةٍ مجرورة بالباء.'],
    '4:0': ['من مواضع لا الزائدة: بعد و مع النفي، وبعد أنْ، وقبل القسم.'],
    '4:5': ['قد يقوّي النفي النفي، وقد يؤول إلى إثبات؛ بحسب التركيب.'],
    '5:2': ['قد يفيد ترك القسم لوضوح الأمر مزيدا من التأكيد.'],
  }, analysisItemLabels: { 'bank-19': { 'فعل الشرط وفاعله': 'فعل الشرط؛ الواو اسمه أو فاعله' } }, visuals: { '1:1': v('Same spelling, different functions', ['إنْ', 'Lightened or conditional'], ['إنْ', 'Negative or emphatic']) } }),
};

export const checks = {
  '18/l1': [q('What distinguishes هلا صليت from هلا تصلي in these examples?', ['The verb’s intended time: reproach versus urging.', 'Only the shaddah.', 'Only the presence of a question mark.', 'Active versus passive voice.'], 'Read past failure versus action still possible.'),
    q('Which combination explains هلا in the traditional account?', ['Interrogative هل and negative لا.', 'Conditional لولا and a vocative.', 'أنّ and negative لا للجنس.', 'همزة التسوية and أم.'], 'A question about an omitted act becomes reproach or urging.'),
    q('In the challenging reading, what does لولا يكلمنا الله... express?', ['تعجيز: a demand meant to expose supposed inability.', 'A sincere wish alone.', 'Only third-party astonishment.', 'A superior’s direct rebuke.'], 'The interpretation concerns the speakers’ expectation.'),
    q('In the wishing account of a plea for delay, what is the sense?', ['تمنّ: requesting what one cannot demand by rebuke.', 'A superior rebukes a subordinate.', 'Only astonishment about an absent person.', 'A verb that must be present in written form.'], 'The source’s deathbed context needed correction.'),
    q('What is لولا in لولا القرآنُ لما اهتدينا?', ['Conditional لولا.', 'Reproaching لولا.', 'Urging لولا.', 'Astonishment alone.'], 'The existing Quran prevents lack of guidance.'),
    q('Why does فلولا كانت قرية آمنت... imply failure among those towns?', ['The reproach and context imply the missed act.', 'إلا always negates every earlier verb.', 'كانت is passive.', 'Any indefinite noun makes its clause negative.'], 'No separate negative ما is required here.')],
  '18/l2': [q('Which three are attention particles here?', ['ألا، أما، ها.', 'هلا، ألّا، لولا.', 'ما، لا، إنْ.', 'إنْ، أنْ، ما.'], 'Notice which spellings lack shaddah.'),
    q('What does ألا حين يستغشون... يعلم... illustrate?', ['ألا can introduce nominal or verbal clauses.', 'Only verbal clauses are possible.', 'إنّ must immediately follow ألا.', 'Only past verbs can follow it.'], 'يعلم supplies the verbal clause.'),
    q('Compare ألا إنهم هم المفسدون and ألا تأكلون.', ['First attention; second invitation or urging.', 'First invitation; second attention.', 'Both have exactly the same function.', 'The distinction exists only in Quran quotations.'], 'Deleting the second ألا loses an invitation, not grammaticality.'),
    q('How is ما ترى الدهر... explained in the cited poetic analysis?', ['The hamzah of أما is omitted.', 'It must be ordinary negative ما.', 'أما never has a hamzah.', 'Hamzah exists only when an oath follows.'], 'Recover the form from the cited context.'),
    q('Where does ها attach in هؤلاء قومنا?', ['A near demonstrative.', 'A raised pronoun.', 'A past verb with قد.', 'Vocative أيّ.'], 'The base demonstrative is أولاء.'),
    q('What bridges يا and الناس in يا أيها الناس?', ['أيّ with ها attached.', 'An omitted preposition.', 'تنوين replacing أل.', 'A second يا.'], 'This is the ordinary pattern; special exceptions are separate.')],
  '18/l3': [q('What do a مصدر particle and its clause form?', ['A verbal-noun equivalent occupying one syntactic position.', 'A passive past verb.', 'Necessarily a حال.', 'Necessarily a vocative adjective.'], 'The name is مصدر مؤول.'),
    q('What kind of ما is in ما دمت حيّا?', ['مصدرية ظرفية, familiar with دام.', 'Only non-temporal مصدرية.', 'Relative ما requiring a عائد.', 'Negative ما.'], 'It includes duration.'),
    q('In the adopted analysis, what is لو تكفرون after ودّوا?', ['A مصدر equivalent filling the object position.', 'A condition answered by كما كفروا.', 'A verb made jussive by لو.', 'A negated act of disbelief.'], 'Compare ودّوا كفركم.'),
    q('What does the hamzah do in سواء عليهم أأنذرتهم أم لم تنذرهم?', ['Presents equal alternatives interpreted as مصدر phrases.', 'Asks for real information.', 'Negates أنذرتهم outright.', 'Gives أنذرتهم جزم.'], 'No answer is sought.')],
  '18/l4': [q('What does غير عامل mean for these negators?', ['Negation without case or mood government.', 'They never precede verbs.', 'They only negate nouns.', 'They cannot combine with إلا.'], 'Meaning and grammatical government are different.'),
    q('What reading is taught for ما in وما يشعرون?', ['Present-time negation here.', 'Past-time meaning only.', 'No usual time preference in this account.', 'Future time only.'], 'الحال is the ordinary reading discussed.'),
    q('What permits لا in فلا صدّق ولا صلّى?', ['Negation is repeated across the past verbs.', 'The sentence is a supplication.', 'The sentence is ungrammatical.', 'The verbs are passive.'], 'The two past verbs are different words.'),
    q('What does negative إنْ with إلا express?', ['Restriction: nothing but or only.', 'A conditional answered by إلا.', 'A double negative that simply cancels.', 'A request for information.'], 'Read إن أنتم إلا في ضلال كبير.')],
  '18/l5': [q('What does زائد mean here?', ['Optional in the core syntax, with an expressive contribution.', 'Meaningless and ignorable.', 'Ungrammatical except in poetry.', 'Only found in unreliable reports.'], 'Syntactic omission can lose emphasis.'),
    q('What does إنْ add in ما إن أتيت...?', ['It reinforces the negation of ما.', 'A condition requiring an answer.', 'An independent negative replacing ما.', 'جزم on the past verb.'], 'The past verb’s form is unchanged.'),
    q('What interpretation does the source propose for added أنْ in 28:19?', ['Musa’s hesitation after the previous day’s event.', 'أنْ is compulsory after every temporal لمّا.', 'The second day preceded the first.', 'يبطش becomes jussive.'], 'This is a proposed rhetorical reading, not a fixed grammar rule.'),
    q('Why does رحمةٍ remain مجرور in فبما رحمة?', ['This ما does not stop الباء from governing.', 'ما cancels الباء and makes رفع.', 'الباء loses all meaning.', 'ما gives رحمة نصب.'], 'Distinguish this ما from الكافّة.'),
    q('What does لا add in ما جاء زيد ولا عمرو?', ['Separate negation: neither came; و coordinates.', 'It makes Amr’s arrival affirmative.', 'It turns و into a conditional particle.', 'It has no effect.'], 'The negation explicitly reaches each name.'),
    q('What do the two discussed readings of لا أقسم share?', ['A rhetorical effect of emphasis.', 'Denial of Resurrection.', 'جزم on أقسم.', 'A prohibition addressed to someone.'], 'One asserts an oath; the other treats it as unnecessary.')],
};

export const quizzes = {
  '18/l1': [q('In the ordinary pattern, reproach concerns which intended time?', ['Past, an act already missed.', 'Only present ongoing action.', 'An imperative form.', 'Only a jussive present form.']),
    q('Which form ordinarily illustrates urging toward action?', ['A present verb.', 'Only a past verb.', 'An imperative after the particle.', 'Only past with قد.']),
    q('What distinguishes the two prayer examples?', ['The verb’s intended time in context.', 'Whether a question mark is printed.', 'Whether ألّا follows هلا.', 'The number of words.']),
    q('Which reading makes لولا يكلمنا الله... a challenge?', ['تعجيز.', 'تمنّ alone.', 'تعجب alone.', 'Direct توبيخ alone.']),
    q('In the source’s model, what does a superior’s reprimand illustrate?', ['توبيخ, also التغليط والتنديم.', 'Wishing alone.', 'Third-party astonishment.', 'Only future urging.']),
    q('What is لولا in لولا القرآنُ لما اهتدينا?', ['Conditional.', 'Reproaching.', 'Urging.', 'Astonishment alone.'])],
  '18/l2': [q('Name the attention particles studied.', ['ألا، أما، ها.', 'هلا، ألّا، لولا.', 'ما، لو، همزة التسوية.', 'إنْ، أنْ، لا.']),
    q('What does ألا add in ألا إنهم هم المفسدون?', ['Attention to an already complete assertion.', 'An invitation to act.', 'A required case ending.', 'A denial that can never be omitted.']),
    q('What is the function adopted for ألا تأكلون?', ['Invitation or urging.', 'Attention alone.', 'A genuine information question.', 'Unqualified negation.']),
    q('What commonly follows attention-giving أما?', ['An oath.', 'A condition.', 'A vocative.', 'An exception.']),
    q('What hosts ها in هؤلاء قومنا?', ['A near demonstrative.', 'A raised pronoun.', 'Past with قد.', 'Vocative أيّ.']),
    q('Why use أيّ in يا أيها الناس?', ['The ordinary pattern avoids direct يا + an أل-defined noun.', 'All fixed nouns are barred after يا.', 'يا only precedes pronouns.', 'Every vocative requires أيّ.'])],
  '18/l3': [q('What are the alternative names of أحرف المصدر?', ['موصولات حرفية and حروف موصولة.', 'Attention and vocative particles.', 'Jussive and accusative particles only.', 'Coordinators and exception particles.']),
    q('What kind of ما is in ما دمت حيّا?', ['مصدرية ظرفية.', 'مصدرية غير ظرفية.', 'موصولة.', 'نافية.']),
    q('What kind of ما is adopted in فصبروا على ما كذّبوا?', ['مصدرية غير ظرفية.', 'مصدرية ظرفية.', 'استفهامية.', 'شرطية.']),
    q('What does relative ما require that مصدرية ما does not?', ['A referring عائد, expressed or legitimately omitted.', 'A following تمييز.', 'A مضاف إليه.', 'A predicate of ما itself in every use.']),
    q('What is لو تكفرون in the adopted analysis after ودّوا?', ['A مصدر equivalent, كفركم, serving as object.', 'A condition answered by كما كفروا.', 'A حال describing the manner of wishing.', 'An adjective of the verb.']),
    q('Which مصدر particles govern and belong to the other group?', ['كي، أنْ، أنّ.', 'ما، لو، همزة التسوية.', 'هلا، ألّا، لولا.', 'ألا، أما، ها.'])],
  '18/l4': [q('What does non-governing negation do?', ['Negates meaning without assigning case or mood.', 'Only precedes nouns.', 'Never negates a verb.', 'Forbids إلا.']),
    q('What is the usual ما + present reading in the account taught?', ['الحال, the present.', 'No preferred time at all.', 'Only the future.', 'Only the past.']),
    q('Which verb form does لا ordinarily negate?', ['Present.', 'Past.', 'Imperative.', 'Past only.']),
    q('What pattern is فلا صدّق ولا صلّى?', ['Repeated negation across past verbs.', 'A future-oriented supplication.', 'An ungrammatical sentence.', 'A passive-voice exception.']),
    q('Why does لا قدّر الله use a past form?', ['It is a supplication with future-oriented meaning.', 'The verb is repeated.', 'It necessarily violates grammar.', 'قدّر is actually present form.']),
    q('What does إن أنتم إلا في ضلال كبير express?', ['Negative restriction: only.', 'A condition.', 'A question.', 'A supplication.'])],
  '18/l5': [q('What does syntactic زيادة mean?', ['Not required by core syntax, while still expressive.', 'Meaningless filler.', 'Found only in weak reports.', 'Allowed only in verse.']),
    q('Why does the source favour the name صلة for Quranic wording?', ['It emphasizes eloquence without suggesting purposeless wording.', 'It denies every meaning.', 'It refers to an entirely different set of particles.', 'It declares the term زائد grammatically invalid.']),
    q('What accompanies إنْ in ما إن أتيت...?', ['Negative ما.', 'Prohibitive لا.', 'Temporal لمّا.', 'مصدرية أنْ.']),
    q('Where does added أنْ commonly occur in the examples, with the proposed time nuance?', ['After temporal لمّا; a possible gap in time.', 'After إذا; mandatory doubt.', 'After حتى; mandatory purpose.', 'After conditional لولا; impossibility.']),
    q('What can ما reinforce with conditional tools?', ['General scope: whenever or wherever.', 'A single uniquely specified case.', 'Negation cancelling the condition.', 'An information question.']),
    q('What does repeated لا make explicit in ما جاء زيد ولا عمرو?', ['Neither person came.', 'Zayd came but Amr did not.', 'Both came.', 'The sentence is a question.'])],
};
