import { card as c, rows as r, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '15/l5': plan(78, 'Contrasting with لا and بل', [
    [c('لا denies the ruling of the second item', 0, 1, 2, 3), c('One seen, the other not seen', 4, 5)],
    [c('A positive statement or command comes first', 0, 1), c('After negation, the coordination uses و', 2, 3)],
    [c('Repeating لا with descriptions', 0, 1, 2), c('Two negated attributes', 3, 4), c('Two negated circumstances', 5, 6), c('Each item, or only their combination?', 7, 8)],
    [c('بل turns to what follows', 0, 1, 2), c('A command redirected to tomorrow', 3, 4)],
    [c('After negation', 0, 1, 2, 3, 4), c('Compare withdrawal with retained negation', 5, 6)],
  ], [
    ['لا العاطفة', 'Affirms the first item’s ruling and denies it of the second.'],
    ['ولا', 'In the negative patterns here, و coordinates and لا reinforces negation.'],
    ['بل after affirmation', 'Withdraws the first assertion and transfers the ruling to the second.'],
    ['بل after negation', 'Retains the first negation and affirms the opposite for the second.'],
  ], { copy: {
    '0:0': 'لا is seventh in the list of conjunctions.',
    '0:3': '“Do good, not evil.” صالحا receives the command; لا denies that same ruling of سيئا. The items share grammatical case but not the same affirmation.',
    '0:5': '“I saw Amr, not Khalid.” Seeing is affirmed of Amr and denied of Khalid.',
    '1:1': 'Coordinating لا here follows an affirmative statement or command. After negation or prohibition, the paired negative form uses ولا: و does the coordination, with لا reinforcing the negation.',
    '1:3': 'لن ترضى is already negative. ولا النصارى adds the second negated group; bare لا النصارى does not give this construction. The quoted verse continues with حتى تتبع ملتهم, the stated condition of approval.',
    '2:0': 'Negated descriptions have a repetition pattern.',
    '2:2': 'For the paired negative خبر, نعت and حال constructions here, use لا before the first and ولا before the next. The first لا need not itself have a preceding و.',
    '2:4': 'Paradise’s fruit is neither cut off nor withheld. مقطوعة and ممنوعة are negated attributes of فاكهة, each with لا.',
    '2:6': 'He prayed neither heedless nor distracted. غافلا and لاهيا are two negated حال descriptions of his state.',
    '2:8': 'On the combination reading, لا تأكل سمكا ولبنا forbids taking them together. Repeated لا in لا تأكل سمكا ولا لبنا clearly prohibits each separately, whether together or alone. Context matters for the unrepeated form; bare و alone does not always guarantee permission for each item.',
    '3:0': 'بل is eighth in the list. إضراب turns attention away from the first item to the next.',
    '3:4': '“Fast today, rather tomorrow.” The instruction is redirected to tomorrow. The source calls this إبطال of the first instruction. More precisely, today becomes مسكوتا عنه: withdrawing its command does not automatically prohibit fasting today.',
    '4:1': 'After a negative statement or prohibition, بل preserves the first negative ruling and gives its opposite to the next item.',
    '4:3': '“Do not fast today; rather, fast tomorrow.”',
    '4:4': 'Today’s prohibition remains, تقرير. Tomorrow receives the positive command. This differs from simply withdrawing a command for today.',
    '4:6': 'Both examples direct fasting tomorrow. After صم اليوم, the earlier command is withdrawn. After لا تصم اليوم, the earlier prohibition remains. Only the second wording explicitly retains a prohibition on today.',
  }, boxCopy: {
    '0:1': ['لا العاطفة تنفي الحكم عن المعطوف.'],
    '1:0': ['تسبق لا العاطفة بإثبات أو أمر. ومع النفي في هذا النمط: ولا.'],
    '2:7': ['لا تأكل سمكا ولبنا.', 'لا تأكل سمكا ولا لبنا.'],
    '3:2': ['بعد الإيجاب أو الأمر، بل تنقل الحكم إلى التالي ويصير الأول كالمسكوت عنه.'],
    '4:5': ['بعد الإثبات: نقل الحكم. بعد النفي: تقريره للأول وضدّه للثاني.'],
  }, visuals: { '4:1': v('What remains about today?', ['صم اليوم بل غدا', 'The command is withdrawn'], ['لا تصم اليوم بل غدا', 'The prohibition remains']) } }),
  '15/l6': plan(79, 'Alternatives with إمّا, Contrast with لكن', [
    [c('Does إمّا count as a conjunction?', 0, 1, 2)],
    [c('A repeated pair of alternatives', 0, 1, 2, 3), c('أو may replace the second إمّا', 4, 5), c('Bare و does not complete this pattern', 6, 7)],
    [c('Two analyses of وإمّا', 0, 1, 2), c('A related debate about ولكن', 3, 4)],
    [c('لكنْ contrasts the second item', 0, 1, 2, 3), c('Conditions for coordinating لكنْ', 4, 5)],
    [c('و joins clauses around لكنْ', 0, 1), c('لكنْ can introduce a fresh statement', 2, 3), c('Identify what و is connecting', 4, 5), c('Light لكنْ and strong لكنّ', 6, 7)],
  ], [
    ['إمّا', 'Introduces alternatives; the preferred account assigns coordination to و.'],
    ['Its pair', 'إمّا... وإمّا, or إمّا... أو in the pattern taught.'],
    ['لكنْ العاطفة', 'After negation/prohibition, without و, joining a single item.'],
    ['لكنّ / لكنْ', 'Strong form governs اسم and خبر; light form retains contrast without that government.'],
  ], { analysisPrompt: 'Use the preferred analysis.', copy: {
    '0:0': 'The nine listed conjunctions are و، ف، ثمّ، حتى، أو، أم، لا، بل، لكن. Related إمّا is sometimes counted as a tenth.',
    '0:2': 'It presents alternatives like أو and أم. The preferred analysis here does not make إمّا itself a conjunction, though some grammarians do.',
    '1:1': 'In this pattern, repeat إمّا before each alternative, or use أو in the second place.',
    '1:3': '“We showed him the way, whether grateful or ungrateful.” The two alternatives are marked by إمّا شاكرا and وإمّا كفورا.',
    '1:5': '“The noun is either masculine or feminine.” أو supplies the second alternative instead of another إمّا.',
    '1:7': 'الاسم إمّا مذكر ومؤنث does not express this two-alternative pattern correctly. The second marker should be وإمّا or أو, not bare و.',
    '2:1': 'The first إمّا introduces the detailed alternatives. With the second, grammarians differ over whether و or إمّا performs the coordination.',
    '2:4': 'The source compares this with rival accounts of ولكن: either و coordinates or it is treated as added. The account used below assigns coordination to و, leaving لكنْ to convey contrast. “Added” does not mean meaningless.',
    '3:0': 'لكنْ is ninth in the conjunction list.',
    '3:3': '“Zayd did not come, but Khalid did.” Zayd’s coming is denied; Khalid’s is affirmed. لكنْ conveys استدراك.',
    '3:5': 'For single-item coordination, لكنْ follows negation or prohibition and has no preceding و. With ولكن, the standard account gives coordination to و; لكنْ retains استدراك. A following full clause is a different construction.',
    '4:1': 'رسولَ is خبر of understood كان: ولكن كان رسول الله. و joins this affirmative clause to the preceding negative clause. It cannot simply join رسول to أبا under the same negation. لكنْ retains contrast; وخاتم joins the two affirmed descriptions.',
    '4:3': '“But they do not perceive.” In this account, و opens a fresh clause, واو الابتداء. لكنْ supplies contrast without coordinating two individual nouns.',
    '4:5': 'Ask what و connects: complete clauses, individual items, or a fresh statement? With preceding و, لكنْ is not the conjunction in the preferred analysis. It still contributes the contrast.',
    '4:7': 'Light لكنْ is analysed as the lightened form of لكنّ. Both convey استدراك. Strong لكنّ governs اسم and خبر; light لكنْ loses that case government and may coordinate only under its own conditions.',
  }, boxCopy: {
    '0:1': ['إمّا ليست عاطفة في القول الراجح هنا، ومعناها قريب من أو وأم.'],
    '1:0': ['إمّا... وإمّا، أو إمّا... أو.'],
    '2:0': ['إمّا الأولى للتفصيل. وفي الثانية بعد الواو تحليلان.'],
    '3:1': ['لكنْ للاستدراك: مخالفة ما بعدها لما قبلها.'],
    '3:4': ['لكنْ العاطفة: بعد نفي أو نهي، دون واو، ومعطوفها مفرد.'],
    '4:4': ['حدّد ما توصله الواو، ولا تفترض أن لكنْ هي العاطف معها.'],
  }, tableCopy: { '2:2': {
    0: ['One account', 'و is added; second إمّا coordinates.'],
    1: ['Preferred here', 'و coordinates; إمّا details the alternatives, without independent coordination.'],
  } }, visuals: { '1:2': v('Complete the paired pattern', ['إمّا مذكر', 'First alternative'], ['وإمّا مؤنث / أو مؤنث', 'Second alternative']),
    '2:1': v('Related analyses', ['وإمّا', 'Who performs coordination?'], ['ولكن', 'A similar attribution debate']),
    '4:3': v('Shared contrast, different government', ['لكنّ', 'اسم منصوب وخبر مرفوع'], ['لكنْ', 'No اسم-and-خبر government']) } }),
  '15/l3': plan(76, 'The Endpoint with حتى', [
    [c('An endpoint reached in stages', 0, 1, 2, 3, 4)],
    [c('Endpoints in time and place', 0, r(1, 0, 1), p(2, 0)), c('An endpoint in rank', r(1, 2), p(2, 1), 3, 4)],
    [c('The coordinated item belongs to the whole', 0, 1, 2, 3)],
    [c('A literal endpoint', 0, 1, r(2, 0)), c('Either extreme of a rank scale', r(2, 1, 2))],
    [c('Coordination and preposition differ', 0, 1), c('A coordinated endpoint is included', 2, 3), c('An endpoint outside Ramadan', 4, 5), c('An endpoint interpreted through context', 6, 7)],
    [c('Prepositional endpoints need interpretation', 0, r(1, 0, 1)), c('Two analyses can retain the same meaning', r(1, 2), 2)],
  ], [
    ['غاية وتدريج', 'An endpoint approached in stages, including a scale of rank.'],
    ['عاطفة', 'The item belongs to the preceding whole and marks an endpoint or extreme.'],
    ['Inclusion', 'Coordination includes the endpoint in the ruling.'],
    ['جارّة', 'No part-of-whole requirement; context determines endpoint inclusion.'],
  ], { copy: {
    '0:0': 'حتى is fourth in the conjunction list.',
    '0:2': 'غاية is an endpoint. تدريج is progression toward it, bit by bit.',
    '0:4': 'Reading the Quran through Surat al-Nas proceeds surah by surah to the final one. Here سورةَ is coordinated with القرآنَ.',
    '1:4': '“Even the Prophets” ranks them highest, without claiming they died last in time. Ordinary people have died after many Prophets. This use, like و, does not impose chronology.',
    '2:1': 'The item after coordinating حتى must belong to the preceding whole.',
    '2:3': 'The head belongs to the fish. أكلت السمكة حتى الفاكهة fails: fruit is not part of the fish. Use و or ثمّ for that separate item.',
    '3:1': 'The endpoint may be literal, حقيقة, or an extreme on a relevant scale, حكما. Merely belonging to the whole is not enough.',
    '4:0': 'حتى can also be a preposition. Its endpoint meaning does not by itself identify its grammatical use.',
    '4:3': '“I fasted Ramadan, including its last day.” آخرَ is coordinated with رمضانَ. The day belongs to Ramadan and shares the fasting ruling.',
    '4:5': 'Eid is outside Ramadan, so حتى يومِ الفطر is prepositional, with جر. The endpoint is excluded here: Eid fasting is prohibited.',
    '4:7': 'In سرت النهار حتى العصرِ, Asr is a time within the day. The source reads the journey as including that endpoint where no clue excludes it. With prepositional حتى, inclusion depends on the intended limit and context; Eid provides a clear excluding clue.',
    '5:0': 'Compare exclusion, contextual inclusion and guaranteed inclusion by coordination.',
    '5:2': 'Until Ramadan’s last day can have آخرَ for coordination or آخرِ for prepositional government. Where context includes that day, both yield the same meaning. The ending distinguishes the grammar; an endpoint outside Ramadan, يوم الفطر, cannot be coordinated as its part.',
  }, boxCopy: {
    '0:1': ['حتى للغاية والتدريج: بلوغ النهاية شيئا فشيئا.'],
    '1:0': ['الغاية: زمان، مكان، رتبة.'],
    '4:1': ['Coordinating حتى: a part of the whole, necessarily sharing its ruling.', 'Prepositional حتى: no part requirement; inclusion is read from context.'],
    '4:2': ['صمت رمضان حتى آخرَ يومٍ منه.'],
    '4:4': ['صمت رمضان حتى يومِ الفطر.'],
    '4:6': ['سرت النهار حتى العصرِ.'],
  }, copyParts: { '1:2': [
    'The peace of Laylat al-Qadr continues through the night to dawn: a time limit. Walking to the masjid door progresses step by step to a place. Both examples use prepositional حتى.',
    'مات الناس حتى الأنبياء reaches the highest rank of people on the scale: even the Prophets. الأنبياءُ is coordinated with الناسُ.',
  ] }, tableCopy: {
    '3:2': { 0: ['Literal endpoint', 'قرأت القرآن حتى سورةَ الناس', 'Al-Nas is the final surah. Al-Kahf is not the endpoint of the whole Quran.'],
      1: ['High extreme: قوة أو تعظيم', 'مات الناس حتى الأنبياءُ', 'Highest rank, not latest death.'],
      2: ['Low extreme: ضعف أو تحقير', 'قدم الحجاج حتى المشاةُ', 'Even those on foot: lower on the speed scale, not necessarily last in every case.'] },
    '5:1': { 0: ['جارّة: excluded endpoint', 'Context excludes it.', 'صمت رمضان حتى يومِ الفطر.'],
      1: ['جارّة: included endpoint', 'Included in the interpretation taught.', 'سرت النهار حتى العصرِ.'],
      2: ['عاطفة: included endpoint', 'Necessarily shares the ruling.', 'صمت رمضان حتى آخرَ أيامه.'] },
  } }),
  '15/l4': plan(77, 'Alternatives with أم and أو', [
    [c('Connected أم follows a question pattern', 0, 1, 2)],
    [c('Asking the listener to specify one', 0, 1, 2), c('A rhetorical question needs no uncertainty', 3)],
    [c('Whether one or the other: the same result', 0, 1, 2), c('Look for سواء or its equivalent', 3, 4)],
    [c('The second alternative is the معادل', 0, 1), c('Alternatives can be verbs or subjects', r(2, 0, 1)), c('Alternatives can be objects', r(2, 2), 3)],
    [c('Three common uses of أو', 0, 1), c('A rhetorical alternative prompts reflection', 2, 3), c('A choice that satisfies the requirement', 4, 5)],
    [c('A prohibition covers both alternatives', 0, 1, 2), c('Read the clause type and context', 3, 4)],
  ], [
    ['أم المتصلة', 'After a question hamzah or a hamzah of equal outcome.'],
    ['تعيين / تسوية', 'Specify one alternative / declare the same result with either.'],
    ['أو', 'Here: doubt or rhetorical uncertainty, choice, or both alternatives under negation.'],
    ['Context', 'A rhetorical question need not express the speaker’s uncertainty.'],
  ], { copy: {
    '0:0': 'أم is sixth in the conjunction list. This lesson studies connected أم, المتصلة.',
    '0:2': 'This connected use follows a question hamzah or its equivalent, such as hamzah of تسوية. Unlike ordinary أو, it does not freely join choices in a command. Other uses of أم are outside this rule.',
    '1:2': 'Yusuf asks his fellow prisoners to identify which is better: separate lords, or Allah, the One, the Subduer. He knows the answer; طلب التعيين directs the listeners to acknowledge it.',
    '1:3': '“Which is it: a teacher of twenty years, or you?” The question may press an obvious comparison rather than express real doubt. Specifying one answer is still its rhetorical structure.',
    '2:2': '“It is the same to them whether you warn them or not.” The people described will not believe either way. أم gives the second side of an equivalence; no choice is requested.',
    '2:4': 'سواء or an equivalent signals equality of outcome. تعيين asks which one; تسوية says either has the same result. The English “or” alone cannot distinguish them.',
    '3:1': 'The first alternative follows the question hamzah. The counterpart after أم is المعادل, balancing it in the question.',
    '3:3': 'الذكرين and الأنثيين are objects of حرّم. Likewise, يمسكه and يدسه are verbs, while أرباب and الله occupy the subject comparison. المعادل can share other grammatical roles too.',
    '4:0': 'أو is fifth in the list. These are three common uses, not an exhaustive list of every context.',
    '4:3': '“Either we or you are rightly guided or in clear error.” The Prophet ﷺ is not uncertain of his guidance. This is rhetorical تشكيك or إبهام: the listeners must weigh the alternatives and confront the truth.',
    '4:5': 'The fidyah for shaving because of illness or a head ailment offers fasting, charity or sacrifice. One permitted option meets the requirement: تخيير, not a demand for all three.',
    '5:2': 'ولا تطع منهم آثما أو كفورا forbids obeying either category. It does not permit one while forbidding the other. Likewise, “Do not drink alcohol or wine” covers both named alternatives.',
    '5:4': 'First identify the clause: statement, command, negation or prohibition. Then read its context. Here those yield شك/تشكيك, تخيير, and a ruling covering both alternatives.',
  }, boxCopy: {
    '0:1': ['أم المتصلة لطلب التعيين أو التسوية.'],
    '1:0': ['بعد همزة الاستفهام، أم تطلب تعيين أحد الأمرين.'],
    '2:0': ['أم بعد همزة التسوية: الأمران سواء في الحكم.'],
    '3:0': ['ما بعد أم يسمّى المعادل، ويوازن الطرف الأول بعد الهمزة.'],
    '4:1': ['من معاني أو: الشك في الخبر، والتخيير في الأمر، وشمول النفي أو النهي للبديلين.'],
    '5:0': ['في المثال هنا، النهي يشمل كلا الأمرين بعد أو.'],
  }, visuals: { '1:1': v('The speaker can already know', ['السؤال', 'Presents the comparison'], ['التعيين', 'Asks the listener to name one']),
    '2:1': v('Two different demands', ['تعيين', 'Which one?'], ['تسوية', 'Either has the same result']) } }),
  '15/l2': plan(75, 'Sequence with ثمّ and ف', [
    [c('ثمّ marks order with a delay', 0, 1, 2), c('An example of تراخي', 3, 4, 5)],
    [c('Two kinds of order between clauses', 0, 1), c('Life, death and return', 2, 3), c('A further, weightier statement', 4, 5), c('Test the context before choosing', 6, 7)],
    [c('فاء marks close succession', 0, 1, 2, 3), c('Closeness depends on the event', 4, 5), c('Travel and entering a doorway', 6, 7)],
    [c('Three links between full clauses', 0, 1), c('A sequence in time', 2, 3), c('Detail after a general statement', 4, 5),
      c('A reason following the instruction', p(6, 0)), c('An instruction following its reason', p(6, 1), 7, 8)],
    [c('فاء can reveal an omitted episode', 0, 1, 2), c('Supply the missing causal episode', 3, 4)],
  ], [
    ['ثمّ', 'Joining, order and delay: جمع، ترتيب، تراخي.'],
    ['فاء', 'Joining, order and close succession: جمع، ترتيب، تعقيب.'],
    ['Between clauses', 'Time sequence, order of presentation, or a causal relation.'],
    ['فاء فصيحة', 'Signals an understood episode or clause before its stated result.'],
  ], { copy: {
    '0:0': 'ثمّ is third in the traditional list of nine conjunctions.',
    '0:2': 'In its temporal use, ثمّ joins two items, puts the first before the second, and marks a gap between them.',
    '0:4': 'Ali accepted Islam early; Umar later. ثمّ presents Umar’s belief after Ali’s with a real intervening period, تراخي.',
    '1:0': 'Between full clauses, ثمّ can order events or statements.',
    '1:3': 'From lifelessness to life, then death, renewed life and return to Allah: these are stages in time. ثمّ marks chronological progression, ترتيب زماني.',
    '1:5': '“To Us is their return; furthermore, Allah witnesses what they do.” His witnessing is already continuous. ثمّ advances to a weightier fact, ترتيب ذكري, rather than a later event.',
    '1:7': 'Does a real time sequence make sense? Life, death and resurrection: yes. Allah’s ongoing witnessing starting only after return: no. Read the latter as progression in the statement’s force, not chronology.',
    '2:0': 'فاء is second in the traditional list.',
    '2:3': 'Khadijah believed, followed closely by Abu Bakr. أبو بكر shares the subject’s ruling by عطف. فاء marks تعقيب, rather than the delayed succession expressed by ثمّ.',
    '2:5': 'تعقيب has no fixed duration. A race is measured in fractions of a second, illustrated by 0.1 versus 0.3 seconds; cosmic timescales may use thousands of years. These are illustrations, not grammatical cutoffs.',
    '2:7': 'Travel from Makkah to Madinah takes longer than Amr following Zayd through a doorway. Both can be close succession on the scale of the activity.',
    '3:0': 'Between single items, فاء gives ordered succession. Between clauses, examine the relation.',
    '3:3': '“You were lifeless, then He gave you life.” فاء moves from the earlier state to the following event: ترتيب زماني.',
    '3:5': '“Something greater” is مجمل, general. “Show us Allah openly” supplies the detail, مفصل. فقالوا explains the same request, not a later one: عطف مفصل على مجمل, a kind of ترتيب ذكري or رتبي.',
    '3:8': 'Find the logical reason, whichever side it occupies. These clause links are broader than فاء السببية before a منصوب مضارع studied earlier.',
    '4:0': 'Sometimes the preceding causal episode is understood.',
    '4:2': 'The فاء is called فصيحة because it reveals what the context leaves unspoken.',
    '4:4': 'Between “Go to the people who denied Our signs” and “We destroyed them”, supply ذهبا إليهم فكذبوهما: Musa and Harun went and were rejected. The فاء before دمرناهم points to that omitted cause.',
  }, analysisLabels: {
    'فعل مضارع ومفعوله وفاعله مستتر': 'فعل مضارع مرفوع بثبوت النون',
  }, boxCopy: {
    '0:1': ['ثمّ للجمع مع الترتيب والتراخي.'],
    '2:1': ['الفاء للجمع مع الترتيب والتعقيب.'],
    '2:6': ['سافرت إلى مكة فالمدينة.', 'دخل زيد الدار فعمرو.'],
    '3:1': ['بين الجمل: ترتيب زماني، أو ذكري، أو علاقة سببية.'],
    '3:7': ['حدّد السبب من المعنى، لا من موضعه وحده.'],
  }, copyParts: { '3:6': [
    'وتزوّدوا فإنّ خير الزاد التقوى: “Take provisions, for the best provision is mindfulness of Allah.” The clause after فاء supplies a reason for the preceding instruction. Here the relation is like “because”: the reason is stated second.',
    'يا قوم إنكم ظلمتم أنفسكم باتخاذكم العجل فتوبوا إلى بارئكم: “You wronged yourselves by taking the calf, so repent to your Creator.” The wrongdoing gives the reason; the following command is its consequence. Here فاء is like “therefore”.',
  ] }, visuals: {
    '1:0': v('What is being ordered?', ['زماني', 'Events in time'], ['ذكري', 'Statements in presentation']),
    '3:3': v('An instruction justified', ['تزوّدوا', 'The instruction'], ['خير الزاد التقوى', 'The stated reason']),
  } }),
  '15/l1': plan(74, 'Joining with و', [
    [c('Particles without independent government', 0, 1, 2)],
    [c('و joins without specifying order', 0, 1), c('Shared object roles with و', 2, 3, 4), c('Three possible arrival scenarios', 5, 6, 7)],
    [c('Context can establish simultaneity', 0, 1, 2, 3)],
    [c('Context can establish a sequence', 0, 1), c('Mention order and time', 2, 3, 4, 5)],
    [c('Distributive counts are alternatives', 0, 1, 2, 3), c('The same pattern describes wings', 4, 5)],
    [c('Coordination inside a condition', 0, 1, 2)],
  ], [
    ['غير عامل', 'Meaningful particles without independent case government.'],
    ['و', 'الجمع المطلق: joins items without itself specifying order or simultaneity.'],
    ['قرينة', 'Context can establish togetherness, sequence or alternatives.'],
    ['معطوف', 'Shares the preceding item’s grammatical ruling through coordination.'],
  ], { copy: {
    '0:0': 'The next section studies particles with no independent case government. They still contribute meaning and structure; earlier lessons also mentioned some non-governing uses.',
    '0:2': 'The course groups them into eighteen categories. First come nine coordinating particles, beginning with و.',
    '1:1': 'و joins a معطوف to its معطوف عليه. By itself, it specifies neither order, ترتيب, nor simultaneity, معية.',
    '1:3': 'الرسولَ shares the object role and command to obey. و does not specify which obedience comes first.',
    '1:6': 'جاء زيد وعمرو fits all three: they arrived together; Zayd arrived first; or Amr arrived first.',
    '1:7': 'Any inferred order comes from context or convention. A و in a verse or hadith alone does not prove chronological sequence.',
    '2:0': 'A قرينة supplies more information.',
    '2:3': 'Ibrahim and Ismail share the work of raising the House’s foundations. إسماعيل shares the subject’s ruling by عطف; their working together is supplied by context.',
    '3:1': 'The earth shakes, releases its burdens, and people ask what is wrong. This judgement scene supplies a logical sequence; و itself merely joins the events.',
    '3:3': 'Mention order can also differ from time order.',
    '3:5': 'The speakers deny the afterlife. نموت ونحيا cannot mean “we die, then rise again”. It presents this world’s cycle of living and dying, not resurrection or a fixed sequence for one person.',
    '4:0': 'Not every و has the same use.',
    '4:3': 'مثنى وثلاث ورباع distributes alternatives: two, three or four, not nine. The source explains this with an أو-like sense. Another account retains coordination while the distributive wording and context supply the alternatives.',
    '4:5': 'Angels’ wings use the same distributive pattern: in twos, threes or fours. The counts are alternatives across the described groups, not one sum.',
    '5:1': 'In this condition, لله وملائكته ورسله وجبريل وميكال forms a coordinated list. لام governs the first genitive; the others share جر by عطف. عدوّا relates to the prepositional phrase, not directly governing these case endings.',
    '5:2': 'Whether in a command, condition or description, coordinating و joins. Context supplies further meaning, including the alternative-count interpretation just discussed.',
  }, analysisLabels: { 'مفعول به منصوب': 'مفعول مطلق منصوب' }, boxCopy: { '0:1': ['الحرف غير العامل: ثمانية عشر قسما. أولها أحرف العطف، وهي تسعة.'],
    '1:5': ['جاء زيد وعمرو: معا، أو زيد أولا، أو عمرو أولا.'],
    '3:2': ['ترتيب الذكر لا يوجب ترتيب الوقوع.'] },
    visuals: { '1:2': v('The same words fit all three', ['معا', 'Together'], ['زيد أولا', 'Zayd first'], ['عمرو أولا', 'Amr first']) } }),
};

export const checks = {
  '15/l5': [q('What does coordinating لا do to the second item’s ruling?', ['Denies it, while retaining the first item’s ruling.', 'Affirms it exactly like و.', 'Cancels the first item instead.', 'Changes neither meaning.'], 'Compare اعمل صالحا لا سيئا.'),
    q('Why use ولا النصارى after لن ترضى... اليهود?', ['The preceding statement is negative; و coordinates and لا reinforces that negation.', 'و is always optional.', 'لا never occurs without و in the Quran.', 'The two groups require و for number agreement.'], 'This is not bare coordinating لا after affirmation.'),
    q('What does repeating لا clarify in لا تأكل سمكا ولا لبنا?', ['Each item is prohibited separately.', 'Each is allowed separately.', 'The meaning cannot change.', 'The prohibition becomes a command.'], 'Compare the possible combination reading of the unrepeated form.'),
    q('What happens to today’s command in صم اليوم بل غدا?', ['It is withdrawn; the command moves to tomorrow.', 'It remains explicitly commanded.', 'Both days remain equally commanded.', 'بل does nothing after commands.'], 'Withdrawing a command is not itself a prohibition.'),
    q('How do صم اليوم بل غدا and لا تصم اليوم بل غدا differ?', ['First: withdraw the command. Second: retain the prohibition.', 'They use exactly the same mechanism.', 'First: retain negation. Second: withdraw affirmation.', 'Neither uses coordinating بل.'], 'Check the polarity before بل.')],
  '15/l6': [q('Does the preferred account count إمّا as a tenth conjunction?', ['No, though it presents alternatives like أو and أم.', 'Yes, unanimously.', 'It is instead a preposition.', 'It is always a noun.'], 'Separate meaning from grammatical classification.'),
    q('What completes the alternative pattern begun by إمّا?', ['A repeated إمّا or specifically أو.', 'Any conjunction.', 'No second marker.', 'Exactly three options.'], 'Bare و does not give the paired pattern here.'),
    q('Which form has a related debate over و’s coordinating role?', null, 'It also expresses contrast.'),
    q('For single-item coordination, what does لكنْ require?', ['Negation or prohibition before it, with no preceding و.', 'Affirmation and a required و.', 'A question hamzah.', 'A following مضارع.'], 'Distinguish لكنْ from ولكن.'),
    q('In the reading taught for ولكن لا يشعرون, what does و do?', ['Introduces a fresh clause; لكنْ supplies contrast.', 'Coordinates two individual nouns.', 'Has no function at all.', 'Turns لكنْ into governing لكنّ.'], 'Identify the structure that follows.')],
  '15/l3': [q('What does reading surah by surah toward al-Nas illustrate?', ['تدريج: progression toward the endpoint.', 'Only the endpoint.', 'Neither, because every حتى is prepositional.', 'Joining with no progression.'], 'Distinguish the journey from its limit.'),
    q('Does مات الناس حتى الأنبياءُ say the Prophets died last?', ['No; the endpoint is rank, not chronology.', 'Yes; rank always fixes time order.', 'Yes; Prophets always outlive everyone.', 'No; حتى must be prepositional.'], 'Look at the scale being used.'),
    q('Why does أكلت السمكة حتى الفاكهة fail as coordination?', ['Fruit is not part of the fish.', 'Their genders conflict.', 'حتى never permits نصب.', 'أل blocks coordination.'], 'Test the part-to-whole relation.'),
    q('How are المشاة an endpoint in قدم الحجاج حتى المشاةُ?', ['حكما: the lower end of the speed scale.', 'حقيقة: necessarily the very last arrivals.', 'They are not pilgrims.', 'حكما: the highest rank of greatness.'], 'An endpoint can be an extreme on a scale.'),
    q('What is حتى in صمت رمضان حتى يومِ الفطر?', ['Prepositional: Eid is outside Ramadan.', 'Coordinating: Eid was fasted too.', 'A meaningless filler.', 'Both uses have identical rules everywhere.'], 'Check the whole, the endpoint and the case ending.'),
    q('How can آخرَ أيامه and آخرِ أيامه retain the same fasting meaning?', ['The day belongs to Ramadan and is included in both intended readings.', 'Both constructions are impossible.', 'A part can never follow prepositional حتى.', 'رمضان changes its case.'], 'The endpoint’s inclusion and its case are separate questions.')],
  '15/l4': [q('What restriction applies to connected أم in this lesson?', ['It follows a question or question-like pattern.', 'It occurs only in poetry.', 'It joins only verbs.', 'It always replaces و.'], 'The rule concerns أم المتصلة.'),
    q('What does Yusuf’s question with أم ask listeners to do?', ['Name one alternative, though he already knows the answer.', 'Choose his belief for him.', 'Declare the alternatives equal.', 'Cancel a preceding statement with بل.'], 'Identify the rhetorical request.'),
    q('What does سواء signal in سواء عليهم أأنذرتهم أم لم تنذرهم?', ['تسوية: equal outcome, no requested choice.', 'تعيين: choose one.', 'Meaningless أم.', 'Both meanings indistinguishably.'], 'The sentence declares the outcome equal.'),
    q('What role do الذكرين and الأنثيين share in آلذكرين حرّم أم الأنثيين?', ['Object of حرّم.', 'Subject of حرّم.', 'مبتدأ.', 'حال.'], 'Ask what the verb’s prohibition concerns.'),
    q('What is أو doing rhetorically in وإنا أو إياكم لعلى هدى...?', ['تشكيك: prompting listeners to weigh the alternatives.', 'Free choice of either truth.', 'Declaring both equal.', 'Cancelling the first claim.'], 'The speaker is not personally uncertain.'),
    q('Why does ولا تطع منهم آثما أو كفورا prohibit both?', ['The prohibition covers either alternative in this context.', 'أو always means both in every context.', 'The words are not coordinated.', 'Prohibition prevents coordination.'], 'Compare a prohibition with a positive choice.')],
  '15/l2': [q('Which part of ثمّ’s meaning expresses a real delay?', ['تراخي.', 'Joining alone.', 'Order alone.', 'The names Ali and Umar.'], 'Order and delay are distinct.'),
    q('What does ثمّ do in ثمّ الله شهيد على ما يفعلون?', ['Advances to a weightier statement: ترتيب ذكري.', 'Starts Allah’s witnessing at a later time.', 'Contributes no meaning.', 'Gives delay with no order.'], 'His witnessing does not begin only after their return.'),
    q('What does وتعقّب كل شيء بحسبه mean?', ['Closeness is relative to the activity’s timescale.', 'The same fixed duration applies everywhere.', 'Only journeys allow تعقيب.', 'تعقيب and تراخي are identical.'], 'Compare travel with entering a doorway.'),
    q('What does وتزوّدوا فإن خير الزاد التقوى teach about a causal clause link?', ['The stated reason may follow the instruction it justifies.', 'The reason must always precede فاء.', 'فاء cannot connect a reason here.', 'The command causes تقوى to be the best provision.'], 'Distinguish reading order from logical relation.'),
    q('What signals the omitted rejection episode before فدمّرناهم?', ['فاء الفصيحة.', 'A ثمّ in place of فاء.', 'The dual ending of اذهبا alone.', 'Nothing; it has no role in the meaning.'], 'Supply what happened between sending and destruction.')],
  '15/l1': [q('What distinguishes a حرف غير عامل?', ['It carries meaning without independent case government.', 'It always gives جر.', 'It must open a sentence.', 'It has no meaning.'], 'Meaning and government are separate properties.'),
    q('What does جاء زيد وعمرو establish by itself?', ['Both came; order and simultaneity are unspecified.', 'Zayd must have arrived first.', 'Both must have arrived together.', 'Togetherness applies only to people.'], 'All three arrival scenarios remain possible.'),
    q('What establishes Ibrahim and Ismail’s working together?', ['The context.', 'و always meaning “together”.', 'Every coordination implying sequence.', 'Ismail’s رفع by itself.'], 'Look for a قرينة.'),
    q('Why does نموت ونحيا not affirm resurrection in this passage?', ['The speakers deny the afterlife; و does not impose that sequence.', 'و itself forbids every sequence.', 'نموت is مبني.', 'Two verbs with one subject cannot be sequential.'], 'Read the statement in its setting.'),
    q('What does مثنى وثلاث ورباع mean here?', ['Alternative counts: two, three or four.', 'A total of nine.', 'و marks the state of النساء.', 'و is a تمييز.'], 'The numbers are distributive.'),
    q('What does و contribute to the list in من كان عدوّا لله وملائكته...?', ['Joining under a shared ruling, without specifying order.', 'Order of creation.', 'Independent government of every case ending.', 'A claim that the named angels outrank Allah.'], 'A surrounding condition does not change coordination.')],
};
export const quizzes = {
  '15/l5': [q('What does لا do in اعمل صالحا لا سيئا?', ['Denies the second item the affirmed ruling.', 'Affirms both alike.', 'Denies the first item instead.', 'Has no semantic effect.']),
    q('Why use ولا after the negative لن ترضى...?', ['و coordinates the second group; لا reinforces negation.', 'و is always optional.', 'Only the group names require it.', 'لا cannot follow المضارع.']),
    q('What does repeated لا in لا تأكل سمكا ولا لبنا make explicit?', ['Separate prohibition of each item.', 'Permission for each separately.', 'Permission rather than prohibition.', 'No possible difference.']),
    q('What does بل do to today’s command in صم اليوم بل غدا?', ['Withdraws it and redirects the command to tomorrow.', 'Reaffirms it unchanged.', 'Commands both days equally.', 'Nothing.']),
    q('What does بل preserve in لا تصم اليوم بل غدا?', ['Today’s prohibition, while commanding tomorrow.', 'Nothing: it cancels the first prohibition.', 'An equal ruling for both days.', 'A free choice of days.']),
    q('Why repeat لا in لا مقطوعة ولا ممنوعة?', ['The paired negated attributes each receive لا.', 'لا is never repeated in the Quran.', 'The attributes are not coordinated.', 'Two conjunctions are required for agreement.'])],
  '15/l6': [q('How does the preferred analysis classify إمّا?', ['Not a conjunction, though it presents alternatives.', 'Unanimously a tenth conjunction.', 'A preposition.', 'Always a verb.']),
    q('What supplies إمّا’s second alternative marker?', ['Repeated إمّا or أو.', 'Any conjunction.', 'Only repeated إمّا, never أو.', 'Always nothing.']),
    q('Which form has a related debate over the role of و?', null),
    q('For single-item coordination, what does لكنْ require?', ['Preceding negation/prohibition and no preceding و.', 'Affirmation plus و.', 'A question hamzah.', 'A following imperative.']),
    q('What connects the clauses in ما كان محمد... ولكن رسول الله?', ['و; لكنْ gives contrast, and كان is understood before رسولَ.', 'لكنْ alone; و is added in the preferred account.', 'Neither: there is no connection.', 'Both are independent conjunctions together.']),
    q('In the reading taught, what is و in ولكن لا يشعرون?', ['An introductory و opening a fresh clause.', 'A conjunction of two individual nouns.', 'A preposition.', 'A detailing particle.'])],
  '15/l3': [q('Reading surah by surah toward al-Nas illustrates which meaning?', null),
    q('Does even the Prophets in مات الناس حتى الأنبياءُ impose chronology?', ['No; this is rank, not time order.', 'Yes; rank always fixes chronology.', 'Yes; they always die last.', 'It describes neither rank nor time.']),
    q('Which condition fails in أكلت السمكة حتى الفاكهة?', ['The following item must belong to the preceding whole.', 'Only being the final item.', 'An affirmative statement or command.', 'A required preceding و.']),
    q('What kind of endpoint are المشاة among arriving pilgrims?', ['حكما: the lower end of a speed scale.', 'حقيقة: always the last actual arrivals.', 'حكما: the highest greatness.', 'No endpoint at all.']),
    q('Why is حتى prepositional before يومِ الفطر in the example?', ['Eid is outside Ramadan, not a coordinated part of it.', 'Eid is a fasted part of Ramadan.', 'حتى has no meaning.', 'Both grammatical uses are always identical.']),
    q('Why can حتى آخرَ أيامه and حتى آخرِ أيامه describe the same fast?', ['That day belongs to Ramadan and is included in the intended context.', 'Neither is grammatical.', 'The last day cannot be coordinated.', 'رمضان changes its own case.'])],
  '15/l4': [q('What restriction applies to أم المتصلة?', ['A question or question-like construction.', 'Only joining verbs.', 'Only opening a sentence.', 'It is simply و.']),
    q('What is طلب التعيين doing in Yusuf’s rhetorical question?', ['Asking the listeners to name the known better alternative.', 'Declaring the alternatives equal.', 'Cancelling a preceding ruling.', 'Expressing Yusuf’s own doubt.']),
    q('What does سواء signal before أأنذرتهم أم لم تنذرهم?', ['تسوية: no requested choice.', 'تعيين: choose one.', 'Free choice with أو.', 'Genuine uncertainty.']),
    q('What role do الذكرين and الأنثيين share after حرّم?', null),
    q('What rhetorical use appears in وإنا أو إياكم لعلى هدى...?', ['تشكيك: prompting the listener’s reflection.', 'Free choice.', 'Equality of both alternatives.', 'Cancelling the first alternative.']),
    q('Why does ولا تطع... آثما أو كفورا cover both categories?', ['The prohibition applies to either alternative here.', 'أو always means both.', 'There is no coordination.', 'The prohibition is optional.'])],
  '15/l2': [q('Which element of ثمّ’s meaning expresses a delay?', null),
    q('What kind of order appears in ثمّ الله شهيد على ما يفعلون?', null),
    q('How does temporal فاء differ from ثمّ?', ['Close succession rather than a delay.', 'They are identical.', 'فاء specifies no order.', 'فاء gives delay and ثمّ close succession.']),
    q('فقالوا أرنا الله جهرة explains أكبر من ذلك. What is this?', ['Detail after a general statement: ترتيب ذكري.', 'Two events separated in time.', 'فاء فصيحة revealing an omitted cause.', 'Only closeness in time.']),
    q('What justifies the instruction in وتزوّدوا فإن خير الزاد التقوى?', ['The following clause gives its reason.', 'The instruction causes تقوى to be best.', 'Neither clause has a causal relation.', 'Each causes the other simultaneously.']),
    q('What does فاء الفصيحة before فدمّرناهم reveal?', ['An omitted causal episode.', 'Destruction before the messengers were sent.', 'The absence of any cause.', 'A prepositional use of فاء.'])],
  '15/l1': [q('What defines a non-governing particle?', ['Meaning without independent case government.', 'Always giving جر.', 'All eighteen categories being prepositions.', 'Never occurring with a noun.']),
    q('What is coordinating و’s basic contribution?', ['Joining without inherent order or simultaneity.', 'Order and close succession.', 'Order with a time gap.', 'Only exclusive choice.']),
    q('Why can جاء زيد وعمرو fit three arrival scenarios?', ['و itself leaves order and simultaneity open.', 'و always means together.', 'Zayd must come first.', 'و cannot coordinate proper names.']),
    q('What shows Ibrahim and Ismail raised the foundations together?', ['Context.', 'و inherently meaning simultaneity.', 'إسماعيل being منصوب.', 'A required hidden particle.']),
    q('What would “we die, then rise again” wrongly imply in نموت ونحيا?', ['Resurrection, which these speakers deny.', 'جزم on نموت.', 'و becoming a preposition.', 'A universal simultaneity rule.']),
    q('What does مثنى وثلاث ورباع express in this context?', ['Alternative distributive counts.', 'Nine in total.', 'و acting as تمييز.', 'و acting as حال.'])],
};
