import { card as c, rows as r, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '19/l1': plan(94, 'Questions and Future Meaning', [
    [c('Two questioning particles', 0, 1, 2)],
    [c('Confirm a claim or identify an alternative', 0, 1), c('A polar question used for reproach', 2, 3), c('A choice between named alternatives', 4, 5)],
    [c('The hamzah can precede negation', 0, 1, 2, 3)],
    [c('Order beside a coordinator', 0, 1), c('Hamzah before و', 2, 3), c('هل after و', 4, 5), c('Recognize the opening pattern', 6, 7)],
    [c('س and سوف give future meaning', 0, 1, 2)],
    [c('Names and the traditional comparison', r(0, 0, 1), 1), c('Relative time in the examples', 2, 3)],
  ], [
    ['همزة / هل', 'Hamzah: تصديق or تصوّر. هل: تصديق in the standard distinction.'],
    ['Position', 'Questioning hamzah precedes the coordinator; هل follows it.'],
    ['Negation', 'Hamzah can precede a negative clause in the standard pattern.'],
    ['س / سوف', 'Both mark the future; a universal near/far division is disputed.'],
  ], { copy: {
    '0:0': 'The two non-governing question particles are الهمزة and هل.',
    '0:2': 'Both can introduce nominal or verbal clauses and have no إعراب position. Compare the nominal أنتم examples with verbal أكفرتم and هل يستوي.',
    '1:1': 'تصديق asks whether a claim is true: a polar question. تصوّر asks which alternative is intended. Hamzah can do either; هل introduces تصديق in the standard distinction. Negative questions require the نعم/بلى distinction studied earlier.',
    '1:3': '“Do you say about Allah what you do not know?” Its form is polar, but its rhetorical purpose is reproach. Grammatical form and communicative purpose are different.',
    '1:5': 'Yusuf asks his fellow prisoners: “Are separate lords better, or Allah, the One, the Prevailing?” The form requires identifying an alternative, not a simple yes or no: تصوّر with hamzah.',
    '2:1': 'The standard account allows hamzah before affirmative or negative clauses, while هل introduces the affirmative pattern.',
    '2:3': '“Did We not expand your breast for you?” Hamzah precedes لم نشرح. The regular classical pattern taught uses ألم, not a direct substitution هل لم.',
    '3:1': 'At a coordinated opening, interrogative hamzah precedes the coordinator; هل follows it.',
    '3:3': 'In أومن كان ميتا, read أَ then وَ then مَن. This questioning hamzah leads the coordinator; the rule does not concern every word beginning with أ.',
    '3:5': 'وهل أتاك حديث موسى: “Has the story of Musa reached you?” The coordinator و comes before هل, not after it.',
    '3:7': 'The opening أَوَ... identifies hamzah; وَهَلْ... identifies هل. Use the order as an early parsing clue.',
    '4:0': 'س and سوف give a present-form verb future meaning without assigning نصب or جزم.',
    '4:2': 'The source contrasts a nearer future with س and a more distant future with سوف, pairing them with negative لا and لن. This is a traditional account, not a universal rule: grammarians dispute the time difference, and the negators are not exclusive mechanical counterparts.',
    '5:1': 'تنفيس suggests opening the verb toward future time. تسويف connects with سوّف, “put off”, and المسوّفون, “those who keep saying later”. These names do not measure a fixed delay.',
    '5:3': 'The boy growing into youth is relatively nearer; the young man reaching old age is relatively farther in this illustration. Context establishes that comparison. It does not prove that every سوف event must be later than every س event.',
  }, boxCopy: {
    '0:1': ['أأنتم أعلم أم الله؟ أكفرتم بعد إيمانكم؟', 'فهل أنتم منتهون؟ هل يستوي الذين يعلمون والذين لا يعلمون؟'],
    '2:0': ['في القاعدة المشهورة: الهمزة للإيجاب والنفي، وهل للإيجاب.'],
    '3:6': ['أَوَ... مقابل وَهَلْ...: لاحظ ترتيب الافتتاح.'],
    '4:1': ['سيقول السفهاء من الناس. سوف تعلمون.'],
  }, tableCopy: { '5:0': {
    0: ['س', 'حرف تنفيس', 'Source comparison: nearer; paired with لا.'],
    1: ['سوف', 'حرف تسويف', 'Source comparison: farther; paired with لن.'],
  } }, tableHeaders: { '5:0': ['Particle', 'Name', 'Traditional comparison, not a universal test'] }, analysisItemLabels: {
    'bank-21': { 'حرف استفهام للتصوّر': 'استفهام للتصوّر', 'مسند إليه الحكم بالخيرية': 'خبر: الخيرية', 'حرف عطف يفيد التصوّر': 'أم المتصلة', 'خبر مرفوع': 'مفعول به منصوب', 'الخيار الأول مرفوع': 'الخيار الثالث', 'حرف استقبال للمستقبل القريب': 'استقبال للقريب', 'حرف استفهام للتصديق فقط': 'استفهام للتصديق فقط', 'حرف عطف يفيد التصديق': 'عطف يفيد التصديق' },
  }, visuals: { '3:0': v('Read Arabic chunks from right to left', ['أَ + وَ', 'Hamzah before the coordinator'], ['وَ + هَلْ', 'هل after the coordinator']) } }),
  '19/l2': plan(95, 'Explanatory أيْ and أنْ', [
    [c('Restate an expression more clearly', 0, 1)],
    [c('أيْ explains a word or a clause', 0, 1), c('A word explained with أيْ', 2, 3, 4), c('A clause explained with أيْ', 5, 6)],
    [c('Conditions for explanatory أنْ', 0, 1), c('Communication without the word قال', 2, 4), c('Calling and revelation', r(3, 0, 1)), c('A charge and a letter', r(3, 2, 3))],
    [c('A preposition gives a مصدر reading', 0, 1), c('أن تذبحوا as a مصدر', 2, 3)],
    [c('Permission does not mean obligation', 0, 1, 2, 3), c('Check for a preceding complete clause', 4, 5), c('The lightened أنّ analysis', 6, 7)],
  ], [
    ['أيْ', 'Explains a word or clause.'],
    ['أنْ التفسيرية', 'Follows a complete clause implying speech, without قال in the standard account.'],
    ['A governing preposition', 'Expressed or understood before the أنْ clause: مصدرية.'],
    ['Other constructions', 'أنْ is not compulsory; آخر دعواهم takes lightened أنّ in the example.'],
  ], { copy: {
    '0:0': 'أيْ and أنْ can introduce a clearer restatement. Their permissible constructions differ.',
    '1:1': 'أيْ can explain either a مفرد or a جملة.',
    '1:3': 'الفردوس is clarified by the more familiar الجنة. This is an explanatory gloss; it need not assert that every use of the two words has identical scope.',
    '1:6': '“I sought Allah’s forgiveness, that is, I asked Allah to forgive me.” أيْ expands the first clause into a fuller statement of its meaning.',
    '2:1': 'أنْ التفسيرية introduces a clause, not a single word. A complete preceding clause conveys saying without قال in the standard account. No expressed or understood preposition may govern the أنْ clause itself.',
    '2:2': 'Calling, revealing, charging someone and writing all communicate something without necessarily using قال.',
    '2:4': 'نادى، أوحى، عهد and كتب illustrate that shared communication. A preposition elsewhere, such as إلى موسى, does not itself rule out تفسيرية: the restriction concerns a preposition governing أنْ and its clause.',
    '3:1': 'If a preposition governs أنْ and its clause, أنْ is مصدرية. A verb’s ability to take a preposition elsewhere does not alone settle every construction; examine the form used.',
    '3:3': '“Allah commands you to slaughter a cow.” The مصدر account supplies ب before أن تذبحوا, comparable to يأمركم بالعدل. The منصوب تذبحوا supports this analysis. Some editions of Jalalayn show the understood ب in the explanation.',
    '4:1': 'The conditions permit explanatory أنْ; they do not require its presence.',
    '4:3': '“Their Lord called to them: Did I not forbid you from that tree?” نادى conveys saying, but ألم أنهكما follows without أنْ. Compare وناديناه أن يا إبراهيم, where أنْ is present.',
    '4:5': 'If what precedes أنْ is only a مبتدأ still needing a خبر, it cannot supply the complete preceding clause required here. The following example uses lightened أنّ; not every non-explanatory أنْ is automatically مخففة.',
    '4:7': '“The last of their call is: Praise be to Allah, Lord of the worlds.” آخر is مبتدأ; دعواهم is مضاف إليه. The phrase still needs its خبر, so أنِ is مخففة من الثقيلة in this analysis, with an understood شأن pronoun.',
  }, boxCopy: {
    '0:1': ['حرفا التفسير: أيْ، وأنْ.'],
    '2:0': ['جملة بمعنى القول لا بلفظه؛ ولا جارّ يحكم أنْ وصلتها.'],
    '3:0': ['إذا حكم الجارّ أنْ وصلتها فهي مصدرية.'],
    '4:4': ['آخر دعواهم لم يتم خبره؛ فأنْ في المثال مخففة.'],
  }, analysisItemLabels: { 'bank-18': { 'مفعول به': 'فاعل مرفوع' } } }),
  '19/l3': plan(96, 'Kinds of Tanwin', [
    [c('Tanwin supplies a final ن sound', 0, 1, 2), c('Four standard kinds of tanwin', 3)],
    [c('تمكين: a fully declinable noun', 0, 1, 2)],
    [c('تنكير with اسم الفعل', 0, 1, 2), c('An indefinite use of a fixed name', 3, 4)],
    [c('مقابلة in the feminine plural', 0, 1, 2), c('Tanwin and إضافة', 3, 4)],
    [c('عوض for an omitted letter', 0, r(1, 0)), c('عوض for an omitted word', r(1, 1), 2), c('عوض for an omitted clause', r(1, 2))],
    [c('A poetic ending beyond noun tanwin', 0, 1, 2), c('A noun and verb share the poetic ending', 3, 4, 5)],
  ], [
    ['تمكين', 'Marks full declinability, not merely indefiniteness.'],
    ['تنكير / مقابلة', 'Indefinite use of certain fixed words; sound feminine plural comparison.'],
    ['عوض', 'Compensates for an omitted letter, word or clause.'],
    ['ترنم', 'A rhyme-related ن ending that is not restricted to nouns.'],
  ], { copy: {
    '0:0': 'Tanwin is written as a diacritic but represents an added final ن sound. This explains treating it as a حرف in the source’s classification.',
    '0:2': 'In connected reading, أحدٌ before الله الصمد has a linking ن sound with kasrah to avoid two adjacent vowelless sounds: أحدُنِ الله, a pronunciation guide, not Quranic spelling. Its name relates to نون. Other following letters have their own recitation rules.',
    '1:0': 'تنوين التمكين is also called تنوين الصرف or الأمكنية. It belongs to fully declinable معرب منصرف nouns.',
    '1:2': 'زيدٌ and رجلٌ are both fully declinable. بيتٌ is indefinite, yet its tanwin is تمكين because of its grammatical type. Indefiniteness alone does not make tanwin تنكير.',
    '2:0': 'تنوين التنكير occurs with certain أسماء الأفعال and fixed names ending in ويه.',
    '2:2': 'صهْ asks for silence about the particular speech at issue. صهٍ generalizes: “Be quiet altogether.” Tanwin distinguishes an indefinite reference.',
    '2:4': 'سيبويه refers to a particular named person. سيبويهٍ gives an indefinite “a Sibawayh”. In هذا سيبويهٍ جديد, the source uses that metaphorically for a grammarian of comparable calibre; tanwin itself marks indefiniteness, not scholarly ability.',
    '3:0': 'تنوين المقابلة belongs to the sound feminine plural in this classification.',
    '3:2': 'مسلماتٌ has tanwin corresponding to the ن of مسلمون. Both forms here stand without a following مضاف إليه. Their markers disappear in إضافة, though their behaviour with أل is not identical.',
    '3:4': 'كتابٌ stands without a مضاف إليه. In كتابُ زيدٍ, إضافة removes tanwin from كتاب. This contrast explains the example; lack of tanwin alone does not prove إضافة in every noun.',
    '4:0': 'تنوين العوض substitutes for a letter, word or whole clause. Begin with a letter.',
    '5:0': 'Some grammarians add تنوين الترنم beyond the four noun-specific types. It concerns poetic delivery rather than nominal case or definiteness.',
    '5:2': 'In an open rhyme, the rhyme consonant is vowelled and can be followed by a lengthening letter. The ن ending replaces that lengthening in the cited account, often called “cutting off” الترنم. It can occur on a noun, verb or particle.',
    '5:4': '“Reduce your blame and reproach, and say, if I was right, ‘he was right’.” العتابن is a noun; أصابن a past verb. The ن endings replace rhyme-lengthened العتابا and أصابا here, not ordinary noun tanwin spreading to a verb.',
    '5:5': 'This completes the source’s section on non-governing particles.',
  }, boxCopy: { '0:1': ['أصل التنوين نون ساكنة تلحق آخر الاسم لفظا.'], '3:3': ['كتابٌ بلا إضافة؛ كتابُ زيدٍ بحذف التنوين.'] }, tableCopy: { '4:1': {
    0: ['حرف', 'غواشٍ', 'The ي of غواشي is omitted in رفع and جر in this analysis; نصب has غواشيَ. Do not start from an already nunated غواشيٌ.'],
    1: ['كلمة', 'كلٌّ آمن', 'Understood كلّ أحدٍ آمن: tanwin replaces the omitted مضاف إليه.'],
    2: ['جملة', 'ويومئذٍ يفرح المؤمنون', 'Tanwin on إذ replaces its following clause: يوم إذ كان كذا, “the day when that occurred”.'],
  } }, analysisLabels: { 'مبتدأ يحمل تنوين تعويض عن كلمة (أَحَدٍ) محذوفة': 'مبتدأ؛ تنوين عوض عن أحدٍ', 'مبتدأ يحمل تنوين تعويض عن جملة (يَوْمَ إِذْ كَانَ كَذَا) محذوفة': 'مبتدأ؛ تنوين عوض عن جملة', 'ظرف يحمل تنوين تعويض عن جملة محذوفة': 'ظرف؛ تنوين إذ عوض عن جملة' }, analysisItemLabels: { 'bank-19': { 'خبر مرفوع': 'مفعول به منصوب', 'خبر': 'جملة فعلية في محل رفع خبر' } }, diagramLabels: { '4:2': { 'مبتدأ يحمل تنوين تعويض عن كلمة (أَحَدٍ) محذوفة': 'مبتدأ؛ تنوين عوض عن أحدٍ', 'خبر': 'جملة فعلية في محل رفع خبر' } }, visuals: { '0:1': v('Four noun-specific functions', ['تمكين / تنكير', 'Declinability or indefiniteness'], ['مقابلة / عوض', 'Correspondence or compensation']) } }),
};

export const checks = {
  '19/l1': [q('Which two particles introduce questions?', ['الهمزة وهل.', 'السين وسوف.', 'أيْ وأنْ.', 'الفاء واللام.'], 'Distinguish questioning from future meaning.'),
    q('What kind of question offers separate lords or Allah as alternatives?', ['تصوّر, introduced by hamzah.', 'تصديق, with either particle.', 'تصوّر, introduced only by هل.', 'تصديق, introduced only by هل.'], 'A simple yes or no does not identify the alternative.'),
    q('Under the regular rule taught, can هل replace hamzah in ألم نشرح?', ['No; هل uses the affirmative pattern here.', 'Yes; both freely introduce negation.', 'Yes, because the verb is present.', 'No; hamzah also forbids negation.'], 'Hamzah precedes لم in the example.'),
    q('How do hamzah and هل combine with a coordinator?', ['Hamzah before it; هل after it.', 'Both before it.', 'Both after it.', 'هل before it; hamzah after it.'], 'Compare أَوَ and وَهَلْ.'),
    q('Which near/far comparison does the source present as a traditional account?', ['س nearer, paired with لا; سوف farther, paired with لن.', 'س farther; سوف nearer.', 'Only س marks future meaning.', 'No comparison is presented at all.'], 'The account is disputed, not a universal timing rule.'),
    q('In the boy/youth illustration, which marks the nearer change?', ['س, called حرف تنفيس.', 'سوف, called حرف تنفيس.', 'س, called حرف تسويف.', 'سوف, called حرف تسويف.'], 'Read the illustration’s relative times.')],
  '19/l2': [q('Name the two explanatory particles.', ['أيْ وأنْ.', 'الهمزة وهل.', 'السين وسوف.', 'لا وإنْ.'], 'They introduce a restatement.'),
    q('Can أيْ explain both الفردوس and استغفرت الله?', ['Yes: a word or a clause.', 'Only the single word.', 'Only the whole clause.', 'Only verbal clauses, never nouns.'], 'Its range is broader than أنْ’s.'),
    q('Which communication type is وناديناه أن يا إبراهيم?', ['Calling: النداء.', 'Revelation: الوحي.', 'A charge: العهد.', 'Writing: الكتابة.'], 'نادى conveys speaking without قال.'),
    q('Why is أن تذبحوا مصدرية in the account taught?', ['It forms the clause governed by understood ب after يأمر.', 'ذبح cannot form a clause.', 'بقرة is an إضافة.', 'أمر never conveys communication.'], 'Compare يأمركم بالعدل and the منصوب تذبحوا.'),
    q('What is أنِ in وآخر دعواهم أن الحمد لله...?', ['Lightened أنّ; the preceding subject still needs a predicate.', 'Explanatory, simply because دعوى involves words.', 'مصدرية after an expressed preposition.', 'Meaningless زائد.'], 'آخر دعواهم is not a complete preceding clause.')],
  '19/l3': [q('Why does the source treat tanwin as a حرف?', ['It represents an added final ن sound.', 'It always changes lexical meaning.', 'It only attaches to verbs.', 'It is always identical to poetic ترنم.'], 'Distinguish the written mark from its sound.'),
    q('Why is the tanwin of بيتٌ تمكين?', ['It is a fully declinable noun.', 'Every indefinite word has تمكين.', 'بيت can never take أل.', 'تمكين only belongs to proper names.'], 'Grammatical type determines the category.'),
    q('What changes in the example هذا سيبويهٍ جديد?', ['The name has an indefinite use: “a Sibawayh”.', 'A verb becomes a noun.', 'Nothing changes in reference.', 'A fixed name becomes fully declinable.'], 'The comparison to a skilled grammarian comes from context.'),
    q('What corresponds to the tanwin in مسلماتٌ?', ['The ن of مسلمون.', 'An ألف.', 'A تاء.', 'A كسرة.'], 'This explains the name مقابلة.'),
    q('What does tanwin replace in كلٌّ آمن?', ['The omitted word أحدٍ.', 'A letter ي.', 'An entire clause.', 'Nothing: this is تمكين.'], 'Expand it to كلّ أحدٍ آمن.'),
    q('What do العتابن and أصابن show about poetic ترنم?', ['It concerns rhyme delivery and can occur on a verb.', 'Both are nouns with تمكين.', 'Both are sound feminine plurals.', 'أصاب has become a noun.'], 'One example is a noun; the other is a past verb.')],
};

export const quizzes = {
  '19/l1': [q('Which question type is excluded from هل in the standard distinction?', ['تصوّر between named alternatives.', 'تصديق, a polar question.', 'Neither: هل cannot ask anything.', 'Both types are equally available.']),
    q('What does ألم نشرح show in the standard comparison?', ['Hamzah can precede negation; هل uses the affirmative pattern.', 'Both freely precede any negation.', 'هل can precede negation but hamzah cannot.', 'Neither can precede negation.']),
    q('Can the opening وهل be reversed to هل و in the pattern taught?', ['No; هل follows the coordinator.', 'Yes; the order is free.', 'Yes, only for metre in this rule.', 'No; هل cannot combine with و at all.']),
    q('In سيقول, which particle and traditional pairing does the source give?', ['س, paired with لا.', 'سوف, paired with لن.', 'س, paired with لن.', 'سوف, paired with لا.']),
    q('What name connects سوف with سوّف?', ['حرف تسويف.', 'حرف تنفيس.', 'حرف تصديق.', 'حرف تصوّر.']),
    q('What is the form of أأرباب متفرقون خير أم الله...?', ['تصوّر introduced by hamzah.', 'تصديق introduced by هل.', 'تصوّر introduced by هل.', 'تصديق introduced by hamzah.'])],
  '19/l2': [q('What can أيْ explain?', ['A word or a clause.', 'Only a word.', 'Only a clause.', 'Neither.']),
    q('What does explanatory أنْ introduce?', ['A clause, not an isolated word.', 'Only one word.', 'A word or clause equally.', 'A governing preposition.']),
    q('What precedes explanatory أنْ in the standard rule?', ['A complete clause implying speech without قال.', 'Any isolated word.', 'A preposition governing its clause.', 'Nothing is required.']),
    q('Why is أن تذبحوا مصدرية in the adopted account?', ['An understood ب governs its مصدر clause after يأمر.', 'ذبح itself lacks a speech meaning.', 'بقرة is a single word.', 'A مضاف إليه directly precedes أنْ.']),
    q('What does وناداهما ربهما ألم أنهكما show?', ['Explanatory أنْ is permitted, not compulsory.', 'نادى cannot convey speech.', 'أنْ is always compulsory.', 'The example contains no complete preceding clause.']),
    q('What precedes أنِ in وآخر دعواهم أن الحمد لله?', ['A subject awaiting a predicate; أنِ is lightened أنّ.', 'A complete clause; أنِ is explanatory.', 'An understood preposition; أنِ is مصدرية for that reason.', 'Nothing; أنِ is purposeless.'])],
  '19/l3': [q('What sound underlies ordinary tanwin?', ['An added final ن, originally vowelless.', 'An initial hamzah.', 'A final د.', 'A written but never pronounced ن.']),
    q('What determines تمكين in بيتٌ?', ['Its fully declinable grammatical type.', 'Beginning with أل.', 'Gender alone.', 'Having more than three letters.']),
    q('What does the tanwin of سيبويهٍ mark in the example?', ['An indefinite use of the name.', 'Only a change from fixed to declinable.', 'A feminine form.', 'No change in reference.']),
    q('What corresponds to مقابلة tanwin in مسلماتٌ?', ['The ن of مسلمون.', 'The و of مسلمون.', 'The م of مسلمون.', 'Nothing.']),
    q('What is omitted after إذ in ويومئذٍ يفرح المؤمنون?', ['A clause, understood from context.', 'One letter.', 'The word أحدٍ.', 'Nothing: it is ordinary تمكين.']),
    q('Why can poetic ترنم occur on a noun, verb or particle?', ['It is a rhyme-related ending, not nominal case or indefiniteness.', 'It is restricted to nouns.', 'It replaces every ordinary tanwin in poetry.', 'It occurs only on past verbs.'])],
};
