import { card as c, rows as r, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '12/l1': plan(56, 'Kasrah in إنّ', [
    [c('Emphasis with اسم منصوب and خبر مرفوع', 0, 1, 2, 3, 4), c('Choose the hamzah by its position', 5, 6, 7)],
    [c('At the actual start of speech', 0, 1), c('Still a beginning after ألا or كلّا', 2, 3, 4)],
    [c('The answer to an oath', 0, 1, 2)],
    [c('Quoted speech remains a clause', 0, 1, 2)],
    [c('A self-contained clause of حال', 0, 1, 2)],
    [c('حتى opening a fresh sentence', 0, 1, 2), c('Analyse the sentence after حتى', 3)],
  ], [
    ['إنّ', 'Emphasis, تأكيد or تحقيق; اسم منصوب and خبر مرفوع.'],
    ['Kasrah', 'موضع الجملة: a real beginning or a beginning in grammatical status.'],
    ['حكما', 'After ألا / كلا, in an oath’s answer, quotation or حال clause.'],
    ['حتى الابتدائية', 'Introduces a new clause, unlike prepositional حتى.'],
  ], { copy: {
    '0:0': 'Seven particles in this category give their اسم نصب and خبر رفع. إنّ is first.',
    '0:2': 'Its emphasis is called تأكيد or تحقيق.',
    '0:4': '“Allah is Forgiving, Merciful.” اللهَ is اسم إنّ; غفورٌ and رحيمٌ are مرفوع predicates.',
    '0:5': 'إنّ and أنّ are not freely interchangeable spellings.',
    '0:7': 'Use إنّ where its clause stands as a sentence, truly initial or treated as initial. أنَّ fills a noun-equivalent position, explored later.',
    '1:0': 'حقيقة الابتداء: nothing precedes إنّ. “We sent down the Book to you in truth.”',
    '1:2': 'ألا alerts; كلّا rebukes. Neither occupies a subject, object or predicate role. The clause still counts as beginning: ابتداء حكما.',
    '1:4': '“It is they who are the corrupters.” “No! Man does transgress.”',
    '2:0': 'An oath’s answer also counts as ابتداء حكما.',
    '2:2': '“By the wise Quran, you are among the messengers.” والقرآن الحكيم is the oath; إنك لمن المرسلين answers it. The answer has its own standing despite being inside the larger oath structure.',
    '3:0': 'After a verb of saying, distinguish the quotation itself.',
    '3:2': '“He said, ‘I am Allah’s servant.’” إني عبد الله is مقول القول, a whole clause occupying قال’s object position. It retains its own sentence form, so it begins with إنّ.',
    '4:0': 'A clause introduced by واو الحال remains self-contained.',
    '4:2': 'The verse condemns the false claim “Allah has begotten”: “They are liars.” وإنهم لكاذبون describes their state while speaking. The clause occupies حال’s نصب position but retains sentence form, hence إنّ.',
    '5:0': 'Distinguish prepositional حتى from حتى الابتدائية.',
    '5:2': '“People repented, even the polytheist.” إن المشرك تاب is a fresh clause after حتى, not a noun governed by it. Hence kasrah.',
  }, boxCopy: { '0:1': ['إنّ للتأكيد أو التحقيق؛ تنصب الاسم وترفع الخبر.'] } }),
  '12/l2': plan(57, 'More Positions for إنّ', [
    [c('A relative clause after ما', 0, 1, 2), c('Two roles, the same kasrah', 3, 4)],
    [c('A clause describing an indefinite noun', 0, 1, 2)],
    [c('لام suspends the verb’s direct government', 0, 1, 2)],
    [c('Restriction with إلا followed by a clause', 0, 1, 2), c('Contrast an exception with أنّ', 3, 4)],
    [c('Why إنّ is preferred after حيث', 0, 1, 2, 3, 4)],
    [c('What does the subject name?', 0), c('A whole clause gives the judgement', 1, 2), c('An abstract subject takes a noun-equivalent', 3, 4), c('Analyse the inner إنّ clause', 5)],
  ], [
    ['Clauses', 'إنّ can open صلة, نعت or a predicate clause.'],
    ['تعليق', 'لام المزحلقة suspends يعلم’s direct government.'],
    ['إلا / حيث', 'Restrictive إلا takes a clause; حيث prefers one.'],
    ['عين / معنى', 'Entity: a clause. Abstract meaning: a possible مصدر مؤول.'],
  ], { copy: {
    '0:0': 'إنّ can open the صلة of a relative pronoun.',
    '0:2': '“We gave him treasures whose keys burdened a company of strong men.” Read ما as موصول: إن مفاتحه لتنوء... is its صلة.',
    '0:4': 'With relative ما, the clause is صلة. With indefinite ما meaning شيء, it is نعت. Both are clause positions, so the spelling remains إنّ.',
    '1:0': 'A clause may directly describe an indefinite noun.',
    '1:2': '“I looked at a man who is righteous.” إنه صالح is نعت for رجل, a complete clause used as a description. Hence إنّ.',
    '2:0': 'يعلم can take a noun-equivalent with أنّ. But emphatic لام on the predicate, لام المزحلقة, causes تعليق: direct verbal government is suspended. The clause keeps its object position, with إنّ instead of أنّ.',
    '2:2': '“Allah knows that you are His messenger.” لرسوله supplies the suspending لام.',
    '3:0': 'Here إلا restricts the statement, حصر, rather than excluding a noun from a group.',
    '3:2': '“We sent no messengers before you except that they ate food and walked in markets.” The continuation is a clause with إنّ.',
    '3:4': '“He is brave, except that he is not generous.” Here the exception is a noun-equivalent with أنّ. The contrast concerns what follows إلا in each construction.',
    '4:0': 'Kasrah after حيث is preferred in the account here.',
    '4:2': '“I sat where Ali is sitting.”',
    '4:4': 'حيث is مضاف. The stronger view requires a following clause, hence إنّ. Another permits إضافة to a noun-equivalent too, allowing أنّ. The choice reflects that disagreement.',
    '5:0': 'اسم عين names a person, group or entity; اسم معنى names an abstraction. A clause can predicate something about an entity; a مصدر مؤول can match an abstract meaning.',
    '5:2': 'The named groups are believers, Jews, Sabians, Christians, Magians and polytheists. “Allah will judge between them on Resurrection Day.” The second إنّ clause is خبر of the first: it gives a judgement about those people.',
    '5:4': '“What is hoped is that he is forgiven.” المرجو denotes the hoped-for meaning. أنه مغفور is a noun-equivalent predicate, unlike a complete clause describing people.',
  }, boxCopy: { '0:3': ['ما موصولة: الجملة صلة. ما نكرة بمعنى شيء: الجملة نعت.'],
    '4:3': ['حيث مضاف: إلى جملة عند فريق، وإلى مفرد أيضا عند آخر.'] },
    visuals: { '5:0': v('Match the predicate to what is named', ['رجل', 'An entity, اسم عين'], ['الرجاء', 'An abstraction, اسم معنى']) } }),
  '12/l3': plan(58, 'Fatḥah in أنّ', [
    [c('A noun-equivalent with added emphasis', 0, 1, 2), c('Comparing two expressions of knowledge', 3, 4), c('A slot that a noun could occupy', 5, 6)],
    [c('The مصدر مؤول as فاعل', 0, 1), c('The مصدر مؤول as نائب فاعل', 2, 3)],
    [c('An object of knowing', 0, 1), c('An outer predicate omitted after لو', 2, 3, 4, 5), c('A delayed مبتدأ after a fronted خبر', 6, 7)],
    [c('The predicate of an abstract subject', 0, 1, 2), c('A noun-equivalent governed by باء', 3, 4)],
    [c('A مضاف إليه after مثل', 0, 1, 2, 3), c('A time reference after مذ', 4, 5), c('A duration introduced by ما', 6, 7)],
    [c('Joined to a noun by عطف', 0, 1, 2), c('Restating a noun as بدل', 3, 4)],
  ], [
    ['أنّ', 'حرف مصدر and حرف تأكيد together.'],
    ['موضع المفرد', 'A noun-equivalent can be subject, passive subject, object, مبتدأ or خبر.'],
    ['Other positions', 'After a preposition, in إضافة, or fixing a time/duration.'],
    ['A تابع', 'The noun-equivalent may follow a noun through عطف or بدل.'],
  ], { copy: {
    '0:0': 'أنّ is the second particle in the seven-member category.',
    '0:2': 'Compare قيامك; ظننتك قائما with two objects; ظننت قيامك; and ظننت أنك قائم. أنّ turns its clause into a noun-equivalent and adds emphasis. That makes the last formulation strongest in this comparison.',
    '0:4': '“We know your heart is constrained by their words” uses أنّ. “If you know them to be believers, do not return them” has a second object, مؤمنات. The course uses this contrast to illustrate the emphasis أنّ adds.',
    '0:6': 'أنّ fills موضع المفرد: subject, passive subject, object, مبتدأ, خبر, مضاف إليه and similar noun positions. إنّ instead occupies a clause position.',
    '1:1': '“Until it becomes clear that it is the truth.” أنه الحق is the source-equivalent فاعل of يتبين.',
    '1:3': '“It was revealed to me that a group of jinn listened.” أنه استمع نفر... is نائب فاعل of passive أوحي.',
    '2:1': '“They know it is the truth from their Lord.” The source-equivalent fills يعلمون’s object construction.',
    '2:3': '“Had they believed and feared Allah, a reward from Allah would be better.”',
    '2:5': 'The whole أنّ construction is مبتدأ with omitted outer خبر, such as ثابت. Inside it, آمنوا واتقوا is the stated خبر أنّ, usually past-tense after لو.',
    '2:7': '“Of His signs is that you see the earth stilled.” من آياته is خبر مقدم; أنك ترى الأرض خاشعة is مبتدأ مؤخر.',
    '3:0': 'Recall the contrast between a person/entity and an abstract meaning.',
    '3:2': '“What is hoped is that he is forgiven.” The abstract المرجو has the noun-equivalent أنه مغفور as its predicate.',
    '3:4': '“Bear witness that we are Muslims.” أنّ and its clause form the noun-equivalent governed by باء, so the hamzah has fatḥah.',
    '4:1': '“It is truth, as surely as you speak.”',
    '4:3': 'ما adds emphasis. Without it: مثل أنكم تنطقون. The source-equivalent is مضاف إليه of مثل, a noun position.',
    '4:5': '“He has not abandoned prayer since returning from Hajj.” The source-equivalent fixes time after مذ, a time noun or, in another use, a preposition.',
    '4:7': '“Fast as long as you are able.” In this account, ما is مصدرية ظرفية: the following construction fixes the duration of fasting as a noun-equivalent.',
    '5:0': 'A source-equivalent can also be تابع to a noun.',
    '5:2': '“Remember My favour upon you and that I preferred you over the worlds.” وأني فضلتكم is joined by عطف to نعمتي.',
    '5:4': '“Allah promised you one of the two groups, that it would be yours.” أنها لكم is بدل of إحدى الطائفتين, restating the promise.',
  }, boxCopy: { '0:5': ['تفتح همزة أنّ في موضع المفرد، بتأويلها مع ما بعدها بمصدر.'],
    '2:4': ['الخبر الخارجي محذوف، وخبر أنّ الداخلي مذكور.'] } }),
};

export const checks = {
  '12/l1': [q('Which hamzah belongs in موضع الجملة?', ['Kasrah: إنّ opens the clause.', 'Fatḥah: it is a noun position.', 'Either, regardless of position.', 'Kasrah only after an oath.'], 'Distinguish a clause from a noun-equivalent.'),
    q('Why does إنّ keep kasrah after ألا or كلّا?', ['ابتداء حكما; neither particle occupies a clause role.', 'Nothing precedes it, حقيقة.', 'Neither can count as a beginning.', 'Only ألا permits it, never كلّا.'], 'A preceding particle need not remove the clause’s initial status.'),
    q('Why kasrah in والقرآن الحكيم إنك لمن المرسلين?', ['The oath’s answer has independent standing, حكما.', 'An oath forces fatḥah.', 'والقرآن is مبتدأ.', 'The answer literally starts the whole utterance.'], 'Locate the oath and its answer.'),
    q('Why إنّي after قال despite the quotation’s object position?', ['Quoted speech retains its own clause form.', 'قال forces kasrah on anything after it.', 'Every pronoun requires kasrah.', 'A quotation can never be expressed as a مصدر.'], 'Separate a clause’s function from its internal form.'),
    q('Why إنّ in the حال clause وإنهم لكاذبون?', ['It remains a self-contained clause within its نصب position.', 'حال always has رفع.', 'واو الحال is واو القسم.', 'حال cannot follow واو.'], 'حال can be expressed by a whole clause.'),
    q('Which حتى precedes إن المشرك تاب here?', ['ابتدائية, opening a fresh clause.', 'Prepositional, governing المشرك.', 'Conjunctive, joining المشرك to الناس.', 'It has no function.'], 'The continuation is an entire sentence.')],
  '12/l2': [q('Does relative versus indefinite ما change إنّ in the treasure example?', ['No; صلة or نعت remains a clause.', 'Only relative ما takes إنّ.', 'Only indefinite ما takes إنّ.', 'Neither allows إنّ.'], 'Both proposed roles call for a clause.'),
    q('What is إنه صالح after نظرت إلى رجل?', ['A نعت clause for رجل, with إنّ.', 'حال requiring أنّ.', 'A second object requiring أنّ.', 'بدل requiring أنّ.'], 'رجل is indefinite and receives a description.'),
    q('What allows إنّ in يعلم إنك لرسوله?', ['لام المزحلقة triggers تعليق.', 'Every present verb requires إنّ.', 'الله names an entity.', 'إضافة in رسوله forces kasrah.'], 'Look for emphatic لام on the predicate.'),
    q('Which spelling follows the two إلا constructions taught here?', ['حصر: إنّ. Exception: أنّ.', 'Both إنّ.', 'Both أنّ.', 'حصر: أنّ. Exception: إنّ.'], 'Distinguish the restricted clause from the noun-equivalent exception.'),
    q('Why is إنّ preferred after حيث in this account?', ['The stronger view requires a clause; another allows a noun-equivalent.', 'حيث always requires a noun-equivalent.', 'There is no alternative view.', 'Only when حيث means “since”.'], 'The dispute is about إضافة after حيث.'),
    q('Which category names people/entities, contrasting abstractions?', ['اسم عين; its opposite is اسم معنى.', 'اسم صفة versus اسم ذات.', 'اسم جامد versus اسم مشتق.', 'اسم علم versus اسم نكرة.'], 'Distinguish what the subject names, not its spelling.')],
  '12/l3': [q('Why is ظننت أنك قائم emphatic in the given comparison?', ['أنّ combines مصدرية with تأكيد.', 'It always precedes a past verb.', 'It requires two explicit objects.', 'It occurs only after heart verbs.'], 'It both nominalises and reinforces.'),
    q('Which pairing is right: يتبين أنه الحق / أوحي أنه استمع نفر?', ['فاعل of يتبين; نائب فاعل of أوحي.', 'نائب فاعل; فاعل.', 'Both فاعل.', 'Both نائب فاعل.'], 'The second verb is passive.'),
    q('In the offered لو analysis, what is the whole أنهم آمنوا واتقوا?', ['مبتدأ with an omitted outer خبر, such as ثابت.', 'مفعول به.', 'فاعل only.', 'خبر of an omitted مبتدأ.'], 'Distinguish the whole مصدر مؤول from its internal predicate.'),
    q('Why أنّ in المرجو أنه مغفور?', ['المرجو names an abstract meaning, matching the noun-equivalent.', 'It names a concrete person.', 'Every اسم مفعول forces أنّ.', 'المرجو is مبني.'], 'What is hoped is a meaning, not a person.'),
    q('Why أنّ after مذ in the Hajj example?', ['The noun-equivalent supplies its time reference.', 'مذ always requires إنّ.', 'It is an unrelated مبتدأ.', 'مذ never permits a مصدر مؤول.'], 'Identify the time being fixed.'),
    q('Why fatḥah in وأني فضلتكم joined to نعمتي?', ['It is تابع to a noun and shares its noun position.', 'All عطف forces fatḥah.', 'نعمتي is اسم أنّ.', 'التي forces أنّ anywhere later.'], 'Look at the noun being coordinated.')],
};
export const quizzes = {
  '12/l1': [q('Kasrah in إنّ belongs in which position?'), q('What kind of beginning is إنا أنزلنا إليك الكتاب بالحق?'),
    q('What do ألا and كلّا share before إنّ?', ['Neither occupies a clause role; a beginning remains.', 'Both govern جر.', 'Both are conjunctions.', 'Both force fatḥah on verbs.']),
    q('What is إنك لمن المرسلين after والقرآن الحكيم?'), q('Why إنّي after قال?', ['The quotation retains its own clause form.', 'قال is specifically past tense.', 'عبد الله is definite.', 'إني always forces kasrah in any position.']),
    q('Which حتى precedes إن المشرك تاب?', ['ابتدائية, opening a clause.', 'Prepositional, governing المشرك.', 'Conjunctive, joining the two nouns.', 'Causal, explaining the repentance.'])],
  '12/l2': [q('With relative ما, what is إن مفاتحه لتنوء...?'), q('What role and spelling belong to إنه صالح after رجل?'),
    q('Why إنّ in والله يعلم إنك لرسوله?', ['لام المزحلقة causes تعليق.', 'يعلم is past tense.', 'لرسوله has جر.', 'الله is بدل.']),
    q('Which إلا appears in هو شجاع إلا أنه ليس بكريم?'), q('Which alternative allows أنّ after حيث?', ['إضافة to a noun-equivalent as well as a clause.', 'No clause can follow حيث.', 'There is no alternative.', 'حيث always forces أنّ.']),
    q('The named groups in the judgement verse are persons, belonging to which category?', ['اسم عين.', 'اسم معنى.', 'اسم صفة.', 'الاسم المؤول.'])],
  '12/l3': [q('Why is ظننت أنك قائم more emphatic in this comparison?', ['أنّ combines مصدرية and تأكيد.', 'قيامك is مبني.', 'ظننت rejects a plain مصدر.', 'قيامك can only be فاعل.']),
    q('Which is not a noun position for أنّ?'), q('What is أنه استمع نفر after passive أوحي?'),
    q('In the offered لو analysis, what is the outer خبر of the whole مصدر مؤول أنهم آمنوا واتقوا?', ['Omitted, understood as ثابت.', 'لمثوبة itself.', 'No predicate is needed at all.', 'آمنوا واتقوا, with no outer predicate.']),
    q('Which kind of meaning does المرجو name here?'), q('What is أنها لكم after إحدى الطائفتين?')],
};

Object.assign(plans, {
  '12/l4': plan(59, 'Where Both إنّ and أنّ Are Possible', [
    [c('The same reason, two grammatical forms', 0, 1, 2, 3)],
    [c('Mercy and a conditional promise', 0, 1), c('Two forms after the conditional فاء', 2)],
    [c('Fatḥah is common after لا جرم', 0, 1), c('The development of لا جرم', 2), c('Three offered analyses of لا جرم', 3)],
    [c('Rejoicing in favour, bounty and certainty', 0, 1), c('Join a noun or begin another clause', 2)],
    [c('Sudden discovery with إذا الفجائية', 0, 1), c('Analyse the clause of discovery', 2)],
  ], [
    ['Both spellings', 'Each requires its own analysis: clause or noun-equivalent.'],
    ['Reasons and conditions', 'Independent explanation, or a noun-equivalent with understood structure.'],
    ['لا جرم', 'Fatḥah is common; kasrah treats it as an oath-like expression.'],
    ['واو / إذا', 'A noun or clause can follow واو here; both forms follow sudden-discovery إذا.'],
  ], { copy: {
    '0:0': 'Some positions permit both, with different إعراب.',
    '0:3': '“Seek Allah’s forgiveness; He is Forgiving, Merciful.” إنّه gives a fresh explanatory clause, grammatically separate. أنّه implies لأنّه: a reason attached through omitted لام. Both explain the command.',
    '1:1': '“Your Lord has decreed mercy: whoever does wrong, then repents and reforms, finds forgiveness and mercy.” The first أنّ restates الرحمة as بدل. The second follows فاء الجزاء and admits the two forms discussed next.',
    '1:2': '<b>إنّه</b>: a fresh clause indicating the understood answer, “Allah accepts his repentance and has mercy.”<br><b>أنّه</b>: a مصدر مؤول as مبتدأ with omitted خبر, فمغفرته ورحمته للتائب; or as خبر of omitted الأمر, فالأمر أنه غفور رحيم. The resulting sentence supplies or indicates the answer.',
    '2:1': '“Allah surely knows what they conceal and proclaim.” Fatḥah is most common here; kasrah is also attested.',
    '2:3': '<b>With أنّ</b>: لا جرم is verb-like, “It is inevitable”, with the source-equivalent as فاعل. Alternatively لا negates the genus, جرم is its اسم, and the source-equivalent is خبر.<br><b>With إنّ</b>: لا جرم functions like an oath; the following clause is its answer.',
    '3:1': '“They rejoice in Allah’s favour and bounty, and that He does not lose believers’ reward.” نعمة and فضل are nouns already available for coordination.',
    '3:2': '<b>أنّ</b>: coordinate the noun-equivalent with نعمة وفضل, a third thing rejoiced in.<br><b>إنّ</b>: coordinate a whole clause with يستبشرون, or begin a fresh assertion. The attachment changes with the spelling.',
    '4:1': '“I went out, and suddenly Saʿid was standing!” Both إنّ and أنّ are possible after إذا الفجائية. The course cites ordinary Arabic usage for this construction, not a Quranic occurrence.',
  }, boxCopy: { '0:1': ['يجوز الوجهان في مواضع معينة، ولكل وجه إعرابه.'],
    '2:2': ['جرم originally means “earned a sin”. The course traces لا جرم from that setting to oaths and necessity, then plain emphasis.',
      'لا جرم أنك ذاهب: “You are inevitably going.” لا جرم لتقومن: “You will surely stand.”'] },
    visuals: { '1:1': v('Locate the understood outer structure', ['فَمَغْفِرَتُهُ وَرَحْمَتُهُ لِلتَّائِبِ', 'Restored outer predicate'], ['فَالْأَمْرُ أَنَّهُ غَفُورٌ رَحِيمٌ', 'Restored outer subject']),
      '2:2': v('What follows لا جرم?', ['أنّ', 'A noun-equivalent'], ['إنّ', 'An oath’s answer']),
      '3:1': v('Choose the attachment', ['نعمة وفضل', 'Another noun-equivalent: أنّ'], ['يستبشرون...', 'Another clause: إنّ']) } }),
  '12/l5': plan(60, 'Further Rules of إنّ and أنّ', [
    [c('Keep conditional مَن first', 0, 1, 2, 3, 4)],
    [c('A phrase-predicate may precede a definite اسم', 0, 1, 2, 3, 4), c('The indefinite pattern taught here', 5, 6, 7)],
    [c('First complete the predicate', 0, 1), c('Coordinate with the visible نصب', 2, 3), c('Coordinate with the underlying رفع', 4, 5), c('A further comparison with رسوله', 6, 7)],
    [c('Negation can license باء', 0, 1, 2, 3)],
    [c('أنّ with the sense of لعلّ', 0, 1, 2), c('The same sense in ordinary usage', 3, 4)],
  ], [
    ['صدر الكلام', 'Conditional من keeps its initial position. Relative من differs.'],
    ['شبه جملة', 'Fronting: allowed with definite; required in the indefinite pattern shown.'],
    ['Coordination', 'After the predicate: visible نصب or the stated underlying رفع.'],
    ['Other uses', 'Negation can license باء; أنّ can mean لعلّ.'],
  ], { copy: {
    '0:0': 'A restriction on the اسم.',
    '0:2': 'Conditional من must come first; إنّ or أنّ would displace it.',
    '0:4': '“Whoever stays silent has been saved.” فقد emphasises the answer. Relative من is a different construction.',
    '1:0': 'A جار ومجرور or ظرف predicate has special ordering rules.',
    '1:2': 'With a definite اسم, placing it between إنّ and the اسم is allowed.',
    '1:4': '“To Us is their return.” إيابهم is definite by إضافة to a pronoun, so fronted إلينا is permissible.',
    '1:5': 'The simple indefinite pattern here requires the phrase-predicate first.',
    '1:7': '“In that is a lesson for those with insight.” في ذلك is خبر مقدم before the indefinite عبرة. This is the fronting pattern illustrated by the rule.',
    '2:1': 'Compare إن زيدا قائم وعمرَ, where the predicate is already complete, with إن زيدا وعمرَ قائمان, where coordination precedes it. The following alternatives concern the first order.',
    '2:3': '“Allah’s promise is true, and the Hour is beyond doubt.” In Hamzah’s reading, الساعةَ follows the visible نصب of وعدَ, اسم إنّ. The alternative follows the underlying initial رفع instead.',
    '2:5': '“Are we to be raised, and our forefathers?” آباؤنا has رفع. This account coordinates with the original مبتدأ position. Some assign that position to إنّ with its اسم, others to the اسم alone.',
    '2:7': 'In the announcement that Allah and His Messenger are free of the polytheists, رسولهُ follows the underlying رفع in this account. Another reading has رسولهَ, following the visible نصب of اللهَ. The meaning agrees; the case analysis differs.',
    '3:1': 'Compare added باء with ليس and ما المشبهة بليس.',
    '3:3': '“Do they not see that Allah, who created the heavens and earth without tiring, can revive the dead?” لم in أولم يروا licenses باء on بقادر, خبر أنّ.',
    '4:2': '“What makes you realise that perhaps, when it comes, they will not believe?” In this interpretation أنها means لعلها, expectation rather than the usual plain emphasis.',
    '4:4': '“Go to the market; perhaps you will buy me something.” أنك here conveys لعلك.',
  }, boxCopy: { '0:1': ['لا يكون اسم إنّ أو أنّ مما يلزم صدر الكلام.'],
    '0:3': ['مَن صمت فقد نجا. لا: إنّ مَن صمت نجا (مَن شرطية).'],
    '1:1': ['معرفة: توسط شبه الجملة جائز. وفي نمط النكرة هنا: واجب.'],
    '2:0': ['استكمال الخبر: وقوع المعطوف بعد الخبر، لا قبله.'],
    '3:0': ['للنفي قبل أنّ أثر في خبرها.'] },
    visuals: { '2:0': v('Where is the coordinated noun?', ['إنّ زيدًا قائمٌ وعمرَ', 'After the complete predicate'], ['إنّ زيدًا وعمرَ قائمان', 'Before the predicate']) } }),
  '12/l6': plan(61, 'Comparison, Correction and Expectation', [
    [c('كأنّ makes a comparison', 0, 1, 2, 3)],
    [c('A more emphatic comparison than كاف', 0, 1), c('Compound or simple particle?', 2, 3)],
    [c('لكنّ removes a possible false impression', 0, 1, 2, 3), c('Lack of strength does not mean cowardice', 4, 5)],
    [c('واو often precedes لكنّ', 0, 1, 2, 3), c('Analyse the correction with لكنّ', 4)],
    [c('لعلّ expresses expectation', 0, 1, 2), c('Hope for something welcome', 3, 4, 5), c('Apprehension about something feared', 6, 7),
      c('The purpose of a command', 8, 9), c('Hope for protection or an “as if” rebuke', 10, 11)],
    [c('Joining a لعلّ clause to a purpose', 0, 1), c('Two purposes of revelation', 2, 3), c('A shorter form: علّ', 4, 5)],
  ], [
    ['كأنّ', 'Emphatic likeness; analysed as compound or simple.'],
    ['لكنّ', 'استدراك removes an impression left by the previous statement.'],
    ['لعلّ', 'ترجّي, إشفاق, purpose, or the “as if” sense in the offered reading.'],
    ['Purpose and form', 'A لعلّ clause can join another purpose; علّ is an attested shorter form.'],
  ], { copy: {
    '0:0': 'كأنّ is third in this particle category.',
    '0:3': '“The glass is like a pearly star.” The lamp’s glass is compared to a brilliant star. كأنّ gives its اسم نصب and خبر رفع.',
    '1:1': 'Compare زيد كالأسد, “Zayd is like a lion”. The course gives كأنّ stronger emphasis, invoking زيادة اللفظ تدل على زيادة المعنى, also phrased زيادة المبنى: extra wording can carry extra meaning.',
    '1:3': 'The compound account joins comparison كاف with emphatic أنّ. The simple account treats كأنّ as one particle, despite that resemblance. Both accounts presented here retain its stronger comparison.',
    '2:0': 'لكنّ is the fourth particle.',
    '2:3': 'A second statement removes a possible false impression, whether something was assumed true or false. تعقيب pictures following on the heel, عقب, of the first statement.',
    '2:5': '“Zayd is not strong, but he is brave.” A listener might infer cowardice from weakness. لكنه شجاع removes that impression without denying the first statement.',
    '3:1': 'In Quranic usage, واو commonly precedes لكنّ.',
    '3:3': '“Sulayman did not disbelieve, but the devils did.” Clearing Sulayman could suggest no disbelief occurred in the story. The second clause identifies who did disbelieve.',
    '4:0': 'لعلّ is the fifth particle.',
    '4:2': 'توقع is expectation: either welcome or feared. Two further uses express purpose or the sense of كأنّ.',
    '4:4': '“Fear Allah, that you may receive mercy.” Hope for something welcome is ترجّي.',
    '4:5': 'Hope differs from certainty. It may belong to speaker or addressee. Here it is framed for the addressee, not uncertainty in Allah’s knowledge: mercy is an incentive tied to their تقوى.',
    '4:7': '“Perhaps you would destroy yourself with grief over them.” إشفاق concerns something feared. The verse addresses the Prophet’s intense concern for people’s guidance and the grief it brings.',
    '4:9': '“Do good so that you may succeed.” لعلّ can give a purpose, like كي or لام التعليل.',
    '4:11': '“You build strongholds, hoping to last.” One interpretation is ordinary hope for protection. Another gives كأنّ: “as though you would live forever”, a rebuke, since no fortress prevents death.',
    '5:1': 'A لعلّ clause may coordinate with مفعول لأجله, whether a bare مصدر, صريح, or expressed through a preposition, غير صريح.',
    '5:3': '“We sent down the message so you explain to people what was revealed, and so they reflect.” لتبين is the first purpose, expressed with لام. ولعلهم يتفكرون adds a second purpose by عطف.',
    '5:5': 'Dropping initial لام gives علّ, attested in older poetry and less used in later Arabic. It keeps the particle’s function.',
  }, analysisLabels: {
    'لكنّ للاستدراك واسمها (ضمير الهاء)': 'لكنّ استدراك؛ هـ اسمها',
    'كأنّ للتشبيه واسمها (ضمير الهاء)': 'كأنّ تشبيه؛ هـ اسمها',
    'لكنّ للاستدراك واسمها (الكاف)': 'لكنّ استدراك؛ ك اسمها',
  }, boxCopy: { '1:0': ['كأنّ آكد في التشبيه من الكاف، في العرض هنا.'],
    '2:2': ['الاستدراك: تعقيب الكلام بما يرفع توهّم ثبوت شيء أو نفيه.'] },
    visuals: { '4:0': v('Two directions of expectation', ['ترجّي', 'Something welcome'], ['إشفاق', 'Something feared']),
      '5:2': v('Two forms of the same particle', ['لعلّ', 'Full form'], ['علّ', 'Initial لام omitted']) } }),
});

Object.assign(checks, {
  '12/l4': [q('How do the two spellings explain استغفروا الله...?', ['إنّ: fresh reason clause. أنّ: attached through implied لام.', 'إنّ: implied لام. أنّ: fresh clause.', 'Exactly the same إعراب.', 'إنّ is ungrammatical here.'], 'Both give the reason, but their grammar differs.'),
    q('What does فإنه غفور رحيم do in the offered conditional analysis?', ['A fresh clause indicating the understood answer.', 'مبتدأ with omitted خبر.', 'بدل of الرحمة.', 'Object of تاب.'], 'Distinguish the إنّ form from the noun-equivalent form.'),
    q('Which form is common after لا جرم, and how is it analysed?', ['أنّ: source-equivalent as فاعل, or خبر لا.', 'إنّ: always an oath, exclusively.', 'Both are equally rare.', 'أنّ is never attested.'], 'The fatḥah form has two proposed noun positions.'),
    q('What does وأن الله لا يضيع... join in the rejoicing example?', ['The nouns نعمة وفضل: another object of rejoicing.', 'Only the whole يستبشرون clause.', 'A fresh clause with no coordination.', 'بدل of فضل alone.'], 'Fatḥah marks a noun-equivalent.'),
    q('What is allowed after إذا الفجائية in the example?', ['Both spellings, cited from ordinary Arabic usage.', 'Only إنّ.', 'Only أنّ.', 'Neither.'], 'The sudden discovery is one of the permitted-choice positions.')],
  '12/l5': [q('Why can conditional من not be اسم إنّ or أنّ?', ['Its required initial position conflicts with that governed slot.', 'It can never occupy any نصب position.', 'Conditions only contain verbs.', 'إنّ then needs no اسم.'], 'The restriction is on conditional, not relative, من.'),
    q('Why is fronted إلينا optional with إيابهم in this contrast?', ['إيابهم is definite; the shown عبرة pattern is indefinite.', 'إيابهم is indefinite; عبرة is definite.', 'Both require fronting in every case.', 'Both forbid fronting.'], 'إضافة to a pronoun makes إيابهم definite.'),
    q('What does الساعةَ follow in Hamzah’s cited reading?', ['The visible نصب of اسم إنّ, وعدَ.', 'The underlying رفع.', 'بدل of الله.', 'حال describing وعد.'], 'The question concerns coordination after the completed predicate.'),
    q('What licenses باء in أولم يروا أن الله...بقادر?', ['The earlier negation لم.', 'Every خبر أنّ always takes باء.', 'قادر inherently has جر.', 'باء belongs to السماوات.'], 'Recall added باء with negation.'),
    q('Which sense is proposed for أنها in the signs example?', ['لعلها: expectation.', 'Only its usual emphasis.', 'ليست: negation.', 'إنْ: condition.'], 'Compare the market idiom with أنك.')],
  '12/l6': [q('What does كأنّ do in the glass-and-star comparison?', ['Comparison; اسم منصوب and خبر مرفوع.', 'It negates the likeness.', 'It is a plain conjunction.', 'It asks a question.'], 'It belongs to the same government category as إنّ.'),
    q('Why is كأنّ described as more emphatic than كاف here?', ['Extra wording can carry extra meaning, on either analysis.', 'كاف cannot express likeness.', 'كأنّ is shorter.', 'كاف occurs only with heart verbs.'], 'Recall زيادة المبنى and the compound/simple accounts.'),
    q('What impression does لكنه شجاع remove after ما زيد قويا?', ['That lack of strength also means lack of courage.', 'That Zayd is dead.', 'It confirms his cowardice.', 'It removes no impression.'], 'Distinguish physical strength from bravery.'),
    q('What does ولكن الشياطين كفروا clarify?', ['Disbelief occurred, though Sulayman was innocent of it.', 'Sulayman was a devil.', 'There was no possible impression.', 'The devils never existed.'], 'The correction identifies who did disbelieve.'),
    q('Which pair fits mercy versus feared destructive grief?', ['Mercy: ترجّي. Grief: إشفاق.', 'Mercy: إشفاق. Grief: ترجّي.', 'Both are hoped for.', 'Both are feared.'], 'Separate welcome and unwelcome expectations.'),
    q('What does ولعلهم يتفكرون join in the revelation example?', ['The purpose لتبين للناس.', 'The noun الذكر.', 'The main verb أنزلنا.', 'Nothing; no coordination occurs.'], 'Two purposes accompany sending down the message.')],
});
Object.assign(quizzes, {
  '12/l4': [q('What distinguishes the positions allowing both spellings?', ['Both are allowed, each with its own إعراب.', 'Both are forbidden.', 'Both must occur together.', 'They occur only in poetry.']),
    q('With أنّ after استغفروا الله, which preposition is implied?', ['لام: because He is Forgiving, Merciful.', 'باء.', 'مِن.', 'No governor is needed.']),
    q('Which spelling is common after لا جرم?', ['Fatḥah, أنّ.', 'Kasrah, إنّ.', 'Both equally.', 'The particle is always omitted.']),
    q('With إنّ, how does لا جرم function?', ['Like an oath, followed by its answer.', 'Like a verb followed by فاعل.', 'Only as لا النافية للجنس.', 'As bare negation with no role.']),
    q('What does kasrah allow after وفضل in the rejoicing example?', ['Coordination with a clause, or a fresh beginning.', 'Coordination with نعمة alone.', 'بدل of فضل.', 'حال of المؤمنين.']),
    q('Where does this course cite فإذا إن سعيدا واقف?', ['Ordinary Arabic usage, not a Quranic example.', 'Many Quranic occurrences.', 'The Quran, only with أنّ.', 'No source of usage is stated.'])],
  '12/l5': [q('Why can conditional من not serve as اسم إنّ?', ['It requires its own initial position.', 'Simply because it is مبني.', 'It can only ever be مبتدأ.', 'إنّ rejects every relative pronoun.']),
    q('In the simple indefinite pattern shown, phrase-predicate fronting is:'),
    q('What underlies رفع of آباؤنا in the account given?', ['The original رفع position of إنّا with its اسم.', 'The visible نصب of اسم إنّ.', 'خبر إنّ directly.', 'No coordination; only a separate مبتدأ.']),
    q('Which earlier meaning can license باء on خبر أنّ?'), q('Which particle’s meaning can أنّ convey in the signs example?'),
    q('What is استكمال الخبر before a coordinated noun?', ['The predicate has already been stated in full.', 'The noun comes before any predicate.', 'The noun must have جر.', 'إنّ never allows coordination.'])],
  '12/l6': [q('What does كأنّ convey in the glass-and-star example?'), q('Which principle explains the emphasis of كأنّ in this account?'),
    q('What is استدراك?', ['A following statement removes a possible false impression.', 'A comparison showing likeness.', 'Hope for something possible.', 'Emphasis without a follow-up correction.']),
    q('What commonly precedes لكنّ in Quranic usage?'), q('Which لعلّ sense concerns destructive grief?'), q('What shorter form of لعلّ is attested?')],
});
