import { card as c, part as p, rows as r, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '25/l3': plan(122, 'The Absolute Object', [
    [c('Reinforce, describe or count an action', 0, 1, 2), c('Why it is called مطلق', 3, 4)],
    [c('Its own مصدر or a related one', 0, 1, 2), c('Separate the object from the مصدر', 3)],
    [c('An اسم مصدر or a description', p(0,0)), c('A pronoun for the source action', p(0,1)), c('Point to, count or describe the action', p(0,2)), c('A quantity added to the مصدر', p(0,3)), c('An اسم مصدر in a sentence', 1), c('A count in a sentence', 2)],
    [c('Three kinds of governor', 0, 1)],
    [c('Emphasis or a specified kind', p(0,0)), c('Point to a kind or count occurrences', p(0,1)), c('Pure emphasis leaves the مصدر unmodified', 1, 2), c('Count and kind', 3, 4, 5)],
    [c('A مصدر can stand in for a verb', 0, p(1,0)), c('Invocation and confirmation', p(1,1)), c('Alternatives and fixed expressions', p(1,2)), c('An omitted command', 2)],
  ], [
    ['مفعول مطلق', 'A مصدر or substitute reinforces, describes or counts the action.'],
    ['Governor', 'A verb, مصدر or derivative; some examples have an omitted-verb account.'],
    ['Substitutes', 'Seven source patterns stand in for a مصدر.'],
    ['Omitted verb', 'Six source usages, from directives to fixed expressions.'],
  ], { copy:{
    '0:0':'This begins the source’s twelve منصوبات, starting with المفعول المطلق. The preceding sequence reviewed four مرفوعات; other raised categories were treated with their governors earlier.',
    '0:2':'A مصدر or its substitute reinforces the action, specifies its kind, or counts occurrences. Its governor may be a verb or an equivalent. Following the governor is common, not an absolute position requirement.',
    '0:4':'مطلق means “unrestricted” in its grammatical name. Compare the relational labels مفعول به، فيه، له and معه. These labels specify a relation; they do not mean every actual object is preceded by a preposition. مع itself is a noun used adverbially, not a حرف جر.',
    '1:0':'The source compares two مصدر relationships.',
    '1:2':'ترتيلا belongs to رتّل itself. تبتيلا belongs to بتّل, while تبتّل normally has تبتّلا. The example connects their related meanings; they share a root but differ in verbal form. Other accounts supply an omitted بتّل or discuss مصدر substitution.',
    '3:1':'A verb governs in ورتل القرآن ترتيلا. A مصدر can govern جزاءً in فإن جهنم جزاؤكم جزاء موفورا; another account supplies an omitted verb. A derivative governs in والصافات صفا. The three governor types are فعل, مصدر and مشتق.',
    '4:2':'For pure emphasis, the مصدر is indefinite and unmodified: no adjective, إضافة, unit تاء, dual or plural. A form specifying kind or number belongs to another category.',
    '4:4':'Counting allows dual and plural; pure emphasis does not. Unlike the source’s blanket prohibition, many grammarians also allow distinct kinds to be counted, although this is disputed. سجدتين counts two prostrations.',
    '5:0':'A مصدر may replace its unspoken governing verb. The source groups six usages.',
  }, copyParts:{'2:0':[
    'اسم المصدر can substitute: توضأ وضوء رسول الله uses وضوء for the act of washing. A description can substitute for its مصدر: واذكر ربك كثيرا supplies ذكرا كثيرا. The noun or adjective takes the source expression’s role.',
    'A pronoun can refer back to a مصدر. In فإني أعذبه عذابا لا أعذبه أحدا من العالمين, the second ـه refers to the previously mentioned punishment in the taught account. The first ـه refers to the person punished; the two pronouns have different roles.',
    'A demonstrative can specify the act: اجتهد ذلك الاجتهاد. A count can measure it: يصلي المسلمون خمس مرات. A manner word can describe its kind: رجع القهقرى, returning backwards. These substitute for the corresponding مصدر expression.',
    'كل، بعض and أي can be added to a مصدر and stand in its place. ولا تبسطها كل البسط, “do not extend it completely”, uses كل to qualify the amount of البسط. The genitive مصدر completes the added word.',
  ],'4:0':[
    'Pure emphasis reinforces the action: ورتل القرآن ترتيلا. A kind can be specified by إضافة, وظننتم ظن السوء, or description, إنا فتحنا لك فتحا مبينا. Each answers a different question: the action itself, or what kind of action.',
    'A kind may be specified by a demonstrative, اجتهد ذلك الاجتهاد, or familiar-reference أل, اجتهد الاجتهاد. A counting مصدر instead states how often: سجدت سجدتين, “she prostrated twice”.',
  ],'5:1':[
    'For command, وبالوالدين إحسانا supplies أحسنوا بالوالدين إحسانا. صبرا لا جزعا combines a command and prohibition: اصبر صبرا ولا تجزع جزعا. The source lists the latter under prohibition because of لا جزعا, not because صبرا itself prohibits patience.',
    'For invocation, بعدا للقوم الظالمين wishes the wrongdoers far away; the source explains بَعِدوا بُعدا. For confirmation, أولئك هم المؤمنون حقا affirms the preceding claim, supplying حق ذلك حقا.',
    'For subsequent alternatives, فشدوا الوثاق فإما منا بعد وإما فداء specifies release by favour or ransom. Fixed attested expressions include سبحانك، معاذ الله، حجرا محجورا، لبيك and غفرانك. Learn their established omitted-verb usages without unrestricted analogy.',
  ]}, tableCopy:{'1:1':{0:['مصدر عامله','The governor’s own مصدر','ورتل القرآن ترتيلا'],1:['مصدر بمعناه','A related verb’s مصدر','وتبتل إليه تبتيلا']}}, boxCopy:{'0:1':['مصدر أو نائبه لتوكيد العامل، أو بيان النوع أو العدد.'],'0:3':['مطلق: اسمه غير مقيّد بعلاقة مثل به أو فيه.'],'4:1':['مصدر التوكيد نكرة غير موصوف ولا مضاف، ولا معدود.'],'4:3':['العدد يثنّى ويجمع؛ والنوع فيه تفصيل.']}, visuals:{'2:0':v('Two substitutes for a مصدر',['وضوء','اسم مصدر'],['كثيرا','Description of understood ذكرا']),'2:1':v('Identify each pronoun',['أعذبه عذابا','The person punished'],['لا أعذبه أحدا','That punishment']),'2:2':v('Specify the action',['ذلك الاجتهاد','Which effort'],['خمس مرات','How many times'],['القهقرى','In what manner']),'2:3':v('Added quantities',['كل البسط','The whole extent'],['بعض / أي','Other added qualifiers']),'4:0':v('Emphasis and kind',['ترتيلا','Reinforces رتّل'],['ظن السوء','Specifies the kind']),'4:1':v('Kind and count',['ذلك الاجتهاد','That particular effort'],['سجدتين','Two prostrations']),'5:1':v('Two communicative purposes',['بعدا','Invocation'],['حقا','Confirmation'])}, analysisItemLabels:{'bank-19':{'مفعول مطلق مؤكد لعامله':'مفعول مطلق للعدد'}} }),
  '25/l1': plan(120, 'The Predicate and Its Omission', [
    [c('What is said about the topic?', 0, 1, 2), c('A topic and its information', 3, 4, 5)],
    [c('One topic, two predicates', 0, 1, 2, 3, 4), c('A predicate for each quality', 5)],
    [c('The normal order can change', 0, 1, 2, 3), c('A prepositional predicate first', 4, 5, 6), c('An emphasized predicate first', 7, 8)],
    [c('An oath with an understood predicate', 0, 1, 2), c('General existence after لولا', 3, 4), c('The complete لولا construction', 5), c('A و meaning together with', 6, 7, 8), c('A person and their work', 9, 10)],
    [c('A question supplies the missing news', 0, 1, 2), c('A sudden encounter', 3, 4, 5)],
  ], [
    ['خبر', 'The information predicated of the topic; it may be multiple.'],
    ['Order', 'Normally after the subject, but it can precede it.'],
    ['Required omission', 'The taught oath, general-existence لولا and companionship patterns.'],
    ['Optional omission', 'A clear context, including answers and sudden إذا, can supply it.'],
  ], { copy:{
    '0:0':'الخبر is the fourth مرفوع discussed in this sequence.',
    '0:2':'It is what is predicated of the مبتدأ: the news about the topic.',
    '0:4':'محمد is مخبر عنه, the topic. رسول الله supplies the information, مخبر به. Within that predicate phrase, رسول has رفع and الله is مضاف إليه.',
    '1:0':'One topic can receive more than one predicate.',
    '1:2':'Each predicate makes its own assertion about that same topic.',
    '1:4':'In the two-predicate account of وهو الغفور الودود, الغفور and الودود both describe هو independently. An adjective analysis of الودود is also possible; practice specifies the two-predicate account.',
    '2:0':'The source gives a normal order and fronted alternatives.',
    '2:2':'The default is مبتدأ then خبر.',
    '2:3':'A خبر مقدم instead comes before a مبتدأ مؤخر.',
    '2:5':'لكل أجل is the fronted prepositional predicate; كتاب is the later subject. أجل completes كل inside the predicate phrase.',
    '2:8':'In لكاذب أنت, كاذب is a fronted predicate emphasized by لام; أنت is the later subject.',
    '3:0':'Three taught constructions require predicate omission. Required omission applies to the specified form, rather than making every explanatory expansion an invalid sentence.',
    '3:2':'لعمرك introduces an oath. The source supplies لعمرك قسمي, “by your life is my oath.” The following response إنهم لفي سكرتهم يعمهون makes the oath relation clear, so قسمي remains unspoken.',
    '3:4':'لولا رهطك لرجمناك, “Were it not for your clan, we would have stoned you”, supplies موجود after رهطك. General existence, كون عام, is obligatorily omitted here. A particular state, كون خاص, follows different rules and may need to be expressed; لولا does not always delete every predicate.',
    '3:6':'A coordinating و that unambiguously implies companionship can license the taught omitted predicate.',
    '3:8':'For فإنكم وما تعبدون, the source compares two accounts: companionship itself supplies the predicate’s sense, like إنكم مع ما تعبدون; or a predicate such as مقرونان is supplied. Its مفعول معه account is distinct from ordinary coordination. The following Quranic context also admits another predicate analysis.',
    '3:9':'ضيعة means حرفة, livelihood. ضيعتُه is coordinated and raised; مقرونان is omitted in this account. Companionship describes the و’s meaning. The source’s مفعول معه label would require نصب, not this رفع. Some scholars dispute obligatory omission.',
    '4:0':'Elsewhere a recoverable predicate may be omitted, especially in an answer or after sudden إذا.',
    '4:2':'Asked who created the heavens and earth, the answer الله supplies الله خلقهن in the adopted nominal analysis. The question provides the missing خبر; its omission is permitted, not forced.',
    '4:4':'خرجت فإذا الأسد means “I went out, and suddenly, the lion!” The source supplies موجود. Compare زيد في البيت, meaning Zayd is present there, not that he built it. Suddenness and context make the existence predicate recoverable.',
  }, boxCopy:{'1:1':['قد يتعدد الخبر لمبتدأ واحد.'],'3:1':['لَعَمْرُكَ إِنَّهُمْ لَفِي سَكْرَتِهِمْ يَعْمَهُونَ']}, diagramLabels:{'3:10':{'واو المعية':'واو عطف تفيد المعية','مفعول معه (والخبر محذوف تقديره: مقرونان)':'معطوف مرفوع'},'4:5':{'فعل ماضٍ وفاعله ضمير مستتر':'فعل ماضٍ وفاعله التاء المتصلة'}}, analysisPrompt:'Use the lesson’s stated predicate analysis.', analysisItemLabels:{'bank-18':{'خبر أول':'مفعول مطلق','خبر ثانٍ':'حال منصوب'},'bank-19':{'خبر مرفوع':'مفعول به','نعت مرفوع':'نعت مجرور'}} }),
  '25/l2': plan(121, 'Predicate Agreement and Conditional Meaning', [
    [c('Agreement depends on the construction', 0, 1, 2)],
    [c('A derivative matches its referent', 0, 1, 2), c('Separate فصل from the predicate', 3), c('A shared description can stay singular', 4, 5), c('Avoid an unrestricted agreement rule', 6, 7)],
    [c('Two proofs, a dual demonstrative', 0, 1, 2), c('Analyze the dual example', 3)],
    [c('A subject can suggest a condition', 0, 1, 2), c('The response after أمّا', 3, 4), c('A relative clause with conditional force', 5, 6), c('A noun described by a relative clause', 7, 8)],
    [c('Further patterns with conditional force', 0), c('A described indefinite', 1, 2), c('The descriptive clause and its result', 3), c('An إضافة or distributive كل', 4)],
  ], [
    ['Agreement', 'A derivative’s referent and the predicate’s meaning matter.'],
    ['جامد', 'A noun such as فتنة can describe more than one person in singular form.'],
    ['اسم الإشارة', 'Match the referents; the two-proof example uses dual forms.'],
    ['فاء الخبر', 'Conditional force can link description to result; the form alone is insufficient.'],
  ], { copy:{
    '0:0':'Predicate agreement is not an unrestricted rule of identical word shapes.',
    '0:2':'The source highlights a returning hidden pronoun in a derivative, and demonstrative reference. These explain its examples; they are not an exhaustive rule forbidding every other agreement pattern. Underived predicates must still make appropriate semantic sense.',
    '1:0':'A governing derivative can contain a hidden subject returning to its topic.',
    '1:2':'In إنهم هم المفسدون, plural المفسدون carries a hidden هم referring to اسم إن. The displayed analysis treats the separate هم as ضمير فصل. A nominal-clause account of that هم is another possibility.',
    '1:4':'نحن فتنة, “we are a trial”, uses singular فتنة for a shared trial. It is a مصدر without a derivative’s hidden subject. نحن can refer to two speakers as in this Quranic passage, as well as to a larger group.',
    '1:7':'The hidden-pronoun explanation applies to this derivative pattern. It does not make “a hidden pronoun is the only possible reason for agreement” a universal rule; collective meanings and other constructions need their own analysis.',
    '2:0':'A demonstrative identifies the same referents as its predicate.',
    '2:2':'فذانك برهانان من ربك means “those are two proofs from your Lord.” ذانك and برهانان both identify the two proofs, although برهان is underived. This does not require every demonstrative’s predicate to match its surface number: إن هؤلاء ضيفي uses ضيف for several guests.',
    '3:0':'Some nominal subjects carry an if, whoever or whatever relation.',
    '3:2':'فاء can then link the predicate as a result, resembling a conditional response. The source lists seven patterns. Their general and conditional meaning matters; an ordinary relative clause or description does not automatically authorize فاء. أمّا has its own required response link.',
    '3:4':'فأما ثمود فأهلكوا بالطاغية means “As for Thamud, they were destroyed by the overwhelming blast.” أمّا supplies the conditional and topic-setting force; فاء introduces its response.',
    '3:6':'الذين خسروا أنفسهم فهم لا يؤمنون receives a conditional interpretation in this account: those who incur that loss do not believe. A relative is grammatically definite; “whoever-like” here concerns general application and the result relation, not lexical indefiniteness.',
    '3:8':'إن الموت الذي تفرون منه فإنه ملاقيكم connects fleeing from death with its inevitable meeting. The source groups it as a noun described by a verbal relative clause. That description is interpreted with conditional force here, rather than licensing فاء in every described noun.',
    '4:0':'Four further source patterns are: an indefinite described by a verbal clause; one described by a ظرف; an إضافة to such a described indefinite; and كل added to an indefinite. Read each with a general condition-and-result relation.',
    '4:2':'ولد حفظ القرآن فله أجر gives a reward to a child satisfying the description, “whoever memorizes the Quran”. Compare ولد في الفصل فله أجر with a locative description. Neither description alone makes the construction conditional; the intended general rule supplies that force.',
    '4:4':'To describe the orphan in أم يتيم يأتيني فلها مال, use masculine يأتيني. The source’s تأتيـني instead describes the mother, so it does not illustrate that deeper إضافة pattern. كل يتيم فله في قلبي رأفة uses distributive كل: every orphan receives compassion, without a further description.',
  }, boxCopy:{'0:1':['تراعى المطابقة بحسب التركيب والمعنى.'],'1:6':['ضمير الوصف يعود إلى مرجع يناسبه.'],'3:1':['قد يتضمن المبتدأ معنى الشرط.']}, visuals:{'1:2':v('Compare the predicate types',['المفسدون','Derivative with a returning subject'],['فتنة','One shared trial']),'4:0':v('Two ways to express generality',['نكرة موصوفة','A qualifying description'],['كلّ + نكرة','Every member of a category']),'4:3':v('The verb’s referent matters',['يتيم يأتيني','The orphan comes'],['أمّ تأتيـني','The mother comes'])}, diagramLabels:{'4:3':{'رابطة داخلة على خبر المبتدأ لتضمنه معنى الشرط':'فاء رابطة للخبر ذي المعنى الشرطي'}}, analysisPrompt:'Use the ضمير الفصل analysis where applicable.', analysisItemLabels:{'bank-18':{'مبتدأ':'مفعول مطلق'},'bank-19':{'خبر مرفوع':'نعت مرفوع','مبتدأ مرفوع':'مفعول به'}} }),
};

export const checks = {
  '25/l3':[
    q('Why is this object called مطلق?', ['Its name has no qualifying relation such as به or فيه','It only follows present verbs','It never has tanwin','It is always مبني'], 'The explanation concerns the grammatical label.'),
    q('How is تبتيلا related to تبتّل in the account taught?', ['It is the مصدر of related بتّل','It is تبتّل’s regular تبتّلا form','It is not a مصدر','It is a direct object'], 'Distinguish a shared root from the exact verbal form.'),
    q('What does خمس مرات substitute for?', ['The action’s count','Only its manner','An اسم مصدر','A returning pronoun'], 'It answers how many times.'),
    q('May a مصدر govern a مفعول مطلق?', ['Yes, alongside a verb or derivative','No; only verbs can','No مصدر ever governs','Only when the مصدر is مرفوع'], 'Compare the two analyses of جزاؤكم جزاء موفورا.'),
    q('Can a مصدر for pure emphasis be dual like سجدتين?', ['No; counting is a different function','Yes, freely in every type','No مفعول مطلق can ever be dual','Yes, but only with أل'], 'Distinguish pure emphasis from count and kind.'),
    q('What use does وبالوالدين إحسانا illustrate?', ['A command','A prohibition','An invocation','Only a non-analogical fixed formula'], 'The source supplies أحسنوا.'),
  ],
  '25/l1':[
    q('What is مخبر به in محمد رسول الله?', ['رسول الله, the predicate phrase','محمد, the topic','الله alone','There is no predicate'], 'Separate the news from its topic.'),
    q('On the two-predicate reading, how many أخبار follow هو in هو الغفور الودود?', ['Two','One only','None','Three'], 'Use the specified reading.'),
    q('What is the later مبتدأ in لكل أجل كتاب?', ['كتاب','لكل','أجل','No subject is present'], 'The prepositional phrase comes first.'),
    q('Is general-existence موجود omitted obligatorily after لولا رهطك?', ['Yes, in this general-existence pattern','No, it is freely stated here','No predicate is understood','Only in poetry'], 'Do not extend this rule to every particular-state predicate.'),
    q('Is خلقهن obligatorily omitted in the answer الله?', ['No; the question permits its omission','Yes; every answer must omit its predicate','There is no omitted predicate in this analysis','Yes, exactly like general existence after لولا'], 'The question makes the information recoverable.'),
  ],
  '25/l2':[
    q('Which two features does this lesson use to explain agreement?', ['A derivative’s hidden pronoun and demonstrative reference','Every predicate has an identical form','Only dual subjects','Only underived predicates'], 'These are the source’s examples, not an exhaustive universal rule.'),
    q('Why can فتنة remain singular in نحن فتنة?', ['It names one shared trial without a derivative’s hidden subject','It secretly means نحن','نحن can refer only to one person','Predicates never agree with underived subjects'], 'Compare an event noun with a governing adjective.'),
    q('Why are ذانك and برهانان dual in the example?', ['Both identify the two proofs','برهان hides a dual pronoun','Every predicate must always match surface number','ربك is genitive'], 'Match what the words refer to.'),
    q('Why does the taught account license فاء after الذين خسروا أنفسهم?', ['The relative construction has general conditional force','Every الذين must take فاء','فاء is ordinary coordination here','هم لا يؤمنون cannot be predicate'], 'Look for the condition-and-result relation.'),
    q('What licenses فله أجر after ولد حفظ القرآن here?', ['A general condition-and-result reading of the described indefinite','ولد is always definite','فاء is decorative','حفظ is itself the main predicate in this reading'], 'The description is interpreted as a qualifying condition.'),
  ],
};

export const quizzes = {
  '25/l3':[
    q('Why is المفعول المطلق called مطلق?', ['Its name lacks a qualifier such as به or فيه','It can occupy every sentence position','It is always indefinite','It never has a governor']),
    q('What is ترتيلا relative to رتّل?', ['The مصدر of its own governor','A مصدر of a synonymous different verb','An اسم مصدر','Only a manner substitute']),
    q('What does خمس مرات express?', ['The action’s count','An اسم مصدر','A مصدر pronoun','A مصدر adjective']),
    q('What governor type occurs in والصافات صفا?', ['A derivative','A verb','Only a مصدر','A particle']),
    q('Which are the three purposes taught?', ['Emphasis, kind and count','Addition, description and pointing','Fronting, delaying and omission','Literal, figurative and indirect meaning']),
    q('Which use is specifically expressed by لا جزعا in صبرا لا جزعا?', ['Prohibition','Command','Invocation','A fixed attested مصدر only']),
  ],
  '25/l1':[
    q('Which phrase defines الخبر?', ['مخبر به','مخبر عنه','A مصدر particle with a clause','Every adjective of a noun']),
    q('In the two-predicate account of هو الغفور الودود, how many أخبار?', ['Two','One','Three','None']),
    q('What order appears in لكل أجل كتاب?', ['Predicate first, subject second','Subject first, predicate second','There is no subject','Reversed only because كتاب has no أل']),
    q('What is the rule for general-existence موجود after لولا رهطك?', ['Obligatorily omitted here','Freely expressed here','It is not understood','Omission applies only in the Quran']),
    q('In the nominal answer الله, how is omission of خلقهن classified?', ['Permitted because the question supplies it','Required just as after لولا','The full predicate is already spoken','Required only in poetry']),
    q('What is supplied in the adopted parse of كل رجل وضيعته?', ['The predicate مقرونان','An explicitly written مقرونان','A separate predicate only for ضيعته','No predicate can be understood']),
  ],
  '25/l2':[
    q('Must every predicate match its topic’s surface number?', ['No; construction and meaning matter','Yes, without exception','Only if the topic is definite','Only if every predicate is a derivative']),
    q('What does the source locate inside المفسدون?', ['A hidden هم returning to اسم إن','Tanwin enforcing agreement','أل as the sole agreement trigger','A feminine تاء']),
    q('Why can نحن فتنة use singular فتنة?', ['It is an underived event noun without a hidden derivative subject','نحن cannot be subject','فتنة is secretly dual','Arabic has no agreement rules']),
    q('What explains dual برهانان after ذانك here?', ['The two proofs identified by the dual demonstrative','A hidden pronoun in برهان','The genitive ربك','A repeated sentence']),
    q('What licenses فاء in the taught الذين خسروا أنفسهم account?', ['The relative construction’s general conditional force','Every definite relative requires فاء','Every past verb requires following فاء','The absence of a subject']),
    q('What supplies generality in كل يتيم فله في قلبي رأفة?', ['Distributive كل added to an indefinite','يتيم is dual','رأفة is a fronted predicate','Every indefinite automatically licenses فاء']),
  ],
};
