import { card as c, rows as r, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '17/l1': plan(86, 'Conditional and Wishing لو', [
    [c('The traditional account of لو', 0, 1, 2), c('Identify condition and answer', 3, 4)],
    [c('The problem with a sole cause', 0, 1, 2), c('Ibn Hisham’s more precise account', 3, 4)],
    [c('The repentance example', 0, 1, 2, r(5, 0)), c('An independently true answer', 3, 4, r(5, 1))],
    [c('Test the logic with a negative condition', 0, 1, 2), c('What else could explain the answer?', 3, 4)],
    [c('A present form in a hypothetical', 0, 1, 2, 3), c('The answer may carry لام', 4, 5), c('لام and rhetorical emphasis', r(6, 0, 1)), c('An answer without لام', r(6, 2))],
    [c('لو can express a wish', 0, 1, 2, 3), c('Does wishing لو need an answer?', 4, 5)],
    [c('A noun after لو', 0, 1), c('An omitted verb explains نصب', 2, 3, 4), c('أنّ with an understood ثبت', 5, 6)],
  ], [
    ['Conditional لو', 'In the counterfactual use, the condition did not occur; its occurrence would entail the answer.'],
    ['Another cause', 'The answer can be true independently. Do not automatically deny it.'],
    ['لام / wishing', 'Affirmative answers often have لام; wishing لو has two grammatical accounts.'],
    ['Nouns after لو', 'اشتغال supplies a governing verb; an أنّ clause can follow understood ثبت.'],
  ], { copy: {
    '0:0': 'لو، لولا، لوما and أمّا introduce conditional constructions without assigning جزم. Begin with counterfactual لو.',
    '0:2': 'The traditional definition denies the answer because the condition failed. It suits some examples, including Musa’s address after the calf episode, but needs the qualification developed next.',
    '0:4': '“Had You willed, You would have destroyed them before, and me.” شئت is the condition; أهلكتهم is the answer. The earlier destruction and the will for it did not occur.',
    '1:0': 'Why is the traditional definition too broad?',
    '1:2': 'It assumes the condition is the answer’s only possible cause. If another cause exists, the answer may still occur even when this condition does not.',
    '1:4': 'Ibn Hisham’s account retains two claims: the condition did not occur; if it had, the answer would follow. It does not automatically deny the answer independently of that condition.',
    '2:0': 'Compare an answer that may have another cause with one known to remain true.',
    '2:2': 'The example assumes repentance would bring forgiveness and that this man did not repent. It does not, by logic alone, establish that he was never forgiven: another ground may exist. This is a conditional argument, not a ruling on every unrepented sin.',
    '2:4': '“If every tree were pens and the sea ink, replenished by seven seas, Allah’s words would not be exhausted.” The imagined condition did not occur; the inexhaustibility remains true independently.',
    '3:0': 'The source leaves this example for reflection.',
    '3:2': '“An excellent servant is Suhayb: even if he did not fear Allah, he would not disobey Him.” The saying circulates among grammarians and is attributed to Umar in the source; that attribution is not established here. Use it as a grammatical example.',
    '3:4': 'The missing condition is absence of fear, not fear itself. Could love of Allah independently explain non-disobedience? The source invites this question to test the sole-cause assumption.',
    '4:1': 'In the counterfactual use taught here, لو can give a present-form verb a past or hypothetical reading. This is not a rule for every use of لو: grammarians also recognize future conditional uses.',
    '4:3': 'نشاء is present in form. Here it sets up a hypothetical: “Had We willed, We would have made it broken stubble”, rather than reporting an ongoing act of willing.',
    '4:5': 'An affirmative past answer often has لام, but it is not compulsory. The source links its emphasis here with a striking or unexpected outcome. That is a contextual rhetorical account, not a universal test for adding لام.',
    '5:1': 'Wishing لو resembles ليت: “if only”.',
    '5:3': 'The speakers regret in the Hereafter: “If only we had a return, so we could be believers.” They wish for a return; the verse does not grant one.',
    '5:5': 'One account treats لو as pure wishing with no conditional answer. Another retains conditional force and supplies an answer: لو ثبتت لنا كرّة لآمنا, “If a return were available, we would believe”.',
    '6:1': 'The usual verbal construction can contain a fronted noun governed by an omitted verb, or an أنّ clause linked to understood ثبت. These are distinct analyses.',
    '6:3': 'An omitted رأيت governs زيدًا and supplies the condition. Visible رأيته explains it: باب الاشتغال. لو itself does not assign نصب.',
    '6:6': '“Had they done what they were advised, it would have been better.” On this analysis, the أنّ clause is a مصدر مؤول functioning as فاعل of understood ثبت. Its رفع is positional, not a visible ending on the whole clause.',
  }, boxCopy: {
    '1:1': ['التعريف المشهور يفترض انفراد الشرط بالسببية.'],
    '1:3': ['لو لامتناع الشرط واستلزامه للجواب، لا لامتناع الجواب مطلقا.'],
    '4:0': ['لو الامتناعية مع المضارع تفيد الماضي أو الفرض في هذه الأمثلة.'],
    '4:4': ['يكثر اقتران الجواب المثبت باللام، ولا يلزم.'],
    '5:4': ['لو للتمني: هل يبقى لها جواب؟ فيه قولان.'],
    '6:0': ['بعد لو: اسم منصوب بفعل مقدّر، أو أنّ مع تقدير ثبت.'],
  }, tableCopy: { '2:5': {
    0: ['توبة', 'The man did not repent.', 'Whether forgiveness occurred through another cause is not settled.'],
    1: ['Trees as pens', 'The trees were not pens.', 'Allah’s words remain inexhaustible.'],
  }, '3:3': { 0: ['عدم خوف صهيب', 'This absence did not occur.', 'Could love independently explain non-disobedience?'] }, '4:6': {
    0: ['ولو نشاء لجعلنا منكم ملائكة في الأرض يخلفون', 'With لام', 'The source treats the angels scenario as striking. Interpretations of منكم differ.'],
    1: ['فلو شاء لهداكم أجمعين', 'With لام', 'The source reads emphasis in the hypothetical universal guidance.'],
    2: ['لو نشاء أصبناهم بذنوبهم', 'Without لام', 'Punishment for sins is presented as an expected consequence.'],
  } }, diagramLabels: { '6:4': { 'الفعل المفسِّر (فعل الشرط) وفاعله ومفعوله': 'الفعل المفسّر وفاعله ومفعوله' } }, tableHeaders: { '2:5': ['Example', 'Condition', 'Answer'], '3:3': ['Condition', 'Status', 'Reflection'], '4:6': ['Example', 'Form', 'Source’s rhetorical account'] }, analysisItemLabels: {
    'bank-19': { 'فعل الشرط (مضارع بمعنى الماضي)': 'فعل مضارع منصوب بأن مضمرة' },
  } }),
  '17/l2': plan(87, 'Conditional لولا and لوما', [
    [c('An existing cause prevents an outcome', 0, 1, 2), c('Distinguish لو from لولا', 3, 4)],
    [c('The usual two-clause construction', 0, 1)],
    [c('Allah’s favour enables purification', 0, 3), c('Parse the verse', 1, 2)],
    [c('لوما has the same conditional use', 0, 1)],
    [c('An existing cause enables good deeds', 0, 1), c('Parse the لوما construction', 2)],
  ], [
    ['لولا / لوما', 'امتناع لوجود: an existing condition prevents the stated answer.'],
    ['First clause', 'A مبتدأ, with an omitted general-existence خبر in the examples.'],
    ['Answer', 'A verbal clause here; if negative, track the negation carefully.'],
    ['Compare لو', 'Its failed condition does not always imply a failed answer.'],
  ], { copy: {
    '0:0': 'لولا and less common لوما share a conditional meaning.',
    '0:2': '“Were it not for…” introduces something that exists and prevents the stated answer. This is امتناع لوجود, unlike the failed condition of counterfactual لو.',
    '0:4': 'With لولا, the existing condition blocks the answer. With لو, the condition failed; the answer’s independent truth still needs the qualification from the previous lesson. Do not revert to “both always failed”.',
    '1:1': 'In these examples, a nominal clause comes first, then a verbal answer. The first clause’s general-existence خبر is omitted: موجود. This is the common pattern; a specific predicate has further rules and is not always omitted.',
    '2:1': 'The nominal clause’s خبر is understood: موجود.',
    '2:3': '“Were it not for Allah’s favour and mercy upon you, none of you would ever be purified.” Purification depends on that existing favour; the verse does not assert that every individual has actually become purified.',
    '3:1': 'Conditional لوما shares لولا’s meaning and the same common structure: nominal clause with understood موجود, then a verbal answer. Other uses of these particles will follow later.',
    '4:1': '“Were it not for success being granted, we would not have done righteous deeds.” The existing توفيق enabled deeds actually done. لما contains لام plus negative ما. This is a teaching example, not a Quran quotation.',
  }, boxCopy: { '0:3': ['لو: امتناع الشرط. لولا: وجود الشرط يمنع الجواب.'], '1:0': ['في المثال: مبتدأ وخبر محذوف تقديره موجود، ثم جواب فعلي.'] }, analysisItemLabels: {
    'bank-16': { 'مبتدأ (خبره محذوف تقديره ثابت)': 'اسم إنّ منصوب' },
    'bank-17': { 'حرف امتناع لوجود الشرط': 'حرف جر أصلي', 'مبتدأ (خبره محذوف تقديره ثابت)': 'اسم إنّ منصوب', 'جواب الشرط مقترن باللام': 'جواب شرط مقترن بالفاء' },
  }, visuals: { '0:0': v('An existing cause blocks the answer', ['الشرط', 'Exists'], ['الجواب', 'Prevented']) } }),
  '17/l3': plan(88, 'Condition, Detail and Emphasis with أمّا', [
    [c('Three functions of أمّا', 0, 1), c('Two cases introduced by أمّا', 2, 3)],
    [c('The fuller conditional model', 0, 1), c('From the model to أمّا', r(2, 0, 1, 2)), c('Why the construction emphasizes', 3, 4), c('A grammatical model, not etymology', 5, 6)],
    [c('Repeated أمّا gives separate details', 0, 1), c('Thamud and Ad: summary then detail', 2, 3), c('One stated case can imply another', 4, 5, 6, 7)],
    [c('Between أمّا and فاء', 0, 1), c('A nominal subject before فاء', 2, 3), c('A fronted predicate before فاء', 4, 5), c('A condition before فاء', 6, 7), c('A note on the term جواب', 8, 9)],
    [c('A governed noun before فاء', 0, 1), c('The visible verb governs اليتيمَ', 2, 3, 4), c('Two readings of ثمود', 5, 6)],
    [c('Which meaning is prominent?', 0, 1), c('Compare repetition and emphasis', r(2, 0, 1)), c('Recognize the author’s judgement', 3, 4)],
  ], [
    ['أمّا', 'Condition, elaboration and emphasis.'],
    ['فاء', 'Connects the response, following intervening material.'],
    ['Intervening material', 'A subject, predicate, condition, or noun governed by a visible or omitted verb.'],
    ['Context', 'Repetition can highlight detail; the source’s emphasis rule is an interpretation.'],
  ], { copy: {
    '0:0': 'أمّا is the fourth non-governing conditional particle in this group.',
    '0:3': '“As for those who believe, they know it is truth from their Lord; as for those who disbelieve, they ask what Allah intended by this example.” فاء links each response. Repeated أمّا separates the two cases and gives the claims emphasis.',
    '1:1': 'The analysis associated with Sibawayh expands أمّا زيد فمنطلق into “Whatever else may be the case, Zayd is leaving”. أمّا replaces the conditional particle and its clause.',
    '1:4': 'Compared with زيد منطلق, the fuller model asserts leaving whatever else happens. The source hears certainty, readiness to go and firm resolve in this example. Those nuances explain emphasis here, not three mandatory meanings in every أمّا sentence.',
    '1:6': 'Ibn Ashur expresses reservations. Treat the expansion as an account of the construction and its linking فاء, not a documented historical derivation of the word.',
    '2:1': 'After several items are named together, repeated أمّا can give each its own detail.',
    '2:3': 'Thamud and Ad jointly denied the Striking Calamity. The two أمّا clauses then specify their fates: Thamud’s overwhelming destruction and Ad’s furious, violent wind.',
    '2:5': 'Concise speech may mention one case and leave its counterpart understood, so a second أمّا need not appear.',
    '2:7': 'The verse states the believers’ entry into mercy and favour. The contrasting fate of disbelievers is understood from context rather than a second explicit أمّا clause.',
    '3:1': 'Three patterns are illustrated first: مبتدأ, خبر and a conditional clause. The next section adds governed nouns.',
    '3:3': 'الذين آمنوا وعملوا الصالحات is the initial مبتدأ. Its خبر is the whole nominal clause لهم جنات المأوى: لهم is a fronted predicate and جنات a delayed subject within it.',
    '3:5': 'في البيت is the fronted خبر; زيد is its مبتدأ after فاء. The meaning is “As for being in the house, Zayd is there”.',
    '3:7': 'إن كان من المقربين is a conditional clause between أمّا and فاء. The response promises rest, fragrance and a garden of bliss.',
    '3:9': 'The source flags a terminological reservation about calling the following material جواب. The usual working analysis calls it the response and فاء its connector. This aside does not change the sentence’s meaning.',
    '4:1': 'A noun before فاء can be governed by a verb in the response, or by an omitted verb explained afterward. أمّا does not itself give the noun نصب.',
    '4:3': 'اليتيمَ is the fronted object of تقهر: “As for the orphan, do not oppress him”. Its governing verb is visible after فاء.',
    '4:6': 'In ثمودُ, the common reading gives a مبتدأ. An attested ثمودَ reading instead gives an object of an omitted verb explained by هديناهم, as in اشتغال. The visible pronoun هم occupies هدينا’s object position.',
    '5:1': 'In the author’s interpretation, literal or implied repetition foregrounds تفصيل. Without a second case, توكيد becomes more prominent. A single written أمّا may still imply another case, as already shown.',
    '5:4': '“What seems to me” marks the author’s considered view. Treat the relative prominence of detail and emphasis as an interpretation, not an undisputed mechanical rule.',
  }, boxCopy: {
    '1:0': ['أمّا زيد فمنطلق: مهما يكن من شيء فزيد منطلق.'],
    '1:3': ['أمّا تزيد التوكيد على قولنا زيد منطلق.'],
    '2:4': ['قد يذكر أحد القسمين ويُفهم الآخر.'],
    '3:0': ['بين أمّا والفاء: مبتدأ، أو خبر، أو شرط.'],
    '4:0': ['قد يتوسط اسم معموله لعامل ظاهر في الجواب أو مقدّر.'],
    '5:0': ['عند المؤلف: التكرار يبرز التفصيل، وعدم التقسيم يبرز التوكيد.'],
  }, analysisItemLabels: {
    'bank-18': { 'حرف شرط مكرر يفيد التفصيل': 'حرف عطف يفيد الترتيب', 'مبتدأ مرفوع': 'مفعول به مقدم' },
    'bank-19': { 'حرف شرط وتفصيل وتوكيد': 'حرف جر وتعليل', 'مبتدأ مرفوع': 'مفعول به مقدم' },
  } }),
};

export const checks = {
  '17/l1': [q('In لو شئت أهلكتهم..., which is the condition?', ['شئت; أهلكتهم is the answer.', 'أهلكتهم; شئت is the answer.', 'Both names refer to أهلكتهم.', 'There is no condition.'], 'Find the hypothetical act of willing.'),
    q('What does Ibn Hisham’s definition avoid assuming?', ['That the answer cannot have another cause.', 'That the condition failed.', 'That لو normally introduces a verbal construction.', 'That لو can express wishing.'], 'A failed cause does not rule out every other cause.'),
    q('What cannot be inferred from the repentance example alone?', ['That the man was never forgiven.', 'That repentance would lead to forgiveness here.', 'That this condition failed.', 'That the sentence is hypothetical.'], 'Another ground for the answer may exist.'),
    q('What does the Suhayb example invite us to consider?', ['Whether another cause, such as love, explains non-disobedience.', 'Whether Suhayb existed at all.', 'Whether لو forbids negative conditions.', 'Whether the sentence lacks an answer.'], 'Distinguish absence of fear from the reason for obedience.'),
    q('How does the source explain the differing لام in these examples?', ['As emphasis on a striking rather than expected outcome.', 'Only past-form conditions allow it.', 'It marks a negative answer here.', 'It has no rhetorical contribution.'], 'This is the source’s contextual explanation, not a compulsory grammar rule.'),
    q('What does لو express in فلو أن لنا كرة...?', ['Wishing, like ليت.', 'A request for information.', 'Urging someone to act.', 'Simple negation.'], 'The speakers long for a return.'),
    q('Why is زيدًا منصوب in لو زيدًا رأيته...?', ['An omitted verb governs it: اشتغال.', 'لو itself makes it a فاعل.', 'Only an explicit noun can follow لو.', 'A fixed verb cannot govern an object.'], 'رأيته explains an earlier understood رأيت.')],
  '17/l2': [q('What does conditional لولا establish?', ['An existing condition prevents the stated answer.', 'A failed condition guarantees the answer.', 'Both condition and answer occurred.', 'Neither clause has a logical relation.'], 'Recall امتناع لوجود.'),
    q('What is omitted in the ordinary nominal pattern taught here?', ['The general-existence خبر: موجود.', 'The مبتدأ.', 'A فاعل in the nominal clause.', 'The entire first clause.'], 'A specific predicate requires further rules.'),
    q('What is فضلُ in ولولا فضل الله...?', ['مبتدأ with understood موجود.', 'فاعل of زكى.', 'The conditional answer.', 'An object of زكى.'], 'Identify the first nominal clause.'),
    q('How does conditional لوما compare with لولا?', ['Same meaning and usual two-clause pattern.', 'It denies the condition instead.', 'It only has one verbal clause.', 'It is confined to poetry.'], 'The two forms are paired in this use.'),
    q('In لوما التوفيق لما عملنا الصالحات, were deeds actually done?', ['Yes, enabled by the existing توفيق.', 'No righteous deeds occurred.', 'The example gives no indication.', 'No; لوما always forbids future deeds.'], 'The hypothetical failure was prevented.')],
  '17/l3': [q('Which three functions are associated with أمّا?', ['Condition, detail and emphasis.', 'Condition, coordination and جر.', 'Detail, negation and questioning.', 'Emphasis, calling and alerting.'], 'Recall شرط وتفصيل وتوكيد.'),
    q('What does the fuller مهما يكن... model explain?', ['The emphasis in أمّا زيد فمنطلق.', 'A ban on using أمّا once.', 'A ban on relative nouns after أمّا.', 'Why أمّا governs جر.'], 'Whatever else occurs, the claim remains.'),
    q('Why repeat أمّا for Thamud and Ad?', ['To give each nation details after naming both together.', 'Every أمّا must repeat.', 'The two names mean the same nation.', 'The first أمّا was grammatically invalid.'], 'Look for summary followed by تفصيل.'),
    q('What is في البيت in أمّا في البيت فزيد?', ['A fronted خبر.', 'The مبتدأ.', 'A full conditional clause.', 'A repetition of أمّا.'], 'زيد is the subject after فاء.'),
    q('What governs اليتيمَ in فأمّا اليتيم فلا تقهر?', ['تقهر after فاء.', 'أمّا itself.', 'The linking فاء.', 'An unrelated hidden verb.'], 'The visible prohibition takes the fronted object.'),
    q('In the author’s account, what is prominent in the two examples?', ['زيد فمنطلق: emphasis; Thamud and Ad: detail.', 'Zayd: detail; Thamud and Ad: emphasis.', 'Only detail in both.', 'Only emphasis in both.'], 'Distinguish a single claim from two specified cases.')],
};

export const quizzes = {
  '17/l1': [q('What does Ibn Hisham’s account of counterfactual لو retain?', ['The condition failed; had it occurred, the answer would follow.', 'Both clauses must always be false.', 'The answer has only one possible cause.', 'The condition actually occurred.']),
    q('What logical issue does the Suhayb example explore?', ['Whether non-disobedience has an independent cause.', 'Whether لو can precede a noun only.', 'Whether every negative condition lacks an answer.', 'Whether fear and absence of fear are identical.']),
    q('How is نشاء read in the counterfactual لو نشاء لجعلناه حطاما?', ['A present form with a past or hypothetical reading.', 'Only an ongoing act in the present.', 'An imperative.', 'A jussive command.']),
    q('What is the source’s contextual explanation for لام in some answers?', ['Emphasis on a striking or less expected outcome.', 'It must accompany all answers.', 'It can only follow a negative condition.', 'It signals a question.']),
    q('What governs زيدًا in لو زيدًا رأيته لأكرمته?', ['An omitted verb explained by رأيته.', 'لو as a verb.', 'لام in the answer.', 'The noun itself.']),
    q('What additional meaning does فلو أن لنا كرة... express?', ['Wishing for a return.', 'Simply denying a return.', 'An information question.', 'Commanding a present action.'])],
  '17/l2': [q('What is لولا’s conditional relation?', ['An existing condition prevents the stated answer.', 'Both condition and answer necessarily failed.', 'The condition always reinforces the answer.', 'The clauses have no conditional relation.']),
    q('What is the second clause in the examples?', ['A verbal clause serving as the answer.', 'A nominal answer in every example.', 'A verbal مبتدأ.', 'Only a prepositional predicate.']),
    q('What خبر is understood after فضل الله in the example?', ['موجود.', 'كبير.', 'معدوم.', 'منتف.']),
    q('How does conditional لوما relate to لولا?', ['A less common form with the same meaning and pattern.', 'It reverses لولا’s meaning.', 'It only appears in poetry.', 'It has no nominal clause.']),
    q('What happened in لوما التوفيق لما عملنا الصالحات?', ['Success was granted and deeds were done.', 'Neither occurred.', 'Success occurred but deeds did not.', 'Nothing about the actual outcome is conveyed.']),
    q('What must you identify before interpreting لو or لولا?', ['Which particle is present, then its construction and context.', 'Only the word count.', 'Whether it is a Quran quotation.', 'Only the verb’s written form.'])],
  '17/l3': [q('Which labels describe أمّا?', ['شرط، تفصيل، توكيد.', 'شرط، جزم، نصب.', 'تفصيل، عطف، جر.', 'توكيد، نفي، استفهام.']),
    q('What does the مهما يكن من شيء expansion help explain?', ['The construction’s emphasis.', 'Why أمّا cannot repeat.', 'Why every following noun must have رفع.', 'Why أمّا is limited to poetry.']),
    q('What does repeated أمّا for Thamud and Ad mark?', ['تفصيل after a joint mention.', 'Emphasis without any added detail.', 'Denial of either nation’s destruction.', 'A question about the two nations.']),
    q('Which intervening patterns were illustrated before governed nouns?', ['مبتدأ، خبر، جملة شرط.', 'Only a مبتدأ.', 'Only a bare preposition.', 'Only a vocative noun.']),
    q('What governs اليتيمَ before فلا تقهر?', ['تقهر in the response.', 'أمّا.', 'فاء.', 'An unrelated hidden noun.']),
    q('Under the author’s interpretation, what dominates أمّا زيد فمنطلق?', ['Emphasis in this single claim.', 'Detail between multiple cases.', 'Both equally with no prominence.', 'Neither: أمّا is meaningless.'])],
};
