import { card as c, part as p, visual as v, question as q, plan } from './helpers.js';

export const plans = {
  '22/l3': plan(111, 'A Verb Occupied with a Pronoun', [
    [c('The verb already governs a pronoun', 0, 1), c('The noun and its pronoun', 2, 3, 4)],
    [c('Three parts of الاشتغال', 0, 1), c('An omitted verb explained by another', 2)],
    [c('Two ordinary case options', 0, 1, 2, 3)],
    [c('A noun-only environment', 0, 1, 2, 3), c('A verb-only environment', 4, 5, 6)],
    [c('When نصب is preferred', 0, 1), c('An imperative favours نصب', 2, 3), c('Keep coordinated clauses parallel', 4, 5), c('After negative ما', 6, 7)],
    [c('The omitted verb must fit the object', 0, 1), c('Preparing punishment for someone', 2, 3)],
  ], [
    ['اشتغال', 'A following verb governs a returning pronoun or related expression.'],
    ['رفع / نصب', 'A nominal subject, or an object of an omitted explanatory verb.'],
    ['Context', 'Special particles can require a choice; other contexts favour نصب.'],
    ['Explanatory verb', 'It must fit the intended meaning and transitivity.'],
  ], { copy:{
    '0:0':'The fourth omitted-object-governor position is الاشتغال. A noun precedes a verb which is already occupied with that noun’s pronoun. The general category also includes a related noun containing the pronoun.',
    '0:3':'قصصنا governs returning هم. An omitted verb governs رسلا in the نصب account; the visible verb explains it. Remove هم to see the direct relation: قصصنا رسلا.',
    '1:1':'المشغول, also المشتغل, is the operating verb; المشغول به is its returning pronoun or related expression; المشغول عنه is the earlier noun.',
    '1:2':'The descriptive name ما أضمر عامله على شريطة التفسير means that a governor is omitted on condition that what follows explains it. When the first noun is منصوب, the omitted verb, not the visibly occupied verb, gives it نصب.',
    '2:1':'رفع makes a مبتدأ with a following predicate clause. نصب supplies an obligatorily omitted verb. Choosing نصب and omitting its governor are different decisions.',
    '2:3':'“The dead, Allah resurrects them.” الموتى permits both accounts; its final ألف hides the case. The نصب paraphrase supplies يبعث before it.',
    '3:1':'A noun-only environment, such as sudden إذا, requires a nominal start. An omitted transitive verb cannot occupy that position.',
    '3:3':'“Then, behold, Satan follows him.” الشيطانُ is مبتدأ after sudden إذا. This source example illustrates the noun-only environment; its object ـه refers to someone else, so it is not itself the defined returning-object الاشتغال pattern.',
    '3:6':'هلّا الجنة طلبتها supplies an omitted طلبت after the verb-requiring particle, so الجنة is منصوب. The source similarly gives إن الجنة تردها فاعمل صالحا. Use the relevant school’s analysis of the omitted verb after إنْ; conditional constructions have additional restrictions.',
    '4:1':'نصب is preferred with a requesting verb, after a coordinator directly following a verbal clause, or after a tool commonly introducing verbs, such as negative ما and the questioning hamzah. Preference is not obligation; simple nominal alternatives remain possible in these patterns.',
    '4:3':'“Allah, worship Him; His Messenger, follow him.” The imperatives اعبد and اتبع favour an omitted imperative before each fronted noun.',
    '4:5':'“I worship Allah; His Messenger I follow.” After a verbal clause, the نصب account gives the coordinated clause a parallel verbal structure.',
    '4:7':'“Satan, I do not follow.” The source favours نصب after negative ما here because of its common verbal construction, not because ما absolutely forbids nouns.',
    '5:1':'The explaining verb may require a different, semantically suitable omitted verb whose transitivity fits the fronted noun. “Synonym” need not mean identical meaning in every context.',
    '5:3':'أعدّ governs عذابا directly; لهم identifies the recipients. Therefore “prepared the wrongdoers” does not preserve this relation. Supply a suitable verb such as أوعد or يعذّب الظالمين. The source also proposes عدّ and كافأ, but these require contextual interpretation; أعدّ is not generally an intransitive verb.',
  }, boxCopy:{
    '0:1':['اسم متقدم، وعامل بعده مشغول بضميره أو سببيّه.'],
    '1:0':['المشغول، والمشغول به، والمشغول عنه.'],
    '2:0':['الأصل جواز الرفع بالابتداء أو النصب بعامل محذوف.'],
    '3:0':['بعد المختص بالاسم: الرفع في هذا الباب.'],
    '3:4':['بعد المختص بالفعل: عامل محذوف يفسره المذكور.'],
    '4:0':['يرجح النصب مع الطلب، أو العطف على فعلية، أو الغالب دخوله على الفعل.'],
    '5:0':['قد يفسر المذكور عاملًا آخر يلائم المعنى والتعدية.'],
  }, diagramLabels:{'0:4':{'المشغول عنه (منصوب بفعل محذوف يفسِّره المذكور)':'المشغول عنه: ينصبه عامل محذوف','المشغول (فعل) والمشغول به (ضمير هم)':'المشغول: قصصنا؛ المشغول به: هم'}}, visuals:{'1:1':v('Two distinct roles',['فعل محذوف','Governs the fronted noun'],['الفعل المذكور','Governs the returning pronoun'])}, analysisPrompt:'Use the نصب الاشتغال analysis.', analysisItemLabels:{'bank-18':{'المشغول عنه، منصوب بفعل محذوف وجوبًا':'المشغول عنه، مجرور بحرف جر','مفعول به منصوب':'مفعول مطلق منصوب'},'bank-19':{'مفعول به منصوب':'مفعول مطلق منصوب'}} }),
  '22/l4': plan(112, 'An Omitted Governor of حال', [
    [c('The حال remains, its governor is omitted', 0, 1, 2)],
    [c('A حال can stand in for a predicate', 0, 1, p(2,0)), c('The verb inside ما يكون', p(2,1)), c('A حال, with a predicate understood', 3, 4), c('Read the whole construction', 5)],
    [c('Gradual increase or decrease', 0, 1, 2), c('A rebuking question', 3, 4, 5)],
    [c('Reaffirming a whole statement', 0, 1), c('Confirming what is with them', 2, 3), c('Affection in the father example', 4, 5)],
    [c('Expressions learned from usage', 0, 1), c('A congratulatory expression', 2, 3), c('Returning safe and successful', 4, 5)],
  ], [
    ['حذف العامل', 'Four source patterns require omission; other forms are attested.'],
    ['سدّ مسدّ الخبر', 'The حال remains a حال while supplying the missing predicate’s meaning.'],
    ['Other patterns', 'Gradual change, rebuke and confirmation of a statement.'],
    ['سماعي', 'هنيئا لك and سالما غانما illustrate the adopted حال account.'],
  ], { copy:{
    '0:0':'This is the source’s third group of obligatory governor omission, after المفعول المطلق and المفعول به. The حال may be governed by a verb, a verbal derivative or verbal meaning. An omitted verb is still a لفظي governor, despite the source’s “حذف العامل المعنوي” wording.',
    '0:2':'Four regular patterns are taught, followed by attested expressions outside that set. The lesson concerns omission of the governor, not omission of the حال itself.',
    '1:4':'The natural translation sounds like a predicate: “The servant is closest when prostrating.” In the adopted parse, however, وهو ساجد remains a حال. An understood predicate such as حاصل supplies its government; سدّ مسدّ الخبر does not make the same clause both حال and خبر.',
    '2:2':'“Give a dirham, then more.” صاعدا expresses increasing amount; the source supplies يزيد. The regular construction joins this gradual rise or fall with فاء, or less commonly ثمّ.',
    '2:5':'“Still sitting, when the prayer has been established?” The rebuke supplies a verb such as بقيت or لبثت in an intransitive sense. The source’s paraphrase ألم تزل قاعدا instead makes قاعدا a خبر of ناقص زال, so it explains the meaning but not the same حال analysis.',
    '3:1':'The taught pattern has a حال matching the preceding assertion, with a definite, non-derived مبتدأ and خبر. Its governor is understood, for example أحقّه or أعرفه according to meaning. This account concerns the specified confirming pattern, not all kinds of حال.',
    '3:3':'“It is the truth, confirming what is with them.” The source adopts حال مؤكّدة, reading confirmation as fitting the claim’s truth. Other accounts object that confirming an earlier revelation adds a particular relation not implied by “truth” alone. Exercises identify the stated account.',
    '3:5':'“Khalid is your father, affectionate.” خالد and أبوك are definite and non-derived here. عطوفا reaffirms the affection associated with fatherhood in this conventional example; it is not a logical claim that every actual father is affectionate.',
    '4:1':'These expressions receive the source’s سماعي حال analysis through usage, rather than one of its four general patterns. Other grammatical accounts of some formulas are possible.',
    '4:3':'هنيئا لك is a fixed congratulation or wish for pleasant enjoyment. The source reads هنيئا as حال with an understood governor, such as ثبت لك الخير هنيئا.',
    '4:5':'سالما غانما wishes or describes a safe, successful return. Both words are حال in the account taught; a verb such as رجع is understood.',
  }, boxCopy:{
    '0:1':['يحذف عامل الحال وجوبًا في أنماط قياسية وتراكيب سماعية.'],
    '1:0':['الحال السادة مسد الخبر يغني ذكرها عن عاملهـا المحذوف.'],
    '1:3':['وهو ساجد: حال، تسد مسد الخبر في التحليل المعتمد.'],
    '2:0':['زيادة أو نقص بتدريج مع الفاء أو ثمّ.'],
    '2:3':['قد يحذف عامل الحال بعد استفهام التوبيخ.'],
    '3:0':['حال توافق مضمون جملة من مبتدأ وخبر معرفتين جامدين.'],
  }, copyParts:{'1:2':[
    '“The servant is closest to his Lord while prostrating.” أقرب is مبتدأ; ما is مصدرية. The adopted account supplies a predicate such as حاصل له. The clause وهو ساجد fills its sense as حال, with government understood through that supplied predicate.',
    'The source calls يكون ناقصة with العبد its اسم, but does not specify its needed predicate. A well-attested account instead makes يكون تامة and العبد its فاعل, with من ربه attached to أقرب. Neither requires treating وهو ساجد as an ordinary خبر of أقرب.',
  ]}, visuals:{'1:1':v('Two accounts of يكون',['تامة','العبد: فاعل'],['ناقصة','Needs اسم and خبر'])}, analysisPrompt:'Use the displayed حال analysis.', analysisItemLabels:{'bank-18':{'خبر مرفوع':'مفعول مطلق منصوب'}} }),
  '22/l1': plan(109, 'Competing and Omitted Governors', [
    [c('Competing governors', 0, 1, 2, 3), c('Two verbs share the phrase', 4, 5, 6), c('Two adjectives share the subject', 7, 8)],
    [c('One expression, two possible attachments', 0, 1), c('More than two can compete', 2, 3, 4, 5)],
    [c('Optional and obligatory omission', 0, 1, 2), c('Two directive patterns', 3, 4), c('A command followed by prohibition', 5, 6), c('A question used for rebuke', 7, 8)],
    [c('Detail and confirmation', 0, 1, 2), c('Two options after إمّا', 3, 4), c('Confirming the whole sentence', 5, 6)],
    [c('Expressions learned from usage', 0, 1), c('The family of لبّيك', 2, 3, 4)],
  ], [
    ['تنازع / إعمال', 'Two or more governors seek a following shared expression.'],
    ['Actual government', 'Assign one governor; the others still need an appropriate analysis.'],
    ['قياسي', 'Four source patterns omit a مصدر’s governor by rule.'],
    ['سماعي', 'Learn fixed expressions; لبّيك’s dual shape conveys repetition.'],
  ], { copy: {
    '0:0':'The closing section on العامل begins with التنازع: competing government.',
    '0:2':'Both precede an expression each could govern. Assign one actual governor; the other needs a suitable pronoun or omission. Their semantic relations need not be identical.',
    '0:5':'“Eat and drink from Allah’s provision.” Both commands relate to من رزق الله, written once after them. The diagram identifies the competitors and their shared phrase.',
    '0:8':'“I do not know whether what you are promised is near or far.” قريب and بعيد are operating adjectives competing for ما توعدون as subject in the account taught.',
    '1:0':'التنازع is also called الإعمال. A shared expression gives economy without removing either semantic relation.',
    '1:1':'Either governor may be selected under the construction’s rules; schools differ over preference. The present examples can keep the same visible ending. This is not universally true: competing subject/object demands can change case and require different pronouns.',
    '1:3':'Three or more governors can share an expression.',
    '1:5':'The hadith mentions saying سبحان الله, الحمد لله and الله أكبر after each prayer, thirty-three times. The three verbs share the time phrase دبر كل صلاة and the count ثلاثا وثلاثين مرة.',
    '2:0':'حذف العامل may be optional when context recovers it, or obligatory in a prescribed construction. The source’s three obligatory groups begin with the governor of المفعول المطلق.',
    '2:2':'This source organizes مصدر omission into four قياسي patterns and attested سماعي expressions. These are the patterns studied here, not an exhaustive count for every grammar book.',
    '2:4':'One pattern pairs a command-like مصدر with a prohibited alternative. Another places the مصدر after a question of rebuke. In both, the governing verbs remain unspoken in the construction.',
    '2:6':'“Patience, not panic”: اصبر صبرا ولا تجزع جزعا explains the meaning. Compare حمدا وشكرا لا كفرا and اجتهادا لا كسلا. These explanations reveal the omitted verbs; they are not added to the original utterance.',
    '2:8':'“Such boldness in disobedience?” The source supplies أتجترئ جرأة على المعاصي. The question rebukes the behaviour rather than seeking information.',
    '3:0':'Two further patterns complete the source’s set.',
    '3:2':'A مصدر after إمّا can detail earlier general instruction. A مصدر can also affirm the truth of the whole preceding statement.',
    '3:4':'After the instruction فشدّوا الوثاق, منّا and فداءً name the subsequent alternatives of release by favour or ransom. The grammatical account supplies verbs such as تمنّون and تفادون. The details are alternatives following the earlier instruction, not synonyms of “bind”.',
    '3:6':'حقّا confirms the whole claim: “Those are truly the believers.” Related emphatic forms are بتّا، بتاتا، بتّة and البتّة. The source also records ألبتّة with a cut hamzah; that pronunciation is disputed and non-analogical, while وصل is the regular account.',
    '4:0':'سماعي expressions omit the governor through attested usage. Learn them in their established constructions rather than extending them freely.',
    '4:2':'The related forms are لبّيك، سعديك، حنانيك، دواليك and حذاريك.',
    '4:4':'Their dual shape expresses repeated or intensified action, not exactly two occurrences. لبّيك conveys response after response and continuing readiness to answer.',
  }, boxCopy:{
    '0:1':['تنازع عاملين في معمول متأخر عنهما.'],
    '0:3':['فعلان، أو وصفان عاملان، أو فعل ووصف عامل.'],
    '2:1':['حذف عامل المصدر: قياسي وسماعي.'],
    '2:3':['أمر ونهي بمصدرين؛ أو مصدر بعد استفهام التوبيخ.'],
    '3:1':['تفصيل بعد إمّا؛ أو تأكيد لمضمون الجملة.'],
    '4:3':['التثنية هنا للتكثير، لا لعدد اثنين.'],
  }, analysisPrompt:'Identify the roles in التنازع.', analysisItemLabels:{'bank-18':{'فعل أمر مبني على حذف النون':'فعل ماض مبني على الفتح'},'bank-19':{'صفة مشبهة مرفوعة':'مصدر منصوب','مبتدأ مرفوع':'مفعول مطلق منصوب'}} }),
  '22/l2': plan(110, 'Warning, Urging and Specification', [
    [c('Warn someone away from harm', 0, 1, 2)],
    [c('The four roles in a warning', 0, 1), c('Three patterns with إيّاك', 2, 3), c('A coordinated warning', 4, 5), c('A preposition expressed or understood', 6, 7)],
    [c('Warn using a visible noun', 0, 1, 2), c('Repeat the expression warned against', 3, 4, 5), c('Warning meaning with a visible verb', 6, 7)],
    [c('Urge someone toward good', 0, 1), c('The four roles in urging', 2, 3), c('Repetition and coordination', 4, 5, 6, 7, 8), c('Urging with an explicit verb', 9)],
    [c('Related welcoming expressions', 0, 1, 2), c('Leave a person to himself', 3, 4)],
    [c('Specify a pronoun’s referent', 0, 1, 2, 3), c('اختصاص with أيّها', 4, 5, 6)],
  ], [
    ['تحذير', 'Warn against harm; the prescribed forms omit their governor.'],
    ['إغراء', 'Urge toward good; repetition or coordination requires omission.'],
    ['ملحق', 'Similar omitted-verb expressions need not warn or urge.'],
    ['اختصاص', 'An understood أخصّ or أعني specifies a preceding pronoun.'],
  ], { copy:{
    '0:0':'The source next studies omitted governors of المفعول به, organized into five positions. التحذير is the first.',
    '0:2':'التحذير warns the addressee away from harm. Compare التوبيخ, which reproaches conduct already occurring or done. Their purposes differ; actual speech can combine a rebuke with a warning.',
    '1:1':'The four roles: an understood warning verb, the speaker who warns, the addressee warned, and the danger. The source gives احذر، باعد، تجنّب، قِ and توقّ as explanatory verbs. Choose a verb and subject appropriate to each construction.',
    '1:2':'إيّاك identifies the addressee. In the standard warning construction its governor is obligatorily omitted.',
    '1:5':'“Beware of envy.” The source adopts coordination: الحسدَ joins إيّاك. Other analyses distinguish the supplied verbs or treat the و differently; exercises ask for this account.',
    '1:7':'إيّاك من الحسد expresses مِن. إيّاك أن تحسد has an understood relation through مِن before the clause. Both warn against envy without repeating the full governing verb.',
    '2:0':'A visible noun such as نفسك can identify the person warned. The source illustrates it alone, repeated, or coordinated with the danger. Alone, omission is optional; repetition or coordination requires it.',
    '2:2':'نفسك والحسد: “Save yourself from envy.” The visible noun replaces the separate pronoun in this warning pattern.',
    '2:3':'Another pattern states only the warning target, repeated or coordinated with another target. It does not need إيّاك or a noun explicitly identifying the addressee.',
    '2:5':'اللهَ اللهَ means “Fear Allah”, with repetition. In the source’s warning account, the warning concerns disobedience or punishment, not Allah as an ordinary harmful object. Read as urging observance, it can instead be discussed with إغراء.',
    '2:7':'قوا أنفسكم وأهليكم نارا plainly warns, but قوا is a spoken imperative. It is not the omitted-verb warning construction defined here. Meaning and the technical syntactic category need not coincide.',
    '3:0':'الإغراء encourages the addressee to pursue something good.',
    '3:3':'Its four roles are the understood urging verb, speaker, addressee and good thing urged. The source supplies الزم، اطلب، خذ and افعل as explanatory verbs.',
    '3:6':'الصبر الصبر urges patience by repetition.',
    '3:8':'العلم والحلم coordinates knowledge and forbearance. Repetition or coordination requires omission; a single uncoordinated noun can have optional omission.',
    '3:9':'يا يحيى خذ الكتاب بقوة encourages taking the Book firmly, but خذ is explicit. It expresses urging without being the omitted-verb إغراء construction.',
    '4:0':'Other set phrases have a similar omitted governor without themselves warning or urging. They are ملحق, attached to the family by their syntax.',
    '4:2':'مرحبا وأهلا وسهلا is explained through أصبت: “You have found spaciousness, welcoming people and easy ground”. These are traditional explanatory glosses of a welcome.',
    '4:4':'وامرأ ونفسه is explained through دع: “Leave a man to himself”. The governing command is unspoken.',
    '5:0':'الاختصاص clarifies a pronoun, or expresses pride or modesty. Ambiguity is not compulsory.',
    '5:3':'أهل البيت specifies عليكم through understood أعني or أخصّ. The angels address Ibrahim’s household through Sarah (11:73), not the Companions, Muhajirun or Ansar mentioned in the source.',
    '5:4':'أيّها and أيّتها can specify a pronoun without يا. In this construction أيّ is built on ضم in an accusative position, and its following descriptor has رفع, resembling the vocative form.',
    '5:6':'In Ka‘b ibn Malik’s account, كلامنا أيّها الثلاثة specifies “us, the three”. It identifies the pronoun’s referents without turning the sentence into a call addressed to someone else.',
  }, boxCopy:{
    '0:1':['التحذير: اسم منصوب بعامل محذوف للتنبيه على ما يجتنب.'],
    '1:0':['فعل التحذير، والمحذِّر، والمحذَّر، والمحذَّر منه.'],
    '1:3':['إيّاك والحسدَ: عطف.','إيّاك إيّاك المراءَ: تكرار ثم نصب.','إيّاك من الحسدِ: جر بمن، ملفوظة أو مقدرة.'],
    '3:1':['الإغراء: الحث على مرغوب باسم منصوب بعامل محذوف.'],
    '3:2':['فعل الإغراء، والمغري، والمغرى، والمغرى به.'],
    '3:4':['يجب حذف العامل مع التكرار أو العطف.'],
    '5:1':['اختصاص: أخصّ أو أعني.'],
  }, visuals:{'3:3':v('A spoken governor',['خذ','Explicit imperative'],['الكتاب','Its object'])}, analysisPrompt:'Use the coordination account.', analysisItemLabels:{'bank-18':{'مفعول به منصوب':'نائب فاعل مرفوع'}} }),
};

export const checks = {
  '22/l3':[q('What does قصصنا govern visibly in ورسلا قد قصصناهم?', ['The returning pronoun هم.','رسلا directly without a pronoun.','Nothing.','Both رسلا and هم as one direct object.'],'The fronted نصب has an omitted governor.'),q('What does على شريطة التفسير explain?', ['The following verb reveals the omitted governor.','The governor is always visibly repeated.','There is no returning pronoun.','Two visible governors compete for one expression.'],'This names the نصب account of الاشتغال.'),q('What case accounts are discussed for الموتى يبعثهم الله?', ['رفع as مبتدأ or نصب by an omitted verb.','Only رفع is ever possible.','Only نصب is ever possible.','No grammatical role exists.'],'The final ألف conceals the ending.'),q('How is الجنة treated after هلّا in هلّا الجنة طلبتها?', ['منصوب by an omitted verb.','مرفوع because هلّا requires a noun.','Freely either case in this pattern.','Without any syntactic role.'],'هلّا requires a verbal construction.'),q('Why is نصب preferred in الله اعبده?', ['The requesting verb favours an omitted imperative.','Every imperative forces رفع.','Only because the Name is definite.','No preference exists.'],'Preference does not make رفع universally impossible.'),q('Why not supply أعدّ directly before الظالمين in this meaning?', ['The people are recipients through لام; punishment is the direct object.','A past verb can never explain an omitted verb.','A plural noun cannot be an object.','Preparing people is exactly the intended relation.'],'أعدّ does take عذابا as a direct object.')],
  '22/l4':[q('Where does حذف عامل الحال stand in the source’s omission groups?', ['Third.','First.','Second.','Outside the groups entirely.'],'After the governors of المفعول المطلق and المفعول به.'),q('What is وهو ساجد in the adopted hadith analysis?', ['حال standing in for the omitted predicate’s sense.','The ordinary خبر directly.','Neither حال nor connected to a predicate.','Both an ordinary خبر and حال simultaneously.'],'Keep grammatical role separate from translation.'),q('What licenses the صاعدا construction taught?', ['Gradual increase with فاء or ثمّ.','Only rebuke after a question.','Only confirming a prior statement.','No regular condition at all.'],'The source supplies يزيد.'),q('What noun pattern is required in خالد أبوك عطوفا here?', ['Definite, non-derived مبتدأ and خبر.','Indefinite derived nouns only.','Only a definite مبتدأ.','No condition on either noun.'],'The example uses a conventional association with affection.'),q('How is the omission in سالما غانما classified here?', ['سماعي.','The first قياسي pattern.','The fourth قياسي pattern.','No omission.'],'The source supplies a return verb.')],
  '22/l1':[q('What names the shared government in كلوا واشربوا من رزق الله?', ['التنازع, also الإعمال.','الاشتغال.','الاختصاص.','حذف عامل المفعول المطلق.'],'Both verbs precede the shared phrase.'),q('Can either governor receive the shared phrase in these examples?', ['Yes; these examples can retain the same visible case.','Only the first is ever allowed.','Only the second is ever allowed.','The construction is invalid until all schools agree.'],'This does not guarantee identical case in every تنازع.'),q('What pattern does صبرا لا جزعا illustrate?', ['Prohibition paired with a command-like مصدر.','A question of rebuke.','Detail after إمّا.','Confirmation of a statement.'],'Supply اصبر and لا تجزع to explain the meaning.'),q('What does حقّا confirm in أولئك هم المؤمنون حقّا?', ['The truth of the whole statement.','Only المؤمنون as an adjective.','Only أولئك as a repeated demonstrative.','Nothing.'],'It is مؤكّد لمضمون الجملة.'),q('Does لبّيك mean responding exactly twice?', ['No; its dual shape conveys repeated response.','Yes, a literal regular dual.','No relation to dual shape exists.','Only if spoken twice.'],'Think of response after response.')],
  '22/l2':[q('Which function warns against harm to be avoided?', ['التحذير.','Only التوبيخ.','Both refer exclusively to completed events.','Neither.'],'Distinguish warning from reproach.'),q('In the adopted account, how does إياك والحسد join the danger?', ['By coordination with إيّاك.','By repeating the pronoun.','By مِن.','By replacing إيّاك with a visible noun.'],'The و is the coordinator in this account.'),q('Is قوا أنفسكم the omitted-verb تحذير construction?', ['No; قوا is a spoken imperative.','Yes; every warning has that syntax.','Yes, because نارا is accusative.','No; it contains no warning meaning.'],'Separate meaning from grammatical construction.'),q('When must an إغراء governor be omitted?', ['With repetition or coordination.','With any definite noun only.','After every preposition.','Never; omission is always optional.'],'Compare الصبر الصبر and العلم والحلم.'),q('What verb does the source supply for مرحبا?', ['أصبت.','دع.','احذر.','الزم.'],'The greeting welcomes someone to ease and spaciousness.'),q('What does أهل البيت do in the اختصاص analysis?', ['It specifies the referents of عليكم.','It negates عليكم.','It turns عليكم into a vocative noun.','It has no clarifying function.'],'The verse addresses Ibrahim’s household.')],
};

export const quizzes = {
  '22/l3':[q('Name the three components of الاشتغال.', ['المشغول، المشغول به، المشغول عنه.','المحذّر، المحذّر، المحذّر منه.','المغري، المغرى، المغرى به.','Only العامل والمعمول والإعراب.']),q('What two accounts are discussed for الموتى يبعثهم الله?', ['رفع بالابتداء or نصب by an omitted explanatory verb.','Only genitive after an understood preposition.','Only fixed فتح.','Only نصب without another account.']),q('Why does sudden إذا require الشيطانُ to have رفع here?', ['It introduces a nominal construction.','It introduces only verbs.','الشيطان can never take another case.','Every following verb requires a separate overt subject.']),q('What type of tool is هلّا in هلّا الجنة طلبتها?', ['A verb-requiring تحضيض tool.','A noun-only tool.','A question seeking a choice of nouns.','A reply particle.']),q('Why is نصب preferred in الله اعبده?', ['The verb expresses طلب.','The verb only reports a fact.','The Name cannot take رفع.','A noun-only tool precedes it.']),q('What omitted verb fits والظالمين أعد لهم عذابا in the adopted account?', ['A suitable direct-governing verb, such as أوعد.','أعدّ with الظالمين as the thing prepared.','No omitted governor.','A warning to avoid the wrongdoers.'])],
  '22/l4':[q('Does the source include attested omissions beyond its four regular patterns?', ['Yes, a سماعي group.','No, exactly four expressions exist.','Only for المفعول المطلق.','No governor of حال is ever omitted.']),q('Which word does the source explicitly supply for the omitted predicate of أقرب?', ['حاصل.','ساجد as an ordinary predicate.','أقرب repeated as a verb.','No predicate is needed.']),q('What introduces the gradual صاعدا pattern taught?', ['فاء or ثمّ.','Only و.','Only أم.','No linking particle.']),q('What triggers omission in أقاعدا وقد أقيمت الصلاة?', ['A question used for rebuke.','Gradual change.','Confirmation of the preceding statement.','A حال standing in for a predicate.']),q('What relation does the source’s مؤكّدة account assign to مصدقا?', ['Confirmation consistent with the preceding claim of truth.','An entirely unrelated claim.','A description only of another subject.','No relation to الحق.']),q('How does the source classify هنيئا لك under its حال account?', ['سماعي.','First قياسي pattern.','Second قياسي pattern.','Third قياسي pattern.'])],
  '22/l1':[q('What is the relation in كلوا واشربوا من رزق الله?', ['تنازع / إعمال.','اشتغال.','اختصاص.','تحذير.']),q('What competitors are قريب and بعيد in the adopted analysis?', ['Two operating nouns.','Two verbs.','Two prepositions.','No competing words.']),q('What pattern does صبرا لا جزعا show?', ['A command-like مصدر followed by prohibition.','A question of rebuke.','Detail after إمّا.','Confirmation of a whole claim.']),q('What pattern does أجرأة على المعاصي show?', ['A rebuking question.','Prohibition after command.','Detail after إمّا.','Confirmation of a statement.']),q('What relation do منّا and فداءً have after the earlier instruction?', ['تفصيل لمجمل.','توبيخ.','تأكيد لمضمون الجملة.','نهي تابع لأمر.']),q('How does the source classify omission in سبحان الله and لبّيك?', ['سماعي: attested expressions.','The first قياسي pattern.','The fourth قياسي pattern.','No omission occurs.'])],
  '22/l2':[q('What distinguishes warning from reproach in the basic contrast?', ['Warning seeks avoidance; reproach censures conduct.','Warning always concerns only completed events.','They are identical technical constructions.','Warning can never omit a verb.']),q('What pattern is إيّاك إيّاك المراءَ?', ['Repeated pronoun, then accusative danger without coordination.','Coordination with إيّاك.','A danger after مِن.','A visible noun instead of إيّاك.']),q('Which source pattern does الله الله illustrate under its warning account?', ['The third: repetition without an expressed addressee.','The first: إيّاك.','The second: نفسك.','No repeated expression.']),q('Why must the governor be omitted in الصبر الصبر?', ['The urged noun is repeated.','It is merely definite.','It is merely a مصدر.','Omission is never required.']),q('How are مرحبا and وامرأ ونفسه grouped here?', ['ملحق بالتحذير والإغراء.','اختصاص.','اشتغال.','تنازع.']),q('How does أيّها work in كلامنا أيّها الثلاثة?', ['Its form resembles vocative syntax, while its function is specification.','Its form has no shared vocative rules.','It is ungrammatical without يا.','It must be a separate call.'])],
};
