// قَصَصُ النَّبِيِّينَ, volume 6 (Mūsā, part 1), chapter 24 -- بَيْنَ الْحَقِّ
// وَالْبَاطِلِ. Printed pages 152 (heading, partway down, right after
// ch23's closing line "وَفَرِحَ السَّحَرَةُ بِمَوَاعِيدِ فِرْعَوْنَ") - 153 - 154 -
// 155 (top only), ending right before ch25's heading «وَعِيدُ فِرْعَوْنَ»
// which opens partway down page 155 (already transcribed, see
// qasas-v6/chapter-25.js). Transcribed by hand from the scan (vision OCR,
// 200dpi render) against ../CHAPTER-FORMAT.md. Covers Sūrat Ṭāhā 20:66-70
// and Sūrat Yūnus 10:81-82: the contest itself, Mūsā's momentary fear and
// Allah's reassurance, the staff swallowing the sorcerers' illusion, and
// the sorcerers' immediate conversion.
//
// Grammar / lexical notes:
//   -- غَلَبُ مُوسَى / غَلَبُ رَجُلٍ / غَلَبُ دِينٍ / غَلَبُ حَقٍّ (qs-v6-c24-007/
//      008) is Nadwi's own parallel-construct set piece reframing the
//      contest's stakes -- matching the corpus's recurring rhetorical-
//      repetition convention (see ch2's هُوَ الَّذِي, ch14's حَبَّذَا/شَقَاوَةَ,
//      ch19's fourfold إِنَّ).
//   -- Shared lexicon check (cross-checked against known_lemmas.json):
//      رَأَى, مُوسَى, النَّاسُ, فَإِذَا, حِبَال, عَصًا, سِحْر, أَنَّ, سَعَى, فِي,
//      قَلْب, لِمَاذَا, لا, يَوْم, عِنْدَ, اِمْتِحَان, أَكْرَمَ, رَجُل, أَوْ, أَهَانَ,
//      إِذَا, غَلَبَ, سَاحِر, لَا, قَدَّرَ, اللَّه, ذَلِكَ, سَمَحَ, بِ, مَاذَا, كَانَ,
//      عِيَاذ, لَيْسَ, بَلْ, هُوَ, دِين, أَمَامَ, مَلِك, حَقّ, لَكِنَّ, قَالَ, خَافَ,
//      إِنَّ, أَنتَ, أَعْلَى, أَلْقَى, يَمِين, صَنَعَ, إِنَّمَا, يُفْلِحُ/أَفْلَحَ, أَتَى,
//      مَا, جَاءَ, يُصْلِحُ/أَصْلَحَ, عَمِلَ, مُفْسِد, يُحِقُّ/أَحَقَّ, كَلِمَة, لَوْ,
//      كَرِهَ, مُجْرِم, وَقَعَ, عَمِلَ, أَيّ, شَيْء, نَعْرِفُ/عَرَفَ, أَصْل, نَوْع,
//      نَحْنُ, فَنّ, ضَرَبَ, أَمَامَ, شَمْس, مِنْ, أَيْنَ, نَبِيّ, قَدْ, مَنَحَ,
//      فَصَرَخُوا/صَرَخَ, رَبّ, هَارُون, سَجَدَ, رَبّ الْعَالَمِينَ
//      are all already taught (or reused) and are NOT re-listed in
//      newWords here.
//
// ~24 new words (خَطَرَ، خَاطِر، خَوْف، رِهَان، بَاطِل، شَجَّعَ، تَلَقَّفَ، كَيْد،
// أَبْطَلَ، أَصْلَحَ، أَحَقَّ، كَلِمَة، أَفَكَ، بَطَلَ، دُهِشَ، بُهِتَ، أُسْتَاذ، إِمَام،
// قَرَعَ، اِضْمَحَلَّ، ذَابَ، نَدَى، اِقْتَنَعَ، مُعْجِزَة، هَتَفَ -- the climactic
// contest chapter, dense with Qur'an citation).
export const CHAPTER = {
  id: 'ch24',
  title: { ar: 'بَيْنَ الْحَقِّ وَالْبَاطِلِ', en: 'Between Truth and Falsehood' },
  newWords: ['خَيَّلَ', 'أَصْل', 'خَطَرَ', 'خَاطِر', 'خَوْف', 'رِهَان', 'بَاطِل', 'شَجَّعَ', 'تَلَقَّفَ', 'كَيْد', 'أَبْطَلَ', 'أَصْلَحَ', 'أَحَقَّ', 'كَلِمَة', 'أَفَكَ', 'بَطَلَ', 'دُهِشَ', 'بُهِتَ', 'أُسْتَاذ', 'إِمَام', 'قَرَعَ', 'اِضْمَحَلَّ', 'ذَابَ', 'نَدَى', 'اِقْتَنَعَ', 'مُعْجِزَة', 'هَتَفَ'],
  lemmas: {
    خَيَّلَ: { gloss: 'to make appear, cause to imagine' },
    أَصْل: { gloss: 'origin, root' },
    خَطَرَ: { gloss: 'to occur (to the mind)' },
    خَاطِر: { gloss: 'a thought, notion' },
    خَوْف: { gloss: 'fear' },
    رِهَان: { gloss: 'a wager, stake' },
    بَاطِل: { gloss: 'falsehood' },
    شَجَّعَ: { gloss: 'to encourage, embolden' },
    تَلَقَّفَ: { gloss: 'to swallow up, snatch' },
    كَيْد: { gloss: 'a trick, scheme' },
    أَبْطَلَ: { gloss: 'to nullify, render void' },
    أَصْلَحَ: { gloss: 'to set right, make good' },
    أَحَقَّ: { gloss: 'to establish as true, confirm' },
    كَلِمَة: { gloss: 'a word' },
    أَفَكَ: { gloss: 'to fabricate, contrive falsely' },
    بَطَلَ: { gloss: 'to be nullified, come to nothing' },
    دُهِشَ: { gloss: 'to be astonished' },
    بُهِتَ: { gloss: 'to be dumbfounded' },
    أُسْتَاذ: { gloss: 'a master, teacher (of a craft)' },
    إِمَام: { gloss: 'a leading authority (pl. أَئِمَّة)' },
    قَرَعَ: { gloss: 'to strike, knock' },
    اِضْمَحَلَّ: { gloss: 'to dwindle away, vanish' },
    ذَابَ: { gloss: 'to melt' },
    نَدَى: { gloss: 'dew' },
    اِقْتَنَعَ: { gloss: 'to be convinced' },
    مُعْجِزَة: { gloss: 'a miracle' },
    هَتَفَ: { gloss: 'to cry out, shout' },
  },
  paragraphs: [
    {
      en: '"Mūsā saw what the people saw: their ropes and staffs, through their magic, appeared to him to be moving." A thought of fear occurred in Mūsā\'s heart! And why wouldn\'t Mūsā fear? This is the day of the wager! At the test, a man is honored or disgraced! If the sorcerers won -- may Allah never decree that. If Mūsā were defeated -- may Allah never allow that. Then what would happen? We seek refuge in Allah!! Mūsā\'s defeat would not be one man\'s defeat -- it would be the defeat of a religion before a king. Rather, it would be the defeat of truth before falsehood. May Allah never decree that! May Allah never allow that! But Allah encouraged him and said:',
      sentences: [
        {
          id: 'qs-v6-c24-001',
          ar: 'وَرَأَى مُوسَى مَا رَأَى النَّاسُ ﴿فَإِذَا حِبَالُهُمْ وَعِصِيُّهُمْ يُخَيَّلُ إِلَيْهِ مِن سِحْرِهِمْ أَنَّهَا تَسْعَى﴾.',
          en: 'Mūsā saw what the people saw: "their ropes and staffs, through their magic, appeared to him to be moving."',
          tokens: [
            { surface: 'وَرَأَى', lemma: 'رَأَى', pos: 'verb', features: 'conj+perf.3ms', root: 'ر أ ي', gloss: 'to see; and saw' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'nom', gloss: 'Mūsā' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'what' },
            { surface: 'رَأَى', lemma: 'رَأَى', pos: 'verb', features: 'perf.3ms', root: 'ر أ ي', gloss: 'saw' },
            { surface: 'النَّاسُ', lemma: 'نَاس', pos: 'noun', features: 'def.nom', gloss: 'the people' },
            { surface: 'فَإِذَا', lemma: 'إِذَا', pos: 'adv', features: 'conj+adv', gloss: 'and behold' },
            { surface: 'حِبَالُهُمْ', lemma: 'حِبَال', pos: 'noun', features: 'nom+3mp', gloss: 'their ropes' },
            { surface: 'وَعِصِيُّهُمْ', lemma: 'عَصًا', pos: 'noun', features: 'conj+nom.pl+3mp', gloss: 'and their staffs' },
            { surface: 'يُخَيَّلُ', lemma: 'خَيَّلَ', pos: 'verb', features: 'pass+impf.3ms', gloss: 'to make appear; appeared' },
            { surface: 'إِلَيْهِ', lemma: 'إِلَى', pos: 'prep', features: 'prep+3ms', gloss: 'to him' },
            { surface: 'مِن', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'through' },
            { surface: 'سِحْرِهِمْ', lemma: 'سِحْر', pos: 'noun', features: 'gen+3mp', gloss: 'their magic' },
            { surface: 'أَنَّهَا', lemma: 'أَنَّ', pos: 'part', features: 'part+3fs', gloss: 'that they' },
            { surface: 'تَسْعَى', lemma: 'سَعَى', pos: 'verb', features: 'impf.3fs', gloss: 'to move; were moving' },
          ],
        },
        {
          id: 'qs-v6-c24-002',
          ar: 'وَخَطَرَ فِي قَلْبِ مُوسَى خَاطِرُ خَوْفٍ! وَلِمَاذَا لا يَخَافُ مُوسَى؟',
          en: "A thought of fear occurred in Mūsā's heart! And why wouldn't Mūsā fear?",
          tokens: [
            { surface: 'وَخَطَرَ', lemma: 'خَطَرَ', pos: 'verb', features: 'conj+perf.3ms', root: 'خ ط ر', gloss: 'to occur; occurred' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'قَلْبِ', lemma: 'قَلْب', pos: 'noun', features: 'constr.gen', gloss: 'the heart of' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'gen', gloss: 'Mūsā' },
            { surface: 'خَاطِرُ', lemma: 'خَاطِر', pos: 'noun', features: 'nom.constr', root: 'خ ط ر', gloss: 'a thought of' },
            { surface: 'خَوْفٍ', lemma: 'خَوْف', pos: 'noun', features: 'indef.gen', root: 'خ و ف', gloss: 'fear' },
            { surface: 'وَلِمَاذَا', lemma: 'لِمَاذَا', pos: 'adv', features: 'conj+adv', gloss: 'and why' },
            { surface: 'لا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'يَخَافُ', lemma: 'خَافَ', pos: 'verb', features: 'impf.3ms', gloss: 'would fear' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'nom', gloss: 'Mūsā' },
          ],
        },
        {
          id: 'qs-v6-c24-003',
          ar: 'هَذَا يَوْمُ الرِّهَانِ! وَعِنْدَ الِامْتِحَانِ يُكْرَمُ الرَّجُلُ أَوْ يُهَانُ!',
          en: 'This is the day of the wager! At the test, a man is honored or disgraced!',
          tokens: [
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'this' },
            { surface: 'يَوْمُ', lemma: 'يَوْم', pos: 'noun', features: 'nom.constr', gloss: 'is the day of' },
            { surface: 'الرِّهَانِ', lemma: 'رِهَان', pos: 'noun', features: 'def.gen', root: 'ر ه ن', gloss: 'the wager' },
            { surface: 'وَعِنْدَ', lemma: 'عِنْدَ', pos: 'prep', features: 'conj+prep', gloss: 'and at' },
            { surface: 'الِامْتِحَانِ', lemma: 'اِمْتِحَان', pos: 'noun', features: 'def.gen', gloss: 'the test' },
            { surface: 'يُكْرَمُ', lemma: 'أَكْرَمَ', pos: 'verb', features: 'pass+impf.3ms', gloss: 'to honor; is honored' },
            { surface: 'الرَّجُلُ', lemma: 'رَجُل', pos: 'noun', features: 'def.nom', gloss: 'the man' },
            { surface: 'أَوْ', lemma: 'أَوْ', pos: 'conj', features: 'conj', gloss: 'or' },
            { surface: 'يُهَانُ', lemma: 'أَهَانَ', pos: 'verb', features: 'pass+impf.3ms', gloss: 'to disgrace; is disgraced' },
          ],
        },
        {
          id: 'qs-v6-c24-004',
          ar: 'وَإِذَا غَلَبَ السَّحَرَةُ - لَا قَدَّرَ اللَّهُ ذَلِكَ.',
          en: 'If the sorcerers won -- may Allah never decree that.',
          tokens: [
            { surface: 'وَإِذَا', lemma: 'إِذَا', pos: 'adv', features: 'conj+adv', gloss: 'and if' },
            { surface: 'غَلَبَ', lemma: 'غَلَبَ', pos: 'verb', features: 'perf.3ms', gloss: 'won' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'may not' },
            { surface: 'قَدَّرَ', lemma: 'قَدَّرَ', pos: 'verb', features: 'perf.3ms', gloss: 'to decree; decree' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'ذَلِكَ', lemma: 'ذَلِكَ', pos: 'dem', features: 'dem', gloss: 'that' },
          ],
        },
        {
          id: 'qs-v6-c24-005',
          ar: 'وَإِذَا غُلِبَ مُوسَى - لَا سَمَحَ اللَّهُ بِذَلِكَ.',
          en: 'If Mūsā were defeated -- may Allah never allow that.',
          tokens: [
            { surface: 'وَإِذَا', lemma: 'إِذَا', pos: 'adv', features: 'conj+adv', gloss: 'and if' },
            { surface: 'غُلِبَ', lemma: 'غَلَبَ', pos: 'verb', features: 'pass+perf.3ms', gloss: 'were defeated' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'nom', gloss: 'Mūsā' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'may not' },
            { surface: 'سَمَحَ', lemma: 'سَمَحَ', pos: 'verb', features: 'perf.3ms', gloss: 'to allow; allow' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'بِذَلِكَ', lemma: 'بِ', pos: 'prep', features: 'prep+dem', gloss: 'that' },
          ],
        },
        {
          id: 'qs-v6-c24-006',
          ar: 'فَمَاذَا يَكُونُ؟ الْعِيَاذُ بِاللَّهِ!!',
          en: 'Then what would happen? We seek refuge in Allah!!',
          tokens: [
            { surface: 'فَمَاذَا', lemma: 'مَاذَا', pos: 'part', features: 'conj+part', gloss: 'so what' },
            { surface: 'يَكُونُ', lemma: 'كَانَ', pos: 'verb', features: 'impf.3ms', root: 'ك و ن', gloss: 'would happen' },
            { surface: 'الْعِيَاذُ', lemma: 'عِيَاذ', pos: 'noun', features: 'def.nom', gloss: 'refuge' },
            { surface: 'بِاللَّهِ', lemma: 'اللَّه', pos: 'proper', features: 'prep+gen', gloss: 'in Allah' },
          ],
        },
        {
          id: 'qs-v6-c24-007',
          ar: 'وَلَيْسَ غَلَبُ مُوسَى غَلَبَ رَجُلٍ، بَلْ هُوَ غَلَبُ دِينٍ أَمَامَ مَلِكٍ.',
          en: "Mūsā's defeat would not be one man's defeat -- it would be the defeat of a religion before a king.",
          tokens: [
            { surface: 'وَلَيْسَ', lemma: 'لَيْسَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'and is not' },
            { surface: 'غَلَبُ', lemma: 'غَلَبَ', pos: 'noun', features: 'nom.constr', gloss: 'the defeat of' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'gen', gloss: "Mūsā's" },
            { surface: 'غَلَبَ', lemma: 'غَلَبَ', pos: 'noun', features: 'acc.constr', gloss: 'the defeat of' },
            { surface: 'رَجُلٍ', lemma: 'رَجُل', pos: 'noun', features: 'indef.gen', gloss: 'a man' },
            { surface: 'بَلْ', lemma: 'بَلْ', pos: 'conj', features: 'conj', gloss: 'rather' },
            { surface: 'هُوَ', lemma: 'هُوَ', pos: 'noun', features: '3ms', gloss: 'it is' },
            { surface: 'غَلَبُ', lemma: 'غَلَبَ', pos: 'noun', features: 'nom.constr', gloss: 'the defeat of' },
            { surface: 'دِينٍ', lemma: 'دِين', pos: 'noun', features: 'indef.gen', gloss: 'a religion' },
            { surface: 'أَمَامَ', lemma: 'أَمَامَ', pos: 'prep', features: 'prep', gloss: 'before' },
            { surface: 'مَلِكٍ', lemma: 'مَلِك', pos: 'noun', features: 'indef.gen', gloss: 'a king' },
          ],
        },
        {
          id: 'qs-v6-c24-008',
          ar: 'بَلْ هُوَ غَلَبُ حَقٍّ أَمَامَ بَاطِلٍ.',
          en: 'Rather, it would be the defeat of truth before falsehood.',
          tokens: [
            { surface: 'بَلْ', lemma: 'بَلْ', pos: 'conj', features: 'conj', gloss: 'rather' },
            { surface: 'هُوَ', lemma: 'هُوَ', pos: 'noun', features: '3ms', gloss: 'it is' },
            { surface: 'غَلَبُ', lemma: 'غَلَبَ', pos: 'noun', features: 'nom.constr', gloss: 'the defeat of' },
            { surface: 'حَقٍّ', lemma: 'حَقّ', pos: 'noun', features: 'indef.gen', gloss: 'truth' },
            { surface: 'أَمَامَ', lemma: 'أَمَامَ', pos: 'prep', features: 'prep', gloss: 'before' },
            { surface: 'بَاطِلٍ', lemma: 'بَاطِل', pos: 'noun', features: 'indef.gen', root: 'ب ط ل', gloss: 'falsehood' },
          ],
        },
        {
          id: 'qs-v6-c24-009',
          ar: 'لَا قَدَّرَ اللَّهُ ذَلِكَ! لَا سَمَحَ اللَّهُ بِذَلِكَ!',
          en: 'May Allah never decree that! May Allah never allow that!',
          tokens: [
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'may not' },
            { surface: 'قَدَّرَ', lemma: 'قَدَّرَ', pos: 'verb', features: 'perf.3ms', gloss: 'decree' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'ذَلِكَ', lemma: 'ذَلِكَ', pos: 'dem', features: 'dem', gloss: 'that' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'may not' },
            { surface: 'سَمَحَ', lemma: 'سَمَحَ', pos: 'verb', features: 'perf.3ms', gloss: 'allow' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'بِذَلِكَ', lemma: 'بِ', pos: 'prep', features: 'prep+dem', gloss: 'that' },
          ],
        },
        {
          id: 'qs-v6-c24-010',
          ar: 'وَلَكِنَّ اللَّهَ شَجَّعَهُ وَقَالَ:',
          en: 'But Allah encouraged him and said:',
          tokens: [
            { surface: 'وَلَكِنَّ', lemma: 'لَكِنَّ', pos: 'part', features: 'conj+part', gloss: 'but' },
            { surface: 'اللَّهَ', lemma: 'اللَّه', pos: 'proper', features: 'acc', gloss: 'Allah' },
            { surface: 'شَجَّعَهُ', lemma: 'شَجَّعَ', pos: 'verb', features: 'perf.3ms+3ms', root: 'ش ج ع', gloss: 'to encourage; encouraged him' },
            { surface: 'وَقَالَ', lemma: 'قَالَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ق و ل', gloss: 'and said' },
          ],
        },
      ],
      checks: [
        {
          q: 'لِمَاذَا كَانَتْ هَزِيمَةُ مُوسَى أَخْطَرَ مِنْ هَزِيمَةِ أَيِّ رَجُلٍ عَادِيٍّ؟',
          options: ['لِأَنَّهَا لَنْ تَكُونَ غَلَبَ رَجُلٍ بَلْ غَلَبَ دِينٍ وَحَقٍّ أَمَامَ مَلِكٍ وَبَاطِلٍ', 'لِأَنَّ مُوسَى كَانَ غَنِيّاً وَلَهُ سُمْعَةٌ', 'لِأَنَّ الْمَلِكَةَ كَانَتْ سَتَغْضَبُ فَقَطْ'],
          answer: 0,
          qEn: "Why would Mūsā's defeat have been graver than any ordinary man's defeat?",
          optionsEn: ["Because it would not be one man's defeat, but the defeat of a religion and truth before a king and falsehood", 'Because Mūsā was rich and had a reputation', 'Because the queen alone would have been angry'],
        },
      ],
    },
    {
      en: '"Do not fear, indeed you are the uppermost. And throw what is in your right hand; it will swallow up what they have made -- what they have made is only a magician\'s trick, and the magician does not succeed wherever he comes." "Mūsā said: Whatever you have brought is magic; indeed Allah will nullify it. Indeed Allah does not set right the work of corrupters, and Allah establishes the truth by His words, even though the criminals despise it." "So Mūsā threw his staff, and behold, it swallowed up what they had falsely fabricated. So the truth was established, and what they had been doing came to nothing."',
      sentences: [
        {
          id: 'qs-v6-c24-011',
          ar: '﴿لَا تَخَفْ إِنَّكَ أَنتَ الْأَعْلَى﴾.',
          en: '"Do not fear, indeed you are the uppermost."',
          tokens: [
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'تَخَفْ', lemma: 'خَافَ', pos: 'verb', features: 'juss.2ms', gloss: 'fear' },
            { surface: 'إِنَّكَ', lemma: 'إِنَّ', pos: 'part', features: 'part+2ms', gloss: 'indeed you' },
            { surface: 'أَنتَ', lemma: 'أَنْتَ', pos: 'noun', features: '2ms', gloss: 'you' },
            { surface: 'الْأَعْلَى', lemma: 'أَعْلَى', pos: 'adj', features: 'def.nom', gloss: 'are the uppermost' },
          ],
        },
        {
          id: 'qs-v6-c24-012',
          ar: '﴿وَأَلْقِ مَا فِي يَمِينِكَ تَلْقَفْ مَا صَنَعُوا إِنَّمَا صَنَعُوا كَيْدُ سَاحِرٍ وَلَا يُفْلِحُ السَّاحِرُ حَيْثُ أَتَى﴾.',
          en: 'And throw what is in your right hand; it will swallow up what they have made -- what they have made is only a magician\'s trick, and the magician does not succeed wherever he comes.',
          tokens: [
            { surface: 'وَأَلْقِ', lemma: 'أَلْقَى', pos: 'verb', features: 'conj+imp.2ms', gloss: 'to throw; and throw' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'what' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'is in' },
            { surface: 'يَمِينِكَ', lemma: 'يَمِين', pos: 'noun', features: 'gen+2ms', gloss: 'your right hand' },
            { surface: 'تَلْقَفْ', lemma: 'تَلَقَّفَ', pos: 'verb', features: 'juss.3fs', root: 'ل ق ف', gloss: 'to swallow up; it will swallow up' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'what' },
            { surface: 'صَنَعُوا', lemma: 'صَنَعَ', pos: 'verb', features: 'perf.3mp', gloss: 'they have made' },
            { surface: 'إِنَّمَا', lemma: 'إِنَّمَا', pos: 'part', features: 'part', gloss: 'only' },
            { surface: 'صَنَعُوا', lemma: 'صَنَعَ', pos: 'verb', features: 'perf.3mp', gloss: 'what they have made is' },
            { surface: 'كَيْدُ', lemma: 'كَيْد', pos: 'noun', features: 'nom.constr', root: 'ك ي د', gloss: 'a trick of' },
            { surface: 'سَاحِرٍ', lemma: 'سَاحِر', pos: 'noun', features: 'indef.gen', gloss: 'a magician' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'يُفْلِحُ', lemma: 'أَفْلَحَ', pos: 'verb', features: 'impf.3ms', gloss: 'succeeds' },
            { surface: 'السَّاحِرُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom', gloss: 'the magician' },
            { surface: 'حَيْثُ', lemma: 'حَيْثُ', pos: 'adv', features: 'adv', gloss: 'wherever' },
            { surface: 'أَتَى', lemma: 'أَتَى', pos: 'verb', features: 'perf.3ms', gloss: 'he comes' },
          ],
        },
        {
          id: 'qs-v6-c24-013',
          ar: '﴿قَالَ مُوسَى مَا جِئْتُم بِهِ السِّحْرُ إِنَّ اللَّهَ سَيُبْطِلُهُ إِنَّ اللَّهَ لَا يُصْلِحُ عَمَلَ الْمُفْسِدِينَ وَيُحِقُّ اللَّهُ الْحَقَّ بِكَلِمَاتِهِ وَلَوْ كَرِهَ الْمُجْرِمُونَ﴾.',
          en: 'Mūsā said: Whatever you have brought is magic; indeed Allah will nullify it. Indeed Allah does not set right the work of corrupters, and Allah establishes the truth by His words, even though the criminals despise it.',
          tokens: [
            { surface: 'قَالَ', lemma: 'قَالَ', pos: 'verb', features: 'perf.3ms', root: 'ق و ل', gloss: 'said' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'nom', gloss: 'Mūsā' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'whatever' },
            { surface: 'جِئْتُم', lemma: 'جَاءَ', pos: 'verb', features: 'perf.2mp', gloss: 'you have brought' },
            { surface: 'بِهِ', lemma: 'بِ', pos: 'prep', features: 'prep+3ms', gloss: '[with it]' },
            { surface: 'السِّحْرُ', lemma: 'سِحْر', pos: 'noun', features: 'def.nom', gloss: 'is the magic' },
            { surface: 'إِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'اللَّهَ', lemma: 'اللَّه', pos: 'proper', features: 'acc', gloss: 'Allah' },
            { surface: 'سَيُبْطِلُهُ', lemma: 'أَبْطَلَ', pos: 'verb', features: 'fut+impf.3ms+3ms', root: 'ب ط ل', gloss: 'to nullify; will nullify it' },
            { surface: 'إِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'اللَّهَ', lemma: 'اللَّه', pos: 'proper', features: 'acc', gloss: 'Allah' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'يُصْلِحُ', lemma: 'أَصْلَحَ', pos: 'verb', features: 'impf.3ms', root: 'ص ل ح', gloss: 'to set right; sets right' },
            { surface: 'عَمَلَ', lemma: 'عَمَل', pos: 'noun', features: 'acc.constr', gloss: 'the work of' },
            { surface: 'الْمُفْسِدِينَ', lemma: 'مُفْسِد', pos: 'noun', features: 'def.gen.pl', gloss: 'the corrupters' },
            { surface: 'وَيُحِقُّ', lemma: 'أَحَقَّ', pos: 'verb', features: 'conj+impf.3ms', root: 'ح ق ق', gloss: 'to establish as true; and establishes' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'الْحَقَّ', lemma: 'حَقّ', pos: 'noun', features: 'def.acc', gloss: 'the truth' },
            { surface: 'بِكَلِمَاتِهِ', lemma: 'كَلِمَة', pos: 'noun', features: 'prep+pl.gen+3ms', root: 'ك ل م', gloss: 'by His words' },
            { surface: 'وَلَوْ', lemma: 'لَوْ', pos: 'conj', features: 'conj+conj', gloss: 'even though' },
            { surface: 'كَرِهَ', lemma: 'كَرِهَ', pos: 'verb', features: 'perf.3ms', gloss: 'despise' },
            { surface: 'الْمُجْرِمُونَ', lemma: 'مُجْرِم', pos: 'noun', features: 'def.nom.pl', gloss: 'the criminals' },
          ],
        },
        {
          id: 'qs-v6-c24-014',
          ar: '﴿فَأَلْقَى مُوسَى عَصَاهُ فَإِذَا هِيَ تَلْقَفُ مَا يَأْفِكُونَ﴾.',
          en: 'So Mūsā threw his staff, and behold, it swallowed up what they had falsely fabricated.',
          tokens: [
            { surface: 'فَأَلْقَى', lemma: 'أَلْقَى', pos: 'verb', features: 'conj+perf.3ms', gloss: 'to throw; so threw' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'nom', gloss: 'Mūsā' },
            { surface: 'عَصَاهُ', lemma: 'عَصًا', pos: 'noun', features: 'acc+3ms', gloss: 'his staff' },
            { surface: 'فَإِذَا', lemma: 'إِذَا', pos: 'adv', features: 'conj+adv', gloss: 'and behold' },
            { surface: 'هِيَ', lemma: 'هِيَ', pos: 'noun', features: '3fs', gloss: 'it' },
            { surface: 'تَلْقَفُ', lemma: 'تَلَقَّفَ', pos: 'verb', features: 'impf.3fs', root: 'ل ق ف', gloss: 'swallowed up' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'what' },
            { surface: 'يَأْفِكُونَ', lemma: 'أَفَكَ', pos: 'verb', features: 'impf.3mp', root: 'أ ف ك', gloss: 'to fabricate falsely; they had fabricated' },
          ],
        },
        {
          id: 'qs-v6-c24-015',
          ar: '﴿فَوَقَعَ الْحَقُّ وَبَطَلَ مَا كَانُوا يَعْمَلُونَ﴾.',
          en: 'So the truth was established, and what they had been doing came to nothing.',
          tokens: [
            { surface: 'فَوَقَعَ', lemma: 'وَقَعَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'to establish itself; so was established' },
            { surface: 'الْحَقُّ', lemma: 'حَقّ', pos: 'noun', features: 'def.nom', gloss: 'the truth' },
            { surface: 'وَبَطَلَ', lemma: 'بَطَلَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ب ط ل', gloss: 'to come to nothing; and came to nothing' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'what' },
            { surface: 'كَانُوا', lemma: 'كَانَ', pos: 'verb', features: 'perf.3mp', root: 'ك و ن', gloss: 'they had been' },
            { surface: 'يَعْمَلُونَ', lemma: 'عَمِلَ', pos: 'verb', features: 'impf.3mp', gloss: 'doing' },
          ],
        },
      ],
      checks: [
        {
          q: 'مَاذَا حَدَثَ عِنْدَمَا أَلْقَى مُوسَى عَصَاهُ؟',
          options: ['اِبْتَلَعَتِ الْعَصَا مَا صَنَعَهُ السَّحَرَةُ وَبَطَلَ سِحْرُهُمْ', 'لَمْ يَحْدُثْ شَيْءٌ مُخْتَلِفٌ عَنْ سِحْرِ السَّحَرَةِ', 'اِنْكَسَرَتِ الْعَصَا فَوْرَاً'],
          answer: 0,
          qEn: 'What happened when Mūsā threw his staff?',
          optionsEn: ["The staff swallowed up what the sorcerers had made, and their magic came to nothing", 'Nothing different from the sorcerers\' own magic happened', 'The staff broke instantly'],
        },
      ],
    },
    {
      en: 'The sorcerers were astonished and dumbfounded. "What is this?! We know magic and its origin, and we know magic and its kinds. We are the masters of this art! We are its leading authorities! This is not magic! This is not magic! If it were magic, we would have struck magic with magic and matched art with art! But our art dwindled away before this, and melted the way dew melts before the sun." "So where is this from? This is from Allah!" The sorcerers became convinced that Mūsā was a prophet and that Allah had granted him a miracle, so they cried out and shouted: "We believe in the Lord of Hārūn and Mūsā." "And the sorcerers were cast down, prostrating. They said: We believe in the Lord of the worlds, the Lord of Mūsā and Hārūn."',
      sentences: [
        {
          id: 'qs-v6-c24-016',
          ar: 'وَدُهِشَ السَّحَرَةُ وَبُهِتُوا.',
          en: 'The sorcerers were astonished and dumbfounded.',
          tokens: [
            { surface: 'وَدُهِشَ', lemma: 'دُهِشَ', pos: 'verb', features: 'conj+pass+perf.3ms', root: 'د ه ش', gloss: 'to be astonished; and were astonished' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'وَبُهِتُوا', lemma: 'بُهِتَ', pos: 'verb', features: 'conj+pass+perf.3mp', root: 'ب ه ت', gloss: 'to be dumbfounded; and were dumbfounded' },
          ],
        },
        {
          id: 'qs-v6-c24-017',
          ar: 'أَيُّ شَيْءٍ هَذَا؟! إِنَّا نَعْرِفُ السِّحْرَ وَأَصْلَهُ وَإِنَّا نَعْرِفُ السِّحْرَ وَأَنْوَاعَهُ.',
          en: 'What is this?! We know magic and its origin, and we know magic and its kinds.',
          tokens: [
            { surface: 'أَيُّ', lemma: 'أَيّ', pos: 'noun', features: 'constr', gloss: 'what' },
            { surface: 'شَيْءٍ', lemma: 'شَيْء', pos: 'noun', features: 'indef.gen', gloss: 'thing' },
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'is this' },
            { surface: 'إِنَّا', lemma: 'إِنَّ', pos: 'part', features: 'part+1p', gloss: 'indeed we' },
            { surface: 'نَعْرِفُ', lemma: 'عَرَفَ', pos: 'verb', features: 'impf.1p', gloss: 'know' },
            { surface: 'السِّحْرَ', lemma: 'سِحْر', pos: 'noun', features: 'def.acc', gloss: 'magic' },
            { surface: 'وَأَصْلَهُ', lemma: 'أَصْل', pos: 'noun', features: 'conj+acc+3ms', gloss: 'and its origin' },
            { surface: 'وَإِنَّا', lemma: 'إِنَّ', pos: 'part', features: 'conj+part+1p', gloss: 'and indeed we' },
            { surface: 'نَعْرِفُ', lemma: 'عَرَفَ', pos: 'verb', features: 'impf.1p', gloss: 'know' },
            { surface: 'السِّحْرَ', lemma: 'سِحْر', pos: 'noun', features: 'def.acc', gloss: 'magic' },
            { surface: 'وَأَنْوَاعَهُ', lemma: 'نَوْع', pos: 'noun', features: 'conj+pl.acc+3ms', gloss: 'and its kinds' },
          ],
        },
        {
          id: 'qs-v6-c24-018',
          ar: 'وَنَحْنُ أَسَاتِذَةُ الْفَنِّ! وَنَحْنُ أَئِمَّةُ الْفَنِّ!',
          en: 'We are the masters of this art! We are its leading authorities!',
          tokens: [
            { surface: 'وَنَحْنُ', lemma: 'نَحْنُ', pos: 'noun', features: 'conj+1p', gloss: 'and we are' },
            { surface: 'أَسَاتِذَةُ', lemma: 'أُسْتَاذ', pos: 'noun', features: 'nom.constr.pl', root: 'أ س ت ذ', gloss: 'the masters of' },
            { surface: 'الْفَنِّ', lemma: 'فَنّ', pos: 'noun', features: 'def.gen', gloss: 'this art' },
            { surface: 'وَنَحْنُ', lemma: 'نَحْنُ', pos: 'noun', features: 'conj+1p', gloss: 'and we are' },
            { surface: 'أَئِمَّةُ', lemma: 'إِمَام', pos: 'noun', features: 'nom.constr.pl', root: 'أ م م', gloss: 'the leading authorities of' },
            { surface: 'الْفَنِّ', lemma: 'فَنّ', pos: 'noun', features: 'def.gen', gloss: 'this art' },
          ],
        },
        {
          id: 'qs-v6-c24-019',
          ar: 'هَذَا لَيْسَ مِنَ السِّحْرِ! هَذَا لَيْسَ مِنَ السِّحْرِ!',
          en: 'This is not magic! This is not magic!',
          tokens: [
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'this' },
            { surface: 'لَيْسَ', lemma: 'لَيْسَ', pos: 'verb', features: 'perf.3ms', gloss: 'is not' },
            { surface: 'مِنَ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'of' },
            { surface: 'السِّحْرِ', lemma: 'سِحْر', pos: 'noun', features: 'def.gen', gloss: 'magic' },
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'this' },
            { surface: 'لَيْسَ', lemma: 'لَيْسَ', pos: 'verb', features: 'perf.3ms', gloss: 'is not' },
            { surface: 'مِنَ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'of' },
            { surface: 'السِّحْرِ', lemma: 'سِحْر', pos: 'noun', features: 'def.gen', gloss: 'magic' },
          ],
        },
        {
          id: 'qs-v6-c24-020',
          ar: 'لَوْ كَانَ مِنَ السِّحْرِ لَضَرَبْنَا السِّحْرَ بِالسِّحْرِ وَقَرَعْنَا الْفَنَّ بِالْفَنِّ!',
          en: 'If it were magic, we would have struck magic with magic and matched art with art!',
          tokens: [
            { surface: 'لَوْ', lemma: 'لَوْ', pos: 'conj', features: 'conj', gloss: 'if' },
            { surface: 'كَانَ', lemma: 'كَانَ', pos: 'verb', features: 'perf.3ms', root: 'ك و ن', gloss: 'it were' },
            { surface: 'مِنَ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'of' },
            { surface: 'السِّحْرِ', lemma: 'سِحْر', pos: 'noun', features: 'def.gen', gloss: 'magic' },
            { surface: 'لَضَرَبْنَا', lemma: 'ضَرَبَ', pos: 'verb', features: 'part+perf.1p', gloss: 'we would have struck' },
            { surface: 'السِّحْرَ', lemma: 'سِحْر', pos: 'noun', features: 'def.acc', gloss: 'magic' },
            { surface: 'بِالسِّحْرِ', lemma: 'سِحْر', pos: 'noun', features: 'prep+def.gen', gloss: 'with magic' },
            { surface: 'وَقَرَعْنَا', lemma: 'قَرَعَ', pos: 'verb', features: 'conj+perf.1p', root: 'ق ر ع', gloss: 'to match; and matched' },
            { surface: 'الْفَنَّ', lemma: 'فَنّ', pos: 'noun', features: 'def.acc', gloss: 'art' },
            { surface: 'بِالْفَنِّ', lemma: 'فَنّ', pos: 'noun', features: 'prep+def.gen', gloss: 'with art' },
          ],
        },
        {
          id: 'qs-v6-c24-021',
          ar: 'وَلَكِنِ اضْمَحَلَّ فَنُّنَا أَمَامَ هَذَا، وَذَابَ كَمَا يَذُوبُ النَّدَى أَمَامَ الشَّمْسِ.',
          en: 'But our art dwindled away before this, and melted the way dew melts before the sun.',
          tokens: [
            { surface: 'وَلَكِنِ', lemma: 'لَكِنْ', pos: 'conj', features: 'conj+conj', gloss: 'but' },
            { surface: 'اضْمَحَلَّ', lemma: 'اِضْمَحَلَّ', pos: 'verb', features: 'perf.3ms', root: 'ض م ح ل', gloss: 'to dwindle away; dwindled away' },
            { surface: 'فَنُّنَا', lemma: 'فَنّ', pos: 'noun', features: 'nom+1p', gloss: 'our art' },
            { surface: 'أَمَامَ', lemma: 'أَمَامَ', pos: 'prep', features: 'prep', gloss: 'before' },
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'this' },
            { surface: 'وَذَابَ', lemma: 'ذَابَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ذ و ب', gloss: 'to melt; and melted' },
            { surface: 'كَمَا', lemma: 'كَمَا', pos: 'adv', features: 'adv', gloss: 'the way' },
            { surface: 'يَذُوبُ', lemma: 'ذَابَ', pos: 'verb', features: 'impf.3ms', root: 'ذ و ب', gloss: 'melts' },
            { surface: 'النَّدَى', lemma: 'نَدَى', pos: 'noun', features: 'def.nom', root: 'ن د و', gloss: 'the dew' },
            { surface: 'أَمَامَ', lemma: 'أَمَامَ', pos: 'prep', features: 'prep', gloss: 'before' },
            { surface: 'الشَّمْسِ', lemma: 'شَمْس', pos: 'noun', features: 'def.gen', gloss: 'the sun' },
          ],
        },
        {
          id: 'qs-v6-c24-022',
          ar: 'فَمِنْ أَيْنَ هَذَا؟ هَذَا مِنَ اللَّهِ!',
          en: 'So where is this from? This is from Allah!',
          tokens: [
            { surface: 'فَمِنْ', lemma: 'مِنْ', pos: 'prep', features: 'conj+prep', gloss: 'so from' },
            { surface: 'أَيْنَ', lemma: 'أَيْنَ', pos: 'adv', features: 'adv', gloss: 'where' },
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'is this' },
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'this' },
            { surface: 'مِنَ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'is from' },
            { surface: 'اللَّهِ', lemma: 'اللَّه', pos: 'proper', features: 'gen', gloss: 'Allah' },
          ],
        },
        {
          id: 'qs-v6-c24-023',
          ar: 'اقْتَنَعَ السَّحَرَةُ بِأَنَّ مُوسَى نَبِيٌّ وَأَنَّ اللَّهَ قَدْ مَنَحَهُ مُعْجِزَةً فَصَرَخُوا وَهَتَفُوا:',
          en: 'The sorcerers became convinced that Mūsā was a prophet and that Allah had granted him a miracle, so they cried out and shouted:',
          tokens: [
            { surface: 'اقْتَنَعَ', lemma: 'اِقْتَنَعَ', pos: 'verb', features: 'perf.3ms', root: 'ق ن ع', gloss: 'to be convinced; became convinced' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'بِأَنَّ', lemma: 'أَنَّ', pos: 'part', features: 'prep+part', gloss: 'that' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'acc', gloss: 'Mūsā' },
            { surface: 'نَبِيٌّ', lemma: 'نَبِيّ', pos: 'noun', features: 'indef.nom', gloss: 'was a prophet' },
            { surface: 'وَأَنَّ', lemma: 'أَنَّ', pos: 'part', features: 'conj+part', gloss: 'and that' },
            { surface: 'اللَّهَ', lemma: 'اللَّه', pos: 'proper', features: 'acc', gloss: 'Allah' },
            { surface: 'قَدْ', lemma: 'قَدْ', pos: 'part', features: 'part', gloss: 'had' },
            { surface: 'مَنَحَهُ', lemma: 'مَنَحَ', pos: 'verb', features: 'perf.3ms+3ms', gloss: 'to grant; granted him' },
            { surface: 'مُعْجِزَةً', lemma: 'مُعْجِزَة', pos: 'noun', features: 'indef.acc', root: 'ع ج ز', gloss: 'a miracle' },
            { surface: 'فَصَرَخُوا', lemma: 'صَرَخَ', pos: 'verb', features: 'conj+perf.3mp', gloss: 'to cry out; so cried out' },
            { surface: 'وَهَتَفُوا', lemma: 'هَتَفَ', pos: 'verb', features: 'conj+perf.3mp', root: 'ه ت ف', gloss: 'to shout; and shouted' },
          ],
        },
        {
          id: 'qs-v6-c24-024',
          ar: '﴿آمَنَّا بِرَبِّ هَارُونَ وَمُوسَى﴾.',
          en: '"We believe in the Lord of Hārūn and Mūsā."',
          tokens: [
            { surface: 'آمَنَّا', lemma: 'آمَنَ', pos: 'verb', features: 'perf.1p', gloss: 'we believe' },
            { surface: 'بِرَبِّ', lemma: 'رَبّ', pos: 'noun', features: 'prep+constr.gen', gloss: 'in the Lord of' },
            { surface: 'هَارُونَ', lemma: 'هَارُون', pos: 'proper', features: 'gen', gloss: 'Hārūn' },
            { surface: 'وَمُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'conj+gen', gloss: 'and Mūsā' },
          ],
        },
        {
          id: 'qs-v6-c24-025',
          ar: '﴿وَأُلْقِيَ السَّحَرَةُ سَاجِدِينَ قَالُوا آمَنَّا بِرَبِّ الْعَالَمِينَ رَبِّ مُوسَى وَهَارُونَ﴾.',
          en: 'And the sorcerers were cast down, prostrating. They said: We believe in the Lord of the worlds, the Lord of Mūsā and Hārūn.',
          tokens: [
            { surface: 'وَأُلْقِيَ', lemma: 'أَلْقَى', pos: 'verb', features: 'conj+pass+perf.3ms', gloss: 'to cast down; and were cast down' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'سَاجِدِينَ', lemma: 'سَجَدَ', pos: 'noun', features: 'acc.pl', gloss: 'prostrating' },
            { surface: 'قَالُوا', lemma: 'قَالَ', pos: 'verb', features: 'perf.3mp', root: 'ق و ل', gloss: 'they said' },
            { surface: 'آمَنَّا', lemma: 'آمَنَ', pos: 'verb', features: 'perf.1p', gloss: 'we believe' },
            { surface: 'بِرَبِّ', lemma: 'رَبّ', pos: 'noun', features: 'prep+constr.gen', gloss: 'in the Lord of' },
            { surface: 'الْعَالَمِينَ', lemma: 'عَالَم', pos: 'noun', features: 'def.gen.pl', gloss: 'the worlds' },
            { surface: 'رَبِّ', lemma: 'رَبّ', pos: 'noun', features: 'constr.gen', gloss: 'the Lord of' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'gen', gloss: 'Mūsā' },
            { surface: 'وَهَارُونَ', lemma: 'هَارُون', pos: 'proper', features: 'conj+gen', gloss: 'and Hārūn' },
          ],
        },
      ],
      checks: [
        {
          q: 'لِمَاذَا اقْتَنَعَ السَّحَرَةُ أَنْفُسُهُمْ بِأَنَّ مَا فَعَلَهُ مُوسَى لَيْسَ سِحْراً؟',
          options: ['لِأَنَّهُمْ أَسَاتِذَةُ الْفَنِّ وَيَعْرِفُونَ السِّحْرَ حَقَّ الْمَعْرِفَةِ وَلَوْ كَانَ سِحْراً لَقَاوَمُوهُ بِفَنِّهِمْ', 'لِأَنَّ فِرْعَوْنَ أَمَرَهُمْ بِذَلِكَ', 'لِأَنَّهُمْ خَافُوا مِنْ مُوسَى فَقَطْ'],
          answer: 0,
          qEn: "Why did the sorcerers themselves become convinced that what Mūsā did was not magic?",
          optionsEn: ['Because they were masters of the art and knew magic thoroughly, and had it been magic they could have matched it with their own art', 'Because Pharaoh ordered them to believe that', 'Because they were simply afraid of Mūsā'],
        },
      ],
    },
  ],
  workshop: {
    cloze: [
      {
        type: 'cloze',
        pre: 'إِنَّ اللَّهَ لَا يُصْلِحُ عَمَلَ',
        post: '.',
        en: 'Indeed Allah does not set right the work of corrupters.',
        options: ['الْمُفْسِدِينَ', 'الْمُفْسِدُونَ', 'مُفْسِدِينَ', 'الْمُفْسِدِ'],
        answer: 0,
        rationales: [
          'Genitive, definite plural -- second term of the إضافة with عَمَلَ, matching the taught pattern.',
          'Nominative -- wrong case; a genitive is required after a construct noun.',
          'Indefinite -- wrong; "the corrupters" as a known class needs the definite article.',
          'Singular -- wrong number; the reference is to corrupters in general (plural).',
        ],
      },
      {
        type: 'cloze',
        pre: 'اقْتَنَعَ السَّحَرَةُ بِأَنَّ مُوسَى',
        post: 'وَأَنَّ اللَّهَ قَدْ مَنَحَهُ مُعْجِزَةً.',
        en: 'The sorcerers became convinced that Mūsā was a prophet and that Allah had granted him a miracle.',
        options: ['نَبِيٌّ', 'نَبِيّاً', 'النَّبِيَّ', 'نَبِيٍّ'],
        answer: 0,
        rationales: [
          'Nominative, indefinite -- predicate of أَنَّ\'s implied nominal sentence (اسم أَنَّ منصوب لكن خبرها هنا مرفوع), matching the taught pattern.',
          'Accusative -- wrong case for the predicate position here.',
          'Definite -- wrong; "a prophet" (unspecified predicate) is meant, not a particular known one.',
          'Genitive -- wrong case; nothing here governs the genitive.',
        ],
      },
    ],
    shift: [
      {
        type: 'shift',
        base: 'يُؤْمِنُ الرَّجُلُ بِرَبِّ الْعَالَمِينَ',
        pre: '',
        post: 'بِرَبِّ الْعَالَمِينَ',
        targetPerson: 'نَحْنُ',
        targetEn: 'we',
        options: ['نُؤْمِنُ', 'يُؤْمِنُ', 'تُؤْمِنُ', 'أُؤْمِنُ'],
        answer: 0,
        rationales: [
          '1st plural -- matches نَحْنُ, and the same form the sorcerers themselves use (آمَنَّا, perfect of the same paradigm).',
          '3rd masculine singular -- he, the form already given.',
          '2nd masculine singular / 3rd feminine singular -- wrong person.',
          '1st singular -- I.',
        ],
      },
      {
        type: 'shift',
        base: 'يُؤْمِنُ الرَّجُلُ بِرَبِّ الْعَالَمِينَ',
        pre: '',
        post: 'بِرَبِّ الْعَالَمِينَ',
        targetPerson: 'هُمْ',
        targetEn: 'they (m.)',
        options: ['يُؤْمِنُونَ', 'يُؤْمِنُ', 'تُؤْمِنُ', 'نُؤْمِنُ'],
        answer: 0,
        rationales: [
          '3rd masculine plural -- matches هُمْ, the sorcerers themselves.',
          '3rd masculine singular -- he, the form already given.',
          '3rd feminine singular -- she.',
          '1st plural -- we.',
        ],
      },
    ],
  },
};
