// قَصَصُ النَّبِيِّينَ, volume 6 (Mūsā, part 1), chapter 25 -- وَعِيدُ
// فِرْعَوْنَ. Printed pages 155 (heading, partway down, right after ch24's
// closing Qur'an citation 20:73) - 156 - 157 (top only), ending right
// before a PREVIOUSLY UNMAPPED chapter 26 «سَفَاهَةُ فِرْعَوْنَ» whose title
// box opens partway down page 157. Transcribed by hand from the scan
// (vision OCR, 200dpi render) against ../CHAPTER-FORMAT.md.
//
// *** CORRECTION TO QASAS_VOLUME_MAP.md ***: the map lists this as the
// LAST chapter of volume 6 ("closes p.159"). That is wrong -- ch25 itself
// ends on p.157, and a further, unmapped chapter 26 «سَفَاهَةُ فِرْعَوْنَ»
// runs p.157-159 and is what actually closes the volume with the
// triple-rosette divider. Verified directly against the scan (title box
// "٢٦ - سَفَاهَةُ فِرْعَوْنَ" clearly visible partway down p.157). Volume 6
// therefore has 26 chapters, not 25. See chapter-26.js (transcribed
// alongside this file) and flag this to Habib / whoever maintains
// QASAS_VOLUME_MAP.md.
//
// Covers Sūrat ash-Shuʿarāʾ 26:41-51 and Sūrat Ṭāhā 20:71-75: Pharaoh's
// two accusatory "arrows" against the newly-believing sorcerers, his
// mutilation threat, and their defiant reply quoted at length.
//
// Grammar / lexical notes:
//   -- The extended closing Qur'an citation (20:73-75) is split at its
//      coordinated clause boundaries into four fragments
//      (qs-v6-c25-018a..d in spirit, ids qs-v6-c25-018 through -021) per
//      the qasas-v2/ch22 precedent for long āyahs.
//   -- سِهَام / سَهْم ("arrows") throughout is Nadwi's own extended
//      metaphor for Pharaoh's three successive rhetorical attacks --
//      not a literal battle.
//   -- Shared lexicon check (cross-checked against known_lemmas.json):
//      جَنَّ (qasas-v6/ch5), جُنُون, فِرْعَوْن, قَامَ, قَعَدَ, مِسْكِين, وَقَعَ,
//      مَا, لَمْ, كَانَ, إِنَّ, أَرَادَ, أَنْ, مُوسَى, بِ, أَصْبَحَ, جُنْد, صَدَّ,
//      نَاسَ, عَنْ, جَاءَ, فَإِذَا, أَوَّل, مُؤْمِن, اِرْتَدَّ, عَلَى, يَعْتَقِدُ/اِعْتَقَدَ,
//      مَلِك, عَقْل, كَمَا, أَنَّ, لِ, قَلْب, لِسَان, لَيْسَ, لِأَحَدٍ, فِي, مِصْرَ,
//      شَيْء, أَوْ, يُؤْمِنَ/آمَنَ, إِلَّا, إِذْن, قَالَ, كِبْر, آذَنَ, رَمَى,
//      كَبِير, عَلَّمَ, سِحْر, ثَانٍ, مَدِينَة, أَهْل, سَوْفَ, عَلِمَ, أَيْدِي/يَد,
//      أَرْجُل/رِجْل, ثُمَّ, رَبّ, غَفَرَ, خَيْر, أَبْقَى, مَاتَ, حَيِيَ,
//      عَمِلَ, أُولَئِكَ, جَنَّة, تَحْتَ, أَنْهَار/نَهْر, خَالِد, ذَلِكَ
//      are all already taught (or reused) and are NOT re-listed in
//      newWords here.
//
// ~33 new words -- an unusually dense chapter, reproducing several
// consecutive Qur'an āyaht nearly verbatim. No page footnotes (book_note)
// on these pages.
export const CHAPTER = {
  id: 'ch25',
  title: { ar: 'وَعِيدُ فِرْعَوْنَ', en: "Pharaoh's Threat" },
  newWords: ['بَرَقَ', 'رَعَدَ', 'رَجَا', 'هَزَمَ', 'جِسْم', 'سُلْطَان', 'جَبَرُوت', 'مَكْر', 'أَخِير', 'مَسْمُوم', 'كِنَانَة', 'قَطَّعَ', 'خِلَاف', 'صَلَّبَ', 'أَجْمَعِينَ', 'تَلَقَّى', 'جُنَّة', 'إِيمَان', 'ضَيْر', 'مُنْقَلِب', 'طَمِعَ', 'خَطِيئَة', 'حَمَاسَة', 'أَكْرَهَ', 'جَهَنَّم', 'صَالِح', 'دَرَجَة', 'عَدْن', 'زَكَّى'],
  lemmas: {
    جِسْم: { gloss: 'body' },
    أَخِير: { gloss: 'last, final' },
    بَرَقَ: { gloss: 'to flash, flare up (with anger)' },
    رَعَدَ: { gloss: 'to thunder, rage' },
    رَجَا: { gloss: 'to hope for' },
    هَزَمَ: { gloss: 'to defeat' },
    سُلْطَان: { gloss: 'authority, power' },
    جَبَرُوت: { gloss: 'tyranny, overweening pride' },
    مَكْر: { gloss: 'a plot, scheme' },
    مَسْمُوم: { gloss: 'poisoned' },
    كِنَانَة: { gloss: 'quiver (for arrows)' },
    قَطَّعَ: { gloss: 'to cut off (repeatedly, e.g. limbs)' },
    خِلَاف: { gloss: 'opposite side (مِنْ خِلَافٍ: from opposite sides)' },
    صَلَّبَ: { gloss: 'to crucify' },
    تَلَقَّى: { gloss: 'to receive, meet' },
    جُنَّة: { gloss: 'shield, protection' },
    إِيمَان: { gloss: 'faith, belief' },
    ضَيْر: { gloss: 'harm' },
    مُنْقَلِب: { gloss: 'one who returns' },
    طَمِعَ: { gloss: 'to hope eagerly, be eager' },
    خَطِيئَة: { gloss: 'sin, fault (pl. خَطَايَا)' },
    حَمَاسَة: { gloss: 'zeal, fervor' },
    أَكْرَهَ: { gloss: 'to force, compel' },
    أَجْمَعِينَ: { gloss: 'all together' },
    جَهَنَّم: { gloss: 'Hell' },
    صَالِح: { gloss: 'righteous, good' },
    دَرَجَة: { gloss: 'rank, degree' },
    عَدْن: { gloss: "Eden (جَنَّاتُ عَدْنٍ: gardens of Eden)" },
    زَكَّى: { gloss: 'to purify oneself' },
  },
  paragraphs: [
    {
      en: "Pharaoh's fury flared! He stood and sat, flashed and thundered. Poor Pharaoh -- what befell him was what he never expected: he had wanted to defeat Mūsā with the sorcerers, but the sorcerers became Mūsā's own army. He had wanted to turn people away from Mūsā by bringing the sorcerers, and instead they became the very first believers! His own arrows had turned back against him.",
      sentences: [
        {
          id: 'qs-v6-c25-001',
          ar: 'وَجُنَّ جُنُونُ فِرْعَوْنَ!',
          en: "Pharaoh's fury flared!",
          tokens: [
            { surface: 'وَجُنَّ', lemma: 'جَنَّ', pos: 'verb', features: 'conj+pass+perf.3ms', gloss: 'to be driven mad; flared' },
            { surface: 'جُنُونُ', lemma: 'جُنُون', pos: 'noun', features: 'nom', gloss: 'the fury of' },
            { surface: 'فِرْعَوْنَ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'gen', gloss: "Pharaoh's" },
          ],
        },
        {
          id: 'qs-v6-c25-002',
          ar: 'وَقَامَ فِرْعَوْنُ وَقَعَدَ وَبَرَقَ فِرْعَوْنُ وَرَعَدَ.',
          en: 'He stood and sat, flashed and thundered.',
          tokens: [
            { surface: 'وَقَامَ', lemma: 'قَامَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'to stand; and stood' },
            { surface: 'فِرْعَوْنُ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'nom', gloss: 'Pharaoh' },
            { surface: 'وَقَعَدَ', lemma: 'قَعَدَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'to sit; and sat' },
            { surface: 'وَبَرَقَ', lemma: 'بَرَقَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ب ر ق', gloss: 'to flash; and flashed' },
            { surface: 'فِرْعَوْنُ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'nom', gloss: 'Pharaoh' },
            { surface: 'وَرَعَدَ', lemma: 'رَعَدَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ر ع د', gloss: 'to thunder; and thundered' },
          ],
        },
        {
          id: 'qs-v6-c25-003',
          ar: 'مِسْكِينٌ فِرْعَوْنُ وَقَعَ مَا لَمْ يَكُنْ يَرْجُوهُ!',
          en: 'Poor Pharaoh -- what befell him was what he never expected!',
          tokens: [
            { surface: 'مِسْكِينٌ', lemma: 'مِسْكِين', pos: 'noun', features: 'indef.nom', gloss: 'poor' },
            { surface: 'فِرْعَوْنُ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'nom', gloss: 'Pharaoh' },
            { surface: 'وَقَعَ', lemma: 'وَقَعَ', pos: 'verb', features: 'perf.3ms', gloss: 'to befall; befell [him]' },
            { surface: 'مَا', lemma: 'مَا', pos: 'rel', features: 'rel', gloss: 'what' },
            { surface: 'لَمْ', lemma: 'لَمْ', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'يَكُنْ', lemma: 'كَانَ', pos: 'verb', features: 'juss.3ms', root: 'ك و ن', gloss: 'to be; was' },
            { surface: 'يَرْجُوهُ', lemma: 'رَجَا', pos: 'verb', features: 'impf.3ms+3ms', root: 'ر ج و', gloss: 'to hope for; hoping for it' },
          ],
        },
        {
          id: 'qs-v6-c25-004',
          ar: 'إِنَّهُ أَرَادَ أَنْ يَهْزِمَ مُوسَى بِالسَّحَرَةِ فَأَصْبَحَتِ السَّحَرَةُ جُنْدَ مُوسَى.',
          en: "He had wanted to defeat Mūsā with the sorcerers, but the sorcerers became Mūsā's own army.",
          tokens: [
            { surface: 'إِنَّهُ', lemma: 'إِنَّ', pos: 'part', features: 'part+3ms', gloss: 'indeed he' },
            { surface: 'أَرَادَ', lemma: 'أَرَادَ', pos: 'verb', features: 'perf.3ms', gloss: 'to want; wanted' },
            { surface: 'أَنْ', lemma: 'أَنْ', pos: 'part', features: 'part', gloss: 'to' },
            { surface: 'يَهْزِمَ', lemma: 'هَزَمَ', pos: 'verb', features: 'subj.3ms', root: 'ه ز م', gloss: 'to defeat' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'acc', gloss: 'Mūsā' },
            { surface: 'بِالسَّحَرَةِ', lemma: 'سَاحِر', pos: 'noun', features: 'prep+def.gen.pl', gloss: 'with the sorcerers' },
            { surface: 'فَأَصْبَحَتِ', lemma: 'أَصْبَحَ', pos: 'verb', features: 'conj+perf.3fs', gloss: 'to become; but became' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'جُنْدَ', lemma: 'جُنْد', pos: 'noun', features: 'acc.constr', gloss: "the army of" },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'gen', gloss: "Mūsā's" },
          ],
        },
        {
          id: 'qs-v6-c25-005',
          ar: 'إِنَّهُ أَرَادَ أَنْ يَصُدَّ النَّاسَ عَنْ مُوسَى فَجَاءَ بِالسَّحَرَةِ فَإِذَا بِهِمْ أَوَّلُ الْمُؤْمِنِينَ!',
          en: 'He had wanted to turn people away from Mūsā by bringing the sorcerers, and instead they became the very first believers!',
          tokens: [
            { surface: 'إِنَّهُ', lemma: 'إِنَّ', pos: 'part', features: 'part+3ms', gloss: 'indeed he' },
            { surface: 'أَرَادَ', lemma: 'أَرَادَ', pos: 'verb', features: 'perf.3ms', gloss: 'wanted' },
            { surface: 'أَنْ', lemma: 'أَنْ', pos: 'part', features: 'part', gloss: 'to' },
            { surface: 'يَصُدَّ', lemma: 'صَدَّ', pos: 'verb', features: 'subj.3ms', root: 'ص د د', gloss: 'to turn away; turn away' },
            { surface: 'النَّاسَ', lemma: 'نَاس', pos: 'noun', features: 'def.acc', gloss: 'the people' },
            { surface: 'عَنْ', lemma: 'عَنْ', pos: 'prep', features: 'prep', gloss: 'from' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'gen', gloss: 'Mūsā' },
            { surface: 'فَجَاءَ', lemma: 'جَاءَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'to bring; by bringing' },
            { surface: 'بِالسَّحَرَةِ', lemma: 'سَاحِر', pos: 'noun', features: 'prep+def.gen.pl', gloss: 'the sorcerers' },
            { surface: 'فَإِذَا', lemma: 'إِذَا', pos: 'adv', features: 'conj+adv', gloss: 'and instead' },
            { surface: 'بِهِمْ', lemma: 'بِ', pos: 'prep', features: 'prep+3mp', gloss: 'they were' },
            { surface: 'أَوَّلُ', lemma: 'أَوَّل', pos: 'noun', features: 'nom.constr', gloss: 'the first of' },
            { surface: 'الْمُؤْمِنِينَ', lemma: 'مُؤْمِن', pos: 'noun', features: 'def.gen.pl', gloss: 'the believers' },
          ],
        },
        {
          id: 'qs-v6-c25-006',
          ar: 'إِنَّ سِهَامَهُ اِرْتَدَّتْ عَلَيْهِ.',
          en: 'His own arrows had turned back against him.',
          tokens: [
            { surface: 'إِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'سِهَامَهُ', lemma: 'سَهْم', pos: 'noun', features: 'acc.pl+3ms', gloss: 'his arrows' },
            { surface: 'اِرْتَدَّتْ', lemma: 'اِرْتَدَّ', pos: 'verb', features: 'perf.3fs', gloss: 'to turn back; turned back' },
            { surface: 'عَلَيْهِ', lemma: 'عَلَى', pos: 'prep', features: 'prep+3ms', gloss: 'against him' },
          ],
        },
      ],
      checks: [
        {
          q: 'مَاذَا حَدَثَ عِنْدَمَا أَرَادَ فِرْعَوْنُ أَنْ يَهْزِمَ مُوسَى بِالسَّحَرَةِ؟',
          options: ['أَصْبَحَتِ السَّحَرَةُ جُنْدَ مُوسَى وَأَوَّلَ الْمُؤْمِنِينَ', 'هَزَمَتِ السَّحَرَةُ مُوسَى بِالفِعْلِ', 'رَفَضَ السَّحَرَةُ الذَّهَابَ إِلَى الْمَيْدَانِ'],
          answer: 0,
          qEn: "What happened when Pharaoh tried to defeat Mūsā with the sorcerers?",
          optionsEn: ["The sorcerers became Mūsā's army and the first believers", 'The sorcerers actually defeated Mūsā', 'The sorcerers refused to go to the arena'],
        },
      ],
    },
    {
      en: 'Pharaoh believed he was ruler of minds just as he was ruler of bodies, and that he had authority over hearts just as he had authority over tongues, and that no one in Egypt could believe or trust in anything except by his permission -- so he said, in pride and tyranny, "Did you believe in him before I gave you permission?!" Pharaoh shot them with an arrow from the arrows of kings and said, "He is indeed your chief who taught you magic!" He shot them with a second arrow and said, "This is indeed a plot you schemed in the city to drive its people out of it -- you will soon know!!" He shot them with a third, poisoned arrow -- the last arrow in the quiver of kings: "I will surely cut off your hands and feet on opposite sides, then crucify you all."',
      sentences: [
        {
          id: 'qs-v6-c25-007',
          ar: 'وَكَانَ فِرْعَوْنُ يَعْتَقِدُ أَنَّهُ مَلِكُ الْعُقُولِ كَمَا أَنَّهُ مَلِكُ الْأَجْسَامِ.',
          en: 'Pharaoh believed he was ruler of minds just as he was ruler of bodies.',
          tokens: [
            { surface: 'وَكَانَ', lemma: 'كَانَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ك و ن', gloss: 'to be; and was' },
            { surface: 'فِرْعَوْنُ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'nom', gloss: 'Pharaoh' },
            { surface: 'يَعْتَقِدُ', lemma: 'اِعْتَقَدَ', pos: 'verb', features: 'impf.3ms', gloss: 'believing' },
            { surface: 'أَنَّهُ', lemma: 'أَنَّ', pos: 'part', features: 'part+3ms', gloss: 'that he' },
            { surface: 'مَلِكُ', lemma: 'مَلِك', pos: 'noun', features: 'nom.constr', gloss: 'ruler of' },
            { surface: 'الْعُقُولِ', lemma: 'عَقْل', pos: 'noun', features: 'def.gen.pl', gloss: 'the minds' },
            { surface: 'كَمَا', lemma: 'كَمَا', pos: 'adv', features: 'adv', gloss: 'just as' },
            { surface: 'أَنَّهُ', lemma: 'أَنَّ', pos: 'part', features: 'part+3ms', gloss: 'he' },
            { surface: 'مَلِكُ', lemma: 'مَلِك', pos: 'noun', features: 'nom.constr', gloss: 'ruler of' },
            { surface: 'الْأَجْسَامِ', lemma: 'جِسْم', pos: 'noun', features: 'def.gen.pl', gloss: 'the bodies' },
          ],
        },
        {
          id: 'qs-v6-c25-008',
          ar: 'وَأَنَّ لَهُ سُلْطَاناً عَلَى الْقُلُوبِ كَمَا أَنَّ لَهُ سُلْطَاناً عَلَى الْأَلْسِنَةِ.',
          en: 'and that he had authority over hearts just as he had authority over tongues.',
          tokens: [
            { surface: 'وَأَنَّ', lemma: 'أَنَّ', pos: 'part', features: 'conj+part', gloss: 'and that' },
            { surface: 'لَهُ', lemma: 'لِ', pos: 'prep', features: 'prep+3ms', gloss: 'he had' },
            { surface: 'سُلْطَاناً', lemma: 'سُلْطَان', pos: 'noun', features: 'indef.acc', root: 'س ل ط', gloss: 'authority' },
            { surface: 'عَلَى', lemma: 'عَلَى', pos: 'prep', features: 'prep', gloss: 'over' },
            { surface: 'الْقُلُوبِ', lemma: 'قَلْب', pos: 'noun', features: 'def.gen.pl', gloss: 'the hearts' },
            { surface: 'كَمَا', lemma: 'كَمَا', pos: 'adv', features: 'adv', gloss: 'just as' },
            { surface: 'أَنَّ', lemma: 'أَنَّ', pos: 'part', features: 'part', gloss: 'that' },
            { surface: 'لَهُ', lemma: 'لِ', pos: 'prep', features: 'prep+3ms', gloss: 'he had' },
            { surface: 'سُلْطَاناً', lemma: 'سُلْطَان', pos: 'noun', features: 'indef.acc', root: 'س ل ط', gloss: 'authority' },
            { surface: 'عَلَى', lemma: 'عَلَى', pos: 'prep', features: 'prep', gloss: 'over' },
            { surface: 'الْأَلْسِنَةِ', lemma: 'لِسَان', pos: 'noun', features: 'def.gen.pl', gloss: 'the tongues' },
          ],
        },
        {
          id: 'qs-v6-c25-009',
          ar: 'وَلَيْسَ لِأَحَدٍ فِي مِصْرَ أَنْ يَعْتَقِدَ شَيْئاً أَوْ يُؤْمِنَ بِشَيْءٍ إِلَّا بِإِذْنِهِ فَقَالَ فِي كِبْرٍ وَجَبَرُوتٍ: ﴿آمَنتُمْ لَهُ قَبْلَ أَنْ آذَنَ لَكُمْ﴾؟!',
          en: 'and that no one in Egypt could believe or trust in anything except by his permission -- so he said, in pride and tyranny, "Did you believe in him before I gave you permission?!"',
          tokens: [
            { surface: 'وَلَيْسَ', lemma: 'لَيْسَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'and is not' },
            { surface: 'لِأَحَدٍ', lemma: 'أَحَد', pos: 'noun', features: 'prep+indef.gen', gloss: 'for anyone' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'مِصْرَ', lemma: 'مِصْر', pos: 'proper', features: 'gen', gloss: 'Egypt' },
            { surface: 'أَنْ', lemma: 'أَنْ', pos: 'part', features: 'part', gloss: 'to' },
            { surface: 'يَعْتَقِدَ', lemma: 'اِعْتَقَدَ', pos: 'verb', features: 'subj.3ms', gloss: 'believe' },
            { surface: 'شَيْئاً', lemma: 'شَيْء', pos: 'noun', features: 'indef.acc', gloss: 'anything' },
            { surface: 'أَوْ', lemma: 'أَوْ', pos: 'conj', features: 'conj', gloss: 'or' },
            { surface: 'يُؤْمِنَ', lemma: 'آمَنَ', pos: 'verb', features: 'subj.3ms', gloss: 'trust' },
            { surface: 'بِشَيْءٍ', lemma: 'شَيْء', pos: 'noun', features: 'prep+indef.gen', gloss: 'in anything' },
            { surface: 'إِلَّا', lemma: 'إِلَّا', pos: 'part', features: 'part', gloss: 'except' },
            { surface: 'بِإِذْنِهِ', lemma: 'إِذْن', pos: 'noun', features: 'prep+gen+3ms', root: 'أ ذ ن', gloss: 'by his permission' },
            { surface: 'فَقَالَ', lemma: 'قَالَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ق و ل', gloss: 'to say; so said' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'كِبْرٍ', lemma: 'كِبْر', pos: 'noun', features: 'indef.gen', gloss: 'pride' },
            { surface: 'وَجَبَرُوتٍ', lemma: 'جَبَرُوت', pos: 'noun', features: 'conj+indef.gen', root: 'ج ب ر', gloss: 'and tyranny' },
            { surface: 'آمَنتُمْ', lemma: 'آمَنَ', pos: 'verb', features: 'perf.2mp', gloss: 'did you believe' },
            { surface: 'لَهُ', lemma: 'لِ', pos: 'prep', features: 'prep+3ms', gloss: 'in him' },
            { surface: 'قَبْلَ', lemma: 'قَبْلَ', pos: 'prep', features: 'prep', gloss: 'before' },
            { surface: 'أَنْ', lemma: 'أَنْ', pos: 'part', features: 'part', gloss: 'that' },
            { surface: 'آذَنَ', lemma: 'إِذْن', pos: 'verb', features: 'subj.1s', gloss: 'to permit; I permit' },
            { surface: 'لَكُمْ', lemma: 'لِ', pos: 'prep', features: 'prep+2mp', gloss: 'you' },
          ],
        },
        {
          id: 'qs-v6-c25-010',
          ar: 'وَرَمَاهُمْ فِرْعَوْنُ بِسَهْمٍ مِنْ سِهَامِ الْمُلُوكِ فَقَالَ: ﴿إِنَّهُ لَكَبِيرُكُمُ الَّذِي عَلَّمَكُمُ السِّحْرَ﴾!',
          en: 'Pharaoh shot them with an arrow from the arrows of kings and said, "He is indeed your chief who taught you magic!"',
          tokens: [
            { surface: 'وَرَمَاهُمْ', lemma: 'رَمَى', pos: 'verb', features: 'conj+perf.3ms+3mp', root: 'ر م ي', gloss: 'to shoot; and shot them' },
            { surface: 'فِرْعَوْنُ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'nom', gloss: 'Pharaoh' },
            { surface: 'بِسَهْمٍ', lemma: 'سَهْم', pos: 'noun', features: 'prep+indef.gen', gloss: 'with an arrow' },
            { surface: 'مِنْ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'from' },
            { surface: 'سِهَامِ', lemma: 'سَهْم', pos: 'noun', features: 'constr.gen.pl', gloss: 'the arrows of' },
            { surface: 'الْمُلُوكِ', lemma: 'مَلِك', pos: 'noun', features: 'def.gen.pl', gloss: 'kings' },
            { surface: 'فَقَالَ', lemma: 'قَالَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ق و ل', gloss: 'and said' },
            { surface: 'إِنَّهُ', lemma: 'إِنَّ', pos: 'part', features: 'part+3ms', gloss: 'indeed he' },
            { surface: 'لَكَبِيرُكُمُ', lemma: 'كَبِير', pos: 'noun', features: 'part+nom+2mp', gloss: 'your chief' },
            { surface: 'الَّذِي', lemma: 'الَّذِي', pos: 'rel', features: 'rel', gloss: 'who' },
            { surface: 'عَلَّمَكُمُ', lemma: 'عَلَّمَ', pos: 'verb', features: 'perf.3ms+2mp', gloss: 'to teach; taught you' },
            { surface: 'السِّحْرَ', lemma: 'سِحْر', pos: 'noun', features: 'def.acc', gloss: 'magic' },
          ],
        },
        {
          id: 'qs-v6-c25-011',
          ar: 'وَرَمَاهُمْ بِسَهْمٍ ثَانٍ فَقَالَ: ﴿إِنَّ هَذَا لَمَكْرٌ مَّكَرْتُمُوهُ فِي الْمَدِينَةِ لِتُخْرِجُوا مِنْهَا أَهْلَهَا فَسَوْفَ تَعْلَمُونَ﴾!!',
          en: 'He shot them with a second arrow and said, "This is indeed a plot you schemed in the city to drive its people out of it -- you will soon know!!"',
          tokens: [
            { surface: 'وَرَمَاهُمْ', lemma: 'رَمَى', pos: 'verb', features: 'conj+perf.3ms+3mp', root: 'ر م ي', gloss: 'and shot them' },
            { surface: 'بِسَهْمٍ', lemma: 'سَهْم', pos: 'noun', features: 'prep+indef.gen', gloss: 'with an arrow' },
            { surface: 'ثَانٍ', lemma: 'ثَانٍ', pos: 'adj', features: 'indef.gen', gloss: 'second' },
            { surface: 'فَقَالَ', lemma: 'قَالَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ق و ل', gloss: 'and said' },
            { surface: 'إِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'هَذَا', lemma: 'هَذَا', pos: 'dem', features: 'dem', gloss: 'this' },
            { surface: 'لَمَكْرٌ', lemma: 'مَكْر', pos: 'noun', features: 'part+indef.nom', root: 'م ك ر', gloss: 'is indeed a plot' },
            { surface: 'مَّكَرْتُمُوهُ', lemma: 'مَكْر', pos: 'verb', features: 'perf.2mp+3ms', gloss: 'you schemed it' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'الْمَدِينَةِ', lemma: 'مَدِينَة', pos: 'noun', features: 'def.gen', gloss: 'the city' },
            { surface: 'لِتُخْرِجُوا', lemma: 'أَخْرَجَ', pos: 'verb', features: 'prep+subj.2mp', gloss: 'to drive out; to drive out' },
            { surface: 'مِنْهَا', lemma: 'مِنْ', pos: 'prep', features: 'prep+3fs', gloss: 'of it' },
            { surface: 'أَهْلَهَا', lemma: 'أَهْل', pos: 'noun', features: 'acc+3fs', gloss: 'its people' },
            { surface: 'فَسَوْفَ', lemma: 'سَوْفَ', pos: 'part', features: 'conj+part', gloss: 'so you will' },
            { surface: 'تَعْلَمُونَ', lemma: 'عَلِمَ', pos: 'verb', features: 'impf.2mp', gloss: 'soon know' },
          ],
        },
        {
          id: 'qs-v6-c25-012',
          ar: 'وَرَمَاهُمْ بِسَهْمٍ ثَالِثٍ مَسْمُومٍ هُوَ السَّهْمُ الْأَخِيرُ فِي كِنَانَةِ الْمُلُوكِ.',
          en: 'He shot them with a third, poisoned arrow -- the last arrow in the quiver of kings.',
          tokens: [
            { surface: 'وَرَمَاهُمْ', lemma: 'رَمَى', pos: 'verb', features: 'conj+perf.3ms+3mp', root: 'ر م ي', gloss: 'and shot them' },
            { surface: 'بِسَهْمٍ', lemma: 'سَهْم', pos: 'noun', features: 'prep+indef.gen', gloss: 'with an arrow' },
            { surface: 'ثَالِثٍ', lemma: 'ثَالِث', pos: 'adj', features: 'indef.gen', gloss: 'third' },
            { surface: 'مَسْمُومٍ', lemma: 'مَسْمُوم', pos: 'adj', features: 'indef.gen', root: 'س م م', gloss: 'poisoned' },
            { surface: 'هُوَ', lemma: 'هُوَ', pos: 'noun', features: '3ms', gloss: 'it was' },
            { surface: 'السَّهْمُ', lemma: 'سَهْم', pos: 'noun', features: 'def.nom', gloss: 'the arrow' },
            { surface: 'الْأَخِيرُ', lemma: 'أَخِير', pos: 'adj', features: 'def.nom', gloss: 'the last' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'كِنَانَةِ', lemma: 'كِنَانَة', pos: 'noun', features: 'constr.gen', root: 'ك ن ن', gloss: 'the quiver of' },
            { surface: 'الْمُلُوكِ', lemma: 'مَلِك', pos: 'noun', features: 'def.gen.pl', gloss: 'kings' },
          ],
        },
        {
          id: 'qs-v6-c25-013',
          ar: '﴿لَأُقَطِّعَنَّ أَيْدِيَكُمْ وَأَرْجُلَكُم مِّنْ خِلافٍ ثُمَّ لَأُصَلِّبَنَّكُمْ أَجْمَعِينَ﴾.',
          en: '"I will surely cut off your hands and feet on opposite sides, then crucify you all."',
          tokens: [
            { surface: 'لَأُقَطِّعَنَّ', lemma: 'قَطَّعَ', pos: 'verb', features: 'part+impf.1s', root: 'ق ط ع', gloss: 'to cut off; I will surely cut off' },
            { surface: 'أَيْدِيَكُمْ', lemma: 'يَد', pos: 'noun', features: 'pl.acc+2mp', gloss: 'your hands' },
            { surface: 'وَأَرْجُلَكُم', lemma: 'رِجْل', pos: 'noun', features: 'conj+pl.acc+2mp', gloss: 'and your feet' },
            { surface: 'مِّنْ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'from' },
            { surface: 'خِلافٍ', lemma: 'خِلَاف', pos: 'noun', features: 'indef.gen', root: 'خ ل ف', gloss: 'opposite sides' },
            { surface: 'ثُمَّ', lemma: 'ثُمَّ', pos: 'conj', features: 'conj', gloss: 'then' },
            { surface: 'لَأُصَلِّبَنَّكُمْ', lemma: 'صَلَّبَ', pos: 'verb', features: 'part+impf.1s+2mp', root: 'ص ل ب', gloss: 'to crucify; I will surely crucify you' },
            { surface: 'أَجْمَعِينَ', lemma: 'أَجْمَعِينَ', pos: 'adj', features: 'acc.pl', gloss: 'all' },
          ],
        },
      ],
      checks: [
        {
          q: 'بِمَاذَا هَدَّدَ فِرْعَوْنُ السَّحَرَةَ الَّذِينَ آمَنُوا؟',
          options: ['بِتَقْطِيعِ أَيْدِيهِمْ وَأَرْجُلِهِمْ مِنْ خِلَافٍ ثُمَّ صَلْبِهِمْ', 'بِطَرْدِهِمْ مِنْ مِصْرَ فَقَطْ', 'بِسَجْنِهِمْ لِمُدَّةٍ قَصِيرَةٍ'],
          answer: 0,
          qEn: 'What did Pharaoh threaten the sorcerers who believed with?',
          optionsEn: ['Cutting off their hands and feet on opposite sides, then crucifying them', 'Merely expelling them from Egypt', 'A short prison sentence'],
        },
      ],
    },
    {
      en: 'The believers received all these arrows with the shield of faith and patience, and said, "No harm -- indeed to our Lord we shall return. Indeed we hope that our Lord will forgive us our sins, since we were the first of the believers." And they said, in faith and zeal: "Indeed we have believed in our Lord, that He may forgive us our sins and the magic you compelled us to practice -- Allah is better and more lasting. Indeed, whoever comes to his Lord a sinner, for him is Hell, wherein he neither dies nor lives; but whoever comes to Him a believer, having done righteous deeds -- for them are the highest ranks: gardens of Eden, beneath which rivers flow, abiding therein forever. That is the reward of one who purifies himself."',
      sentences: [
        {
          id: 'qs-v6-c25-014',
          ar: 'وَتَلَقَّى الْمُؤْمِنُونَ السِّهَامَ كُلَّهَا بِجُنَّةِ الإِيمَانِ وَالصَّبْرِ وَقَالُوا:',
          en: 'The believers received all these arrows with the shield of faith and patience, and said:',
          tokens: [
            { surface: 'وَتَلَقَّى', lemma: 'تَلَقَّى', pos: 'verb', features: 'conj+perf.3ms', root: 'ل ق ي', gloss: 'to receive; and received' },
            { surface: 'الْمُؤْمِنُونَ', lemma: 'مُؤْمِن', pos: 'noun', features: 'def.nom.pl', gloss: 'the believers' },
            { surface: 'السِّهَامَ', lemma: 'سَهْم', pos: 'noun', features: 'def.acc.pl', gloss: 'the arrows' },
            { surface: 'كُلَّهَا', lemma: 'كُلّ', pos: 'noun', features: 'acc+3fs', gloss: 'all of them' },
            { surface: 'بِجُنَّةِ', lemma: 'جُنَّة', pos: 'noun', features: 'prep+constr.gen', root: 'ج ن ن', gloss: 'with the shield of' },
            { surface: 'الإِيمَانِ', lemma: 'إِيمَان', pos: 'noun', features: 'def.gen', root: 'أ م ن', gloss: 'faith' },
            { surface: 'وَالصَّبْرِ', lemma: 'صَبْر', pos: 'noun', features: 'conj+def.gen', gloss: 'and patience' },
            { surface: 'وَقَالُوا', lemma: 'قَالَ', pos: 'verb', features: 'conj+perf.3mp', root: 'ق و ل', gloss: 'and said' },
          ],
        },
        {
          id: 'qs-v6-c25-015',
          ar: '﴿لا ضَيْرَ إِنَّآ إِلَى رَبِّنَا مُنقَلِبُونَ﴾.',
          en: '"No harm -- indeed to our Lord we shall return."',
          tokens: [
            { surface: 'لا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'no' },
            { surface: 'ضَيْرَ', lemma: 'ضَيْر', pos: 'noun', features: 'acc', root: 'ض ي ر', gloss: 'harm' },
            { surface: 'إِنَّآ', lemma: 'إِنَّ', pos: 'part', features: 'part+1p', gloss: 'indeed we' },
            { surface: 'إِلَى', lemma: 'إِلَى', pos: 'prep', features: 'prep', gloss: 'to' },
            { surface: 'رَبِّنَا', lemma: 'رَبّ', pos: 'noun', features: 'gen+1p', gloss: 'our Lord' },
            { surface: 'مُنقَلِبُونَ', lemma: 'مُنْقَلِب', pos: 'noun', features: 'indef.nom.pl', root: 'ق ل ب', gloss: 'returning' },
          ],
        },
        {
          id: 'qs-v6-c25-016',
          ar: '﴿إِنَّا نَطْمَعُ أَن يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا أَن كُنَّآ أَوَّلَ الْمُؤْمِنِينَ﴾.',
          en: 'Indeed we hope that our Lord will forgive us our sins, since we were the first of the believers."',
          tokens: [
            { surface: 'إِنَّا', lemma: 'إِنَّ', pos: 'part', features: 'part+1p', gloss: 'indeed we' },
            { surface: 'نَطْمَعُ', lemma: 'طَمِعَ', pos: 'verb', features: 'impf.1p', root: 'ط م ع', gloss: 'to hope eagerly; hope' },
            { surface: 'أَن', lemma: 'أَنْ', pos: 'part', features: 'part', gloss: 'that' },
            { surface: 'يَغْفِرَ', lemma: 'غَفَرَ', pos: 'verb', features: 'subj.3ms', gloss: 'will forgive' },
            { surface: 'لَنَا', lemma: 'لِ', pos: 'prep', features: 'prep+1p', gloss: 'us' },
            { surface: 'رَبُّنَا', lemma: 'رَبّ', pos: 'noun', features: 'nom+1p', gloss: 'our Lord' },
            { surface: 'خَطَايَانَا', lemma: 'خَطِيئَة', pos: 'noun', features: 'pl.acc+1p', root: 'خ ط أ', gloss: 'our sins' },
            { surface: 'أَن', lemma: 'أَنْ', pos: 'part', features: 'part', gloss: 'since' },
            { surface: 'كُنَّآ', lemma: 'كَانَ', pos: 'verb', features: 'perf.1p', root: 'ك و ن', gloss: 'we were' },
            { surface: 'أَوَّلَ', lemma: 'أَوَّل', pos: 'noun', features: 'acc.constr', gloss: 'the first of' },
            { surface: 'الْمُؤْمِنِينَ', lemma: 'مُؤْمِن', pos: 'noun', features: 'def.gen.pl', gloss: 'the believers' },
          ],
        },
        {
          id: 'qs-v6-c25-017',
          ar: 'وَقَالُوا فِي إِيمَانٍ وَحَمَاسَةٍ:',
          en: 'And they said, in faith and zeal:',
          tokens: [
            { surface: 'وَقَالُوا', lemma: 'قَالَ', pos: 'verb', features: 'conj+perf.3mp', root: 'ق و ل', gloss: 'and said' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'إِيمَانٍ', lemma: 'إِيمَان', pos: 'noun', features: 'indef.gen', root: 'أ م ن', gloss: 'faith' },
            { surface: 'وَحَمَاسَةٍ', lemma: 'حَمَاسَة', pos: 'noun', features: 'conj+indef.gen', root: 'ح م س', gloss: 'and zeal' },
          ],
        },
        {
          id: 'qs-v6-c25-018',
          ar: '﴿إِنَّا آمَنَّا بِرَبِّنَا لِيَغْفِرَ لَنَا خَطَايَانَا وَمَا أَكْرَهْتَنَا عَلَيْهِ مِنَ السِّحْرِ وَاللَّهُ خَيْرٌ وَأَبْقَى.',
          en: 'Indeed we have believed in our Lord, that He may forgive us our sins and the magic you compelled us to practice -- Allah is better and more lasting.',
          tokens: [
            { surface: 'إِنَّا', lemma: 'إِنَّ', pos: 'part', features: 'part+1p', gloss: 'indeed we' },
            { surface: 'آمَنَّا', lemma: 'آمَنَ', pos: 'verb', features: 'perf.1p', gloss: 'have believed' },
            { surface: 'بِرَبِّنَا', lemma: 'رَبّ', pos: 'noun', features: 'prep+gen+1p', gloss: 'in our Lord' },
            { surface: 'لِيَغْفِرَ', lemma: 'غَفَرَ', pos: 'verb', features: 'prep+subj.3ms', gloss: 'that He may forgive' },
            { surface: 'لَنَا', lemma: 'لِ', pos: 'prep', features: 'prep+1p', gloss: 'us' },
            { surface: 'خَطَايَانَا', lemma: 'خَطِيئَة', pos: 'noun', features: 'pl.acc+1p', root: 'خ ط أ', gloss: 'our sins' },
            { surface: 'وَمَا', lemma: 'مَا', pos: 'rel', features: 'conj+rel', gloss: 'and what' },
            { surface: 'أَكْرَهْتَنَا', lemma: 'أَكْرَهَ', pos: 'verb', features: 'perf.2ms+1p', root: 'ك ر ه', gloss: 'to compel; you compelled us' },
            { surface: 'عَلَيْهِ', lemma: 'عَلَى', pos: 'prep', features: 'prep+3ms', gloss: 'to' },
            { surface: 'مِنَ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'of' },
            { surface: 'السِّحْرِ', lemma: 'سِحْر', pos: 'noun', features: 'def.gen', gloss: 'the magic' },
            { surface: 'وَاللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'conj+nom', gloss: 'and Allah' },
            { surface: 'خَيْرٌ', lemma: 'خَيْر', pos: 'adj', features: 'indef.nom', gloss: 'better' },
            { surface: 'وَأَبْقَى', lemma: 'أَبْقَى', pos: 'adj', features: 'conj+nom', root: 'ب ق ي', gloss: 'and more lasting' },
          ],
        },
        {
          id: 'qs-v6-c25-019',
          ar: 'إِنَّهُ مَن يَأْتِ رَبَّهُ مُجْرِمًا فَإِنَّ لَهُ جَهَنَّمَ لَا يَمُوتُ فِيهَا وَلَا يَحْيَى.',
          en: 'Indeed, whoever comes to his Lord a sinner, for him is Hell, wherein he neither dies nor lives;',
          tokens: [
            { surface: 'إِنَّهُ', lemma: 'إِنَّ', pos: 'part', features: 'part+3ms', gloss: 'indeed' },
            { surface: 'مَن', lemma: 'مَنْ', pos: 'rel', features: 'rel', gloss: 'whoever' },
            { surface: 'يَأْتِ', lemma: 'أَتَى', pos: 'verb', features: 'juss.3ms', gloss: 'comes' },
            { surface: 'رَبَّهُ', lemma: 'رَبّ', pos: 'noun', features: 'acc+3ms', gloss: 'his Lord' },
            { surface: 'مُجْرِمًا', lemma: 'مُجْرِم', pos: 'noun', features: 'indef.acc', gloss: 'a sinner' },
            { surface: 'فَإِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'conj+part', gloss: 'then indeed' },
            { surface: 'لَهُ', lemma: 'لِ', pos: 'prep', features: 'prep+3ms', gloss: 'for him' },
            { surface: 'جَهَنَّمَ', lemma: 'جَهَنَّم', pos: 'proper', features: 'acc', root: 'ج ه ن م', gloss: 'is Hell' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'يَمُوتُ', lemma: 'مَاتَ', pos: 'verb', features: 'impf.3ms', gloss: 'he dies' },
            { surface: 'فِيهَا', lemma: 'فِي', pos: 'prep', features: 'prep+3fs', gloss: 'therein' },
            { surface: 'وَلَا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'يَحْيَى', lemma: 'حَيِيَ', pos: 'verb', features: 'impf.3ms', root: 'ح ي ي', gloss: 'to live; lives' },
          ],
        },
        {
          id: 'qs-v6-c25-020',
          ar: 'وَمَن يَأْتِهِ مُؤْمِنًا قَدْ عَمِلَ الصَّالِحَاتِ فَأُولَئِكَ لَهُمُ الدَّرَجَاتُ الْعُلَى',
          en: 'but whoever comes to Him a believer, having done righteous deeds -- for them are the highest ranks:',
          tokens: [
            { surface: 'وَمَن', lemma: 'مَنْ', pos: 'rel', features: 'conj+rel', gloss: 'and whoever' },
            { surface: 'يَأْتِهِ', lemma: 'أَتَى', pos: 'verb', features: 'juss.3ms+3ms', gloss: 'comes to Him' },
            { surface: 'مُؤْمِنًا', lemma: 'مُؤْمِن', pos: 'noun', features: 'indef.acc', gloss: 'a believer' },
            { surface: 'قَدْ', lemma: 'قَدْ', pos: 'part', features: 'part', gloss: 'having' },
            { surface: 'عَمِلَ', lemma: 'عَمِلَ', pos: 'verb', features: 'perf.3ms', gloss: 'done' },
            { surface: 'الصَّالِحَاتِ', lemma: 'صَالِح', pos: 'noun', features: 'def.acc.pl.f', root: 'ص ل ح', gloss: 'righteous deeds' },
            { surface: 'فَأُولَئِكَ', lemma: 'أُولَئِكَ', pos: 'dem', features: 'conj+dem.pl', gloss: 'then those' },
            { surface: 'لَهُمُ', lemma: 'لِ', pos: 'prep', features: 'prep+3mp', gloss: 'for them' },
            { surface: 'الدَّرَجَاتُ', lemma: 'دَرَجَة', pos: 'noun', features: 'def.nom.pl', root: 'د ر ج', gloss: 'are the ranks' },
            { surface: 'الْعُلَى', lemma: 'أَعْلَى', pos: 'adj', features: 'def.nom.pl', gloss: 'the highest' },
          ],
        },
        {
          id: 'qs-v6-c25-021',
          ar: 'جَنَّاتُ عَدْنٍ تَجْرِي مِن تَحْتِهَا الأَنْهَارُ خَالِدِينَ فِيهَا وَذَلِكَ جَزَاءُ مَن تَزَكَّى﴾.',
          en: 'gardens of Eden, beneath which rivers flow, abiding therein forever. That is the reward of one who purifies himself."',
          tokens: [
            { surface: 'جَنَّاتُ', lemma: 'جَنَّة', pos: 'noun', features: 'nom.pl.constr', gloss: 'gardens of' },
            { surface: 'عَدْنٍ', lemma: 'عَدْن', pos: 'proper', features: 'indef.gen', root: 'ع د ن', gloss: 'Eden' },
            { surface: 'تَجْرِي', lemma: 'جَرَى', pos: 'verb', features: 'impf.3fs', gloss: 'to flow; flow' },
            { surface: 'مِن', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'from' },
            { surface: 'تَحْتِهَا', lemma: 'تَحْتَ', pos: 'adv', features: 'gen+3fs', gloss: 'beneath which' },
            { surface: 'الأَنْهَارُ', lemma: 'نَهْر', pos: 'noun', features: 'def.nom.pl', gloss: 'the rivers' },
            { surface: 'خَالِدِينَ', lemma: 'خَالِد', pos: 'adj', features: 'acc.pl', gloss: 'abiding forever' },
            { surface: 'فِيهَا', lemma: 'فِي', pos: 'prep', features: 'prep+3fs', gloss: 'therein' },
            { surface: 'وَذَلِكَ', lemma: 'ذَلِكَ', pos: 'dem', features: 'conj+dem', gloss: 'and that' },
            { surface: 'جَزَاءُ', lemma: 'جَزَاء', pos: 'noun', features: 'nom.constr', gloss: 'is the reward of' },
            { surface: 'مَن', lemma: 'مَنْ', pos: 'rel', features: 'rel', gloss: 'one who' },
            { surface: 'تَزَكَّى', lemma: 'زَكَّى', pos: 'verb', features: 'perf.3ms', root: 'ز ك و', gloss: 'to purify oneself; purifies himself' },
          ],
        },
      ],
      checks: [
        {
          q: 'كَيْفَ رَدَّ السَّحَرَةُ الْمُؤْمِنُونَ عَلَى تَهْدِيدِ فِرْعَوْنَ؟',
          options: ['لَا ضَيْرَ، إِنَّا إِلَى رَبِّنَا مُنْقَلِبُونَ', 'تَرَاجَعُوا عَنِ الْإِيمَانِ خَوْفاً', 'طَلَبُوا الْعَفْوَ مِنْ فِرْعَوْنَ'],
          answer: 0,
          qEn: "How did the newly-believing sorcerers respond to Pharaoh's threat?",
          optionsEn: ['"No harm -- indeed to our Lord we shall return"', 'They recanted their faith out of fear', 'They asked Pharaoh for pardon'],
        },
      ],
    },
  ],
  workshop: {
    cloze: [
      {
        type: 'cloze',
        pre: 'وَكَانَ فِرْعَوْنُ',
        post: 'أَنَّهُ مَلِكُ الْعُقُولِ.',
        en: 'Pharaoh believed he was ruler of minds.',
        options: ['يَعْتَقِدُ', 'اِعْتَقَدَ', 'يَعْتَقِدَ', 'مُعْتَقِدٌ'],
        answer: 0,
        rationales: [
          'كَانَ + imperfect -- the ongoing-past construction ("used to believe"), matching the taught pattern.',
          'Perfect -- wrong; كَانَ + perfect does not form this ongoing-past meaning.',
          'Subjunctive -- wrong mood; nothing here triggers the subjunctive.',
          'Active participle -- wrong; كَانَ needs a verb here, not an adjective-like participle alone.',
        ],
      },
      {
        type: 'cloze',
        pre: 'إِنَّا آمَنَّا بِرَبِّنَا',
        post: 'لَنَا خَطَايَانَا.',
        en: 'Indeed we have believed in our Lord, that He may forgive us our sins.',
        options: ['لِيَغْفِرَ', 'لِيَغْفِرُ', 'لِغَفَرَ', 'لِيَغْفِرَنَّ'],
        answer: 0,
        rationales: [
          'لِ + subjunctive -- purpose clause ("so that He may forgive"), matching the taught pattern.',
          'لِ + indicative -- wrong mood; لِ of purpose requires the subjunctive.',
          'لِ + perfect -- wrong; a purpose clause takes the subjunctive imperfect, not the perfect.',
          'Emphatic نّ form -- wrong register for this position; not what is printed.',
        ],
      },
    ],
    shift: [
      {
        type: 'shift',
        base: 'يَرْمِي الْمَلِكُ السَّحَرَةَ بِسَهْمٍ',
        pre: '',
        post: 'بِسَهْمٍ',
        targetPerson: 'أَنَا',
        targetEn: 'I',
        options: ['أَرْمِي', 'يَرْمِي', 'تَرْمِي', 'نَرْمِي'],
        answer: 0,
        rationales: [
          '1st singular -- matches أَنَا.',
          '3rd masculine singular -- he, the form already given.',
          '2nd masculine singular / 3rd feminine singular -- wrong person.',
          '1st plural -- we.',
        ],
      },
      {
        type: 'shift',
        base: 'يَرْمِي الْمَلِكُ السَّحَرَةَ بِسَهْمٍ',
        pre: '',
        post: 'بِسَهْمٍ',
        targetPerson: 'هُمْ',
        targetEn: 'they (m.)',
        options: ['يَرْمُونَ', 'يَرْمِي', 'تَرْمِي', 'نَرْمِي'],
        answer: 0,
        rationales: [
          '3rd masculine plural -- matches هُمْ.',
          '3rd masculine singular -- he, the form already given.',
          '3rd feminine singular -- she.',
          '1st plural -- we.',
        ],
      },
    ],
  },
};
