// قَصَصُ النَّبِيِّينَ, volume 6 (Mūsā, part 1), chapter 23 -- إِلَى
// الْمَيْدَانِ. Printed pages 150 (heading, partway down, right after
// ch22's closing Qur'an citation 26:40) - 151 - 152 (top only), ending
// right before ch24's heading «بَيْنَ الْحَقِّ وَالْبَاطِلِ» which opens
// partway down page 152. Transcribed by hand from the scan (vision OCR,
// 200dpi render) against ../CHAPTER-FORMAT.md. Covers Sūrat ash-Shuʿarāʾ
// 26:39-42: the crowds gathering for the sorcerers' contest, street
// gossip doubting Mūsā's chances, and the sorcerers' festive, overconfident
// arrival -- building dramatic irony before ch24's actual contest.
//
// Grammar / lexical notes:
//   -- الْمَطَرِيَّة، الْأُقْصُر، الْجِيزَة are real Egyptian place names
//      (Nadwi's own footnotes on p.150, reproduced here as book_note on
//      the relevant lemma entries) -- footnote (1) glosses الْمَطَرِيَّة as
//      "a story of Egypt in the days of the Pharaohs," footnotes (2)(3)(4)
//      as "ancient cities of Egypt."
//   -- أَفْلَاذَ كَبِدِهَا (qs-v6-c23-008) is an idiom, literally "the
//      livers' fragments," meaning "her own most precious children" --
//      glossed contextually, not word-for-word.
//   -- Shared lexicon check (cross-checked against known_lemmas.json):
//      طِفْل, شَابّ, شَيْخ, رَجُل, اِمْرَأَة, بَقِيَ, حَدِيث, اِسْم, أَسْوَان, أَكْبَر,
//      أَخ, غَلَبَ, نَشَأَ, يَأْس, رَجَاء, عِمْرَان, أَقْبَلَ, عَصًا, ضَحِكَ, فَضْل,
//      أَجْر, غَالِب, جَائِزَة, فَرِحَ, مَلِك, قَوْم, هَلْ, جَاءَ, نَعَمْ, مَاذَا, رَأَى,
//      يَا, مَنْ, إِنَّ, مِصْرَ, قَدْ, أَلْقَى, كَيْفَ, أَيْنَ, تَعَلَّمَ, سِحْر, فِي,
//      قَصْر, خَرَجَ, خَائِف, تَرَقَّبَ, كَانَ, مَدْيَن, سَنَة, لَا, مَا, سَمِعَ,
//      هُنَالِكَ, بَنِي إِسْرَائِيلَ, بَيْنَ, لَعَلَّ, اللَّه, رَحِمَ, نَصَرَ, بِ,
//      يَحْمِلُونَ/حَمَلَ, يَوْم, قَالَ, لِ, فِرْعَوْن, إِذاً, هَذَا, هِيَ, هَذِهِ
//      are all already taught (or reused) and are NOT re-listed in
//      newWords here.
//
// ~23 new words (ضُحًى، فَوْج، مَرِيض، عَاجِز، شَهِير، أَفْلَاذ، كَبِد، فَنّ،
// أَغْلَب، خُيَلَاء، فَخْر، مَلَابِس، مُلَوَّن، حِبَال، مَرِحَ، صَنِيع، مُقَرَّب،
// عَطَاء، خَدَعَ، صَادَ، بَطَل، مَوْعِد -- plus 3 place names).
export const CHAPTER = {
  id: 'ch23',
  title: { ar: 'إِلَى الْمَيْدَانِ', en: 'To the Arena' },
  newWords: ['ضُحًى', 'فَوْج', 'مَيْدَان', 'مَرِيض', 'عَاجِز', 'مَطَرِيَّة', 'أُقْصُر', 'جِيزَة', 'شَهِير', 'أَفْلَاذ', 'كَبِد', 'فَنّ', 'أَغْلَب', 'خُيَلَاء', 'فَخْر', 'مَلَابِس', 'مُلَوَّن', 'حِبَال', 'مَرِحَ', 'صَنِيع', 'مُقَرَّب', 'عَطَاء', 'خَدَعَ', 'صَادَ', 'بَطَل', 'مَوْعِد'],
  lemmas: {
    مَيْدَان: { gloss: 'arena, public square' },
    ضُحًى: { gloss: 'forenoon, mid-morning' },
    فَوْج: { gloss: 'a group, troop (pl. أَفْوَاج)' },
    مَرِيض: { gloss: 'sick, ill' },
    عَاجِز: { gloss: 'incapacitated, unable' },
    مَطَرِيَّة: { gloss: 'al-Maṭariyyah, a district of ancient Egypt', book_note: 'قصة مصر أيام الفراعنة' },
    أُقْصُر: { gloss: 'Luxor', book_note: 'من مدن مصر القديمة' },
    جِيزَة: { gloss: 'Giza', book_note: 'من مدن مصر القديمة' },
    شَهِير: { gloss: 'famous, renowned' },
    أَفْلَاذ: { gloss: '(idiom) most precious children (lit. livers’ fragments)' },
    كَبِد: { gloss: 'liver' },
    فَنّ: { gloss: 'art, skill' },
    أَغْلَب: { gloss: 'greater, predominant' },
    خُيَلَاء: { gloss: 'conceit, vanity' },
    فَخْر: { gloss: 'pride, boastfulness' },
    مَلَابِس: { gloss: 'clothes, garments' },
    مُلَوَّن: { gloss: 'colored' },
    حِبَال: { gloss: 'ropes (sg. حَبْل)' },
    مَرِحَ: { gloss: 'to be joyful, exult' },
    صَنِيع: { gloss: 'a deed, handiwork' },
    مُقَرَّب: { gloss: 'one brought near, favored' },
    عَطَاء: { gloss: 'a gift, grant' },
    خَدَعَ: { gloss: 'to deceive' },
    صَادَ: { gloss: 'to hunt, catch' },
    بَطَل: { gloss: 'a hero' },
    مَوْعِد: { gloss: 'a promise, an appointed pledge' },
  },
  paragraphs: [
    {
      en: 'You could see the people leaving their houses in the forenoon, walking to the arena in troops -- walking to the arena as children, young men and old men, and men and women. Nothing remained in any house except the sick or the incapacitated. And you would hear nothing in al-Maṭariyyah but talk of magic and the names of sorcerers. "Has the greatest sorcerer of Aswan come too?" "Yes, and the sorcerer of Luxor, and the famous sorcerer of Giza!"',
      sentences: [
        {
          id: 'qs-v6-c23-001',
          ar: 'وَتَرَى النَّاسَ يَخْرُجُونَ مِنْ بُيُوتِهِمْ ضُحىً! وَيَمْشُونَ إِلَى الْمِيدَانِ أَفْوَاجاً.',
          en: 'You could see the people leaving their houses in the forenoon! And walking to the arena in troops.',
          tokens: [
            { surface: 'وَتَرَى', lemma: 'رَأَى', pos: 'verb', features: 'conj+impf.2ms', root: 'ر أ ي', gloss: 'to see; you could see' },
            { surface: 'النَّاسَ', lemma: 'نَاس', pos: 'noun', features: 'def.acc', gloss: 'the people' },
            { surface: 'يَخْرُجُونَ', lemma: 'خَرَجَ', pos: 'verb', features: 'impf.3mp', gloss: 'leaving' },
            { surface: 'مِنْ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'from' },
            { surface: 'بُيُوتِهِمْ', lemma: 'بَيْت', pos: 'noun', features: 'pl.gen+3mp', gloss: 'their houses' },
            { surface: 'ضُحىً', lemma: 'ضُحًى', pos: 'noun', features: 'indef.acc', root: 'ض ح و', gloss: 'in the forenoon' },
            { surface: 'وَيَمْشُونَ', lemma: 'مَشَى', pos: 'verb', features: 'conj+impf.3mp', gloss: 'to walk; and walking' },
            { surface: 'إِلَى', lemma: 'إِلَى', pos: 'prep', features: 'prep', gloss: 'to' },
            { surface: 'الْمِيدَانِ', lemma: 'مَيْدَان', pos: 'noun', features: 'def.gen', gloss: 'the arena' },
            { surface: 'أَفْوَاجاً', lemma: 'فَوْج', pos: 'noun', features: 'indef.acc.pl', root: 'ف و ج', gloss: 'in troops' },
          ],
        },
        {
          id: 'qs-v6-c23-002',
          ar: 'وَيَمْشُونَ إِلَى الْمِيدَانِ أَطْفَالاً، وَشُبَّاناً وَشُيُوخاً، وَرِجَالاً وَنِسَاءً.',
          en: 'Walking to the arena as children, young men and old men, and men and women.',
          tokens: [
            { surface: 'وَيَمْشُونَ', lemma: 'مَشَى', pos: 'verb', features: 'conj+impf.3mp', gloss: 'and walking' },
            { surface: 'إِلَى', lemma: 'إِلَى', pos: 'prep', features: 'prep', gloss: 'to' },
            { surface: 'الْمِيدَانِ', lemma: 'مَيْدَان', pos: 'noun', features: 'def.gen', gloss: 'the arena' },
            { surface: 'أَطْفَالاً', lemma: 'طِفْل', pos: 'noun', features: 'indef.acc.pl', gloss: 'as children' },
            { surface: 'وَشُبَّاناً', lemma: 'شَابّ', pos: 'noun', features: 'conj+indef.acc.pl', gloss: 'and young men' },
            { surface: 'وَشُيُوخاً', lemma: 'شَيْخ', pos: 'noun', features: 'conj+indef.acc.pl', gloss: 'and old men' },
            { surface: 'وَرِجَالاً', lemma: 'رَجُل', pos: 'noun', features: 'conj+indef.acc.pl', gloss: 'and men' },
            { surface: 'وَنِسَاءً', lemma: 'نِسَاء', pos: 'noun', features: 'conj+indef.acc', gloss: 'and women' },
          ],
        },
        {
          id: 'qs-v6-c23-003',
          ar: 'وَلَمْ يَبْقَ فِي الْبَيْتِ إِلَّا مَرِيضٌ أَوْ عَاجِزٌ.',
          en: 'Nothing remained in any house except the sick or the incapacitated.',
          tokens: [
            { surface: 'وَلَمْ', lemma: 'لَمْ', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'يَبْقَ', lemma: 'بَقِيَ', pos: 'verb', features: 'juss.3ms', gloss: 'to remain; remained' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'الْبَيْتِ', lemma: 'بَيْت', pos: 'noun', features: 'def.gen', gloss: 'the house' },
            { surface: 'إِلَّا', lemma: 'إِلَّا', pos: 'part', features: 'part', gloss: 'except' },
            { surface: 'مَرِيضٌ', lemma: 'مَرِيض', pos: 'noun', features: 'indef.nom', root: 'م ر ض', gloss: 'the sick' },
            { surface: 'أَوْ', lemma: 'أَوْ', pos: 'conj', features: 'conj', gloss: 'or' },
            { surface: 'عَاجِزٌ', lemma: 'عَاجِز', pos: 'noun', features: 'indef.nom', root: 'ع ج ز', gloss: 'the incapacitated' },
          ],
        },
        {
          id: 'qs-v6-c23-004',
          ar: 'وَلا تَسْمَعُ فِي الْمَطَرِيَّةِ إِلَّا حَدِيثَ السِّحْرِ وَأَسْمَاءَ السَّحَرَةِ.',
          en: 'And you would hear nothing in al-Maṭariyyah but talk of magic and the names of sorcerers.',
          tokens: [
            { surface: 'وَلا', lemma: 'لَا', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'تَسْمَعُ', lemma: 'سَمِعَ', pos: 'verb', features: 'impf.2ms', gloss: 'you would hear' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'الْمَطَرِيَّةِ', lemma: 'مَطَرِيَّة', pos: 'proper', features: 'def.gen', gloss: 'al-Maṭariyyah' },
            { surface: 'إِلَّا', lemma: 'إِلَّا', pos: 'part', features: 'part', gloss: 'except' },
            { surface: 'حَدِيثَ', lemma: 'حَدِيث', pos: 'noun', features: 'acc.constr', gloss: 'the talk of' },
            { surface: 'السِّحْرِ', lemma: 'سِحْر', pos: 'noun', features: 'def.gen', gloss: 'magic' },
            { surface: 'وَأَسْمَاءَ', lemma: 'اِسْم', pos: 'noun', features: 'conj+acc.constr.pl', gloss: 'and the names of' },
            { surface: 'السَّحَرَةِ', lemma: 'سَاحِر', pos: 'noun', features: 'def.gen.pl', gloss: 'the sorcerers' },
          ],
        },
        {
          id: 'qs-v6-c23-005',
          ar: 'هَلْ جَاءَ سَاحِرُ أَسْوَانَ الْأَكْبَرُ أَيْضاً؟',
          en: 'Has the greatest sorcerer of Aswan come too?',
          tokens: [
            { surface: 'هَلْ', lemma: 'هَلْ', pos: 'part', features: 'part', gloss: '(question)' },
            { surface: 'جَاءَ', lemma: 'جَاءَ', pos: 'verb', features: 'perf.3ms', gloss: 'has come' },
            { surface: 'سَاحِرُ', lemma: 'سَاحِر', pos: 'noun', features: 'nom.constr', gloss: 'the sorcerer of' },
            { surface: 'أَسْوَانَ', lemma: 'أَسْوَان', pos: 'proper', features: 'gen', gloss: 'Aswan' },
            { surface: 'الْأَكْبَرُ', lemma: 'أَكْبَر', pos: 'adj', features: 'def.nom', gloss: 'the greatest' },
            { surface: 'أَيْضاً', lemma: 'أَيْضاً', pos: 'adv', features: 'adv', gloss: 'too' },
          ],
        },
        {
          id: 'qs-v6-c23-006',
          ar: 'نَعَمْ وَسَاحِرُ الْأُقْصُرِ وَسَاحِرُ الْجِيزَةِ الشَّهِيرُ!',
          en: 'Yes, and the sorcerer of Luxor, and the famous sorcerer of Giza!',
          tokens: [
            { surface: 'نَعَمْ', lemma: 'نَعَمْ', pos: 'part', features: 'part', gloss: 'yes' },
            { surface: 'وَسَاحِرُ', lemma: 'سَاحِر', pos: 'noun', features: 'conj+nom.constr', gloss: 'and the sorcerer of' },
            { surface: 'الْأُقْصُرِ', lemma: 'أُقْصُر', pos: 'proper', features: 'def.gen', gloss: 'Luxor' },
            { surface: 'وَسَاحِرُ', lemma: 'سَاحِر', pos: 'noun', features: 'conj+nom.constr', gloss: 'and the sorcerer of' },
            { surface: 'الْجِيزَةِ', lemma: 'جِيزَة', pos: 'proper', features: 'def.gen', gloss: 'Giza' },
            { surface: 'الشَّهِيرُ', lemma: 'شَهِير', pos: 'adj', features: 'def.nom', root: 'ش ه ر', gloss: 'the famous' },
          ],
        },
      ],
      checks: [
        {
          q: 'كَيْفَ كَانَ حَالُ النَّاسِ فِي طَرِيقِهِمْ إِلَى الْمِيدَانِ؟',
          options: ['خَرَجُوا مِنْ بُيُوتِهِمْ أَفْوَاجاً وَلَمْ يَبْقَ فِي الْبَيْتِ إِلَّا مَرِيضٌ أَوْ عَاجِزٌ', 'بَقِيَ أَكْثَرُهُمْ فِي بُيُوتِهِمْ', 'ذَهَبَ الرِّجَالُ فَقَطْ دُونَ النِّسَاءِ وَالْأَطْفَالِ'],
          answer: 0,
          qEn: 'What were the people like on their way to the arena?',
          optionsEn: ['They left their houses in troops, and only the sick or incapacitated stayed home', 'Most of them stayed home', 'Only the men went, without the women and children'],
        },
      ],
    },
    {
      lines: true,
      en: '"What do you think, my brother -- who will win?" "Egypt has thrown in her own most precious children -- do you think anyone can defeat them? And how could Mūsā and his brother defeat them, and where did they even learn magic? He grew up in the king\'s palace, then left Egypt afraid and watchful, and was in Madyan for years. So where did they learn magic? In Egypt? No! In Madyan? We never heard there was such an art there!"',
      sentences: [
        {
          id: 'qs-v6-c23-007',
          ar: 'مَاذَا تَرَى يَا أَخِي مَنْ يَغْلِبُ؟',
          en: 'What do you think, my brother -- who will win?',
          tokens: [
            { surface: 'مَاذَا', lemma: 'مَاذَا', pos: 'part', features: 'part', gloss: 'what' },
            { surface: 'تَرَى', lemma: 'رَأَى', pos: 'verb', features: 'impf.2ms', root: 'ر أ ي', gloss: 'do you think' },
            { surface: 'يَا', lemma: 'يَا', pos: 'part', features: 'part', gloss: 'O' },
            { surface: 'أَخِي', lemma: 'أَخ', pos: 'noun', features: 'nom+1s', gloss: 'my brother' },
            { surface: 'مَنْ', lemma: 'مَنْ', pos: 'rel', features: 'rel', gloss: 'who' },
            { surface: 'يَغْلِبُ', lemma: 'غَلَبَ', pos: 'verb', features: 'impf.3ms', gloss: 'will win' },
          ],
        },
        {
          id: 'qs-v6-c23-008',
          ar: 'إِنَّ مِصْرَ قَدْ أَلْقَتْ أَفْلاذَ كَبِدِهَا تَرَى يَغْلِبُهُمْ أَحَدٌ!',
          en: 'Egypt has thrown in her own most precious children -- do you think anyone can defeat them!',
          tokens: [
            { surface: 'إِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'مِصْرَ', lemma: 'مِصْر', pos: 'proper', features: 'acc', gloss: 'Egypt' },
            { surface: 'قَدْ', lemma: 'قَدْ', pos: 'part', features: 'part', gloss: 'indeed' },
            { surface: 'أَلْقَتْ', lemma: 'أَلْقَى', pos: 'verb', features: 'perf.3fs', gloss: 'has thrown' },
            { surface: 'أَفْلاذَ', lemma: 'أَفْلَاذ', pos: 'noun', features: 'acc.constr', root: 'ف ل ذ', gloss: 'the fragments of' },
            { surface: 'كَبِدِهَا', lemma: 'كَبِد', pos: 'noun', features: 'gen+3fs', root: 'ك ب د', gloss: 'her liver (i.e. her own precious children)' },
            { surface: 'تَرَى', lemma: 'رَأَى', pos: 'verb', features: 'impf.2ms', root: 'ر أ ي', gloss: 'do you think' },
            { surface: 'يَغْلِبُهُمْ', lemma: 'غَلَبَ', pos: 'verb', features: 'impf.3ms+3mp', gloss: 'can defeat them' },
            { surface: 'أَحَدٌ', lemma: 'أَحَد', pos: 'noun', features: 'indef.nom', gloss: 'anyone' },
          ],
        },
        {
          id: 'qs-v6-c23-009',
          ar: 'وَكَيْفَ يَغْلِبُهُمْ مُوسَى وَأَخُوهُ وَأَيْنَ تَعَلَّمَا السِّحْرَ؟',
          en: 'And how could Mūsā and his brother defeat them, and where did they even learn magic?',
          tokens: [
            { surface: 'وَكَيْفَ', lemma: 'كَيْفَ', pos: 'adv', features: 'conj+adv', gloss: 'and how' },
            { surface: 'يَغْلِبُهُمْ', lemma: 'غَلَبَ', pos: 'verb', features: 'impf.3ms+3mp', gloss: 'could defeat them' },
            { surface: 'مُوسَى', lemma: 'مُوسَى', pos: 'proper', features: 'nom', gloss: 'Mūsā' },
            { surface: 'وَأَخُوهُ', lemma: 'أَخ', pos: 'noun', features: 'conj+nom+3ms', gloss: 'and his brother' },
            { surface: 'وَأَيْنَ', lemma: 'أَيْنَ', pos: 'adv', features: 'conj+adv', gloss: 'and where' },
            { surface: 'تَعَلَّمَا', lemma: 'تَعَلَّمَ', pos: 'verb', features: 'perf.3md', gloss: 'to learn; did they two learn' },
            { surface: 'السِّحْرَ', lemma: 'سِحْر', pos: 'noun', features: 'def.acc', gloss: 'magic' },
          ],
        },
        {
          id: 'qs-v6-c23-010',
          ar: 'نَشَآ فِي قَصْرِ الْمَلِكِ ثُمَّ خَرَجَ مِنْ مِصْرَ خَائِفاً يَتَرَقَّبُ وَكَانَ فِي مَدْيَنَ سِنِينَ.',
          en: "He grew up in the king's palace, then left Egypt afraid and watchful, and was in Madyan for years.",
          tokens: [
            { surface: 'نَشَآ', lemma: 'نَشَأَ', pos: 'verb', features: 'perf.3ms', gloss: 'to grow up; grew up' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'قَصْرِ', lemma: 'قَصْر', pos: 'noun', features: 'constr.gen', gloss: 'the palace of' },
            { surface: 'الْمَلِكِ', lemma: 'مَلِك', pos: 'noun', features: 'def.gen', gloss: 'the king' },
            { surface: 'ثُمَّ', lemma: 'ثُمَّ', pos: 'conj', features: 'conj', gloss: 'then' },
            { surface: 'خَرَجَ', lemma: 'خَرَجَ', pos: 'verb', features: 'perf.3ms', gloss: 'left' },
            { surface: 'مِنْ', lemma: 'مِنْ', pos: 'prep', features: 'prep', gloss: 'from' },
            { surface: 'مِصْرَ', lemma: 'مِصْر', pos: 'proper', features: 'gen', gloss: 'Egypt' },
            { surface: 'خَائِفاً', lemma: 'خَافَ', pos: 'adj', features: 'indef.acc', gloss: 'afraid' },
            { surface: 'يَتَرَقَّبُ', lemma: 'تَرَقَّبَ', pos: 'verb', features: 'impf.3ms', gloss: 'watchful' },
            { surface: 'وَكَانَ', lemma: 'كَانَ', pos: 'verb', features: 'conj+perf.3ms', root: 'ك و ن', gloss: 'to be; and was' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'مَدْيَنَ', lemma: 'مَدْيَن', pos: 'proper', features: 'gen', gloss: 'Madyan' },
            { surface: 'سِنِينَ', lemma: 'سَنَة', pos: 'noun', features: 'indef.acc.pl', gloss: 'for years' },
          ],
        },
        {
          id: 'qs-v6-c23-011',
          ar: 'فَأَيْنَ تَعَلَّمَا السِّحْرَ؟',
          en: 'So where did they learn magic?',
          tokens: [
            { surface: 'فَأَيْنَ', lemma: 'أَيْنَ', pos: 'adv', features: 'conj+adv', gloss: 'so where' },
            { surface: 'تَعَلَّمَا', lemma: 'تَعَلَّمَ', pos: 'verb', features: 'perf.3md', gloss: 'did they two learn' },
            { surface: 'السِّحْرَ', lemma: 'سِحْر', pos: 'noun', features: 'def.acc', gloss: 'magic' },
          ],
        },
        {
          id: 'qs-v6-c23-012',
          ar: 'أَفِي مِصْرَ؟ لَا!',
          en: 'In Egypt? No!',
          tokens: [
            { surface: 'أَفِي', lemma: 'فِي', pos: 'prep', features: 'part+prep', gloss: 'in?' },
            { surface: 'مِصْرَ', lemma: 'مِصْر', pos: 'proper', features: 'gen', gloss: 'Egypt' },
            { surface: 'لَا', lemma: 'لَا', pos: 'part', features: 'neg', gloss: 'no' },
          ],
        },
        {
          id: 'qs-v6-c23-013',
          ar: 'أَفِي مَدْيَنَ؟ مَا سَمِعْنَا أَنَّ هُنَالِكَ فَنّاً!',
          en: 'In Madyan? We never heard there was such an art there!',
          tokens: [
            { surface: 'أَفِي', lemma: 'فِي', pos: 'prep', features: 'part+prep', gloss: 'in?' },
            { surface: 'مَدْيَنَ', lemma: 'مَدْيَن', pos: 'proper', features: 'gen', gloss: 'Madyan' },
            { surface: 'مَا', lemma: 'مَا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'سَمِعْنَا', lemma: 'سَمِعَ', pos: 'verb', features: 'perf.1p', gloss: 'we heard' },
            { surface: 'أَنَّ', lemma: 'أَنَّ', pos: 'part', features: 'part', gloss: 'that' },
            { surface: 'هُنَالِكَ', lemma: 'هُنَالِكَ', pos: 'adv', features: 'adv', gloss: 'there' },
            { surface: 'فَنّاً', lemma: 'فَنّ', pos: 'noun', features: 'indef.acc', root: 'ف ن ن', gloss: 'such an art' },
          ],
        },
      ],
      checks: [
        {
          q: 'مَا الَّذِي شَكَّكَ النَّاسَ فِي قُدْرَةِ مُوسَى عَلَى مُوَاجَهَةِ السَّحَرَةِ؟',
          options: ['أَنَّهُ لَمْ يُعْرَفْ أَنَّهُ تَعَلَّمَ السِّحْرَ لَا فِي مِصْرَ وَلَا فِي مَدْيَنَ', 'أَنَّهُ كَانَ صَغِيرَ السِّنِّ', 'أَنَّهُ لَمْ يَكُنْ مَعَهُ أَحَدٌ يُسَانِدُهُ'],
          answer: 0,
          qEn: "What made people doubt Mūsā's ability to face the sorcerers?",
          optionsEn: ['No one knew him to have learned magic, neither in Egypt nor in Madyan', 'He was too young', 'He had no one to support him'],
        },
      ],
    },
    {
      en: 'The Children of Israel came, caught between despair and hope -- and despair, perhaps, was greater. "May Allah have mercy on the son of ʿImrān! May Allah grant victory to the Children of Israel." The sorcerers came, striding forward in their vanity and pride. They came out in colored garments, and came out carrying their staffs and ropes. They came out laughing and exulting: "Today is the day of art! Today the king shall see our handiwork, today the people shall see our excellence!"',
      sentences: [
        {
          id: 'qs-v6-c23-014',
          ar: 'وَجَاءَ بَنُو إِسْرَائِيلَ وَهُمْ بَيْنَ يَأْسٍ وَرَجَاء، وَلَعَلَّ الْيَأْسَ أَغْلَبُ، اللَّهُ يَرْحَمُ ابْنَ عِمْرَانَ! اللَّهُ يَنْصُرُ بَنِي إِسْرَائِيلَ.',
          en: 'The Children of Israel came, caught between despair and hope -- and despair, perhaps, was greater. "May Allah have mercy on the son of ʿImrān! May Allah grant victory to the Children of Israel."',
          tokens: [
            { surface: 'وَجَاءَ', lemma: 'جَاءَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'came' },
            { surface: 'بَنُو', lemma: 'اِبْن', pos: 'noun', features: 'pl.constr.nom', root: 'ب ن و', gloss: 'the children of' },
            { surface: 'إِسْرَائِيلَ', lemma: 'إِسْرَائِيل', pos: 'proper', features: 'gen', gloss: 'Israel' },
            { surface: 'وَهُمْ', lemma: 'هُمْ', pos: 'noun', features: 'conj+3mp', gloss: 'while they' },
            { surface: 'بَيْنَ', lemma: 'بَيْنَ', pos: 'prep', features: 'prep', gloss: 'between' },
            { surface: 'يَأْسٍ', lemma: 'يَأْس', pos: 'noun', features: 'indef.gen', gloss: 'despair' },
            { surface: 'وَرَجَاء', lemma: 'رَجَاء', pos: 'noun', features: 'conj+indef.gen', gloss: 'and hope' },
            { surface: 'وَلَعَلَّ', lemma: 'لَعَلَّ', pos: 'part', features: 'conj+part', gloss: 'and perhaps' },
            { surface: 'الْيَأْسَ', lemma: 'يَأْس', pos: 'noun', features: 'def.acc', gloss: 'the despair' },
            { surface: 'أَغْلَبُ', lemma: 'أَغْلَب', pos: 'adj', features: 'nom', root: 'غ ل ب', gloss: 'was greater' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'يَرْحَمُ', lemma: 'رَحِمَ', pos: 'verb', features: 'impf.3ms', gloss: 'may have mercy on' },
            { surface: 'ابْنَ', lemma: 'اِبْن', pos: 'noun', features: 'acc.constr', gloss: 'the son of' },
            { surface: 'عِمْرَانَ', lemma: 'عِمْرَان', pos: 'proper', features: 'gen', gloss: 'ʿImrān' },
            { surface: 'اللَّهُ', lemma: 'اللَّه', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'يَنْصُرُ', lemma: 'نَصَرَ', pos: 'verb', features: 'impf.3ms', gloss: 'may grant victory to' },
            { surface: 'بَنِي', lemma: 'اِبْن', pos: 'noun', features: 'pl.constr.acc', root: 'ب ن و', gloss: 'the children of' },
            { surface: 'إِسْرَائِيلَ', lemma: 'إِسْرَائِيل', pos: 'proper', features: 'gen', gloss: 'Israel' },
          ],
        },
        {
          id: 'qs-v6-c23-015',
          ar: 'وَجَاءَ السَّحَرَةُ وَأَقْبَلُوا بِخُيَلائِهِمْ وَفَخْرِهِمْ.',
          en: 'The sorcerers came, striding forward in their vanity and pride.',
          tokens: [
            { surface: 'وَجَاءَ', lemma: 'جَاءَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'and came' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'وَأَقْبَلُوا', lemma: 'أَقْبَلَ', pos: 'verb', features: 'conj+perf.3mp', gloss: 'to stride forward; and strode forward' },
            { surface: 'بِخُيَلائِهِمْ', lemma: 'خُيَلَاء', pos: 'noun', features: 'prep+gen+3mp', root: 'خ ي ل', gloss: 'in their vanity' },
            { surface: 'وَفَخْرِهِمْ', lemma: 'فَخْر', pos: 'noun', features: 'conj+gen+3mp', root: 'ف خ ر', gloss: 'and their pride' },
          ],
        },
        {
          id: 'qs-v6-c23-016',
          ar: 'وَخَرَجُوا فِي مَلابِسَ مُلَوَّنَةٍ وَخَرَجُوا يَحْمِلُونَ الْعِصِيَّ وَالْحِبَالَ.',
          en: 'They came out in colored garments, and came out carrying their staffs and ropes.',
          tokens: [
            { surface: 'وَخَرَجُوا', lemma: 'خَرَجَ', pos: 'verb', features: 'conj+perf.3mp', gloss: 'came out' },
            { surface: 'فِي', lemma: 'فِي', pos: 'prep', features: 'prep', gloss: 'in' },
            { surface: 'مَلابِسَ', lemma: 'مَلَابِس', pos: 'noun', features: 'indef.gen.pl', root: 'ل ب س', gloss: 'garments' },
            { surface: 'مُلَوَّنَةٍ', lemma: 'مُلَوَّن', pos: 'adj', features: 'indef.gen.f', root: 'ل و ن', gloss: 'colored' },
            { surface: 'وَخَرَجُوا', lemma: 'خَرَجَ', pos: 'verb', features: 'conj+perf.3mp', gloss: 'and came out' },
            { surface: 'يَحْمِلُونَ', lemma: 'حَمَلَ', pos: 'verb', features: 'impf.3mp', gloss: 'carrying' },
            { surface: 'الْعِصِيَّ', lemma: 'عَصًا', pos: 'noun', features: 'def.acc.pl', gloss: 'the staffs' },
            { surface: 'وَالْحِبَالَ', lemma: 'حِبَال', pos: 'noun', features: 'conj+def.acc', root: 'ح ب ل', gloss: 'and the ropes' },
          ],
        },
        {
          id: 'qs-v6-c23-017',
          ar: 'وَخَرَجُوا يَضْحَكُونَ وَيَمْرَحُونَ، الْيَوْمَ يَوْمُ الْفَنِّ!',
          en: 'They came out laughing and exulting: "Today is the day of art!"',
          tokens: [
            { surface: 'وَخَرَجُوا', lemma: 'خَرَجَ', pos: 'verb', features: 'conj+perf.3mp', gloss: 'and came out' },
            { surface: 'يَضْحَكُونَ', lemma: 'ضَحِكَ', pos: 'verb', features: 'impf.3mp', gloss: 'laughing' },
            { surface: 'وَيَمْرَحُونَ', lemma: 'مَرِحَ', pos: 'verb', features: 'conj+impf.3mp', root: 'م ر ح', gloss: 'to exult; and exulting' },
            { surface: 'الْيَوْمَ', lemma: 'يَوْم', pos: 'noun', features: 'def.acc', gloss: 'today' },
            { surface: 'يَوْمُ', lemma: 'يَوْم', pos: 'noun', features: 'nom.constr', gloss: 'is the day of' },
            { surface: 'الْفَنِّ', lemma: 'فَنّ', pos: 'noun', features: 'def.gen', root: 'ف ن ن', gloss: 'art' },
          ],
        },
        {
          id: 'qs-v6-c23-018',
          ar: 'الْيَوْمَ يَرَى الْمَلِكُ صَنِيعَنَا، الْيَوْمَ يَرَى الْقَوْمُ فَضْلَنَا!',
          en: 'Today the king shall see our handiwork, today the people shall see our excellence!',
          tokens: [
            { surface: 'الْيَوْمَ', lemma: 'يَوْم', pos: 'noun', features: 'def.acc', gloss: 'today' },
            { surface: 'يَرَى', lemma: 'رَأَى', pos: 'verb', features: 'impf.3ms', root: 'ر أ ي', gloss: 'shall see' },
            { surface: 'الْمَلِكُ', lemma: 'مَلِك', pos: 'noun', features: 'def.nom', gloss: 'the king' },
            { surface: 'صَنِيعَنَا', lemma: 'صَنِيع', pos: 'noun', features: 'acc+1p', root: 'ص ن ع', gloss: 'our handiwork' },
            { surface: 'الْيَوْمَ', lemma: 'يَوْم', pos: 'noun', features: 'def.acc', gloss: 'today' },
            { surface: 'يَرَى', lemma: 'رَأَى', pos: 'verb', features: 'impf.3ms', root: 'ر أ ي', gloss: 'shall see' },
            { surface: 'الْقَوْمُ', lemma: 'قَوْم', pos: 'noun', features: 'def.nom', gloss: 'the people' },
            { surface: 'فَضْلَنَا', lemma: 'فَضْل', pos: 'noun', features: 'acc+1p', gloss: 'our excellence' },
          ],
        },
      ],
      checks: [
        {
          q: 'كَيْفَ كَانَ شُعُورُ بَنِي إِسْرَائِيلَ مُقَارَنَةً بِالسَّحَرَةِ وَهُمْ ذَاهِبُونَ إِلَى الْمِيدَانِ؟',
          options: ['بَنُو إِسْرَائِيلَ بَيْنَ يَأْسٍ وَرَجَاءٍ، وَالسَّحَرَةُ بِخُيَلَاءَ وَفَخْرٍ وَضَحِكٍ', 'كِلَاهُمَا كَانَ وَاثِقاً مِنَ النَّصْرِ', 'كِلَاهُمَا كَانَ خَائِفاً قَلِقاً'],
          answer: 0,
          qEn: 'How did the Children of Israel feel compared to the sorcerers on their way to the arena?',
          optionsEn: ['Banū Isrāʾīl were caught between despair and hope, while the sorcerers were full of vanity, pride, and laughter', 'Both were confident of victory', 'Both were fearful and anxious'],
        },
      ],
    },
    {
      en: '"When the sorcerers came, they said to Pharaoh: Is there truly a reward for us if we are the victors?" "He said: Yes, and you will surely be among those brought near [to me]." And this is the reward of kings! And this is the gift of kings! And this is what deceives men! And this is what catches heroes! And the sorcerers rejoiced at Pharaoh\'s promises.',
      sentences: [
        {
          id: 'qs-v6-c23-019',
          ar: 'فَلَمَّا جَاءَ السَّحَرَةُ قَالُوا لِفِرْعَوْنَ أَئِنَّ لَنَا لَأَجْرًا إِن كُنَّآ نَحْنُ الْغَالِبِينَ﴾.',
          en: 'When the sorcerers came, they said to Pharaoh: "Is there truly a reward for us if we are the victors?"',
          tokens: [
            { surface: 'فَلَمَّا', lemma: 'لَمَّا', pos: 'adv', features: 'conj+adv', gloss: 'so when' },
            { surface: 'جَاءَ', lemma: 'جَاءَ', pos: 'verb', features: 'perf.3ms', gloss: 'came' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'قَالُوا', lemma: 'قَالَ', pos: 'verb', features: 'perf.3mp', root: 'ق و ل', gloss: 'said' },
            { surface: 'لِفِرْعَوْنَ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'prep+gen', gloss: 'to Pharaoh' },
            { surface: 'أَئِنَّ', lemma: 'إِنَّ', pos: 'part', features: 'part+part', gloss: 'is there truly' },
            { surface: 'لَنَا', lemma: 'لِ', pos: 'prep', features: 'prep+1p', gloss: 'for us' },
            { surface: 'لَأَجْرًا', lemma: 'أَجْر', pos: 'noun', features: 'part+indef.acc', gloss: 'indeed a reward' },
            { surface: 'إِن', lemma: 'إِنْ', pos: 'part', features: 'part', gloss: 'if' },
            { surface: 'كُنَّآ', lemma: 'كَانَ', pos: 'verb', features: 'perf.1p', root: 'ك و ن', gloss: 'we are' },
            { surface: 'نَحْنُ', lemma: 'نَحْنُ', pos: 'noun', features: '1p', gloss: 'we' },
            { surface: 'الْغَالِبِينَ', lemma: 'غَالِب', pos: 'noun', features: 'def.acc.pl', gloss: 'the victors' },
          ],
        },
        {
          id: 'qs-v6-c23-020',
          ar: '﴿قَالَ نَعَمْ وَإِنَّكُمْ إِذاً لَّمِنَ الْمُقَرَّبِينَ﴾.',
          en: 'He said: "Yes, and you will surely be among those brought near [to me]."',
          tokens: [
            { surface: 'قَالَ', lemma: 'قَالَ', pos: 'verb', features: 'perf.3ms', root: 'ق و ل', gloss: 'said' },
            { surface: 'نَعَمْ', lemma: 'نَعَمْ', pos: 'part', features: 'part', gloss: 'yes' },
            { surface: 'وَإِنَّكُمْ', lemma: 'إِنَّ', pos: 'part', features: 'conj+part+2mp', gloss: 'and indeed you' },
            { surface: 'إِذاً', lemma: 'إِذاً', pos: 'adv', features: 'adv', gloss: 'then' },
            { surface: 'لَّمِنَ', lemma: 'مِنْ', pos: 'prep', features: 'part+prep', gloss: 'will surely be among' },
            { surface: 'الْمُقَرَّبِينَ', lemma: 'مُقَرَّب', pos: 'noun', features: 'def.gen.pl', root: 'ق ر ب', gloss: 'those brought near' },
          ],
        },
        {
          id: 'qs-v6-c23-021',
          ar: 'وَهَذِهِ هِيَ جَائِزَةُ الْمُلُوكِ! وَهَذَا عَطَاءُ الْمُلُوكِ!',
          en: 'And this is the reward of kings! And this is the gift of kings!',
          tokens: [
            { surface: 'وَهَذِهِ', lemma: 'هَذِهِ', pos: 'dem', features: 'conj+dem.f', gloss: 'and this' },
            { surface: 'هِيَ', lemma: 'هِيَ', pos: 'noun', features: '3fs', gloss: 'is' },
            { surface: 'جَائِزَةُ', lemma: 'جَائِزَة', pos: 'noun', features: 'nom.constr', gloss: 'the reward of' },
            { surface: 'الْمُلُوكِ', lemma: 'مَلِك', pos: 'noun', features: 'def.gen.pl', gloss: 'kings' },
            { surface: 'وَهَذَا', lemma: 'هَذَا', pos: 'dem', features: 'conj+dem', gloss: 'and this' },
            { surface: 'عَطَاءُ', lemma: 'عَطَاء', pos: 'noun', features: 'nom.constr', root: 'ع ط و', gloss: 'is the gift of' },
            { surface: 'الْمُلُوكِ', lemma: 'مَلِك', pos: 'noun', features: 'def.gen.pl', gloss: 'kings' },
          ],
        },
        {
          id: 'qs-v6-c23-022',
          ar: 'وَهَذَا الَّذِي يُخْدَعُ بِهِ الرِّجَالُ! وَهَذا الَّذِي يُصَادُ بِهِ الْأَبْطَالُ!',
          en: 'And this is what deceives men! And this is what catches heroes!',
          tokens: [
            { surface: 'وَهَذَا', lemma: 'هَذَا', pos: 'dem', features: 'conj+dem', gloss: 'and this' },
            { surface: 'الَّذِي', lemma: 'الَّذِي', pos: 'rel', features: 'rel', gloss: 'is what' },
            { surface: 'يُخْدَعُ', lemma: 'خَدَعَ', pos: 'verb', features: 'pass+impf.3ms', root: 'خ د ع', gloss: 'to deceive; deceives' },
            { surface: 'بِهِ', lemma: 'بِ', pos: 'prep', features: 'prep+3ms', gloss: 'by it' },
            { surface: 'الرِّجَالُ', lemma: 'رَجُل', pos: 'noun', features: 'def.nom.pl', gloss: 'men' },
            { surface: 'وَهَذا', lemma: 'هَذَا', pos: 'dem', features: 'conj+dem', gloss: 'and this' },
            { surface: 'الَّذِي', lemma: 'الَّذِي', pos: 'rel', features: 'rel', gloss: 'is what' },
            { surface: 'يُصَادُ', lemma: 'صَادَ', pos: 'verb', features: 'pass+impf.3ms', root: 'ص ي د', gloss: 'to catch; catches' },
            { surface: 'بِهِ', lemma: 'بِ', pos: 'prep', features: 'prep+3ms', gloss: 'by it' },
            { surface: 'الْأَبْطَالُ', lemma: 'بَطَل', pos: 'noun', features: 'def.nom.pl', root: 'ب ط ل', gloss: 'heroes' },
          ],
        },
        {
          id: 'qs-v6-c23-023',
          ar: 'وَفَرِحَ السَّحَرَةُ بِمَوَاعِيدِ فِرْعَوْنَ.',
          en: "And the sorcerers rejoiced at Pharaoh's promises.",
          tokens: [
            { surface: 'وَفَرِحَ', lemma: 'فَرِحَ', pos: 'verb', features: 'conj+perf.3ms', gloss: 'to rejoice; and rejoiced' },
            { surface: 'السَّحَرَةُ', lemma: 'سَاحِر', pos: 'noun', features: 'def.nom.pl', gloss: 'the sorcerers' },
            { surface: 'بِمَوَاعِيدِ', lemma: 'مَوْعِد', pos: 'noun', features: 'prep+gen.pl', root: 'و ع د', gloss: "at the promises of" },
            { surface: 'فِرْعَوْنَ', lemma: 'فِرْعَوْن', pos: 'proper', features: 'gen', gloss: "Pharaoh's" },
          ],
        },
      ],
      checks: [
        {
          q: 'مَاذَا طَلَبَ السَّحَرَةُ مِنْ فِرْعَوْنَ قَبْلَ الْمُبَارَزَةِ؟',
          options: ['أَجْراً وَأَنْ يَكُونُوا مِنَ الْمُقَرَّبِينَ إِذَا غَلَبُوا', 'أَنْ يُعْفِيَهُمْ مِنَ الضَّرِيبَةِ', 'أَنْ يَمْنَحَهُمْ أَرَاضِيَ زِرَاعِيَّةً'],
          answer: 0,
          qEn: 'What did the sorcerers ask Pharaoh for before the contest?',
          optionsEn: ['A reward, and to be among those brought near to him if they won', 'To be exempted from taxes', 'To be granted farmland'],
        },
      ],
    },
  ],
  workshop: {
    cloze: [
      {
        type: 'cloze',
        pre: 'وَلَمْ يَبْقَ فِي الْبَيْتِ إِلَّا',
        post: 'أَوْ عَاجِزٌ.',
        en: 'Nothing remained in any house except the sick or the incapacitated.',
        options: ['مَرِيضٌ', 'مَرِيضاً', 'مَرِيضٍ', 'الْمَرِيضُ'],
        answer: 0,
        rationales: [
          'Nominative, indefinite -- subject of the (elided) existential clause after إِلَّا, matching the taught pattern.',
          'Accusative -- wrong case; nothing here governs the accusative.',
          'Genitive -- wrong case; no preposition or إضافة governs this word.',
          'Definite -- wrong; an unspecified "some sick person" is meant, not a particular known one.',
        ],
      },
      {
        type: 'cloze',
        pre: 'قَالَ نَعَمْ وَإِنَّكُمْ إِذاً',
        post: 'الْمُقَرَّبِينَ.',
        en: 'He said: Yes, and you will surely be among those brought near.',
        options: ['لَّمِنَ', 'فَمِنَ', 'وَمِنَ', 'كَمِنَ'],
        answer: 0,
        rationales: [
          'لَ (emphatic) + مِنَ -- the emphatic لام reinforcing the promise, matching the taught pattern.',
          'فَ + مِنَ -- wrong particle for this position.',
          'وَ + مِنَ -- wrong; no coordination is needed here.',
          '"like" + مِنَ -- not a real combination; wrong meaning.',
        ],
      },
    ],
    shift: [
      {
        type: 'shift',
        base: 'يَخْرُجُ الرَّجُلُ إِلَى الْمِيدَانِ',
        pre: '',
        post: 'إِلَى الْمِيدَانِ',
        targetPerson: 'هُنَّ',
        targetEn: 'they (f.)',
        options: ['يَخْرُجْنَ', 'يَخْرُجُ', 'تَخْرُجُ', 'نَخْرُجُ'],
        answer: 0,
        rationales: [
          '3rd feminine plural -- matches هُنَّ.',
          '3rd masculine singular -- he, the form already given.',
          '3rd feminine singular / 2nd masculine singular -- wrong number.',
          '1st plural -- we.',
        ],
      },
      {
        type: 'shift',
        base: 'يَخْرُجُ الرَّجُلُ إِلَى الْمِيدَانِ',
        pre: '',
        post: 'إِلَى الْمِيدَانِ',
        targetPerson: 'أَنْتُمْ',
        targetEn: 'you (m. pl.)',
        options: ['تَخْرُجُونَ', 'يَخْرُجُ', 'تَخْرُجُ', 'نَخْرُجُ'],
        answer: 0,
        rationales: [
          '2nd masculine plural -- matches أَنْتُمْ.',
          '3rd masculine singular -- he, the form already given.',
          '2nd masculine singular -- you (m. sg.).',
          '1st plural -- we.',
        ],
      },
    ],
  },
};
