import { card as c, rows as r, part as p, visual as v, question as q, plan } from '../nahw-course/helpers.js';
const clarification = { line: 'clarification' };

export const plans = {
  'as-09/l3': plan(33, 'Rare, Rarer and Excluded Emphasis', [
    [c('Two environments for rare emphasis',0,1,2),c('Negative لا',3,4,5,6,7),c('Reinforcing ما without conditional إنْ',8,9,10)],
    [c('The reported ربما example',0,1,2,3)],
    [c('Rarer after لم or another conditional',0,1,2,5),c('Light نون at the end of a verse',r(3,0),p(4,0)),c('A conditional other than إمّا',r(3,1),p(4,1),clarification)],
    [c('Exclusion requires the complete test',0,1,2,4),c('A negative oath-answer',r(3,0),5),c('Swearing at the present moment',r(3,1),6),c('A separator after لام',r(3,2),7),c('An ordinary unmarked assertion',8)],
  ], [
    ['Rare','Negative لا; reinforcing ما without preceding conditional إنْ.'],
    ['Rarer','لم; a conditional other than إمّا, in condition or answer.'],
    ['Excluded','No obligatory conditions and no other licensed case.'],
    ['Remember','Negative oath, present time and separation from لام require care.'],
  ], {copy:{
    '0:0':'The fourth state includes two non-request environments.',
    '0:2':'Rare after negative لا or reinforcing ما not preceded by conditional إنْ. With إنْ, conditional إمّا belongs to the near-obligatory state instead.',
    '0:4':'“Beware a trial not confined to wrongdoers among you.” The source reads لا as negative; other analyses exist.',
    '0:5':'Why نون here?',
    '0:7':'Similarity to prohibitive لا explains rare emphasis here. It does not license نون after every negative.',
    '0:8':'The second witness has reinforcing ما without conditional إنْ.',
    '0:10':'“When a chief among them dies, his son steals; from a thorn-tree grow its shoots.” ما does not change the basic proposition, but can reinforce it. ينبتنّ illustrates the rare emphatic ending after this ما.',
    '1:0':'The source’s category includes ما after ربّ.',
    '1:2':'Jadhīma al-Abrash says: “Many a time I stood on a high place, north winds lifting my robe.” ترفعنْ has light emphatic نون in the ربما construction. The past setting makes this a disputed poetic usage, not a reason to discard the general future-reference rule.',
    '1:3':'The source places it under قليل; some restrict such usage to poetic necessity.',
    '2:0':'The fifth state has two rarer environments.',
    '2:2':'After لم, or a conditional expression other than إمّا. In the latter, the emphasised verb may be the condition or its answer.',
    '2:5':'Contrast near-obligatory emphasis after إمّا with rare emphasis after other conditional expressions.',
    '2:clarification':'Conditional إنْ reinforced by ما becomes إمّا. The reinforcing particle helps explain the near-obligatory ending there. Without it, ordinary conditional emphasis is much rarer. ما is a particle here, not literally one written letter.',
    '3:0':'The sixth state excludes نون.',
    '3:2':'Both conditions matter: the obligatory oath conditions fail, and none of the other licensed cases applies. Mere failure of the obligatory test is insufficient.',
    '3:4':'The listed exclusions concern a negative oath-answer, present-time reference, or a separator between لام and the verb.',
    '3:5':'“By Allah, kindness between Allah and people does not go to waste.” The second witness means “By Allah, you will not cease remembering Yusuf”: لا before تفتؤ is understood. Expressed or implied negation has the same effect here.',
    '3:6':'The relevant reading is لَأُقْسِمُ, without the alif of لا, reported through Ibn Kathīr’s transmitters. In the source’s analysis, “I swear” is performed now, so no emphatic نون follows. Distinguish it from the familiar spelling لا أقسم.',
    '3:7':'“To Allah you will be gathered”: إلى الله separates لام from تحشرون. “Your Lord will surely give you, and you will be satisfied”: سوف separates لام from يعطيك. The latter is future despite excluding نون.',
    '3:8':'يذهب زيد is an ordinary assertion with none of the five preceding environments. Under the source’s rule, this context does not license emphatic نون.',
  },copyParts:{'2:4':[
    'The poet describes a mountain: the uninformed observer takes it for a turbaned old man on a chair. يعلمَا represents يعلمَنْ, with light نون replaced by alif at the line’s pause, as in ليكونًا.',
    'متى تجتهدنّ تنجح: “Whenever you strive, you succeed.” Here نون is on the condition. The source also records emphasis on the answer of a conditional other than إمّا.',
  ]},boxCopy:{'0:1':['قليل بعد لا النافية أو ما الزائدة.','ما لم تسبق بإنْ الشرطية.'],'0:3':['واتقوا فتنة لا تصيبنّ الذين ظلموا منكم خاصة [8:25].'],'0:6':['لا النافية تشبه أداة النهي صورة.'],'1:1':['ربّما أوفيت في عَلَمٍ','ترفعنْ ثوبي شمالاتُ'],'2:1':['أقلّ بعد لم، أو شرط غير إمّا.','قد يؤكّد الشرط أو الجزاء.'],'3:1':['انتفت شروط الواجب، ولم يكن مما سبق.']},
  tableCopy:{'2:3':{0:['بعد لم','يحسبه الجاهل ما لم يعلما ... شيخا على كرسيّه معمّما.'],1:['شرط غير إمّا','متى تجتهدنّ تنجح.']},'3:3':{0:['جواب قسم منفي','تالله لا يذهب العرف بين الله والناس؛ تالله تفتؤ تذكر يوسف [12:85].'],1:['حال','لَأُقْسِمُ بِيَوْمِ الْقِيَامَةِ [75:1], in the cited reading.'],2:['مفصول من اللام','ولئن متّم أو قتلتم لإلى الله تحشرون [3:158]؛ ولسوف يعطيك ربّك فترضى [93:5].']}},
  visuals:{'3:4':v('No licensing expression',['يَذْهَبُ زَيْدٌ','Zayd goes.'])},
  analysisPrompt:'Which condition excludes emphatic نون here?',analysisHint:'Check negation, present time and separation from لام.',
  analysisLabels:{'أن يكونَ في جَوابِ قَسَمٍ مَنْفِيٍّ، ولو كان النافي مُقَدَّرًا':'Negative oath-answer','أن يكونَ حالًا':'Present-time reference','أن يكونَ مَفْصُولًا من اللامِ':'Separator after لام'},
  analysisText:{'table-3-3':{'تاللهِ لا يَذْهَبُ العُرْفُ بينَ اللهِ والناسِ ؛ ﴿تَاللَّهِ تَفْتَؤُ تَذْكُرُ يُوسُفَ﴾ [يوسف: ٨٥] — أي: لا تَفْتَؤُ':'تاللهِ لا يَذْهَبُ العُرْفُ','كقراءةِ ابنِ كَثِيرٍ: ﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾ [القيامة]':'لَأُقْسِمُ بِيَوْمِ الْقِيَامَةِ','﴿وَلَئِنْ مُتُّمْ أَوْ قُتِلْتُمْ لَإِلَى اللَّهِ تُحْشَرُونَ﴾ [آل عمران: ١٥٨] ؛ ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى﴾ [الضحى: ٥]':'وَلَسَوْفَ يُعْطِيكَ رَبُّكَ'}},
  }),
  'as-09/l2': plan(32, 'Obligatory and Frequent Emphasis', [
    [c('Six contextual rulings',0,1,2),c('Time and construction both matter',3,4,5)],
    [{...c('Four conditions make emphasis obligatory',0,1,2,3,4,5,6),lists:[[3,4,5,6]]},c('Apply all four to an oath',7,clarification)],
    [c('Conditional إمّا makes emphasis near-obligatory',0,1,2,3),c('Fear or removal in the condition',r(4,0,1),p(5,0)),c('Seeing someone in the condition',r(4,2),p(5,1))],
    [c('Requests commonly take emphatic نون',0,1,2),c('Command and prohibition',r(3,0,1),4),c('A prayer for the people',r(3,2),5),c('An appeal for a promise',r(3,3),6),c('A wish and a question',r(3,4,5),7,8)],
  ], [
    ['Obligatory','Affirmative future oath-answer, directly after its لام.'],
    ['Near-obligatory','The condition after إمّا: إنْ + ما.'],
    ['Common','After request expressions: command, prohibition, prayer, appeal, wish or question.'],
    ['Context','Present-time reference excludes نون; future reference alone does not require it.'],
  ], {copy:{
    '0:0':'The imperfect has six rulings rather than one.',
    '0:2':'In order: obligatory, near-obligatory, common, rare, rarer, barred.',
    '0:3':'The imperfect form alone does not settle its time reference.',
    '0:5':'Explicit present-time reference excludes نون. Otherwise examine the whole construction. The six states are not simply degrees of certainty about the future: an oath with سوف can be clearly future yet exclude نون.',
    '1:0':'Four conditions must hold together.',
    '1:2':'Check each condition:',
    '1:3':'مثبت: affirmative.',
    '1:4':'مستقبل: future.',
    '1:5':'جواب قسم: oath-answer.',
    '1:6':'No separator after لام القسم.',
    '1:7':'وتالله لأكيدنّ أصنامكم [21:57]: “By Allah, I shall certainly plot against your idols.” أكيد is affirmative and future, answers تالله, and immediately follows لام. All four conditions require نون here.',
    '1:clarification':'For oath-answers, negation, present time or a separator changes this ruling. Lacking an oath does not universally bar نون: requests have their own rule. Do not treat every failure of the four-condition test as a ban in every construction.',
    '2:0':'The second state is close to obligatory.',
    '2:2':'The verb is the condition introduced by إمّا الشرطية.',
    '2:3':'Here إمّا combines conditional إنْ and reinforcing ما الزائدة. “Extra” describes its grammar, not a lack of function. This conditional إمّا is distinct from إمّا expressing alternatives.',
    '3:0':'The third state is frequent, rather than required.',
    '3:2':'The source lists six kinds of طلب. These include appeals and questions as well as direct commands.',
    '3:4':'ليقومنّ زيد: “Let Zayd stand.” ولا تحسبنّ الله غافلا عما يعمل الظالمون: “Do not think Allah unaware of what the wrongdoers do.” The first uses لام الأمر; the second prohibitive لا.',
    '3:5':'Khirniq, named in the source as بنت هفان, prays: “May my people not perish, who are poison to enemies and a scourge of slaughter-camels.” لا is used in supplication, not to forbid the people from something.',
    '3:6':'“Will you grant an unbroken promise, as I knew you in the days at Dhū Salam?” The source places this appeal under عرض. هلا can also urge strongly in other contexts. تَمُنِّنْ has the light emphatic nūn.',
    '3:7':'The wish asks that she see him when they meet, to know he is a man enamoured of her. The question asks whether he will praise another tribe after Kinda.',
    '3:8':'In these emphatic uses, the requested or questioned action has future reference. Questions in general are not always about the future.',
  },copyParts:{'2:5':[
    'تخافنّ: “if you fear treachery from a people”. نذهبنّ: “if We take you away”. Each emphasised verb is the condition immediately after إمّا.',
    'ترينّ: “if you see any human being, say: I have vowed a fast to the Most Merciful”. The condition is ترينّ; فقولي begins its answer.',
  ]},boxCopy:{'0:1':['واجب؛ قريب من الواجب؛ كثير.','قليل؛ أقلّ؛ ممتنع.'],'0:4':['المضارع للحال أو الاستقبال.','في الحال لا تدخله نون التوكيد.'],'1:1':['جواب القسم: مثبت مستقبل، متصل بلامه.'],'2:1':['إمّا الشرطية: إنْ مؤكّدة بما الزائدة.']},
  tableCopy:{'2:4':{0:['وإمّا تخافنّ من قوم خيانة','الأنفال 8:58'],1:['فإمّا نذهبنّ بك','الزخرف 43:41'],2:['فإمّا ترينّ من البشر أحدا فقولي إني نذرت للرحمن صوما','مريم 19:26']},'3:3':{0:['أمر','ليقومنّ زيد.'],1:['نهي','ولا تحسبنّ الله غافلا عما يعمل الظالمون [14:42].'],2:['دعاء','لا يبعدنْ قومي الذين هم ... سمّ العداة وآفة الجزر.'],3:['عرض','هلا تَمُنِّنْ بوعد غير مخلفة ... كما عهدتك في أيام ذي سلم.'],4:['تمنّ','فليتك يوم الملتقى ترينّني ... لكي تعلمي أنّي امرؤ بك هائم.'],5:['استفهام','أفبعد كندة تمدحنّ قبيلا.']}},
  visuals:{'1:1':v('Read the oath-answer',['لَأَكِيدَنَّ','Affirmative and future'])},
  analysisPrompt:'Identify the kind of request in each witness.',analysisHint:'Distinguish command, prohibition and prayer.',
  analysisLabels:{'أَمْر (بعد لامِ الأمرِ) — command (after لام الأمر)':'أمر','نَهْي — prohibition':'نهي','دُعاء — supplication':'دعاء'},
  analysisText:{'table-3-3':{'لِيَقُومَنَّ زَيْدٌ':'لِيَقُومَنَّ زَيْدٌ','﴿وَلَا تَحْسَبَنَّ اللَّهَ غَافِلًا عَمَّا يَعْمَلُ الظَّالِمُونَ﴾ [إبراهيم: ٤٢]':'وَلَا تَحْسَبَنَّ اللَّهَ غَافِلًا','لا يَبْعَدَنْ قَوْمِيَ الَّذِينَ هُمُ ... سَمُّ العُداةِ وآفَةُ الجُزُرِ — لخِرْنِقَ بنتِ هَفَّانَ':'لا يَبْعَدَنْ قَوْمِي'}},
  }),
  'as-09/l1': plan(31, 'Emphasis with Nūn and Other Means', [
    [c('Two forms of emphatic نون',0,1,2,3),c('Recognise both forms in a verse',r(4,0,1),5),c('The light نون when stopping',6,7,8)],
    [c('قد can emphasise a past assertion',0,1,2,r(3,0),p(4,0)),c('لام emphasises an imperfect assertion',r(3,1),p(4,1)),c('An oath can emphasise without نون',r(3,2),p(4,2),5,6,7)],
    [c('Emphasis and future reference',0,1,2),c('The regular past-form rule',3,4,5,clarification)],
    [c('A past-form prayer in poetry',0,1,2),c('A noun with نون in poetry',3,4,5),c('The command normally permits نون',6,7,8,9)],
  ], [
    ['نون','Heavy نّ or light نْ; both mark emphasis.'],
    ['Meaning','Emphasis and future reference in regular use.'],
    ['Past / command','Past excluded; command permitted. Poetic anomalies are separately recorded.'],
    ['Scope','قد، لام and oaths also emphasise; this chapter studies نون.'],
  ], {copy:{
    '0:0':'The seventh division asks whether نون التوكيد is attached.',
    '0:2':'مؤكد بالنون has emphatic nūn; غير مؤكد lacks that marker. Other kinds of نون are not at issue.',
    '0:3':'ثقيلة is doubled نّ; خفيفة is unvowelled نْ. Either qualifies.',
    '0:5':'“He will certainly be imprisoned and be among the humbled.” ليسجننّ has heavy nūn; ليكونًا represents light nūn. Without the emphatic construction: يُسجن، يكون.',
    '0:6':'The Quranic spelling ليكونًا needs care.',
    '0:8':'Underlying لَيَكُونَنْ has light نون التوكيد. After the preceding fatḥa, it becomes alif in pause. It is not noun tanwīn; in connection the emphatic nūn has its recitation rules.',
    '1:0':'Verbs can be emphasised by other means.',
    '1:2':'Three source examples show emphasis without نون.',
    '1:5':'All three examples express emphasis.',
    '1:7':'The rules that follow concern نون specifically.',
    '2:0':'Regular نون التوكيد combines two functions.',
    '2:2':'It strengthens the assertion or request and gives the action future reference.',
    '2:3':'Form matters too.',
    '2:5':'Past forms exclude نون under the regular rule. Yet a past form can refer to the future in prayer or condition. Future meaning alone does not license the ending.',
    '2:clarification':'Explicit present-time imperfects exclude نون. Other imperfect uses depend on their construction. The source treats poetic exceptions separately from the regular past-form rule.',
    '3:0':'The source records a poetic exception to the past-form rule.',
    '3:2':'“May your good fortune last, if you had shown mercy to a love-stricken man.” دامنّ is past in form but a prayer in meaning. Its request sense helps explain its exceptional treatment like a command: ضرورة شاذة, not a productive rule.',
    '3:3':'A second anomaly concerns a noun.',
    '3:5':'Ruʾba ibn al-ʿAjjāj’s line asks, “Are you going to say: bring the witnesses?” قائل is the active participle of قال; أ is interrogative. The attached emphatic nūn is exceptional on a noun.',
    '3:6':'A command seeks an action still to be performed.',
    '3:8':'اكتبنّ: do write, with heavy nūn. اجتهدنْ: do strive, with light nūn. The general rule permits emphasis on commands; permission is not an obligation.',
    '3:9':'Past and command have general rulings; the imperfect has six contextual states.',
  },copyParts:{'1:4':[
    'قد أفلح المؤمنون [23:1]: “The believers have indeed succeeded.” قد emphasises the assertion in this past-tense example.',
    'وإنّ ربّك ليحكم بينهم [16:124]: “Your Lord will surely judge between them.” The لام strengthens the imperfect assertion.',
    'والله لسوف أذهب: “By Allah, I shall surely go.” The oath reinforces the speaker’s commitment; the verb has no emphatic nūn.',
  ]},boxCopy:{'0:1':['مؤكّد بالنون، وغير مؤكّد بها.'],'0:7':['لَيَكُونَنْ؛ وفي الوقف: لَيَكُونَا.'],'1:1':['قد يكون التوكيد بغير النون.'],'1:6':['هذا الباب لتوكيد الفعل بالنون.'],'2:4':['الماضي لا يؤكّد بالنون في الاستعمال القياسي.'],'3:1':['دامَنَّ سعدُكِ لو رحمتِ متيّما','ضرورة شاذة سهّلها معنى الطلب.'],'3:4':['رؤبة بن العجاج:','أَقَائِلُنَّ أَحْضِرُوا الشُّهُودَا'],'3:7':['الأمر يجوز توكيده بالنون.','اُكْتُبَنَّ؛ اِجْتَهِدَنْ.']},
  tableCopy:{'0:4':{0:['مؤكّد','Heavy or light نون التوكيد.','ليسجننّ وليكونًا من الصاغرين [12:32].'],1:['غير مؤكد بالنون','No emphatic نون.','يُسجن؛ يكون.']},'1:3':{0:['قد','قد أفلح المؤمنون [23:1].'],1:['اللام','وإنّ ربّك ليحكم بينهم [16:124].'],2:['القسم','والله لسوف أذهب.']}},
  analysisPrompt:'Classify each group by whether emphatic نون is attached.',analysisHint:'Both heavy and light emphatic نون count.',
  analysisText:{'table-0-4':{'﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾ [يوسف: ٣٢]':'لَيُسْجَنَنَّ؛ لَيَكُونًا','يُسْجَنُ ، يَكُونُ':'يُسْجَنُ؛ يَكُونُ'}},
  }),
};
export const checks = {
  'as-09/l3':[
    q('How does the source explain rare نون after negative لا?', ['It resembles prohibitive لا in form.','Every negative لا is a request.','The verb is past.','The construction has no recorded basis.'],'This is the source’s negative reading of the witness.'),
    q('How is ترفعنْ in ربما أوفيت... classified by the source?', ['Common.','Excluded.','Rare: ما after ربّ is included.','Obligatory.'],'The source records this disputed poetic use.'),
    q('What explains يعلمَا at the end of the verse?', ['Light نون becomes alif in pause.','نون is simply deleted.','There was no نون.','نون becomes tanwīn.'],'Compare ليكونًا.'),
    q('Why is نون excluded in ولسوف يعطيك ربك?', ['No oath is possible.','سوف separates لام from the verb.','The verb is negated.','The verb refers to now.'],'Future reference alone does not require نون.'),
  ],
  'as-09/l2':[
    q('Context fixes an imperfect to the present. What follows?', ['نون is common.','نون is rare.','نون is excluded.','نون is required.'],'Emphatic نون requires future reference.'),
    q('An oath-answer is future but negated. Is emphatic نون obligatory?', ['No: the affirmative condition fails.','Yes.','It falls under common request usage.','It falls under rare usage.'],'All four obligatory conditions must hold.'),
    q('What forms conditional إمّا?', ['إنْ + reinforcing ما.','إنّ + negative ما.','أمّا with doubled م.','One indivisible particle.'],'Distinguish conditional إمّا from alternatives.'),
    q('Why do these requests commonly take emphatic نون?', ['Every request is negative.','Request makes a verb مبني.','Every request requires لام.','They seek an action still to be realised.'],'Use the future reading of these examples.'),
  ],
  'as-09/l1':[
    q('What underlies the ending of ليكونًا?', ['ياء المخاطبة.','نون النسوة.','Light نون التوكيد, replaced by alif in pause.','Noun tanwīn.'],'Compare connected ليكونَنْ with the pause form.'),
    q('What emphasises قد أفلح المؤمنون?', ['اللام.','القسم.','نون التوكيد.','قد.'],'Identify the actual marker.'),
    q('Why does the regular rule exclude past-form نون التوكيد?', ['نون attaches only to commands.','It marks future emphasis and is not licensed on regular past forms.','Every مبني form excludes it.','Every past verb is already emphatic.'],'Future meaning alone does not license a past-form ending.'),
    q('Why does the general rule permit emphatic نون on commands?', ['Commands have no time reference.','They seek an action still to be performed.','They are مبني.','They have no past.'],'Permission does not mean obligation.'),
  ],
};
export const quizzes = {
  'as-09/l3':[q('Which pair gives the rare state, excluding conditional إمّا?'),q('How does the source explain نون after negative لا?'),q('Which pair gives the rarer state?'),q('What is understood before تفتؤ in تالله تفتؤ تذكر يوسف?'),q('The cited لَأُقْسِمُ reading illustrates which exclusion?', ['Negative oath-answer.','Separation from لام.','Following لم.','Present-time reference.']),q('Which exclusion appears in ولسوف يعطيك ربك فترضى?')],
  'as-09/l2':[q('How many imperfect rulings are listed?'),q('What follows from explicit present-time reference?'),q('How many conditions make the oath-answer obligatory?'),q('Which surah contains وتالله لأكيدنّ أصنامكم?'),q('Near-obligatory emphasis follows which conditional expression?'),q('Frequent emphasis occurs after what kind of expression?')],
  'as-09/l1':[q('What defines مؤكّد بالنون?', ['Attached emphatic nūn, heavy or light.','No emphatic nūn.','قد before the verb.','An oath-answer alone.']),q('How many emphatic نون forms are there?'),q('What two functions does regular emphatic نون express?'),q('What is the regular rule for emphatic نون on the past form?', ['Always permitted.','Obligatory.','Common.','Excluded; poetic anomalies are separate.']),q('What is the general command-form rule?'),q('What does أقائلنّ أحضروا الشهودا illustrate?')],
};
export const practice = {
  'as-09/l3':[q('What qualifies ما الزائدة in the rare state?', ['No preceding conditional إنْ.','It must follow an oath.','It must be doubled.','It must precede لام.'],'إنْ + ما instead gives conditional إمّا.')],
  'as-09/l2':[q('Which is the source’s order of the six states?', ['واجب، كثير، قريب، قليل، ممتنع، أقلّ','كثير، واجب، قليل، أقلّ، قريب، ممتنع','واجب، قريب، كثير، قليل، أقلّ، ممتنع','ممتنع، أقلّ، قليل، كثير، قريب، واجب'],'قريب abbreviates قريب من الواجب here.')],
  'as-09/l1':[q('Does only one kind of emphatic نون count?', ['No: both heavy and light count.','Only heavy.','Only light.','Both only with commands.'],'The definition expressly includes both.')],
};
