import { card as c, rows as r, part as p, visual as v, question as q, plan } from '../nahw-course/helpers.js';

export const plans = {
  'as-07/l1': plan(24, 'Transitivity and Its Two Signs', [
    [c('Does the verb take a direct object?',0,1,2,r(3,0,1)),c('The object is reached directly',4,5,6,7,8)],
    [c('A pronoun referring to the object',0,1,2,3,4),c('A pronoun referring to the action',5,r(6,0,1)),c('Ask what the pronoun represents',7,8,9)],
    [c('A complete passive participle',0,1,2,3,4),c('A required complement changes the test',5)],
    [c('One, two or three objects',0,1,2,r(3,0,1,2),4)],
  ], [
    ['متعدّ / مجاوز','Reaches a مفعول به directly, بنفسه.'],
    ['لازم / قاصر','Does not take a direct object in that use.'],
    ['First sign','An attached هاء refers to an object, not the verb’s مصدر.'],
    ['Second sign','اسم مفعول تام: no required preposition or adverbial complement.'],
  ], {copy:{
    '0:0':'This division asks whether a verb reaches beyond its subject to a direct object.',
    '0:2':'Each class has a second name describing its behaviour.',
    '0:5':'متعدّ in its unqualified sense takes a direct object without a preposition.',
    '0:7':'Muhammad memorised the lesson. حفظ reaches الدرس directly.',
    '0:8':'بنفسه, “by itself”, excludes reaching a complement only through حرف جر. That receives a qualified name later.',
    '1:0':'The first sign examines an attached هاء, “him” or “it”.',
    '1:2':'It must refer to something other than the verb’s own مصدر.',
    '1:4':'“Zayd, Amr struck him.” هاء refers to Zayd, the object of the striking.',
    '1:5':'A pronoun referring to the action itself occurs with both transitive and intransitive verbs.',
    '1:8':'Here هاء represents a مفعول مطلق, a cognate accusative, not a direct object. Such an expression can emphasise or specify the action and occurs with both verb classes.',
    '1:9':'Compare زيد ضربه عمرو, referring to a person, with الفرح فرحه زيد, referring to rejoicing. Attachment alone is insufficient; the pronoun’s reference decides the test.',
    '2:0':'The second sign uses the passive participle.',
    '2:2':'تام means it needs no preposition or adverbial to complete this construction.',
    '2:4':'مضروب means “struck”. It can describe the object without a required complement.',
    '2:5':'The intransitive ذهب gives مذهوب به, “taken away; gone with”. The complement به completes this use. The test distinguishes this from a complete مضروب; it does not claim that intransitive verbs have no passive participles.',
    '3:0':'Count the verb’s objects.',
    '3:2':'Three counts; one further distinction.',
    '3:4':'For two objects, check their relationship.',
  },boxCopy:{'0:4':['المتعدي: ما يجاوز الفاعل إلى المفعول به بنفسه.'],'2:1':['اسم مفعول تام، غير مقترن بحرف جر أو ظرف.'],'3:1':['مفعول واحد، أو مفعولان، أو ثلاثة مفاعيل.']},
  tableCopy:{'0:3':{0:['متعدّ','مجاوز: crosses to a direct object.'],1:['لازم','قاصر: stops short of a direct object.']},'1:6':{0:['الضرب ضربه زيد','Zayd performed that striking.','ضرب is transitive.'],1:['الفرح فرحه زيد','Zayd experienced that rejoicing.','فرح is intransitive.']},'3:3':{0:['One object','The commonest class.'],1:['Two objects','Their origin may or may not be مبتدأ وخبر.'],2:['Three objects','باب أعلم وأرى.']}},
  visuals:{'2:1':v('Compare complete constructions',['مَضْرُوب','Struck'],['مَذْهُوبٌ بِهِ','Taken away'])},
  analysisPrompt:'Classify the verb. Here هاء represents its مصدر.',analysisHint:'A cognate accusative does not make a verb transitive.',
  analysisLabels:{'الفعل المُتَعَدِّي':'متعدّ','الفعل اللازِم':'لازم'},
  }),
  'as-07/l2': plan(25, 'The Three Object Counts', [
    [c('One action, one direct object',0,1,2,3,4)],
    [c('Two objects expressing a proposition',0,1,2,3,4),c('Belief, supposition and certainty',r(5,0,1,2)),c('Recover the underlying statement',6,7,8)],
    [c('Describing a resulting state',0,1,2),c('Transformation in three examples',3,4),c('A recipient and a thing given',5,6,7,8,9),c('Test the intended relationship',10)],
    [c('An added knower or perceiver',0,1,2,3,4,7),c('Three objects in the source’s reading',5,6)],
  ], [
    ['One','حفظ محمد الدرس; one direct object.'],
    ['Two: ظنّ','The objects express a topic-predicate relationship, in belief or transformation.'],
    ['Two: أعطى','Recipient and thing given do not express that relationship.'],
    ['Three','أعلم and أرى add an object to the cognitive two-object construction.'],
  ], {copy:{
    '0:0':'The first class is common and needs no further division here.',
    '0:2':'Each verb governs one direct object.',
    '0:4':'Muhammad memorised the lesson and understood the issue. الدرس and المسألة are the respective objects; the second verb’s subject is understood.',
    '1:0':'The first two-object branch preserves a relationship between a topic and what is said about it.',
    '1:2':'This branch is ظنّ and its sisters.',
    '1:4':'أفعال القلوب express belief, supposition or certainty. In these uses they put both objects in the accusative.',
    '1:7':'The student thought the lesson easy; I knew the student hardworking; I found the text clear.',
    '1:8':'Remove the judging verb and its subject, then restore nominative endings: الدرس سهل، الطالب مجتهد، النص واضح. The two objects express the underlying statement. Other meanings of these verbs may take different object counts.',
    '2:0':'The transformation family describes the state assigned to an object.',
    '2:2':'جعل، صيّر، اتّخذ، ردّ، ترك take two objects in this use. The second states what the first becomes, is made, or is left as.',
    '2:4':'I made dust into gold; the teacher made the lesson easy; the man left the door open. In each source example, the second object describes the first’s resulting state.',
    '2:5':'The other two-object branch lacks this predication.',
    '2:7':'It is أعطى and its sisters.',
    '2:9':'Zayd gave Amr a dirham: عمرا is the recipient and درهما the thing given. Giving does not assert that Amr is a dirham.',
    '2:10':'الدّرس سهل expresses the proposition in ظنّ الطالب الدرس سهلا. عمرو درهم does not express the relationship in أعطى زيد عمرا درهما. Test the intended meaning, not whether the words could form some unrelated or metaphorical sentence.',
    '3:0':'The smallest class is باب أعلم وأرى.',
    '3:2':'These constructions govern three objects.',
    '3:4':'Zayd informed Amr that the lesson was easy. زيد is subject; عمرا، الدرس، سهلا are the three objects.',
    '3:6':'“Thus Allah shows them their deeds as regrets upon them.” In the source’s cognitive reading, الله is subject; attached هم, أعمالهم and حسرات are the three objects. هم is explicit, not an implied pronoun. A visual reading can instead analyse حسرات as حال.',
    '3:7':'Causative hamza raises cognitive علم and رأى from two objects to three, adding the person informed or shown.',
  },boxCopy:{'1:1':['أصلهما المبتدأ والخبر: ظنّ وأخواتها.'],'1:3':['أفعال القلوب: اعتقاد أو ظن أو يقين.'],'2:1':['أفعال التصيير تنصب مفعولين.'],'3:1':['المتعدي لثلاثة: باب أعلم وأرى.']},
  tableCopy:{'1:5':{0:['ظنّ؛ حسب؛ خال؛ زعم','Supposition.'],1:['علم؛ رأى؛ وجد','Knowledge and certainty.'],2:['درى','Certainty.']}},
  analysisPrompt:'Match each group to its source label.',analysisHint:'The source gives درى its own certainty row.',
  analysisLabels:{'for الظَّنّ (supposition)':'الظنّ','العِلْمِيَّة (certainty, knowledge)':'العلمية','for اليَقِين (certainty)':'اليقين'},
  }),
  'as-07/l3': plan(26, 'How Intransitive Verbs Reach Objects', [
    [c('An intransitive verb has no direct object',0,1,2,3,4),c('Three additions, three objects',5,6,r(7,0,1,2),8)],
    [c('Reaching a complement through ب',0,r(1,0),p(2,0)),c('The استفعل route',r(1,1),p(2,1))],
    [c('Borrowing meaning and government',0,1,2),c('Resolve with the sense of intend',3,4,5,6),c('Be spacious with the sense of encompass',7,8)],
    [c('An omitted preposition leaves an accusative',0,1,2,5,6),c('Read the omitted ب in poetry',3,4),c('Regular omission before أنَّ and أنْ',7,8,r(9,0),p(10,0)),c('Recognise the omitted مِن',r(9,1),p(10,1)),c('Prevailing makes the competitor an object',11,12,13,14),c('Follow attested usage',15,16,17,20),c('The causative-hamza exception',18,19)],
  ], [
    ['Forms','أفعل، فعّل، فاعل، استفعل.'],
    ['Syntax','Prepositions, تضمين and نزع الخافض affect government.'],
    ['Prevailing','The competitor becomes an object.'],
    ['Usage','Eight attested routes; a reported productive hamza exception.'],
  ], {copy:{
    '0:0':'This lesson introduces لازم and eight routes by which it can reach an object.',
    '0:2':'لازم does not govern a direct object in the relevant use.',
    '0:4':'Muhammad sat; Ali went out. قعد and خرج need no direct object.',
    '0:6':'Each of these adds one stem letter.',
    '0:8':'أفعل، فعّل، فاعل: transitive here, not in every meaning.',
    '1:0':'The fourth route adds a separate preposition.',
    '2:0':'The sixth route changes meaning without adding a stem letter.',
    '2:2':'تضمين combines a verb’s meaning with another verb’s meaning and government.',
    '2:4':'“Do not resolve upon the marriage contract until the prescribed term ends.” The source explains direct عقدة النكاح by combining عزم على with the meaning of نوى, “intend”.',
    '2:6':'تعزموا takes the direct-object construction of تنووا in this analysis.',
    '2:8':'“Obedience encompassed you.” رحب, “be spacious”, takes كم directly through the incorporated meaning of وسع, “encompass”.',
    '3:0':'The seventh route omits a preposition.',
    '3:2':'توسّعا describes this expanded construction.',
    '3:4':'“You pass the abodes without turning aside; your speech to me is then forbidden.” تمرّون الديار stands for تمرّون بالديار. The omitted ب leaves الديار accusative.',
    '3:6':'نزع الخافض means removing the preposition that governed genitive.',
    '3:8':'Omission before أنَّ and أنْ is regular when the intended preposition is clear, not merely a poetic licence.',
    '3:12':'The eighth route recasts a لازم verb to express prevailing in a contest.',
    '3:14':'“I competed with him in sitting and outdid him; I outdo him.” قعد normally has no object. Here ـه represents the person outdone. The باب نصر rule retains the weak-root exceptions learned earlier.',
    '3:15':'The source qualifies all eight routes.',
    '3:17':'Transitivity is سماعية in this account: learn attested usage. Do not substitute an unattested preposition or assume every route can make every verb transitive.',
    '3:19':'Some grammarians treat causative hamza on an intransitive triliteral as قياس مطّرد, a productive rule. This is the stated exception to requiring each new form to be individually attested.',
    '3:20':'The inventory explains constructions; it is not unrestricted permission to invent them.',
  },copyParts:{'1:2':[
    'ذهبت بعلي, “I took Ali away”, reaches علي through ب. It is متعدّ معنًى, transitive in sense, but not متعدّ بنفسه under the unqualified definition.',
    'The fifth route adds همزة، سين and تاء, giving استفعل. استخرج زيد المال means “Zayd extracted the money”; المال is directly governed.',
  ],'3:10':[
    'شهد الله بأنه restores ب before أنَّ. On the accusative analysis adopted here, the clause is in محل نصب; grammarians also discuss retaining محل جر after omission.',
    'عجبتم من أن جاءكم restores مِن before أنْ. The construction preserves the meaning of being amazed at the reminder’s coming.',
  ]},boxCopy:{'0:5':['أسباب تعدية اللازم ثمانية.'],'2:1':['تضمين اللازم معنى المتعدي، ليتعدّى تعديته.'],'2:5':['تَعْزِمُوا بمعنى تَنْوُوا.'],'3:1':['حذف حرف الجر توسّعا.'],'3:5':['النصب بنزع الخافض.'],'3:16':['تعدية الفعل سماعية.'],'3:18':['قيل: همزة تعدية الثلاثي اللازم قياس مطّرد.']},
  tableHeaders:{'0:7':['Route','Example']},
  tableCopy:{'0:7':{0:['١. الهمزة','أكرم زيد عمرا: Zayd honoured Amr.'],1:['٢. التضعيف','فرّحت زيدا: I made Zayd happy.'],2:['٣. ألف المفاعلة','جالس زيد العلماء: Zayd sat with the scholars.']},'1:1':{0:['٤','حرف الجر','ذهبت بعلي','I took Ali away.','متعدّ معنًى'],1:['٥','همزة وسين وتاء','استخرج زيد المال','Zayd extracted the money.','']},
  '3:9':{0:['شهد الله أنه لا إله إلا هو [3:18]','Allah bears witness that there is no god but He.','Implied: شهد الله بأنه.'],1:['أوعجبتم أن جاءكم ذكر من ربكم [7:63, 69]','Were you amazed that a reminder came from your Lord?','Implied: عجبتم من أن جاءكم.']}},
  analysisPrompt:'Which addition gives each example its direct object?',analysisHint:'Compare أفعل، فعّل and فاعل.',
  analysisLabels:{'الهَمْزَةُ':'الهمزة','التَّضْعِيفُ':'التضعيف','زِيادَةُ أَلِفِ المُفاعَلَةِ — adding the ألف of المفاعلة':'ألف المفاعلة'},
  }),
  'as-07/l4': plan(27, 'When Direct Government Changes', [
    [c('Five routes in the reverse direction',0,1,2),c('Absorbing an intransitive meaning',3,4),c('Oppose with the sense of depart from',5,6,7,8)],
    [c('Recast on فَعُلَ for wonder',0,1,2,3,4),c('A quality replaces the ordinary action reading',5)],
    [c('The affected object becomes the subject',0,r(1,0),2),c('A fronted object and لام التقوية',r(1,1),3)],
    [c('The source’s poetic licence',0,1,2,3,4),c('An added ب in the poetic construction',5,6,7)],
  ], [
    ['Meaning','تضمين or فَعُلَ can change a verb’s construction.'],
    ['مطاوعة','كسرته فانكسر: the former object becomes subject.'],
    ['Government','لام التقوية supports a delayed governor; it does not erase the object’s role.'],
    ['Poetry','The source’s metrical example does not license unrestricted prose usage.'],
  ], {copy:{
    '0:0':'The source lists five routes under أسباب لزوم المتعدي.',
    '0:2':'They reverse the preceding direction. Some change the verb’s construction; others insert a preposition without removing its underlying object relation.',
    '0:4':'تضمين works in reverse: a transitive verb incorporates an intransitive verb’s meaning and construction.',
    '0:6':'“Let those who dissent from his order beware.” خالف ordinarily takes a direct object; this construction has عن.',
    '0:8':'The source explains يخالفون عن through يخرجون عن, “depart from”. The evidence is عن following the verb in this reading.',
    '1:0':'The second route changes the pattern.',
    '1:2':'فَعُلَ, with عين ḍamma, expresses wonder and intensity here.',
    '1:4':'ضَرَبَ reports striking and takes an object. ضَرُبَ زيد means “how capable Zayd is of striking”, like ما أضربه, and is intransitive in this use.',
    '1:5':'Earlier, فَعُلَ described settled qualities. Here the source says the recast verb sheds its ordinary event reading, تنسلخ عن الحدث. It praises a quality rather than governing a particular object of striking. This is a change of construction, not a ban on accusatives caused by ḍamma.',
    '2:0':'The third route is مطاوعة, receiving an action’s effect.',
    '2:2':'كسرتُه, “I broke it”, gives انكسر, “it broke”. The former object becomes subject and no direct object remains. Unlike the original explanation, this example does change pattern. مطاوعة is broader: other patterns can retain an object.',
    '2:3':'In ordinary order: تعبرون الرؤيا, “you interpret visions”. Here الرؤيا comes first, and لام التقوية supports the delayed governor. الرؤيا is genitive in wording but retains its object position. Fronting alone does not turn every transitive verb into an intransitive one.',
    '3:0':'The fifth route is a poetic licence in the source’s analysis.',
    '3:2':'الضرورة الشعرية: metrical necessity.',
    '3:4':'The source pictures a bashful, wide-eyed young woman captivating a heart in a dream and giving her companion drink from something cool and smiling.',
    '3:6':'The explanation is تسقيه ريقا باردا, “she gives him cool saliva to drink”. The source treats ب in ببارد as a poetic addition before the thing given; الضجيع remains the recipient.',
    '3:7':'The example belongs to attested poetry. Its metrical licence does not make this an unrestricted pattern for ordinary prose.',
  },boxCopy:{'0:1':['أسباب لزوم المتعدي أصالة خمسة.'],'0:3':['تضمين المتعدي معنى اللازم ليصير مثله.'],'0:7':['يخالف عن، بمعنى يخرج عن.'],'1:1':['التحويل إلى فَعُلَ للتعجب والمبالغة.']},
  tableCopy:{'2:1':{0:['٣','المطاوعة','كسرته فانكسر','I broke it; it broke.'],1:['٤','ضعف العامل بتأخيره','إن كنتم للرؤيا تعبرون [12:43]','If you interpret visions.']}},
  visuals:{'1:1':v('Distinguish the two readings',['ضَرَبَ','Struck an object'],['ضَرُبَ','Wonder at the quality'])},
  analysisPrompt:'Match each example to the source’s explanation.',analysisHint:'Distinguish receiving an effect from a delayed governor.',
  analysisLabels:{'صَيْرُورَتُهُ مُطاوِعًا — its becoming a مطاوع':'المطاوعة','ضَعْفُ العامِلِ بِتَأْخِيرِهِ — the weakening of the عامل by its being delayed':'ضعف العامل بتأخيره'},
  }),
};
export const checks = {
  'as-07/l1':[
    q('What does بنفسه exclude from unqualified متعدّ?', ['Augmented verbs.','A pronoun subject.','Reaching the complement only through a preposition.','More than one object.'],'Does it govern the object directly?'),
    q('Why does هاء in الفرح فرحه زيد not prove transitivity?', ['The sentence is invalid.','It represents the مصدر as مفعول مطلق.','It is an extra letter.','فرح has no مصدر.'],'Ask what the pronoun refers to.'),
    q('Why does the second sign specify اسم مفعول تام?', ['Only it is مبني.','Otherwise it would be a مصدر.','The intransitive use needs a complement.','Intransitives have no passive participles.'],'Compare مضروب and مذهوب به.'),
    q('Which object count is described as common?', ['باب أعلم وأرى.','One object.','Two objects.','Three objects.'],'Recall حفظ محمد الدرس.'),
  ],
  'as-07/l2':[
    q('Which class needs no further subdivision here?', ['Two objects.','Three objects.','All are subdivided.','One object.'],'It is also the common class.'),
    q('What is the underlying relation in ظنّ الطالب الدرس سهلا?', ['فاعل and حال.','مضاف and مضاف إليه.','مبتدأ and خبر.','Two unrelated objects.'],'Restore الدرس سهل.'),
    q('What relation do عمرا and درهما have in أعطى زيد عمرا درهما?', ['Two objects not originally مبتدأ وخبر.','Only one is an object.','أعطى is intransitive.','A judgment by a فعل قلبي.'],'Recipient and gift do not form the asserted proposition.'),
    q('In the source’s cognitive reading of يريهم الله أعمالهم حسرات, how many objects?', ['One.','None.','Three.','Two.'],'Count هم as the first object.'),
  ],
  'as-07/l3':[
    q('Which addition makes فرّحت زيدا transitive?', ['التضعيف.','الهمزة.','ألف المفاعلة.','التضمين.'],'Compare فرح and فرّح.'),
    q('Why is ذهبت بعلي qualified as متعدّ معنًى?', ['Only its past is transitive.','It reaches Ali through a preposition.','It has two objects.','It has no effect on Ali.'],'Compare معنًى with بنفسه.'),
    q('Which meaning does the source give تعزموا in لا تعزموا عقدة النكاح?', ['تنووا: intend.','تبلغوا: reach.','تعقدوا: contract.','تحذروا: beware.'],'This analysis supplies direct-object government.'),
    q('Under the source’s general rule, may all eight routes freely create unattested constructions?', ['No: follow attested transitivity.','Yes: apply any route.','Only hamza is ever permitted.','Only for triliterals.'],'It separately reports a productive causative-hamza view.'),
  ],
  'as-07/l4':[
    q('What signals the source’s تضمين analysis in يخالفون عن أمره?', ['عن after يخالفون.','The plural ending.','The إضافة in أمره.','The لام in فليحذر.'],'Recall يخرجون عن.'),
    q('Why is the recast ضَرُبَ زيد intransitive here?', ['It describes an admired quality, not a particular striking.','Ḍamma prohibits accusative.','فعل has no مصدر.','Its object is simply omitted.'],'Consider the change of meaning and construction.'),
    q('Why does للرؤيا تعبرون contain لام التقوية?', ['إن requires it.','The governor follows its fronted object.','الرؤيا is a مصدر.','The verb absorbs another meaning.'],'The underlying object relation remains.'),
    q('What distinguishes the source’s poetic-necessity example?', ['A metrical licence, not a general prose rule.','It applies only to intransitives.','It occurs only in the Quran.','It permanently changes the verb.'],'Distinguish an attested poetic construction from unrestricted analogy.'),
  ],
};
export const quizzes = {
  'as-07/l1':[q('What is another name for المتعدي?'),q('What is another name for اللازم?'),q('What defines المتعدي?', ['Added stem letters.','Reaches a direct object by itself.','Does not reach a direct object.','Stays in one tense-form.']),q('What must the attached هاء refer to for the first sign?'),q('What is هاء in الضرب ضربه زيد?'),q('What does تام mean in اسم مفعول تام?')],
  'as-07/l2':[q('What do أفعال القلوب express?'),q('Which group gives transformation verbs in the relevant use?'),q('Under which label is درى placed in the source table?'),q('Classify the two objects in أعطى زيد عمرا درهما.', ['Not originally مبتدأ وخبر.','Originally مبتدأ وخبر.','Only one direct object.','Three direct objects.']),q('Which باب governs three objects?'),q('Which family does جعلت التراب ذهبا illustrate?')],
  'as-07/l3':[q('What defines اللازم?', ['Directly reaches an object.','Stays in one tense-form.','Takes two objects.','Does not take a direct object in this use.']),q('How many routes to transitivity are listed?'),q('Which route gives جالس زيد العلماء?'),q('Which route gives استخرج زيد المال?'),q('What is النصب بنزع الخافض?', ['Borrowing a verb’s meaning.','Recasting on باب نصر.','Accusative after omitting a preposition.','Adding a preposition.']),q('How does the source generally classify transitivity?')],
  'as-07/l4':[q('How many routes are listed under لزوم المتعدي?'),q('Which meaning does يخالف incorporate here?'),q('What does ضَرُبَ زيد express?'),q('Which route does كسرته فانكسر illustrate?'),q('What is the clue in للرؤيا تعبرون?'),q('Which route does تبلت فؤادك في المنام خريدة illustrate?')],
};
export const practice = {
  'as-07/l1':[q('Which secondary names match the two classes?', ['تام and ناقص.','مجاوز for متعدّ; قاصر for لازم.','قاصر for متعدّ; مجاوز for لازم.','جامد and متصرف.'],'Think “crossing to an object”.')],
  'as-07/l2':[q('What does أصلهما المبتدأ والخبر mean?', ['Both objects name the same thing.','The verb was originally intransitive.','The two objects express a topic-predicate statement.','Both objects are definite.'],'Remove the judging verb and its subject, then restore nominative endings.')],
  'as-07/l3':[q('What do قعد محمد and خرج علي illustrate?', ['Two-object transitive.','Frozen.','Intransitive.','One-object transitive.'],'Neither verb governs a direct object here.')],
  'as-07/l4':[q('How do these five routes relate to the previous eight?', ['They run in the reverse direction.','They repeat the same eight.','They concern only intransitives.','They concern only quadriliterals.'],'Compare reaching an object with changing direct government.')],
};
