import { card as c, rows as r, part as p, visual as v, question as q, plan } from '../nahw-course/helpers.js';
const clarification = { line: 'clarification' };

export const plans = {
  'as-12/l4': plan(45, 'Time, Place and Instrument Nouns', [
    [c('Name when or where an event occurs',0,1,2),c('مَفْعَل: the general fatḥa cases',3,4),c('مَفْعِل: kasra and initial weak roots',5,6),c('Imperfect fatḥa and ḍamma',r(7,0,1)),c('Imperfect kasra',r(7,2)),c('Final weakness takes priority',r(7,3,4))],
    [c('Several meanings share one shape',0,1),c('Context supplies the distinction',clarification)],
    [c('Abundance in a place',0,1),c('Recorded kasra: worship, rising and dwelling',p(2,0),p(3,0)),c('Recorded kasra: growth, support and division',p(2,1),p(3,1)),c('Recorded kasra: gathering and other places',p(2,2),p(3,2)),c('Some fatḥa counterparts are also recorded',p(2,3),p(3,3)),c('A further kasra form and the source’s permission',p(2,4),p(3,4))],
    [c('A place of worship and a place of prostration',0,1,2),c('A conventional noun and a specific location',clarification)],
    [c('Name the instrument of an action',0,1,2),c('Three classical patterns have initial kasra',p(3,0),p(4,0)),c('مِفْعَل and مِفْعَلَة',p(3,1),p(4,1)),c('Modern instrument words',5,6)],
    [c('Recorded ḍamma: medicine and containers',p(0,0),p(1,0)),c('Recorded ḍamma: processing tools',p(0,1),p(1,1)),c('Underived instrument names',2,3),c('Duals and broken plurals',r(4,0,1,2))],
  ], [
    ['Time and place','Triliteral مَفْعَل / مَفْعِل; final weakness and initial weakness need attention.'],
    ['Longer stems','Share the passive-participle shape with time, place and مصدر ميمي meanings.'],
    ['Instrument','Classical مِفْعَل، مِفْعَال، مِفْعَلَة; modern and attested alternatives also occur.'],
    ['Usage','Context distinguishes shared forms. Learn lexical exceptions with their meanings.'],
  ], {copy:{
    '0:0':'Time and place share their formation rules.',
    '0:2':'اسم الزمان names the event’s time; اسم المكان its place. Neither is confined to an event already completed.',
    '0:4':'Use مَفْعَل when the imperfect عين has fatḥa or ḍamma, or the final root is weak whatever that vowel. The intervening فاء has sukūn, not an absent consonant. Initial-weak verbs require the next rule too.',
    '0:6':'The book gives مَفْعِل for imperfect عين kasra, or initial weakness with a sound final root. مثال includes و and ي. A reported alternative uses مَفْعَل when و survives in the imperfect, as وجل يوجل; it is an alternative account, not an extra universal rule.',
    '1:1':'مكرم، مستخرج and مستعان have the passive-participle shape. Time, place and مصدر ميمي share it; lexical context may also support a passive-participle reading. منقلب and مغتسل illustrate the overlap. Some triliteral shapes overlap too.',
    '1:clarification':'قرائن decide time, place or event meaning. Without one, the shape remains ambiguous where those lexical readings are possible. A common pattern does not guarantee every noun is actually used in all four senses.',
    '2:1':'مَأْسَدَة: many lions; مَسْبَعَة: predators; مَبْطَخَة: melons; مَقْثَأَة: cucumbers. The third corrects the transcription مطبخة and its invented “kitchens” gloss. This is a recognised abundance-place formation from concrete nouns.',
    '3:0':'The source distinguishes conventional worship-place meaning from the location of a particular prostration.',
    '3:2':'Al-Marṣafī, in الوسيلة, illustrates the latter with “Prostrate where Zayd prostrated, and its blessing will return to you.” This is his cited example. Sībawayh requires fatḥa for موضع السجود in this narrower use.',
    '3:clarification':'مَسْجِد is the conventional name for a place built for worship, even before anyone prostrates there. It is a common noun, not a proper name. مَسْجَد identifies the location of prostration in the source’s distinction.',
    '4:0':'The seventh category names an instrument.',
    '4:2':'The classical derivational definition starts with a triliteral مصدر and names what the action is performed with. The broader class of instrument names also includes recorded, modern and underived words.',
    '4:6':'The course’s modern examples are فعّالة: spectacles, washing machine, refrigerator; فعّال: meter and heater; فاعول: computer. These illustrate usage, not an exhaustive list of modern recognised patterns.',
    '5:1':'All seven have م and عين ḍamma in the source’s recorded forms. مُكْحُلَة is the kohl container; the applicator is a different implement. These are exceptions to the three classical kasra patterns.',
    '5:3':'فأس: axe; قدوم: carpenter’s adze; سكين: knife. These are underived tool names, not products of the regular instrument rule. جامد means not derived, not necessarily that no related verb exists anywhere in the lexicon.',
  },copyParts:{
    '5:0':['مُسْعُط؛ مُدْهُن؛ مُكْحُلَة؛ مُحْرُضَة.','مُنْخُل؛ مُنْصُل؛ مُدُقّ.'],
    '5:1':['These recorded forms have both م and عين ḍamma. مُسْعُط holds nasal medicine; مُدْهُن holds oil; مُكْحُلَة holds kohl, rather than applying it; مُحْرُضَة holds a cleansing agent.','مُنْخُل: sieve; مُنْصُل: blade; مُدُقّ: pounder. These complete the source’s seven recorded exceptions to the three classical instrument patterns with initial kasra.'],
    '2:2':['المَسْجِد؛ المَطْلِع؛ المَسْكِن؛ المَنْسِك.','المَنْبِت؛ المَرْفِق؛ المَسْقِط؛ المَفْرِق.','المَحْشِر؛ المَجْزِر؛ المَظِنّة؛ المَشْرِق؛ المَغْرِب.','سُمع: مَسْكَن؛ مَنْسَك؛ مَفْرَق؛ مَطْلَع.','وسُمع المَجْمِع بالكسر. قالوا: الفتح في كلها جائز وإن لم يسمع.'],
    '2:3':['These nouns have recorded kasra where the general rule predicts fatḥa. مسجد names a worship place even if no prostration has yet occurred there.','Learn the kasra together with each meaning; do not mechanically replace the established word.','The same exception list includes these five place nouns. Each is retained here with its meaning.','These four have both kasra and the expected fatḥa attested. The vowel alternative need not erase a lexical distinction in a particular use.','مَجْمِع comes from an imperfect with عين fatḥa, yet has recorded kasra. The source reports permission for regular fatḥa throughout the list. The next distinction for مسجد shows why intended sense still matters.'],
    '4:3':['مِفْعَال: مِفْتَاح؛ مِنْشَار؛ مِقْرَاض.','مِفْعَل: مِخْلَب؛ مِبْرَد؛ مِشْرَط. مِفْعَلَة: مِكْنَسَة؛ مِقْرَعَة.'],
    '4:4':['Key, saw and scissors illustrate مِفْعَال. All three classical patterns begin with kasra, contrasting with time/place مَـ.','Claw, file and scalpel use مِفْعَل; broom and a striking tool, including a knocker, use مِفْعَلَة. One view treats مفعلة as a branch of مفعل.'],
  },boxCopy:{'0:1':['اسمان لزمان وقوع الفعل أو مكانه.'],'0:3':['مَفْعَل: مَنْصَر؛ مَذْهَب؛ مَرْمًى؛ مَوْقًى؛ مَسْعًى؛ مَقَام؛ مَخَاف؛ مَرْضًى.'],'0:5':['مَفْعِل: مَجْلِس؛ مَبِيع؛ مَوْعِد؛ مَيْسِر؛ مَوْجِل.'],'1:0':['غير الثلاثي: على زنة اسم المفعول.','القرائن تميز الزمان والمكان والمصدر الميمي.'],'2:0':['مَفْعَلَة من الجامد: لكثرة الشيء في المكان.'],'3:1':['اسجد مَسْجَدَ زيد تعد عليك بركته.','سيبويه: موضع السجود، المَسْجَد بالفتح.'],'4:1':['اسم الآلة: مصوغ من مصدر ثلاثي لما وقع الفعل بواسطته.'],'4:5':['فَعَّالَة: نَظَّارَة؛ غَسَّالَة؛ ثَلَّاجَة.','فَعَّال: عَدَّاد؛ سَخَّان.','فَاعُول: حَاسُوب.'],'5:2':['فَأْس؛ قَدُوم؛ سِكِّين.']},
  boxExamples:{'5:0':{heading:'Recorded forms with ḍamma',items:[['مُسْعُط','Nasal-medicine vessel'],['مُنْخُل','Sieve'],['مُنْصُل','Blade'],['مُدُقّ','Pounder'],['مُدْهُن','Oil container'],['مُكْحُلَة','Kohl container'],['مُحْرُضَة','Cleansing-agent container']]}},
  boxPartExamples:{'2:2':{
    0:{heading:'Recorded kasra',items:[['مَسْجِد','Worship place'],['مَطْلِع','Place of rising'],['مَسْكِن','Dwelling'],['مَنْسِك','Ritual place']]},
    1:{heading:'Recorded kasra',items:[['مَنْبِت','Place of growth'],['مَرْفِق','Facility or support'],['مَسْقِط','Place of falling'],['مَفْرِق','Parting-point']]},
    2:{heading:'Recorded kasra',items:[['مَحْشِر','Gathering-place'],['مَجْزِر','Slaughterhouse'],['مَظِنّة','Likely place'],['مَشْرِق','Sunrise-place'],['مَغْرِب','Sunset-place']]},
  }},
  tableCopy:{'0:7':{0:['Imperfect عين fatḥa','مَفْعَل','مَذْهَب: place gone to.'],1:['Imperfect عين ḍamma','مَفْعَل','مَدْخَل: entrance.'],2:['Imperfect عين kasra','مَفْعِل','مَجْلِس: sitting-place; مَضْرِب: striking-place.'],3:['Final weak root','مَفْعَل','مَرْمًى: target; مَوْقًى: protected place.'],4:['Initial weak root; final sound','مَفْعِل','مَوْعِد: appointed time; مَيْسِر: gambling-place. The latter starts from ي, not a deleted و.']},'5:4':{0:['مِفْعَل','Dual مِفْعَلَان; plural مَفَاعِل.'],1:['مِفْعَلَة','Dual مِفْعَلَتَان; plural مَفَاعِل.'],2:['مِفْعَال','Dual مِفْعَالَان; plural مَفَاعِيل.']}},
  analysisPrompt:'Choose the time/place pattern.',analysisHint:'Read the imperfect عين vowel.',
  analysisText:{'table-0-7':{'مَذْهَب — the place gone to':'مَذْهَب','مَدْخَل — the place entered':'مَدْخَل','مَجْلِس، مَضْرِب — the place sat in / struck':'مَجْلِس؛ مَضْرِب'}},
  }),
  'as-12/l3': plan(44, 'Comparative Forms, Conditions and Meaning', [
    [c('The ordinary comparison shares a quality',0,1,2),c('The regular form is أفعل',3,4),c('Three shortened comparatives',p(5,0),p(6,0)),c('A hamza reappears in poetry',p(5,1),p(6,1)),c('A reading and a familiar hadith',p(7,0),p(8,0)),c('The source records another explanation',p(7,1),p(8,1))],
    [c('1. A verb underlies regular formation',0,1,2,3),c('2. Use a bare triliteral verb',4,5),c('Recorded comparisons from أفعل',6,7),c('3. The verb must conjugate',8,9),c('Use a longer comparison where appropriate',clarification)],
    [c('4. The meaning admits degrees',p(0,0),1),c('5. The verb has a complete event meaning',p(0,1),2),c('6. Preserve negation',3,4)],
    [c('7. Avoid a competing أفعل description',0,1),c('The Kūfan view and al-Mutanabbī',p(2,0),p(3,0)),c('Al-Raḍī distinguishes outward and inward traits',p(2,1),p(3,1),clarification),c('Compare a colour through its مصدر',p(4,0),p(5,0)),c('8. Passive voice must remain clear',p(4,1),p(5,1)),c('Three recorded passive-form exceptions',p(4,2),p(5,2)),c('Keep the passive in an interpreted مصدر',p(4,3),p(5,3))],
    [c('Bare أفعل stays singular masculine',0,r(1,0)),c('إضافة to an indefinite noun',r(1,1)),c('إضافة to a definite noun',r(1,2)),c('With أل, agreement is required',r(1,3)),c('Find the expressed مِن',p(2,0),p(3,0)),c('The comparison partner can be omitted',p(2,1),p(3,1)),c('A hidden group explains singular كافر',p(4,0),p(5,0)),c('Both forms of definite إضافة occur',p(4,1),p(5,1))],
    [c('Three uses, beginning with shared quality',0,p(1,0),p(2,0)),c('Compare each thing in its own quality',p(1,1),p(2,1)),c('A description without ranking',p(1,2),p(2,2)),c('Identify the two historical nicknames',3),c('Agreement follows the non-comparative reading',clarification)],
  ], [
    ['Formation','Regular أفعل follows eight conditions; خير، شرّ and حبّ are shortened forms.'],
    ['Alternatives','أشد / أكثر with a مصدر can preserve a longer, negative or passive meaning.'],
    ['Agreement','Bare or indefinite إضافة: singular masculine. Definite إضافة: either. أل: agreement.'],
    ['Meaning','Shared quality, each side’s own quality, or a non-comparative description.'],
  ], {copy:{
    '0:0':'اسم التفضيل normally compares degrees of one quality.',
    '0:2':'Both share the quality and one exceeds the other. This is the ordinary definition; the lesson later explains extended and non-comparative uses.',
    '0:4':'زيد أكرم من عمرو: Zayd is more generous than Amr. هو أعظم منه: he is greater than him.',
    '1:1':'Eight conditions govern direct regular formation. Not every failed condition admits the same alternative.',
    '1:3':'The source treats أقمن بكذا, “more deserving”, and ألصّ من شظاظ, “thievier than Shiẓāẓ”, as exceptions formed without an underlying verb. Shiẓāẓ was a proverbial thief of Banū Ḍabba. The test is not whether the comparative itself is a verb.',
    '1:5':'This means the bare three-letter stem, not merely three roots. أخصر is attributed here to passive اختُصر, so it breaches length and voice conditions. For a longer verb, use a full مصدر: هو أكثر انطلاقا, greater in setting out or freedom of movement.',
    '1:7':'أعطاهم للدراهم: most giving of money. أولاهم للمعروف: most bestowing of kindness. أقفر من غيره: more deserted. Some allow comparatives from أفعل generally; others only when its hamza is not causative.',
    '1:9':'عسى and ليس lack the required conjugation and give no regular comparative. Person endings such as لست do not make ليس conjugating across tense-forms.',
    '1:clarification':'For length or descriptive-pattern restrictions, a full مصدر can follow أشد / أكثر: أكثر انطلاقا؛ أشد حمرة. For negation or passive voice, an interpreted مصدر preserves لا or passive inflection. This does not create degrees where none are intended, or a missing مصدر for every frozen verb.',
    '2:1':'The source excludes مات and فني in their literal endpoint senses: death or perishing is not graded here. This formation rule does not deny metaphorical comparisons or differences in how an event occurs.',
    '2:2':'ناقص here means a copular use such as كان with its predicate, not a weak final root. The source excludes it because that use supplies no independent event for comparison. A complete lexical use is a different case.',
    '2:4':'ما عاج زيد بالدواء: Zayd did not benefit from the medicine. A bare comparative would lose the negation. The course illustrates preserving it with هو أكثر أن لا يذهب إلى المدرسة: a greater degree or frequency of not attending school.',
    '3:1':'The standard restriction concerns an ordinary adjective أفعل / فعلاء, used for colour, defect or physical feature. أحمر already describes red. This is a restriction in the account, not a claim that Arabic cannot ever compare colours directly.',
    '3:clarification':'Al-Raḍī retains the restriction for outward traits; the Kūfan account permits more broadly. These are different positions, not a single exceptionless ban.',
    '4:0':'Three main word forms, with إضافة split into two cases.',
    '5:0':'Meaning supplies three distinct readings.',
    '5:3':'الناقص is يزيد بن الوليد بن عبد الملك, correcting the course’s name. His nickname is linked to reducing the army’s increased pay. الأشج is عمر بن عبد العزيز, nicknamed for a scar on his head.',
    '5:clarification':'In the source’s non-comparative reading, أعدلا means العادلان and agrees with the two people. The additional claim that no other Marwānid was just belongs to the source’s rhetorical interpretation; lack of comparison alone does not logically entail that exclusion.',
  },copyParts:{
    '0:5':['خَيْر منه؛ شَرّ منه؛ وحَبّ شيء إلى الإنسان ما مُنعا.','بلال خير الناس وابن الأخْيَرِ.'],
    '0:6':['خير: better; شرّ: worse; حبّ: more beloved. The poetic phrase means “the dearest thing to a person is what is withheld”. The source explains the shortened forms through frequent use.','“Bilal is the best of people and the son of the best.” الأخير illustrates the restored hamza in an attested poetic form.'],
    '0:7':['مَنِ الْكَذَّابُ الْأَشَرُّ [54:26، قراءة مروية]. أحبّ الأعمال إلى الله أدومها وإن قلّ.','قيل: حذفها في حبّ ضرورة، وفي خير وشرّ شذوذان.'],
    '0:8':['The reported reading الأشَرّ, “more insolent”, has hamza and ش fatḥa with doubled ر. The hadith’s أحبّ, “most beloved”, retains hamza: the most beloved deeds are the most consistent, even if few.','Another view treats حبّ as poetic shortening. It counts خير and شرّ as doubly irregular: omitted hamza and no underlying verb in that analysis. The usual أحبّ is not a rare revival of everyday حبّ.'],
    '2:0':['قابل للتفاوت: فلا يصاغ قياسا من مات وفني.','تامّ: فلا يصاغ من الأفعال الناقصة في استعمالها الناقص.'],
    '3:2':['ابعد بعدت بياضا لا بياض له؛ لأنت أسود في عيني من الظُّلَم.','الرضي في شرح الكافية: يجوز في الباطن، مثل أبله وأرعن وأحمق.'],
    '3:3':['Al-Mutanabbī addresses grey hair: “Away, a whiteness with no brightness; you are blacker in my eyes than darkness.” The source cites أسود as comparative under the Kūfan permission.','Al-Raḍī permits inward traits: أبله, more foolish; أرعن, more rash; أحمق, more stupid. The book named is شرح الكافية, not the course transcription شرح القافية.'],
    '3:4':['عند فقد الشرط السابع: أشدّ حُمْرَةً.','الثامن: ألا يكون مبنيا للمجهول، ولو صورة.','أزهى من ديك؛ أشغل من ذات النحيين؛ كلام أخصر من غيره.','عند فقد الشرط الثامن: أكثر أن يُضْرَبَ.'],
    '3:5':['أشد حمرة compares the intensity of redness using its actual مصدر. The auxiliary comparative carries the comparison while حمرة preserves the intended quality.','Passive-shaped derivation is excluded to avoid confusing it with the active. زُهِي means “became proud” despite its passive form, which is why ولو صورة matters.','أزهى: prouder than a rooster, from زُهي. أشغل: proverbially busier than the woman with two butter-skins, from شُغل. أخصر: more concise, from اختُصر. The last also violates the stem-length condition.','The course’s أكثر أن يُضرب retains passive voice: greater frequency or extent of being struck. It need not mean merely “more likely”. أن plus the passive verb supplies the interpreted مصدر.'],
    '4:2':['لَيُوسُفُ وَأَخُوهُ أَحَبُّ إِلَى أَبِينَا مِنَّا [12:8]؛ أَحَبَّ إِلَيْكُمْ مِنَ اللَّهِ وَرَسُولِهِ [9:24].','وَالْآخِرَةُ خَيْرٌ وَأَبْقَى [87:17]؛ أَنَا أَكْثَرُ مِنْكَ مَالًا وَأَعَزُّ نَفَرًا [18:34].'],
    '4:3':['“Joseph and his brother are more beloved to our father than we”; “more beloved to you than Allah and His Messenger”. The missing مِنّا is restored in the first excerpt so its claim about مِن is visible.','“The Hereafter is better and more lasting” omits the comparison partner. “I have more wealth than you and greater numbers” expresses منك after أكثر and understands it after أعز. Omission is permitted when context supplies the comparison.'],
    '4:4':['وَلَا تَكُونُوا أَوَّلَ كَافِرٍ بِهِ [2:41]؛ التقدير: أول فريق كافر.','جَعَلْنَا فِي كُلِّ قَرْيَةٍ أَكَابِرَ مُجْرِمِيهَا [6:123]؛ أَحْرَصَ النَّاسِ عَلَى حَيَاةٍ [2:96].'],
    '4:5':['“Do not be the first to disbelieve in it.” كافر is indefinite. The apparent mismatch is its singular number with plural addressees, explained through omitted فريق. أول itself already stays singular masculine under indefinite إضافة.','أكابر مجرميها, “the greatest of its criminals”, uses plural agreement. أحرص الناس, “the most eager of people for life”, stays singular while describing plural هم in ولتجدنهم. Definite إضافة permits both in the comparative reading.'],
    '5:1':['الأولى: اشتراك في صفة، وزيادة أحدهما فيها.','الثانية: زيادة كلّ في صفته، دون وصف مشترك.','الثالثة: ثبوت الوصف دون نظر إلى تفضيل.'],
    '5:2':['The ordinary comparative measures both sides on one shared quality, as أكرم compares generosity.','العسل أحلى من الخل: in the source’s special reading, honey exceeds in sweetness as compared with vinegar in sourness. This is not the only possible reading of an ordinary sweetness comparison.','الناقص والأشج أعدلا بني مروان: the source reads this as “the two just men of Banū Marwān”, without ranking degrees of justice. It further interprets the phrase as excluding the others.'],
  },boxCopy:{'0:1':['اسم التفضيل: اشتراك في صفة وزيادة أحدهما فيها.'],'0:3':['القياس: أَفْعَل.'],'1:0':['للصياغة المباشرة ثمانية شروط.'],'1:2':['الأول: أن يكون له فعل.'],'1:4':['الثاني: ثلاثي مجرد. والبديل: أكثر انطلاقا.'],'1:6':['أعطاهم للدراهم؛ أولاهم للمعروف؛ أقفر من غيره.'],'1:8':['الثالث: متصرف. فلا عسى ولا ليس.'],'2:3':['السادس: مثبت. يُحفظ النفي في المصدر المؤول.'],'3:0':['السابع: ألا يكون وصفه أفعل، مؤنثه فعلاء.']},
  tableCopy:{'4:1':{0:['Bare','Singular masculine; مِن expresses the partner, or is understood.','زيد أفضل من عمرو؛ الهندات أفضل من غيرهن.'],1:['Indefinite إضافة','أفعل stays singular masculine; its indefinite complement matches the described group.','زيد أفضل طالب؛ الزيدون أفضل طلاب.'],2:['Definite إضافة','Either singular masculine or agreement, when comparison is intended.','الزيدان أفضل الطلاب / أفضلا الطلاب.'],3:['With أل','Agreement required; no comparative مِن.','زيد الأفضل؛ الزيدون الأفضلون / الأفاضل.']}},
  analysisPrompt:'Identify the comparative’s wording state.',analysisHint:'Look for أل or an إضافة, and distinguish definite from indefinite.',
  analysisLabels:{'مُجَرَّدٌ من أل والإضافة — stripped of أل and of إضافة':'Bare','مضافًا إلى نَكِرَةٍ — مضاف to an indefinite noun':'Indefinite إضافة','مضافًا إلى مَعْرِفَةٍ — مضاف to a definite noun':'Definite إضافة'},
  analysisText:{'table-4-1':{'زيدٌ أفضلُ مِنْ عمرو؛ الهنداتُ أفضلُ مِنْ … (even describing a feminine plural, أفضل stays singular masculine)':'زيد أفضل من عمرو','زيدٌ أفضلُ طالبٍ؛ الزيدونَ أفضلُ طُلَّابٍ (أفضل itself stays singular; طالبٍ/طُلَّابٍ shifts)':'الزيدون أفضل طلاب','الزيدانِ أفضلُ الطلاب (singular) / أفضلا الطلاب (dual, agreeing)':'الزيدان أفضل الطلاب / أفضلا الطلاب'}},
  }),
  'as-12/l2': plan(43, 'Passive Participles and Settled Qualities', [
    [c('Name the entity affected by the event',0,1,2),c('Recognise مفعول beneath weak-letter changes',3,4),c('فعيل can have passive meaning',p(5,0),p(6,0)),c('مفعول can name the event or quality',p(5,1),p(6,1))],
    [c('Beyond three letters: penultimate fatḥa',0,1,2),c('One surface form, two possible readings',3,4,clarification),c('An intransitive verb needs an eligible complement',5,6)],
    [c('A quality presented as settled',0,1,2),c('Two common source أبواب',3,4),c('Other source أبواب are attested',5,6),c('Settled meaning is not a clock',clarification)],
    [c('Twelve common patterns, grouped 2 + 4 + 6',0,1,r(2,0,1)),c('باب شرف: short descriptive patterns',r(3,0,1)),c('باب شرف: long medial alif',r(3,2,3)),c('Shared patterns: first-vowel contrast',r(4,0,1)),c('Shared patterns: فُعْل and فَعِل',r(4,2,3)),c('Shared patterns: فاعل and فعيل',r(4,4,5))],
    [c('Two forms can describe the same quality',0,1),c('A longer verb can name a settled quality',p(2,0),p(3,0)),c('A triliteral quality can be presented as an event',p(2,1),p(3,1)),c('Intended meaning selects the reading',clarification)],
  ], [
    ['مفعول','Affected entity: مفعول, or مُـ with penultimate fatḥa.'],
    ['Context','إعلال and إدغام can hide the active/passive vowel difference.'],
    ['صفة مشبهة','Regularly from an intransitive verb, presenting a quality as settled.'],
    ['Patterns','Twelve common shapes; other forms are attested.'],
  ], {copy:{
    '0:0':'اسم المفعول presents the affected side of an event.',
    '0:2':'The definition relates it to the مصدر of the passive verb. The مصدر itself has no active/passive conjugation, and مجهول does not require that the agent be factually unknown.',
    '0:4':'منصور and موعود show مفعول directly. The other five retain that underlying pattern: مقوول، مبيوع، مرموي، موقوي، مطووي. The source’s list omitted موقوي; it is restored here. Weak-letter rules explain the surface forms.',
    '1:1':'Replace the imperfect prefix with مُـ, as for the active participle, but use penultimate fatḥa instead of kasra.',
    '1:2':'مُكْرَم: honoured. مُعَظَّم: exalted. مُسْتَعَان به: sought for help. The vowel difference may later be hidden by sound changes.',
    '1:4':'مُخْتار can mean choosing or chosen. Context and the underlying vowel decide which reading is intended.',
    '1:clarification':'إعلال hides the vowel contrast in مختار; إدغام hides it in doubled forms. Both readings require an appropriate construction and meaning. Ambiguous spelling does not make every occurrence equally active and passive.',
    '1:6':'An eligible ظرف, جار ومجرور or مصدر supplies the passive complement, under the earlier conditions of تصرف and اختصاص. In the promoted adverbial example, يومُ is nominative; the original accusative display obscured that role.',
    '2:0':'This noun presents a quality as settled in its bearer.',
    '2:2':'حسن describes someone as good-looking. ضارب presents striking as an event. ثبوت concerns how the quality is presented, not a claim that it can never change. An active participle need not describe something happening right now.',
    '2:4':'Intransitive باب فرح, فَعِلَ, and باب شرف, فَعُلَ, supply the common patterns. This is a tendency, not an exclusive source rule.',
    '2:6':'سيّد: master, from ساد يسود. ميّت: dead, from مات يموت. شيخ: elder, from شاخ يشيخ. These come from other أبواب, beyond the two most common sources.',
    '2:clarification':'Regular formation uses an intransitive verb and intended ثبوت. اسم الفاعل can use either transitivity and may refer to past, present or future through context. The contrast is settled quality versus event presentation, not permanent versus “happening now”.',
    '3:1':'In this inventory, two patterns belong to باب فرح, four to باب شرف, and six are shared.',
    '4:1':'ماجد / مجيد: glorious. نابه / نبيه: distinguished. Two forms may describe the same root meaning. شَكُس, ill-tempered, is a rare فَعُل description outside the twelve.',
    '4:clarification':'معتدل القامة uses the non-triliteral active shape with intended settled stature. حاسن وجهه presents beauty as occurring or renewed. Neither reading requires a particular cause, such as food or grooming; those were illustrative suggestions in the course.',
  },copyParts:{'0:5':['فَعِيل بمعنى مفعول: قَتِيل، جَرِيح.','ليس لفلان مَعْقُول: أي عَقْل. ما عنده مَعْلُوم: أي عِلْم.'],
    '0:6':['قتيل means مقتول, killed; جريح means مجروح, wounded. This concerns فعيل’s passive sense, contrasting with its active sense in قدير.','The pattern مفعول, not the literal word مفعول alone, can carry a مصدر sense. معقول here is intellect; معلوم is knowledge. These are recorded uses, not a general replacement rule.'],
    '4:2':['غير الثلاثي على زنة اسم الفاعل للثبوت: مُعْتَدِل القامة؛ مُنْطَلِق اللسان.','للتجدد والحدوث: زيد شاجع أمس؛ وشارف غدا؛ وحاسن وجهه.'],
    '4:3':['معتدل القامة: of even stature. منطلق اللسان: fluent of speech. The active-participle shape can function as صفة مشبهة when a settled quality is intended.','شاجع أمس: brave yesterday; شارف غدا: noble tomorrow; حاسن وجهه: his face showing beauty. Recasting onto فاعِل presents an occurrence or renewed state. Past and future examples show that حدوث does not mean “right now”.'],
  },boxCopy:{'0:1':['اسم المفعول: مشتق من مصدر المبني للمجهول، لمن وقع عليه الفعل.'],'1:0':['مثل اسم الفاعل، لكن بفتح ما قبل الآخر.'],'1:3':['مُخْتار؛ مُعْتَدّ؛ مُنْصَبّ؛ مُحَابّ؛ مُتَحَابّ.'],'1:5':['ظرف: مَجْلُوسٌ يومُ الخميسِ.','جار ومجرور: مَجْلُوسٌ في المسجد.','مصدر: مَجْلُوسٌ جُلُوسٌ طويلٌ.'],'2:1':['الصفة المشبهة: مصوغة من مصدر اللازم للدلالة على الثبوت.'],'2:3':['يغلب بناؤها من لازم باب فرح وباب شرف.'],'2:5':['سَادَ يَسُودُ: سَيِّد.','مَاتَ يَمُوتُ: مَيِّت.','شَاخَ يَشِيخُ: شَيْخ.'],'3:0':['اثنا عشر وزنا غالبا: ٢ + ٤ + ٦.'],'4:0':['ماجد ومجيد؛ نابه ونبيه.','وخارج الاثني عشر: شَكُس، لسيئ الخلق.']},
  boxExamples:{'0:3':{heading:'The مفعول family',items:['مَنْصُور','مَوْعُود','مَقُول','مَبِيع','مَرْمِيّ','مَوْقِيّ','مَطْوِيّ']}},
  tableCopy:{'3:2':{0:['أَفْعَل / فَعْلَاء','أَحْمَر؛ حَمْرَاء','Red, masculine and feminine.'],1:['فَعْلَان / فَعْلَى','عَطْشَان؛ عَطْشَى','Thirsty, masculine and feminine.']},
    '3:3':{0:['فَعَل','حَسَن؛ بَطَل','Good-looking; brave. Two fatḥas.'],1:['فُعُل','جُنُب','In a state of major ritual impurity. Two ḍammas; rare.'],2:['فُعَال','شُجَاع؛ فُرَات','Brave; sweet or fresh water. Initial ḍamma.'],3:['فَعَال','رجل جَبَان؛ امرأة حَصَان','Cowardly man; chaste woman. Initial fatḥa; single عين.']},
    '3:4':{0:['فَعْل','سَبْط؛ ضَخْم','سبط: well-proportioned or tall, from سَبِطَ. ضخم: large, from ضَخُمَ.'],1:['فِعْل','صِفْر؛ مِلْح','Empty, from صَفِرَ; salty, from مَلُحَ.'],2:['فُعْل','حُرّ؛ صُلْب','Free, from underlying حَرِرَ; hard, from صَلُبَ.'],3:['فَعِل','فَرِح؛ نَجِس','Joyful, from فَرِحَ; impure, from نَجُسَ.'],4:['فَاعِل','صَاحِب؛ طَاهِر','Companion, from صَحِبَ; pure, from طَهُرَ.'],5:['فَعِيل','بَخِيل؛ كَرِيم','Stingy, from بَخِلَ; generous, from كَرُمَ.']}},patternTables:['3:2','3:3','3:4'],
  visuals:{'2:3':v('How the meaning is presented',['الثبوت','A settled quality'],['الحدوث والتجدد','An event or renewed state']),'4:3':v('Shape and intended meaning',['مُعْتَدِل القامة','Settled stature'],['حاسِن وجهه','Beauty presented as occurring'])},
  analysisPrompt:'Identify the صفة مشبهة pattern.',analysisHint:'Read the first two vowels; the examples come from باب شرف.',
  analysisText:{'table-3-3':{'حَسَن (good-looking), بَطَل (brave)':'حَسَن؛ بَطَل','جُنُب (in a state of ritual impurity)':'جُنُب','شُجاع (brave), فُرات (sweet-tasting, of water)':'شُجَاع؛ فُرَات'}},
  }),
  'as-12/l1': plan(42, 'Active Participles and Intensive Forms', [
    [c('Name the subject of the event',0,1,2),c('The usual triliteral pattern: فاعِل',3,4),c('Hollow roots yield a medial hamza',5,6)],
    [c('Events and settled descriptions',0,r(1,0,1)),c('Other triliteral descriptive patterns',r(1,2,3),2),c('Beyond three letters: مُـ and kasra',3,4),c('The distinguishing vowel can be underlying',clarification)],
    [c('Three recorded penultimate-fatḥa forms',0,1,2),c('Three recorded فاعل forms from أفعل',3,4)],
    [c('Intensify an active description',0,1,2),c('Repeated action and generosity',r(3,0,1)),c('Forgiving, hearing and vigilance',r(3,2,3,4))],
    [c('Other recorded intensive patterns',0,r(1,0,1)),c('Insulting, distinguishing and greatness',r(1,2,3,4)),c('Single and doubled ع are different patterns',2,3),c('Active form with passive meaning',p(4,0),p(5,0)),c('An active gloss does not settle intensity',p(4,1),p(5,1),clarification)],
  ], [
    ['فاعل','Usual triliteral form; إعلال and إدغام may alter it.'],
    ['Longer stems','Initial مُـ and penultimate kasra, sometimes underlying.'],
    ['Intensity','Five familiar patterns, plus attested alternatives.'],
    ['Meaning','Context and usage clarify a form’s intended sense.'],
  ], {copy:{
    '0:0':'اسم الفاعل names the subject in an active description.',
    '0:2':'It is derived from the مصدر of an active verb. ساقط, “falling”, shows why أو تعلق به is included: being the grammatical subject does not require deliberate action. The مصدر itself does not conjugate for active and passive voice.',
    '0:4':'ناصر helps; ضارب strikes; قابل accepts. مادّ has إدغام. واقٍ, طاوٍ and بائع have weak-letter changes. The book’s واقٍ, “protecting”, corrects the course transcription راق; the underlying category remains فاعِل.',
    '0:6':'The weak عين, represented by alif in the hollow past, becomes hamza in the participle: قال قائل؛ باع بائع. It is not the added alif of فاعِل that turns into hamza. باع has original ي, so its pre-change participle is بايِع, not باوِع.',
    '1:0':'The table also includes settled descriptive forms.',
    '1:2':'فرح، أحمر، عطشان، بطل and كريم illustrate the صفة مشبهة patterns developed next. These are common descriptions from the two intransitive أبواب, not proof that every verb in either باب excludes فاعِل.',
    '1:4':'Take the imperfect stem; replace its opening أ، ن، ي or ت with مُـ; give the penultimate kasra. مُدَحْرِج، مُنْطَلِق and مُسْتَخْرِج follow this rule. Recorded departures are learned individually.',
    '1:clarification':'مُشْتَدّ has underlying penultimate kasra before إدغام. مُحْتاج has it before إعلال. The expected vowel can therefore be تقديرا, structurally present although no separate kasra is heard in the final form.',
    '2:0':'The source records three active descriptions with penultimate fatḥa.',
    '2:2':'مُسْهَب: much given to speech; مُحْصَن: chaste or married in this reading; مُلْفَج: bankrupt, like مفلس. أحصن also means “fortify”, but the fortifier is مُحْصِن. Lexical sense and context distinguish active from passive uses.',
    '2:4':'عاشب: a place with vegetation. وارس: producing the yellow dye plant ورس or its yellow coating. يافع: a boy approaching maturity. The book excludes مُفْعِل for these examples; lexica also record مُورِس, so that restriction is an attributed account.',
    '3:0':'An active description can indicate frequent or intense action.',
    '3:2':'These five familiar صيغ المبالغة are grouped with اسم الفاعل in the earlier seven-noun inventory. A pattern is not a licence to invent every possible intensive word.',
    '4:0':'Other patterns are recorded beyond the familiar five.',
    '4:3':'“They devised a great scheme.” The book reports كُبَّارًا and كُبَارًا in readings of [71:22]. Doubling changes فُعَال to فُعَّال; it is not merely a different vowel on the same single consonant.',
    '4:clarification':'The source’s قدير بمعنى قادر and غفور بمعنى غافر identify an active sense. They do not by themselves prove that every use lacks intensity. Read the lexical meaning and context; do not erase مبالغة simply because the gloss uses فاعل.',
  },copyParts:{'4:4':['فِي عِيشَةٍ رَاضِيَةٍ [69:21]: أي مَرْضِيَّة.','فَعِيل بمعنى فاعِل: قدير، قادر. فَعُول بمعنى فاعِل: غفور، غافر.'],
    '4:5':['In the source’s analysis, راضية means a life that is pleasing or approved, مرضية. This is an active-looking form with passive sense, an occasional use rather than the general model.','فعيل and فعول can convey active meaning, as قدير and غفور do. This contrasts with فعيل carrying passive meaning, such as قتيل. The grammatical direction of the meaning is separate from its intensity.'],
  },boxCopy:{'0:1':['اسم الفاعل: مشتق من مصدر المبني للفاعل، لمن وقع منه الفعل أو تعلق به.'],'0:5':['الأجوف المعلّ: قال قائل؛ باع بائع.'],'1:3':['زنة المضارع، بميم مضمومة وكسر ما قبل الآخر.'],'2:1':['أَسْهَبَ: مُسْهَب؛ أَحْصَنَ: مُحْصَن؛ أَلْفَجَ: مُلْفَج.'],'2:3':['أَعْشَبَ: عاشِب؛ أَوْرَسَ: وارِس؛ أَيْفَعَ: يافِع.'],'3:1':['صيغ المبالغة: للكثرة والمبالغة في الحدث.'],'4:2':['وَمَكَرُوا مَكْرًا كُبَّارًا [71:22]']},
  boxExamples:{'0:3':{heading:'The فاعِل family',items:['نَاصِر','ضَارِب','قَابِل','مَادّ','وَاقٍ','طَاوٍ','بَائِع']}},
  tableCopy:{'1:1':{0:['فَعَلَ','Transitive or intransitive: فاعِل.','جالِس؛ ضارِب'],1:['فَعِلَ المتعدي','فاعِل','فاهِم'],2:['فَعِلَ اللازم','فَعِل؛ أَفْعَل؛ فَعْلَان','فَرِح؛ أَحْمَر؛ عَطْشَان'],3:['فَعُلَ اللازم','فَعَل؛ فَعِيل','بَطَل؛ كَرِيم']},
    '3:3':{0:['فَعَّال','أَكَّال؛ شَرَّاب','Eats or drinks a great deal; doubled عين.'],1:['مِفْعَال','مِنْحَار','Slaughters many camels, in generosity or sacrifice.'],2:['فَعُول','غَفُور','Forgives greatly.'],3:['فَعِيل','سَمِيع','Hears exceedingly well.'],4:['فَعِل','حَذِر','Very wary; fatḥa then kasra.']},
    '4:1':{0:['فِعِّيل','سِكِّير','Much given to drink; initial kasra and doubled عين kasra.'],1:['مِفْعِيل','مِعْطِير','Heavily perfumed; initial kasra then sukūn.'],2:['فُعَلَة','هُمَزَة؛ لُمَزَة','Habitually insults or defames; ḍamma then fatḥa.'],3:['فَاعُول','فَارُوق','Distinguishes truth from falsehood.'],4:['فُعَال؛ فُعَّال','طُوَال؛ طُوَّال؛ كُبَار؛ كُبَّار','Exceedingly tall or great; single or doubled عين.']}},patternTables:['3:3','4:1'],
  analysisPrompt:'Identify the intensive pattern.',analysisHint:'Watch doubled عين and the opening vowel.',
  analysisText:{'table-3-3':{'أَكَّال (one who eats a great deal), شَرَّاب (one who drinks a great deal)':'أَكَّال؛ شَرَّاب','مِنْحار (one who slaughters camels often, for generosity or sacrifice)':'مِنْحَار','غَفُور (one who forgives a great deal)':'غَفُور'}},
  }),
};
export const checks = {
  'as-12/l4':[
    q('What selects مَفْعِل in the book’s main rule?', ['Imperfect عين kasra, or initial weakness with a sound final root.','A hollow root by itself.','Imperfect عين ḍamma alone.','Final weakness.'],'Final weakness instead selects مَفْعَل.'),
    q('What distinguishes time, place and مصدر ميمي in a shared shape?', ['Context.','Penultimate vowel alone.','Initial م vowel alone.','Letter count.'],'Several meanings can share the complete form.'),
    q('What is plentiful in a مَسْبَعَة?', ['Predators.','Hunted animals only.','Seven unspecified things.','Things driven away.'],'It is formed from سبع, a beast of prey.'),
    q('Which form does Sībawayh require for the specific prostration-place?', ['مَسْجَد, with fatḥa.','مَسْجِد, with kasra.','Either without a distinction.','مَسْجَدَة.'],'This is the source’s narrower sense.'),
    q('What do the three classical instrument patterns share?', ['Initial م kasra.','Initial م fatḥa.','Initial م ḍamma.','An alif before the last letter.'],'Compare مِفْعَل، مِفْعَال and مِفْعَلَة.'),
    q('Which pattern gives the plural مَفَاعِيل?', ['مِفْعَال','مِفْعَل','مِفْعَلَة','All three.'],'The long alif distinguishes this family.'),
  ],
  'as-12/l3':[
    q('Which comparative forms omit the usual hamza?', ['خَيْر؛ شَرّ؛ حَبّ','أكرم؛ أعظم؛ أفضل','خير؛ أحبّ؛ أشرّ','حبّ؛ شرّ؛ أخير'],'Use all three shortened forms.'),
    q('Which condition does ألصّ violate in the source’s account?', ['An underlying verb.','A triliteral stem.','Conjugation.','Complete event meaning.'],'The book derives it from the noun لص.'),
    q('Why are literal مات and فني excluded here?', ['Their endpoint meaning admits no degree in this rule.','They are copulas.','They are negated.','They are frozen.'],'The condition concerns gradability.'),
    q('Why is أزهى from زُهي exceptional here?', ['The underlying verb is passive-shaped.','The stem is longer than three.','It is negated.','It is copular.'],'The source’s analysis uses زُهي, not an active alternative.'),
    q('How does bare أفعل behave?', ['Singular masculine; مِن is expressed or understood.','Agreement; comparative مِن forbidden.','Either agreement or non-agreement.','Only its annexed noun agrees.'],'Compare الهندات أفضل من غيرهن.'),
    q('How does the source read العسل أحلى من الخل here?', ['Each is compared in its own quality.','Only one shared quality.','No comparison at all.','An irregular formation.'],'Its stated reading compares sweetness with sourness.'),
  ],
  'as-12/l2':[
    q('What does معقول بمعنى عقل show?', ['The pattern مفعول can carry a مصدر sense.','It must be an active participle.','It must be a صفة مشبهة.','It names an instrument.'],'The example means that someone lacks intellect.'),
    q('Why can مختار mean choosing or chosen?', ['إعلال hides the vowel contrast; context decides.','It has two unrelated roots.','It follows no derivational rule.','It must come from an intransitive verb.'],'Compare underlying active kasra with passive fatḥa.'),
    q('Which verb supplies the regular صفة مشبهة?', ['Intransitive.','Transitive.','Frozen.','Necessarily passive.'],'Use مصدر اللازم in the definition.'),
    q('Which pair belongs to باب فرح in this inventory?', ['أَفْعَل؛ فَعْلَان','فُعَال؛ فَعَال','فَاعِل؛ فَعِيل','فَعَل؛ فُعُل'],'Think of red and thirsty with their feminine partners.'),
    q('Why is معتدل القامة a صفة مشبهة here?', ['A settled quality is intended.','Its verb is transitive.','Its pattern is irregular.','A renewed event is intended.'],'Shape alone does not choose the reading.'),
  ],
  'as-12/l1':[
    q('Why does the definition include أو تعلق به?', ['To include a subject such as ساقط, even without deliberate action.','To include the مصدر الميمي.','To redefine the passive participle.','To require permanent qualities.'],'Grammatical subjecthood need not imply intention.'),
    q('Why do مشتدّ and محتاج satisfy the kasra rule?', ['Kasra is underlying, hidden by إدغام or إعلال.','The rule is optional.','Their م is silent.','They have no imperfect.'],'Inspect the form before its sound changes.'),
    q('What is unusual about مُسْهَب، مُحْصَن and مُلْفَج here?', ['Penultimate fatḥa in the recorded active reading.','No initial م.','An unchanged imperfect prefix.','No مصدر.'],'The question concerns their source’s active readings.'),
    q('Which intensive pattern doubles عين?', ['فَعَّال','فَعُول','فَعِل','مِفْعَال'],'Compare أكّال and شرّاب.'),
    q('What does راضية بمعنى مرضية illustrate?', ['An active form can occasionally have passive sense.','فعيل with active sense.','Every intensive is irregular.','A passive form used actively.'],'Use the source’s analysis of عيشة راضية.'),
  ],
};
export const quizzes = {
  'as-12/l4':[q('What do time and place nouns name?', ['When or where an event occurs.','Who is affected.','Its instrument.','A settled quality.']),q('Why is مَجْلِس on مَفْعِل?', ['Imperfect عين kasra.','Final weakness.','Both first and final weakness.','Imperfect عين ḍamma.']),q('Which shape supplies non-triliteral time/place nouns?'),q('What is plentiful in a مَقْثَأَة?'),q('What base does the classical derived-instrument definition use?', ['A triliteral مصدر.','Any passive participle.','Only a non-triliteral مصدر.','Only the imperfect directly.']),q('What does مُنْخُل mean?')],
  'as-12/l3':[q('What is the regular comparative pattern?'),q('What explanation does the source give for the shortened hamza forms?', ['Frequent use.','Two unvowelled letters meeting.','Pausing.','A neighbouring ي.']),q('Which requirement excludes عسى and ليس?', ['Conjugating.','Affirmative.','Active.','Triliteral.']),q('Which requirement excludes copular كان in its incomplete use?', ['Complete event meaning.','Conjugating.','Triliteral.','Affirmative.']),q('What is required when the comparative carries أل?', ['Agreement; no comparative مِن.','Only an annexed noun agrees.','Singular masculine with مِن.','Either agreement or non-agreement.']),q('How does the source read أعدلا بني مروان?', ['Settled description without ranking.','One shared quality, unequal degrees.','Each side in a different quality.','A breach of a formation condition.'])],
  'as-12/l2':[q('What is the source relationship in the passive-participle definition?', ['The مصدر of the passive verb.','The مصدر of the active verb.','Only the passive imperfect as ultimate origin.','A صفة مشبهة.']),q('What is the underlying form of مبيع?'),q('What distinguishes the regular non-triliteral passive participle?', ['Penultimate fatḥa instead of kasra.','Initial م fatḥa instead of ḍamma.','Keep the imperfect prefix.','Penultimate ḍamma instead of kasra.']),q('Which eligible complements support an intransitive passive participle?', ['ظرف، جار ومجرور or مصدر.','Only حال.','Only تمييز.','Only a verbal noun.']),q('What meaning defines the صفة مشبهة?', ['A quality presented as settled.','Intense action alone.','An event presented as renewed.','Time or place of an event.']),q('What does حَصَان mean of a woman?')],
  'as-12/l1':[q('What is the source relationship in the active-participle definition?', ['The مصدر of the active verb.','The مصدر of the passive verb.','Only the imperfect as an ultimate origin.','A صفة مشبهة.']),q('Which descriptions occur from intransitive فَعِلَ?', ['فَعِل؛ أَفْعَل؛ فَعْلَان','Only فاعِل.','Only فَعَل and فَعِيل.','Only مُفْعِل.']),q('Which descriptions are illustrated from فَعُلَ?', ['فَعَل؛ فَعِيل','Only فاعِل.','أَفْعَل؛ فَعْلَان','Only مِفْعَال.']),q('Which form does the source give for أيفع الغلام?', ['يافِع','أَيْفَعُ','مُيْفِع','مُوفَع']),q('Which list contains the familiar five intensive patterns?', ['فَعَّال، مِفْعَال، فَعُول، فَعِيل، فَعِل','فاعِل، مُفْعِل، فَعِل، أَفْعَل، فَعْلَان','فَعُول، فَعِيل، فِعِّيل، فُعَلَة، فاعُول','فَعَّال، فُعَال، فاعُول، فُعَلَة، مِفْعِيل']),q('What does قدير بمعنى قادر establish?', ['فعيل can express active meaning.','فاعل must have passive meaning.','فعول is never a familiar intensive pattern.','فعيل can never have active meaning.'])],
};
export const practice = {
  'as-12/l4':[q('Why do مذهب and مدخل use مَفْعَل?', ['Imperfect عين fatḥa or ḍamma.','Imperfect عين kasra.','No vowel anywhere.','Tanwīn.'],'Compare يذهب and يدخل.')],
  'as-12/l3':[q('What is the source base in the definition of اسم التفضيل?', ['المصدر','المضارع','الصفة المشبهة','اسم المفعول'],'Recall the derivational account of Module 11.')],
  'as-12/l2':[q('What do منصور and موعود illustrate?', ['Triliteral passive مفعول without reshaping.','Intensive forms.','Settled-quality adjectives.','Instrument nouns.'],'Both retain the visible مفعول pattern.')],
  'as-12/l1':[q('Which formation gives ناصر، ضارب and قابل?', ['Triliteral فاعِل.','Non-triliteral imperfect shape.','An intensified passive participle.','An intensive pattern.'],'They illustrate the usual triliteral active participle.')],
};
