import { card as c, rows as r, part as p, visual as v, question as q, plan } from '../nahw-course/helpers.js';
const clarification = { line: 'clarification' };

export const plans = {
  'as-05/l1': plan(17, 'The Meanings of أَفْعَلَ', [
    [c('Root meaning and pattern meaning',0,1,2),c('What augmentation can add',3,4,5)],
    [c('From subject to object',0,1,2,3,4),c('Move up a degree of transitivity',r(5,0,1)),c('The limited move to three objects',r(5,2),6,7,8)],
    [c('Becoming possessed of something',0,r(1,0)),c('Entering a place or time',r(1,1)),c('Removing a quality or obstruction',r(1,2),2)],
    [c('Finding a quality, rather than causing it',0,r(1,0),2),c('Becoming ready for an action',r(1,1)),c('Offering something for an action',r(1,2))],
    [c('Judging something great',r(0,0)),c('Accepting the effect of فعّل',r(0,1)),c('Enabling someone to act',r(0,2)),c('An augmented form can share its root’s meaning',1,2,3),c('A used form without its bare counterpart',4,5),c('Rare reversals of transitivity',6,p(7,0)),c('أكبّ: the subject undergoes the effect',p(7,1),clarification)],
  ], [
    ['أفعل', 'Ten meanings in the source; التعدية is the commonest.'],
    ['Context', 'أكرم can honour someone or find them generous.'],
    ['مطاوعة', 'Accepting an effect contrasts with causing it. أكبّ illustrates a rare reversal.'],
    ['Usage', 'A pattern may share a bare meaning or lack a used bare counterpart.'],
  ], {copy:{
    '0:0':'A word’s roots and its pattern both contribute meaning.',
    '0:2':'These lessons ask what the صيغة contributes beyond the particular root. The pattern provides possibilities, not one inevitable meaning for every root.',
    '0:4':'ذهبت, “I went”, and ضربت زيدا, “I struck Zayd”, illustrate ordinary bare action. Augmentation commonly adds meaning; some attested uses instead share a bare meaning or lack a used bare counterpart.',
    '0:5':'Compare what أفعل، انفعل or استفعل contributes in its actual use.',
    '1:0':'Ten meanings; التعدية is the commonest.',
    '1:2':'Causative hamza makes the original فاعل an object.',
    '1:4':'أقمت زيدا، أقعدته، أقرأته mean “I made him stand, sit, read”. Zayd receives the effect: مقاما، مقعدا، مقرأ.',
    '1:6':'The final degree is narrowly restricted.',
    '1:8':'The source names رأى and علم in their two-object cognitive use. أريت زيدا بكرا قائما shows Zayd that Bakr is standing; أعلمت زيدا بكرا قائما informs him of it.',
    '2:0':'The remaining meanings are individually less common than causation.',
    '2:2':'أعجمت الكتاب removes عُجمة, ambiguity, by adding dots; it does not make the text obscure.',
    '3:0':'A familiar form can have more than one reading.',
    '3:2':'أكرمته may mean “I honoured him” under التعدية or “I found him generous” under المصادفة. Context decides.',
    '4:1':'Three qualifications limit the expectation of a new meaning.',
    '4:3':'سرى/أسرى: travel by night. سقى/أسقى: give drink. طاف/أطاف: circle. ضاء/أضاء: shine. The source groups them by shared meaning; some explanations still distinguish emphasis or intensity.',
    '4:5':'The source gives أفلح, “succeed” (فاز), أقسم بالله, “swear by Allah”, and أدرك الشيء, “attain it”, as forms without the corresponding used bare verb in the stated sense.',
    '4:clarification':'Usually ذهب becomes causative أذهب. Here كببت زيدا, “I threw Zayd down”, is transitive; أكبّ زيد, “Zayd fell down”, is intransitive. The rare pairing illustrates accepting an effect, not causing another person to act.',
  }, copyParts:{'4:7':[
    'نسلت ريش الطائر, “I plucked the feathers”, contrasts with أنسل الريش, “the feathers moulted”. عرضت الشيء, “I displayed it”, contrasts with أعرض الشيء, “it appeared”. The augmented form is intransitive in these source examples.',
    'كببت زيدا على وجهه, “I threw Zayd face-down”, gives أكبّ زيد على وجهه, “Zayd fell face-down”. قشعت الريح السحاب, “the wind swept the clouds away”, contrasts with أقشع السحاب, “the clouds cleared”.',
  ]},boxCopy:{'0:3':['الأصل في المجرد إسناد الحدث إلى فاعله؛ وتطلب بالزيادة معان جديدة.'],'1:1':['التعدية: تصيير الفاعل مفعولا بالهمزة.'],'1:3':['قام زيد، وقعد، وقرأ.','أقمت زيدا، وأقعدته، وأقرأته.'],'1:7':['من المتعدي لاثنين إلى ثلاثة بالهمزة: رأى وعلم.']},
  tableCopy:{'1:5':{0:['لازم ← متعدّ لواحد','قام زيد؛ أقمت زيدا','Zayd stood; I made him stand.'],1:['متعدّ لواحد ← لاثنين','قرأ زيد الكتاب؛ أقرأته إياه','Zayd read the book; I made him read it.'],2:['متعدّ لاثنين ← لثلاثة','علم الطالب المسألة سهلة؛ أعلمت الطالب المسألة سهلة','The student knew the problem was easy; I informed the student of that.']},
  '2:1':{0:['الصيرورة','Becoming possessed of something.','ألبن الرجل؛ أتمر؛ أفلس: possessed of milk, dates or fulūs in the source’s analysis. أفلس ordinarily means becoming insolvent, not wealthy.'],1:['الدخول','Entering a place or time.','أشأم؛ أعرق: enter al-Shām or Iraq. أصبح؛ أمسى: reach morning or evening. Likewise أفجر، أظهر، أعصر، أضحى، أشهر for their times.'],2:['السلب والإزالة','Removing something.','أقذيت عين فلان: remove a speck. أعجمت الكتاب: remove ambiguity by dotting.']},
  '3:1':{0:['المصادفة','Finding a quality on encountering someone.','أحمدت زيدا؛ أكرمته؛ أبخلته: found him praiseworthy, generous or miserly.'],1:['الاستحقاق','Becoming fit or ready.','أحصد الزرع: ready for harvest. أزوجت هند: fit for marriage in the source example.'],2:['التعريض','Offering or exposing.','أرهنت المتاع؛ أبعته: offered the goods for pawning or sale.']},
  '4:0':{0:['بمعنى استفعل','Believing someone great.','أعظمته = استعظمته.'],1:['مطاوعة فعّل','Accepting the effect of a preceding action.','فطّرته فأفطر: made him break his fast, so he did. بشّرته فأبشر: gave good news, so he rejoiced.'],2:['التمكين','Enabling the object to perform an action.','أحفرته النهر: enabled him to dig the river.']},
  },analysisPrompt:'Identify the meaning of أفعل in each group.',analysisHint:'Distinguish becoming possessed, entering, and removing.',
  analysisLabels:{'الثاني: صَيْرُورَةُ شَيْءٍ ذا شَيْءٍ — becoming possessed of a thing':'الصيرورة','الثالث: الدُّخُولُ في شَيْءٍ — entering into something':'الدخول','الرابع: السَّلْبُ والإزالَةُ — removal, stripping away':'السلب والإزالة'},
  analysisText:{'table-2-1':{
    'أَلْبَنَ الرَّجُلُ، أَتْمَرَ، أَفْلَسَ — he became possessed of milk, of dates, of money':'أَلْبَنَ؛ أَتْمَرَ؛ أَفْلَسَ',
    'أَشْأَمَ، أَعْرَقَ، أَصْبَحَ، أَمْسَى — he entered الشام, العراق, the morning, the evening (and likewise أَفْجَرَ، أَظْهَرَ، أَعْصَرَ، أَضْحَى، أَشْهَرَ)':'أَشْأَمَ؛ أَعْرَقَ؛ أَصْبَحَ؛ أَمْسَى',
    'أَقْذَيْتُ عَيْنَ فُلانٍ، وأَعْجَمْتُ الكِتابَ — I removed the القَذَى (speck) from his eye, and I removed the عُجْمَة (ambiguity) of the book by dotting it':'أَقْذَيْتُ عَيْنَهُ؛ أَعْجَمْتُ الكِتَابَ',
  }} }),
  'as-05/l2': plan(18, 'Participation, Prevailing and Intensification', [
    [c('Both act; the sentence assigns different roles',0,1,2),c('Participation can make a verb transitive',3,4)],
    [c('A contest and its winner',0,1,2,clarification)],
    [c('One action follows another',0,1),c('Intensification and a shared bare meaning',2,r(3,0,1)),c('Reciprocal wording used rhetorically',r(3,2))],
    [c('فعّل also adds transitivity',0,1,r(2,0)),c('فعّل also expresses removal',r(2,1),3,4)],
    [c('More action, more objects or more subjects',r(0,0,1,2)),c('Becoming like something else',r(0,3)),c('Attributing a quality',r(0,4)),c('Turning toward a direction',r(0,5)),c('Reporting a spoken phrase',r(0,6)),c('Accepting someone’s action',r(0,7)),c('Shared meanings and unattested counterparts',1,2,3)],
  ], [
    ['فاعل', 'Commonly participation or succession.'],
    ['Prevailing', 'فَعَلَ: normally باب نصر; certain weak roots use باب ضرب.'],
    ['فعّل', 'Eight common meanings; التعدية and الإزالة are shared with أفعل.'],
    ['التكثير', 'Intensification can concern the action, objects or subjects.'],
  ], {copy:{
    '0:0':'The first common meaning of فاعل is participation.',
    '0:2':'Two or more act on one another. In the source’s presentation, the initiator is فاعل and the respondent مفعول, although both participate. Grammatical roles do not make one participant inactive.',
    '0:4':'مشيت, “I walked”, gives ماشيته, “I walked alongside him”. كرم, “be noble”, gives كارمته, “I vied with him in nobility”. The participating construction takes an object.',
    '1:0':'The participating form can describe a contest without identifying its winner.',
    '1:2':'For prevailing, the bare form is transitive regardless of its original باب or transitivity.',
    '1:clarification':'كارمته means “I vied with him in generosity”; كَرَمْتُهُ means “I outdid him”. Distinguish competing from actually prevailing.',
    '2:1':'واليت الصوم and تابعته mean maintaining the fast in succession: أوليت and أتبعت بعضه بعضا, making one part follow another.',
    '2:2':'Other uses share meanings with different patterns.',
    '3:1':'Two of فعّل’s eight common meanings are shared with أفعل.',
    '3:4':'Six further meanings follow in this comparison with أفعل. They are not claims that no other pattern can express any similar meaning.',
    '4:1':'Actual usage qualifies the expectation of a distinct added meaning.',
    '4:3':'زُيِّنَ لِلنَّاسِ حُبُّ الشَّهَوَاتِ: “Love of desires was made attractive to people.” زيّن can share زان’s meaning. ولّى/تولّى both turn away; فكّر/تفكّر both reflect. The source gives عيّره, “reproach” (عابه), and عجّزت المرأة, “grew old”, without used bare counterparts in those senses.',
  },boxCopy:{'0:1':['التشارك بين اثنين فأكثر: يفعل أحدهما بصاحبه فيقابله بمثله.','للبادئ نسبة الفاعلية وللمقابل نسبة المفعولية.'],'1:1':['تدل صيغة فَعَلَ على الغلبة، غالبا من باب نصر.','واوي الفاء أو يائي العين أو اللام: من باب ضرب.'],'2:0':['الموالاة: وقوع الفعل بعضه في أثر بعض، بمعنى أفعل المتعدي.'],'3:3':['وتنفرد بستة في هذه المقارنة.'],'4:2':['قد ترد بمعنى أصلها أو تفعّل، أو تغني عن أصل غير مستعمل.']},
  tableCopy:{'2:3':{0:['بمعنى فعّل','ضاعفت الشيء = ضعّفته: intensification.'],1:['بمعنى فعل','دافع/دفع; سافر/سفر. Shared meaning, with an account distinguishing emphasis: سفر as going out, سافر as distant travel.'],2:['مفاعلة مجازية','يُخَادِعُونَ اللَّهَ: the source describes their concealed disbelief, professed Islam and divine recompense through reciprocal wording. It does not mean that God is literally deceived.']},
  '3:2':{0:['التعدية','لازم becomes transitive to one; one object can become two.','قوّمت زيدا؛ قعّدته. فهم زيد الدرس؛ فهّمته الدرس: made him understand it.'],1:['الإزالة','Removing a quality or covering.','جرّبت البعير: removed its mange (جرب). قشّرت الفاكهة: removed its peel (قشر).']},
  '4:0':{0:['التكثير في الفعل','More action.','جوّل؛ طوّف: much wandering and circling.'],1:['في المفعول','More objects.','غلّقت الأبواب: she closed many doors.'],2:['في الفاعل','More subjects.','موّتت الإبل؛ برّكت: many camels died or knelt.'],3:['الصيرورة لشبه','Becoming similar to another thing.','قوّس زيد: became bow-like in bending. حجّر الطين: the clay became stone-like in hardness.'],4:['النسبة','Attributing the root quality.','فسّقت زيدا؛ كفّرته: attributed فسق or كفر to him.'],5:['التوجه','Turning toward something.','شرّقت؛ غرّبت: turned east or west.'],6:['حكاية القول','Abbreviating a spoken phrase.','هلّل؛ سبّح؛ لبّى؛ أمّن؛ كبّر؛ سلّم.'],7:['القبول','Accepting someone’s action.','شفّعت زيدا: accepted his intercession (شفاعة).']},
  },tableExamples:{'4:0':{6:{heading:'Reporting a spoken phrase',items:[['هَلَّلَ','لا إله إلا الله'],['سَبَّحَ','سبحان الله'],['لَبَّى','لبّيك'],['أَمَّنَ','آمين'],['كَبَّرَ','الله أكبر'],['سَلَّمَ','السلام عليكم']]}}},
  analysisPrompt:'Identify the meaning of فعّل in each group.',analysisHint:'Distinguish intensification, becoming similar, and attributing a quality.',
  analysisLabels:{'التَكْثِير (المُبالَغَة) — intensification, the most common meaning':'التكثير','صَيْرُورَةُ شَيْءٍ شِبْهَ شَيْءٍ — a thing becoming similar to another thing':'الصيرورة لشبه','نِسْبَةُ الشَيْءِ إلى أَصْلِ الفِعْلِ — attributing something to the root meaning of the verb':'النسبة'},
  analysisText:{'table-4-0':{'جَوَّلَ وطَوَّفَ — he did much wandering and circling about':'جَوَّلَ؛ طَوَّفَ','قَوَّسَ زَيدٌ وحَجَّرَ الطِّينُ — he became bow-like in his curve; the clay became stone-like in its hardness':'قَوَّسَ زَيدٌ؛ حَجَّرَ الطِّينُ','فَسَّقْتُ زَيدًا، أو كَفَّرْتُهُ — I attributed him to الفِسْق (moral corruption) or الكُفْر (disbelief)':'فَسَّقْتُ زَيدًا؛ كَفَّرْتُهُ'}} }),
  'as-05/l3': plan(19, 'Receiving an Effect and Other Pattern Meanings', [
    [c('انفعل receives an effect',0,1,2),c('Physical actions',3,4,5,r(6,0)),c('An augmented source can also give انفعل',r(6,1)),c('Why teaching does not give انفعل here',7,8,clarification)],
    [c('افتعل: taking something for oneself',0,1,r(2,0)),c('Effort in obtaining the action',r(2,1)),c('Mutual action in افتعل',r(2,2))],
    [c('Displaying an action or quality',r(0,0)),c('Intensifying the root meaning',r(0,1)),c('Receiving effects from different patterns',r(0,2),1,2,p(3,0)),c('Forms without the stated bare counterpart',p(3,1))],
    [c('افعلّ: stronger colour or defect',0,1,2,3,4)],
  ], [
    ['انفعل', 'Intransitive مطاوعة; the source restricts its formation to physical actions.'],
    ['افتعل', 'Six meanings, including adoption, effort, participation and receiving an effect.'],
    ['مطاوعة', 'Acceptance of an effect; this meaning alone does not make every pattern intransitive.'],
    ['افعلّ', 'Intransitive, usually stronger colour or physical defect.'],
  ], {copy:{
    '0:0':'The source assigns انفعل one central meaning.',
    '0:2':'Its subject undergoes an effect, and this pattern is لازم. Receiving an effect is not a general proof of intransitivity for every other pattern.',
    '0:3':'The source restricts its regular formation to أفعال علاجية.',
    '0:5':'Physical acts: cutting, breaking, opening. Mental acts are excluded.',
    '0:8':'The source rejects علّمته فانعلم and فهّمته فانفهم in this classical pattern rule.',
    '0:clarification':'Teaching and making someone understand lie outside the stated physical-action rule. They still have other responses, such as علّمته فتعلّم. Keep the restriction on انفعل separate from the wider meaning of مطاوعة.',
    '1:1':'افتعل has six well-known meanings. First: taking something for oneself.',
    '2:1':'Its response meaning also occurs after augmented verbs.',
    '3:0':'Usually colour or physical defects.',
    '3:3':'احمرّ: redden; ابيضّ: whiten; اعورّ: become one-eyed; اعمشّ: become bleary-eyed. All are intransitive.',
    '3:4':'The source compares حَمِرَ, “was red”, احْمَرَّ, “reddened”, and احْمَارَّ, “deeply red”. This is an intensity comparison within its examples.',
  },copyParts:{'2:3':[
    'قرّبته فاقترب: brought it near, so it drew near. بعّدته فابتعد: pushed it away, so it moved away. أنصفته فانتصف: gave him justice, so he received his due.',
    'The source gives ارتجل الخطبة, “improvise a speech”; اشتمل الثوب, “wrap oneself in a garment”; افتقر, “become poor”; استلم الحجر, “touch the Black Stone”; and انتهى, “come to an end”, without corresponding bare forms in the stated senses.',
  ]},boxCopy:{'0:1':['المطاوعة: قبول تأثير الغير.','انفعل لا يكون إلا لازما.'],'0:4':['العلاجي: ما يفعل بالجوارح، لا بالقلب أو العقل.'],'2:2':['قد يطاوع افتعل الثلاثي، وفعّل، وأفعل.'],'3:1':['افعلّ لازم، ويقوّي اللون أو العيب غالبا.'],'3:2':['احْمَرَّ؛ ابْيَضَّ؛ اعْوَرَّ؛ اعْمَشَّ.']},
  tableCopy:{'0:6':{0:['Triliteral: common','قطعته فانقطع؛ كسرته فانكسر؛ فتحته فانفتح.','Cut, broke, opened; it received the effect.'],1:['Augmented: rarer','أطلقته فانطلق؛ عدّلته فانعدل.','Released it, so it went; straightened it, so it became straight. The source forms are أفعل and فعّل. These less common pairs still express receiving their effect.']},
  '1:2':{0:['الاتخاذ','Taking for oneself.','اختتم زيد؛ اختدم: took a ring (خاتم) or servant (خادم).'],1:['الاجتهاد والطلب','Effort in seeking an action.','اكتسب؛ اكتتب: strive to earn or write, compared with كسب؛ كتب. Likewise سمع and استمع: hear and listen attentively.'],2:['التشارك','Mutual action.','اختصم زيد وعمرو: Zayd and ʿAmr disputed with one another.']},
  '2:0':{0:['الإظهار','اعتذر؛ اعتظم: displayed an excuse or greatness.'],1:['المبالغة','اقتدر؛ ارتدّ: intensified ability or turning back, including apostasy in the source’s gloss. اشتدّ/شدّ and اقترأ/قرأ also illustrate intensity. اقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ [21:1], “their reckoning drew near”; اقْتَرَبَتِ السَّاعَةُ [54:1], “the Hour drew near”: stronger proximity than قرب in this account.'],2:['مطاوعة الثلاثي','عدلته فاعتدل؛ جمعته فاجتمع: straightened or gathered it, so it became straight or gathered.']},
  },analysisPrompt:'Identify the meaning of افتعل.',analysisHint:'Distinguish taking for oneself, effort and mutual action.',
  analysisLabels:{'الاتِّخاذ — adopting, taking for oneself':'الاتخاذ','الاجْتِهادُ والطَّلَب — effort and seeking':'الاجتهاد والطلب','التَّشارُك (أي المُفاعَلَة) — mutual action, i.e. المفاعلة':'التشارك'},
  analysisText:{'table-1-2':{'اخْتَتَمَ زَيدٌ، واخْتَدَمَ — he took for himself a ring (خاتَم) and a servant (خادِم)':'اخْتَتَمَ؛ اخْتَدَمَ','اكْتَسَبَ، واكْتَتَبَ — he strove and sought الكَسْب (earning) and الكِتابة (writing); it carries more effort than كَسَبَ and كَتَبَ (likewise سَمِعَ and اسْتَمَعَ)':'اكْتَسَبَ؛ اكْتَتَبَ','اخْتَصَمَ زَيدٌ وعَمْرٌو — they disputed with each other':'اخْتَصَمَ زَيدٌ وعَمْرٌو'}} }),

  'as-05/l4': plan(20, 'Effort, Shared Action and Seeking', [
    [c('تفعّل receives the effect of فعّل',r(0,0)),c('Taking something for oneself',r(0,1)),c('Effort in acquiring a quality',r(0,2),1,2,3),c('Avoiding an action or doing it gradually',r(0,3,4)),c('Used forms without a bare counterpart',4,5)],
    [c('تفاعل puts both participants in the subject',0,1),c('Two objects become one',2,3,r(5,0),clarification),c('One object becomes none',4,r(5,1))],
    [c('Appearing to act without actually doing so',r(0,0),1,2,3),c('Gradual occurrence or receiving an effect',r(0,1,2))],
    [c('Seeking: a request or an effort',r(0,0,1)),c('Becoming: literal or figurative',r(0,2,3)),c('Judging a thing’s quality',r(0,4))],
    [c('Reporting a phrase with استفعل',r(0,0)),c('Intensity or finding a quality',r(0,1,2)),c('Sharing أفعل’s meaning or receiving its effect',1,2),c('Three patterns of intensity',3,4,5,6)],
  ], [
    ['تفعّل', 'Five meanings, including effort, gradualness and receiving an effect.'],
    ['تفاعل', 'Four meanings; participation puts both parties in the grammatical subject.'],
    ['استفعل', 'Six meanings; seeking is the commonest, literally or figuratively.'],
    ['Remaining three', 'افعوعل، افعوّل، افعالّ intensify the underlying meaning.'],
  ], {copy:{
    '0:1':'The course quotes this wording to illustrate effort.',
    '0:3':'“Knowledge through learning; forbearance through practising it; understanding through studying it.” تعلّم، تحلّم and تفقّه illustrate striving to acquire these qualities. The combined wording is retained as the course’s quotation.',
    '0:5':'The source gives تكلّم, “speak”, and تصدّى, “turn attention to”, without corresponding used bare verbs in these senses.',
    '1:1':'تفاعل has four familiar meanings. For participation: تخاصم زيد وعمرو, “Zayd and ʿAmr disputed”. Both are subjects in the wording and recipients of one another’s action in meaning.',
    '1:2':'The same participants:',
    '1:4':'In خاصم زيد عمرا, Zayd is subject and ʿAmr object; both participate.',
    '1:clarification':'In these participation pairs, تفاعل makes one former object part of the subject. Other meanings require separate analysis.',
    '2:1':'The following verse illustrates deliberate appearance.',
    '2:3':'“The foolish man is not his people’s leader; their leader is the one who feigns foolishness.” المتغابي displays foolishness without actually being foolish.',
    '4:2':'أجاب and استجاب share “respond”. أحكمته فاستحكم: made it firm, so it became firm. أقمته فاستقام: set it upright, so it stood upright.',
    '4:3':'Three patterns share intensity.',
    '4:5':'افعوعل، افعوّل and افعالّ strengthen the underlying meaning in the source’s account.',
  },boxCopy:{'1:0':['التشريك: طرفا الفعل فاعلان لفظا، وكل منهما مفعول معنى.','الأول فاعل، والآخر معطوف عليه.'],'4:4':['باقي الصيغ تقوّي المعنى.']},
  tableCopy:{'0:0':{0:['مطاوعة فعّل','Receiving its effect.','نبّهته فتنبّه؛ كسّرته فتكسّر؛ علّمته فتعلّم؛ أدّبته فتأدّب: alerted, broke, taught or disciplined, then the effect was received.'],1:['الاتخاذ','Taking for oneself.','توسّد ثوبه: made his garment a pillow (وسادة). تبنّى الولد: adopted the child as a son.'],2:['التكلف','Striving through difficulty.','تصبّر؛ تحلّم: practised patience and forbearance.'],3:['التجنب','Avoiding the action.','تحرّج؛ تهجّد: avoided حرج, wrongdoing, and هجود, sleep.'],4:['التدريج','Doing it stage by stage.','تجرّعت الماء: drank gulp by gulp. تحفّظت العلم: memorised point by point.']},
  '1:5':{0:['جاذب زيد عمرا ثوبا','تجاذب زيد وعمرو ثوبا','Two objects become one: ثوب remains.'],1:['خاصم زيد عمرا','تخاصم زيد وعمرو','One object becomes none.']},
  '2:0':{0:['التظاهر','تناوم؛ تغافل؛ تعامى: feigned sleep, heedlessness or blindness.'],1:['التدريج','تزايد النيل؛ تواردت الإبل: the Nile rose, or camels arrived, gradually.'],2:['مطاوعة فاعل','باعدته فتباعد: moved it away, so it became distant.']},
  '3:0':{0:['الطلب حقيقة','A literal request.','استغفرت الله: sought Allah’s forgiveness.'],1:['الطلب مجازا','Effort treated as seeking.','استخرجت الذهب من المعدن: extracted gold from the mine. The effort is seeking, without asking the mine.'],2:['الصيرورة حقيقة','A literal change of state.','استحجر الطين؛ استحصن المهر: clay became stone; the colt became a stallion.'],3:['الصيرورة مجازا','Becoming like something.','إن البغاث بأرضنا يستنسر: weak-flying birds become eagle-like in strength in our land.'],4:['اعتقاد الصفة','Judging it to have a quality.','استحسنت كذا؛ استصوبته: judged it good or correct.']},
  '4:0':{0:['حكاية القول','استرجع: said إنا لله وإنا إليه راجعون, “We belong to Allah and to Him we return”.'],1:['القوة','استُهتر؛ استكبر: foolish talk or arrogance intensified.'],2:['المصادفة','استكرمت زيدا؛ استبخلته: found him generous or miserly.']},
  '4:6':{0:['اعشوشب المكان','More grass than عشب.'],1:['اخشوشن','Stronger coarseness than خشن.'],2:['احمارّ','Stronger redness than حمر or احمرّ in this account.']},
  },patternTables:['1:5'],tableHeaders:{'1:5':['فاعل','تفاعل','Objects']},
  analysisPrompt:'Identify the meaning of تفعّل.',analysisHint:'Distinguish receiving an effect, taking for oneself and effort.',
  analysisLabels:{'مُطاوَعَةُ فَعَّلَ مُضَعَّفِ العَيْنِ — the مطاوع of doubled-عين فَعَّلَ':'مطاوعة فعّل','الاتِّخاذ — adopting for oneself':'الاتخاذ','التَكَلُّف — exerting effort, forcing oneself':'التكلف'},
  analysisText:{'table-0-0':{'نَبَّهْتُهُ فَتَنَبَّهَ ، كَسَّرْتُهُ فَتَكَسَّرَ ، عَلَّمْتُهُ فَتَعَلَّمَ ، أَدَّبْتُهُ فَتَأَدَّبَ':'نَبَّهْتُهُ فَتَنَبَّهَ؛ عَلَّمْتُهُ فَتَعَلَّمَ','تَوَسَّدَ ثَوْبَهُ — اتَّخَذَهُ وِسادَةً ؛ تَبَنَّى الوَلَدَ — he took his garment as a pillow (وِسادَة); he adopted the child as a son':'تَوَسَّدَ ثَوْبَهُ؛ تَبَنَّى الوَلَدَ','تَصَبَّرَ وتَحَلَّمَ — he forced himself to be patient (صَبْر) and forbearing (حِلْم)':'تَصَبَّرَ؛ تَحَلَّمَ'}} }),
};

export const checks = {
  'as-05/l1':[
    q('What does بصيغتها وبنائها لا بحروفها identify?', ['A contribution of the pattern rather than the particular root.','The root letters’ meaning.','Attestation alone.','Context alone.'],'Distinguish root meaning from pattern meaning.'),
    q('Which two-object verbs gain a third object through hamza here?', ['قام وقعد','قرأ وكتب','ذهب وخرج','رأى وعلم'],'Use their two-object cognitive reading.'),
    q('How does the source classify أفلس through its connection with فلوس?', ['التعدية','الصيرورة','الدخول','السلب والإزالة'],'It is a change of state; ordinary usage means insolvency.'),
    q('Which meaning appears in أحصد الزرع?', ['التعريض','الصيرورة','الاستحقاق: becoming ready to harvest.','المصادفة'],'The crop becomes fit for the action.'),
    q('كببت زيدا is transitive; أكبّ زيد is intransitive. Which use is this?', ['الصيرورة','التعريض','Rare مطاوعة: receiving an effect.','Ordinary causative التعدية.'],'The augmented subject undergoes the result.'),
  ],
  'as-05/l2':[
    q('How does the source assign roles in ماشيته?', ['Initiator: subject; respondent: object.','Both are grammatical subjects.','Both are objects.','Neither has a role.'],'Both participate, but the syntax distinguishes them.'),
    q('Which form states that one contestant prevailed?', ['استفعل','Bare فَعَلَ, normally باب نصر.','فاعل itself.','تفاعل'],'Distinguish participating from winning.'),
    q('How does the source explain يخادعون الله?', ['A bare form expressing victory.','Reciprocal wording used rhetorically for their conduct and its recompense.','Both sides literally deceive each other.','No meaning beyond خدع.'],'The account is figurative, not literal deception of God.'),
    q('Which meanings do فعّل and أفعل share here?', null, 'Recall causing an action and removing a quality.'),
    q('Which is the commonest meaning of فعّل?', null, 'It may concern the action, objects or subjects.'),
  ],
  'as-05/l3':[
    q('Why does the source reject علّمته فانعلم?', ['انفعل requires transitivity.','علّم has no response form.','The verbs belong to different أبواب.','Its rule for انفعل is restricted to physical actions.'],'Teaching has a different response form: تعلّم.'),
    q('What meaning distinguishes اكتسب from كسب in this account?', ['Intransitivity.','Receiving كسب’s effect.','Mutual action.','Greater effort in obtaining the action.'],'Recall الاجتهاد والطلب.'),
    q('Which meaning does اقترب للناس حسابهم illustrate here?', ['التشارك','Intensification beyond قرب.','المطاوعة','الاتخاذ'],'Use the source’s comparison of proximity.'),
    q('What is the usual meaning of افعلّ?', ['الاتخاذ','الطلب','Stronger colour or physical defect.','المطاوعة'],'غالبا allows the exceptions studied earlier.'),
  ],
  'as-05/l4':[
    q('تحرّج and تهجّد avoid حرج and هجود. Which meaning?', ['التكلف','التدريج','الاتخاذ','التجنب'],'Avoiding wrongdoing or sleep.'),
    q('خاصم زيد عمرا has one object. What about تخاصم زيد وعمرو?', ['Two objects.','Three objects.','Intransitive: both participants are in the subject.','Still one object.'],'The other participant moves into the subject.'),
    q('تناوم and تغافل describe unreal sleep or heedlessness. Which meaning?', ['مطاوعة فاعل','التشريك','التظاهر بالفعل دون حقيقته','التدريج'],'The person only displays the state.'),
    q('Why is extracting gold classified as طلب?', ['It is an error.','Figuratively: effort in obtaining it counts as seeking.','The mine receives a literal request.','It must mean becoming.'],'A request need not be spoken to someone.'),
    q('Which remaining three patterns express intensity?', ['انفعل، افتعل، افعلّ','تفعّل، تفاعل، استفعل','أفعل، فاعل، فعّل','افعوعل، افعوّل، افعالّ'],'Compare اعشوشب، اخشوشن and احمارّ.'),
  ],
};
export const quizzes = {
  'as-05/l1':[q('Which meaning of أفعل is the commonest?'),q('What defines causative التعدية?'),q('Which meaning includes أصبح and أمسى?'),q('What does أعجمت الكتاب mean here?', ['Exposed it to ambiguity.','Removed ambiguity by dotting it.','Made it foreign.','Found it foreign.']),q('Which meaning includes أرهنت المتاع?'),q('How does المطاوعة relate to التعدية in this contrast?', ['The same action of causing.','A kind of becoming only.','Offering for an action.','Receiving an effect rather than causing it.'])],
  'as-05/l2':[q('What is the first common meaning of فاعل?'),q('Which form states that one party prevailed?', ['فاعل','فعّل','تفاعل','فَعَلَ, normally باب نصر.']),q('Which meaning appears in واليت الصوم وتابعته?'),q('How many common meanings does فعّل have?'),q('What does شفّعت زيدا mean here?'),q('Which meaning appears in فسّقت زيدا?')],
  'as-05/l3':[q('What central meaning does the source assign انفعل?'),q('What defines المطاوعة?'),q('What is a فعل علاجي in this rule?', ['A mental action.','Seeking an occurrence.','Any augmented verb.','A physical action carried out with the limbs.']),q('How many familiar meanings does افتعل have?'),q('Which meaning appears in اختتم زيد?'),q('What is the transitivity of افعلّ?')],
  'as-05/l4':[q('How many meanings of تفعّل are listed?'),q('Which meaning appears in توسّد ثوبه?'),q('How many familiar meanings does تفاعل have?'),q('How are the participants presented in تخاصم زيد وعمرو?', ['Neither is expressed.','Both in the subject, both receiving action in meaning.','One subject and one direct object.','Both direct objects.']),q('What is the commonest meaning of استفعل?'),q('What do افعوعل، افعوّل and افعالّ share?', ['المطاوعة','الطلب','التشارك','Intensification of the underlying meaning.'])],
};
export const practice = {
  'as-05/l1':[q('What does attributing meaning to the صيغة identify?', ['The pattern’s contribution as realised in established usage.','Meaning belonging only to one named root.','The roots’ meaning alone.','Attestation without a pattern contribution.'],'It does not guarantee one meaning for every root.')],
  'as-05/l2':[q('مشيت is intransitive. What is ماشيته?', null, 'The companion is now its object.')],
  'as-05/l3':[q('Which statement correctly describes انفعل here?', ['Physical-action eligibility alone proves all verbs intransitive.','This pattern expresses receiving an effect in an intransitive construction.','Its spelling leaves no room for an object.','Its ن always blocks objects.'],'Keep its pattern rule separate from other مطاوعة forms.')],
  'as-05/l4':[q('نبّهته فتنبّه receives the effect of which pattern?', null, 'Compare نبّه with تنبّه.')],
};
