import { card as c, rows as r, part as p, visual as v, question as q, plan } from '../nahw-course/helpers.js';
const clarification = { line:'clarification' };

export const plans = {
  'as-14/l1': plan(50, 'Classify a Noun’s Ending', [
    [c('Four classes, with precise conditions',0,1,2,3),c('A noun that declines',4,r(5,0,1)),c('A fixed final yāʾ',r(5,2,3)),c('Kasra before yāʾ matters',r(5,4),6),c('A case letter is not a fixed ending',clarification)],
    [c('مقصور: a fixed final alif',0,1,2),c('Nouns, declension and a final alif',r(3,0,1,2)),c('Exclude case-marking alif',r(3,3),clarification)],
    [c('ممدود and the remaining class',0,1),c('Weak-letter endings can behave like sound ones',2,clarification)],
    [c('A rule or recorded lexical usage',0,1,2)],
  ],[
    ['منقوص','A declining noun: fixed ي after kasra.'],
    ['مقصور','A declining noun: fixed final alif.'],
    ['ممدود','A declining noun: hamza after an added alif.'],
    ['صحيح','The remaining class, including similar-behaving endings.'],
  ],{copy:{
    '0:0':'This division classifies a noun’s ending. Number is considered next.',
    '0:2':'The four classes are منقوص، مقصور، ممدود and صحيح.',
    '0:3':'منقوص is a declining noun with fixed, single final ي preceded by kasra. الداعي and المنادي both mean a caller; المنادي is not “the one called upon”. Each qualifier matters.',
    '0:4':'The definition excludes words that fail a condition.',
    '0:6':'ظَبْي, gazelle, and رَمْي, throwing, have sukūn before ي. Their case vowels appear, so they behave like sound-final nouns: مُلحَق بالصحيح.',
    '0:clarification':'The five nouns are أب، أخ، حم، فو، ذو. Their case letter changes: أبوك، أباك، أبيك. This ي is not fixed. “Fixed” concerns the noun’s underlying ending; the spelling قاضٍ does not cease to be منقوص when its ي is regularly omitted.',
    '1:1':'الهدى, guidance, and المصطفى, the chosen one, end in fixed alif. It may be written ى, as here, or ا, as in عصا.',
    '1:2':'Alif necessarily follows fatḥa, so the definition needs no separate vowel condition. Compare final ي, which may follow kasra or sukūn.',
    '1:clarification':'The five nouns use alif in نصب, as أباك. The dual uses alif in رفع, as رجلان, before its ن. These are changing case letters, not fixed lexical endings; the definition does not claim رجلان literally ends in alif.',
    '2:1':'ممدود ends in hamza after an added alif: صحراء, desert; حمراء, red feminine. The definition requires the alif to be added, not the hamza. صحيح names the remaining class, as رجل and كتاب.',
    '2:2':'Strict صحيح ends in a sound consonant. دَلْو, bucket, ends in و after sukūn; ظبي and رمي end in ي after sukūn. These resemble صحيح in their visible case endings.',
    '2:clarification':'The distinction here concerns the noun’s ending and case behaviour. A weak root letter elsewhere does not prevent a sound ending. Alif cannot follow sukūn; the similar-to-sound examples use و or ي.',
    '3:1':'قياسي follows a stated formation rule, the morphologist’s concern. سماعي is learned word by word from attested usage, the lexicographer’s concern. It does not mean the word has no grammatical rules at all.',
    '3:2':'The lexicographer records words and their meanings. The following lessons first establish regular مقصور patterns, then regular ممدود patterns and recorded examples of both.',
  },boxCopy:{'0:1':['المنقوص: اسم معرب آخره ياء لازمة، مكسور ما قبلها.','الداعي؛ المنادي.'],'1:0':['المقصور: اسم معرب آخره ألف لازمة.'],'2:0':['الممدود: اسم معرب آخره همزة تلي ألفا زائدة.','الصحيح: ما عدا ذلك.'],'3:0':['القياسي: موضع نظر الصرفي.','السماعي: موضع نظر اللغوي.']},
  tableCopy:{'0:5':{0:['اسم','Excludes verbs.','رَضِيَ: he was pleased.'],1:['معرب','Excludes indeclinables.','الذي: who / which.'],2:['آخره ياء','Excludes fixed final alif.','الهدى: مقصور.'],3:['ياء لازمة','Excludes changing case ي.','أبيك: the five nouns in جر.'],4:['مكسور ما قبلها','Excludes ي after sukūn.','ظَبْي؛ رَمْي']},
    '1:3':{0:['اسم','Excludes verbs and particles.','دعا: he called; إلى: to.'],1:['معرب','Excludes indeclinables.','أنا: I; هذا: this.'],2:['آخره ألف','Excludes منقوص.','الداعي ends in ي.'],3:['ألف لازمة','Excludes case alif.','The five nouns in نصب; the dual in رفع.']}},
  analysisPrompt:'Which condition excludes each word?',analysisHint:'A verb is not a noun; الذي is indeclinable; ظبي has sukūn before ي.',
  analysisText:{'table-0-5':{'كرَضِيَ, he was pleased':'رَضِيَ','كالذى, who/which':'الذي'}},
  analysisLabels:{'بالاسم — being a noun':'اسم','وبالمعرب — being معرب':'معرب','وبمكسور ما قبلها — preceded by a letter with a كسرة':'Kasra before ي'},
  }),
  'as-14/l2': plan(51, 'Regular Formation of Short-Alif Nouns', [
    [c('Use a sound-final counterpart',0,1,2),c('1. The مصدر of final-weak فَعِلَ',3,4,5),c('2. فِعَل plurals of فِعْلَة',6),c('What the counterpart establishes',clarification)],
    [c('3. فُعَل plurals of فُعْلَة',0,1),c('4. Non-triliteral passive participles',2,3)],
    [c('5. Two uses of أَفْعَل',p(0,0),1),c('6. Plurals of feminine فُعْلَى',p(0,1),2),c('Compare like with like',clarification)],
    [c('7. A collective without ة',p(0,0),1),c('8. Event, time or place on مَفْعَل',p(0,1),2)],
  ],[
    ['Counterpart','Same pattern, sound final root, required penultimate fatḥa.'],
    ['Eight cases','مصادر, plurals, descriptions and other noun families.'],
    ['Vowels','Distinguish فِعَل from فُعَل and their counterparts.'],
    ['Result','Final weakness yields the short-alif ending in these patterns.'],
  ],{copy:{
    '0:1':'The noun has a weak final root and a sound-final counterpart whose pattern requires penultimate fatḥa. “Sound-final” does not require every root letter to be sound.',
    '0:2':'Eight entries apply this comparison. It is the required pattern vowel, not an accidental resemblance between two spellings, that licenses the rule.',
    '0:4':'The مصدر comes from a final-weak verb of باب سمع, فَعِلَ: fatḥa then kasra.',
    '0:5':'جَوًى, longing; هَوًى, passion; عَمًى, blindness. Their sound-final counterparts are فَرَح, joy; أَشَر, insolence; طَرَب, elation. The مصدر pattern requires fatḥa before its final root.',
    '0:6':'فِرْيَة / فِرًى: falsehoods; مِرْيَة / مِرًى: doubts or disputes; لِحْيَة / لِحًى: beards. These are فِعَل plurals of فِعْلَة. Their sound-final counterpart is قِرْبَة / قِرَب, waterskins, named alongside the next rule.',
    '0:clarification':'فَرَح، أَشَر and طَرَب establish the required vowel for جَوًى، هَوًى and عَمًى. The course delays the second entry’s counterpart until the third entry; قِرَب supplies it. Without the required counterpart, the formation is سماعي.',
    '1:1':'مُدْيَة / مُدًى: knives; زُبْيَة / زُبًى: high places. Their فُعَل counterpart is قُرْبَة / قُرَب, acts of drawing near. قِرَب, waterskins, instead belongs to the preceding فِعَل rule.',
    '1:3':'مُعْطًى, given; مُسْتَدْعًى, summoned. Compare مُكْرَم and مُسْتَخْرَج: passive participles of stems longer than three letters. The fatḥa is before the weak final root, not on it; the weak-letter rules yield final alif.',
    '2:1':'أقصى, furthest, is comparative; أعمى, blind, is a settled-quality description. Compare sound-final أبعد, further, and أعمش, weak- or watering-eyed. “Settled” describes presentation of the quality, not eternal permanence.',
    '2:2':'دُنْيَا / دُنًى is a feminine فُعْلَى and its plural; compare أُخْرَى / أُخَر. دنيا means nearer or lower, and الدنيا conventionally names this world. The pair is not two singular names for “this world”.',
    '2:clarification':'Match أقصى with أبعد for comparative meaning, and أعمى with أعمش for the non-comparative description. The shared أَفْعَل formation supports both uses.',
    '3:1':'حَصَاة: one pebble; حَصًى: pebbles collectively. Compare مَدَرَة / مَدَر, one lump / lumps of dried clay. The فَعَل collective lacks ة; ة identifies one unit.',
    '3:2':'مَلْهًى and مَسْعًى can name amusement or striving, their time or place as context permits. Compare مَذْهَب and مَسْرَح, the latter meaning pasture. This مَفْعَل family requires penultimate fatḥa.',
  },boxCopy:{'0:0':['اسم معتل اللام، له نظير صحيح الآخر يلتزم فتح ما قبل آخره.'],'0:3':['مصدر فَعِلَ المعتل اللام: الجَوَى؛ الهَوَى؛ العَمَى.'],'1:0':['فُعَل جمع فُعْلَة: مُدْيَة ومُدًى؛ زُبْيَة وزُبًى.'],'1:2':['اسم مفعول معتل اللام، من فعل زائد على الثلاثة.','مُعْطًى؛ مُسْتَدْعًى.']},
  copyParts:{'2:0':['أَفْعَل: الأقصى والأعمى؛ ونظيرهما الأبعد والأعمش.','جمع فُعْلَى أنثى أفعل: الدُّنيا والدُّنا؛ ونظيره الأُخرى والأُخر.'],'3:0':['اسم الجنس فَعَل: حَصَاة وحَصًى؛ ونظيره مَدَرَة ومَدَر.','مَفْعَل للمصدر أو الزمان أو المكان: مَلْهًى ومَسْعًى؛ ونظيره مَذْهَب ومَسْرَح.']},
  visuals:{'0:2':v('Keep initial kasra',['فِرْيَة','One falsehood'],['فِرًى','Plural on فِعَل'])},
  }),
  'as-14/l3': plan(52, 'Extended Alif: Rules and Recorded Words', [
    [c('The counterpart requires an added alif',0,1,2),c('1. مصادر of verbs beginning with همزة وصل',3,4,5),c('Contrast the two counterpart tests',clarification)],
    [c('2. The مصدر of final-weak أَفْعَلَ',p(0,0),1),c('3. Singulars in the أَفْعِلَة family',p(0,1),2)],
    [c('4. Sound and illness مصادر',0,1),c('Without this counterpart: سماعي',2,3,clarification)],
    [c('Recorded short-alif nouns',0,r(1,0,1,2,3)),c('Wealth and footwear',r(2,0,1)),c('Youthfulness and high standing',r(2,2,3)),c('Hamza can distinguish lexical meanings',clarification)],
  ],[
    ['Regular ممدود','A weak final root after the pattern’s added alif.'],
    ['Four cases','Three structural families, then sound and illness مصادر.'],
    ['سماعي','Learn the established word and meaning.'],
    ['Ending','Both forms have long ā; ممدود adds final hamza.'],
  ],{copy:{
    '0:1':'The noun has a weak final root and a sound-final counterpart with an obligatory added alif before that root.',
    '0:2':'For مقصور, the counterpart requires penultimate fatḥa. For ممدود, it requires an added alif. Four regular cases follow.',
    '0:4':'ارْعَوَى / ارْعِوَاء: desist / desisting; ابْتَغَى / ابْتِغَاء: seek / seeking; اسْتَقْصَى / اسْتِقْصَاء: investigate fully / full investigation. همزة الوصل is pronounced initially and omitted in connected speech.',
    '0:5':'Their sound-final counterparts are احمرّ / احمرار، اقتدر / اقتدار، استخرج / استخراج. The مصدر pattern supplies alif; the weak final root after it becomes hamza.',
    '0:clarification':'احمرار supports ارعواء; اقتدار supports ابتغاء. The regular added alif distinguishes this test from the required penultimate fatḥa in the مقصور lesson.',
    '1:1':'أعطى / إعطاء: give / giving; أملى / إملاء: dictate / dictating. Compare أكرم / إكرام and أحسن / إحسان. The مصدر of أَفْعَلَ has the required added alif.',
    '1:2':'كِساء / أَكْسِية: garment / garments; رِداء / أَرْدِية: cloak / cloaks. Compare حِمار / أَحْمِرة and سِلاح / أَسْلِحة. This final-weak noun family supplies the required counterpart; an أفعلة plural alone does not prove that every singular in Arabic has an alif.',
    '2:1':'رُغاء: camel’s cry; ثُغاء: sheep’s bleating, beside صُراخ, crying. مُشاء: diarrhoea, beside زُكام, a cold. The source groups these final-weak فَعَلَ مصادر by sound or illness as well as their pattern.',
    '2:3':'سماعي lacks the particular sound-final counterpart required by these formation rules. It does not mean that no similar-looking word exists, or that the noun lacks grammar.',
    '2:clarification':'The lexicographer records such words and meanings. The following lists give examples of both endings; they are not an exhaustive inventory of everything left over.',
    '3:0':'Learn each recorded ending with its lexical meaning.',
    '3:clarification':'السَّنَا: light; السَّناء: high standing. الثَّرَى: earth; الثَّراء: wealth. Both مقصور and ممدود have long ā. The difference here is final hamza, not a short vowel versus a long vowel.',
  },boxCopy:{'0:0':['معتل اللام، له نظير صحيح الآخر يلتزم زيادة ألف قبل آخره.'],'0:3':['مصدر ما أوله همزة وصل: ارعواء؛ ابتغاء؛ استقصاء.'],'2:0':['مصدر فَعَل الدال على صوت أو داء.','الرُّغاء؛ الثُّغاء؛ المُشاء.'],'2:2':['السماعي منهما: ما فقد ذلك النظير.']},
  copyParts:{'1:0':['مصدر أَفْعَل المعتل اللام: إعطاء؛ إملاء.','مفرد أَفْعِلَة: كساء وأكسية؛ رداء وأردية.']},
  tableCopy:{'3:1':{0:['الفَتَى','Young man; singular of فتيان.'],1:['الحِجَا','Reason or intellect.'],2:['السَّنَا','Light.'],3:['الثَّرَى','Earth, especially moist earth.']},'3:2':{0:['الثَّراء','Initial fatḥa.','Abundance of wealth.'],1:['الحِذاء','Initial kasra.','Sandal or footwear.'],2:['الفُتاء','Initial ḍamma.','Youthfulness.'],3:['السَّناء','Initial fatḥa.','High standing or nobility.']}},
  visuals:{'3:3':v('Read the complete ending',['السَّنَا','Light'],['السَّنَاء','High standing'])},
  analysisPrompt:'Match the recorded words to their meanings.',analysisHint:'Distinguish youth, intellect and light.',
  analysisLabels:{'واحد الفِتْيان — one of the young men':'Young man','أي العقل — reason, intellect':'Intellect','أى الضَّوْء — light':'Light'},
  }),
};
export const checks = {
  'as-14/l1':[
    q('Why is ظَبْيٌ not منقوص?', ['Its ي is not fixed.','It is indeclinable.','It ends in alif.','Sukūn precedes ي.'],'منقوص requires kasra before the final ي.'),
    q('What does لازمة exclude from مقصور?', ['Verbs and particles.','Indeclinables.','The five nouns in نصب and the dual in رفع.','The five nouns in جر.'],'A case-marking alif changes with case.'),
    q('Why does دَلْوٌ resemble صحيح?', ['Its final letter is sound.','Hamza follows an added alif.','Its alif is not fixed.','Its final و follows sukūn.'],'Its case vowels appear.'),
    q('Who studies the recorded سماعي words as lexical entries?', ['The lexicographer.','The morphologist as regular formations.','The syntactician alone.','The legal theorist.'],'Words and meanings are recorded together.'),
  ],
  'as-14/l2':[
    q('Which counterparts support الجوى، الهوى and العمى?', ['مكرم؛ مستخرج','أبعد؛ أعمش','فرح؛ أشر؛ طرب','قِرَب؛ قُرَب'],'Compare the مصدر pattern’s penultimate vowel.'),
    q('Why are مُعْطًى and مُسْتَدْعًى regular مقصور?', ['Comparative forms.','مصادر of فَعِلَ.','Final-weak non-triliteral passive participles.','Plurals of فُعْلَة.'],'The passive pattern requires penultimate fatḥa.'),
    q('What is أعمى in this list?', ['Comparative أفعل.','A plural of فُعْلَى.','A passive participle.','Non-comparative أفعل: صفة مشبهة.'],'Compare أعمش, not the comparative أبعد.'),
    q('What marks the collective in حصاة / حصى?', ['Absence of ة.','Addition of ة.','Penultimate fatḥa alone.','Addition of alif.'],'حصاة names one pebble.'),
  ],
  'as-14/l3':[
    q('Which sound-final counterpart supports ابتغاء?', ['اقتدر / اقتدار','أكرم / إكرام','حمار / أحمرة','صراخ'],'Both come from the same verb family.'),
    q('Which family supports رداء / أردية?', ['صراخ؛ زكام','حمار / أحمرة؛ سلاح / أسلحة','أكرم / إكرام؛ أحسن / إحسان','احمرّ / احمرار'],'Compare singulars and their أفعلة plurals.'),
    q('What makes the formation سماعي here?', ['Being a مصدر.','An added alif alone.','Lacking the required sound-final counterpart.','A weak final root alone.'],'It is learned from recorded usage.'),
    q('What do السنا and السناء mean respectively?', ['Nobility; light.','Intellect; sandal.','Earth; wealth.','Light; nobility.'],'The final hamza distinguishes the words.'),
  ],
};
export const quizzes = {
  'as-14/l1':[q('How does a منقوص noun end?', ['Fixed ي after kasra.','Fixed alif.','Hamza after an added alif.','A sound consonant.']),q('الداعي and المنادي illustrate which ending?', ['مقصور','ممدود','صحيح','منقوص']),q('What does معرب exclude in the definition?', ['A verb such as رضي.','مقصور.','The five nouns.','An indeclinable such as الذي.']),q('الهدى and المصطفى illustrate which ending?', ['صحيح','مقصور','منقوص','ممدود']),q('What does اسم exclude from مقصور?', ['Verbs and particles: دعا، إلى.','Indeclinables: أنا، هذا.','Nominative duals.','منقوص.']),q('What precedes the final hamza of ممدود?', ['Sukūn.','A requirement that hamza be a root.','An added alif.','A fixed ي.'])],
  'as-14/l2':[q('What must the regular مقصور counterpart require?', ['A regular مصدر.','Acceptance of ة.','Penultimate fatḥa.','An added final alif.']),q('Which pattern gives فِرْيَة / فِرًى?', ['فِعَل plural of فِعْلَة.','فُعَل plural of فُعْلَة.','مصدر of فَعِلَ.','Passive participle.']),q('Which sound-final plural matches مُدًى and زُبًى?', ['أبعد؛ أعمش','أخرى؛ أخر','قُرَب, with ḍamma.','مدرة؛ مدر']),q('What corresponds to دنيا / دنا?', ['مذهب؛ مسرح','أخرى؛ أخر','أبعد؛ أعمش','مكرم؛ مستخرج']),q('Which family includes ملهى and مسعى?', ['Non-triliteral passive participles.','Comparative أفعل.','Collective nouns.','مفعل: event, time or place.']),q('What does مَسْرَح mean here?', ['Knife.','High place.','Pasture.','Lumps of clay.'])],
  'as-14/l3':[q('How does the added alif occur in the counterpart?', ['Obligatorily.','Optionally.','It is forbidden.','Without a formation rule.']),q('Which counterpart supports ارعواء?', ['احمرّ / احمرار','أكرم / إكرام','حمار / أحمرة','صراخ']),q('What gives إعطاء and إملاء?', ['A sound or illness مصدر of فَعَلَ.','The مصدر of final-weak أَفْعَلَ.','A verb beginning with همزة وصل.','A singular of أفعلة.']),q('What is الرغاء?', ['Sheep’s bleating.','Diarrhoea.','Wealth.','Camel’s cry.']),q('What does الحجا mean?', ['Light.','Earth.','Nobility.','Intellect.']),q('What does الحذاء mean?', ['Sandal.','Wealth.','Youthfulness.','Nobility.'])],
};
export const practice = {
  'as-14/l1':[q('Which division classifies noun endings?', ['جامد / مشتق','مجرد / مزيد','منقوص / مقصور / ممدود / صحيح','مذكر / مؤنث'],'Use the complete ending and its conditions.')],
  'as-14/l2':[q('Which باب is فَعِلَ with fatḥa then kasra?', ['باب سمع','باب ضرب','باب نصر','باب كرم'],'Read both stated vowels.'),q('Which weak-final مصادر match فرح، أشر and طرب?', ['جوى؛ هوى؛ عمى','فِرًى؛ مِرًى','مُدًى؛ زُبًى','حصى؛ مدر'],'They share the required penultimate fatḥa.')],
  'as-14/l3':[q('What does regular ممدود require?', ['A fixed final alif.','An original hamza.','A counterpart requiring penultimate fatḥa.','A sound-final counterpart requiring an added alif.'],'Distinguish the two counterpart tests.')],
};
