import { card as c, rows as r, part as p, visual as v, question as q, plan } from '../nahw-course/helpers.js';
const clarification = { line: 'clarification' };
const examples = (heading, ...items) => ({ heading, items });

export const plans = {
  'as-11/l5': plan(41, 'Verbal Nouns beyond Three Letters', [
    [c('A regular pattern for every productive structure',0,1,2),c('Four-letter stems: two pattern pairs',r(3,0,1)),c('Four-letter stems: doubled and reciprocal',r(3,2,3)),c('Five-letter stems beginning with ت',r(4,0,1,2)),c('Five-letter stems beginning with وصل',r(4,3,4,5)),c('Six-letter stems: first three patterns',r(5,0,1,2)),c('Six-letter stems: doubled endings',r(5,3,4),6)],
    [c('Sound and weak final roots in فعّل',p(0,0),p(0,1),1),c('Sound roots with attested تَفْعِلَة',p(2,0),p(3,0)),c('A final hamza can follow the weak model',p(2,1),p(3,1),clarification)],
    [c('Sound عين: إفعال',p(0,0)),c('Hollow عين: transfer, merge, compensate',p(0,1),1),c('When the compensating ة is omitted',p(2,0),p(3,0)),c('اسم مصدر: an uncompensated shorter form',p(2,1),p(3,1))],
    [c('A regular initial همزة وصل',0,1,2),c('A supplied hamza does not change the family',p(3,0),p(4,0)),c('Hollow استفعل follows hollow أفعل',p(3,1),p(4,1)),c('Added ت: change the fourth letter',p(5,0)),c('Final ي changes that ḍamma to kasra',p(5,1),6,clarification)],
    [c('Quadriliteral and attached forms',p(0,0),1),c('Repeated root pairs admit فِعْلَال',p(0,1)),c('Whispering and the whisperer',2,3),c('فاعل: two regular مصدر forms',p(4,0),p(5,0)),c('Initial ي excludes فِعَال here',p(4,1),p(5,1)),c('An attested departure from the map',p(4,2))],
  ], [
    ['Four-letter stems','فعّل: تفعيل / تفعلة. أفعل: إفعال. فاعل: مفاعلة / فعال. فعلل: فعللة.'],
    ['Initial وصل','Kasra on the third letter; add alif before the last. Check hollow and assimilated forms.'],
    ['Initial added ت','Ḍamma on the fourth letter; kasra before final ي.'],
    ['Usage','Weak roots, compensation and recorded alternatives refine the regular map.'],
  ], {copy:{
    '0:0':'Here four, five and six count stem letters, including additions.',
    '0:2':'Each productive structure has a regular مصدر formation. Some admit two patterns; some require weak-letter adjustments. A recorded اسم مصدر is not a second regular full مصدر.',
    '0:6':'Quadriliteral مضاعف repeats root pairs, as ز ل ز ل, not adjacent identical middle roots. فِعْلَال is regular especially there. Other departures require attestation.',
    '1:1':'The weak-final model removes the ي of تفعيل and compensates with final ة. That ة is an added compensating letter, not an original root.',
    '1:clarification':'Compensation explains the form, not a ban on all alternative verbal nouns. Some sound-final and hamzated verbs have both تفعيل and تفعلة in recorded usage.',
    '2:1':'In the source’s analysis: move عين’s vowel to فاء; change the weak root to alif; remove the second of the adjacent alifs; add compensating ة. أَقَامَ إِقَامَة؛ أَنَابَ إِنَابَة.',
    '3:0':'Two larger families follow a general operation.',
    '3:2':'This applies to initial وصل belonging to the pattern. Weak letters still undergo their normal adjustments.',
    '3:6':'With final ي, the fourth letter takes kasra instead. This is a local adjustment to the added-ت rule.',
    '3:clarification':'Compare the operations: initial وصل, third-letter kasra plus alif; added ت, fourth-letter ḍamma. Final ي modifies the latter vowel. The وصل family also has weak-letter changes, as اصطفاء already shows.',
    '4:1':'The regular فَعْلَلَة covers the true quadriliteral and its attached forms. The second pattern فِعْلَال is regular for repeated root pairs, and otherwise requires attestation.',
    '4:3':'وِسْواس names whispering; وَسْواس in [114:4] names the whisperer, المُوَسْوِس. The book says this agent meaning is frequent with initial fatḥa, not that every such fatḥa form must be an agent.',
  },copyParts:{
    '1:0':['فَعَّلَ صحيح اللام: تَفْعِيل. طَهَّرَ تَطْهِيرًا؛ يَسَّرَ تَيْسِيرًا.','معتل اللام: تَفْعِلَة. زَكَّى تَزْكِيَة؛ رَبَّى تَرْبِيَة.'],
    '1:2':['جَرَّبَ تَجْرِبَة؛ ذَكَّرَ تَذْكِرَة؛ بَصَّرَ تَبْصِرَة؛ فَكَّرَ تَفْكِرَة؛ كَمَّلَ تَكْمِلَة؛ فَرَّقَ تَفْرِقَة؛ كَرَّمَ تَكْرِمَة.','بَرَّأَ تَبْرِئَة؛ جَزَّأَ تَجْزِئَة. والقياس: تَبْرِيئًا؛ تَجْزِيئًا.'],
    '1:3':['The book records these sound-final تفعلة forms outside its general تفعيل rule. They are attested alternatives, not forms produced “without cause”.','A final hamza may follow the weak-final تفعلة model. The source also gives the regular تفعيل forms; learn the attested alternatives for each verb.'],
    '2:0':['أَفْعَلَ صحيح العين: إِفْعَال. أَكْرَمَ إِكْرَامًا؛ أَحْسَنَ إِحْسَانًا.','إِقْوَام: نقل، فقلب، فحذف، فتعويض. النتيجة: إِقَامَة.'],
    '2:2':['وَإِقَامِ الصَّلَاةِ [24:37]. ابن مالك يختار حذف التاء في الإضافة؛ وبعضهم يجيزه مطلقا.','أَنْبَتَ نَبَاتًا؛ أَعْطَى عَطَاءً. فَعَال هنا اسم مصدر.'],
    '2:3':['“Establishment of prayer”: إقام is annexed to الصلاة. Ibn Mālik prefers this omission in إضافة; others allow it beyond that condition.','An اسم مصدر denotes the event but lacks some letters of the corresponding verbal expression without compensation. Compare نَبَات with full إِنْبَات, and عَطَاء with إِعْطَاء.'],
    '3:3':['اطَّايَرَ من تَطَايَرَ: تَطَايُر. اطَّيَّرَ من تَطَيَّرَ: تَطَيُّر.','اسْتَقَامَ اسْتِقَامَة؛ اسْتَعَاذَ اسْتِعَاذَة.'],
    '3:4':['The hamza was supplied after assimilation; it is not the defining prefix of a وصل pattern. Keep the original تفاعل or تفعّل مصدر.','Hollow استفعل uses the same transfer, alif loss and compensating ة as hollow أفعل. Its extra prefix does not prevent إعلال.'],
    '3:5':['ما بُدئ بتاء زائدة: ضمّ رابعه. تَدَحْرَجَ تَدَحْرُجًا؛ تَشَيْطَنَ تَشَيْطُنًا؛ تَجَوْرَبَ تَجَوْرُبًا.','مع لام يائية: تَوَانَى تَوَانِيًا؛ تَغَالَى تَغَالِيًا.'],
    '4:0':['دَحْرَجَ دَحْرَجَة؛ زَلْزَلَ زَلْزَلَة؛ وَسْوَسَ وَسْوَسَة؛ بَيْطَرَ بَيْطَرَة.','زَلْزَلَ زِلْزَالًا؛ وَسْوَسَ وِسْوَاسًا. وغير المضاعف سماعي: دَحْرَجَ دِحْرَاجًا.'],
    '4:4':['قَاتَلَ قِتَالًا ومُقَاتَلَة؛ خَاصَمَ خِصَامًا ومُخَاصَمَة.','يَاسَرَ مُيَاسَرَة؛ يَامَنَ مُيَامَنَة. مع فاء يائية، يمتنع فِعَال في القياس.','كَذَّبَ كِذَّابًا: سماعي خارج القياس؛ القياس تَكْذِيبًا.'],
    '4:5':['فاعل normally admits فِعَال and مُفَاعَلَة. It is not the only structure with two regular options: repeated-root فعلل also has two.','If its first root is ي, the regular formation is مفاعلة alone. Use مياسرة and ميامنة, rather than mechanically forming فِعَال.'],
  },boxCopy:{'0:1':['لغير الثلاثي مصدر قياسي، مع تفصيل بحسب البناء.'],'3:1':['اكسر الثالث، وزد ألفا قبل الآخر.','انْطَلَقَ انْطِلَاقًا؛ اقْتَدَرَ اقْتِدَارًا؛ اصْطَفَى اصْطِفَاءً؛ اسْتَغْفَرَ اسْتِغْفَارًا.'],'4:2':['مِنْ شَرِّ الْوَسْوَاسِ [114:4]','الوَسْوَاس: المُوَسْوِس.']},
  boxPartExamples:{'1:2':{0:{heading:'Recorded sound-final alternatives',items:['جَرَّبَ تَجْرِبَة','ذَكَّرَ تَذْكِرَة','بَصَّرَ تَبْصِرَة','فَكَّرَ تَفْكِرَة','كَمَّلَ تَكْمِلَة','فَرَّقَ تَفْرِقَة','كَرَّمَ تَكْرِمَة']}},'3:5':{0:{heading:'Ḍamma on the fourth letter',items:['تَدَحْرَجَ تَدَحْرُجًا','تَشَيْطَنَ تَشَيْطُنًا','تَجَوْرَبَ تَجَوْرُبًا']}},'4:0':{0:{heading:'The regular فَعْلَلَة family',items:['دَحْرَجَ دَحْرَجَة','زَلْزَلَ زَلْزَلَة','وَسْوَسَ وَسْوَسَة','بَيْطَرَ بَيْطَرَة']}}},
  tableCopy:{'0:3':{0:['فَعْلَلَ','فَعْلَلَة؛ فِعْلَال'],1:['أَفْعَلَ','إِفْعَال. فَعَال is a recorded اسم مصدر.'],2:['فَعَّلَ','تَفْعِيل؛ تَفْعِلَة'],3:['فَاعَلَ','مُفَاعَلَة؛ فِعَال']},
    '0:4':{0:['تَفَعْلَلَ','تَفَعْلُل','Added initial ت.'],1:['تَفَعَّلَ','تَفَعُّل','Added initial ت.'],2:['تَفَاعَلَ','تَفَاعُل','Added initial ت.'],3:['انْفَعَلَ','انْفِعَال','Regular initial همزة وصل.'],4:['افْتَعَلَ','افْتِعَال','Regular initial همزة وصل.'],5:['افْعَلَّ','افْعِلَال','Regular initial همزة وصل.']},
    '0:5':{0:['اسْتَفْعَلَ','اسْتِفْعَال'],1:['افْعَوْعَلَ','افْعِيعَال'],2:['افْعَوَّلَ','افْعِوَّال'],3:['افْعَلَلَّ','افْعِلْلَال. Compact: افْعِلَّال.'],4:['افْعَالَّ','افْعِيلَال']}},
  analysisPrompt:'Match each four-letter stem with its source’s verbal-noun forms.',analysisHint:'The أفعل entry includes a shorter اسم مصدر, distinguished in the lesson.',
  analysisLabels:{'إفْعَال، وفَعَال':'إِفْعَال؛ فَعَال (اسم مصدر)'},
  }),
  'as-11/l3': plan(39, 'Triliteral Verbal Nouns: The Basic Map', [
    [c('Count stem letters, then inspect the pattern',0,1,2),c('Three past patterns and their transitivity',r(3,0,1,2))],
    [c('The basic map has meaning-based exceptions',0,r(1,0,1)),c('فَعُلَ has no transitive branch',r(1,2),2)],
    [c('Two transitive patterns share فَعْل',0,1),c('An occupation changes the regular pattern',2,3,clarification)],
    [c('Intransitive فَعِلَ usually gives فَعَل',0,1,2),c('Office and colour',r(3,0,1),4),c('An action with a فاعل description',r(3,2))],
  ], [
    ['Past vowels','فَعَلَ and فَعِلَ can be transitive or intransitive; فَعُلَ is intransitive.'],
    ['Transitive','The basic مصدر is فَعْل; occupation modifies the فَعَلَ branch.'],
    ['Intransitive فَعِلَ','The basic مصدر is فَعَل; meaning can select other patterns.'],
    ['Usage','These are the book’s regular tendencies. Attested verbal nouns must also be learned.'],
  ], {copy:{
    '0:0':'A مصدر names an event without tense. Start with the triliteral stem.',
    '0:2':'Three, four, five and six here count letters in the verb stem, not five or six original roots. Each productive structure has a مصدر pattern. The bare triliteral past has three عين vowels.',
    '1:0':'The map shows the book’s basic قياس, before its semantic exceptions. It guides recognition; do not replace an attested مصدر mechanically.',
    '1:2':'فَعُلَ is intransitive in this account. Its transitive cell is therefore empty, not an unknown fourth rule.',
    '2:1':'فَعْل has fatḥa then sukūn on عين. ضَرَبَ ضَرْبًا؛ رَدَّ رَدًّا؛ فَهِمَ فَهْمًا؛ أَمِنَ أَمْنًا. The past’s fatḥa or kasra does not change this shared transitive source pattern.',
    '2:3':'الأول limits this stated exception to transitive فَعَلَ. For an occupation, its regular pattern is فِعَالَة.',
    '2:clarification':'خِياطة is sewing; حِياكة is weaving; تِجارة is trade. The course also lists تجارة here; تَجَرَ reappears among intransitive occupation verbs. Do not infer transitivity from the noun’s ending.',
    '3:1':'فَرِحَ فَرَحًا: be happy. جَوِيَ جَوًى: suffer inward grief. شَلَّ شَلَلًا: become paralysed or withered. The مصدر has underlying فَعَل, two fatḥas, with weak or doubled adjustments as needed.',
    '3:2':'Three meanings can lead to another regular pattern.',
    '3:4':'ولاية is governing; حُوّة is a red inclining to black. أَزِفَ in the next group means “draw near”.',
  },boxCopy:{'0:1':['أبنية الفعل: ثلاثية، رباعية، خماسية، سداسية.'],'2:0':['فَعَلَ وفَعِلَ المتعديان: مصدرهما فَعْل.'],'2:2':['فَعَلَ الدال على حرفة: فِعَالَة.'],'3:0':['فَعِلَ اللازم: مصدره القياسي فَعَل.']},
  tableCopy:{'0:3':{0:['فَعَلَ','عين fatḥa','ضَرَبَه: struck him, transitive. قَعَدَ: sat, intransitive.'],1:['فَعِلَ','عين kasra','فَهِمَ الدرس: understood it, transitive. رَضِيَ: was pleased, intransitive.'],2:['فَعُلَ','عين ḍamma','Intransitive.']},'1:1':{0:['فَعَلَ','لازم: فُعُول، قُعُود','متعدّ: فَعْل، ضَرْب'],1:['فَعِلَ','لازم: فَعَل، فَرَح','متعدّ: فَعْل، أَمْن'],2:['فَعُلَ','فُعُولَة: سُهُولة؛ فَعَالَة: بَلاغة','No transitive branch.']},'3:3':{0:['Trade or office','فِعَالَة','وَلِيَ عليهم وِلَايَة: governed them.'],1:['Colour','فُعْلَة','حَوِيَ حُوّة؛ حَمِرَ حُمْرة.'],2:['Action; its description is فاعِل','فُعُول','أَزِفَ الوقت أُزُوفًا؛ قَدِمَ من السفر قُدُومًا؛ صَعِدَ في السُّلَّم والدَّرَج صُعُودًا.']}},
  visuals:{'3:2':v('The action and its description',['قَدِمَ؛ قادِم','Arrive; arriving'],['صَعِدَ؛ صاعِد','Ascend; ascending'])},
  analysisPrompt:'Choose the مصدر pattern for each group.',analysisHint:'Distinguish office, colour, and an action described with فاعل.',
  analysisLabels:{'فِعَالَة، بكسر الفاء — فِعَالَة, with كسرة on the ف':'فِعَالَة','فُعْلَة، بضم فسكون — فُعْلَة: ضمة then سكون':'فُعْلَة','الفُعُول، بضم الفاء — الفُعُول, ضمة on the ف':'فُعُول'},
  analysisText:{'table-3-3':{'وَلِيَ عليهم وِلَايَة':'وَلِيَ وِلَايَة','حَوِيَ حُوَّة، وحَمِرَ حُمْرة':'حَوِيَ حُوَّة؛ حَمِرَ حُمْرة','أَزِفَ الوقتُ أُزُوفا، وقَدِمَ من السفر قُدُومًا، وصَعِدَ في السُّلَّمِ والدَّرَجِ صُعُودًا':'أَزِفَ أُزُوفًا؛ قَدِمَ قُدُومًا؛ صَعِدَ صُعُودًا'}},
  }),
  'as-11/l4': plan(40, 'Regular Tendencies and Attested Verbal Nouns', [
    [c('The base pattern is فُعُول',0,1,2),c('A weak عين changes the options',p(3,0),p(4,0)),c('Refusal and resistance',p(3,1),p(4,1),5,6)],
    [c('Motion and illness',0,r(1,0,1)),c('Travel and animal calls',r(1,2,3)),c('Trade, representation and mediation',r(1,4),2),c('One pattern can serve different meanings',clarification)],
    [c('Two regular patterns for فَعُلَ',0,1,2)],
    [c('Attested usage can depart from the map',0,1,clarification),c('فَعَلَ: seeking, growing, writing, guarding',p(2,0)),c('فَعَلَ: thanking, reckoning, remembering, concealing',p(2,1)),c('فَعَلَ: lying, prevailing, protecting, forgiving',p(2,2)),c('فَعَلَ: disobeying, deciding, guiding, seeing',p(2,3)),c('فَعِلَ: playing, ripening, disliking, growing fat',p(3,0)),c('فَعِلَ: strength, acceptance and mercy',p(3,1)),c('فَعُلَ: generosity, greatness and glory',p(4,0)),c('فَعُلَ: goodness, forbearance and beauty',p(4,1))],
  ], [
    ['فَعَلَ اللازم','Usually فُعُول; a weak عين or particular meanings select other patterns.'],
    ['Meaning','Resistance, motion, illness, travel, sound and occupation guide the choice.'],
    ['فَعُلَ','Regular فُعُولَة or فَعَالَة; attested exceptions also occur.'],
    ['سماعي','Memorise the recorded form. Do not turn an exception into a productive rule.'],
  ], {copy:{
    '0:0':'For intransitive فَعَلَ, begin with فُعُول, then check root type and meaning.',
    '0:2':'قَعَدَ قُعُودًا: sit. جَلَسَ جُلُوسًا: sit. نَهَضَ نُهُوضًا: rise. These illustrate the base pattern.',
    '0:5':'Read the verb’s meaning as well as its root type.',
    '0:6':'نِفار is shunning; إِباق is running away. The corrected جَمَحَ جِمَاحًا means resisting control, not the source transcription جمع جماعا.',
    '1:0':'Five further meaning groups refine the base rule.',
    '1:2':'عَرَفَ على القوم: spoke for or represented them. سَفَرَ بينهم: mediated peace. غَلَى: boiled. مَشَى بطنه describes diarrhoea, not inflation. الذميل is a kind of walking or travelling pace.',
    '1:clarification':'فِعَالَة serves occupation under transitive فَعَلَ, intransitive فَعَلَ and intransitive فَعِلَ in this map. فُعَال serves illness and sound. A pattern alone does not identify one meaning; read the actual verb.',
    '2:1':'Both patterns are regular choices in the book’s map, not interchangeable options for every verb. Other attested مصادر exist, as the final examples show.',
    '2:2':'عَذُبَ الماء: the water was sweet or fresh.',
    '3:1':'A سماعي form is learned from recorded usage. Departure from this map does not make it incorrect Arabic.',
    '3:clarification':'The lists follow past-verb patterns: first فَعَلَ, then فَعِلَ, then فَعُلَ. Judge each مصدر against its own verb and meaning, not just the مصدر’s visible shape.',
  },copyParts:{'0:3':['معتل العين: فَعْل مثل سَيْر؛ فِعَال مثل قِيَام؛ فِعَالَة مثل نِيَاحَة.','الدال على امتناع: فِعَال. أَبَى إِبَاءً؛ نَفَرَ نِفَارًا؛ جَمَحَ جِمَاحًا؛ أَبَقَ إِبَاقًا.'],
    '0:4':['A weak عين gives three recorded alternatives to فُعُول: travelling, standing and lamentation illustrate فَعْل، فِعَال and فِعَالَة respectively.','A sense of refusal or resistance selects فِعَال with initial kasra. These four examples preserve the complete family.'],
    '3:2':['Learn these four attested pairs together: their past forms share فَعَلَ, but their verbal nouns do not share one pattern.','Four more فَعَلَ pairs. Sukūn, long vowels and endings belong to the attested مصدر, not a freely chosen substitute.','These فَعَلَ verbs retain their recorded مصادر even where the basic map suggests another form.','Final-weak فَعَلَ verbs also require their recorded مصادر. Notice the different endings rather than replacing them with one common pattern.'],
    '3:3':['These four past forms have عين kasra, فَعِلَ. Their recorded مصادر are listed as exceptions to the preceding rules.','The remaining فَعِلَ examples name strength, acceptance and mercy. Keep each verb and its own مصدر together.'],
    '3:4':['These فَعُلَ examples do not take either regular فُعُولَة or فَعَالَة. Their attested forms must be learned.','Three further فَعُلَ pairs show why the regular map cannot replace knowledge of usage.'],
  },boxCopy:{'0:1':['فَعَلَ اللازم: فُعُول، ما لم يتدخل سبب آخر.'],'3:0':['السماعي يُحفظ ولا يُقاس عليه.']},
  boxExamples:{'2:0':{heading:'Two regular families',items:[['صَعُبَ صُعُوبَة','Difficulty: فُعُولَة'],['عَذُبَ عُذُوبَة','Sweetness: فُعُولَة'],['بَلُغَ بَلَاغَة','Eloquence: فَعَالَة'],['فَصُحَ فَصَاحَة','Fluency: فَعَالَة'],['صَرُحَ صَرَاحَة','Clarity: فَعَالَة']]}},
  tableCopy:{'1:1':{0:['Turning or tossing','فَعَلَان','جَالَ جَوَلَانًا؛ غَلَى غَلَيَانًا.'],1:['Illness','فُعَال','مَشَى بطنه مُشَاء: his bowels became loose.'],2:['Travel','فَعِيل','رَحَلَ رَحِيلًا؛ ذَمَلَ ذَمِيلًا.'],3:['Sound','فُعَال or فَعِيل','صَرَخَ صُرَاخًا؛ عَوَى الكلب عُوَاءً؛ صَهَلَ الفرس صَهِيلًا؛ نَهَقَ الحمار نَهِيقًا؛ زَأَرَ الأسد زَئِيرًا.'],4:['Trade or office','فِعَالَة','تَجَرَ تِجَارَة؛ عَرَفَ على القوم عِرَافَة؛ سَفَرَ بينهم سِفَارَة.']}},
  visuals:{'1:3':v('Same pattern, different meanings',['مُشَاء','Illness'],['صُرَاخ','Sound'])},
  exampleGroups:{
    '3:1':examples('Attested فَعَلَ pairs',['طَلَبَ طَلَبًا','Seeking'],['نَبَتَ نَبَاتًا','Growing'],['كَتَبَ كِتَابًا','Writing'],['حَرَسَ حِرَاسَة','Guarding']),
    '3:2':examples('Attested فَعَلَ pairs',['شَكَرَ شُكْرًا','Thanking'],['حَسَبَ حُسْبَانًا','Reckoning'],['ذَكَرَ ذِكْرًا','Remembering'],['كَتَمَ كِتْمَانًا','Concealing']),
    '3:3':examples('Attested فَعَلَ pairs',['كَذَبَ كَذِبًا','Lying'],['غَلَبَ غَلَبَة','Prevailing'],['حَمَى حِمَايَة','Protecting'],['غَفَرَ غُفْرَانًا','Forgiving']),
    '3:4':examples('Attested فَعَلَ pairs',['عَصَى عِصْيَانًا','Disobeying'],['قَضَى قَضَاءً','Deciding'],['هَدَى هِدَايَة','Guiding'],['رَأَى رُؤْيَة','Seeing']),
    '3:5':examples('Attested فَعِلَ pairs',['لَعِبَ لَعِبًا','Playing'],['نَضِجَ نُضْجًا','Ripening'],['كَرِهَ كَرَاهِيَة','Disliking'],['سَمِنَ سِمَنًا','Growing fat']),
    '3:6':examples('Attested فَعِلَ pairs',['قَوِيَ قُوَّة','Strength'],['قَبِلَ قَبُولًا','Acceptance'],['رَحِمَ رَحْمَة','Mercy']),
    '3:7':examples('Attested فَعُلَ pairs',['كَرُمَ كَرَمًا','Generosity'],['عَظُمَ عِظَمًا','Greatness'],['مَجُدَ مَجْدًا','Glory']),
    '3:8':examples('Attested فَعُلَ pairs',['حَسُنَ حُسْنًا','Goodness'],['حَلُمَ حِلْمًا','Forbearance'],['جَمُلَ جَمَالًا','Beauty'])},
  analysisPrompt:'Match each group with its regular مصدر pattern.',analysisHint:'Consider motion, illness and travel.',
  analysisLabels:{'فَعَلَان، بفتحات — فَعَلَان, all فتحات':'فَعَلَان','فُعَال، بالضم — فُعَال, with ضمة':'فُعَال'},
  analysisText:{'table-1-1':{'جَالَ جَوَلَانًا، وغَلَى غَلَيَانًا':'جَالَ جَوَلَانًا؛ غَلَى غَلَيَانًا','مَشَى بَطْنُه مُشَاء':'مَشَى بطنه مُشَاء','رَحَلَ رَحِيلًا، وذَمَلَ ذَمِيلًا':'رَحَلَ رَحِيلًا؛ ذَمَلَ ذَمِيلًا'}},
  }),
  'as-11/l1': plan(37, 'Underived Nouns and Derivation', [
    [c('جامد: not taken from another word',0,1,2),c('Perceptible things and abstract meanings',r(3,0,1),4)],
    [c('مشتق: an entity viewed through a quality',0,1,2),c('The usual starting point is a مصدر',3,4,5),c('A quality and its bearer',clarification)],
    [c('Concrete sources are also attested',0,1,2,r(3,0)),c('Abundance and resemblance',r(3,1,2)),c('Adding a named substance',r(3,3,4))],
    [c('Derivation links meaning and form',0,1),c('The same roots, in the same order',r(2,0),3,4,5),c('Reordering or replacing a root',r(2,1,2))],
    [c('Two accounts of the starting point',0,1,2),c('Meaning versus conjugational order',3)],
  ], [
    ['جامد','Not derived from another word; it can name a thing or an abstract meaning.'],
    ['مشتق','Taken from another word, naming an entity with a quality in view.'],
    ['صغير','Shared roots in the same order; the focus of this morphology course.'],
    ['Origin','The book follows the Baṣran مصدر account and records the Kūfan verb account.'],
  ], {copy:{
    '0:0':'This division asks whether the noun is derived from another word.',
    '0:2':'A جامد may name a perceptible thing or an abstract meaning. Abstractness alone does not make a noun derived.',
    '0:4':'رجل names an entity, but not through a derived quality. The distinction is how the word names its referent, not whether its referent is a person.',
    '1:0':'A derived noun keeps a quality in view while naming an entity.',
    '1:2':'عالِم: one with عِلْم, knowledge. ظَريف: one with ظَرْف, wit. مَضْروب: something affected by ضَرْب, striking. Each differs from the name of the quality or event itself.',
    '1:3':'The book adopts the Baṣran account of derivation.',
    '1:5':'The usual source is an abstract مصدر: فَهِمَ from الفهم and نَصَرَ from النصر. Here اشتقاق includes deriving verbs; the preceding مشتق definition described nouns.',
    '1:clarification':'عِلْم names knowledge; عالِم names someone through that quality. This is not simply abstract versus concrete: قلم is a concrete جامد. Derivation and the way the quality is understood decide the classification.',
    '2:0':'The book treats derivation from concrete nouns as exceptional.',
    '2:2':'Its recorded examples show that “rare” does not mean impossible.',
    '3:1':'Two conditions: corresponding meanings and a change of form. This account distinguishes three kinds by what happens to the root letters.',
    '3:4':'الصغير is the principal concern of the morphologist, الصرفي.',
    '3:5':'الكبير and الأكبر belong here to lexical study; the following chapter concentrates on الصغير. “Same letters” means shared roots, not identical complete spellings.',
    '4:0':'The two schools give different kinds of priority.',
    '4:2':'The book follows the first view, المصدر, attributed to the Baṣrans and adopted by its morphologists. It also records the Kūfan view, الفعل.',
    '4:3':'Baṣran argument: the مصدر denotes an event without tense, so its meaning is simpler than the verb’s event plus time. Kūfan argument: the مصدر comes after the verb in التصريف, so the verb is prior in that ordering.',
  },boxCopy:{'1:4':['الاشتقاق غالبا من المصدر: فَهِمَ من الفهم.'],'3:0':['الاشتقاق: أخذ كلمة من أخرى، مع تناسب في المعنى وتغيير في اللفظ.'],'4:1':['البصريون: الأصل المصدر.','الكوفيون: الأصل الفعل.']},
  tableCopy:{'0:3':{0:['محسوسة','Perceptible entities, not necessarily events.','قَلَم، رَجُل، شَجَر، بَقَر'],1:['معنوية','An abstract meaning without viewing it as a bearer’s quality.','مصادر: نَصْر، فَهْم، قِيام، قُعُود. The source also lists ضَوْء، نُور، زَمان as non-maṣdar meanings.']},
    '2:3':{0:['أَوْرَقَتِ الأشجارُ','الوَرَق','The trees put out leaves.'],1:['أَسْبَعَتِ الأرضُ','السَّبُع','The land abounded in beasts of prey.'],2:['عَقْرَبْتُ الصُّدْغَ','العَقْرَب','I curled the temple hair like a scorpion.'],3:['نَرْجَسْتُ الدواءَ','النَّرْجِس','I put narcissus into the medicine.'],4:['فَلْفَلْتُ الطعامَ','الفُلْفُل','I put pepper into the food.']},
    '3:2':{0:['صغير','Same roots and order.','عَلِمَ وعالِم من العلم؛ فَهِمَ من الفهم.'],1:['كبير','Same roots; different order.','جَبَذَ من الجَذْب: metathesis, قَلْب.'],2:['أكبر','Most roots shared; the rest correspond.','نَعَقَ من النَّهْق: ع and ه have related places of articulation.']}},patternTables:['2:3'],
  visuals:{'1:2':v('Knowledge and its bearer',['عِلْم','The meaning'],['عالِم','An entity with that quality']),'4:1':v('Two kinds of priority',['المصدر','Simpler meaning'],['الفعل','Earlier in conjugational ordering'])},
  analysisPrompt:'Which concrete noun underlies each verb?',analysisHint:'Look for leaves, beasts of prey, or the scorpion comparison.',
  }),
  'as-11/l2': plan(38, 'The Ten Derivations', [
    [c('Three verbs and seven noun categories',0,1,2,3),c('Count time and place separately',4)],
    [c('Three verb forms from ضرب',0,r(1,0,1,2)),c('Doer and affected entity',r(1,3,4)),c('Why this verb supplies no regular صفة مشبهة',r(1,5),2),c('Comparison, time, place and instrument',r(1,6,7,8)),c('Two vowels distinguish place and tool',clarification)],
    [c('Two appended transformations',0,1,4),c('Relation and diminutive',2,3)],
    [c('Intensification belongs with the doer',0,1)],
  ], [
    ['Ten','Past, imperfect and imperative, plus seven noun categories.'],
    ['Seven','Doer, affected entity, settled quality, comparison, time, place and instrument.'],
    ['مبالغة','Counted with اسم الفاعل in this inventory.'],
    ['Appended','المنسوب and المصغر accompany the list without joining its ten derivations.'],
  ], {copy:{
    '0:0':'The book derives this inventory from the مصدر.',
    '0:2':'Ten categories in all.',
    '0:3':'The verbs are الماضي, past; المضارع, imperfect; and الأمر, imperative. Their forms were introduced earlier.',
    '0:4':'اسم الفاعل includes its intensive صيغ المبالغة. Then come اسم المفعول، الصفة المشبهة، اسم التفضيل، اسم الزمان، اسم المكان and اسم الآلة. Time and place count separately even when their form is identical. Module 12 develops these seven categories.',
    '1:0':'Use ضَرْب, “striking”, to compare the inventory.',
    '1:2':'The regular صفة مشبهة in this account comes from an intransitive verb. ضَرَبَ is transitive, so this table leaves its slot empty. حَسَن, “good-looking”, illustrates the category using another verb; it is not derived from ضرب.',
    '1:clarification':'مَضْرِب names a time or place: م fatḥa, ر kasra. مِضْرَب names a tool: م kasra, ر fatḥa. Both vowel changes matter. The empty صفة مشبهة slot concerns regular formation from this transitive verb, not every possible lexical use of its root.',
    '2:1':'The source appends two transformations without counting them among these ten.',
    '2:2':'المنسوب marks relation with doubled يّ: مِصْر becomes مِصْرِيّ. رجلٌ مِصْرِيٌّ means an Egyptian man.',
    '2:3':'المصغر can suggest small size, fewness, youth or slightness: رَجُل becomes رُجَيْل, a little man.',
    '2:4':'Both reshape a word. Their attachment to this list uses the book’s restricted sense of اشتقاق; each has its own treatment.',
    '3:0':'ضَرَّاب means one who strikes a great deal. This intensive form is counted with the doer ضَارِب, so it adds no eighth noun category.',
    '3:1':'That is why both appear in one table entry.',
  },boxCopy:{'0:1':['من المصدر: ثلاثة أفعال وسبعة أسماء.'],'2:0':['يُلحق بها المنسوب والمصغر.']},
  tableCopy:{'1:1':{0:['الماضي','ضَرَبَ'],1:['المضارع','يَضْرِبُ'],2:['الأمر','اضْرِبْ'],3:['اسم الفاعل والمبالغة','ضَارِب؛ ضَرَّاب'],4:['اسم المفعول','مَضْرُوب'],5:['الصفة المشبهة','No regular form here. Compare حَسَن from another verb.'],6:['اسم التفضيل','أَضْرَبُ'],7:['الزمان والمكان','مَضْرِب'],8:['اسم الآلة','مِضْرَب']}},
  visuals:{'0:1':v('Seven noun categories',['فاعل، مفعول، صفة مشبهة','Agent, patient, settled quality'],['تفضيل، زمان، مكان، آلة','Comparison, time, place, tool']),'1:4':v('Read both vowels',['مَضْرِب','Time or place'],['مِضْرَب','Instrument']),'3:0':v('One category, two forms',['ضَارِب','One who strikes'],['ضَرَّاب','One who strikes a great deal'])},
  analysisPrompt:'Classify these three verb forms.',analysisHint:'Distinguish past, imperfect and imperative.',
  }),
};
export const checks = {
  'as-11/l5':[
    q('What do انفعل، افتعل، افعلّ and six-letter stems share?', ['Regular initial همزة وصل.','Added initial ت.','All are intransitive.','All have repeated roots.'],'Inspect the pattern’s opening.'),
    q('Why does ربّى give تربية?', ['Weak final root.','Initial hamza root.','Repeated root pairs.','Weak middle root.'],'The adjustment concerns لام, not عين.'),
    q('What is the ة in إقامة?', ['Original root.','Emphasis.','Compensation for a deleted alif.','A marker of female gender.'],'Follow the source’s hollow-verb derivation.'),
    q('Why does اطّيّر keep the تفعّل مصدر?', ['Weak عين.','Adjacent repeated roots alone.','Six-letter root.','Its supplied hamza does not define the pattern.'],'Undo assimilation: تطيّر.'),
    q('Why is مياسرة the regular مصدر of ياسر?', ['Weak final root.','No regular مصدر.','Initial ي excludes فِعَال in this pattern.','Repeated root pairs.'],'The condition concerns فاء.'),
  ],
  'as-11/l3':[
    q('Which bare past pattern is intransitive here?', ['فَعَلَ','فَعِلَ','All three can be transitive.','فَعُلَ'],'Read the عين vowel.'),
    q('Which two regular مصدر patterns belong to فَعُلَ?', ['فَعَل؛ فَعْل','فِعَالَة؛ فُعْلَة','فُعُولَة؛ فَعَالَة','فُعُول؛ فَعْل'],'Think of سهولة and بلاغة.'),
    q('Why does خياطة take فِعَالَة?', ['Occupation.','Colour.','Intransitivity alone.','A doubled root.'],'The exception is semantic.'),
    q('Why does حَمِرَ حُمْرة take فُعْلَة?', ['Physical action.','Colour.','Occupation.','Governing.'],'It names redness.'),
  ],
  'as-11/l4':[
    q('Why does قيام leave the base فُعُول pattern?', ['Weak عين.','Refusal.','Sound.','Transitivity.'],'Inspect the root of قام.'),
    q('What unites عواء and صهيل?', ['Illness: فُعَال.','Motion: فَعَلَان.','Sound: فُعَال or فَعِيل.','Travel: فَعِيل.'],'Both name animal calls.'),
    q('Which pattern is فصاحة?', ['فُعُول','فِعَالَة','فَعَالَة','فُعُولَة'],'Read the first vowel.'),
    q('Why is كَرُمَ كَرَمًا سماعي here?', ['Its rule gives فَعَل.','Its rule gives فُعُولَة or فَعَالَة.','Its rule gives فَعْل.','Its rule gives فُعُول.'],'Compare with the فَعُلَ map.'),
  ],
  'as-11/l1':[
    q('Why is قيام جامد in this account?', ['Every abstract noun must be جامد.','It has no related verb.','It names a perceptible object.','It names the event without viewing it in a bearer.'],'Abstractness alone does not decide derivation.'),
    q('What does مع ملاحظة صفة add?', ['An entity is named with a quality in view.','It must serve as a grammatical adjective.','It must be feminine.','A related verb must be in use.'],'Compare علم with عالم.'),
    q('What does عقربت الصدغ mean?', ['I removed the temple hair.','I curled the temple hair like a scorpion.','I placed a scorpion on the temple.','A scorpion stung the temple.'],'The concrete noun supplies a comparison.'),
    q('نعق from النهق illustrates which kind?', ['No derivation.','الأكبر: most roots shared; others correspond.','الصغير: same roots and order.','الكبير: same roots, reordered.'],'Compare ع with ه.'),
    q('What priority does the Kūfan argument use?', ['Simpler meaning.','Greater frequency.','Inability of a مصدر to stand alone.','The مصدر follows the verb in التصريف.'],'Distinguish ordering from simplicity.'),
  ],
  'as-11/l2':[
    q('How are the ten categories divided?', ['Three verbs and seven nouns.','Five of each.','Four verbs and six nouns.','Two verbs and eight nouns.'],'Time and place count separately.'),
    q('Why is the regular صفة مشبهة slot empty for ضرب?', ['Its مصدر is irregular.','ضرب is transitive; this formation uses an intransitive verb.','ضرب is frozen.','Its regular form was simply forgotten.'],'حسن is supplied from another verb.'),
    q('How are المنسوب and المصغر treated?', ['Two abstract underived nouns.','Appended to the inventory, outside its ten.','An eighth and ninth noun category.','Two kinds of مصدر.'],'Use the source’s restricted inventory.'),
    q('Why are ضراب and ضارب grouped together?', ['Intensification is counted with اسم الفاعل.','ضراب is a plural.','ضراب is the صفة مشبهة.','They are spelling variants.'],'Their meanings differ, but the inventory groups them.'),
  ],
};
export const quizzes = {
  'as-11/l5':[q('What is the regular مصدر of أفعل with sound عين?'),q('Which operation forms اصطفاء?', ['Transfer عين’s vowel to فاء.','Third-letter kasra; add alif before the last.','Fourth-letter ḍamma.','Drop تفعيل’s ي and add ة.']),q('Which operation forms تدحرجًا?', ['فَعْلَلَة.','فِعْلَال.','Added ت: fourth-letter ḍamma.','Initial وصل: third-letter kasra.']),q('Which two regular مصدر forms belong to فاعل?'),q('Why is زلزل زلزالًا regular?'),q('How is كذّب كذّابًا classified here?', ['Outside the regular pattern.','The regular pattern.','The underlying form.','Always preferred over تكذيب.'])],
  'as-11/l3':[q('Which transitivity is possible for فَعِلَ?'),q('What is the base مصدر of فَعَلَ اللازم?'),q('Which rule does ردّ ردّا illustrate?'),q('What is the pattern of وِلَايَة?'),q('Why does صعد صعودا take فُعُول?', ['Occupation.','Sound.','Action with a فاعِل description.','Colour.']),q('Which past category supplies شلّ شللا?')],
  'as-11/l4':[q('What is the default مصدر of فَعَلَ اللازم?'),q('Which meaning explains أبى إباء?'),q('Which rule does جال جولانا illustrate?'),q('Which meaning explains مشى بطنه مشاء?'),q('Which pair is regular for فَعُلَ?'),q('How is a form outside these rules learned?')],
  'as-11/l1':[q('What defines جامد?'),q('Classify قلم، شجر and بقر.'),q('What does الاشتقاق الصغير retain?'),q('جبذ from الجذب illustrates which kind?'),q('Why do the Baṣrans give the مصدر priority?', ['Dictionary order.','No case endings.','Only wording connects verb and مصدر.','It denotes an event alone, a simpler meaning.']),q('Which noun underlies أسبعت الأرض?')],
  'as-11/l2':[q('Which three verb forms are derived?'),q('What is اسم المفعول of ضرب?'),q('Which form names the instrument?'),q('Which form names the time or place?'),q('What does رجل مصري illustrate?'),q('What is اسم التفضيل of ضرب?')],
};
export const practice = {
  'as-11/l5':[q('What is the regular مصدر pattern of تفاعل?', ['تَفَاعُل','تَفَعُّل','تَفَعْلُل','مُفَاعَلَة'],'Change the fourth letter to ḍamma.')],
  'as-11/l3':[q('What stem lengths organise these verb structures?', ['Three or four only.','Three or five only.','Four, five or six only.','Three, four, five or six.'],'This counts stem letters, not original roots.')],
  'as-11/l4':[q('Which rule does نهض نهوضا illustrate?', ['Travel: فَعِيل.','Motion: فَعَلَان.','Intransitive فَعَلَ: فُعُول.','Refusal: فِعَال.'],'It follows the base pattern.')],
  'as-11/l1':[q('How does the source divide جامد nouns?', ['Singular and plural.','Perceptible entities and abstract meanings.','Entities and derived qualities.','Time and place.'],'The division does not depend on number.')],
  'as-11/l2':[q('How many derivations are in this inventory?', ['Three.','Twelve.','Ten.','Seven.'],'Add the three verbs and seven noun categories.')],
};
