import { authoredLesson, source as S, choice as C, order as O, recall as R, selectGroup as G } from './activities.js';
// These sentence IDs are reserved: no guided lesson or review may use them.
// An assessment accepts the first submission, then gives teaching feedback.
function checkpoint(unit, stage, title, source, chunks, hint, paraphrase, exercises, kind='checkpoint') {
  return authoredLesson({id:`${kind}-${unit}`,kind,unit,stage,title,titleAr:kind==='cumulative'?'قِرَاءَةٌ مُتَّصِلَةٌ':'نَصٌّ جَدِيدٌ',archetype:kind==='cumulative'?'extensive':'unseen-challenge',source,chunks,
    context:kind==='cumulative'?'Read the connected passage once for its overall meaning. Open help only when you need it.':'Try this reserved passage before opening help. Your first answers determine the checkpoint evidence; corrections are for learning.',
    objective:'Apply the unit’s language to a previously unstudied source passage.',
    support:{vocabulary:hint,structure:'Identify each action and its participant before joining the clauses.',paraphrase,explanation:paraphrase},
    exercises:exercises.map(e=>({...e,phase:'assess',assessment:true,useSource:true,contextId:`reserved-${source.bookId}-${source.chapterId}-${source.sentenceIds.join('-')}`})),
    minutes:kind==='cumulative'?12:7,flow:exercises.map(e=>e.id),reserved:true});
}
export const CHECKPOINTS = [
  checkpoint('daily-actions',1,'A new morning routine',S('qiraah-v1','ch1','qr1-1-006','qr1-1-007'),['أَرْجِعُ إِلَى الْبَيْتِ','وَأَتْلُو','ثُمَّ أَخْرُجُ إِلَى الْبُسْتَانِ وَأَجْرِي'],'أَتْلُو: read/recite. الْبُسْتَان: garden.','يَعُودُ إِلَى بَيْتِهِ وَيَقْرَأُ ثُمَّ يَذْهَبُ إِلَى الْبُسْتَانِ.',[
    C('gist','comprehension','assess','','Which happens after reading?',[['الخُرُوجُ إِلَى الْبُسْتَانِ','ثم introduces the later outing.'],['النَّوْمُ','Sleeping is not stated.'],['الدُّخُولُ إِلَى الْمَدْرَسَةِ','School is not a destination in this excerpt.']],['return','thumma-sequence'],'Find ثم.'),
    O('sequence','assess','Rebuild the order of events.',['أَرْجِعُ إِلَى الْبَيْتِ','وَأَتْلُو','ثُمَّ أَخْرُجُ وَأَجْرِي'],['return','go-out'],'The return precedes reading; ثم marks the outing.'),
    R('destination','assess','','اُكْتُبِ الْمَكَانَ الَّذِي يَخْرُجُ إِلَيْهِ.','البستان','skill-comprehension','Look after إلى in the second sentence.','The garden is the destination of the outing.'),
  ]),
  checkpoint('time-and-sequence',1,'Waiting for the journey',S('qiraah-v1','ch8','qr1-8-003','qr1-8-004'),['اِسْتَيْقَظْتُ قَبْلَ السَّحَرِ','وَبَقِيتُ أَنْتَظِرُ سَاعَةَ السَّفَرِ','وَاسْتَيْقَظَ أَهْلُ الْبَيْتِ مُبَكِّرِينَ'],'السَّحَر: time before dawn.','اِسْتَيْقَظَ الطِّفْلُ أَوَّلًا وَانْتَظَرَ وَقْتَ السَّفَرِ.',[
    C('time','comprehension','assess','','مَتَى اسْتَيْقَظَ الطِّفْلُ؟',[['قَبْلَ السَّحَرِ','Before modifies waking.'],['بَعْدَ الرِّحْلَةِ','He is still waiting for departure.'],['عِنْدَ الْغُرُوبِ','Sunset is not stated.']],['before','wake'],'Read the first time phrase.'),
    R('waiting','assess','','أَكْمِلْ مِنَ النَّصِّ: بَقِيتُ … سَاعَةَ السَّفَرِ.','أنتظر','wait','He has woken but cannot leave yet.','أنتظر means I wait.'),
    O('order','assess','Build waking → waiting → the household waking.',['اِسْتَيْقَظْتُ','وَانْتَظَرْتُ السَّفَرَ','ثُمَّ اسْتَيْقَظَ أَهْلُ الْبَيْتِ'],['wake','early'],'The narration presents the child’s wait before the household activity.'),
  ]),
  checkpoint('description-and-manner',1,'A river and its water',S('qiraah-v1','ch20','qr1-20-005','qr1-20-006'),['يَجْرِي مِنْ تَحْتِ الْقَرْيَةِ نَهْرٌ','مَاؤُهُ نَقِيٌّ شَفَّافٌ','لِأَنَّهُ يَجْرِي عَلَى الرَّمْلِ'],'نَقِيٌّ شَفَّافٌ: clear and transparent. الرَّمْل: sand.','مَاءُ النَّهْرِ صَافٍ لِأَنَّهُ يَجْرِي عَلَى الرَّمْلِ.',[
    C('description','comprehension','assess','','What is described as clear?',[['مَاءُ النَّهْرِ','ماؤه names the water belonging to the river.'],['الْقَرْيَةُ','The village locates the river.'],['النَّاسُ','No people are described here.']], 'skill-reference','Expand the suffix in ماؤه.'),
    G('descriptors','assess','','Select the water’s two descriptions.',['مَاؤُهُ','نَقِيٌّ','شَفَّافٌ','لِأَنَّهُ'],[1,2],'skill-chunking','Both adjectives describe water.'),
    R('reason','assess','','اُكْتُبِ الْكَلِمَةَ الَّتِي تُقَدِّمُ السَّبَبَ مَعَ ضَمِيرِهَا.','لأنه','because','It starts the second clause.','لأنه introduces the stated reason.'),
  ]),
  checkpoint('people-and-reference',2,'A worker leaves something behind',S('qiraah-v1','ch13','qr1-13-001','qr1-13-002','qr1-13-003','qr1-13-004'),['اِسْتَأْجَرَ رَجُلٌ قَوْمًا','فَأَعْطَاهُمْ أَجْرَهُمْ','وَلَكِنَّ رَجُلًا لَمْ يَأْخُذْ أَجْرَهُ'],'اِسْتَأْجَرَ: hired. أَجْر: wages.','عَمِلَ قَوْمٌ وَأَخَذُوا الْأُجُورَ إِلَّا رَجُلًا تَرَكَ أَجْرَهُ وَذَهَبَ.',[
    C('referent','pronoun_reference','assess','','إِلَى مَاذَا تَعُودُ ـهُ فِي تَرَكَهُ؟',[['أَجْرِ الْعَامِلِ','He leaves his wages.'],['صَاحِبِ الْعَمَلِ','The abandoned object is the wage, not the employer.'],['الْقَوْمِ كُلِّهِمْ','The singular suffix follows أجره.']], 'pronoun-hu','Follow the object of لم يأخذ.'),
    O('roles','assess','Expand the two actors: the employer first, then the worker.',['أَعْطَى صَاحِبُ الْعَمَلِ الْأُجُورَ','وَلَكِنَّ عَامِلًا تَرَكَ أَجْرَهُ','وَذَهَبَ'],['give','take'],'The employer gives; one worker leaves without taking.'),
    R('time','assess','','أَكْمِلْ مِنَ النَّصِّ: … فَرَغُوا مِنْ شُغْلِهِمْ جَاؤُوا إِلَيْهِ.','ولما','lamma','Use the connector with the initial و.','ولما links finishing work to coming for payment.'),
  ]),
  checkpoint('narrative-links',2,'Preparing a race',S('qiraah-v1','ch10','qr1-10-001','qr1-10-002','qr1-10-003','qr1-10-004','qr1-10-005'),['اخْتَارَ الْمُعَلِّمُ الطُّلَّابَ','وَأَوْقَفَهُمْ فِي صُفُوفٍ','فِي كُلِّ صَفٍّ ثَلَاثَةٌ'],'أَقْرَان وَأَكْفَاء: peers and equals.','اخْتَارَ الْمُعَلِّمُ أَرْبَعَةً وَعِشْرِينَ طَالِبًا وَرَتَّبَهُمْ فِي صُفُوفٍ.',[
    C('first','comprehension','assess','','مَاذَا فَعَلَ الْمُعَلِّمُ أَوَّلًا؟',[['اخْتَارَ الطُّلَّابَ.','أولًا explicitly marks selection.'],['أَعْلَنَ الْفَائِزَ.','The race has not been described as run yet.'],['رَجَعَ إِلَى بَيْتِهِ.','No return is mentioned.']], 'skill-clause-links','The text names the first step.'),
    O('stages','assess','Put selecting before arranging, then the detail about each row.',['اخْتَارَ الطُّلَّابَ','فَأَوْقَفَهُمْ فِي صُفُوفٍ','فِي كُلِّ صَفٍّ ثَلَاثَةٌ'],'skill-comprehension','The last phrase describes the arrangement, not another race.'),
    R('who','assess','','إِلَى مَنْ يَعُودُ هُمْ فِي أَوْقَفَهُمْ؟ اُكْتُبْ: الطُّلَّاب أَوِ الْمُعَلِّمُون.','الطلاب','skill-reference','Who did the teacher choose?','The chosen students are arranged in rows.'),
  ]),
  checkpoint('description-in-stories',2,'A repeated evening routine',S('qiraah-v1','ch16','qr1-16-003','qr1-16-004','qr1-16-005','qr1-16-006','qr1-16-007'),['كَانَ يَذْهَبُ كُلَّ يَوْمٍ','وَيَرْعَى الْمَاشِيَةَ','وَيَرْجِعُ بِهَا','فَيَحْلِبُهَا وَيَسْقِي أَهْلَهُ'],'الْمَاشِيَة: livestock. يَحْلِبُ: milks.','يَرْعَى الرَّجُلُ الْحَيَوَانَاتِ نَهَارًا وَيَعُودُ مَسَاءً لِيَسْقِيَ أَهْلَهُ اللَّبَنَ.',[
    C('habit','comprehension','assess','','هَلْ هَذَا حَدَثٌ وَاحِدٌ أَمْ عَادَةٌ؟',[['عَادَةٌ تَتَكَرَّرُ','كان يذهب كل يوم makes recurrence explicit.'],['حَدَثٌ وَاحِدٌ','Every day rules out a one-off reading.']], 'kana-habit','Notice كل يوم.'),
    R('object','assess','','مَا الَّذِي يَرْجِعُ بِهِ؟ اُكْتُبِ الِاسْمَ مِنَ النَّصِّ.','الماشية','pronoun-ha','Expand بها and يحلبها.','Both feminine singular suffixes resume الماشية.'),
    O('routine','assess','Rebuild going out → tending → returning → providing milk.',['يَذْهَبُ إِلَى الْمَرْعَى','فَيَرْعَى الْمَاشِيَةَ','وَيَرْجِعُ بِهَا','فَيَسْقِي أَهْلَهُ اللَّبَنَ'],'kana-habit','The routine is connected across the clauses.'),
  ]),
  checkpoint('long-dependencies',3,'A description inside a description',S('qiraah-v2','ch67','qr2-67-011','qr2-67-012'),['يَخْرُجُ ذَلِكَ الْقُطْنُ','الَّذِي بِهِ لِبَاسُكُمْ','وَسَرَابِيلُ تَقِيكُمُ الْحَرَّ'],'سَرَابِيل: garments. تَقِي: protects. The speaker is the earth.','يَخْرُجُ الْقُطْنُ مِنَ الْأَرْضِ وَيُصْنَعُ مِنْهُ اللِّبَاسُ الَّذِي يَحْمِي النَّاسَ مِنَ الْحَرِّ.',[
    C('head','pronoun_reference','assess','','إِلَى مَاذَا يَعُودُ بِهِ؟',[['الْقُطْنِ','The relative clause resumes the cotton.'],['الْحَرِّ','Heat occurs later as what garments protect against.'],['الشِّتَاءِ','Winter is a time phrase.']], 'relative-alladhi','Return to the head before الذي.'),
    O('dependency','assess','Reconstruct material → use → benefit.',['يَخْرُجُ الْقُطْنُ','فَنَصْنَعُ مِنْهُ اللِّبَاسَ','لِيَقِيَنَا الْحَرَّ'],'relative-alladhi','Keep the cotton as the material and garments as the protection.'),
    R('material','assess','','مَا مَادَّةُ اللِّبَاسِ فِي النَّصِّ؟','القطن','skill-comprehension','The head noun is a crop.','Cotton connects the source with the manufactured garments.'),
  ]),
  checkpoint('change-and-continuation',4,'Beginning to explain',S('qiraah-v2','ch61','qr2-61-004'),['أَخَذَ سَعِيدٌ يَتَجَوَّلُ','يُحَدِّثُ رَشِيدًا','عَنِ الْقِطَارِ وَنِظَامِ الْمَحَطَّةِ'],'يَتَجَوَّل: walks around.','بَدَأَ سَعِيدٌ يَمْشِي فِي الْمَحَطَّةِ وَيَشْرَحُ لِرَشِيدٍ نِظَامَهَا.',[
    C('onset','comprehension','assess','','مَا مَعْنَى أَخَذَ هُنَا؟',[['بَدَأَ','An imperfect action follows أخذ.'],['تَنَاوَلَ شَيْئًا','No object being picked up follows.']], 'akhadha-imperfect','Look for the imperfect verb.'),
    R('listener','assess','','مَنْ يَسْتَمِعُ إِلَى سَعِيدٍ؟','رشيد','skill-reference','Identify the object of يحدث.','Rashid receives the explanation; Said gives it.'),
    O('simple','assess','Rebuild beginning → movement → accompanying explanation.',['بَدَأَ سَعِيدٌ يَتَجَوَّلُ','وَهُوَ يُحَدِّثُ رَشِيدًا','عَنِ الْقِطَارِ'],['akhadha-imperfect','hal-processing'],'The explanation accompanies the walking.'),
  ]),
  checkpoint('reason-and-judgement',5,'Where the value came from',S('qiraah-v2','ch46','qr2-46-003','qr2-46-004','qr2-46-005','qr2-46-006','qr2-46-007','qr2-46-008','qr2-46-009'),['هَلْ تَعْرِفُ تَارِيخَهُ؟','كَمْ عَمِلَ فِيهِ مِنَ الْأَيْدِي؟','زَرَعَ الزَّرَّاعُ الْقُطْنَ','وَتَحَمَّلَ عَنَاءً شَدِيدًا'],'The object being addressed is a new shirt. الأيدي: hands, here workers.','يُذَكِّرُ الْكَاتِبُ بِالْعَمَلِ الْكَثِيرِ وَرَاءَ صُنْعِ الْقَمِيصِ.',[
    C('claim','interpretation_choice','assess','','لِمَاذَا يَسْأَلُ الْكَاتِبُ عَنِ الْأَيْدِي؟',[['لِيُلْفِتَ إِلَى عَمَلِ النَّاسِ.','Hands stand for the people doing the work.'],['لِيَصِفَ لَوْنَ الْأَيْدِي.','Colour is not being discussed.'],['لِيَقُولَ إِنَّ الْقَمِيصَ بِلَا تَارِيخٍ.','The questions invite reconstruction of its history.']], 'metonymic-work','Connect hands with عمل and تعب.'),
    O('argument','assess','Summarise garment → labour → appreciation.',['وَرَاءَ الْقَمِيصِ','عَمَلُ كَثِيرٍ مِنَ النَّاسِ','فَيَنْبَغِي أَنْ نُقَدِّرَهُ'],'metonymic-work','The final appreciation is an inference supported by the repeated labour questions.'),
    R('beginning','assess','','مَاذَا زَرَعَ الزَّرَّاعُ؟','القطن','skill-comprehension','Read the beginning of the garment’s history.','Cotton is the initial material.'),
  ]),
  checkpoint('rhetoric-and-inference',5,'A voice from beneath your feet',S('qiraah-v2','ch67','qr2-67-001','qr2-67-002','qr2-67-003','qr2-67-004','qr2-67-005'),['أَنَا تُرَابٌ','النَّاسُ يَنْتَفِعُونَ بِي','ثُمَّ يَحْتَقِرُونَنِي'],'يَطَؤُنِي: tread on me. يَحْتَقِرُون: look down on.','يَقُولُ التُّرَابُ إِنَّ النَّاسَ يَسْتَفِيدُونَ مِنْهُ وَلَكِنَّهُمْ يَحْتَقِرُونَهُ.',[
    C('contrast','interpretation_choice','assess','','مَا التَّنَاقُضُ الَّذِي يَشْكُو مِنْهُ؟',[['يَنْفَعُهُمْ وَهُمْ يَحْتَقِرُونَهُ.','The benefit contrasts with their contempt.'],['لَا يَنْفَعُ أَحَدًا.','ينتفعون explicitly states usefulness.'],['لَا يَعْرِفُهُ أَحَدٌ.','People tread on and use him.']], 'skill-inference','Read benefit and treatment together.'),
    O('plain','assess','State the complaint with a contrast connector.',['التُّرَابُ نَافِعٌ لِلنَّاسِ','وَلَكِنَّهُمْ','لَا يُقَدِّرُونَهُ'],'lakin-contrast','The paraphrase makes the implicit contrast explicit.'),
    R('speaker','assess','','مَنْ هُوَ الْمُتَكَلِّمُ؟','تراب','skill-comprehension','The first sentence identifies the voice.','The dust speaks through personification.'),
  ]),
  checkpoint('poetic-order',6,'An ant’s winter provision',S('qiraah-v1','ch3','qr1-3-005','qr1-3-006'),['كُلَّ صَيْفٍ أَجْمَعُ لِي طَعَامًا','فَإِذَا جَاءَ الْمَطَرُ','كَانَ لِي بَيْتِي الْمَقَرَّ'],'الْمَقَرّ: place of settling. The speaker is an ant.','أَجْمَعُ الطَّعَامَ صَيْفًا وَأَسْكُنُ فِي بَيْتِي عِنْدَ الْمَطَرِ.',[
    C('purpose','comprehension','assess','','مَا الْعِلَاقَةُ بَيْنَ الصَّيْفِ وَالْمَطَرِ؟',[['يَجْمَعُ الطَّعَامَ ثُمَّ يَسْتَقِرُّ فِي بَيْتِهِ.','Provision precedes the rainy period.'],['يَتْرُكُ الطَّعَامَ عِنْدَ الْمَطَرِ.','Abandoning food is not stated.']], 'skill-poetry','Follow فإذا as the later condition.'),
    O('prose','assess','Restore prose order: action → object → beneficiary → time.',['أَجْمَعُ','طَعَامًا','لِي','كُلَّ صَيْفٍ'],'skill-poetry','The fronted time phrase can be moved after the core clause.',{type:'poetry_reorder'}),
    R('time','assess','','فِي أَيِّ فَصْلٍ يَجْمَعُ طَعَامَهُ؟','الصيف','skill-comprehension','The fronted time phrase names the season.','The ant gathers food in summer.'),
  ]),
  checkpoint('imagery-and-compression',6,'A golden cage',S('qiraah-v1','ch5','qr1-5-001','qr1-5-002','qr1-5-003'),['الْحَبْسُ لَيْسَ مَذْهَبِي','فَلَسْتُ أَرْضَى قَفَصًا','وَإِنْ يَكُنْ مِنْ ذَهَبٍ'],'مَذْهَبِي: my way/choice. طَرَبِي: my joy.','لَا أُحِبُّ الْحَبْسَ حَتَّى لَوْ كَانَ الْقَفَصُ ذَهَبِيًّا؛ أُرِيدُ الْغَابَةَ.',[
    C('value','interpretation_choice','assess','','أَيُّ شَيْءٍ أَعْلَى قِيمَةً عِنْدَ الطَّائِرِ؟',[['الْحُرِّيَّةُ','Even gold does not make captivity acceptable.'],['ذَهَبُ الْقَفَصِ','وإن يكن rejects gold as a sufficient compensation.']], 'skill-inference','Keep the concessive even if.'),
    O('concession','assess','Restate captivity first, then the concession.',['لَا أَرْضَى الْحَبْسَ','حَتَّى لَوْ كَانَ','الْقَفَصُ مِنْ ذَهَبٍ'],'skill-poetry','The concession intensifies the refusal.',{type:'poetry_reorder'}),
    R('destination','assess','','مَا الْمَكَانُ الَّذِي يَطْلُبُهُ؟ اُكْتُبْ: الْغَابَات أَوِ الْقَفَص.','الغابات','skill-comprehension','Read غايتي.','The forests are the desired destination.'),
  ]),
];

export const CUMULATIVE = [
  checkpoint('stage-1',1,'A day away from lessons',S('qiraah-v1','ch1','qr1-1-026','qr1-1-027','qr1-1-028','qr1-1-029','qr1-1-030','qr1-1-031','qr1-1-032'),['أَقُومُ مُبَكِّرًا يَوْمَ الْعُطْلَةِ','وَأَقْضِي الْيَوْمَ فِي مُطَالَعَةٍ وَمُحَادَثَةٍ وَزِيَارَةٍ','وَأَمْكُثُ أَحْيَانًا وَأَخْرُجُ أَحْيَانًا'],'الْعُطْلَة: day off. عِيَادَة: visiting someone sick.','يَسْتَيْقِظُ مُبَكِّرًا وَيَقْرَأُ وَيَزُورُ أَهْلَهُ وَأَصْدِقَاءَهُ.',[
    C('whole','comprehension','assess','','Which summary is supported?',[['He keeps an early start but varies the rest of the day.','أيضا preserves waking early; أحيانا introduces variation.'],['He always stays at home.','Sometimes he goes out.'],['He spends every day at school.','This passage describes a day off.']],['early','stay'],'Compare أيضا with أحيانا.'),
    G('alternatives','assess','','Select the words that mark alternatives.',['أَمْكُثُ','أَحْيَانًا','فِي الْبَيْتِ','وَأَخْرُجُ','أَحْيَانًا'],[1,4],'some-days','أحيانا means sometimes.'),
    O('summary','assess','Rebuild a short summary in the order mentioned.',['يَسْتَيْقِظُ مُبَكِّرًا','وَيَقْرَأُ وَيَتَحَدَّثُ','وَيَزُورُ أَهْلَهُ'],['early','read'],'Follow the named activities without turning sometimes into always.'),
  ],'cumulative'),
  checkpoint('stage-2',2,'Encouraging a friend',S('qiraah-v1','ch20','qr1-20-015','qr1-20-016','qr1-20-017','qr1-20-018','qr1-20-019'),['دَعَوْنَا صَدِيقَنَا','فَقَالَ إِنِّي أَخَافُ','فَشَجَّعْنَاهُ','فَتَشَجَّعَ وَدَخَلَ'],'شَجَّعْنَاهُ: encouraged him.','خَافَ الصَّدِيقُ مِنَ الْمَاءِ فَشَجَّعَهُ أَصْحَابُهُ حَتَّى دَخَلَ.',[
    C('change','comprehension','assess','','مَا الَّذِي تَغَيَّرَ؟',[['خَافَ الصَّدِيقُ ثُمَّ دَخَلَ الْمَاءَ.','Encouragement precedes his entry.'],['خَافَ أَصْحَابُهُ فَخَرَجُوا.','The fear belongs to the visiting friend.']], 'skill-reference','Follow the shift from we to he.'),
    O('sequence','assess','Arrange the story’s causal chain.',['دَعَوْهُ إِلَى الْمَاءِ','فَذَكَرَ خَوْفَهُ','فَشَجَّعُوهُ','فَدَخَلَ'],'skill-clause-links','Each later event responds to the earlier one.'),
    R('speaker','assess','','مَنْ قَالَ إِنِّي أَخَافُ؟ اُكْتُبْ: الصَّدِيق أَوِ الرَّاوِي.','الصديق','dialogue-person','Look at فقال after the invitation.','The invited friend voices the fear.'),
  ],'cumulative'),
  checkpoint('stage-3',3,'Description, background and reaction',S('qiraah-v1','ch31','qr1-31-013','qr1-31-014','qr1-31-015','qr1-31-016','qr1-31-017','qr1-31-018'),['وَلَدٌ يَتِيمٌ تَخْدُمُ أُمُّهُ','لَيْسَ عِنْدَهُ لِبَاسٌ جَدِيدٌ','وَكَانَ يَنْظُرُ إِلَى أَتْرَابِهِ','وَكَانَتْ أُمُّهُ مَحْزُونَةً'],'أَتْرَاب: peers. غِبْطَة: wish for similar good fortune.','لَا يَمْلِكُ الطِّفْلُ ثِيَابًا جَدِيدَةً وَيَنْظُرُ إِلَى أَصْحَابِهِ بِخَجَلٍ، وَأُمُّهُ حَزِينَةٌ.',[
    C('reference','pronoun_reference','assess','','مَنْ تَخْدُمُ فِي بَيْتِ سَعِيدٍ؟',[['أُمُّ الْوَلَدِ','أمه is the subject inside the description of ولد.'],['سَعِيدٌ','He is the owner of the house.'],['الْوَلَدُ','His mother is explicitly named as the worker.']], 'relative-alladhi','Hold the boy as head while reading his mother’s action.'),
    O('description','assess','Unpack the opening: boy → mother → workplace.',['هُنَاكَ وَلَدٌ يَتِيمٌ','أُمُّهُ تَخْدُمُ','فِي بَيْتِ سَعِيدٍ'],'skill-syntax','The embedded description explains his household situation.'),
    R('emotion','assess','','اُكْتُبْ صِفَةَ الْأُمِّ فِي آخِرِ الْمَقْطَعِ.','محزونة','skill-comprehension','The final sentence names her emotional state.','His mother is sad, remembering his father.'),
  ],'cumulative'),
  checkpoint('stage-4',4,'Endurance and its reason',S('qiraah-v2','ch60','qr2-60-027','qr2-60-028','qr2-60-029','qr2-60-030','qr2-60-031','qr2-60-032'),['وَهُوَ يُحَدِّثُنَا','لَدَغَتْهُ عَقْرَبٌ','وَلَا يَقْطَعُ الْحَدِيثَ','إِنَّمَا صَبَرْتُ إِجْلَالًا لِلْحَدِيثِ'],'لَدَغَتْهُ: stung him. إِجْلَالًا: out of reverence.','اسْتَمَرَّ مَالِكٌ فِي الْحَدِيثِ مَعَ الْأَلَمِ وَبَيَّنَ بَعْدَ ذَلِكَ سَبَبَ صَبْرِهِ.',[
    C('reason','interpretation_choice','assess','','مَا السَّبَبُ الَّذِي ذَكَرَهُ لِصَبْرِهِ؟',[['إِجْلَالُ الْحَدِيثِ','إنما introduces his restricted explanation.'],['أَنَّهُ لَمْ يَشْعُرْ بِشَيْءٍ','His changing colour indicates an effect.'],['عَدَمُ وُجُودِ النَّاسِ','He explains after the people disperse.']], 'skill-constructions','Keep the reason after إنما.'),
    O('sequence','assess','Put continuing first, dispersal next, explanation last.',['اِسْتَمَرَّ فِي الْحَدِيثِ','فَلَمَّا تَفَرَّقَ النَّاسُ','بَيَّنَ سَبَبَ صَبْرِهِ'],['lamma','continue'],'The explanation comes after the audience disperses.'),
    R('restrictor','assess','','اُكْتُبِ الْأَدَاةَ الَّتِي تُقَدِّمُ السَّبَبَ الْمَقْصُودَ وَحْدَهُ.','إنما','skill-constructions','It begins his quoted explanation.','إنما focuses the stated explanation.'),
  ],'cumulative'),
  checkpoint('stage-5',5,'Means, care and dignity',S('qiraah-v2','ch37','qr2-37-001','qr2-37-002','qr2-37-003','qr2-37-004','qr2-37-005','qr2-37-006','qr2-37-007','qr2-37-008','qr2-37-009','qr2-37-010'),['يُرْسِلُ إِلَيْهِ قَلِيلًا مِنَ النُّقُودِ','وَلَكِنَّهُ مُدَبِّرٌ عَاقِلٌ','يَغْسِلُ ثِيَابَهُ وَيَرْقَعُهَا','لَا يَخْجَلُ مِنَ الْمَرْقُوعِ بَلْ مِنَ الْوَسِخِ'],'مُدَبِّر: resourceful. رَقَعَ: patched.','طَاهِرٌ قَلِيلُ الْمَالِ وَلَكِنَّهُ يَعْتَنِي بِثِيَابِهِ وَيَرَى الْعَيْبَ فِي الْوَسَخِ لَا فِي الْفَقْرِ.',[
    C('judgement','interpretation_choice','assess','','مَا الْمِقْيَاسُ الَّذِي يُقَدِّمُهُ النَّصُّ؟',[['النَّظَافَةُ وَالْعِنَايَةُ أَهَمُّ مِنْ غَلَاءِ الثِّيَابِ.','The contrasts concern care despite limited money.'],['الثَّوْبُ الْمَرْقُوعُ مُخْجِلٌ دَائِمًا.','The text explicitly says he is not ashamed of it.'],['طَاهِرٌ غَنِيٌّ جِدًّا.','His father sends only a little money.']], 'skill-inference','Compare the two statements about shame.'),
    O('contrast','assess','Summarise limited means, action, then judgement.',['مَعَهُ مَالٌ قَلِيلٌ','وَلَكِنَّهُ يَعْتَنِي بِثِيَابِهِ','وَيَخْجَلُ مِنَ الْوَسَخِ لَا مِنَ الرُّقَعِ'],['lakin-contrast','clean'],'Keep the distinction that motivates the description.'),
    R('care','assess','','بِمَاذَا يَغْسِلُ ثِيَابَهُ؟ اُكْتُبِ الْعِبَارَةَ مِنَ النَّصِّ.','بيده','skill-reference','Look at the washing clause.','He washes them with his own hand.'),
  ],'cumulative'),
  checkpoint('stage-6',6,'Advice across connected verses',S('qiraah-v2','ch44','qr2-44-004','qr2-44-005','qr2-44-006'),['لَا تُغْضِبِ الْجَلِيسَ','لَا تُكْثِرِ الْعِتَابَ','فَكَثْرَةُ الْمُعَاتَبَةِ تَدْعُو إِلَى الْمُجَانَبَةِ'],'الْعِتَاب: reproach. الْمُجَانَبَة: keeping away.','لَا تُكْثِرْ مِنْ لَوْمِ أَصْحَابِكَ لِئَلَّا يَبْتَعِدُوا عَنْكَ.',[
    C('connection','clause_relationship','assess','','مَا عِلَاقَةُ الْبَيْتِ الْأَخِيرِ بِالنَّصِيحَةِ؟',[['يُبَيِّنُ سَبَبَهَا وَنَتِيجَةَ مُخَالَفَتِهَا.','Excessive reproach leads to avoidance.'],['يَنْقُضُهَا وَيَدْعُو إِلَى الْعِتَابِ.','The final line explains rather than reverses the advice.']], 'skill-poetry','Follow فـ into the explanation.'),
    O('prose','assess','Restore advice → purpose in ordinary prose.',['لَا تُكْثِرْ مِنَ الْعِتَابِ','لِئَلَّا','يَبْتَعِدَ عَنْكَ أَصْحَابُكَ'],'skill-poetry','The reformulation makes the implied preventive purpose explicit.',{type:'poetry_reorder'}),
    R('family','assess','','اُكْتُبِ الْكَلِمَةَ فِي الْبَيْتِ الْأَخِيرِ الَّتِي تَشْتَرِكُ مَعَ الْعِتَابِ فِي الْجِذْرِ.','المعاتبة','skill-morphology','Both words use ع ت ب.','المعاتبة is another verbal noun in the same family.'),
  ],'cumulative'),
];

// Two independently scored examples per stage, each with its own authentic
// source and progressive help. No lesson passage doubles as a diagnostic.
const placementRows = [
  [1,S('qiraah-v1','ch19','qr1-19-010'),'وَلَيْسَ بَيْنَ بُيُوتِنَا إِلَّا بَيْتٌ وَاحِدٌ.','كَمْ بَيْتًا بَيْنَ بُيُوتِهِمْ؟','بَيْتٌ وَاحِدٌ','بُيُوتٌ كَثِيرَةٌ','Only one house separates them.','skill-comprehension'],
  [1,S('qiraah-v1','ch8','qr1-8-016'),'وَذَهَبَ عَمِّي فَاشْتَرَى تَذَاكِرَ الْقِطَارِ.','مَا الَّذِي اشْتَرَاهُ؟','تَذَاكِرَ','قِطَارًا','Tickets are bought; the train is what the tickets are for.','ticket'],
  [2,S('qiraah-v1','ch8','qr1-8-013'),'وَسَلَّمْتُ عَلَى أَبِي فَوَدَّعَنِي وَدَعَا لِي.','مَنْ وَدَّعَ الرَّاوِيَ؟','أَبُوهُ','عَمُّهُ','The father is the preceding participant and bids farewell.','skill-reference'],
  [2,S('qiraah-v1','ch13','qr1-13-009'),'جَاءَهُ الْأَجِيرُ وَهُوَ خَائِفٌ أَنْ لَا يَعْرِفَهُ الرَّجُلُ.','مَنْ هُوَ الْخَائِفُ؟','الْأَجِيرُ','الرَّجُلُ الَّذِي اسْتَأْجَرَهُ','The state clause describes the arriving worker.','hal-processing'],
  [3,S('qiraah-v2','ch32','qr2-32-008'),'كَانَ فِي تِلْكَ الْكَعْبَةِ ثَلَاثُمِئَةٍ وَسِتُّونَ صَنَمًا.','مَا الَّذِي كَانَ فِي الْمَكَانِ؟','الْأَصْنَامُ','النَّاسُ','The delayed noun group identifies what was located there.','delayed-subject'],
  [3,S('qiraah-v2','ch35','qr2-35-023'),'وَصَنَعَ اللِّبَاسَ بِالْمَالِ الَّذِي حَصَلَ لَهُ بِالْكِيمِيَاءِ.','إِلَى مَاذَا يَعُودُ الَّذِي؟','الْمَالِ','اللِّبَاسِ','The adjacent head of the relative is المال.','relative-alladhi'],
  [4,S('qasas-v5','ch13','qs-v5-c13-012'),'أَصْبَحُوا كَعَادَتِهِمْ فَإِذَا بِصَيْحَةٍ مَعَ زِلْزَالٍ شَدِيدٍ.','مَاذَا تُفِيدُ فَإِذَا بِـ؟','الْمُفَاجَأَةَ','عَادَةً مُتَكَرِّرَةً','فإذا بـ introduces the unexpected event interrupting the routine.','skill-constructions'],
  [4,S('qiraah-v2','ch35','qr2-35-028'),'لَمْ يَزَلْ أَبُوهُمْ يَسِيرُ بِهِمْ طَرِيقًا بَعْدَ طَرِيقٍ.','هَلْ تَوَقَّفَ عَنِ السَّيْرِ فِي هَذِهِ الْجُمْلَةِ؟','لَا، اِسْتَمَرَّ.','نَعَمْ، تَوَقَّفَ.','لم يزل + imperfect describes continuation.','ma-zala'],
  [5,S('qiraah-v2','ch66','qr2-66-022'),'فَتَعَجَّبَ مِنْ فَصَاحَتِهِمْ.','مَا سَبَبُ التَّعَجُّبِ؟','بَرَاعَتُهُمْ فِي الْكَلَامِ','كَثْرَةُ مَالِهِمْ','فصاحة concerns eloquent speech.','skill-vocabulary'],
  [5,S('qiraah-v1','ch20','qr1-20-001'),'قَرْيَتِي جَمِيلَةٌ فِي وَسَطِ حُقُولٍ وَبَسَاتِينَ كَأَنَّهَا جَزِيرَةٌ فِي بَحْرٍ أَخْضَرَ.','مَا الْبَحْرُ الْأَخْضَرُ؟','الْحُقُولُ وَالْبَسَاتِينُ','مَاءُ بَحْرٍ حَقِيقِيٍّ','The green surroundings supply the sea image.','kaanna-image'],
  [6,S('qiraah-v1','ch25','qr1-25-001'),'شَرُّ الْمَقَالِ الْكَذِبُ، خَيْرُ الْخِصَالِ الْأَدَبُ.','مَا أَفْضَلُ الْخِصَالِ فِي الْبَيْتِ؟','الْأَدَبُ','الْكَذِبُ','The parallel halves oppose the worst speech and best quality.','skill-poetry'],
  [6,S('qiraah-v2','ch48','qr2-48-009'),'عَزِيزُهَا ذَلِيلٌ، كَثِيرُهَا قَلِيلٌ.','مَاذَا تَصْنَعُ الْمُقَابَلَةُ؟','تُبَيِّنُ أَنَّ الْقِيمَةَ الظَّاهِرَةَ خَادِعَةٌ.','تُعَدِّدُ أَرْقَامًا فَقَطْ.','The oppositions overturn the apparent value of worldly things.','skill-inference'],
];
export const PLACEMENT = {id:'literature-placement',revision:1,stage:1,unit:'placement',title:'Find your starting point',titleAr:'مِنْ أَيْنَ أَبْدَأُ؟',archetype:'diagnostic',kind:'diagnostic',minutes:10,source:{kind:'practice'},vocabulary:[],constructions:[],chunks:[],support:{},objectives:[{id:'placement',text:'Find a starting stage from vocabulary, syntax and comprehension evidence.'}],context:'Try increasingly demanding source excerpts. Answers and help guide a recommendation; you can choose any stage afterwards.',
  exercises:placementRows.map(([level,source,arabic,prompt,correct,wrong,feedback,target],i)=>({...C(`placement-${i+1}`,'comprehension','assess',arabic,prompt,[[correct,feedback],[wrong,feedback]],target,'Read the participants and the relationship carefully.'),source,level,assessment:true,contextId:`diagnostic-${i+1}`,reserved:true})),
};
PLACEMENT.flow=PLACEMENT.exercises.map(e=>e.id);
