import { defineLesson } from './authoring.js';

// Authentic excerpts stay in the source collection. All new contexts below
// are teaching examples, not quotations attributed to the source author.
export const NARRATIVE_LESSONS = [
  defineLesson({
    id: 'first-prepare-then-go', stage: 1, title: 'First this, then that', titleAr: 'ثُمَّ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch1', sentenceIds: ['qr1-1-003'] },
    context: 'A pupil describes the start of an ordinary day.',
    objectives: [{ id: 'sequence', text: 'Follow two actions connected by ثُمَّ and recognise what someone prepares for.' }],
    vocabulary: [{ id: 'prepare-for', ar: 'أَسْتَعِدُّ لِـ', meaning: 'أَتَهَيَّأُ لِـ' }],
    constructions: [{ id: 'thumma-sequence', ar: '… ثُمَّ …', meaning: 'The next action happens after the first.' }],
    chunks: ['أَسْتَعِدُّ لِلصَّلَاةِ', 'ثُمَّ أَذْهَبُ', 'مَعَ وَالِدِي', 'إِلَى الْمَسْجِدِ،'],
    support: { vocabulary: 'أَسْتَعِدُّ: أَتَهَيَّأُ. وَالِدِي: أَبِي.', structure: 'ثُمَّ separates preparing from going. مَعَ names the companion; إِلَى names the destination.', paraphrase: 'أَتَهَيَّأُ لِلصَّلَاةِ، وَبَعْدَ ذَلِكَ أَذْهَبُ إِلَى الْمَسْجِدِ مَعَ أَبِي.', explanation: 'Preparing comes first. ثُمَّ gives an order without telling us exactly how many minutes pass.' },
    prepare: { arabic: 'أَسْتَعِدُّ لِلسَّفَرِ؛ أَضَعُ ثِيَابِي فِي الْحَقِيبَةِ.', prompt: 'What is أَسْتَعِدُّ doing here?', choices: [['أَتَهَيَّأُ', 'Packing is preparation for the journey.'], ['أَرْجِعُ', 'Packing before a journey does not mean returning.'], ['أَنْسَى', 'The traveller is getting ready, not forgetting.']], answer: 0, hint: 'Look at the act of packing.', targets: ['prepare-for'] },
    notice: { arabic: 'أَسْتَعِدُّ لِلصَّلَاةِ ثُمَّ أَذْهَبُ', prompt: 'Which comes first?', choices: [['الذَّهَابُ', 'Going comes after ثُمَّ.'], ['الِاسْتِعْدَادُ', 'The preparation comes before ثُمَّ.'], ['كِلَاهُمَا فِي اللَّحْظَةِ نَفْسِهَا', 'ثُمَّ presents successive actions, not simultaneous ones.']], answer: 1, hint: 'Read the action before ثُمَّ.', targets: ['thumma-sequence'] },
    manipulate: { prompt: 'Put preparation first, then going, then the companion and destination.', chunks: ['أَسْتَعِدُّ لِلصَّلَاةِ', 'ثُمَّ أَذْهَبُ', 'مَعَ وَالِدِي', 'إِلَى الْمَسْجِدِ'], explanation: 'Keep ثُمَّ with the later action. The remaining phrases tell us with whom and where.', hint: 'Start with أَسْتَعِدُّ.', targets: ['prepare-for', 'thumma-sequence'] },
    decode: { prompt: 'Which account keeps the sequence?', choices: [['أَذْهَبُ ثُمَّ أَتَهَيَّأُ.', 'This reverses preparation and departure.'], ['أَبِي يَذْهَبُ وَحْدَهُ.', 'مَعَ وَالِدِي includes the narrator.'], ['أَتَهَيَّأُ، ثُمَّ أَذْهَبُ مَعَ أَبِي.', 'The narrator prepares and then accompanies the father.']], answer: 2, targets: ['prepare-for', 'thumma-sequence'] },
    understand: { prompt: 'Does ثُمَّ tell us the exact length of the delay?', choices: [['لَا، تُبَيِّنُ التَّرْتِيبَ.', 'It tells us which action follows, without a measured duration.'], ['نَعَمْ، سَاعَةٌ.', 'No hour is named.'], ['نَعَمْ، يَوْمٌ.', 'No day-long delay is stated.']], answer: 0, hint: 'There is no number or unit of time.', targets: ['thumma-sequence'] },
    transfer: [
      { prompt: 'New routine: preparation → going → destination. Build “I prepare for the lesson, then go to school”.', chunks: ['أَسْتَعِدُّ لِلدَّرْسِ', 'ثُمَّ أَذْهَبُ', 'إِلَى الْمَدْرَسَةِ'], explanation: 'The activity changes, but preparation still precedes departure.', hint: 'Keep لِلدَّرْسِ attached to preparing.', targets: ['prepare-for', 'thumma-sequence'] },
      { arabic: 'غَسَلَ خَالِدٌ يَدَيْهِ ثُمَّ أَكَلَ.', prompt: 'مَاذَا فَعَلَ أَوَّلًا؟', choices: [['أَكَلَ.', 'Eating comes after ثُمَّ.'], ['غَسَلَ يَدَيْهِ.', 'Washing is the first event.'], ['نَامَ.', 'Sleeping is not mentioned.']], answer: 1, hint: 'Find the first verb.', targets: ['thumma-sequence'] },
    ],
  }),
  defineLesson({
    id: 'near-and-far', stage: 1, title: 'Near what?', titleAr: 'قَرِيبٌ مِنْ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch1', sentenceIds: ['qr1-1-004'] },
    context: 'The pupil explains where the mosque is in relation to home.',
    objectives: [{ id: 'distance', text: 'Read قَرِيبٌ مِنْ as a distance relationship and identify its two places.' }],
    vocabulary: [{ id: 'near', ar: 'قَرِيبٌ', meaning: 'لَيْسَ بَعِيدًا' }],
    constructions: [{ id: 'distance-min', ar: 'قَرِيبٌ مِنْ …', meaning: 'مِنْ introduces the place used as the point of comparison.' }],
    chunks: ['وَالْمَسْجِدُ', 'قَرِيبٌ', 'مِنْ بَيْتِي،'],
    support: { vocabulary: 'بَيْتِي: مَنْزِلِي. قَرِيبٌ: لَيْسَ بَعِيدًا.', structure: 'This describes location. مِنْ after قَرِيبٌ does not describe a journey out of the house.', paraphrase: 'الْمَسَافَةُ بَيْنَ بَيْتِي وَالْمَسْجِدِ قَصِيرَةٌ.', explanation: 'The mosque and the narrator’s home are close together. No movement is asserted.' },
    prepare: { arabic: 'الدُّكَّانُ قَرِيبٌ؛ أَصِلُ إِلَيْهِ فِي دَقِيقَةٍ.', prompt: 'Choose the meaning of قَرِيبٌ.', choices: [['بَعِيدٌ جِدًّا', 'A minute’s journey suggests a short distance.'], ['لَيْسَ بَعِيدًا', 'قَرِيبٌ describes something nearby.'], ['مُغْلَقٌ', 'The sentence gives distance, not opening hours.']], answer: 1, hint: 'Use the short journey as a clue.', targets: ['near'] },
    notice: { arabic: 'قَرِيبٌ مِنْ بَيْتِي', prompt: 'What role does بَيْتِي have?', choices: [['الْمَكَانُ الَّذِي نَقِيسُ مِنْهُ الْقُرْبَ', 'The house is the reference point for the distance.'], ['الشَّيْءُ الَّذِي أَشْتَرِيهِ', 'Nothing is being bought.'], ['شَخْصٌ يَذْهَبُ', 'بَيْتِي is a place, not a person going somewhere.']], answer: 0, hint: 'Read قَرِيبٌ مِنْ as a unit.', targets: ['distance-min'] },
    manipulate: { prompt: 'Build a location statement: mosque → distance → reference place.', chunks: ['الْمَسْجِدُ', 'قَرِيبٌ', 'مِنْ بَيْتِي'], explanation: 'The place comes first, followed by how close it is and to what.', hint: 'Keep مِنْ with بَيْتِي.', targets: ['distance-min'] },
    decode: { prompt: 'Which simpler statement matches?', choices: [['الْمَسْجِدُ بَعِيدٌ عَنْ بَيْتِي.', 'بَعِيدٌ reverses the distance.'], ['خَرَجَ الْمَسْجِدُ مِنْ بَيْتِي.', 'There is no leaving; مِنْ belongs to قَرِيبٌ.'], ['بَيْتِي وَالْمَسْجِدُ مُتَقَارِبَانِ.', 'The two places are close together.']], answer: 2, targets: ['near', 'distance-min'] },
    understand: { prompt: 'Is anyone travelling in this sentence?', choices: [['نَعَمْ، الْأَبُ.', 'No father or travel verb appears here.'], ['لَا، هُوَ وَصْفٌ لِلْمَكَانِ.', 'It states a location relationship.'], ['نَعَمْ، الْمُتَكَلِّمُ.', 'The possessive “my” does not imply movement.']], answer: 1, hint: 'Look for an action verb; there is none.', targets: ['distance-min'] },
    transfer: [
      { prompt: 'Describe the school: place → nearby → the market it is near.', chunks: ['الْمَدْرَسَةُ', 'قَرِيبَةٌ', 'مِنَ السُّوقِ'], explanation: 'قَرِيبَةٌ describes the school; مِنَ السُّوقِ gives the reference place.', hint: 'Begin with الْمَدْرَسَةُ.', targets: ['near', 'distance-min'] },
      { arabic: 'بَيْتُ مَرْيَمَ قَرِيبٌ مِنَ النَّهْرِ.', prompt: 'مَا الْمَكَانَانِ الْمُتَقَارِبَانِ؟', choices: [['الْبَيْتُ وَالنَّهْرُ', 'مِنَ النَّهْرِ relates the home to the river.'], ['مَرْيَمُ وَالْمَدْرَسَةُ', 'The school is absent; Maryam names the house’s owner.'], ['السُّوقُ وَالنَّهْرُ', 'No market is mentioned.']], answer: 0, hint: 'Separate the house’s owner from its location.', targets: ['distance-min'] },
    ],
  }),
  defineLesson({
    id: 'at-the-appointed-time', stage: 1, title: 'Arriving on time', titleAr: 'فِي الْمِيعَادِ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch1', sentenceIds: ['qr1-1-011'] },
    context: 'The pupil is describing the journey to school.',
    objectives: [{ id: 'arrival', text: 'Distinguish the destination of أَصِلُ إِلَى from the timing in فِي الْمِيعَادِ.' }],
    vocabulary: [{ id: 'appointed-time', ar: 'الْمِيعَادُ', meaning: 'الْوَقْتُ الْمُحَدَّدُ' }],
    constructions: [{ id: 'arrival-destination', ar: 'أَصِلُ إِلَى …', meaning: 'إِلَى identifies where someone arrives.' }],
    chunks: ['وَأَصِلُ', 'إِلَى الْمَدْرَسَةِ', 'فِي الْمِيعَادِ.'],
    support: { vocabulary: 'أَصِلُ: أَبْلُغُ الْمَكَانَ. الْمِيعَادُ: الْوَقْتُ الْمُحَدَّدُ.', structure: 'إِلَى الْمَدْرَسَةِ answers where; فِي الْمِيعَادِ answers when.', paraphrase: 'أَبْلُغُ الْمَدْرَسَةَ فِي الْوَقْتِ الْمُحَدَّدِ.', explanation: 'The narrator arrives at school on time. The school is not a time expression.' },
    prepare: { arabic: 'مِيعَادُ اللِّقَاءِ السَّاعَةُ التَّاسِعَةُ.', prompt: 'What does مِيعَادُ identify?', choices: [['مَكَانَ اللِّقَاءِ', 'Nine o’clock is a time, not a place.'], ['عَدَدَ الْحَاضِرِينَ', 'The nine belongs to the clock, not a head count.'], ['وَقْتَ اللِّقَاءِ', 'الْمِيعَادُ is the appointed time.']], answer: 2, hint: 'السَّاعَةُ points to time.', targets: ['appointed-time'] },
    notice: { arabic: 'أَصِلُ إِلَى الْمَدْرَسَةِ فِي الْمِيعَادِ', prompt: 'Which phrase answers أَيْنَ أَصِلُ؟', choices: [['إِلَى الْمَدْرَسَةِ', 'This is the destination reached.'], ['فِي الْمِيعَادِ', 'This tells when the arrival happens.'], ['أَصِلُ', 'This names the action without its destination.']], answer: 0, hint: 'Find the place after إِلَى.', targets: ['arrival-destination'] },
    manipulate: { prompt: 'Put the action first, then destination, then time.', chunks: ['أَصِلُ', 'إِلَى الْمَدْرَسَةِ', 'فِي الْمِيعَادِ'], explanation: 'Both phrases belong to arriving, but answer different questions.', hint: 'School is the destination, الْمِيعَادُ the timing.', targets: ['arrival-destination', 'appointed-time'] },
    decode: { prompt: 'Which account preserves place and time?', choices: [['أَغَادِرُ الْمَدْرَسَةَ مُتَأَخِّرًا.', 'This changes arriving to leaving and on time to late.'], ['أَبْلُغُ الْمَدْرَسَةَ فِي الْوَقْتِ الْمُحَدَّدِ.', 'Both the destination and the timing match.'], ['أَصِلُ إِلَى الْبَيْتِ بَعْدَ الْمِيعَادِ.', 'Both home and lateness differ from the source.']], answer: 1, targets: ['arrival-destination', 'appointed-time'] },
    understand: { prompt: 'Does the source say that the pupil is late?', choices: [['نَعَمْ، تَأَخَّرَ.', 'فِي الْمِيعَادِ means on time.'], ['لَمْ يَصِلْ أَصْلًا.', 'أَصِلُ explicitly describes arrival.'], ['لَا، يَصِلُ فِي الْوَقْتِ الْمُحَدَّدِ.', 'No lateness is reported.']], answer: 2, hint: 'Compare فِي with بَعْدَ الْمِيعَادِ.', targets: ['appointed-time'] },
    transfer: [
      { prompt: 'New journey: action → traveller → station → on time.', chunks: ['وَصَلَ', 'الْمُسَافِرُ', 'إِلَى الْمَحَطَّةِ', 'فِي الْمِيعَادِ'], explanation: 'The same destination and timing pattern works for a traveller.', hint: 'Put إِلَى before the station.', targets: ['arrival-destination', 'appointed-time'] },
      { arabic: 'وَصَلَتْ مَرْيَمُ إِلَى الْمَكْتَبَةِ بَعْدَ الْمِيعَادِ.', prompt: 'What has changed from arriving فِي الْمِيعَادِ?', choices: [['وَصَلَتْ مُتَأَخِّرَةً.', 'بَعْدَ moves the arrival beyond the appointed time.'], ['لَمْ تَصِلْ.', 'وَصَلَتْ confirms arrival.'], ['وَصَلَتْ إِلَى الْمَدْرَسَةِ.', 'The named destination is the library.']], answer: 0, hint: 'Read بَعْدَ together with الْمِيعَادِ.', targets: ['appointed-time'] },
    ],
  }),
  defineLesson({
    id: 'how-an-action-is-done', stage: 1, title: 'How is it done?', titleAr: 'بِأَدَبٍ وَسَكِينَةٍ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch1', sentenceIds: ['qr1-1-014'] },
    context: 'The narrator describes behaviour during a lesson.',
    objectives: [{ id: 'manner', text: 'Process بِـ + a quality as the manner of an action rather than a place or companion.' }],
    vocabulary: [{ id: 'calmness', ar: 'سَكِينَةٌ', meaning: 'هُدُوءٌ وَطُمَأْنِينَةٌ' }],
    constructions: [{ id: 'bi-manner', ar: 'بِأَدَبٍ', meaning: 'بِـ can tell us how an action is performed.' }],
    chunks: ['وَأَجْلِسُ', 'بِأَدَبٍ', 'وَسَكِينَةٍ،'],
    support: { vocabulary: 'أَدَبٌ: حُسْنُ السُّلُوكِ. سَكِينَةٌ: هُدُوءٌ.', structure: 'بِـ carries across the two linked qualities: بِأَدَبٍ وَبِسَكِينَةٍ.', paraphrase: 'أَجْلِسُ هَادِئًا وَحَسَنَ السُّلُوكِ.', explanation: 'The sentence describes the way of sitting. It does not name the seat or a companion.' },
    prepare: { arabic: 'جَلَسَ الطِّفْلُ بِسَكِينَةٍ، لَا يَصِيحُ وَلَا يَضْطَرِبُ.', prompt: 'Choose the meaning of سَكِينَةٍ.', choices: [['هُدُوءٍ', 'No shouting or agitation: the child is calm.'], ['ضَجِيجٍ', 'Noise conflicts with the following description.'], ['خَوْفٍ شَدِيدٍ', 'سَكِينَةٌ is calmness, not intense fear.']], answer: 0, hint: 'Read the two things the child is not doing.', targets: ['calmness'] },
    notice: { arabic: 'أَجْلِسُ بِأَدَبٍ وَسَكِينَةٍ', prompt: 'Which question do the last two words answer?', choices: [['أَيْنَ أَجْلِسُ؟', 'They do not name a place.'], ['كَيْفَ أَجْلِسُ؟', 'They describe the manner of sitting.'], ['مَعَ مَنْ أَجْلِسُ؟', 'These are qualities, not companions.']], answer: 1, hint: 'أَدَبٌ and سَكِينَةٌ are qualities.', targets: ['bi-manner'] },
    manipulate: { prompt: 'Build the action followed by good manners, then calmness.', chunks: ['أَجْلِسُ', 'بِأَدَبٍ', 'وَسَكِينَةٍ'], explanation: 'One بِـ can introduce two qualities joined by وَ.', hint: 'Begin with the sitting action.', targets: ['bi-manner', 'calmness'] },
    decode: { prompt: 'Which restatement describes the same behaviour?', choices: [['أَجْلِسُ فِي مَكَانٍ بَعِيدٍ.', 'No distance is given.'], ['أَجْلِسُ وَأَصِيحُ.', 'Shouting conflicts with سَكِينَةٍ.'], ['أَجْلِسُ هَادِئًا مُؤَدَّبًا.', 'Both calmness and good conduct are preserved.']], answer: 2, targets: ['bi-manner', 'calmness'] },
    understand: { prompt: 'Can this sentence tell us which room the narrator is in?', choices: [['لَا، تَصِفُ طَرِيقَةَ الْجُلُوسِ.', 'It describes conduct, not the room.'], ['نَعَمْ، الْمَطْبَخُ.', 'No kitchen is named.'], ['نَعَمْ، غُرْفَةُ النَّوْمِ.', 'No bedroom is named.']], answer: 0, hint: 'Separate manner from location.', targets: ['bi-manner'] },
    transfer: [
      { prompt: 'New action: speaking → person → calm manner.', chunks: ['تَكَلَّمَ', 'خَالِدٌ', 'بِسَكِينَةٍ'], explanation: 'The quality now describes speaking instead of sitting.', hint: 'Place بِسَكِينَةٍ after the speaker.', targets: ['bi-manner', 'calmness'] },
      { arabic: 'قَرَأَتْ مَرْيَمُ الرِّسَالَةَ بِاهْتِمَامٍ.', prompt: 'What does بِاهْتِمَامٍ add?', choices: [['مَكَانَ الْقِرَاءَةِ', 'Interest is not a location.'], ['طَرِيقَةَ الْقِرَاءَةِ', 'It tells us she read attentively.'], ['اسْمَ كَاتِبِ الرِّسَالَةِ', 'The writer’s name is not supplied.']], answer: 1, hint: 'اهْتِمَامٌ means attention or interest.', targets: ['bi-manner'] },
    ],
  }),
  defineLesson({
    id: 'some-days', stage: 1, title: 'Some days, not every day', titleAr: 'فِي بَعْضِ الْأَيَّامِ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch1', sentenceIds: ['qr1-1-017'] },
    context: 'The pupil describes how afternoons can differ.',
    objectives: [{ id: 'frequency', text: 'Distinguish بَعْضِ الْأَيَّامِ from كُلَّ يَوْمٍ and recognise مَكَثَ again in context.' }],
    vocabulary: [{ id: 'stay', ar: 'أَمْكُثُ', meaning: 'أَبْقَى' }],
    constructions: [{ id: 'some-days', ar: 'فِي بَعْضِ الْأَيَّامِ', meaning: 'On some days; no exact number is stated.' }],
    chunks: ['وَفِي بَعْضِ الْأَيَّامِ', 'أَمْكُثُ', 'فِي الْبَيْتِ،'],
    support: { vocabulary: 'بَعْضٌ: جُزْءٌ مِنَ الْكُلِّ. أَمْكُثُ: أَبْقَى.', structure: 'The first فِي phrase gives frequency; the second gives the place of staying.', paraphrase: 'أَبْقَى فِي الْبَيْتِ أَحْيَانًا.', explanation: 'Some days is not every day. No precise count or duration is given.' },
    prepare: { arabic: 'مَكَثَ خَالِدٌ فِي الْبَيْتِ وَلَمْ يَخْرُجْ.', prompt: 'مَا مَعْنَى مَكَثَ؟', choices: [['خَرَجَ', 'The sentence explicitly says he did not go out.'], ['رَكَضَ', 'Running is not the action here.'], ['بَقِيَ', 'مَكَثَ means remained or stayed.']], answer: 2, hint: 'Use وَلَمْ يَخْرُجْ.', targets: ['stay'] },
    notice: { arabic: 'فِي بَعْضِ الْأَيَّامِ أَمْكُثُ فِي الْبَيْتِ', prompt: 'Which phrase tells how often, rather than where?', choices: [['فِي بَعْضِ الْأَيَّامِ', 'Days frame the frequency of the activity.'], ['فِي الْبَيْتِ', 'The house is its location.'], ['أَمْكُثُ', 'The verb states the action.']], answer: 0, hint: 'Look for the phrase containing days.', targets: ['some-days'] },
    manipulate: { prompt: 'Put frequency first, then staying, then the place.', chunks: ['فِي بَعْضِ الْأَيَّامِ', 'أَمْكُثُ', 'فِي الْبَيْتِ'], explanation: 'The two فِي phrases have different jobs: when and where.', hint: 'Begin with the days.', targets: ['some-days', 'stay'] },
    decode: { prompt: 'Which statement matches?', choices: [['لَا أَبْقَى فِي الْبَيْتِ أَبَدًا.', 'Never contradicts the stated occasional staying.'], ['أَبْقَى فِي الْبَيْتِ أَحْيَانًا.', 'أَحْيَانًا keeps the sense of some days.'], ['أَبْقَى فِي الْبَيْتِ كُلَّ يَوْمٍ.', 'Every day is stronger than the source.']], answer: 1, targets: ['some-days', 'stay'] },
    understand: { prompt: 'How many days exactly?', choices: [['سَبْعَةٌ', 'No seven is stated.'], ['يَوْمٌ وَاحِدٌ فَقَطْ', 'Some days is not an exact count of one.'], ['لَمْ يُذْكَرْ عَدَدٌ.', 'بَعْضٌ leaves the number unspecified.']], answer: 2, hint: 'بَعْضٌ is not a numeral.', targets: ['some-days'] },
    transfer: [
      { prompt: 'New habit: some days → I visit → my friend.', chunks: ['فِي بَعْضِ الْأَيَّامِ', 'أَزُورُ', 'صَدِيقِي'], explanation: 'The expression marks an occasional activity regardless of the verb.', hint: 'Start with the frequency phrase.', targets: ['some-days'] },
      { arabic: 'تَمْكُثُ مَرْيَمُ فِي الْمَكْتَبَةِ كُلَّ يَوْمٍ.', prompt: 'What differs from فِي بَعْضِ الْأَيَّامِ?', choices: [['تَبْقَى هُنَاكَ يَوْمِيًّا.', 'كُلَّ يَوْمٍ means daily, not occasionally.'], ['لَا تَبْقَى هُنَاكَ.', 'تَمْكُثُ says that she stays.'], ['تَبْقَى هُنَاكَ يَوْمًا وَاحِدًا فَقَطْ.', 'كُلَّ repeats the action across days.']], answer: 0, hint: 'Compare كُلَّ with بَعْضِ.', targets: ['some-days', 'stay'] },
    ],
  }),
  defineLesson({
    id: 'before-sunset', stage: 1, title: 'Before sunset', titleAr: 'قَبْلَ الْغُرُوبِ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch12', sentenceIds: ['qr1-12-038'] },
    context: 'Family and friends gather on the day of the narrator’s first fast.',
    objectives: [{ id: 'before', text: 'Place an event before a time marker and follow two groups sharing one verb.' }],
    vocabulary: [{ id: 'sunset', ar: 'الْغُرُوبُ', meaning: 'غِيَابُ الشَّمْسِ آخِرَ النَّهَارِ' }],
    constructions: [{ id: 'before-time', ar: 'قَبْلَ …', meaning: 'The action precedes the named time.' }],
    chunks: ['وَقَبْلَ الْغُرُوْبِ', 'حَضَرَ', 'أَصْدِقَاءُ أَبِيْ', 'وَأَقَارِبُنَا.'],
    support: { vocabulary: 'حَضَرَ: جَاءَ. أَقَارِبُنَا: أَهْلُ قَرَابَتِنَا.', structure: 'قَبْلَ الْغُرُوبِ sets the time for both the father’s friends and the relatives arriving.', paraphrase: 'جَاءَ أَصْدِقَاءُ أَبِي وَأَقَارِبُنَا وَالشَّمْسُ لَمْ تَغْرُبْ بَعْدُ.', explanation: 'The arrivals precede sunset. The sentence does not put one group before sunset and the other after it.' },
    prepare: { arabic: 'غَابَتِ الشَّمْسُ وَبَدَأَ اللَّيْلُ؛ هَذَا وَقْتُ الْغُرُوبِ.', prompt: 'Which time is الْغُرُوبُ?', choices: [['بِدَايَةُ الصَّبَاحِ', 'Morning begins with sunrise, not sunset.'], ['آخِرُ النَّهَارِ', 'The sun disappears at the end of the day.'], ['وَسَطُ النَّهَارِ', 'Noon does not match the beginning of night.']], answer: 1, hint: 'The sentence says night begins.', targets: ['sunset'] },
    notice: { arabic: 'قَبْلَ الْغُرُوبِ حَضَرَ أَصْدِقَاءُ أَبِي', prompt: 'Which happens first?', choices: [['غُرُوبُ الشَّمْسِ', 'قَبْلَ places the arrival earlier.'], ['لَا يُعْرَفُ', 'The connector does give the order.'], ['حُضُورُ الْأَصْدِقَاءِ', 'The friends arrive before the sunset marker.']], answer: 2, hint: 'Read قَبْلَ as earlier than.', targets: ['before-time'] },
    manipulate: { prompt: 'Arrange time → arriving → father’s friends → relatives.', chunks: ['قَبْلَ الْغُرُوبِ', 'حَضَرَ', 'أَصْدِقَاءُ أَبِي', 'وَأَقَارِبُنَا'], explanation: 'Both groups share حَضَرَ and the same time phrase.', hint: 'Start with قَبْلَ.', targets: ['before-time'] },
    decode: { prompt: 'Choose the faithful reading.', choices: [['جَاءَ الْأَصْدِقَاءُ وَالْأَقَارِبُ قَبْلَ غِيَابِ الشَّمْسِ.', 'Both groups arrive before sunset.'], ['جَاءَ الْجَمِيعُ بَعْدَ غِيَابِ الشَّمْسِ.', 'بَعْدَ reverses the time relation.'], ['جَاءَ أَبِي وَحْدَهُ.', 'أَصْدِقَاءُ أَبِي means his friends, not the father alone.']], answer: 0, targets: ['before-time', 'sunset'] },
    understand: { prompt: 'Were the relatives given a separate, later arrival time?', choices: [['نَعَمْ، بَعْدَ الْعِشَاءِ.', 'No separate evening time appears.'], ['لَا، يَشْتَرِكُونَ فِي الْوَقْتِ نَفْسِهِ.', 'وَأَقَارِبُنَا is joined under the same time description.'], ['نَعَمْ، فِي الْغَدِ.', 'Tomorrow is not mentioned.']], answer: 1, hint: 'The sentence has one time phrase and one shared verb.', targets: ['before-time'] },
    transfer: [
      { prompt: 'New journey: before sunset → returned → the travellers.', chunks: ['قَبْلَ الْغُرُوبِ', 'رَجَعَ', 'الْمُسَافِرُونَ'], explanation: 'قَبْلَ still places the event before the marker.', hint: 'Begin with the time phrase.', targets: ['before-time', 'sunset'] },
      { arabic: 'فَتَحَ الْحَارِسُ الْبَابَ قَبْلَ وُصُولِ الطُّلَّابِ.', prompt: 'مَاذَا حَدَثَ أَوَّلًا؟', choices: [['وَصَلَ الطُّلَّابُ.', 'Their arrival is the later marker.'], ['أُغْلِقَ الْبَابُ.', 'Opening, not closing, is stated.'], ['فُتِحَ الْبَابُ.', 'The door opens before the students arrive.']], answer: 2, hint: 'قَبْلَ relates opening to arrival.', targets: ['before-time'] },
    ],
  }),
  defineLesson({
    id: 'from-after-until', stage: 1, title: 'A stretch of time', titleAr: 'بَعْدَ … إِلَى …', minutes: 6,
    source: { bookId: 'qiraah-v1', chapterId: 'ch1', sentenceIds: ['qr1-1-016'] },
    context: 'The pupil describes a break in the afternoon routine.',
    objectives: [{ id: 'interval', text: 'Read a start and end time together and keep negation attached to the action throughout that interval.' }],
    vocabulary: [{ id: 'after-time', ar: 'بَعْدَ', meaning: 'فِي وَقْتٍ يَلِي …' }],
    constructions: [{ id: 'time-until', ar: 'بَعْدَ … إِلَى …', meaning: 'One time starts the interval; another ends it.' }],
    chunks: ['وَلَا أَقْرَأُ', 'بَعْدَ صَلَاةِ الْعَصْرِ', 'إِلَى الْمَغْرِبِ،'],
    support: { vocabulary: 'الْعَصْرُ: afternoon prayer. الْمَغْرِبُ: sunset / sunset prayer here.', structure: 'لَا negates reading. بَعْدَ gives the start of the break and إِلَى gives its endpoint.', paraphrase: 'أَتَوَقَّفُ عَنِ الْقِرَاءَةِ مِنْ بَعْدِ الْعَصْرِ حَتَّى الْمَغْرِبِ.', explanation: 'This is a break over a specified interval, not a claim that the narrator never reads. What happens after sunset is not stated here.' },
    prepare: { arabic: 'أَكَلْتُ، وَبَعْدَ الطَّعَامِ غَسَلْتُ يَدَيَّ.', prompt: 'When is بَعْدَ الطَّعَامِ?', choices: [['قَبْلَ الْأَكْلِ', 'That would be before the meal.'], ['فِي أَثْنَاءِ الْأَكْلِ', 'During is not after.'], ['عَقِبَ الْأَكْلِ', 'The meal is followed by washing.']], answer: 2, hint: 'The first action has already happened.', targets: ['after-time'] },
    notice: { arabic: 'لَا أَقْرَأُ بَعْدَ الْعَصْرِ إِلَى الْمَغْرِبِ', prompt: 'Which phrase gives the endpoint of the break?', choices: [['إِلَى الْمَغْرِبِ', 'إِلَى marks the far end of the interval.'], ['بَعْدَ الْعَصْرِ', 'This gives the starting side of the interval.'], ['لَا أَقْرَأُ', 'This states what is not done.']], answer: 0, hint: 'Find إِلَى.', targets: ['time-until'] },
    manipulate: { prompt: 'Build the break: no reading → start time → endpoint.', chunks: ['لَا أَقْرَأُ', 'بَعْدَ صَلَاةِ الْعَصْرِ', 'إِلَى الْمَغْرِبِ'], explanation: 'The negated action applies across the interval between these time markers.', hint: 'Place the start before the endpoint.', targets: ['time-until'] },
    decode: { prompt: 'Which statement preserves the break?', choices: [['أَقْرَأُ طُولَ هَذَا الْوَقْتِ.', 'لَا rules out reading in the interval.'], ['لَا أَقْرَأُ مِنْ بَعْدِ الْعَصْرِ حَتَّى الْمَغْرِبِ.', 'The negative action and both limits remain.'], ['لَا أَقْرَأُ فِي أَيِّ وَقْتٍ.', 'The source restricts the claim to a particular interval.']], answer: 1, targets: ['time-until', 'after-time'] },
    understand: { prompt: 'Does this sentence prove that reading starts immediately at sunset?', choices: [['نَعَمْ، فِي اللَّحْظَةِ نَفْسِهَا.', 'An endpoint alone does not assert the next action.'], ['نَعَمْ، لِمُدَّةِ سَاعَةٍ.', 'No reading duration is supplied.'], ['لَا، لَمْ يَذْكُرْ مَا بَعْدَ ذَلِكَ.', 'We know the interval of the break, not the following activity.']], answer: 2, hint: 'Do not add an unstated next event.', targets: ['time-until'] },
    transfer: [
      { prompt: 'New break: no playing → after lunch → evening.', chunks: ['لَا أَلْعَبُ', 'بَعْدَ الْغَدَاءِ', 'إِلَى الْمَسَاءِ'], explanation: 'The time frame now applies to playing.', hint: 'إِلَى introduces the ending time.', targets: ['time-until', 'after-time'] },
      { arabic: 'بَقِيَتْ مَرْيَمُ فِي الْمَكْتَبَةِ مِنَ الصَّبَاحِ إِلَى الظُّهْرِ.', prompt: 'مَتَى تَنْتَهِي الْمُدَّةُ الْمَذْكُورَةُ؟', choices: [['عِنْدَ الظُّهْرِ', 'إِلَى الظُّهْرِ supplies the endpoint.'], ['عِنْدَ الصَّبَاحِ', 'Morning is the starting point.'], ['فِي الْمَكْتَبَةِ', 'The library is the place, not a time.']], answer: 0, hint: 'The end follows إِلَى.', targets: ['time-until'] },
    ],
  }),
];
