// Short prose lessons linked to unchanged source sentences. Transfer sentences
// are authored teaching examples, not quotations from the source works.
export const PROSE_LESSONS = [
  {
    id: 'a-little-later', revision: 1, stage: 1,
    title: 'A little later', titleAr: 'بَعْدَ قَلِيلٍ', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch8', sentenceIds: ['qr1-8-028'] },
    context: 'The narrator is waiting at a railway station. Follow the order of two events.',
    objectives: [{ id: 'sequence', text: 'Read بَعْدَ قَلِيلٍ as a short delay and follow the next action introduced by فَـ.' }],
    vocabulary: [{ id: 'short-delay', ar: 'بَعْدَ قَلِيلٍ', meaning: 'بَعْدَ وَقْتٍ قَصِيرٍ' }],
    constructions: [{ id: 'fa-sequence', ar: 'جَاءَ … فَخَرَجْنَا', meaning: 'The second action follows the first in the story.' }],
    chunks: ['وَبَعْدَ قَلِيْلٍ', 'جَاءَ الْقِطَارُ', 'فَخَرَجْنَا', 'مِنَ الْمَنْظَرَةِ.'],
    support: {
      vocabulary: 'الْقِطَارُ: train. الْمَنْظَرَةُ هُنَا: قَاعَةُ الِانْتِظَارِ. This uncommon place word is only a reading aid.',
      structure: 'بَعْدَ قَلِيلٍ sets the time. The train arrives first; فَـ then introduces what the narrator and his companions do.',
      paraphrase: 'بَعْدَ وَقْتٍ قَصِيرٍ وَصَلَ الْقِطَارُ، فَغَادَرْنَا قَاعَةَ الِانْتِظَارِ.',
      explanation: 'The short delay comes before the train arrives. The ـنَا in خَرَجْنَا changes the subject from the train to “we”.',
    },
    exercises: [
      { id: 'word', phase: 'prepare', type: 'contextual_vocabulary',
        arabic: 'انْتَظَرْتُ دَقَائِقَ، وَبَعْدَ قَلِيلٍ جَاءَ صَدِيقِي.',
        prompt: 'How long was the wait in بَعْدَ قَلِيلٍ?',
        options: ['وَقْتًا قَصِيرًا', 'سَنَوَاتٍ كَثِيرَةً', 'لَمْ أَنْتَظِرْ أَصْلًا'], answer: 0,
        feedback: ['دَقَائِقَ gives the clue: a short time passed.', 'قَلِيلٍ and دَقَائِقَ do not describe years of waiting.', 'بَعْدَ places the arrival after a wait, even though it was short.'],
        hint: 'The narrator waited minutes before the friend arrived.', targets: ['short-delay'] },
      { id: 'notice', phase: 'notice', type: 'clause_relationship',
        arabic: 'جَاءَ الْقِطَارُ فَخَرَجْنَا', prompt: 'Which event comes first?',
        options: ['خُرُوجُنَا', 'مَجِيءُ الْقِطَارِ', 'لَا يُبَيِّنُ الْكَلَامُ التَّرْتِيبَ'], answer: 1,
        feedback: ['خَرَجْنَا follows فَـ; it comes after the train arrives.', 'جَاءَ is the first event. فَـ carries the story on to our leaving.', 'Here فَـ links the next event to the one just mentioned.'],
        hint: 'Read what happens before the فَـ attached to خَرَجْنَا.', targets: ['fa-sequence'] },
      { id: 'build', phase: 'manipulate', type: 'reorder_chunks',
        prompt: 'Start with the short delay, then the train arriving, then our leaving.',
        options: ['وَبَعْدَ قَلِيْلٍ', 'جَاءَ الْقِطَارُ', 'فَخَرَجْنَا', 'مِنَ الْمَنْظَرَةِ'], answer: [0, 1, 2, 3],
        explanation: 'The time phrase opens the sequence. فَخَرَجْنَا introduces the next action; مِنَ tells us where we left from.',
        hint: 'Keep مِنَ الْمَنْظَرَةِ with خَرَجْنَا.', targets: ['short-delay', 'fa-sequence'] },
      { id: 'decode', phase: 'decode', type: 'arabic_paraphrase',
        prompt: 'Which reading keeps the same timing and order?',
        options: ['خَرَجْنَا، وَبَعْدَ ذَلِكَ جَاءَ الْقِطَارُ.', 'جَاءَ الْقِطَارُ بَعْدَ وَقْتٍ طَوِيلٍ، فَخَرَجْنَا.', 'جَاءَ الْقِطَارُ بَعْدَ وَقْتٍ قَصِيرٍ، فَخَرَجْنَا.'], answer: 2,
        feedback: ['This reverses the order: the train arrives before we leave.', 'بَعْدَ قَلِيلٍ describes a short wait, not a long one.', 'The brief wait, arrival and departure all keep their original order.'],
        targets: ['short-delay', 'fa-sequence'] },
      { id: 'meaning', phase: 'understand', type: 'comprehension',
        prompt: 'مَاذَا فَعَلْنَا بَعْدَ مَجِيءِ الْقِطَارِ؟',
        options: ['خَرَجْنَا مِنْ قَاعَةِ الِانْتِظَارِ.', 'رَجَعْنَا إِلَى بُيُوتِنَا.', 'بَقِينَا فِي قَاعَةِ الِانْتِظَارِ.'], answer: 0,
        feedback: ['فَخَرَجْنَا states what we did next; الْمَنْظَرَةِ is the waiting hall here.', 'The sentence says we left the waiting hall, not that we went home.', 'خَرَجْنَا means we went out, so we did not stay there.'],
        hint: 'Follow فَـ to the next action.', targets: ['fa-sequence'] },
      { id: 'transfer-build', phase: 'transfer', type: 'sentence_reconstruction',
        prompt: 'New scene: start with “a little later”, then “the teacher arrived, so we stood up”.',
        options: ['بَعْدَ قَلِيلٍ', 'جَاءَ الْمُعَلِّمُ', 'فَقُمْنَا'], answer: [0, 1, 2],
        explanation: 'The teacher’s arrival replaces the train’s arrival. فَـ still introduces the action that follows.',
        hint: 'Begin with the time phrase and put فَقُمْنَا after the arrival.', targets: ['short-delay', 'fa-sequence'] },
      { id: 'transfer-meaning', phase: 'transfer', type: 'transfer_example',
        arabic: 'بَعْدَ قَلِيلٍ تَوَقَّفَ الْمَطَرُ فَخَرَجَ الْأَطْفَالُ.',
        prompt: 'Which account matches this new sentence?',
        options: ['خَرَجَ الْأَطْفَالُ قَبْلَ تَوَقُّفِ الْمَطَرِ.', 'تَوَقَّفَ الْمَطَرُ بَعْدَ وَقْتٍ قَصِيرٍ، ثُمَّ خَرَجَ الْأَطْفَالُ.', 'تَوَقَّفَ الْمَطَرُ بَعْدَ وَقْتٍ طَوِيلٍ، ثُمَّ خَرَجَ الْأَطْفَالُ.'], answer: 1,
        feedback: ['فَخَرَجَ follows the rain stopping; the children do not go out first.', 'A short delay passes, the rain stops, and the children then go out.', 'The order is right, but طَوِيلٍ changes the meaning of قَلِيلٍ.'],
        hint: 'Check both the time phrase and the event after فَـ.', targets: ['short-delay', 'fa-sequence'] },
    ],
  },
  {
    id: 'someone-in-a-state', revision: 1, stage: 2,
    title: 'Who is feeling this way?', titleAr: 'تَرَاهُ مَسْرُورًا', minutes: 5,
    source: { bookId: 'qiraah-v1', chapterId: 'ch19', sentenceIds: ['qr1-19-020'] },
    context: 'The narrator is describing his friend Qāsim. Work out which person the description belongs to.',
    objectives: [{ id: 'state-reference', text: 'Connect a description of someone’s state to the person it describes, including a person named by ـهُ.' }],
    vocabulary: [{ id: 'pleased', ar: 'مَسْرُورٌ', meaning: 'فَرِحٌ' }],
    constructions: [
      { id: 'hal-processing', ar: 'تَرَاهُ … مَسْرُورًا', meaning: 'A state can describe the person being seen.' },
      { id: 'pronoun-hu', ar: 'تَرَاهُ', meaning: 'ـهُ names the person being seen.' },
    ],
    chunks: ['تَرَاهُ', 'دَائِماً', 'مَسْرُوراً ،'],
    support: {
      vocabulary: 'مَسْرُورٌ: فَرِحٌ. دَائِمًا: فِي كُلِّ وَقْتٍ.',
      structure: 'تَرَى addresses “you”; ـهُ points to Qāsim. مَسْرُورًا describes Qāsim as you see him, not the person looking.',
      paraphrase: 'كُلَّمَا رَأَيْتَ قَاسِمًا وَجَدْتَهُ فَرِحًا.',
      explanation: 'The person seeing and the person described are different. Read تَرَاهُ … مَسْرُورًا together across دَائِمًا.',
    },
    exercises: [
      { id: 'word', phase: 'prepare', type: 'contextual_vocabulary',
        arabic: 'سَمِعَ الطِّفْلُ خَبَرًا حَسَنًا، فَابْتَسَمَ وَكَانَ مَسْرُورًا.',
        prompt: 'Which word explains مَسْرُورًا here?',
        options: ['حَزِينًا', 'نَائِمًا', 'فَرِحًا'], answer: 2,
        feedback: ['The good news and smile point to happiness, not sadness.', 'The child hears the news and smiles; the word is describing his feeling.', 'The smile after good news makes فَرِحًا the fitting meaning.'],
        hint: 'Use the good news and the smile as clues.', targets: ['pleased'] },
      { id: 'notice', phase: 'notice', type: 'pronoun_reference',
        arabic: 'قَاسِمٌ صَدِيقِي. تَرَاهُ مَسْرُورًا.',
        prompt: 'Who is مَسْرُورًا describing?',
        options: ['الشَّخْصَ الَّذِي يَنْظُرُ إِلَى قَاسِمٍ', 'قَاسِمًا', 'صَدِيقًا آخَرَ لَمْ يُذْكَرْ'], answer: 1,
        feedback: ['The observer is the “you” in تَرَى. The description belongs to the person represented by ـهُ.', 'ـهُ points to Qāsim, the person you see looking happy.', 'No other friend is introduced. Keep the description attached to the named person.'],
        hint: 'Separate “you see” from “him”.', targets: ['hal-processing', 'pronoun-hu'] },
      { id: 'build', phase: 'manipulate', type: 'sentence_reconstruction',
        prompt: 'Build “You see Qāsim happy”: action first, then the person, then his state.',
        options: ['تَرَى', 'قَاسِمًا', 'مَسْرُورًا'], answer: [0, 1, 2],
        explanation: 'Naming قَاسِمًا makes the relationship visible. In تَرَاهُ, ـهُ fills the same place.',
        hint: 'Put the person being seen between the action and his state.', targets: ['hal-processing', 'pleased'] },
      { id: 'decode', phase: 'decode', type: 'arabic_paraphrase',
        prompt: 'Which simpler sentence preserves the description of Qāsim?',
        options: ['تَرَى قَاسِمًا حَزِينًا فِي كُلِّ مَرَّةٍ.', 'يَرَاكَ قَاسِمٌ وَأَنْتَ فَرِحٌ.', 'كُلَّمَا رَأَيْتَ قَاسِمًا وَجَدْتَهُ فَرِحًا.'], answer: 2,
        feedback: ['حَزِينًا reverses the meaning of مَسْرُورًا.', 'This exchanges the observer and the person being described.', 'Qāsim remains the person seen, and he is consistently described as happy.'],
        targets: ['hal-processing', 'pronoun-hu', 'pleased'] },
      { id: 'meaning', phase: 'understand', type: 'interpretation_choice',
        prompt: 'Does this sentence tell us how the observer feels?',
        options: ['لَا؛ إِنَّمَا يَصِفُ حَالَ قَاسِمٍ.', 'نَعَمْ؛ الْمُرَاقِبُ حَزِينٌ.', 'نَعَمْ؛ الْمُرَاقِبُ مَسْرُورٌ.'], answer: 0,
        feedback: ['The description is attached to Qāsim. The observer’s own feeling is not stated.', 'Nothing in the sentence says the observer is sad.', 'Seeing a happy person does not tell us that the observer is also happy.'],
        hint: 'The state belongs to the person represented by ـهُ.', targets: ['hal-processing', 'pronoun-hu'] },
      { id: 'transfer-build', phase: 'transfer', type: 'sentence_reconstruction',
        prompt: 'New scene: “I saw Maryam smiling.” Put the action, the person and her state in that order.',
        options: ['رَأَيْتُ', 'مَرْيَمَ', 'مُبْتَسِمَةً'], answer: [0, 1, 2],
        explanation: 'مُبْتَسِمَةً describes Maryam, the person seen. The observer is the “I” in رَأَيْتُ.',
        hint: 'The feminine description goes with Maryam.', targets: ['hal-processing'] },
      { id: 'transfer-meaning', phase: 'transfer', type: 'transfer_example',
        arabic: 'عَادَ خَالِدٌ مِنَ الْمَدْرَسَةِ مَسْرُورًا.',
        prompt: 'مَنْ كَانَ فَرِحًا؟',
        options: ['الْمُتَكَلِّمُ', 'خَالِدٌ', 'كُلُّ مَنْ فِي الْمَدْرَسَةِ'], answer: 1,
        feedback: ['The speaker reports the event without stating their own feeling.', 'Here the state describes Khālid, the person returning.', 'مَسْرُورًا describes Khālid, not everyone at the school.'],
        hint: 'Find the person taking part in عَادَ.', targets: ['hal-processing', 'pleased'] },
    ],
  },
  {
    id: 'the-action-continues', revision: 1, stage: 3,
    title: 'The action continues', titleAr: 'مَا زَالَ', minutes: 6,
    source: { bookId: 'qasas-v4', chapterId: 'ch8', sentenceIds: ['qs-v4-c08-001'] },
    context: 'Hūd speaks to his people. Read an expression that keeps an action going.',
    objectives: [{ id: 'continuation', text: 'Understand مَا زَالَ + a verb as continuing action and read بِرِفْقٍ as its manner.' }],
    vocabulary: [{ id: 'gentleness', ar: 'رِفْقٌ', meaning: 'لِينٌ، خِلَافُ الْعُنْفِ' }],
    constructions: [{ id: 'ma-zala', ar: 'مَا زَالَ يَفْعَلُ', meaning: 'He continued doing it / is still doing it, according to context.' }],
    chunks: ['وَمَا زَالَ هُودٌ', 'يَنْصَحُ لِقَوْمِهِ', 'وَيَدْعُوهُمْ', 'بِحِكْمَةٍ وَرِفْقٍ.'],
    support: {
      vocabulary: 'يَنْصَحُ لِقَوْمِهِ: يُرْشِدُهُمْ إِلَى الْخَيْرِ. رِفْقٌ: لِينٌ.',
      structure: 'Read مَا زَالَ as one expression with the following verbs. In this narrative, the advising and calling continue. بِحِكْمَةٍ وَرِفْقٍ describes his manner.',
      paraphrase: 'اسْتَمَرَّ هُودٌ فِي نُصْحِ قَوْمِهِ وَدَعْوَتِهِمْ بِحِكْمَةٍ وَلِينٍ.',
      explanation: 'مَا زَالَ does not mean that the advice stopped. The expression denies its ending, so the action continues.',
    },
    exercises: [
      { id: 'word', phase: 'prepare', type: 'contextual_vocabulary',
        arabic: 'أَمْسَكَ الْأَبُ يَدَ الطِّفْلِ بِرِفْقٍ، دُونَ أَنْ يُؤْلِمَهُ.',
        prompt: 'How did the father hold the child’s hand?',
        options: ['بِعُنْفٍ', 'بِلِينٍ', 'بِغَضَبٍ'], answer: 1,
        feedback: ['Violence conflicts with بِرِفْقٍ and the care not to hurt him.', 'بِرِفْقٍ means gently; he avoids causing pain.', 'The phrase describes a gentle manner, not anger.'],
        hint: 'دُونَ أَنْ يُؤْلِمَهُ means without hurting him.', targets: ['gentleness'] },
      { id: 'notice', phase: 'notice', type: 'interpretation_choice',
        arabic: 'مَا زَالَ هُودٌ يَنْصَحُ لِقَوْمِهِ', prompt: 'What does مَا زَالَ tell you about the advising?',
        options: ['تَوَقَّفَ عَنِ النُّصْحِ.', 'لَمْ يَنْصَحْهُمْ قَطُّ.', 'اسْتَمَرَّ فِي النُّصْحِ.'], answer: 2,
        feedback: ['Do not treat مَا as negating يَنْصَحُ on its own. مَا زَالَ expresses continuation.', 'The advice is already happening and continues; it is not absent.', 'The whole expression means that he kept advising them.'],
        hint: 'Read مَا زَالَ together before interpreting the next verb.', targets: ['ma-zala'] },
      { id: 'build', phase: 'manipulate', type: 'reorder_chunks',
        prompt: 'Start with مَا زَالَ هُودٌ. Place the advice before the calling, then their manner.',
        options: ['مَا زَالَ هُودٌ', 'يَنْصَحُ لِقَوْمِهِ', 'وَيَدْعُوهُمْ', 'بِحِكْمَةٍ وَرِفْقٍ'], answer: [0, 1, 2, 3],
        explanation: 'مَا زَالَ opens the continuing action. The two verbs tell us what he does, and the final phrase describes his manner.',
        hint: 'The بِـ phrase answers how he addresses them.', targets: ['ma-zala', 'gentleness'] },
      { id: 'decode', phase: 'decode', type: 'arabic_paraphrase',
        prompt: 'Which reading preserves both continuation and manner?',
        options: ['اسْتَمَرَّ هُودٌ يَنْصَحُ قَوْمَهُ وَيَدْعُوهُمْ بِلِينٍ وَحِكْمَةٍ.', 'تَوَقَّفَ هُودٌ عَنْ نُصْحِ قَوْمِهِ وَدَعْوَتِهِمْ.', 'اسْتَمَرَّ هُودٌ يَدْعُو قَوْمَهُ بِعُنْفٍ.'], answer: 0,
        feedback: ['The advice continues, and gentleness and wisdom remain part of the meaning.', 'تَوَقَّفَ reverses the continuation expressed by مَا زَالَ.', 'The action continues, but بِعُنْفٍ reverses the manner بِرِفْقٍ.'],
        targets: ['ma-zala', 'gentleness'] },
      { id: 'meaning', phase: 'understand', type: 'comprehension',
        prompt: 'كَيْفَ كَانَ يَدْعُو قَوْمَهُ؟',
        options: ['بِغَضَبٍ وَعُنْفٍ', 'بِحِكْمَةٍ وَلِينٍ', 'لَمْ يَكُنْ يَدْعُوهُمْ'], answer: 1,
        feedback: ['The source names رِفْقٍ, the opposite of violence.', 'لِينٍ restates رِفْقٍ while keeping حِكْمَةٍ.', 'مَا زَالَ says the calling continues; it does not cancel it.'],
        hint: 'Use the phrase beginning بِحِكْمَةٍ.', targets: ['gentleness', 'ma-zala'] },
      { id: 'transfer-build', phase: 'transfer', type: 'sentence_reconstruction',
        prompt: 'Build “Khālid is still waiting at the door”: مَا زَالَ, then the person, action and place.',
        options: ['مَا زَالَ', 'خَالِدٌ', 'يَنْتَظِرُ', 'عِنْدَ الْبَابِ'], answer: [0, 1, 2, 3],
        explanation: 'The waiting is ongoing. Changing the person and action does not change the meaning of مَا زَالَ.',
        hint: 'Name the person before the verb describing what continues.', targets: ['ma-zala'] },
      { id: 'transfer-meaning', phase: 'transfer', type: 'transfer_example',
        arabic: 'مَا زَالَتْ مَرْيَمُ تُعَامِلُ الصَّغِيرَ بِرِفْقٍ.',
        prompt: 'What remains true in this new sentence?',
        options: ['تَوَقَّفَتْ عَنْ مُعَامَلَتِهِ بِلِينٍ.', 'تُوَاصِلُ مُعَامَلَتَهُ بِعُنْفٍ.', 'تُوَاصِلُ مُعَامَلَتَهُ بِلِينٍ.'], answer: 2,
        feedback: ['مَا زَالَتْ expresses continuation, not stopping.', 'The continuation is right, but violence changes the meaning of بِرِفْقٍ.', 'The feminine زَالَتْ still expresses continuation, and بِرِفْقٍ still means gently.'],
        hint: 'Check the ongoing action and its manner separately.', targets: ['ma-zala', 'gentleness'] },
    ],
  },
  {
    id: 'while-another-event-happens', revision: 1, stage: 4,
    title: 'While something else happens', titleAr: 'بَيْنَمَا … إِذْ', minutes: 7,
    source: { bookId: 'qasas-v6', chapterId: 'ch8', sentenceIds: ['qs-v6-c08-004c'] },
    context: 'The king and queen of Egypt are beside the Nile. Follow an event that occurs during their walk.',
    objectives: [
      { id: 'background-event', text: 'Separate the ongoing scene in بَيْنَمَا from the event introduced by إِذْ.' },
      { id: 'seeing', text: 'Understand وَقَعَ بَصَرُهُ عَلَى as catching sight of something, including the dual form بَصَرُهُمَا.' },
    ],
    vocabulary: [{ id: 'stroll', ar: 'تَنَزَّهَ', meaning: 'خَرَجَ يَمْشِي لِيَسْتَمْتِعَ وَيَسْتَرِيحَ' }],
    constructions: [
      { id: 'while-event', ar: 'بَيْنَمَا … إِذْ …', meaning: 'One event occurs during an ongoing situation.' },
      { id: 'catch-sight', ar: 'وَقَعَ بَصَرُهُ عَلَى', meaning: 'He caught sight of / noticed.' },
      { id: 'dual-reference', ar: 'يَتَنَزَّهَانِ … بَصَرُهُمَا', meaning: 'The two walkers are also the two people who see.' },
    ],
    chunks: ['وَبَيْنَمَا يَتَنَزَّهَانِ', 'إِذْ وَقَعَ بَصَرُهُمَا', 'عَلَى صُنْدُوقٍ'],
    support: {
      vocabulary: 'يَتَنَزَّهَانِ: يَمْشِيَانِ لِلنُّزْهَةِ. صُنْدُوقٌ: a box or chest.',
      structure: 'بَيْنَمَا sets the ongoing walk. إِذْ introduces what happens during it. ـانِ and ـهُمَا both point to the king and queen.',
      paraphrase: 'أَثْنَاءَ نُزْهَةِ الْمَلِكِ وَالْمَلِكَةِ، رَأَيَا صُنْدُوقًا.',
      explanation: 'Their sight falls on the chest: they notice it. The wording does not say they fell or opened it. Seeing happens while the walk is in progress.',
    },
    exercises: [
      { id: 'word', phase: 'prepare', type: 'contextual_vocabulary',
        arabic: 'خَرَجَ سَالِمٌ يَتَنَزَّهُ فِي الْحَدِيقَةِ لِيَسْتَرِيحَ مِنَ الْعَمَلِ.',
        prompt: 'What is Sālim doing in يَتَنَزَّهُ?',
        options: ['يَعْمَلُ فِي زِرَاعَةِ الْحَدِيقَةِ.', 'يَمْشِي لِيَسْتَمْتِعَ وَيَسْتَرِيحَ.', 'يَبْحَثُ عَنْ شَيْءٍ ضَائِعٍ.'], answer: 1,
        feedback: ['The garden is the setting, but he is taking a break from work.', 'The walk is for rest and enjoyment.', 'The sentence gives rest as his purpose; it mentions no lost object.'],
        hint: 'لِيَسْتَرِيحَ explains why he went out.', targets: ['stroll'] },
      { id: 'expression', phase: 'prepare', type: 'contextual_vocabulary',
        arabic: 'وَقَعَ بَصَرِي عَلَى كِتَابٍ فِي النَّافِذَةِ، فَوَقَفْتُ أَنْظُرُ إِلَيْهِ.',
        prompt: 'What does وَقَعَ بَصَرِي عَلَى describe?',
        options: ['سَقَطْتُ فَوْقَ الْكِتَابِ.', 'سَقَطَ الْكِتَابُ مِنَ النَّافِذَةِ.', 'لَاحَظْتُ الْكِتَابَ وَرَأَيْتُهُ.'], answer: 2,
        feedback: ['It is بَصَرِي, my sight, that “falls on” the book. I have not physically fallen.', 'The book is what I notice; the expression says nothing about it falling.', 'Read the whole expression as catching sight of the book.'],
        hint: 'The following action is stopping to look at it.', targets: ['catch-sight'] },
      { id: 'notice', phase: 'notice', type: 'pronoun_reference',
        arabic: 'يَتَنَزَّهَانِ … بَصَرُهُمَا', prompt: 'How many people do both actions?',
        options: ['شَخْصَانِ فِي الْفِعْلَيْنِ', 'شَخْصٌ يَمْشِي وَشَخْصَانِ يَرَيَانِ', 'شَخْصَانِ يَمْشِيَانِ وَشَخْصٌ يَرَى'], answer: 0,
        feedback: ['ـانِ and ـهُمَا both refer to the same pair.', 'The ـانِ ending of يَتَنَزَّهَانِ already marks two walkers.', 'ـهُمَا keeps both people in the seeing event.'],
        hint: 'Both endings refer to two people.', targets: ['dual-reference'] },
      { id: 'build', phase: 'manipulate', type: 'reorder_chunks',
        prompt: 'Begin with the ongoing walk, then the seeing event, then what they see.',
        options: ['وَبَيْنَمَا يَتَنَزَّهَانِ', 'إِذْ وَقَعَ بَصَرُهُمَا', 'عَلَى صُنْدُوقٍ'], answer: [0, 1, 2],
        explanation: 'بَيْنَمَا opens the background scene. إِذْ introduces the event inside it, and عَلَى completes the expression about seeing.',
        hint: 'Keep وَقَعَ بَصَرُهُمَا connected to عَلَى صُنْدُوقٍ.', targets: ['while-event', 'catch-sight'] },
      { id: 'decode', phase: 'decode', type: 'arabic_paraphrase',
        prompt: 'Which reading keeps the same relationship between walking and seeing?',
        options: ['فَرَغَا مِنَ النُّزْهَةِ ثُمَّ خَرَجَا لِيَبْحَثَا عَنْ صُنْدُوقٍ.', 'أَثْنَاءَ نُزْهَتِهِمَا رَأَيَا صُنْدُوقًا.', 'أَثْنَاءَ نُزْهَتِهِمَا سَقَطَا عَلَى صُنْدُوقٍ.'], answer: 1,
        feedback: ['بَيْنَمَا places the seeing during the walk; it does not describe a later search.', 'Both people notice the chest while their walk is still in progress.', 'وَقَعَ بَصَرُهُمَا describes seeing, not the two people physically falling.'],
        targets: ['while-event', 'catch-sight', 'dual-reference'] },
      { id: 'meaning', phase: 'understand', type: 'comprehension',
        prompt: 'What does this excerpt establish about the chest?',
        options: ['فَتَحَاهُ.', 'أَخَذَاهُ مَعَهُمَا.', 'رَأَيَاهُ.'], answer: 2,
        feedback: ['Opening would require another action; it is not stated in the excerpt.', 'Seeing the chest does not establish that they took it.', 'The expression establishes that both caught sight of it.'],
        hint: 'Limit your answer to the event expressed by وَقَعَ بَصَرُهُمَا عَلَى.', targets: ['catch-sight', 'dual-reference'] },
      { id: 'transfer-build', phase: 'transfer', type: 'sentence_reconstruction',
        prompt: 'New scene: start with “while I was reading”, then introduce hearing a voice using إِذْ.',
        options: ['بَيْنَمَا كُنْتُ أَقْرَأُ', 'إِذْ سَمِعْتُ', 'صَوْتًا'], answer: [0, 1, 2],
        explanation: 'Reading is the ongoing activity; hearing the voice is the event that occurs during it.',
        hint: 'The ongoing activity comes after بَيْنَمَا.', targets: ['while-event'] },
      { id: 'transfer-meaning', phase: 'transfer', type: 'transfer_example',
        arabic: 'بَيْنَمَا يَتَنَزَّهُ خَالِدٌ إِذْ وَقَعَ بَصَرُهُ عَلَى قِطَّةٍ.',
        prompt: 'Which account preserves the new scene?',
        options: ['رَأَى خَالِدٌ قِطَّةً أَثْنَاءَ نُزْهَتِهِ.', 'سَقَطَ خَالِدٌ عَلَى قِطَّةٍ أَثْنَاءَ نُزْهَتِهِ.', 'انْتَهَى خَالِدٌ مِنْ نُزْهَتِهِ، ثُمَّ خَرَجَ لِيَبْحَثَ عَنْ قِطَّةٍ.'], answer: 0,
        feedback: ['The person and object change, but noticing still happens during the walk.', 'بَصَرُهُ is his sight; the idiom does not describe a physical fall.', 'بَيْنَمَا keeps the seeing inside the walk, not in a later search.'],
        hint: 'Keep the ongoing scene and the meaning of وَقَعَ بَصَرُهُ عَلَى together.', targets: ['while-event', 'catch-sight', 'stroll'] },
    ],
  },
];
