// القراءة الراشدة, volume one -- the book shell the Library screen reads.
//
// Chapter BODIES are lazy: only `load()` pulls in a chapter-NN.js (each is
// tens of kilobytes of tokenized prose, and a reader only ever has one open),
// so the shells here stay cheap enough to import eagerly from
// content-lit/index.js. Everything in a shell is what the contents page needs
// to draw a chapter row before it is opened; everything else lives in the
// chapter module.
//
// Adding a chapter: author chapter-NN.js directly (see ../CHAPTER-FORMAT.md),
// then add one entry here, in reading order. Order is what gates progression --
// chapter N unlocks when chapter N-1 is finished.
export const BOOK = {
  id: 'qiraah-v1',
  title: { ar: 'الْقِرَاءَةُ الرَّاشِدَةُ', en: 'Al-Qirāʾah ar-Rāshidah' },
  volumeLabel: 'Volume One',
  author: { ar: 'أَبُو الْحَسَنِ عَلِيٌّ النَّدْوِيُّ', en: 'Abū al-Ḥasan ʿAlī an-Nadwī' },
  blurb: 'Graded classical prose for the first year — short, vowelled passages read one paragraph at a time, then drilled on their own patterns and vocabulary.',
  chapters: [
    {
      id: 'ch1',
      number: 1,
      title: { ar: 'كَيْفَ أَقْضِي يَوْمِي', en: 'How I Spend My Day' },
      pages: [30, 31],
      blurb: 'A day from waking to sleeping, told entirely in the first-person مضارع.',
      load: () => import('./chapter-01.js'),
    },
    {
      id: 'ch2',
      number: 2,
      title: { ar: 'لَمَّا بَلَغْتُ السَّابِعَةَ مِنْ عُمُرِيْ', en: 'When I Reached the Seventh Year of My Age' },
      pages: [32, 33, 34],
      blurb: 'A boy takes up the discipline of prayer at his father’s side, and keeps it up through a crowded match and every excuse not to.',
      load: () => import('./chapter-02.js'),
    },
    {
      id: 'ch3',
      number: 3,
      title: { ar: 'النَّمْلَةُ', en: 'The Ant' },
      pages: [35, 36],
      blurb: 'A short poem: the ant speaks in her own voice about hard work, planning ahead, and never being idle. The book’s first verse chapter.',
      load: () => import('./chapter-03.js'),
    },
    {
      id: 'ch4',
      number: 4,
      title: { ar: 'فِي السُّوْقِ', en: 'In the Market' },
      pages: [37, 38, 39, 40],
      blurb: 'Umar takes his new neighbor Khalid on a tour of the market — fruit-sellers, cloth shops, a shoe bargain, a restaurant, and the stationer’s. The book’s first dialogue chapter.',
      load: () => import('./chapter-04.js'),
    },
    {
      id: 'ch5',
      number: 5,
      title: { ar: 'الطَّائِرُ', en: 'The Bird' },
      pages: [41, 42],
      blurb: 'A caged bird refuses to call captivity home, however gilded the cage — a short second poem, sung in its own voice.',
      load: () => import('./chapter-05.js'),
    },
    {
      id: 'ch6',
      number: 6,
      title: { ar: 'نُزْهَةٌ وَطَبْخٌ', en: 'An Outing and Cooking' },
      pages: [43, 44, 45],
      blurb: 'Five friends plan a picnic on a school holiday — hiring a carriage, dividing up the cooking and firewood, eating together, and praying Ẓuhr before heading home. The book’s first first-person-plural chapter.',
      load: () => import('./chapter-06.js'),
    },
    {
      id: 'ch7',
      number: 7,
      title: { ar: 'مَنْ يَمْنَعُكَ مِنِّيْ؟', en: 'Who Will Protect You From Me?' },
      pages: [46, 47, 48],
      blurb: 'A hadith from a ghazwah: a polytheist draws the sleeping Prophet’s ﷺ own sword on him and asks who will protect him now — the book’s first third-person sīrah narrative.',
      load: () => import('./chapter-07.js'),
    },
    {
      id: 'ch8',
      number: 8,
      title: { ar: 'سَفَرُ الْقِطَارِ', en: 'The Train Journey' },
      pages: [49, 50, 51, 52],
      blurb: 'A boy’s first train journey — the frantic morning departure, the crowded platform, vendors and gifts on board, a prayer stop at Ẓuhr, and reunion with friends back home. The book’s longest chapter yet.',
      load: () => import('./chapter-08.js'),
    },
    {
      id: 'ch9',
      number: 9,
      title: { ar: 'مَاذَا تُحِبُّ أَنْ تَكُوْنَ؟', en: 'What Do You Like to Be?' },
      pages: [53, 54, 55, 56],
      blurb: 'A teacher asks nine students what they want to be when they grow up — driver, ship’s captain, doctor, farmer, merchant, inventor, soldier, a rich man, a scholar — with a brief debate along the way and a closing word on wealth as a trust. The book’s first multi-speaker classroom dialogue.',
      load: () => import('./chapter-09.js'),
    },
    {
      id: 'ch10',
      number: 10,
      title: { ar: 'مُسَابَقَةٌ', en: 'A Competition' },
      pages: [57, 58, 59],
      blurb: 'The sports teacher lines up twenty-four students, three to a row, for a school running competition — Muhammad wins the first heat with Ibrahim close behind, the narrator comes in second in his own heat, and Khalid takes the next, before the teacher closes with a reminder that the Prophet ﷺ himself used to race, and that a Muslim should stay fit for jihad.',
      load: () => import('./chapter-10.js'),
    },
    {
      id: 'ch11',
      number: 11,
      title: { ar: 'السَّاعَةُ', en: 'The Watch' },
      pages: [60, 61, 62],
      blurb: 'Harith’s watch has stopped because he forgot to wind it, so Sa’id helps him set it by his own — leading into an easy back-and-forth about telling time, what their watches cost, and why a watch matters: it is how a student knows the school schedule and a Muslim knows the prayer times.',
      load: () => import('./chapter-11.js'),
    },
    {
      id: 'ch12',
      number: 12,
      title: { ar: 'اَلْفُطُوْرُ', en: 'Breaking the Fast' },
      pages: [63, 64, 65],
      blurb: 'A boy begs his parents to let him fast a day of Ramadan, envying the honor and gifts his friend Mahmoud got for fasting — his parents relent, his mother hosts a sahoor with his friends, and he makes it through hunger, midday thirst, and an afternoon temptation to break his fast early, resisting because, even if no one else sees him, God does — until the adhan finally sounds and the family breaks the fast together at the mosque.',
      load: () => import('./chapter-12.js'),
    },
    {
      id: 'ch13',
      number: 13,
      title: { ar: 'اَلْأَمَانَةُ', en: 'The Trust' },
      pages: [66, 67, 68],
      blurb: 'The hadith of the honest employer, one of three trapped by a boulder in a cave: when a hired worker leaves without collecting his wage, the man invests it faithfully rather than touch it himself, and it grows into camels, cattle, sheep, and servants he hands over whole years later — the same trustworthiness he later begs God, in the darkness of the cave, to save him for.',
      load: () => import('./chapter-13.js'),
    },
    {
      id: 'ch14',
      number: 14,
      title: { ar: 'اَلصَّيْدُ', en: 'The Hunt' },
      pages: [69, 70, 71],
      blurb: 'A hunting trip with friends goes hungry and thirsty when the boy carrying lunch loses the way, but the group presses on into the forest, downs a wild cow and pigeons and ducks — each kill properly slaughtered with a blessing — until the narrator gets his own turn with the rifle and brings down two pigeons himself, and the whole village shares in the meat that evening.',
      load: () => import('./chapter-14.js'),
    },
    {
      id: 'ch15',
      number: 15,
      title: { ar: 'مَأْدُبَةٌ', en: 'A Banquet' },
      pages: [72, 73],
      blurb: 'The narrator’s brother comes home from Hajj to a family feast — clean mats spread out front, pitchers and soap for washing hands, a wide sufra laden with hot bread, meat, rice, and yogurt — and after the meal the guests linger to hear news of the Hijaz, Mecca, Medina, Arafat, and Mina, longing for Hajj themselves, before rising to leave with the traditional guest’s blessing on the household. The book’s shortest chapter, at two pages.',
      load: () => import('./chapter-15.js'),
    },
    {
      id: 'ch16',
      number: 16,
      title: { ar: 'بِرُّ الْوَالِدَيْنِ', en: 'Dutifulness to One’s Parents' },
      pages: [74, 75, 76],
      blurb: 'The second man’s story from the hadith of the three men in the cave: a herder dutiful to his elderly parents comes home late one night to find them already asleep, and refuses to wake them or let his own hungry children drink the milk first — standing all night with the cup in hand until they wake at dawn. Years later, trapped in a cave behind a rolling boulder, he calls on God by that very act of devotion, and is freed.',
      load: () => import('./chapter-16.js'),
    },
    {
      id: 'ch17',
      number: 17,
      title: { ar: 'فَضِيْلَةُ الشُّغْلِ', en: 'The Virtue of Work' },
      pages: [77, 78],
      blurb: 'The hadith of the Prophet ﷺ and the poor man of the Anṣār: rather than give him charity, the Prophet auctions off the man’s last two possessions with his own hand, hands him the proceeds to buy food and an axe, and sends him off to gather and sell firewood for a fortnight — closing with the saying that this is better for him than begging leaving a mark on his face on the Day of Judgment.',
      load: () => import('./chapter-17.js'),
    },
    {
      id: 'ch18',
      number: 18,
      title: { ar: 'تَرْنِيْمَةُ الْوَلَدِ فِي الصَّبَاحِ', en: 'The Child’s Morning Song' },
      pages: [79],
      blurb: 'The book’s third verse chapter and its shortest yet, at a single page — an eight-line hymn in a child’s voice giving thanks at sunrise, delighting in the birdsong and the light, wishing never to be idle, and thanking God for protection through the night.',
      load: () => import('./chapter-18.js'),
    },
    {
      id: 'ch19',
      number: 19,
      title: { ar: 'أَصْدِقَائِيْ', en: 'My Friends' },
      pages: [80, 81, 82],
      blurb: 'The narrator introduces his four closest friends: well-mannered, forbearing Ḥasan, next door and never once quarreled with in years; clever, ever-cheerful Qāsim, a natural storyteller who has never failed an exam; the orphan ʿUmar, too proud to lean on his sewing mother, who fails once, is talked out of quitting school, and comes back to excel; and Muḥammad, a bright, diligent top-of-the-class writer — closing with the hope that the narrator himself is not the worst of the four.',
      load: () => import('./chapter-19.js'),
    },
    {
      id: 'ch20',
      number: 20,
      title: { ar: 'قَرْيَتِيْ', en: 'My Village' },
      pages: [83, 84, 85],
      blurb: 'A first-person portrait of the narrator’s village and the clear, sand-bottomed river running beneath it — swimming lessons, a frightened friend from town coaxed into the water, the village turning almost into an island when the river floods, the year of the great flood that emptied it for a month, its fame as a birthplace of scholars, and the three-hundred-year-old riverside mosque that has never once given way.',
      load: () => import('./chapter-20.js'),
    },
    {
      id: 'ch21',
      number: 21,
      title: { ar: 'تَرْنِيْمَةُ اللَّيْلِ', en: "Night's Lullaby" },
      pages: [86, 87],
      blurb: 'A parent sings a child to sleep, verse by verse, safe in the keeping of the Lord who is never heedless of anyone. The book’s fourth poem, and its first lullaby.',
      load: () => import('./chapter-21.js'),
    },
    {
      id: 'ch22',
      number: 22,
      title: { ar: 'مُسَابَقَةٌ بَيْنَ شَقِيْقَيْنِ', en: 'A Race Between Two Brothers' },
      pages: [88, 89],
      blurb: 'At Badr, two young Ansari brothers each secretly vow to kill Abu Jahl for insulting the Messenger of Allah ﷺ — and when both strike him down, each independently tells the Prophet ﷺ "I killed him." The book’s second sirah narrative, drawn from the two Sahihs.',
      load: () => import('./chapter-22.js'),
    },
    {
      id: 'ch23',
      number: 23,
      title: { ar: 'جَزَاءُ الْوَالِدَيْنِ', en: 'The Reward of Parents' },
      pages: [90, 91, 92],
      blurb: 'A grown son looks back on a mother’s sleepless nights and a father’s constant care, and asks how a child could ever repay them — closing in his own words with the Qurʾanic duʿaā’ for mercy on the two who raised him small.',
      load: () => import('./chapter-23.js'),
    },
    {
      id: 'ch24',
      number: 24,
      title: { ar: 'أَدَبُ الأَكْلِ وَالشُّرْبِ', en: 'The Etiquette of Eating and Drinking' },
      pages: [93, 94, 95],
      blurb: 'A boy raised at the Prophet’s ﷺ own table learns to name Allah and eat from what is nearest him — followed by fifteen more hadiths on table manners, from licking one’s fingers to the ban on silver and gold vessels. The book’s first hadith anthology.',
      load: () => import('./chapter-24.js'),
    },
    {
      id: 'ch25',
      number: 25,
      title: { ar: 'شَرٌّ وَخَيْرٌ', en: 'Bad and Good' },
      pages: [96, 97],
      blurb: 'Ten two-line proverbs on lying and manners, stinginess and generosity, reason and vanity, the fleetingness of life and wealth -- the last three attributed to the poet Abu al-’Atahiyah. The book’s fifth verse chapter, and its first not a single continuous poem.',
      load: () => import('./chapter-25.js'),
    },
    {
      id: 'ch26',
      number: 26,
      title: { ar: 'يَوْمٌ مَطِيْرٌ', en: 'A Rainy Day' },
      pages: [98, 99, 100],
      blurb: 'A night of rain leaves the roads a muddy mess, and the narrator forgets his umbrella, visits his friend Mas’ud who talks him out of a walk, and races the returning rain home -- closing on the year’s heavy floods and the houses they brought down.',
      load: () => import('./chapter-26.js'),
    },
    {
      id: 'ch27',
      number: 27,
      title: { ar: 'الْبَرِيْدُ', en: 'The Post' },
      pages: [101, 102, 103],
      blurb: 'Khalid asks Tariq how a letter reaches his brother in Delhi without either of them traveling -- envelope, address, and stamp, a red mailbox on the street, sorting and a train ride, and a second sorting before a postman carries it the last stretch.',
      load: () => import('./chapter-27.js'),
    },
    {
      id: 'ch28',
      number: 28,
      title: { ar: 'الْبَرِيْدُ', en: 'The Post (II)' },
      pages: [104, 105, 106],
      blurb: 'Khalid and Tariq keep talking about the post -- the postman himself in his grey uniform and leather satchel, a second postman on a red bicycle who only rides for urgent telegrams, one postman per neighborhood rather than one for a whole city, and how the postage stamp pays for it all -- before Khalid resolves to write to his own friend Jameel.',
      load: () => import('./chapter-28.js'),
    },
    {
      id: 'ch29',
      number: 29,
      title: { ar: 'مَنْ يَضَعُ الْحَجَرَ؟', en: 'Who Places the Stone?' },
      pages: [107, 108, 109],
      blurb: 'The story of the Kaaba -- built by Ibrahim, the Friend of Allah, then rebuilt by Quraysh when its old structure gave way -- leads into the pre-Islamic dispute over which tribe would have the honor of setting the Black Stone in its place, escalating toward tribal war.',
      load: () => import('./chapter-29.js'),
    },
    {
      id: 'ch30',
      number: 30,
      title: { ar: 'مَنْ يَضَعُ الْحَجَرَ؟', en: 'Who Places the Stone? (II)' },
      pages: [110, 111],
      blurb: 'Quraysh weighs war against a peaceful way to place the Black Stone, until an elder proposes that whoever next enters the mosque door shall decide -- and it turns out to be the young Muhammad ﷺ, already known to them as al-Amin, the Trustworthy, who spreads the stone in a cloth so every tribe can share in lifting it into place.',
      load: () => import('./chapter-30.js'),
    },
    {
      id: 'ch31',
      number: 31,
      title: { ar: 'يَوْمُ الْعِيْدِ', en: 'The Day of Eid' },
      pages: [112, 113, 114],
      blurb: "On the night the crescent moon is sighted, children rush home rejoicing, hardly sleeping before the morning of Eid -- new clothes, new shoes, and gifts for most, but not for a poor orphan boy, who eyes the other children's finery with shame until his mother's kind employer, Sa'id, is moved to give him a clean garment of his own. The chapter closes with the people gathering at the prayer ground for the Eid prayer and sermon, exchanging visits and Eid greetings, and reflecting wistfully on Ramadan once it has gone -- the final chapter of Volume 1.",
      load: () => import('./chapter-31.js'),
    },
  ],
};
