// القراءة الراشدة, volume two, chapter 62 (printed heading "٦٢") --
// الْقَاطِرَةُ (٢) -- "The Locomotive (2)".
//
// Source: _al-qir`atur-rashida 1-2.pdf, printed pages 205-207. Direct
// continuation of own ch61 -- Sa'id (the father) is still speaking to
// Rashid throughout; no new "قَالَ" frame reopens, so unlike ch61 this
// chapter's paragraphs are Sa'id's uninterrupted explanation.
//
// Paragraph granularity: 8 blank-line-separated blocks -- P1-C (the
// furnace, boiler pipes, and gearing that turn the wheels) on p.205; P-D
// (the fireman and the driver's duties, the signal flags) spans
// p.205-206; P-E (the regulator and the brake) and P-F (the rail line) on
// p.206; P-G (recap) and P-H (the closing Qur'anic exclamation, Q43:13-14)
// on p.207, followed by the printed "٭ ٭ ٭" divider (not tokenized).
//
// Qur'anic quotation (qr2-62-050): kept as ONE sentence spanning both
// verses (13 tokens) rather than split at the ۝ mark, per the project's
// documented workaround (QASAS_AGENT_BRIEF.md §6) for a chapter-format gap
// -- there is no `type` field to mark a sentence "don't drill this", so a
// Qur'anic clause is instead kept outside the 3-9 token buildable range on
// purpose. Its full reference (Q43:13-14, Surat az-Zukhruf) is noted in
// its own `en`.
//
// Homographs / reused lemmas (existing lemma key, no new newWords entry):
// "دَارَ/أَدَارَ" reuses the corpus's existing "دار" lemma (Form IV
// causative "turn/rotate it" vs. the base "turn"); "رَجَعَ", "أَمِيْنُ",
// "الشُّكْرَ", "رَكِبْتَ", "بَلَدٍ", "الأَنْفُسِ", "يَحِقُّ", "اجْتَمَعَ",
// "دَفَعَ", and "الطَّرِيْقَ" all reuse already-known lemma keys.
export const CHAPTER = {
  id: 'ch62',
  title: { ar: 'الْقَاطِرَةُ', en: 'The Locomotive' },
  newWords: [
    'موقد', 'فحم', 'حجري', 'حوض', 'متين', 'أنبوب', 'وقاد', 'أشرف', 'أدار', 'دوران',
    'مفتاح', 'واجب', 'جد', 'طوع',
    'إشارة', 'بيرق', 'أحمر', 'أخضر', 'آلة',
    'مصد', 'عربة', 'حديدي', 'لولا', 'غاص',
    'بالغ', 'ألهم', 'حكمة'
  ],
  lemmas: {
    'موقد': { gloss: 'furnace, firebox' },
    'فحم': { gloss: 'coal' },
    'حجري': { gloss: 'stony, mineral (coal: الفحم الحجري = "mineral/hard coal")' },
    'حوض': { gloss: 'tank, basin' },
    'متين': { gloss: 'sturdy, solid' },
    'أنبوب': { gloss: 'pipe, tube' },
    'وقاد': { gloss: 'stoker, fireman' },
    'أشرف': { gloss: 'to oversee, supervise' },
    'أدار': { gloss: 'to turn, rotate (something)' },
    'دوران': { gloss: 'rotation, turning' },
    'مفتاح': { gloss: 'key' },
    'واجب': { gloss: 'duty' },
    'جد': { gloss: 'diligence, earnestness' },
    'طوع': { gloss: 'compliance, obedience (طَوْعُ إِشَارَتِهِ: at his signal\'s command)' },
    'إشارة': { gloss: 'signal' },
    'بيرق': { gloss: 'flag', book_note: 'الْبَيْرَق : جمع الْبَيَارِق : الْعَلَم الْكَبِير .' },
    'ضغط': { gloss: 'to press', book_note: 'ضَغَطَ يَضْغَطُ ضَغْطاً: عليه (عليها) شَدَّدَ وضَيَّقَ.' },
    'أحمر': { gloss: 'red' },
    'أخضر': { gloss: 'green' },
    'آلة': { gloss: 'lever, mechanism, instrument' },
    'مصد': { gloss: 'brake' },
    'عربة': { gloss: 'carriage, cart' },
    'حديدي': { gloss: 'iron, made of iron' },
    'لولا': { gloss: 'were it not for' },
    'غاص': { gloss: 'to sink, plunge' },
    'بالغ': { gloss: 'reaching, attaining' },
    'شق': { gloss: 'hardship, difficulty', book_note: 'بِشِقِّ الأَنْفُسِ: بِالْجُهْدِ وَالْمَشَقَّةِ.' },
    'ألهم': { gloss: 'to inspire' },
    'حكمة': { gloss: 'wisdom' }
  },
  paragraphs: [
    {
      en: 'Look, Rashid, at this furnace in the locomotive — the man shovels coal into it, and above the furnace is a very sturdy water tank with numerous pipes in it; the water is heated by the fire and turns to steam, which then passes into the pipes.',
      sentences: [
        { id: 'qr2-62-001', ar: 'انْظُرْ يَا رَشِيْدُ!', en: 'Look, Rashid!',
          tokens: [
            { surface: 'انْظُرْ', lemma: 'نظر', pos: 'verb', features: 'imp.2ms', gloss: 'look!' },
            { surface: 'يَا', lemma: 'يا', pos: 'part', gloss: 'O (vocative)' },
            { surface: 'رَشِيْدُ', lemma: 'رشيد', pos: 'proper', gloss: 'Rashid' },
          ] },
        { id: 'qr2-62-002', ar: 'إِلَىٰ هٰذَا الْمَوْقِدِ فِي الْقَاطِرَةِ،', en: 'at this furnace in the locomotive,',
          tokens: [
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'at' },
            { surface: 'هٰذَا', lemma: 'هذا', pos: 'dem', gloss: 'this' },
            { surface: 'الْمَوْقِدِ', lemma: 'موقد', pos: 'noun', features: 'def.gen', gloss: 'the furnace' },
            { surface: 'فِي', lemma: 'في', pos: 'prep', gloss: 'in' },
            { surface: 'الْقَاطِرَةِ', lemma: 'قاطرة', pos: 'noun', features: 'def.gen', gloss: 'the locomotive' },
          ] },
        { id: 'qr2-62-003', ar: 'يُلْقِيْ فِيْهِ الرَّجُلُ الْفَحْمَ الْحَجَرِيَّ،', en: 'the man throws coal into it,',
          tokens: [
            { surface: 'يُلْقِيْ', lemma: 'ألقى', pos: 'verb', features: 'impf.3ms', gloss: 'to throw, cast' },
            { surface: 'فِيْهِ', lemma: 'في', pos: 'prep', features: '3ms', gloss: 'into it' },
            { surface: 'الرَّجُلُ', lemma: 'رجل', pos: 'noun', features: 'def.nom', gloss: 'the man' },
            { surface: 'الْفَحْمَ', lemma: 'فحم', pos: 'noun', features: 'def.acc', gloss: 'the coal' },
            { surface: 'الْحَجَرِيَّ', lemma: 'حجري', pos: 'adj', features: 'def.acc', gloss: 'mineral, stony' },
          ] },
        { id: 'qr2-62-004', ar: 'وَفَوْقَ هٰذَا الْمَوْقِدِ حَوْضٌ مِنْ مَاءٍ مَتِيْنٌ جِدّاً',
          en: 'and above this furnace is a very sturdy tank of water',
          tokens: [
            { surface: 'وَفَوْقَ', lemma: 'فوق', pos: 'adv', features: 'conj', gloss: 'and above' },
            { surface: 'هٰذَا', lemma: 'هذا', pos: 'dem', gloss: 'this' },
            { surface: 'الْمَوْقِدِ', lemma: 'موقد', pos: 'noun', features: 'def.gen', gloss: 'the furnace' },
            { surface: 'حَوْضٌ', lemma: 'حوض', pos: 'noun', features: 'indef.nom', gloss: 'a tank, basin' },
            { surface: 'مِنْ', lemma: 'من', pos: 'prep', gloss: 'of' },
            { surface: 'مَاءٍ', lemma: 'ماء', pos: 'noun', features: 'indef.gen', gloss: 'water' },
            { surface: 'مَتِيْنٌ', lemma: 'متين', pos: 'adj', features: 'indef.nom', gloss: 'sturdy, solid' },
            { surface: 'جِدّاً', lemma: 'جدا', pos: 'adv', features: 'indef.acc', gloss: 'very' },
          ] },
        { id: 'qr2-62-005', ar: 'وَفِيْهِ أَنَابِيْبُ عَدِيْدَةٌ', en: 'with numerous pipes in it;',
          tokens: [
            { surface: 'وَفِيْهِ', lemma: 'في', pos: 'prep', features: 'conj+3ms', gloss: 'and in it' },
            { surface: 'أَنَابِيْبُ', lemma: 'أنبوب', pos: 'noun', features: 'indef.nom.pl', gloss: 'pipes' },
            { surface: 'عَدِيْدَةٌ', lemma: 'عديد', pos: 'adj', features: 'indef.nom', gloss: 'numerous' },
          ] },
        { id: 'qr2-62-006', ar: 'يَسْخُنُ هٰذَا الْمَاءُ بِالنَّارِ وَيَتَحَوَّلُ بُخَاراً،',
          en: 'this water is heated by the fire and turns into steam,',
          tokens: [
            { surface: 'يَسْخُنُ', lemma: 'سخن', pos: 'verb', features: 'impf.3ms', gloss: 'to become hot, be heated' },
            { surface: 'هٰذَا', lemma: 'هذا', pos: 'dem', gloss: 'this' },
            { surface: 'الْمَاءُ', lemma: 'ماء', pos: 'noun', features: 'def.nom', gloss: 'the water' },
            { surface: 'بِالنَّارِ', lemma: 'نار', pos: 'noun', features: 'def.gen', gloss: 'by the fire' },
            { surface: 'وَيَتَحَوَّلُ', lemma: 'تحول', pos: 'verb', features: 'conj+impf.3ms', gloss: 'to turn into, become' },
            { surface: 'بُخَاراً', lemma: 'بخار', pos: 'noun', features: 'indef.acc', gloss: 'steam' },
          ] },
        { id: 'qr2-62-007', ar: 'وَيَنْتَقِلُ هٰذَا الْبُخَارُ إِلَى الأَنَابِيْبِ.', en: 'and this steam passes into the pipes.',
          tokens: [
            { surface: 'وَيَنْتَقِلُ', lemma: 'انتقل', pos: 'verb', features: 'conj+impf.3ms', gloss: 'to move, transfer' },
            { surface: 'هٰذَا', lemma: 'هذا', pos: 'dem', gloss: 'this' },
            { surface: 'الْبُخَارُ', lemma: 'بخار', pos: 'noun', features: 'def.nom', gloss: 'the steam' },
            { surface: 'إِلَى', lemma: 'إلى', pos: 'prep', gloss: 'into' },
            { surface: 'الأَنَابِيْبِ', lemma: 'أنبوب', pos: 'noun', features: 'def.gen.pl', gloss: 'the pipes' },
          ] },
      ],
      checks: [
        { q: 'أَيْنَ يُلْقِيْ الرَّجُلُ الْفَحْمَ الْحَجَرِيَّ؟', options: ['فِي الْمَوْقِدِ', 'فِي الْحَوْضِ', 'فِي الأَنَابِيْبِ'], answer: 0,
          qEn: 'Where does the man throw the coal?', optionsEn: ['Into the furnace', 'Into the tank', 'Into the pipes'] },
      ],
    },
    {
      en: 'Come with me into the locomotive, for its driver is a friend of mine, and there you will understand its construction well.',
      sentences: [
        { id: 'qr2-62-008', ar: 'وَتَعَالَ مَعِيَ فِي الْقَاطِرَةِ،', en: 'Come with me into the locomotive,',
          tokens: [
            { surface: 'وَتَعَالَ', lemma: 'تعال', pos: 'verb', features: 'conj+imp.2ms', gloss: 'come!' },
            { surface: 'مَعِيَ', lemma: 'مع', pos: 'prep', features: '1s', gloss: 'with me' },
            { surface: 'فِي', lemma: 'في', pos: 'prep', gloss: 'into' },
            { surface: 'الْقَاطِرَةِ', lemma: 'قاطرة', pos: 'noun', features: 'def.gen', gloss: 'the locomotive' },
          ] },
        { id: 'qr2-62-009', ar: 'فَإِنَّ سَائِقَهَا مِنْ أَصْدِقَائِيْ،', en: 'for its driver is one of my friends,',
          tokens: [
            { surface: 'فَإِنَّ', lemma: 'إن', pos: 'part', gloss: 'for indeed' },
            { surface: 'سَائِقَهَا', lemma: 'سائق', pos: 'noun', features: 'acc+3fs', gloss: 'its driver' },
            { surface: 'مِنْ', lemma: 'من', pos: 'prep', gloss: 'from, among' },
            { surface: 'أَصْدِقَائِيْ', lemma: 'صديق', pos: 'noun', features: 'gen.pl+1s', gloss: 'my friends' },
          ] },
        { id: 'qr2-62-010', ar: 'وَهُنَا تَفْهَمُ تَرْكِيْبَ الْقَاطِرَةِ جَيِّداً.', en: 'and here you will understand the locomotive’s construction well.',
          tokens: [
            { surface: 'وَهُنَا', lemma: 'هنا', pos: 'adv', features: 'conj', gloss: 'and here' },
            { surface: 'تَفْهَمُ', lemma: 'فهم', pos: 'verb', features: 'impf.2ms', gloss: 'to understand' },
            { surface: 'تَرْكِيْبَ', lemma: 'تركيب', pos: 'noun', features: 'acc.constr', gloss: 'the construction of' },
            { surface: 'الْقَاطِرَةِ', lemma: 'قاطرة', pos: 'noun', features: 'def.gen', gloss: 'the locomotive' },
            { surface: 'جَيِّداً', lemma: 'جيد', pos: 'adv', features: 'indef.acc', gloss: 'well' },
          ] },
      ],
      checks: [
        { q: 'مَنْ سَائِقُ هٰذِهِ الْقَاطِرَةِ؟', options: ['صَدِيْقٌ لِسَعِيْدٍ', 'أَخُو رَشِيْدٍ', 'مُعَلِّمُ رَشِيْدٍ'], answer: 0,
          qEn: 'Who is the driver of this locomotive?', optionsEn: ['A friend of Sa’id', 'Rashid’s brother', 'Rashid’s teacher'] },
      ],
    },
    {
      en: 'Look at the pipes: they connect to these delicate mechanisms that turn the locomotive’s wheels. When the steam gathers in the pipes it pushes the mechanisms with its force, turning them, and by their turning the wheels turn and the locomotive moves.',
      sentences: [
        { id: 'qr2-62-011', ar: 'انْظُرْ إِلَى الأَنَابِيْبِ،', en: 'Look at the pipes,',
          tokens: [
            { surface: 'انْظُرْ', lemma: 'نظر', pos: 'verb', features: 'imp.2ms', gloss: 'look!' },
            { surface: 'إِلَى', lemma: 'إلى', pos: 'prep', gloss: 'at' },
            { surface: 'الأَنَابِيْبِ', lemma: 'أنبوب', pos: 'noun', features: 'def.gen.pl', gloss: 'the pipes' },
          ] },
        { id: 'qr2-62-012', ar: 'إِنَّهَا مُتَّصِلَةٌ بِهٰذِهِ الآلاَتِ الدَّقِيْقَةِ الَّتِيْ تُدِيْرُ عَجَلاَتِ الْقَاطِرَةِ،',
          en: 'they are connected to these delicate mechanisms that turn the locomotive’s wheels,',
          tokens: [
            { surface: 'إِنَّهَا', lemma: 'إن', pos: 'part', features: '3fp', gloss: 'indeed they (are)' },
            { surface: 'مُتَّصِلَةٌ', lemma: 'متصل', pos: 'adj', features: 'indef.nom', gloss: 'connected' },
            { surface: 'بِهٰذِهِ', lemma: 'هذه', pos: 'dem', features: 'gen', gloss: 'to these' },
            { surface: 'الآلاَتِ', lemma: 'آلة', pos: 'noun', features: 'def.gen.pl', gloss: 'the mechanisms' },
            { surface: 'الدَّقِيْقَةِ', lemma: 'دقيق', pos: 'adj', features: 'def.gen', gloss: 'delicate, precise' },
            { surface: 'الَّتِيْ', lemma: 'التي', pos: 'rel', gloss: 'which' },
            { surface: 'تُدِيْرُ', lemma: 'أدار', pos: 'verb', features: 'impf.3fs', gloss: 'to turn, rotate (something)' },
            { surface: 'عَجَلاَتِ', lemma: 'عجلة', pos: 'noun', features: 'acc.constr.pl', gloss: 'the wheels of' },
            { surface: 'الْقَاطِرَةِ', lemma: 'قاطرة', pos: 'noun', features: 'def.gen', gloss: 'the locomotive' },
          ] },
        { id: 'qr2-62-013', ar: 'فَإِذَا اجْتَمَعَ هٰذَا الْبُخَارُ فِي الأَنَابِيْبِ دَفَعَ بِقُوَّتِهِ الآلاَتِ،',
          en: 'so when this steam gathers in the pipes, it pushes the mechanisms with its force,',
          tokens: [
            { surface: 'فَإِذَا', lemma: 'إذا', pos: 'part', features: 'conj', gloss: 'so when' },
            { surface: 'اجْتَمَعَ', lemma: 'اجتمع', pos: 'verb', features: 'perf.3ms', gloss: 'to gather' },
            { surface: 'هٰذَا', lemma: 'هذا', pos: 'dem', gloss: 'this' },
            { surface: 'الْبُخَارُ', lemma: 'بخار', pos: 'noun', features: 'def.nom', gloss: 'the steam' },
            { surface: 'فِي', lemma: 'في', pos: 'prep', gloss: 'in' },
            { surface: 'الأَنَابِيْبِ', lemma: 'أنبوب', pos: 'noun', features: 'def.gen.pl', gloss: 'the pipes' },
            { surface: 'دَفَعَ', lemma: 'دفع', pos: 'verb', features: 'perf.3ms', gloss: 'to push' },
            { surface: 'بِقُوَّتِهِ', lemma: 'قوة', pos: 'noun', features: 'gen+3ms', gloss: 'with its force' },
            { surface: 'الآلاَتِ', lemma: 'آلة', pos: 'noun', features: 'def.acc.pl', gloss: 'the mechanisms' },
          ] },
        { id: 'qr2-62-014', ar: 'فَأَدَارَهَا وَبِدَوَرَانِهَا تَدُوْرُ الْعَجَلاَتُ،',
          en: 'turning them, and by their turning the wheels turn,',
          tokens: [
            { surface: 'فَأَدَارَهَا', lemma: 'أدار', pos: 'verb', features: 'conj+perf.3ms+3fp', gloss: 'and turned them' },
            { surface: 'وَبِدَوَرَانِهَا', lemma: 'دوران', pos: 'noun', features: 'conj+gen+3fp', gloss: 'and by their rotation' },
            { surface: 'تَدُوْرُ', lemma: 'دار', pos: 'verb', features: 'impf.3fs', gloss: 'to turn, rotate' },
            { surface: 'الْعَجَلاَتُ', lemma: 'عجلة', pos: 'noun', features: 'def.nom.pl', gloss: 'the wheels' },
          ] },
        { id: 'qr2-62-015', ar: 'وَتَسِيْرُ الْقَاطِرَةُ.', en: 'and the locomotive moves.',
          tokens: [
            { surface: 'وَتَسِيْرُ', lemma: 'سار', pos: 'verb', features: 'conj+impf.3fs', gloss: 'to move, travel' },
            { surface: 'الْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'def.nom', gloss: 'the locomotive' },
          ] },
      ],
      checks: [
        { q: 'مَاذَا يَدْفَعُ الآلاَتِ الَّتِيْ تُدِيْرُ الْعَجَلاَتِ؟', options: ['الْبُخَارُ', 'الْمَاءُ الْبَارِدُ', 'الرِّيْحُ'], answer: 0,
          qEn: 'What pushes the mechanisms that turn the wheels?', optionsEn: ['The steam', 'Cold water', 'The wind'] },
      ],
    },
    {
      en: 'This is the fireman who watches the fire and the water and oversees them both; and this is our friend the driver. If the locomotive pulls the train and delivers passengers from land to land, our friend is the one driving it — he is the key to the train, and to him goes the credit for its running; he stays watchfully at his work and carries out his duty with trustworthiness and diligence. Likewise the guard deserves the passengers’ thanks, for he watches the track and the train’s stopping and starting, and the driver and the locomotive obey his signal: if he waves the red flag the train stops, and if he waves the green flag it moves.',
      sentences: [
        { id: 'qr2-62-016', ar: 'وَهٰذَا هُوَ الْوَقَّادُ الَّذِيْ يُرَاقِبُ النَّارَ وَالْمَاءَ،',
          en: 'This is the fireman who watches over the fire and the water,',
          tokens: [
            { surface: 'وَهٰذَا', lemma: 'هذا', pos: 'dem', features: 'conj', gloss: 'and this' },
            { surface: 'هُوَ', lemma: 'هو', pos: 'part', gloss: '(is)' },
            { surface: 'الْوَقَّادُ', lemma: 'وقاد', pos: 'noun', features: 'def.nom', gloss: 'the fireman, stoker' },
            { surface: 'الَّذِيْ', lemma: 'الذي', pos: 'rel', gloss: 'who' },
            { surface: 'يُرَاقِبُ', lemma: 'راقب', pos: 'verb', features: 'impf.3ms', gloss: 'to watch over, monitor' },
            { surface: 'النَّارَ', lemma: 'نار', pos: 'noun', features: 'def.acc', gloss: 'the fire' },
            { surface: 'وَالْمَاءَ', lemma: 'ماء', pos: 'noun', features: 'conj+def.acc', gloss: 'and the water' },
          ] },
        { id: 'qr2-62-017', ar: 'وَيُشْرِفُ عَلَيْهِمَا،', en: 'and supervises them both,',
          tokens: [
            { surface: 'وَيُشْرِفُ', lemma: 'أشرف', pos: 'verb', features: 'conj+impf.3ms', gloss: 'to oversee, supervise' },
            { surface: 'عَلَيْهِمَا', lemma: 'على', pos: 'prep', features: '3md', gloss: 'over them both' },
          ] },
        { id: 'qr2-62-018', ar: 'وَهٰذَا صَدِيْقُنَا السَّائِقُ،', en: 'and this is our friend the driver.',
          tokens: [
            { surface: 'وَهٰذَا', lemma: 'هذا', pos: 'dem', features: 'conj', gloss: 'and this' },
            { surface: 'صَدِيْقُنَا', lemma: 'صديق', pos: 'noun', features: 'nom+1p', gloss: 'our friend' },
            { surface: 'السَّائِقُ', lemma: 'سائق', pos: 'noun', features: 'def.nom', gloss: 'the driver' },
          ] },
        { id: 'qr2-62-019', ar: 'وَإِذَا كَانَتِ الْقَاطِرَةُ تَجُرُّ الْقِطَارَ،', en: 'If the locomotive pulls the train',
          tokens: [
            { surface: 'وَإِذَا', lemma: 'إذا', pos: 'part', features: 'conj', gloss: 'and if' },
            { surface: 'كَانَتِ', lemma: 'كان', pos: 'verb', features: 'perf.3fs', gloss: 'to be' },
            { surface: 'الْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'def.nom', gloss: 'the locomotive' },
            { surface: 'تَجُرُّ', lemma: 'جر', pos: 'verb', features: 'impf.3fs', gloss: 'to pull, tow' },
            { surface: 'الْقِطَارَ', lemma: 'قطار', pos: 'noun', features: 'def.acc', gloss: 'the train' },
          ] },
        { id: 'qr2-62-020', ar: 'وَتُوْصِلُ الرُّكَّابَ مِنْ دِيَارٍ إِلَىٰ دِيَارٍ،', en: 'and delivers passengers from land to land,',
          tokens: [
            { surface: 'وَتُوْصِلُ', lemma: 'أوصل', pos: 'verb', features: 'conj+impf.3fs', gloss: 'to deliver, convey' },
            { surface: 'الرُّكَّابَ', lemma: 'ركاب', pos: 'noun', features: 'def.acc', gloss: 'the passengers' },
            { surface: 'مِنْ', lemma: 'من', pos: 'prep', gloss: 'from' },
            { surface: 'دِيَارٍ', lemma: 'دار', pos: 'noun', features: 'indef.gen.pl', gloss: 'lands, homes' },
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'to' },
            { surface: 'دِيَارٍ', lemma: 'دار', pos: 'noun', features: 'indef.gen.pl', gloss: 'lands, homes' },
          ] },
        { id: 'qr2-62-021', ar: 'فَصَاحِبُنَا يَسُوْقُ الْقَاطِرَةَ،', en: 'then our friend drives the locomotive,',
          tokens: [
            { surface: 'فَصَاحِبُنَا', lemma: 'صاحب', pos: 'noun', features: 'conj+nom+1p', gloss: 'then our friend' },
            { surface: 'يَسُوْقُ', lemma: 'ساق', pos: 'verb', features: 'impf.3ms', gloss: 'to drive' },
            { surface: 'الْقَاطِرَةَ', lemma: 'قاطرة', pos: 'noun', features: 'def.acc', gloss: 'the locomotive' },
          ] },
        { id: 'qr2-62-022', ar: 'فَهُوَ مِفْتَاحُ الْقِطَارِ،', en: 'for he is the key to the train,',
          tokens: [
            { surface: 'فَهُوَ', lemma: 'هو', pos: 'part', features: 'conj', gloss: 'for he (is)' },
            { surface: 'مِفْتَاحُ', lemma: 'مفتاح', pos: 'noun', features: 'nom.constr', gloss: 'the key of' },
            { surface: 'الْقِطَارِ', lemma: 'قطار', pos: 'noun', features: 'def.gen', gloss: 'the train' },
          ] },
        { id: 'qr2-62-023', ar: 'وَإِلَيْهِ يَرْجِعُ الْفَضْلُ فِيْ سَيْرِ الْقِطَارِ', en: 'and to him goes the credit for the train’s running,',
          tokens: [
            { surface: 'وَإِلَيْهِ', lemma: 'إلى', pos: 'prep', features: 'conj+3ms', gloss: 'and to him' },
            { surface: 'يَرْجِعُ', lemma: 'رجع', pos: 'verb', features: 'impf.3ms', gloss: 'to go back, be due (to)' },
            { surface: 'الْفَضْلُ', lemma: 'فضل', pos: 'noun', features: 'def.nom', gloss: 'the credit, merit' },
            { surface: 'فِيْ', lemma: 'في', pos: 'prep', gloss: 'for, in' },
            { surface: 'سَيْرِ', lemma: 'سير', pos: 'noun', features: 'gen.constr', gloss: 'the running of' },
            { surface: 'الْقِطَارِ', lemma: 'قطار', pos: 'noun', features: 'def.gen', gloss: 'the train' },
          ] },
        { id: 'qr2-62-024', ar: 'وَهُوَ يَسْهَرُ عَلَىٰ عَمَلِهِ،', en: 'and he stays watchfully at his work,',
          tokens: [
            { surface: 'وَهُوَ', lemma: 'هو', pos: 'part', features: 'conj', gloss: 'and he' },
            { surface: 'يَسْهَرُ', lemma: 'سهر', pos: 'verb', features: 'impf.3ms', gloss: 'to stay up watchfully, keep vigil' },
            { surface: 'عَلَىٰ', lemma: 'على', pos: 'prep', gloss: 'at, over' },
            { surface: 'عَمَلِهِ', lemma: 'عمل', pos: 'noun', features: 'gen+3ms', gloss: 'his work' },
          ] },
        { id: 'qr2-62-025', ar: 'وَيَقُوْمُ بِوَاجِبِهِ بِأَمَانَةٍ وَجِدٍّ،', en: 'and carries out his duty with trustworthiness and diligence,',
          tokens: [
            { surface: 'وَيَقُوْمُ', lemma: 'قام', pos: 'verb', features: 'conj+impf.3ms', gloss: 'to carry out (بِـ)' },
            { surface: 'بِوَاجِبِهِ', lemma: 'واجب', pos: 'noun', features: 'gen+3ms', gloss: 'his duty' },
            { surface: 'بِأَمَانَةٍ', lemma: 'أمانة', pos: 'noun', features: 'indef.gen', gloss: 'with trustworthiness' },
            { surface: 'وَجِدٍّ', lemma: 'جد', pos: 'noun', features: 'conj+indef.gen', gloss: 'and diligence' },
          ] },
        { id: 'qr2-62-026', ar: 'وَكَذٰلِكَ أَمِيْنُ الْقِطَارِ يَسْتَحِقُّ الشُّكْرَ مِنَ الرُّكَّابِ،',
          en: 'and likewise the train guard deserves thanks from the passengers,',
          tokens: [
            { surface: 'وَكَذٰلِكَ', lemma: 'كذلك', pos: 'adv', features: 'conj', gloss: 'and likewise' },
            { surface: 'أَمِيْنُ', lemma: 'أمين', pos: 'noun', features: 'nom.constr', gloss: 'the guard, custodian of' },
            { surface: 'الْقِطَارِ', lemma: 'قطار', pos: 'noun', features: 'def.gen', gloss: 'the train' },
            { surface: 'يَسْتَحِقُّ', lemma: 'استحق', pos: 'verb', features: 'impf.3ms', gloss: 'to deserve' },
            { surface: 'الشُّكْرَ', lemma: 'شكر', pos: 'noun', features: 'def.acc', gloss: 'the thanks' },
            { surface: 'مِنَ', lemma: 'من', pos: 'prep', gloss: 'from' },
            { surface: 'الرُّكَّابِ', lemma: 'ركاب', pos: 'noun', features: 'def.gen', gloss: 'the passengers' },
          ] },
        { id: 'qr2-62-027', ar: 'فَإِنَّهُ يُلاَحِظُ الطَّرِيْقَ وَيَلْحَظُ وُقُوْفَ الْقِطَارِ وَسَيْرَهُ،',
          en: 'for he observes the track and watches over the train’s stopping and moving,',
          tokens: [
            { surface: 'فَإِنَّهُ', lemma: 'إن', pos: 'part', features: '3ms', gloss: 'for indeed he' },
            { surface: 'يُلاَحِظُ', lemma: 'لاحظ', pos: 'verb', features: 'impf.3ms', gloss: 'to observe, watch closely' },
            { surface: 'الطَّرِيْقَ', lemma: 'طريق', pos: 'noun', features: 'def.acc', gloss: 'the track, road' },
            { surface: 'وَيَلْحَظُ', lemma: 'لحظ', pos: 'verb', features: 'conj+impf.3ms', gloss: 'to notice, watch over' },
            { surface: 'وُقُوْفَ', lemma: 'وقوف', pos: 'noun', features: 'acc.constr', gloss: 'the stopping of' },
            { surface: 'الْقِطَارِ', lemma: 'قطار', pos: 'noun', features: 'def.gen', gloss: 'the train' },
            { surface: 'وَسَيْرَهُ', lemma: 'سير', pos: 'noun', features: 'conj+acc+3ms', gloss: 'and its moving' },
          ] },
        { id: 'qr2-62-028', ar: 'وَالسَّائِقُ وَالْقَاطِرَةُ طَوْعُ إِشَارَتِهِ،', en: 'and the driver and the locomotive are at the mercy of his signal,',
          tokens: [
            { surface: 'وَالسَّائِقُ', lemma: 'سائق', pos: 'noun', features: 'conj+def.nom', gloss: 'and the driver' },
            { surface: 'وَالْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'conj+def.nom', gloss: 'and the locomotive' },
            { surface: 'طَوْعُ', lemma: 'طوع', pos: 'noun', features: 'nom.constr', gloss: 'in compliance with' },
            { surface: 'إِشَارَتِهِ', lemma: 'إشارة', pos: 'noun', features: 'gen+3ms', gloss: 'his signal' },
          ] },
        { id: 'qr2-62-029', ar: 'فَإِذَا هَزَّ الْبَيْرَقَ الأَحْمَرَ وَقَفَ الْقِطَارُ،', en: 'so if he waves the red flag, the train stops,',
          tokens: [
            { surface: 'فَإِذَا', lemma: 'إذا', pos: 'part', features: 'conj', gloss: 'so if' },
            { surface: 'هَزَّ', lemma: 'هز', pos: 'verb', features: 'perf.3ms', gloss: 'to wave, shake' },
            { surface: 'الْبَيْرَقَ', lemma: 'بيرق', pos: 'noun', features: 'def.acc', gloss: 'the flag' },
            { surface: 'الأَحْمَرَ', lemma: 'أحمر', pos: 'adj', features: 'def.acc', gloss: 'the red' },
            { surface: 'وَقَفَ', lemma: 'وقف', pos: 'verb', features: 'perf.3ms', gloss: 'to stop' },
            { surface: 'الْقِطَارُ', lemma: 'قطار', pos: 'noun', features: 'def.nom', gloss: 'the train' },
          ] },
        { id: 'qr2-62-030', ar: 'وَإِذَا هَزَّ الْبَيْرَقَ الأَخْضَرَ تَحَرَّكَ الْقِطَارُ.', en: 'and if he waves the green flag, the train moves.',
          tokens: [
            { surface: 'وَإِذَا', lemma: 'إذا', pos: 'part', features: 'conj', gloss: 'and if' },
            { surface: 'هَزَّ', lemma: 'هز', pos: 'verb', features: 'perf.3ms', gloss: 'to wave, shake' },
            { surface: 'الْبَيْرَقَ', lemma: 'بيرق', pos: 'noun', features: 'def.acc', gloss: 'the flag' },
            { surface: 'الأَخْضَرَ', lemma: 'أخضر', pos: 'adj', features: 'def.acc', gloss: 'the green' },
            { surface: 'تَحَرَّكَ', lemma: 'تحرك', pos: 'verb', features: 'perf.3ms', gloss: 'to move, set off' },
            { surface: 'الْقِطَارُ', lemma: 'قطار', pos: 'noun', features: 'def.nom', gloss: 'the train' },
          ] },
      ],
      checks: [
        { q: 'مَاذَا يَحْدُثُ إِذَا هَزَّ أَمِيْنُ الْقِطَارِ الْبَيْرَقَ الأَحْمَرَ؟', options: ['يَقِفُ الْقِطَارُ', 'يَتَحَرَّكُ الْقِطَارُ', 'يُسْرِعُ الْقِطَارُ'], answer: 0,
          qEn: 'What happens if the train guard waves the red flag?', optionsEn: ['The train stops', 'The train sets off', 'The train speeds up'] },
      ],
    },
    {
      en: 'And look at this lever in the driver’s hand. If he raises it upward, the steam surges and the locomotive moves; if he presses it down, the steam settles and the locomotive quiets. Then the driver presses another lever, this one, called the brake, and the locomotive stops at once — and all the carriages, coupled to it, move as it moves and stop as it stops.',
      sentences: [
        { id: 'qr2-62-031', ar: 'وَانْظُرْ إِلَىٰ هٰذِهِ الآلَةِ الَّتِيْ فِيْ يَدِ السَّائِقِ هٰذِهِ.',
          en: 'And look at this lever which is in the driver’s hand, this one.',
          tokens: [
            { surface: 'وَانْظُرْ', lemma: 'نظر', pos: 'verb', features: 'conj+imp.2ms', gloss: 'look!' },
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'at' },
            { surface: 'هٰذِهِ', lemma: 'هذه', pos: 'dem', gloss: 'this (f.)' },
            { surface: 'الآلَةِ', lemma: 'آلة', pos: 'noun', features: 'def.gen', gloss: 'the lever, mechanism' },
            { surface: 'الَّتِيْ', lemma: 'التي', pos: 'rel', gloss: 'which' },
            { surface: 'فِيْ', lemma: 'في', pos: 'prep', gloss: 'in' },
            { surface: 'يَدِ', lemma: 'يد', pos: 'noun', features: 'gen.constr', gloss: 'the hand of' },
            { surface: 'السَّائِقِ', lemma: 'سائق', pos: 'noun', features: 'def.gen', gloss: 'the driver' },
            { surface: 'هٰذِهِ', lemma: 'هذه', pos: 'dem', gloss: 'this (f.)' },
          ] },
        { id: 'qr2-62-032', ar: 'فَإِذَا رَفَعَهَا السَّائِقُ إِلَىٰ فَوْقُ،', en: 'If the driver raises it upward,',
          tokens: [
            { surface: 'فَإِذَا', lemma: 'إذا', pos: 'part', features: 'conj', gloss: 'so if' },
            { surface: 'رَفَعَهَا', lemma: 'رفع', pos: 'verb', features: 'perf.3ms+3fs', gloss: 'raised it' },
            { surface: 'السَّائِقُ', lemma: 'سائق', pos: 'noun', features: 'def.nom', gloss: 'the driver' },
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'to' },
            { surface: 'فَوْقُ', lemma: 'فوق', pos: 'adv', gloss: 'above, upward' },
          ] },
        { id: 'qr2-62-033', ar: 'انْدَفَعَ الْبُخَارُ وَسَارَتِ الْقَاطِرَةُ،', en: 'the steam surges and the locomotive moves,',
          tokens: [
            { surface: 'انْدَفَعَ', lemma: 'اندفع', pos: 'verb', features: 'perf.3ms', gloss: 'to surge, rush forth' },
            { surface: 'الْبُخَارُ', lemma: 'بخار', pos: 'noun', features: 'def.nom', gloss: 'the steam' },
            { surface: 'وَسَارَتِ', lemma: 'سار', pos: 'verb', features: 'conj+perf.3fs', gloss: 'to move, travel' },
            { surface: 'الْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'def.nom', gloss: 'the locomotive' },
          ] },
        { id: 'qr2-62-034', ar: 'وَإِذَا ضَغَطَ عَلَيْهَا سَكَنَ الْبُخَارُ وَهَدَأَتِ الْقَاطِرَةُ،',
          en: 'and if he presses it down, the steam settles and the locomotive quiets,',
          tokens: [
            { surface: 'وَإِذَا', lemma: 'إذا', pos: 'part', features: 'conj', gloss: 'and if' },
            { surface: 'ضَغَطَ', lemma: 'ضغط', pos: 'verb', features: 'perf.3ms', gloss: 'to press' },
            { surface: 'عَلَيْهَا', lemma: 'على', pos: 'prep', features: '3fs', gloss: 'on it' },
            { surface: 'سَكَنَ', lemma: 'سكن', pos: 'verb', features: 'perf.3ms', gloss: 'to settle, become still' },
            { surface: 'الْبُخَارُ', lemma: 'بخار', pos: 'noun', features: 'def.nom', gloss: 'the steam' },
            { surface: 'وَهَدَأَتِ', lemma: 'هدأ', pos: 'verb', features: 'conj+perf.3fs', gloss: 'to become calm, quiet' },
            { surface: 'الْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'def.nom', gloss: 'the locomotive' },
          ] },
        { id: 'qr2-62-035', ar: 'حِيْنَئِذٍ يَضْغَطُ السَّائِقُ عَلَىٰ آلَةٍ أُخْرَىٰ،', en: 'then the driver presses another lever,',
          tokens: [
            { surface: 'حِيْنَئِذٍ', lemma: 'حينئذ', pos: 'adv', gloss: 'then, at that time' },
            { surface: 'يَضْغَطُ', lemma: 'ضغط', pos: 'verb', features: 'impf.3ms', gloss: 'to press' },
            { surface: 'السَّائِقُ', lemma: 'سائق', pos: 'noun', features: 'def.nom', gloss: 'the driver' },
            { surface: 'عَلَىٰ', lemma: 'على', pos: 'prep', gloss: 'on' },
            { surface: 'آلَةٍ', lemma: 'آلة', pos: 'noun', features: 'indef.gen', gloss: 'a lever, mechanism' },
            { surface: 'أُخْرَىٰ', lemma: 'آخر', pos: 'adj', features: 'indef.gen', gloss: 'another' },
          ] },
        { id: 'qr2-62-036', ar: 'وَهِيَ هٰذِهِ وَتُسَمَّىٰ الْمِصَدَّ،', en: 'this one here, called the brake,',
          tokens: [
            { surface: 'وَهِيَ', lemma: 'هي', pos: 'part', features: 'conj', gloss: 'and it (is)' },
            { surface: 'هٰذِهِ', lemma: 'هذه', pos: 'dem', gloss: 'this (f.)' },
            { surface: 'وَتُسَمَّىٰ', lemma: 'سمى', pos: 'verb', features: 'conj+impf.pass.3fs', gloss: 'to be called, named' },
            { surface: 'الْمِصَدَّ', lemma: 'مصد', pos: 'noun', features: 'def.acc', gloss: 'the brake' },
          ] },
        { id: 'qr2-62-037', ar: 'وَتَقِفُ الْقَاطِرَةُ مِنْ سَاعَتِهَا،', en: 'and the locomotive stops at once,',
          tokens: [
            { surface: 'وَتَقِفُ', lemma: 'وقف', pos: 'verb', features: 'conj+impf.3fs', gloss: 'to stop' },
            { surface: 'الْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'def.nom', gloss: 'the locomotive' },
            { surface: 'مِنْ', lemma: 'من', pos: 'prep', gloss: 'from' },
            { surface: 'سَاعَتِهَا', lemma: 'ساعة', pos: 'noun', features: 'gen+3fs', gloss: 'its hour (idiom: at once)' },
          ] },
        { id: 'qr2-62-038', ar: 'وَالْعَرَبَاتُ كُلُّهَا مُرَكَّبَةٌ بِالْقَاطِرَةِ تَسِيْرُ بِسَيْرِهَا،',
          en: 'and all the carriages, coupled to the locomotive, move as it moves,',
          tokens: [
            { surface: 'وَالْعَرَبَاتُ', lemma: 'عربة', pos: 'noun', features: 'conj+def.nom.pl', gloss: 'and the carriages' },
            { surface: 'كُلُّهَا', lemma: 'كل', pos: 'noun', features: 'nom+3fp', gloss: 'all of them' },
            { surface: 'مُرَكَّبَةٌ', lemma: 'ركب', pos: 'adj', features: 'indef.nom', gloss: 'coupled, mounted' },
            { surface: 'بِالْقَاطِرَةِ', lemma: 'قاطرة', pos: 'noun', features: 'def.gen', gloss: 'to the locomotive' },
            { surface: 'تَسِيْرُ', lemma: 'سار', pos: 'verb', features: 'impf.3fs', gloss: 'to move, travel' },
            { surface: 'بِسَيْرِهَا', lemma: 'سير', pos: 'noun', features: 'gen+3fs', gloss: 'as it moves' },
          ] },
        { id: 'qr2-62-039', ar: 'وَتَقِفُ بِوُقُوْفِهَا.', en: 'and stop as it stops.',
          tokens: [
            { surface: 'وَتَقِفُ', lemma: 'وقف', pos: 'verb', features: 'conj+impf.3fs', gloss: 'to stop' },
            { surface: 'بِوُقُوْفِهَا', lemma: 'وقوف', pos: 'noun', features: 'gen+3fs', gloss: 'as it stops' },
          ] },
      ],
      checks: [
        { q: 'مَا اسْمُ الآلَةِ الَّتِيْ تُوْقِفُ الْقَاطِرَةَ فَوْراً؟', options: ['الْمِصَدُّ', 'الْمَوْقِدُ', 'الْمِفْتَاحُ'], answer: 0,
          qEn: 'What is the name of the lever that stops the locomotive at once?', optionsEn: ['The brake', 'The furnace', 'The key'] },
      ],
    },
    {
      en: 'This is the railway line the train moves on; were it not for it, the train would sink into the ground, because the soil cannot bear its weight.',
      sentences: [
        { id: 'qr2-62-040', ar: 'وَهٰذَا هُوَ الْخَطُّ الْحَدِيْدِيُّ الَّذِي يَسِيْرُ عَلَيْهِ الْقِطَارُ،',
          en: 'This is the railway line the train moves on,',
          tokens: [
            { surface: 'وَهٰذَا', lemma: 'هذا', pos: 'dem', features: 'conj', gloss: 'and this' },
            { surface: 'هُوَ', lemma: 'هو', pos: 'part', gloss: '(is)' },
            { surface: 'الْخَطُّ', lemma: 'خط', pos: 'noun', features: 'def.nom', gloss: 'the line' },
            { surface: 'الْحَدِيْدِيُّ', lemma: 'حديدي', pos: 'adj', features: 'def.nom', gloss: 'iron, railway' },
            { surface: 'الَّذِي', lemma: 'الذي', pos: 'rel', gloss: 'which' },
            { surface: 'يَسِيْرُ', lemma: 'سار', pos: 'verb', features: 'impf.3ms', gloss: 'to move, travel' },
            { surface: 'عَلَيْهِ', lemma: 'على', pos: 'prep', features: '3ms', gloss: 'on it' },
            { surface: 'الْقِطَارُ', lemma: 'قطار', pos: 'noun', features: 'def.nom', gloss: 'the train' },
          ] },
        { id: 'qr2-62-041', ar: 'وَلَوْلاَ هُوَ لَغَاصَ الْقِطَارُ فِي الأَرْضِ،', en: 'and were it not for it, the train would sink into the ground,',
          tokens: [
            { surface: 'وَلَوْلاَ', lemma: 'لولا', pos: 'part', features: 'conj', gloss: 'and were it not for' },
            { surface: 'هُوَ', lemma: 'هو', pos: 'part', gloss: 'it' },
            { surface: 'لَغَاصَ', lemma: 'غاص', pos: 'verb', features: 'perf.3ms', gloss: 'to sink, plunge' },
            { surface: 'الْقِطَارُ', lemma: 'قطار', pos: 'noun', features: 'def.nom', gloss: 'the train' },
            { surface: 'فِي', lemma: 'في', pos: 'prep', gloss: 'into' },
            { surface: 'الأَرْضِ', lemma: 'أرض', pos: 'noun', features: 'def.gen', gloss: 'the ground' },
          ] },
        { id: 'qr2-62-042', ar: 'لأَنَّ التُّرْبَةَ لاَ تَحْمِلُ ثِقْلَ الْقِطَارِ.', en: 'because the soil cannot bear the weight of the train.',
          tokens: [
            { surface: 'لأَنَّ', lemma: 'لأن', pos: 'part', gloss: 'because' },
            { surface: 'التُّرْبَةَ', lemma: 'تربة', pos: 'noun', features: 'def.acc', gloss: 'the soil' },
            { surface: 'لاَ', lemma: 'لا', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'تَحْمِلُ', lemma: 'حمل', pos: 'verb', features: 'impf.3fs', gloss: 'to carry, bear' },
            { surface: 'ثِقْلَ', lemma: 'ثقل', pos: 'noun', features: 'acc.constr', gloss: 'the weight of' },
            { surface: 'الْقِطَارِ', lemma: 'قطار', pos: 'noun', features: 'def.gen', gloss: 'the train' },
          ] },
      ],
      checks: [
        { q: 'لِمَاذَا يَحْتَاجُ الْقِطَارُ إِلَىٰ خَطٍّ حَدِيْدِيٍّ؟', options: ['لِأَنَّ التُّرْبَةَ لاَ تَحْمِلُ ثِقْلَهُ', 'لِأَنَّهُ يُزَيِّنُ الطَّرِيْقَ', 'لِأَنَّهُ أَرْخَصُ'], answer: 0,
          qEn: 'Why does the train need a rail line?', optionsEn: ['Because the soil cannot bear its weight', 'Because it decorates the road', 'Because it is cheaper'] },
      ],
    },
    {
      en: 'This is the locomotive that pulls the train, and this is the train that delivers passengers from land to land, carrying people’s burdens to a country they could reach only with great hardship.',
      sentences: [
        { id: 'qr2-62-043', ar: 'هٰذِهِ هِيَ الْقَاطِرَةُ الَّتِيْ تَجُرُّ الْقِطَارَ،', en: 'This is the locomotive that pulls the train,',
          tokens: [
            { surface: 'هٰذِهِ', lemma: 'هذه', pos: 'dem', gloss: 'this (f.)' },
            { surface: 'هِيَ', lemma: 'هي', pos: 'part', gloss: '(is)' },
            { surface: 'الْقَاطِرَةُ', lemma: 'قاطرة', pos: 'noun', features: 'def.nom', gloss: 'the locomotive' },
            { surface: 'الَّتِيْ', lemma: 'التي', pos: 'rel', gloss: 'which' },
            { surface: 'تَجُرُّ', lemma: 'جر', pos: 'verb', features: 'impf.3fs', gloss: 'to pull, tow' },
            { surface: 'الْقِطَارَ', lemma: 'قطار', pos: 'noun', features: 'def.acc', gloss: 'the train' },
          ] },
        { id: 'qr2-62-044', ar: 'وَهٰذَا هُوَ الْقِطَارُ الَّذِيْ يُوْصِلُ الرُّكَّابَ مِنْ دِيَارٍ إِلَىٰ دِيَارٍ،',
          en: 'and this is the train that delivers passengers from land to land,',
          tokens: [
            { surface: 'وَهٰذَا', lemma: 'هذا', pos: 'dem', features: 'conj', gloss: 'and this' },
            { surface: 'هُوَ', lemma: 'هو', pos: 'part', gloss: '(is)' },
            { surface: 'الْقِطَارُ', lemma: 'قطار', pos: 'noun', features: 'def.nom', gloss: 'the train' },
            { surface: 'الَّذِيْ', lemma: 'الذي', pos: 'rel', gloss: 'which' },
            { surface: 'يُوْصِلُ', lemma: 'أوصل', pos: 'verb', features: 'impf.3ms', gloss: 'to deliver, convey' },
            { surface: 'الرُّكَّابَ', lemma: 'ركاب', pos: 'noun', features: 'def.acc', gloss: 'the passengers' },
            { surface: 'مِنْ', lemma: 'من', pos: 'prep', gloss: 'from' },
            { surface: 'دِيَارٍ', lemma: 'دار', pos: 'noun', features: 'indef.gen.pl', gloss: 'lands, homes' },
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'to' },
            { surface: 'دِيَارٍ', lemma: 'دار', pos: 'noun', features: 'indef.gen.pl', gloss: 'lands, homes' },
          ] },
        { id: 'qr2-62-045', ar: 'وَيَحْمِلُ أَثْقَالَ النَّاسِ إِلَىٰ بَلَدٍ لَمْ يَكُوْنُوْا بَالِغِيْهِ إِلاَّ بِشِقِّ الأَنْفُسِ.',
          en: 'and carries people’s burdens to a country they could reach only with great hardship.',
          tokens: [
            { surface: 'وَيَحْمِلُ', lemma: 'حمل', pos: 'verb', features: 'conj+impf.3ms', gloss: 'to carry' },
            { surface: 'أَثْقَالَ', lemma: 'ثقل', pos: 'noun', features: 'acc.constr.pl', gloss: 'the loads of' },
            { surface: 'النَّاسِ', lemma: 'ناس', pos: 'noun', features: 'def.gen', gloss: 'the people' },
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'to' },
            { surface: 'بَلَدٍ', lemma: 'بلد', pos: 'noun', features: 'indef.gen', gloss: 'a country, land' },
            { surface: 'لَمْ', lemma: 'لم', pos: 'part', features: 'neg', gloss: 'not' },
            { surface: 'يَكُوْنُوْا', lemma: 'كان', pos: 'verb', features: 'jussive.3mp', gloss: 'to be' },
            { surface: 'بَالِغِيْهِ', lemma: 'بالغ', pos: 'noun', features: 'acc.pl.constr+3ms', gloss: 'reaching it' },
            { surface: 'إِلاَّ', lemma: 'إلا', pos: 'part', gloss: 'except, only' },
            { surface: 'بِشِقِّ', lemma: 'شق', pos: 'noun', features: 'gen.constr', gloss: 'with the hardship of' },
            { surface: 'الأَنْفُسِ', lemma: 'نفس', pos: 'noun', features: 'def.gen.pl', gloss: 'the selves (idiom: great hardship)' },
          ] },
      ],
      checks: [
        { q: 'كَيْفَ كَانَ النَّاسُ يَبْلُغُوْنَ الْبِلاَدَ الْبَعِيْدَةَ قَبْلَ الْقِطَارِ؟', options: ['بِشِقِّ الأَنْفُسِ وَجَهْدٍ كَبِيْرٍ', 'بِسُهُوْلَةٍ تَامَّةٍ', 'لَمْ يَكُوْنُوْا يُسَافِرُوْنَ أَبَداً'], answer: 0,
          qEn: 'How did people used to reach distant lands before the train?', optionsEn: ['With great hardship and effort', 'With complete ease', 'They never traveled at all'] },
      ],
    },
    {
      en: 'Look, Rashid, how Allah inspired man with wisdom and craft, and granted him the intellect by which he harnesses iron and steam — is it not fitting for you to say, when you ride the train: "Glory be to Him who has subjected this to us, for we could never have accomplished it by ourselves; and indeed, to our Lord we will surely return" (Qur\'an, Az-Zukhruf 43:13-14)?',
      sentences: [
        { id: 'qr2-62-046', ar: 'انْظُرْ يَا رَشِيْدُ!', en: 'Look, Rashid!',
          tokens: [
            { surface: 'انْظُرْ', lemma: 'نظر', pos: 'verb', features: 'imp.2ms', gloss: 'look!' },
            { surface: 'يَا', lemma: 'يا', pos: 'part', gloss: 'O (vocative)' },
            { surface: 'رَشِيْدُ', lemma: 'رشيد', pos: 'proper', gloss: 'Rashid' },
          ] },
        { id: 'qr2-62-047', ar: 'كَيْفَ أَلْهَمَ اللهُ الإِنْسَانَ الْحِكْمَةَ وَالصِّنَاعَةَ،', en: 'How Allah inspired man with wisdom and craft,',
          tokens: [
            { surface: 'كَيْفَ', lemma: 'كيف', pos: 'adv', gloss: 'how' },
            { surface: 'أَلْهَمَ', lemma: 'ألهم', pos: 'verb', features: 'perf.3ms', gloss: 'to inspire' },
            { surface: 'اللهُ', lemma: 'الله', pos: 'proper', features: 'nom', gloss: 'Allah' },
            { surface: 'الإِنْسَانَ', lemma: 'إنسان', pos: 'noun', features: 'def.acc', gloss: 'man, mankind' },
            { surface: 'الْحِكْمَةَ', lemma: 'حكمة', pos: 'noun', features: 'def.acc', gloss: 'wisdom' },
            { surface: 'وَالصِّنَاعَةَ', lemma: 'صناعة', pos: 'noun', features: 'conj+def.acc', gloss: 'and craft, industry' },
          ] },
        { id: 'qr2-62-048', ar: 'وَرَزَقَهُ الْعَقْلَ الَّذِيْ يُسَخِّرُ بِهِ الْحَدِيْدَ وَالْبُخَارَ،',
          en: 'and granted him the intellect by which he harnesses iron and steam,',
          tokens: [
            { surface: 'وَرَزَقَهُ', lemma: 'رزق', pos: 'verb', features: 'conj+perf.3ms+3ms', gloss: 'and granted him' },
            { surface: 'الْعَقْلَ', lemma: 'عقل', pos: 'noun', features: 'def.acc', gloss: 'the intellect' },
            { surface: 'الَّذِيْ', lemma: 'الذي', pos: 'rel', gloss: 'which' },
            { surface: 'يُسَخِّرُ', lemma: 'سخر', pos: 'verb', features: 'impf.3ms', gloss: 'to harness, subjugate for use' },
            { surface: 'بِهِ', lemma: 'ب', pos: 'prep', features: '3ms', gloss: 'by it' },
            { surface: 'الْحَدِيْدَ', lemma: 'حديد', pos: 'noun', features: 'def.acc', gloss: 'the iron' },
            { surface: 'وَالْبُخَارَ', lemma: 'بخار', pos: 'noun', features: 'conj+def.acc', gloss: 'and the steam' },
          ] },
        { id: 'qr2-62-049', ar: 'أَفَلاَ يَحِقُّ لَكَ أَنْ تَقُوْلَ إِذَا رَكِبْتَ الْقِطَارَ:',
          en: 'is it not fitting for you to say, when you ride the train:',
          tokens: [
            { surface: 'أَفَلاَ', lemma: 'لا', pos: 'part', features: 'neg', gloss: 'is it not' },
            { surface: 'يَحِقُّ', lemma: 'حق', pos: 'verb', features: 'impf.3ms', gloss: 'to be fitting, due' },
            { surface: 'لَكَ', lemma: 'ل', pos: 'prep', features: '2ms', gloss: 'for you' },
            { surface: 'أَنْ', lemma: 'أن', pos: 'part', gloss: 'that' },
            { surface: 'تَقُوْلَ', lemma: 'قال', pos: 'verb', features: 'subj.2ms', gloss: 'to say' },
            { surface: 'إِذَا', lemma: 'إذا', pos: 'part', gloss: 'when' },
            { surface: 'رَكِبْتَ', lemma: 'ركب', pos: 'verb', features: 'perf.2ms', gloss: 'to ride' },
            { surface: 'الْقِطَارَ', lemma: 'قطار', pos: 'noun', features: 'def.acc', gloss: 'the train' },
          ] },
        {
          id: 'qr2-62-050',
          ar: '﴿ سُبْحَانَ الَّذِيْ سَخَّرَ لَنَا هٰذَا وَمَا كُنَّا لَهُ مُقْرِنِيْنَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُوْنَ ﴾.',
          en: '"Glory be to Him who has subjected this to us, for we could never have accomplished it ourselves. And indeed, to our Lord we will surely return." (Qur’an 43:13-14, Surat az-Zukhruf) -- kept as a single 13-token unit, above the 3-9 token buildable range, so it is not offered in the Build stage; see the header comment.',
          tokens: [
            { surface: 'سُبْحَانَ', lemma: 'سبحان', pos: 'noun', features: 'acc', gloss: 'glory be to' },
            { surface: 'الَّذِيْ', lemma: 'الذي', pos: 'rel', gloss: 'who' },
            { surface: 'سَخَّرَ', lemma: 'سخر', pos: 'verb', features: 'perf.3ms', gloss: 'to subject, harness' },
            { surface: 'لَنَا', lemma: 'ل', pos: 'prep', features: '1p', gloss: 'to us' },
            { surface: 'هٰذَا', lemma: 'هذا', pos: 'dem', gloss: 'this' },
            { surface: 'وَمَا', lemma: 'ما', pos: 'part', features: 'conj+neg', gloss: 'and not' },
            { surface: 'كُنَّا', lemma: 'كان', pos: 'verb', features: 'perf.1p', gloss: 'to be' },
            { surface: 'لَهُ', lemma: 'ل', pos: 'prep', features: '3ms', gloss: 'for it' },
            { surface: 'مُقْرِنِيْنَ', lemma: 'مقرن', pos: 'noun', features: 'acc.pl', gloss: 'able (to master, subdue)' },
            { surface: 'وَإِنَّا', lemma: 'إن', pos: 'part', features: 'conj+1p', gloss: 'and indeed we' },
            { surface: 'إِلَىٰ', lemma: 'إلى', pos: 'prep', gloss: 'to' },
            { surface: 'رَبِّنَا', lemma: 'رب', pos: 'noun', features: 'gen+1p', gloss: 'our Lord' },
            { surface: 'لَمُنْقَلِبُوْنَ', lemma: 'منقلب', pos: 'noun', features: 'nom.pl', gloss: 'surely returning' },
          ],
        },
      ],
      checks: [
        { q: 'مَاذَا يَنْبَغِيْ أَنْ يَقُوْلَ الْمُسْلِمُ إِذَا رَكِبَ الْقِطَارَ؟', options: ['﴿ سُبْحَانَ الَّذِيْ سَخَّرَ لَنَا هٰذَا... ﴾', 'الْحَمْدُ للهِ رَبِّ الْعَالَمِيْنَ فَقَطْ', 'لاَ شَيْءَ خَاصّاً'], answer: 0,
          qEn: 'What should a Muslim say when riding the train?', optionsEn: ['"Glory be to Him who has subjected this to us..."', 'Just "Praise be to the Lord of the worlds"', 'Nothing in particular'] },
      ],
    },
  ],
  workshop: {
    cloze: [
      {
        type: 'cloze',
        pre: 'فَإِذَا هَزَّ الْبَيْرَقَ الأَحْمَرَ',
        post: 'الْقِطَارُ.',
        en: 'If he waves the red flag, the train stops.',
        options: ['وَقَفَ', 'يَقِفُ', 'وَقَفَتْ', 'وَقَفُوا'],
        answer: 0,
        rationales: [
          'Perfect 3rd masculine singular — matches الْقِطَارُ (masculine) in a past narrative frame.',
          'Imperfect, wrong tense for this narrated sequence.',
          'Perfect 3rd feminine singular, wrong gender.',
          'Perfect 3rd masculine plural, wrong number.',
        ],
      },
      {
        type: 'cloze',
        pre: 'فَإِذَا رَفَعَهَا السَّائِقُ إِلَىٰ فَوْقُ، انْدَفَعَ الْبُخَارُ وَ',
        post: 'الْقَاطِرَةُ.',
        en: 'the steam surges and the locomotive moves.',
        options: ['سَارَتِ', 'سَارَ', 'يَسِيْرُ', 'سِرْنَا'],
        answer: 0,
        rationales: [
          '3rd feminine singular past (الْقَاطِرَة is feminine).',
          '3rd masculine singular, wrong gender.',
          'Present tense, wrong for this narrated sequence.',
          '1st person plural, wrong person.',
        ],
      },
    ],
    shift: [
      {
        type: 'shift',
        base: 'تَجُرُّ الْقِطَارَ',
        pre: '',
        post: 'الْقِطَارَ',
        targetPerson: 'أَنْتُنَّ',
        targetEn: 'you (f. pl.)',
        options: ['تَجْرُرْنَ', 'يَجْرُرْنَ', 'تَجُرُّوْنَ', 'نَجُرُّ'],
        answer: 0,
        rationales: ['2nd feminine plural takes the suffix ـْنَ.', '3rd feminine plural, wrong person.', '2nd masculine plural, wrong gender.', '1st person plural, wrong person.'],
      },
      {
        type: 'shift',
        base: 'يَضْغَطُ عَلَىٰ آلَةٍ أُخْرَىٰ',
        pre: '',
        post: 'عَلَىٰ آلَةٍ أُخْرَىٰ',
        targetPerson: 'أَنَا',
        targetEn: 'I',
        options: ['أَضْغَطُ', 'تَضْغَطُ', 'نَضْغَطُ', 'يَضْغَطُوْنَ'],
        answer: 0,
        rationales: ['1st person singular takes the prefix أَـ.', '', '', ''],
      },
    ],
  },
};
