// القراءة الراشدة, volume two -- the book shell the Library screen reads.
//
// Mirrors qiraah-v1/index.js exactly (see that file and README.md's
// "Adding a book" section). Split out as its own book because the source
// PDF's volume two begins its own title page at printed page 117 (chapter
// 32 "شَهَادَةُ الْيَتِيمِ"), even though the printed chapter *numbering*
// carries on continuously from volume one rather than resetting to 1 the
// way Qaṣaṣ an-Nabiyyīn's volumes do (see QASAS_AGENT_BRIEF.md §1).
//
// Chapter *module* ids/filenames in this book use the printed chapter
// number (ch32/chapter-32.js, ch33/chapter-33.js, ...) rather than resetting
// to ch1, because the print numbers volume two's chapters continuously from
// volume one. The list below runs ch32 (page 117, where volume two's title
// page is) to ch60, in reading order -- order is what gates progression,
// chapter N unlocking when chapter N-1 is finished.
export const BOOK = {
  id: "qiraah-v2",
  title: { ar: "الْقِرَاءَةُ الرَّاشِدَةُ", en: "Al-Qirāʾah ar-Rāshidah" },
  volumeLabel: "Volume Two",
  author: { ar: "أَبُو الْحَسَنِ عَلِيٌّ النَّدْوِيُّ", en: "Abū al-Ḥasan ʿAlī an-Nadwī" },
  blurb: "The second volume of the graded reader, opening at printed page 117 (chapter 32) and continuing the same chapter numbering as volume one.",
  chapters: [
    {
      id: "ch32",
      number: 32,
      title: { ar: "شَهَادَةُ الْيَتِيمِ", en: "The Orphan's Witness" },
      pages: [117, 118, 119],
      blurb: "How the Prophet's ﷺ mosque in Madinah came to be built: the Hijrah, the camel left to kneel where it chose, and the plot of land belonging to two orphan boys, Sahl and Suhayl, who offered it for Allah's sake — and the Prophet ﷺ who would not take it without paying, then carried the bricks himself.",
      load: () => import("./chapter-32.js"),
    },
    {
      id: "ch33",
      number: 33,
      title: { ar: "كِسْرَةٌ مِنَ الْخُبْزِ", en: "A Piece of Bread" },
      pages: [120, 121, 122, 123],
      blurb: "A piece of bread stops the boy about to eat it and tells its own life story — sown as a grain, rained on, ripened, harvested, threshed under the oxen's feet, winnowed, ground between millstones, kneaded and flattened on the hot griddle — all of it, it says, for your comfort.",
      load: () => import("./chapter-33.js"),
    },
    {
      id: "ch34",
      number: 34,
      title: { ar: "عِيَادَةُ الْمَرِيْضِ", en: "Visiting the Sick" },
      pages: [124, 125, 126],
      blurb: "Hamid finds his friend Husayn absent from school with a fever and goes to visit him — asking permission at the door, sitting gently, hearing the doctor's examination, and leaving before the visit tires the patient. A lesson in the manners of visiting the sick as much as in vocabulary.",
      load: () => import("./chapter-34.js"),
    },
    {
      id: "ch35",
      number: 35,
      title: { ar: "الْكِيْمِيَاء", en: "Alchemy" },
      pages: [127, 128, 129, 130],
      blurb: "The children dream of the old craft that turns dust into gold, and their father promises to teach it to them. He walks them out at dawn — to a farmer plowing his field, and to workmen sweating over their craft — and shows them where the gold really comes from.",
      load: () => import("./chapter-35.js"),
    },
    {
      id: "ch36",
      number: 36,
      title: { ar: "يَوْمٌ صَائِفٌ", en: "A Summer Day" },
      pages: [131, 132],
      blurb: "A day of scorching heat, drawn from the inside out: grass screens and sprinkled water, the huts that stay cooler than the plastered palaces, the thermometer at a hundred and eighteen, the rich escaping to the hills and everyone else enduring — until the wind drops and the evening makes going out pleasant again.",
      load: () => import("./chapter-36.js"),
    },
    {
      id: "ch37",
      number: 37,
      title: { ar: "النَّظَافَةُ", en: "Cleanliness" },
      pages: [133, 134, 135],
      blurb: "Tahir, a farmer's son of modest means, is never seen in dirty clothes — his room ordered, his books unmarked, his teeth cleaned with the siwak. Set against Shahid, the rich boy whose books are a museum of scribbles, and who says keeping things tidy would waste his time.",
      load: () => import("./chapter-37.js"),
    },
    {
      id: "ch38",
      number: 38,
      title: { ar: "الْحَنِيْنُ إِلَىٰ الشَّهَادَةِ (١)", en: "Yearning for Martyrdom (1)" },
      pages: [136, 137, 138],
      blurb: "Umayr ibn Abi Waqqas, sixteen years old, hides among the army going out to Badr for fear the Prophet ﷺ will send him home for being young — and is sent home, and weeps, until the Prophet ﷺ relents. Continues in part 2.",
      load: () => import("./chapter-38.js"),
    },
    {
      id: "ch39",
      number: 39,
      title: { ar: "الْحَنِيْنُ إِلَىٰ الشَّهَادَةِ (٢)", en: "Yearning for Martyrdom (2)" },
      pages: [139, 140],
      blurb: "At Uhud the boys press to be let out with the army: Rafi' ibn Khadij stretches himself taller to look old enough, and Samurah ibn Jundub claims he can throw him — so the Prophet ﷺ has the two of them wrestle for it.",
      load: () => import("./chapter-39.js"),
    },
    {
      id: "ch40",
      number: 40,
      title: { ar: "كُنْ أَحَدَ السَّبْعَةِ (١)", en: "Be One of the Seven (1)" },
      pages: [141, 142, 143],
      blurb: "A blazing June holiday, the boys at home with their father Sulayman, and a conversation that turns from how far the sun is from the earth to the hadith of the seven whom Allah will shade on the day when there is no shade but His — beginning with the just ruler. Continues in part 2.",
      load: () => import("./chapter-40.js"),
    },
    {
      id: "ch41",
      number: 41,
      title: { ar: "كُنْ أَحَدَ السَّبْعَةِ (٢)", en: "Be One of the Seven (2)" },
      pages: [144, 145, 146],
      blurb: "Sulayman finishes teaching his sons the hadith of the seven whom Allah will shade: the youth raised in worship, the heart attached to the mosque, the two friends who love each other for Allah's sake, the man who followed Yusuf's example in chastity, the secret almsgiver, and the one who weeps remembering Allah alone. Continues chapter 40.",
      load: () => import("./chapter-41.js"),
    },
    {
      id: "ch42",
      number: 42,
      title: { ar: "الْعَيْنُ (١)", en: "The Eye (1)" },
      pages: [147, 148, 149],
      blurb: "A descriptive essay on the eye as a sign of Allah's design -- its structure, the eyelids and lashes that guard it, common ailments like ophthalmia and nearsightedness and how to avoid them, the right kind of light to read by at night, and the eye as an irreplaceable blessing. Continues in part 2 (printed chapter 43).",
      load: () => import("./chapter-42.js"),
    },
    {
      id: "ch43",
      number: 43,
      title: { ar: "الْعَيْنُ (٢)", en: "The Eye (2)" },
      pages: [150, 151],
      blurb: "Part 2 concludes: the eye as a blessing worth Paradise, the blind scholars (Qatadah, Hammad ibn Zayd, al-Ma'arri, Bashar ibn Burd, al-Shatibi, and others) who excelled despite their loss, using sight and tears in Allah's obedience, and the Prophet's ﷺ own supplication about the heart, soul, and eye.",
      load: () => import("./chapter-43.js"),
    },
    {
      id: "ch44",
      number: 44,
      title: { ar: "أَدَبُ الْمُعَاشَرَةِ", en: "The Etiquette of Companionship" },
      pages: [152, 153],
      blurb: "A short didactic poem (verse chapter, like qiraah-v1's chapter-03/05) of practical advice on good company: honor lies in trustworthiness, not wealth or lineage; don't provoke or over-criticize friends; defer to the group when among nobles; speak only what suits the occasion; and avoid vulgar jokes and excessive frivolity.",
      load: () => import("./chapter-44.js"),
    },
    {
      id: "ch45",
      number: 45,
      title: { ar: "عِيْدُ الأَضْحَىٰ", en: "The Feast of Sacrifice (ʿĪd al-Aḍḥā)" },
      pages: [154, 155, 156, 157],
      blurb: "A boy narrates his family's Eid al-Adha: his father sighting the new moon of Dhul-Hijjah and teaching him the Prophet's ﷺ hilal-supplication, the teacher's explanation of the Hajj-day sequence, the shared-share sacrificial cow his father raises himself, Eid morning's new clothes and prayer, the sacrifice, distributing and drying the meat, a neighbor's banquet, and the imam's takbir through the 13th of Dhul-Hijjah.",
      load: () => import("./chapter-45.js"),
    },
    {
      id: "ch46",
      number: 46,
      title: { ar: "تَارِيْخُ الْقَمِيْصِ", en: "The History of the Shirt" },
      pages: [158, 159, 160],
      blurb: "A direct-address essay tracing a new shirt's supply chain back from the reader's own body: the farmer sowing and tending the cotton field, children picking the cotton, the ginner, the mill, the weaver, the merchant, the father earning the money 'by the sweat of his brow,' and the tailor sewing through the night -- closing with the supplication for putting on a new garment.",
      load: () => import("./chapter-46.js"),
    },
    {
      id: "ch47",
      number: 47,
      title: { ar: "الأَسَدُ", en: "The Lion" },
      pages: [161, 162, 163],
      blurb: "A descriptive essay on the lion: its mighty build and mane, its roar, its jaws and claws and the way it stalks and pounces on prey, its courage compared to other beasts, the lioness defending her cubs, and closing measurements of the animal's body and stride.",
      load: () => import("./chapter-47.js"),
    },
    {
      id: "ch48",
      number: 48,
      title: { ar: "غُرُوْرُ الدُّنْيَا", en: "The World's Delusion" },
      pages: [164, 165],
      blurb: "A short maxim-poem by Abu al-'Atahiya (verse chapter, like chapter-44) on the world's delusive nature: true nobility belongs only to the contented ascetic, while the world -- however beloved for its beauty -- is treacherous, fickle, and untrustworthy, separating loved ones and wearying even those who cling to it; the ignorant and base prosper by it while the wise and cultured suffer through it.",
      load: () => import("./chapter-48.js"),
    },
    {
      id: "ch49",
      number: 49,
      title: { ar: "رِسَالَةٌ إِلَىٰ رَسُوْلِ اللهِ ﷺ", en: "A Message to the Messenger of Allah ﷺ" },
      pages: [166, 167, 168],
      blurb: "An essay on the early Muslims' belief that death is a bridge to the Hereafter, framed through the everyday scenario of sending a message home with a traveling relative: every Muslim who crosses that bridge meets the Messenger of Allah ﷺ, who will ask after his community, regardless of whether any human messenger ever completes the earthly journey. Illustrated by the Prophet's ﷺ promise of victory before the Muslims' advance on Syria, and a battlefield anecdote at Yarmouk in which a man prepared for martyrdom sends his greeting to the Messenger ﷺ through Abu Ubaydah.",
      load: () => import("./chapter-49.js"),
    },
    {
      id: "ch50",
      number: 50,
      title: { ar: "حَادِثَةٌ", en: "An Incident" },
      pages: [169, 170, 171, 172],
      blurb: "A first-person narrative: an elderly guest insists on bathing in the flooded river rather than the bathhouse, quickly tires and is swept into the current. A relative skilled at swimming rescues him -- careful not to let the drowning man grab him directly -- pushing him from below, then a fisherman's stick, until he reaches the shore, vomits the water he swallowed, and is ferried home on a raft of jars. Shaken, he warns every future visitor never to enter the river, yet still resents his rescuer for not simply grabbing his hand.",
      load: () => import("./chapter-50.js"),
    },
    {
      id: "ch51",
      number: 51,
      title: { ar: "فَتَى الإِسْلاَمِ", en: "The Youth of Islam" },
      pages: [173, 174, 175],
      blurb: "An essay contrasting the shallow ambitions of ordinary youths -- eating, playing, dressing up, and at best a certificate and a government salary -- with the towering ambition of the Muslim youth under the Islamic state, who aspired to jihad, conquest, or martyrdom. Illustrated by Muhammad bin Qasim ath-Thaqafi, who invaded India, defeated its armies, conquered Sindh and reached Multan, and won the love of the very people he conquered through his justice and generosity -- all before the age of seventeen.",
      load: () => import("./chapter-51.js"),
    },
    {
      id: "ch52",
      number: 52,
      title: { ar: "الرِّمَايَةُ", en: "Marksmanship" },
      pages: [176, 177, 178],
      blurb: "A boy narrates learning to shoot: an air rifle at first, missing badly and then improving with two months of practice, plus a rich man's elaborate mechanical target -- an iron soldier that snaps upright and salutes when struck. He graduates to a full rifle for real hunting, and closes by relating his teacher's account of the Prophet's ﷺ hadith commanding the sons of Isma'il to practice archery.",
      load: () => import("./chapter-52.js"),
    },
    {
      id: "ch53",
      number: 53,
      title: { ar: "الْجَمَلُ", en: "The Camel" },
      pages: [179, 180],
      blurb: "A descriptive essay (part 1) on the camel's anatomy: its size and long neck for grazing without kneeling, small head, sand-resistant padded feet, fatty hump beneath the saddle, gentle dark eyes, the chest callus ('kalkal') it rests on, and its multi-chambered stomach that lets it chew a stored cud when food runs out -- with the hump's fat serving as a slow-release energy reserve. Continues in part 2 (printed chapter 54).",
      load: () => import("./chapter-53.js"),
    },
    {
      id: "ch54",
      number: 54,
      title: { ar: "الْجَمَلُ", en: "The Camel" },
      pages: [181, 182],
      blurb: "Part 2 concludes: waterless deserts that only camel caravans can cross, their camels carrying provisions and heavy merchandise without tiring -- earning the camel its epithet 'the ship of the desert'. The camel sometimes saves lost travelers by smelling water from afar; it is gentle and patient but vengeful once truly provoked; and at full strength it refuses food unless fed by hand, extending its 'shiqshiqah' from its throat and gurgling in what people call its 'fast'.",
      load: () => import("./chapter-54.js"),
    },
    {
      id: "ch55",
      number: 55,
      title: { ar: "أَنَا هُنَا فَاعْرِفُوْنِيْ!", en: "I Am Here, So Know Me!" },
      pages: [183, 184, 185, 186],
      blurb: "Water narrates its own life story in the first person -- born in the vast sea, rising as vapor into clouds, falling as rain, boiling as kettle-steam, freezing into hail and snow and glacial ice, plunging as a waterfall, flowing as the Sindh, Tigris, Euphrates and Nile, drifting as fog, settling as dew, and finally chilling drinks as manufactured ice -- each stage closing with water's refrain: 'and I am here, so know me.'",
      load: () => import("./chapter-55.js"),
    },
    {
      id: "ch56",
      number: 56,
      title: { ar: "سَفِيْنَةٌ عَلَى الْبَرِّ", en: "A Ship on Land" },
      pages: [187, 188, 189, 190],
      blurb: "Mehmed II besieges Constantinople -- which the Arabs had failed to conquer in six earlier campaigns -- with 300,000 men, a massive artillery train, and a hundred warships. When the enemy chains off the Golden Horn, the twenty-four-year-old sultan has his fleet dragged overland on greased timbers to outflank them, and the city -- capital of Byzantium and of Christendom -- falls in 1453, remaining in Muslim hands to this day.",
      load: () => import("./chapter-56.js"),
    },
    {
      id: "ch57",
      number: 57,
      title: { ar: "الْخَلِيْفَةُ عُمَرُ بْنُ عَبْدِ الْعَزِيْزِ (١)", en: "The Caliph Umar bin Abdul Aziz (1)" },
      pages: [191, 192, 193],
      blurb: "Born in 61 AH to Umm Asim, a great-granddaughter of Umar bin al-Khattab, young Umar bin Abdul Aziz memorized the Qur'an early and grew up devoted to the scholars and the Prophet's ﷺ mosque, though given to comfort and fine perfume. Designated caliph without seeking it, he renounces his life of ease overnight: refusing the state mount for his own mule, returning the caliph's furnishings to the treasury, redressing grievances, and living so plainly that he mends his own lamp, pays back the cost of hot water heated in the public kitchen, and preaches in a patched shirt. Continues in part 2 (own ch58).",
      load: () => import("./chapter-57.js"),
    },
    {
      id: "ch58",
      number: 58,
      title: { ar: "الْخَلِيْفَةُ عُمَرُ بْنُ عَبْدِ الْعَزِيْزِ (٢)", en: "The Caliph Umar bin Abdul Aziz (2)" },
      pages: [194, 195],
      blurb: "Concludes the biography: Umar acquires nothing new -- no mount, wife, or slave-girl -- from the day he takes office to the day he dies, and is never once seen laughing. He refuses dates carried on the postal service's mounts since they belong to all Muslims equally, weeps when his daughters go without over lentils and onions, and gives away his wife's jewelry. He writes public business by candle but saves his own lamp for personal matters, leaves no poor person in the land, and never lets a day's work wait for tomorrow. He dies in 101 AH.",
      load: () => import("./chapter-58.js"),
    },
    {
      id: "ch59",
      number: 59,
      title: { ar: "فِيْ بَيْتِ أَبِيْ أَيُّوْبَ الأَنْصَارِيِّ", en: "In the House of Abu Ayyub al-Ansari" },
      pages: [196, 197],
      blurb: "A first-person hadith narration by Abu Ayyub al-Ansari, may Allah be pleased with him: when the Prophet ﷺ stayed in his house, Abu Ayyub insisted the Prophet ﷺ take the upper floor while his own family took the lower floor, out of respect. A water jar breaks and spills onto the floor below, and Abu Ayyub and his wife mop it up with a blanket for fear it might disturb the Prophet ﷺ. Whenever a supper of theirs contained garlic or onion and the Prophet ﷺ sent it back untouched, Abu Ayyub would ask why, learning the Prophet ﷺ simply disliked their smell -- so Abu Ayyub began avoiding them too, out of love for him. Cited from Ibn Hisham's Sira.",
      load: () => import("./chapter-59.js"),
    },
    {
      id: "ch60",
      number: 60,
      title: { ar: "الإِمَامُ مَالِكُ بْنُ أَنَسٍ", en: "Imam Malik bin Anas" },
      pages: [198, 199, 200, 201],
      blurb: "The life of Imam Malik, born in Madinah in the year ninety-three: his teachers, the crowds that travelled to his door for hadith and fiqh, the authority he held in issuing rulings, and the reverence with which he treated the Prophet's ﷺ city and traditions.",
      load: () => import("./chapter-60.js"),
    },
    {
      id: "ch61",
      number: 61,
      title: { ar: "الْقَاطِرَةُ (١)", en: "The Locomotive (1)" },
      pages: [202, 203, 204],
      blurb: "Rashid and his father Sa'id arrive at the station, and Sa'id begins explaining in his own words how a steam locomotive works and what a train is made of, closing with the story of Stephenson and a moral about the ignorant versus the learned.",
      load: () => import("./chapter-61.js"),
    },
    {
      id: "ch62",
      number: 62,
      title: { ar: "الْقَاطِرَةُ (٢)", en: "The Locomotive (2)" },
      pages: [205, 206, 207],
      blurb: "Sa'id's explanation continues without a break: the furnace and boiler pipes that turn the wheels, the fireman and driver's duties and signal flags, the regulator and the brake, the rail line itself, and a closing Qur'anic exclamation at what Allah has subjected to mankind.",
      load: () => import("./chapter-62.js"),
    },
    {
      id: "ch63",
      number: 63,
      title: { ar: "جِسْمُ النَّبَاتِ (١)", en: "The Body of the Plant (1)" },
      pages: [208, 209, 210, 211],
      blurb: "Umar takes his son Abbas out to the family garden to study a plant up close, watching the gardener clear and prepare the soil and answering Abbas's question about why plants need sunlight, before the gardener leaves to fetch a sapling to plant.",
      load: () => import("./chapter-63.js"),
    },
    {
      id: "ch64",
      number: 64,
      title: { ar: "جِسْمُ النَّبَاتِ (٢)", en: "The Body of the Plant (2)" },
      pages: [212, 213, 214],
      blurb: "As the gardener plants the sapling, Umar explains to Abbas in turn what the roots, stem and leaves are for, closing the lesson with a reflection on God's craftsmanship visible in even the humblest plant.",
      load: () => import("./chapter-64.js"),
    },
    {
      id: "ch65",
      number: 65,
      title: { ar: "الْبَبَّغَاءُ", en: "The Parrot" },
      pages: [215, 216],
      blurb: "A ten-verse poem by Abu Ishaq al-Sabi describing a pet parrot's plumage, voice and captivity, addressed at moments directly to its owner.",
      load: () => import("./chapter-65.js"),
    },
    {
      id: "ch66",
      number: 66,
      title: { ar: "الْحَجَّاجُ وَالْفِتْيَةُ", en: "Al-Hajjaj and the Youths" },
      pages: [217, 218, 219],
      blurb: "On night patrol in disguise, the harsh governor al-Hajjaj ibn Yusuf overhears three drunken young men boast of their fathers in verse, and correctly guesses each one's lineage before revealing himself to them the next morning.",
      load: () => import("./chapter-66.js"),
    },
    {
      id: "ch67",
      number: 67,
      title: { ar: "أَنَا تُرَابٌ", en: "I Am Dust" },
      pages: [220, 221, 222, 223],
      blurb: "Dust itself narrates everything mankind owes to it -- food, clothing, silk, pottery, paper, minerals and fuel -- before closing on its role as the resting place of prophets, martyrs and scholars, and a warning against walking the earth arrogantly.",
      load: () => import("./chapter-67.js"),
    },
    {
      id: "ch68",
      number: 68,
      title: { ar: "السُّلْطَانُ مَحْمُوْدُ بْنُ مُحَمَّدٍ الْغُجْرَاتِي", en: "Sultan Mahmud son of Muhammad al-Gujarati" },
      pages: [224, 225, 226, 227],
      blurb: "A biographical sketch of Sultan Mahmud Begada of Gujarat: his evenhanded rule, his mosques, schools and irrigation works, his patronage of scholars, and his final pilgrimage to the tomb he built beside his teacher's grave.",
      load: () => import("./chapter-68.js"),
    },
    {
      id: "ch69",
      number: 69,
      title: { ar: "الْبَاخِرَةُ (١)", en: "The Steamship (1)" },
      pages: [228, 229, 230],
      blurb: "Before the steamship itself appears, a historical set-up on the danger and hardship of travel by sail, the pilgrimage journeys Muslims braved anyway, and the great medieval travelers -- Ibn Battuta, Ibn Jubayr and Sulayman the Merchant -- who crossed the Islamic world by ship.",
      load: () => import("./chapter-69.js"),
    },
    {
      id: "ch70",
      number: 70,
      title: { ar: "الْبَاخِرَةُ (٢)", en: "The Steamship (2)" },
      pages: [231, 232, 233],
      blurb: "The paddle wheel and the first steamship, built on the same steam-turbine principle already explained for the locomotive; the Atlantic crossing cut from two months to five days, the captain and the helm, and a closing Qur'anic reflection on what Allah has subjected to mankind.",
      load: () => import("./chapter-70.js"),
    },
    {
      id: "ch71",
      number: 71,
      title: { ar: "جِسْمُ الطُّيُوْرِ", en: "The Body of Birds" },
      pages: [234, 235, 236, 237],
      blurb: "A biology lesson on how every animal's body fits its habitat and diet: the elephant's trunk, the camel's stomachs, then birds in turn -- feathers and hollow bones, beaks shaped by diet, legs suited to hopping, wading or swimming, and the talons of birds of prey.",
      load: () => import("./chapter-71.js"),
    },
    {
      id: "ch72",
      number: 72,
      title: { ar: "شِيْرُشَاه السُّوْرِيّ سُلْطَانُ الْهِنْدِ (١)", en: "Sher Shah Suri, Sultan of India (1)" },
      pages: [238, 239, 240],
      blurb: "Sher Shah Suri's modest origins and education in Jaunpur, and his exacting daily routine as sultan -- prayer, army review, audiences with governors and envoys -- and a severity toward rebels and highway-robbers that spared no one, kin included.",
      load: () => import("./chapter-72.js"),
    },
    {
      id: "ch73",
      number: 73,
      title: { ar: "شِيْرُشَاه السُّوْرِيّ سُلْطَانُ الْهِنْدِ (٢)", en: "Sher Shah Suri, Sultan of India (2)" },
      pages: [241, 242],
      blurb: "His great road from Bengal to the Indus, lined with caravanserais, mosques and fruit trees, and a second garrisoned road to Agra; the book closes on his regret at reaching the throne only in old age and his death on 12 Rabi' al-Awwal 952 AH.",
      load: () => import("./chapter-73.js"),
    },
  ],
};
