// Shared by the string checks and the browser's visual-order checks.
export const bidiCases = [
  {
    name: 'Reported Advanced Sarf sentence',
    text: "That closing exclusion is the boundary line with النحو: إعراب and بناء belong to النحو, and everything else about a word's shape belongs here.",
    order: ['النحو', ':', 'إعراب', 'and', 'بناء'],
  },
  { name: 'Colon in mixed prose', text: 'كِتَابُ الوَلَدِ is مركب ناقص: كتاب is مضاف.', order: ['مركب ناقص', ':', 'كتاب'] },
  { name: 'Comma in mixed prose', text: 'Choose فاعل, مفعول به, or مبتدأ.', order: ['فاعل', ',', 'مفعول به'] },
  { name: 'Full stop in mixed prose', text: 'First identify الفاعل. المفعول به comes next.', order: ['الفاعل', '.', 'المفعول به'] },
  { name: 'Semicolon in mixed prose', text: 'Compare النحو; الصرف is different.', order: ['النحو', ';', 'الصرف'] },
  { name: 'Spaced dash in mixed prose', text: 'Compare الفاعل — المفعول به in context.', order: ['الفاعل', '—', 'المفعول به'] },
  { name: 'Spaced slash in mixed prose', text: 'Choose الفاعل / المفعول به here.', order: ['الفاعل', '/', 'المفعول به'] },
  { name: 'Spaced plus in mixed prose', text: 'Combine مبتدأ + خبر here.', order: ['مبتدأ', '+', 'خبر'] },
  { name: 'Arabic comma in English list', text: 'Choose الفاعل، المفعول به here.', order: ['الفاعل', '،', 'المفعول به'] },
  { name: 'Numbered terms', text: 'Choose (1) فاعل, (2) مفعول به.', order: ['(1)', 'فاعل', '(2)', 'مفعول به'] },
  { name: 'Arabic parenthetical', text: 'The meaning (أي: تثبت) is clear.', order: ['أي', ':', 'تثبت'], rtl: true },
  { name: 'Independent parenthetical', text: 'In فِعْلٌ وَفَاعِلٌ (هِيَ), identify the subject.', order: ['فِعْلٌ وَفَاعِلٌ', '(هِيَ)'] },
  { name: 'Arabic-only definition', text: 'الكلمة: قول مفرد', order: ['الكلمة', ':', 'قول مفرد'], rtl: true },
  { name: 'Arabic-only sentences', text: 'جاء زيد. خرج عمرو.', order: ['جاء', 'زيد', 'خرج', 'عمرو'], rtl: true },
  { name: 'Repeated term does not reorder phrase', text: 'In كَانَ رَسُوْلُ اللّٰهِ يَخْطُبُ قَائِمًا, what is قَائِمًا?', order: ['كَانَ', 'رَسُوْلُ', 'اللّٰهِ', 'يَخْطُبُ', 'قَائِمًا'], rtl: true },
  { name: 'Unspaced compound', text: 'Identify مُضَافٌ–مُضَافٌ إِلَيْهِ here.', order: ['مُضَافٌ', '–', 'مُضَافٌ إِلَيْهِ'], rtl: true },
  { name: 'Unspaced alternatives', text: 'Compare مذ/منذ here.', order: ['مذ', '/', 'منذ'], rtl: true },
  { name: 'Quranic quotation with ellipsis', text: 'Read ﴿وَلَوْ أَنَّمَا فِي الْأَرْضِ...مَا نَفِدَتْ كَلِمَاتُ اللَّهِ﴾ again.', order: ['وَلَوْ', 'الْأَرْضِ', '...', 'مَا نَفِدَتْ'], rtl: true },
  { name: 'Quoted Arabic sentence', text: 'Read “قال زيد: جاء عمرو” again.', order: ['قال', 'زيد', ':', 'جاء', 'عمرو'], rtl: true },
  { name: 'English punctuation across markup', html: 'With <strong>النحو</strong>: إعراب and بناء belong here.', order: ['النحو', ':', 'إعراب'] },
  { name: 'Existing term markup', html: 'With <bdi>النحو</bdi>: <bdi>إعراب</bdi> and بناء belong here.', order: ['النحو', ':', 'إعراب'] },
  { name: 'Explicit Arabic passage', html: 'Read <span dir="rtl">قال زيد: <strong>جاء عمرو</strong></span> again.', order: ['قال', 'زيد', ':', 'جاء', 'عمرو'], rtl: true },
  { name: 'Arabic-only rich text', html: 'قال <strong>زيد</strong>: جاء عمرو.', order: ['قال', 'زيد', ':', 'جاء', 'عمرو'], rtl: true },
  { name: 'Non-breaking spaces', text: 'In مضاف\u00a0إليه: كتاب belongs here.', order: ['مضاف\u00a0إليه', ':', 'كتاب'] },
  { name: 'Search highlight in Arabic title', html: 'الكلمة: <mark class="search-hit">قول</mark> مفرد', order: ['الكلمة', ':', 'قول', 'مفرد'], rtl: true },
  { name: 'Arabic text before an isolated term', html: 'قال <bdi>زيد</bdi>', order: ['قال', 'زيد'], rtl: true },
  { name: 'Multiple isolated terms in an Arabic field', html: '<bdi>النحو</bdi>: <bdi>إعراب</bdi>', order: ['النحو', ':', 'إعراب'], rtl: true },
  { name: 'Nested markup in Arabic scope', html: 'Read <bdi dir="rtl">قال <strong>زيد: <em>جاء</em> عمرو</strong></bdi> again.', order: ['قال', 'زيد', ':', 'جاء', 'عمرو'], rtl: true },
  { name: 'Single Arabic phrase wraps without reversal', text: 'Read هذا كتاب الطالب الجديد في المدرسة الكبيرة again.', order: ['هذا', 'كتاب', 'الطالب', 'الجديد', 'في', 'المدرسة', 'الكبيرة'], rtl: true },
];
