// Advanced Sarf — Module 11
// التقسيم الثالث للاسم: المذكَّر والمؤنَّث (week 27)

export default {
  id: 'as-11',
  title: 'المذكَّر والمؤنَّث',
  heading: 'الاسم',
  blurb: 'الاسم divided by gender: the two kinds of مؤنث, and the marks — التاء and الألف — that show it.',
  lessons: [
    {
      id: 'l1',
      title: 'قسمة الاسم إلى مذكَّر ومؤنَّث',
      subtitle: 'حقيقيّ against مجازيّ, and لفظيّ against معنويّ — two cuts through the same material',
      concepts: [
        {
          heading: 'المذكَّر والمؤنَّث، والحقيقيّ والمجازيّ',
          lines: [
            { html: `<bdi>ينقسم الاسم إلى مذكر ومؤنث: فالمذكر كرجل، وكتاب، وكرسيّ.</bdi>`, list: false },
            { html: `<bdi>والمؤنث نوعان.</bdi>`, list: false },
            { html: `<bdi>حقيقيّ، وهو ما دلَّ على ذات حِرٍ، كفاطمة وهند.</bdi>`, list: true, bullet: true },
            { html: `<bdi>ومجازيّ، وهو ما ليس كذلك، كأُذُن، ونار، وشمس.</bdi>`, list: true, bullet: true },
          ],
          clarification: `The line runs through nature, not through language: a حقيقيّ feminine has a female body, a مجازيّ one is treated as feminine by the Arabs without being female at all. That is why the second kind needs evidence, and the first does not.`,
          exercise: {
            prompt: `<bdi>نار</bdi> and <bdi>شمس</bdi> are:`,
            kind: 'mcq',
            options: ['مؤنث حقيقيّ', 'مذكَّر', 'مؤنث لفظيّ', 'مؤنث مجازيّ'],
            correct: 3,
          },
        },
        {
          heading: 'ما يُستدلّ به على المؤنث المجازيّ',
          lines: [
            { html: `<bdi>ويُستدلّ على تأنيثه</bdi> by any of five things.`, list: false },
            { table: {
              title: 'الأدلّة الخمسة',
              headers: ['الدليل', 'المثال'],
              rows: [
                ['بضمير المؤنث', 'الشمس رأيتُها'],
                ['أو إشارته', 'هذه الشمس'],
                ['أو لحوق تاء التأنيث في الفعل', 'طلعتْ'],
                ['أو ظهور التاء في تصغيره', 'أُذَيْنَة'],
                ['أو حذفها من اسم عدده', 'ثلاث آبار'],
              ],
            } },
            { html: `The last is the surest of them for a word whose gender is otherwise silent: the عدد drops its تاء before a feminine مَعْدُود, so <bdi>ثلاث آبار</bdi> settles that <bdi>بئر</bdi> is مؤنث.`, list: false },
          ],
          exercise: {
            prompt: `<bdi>ثلاث آبار</bdi> proves <bdi>بئر</bdi> is feminine by:`,
            kind: 'mcq',
            options: ['الإشارة', 'حذف التاء من اسم العدد', 'ظهور التاء في التصغير', 'لحوق تاء التأنيث بالفعل'],
            correct: 1,
          },
        },
        {
          heading: 'اللفظيّ والمعنويّ',
          lines: [
            { html: `<bdi>وينقسم المؤنث إلى لفظيّ: وهو ما وُضِع لِمُذَكَّر وفيه علامة من علامات التأنيث، كطلحة وزكريَّاء.</bdi>`, list: false },
            { html: `<bdi>وإلى مَعْنَوي، وهو ما كان عَلَمًا لمؤنث وليس فيه علامة، كمَرْيم وهند وزينب.</bdi>`, list: false },
            { html: `<bdi>وإلى لفظيّ ومعنويّ، وهو ما كان عَلَمًا لمؤنث وفيه علامة كفاطمةَ، وسَلْمَى، وعاشُوراء، مُسمَّى به مؤنث.</bdi>`, list: false },
            { table: {
              title: 'الأقسام الثلاثة',
              headers: ['القسم', 'الضابط', 'المثال'],
              rows: [
                ['لفظيّ', 'وُضِع لمذكَّر وفيه علامة تأنيث', 'طلحة، زكريَّاء'],
                ['معنويّ', 'عَلَم لمؤنث ولا علامة فيه', 'مَرْيم، هند، زينب'],
                ['لفظيّ ومعنويّ', 'عَلَم لمؤنث وفيه علامة', 'فاطمة، سَلْمَى، عاشُوراء'],
              ],
            } },
          ],
          clarification: `The two divisions are asking different questions. حقيقيّ / مجازيّ asks whether the thing is female. لفظيّ / معنويّ asks whether the word carries a mark and whether it names a female. That is why طلحة is لفظيّ and not مؤنث at all in sense, while هند is معنويّ with nothing on the word to show it.`,
          exercise: {
            prompt: `<bdi>طلحة</bdi> is مؤنث لفظيّ because:`,
            kind: 'mcq',
            options: ['it was laid down for a مذكَّر yet carries a mark of التأنيث', 'it is a عَلَم for a female with no mark', 'it is a عَلَم for a female with a mark', 'it is مؤنث مجازيّ'],
            correct: 0,
          },
        },
        {
          heading: 'أصالة التذكير',
          lines: [
            { html: `<bdi>ولكون المذكر هو الأصل (في الأسماء)، لم يُحْتَجْ فيه إلى علامة، بخلاف المؤنث فله علامتان.</bdi>`, list: false },
            { html: `The two are <bdi>التاء</bdi> and <bdi>الألف</bdi>, and the rest of this division is taken up with them.`, list: false },
          ],
          exercise: {
            prompt: `Why does the مذكَّر carry no علامة?`,
            kind: 'mcq',
            options: ['Because it cannot take a diminutive form', 'Because it is the أصل among nouns', 'Because it is used more frequently', 'Because its علامة has been dropped for lightening'],
            correct: 1,
          },
        },
      ],
      quiz: [
        { q: 'المؤنث الحقيقيّ is:', options: ['That which points to a female body', 'That which carries a mark of التأنيث', 'That which is a proper name', 'That which has no mark'], correct: 0 },
        { q: 'أُذُن، نار، شمس are:', options: ['مؤنث مجازيّ', 'مؤنث حقيقيّ', 'مذكَّر', 'مؤنث لفظيّ'], correct: 0 },
        { q: 'أُذَيْنَة is evidence of التأنيث by:', options: ['ضمير المؤنث', 'ظهور التاء في التصغير', 'حذف التاء من اسم العدد', 'الإشارة'], correct: 1 },
        { q: 'مَرْيم، هند، زينب are:', options: ['مؤنث معنويّ', 'مؤنث لفظيّ', 'مؤنث لفظيّ ومعنويّ', 'مذكَّر'], correct: 0 },
        { q: 'فاطمة، سَلْمَى، عاشُوراء are:', options: ['مؤنث مجازيّ', 'مؤنث لفظيّ ومعنويّ', 'مؤنث لفظيّ', 'مؤنث معنويّ'], correct: 1 },
        { q: 'The two علامات of التأنيث are:', options: ['التاء والألف', 'التاء والياء', 'الألف والنون', 'التاء والواو'], correct: 0 },
      ],
      bank: [
        { title: 'أمثلة المذكَّر', kind: 'mcq', prompt: 'Which set is offered for the مذكَّر?', options: ['فاطمة، هند، زينب', 'أُذُن، نار، شمس', 'طلحة، زكريَّاء', 'رجل، كتاب، كرسيّ'], correct: 3 },
        { title: 'حِر', kind: 'mcq', prompt: 'ذات حِرٍ in the definition of the حقيقيّ refers to:', options: ['heat', 'freedom', 'a proper name', 'the private part of a woman'], correct: 3 },
        { title: 'حدّ المجازيّ', kind: 'mcq', prompt: 'The مؤنث المجازيّ is defined as:', options: ['That which is a proper name for a female', 'That which was coined for a male', 'That which does not point to a female body', 'That which carries a mark of التأنيث'], correct: 2 },
        { title: 'الشمس رأيتها', kind: 'mcq', prompt: 'الشمس رأيتُها proves تأنيث by:', options: ['إشارة المؤنث', 'تاء التأنيث في الفعل', 'حذف التاء من العدد', 'ضمير المؤنث'], correct: 3 },
        { title: 'هذه الشمس', kind: 'mcq', prompt: 'هذه الشمس proves تأنيث by:', options: ['اسم العدد', 'الإشارة', 'الضمير', 'التصغير'], correct: 1 },
        { title: 'طلعت', kind: 'mcq', prompt: 'طلعتْ proves تأنيث by:', options: ['ظهور التاء في التصغير', 'الإشارة', 'حذف التاء من العدد', 'لحوق تاء التأنيث في الفعل'], correct: 3 },
        { title: 'عدد الأدلة', kind: 'mcq', prompt: 'How many signs of the مؤنث المجازيّ are listed?', options: ['ثلاثة', 'ستة', 'سبعة', 'خمسة'], correct: 3 },
        { title: 'زكريّاء', kind: 'mcq', prompt: 'زكريَّاء is مؤنث:', options: ['لفظيّ ومعنويّ', 'حقيقيّ', 'لفظيّ', 'معنويّ'], correct: 2 },
        { title: 'عاشوراء', kind: 'mcq', prompt: 'عاشُوراء is placed under:', options: ['المعنويّ', 'المجازيّ', 'اللفظيّ والمعنويّ', 'اللفظيّ'], correct: 2 },
        { title: 'سَلْمَى', kind: 'mcq', prompt: 'The علامة in سَلْمَى is:', options: ['الألف', 'التاء', 'النون', 'الياء'], correct: 0 },
        { title: 'هند بلا علامة', kind: 'mcq', prompt: 'هند is معنويّ rather than لفظيّ ومعنويّ because:', options: ['ليس عَلَمًا', 'وُضِع لمذكَّر', 'هو مجازيّ', 'ليس فيه علامة'], correct: 3 },
        { title: 'المذكَّر أصل', kind: 'mcq', prompt: 'What follows from the مذكَّر being الأصل?', options: ['أنه لا يُصغَّر', 'أنه لا يُجمع', 'أن علامته الألف', 'لم يُحتَجْ فيه إلى علامة'], correct: 3 },
        { title: 'علامتان للمؤنث', kind: 'mcq', prompt: 'How many علامات does the مؤنث have?', options: ['خمس', 'اثنتان', 'واحدة', 'ثلاث'], correct: 1 },
        { title: 'ثلاث آبار', kind: 'mcq', prompt: 'In ثلاث آبار, what has been done to the عدد?', options: ['كُسِرت لامه', 'صُغِّر', 'حُذِفت تاؤه', 'زِيدت تاؤه'], correct: 2 },
        { title: 'موضع الاستدلال', kind: 'mcq', prompt: 'Against which kind of مؤنث are these signs needed?', options: ['المجازيّ', 'الحقيقيّ', 'اللفظيّ', 'اللفظيّ والمعنويّ'], correct: 0 },
        { title: 'كرسيّ', kind: 'mcq', prompt: 'كرسيّ is placed among:', options: ['المذكَّر', 'المؤنث المجازيّ', 'المؤنث اللفظيّ', 'المؤنث المعنويّ'], correct: 0 },
        { title: 'وضع اللفظيّ', kind: 'mcq', prompt: 'The مؤنث اللفظيّ was laid down for:', options: ['مؤنث حقيقيّ', 'مؤنث مجازيّ', 'جنس لا لواحد', 'مُذَكَّر'], correct: 3 },
        { title: 'مسمَّى به مؤنث', kind: 'mcq', prompt: 'The قيد مُسمَّى به مؤنث attaches to:', options: ['المجازيّ', 'اللفظيّ والمعنويّ', 'اللفظيّ وحده', 'المعنويّ وحده'], correct: 1 },
        { title: 'أُذُن', kind: 'mcq', prompt: 'أُذُن shows its تأنيث in تصغير as:', options: ['أُذَيْنَى', 'أُذَيْنَة', 'أُذَيْن', 'أُذَيَّة'], correct: 1 },
        { title: 'موضع العلامتين', kind: 'mcq', prompt: 'The two علامات belong to:', options: ['both equally', 'الأعلام only', 'المؤنث', 'المذكَّر'], correct: 2 },
        { title: 'فاطمة وهند', kind: 'mcq', prompt: 'فاطمة and هند are given together as examples of:', options: ['المؤنث اللفظيّ', 'المذكَّر', 'المؤنث الحقيقيّ', 'المؤنث المجازيّ'], correct: 2 },
        { title: 'قسمتان لا واحدة', kind: 'mcq', prompt: 'حقيقيّ / مجازيّ and لفظيّ / معنويّ are:', options: ['kinds of علامة', 'two different cuts through the noun', 'two names for one division', 'stages of the same division'], correct: 1 },
        { title: 'دلالة الحقيقيّ', kind: 'mcq', prompt: 'What does the حقيقيّ point to that the مجازيّ does not?', options: ['ذات حِرٍ', 'علامة تأنيث', 'العَلَمية', 'الجَمْعية'], correct: 0 },
        { title: 'زينب', kind: 'mcq', prompt: 'زينب carries:', options: ['an ألف مقصورة', 'an ألف ممدودة', 'no علامة, though it names a female', 'a تاء'], correct: 2 },
      ],
    },
    {
      id: 'l2',
      title: 'العلامة الأولى: التاء',
      subtitle: 'Where the تاء goes, where it refuses to go, and the five words that keep it out',
      concepts: [
        {
          heading: 'التاء في الفعل وفي الاسم',
          lines: [
            { html: `<bdi>الأولى: التاء، وتكون ساكنة في الفعل، نحو قامتْ هند، ومتحركة فيه، نحو هى تَقوم.</bdi>`, list: false },
            { html: `<bdi>وفي الاسم، نحو صائمة وظريفة</bdi> — <bdi>ظريفة</bdi> is elegant.`, list: false },
            { html: `<bdi>وأصل وضع التاء في الاسم: للفَرْق بين المذكر والمؤنث.</bdi>`, list: false },
          ],
          exercise: {
            prompt: `In <bdi>هى تَقوم</bdi>, the تاء is:`,
            kind: 'mcq',
            options: ['زائدة للمبالغة', 'متحركة في الفعل', 'ساكنة في الفعل', 'في الاسم'],
            correct: 1,
          },
        },
        {
          heading: 'موضعها من الأوصاف والجوامد',
          lines: [
            { html: `<bdi>وفي الأوصاف المشتقة المشتركة بينهما، فلا تدخل في الوصف المختص بالنساء، كحائِضٍ، وحائِلٍ، وفارك، ومُرْضِع وعانِس.</bdi>`, list: false },
            { html: `<bdi>حائِل</bdi> is a woman who is not pregnant; <bdi>فارك</bdi> a woman who hates her husband; <bdi>عانِس</bdi> a middle-aged unmarried woman.`, list: false },
            { html: `<bdi>أما دخولها على الجامد المشترَكِ معناه بينهما، فسماعيّ، كرجل ورَجُلة، وإنسانة، وَفتَى وفتاة.</bdi>`, list: false },
          ],
          clarification: `The rule follows from why the تاء was put there in the first place. Its work is to mark off feminine from masculine, so where a وصف belongs to women alone there is nothing to mark off, and the تاء stays away. On a جامد there is no such reasoning to run, which is why entry there is سماعيّ.`,
          exercise: {
            prompt: `Why does <bdi>حائِض</bdi> take no تاء?`,
            kind: 'mcq',
            options: ['Because it is جامد', 'Because it is on the وزن فاعِل', 'Because its تاء has been dropped for lightening', 'Because it is a وصف used only of women, so there is no need to mark the difference'],
            correct: 3,
          },
        },
        {
          heading: 'الخمسة المستثناة: الأول والثاني',
          lines: [
            { html: `<bdi>ويُستثنى من دخولها في الوصف المشترك خمسةُ ألفاظ، فلا تدخل فيها.</bdi>`, list: false },
            { html: `<bdi>أحدها: فَعُول بمعنى فاعل، كرجل صَبُور، وامرأة صَبُور، ومنه ﴿وَمَا كَانَتْ أُمُّكِ بَغِيًّا﴾ [مريم: ٢٨]، أصله بَغُويًا.</bdi>`, list: false },
            { html: `<bdi>ثانيها: فَعِيل بمعنى مَفعُول إن تَبِعَ موصوفه، كرجل جَريح، وامرأة جَريح، فإن كان بمعنى فاعِل، أوْ لَمْ يَتْبَع موصوفه، لَحِقَتْه، كامرأة رحيمة، ورأيت قَتِيلة.</bdi>`, list: false },
          ],
          clarification: `The second exception has two conditions, and both must hold. فَعِيل keeps the تاء off only where it carries a مفعول sense and follows its موصوف. Turn either one and the تاء returns: رحيمة is فَعِيل بمعنى فاعِل, and قَتِيلة stands without a موصوف before it.`,
          exercise: {
            prompt: `Why does <bdi>رأيت قَتِيلة</bdi> take the تاء although it is <bdi>فَعِيل بمعنى مفعول</bdi>?`,
            kind: 'mcq',
            options: ['Because it carries the sense of فاعِل', 'Because it is جامد', 'Because it is used only of women', 'Because it does not follow its موصوف'],
            correct: 3,
          },
        },
        {
          heading: 'الخمسة المستثناة: الثالث إلى الخامس',
          lines: [
            { table: {
              title: 'بقية الخمسة',
              headers: ['الوزن', 'المثال', 'الشاذّ'],
              rows: [
                ['مِفْعال', 'مِهْذار', 'وشذَّ مِيقَانة'],
                ['مِفْعِيل', 'مِعْطير', 'وشذَّ مِسْكِينة — وقد سُمِع حذفها على القياس'],
                ['مِفْعَل', 'مِغْشَم', '—'],
              ],
            } },
            { html: `<bdi>مِهْذار</bdi> is a babbling fool; <bdi>مِيقَانة</bdi> a woman who believes everything she is told; <bdi>مِعْطير</bdi> one who frequently perfumes themselves; <bdi>مِغْشَم</bdi> one who performs matters randomly and without consideration.`, list: false },
          ],
          exercise: {
            prompt: `<bdi>مِسْكِينة</bdi> is noted as شاذّ under which وزن?`,
            kind: 'mcq',
            options: ['مِفْعِيل', 'مِفْعال', 'مِفْعَل', 'فَعُول'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'The تاء in قامتْ هند is:', options: ['للمبالغة', 'ساكنة في الفعل', 'متحركة في الفعل', 'في الاسم'], correct: 1 },
        { q: 'The original purpose of the تاء in the اسم is:', options: ['تعويض المحذوف', 'تمييز الواحد من جنسه', 'الفَرْق بين المذكر والمؤنث', 'المبالغة'], correct: 2 },
        { q: 'رجل ورَجُلة، وإنسانة are described as:', options: ['قياسيّ في الوصف المشترك', 'شاذّ في مِفْعال', 'من الخمسة المستثناة', 'سماعيّ — دخول التاء على الجامد'], correct: 3 },
        { q: 'رجل صَبُور and امرأة صَبُور illustrate:', options: ['فَعُول بمعنى فاعل', 'فَعِيل بمعنى مفعول', 'مِفْعال', 'مِفْعِيل'], correct: 0 },
        { q: 'The أصل of بَغِيًّا is:', options: ['بَغُويًا', 'بَاغِيَة', 'بَغِيَّة', 'بَغْوًا'], correct: 0 },
        { q: 'مِغْشَم is on the وزن:', options: ['مِفْعِيل', 'فَعِيل', 'مِفْعَل', 'مِفْعال'], correct: 2 },
      ],
      bank: [
        { title: 'صائمة وظريفة', kind: 'mcq', prompt: 'صائمة and ظريفة show the تاء:', options: ['ساكنة في الفعل', 'متحركة في الفعل', 'عوضًا عن محذوف', 'في الاسم'], correct: 3 },
        { title: 'ظريفة', kind: 'mcq', prompt: 'ظريفة means:', options: ['elegant', 'fasting', 'patient', 'merciful'], correct: 0 },
        { title: 'الوصف المختصّ', kind: 'mcq', prompt: 'Which list is of أوصاف مختصّة بالنساء?', options: ['رَجُلة، إنسانة، فتاة', 'صائمة، ظريفة، رحيمة', 'حائض، حائل، فارك، مُرْضِع، عانِس', 'صَبُور، جَريح، مِهْذار، مِعْطير، مِغْشَم'], correct: 2 },
        { title: 'حائل', kind: 'mcq', prompt: 'حائِل means:', options: ['a middle-aged unmarried woman', 'a nursing woman', 'a woman who is not pregnant', 'a woman who hates her husband'], correct: 2 },
        { title: 'فارك', kind: 'mcq', prompt: 'فارك means:', options: ['a woman who hates her husband', 'a woman who is not pregnant', 'a nursing woman', 'a menstruating woman'], correct: 0 },
        { title: 'عانِس', kind: 'mcq', prompt: 'عانِس means:', options: ['a woman who believes everything', 'a middle-aged unmarried woman', 'a nursing woman', 'a woman who hates her husband'], correct: 1 },
        { title: 'فتى وفتاة', kind: 'mcq', prompt: 'فتَى وفتاة is grouped with:', options: ['الخمسة المستثناة', 'الوصف المختصّ بالنساء', 'الجامد المشترَك معناه — سماعيّ', 'الوصف المشترك — قياسيّ'], correct: 2 },
        { title: 'عدد المستثنى', kind: 'mcq', prompt: 'How many ألفاظ are excepted from taking the تاء in the وصف المشترك?', options: ['ستة', 'خمسة', 'ثلاثة', 'أربعة'], correct: 1 },
        { title: 'شاهد بغيًّا', kind: 'mcq', prompt: '﴿وَمَا كَانَتْ أُمُّكِ بَغِيًّا﴾ is from:', options: ['يوسف: ٨', 'مريم: ٢٨', 'مريم: ٢٧', 'النور: ٣٣'], correct: 1 },
        { title: 'قيد فَعُول', kind: 'mcq', prompt: 'فَعُول keeps the تاء off only when it is:', options: ['تابعًا لموصوفه', 'غير تابع لموصوفه', 'بمعنى فاعل', 'بمعنى مفعول'], correct: 2 },
        { title: 'قيدا فَعِيل', kind: 'mcq', prompt: 'فَعِيل keeps the تاء off on two conditions:', options: ['Being بمعنى مفعول and not following its موصوف', 'Being جامد and following its موصوف', 'Being بمعنى مفعول and following its موصوف', 'Being بمعنى فاعل and following its موصوف'], correct: 2 },
        { title: 'رحيمة', kind: 'mcq', prompt: 'امرأة رحيمة takes the تاء because فَعِيل here is:', options: ['بمعنى مفعول', 'غير تابع لموصوفه', 'مختصّ بالنساء', 'بمعنى فاعِل'], correct: 3 },
        { title: 'رجل جريح', kind: 'mcq', prompt: 'امرأة جَريح keeps no تاء because فَعِيل is:', options: ['جامدًا', 'بمعنى مفعول وقد تَبِعَ موصوفه', 'بمعنى فاعل', 'على وزن مِفْعال'], correct: 1 },
        { title: 'مِهْذار', kind: 'mcq', prompt: 'مِهْذار means:', options: ['a babbling fool', 'one who perfumes themselves often', 'one who acts without consideration', 'one who believes everything'], correct: 0 },
        { title: 'مِيقَانة', kind: 'mcq', prompt: 'مِيقَانة means:', options: ['a woman who is unmarried', 'a woman who believes everything she is told', 'a woman who talks too much', 'a woman who perfumes herself'], correct: 1 },
        { title: 'مِعْطير', kind: 'mcq', prompt: 'مِعْطير means:', options: ['one who frequently perfumes themselves', 'one who talks a great deal', 'one who acts randomly', 'one who is easily deceived'], correct: 0 },
        { title: 'مِغْشَم', kind: 'mcq', prompt: 'مِغْشَم means:', options: ['one who perfumes themselves', 'a babbling fool', 'a patient person', 'one who performs matters randomly and without consideration'], correct: 3 },
        { title: 'حذف تاء مسكينة', kind: 'mcq', prompt: 'What is said about مِسْكِينة besides its being شاذّ?', options: ['وقد سُمِع حذفها على القياس', 'ولا يجوز حذفها', 'وهي لغة ضعيفة', 'وقد سُمِع فيها التشديد'], correct: 0 },
        { title: 'الثالث من الخمسة', kind: 'mcq', prompt: 'The third of the five is:', options: ['فَعِيل', 'مِفْعال', 'مِفْعِيل', 'مِفْعَل'], correct: 1 },
        { title: 'الخامس من الخمسة', kind: 'mcq', prompt: 'The fifth of the five is:', options: ['فَعُول', 'مِفْعَل', 'مِفْعال', 'مِفْعِيل'], correct: 1 },
        { title: 'موضع القياس', kind: 'mcq', prompt: 'The تاء enters قياسًا in:', options: ['الجوامد المشتركة', 'الأوصاف المختصة بالنساء', 'الخمسة المستثناة', 'الأوصاف المشتقة المشتركة بين المذكر والمؤنث'], correct: 3 },
        { title: 'رَجُلة', kind: 'mcq', prompt: 'رَجُلة is:', options: ['a قياسيّ entry on a وصف', 'one of the five excepted', 'a شاذّ under مِفْعال', 'a سماعيّ entry of the تاء on a جامد'], correct: 3 },
        { title: 'تاء الفعل', kind: 'mcq', prompt: 'The تاء in the فعل comes in how many states?', options: ['ثلاث', 'اثنتين — ساكنة ومتحركة', 'واحدة — ساكنة', 'واحدة — متحركة'], correct: 1 },
        { title: 'صبور للرجل والمرأة', kind: 'mcq', prompt: 'That both رجل and امرأة are صَبُور shows:', options: ['فَعُول always takes the تاء', 'صَبُور is جامد', 'صَبُور is مختصّ بالنساء', 'فَعُول بمعنى فاعل does not take the تاء'], correct: 3 },
      ],
    },
    {
      id: 'l3',
      title: 'زيادة التاء والألف المقصورة',
      subtitle: 'The purposes a تاء may be added for, and the eight أوزان of the shortened ألف',
      concepts: [
        {
          heading: 'أغراض زيادة التاء',
          lines: [
            { html: `<bdi>وقد تُزاد التاء</bdi> for purposes other than التأنيث.`, list: false },
            { table: {
              title: 'الأغراض',
              headers: ['الغرض', 'المثال'],
              rows: [
                ['لتمييز الواحد من جنسه', 'لَبِن ولَبِنَة، وتَمر وتَمْرة، ونَمل ونَمْلة'],
                ['ولعكسه', 'كَمْء وكَمْأة'],
                ['وللمبالغة', 'راوية'],
                ['ولزيادتها', 'عَلَّامَة'],
                ['ولتعويض فاء الكلمة', 'عِدة'],
                ['أو عينها', 'إقامة'],
                ['أو لامها', 'سَنَة'],
                ['أو مَدّة', 'تَزْكِية'],
              ],
            } },
            { html: `<bdi>اللَّبِن</bdi> is bricks; <bdi>الكَمْء</bdi> is truffle.`, list: false },
          ],
          clarification: `The first two purposes are opposites. In لَبِن / لَبِنَة the تاء picks one out of a mass, so the bare word is the جنس; in كَمْء / كَمْأة it goes the other way, the bare word being the single item. And التعويض subdivides fourfold according to which letter of the root has gone missing — فاء in عِدة, عين in إقامة, لام in سَنَة, or a مَدّة in تَزْكِية.`,
          exercise: {
            prompt: `In <bdi>عِدة</bdi>, the تاء compensates for:`,
            kind: 'mcq',
            options: ['عين الكلمة', 'لام الكلمة', 'مَدّة', 'فاء الكلمة'],
            correct: 3,
          },
        },
        {
          heading: 'العلامة الثانية: الألف وقسماها',
          lines: [
            { html: `<bdi>العلامة الثانية: الألف. وهي قسمان.</bdi>`, list: false },
            { html: `<bdi>مفردة، وهي المقصورة، كجُبْلَى وبُشْرى.</bdi>`, list: true, bullet: true },
            { html: `<bdi>وغير مفردة (الممدودة)، وهى التى قبلها ألف، فتُقْلَب هي همزة، كحمْراء وعَذْراء.</bdi>`, list: true, bullet: true },
          ],
          clarification: `The ممدودة is not a different letter but the same ألف preceded by another ألف. Two ألفs cannot stand together, so the second turns into a همزة — which is why حمراء ends in a همزة you can hear and جُبْلَى does not.`,
          exercise: {
            prompt: `Why does the ألف of the ممدودة appear as a همزة?`,
            kind: 'mcq',
            options: ['Because it is the لام of the word', 'Because an ألف comes before it, so it is turned into a همزة', 'Because it is زائدة', 'Because it compensates for something dropped'],
            correct: 1,
          },
        },
        {
          heading: 'أوزان المقصورة: الأول إلى الرابع',
          lines: [
            { html: `<bdi>وللمقصورة أوزان، منها</bdi> — eight are listed.`, list: false },
            { table: {
              title: 'الأربعة الأولى',
              headers: ['الوزن', 'الضبط', 'الأمثلة'],
              rows: [
                ['فُعَلَى', 'بضم ففتح', 'أُرَبَى: للدَّاهية، وأُدَمَى: لموضع، وكذا شُعَبَى لموضع'],
                ['فُعْلَى', 'بضم فسكون', 'بُهْمَى لنَبْتٍ، وحُبْلَى صفة، وبُشْرَى مصدرًا'],
                ['فَعَلَى', 'بفتحات', 'بَرَدى اسم لنهر، وحَيَدَى للحمار السريع في مشيه، وبَشَكَى للناقة السريعة'],
                ['فَعْلَى', 'بفتح فسكون', 'مَرْضَى جمعًا، ونَجْوَى مصدرًا، وسَبْعَى صفةً'],
              ],
            } },
            { html: `<bdi>أُرَبَى</bdi> is calamity.`, list: false },
          ],
          exercise: {
            prompt: `<bdi>بُهْمَى</bdi>, <bdi>حُبْلَى</bdi> and <bdi>بُشْرَى</bdi> stand under which وزن?`,
            kind: 'mcq',
            options: ['فَعَلَى بفتحات', 'فَعْلَى بفتح فسكون', 'فُعْلَى بضم فسكون', 'فُعَلَى بضم ففتح'],
            correct: 2,
          },
        },
        {
          heading: 'أوزان المقصورة: الخامس إلى الثامن',
          lines: [
            { table: {
              title: 'الأربعة الأخيرة',
              headers: ['الوزن', 'الضبط', 'الأمثلة'],
              rows: [
                ['فُعَالى', 'بالضم والتخفيف', 'حُبَارَى لطائر، وسُكَارَى جمعًا، وعُلَادَى صفة للشديد من الإبل'],
                ['فُعَّلى', 'بضم ففتح العين المشددة', 'سُمَّهَى: للباطل'],
                ['فِعَلَّى', 'بكسر ففتح، فلام مشددة', 'سِبَطْرَى: لمِشية فيها تبخْتُر'],
                ['فِعْلَى', 'بكسر فسكون', 'حِجْلَى جمع حَجَلَة، وظِرْبَى جمع ظِرْبان'],
              ],
            } },
            { html: `<bdi>حِجْلَى</bdi> is the plural of <bdi>حَجَلَة</bdi> بفتحات, a bird; <bdi>ظِرْبَى</bdi> is the plural of <bdi>ظِرْبان</bdi> بفتح فكسر, <bdi>اسم لدُوَيْبَة مُنتنة الرائحة</bdi>. <bdi>سِبَطْرَى</bdi> is a gait done with pride.`, list: false },
            { html: `<bdi>ولم يوجد في اللغة جمع على هذا الوزن إلا هذان اللفظان وذِكرى مصدرًا.</bdi>`, list: false },
          ],
          exercise: {
            prompt: `What is said about <bdi>فِعْلَى</bdi> as a plural pattern?`,
            kind: 'mcq',
            options: ['That it never comes as a plural pattern at all', 'That no plural is found on it except حِجْلَى and ظِرْبَى', 'That it is the commonest of the plural patterns', 'That it is confined to مصادر'],
            correct: 1,
          },
        },
      ],
      quiz: [
        { q: 'لَبِن ولَبِنَة illustrates a تاء added for:', options: ['التعويض', 'مجرد الزيادة', 'تمييز الواحد من جنسه', 'المبالغة'], correct: 2 },
        { q: 'كَمْء وكَمْأة illustrates:', options: ['التعويض عن اللام', 'عكس تمييز الواحد من جنسه', 'المبالغة', 'التعويض عن الفاء'], correct: 1 },
        { q: 'راوية shows a تاء for:', options: ['المبالغة', 'الزيادة', 'التعويض', 'التمييز'], correct: 0 },
        { q: 'The ألف الممدودة is the one that:', options: ['تُعوَّض عن اللام', 'قبلها ألف، فتُقْلَب همزة', 'تقع في آخر الفعل', 'تُزاد للمبالغة'], correct: 1 },
        { q: 'حُبَارَى، سُكَارَى، عُلَادَى are on:', options: ['فِعَلَّى', 'فِعْلَى', 'فُعَالى', 'فُعَّلى'], correct: 2 },
        { q: 'سُمَّهَى means:', options: ['مِشية فيها تبختر', 'طائر', 'الباطل', 'الداهية'], correct: 2 },
      ],
      bank: [
        { title: 'اللَّبِن', kind: 'mcq', prompt: 'اللَّبِن means:', options: ['bricks', 'milk', 'dates', 'ants'], correct: 0 },
        { title: 'الكَمْء', kind: 'mcq', prompt: 'الكَمْء means:', options: ['brick', 'ant', 'date', 'truffle'], correct: 3 },
        { title: 'عَلَّامَة', kind: 'mcq', prompt: 'عَلَّامَة is listed under a تاء added:', options: ['للتمييز', 'لزيادتها', 'للمبالغة', 'للتعويض'], correct: 1 },
        { title: 'إقامة', kind: 'mcq', prompt: 'In إقامة, the تاء compensates for:', options: ['فاء الكلمة', 'لام الكلمة', 'مَدّة', 'عين الكلمة'], correct: 3 },
        { title: 'سَنَة', kind: 'mcq', prompt: 'In سَنَة, the تاء compensates for:', options: ['عين الكلمة', 'مَدّة', 'لام الكلمة', 'فاء الكلمة'], correct: 2 },
        { title: 'تَزْكِية', kind: 'mcq', prompt: 'In تَزْكِية, the تاء compensates for:', options: ['لام الكلمة', 'مَدّة', 'فاء الكلمة', 'عين الكلمة'], correct: 1 },
        { title: 'نَمل ونَمْلة', kind: 'mcq', prompt: 'نَمل ونَمْلة belongs with:', options: ['عكسه', 'المبالغة', 'التعويض', 'تمييز الواحد من جنسه'], correct: 3 },
        { title: 'قسما الألف', kind: 'mcq', prompt: 'The two kinds of ألف are:', options: ['الأصلية والزائدة', 'المفردة والمثناة', 'المقصورة والممدودة', 'الساكنة والمتحركة'], correct: 2 },
        { title: 'جُبْلَى وبُشْرَى', kind: 'mcq', prompt: 'جُبْلَى and بُشْرى illustrate:', options: ['الألف الممدودة', 'تاء التعويض', 'تاء المبالغة', 'الألف المقصورة'], correct: 3 },
        { title: 'حمراء وعذراء', kind: 'mcq', prompt: 'حمْراء and عَذْراء illustrate:', options: ['تاء المبالغة', 'وزن فُعَالى', 'الألف الممدودة', 'الألف المقصورة'], correct: 2 },
        { title: 'أُرَبَى', kind: 'mcq', prompt: 'أُرَبَى means:', options: ['a plant', 'a swift she-camel', 'calamity', 'a place'], correct: 2 },
        { title: 'أُدَمَى وشُعَبَى', kind: 'mcq', prompt: 'أُدَمَى and شُعَبَى are:', options: ['names of places', 'names of plants', 'names of birds', 'مصادر'], correct: 0 },
        { title: 'بُهْمَى', kind: 'mcq', prompt: 'بُهْمَى is:', options: ['a bird', 'a مصدر', 'a plant', 'a place'], correct: 2 },
        { title: 'بُشْرَى', kind: 'mcq', prompt: 'Under فُعْلَى, بُشْرَى is classed as:', options: ['صفة', 'جمعًا', 'اسم موضع', 'مصدرًا'], correct: 3 },
        { title: 'حُبْلَى', kind: 'mcq', prompt: 'Under فُعْلَى, حُبْلَى is classed as:', options: ['مصدرًا', 'جمعًا', 'اسم نبت', 'صفة'], correct: 3 },
        { title: 'بَرَدَى', kind: 'mcq', prompt: 'بَرَدى is:', options: ['a swift she-camel', 'a calamity', 'the name of a river', 'a swift donkey'], correct: 2 },
        { title: 'حَيَدَى', kind: 'mcq', prompt: 'حَيَدَى is:', options: ['a donkey swift in its gait', 'a swift she-camel', 'a river', 'a place'], correct: 0 },
        { title: 'بَشَكَى', kind: 'mcq', prompt: 'بَشَكَى is:', options: ['a plant', 'a swift she-camel', 'a swift donkey', 'a bird'], correct: 1 },
        { title: 'مَرْضَى ونَجْوَى وسَبْعَى', kind: 'mcq', prompt: 'Under فَعْلَى, the three are classed respectively as:', options: ['جمعًا، مصدرًا، صفةً', 'صفةً، جمعًا، مصدرًا', 'مصدرًا، صفةً، جمعًا', 'كلها مصادر'], correct: 0 },
        { title: 'عُلَادَى', kind: 'mcq', prompt: 'عُلَادَى is a صفة for:', options: ['الشديد من الإبل', 'الطائر', 'السكران', 'الموضع'], correct: 0 },
        { title: 'سِبَطْرَى', kind: 'mcq', prompt: 'سِبَطْرَى is:', options: ['a foul-smelling creature', 'a gait done with pride', 'a bird', 'a falsehood'], correct: 1 },
        { title: 'ضبط فِعَلَّى', kind: 'mcq', prompt: 'فِعَلَّى is vowelled:', options: ['بكسر ففتح، فلام مشددة', 'بضم ففتح العين المشددة', 'بالضم والتخفيف', 'بكسر فسكون'], correct: 0 },
        { title: 'حِجْلَى', kind: 'mcq', prompt: 'حِجْلَى is the plural of:', options: ['حَجَلَة', 'حِجْل', 'حَاجِل', 'حَجْلاء'], correct: 0 },
        { title: 'ذِكرى', kind: 'mcq', prompt: 'Besides حِجْلَى and ظِرْبَى, what else comes on فِعْلَى?', options: ['نَجْوَى مصدرًا', 'سُمَّهَى', 'ذِكرى مصدرًا', 'بُشْرَى مصدرًا'], correct: 2 },
      ],
    },
    {
      id: 'l4',
      title: 'أوزان الألف الممدودة',
      subtitle: 'Ten patterns, from فَعْلاء to مَفْعولاء',
      concepts: [
        {
          heading: 'الأول إلى الثالث',
          lines: [
            { html: `<bdi>وللممدودة أوزان. منها</bdi> — ten are listed.`, list: false },
            { table: {
              title: 'الثلاثة الأولى',
              headers: ['الوزن', 'الضبط', 'الأمثلة'],
              rows: [
                ['فَعْلاء', 'بفتح فسكون', 'صحراء اسمًا، ورَغْباء مصدرًا، وحمراء صفة لمؤنث أَفْعَل'],
                ['أَفْعِلاء', 'بفتح وسكون، ومثلَّث العين، مخفَّف اللام', 'أَربِعاء لليوم المعروف'],
                ['فُعْلُلاء', 'بضمتين بينهما ساكن', 'قُرْفُصاء لهيئة مخصوصة في القُعود'],
              ],
            } },
          ],
          exercise: {
            prompt: `Under <bdi>فَعْلاء</bdi>, <bdi>رَغْباء</bdi> is classed as:`,
            kind: 'mcq',
            options: ['اسمًا', 'صفةً', 'جمعًا', 'مصدرًا'],
            correct: 3,
          },
        },
        {
          heading: 'الرابع إلى السادس',
          lines: [
            { table: {
              title: 'الثلاثة التالية',
              headers: ['الوزن', 'الضبط', 'الأمثلة'],
              rows: [
                ['فاعُولاء', '—', 'تاسوعاء وعاشوراء: التاسع والعاشر من المحرَّم'],
                ['فاعِلاء', 'بكسر العين', 'قاصِعاء ونافِقاء: لِبابَيْ حُجْر اليَرْبُوْع'],
                ['فِعْلِياء', 'بكسرتين بينهما سكون، مخفَّف الياء', 'كِبْرِياء'],
              ],
            } },
            { html: `<bdi>كِبْرِياء</bdi> is greatness. <bdi>قاصِعاء</bdi> and <bdi>نافِقاء</bdi> are the two mouths of the jerboa's burrow.`, list: false },
          ],
          exercise: {
            prompt: `<bdi>تاسوعاء</bdi> and <bdi>عاشوراء</bdi> are on the وزن:`,
            kind: 'mcq',
            options: ['فاعُولاء', 'فاعِلاء', 'فِعْلِياء', 'فُعْلُلاء'],
            correct: 0,
          },
        },
        {
          heading: 'السابع والثامن',
          lines: [
            { html: `<bdi>وَفُعَلاء لفتح العين، وتثليث الفاء</bdi>, so it runs through three vowellings of the فاء.`, list: false },
            { table: {
              title: 'تثليث الفاء في فُعَلاء',
              headers: ['الضبط', 'المثال', 'المعنى'],
              rows: [
                ['بفتحات', 'جَنَفاء', 'لموضع'],
                ['بكسر ففتح', 'سِيَراء', 'لثوبِ خزِّ مخطَّط'],
                ['بضم ففتح', 'نُفَساء', '—'],
              ],
            } },
            { html: `<bdi>وفُنْعُلاء: بضمتين بينهما سكون، كخُنْفُساء: للحيوان المعروف.</bdi>`, list: false },
          ],
          clarification: `The seventh entry is really three: the عين is fixed on a fatḥa while the فاء takes fatḥa, kasra and ḍamma in turn, giving جَنَفاء، سِيَراء، نُفَساء. That is what <bdi>تثليث الفاء</bdi> means.`,
          exercise: {
            prompt: `<bdi>سِيَراء</bdi> is:`,
            kind: 'mcq',
            options: ['a striped garment, لثوبِ خزِّ مخطَّط', 'a place', 'a well-known animal', 'a kind of date'],
            correct: 0,
          },
        },
        {
          heading: 'التاسع والعاشر',
          lines: [
            { table: {
              title: 'الأخيران',
              headers: ['الوزن', 'الضبط', 'المثال'],
              rows: [
                ['فَعِيلاء', 'بفتح فكسر', 'قَرِيثاء بالثاء المثلثة: لنوع من التمر'],
                ['مَفْعولاء', '—', 'مَشْيوخاء: جمع شيخ'],
              ],
            } },
            { html: `<bdi>مَشْيوخاء</bdi> is the only one of the ten given as a plural.`, list: false },
          ],
          exercise: {
            prompt: `<bdi>مَشْيوخاء</bdi> is:`,
            kind: 'mcq',
            options: ['اسم موضع', 'جمع شيخ', 'مصدر', 'صفة'],
            correct: 1,
          },
        },
      ],
      quiz: [
        { q: 'صحراء is classed under فَعْلاء as:', options: ['اسمًا', 'مصدرًا', 'صفةً', 'جمعًا'], correct: 0 },
        { q: 'حمراء is classed under فَعْلاء as:', options: ['مصدرًا', 'جمعًا', 'صفة لمؤنث أَفْعَل', 'اسمًا'], correct: 2 },
        { q: 'أَربِعاء is on the وزن:', options: ['أَفْعِلاء', 'فاعِلاء', 'فِعْلِياء', 'فَعِيلاء'], correct: 0 },
        { q: 'قُرْفُصاء denotes:', options: ['يومًا من الأسبوع', 'نوعًا من التمر', 'حيوانًا معروفًا', 'هيئة مخصوصة في القُعود'], correct: 3 },
        { q: 'قاصِعاء and نافِقاء are:', options: ['بابا حُجْر اليربوع', 'اسمان لموضعين', 'نوعان من التمر', 'صفتان للناقة'], correct: 0 },
        { q: 'خُنْفُساء is on the وزن:', options: ['فَعِيلاء', 'فُنْعُلاء', 'فُعْلُلاء', 'فاعُولاء'], correct: 1 },
      ],
      bank: [
        { title: 'عدد أوزان الممدودة', kind: 'mcq', prompt: 'How many أوزان of the ممدودة are listed?', options: ['ثمانية', 'اثنا عشر', 'ستة', 'عشرة'], correct: 3 },
        { title: 'ضبط فَعْلاء', kind: 'mcq', prompt: 'فَعْلاء is vowelled:', options: ['بكسر فسكون', 'بضمتين', 'بفتح فسكون', 'بفتحتين'], correct: 2 },
        { title: 'رَغْباء', kind: 'mcq', prompt: 'رَغْباء sits beside صحراء and حمراء as the:', options: ['مصدر of the three', 'اسم of the three', 'صفة of the three', 'جمع of the three'], correct: 0 },
        { title: 'ضبط أَفْعِلاء', kind: 'mcq', prompt: 'أَفْعِلاء is described as بفتح وسكون, and the عين as:', options: ['مفتوحة لا غير', 'مكسورة لا غير', 'مضمومة لا غير', 'مثلَّثة'], correct: 3 },
        { title: 'لام أَفْعِلاء', kind: 'mcq', prompt: 'The لام of أَفْعِلاء is:', options: ['مقلوبة همزة', 'مخفَّفة', 'مشدَّدة', 'محذوفة'], correct: 1 },
        { title: 'يوم الأربعاء', kind: 'mcq', prompt: 'أَربِعاء is the name of:', options: ['نبت', 'هيئة في القعود', 'اليوم المعروف', 'موضع'], correct: 2 },
        { title: 'ضبط فُعْلُلاء', kind: 'mcq', prompt: 'فُعْلُلاء is vowelled:', options: ['بضم فكسر', 'بضمتين بينهما ساكن', 'بكسرتين بينهما ساكن', 'بفتحتين بينهما ساكن'], correct: 1 },
        { title: 'تاسوعاء', kind: 'mcq', prompt: 'تاسوعاء is:', options: ['الأول من المحرَّم', 'يوم من الأسبوع', 'التاسع من المحرَّم', 'العاشر من المحرَّم'], correct: 2 },
        { title: 'عاشوراء', kind: 'mcq', prompt: 'عاشوراء is:', options: ['الحادي عشر من المحرَّم', 'يوم من الأسبوع', 'العاشر من المحرَّم', 'التاسع من المحرَّم'], correct: 2 },
        { title: 'عين فاعِلاء', kind: 'mcq', prompt: 'The عين of فاعِلاء is:', options: ['ساكنة', 'مكسورة', 'مفتوحة', 'مضمومة'], correct: 1 },
        { title: 'اليَرْبُوع', kind: 'mcq', prompt: 'قاصِعاء and نافِقاء belong to the burrow of:', options: ['الحَجَلَة', 'الظِّرْبان', 'اليَرْبُوع', 'الخُنْفُساء'], correct: 2 },
        { title: 'كِبْرِياء', kind: 'mcq', prompt: 'كِبْرِياء means:', options: ['greatness', 'falsehood', 'calamity', 'pride of gait'], correct: 0 },
        { title: 'ياء فِعْلِياء', kind: 'mcq', prompt: 'The ياء of فِعْلِياء is:', options: ['مقلوبة', 'مخفَّفة', 'مشدَّدة', 'محذوفة'], correct: 1 },
        { title: 'جَنَفاء', kind: 'mcq', prompt: 'جَنَفاء, بفتحات, is:', options: ['a woman after childbirth', 'a kind of date', 'a place', 'a garment'], correct: 2 },
        { title: 'نُفَساء', kind: 'mcq', prompt: 'نُفَساء carries which vowelling of the فاء?', options: ['بضم ففتح', 'بفتحات', 'بكسر ففتح', 'بسكون'], correct: 0 },
        { title: 'تثليث الفاء', kind: 'mcq', prompt: 'تثليث الفاء in the seventh وزن means the فاء takes:', options: ['الكسر والضم فقط', 'السكون وحده', 'الفتح والكسر والضم', 'الفتح والسكون فقط'], correct: 2 },
        { title: 'عين فَعَلاء', kind: 'mcq', prompt: 'Through all three vowellings of the فاء, the عين of that وزن stays:', options: ['مضمومة', 'ساكنة', 'مفتوحة', 'مكسورة'], correct: 2 },
        { title: 'خُنْفُساء', kind: 'mcq', prompt: 'خُنْفُساء denotes:', options: ['موضعًا', 'ثوبًا مخطَّطًا', 'هيئة في القعود', 'الحيوان المعروف'], correct: 3 },
        { title: 'ضبط فَعِيلاء', kind: 'mcq', prompt: 'فَعِيلاء is vowelled:', options: ['بفتح فسكون', 'بكسر ففتح', 'بضم ففتح', 'بفتح فكسر'], correct: 3 },
        { title: 'قَرِيثاء', kind: 'mcq', prompt: 'قَرِيثاء, بالثاء المثلثة, denotes:', options: ['نوعًا من التمر', 'نوعًا من الطير', 'موضعًا', 'ثوبًا'], correct: 0 },
        { title: 'حرف قَرِيثاء', kind: 'mcq', prompt: 'Which letter is singled out in قَرِيثاء?', options: ['القاف', 'الراء', 'الياء', 'الثاء المثلثة'], correct: 3 },
        { title: 'مَفْعولاء', kind: 'mcq', prompt: 'The tenth وزن is:', options: ['فَعِيلاء', 'فُنْعُلاء', 'فِعْلِياء', 'مَفْعولاء'], correct: 3 },
        { title: 'مفرد مَشْيوخاء', kind: 'mcq', prompt: 'مَشْيوخاء is the plural of:', options: ['شَيْخَة', 'شيخ', 'مَشْيَخَة', 'شائخ'], correct: 1 },
        { title: 'صحراء وحمراء', kind: 'mcq', prompt: 'صحراء and حمراء differ in that the first is اسم and the second:', options: ['مصدر', 'جمع', 'اسم موضع', 'صفة لمؤنث أَفْعَل'], correct: 3 },
      ],
    },
  ],
};
