// Advanced Sarf — Module 12
// التقسيم الرابع للاسم: المنقوص والمقصور والممدود والصحيح (week 28)

export default {
  id: 'as-12',
  title: 'المنقوص والمقصور والممدود والصحيح',
  heading: 'الاسم',
  blurb: 'الاسم divided by what stands at its end: المنقوص, المقصور, الممدود, and الصحيح.',
  lessons: [
    {
      id: 'l1',
      title: 'الأقسام الأربعة',
      subtitle: 'المنقوص، المقصور، الممدود، الصحيح — and the work each قيد does',
      concepts: [
        {
          heading: 'المنقوص',
          lines: [
            { html: `<bdi>ينقسم الاسم إلى منقوص، ومقصور، وممدود، وصحيح.</bdi>`, list: false },
            { html: `<bdi>فالمنقوص: هو الاسمُ المُعْرَبُ الذى آخره ياءٌ لازمةٌ مَكْسُورٌ ما قبلها، كالداعِى والمُنادِي.</bdi>`, list: false },
            { html: `Every قيد in that definition throws something out.`, list: false },
            { table: {
              title: 'قيود المنقوص',
              headers: ['القيد', 'يَخْرُج به', 'المثال'],
              rows: [
                ['بالاسم', 'الفعل', 'كرَضِيَ'],
                ['وبالمعرب', 'المبنيّ', 'كالذى'],
                ['وبالذى آخره ياءٌ', 'المقصور', '—'],
                ['وبلازمةٍ', 'الأسماء الخمسة في حالة الجرّ', '—'],
                ['وبمكسورٍ ما قبلها', 'ما سكن ما قبل يائه', 'نحو ظَبْيٌ ورَمْيٌ — فإنه مُلْحَقٌ بالصحيح'],
              ],
            } },
            { html: `<bdi>ظَبْيٌ</bdi> and <bdi>رَمْيٌ</bdi> are <bdi>مُلْحَقٌ بالصحيح، لسكون ما قبل يائه</bdi>.`, list: false },
          ],
          clarification: `The قيد <bdi>لازمة</bdi> is what separates a true منقوص from أبوك، أخوك and their fellows: those end in a ياء only in the جرّ, and take a واو or an ألف elsewhere, so their ياء is not fixed to the word.`,
          exercise: {
            prompt: `Why is <bdi>ظَبْيٌ</bdi> not a منقوص?`,
            kind: 'mcq',
            options: ['Because its ياء is not لازمة', 'Because it is مبنيّ', 'Because it ends in an ألف', 'Because the letter before its ياء is ساكن, so it is مُلْحَق بالصحيح'],
            correct: 3,
          },
        },
        {
          heading: 'المقصور',
          lines: [
            { html: `<bdi>والمقصور: هو الاسم المُعْرَبُ الذى آخره ألفٌ لازمةٌ، كالهُدَى والمصطفى.</bdi>`, list: false },
            { table: {
              title: 'قيود المقصور',
              headers: ['القيد', 'يَخْرُج به', 'المثال'],
              rows: [
                ['بالاسم', 'الفعل والحرف', 'كدَعا وإلى'],
                ['وبالمعرَب', 'المبنيّ', 'كأنا وهذا'],
                ['وبما آخره ألف', 'المنقوص', '—'],
                ['وبلازمةٍ', 'الأسماء الخمسة في حالة النصب، والمثنى في حالة الرفع', '—'],
              ],
            } },
          ],
          clarification: `The same قيد <bdi>لازمة</bdi> does different work in each definition, because a different set of words takes that ending temporarily. For the منقوص it was the أسماء الخمسة in the جرّ; for the مقصور it is those same five in the نصب, together with the مثنى in the رفع.`,
          exercise: {
            prompt: `Which does the قيد <bdi>لازمة</bdi> exclude from the مقصور?`,
            kind: 'mcq',
            options: ['الفعل والحرف', 'المبنيّ', 'الأسماء الخمسة في النصب، والمثنى في الرفع', 'الأسماء الخمسة في الجرّ'],
            correct: 2,
          },
        },
        {
          heading: 'الممدود والصحيح',
          lines: [
            { html: `<bdi>والممدود: هو الاسم المعرب الذى آخِرُهُ همزةٌ تَلِى ألفًا زائدةً، كصحراء وحمراء.</bdi>`, list: false },
            { html: `<bdi>والصحيح: ما عَدَا ذلك، كرجل وكتاب</bdi> — <bdi>آخره صحيح أو شبيهٌ بصحيح، لامه حرف علّة وقبله سكون، نحو: دَلْوٌ</bdi>.`, list: false },
          ],
          clarification: `The صحيح is the residue: whatever is left once the other three are taken out. It covers two things at once — a word whose last letter is a sound consonant, like رجل and كتاب, and a word whose لام is a حرف علّة but is preceded by a سكون, like دَلْو, which is why ظَبْي and رَمْي were attached to it above.`,
          exercise: {
            prompt: `<bdi>دَلْوٌ</bdi> is counted صحيح because:`,
            kind: 'mcq',
            options: ['Its لام is a sound letter', 'It ends in a همزة following an added ألف', 'Its ألف is not لازمة', 'Its لام is a حرف علّة preceded by سكون, so it resembles الصحيح'],
            correct: 3,
          },
        },
        {
          heading: 'القياسيّ والسماعيّ',
          lines: [
            { html: `<bdi>وكل من المقصور والممدود: قياسيّ، وهو مَوْضِعُ نَظَرِ الصرفيّ، وسماعيّ، وهو موضع نظر اللُّغَوِيّ، الذى يَسْرُدُ ألفاظَ العرب، ويضع معانيها بإزائها.</bdi>`, list: false },
            { html: `<bdi>يَسْرُدُ</bdi> is to detail out, one by one; <bdi>بإزائها</bdi> is by itself, set against them.`, list: false },
          ],
          exercise: {
            prompt: `The سماعيّ مقصور and ممدود belong to the study of:`,
            kind: 'mcq',
            options: ['اللُّغَوِيّ', 'الصرفيّ', 'النحويّ', 'الأصوليّ'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'المنقوص is the معرب noun ending in:', options: ['ياء لازمة مكسور ما قبلها', 'ألف لازمة', 'همزة تلي ألفًا زائدة', 'حرف صحيح'], correct: 0 },
        { q: 'الداعِى and المُنادِي illustrate:', options: ['المقصور', 'الممدود', 'الصحيح', 'المنقوص'], correct: 3 },
        { q: 'The قيد بالمعرب in المنقوص excludes:', options: ['الفعل كرَضِيَ', 'المقصور', 'الأسماء الخمسة', 'المبنيّ كالذى'], correct: 3 },
        { q: 'الهُدَى and المصطفى illustrate:', options: ['الصحيح', 'المقصور', 'المنقوص', 'الممدود'], correct: 1 },
        { q: 'The قيد بالاسم in المقصور excludes:', options: ['الفعل والحرف، كدَعا وإلى', 'المبنيّ كأنا وهذا', 'المثنى في الرفع', 'المنقوص'], correct: 0 },
        { q: 'The ممدود ends in a همزة that:', options: ['تقع بعد سكون', 'تكون أصلية', 'تَلِي ألفًا زائدة', 'تَلِي ياءً لازمة'], correct: 2 },
      ],
      bank: [
        { title: 'الأقسام الأربعة', kind: 'mcq', prompt: 'The fourth division sorts the noun into:', options: ['جامد ومشتقّ', 'مجرَّد ومزيد', 'منقوص، مقصور، ممدود، صحيح', 'مذكَّر ومؤنَّث'], correct: 2 },
        { title: 'رَضِيَ', kind: 'mcq', prompt: 'رَضِيَ is excluded from المنقوص by the قيد:', options: ['بمكسور ما قبلها', 'بالاسم', 'بالمعرب', 'بلازمة'], correct: 1 },
        { title: 'الذى', kind: 'mcq', prompt: 'الذى is excluded from المنقوص by the قيد:', options: ['بلازمة', 'بمكسور ما قبلها', 'بالمعرب', 'بالاسم'], correct: 2 },
        { title: 'الأسماء الخمسة جرًّا', kind: 'mcq', prompt: 'The أسماء الخمسة in the جرّ are excluded from المنقوص by:', options: ['قيد الاسمية', 'قيد كسر ما قبل الياء', 'قيد اللزوم', 'قيد الإعراب'], correct: 2 },
        { title: 'رَمْيٌ', kind: 'mcq', prompt: 'رَمْيٌ is:', options: ['مُلْحَق بالصحيح', 'منقوص', 'مقصور', 'ممدود'], correct: 0 },
        { title: 'علّة إلحاق ظَبْي', kind: 'mcq', prompt: 'ظَبْيٌ is attached to الصحيح because of:', options: ['كون يائه غير لازمة', 'كونه مبنيًّا', 'سكون ما قبل يائه', 'كسر ما قبل يائه'], correct: 2 },
        { title: 'دَعا وإلى', kind: 'mcq', prompt: 'دَعا and إلى are excluded from المقصور because they are:', options: ['من الأسماء الخمسة', 'فعل وحرف', 'مبنيّان من الأسماء', 'منقوصان'], correct: 1 },
        { title: 'أنا وهذا', kind: 'mcq', prompt: 'أنا and هذا are excluded from المقصور by the قيد:', options: ['بالمعرَب', 'بالاسم', 'بلازمة', 'بما آخره ألف'], correct: 0 },
        { title: 'المثنى رفعًا', kind: 'mcq', prompt: 'The مثنى في حالة الرفع is excluded from المقصور by:', options: ['قيد الاسمية', 'قيد الألف', 'قيد اللزوم', 'قيد الإعراب'], correct: 2 },
        { title: 'إخراج المنقوص', kind: 'mcq', prompt: 'Which قيد of المقصور shuts out the منقوص?', options: ['بالمعرَب', 'بلازمة', 'وبما آخره ألف', 'بالاسم'], correct: 2 },
        { title: 'صحراء وحمراء', kind: 'mcq', prompt: 'صحراء and حمراء illustrate:', options: ['الصحيح', 'الممدود', 'المقصور', 'المنقوص'], correct: 1 },
        { title: 'زيادة الألف', kind: 'mcq', prompt: 'In the definition of الممدود, the ألف before the همزة is described as:', options: ['أصلية', 'لازمة', 'مقلوبة', 'زائدة'], correct: 3 },
        { title: 'حدّ الصحيح', kind: 'mcq', prompt: 'الصحيح is defined as:', options: ['That which ends in a همزة', 'That which does not admit إعراب', 'That which is none of the above', 'That which ends in a letter of علّة'], correct: 2 },
        { title: 'رجل وكتاب', kind: 'mcq', prompt: 'رجل and كتاب are given for:', options: ['المقصور', 'المنقوص', 'الصحيح', 'الممدود'], correct: 2 },
        { title: 'دَلْو', kind: 'mcq', prompt: 'دَلْوٌ is offered as an example of a word:', options: ['مقصور سماعيّ', 'شبيه بالصحيح — لامه حرف علّة وقبله سكون', 'منقوص', 'ممدود'], correct: 1 },
        { title: 'نظر الصرفيّ', kind: 'mcq', prompt: 'The قياسيّ مقصور and ممدود are the ground of:', options: ['المحدِّث', 'الأصوليّ', 'الصرفيّ', 'اللُّغَوِيّ'], correct: 2 },
        { title: 'عمل اللغويّ', kind: 'mcq', prompt: 'The اللُّغَوِيّ is described as one who:', options: ['يجمع الشواهد الشعرية', 'يَسْرُدُ ألفاظَ العرب ويضع معانيها بإزائها', 'يقيس اللفظ على نظيره', 'يبحث في الإعراب'], correct: 1 },
        { title: 'يَسْرُدُ', kind: 'mcq', prompt: 'يَسْرُدُ means:', options: ['to abridge', 'to detail out, one by one', 'to memorise', 'to translate'], correct: 1 },
        { title: 'بإزائها', kind: 'mcq', prompt: 'بإزائها means:', options: ['in their place', 'after them', 'in their order', 'by itself, set against them'], correct: 3 },
        { title: 'انقسام المقصور والممدود', kind: 'mcq', prompt: 'المقصور and الممدود each divide into:', options: ['مفرد وجمع', 'قياسيّ وسماعيّ', 'لازم ومتعدٍّ', 'حقيقيّ ومجازيّ'], correct: 1 },
        { title: 'المُنادِي', kind: 'mcq', prompt: 'المُنادِي ends in a ياء that is:', options: ['مقلوبة عن ألف', 'لازمة، ومكسور ما قبلها', 'غير لازمة', 'ساكن ما قبلها'], correct: 1 },
        { title: 'المصطفى', kind: 'mcq', prompt: 'المصطفى ends in an ألف that is:', options: ['زائدة تليها همزة', 'غير لازمة', 'مقلوبة عن ياء', 'لازمة'], correct: 3 },
        { title: 'مقابلة القيود', kind: 'mcq', prompt: 'What do the قيد lists in the two definitions have in common?', options: ['كلها زوائد لا عمل لها', 'كل قيد يخرج به شيء بعينه', 'كلها تخرج الأفعال', 'كلها تتعلق بالإعراب'], correct: 1 },
        { title: 'الصحيح والملحق به', kind: 'mcq', prompt: 'Which pair is attached to الصحيح rather than being منقوصًا?', options: ['الداعِى والمُنادِي', 'الهُدَى والمصطفى', 'صحراء وحمراء', 'ظَبْيٌ ورَمْيٌ'], correct: 3 },
      ],
    },
    {
      id: 'l2',
      title: 'المقصور القياسيّ',
      subtitle: 'Eight places where a معتلّ اللام noun must end in an ألف — each with its صحيح counterpart',
      concepts: [
        {
          heading: 'الضابط، والأول والثاني',
          lines: [
            { html: `<bdi>والمقصور القياسيّ: هو كلّ اسمٍ معتلِّ اللام، له نظيرٌ من الصحيح، مُلْتَزَمٌ فتحُ ما قبل آخره.</bdi>`, list: false },
            { html: `<bdi>وذلك كمصدر الفعل المعتلِ اللام، الذى على وزن</bdi>:`, list: false },
            { html: `<bdi>فَعِلَ (باب سمع)، بفتح فكسر، كالجَوَى والهَوَى والعَمَى، فإنه نظيرُ الفرَح والأَشَرِ والطَّرَب.</bdi>`, list: true, bullet: true },
            { html: `<bdi>وكفِعَل بكسر ففتح، في جمع فِعْلَة، بكسر فسكون، نحو فِرْيَة وفِرىً، ومِرْيَة ومِرىً</bdi> — <bdi>الفِرْيَة</bdi> is falsehood, <bdi>المِرْيَة</bdi> doubt or argument, <bdi>نحو: لِحْيَة لِحًى</bdi>.`, list: true, bullet: true },
          ],
          clarification: `The whole rule turns on the نظير. A word is مقصور بالقياس only if the same pattern, run on a صحيح root, would keep a fatḥa on the letter before the last — الفرَح، الأَشَر، الطَّرَب beside الجَوَى، الهَوَى، العَمَى. Where that counterpart does not exist, the قياس has nothing to stand on and the word is سماعيّ. Of the eight entries, only the second is set out without a نظير named beside it.`,
          exercise: {
            prompt: `<bdi>الجَوَى</bdi>, <bdi>الهَوَى</bdi> and <bdi>العَمَى</bdi> are قياسيّ because their نظير from the صحيح is:`,
            kind: 'mcq',
            options: ['مُكْرَم ومستخْرَج', 'الأبعدُ والأعمش', 'الفرَح والأَشَر والطَّرَب', 'قِرَب وقُرَب'],
            correct: 2,
          },
        },
        {
          heading: 'الثالث والرابع',
          lines: [
            { html: `<bdi>وفُعَل، بضم ففتح، في جمع فُعْلَة، بضم فسكون، نحو ومُدْيَة ومُدىً، وزُبْيَة وزُبىً، فإن نظيرهما قِرَب بالكسر، وقُرَب بالضم، في جمع قِرْبة بالكسر وقُرْبَة بالضم.</bdi>`, list: false },
            { html: `<bdi>المُدْيَة</bdi> is a knife, <bdi>الزُّبْيَة</bdi> a high place, <bdi>القِرَب</bdi> waterskins.`, list: false },
            { html: `<bdi>وكذا كل اسم مفعولٍ معتل اللام، زائد على الثلاثة، كمُعْطًى ومُسْتَدعًى، فإن نظيرَه مُكْرَم ومستخْرَج.</bdi>`, list: false },
          ],
          exercise: {
            prompt: `<bdi>مُعْطًى</bdi> and <bdi>مُسْتَدعًى</bdi> are مقصور قياسيّ as:`,
            kind: 'mcq',
            options: ['صيغة تفضيل', 'مصدر فَعِلَ', 'اسم مفعول معتلّ اللام زائد على الثلاثة', 'جمع فُعْلَة'],
            correct: 2,
          },
        },
        {
          heading: 'الخامس والسادس',
          lines: [
            { html: `<bdi>وكذا أفعل صيغة تفضيل كالأَقْصَى، أو لغيره كالأعمى (صفة مشبهة)، ونظيرهما من الصحيح الأبعدُ والأعمش.</bdi>`, list: false },
            { html: `<bdi>الأَقْصَى</bdi> is the remotest; <bdi>الأعمش</bdi> is one affected by an eye disease.`, list: false },
            { html: `<bdi>وكذا ما كان جمعا لفُعْلَى أنثى أفعل (تفضيل)، كالدُّنيا والدُّنا. ونظيره الأُخْرَى والأُخَر.</bdi>`, list: false },
          ],
          clarification: `The fifth entry covers أَفْعَل in both of its senses at once — as a تفضيل in الأَقْصَى and as a صفة مشبهة in الأعمى — and gives one نظير for each: الأبعد against the first, الأعمش against the second.`,
          exercise: {
            prompt: `<bdi>الأعمى</bdi> is placed in this list as:`,
            kind: 'mcq',
            options: ['أفعل تفضيل', 'جمع فُعْلَى', 'اسم مفعول', 'أفعل لغير التفضيل — صفة مشبهة'],
            correct: 3,
          },
        },
        {
          heading: 'السابع والثامن',
          lines: [
            { html: `<bdi>وكذا ما كان من أسماء الأجناس دالًّا على الجَمْعِيَّة بالتَّجَرُّد من التاء، على وزن فَعَل بفتحتين، وعلى الوحدة بالتاء، كحَصَاة وحَصًى، ونظيره مَدَرَة ومَدَر.</bdi>`, list: false },
            { html: `<bdi>المَدَر</bdi> is pieces of clay.`, list: false },
            { html: `<bdi>وكذا المَفْعَل مدلولًا به على مصدر أو زمان أو مكان، نحو: مَلْهًى ومَسْعًى ونظيرُه مَذْهَب ومَسْرَح</bdi> — <bdi>المَسْرَح</bdi> is pasture.`, list: false },
          ],
          exercise: {
            prompt: `In <bdi>حَصَاة وحَصًى</bdi>, what marks the جَمْعِيَّة?`,
            kind: 'mcq',
            options: ['التَّجَرُّد من التاء', 'لحوق التاء', 'فتح ما قبل الآخر', 'زيادة الألف'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'The المقصور القياسيّ is defined as every اسم معتلّ اللام that:', options: ['له مصدر قياسيّ', 'يقبل التاء', 'له نظير من الصحيح مُلْتَزَمٌ فتحُ ما قبل آخره', 'آخره ألف زائدة'], correct: 2 },
        { q: 'فِرْيَة وفِرىً belongs to which entry?', options: ['فِعَل في جمع فِعْلَة', 'فُعَل في جمع فُعْلَة', 'مصدر فَعِلَ', 'اسم المفعول'], correct: 0 },
        { q: 'The نظير of مُدىً and زُبىً is:', options: ['الأبعد والأعمش', 'الأُخْرَى والأُخَر', 'قِرَب وقُرَب', 'مَدَرَة ومَدَر'], correct: 2 },
        { q: 'The نظير of الدُّنيا والدُّنا is:', options: ['مَذْهَب ومَسْرَح', 'الأُخْرَى والأُخَر', 'الأبعد والأعمش', 'مُكْرَم ومستخْرَج'], correct: 1 },
        { q: 'مَلْهًى ومَسْعًى fall under:', options: ['اسم المفعول الزائد على الثلاثة', 'أفعل التفضيل', 'أسماء الأجناس', 'المَفْعَل الدالّ على مصدر أو زمان أو مكان'], correct: 3 },
        { q: 'المَسْرَح means:', options: ['a knife', 'a high place', 'pasture', 'pieces of clay'], correct: 2 },
      ],
      bank: [
        { title: 'باب سمع', kind: 'mcq', prompt: 'فَعِلَ بفتح فكسر is identified as:', options: ['باب سمع', 'باب ضرب', 'باب نصر', 'باب كرم'], correct: 0 },
        { title: 'الأَشَر', kind: 'mcq', prompt: 'الفرَح، الأَشَر، الطَّرَب are the نظير of:', options: ['الجَوَى والهَوَى والعَمَى', 'فِرىً ومِرىً', 'مُدىً وزُبىً', 'حَصًى ومَدَر'], correct: 0 },
        { title: 'الفِرْيَة', kind: 'mcq', prompt: 'الفِرْيَة means:', options: ['doubt', 'a knife', 'a waterskin', 'falsehood'], correct: 3 },
        { title: 'المِرْيَة', kind: 'mcq', prompt: 'المِرْيَة means:', options: ['clay', 'pasture', 'doubt, argument', 'falsehood'], correct: 2 },
        { title: 'لِحْيَة لِحًى', kind: 'mcq', prompt: 'لِحْيَة لِحًى stands alongside:', options: ['حَصَاة وحَصًى', 'زُبْيَة وزُبىً', 'فِرْيَة وفِرىً', 'مُدْيَة ومُدىً'], correct: 2 },
        { title: 'ضبط فِعَل', kind: 'mcq', prompt: 'فِعَل, the plural of فِعْلَة, is vowelled:', options: ['بكسر ففتح', 'بفتح فكسر', 'بضم ففتح', 'بفتحتين'], correct: 0 },
        { title: 'ضبط فُعَل', kind: 'mcq', prompt: 'فُعَل, the plural of فُعْلَة, is vowelled:', options: ['بضم ففتح', 'بكسر ففتح', 'بضمتين', 'بفتحتين'], correct: 0 },
        { title: 'المُدْيَة', kind: 'mcq', prompt: 'المُدْيَة means:', options: ['a high place', 'a waterskin', 'a piece of clay', 'a knife'], correct: 3 },
        { title: 'الزُّبْيَة', kind: 'mcq', prompt: 'الزُّبْيَة means:', options: ['a knife', 'a waterskin', 'a pasture', 'a high place'], correct: 3 },
        { title: 'القِرَب', kind: 'mcq', prompt: 'القِرَب means:', options: ['high places', 'waterskins', 'knives', 'clay pieces'], correct: 1 },
        { title: 'قِرْبة وقُرْبَة', kind: 'mcq', prompt: 'قِرَب and قُرَب are the plurals of:', options: ['قِرْبة بالكسر وقُرْبَة بالضم', 'قِرْبة بالكسر only', 'قُرْبَة بالضم only', 'قَرَبَة بالفتح'], correct: 0 },
        { title: 'شرط اسم المفعول', kind: 'mcq', prompt: 'The اسم مفعول entry requires the verb to be:', options: ['معتلّ اللام وزائدًا على الثلاثة', 'ثلاثيًّا معتلّ اللام', 'معتلّ العين', 'مضاعفًا'], correct: 0 },
        { title: 'نظير مُعْطًى', kind: 'mcq', prompt: 'The نظير of مُعْطًى ومُسْتَدعًى is:', options: ['مَذْهَب ومَسْرَح', 'مُكْرَم ومستخْرَج', 'الأبعد والأعمش', 'قِرَب وقُرَب'], correct: 1 },
        { title: 'الأَقْصَى', kind: 'mcq', prompt: 'الأَقْصَى means:', options: ['remotest', 'blindest', 'nearest', 'greatest'], correct: 0 },
        { title: 'الأعمش', kind: 'mcq', prompt: 'الأعمش is:', options: ['one who is blind', 'the remotest', 'one who is deaf', 'one affected by an eye disease'], correct: 3 },
        { title: 'وصف الأعمى', kind: 'mcq', prompt: 'الأعمى is marked in the list as:', options: ['جمع', 'صفة مشبهة', 'صيغة تفضيل', 'اسم مفعول'], correct: 1 },
        { title: 'الدُّنيا', kind: 'mcq', prompt: 'الدُّنيا والدُّنا falls under which entry?', options: ['That which is a plural of فُعْلَى, the feminine of أفعل', 'أفعل صيغة تفضيل', 'اسم المفعول', 'أسماء الأجناس'], correct: 0 },
        { title: 'وزن اسم الجنس', kind: 'mcq', prompt: 'The اسم جنس entry is on the وزن:', options: ['مَفْعَل', 'فَعَل بفتحتين', 'فِعَل بكسر ففتح', 'فُعَل بضم ففتح'], correct: 1 },
        { title: 'الوحدة بالتاء', kind: 'mcq', prompt: 'In حَصَاة وحَصًى, الوحدة is marked by:', options: ['الألف', 'كسر ما قبل الآخر', 'التاء', 'التجرّد من التاء'], correct: 2 },
        { title: 'مَدَرَة ومَدَر', kind: 'mcq', prompt: 'مَدَرَة ومَدَر is the نظير of:', options: ['مُدْيَة ومُدىً', 'فِرْيَة وفِرىً', 'الدُّنيا والدُّنا', 'حَصَاة وحَصًى'], correct: 3 },
        { title: 'المَدَر', kind: 'mcq', prompt: 'المَدَر means:', options: ['pebbles', 'waterskins', 'high places', 'pieces of clay'], correct: 3 },
        { title: 'ثلاث دلالات للمَفْعَل', kind: 'mcq', prompt: 'The مَفْعَل entry covers which three senses?', options: ['فاعل أو مفعول أو مصدر', 'مصدر أو زمان أو مكان', 'مصدر أو آلة أو مكان', 'زمان أو مكان أو آلة'], correct: 1 },
        { title: 'مَذْهَب ومَسْرَح', kind: 'mcq', prompt: 'مَذْهَب and مَسْرَح serve as the نظير of:', options: ['مَلْهًى ومَسْعًى', 'مُعْطًى ومُسْتَدعًى', 'الأَقْصَى والأعمى', 'حَصًى ومَدَر'], correct: 0 },
        { title: 'دور النظير', kind: 'mcq', prompt: 'What makes a مقصور قياسيّ rather than سماعيّ?', options: ['كثرة استعماله', 'كونه معتلّ اللام', 'كونه مصدرًا', 'وجود نظير من الصحيح ملتزَم فتح ما قبل آخره'], correct: 3 },
      ],
    },
    {
      id: 'l3',
      title: 'الممدود: القياسي والسماعي',
      subtitle: 'Four places where the ألف must be added before the last letter, and what falls outside them',
      concepts: [
        {
          heading: 'الضابط، والأول',
          lines: [
            { html: `<bdi>والممدود القياسي: كل اسم معتل اللام نظير من الصحيح الآخر، مُلْتَزَمٌ فيه زيادة ألف قبل آخره.</bdi>`, list: false },
            { html: `<bdi>وذلك: كمصدر ما أوَّله همزةُ وصلٍ، نحو: ارْعَوَى ارْعِواء، وابتغَى ابْتِغاء، واستَقْصَى استِقْصاء، فإن نظيرها من الصحيح: احمرَّ احمرارًا، واقتدر اقتدارًا، واستخرج استخراجًا.</bdi>`, list: false },
          ],
          clarification: `The ممدود rule is the mirror of the مقصور one. There the نظير had to keep a fatḥa before the last letter; here it has to carry an added ألف in the same slot. So احمرار decides ارْعِواء, and اقتدار decides ابْتِغاء.`,
          exercise: {
            prompt: `<bdi>ابْتِغاء</bdi> is ممدود قياسيّ because its نظير from the صحيح is:`,
            kind: 'mcq',
            options: ['اقتدر اقتدارًا', 'أكرم إكرامًا', 'حِمَار وأَحْمِرَة', 'صُراخ'],
            correct: 0,
          },
        },
        {
          heading: 'الثاني والثالث',
          lines: [
            { html: `<bdi>كذا مصدر كل فعل معتل اللام يُوازِن أفعل، كأعطى إعْطاء وأمْلَى إملاء، فإن نظيره من الصحيح أكرم إكرامًا، وأحسن إحسانًا.</bdi>`, list: false },
            { html: `<bdi>وكذا كل ما كان مفردَ الأفْعِلة، ككِساء وأَكْسِية، ورداء وأَرْدِيَة، فإن نظيره من الصحيح حِمَارٌ وأَحْمِرَة، وسلاحٌ وأَسْلِحة.</bdi>`, list: false },
            { html: `<bdi>الكِساء</bdi> is a garment.`, list: false },
          ],
          exercise: {
            prompt: `<bdi>رداء وأَرْدِيَة</bdi> is قياسيّ because its نظير is:`,
            kind: 'mcq',
            options: ['صُراخ وزُكام', 'حِمَارٌ وأَحْمِرَة، وسلاحٌ وأَسْلِحة', 'أكرم إكرامًا، وأحسن إحسانًا', 'احمرَّ احمرارًا'],
            correct: 1,
          },
        },
        {
          heading: 'الرابع، وحدّ السماعيّ',
          lines: [
            { html: `<bdi>وكذا كل مصدر لفَعَل بفتحتين دالًّا على صوت أو داء، كالرُّغاء: لصوت البعير، والثُّغاء: لصوت الشاة، فإن نظيره الصُّراخ، وكالمُشاء، فإن نظيره الزُّكام.</bdi>`, list: false },
            { html: `<bdi>المُشاء</bdi> is a stomach illness.`, list: false },
            { html: `<bdi>والسماعيّ منهما ما فقد ذلك النظير.</bdi>`, list: false },
          ],
          clarification: `The last sentence closes the whole division: whatever مقصور or ممدود has no such counterpart in the صحيح is سماعيّ, and belongs to the lexicographer rather than to the صرفيّ. The two lists that follow are simply what that leaves over.`,
          exercise: {
            prompt: `What makes a مقصور or ممدود سماعيّ?`,
            kind: 'mcq',
            options: ['That it is a مصدر', 'That its ألف is زائدة', 'That it lacks the نظير from الصحيح', 'That it is معتلّ اللام'],
            correct: 2,
          },
        },
        {
          heading: 'السماعيّ من المقصور والممدود',
          lines: [
            { table: {
              title: 'فمن المقصور سماعًا',
              headers: ['اللفظ', 'المعنى'],
              rows: [
                ['الفَتَى', 'واحد الفِتْيان'],
                ['الحِجَا', 'أي العقل'],
                ['السَّنَا', 'أى الضَّوْء'],
                ['الثَّرَى', 'أى التراب'],
              ],
            } },
            { table: {
              title: 'ومن الممدود سماعًا',
              headers: ['اللفظ', 'الضبط', 'المعنى'],
              rows: [
                ['الثَّراء', 'بالفتح', 'لكثرة المال'],
                ['الحِذاء', 'بالكسر', 'للنعل'],
                ['الفُتاء', 'بالضم', 'لحداثة السنّ'],
                ['السَّناء', 'بفتح السين', 'للشرف'],
              ],
            } },
          ],
          clarification: `Two pairs in these lists differ only by the مدّ, and the meaning moves with it. <bdi>السَّنَا</bdi> مقصورًا is light, <bdi>السَّناء</bdi> ممدودًا is high standing; <bdi>الثَّرَى</bdi> مقصورًا is dust, <bdi>الثَّراء</bdi> ممدودًا is wealth.`,
          exercise: {
            prompt: `<bdi>السَّنَا</bdi> and <bdi>السَّناء</bdi> mean, respectively:`,
            kind: 'mcq',
            options: ['nobility and light', 'reason and a sandal', 'dust and abundance of wealth', 'light and nobility'],
            correct: 3,
          },
        },
      ],
      quiz: [
        { q: 'The ممدود القياسيّ requires a نظير in which زيادة ألف قبل الآخر is:', options: ['مُلْتَزَمة', 'جائزة', 'ممتنعة', 'سماعية'], correct: 0 },
        { q: 'ارْعَوَى ارْعِواء has as its نظير:', options: ['احمرَّ احمرارًا', 'أكرم إكرامًا', 'حِمَار وأَحْمِرَة', 'صُراخ'], correct: 0 },
        { q: 'أعطى إعْطاء and أمْلَى إملاء fall under مصدر:', options: ['فَعَل denoting a sound or an illness', 'Every لام-weak verb that weighs أفعل', 'That whose first letter is همزة وصل', 'The singular of الأفْعِلة'], correct: 1 },
        { q: 'الرُّغاء is:', options: ['صوت الشاة', 'داء في البطن', 'كثرة المال', 'صوت البعير'], correct: 3 },
        { q: 'الحِجَا means:', options: ['الضَّوْء', 'التراب', 'الشرف', 'العقل'], correct: 3 },
        { q: 'الحِذاء بالكسر means:', options: ['النعل', 'كثرة المال', 'حداثة السنّ', 'الشرف'], correct: 0 },
      ],
      bank: [
        { title: 'حدّ الممدود القياسيّ', kind: 'mcq', prompt: 'The ممدود القياسيّ is every اسم معتلّ اللام that has:', options: ['ألفًا لازمة', 'همزة أصلية', 'نظيرًا ملتزَمًا فتح ما قبل آخره', 'نظيرًا من الصحيح الآخر ملتزَمًا فيه زيادة ألف قبل آخره'], correct: 3 },
        { title: 'استِقْصاء', kind: 'mcq', prompt: 'استَقْصَى استِقْصاء has as its نظير:', options: ['أحسن إحسانًا', 'استخرج استخراجًا', 'اقتدر اقتدارًا', 'احمرَّ احمرارًا'], correct: 1 },
        { title: 'همزة الوصل', kind: 'mcq', prompt: 'The first entry of the ممدود covers مصدر of a verb whose first letter is:', options: ['ميم زائدة', 'همزة وصل', 'همزة قطع', 'تاء زائدة'], correct: 1 },
        { title: 'ثلاثة نظائر', kind: 'mcq', prompt: 'How many صحيح نظائر are offered for the همزة الوصل entry?', options: ['أربعة', 'واحد', 'ثلاثة — احمرار واقتدار واستخراج', 'اثنان'], correct: 2 },
        { title: 'إعطاء وإملاء', kind: 'mcq', prompt: 'The نظير of إعْطاء and إملاء is:', options: ['إكرامًا وإحسانًا', 'احمرارًا واقتدارًا', 'أَحْمِرَة وأَسِلحة', 'الصُّراخ والزُّكام'], correct: 0 },
        { title: 'الكِساء', kind: 'mcq', prompt: 'الكِساء means:', options: ['a donkey', 'a garment', 'a sandal', 'a weapon'], correct: 1 },
        { title: 'أَكْسِية', kind: 'mcq', prompt: 'كِساء وأَكْسِية illustrates:', options: ['مصدر أفعل', 'مصدر ما أوّله همزة وصل', 'مصدر فَعَل الدالّ على صوت', 'مفرد الأفْعِلة'], correct: 3 },
        { title: 'حِمار وسِلاح', kind: 'mcq', prompt: 'حِمَارٌ وأَحْمِرَة، وسلاحٌ وأَسْلِحة are the نظير of:', options: ['كِساء وأَكْسِية، ورداء وأَرْدِيَة', 'ارْعِواء وابْتِغاء', 'إعْطاء وإملاء', 'الرُّغاء والثُّغاء'], correct: 0 },
        { title: 'وزن الرابع', kind: 'mcq', prompt: 'The fourth entry is the مصدر of a verb on the وزن:', options: ['أفعل', 'افتعل', 'فَعَل بفتحتين', 'فَعِل بفتح فكسر'], correct: 2 },
        { title: 'دلالة الرابع', kind: 'mcq', prompt: 'That fourth entry requires the مصدر to point to:', options: ['صوت أو داء', 'حرفة أو ولاية', 'لون أو عيب', 'زمان أو مكان'], correct: 0 },
        { title: 'الثُّغاء', kind: 'mcq', prompt: 'الثُّغاء is:', options: ['صوت الشاة', 'صوت البعير', 'صوت الأسد', 'صوت الحمار'], correct: 0 },
        { title: 'نظير الرغاء', kind: 'mcq', prompt: 'The نظير of الرُّغاء and الثُّغاء is:', options: ['الاستخراج', 'الإكرام', 'الصُّراخ', 'الزُّكام'], correct: 2 },
        { title: 'المُشاء', kind: 'mcq', prompt: 'المُشاء means:', options: ['a head cold', 'a stomach illness', 'a kind of walking', 'a loud cry'], correct: 1 },
        { title: 'نظير المُشاء', kind: 'mcq', prompt: 'The نظير of المُشاء is:', options: ['الرُّغاء', 'الزُّكام', 'الصُّراخ', 'الثُّغاء'], correct: 1 },
        { title: 'الفَتَى', kind: 'mcq', prompt: 'الفَتَى is explained as:', options: ['reason/intellect', 'light', 'dust', 'one of the fityān'], correct: 3 },
        { title: 'الثَّرَى', kind: 'mcq', prompt: 'الثَّرَى means:', options: ['reason/intellect', 'dust', 'abundance of wealth', 'light'], correct: 1 },
        { title: 'السَّنَا مقصورًا', kind: 'mcq', prompt: 'السَّنَا, مقصورًا, means:', options: ['light', 'nobility, high standing', 'youthfulness', 'sandal'], correct: 0 },
        { title: 'الثَّراء', kind: 'mcq', prompt: 'الثَّراء بالفتح means:', options: ['nobility, high standing', 'sandal', 'abundance of wealth', 'dust'], correct: 2 },
        { title: 'الفُتاء', kind: 'mcq', prompt: 'الفُتاء بالضم means:', options: ['sandal', 'nobility, high standing', 'youthfulness', 'abundance of wealth'], correct: 2 },
        { title: 'السَّناء', kind: 'mcq', prompt: 'السَّناء بفتح السين means:', options: ['light', 'abundance of wealth', 'youthfulness', 'nobility, high standing'], correct: 3 },
        { title: 'ضبط الحِذاء', kind: 'mcq', prompt: 'الحِذاء is vowelled:', options: ['بالكسر', 'بالفتح', 'بالضم', 'بالسكون'], correct: 0 },
        { title: 'المدّ يغيّر المعنى', kind: 'mcq', prompt: 'الثَّرَى and الثَّراء differ in:', options: ['التذكير والتأنيث', 'القصر والمدّ، ومعهما المعنى', 'حركة الفاء فقط', 'العدد'], correct: 1 },
        { title: 'ضابط السماعيّ', kind: 'mcq', prompt: 'السماعيّ من المقصور والممدود is:', options: ['That which was not heard from the Arabs', 'That which lacks that نظير', 'That which is used frequently', 'That which does not occur in the Qur’an'], correct: 1 },
        { title: 'تقابل الضابطين', kind: 'mcq', prompt: 'The نظير of a مقصور keeps a fatḥa before its last letter; the نظير of a ممدود:', options: ['يلتزم كسر ما قبل آخره', 'يلتزم سكون ما قبل آخره', 'لا يشترط فيه شيء', 'يلتزم زيادة ألف قبل آخره'], correct: 3 },
      ],
    },
  ],
};
