// Module 08 — المؤكَّد وغير المؤكَّد (The Emphasised Verb and the Unemphasised)
//
// Covers Week 16 of the Advanced Sarf course: التقسيم السابع للفعل من حيث
// كونه مؤكَّدًا أو غير مؤكَّد, from شذا العرف في فن الصرف by أحمد الحملاوي.
// Definitions, rules, شواهد and verses are kept faithful to the source.
// Concept bodies are short by design; quiz/bank question text is English with
// Arabic morphological terms left in Arabic.
//
// Scope: نون التوكيد ثقيلة and خفيفة; the other ways a verb is emphasised
// (قد، اللام، القسم); why the ماضي is never emphasised and the أمر always may
// be; and the six states of the مضارع — واجب، قريب من الواجب، كثير، قليل،
// أقلّ، ممتنع — with the شواهد for each. This closes the seven divisions of
// الفعل; التقسيم الأول للاسم follows in Module 09.

export default {
  id: 'as-08',
  title: 'المؤكَّد وغير المؤكَّد',
  heading: 'الفعل',
  blurb: 'الفعل divided by whether نون التوكيد may attach to it — and the six grades along which المضارع runs.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'التوكيد بالنون وبغيرها',
      subtitle: 'The نون and its Alternatives — what emphasis does, and how the ماضي and the أمر stand at opposite extremes',
      concepts: [
        {
          heading: 'التعريفان ونونا التوكيد',
          lines: [
            { html: `<bdi>يَنْقَسِمُ الفِعْلُ إلى مُؤَكَّدٍ بِالنُّونِ، وغَيْرِ مُؤَكَّدٍ</bdi> — الفعل divides into مُؤَكَّد بالنون (emphasized with the نون) and غير مؤكَّد.`, list: false },
            { table: { headers: ['القسم', 'التعريف', 'أمثلة'], rows: [
              ['المُؤَكَّد', 'ما لَحِقَتْهُ نُونُ التَّوْكِيدِ، ثَقِيلَةً كانَتْ أو خَفِيفَةً', '﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾ [يوسف: ٣٢]'],
              ['غَيْرُ المُؤَكَّد', 'ما لم تَلْحَقْهُ', 'يُسْجَنُ ، يَكُونُ'],
            ] } },
            { html: `The شاهد carries both نونان at once — the heavy on <bdi>لَيُسْجَنَنَّ</bdi>, the light on <bdi>لَيَكُونًا</bdi>. <bdi>﴿لَيَكُونًا﴾ الأَصْلُ: لَيَكُونَنْ، ولكنها قُلِبَتْ أَلِفًا في الوَقْفِ</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `﴿لَيَكُونًا﴾ ends in what looks like an alif with tanwīn. What is it in origin?`,
            kind: 'mcq',
            options: ['ياء المخاطبة', 'A نون النسوة', 'لَيَكُونَنْ — the light نون التوكيد, turned into an alif in pause', 'A تنوين, making it a noun'],
            correct: 2,
          },
        },
        {
          heading: 'التوكيد بغير النون',
          lines: [
            { html: `<bdi>وتَوْكِيدُ الفِعْلِ قد يَكُونُ بِغَيْرِ نُونِ التَّوْكِيدِ</bdi> — and a verb's emphasis may also come by means other than نون التوكيد.`, list: false },
            { table: { headers: ['الأداة', 'الشاهد'], rows: [
              ['قَدْ', '﴿قَدْ أَفْلَحَ الْمُؤْمِنُونَ﴾'],
              ['اللام', '﴿وإنَّ رَبَّكَ لَيَحْكُمُ بَيْنَهُمْ﴾'],
              ['القَسَم', 'واللهِ لَسَوْفَ أَذْهَبُ'],
            ] } },
            { html: `<bdi>ولكنَّ هذا البابَ مَعْقُودٌ لِلْكَلامِ على تَوْكِيدِ الفِعْلِ بِالنُّونِ</bdi> — but this باب is devoted to discussing the verb's emphasis specifically by the نون — the other three are noted and set aside.`, list: false },
          ],
          exercise: {
            prompt: `﴿قَدْ أَفْلَحَ الْمُؤْمِنُونَ﴾ is an instance of emphasis. By what means?`,
            kind: 'mcq',
            options: ['اللام', 'القسم', 'نون التوكيد', 'قَدْ'],
            correct: 3,
          },
        },
        {
          heading: 'ما يدل عليه التوكيد بالنون، والماضي',
          lines: [
            { html: `<bdi>التَّوْكِيدُ بِالنُّونِ يَدُلُّ على شَيْئَيْنِ</bdi>: <bdi>التَّوْكِيد</bdi> and <bdi>الاسْتِقْبال</bdi>.`, list: false },
            { html: `That second meaning settles the whole باب. <bdi>فالماضي لا يُؤَكَّدُ مُطْلَقًا، التَّوْكِيدُ إنَّما يُؤَكَّدُ بِهِ حَدَثٌ مُسْتَقْبَلٌ</bdi>.`, list: false },
            { html: `A نون that carries futurity cannot attach to a form that names something already done — the two would contradict each other.`, list: false },
          ],
          clarification: `Everything in this باب follows from the نون carrying two things rather than one. If it only added emphasis, there would be no reason a ماضي could not take it — a past event can be asserted emphatically. But it also imposes الاستقبال, and that is what the ماضي cannot accommodate. Read the six states of the مضارع in the next two lessons with this in mind: the مضارع is صالح for both الحال and الاستقبال, so whether the نون may attach turns on whether the context has already fixed the verb to the future or left it open — and where the context fixes it to الحال, the نون is barred outright.`,
          exercise: {
            prompt: `Why can the ماضي never take نون التوكيد؟`,
            kind: 'mcq',
            options: ['The نون attaches only to the أمر', 'The نون imposes الاستقبال, which a past event cannot accommodate', 'The ماضي is مبني', 'The ماضي already carries emphasis'],
            correct: 1,
          },
        },
        {
          heading: 'الشاذ في الماضي والاسم، والأمر',
          lines: [
            { html: `<bdi>وأمَّا قَوْلُهُ: دامَنَّ سَعْدُكِ لو رَحِمْتِ مُتَيَّمًا</bdi> — <bdi>فضَرُورَةٌ شاذَّةٌ، سَهَّلَها ما في الفِعْلِ من مَعْنَى الطَّلَبِ، فعُومِلَ مُعامَلَةَ الأَمْرِ</bdi> — as for the line دامَنَّ سَعْدُكِ لو رَحِمْتِ مُتَيَّمًا, that is an anomalous poetic necessity, made easier by the sense of الطلب (request) present in the verb, so it was treated as though it were an أمر.`, list: false },
            { html: `<bdi>كما شَذَّ تَوْكِيدُ الاسْمِ في قَوْلِ رُؤْبَةَ بنِ العَجَّاجِ: أَقائِلُنَّ (أنتَ) أَحْضِرُوا الشُّهُودا</bdi> — just as the emphasis of a noun is likewise anomalous in the line of رُؤْبَة بن العَجَّاج: أَقائِلُنَّ (أنتَ) أَحْضِرُوا الشُّهُودا.`, list: false },
            { html: `<bdi>والأَمْرُ يَجُوزُ تَوْكِيدُهُ مُطْلَقًا، الأَمْرُ يُطْلَبُ بِهِ حُدُوثُ الفِعْلِ في المُسْتَقْبَلِ دائِمًا</bdi> — and the أمر may always be emphasized, unconditionally: the أمر always seeks the action's occurrence in the future — <bdi>نحو: اكْتُبَنَّ واجْتَهِدَنْ</bdi>.`, list: false },
            { html: `So the ماضي and the أمر sit at the two extremes: the first can never take the نون, the second always can. Only the مضارع varies.`, list: false },
          ],
          exercise: {
            prompt: `Why may the أمر always take نون التوكيد؟`,
            kind: 'mcq',
            options: ['It carries no time reference at all', 'What it seeks is always in the future, which is what the نون requires', 'It is مبني', 'It has no ماضٍ'],
            correct: 1,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the definition of المؤكَّد؟',
          options: ['That which نون التوكيد has attached to, heavy or light', 'That which نون التوكيد has not attached to', 'That which قد has entered on', 'That which stands as the answer to an oath'],
          correct: 0,
        },
        {
          q: 'نون التوكيد comes in how many forms?',
          options: ['أربع', 'اثنتان — ثقيلة وخفيفة', 'واحدة', 'ثلاث'],
          correct: 1,
        },
        {
          q: 'The نون التوكيد indicates which two things?',
          options: ['الاستقبال والطلب', 'التوكيد والمضيّ', 'التوكيد والاستقبال', 'التوكيد والحال'],
          correct: 2,
        },
        {
          q: 'What is the ruling on emphasising the ماضي؟',
          options: ['It may always be emphasised', 'Its emphasis is obligatory', 'Its emphasis is common', 'It is never emphasised'],
          correct: 3,
        },
        {
          q: 'What is the ruling on emphasising the أمر؟',
          options: ['Its emphasis is obligatory', 'Its emphasis is forbidden', 'It may always be emphasised', 'It is never emphasised'],
          correct: 2,
        },
        {
          q: 'أَقائِلُنَّ أَحْضِرُوا الشُّهُودا is an example of what?',
          options: ['امتناع التوكيد', 'شذوذ توكيد الاسم', 'شذوذ توكيد الماضي', 'وجوب توكيد المضارع'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: 'ثقيلة وخفيفة',
          kind: 'mcq',
          prompt: 'Does it matter which of the two نونان attaches for a verb to count as مؤكَّد؟',
          options: ['No — the definition covers both', 'Yes — only the heavy counts', 'Yes — only the light counts', 'Only in the أمر'],
          correct: 0,
        },
        {
          title: 'ليسجنن',
          kind: 'mcq',
          prompt: 'In ﴿لَيُسْجَنَنَّ وَلَيَكُونًا﴾, which نون is on the first verb?',
          options: ['الثقيلة', 'الخفيفة', 'نون النسوة', 'نون الوقاية'],
          correct: 0,
        },
        {
          title: 'قلب النون ألفًا',
          kind: 'mcq',
          prompt: 'Why does لَيَكُونَنْ appear as لَيَكُونًا؟',
          options: ['The verb has been made a noun', 'The light نون is turned into an alif in pause', 'The نون is dropped', 'A تنوين has been added'],
          correct: 1,
        },
        {
          title: 'سورة الشاهد',
          kind: 'mcq',
          prompt: 'From which sūra is ﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾ taken?',
          options: ['يوسف', 'الأنبياء', 'الأنفال', 'مريم'],
          correct: 0,
        },
        {
          title: 'يُسجن ويكون',
          kind: 'mcq',
          prompt: 'يُسْجَنُ and يَكُونُ are examples of what?',
          options: ['المؤكَّد بالنون الثقيلة', 'المؤكَّد بقد', 'غير المؤكَّد', 'المؤكَّد بالنون الخفيفة'],
          correct: 2,
        },
        {
          title: 'قد أفلح',
          kind: 'mcq',
          prompt: '﴿قَدْ أَفْلَحَ الْمُؤْمِنُونَ﴾ emphasises a verb in which tense?',
          options: ['None — it is a noun', 'الماضي', 'المضارع', 'الأمر'],
          correct: 1,
        },
        {
          title: 'التوكيد باللام',
          kind: 'mcq',
          prompt: 'Which شاهد shows emphasis by the لام؟',
          options: ['﴿وإنَّ رَبَّكَ لَيَحْكُمُ بَيْنَهُمْ﴾', '﴿قَدْ أَفْلَحَ الْمُؤْمِنُونَ﴾', 'واللهِ لَسَوْفَ أَذْهَبُ', '﴿لَيُسْجَنَنَّ﴾'],
          correct: 0,
        },
        {
          title: 'التوكيد بالقسم',
          kind: 'mcq',
          prompt: 'واللهِ لَسَوْفَ أَذْهَبُ illustrates emphasis by which means?',
          options: ['نون التوكيد', 'أداة الطلب', 'القسم', 'قَدْ'],
          correct: 2,
        },
        {
          title: 'موضوع الباب',
          kind: 'mcq',
          prompt: 'Having named four ways of emphasising a verb, which does this باب actually treat?',
          options: ['التوكيد بالنون', 'التوكيد بقد', 'التوكيد باللام', 'التوكيد بالقسم'],
          correct: 0,
        },
        {
          title: 'الدلالتان',
          kind: 'mcq',
          prompt: 'Which of the نون’s two meanings is the one that excludes the ماضي؟',
          options: ['Neither — the exclusion is arbitrary', 'الاستقبال', 'التوكيد', 'Both equally'],
          correct: 1,
        },
        {
          title: 'دامَنَّ سعدك',
          kind: 'mcq',
          prompt: 'دامَنَّ سَعْدُكِ لو رَحِمْتِ مُتَيَّمًا is a ماضٍ carrying a نون. How is it judged?',
          options: ['واجب', 'كثير', 'ضرورة شاذة', 'قياسي مطرد'],
          correct: 2,
        },
        {
          title: 'ما سهَّل الشذوذ',
          kind: 'mcq',
          prompt: 'What is said to have made the شذوذ in دامَنَّ easier?',
          options: ['The verb is معتل', 'The verb is مضعَّف', 'The metre required it', 'The verb carries a sense of الطلب, so it was treated like an أمر'],
          correct: 3,
        },
        {
          title: 'رؤبة بن العجاج',
          kind: 'mcq',
          prompt: 'أَقائِلُنَّ أَحْضِرُوا الشُّهُودا is attributed to whom?',
          options: ['ابن مالك', 'رُؤْبَة بن العَجَّاج', 'خِرْنِق بنت هَفَّان', 'جَذِيمة الأبرش'],
          correct: 1,
        },
        {
          title: 'شذوذ الاسم',
          kind: 'mcq',
          prompt: 'What is شاذ about أَقائِلُنَّ؟',
          options: ['The verb is مبني للمجهول', 'The نون is doubled', 'A نون التوكيد has attached to an اسم', 'A نون has attached to a ماضٍ'],
          correct: 2,
        },
        {
          title: 'اكتبنَّ واجتهدنْ',
          kind: 'mcq',
          prompt: 'اكْتُبَنَّ and اجْتَهِدَنْ differ in which نون each carries?',
          options: ['The first the light, the second the heavy', 'Both the heavy', 'Both the light', 'The first the heavy, the second the light'],
          correct: 3,
        },
        {
          title: 'مطلقًا مرتين',
          kind: 'mcq',
          prompt: 'The word مطلقًا is used of both the ماضي and the أمر. What does each assertion say?',
          options: ['The ماضي never takes the نون; the أمر always may', 'Both always may', 'Both never may', 'The ماضي always may; the أمر never'],
          correct: 0,
        },
        {
          title: 'موقع المضارع',
          kind: 'mcq',
          prompt: 'Given that the ماضي and the أمر are settled, which form is the subject of the rest of this باب؟',
          options: ['المضارع', 'الماضي', 'الأمر', 'اسم الفعل'],
          correct: 0,
        },
        {
          title: 'سبب جواز الأمر',
          kind: 'mcq',
          prompt: 'What about the أمر makes it always eligible for the نون؟',
          options: ['It has no فاعل ظاهر', 'It carries no time', 'حدوث الفعل is always sought in the future', 'It is مبني'],
          correct: 2,
        },
        {
          title: 'معاملة الأمر',
          kind: 'mcq',
          prompt: 'دامَنَّ was treated مُعامَلَةَ الأَمْرِ. Why does that make the نون tolerable?',
          options: ['Because the أمر always admits the نون, and the verb carried a sense of request', 'Because the أمر is مبني', 'Because the أمر has no ماضٍ', 'Because the نون was light'],
          correct: 0,
        },
        {
          title: 'المؤكَّد وغير المؤكَّد',
          kind: 'mcq',
          prompt: 'This division sorts verbs by what?',
          options: ['Whether they take an object', 'Whether they inflect', 'Whether نون التوكيد has attached to them', 'Whether they carry a زمن'],
          correct: 2,
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'حالات المضارع: الواجب والكثير',
      subtitle: 'The First Three Grades — where the نون must attach, where it nearly must, and where it commonly does',
      concepts: [
        {
          heading: 'الحالات الست',
          lines: [
            { html: `<bdi>وأمَّا المُضارِعُ فله سِتُّ حالاتٍ</bdi>: <bdi>واجِبًا</bdi>، <bdi>قَرِيبًا من الواجِبِ</bdi>، <bdi>كَثِيرًا</bdi>، <bdi>قَلِيلًا</bdi>، <bdi>أَقَلَّ</bdi>، <bdi>مُمْتَنِعًا</bdi> — the مضارع has six states: واجِب (obligatory), قَرِيب من الواجِب (near-obligatory), كَثِير (common), قَلِيل (rare), أَقَلّ (rarer still), and مُمْتَنِع (impossible).`, list: false },
            { html: `<bdi>الأَصْلُ في المُضارِعِ أنَّهُ يَأْتِي في الحالِ أو الاسْتِقْبالِ، فإن كان في الحالِ فلا تَدْخُلُهُ نُونُ التَّوْكِيدِ</bdi> — the default for the مضارع is that it comes for الحال (the present) or الاستقبال (the future); if it is for الحال, نون التوكيد does not enter on it.`, list: false },
            { html: `The six run as a single scale from obligatory to impossible, and what moves a verb along it is how firmly its context has fixed it to the future.`, list: false },
          ],
          exercise: {
            prompt: `A مضارع is fixed by its context to الحال. What follows for نون التوكيد؟`,
            kind: 'mcq',
            options: ['It commonly attaches', 'It rarely attaches', 'It cannot attach at all', 'It must attach'],
            correct: 2,
          },
        },
        {
          heading: 'الحالة الأولى: الواجب',
          lines: [
            { html: `<bdi>فيَجِبُ تَأْكِيدُهُ إذا كان</bdi> — and four conditions must hold together:`, list: false },
            { html: `<bdi>مُثْبَتًا</bdi> — positive, not negated.`, list: true, bullet: true },
            { html: `<bdi>مُسْتَقْبَلًا</bdi> — future in reference.`, list: true, bullet: true },
            { html: `<bdi>في جَوابِ قَسَمٍ</bdi> — standing as the answer to an oath.`, list: true, bullet: true },
            { html: `<bdi>غَيْرَ مَفْصُولٍ عن لامِهِ (لامِ القَسَمِ) بِفاصِلٍ</bdi> — not separated from its لام.`, list: true, bullet: true },
            { html: `<bdi>نحو: ﴿وَتَاللَّهِ لَأَكِيدَنَّ أَصْنَامَكُمْ﴾ [الأنبياء: ٥٧]</bdi>`, list: false },
            { html: `All four hold in the شاهد: أَكِيدُ is positive, it refers to what he will do, it answers تاللهِ, and the لام sits immediately before it.`, list: false },
          ],
          clarification: `Keep the four conditions in view, because the sixth state — الممتنع — is defined as their failure. Each one that drops out has a name in that later list: negate the verb and you are in a جواب قسم منفيّ; make it present rather than future and it is حال; put anything between the لام and the verb and it is مفصول من اللام. So the واجب and the ممتنع are two readings of one set of conditions, met or unmet — which is why the باب can move straight from the strongest case to the weakest by simply undoing them one at a time.`,
          exercise: {
            prompt: `A مضارع answers an oath, is future, and follows its لام directly — but it is negated. Where does it fall?`,
            kind: 'mcq',
            options: ['Not in الواجب — one of the four conditions has failed', 'Still in الواجب', 'In الكثير', 'In القليل'],
            correct: 0,
          },
        },
        {
          heading: 'الحالة الثانية: القريب من الواجب',
          lines: [
            { html: `<bdi>ويكونُ قَرِيبًا من الواجِبِ إذا كان شَرْطًا لِإِنِ المُؤَكَّدَةِ بِما الزائِدَةِ، أي (إمَّا) الشَّرْطِيَّة</bdi> — it is قريب من الواجب when it is the شرط of إنْ reinforced with the added ما — that is, إمَّا الشرطية.`, list: false },
            { table: { title: 'شواهد إمَّا الشرطية (Evidence for إمَّا الشرطية)', headers: ['الشاهد (Evidence)', 'السورة (Sūrah)'], rows: [
              ['﴿وَإِمَّا تَخَافَنَّ مِنْ قَوْمٍ خِيَانَةً﴾', 'الأنفال: ٥٨'],
              ['﴿فَإِمَّا نَذْهَبَنَّ بِكَ﴾', 'الزخرف: ٤١'],
              ['﴿فَإِمَّا تَرَيِنَّ مِنَ الْبَشَرِ أَحَدًا فَقُولِي إِنِّي نَذَرْتُ لِلرَّحْمَنِ صَوْمًا﴾', 'مريم: ٢٦'],
            ] } },
            { html: `<bdi>إمَّا</bdi> is <bdi>إِنْ</bdi> الشرطية with the redundant <bdi>ما</bdi> attached to reinforce it — and it is that reinforcement which pulls the نون so close to being required.`, list: false },
          ],
          exercise: {
            prompt: `What is إمَّا الشرطية made of?`,
            kind: 'mcq',
            options: ['إِنْ الشرطية reinforced by the زائدة ما', 'إِنَّ with the ما of negation', 'أَمَّا with a doubled ميم', 'A single indivisible particle'],
            correct: 0,
          },
        },
        {
          heading: 'الحالة الثالثة: الكثير',
          lines: [
            { html: `<bdi>ويكونُ كَثِيرًا إذا وَقَعَ بعد أَداةِ طَلَبٍ</bdi> — it is كثير when it follows an أداة طلب (particle of request), and six of them are named.`, list: false },
            { table: { headers: ['أداة الطلب (Particle of Request)', 'الشاهد (Evidence)'], rows: [
              ['أَمْر (بعد لامِ الأمرِ) — command (after لام الأمر)', 'لِيَقُومَنَّ زَيْدٌ'],
              ['نَهْي — prohibition', '﴿وَلَا تَحْسَبَنَّ اللَّهَ غَافِلًا عَمَّا يَعْمَلُ الظَّالِمُونَ﴾ [إبراهيم: ٤٢]'],
              ['دُعاء — supplication', 'لا يَبْعَدَنْ قَوْمِيَ الَّذِينَ هُمُ ... سَمُّ العُداةِ وآفَةُ الجُزُرِ — لخِرْنِقَ بنتِ هَفَّانَ'],
              ['عَرْض — gentle suggestion', 'هَلَّا تَمُنِنْ بِوَعْدٍ غَيْرَ مُخْلِفَةٍ ... كما عَهِدْتُكِ في أَيَّامِ ذِي سَلَمِ'],
              ['تَمَنٍّ — wishing', 'فَلَيْتَكِ يَوْمَ المُلْتَقَى تَرَيِنَّنِي ... لِكَيْ تَعْلَمِي أَنِّي امْرُؤٌ بِكِ هائِمُ'],
              ['اسْتِفْهام — questioning', 'أَفَبَعْدَ كِنْدَةَ تَمْدَحَنَّ قَبِيلًا'],
            ] } },
            { html: `What unites the six is that each seeks something not yet realised — which is exactly the futurity the نون requires.`, list: false },
          ],
          exercise: {
            prompt: `Why does a طلب make the نون common on the verb after it?`,
            kind: 'mcq',
            options: ['A طلب is always negated', 'A طلب makes the verb مبني', 'A طلب requires a لام', 'A طلب seeks what has not yet happened, which supplies the futurity the نون requires'],
            correct: 3,
          },
        },
      ],
      quiz: [
        {
          q: 'How many states does the مضارع have with respect to نون التوكيد؟',
          options: ['ثلاث', 'ست', 'أربع', 'خمس'],
          correct: 1,
        },
        {
          q: 'A مضارع fixed to الحال:',
          options: ['Its emphasis is obligatory', 'Its emphasis is common', 'Its emphasis is rare', 'نون التوكيد cannot attach at all'],
          correct: 3,
        },
        {
          q: 'How many conditions must hold for توكيد to be واجبًا؟',
          options: ['خمسة', 'اثنان', 'أربعة', 'ثلاثة'],
          correct: 2,
        },
        {
          q: '﴿وَتَاللَّهِ لَأَكِيدَنَّ أَصْنَامَكُمْ﴾ is from which sūra?',
          options: ['الزخرف', 'الأنبياء', 'الأنفال', 'إبراهيم'],
          correct: 1,
        },
        {
          q: 'The verb becomes قريبًا من الواجب when it is the شرط of:',
          options: ['لام القسم', 'إمَّا الشرطية', 'لَمْ', 'لا النافية'],
          correct: 1,
        },
        {
          q: 'The verb becomes كثيرًا when it falls after:',
          options: ['أداة جزاء', 'لَمْ', 'أداة طلب', 'أداة نفي'],
          correct: 2,
        },
      ],
      bank: [
        {
          title: 'ترتيب الحالات',
          kind: 'mcq',
          prompt: 'Which sequence gives the six states in order?',
          options: ['واجب، كثير، قريب من الواجب، قليل، ممتنع، أقلّ', 'كثير، واجب، قليل، أقلّ، قريب من الواجب، ممتنع', 'واجب، قريب من الواجب، كثير، قليل، أقلّ، ممتنع', 'ممتنع، أقلّ، قليل، كثير، قريب من الواجب، واجب'],
          correct: 2,
        },
        {
          title: 'ما يحرك الفعل على السلم',
          kind: 'mcq',
          prompt: 'What determines where a مضارع falls on this scale?',
          options: ['How many letters it has', 'Whether it is مجرد or مزيد', 'Whether it is متعدٍّ', 'How firmly its context fixes it to the future'],
          correct: 3,
        },
        {
          title: 'الأصل في المضارع',
          kind: 'mcq',
          prompt: 'What is the أصل of the مضارع with respect to time, and why does it matter here?',
          options: ['It is fixed to الاستقبال, so the نون always attaches', 'It carries no time at all', 'It is صالح for الحال or الاستقبال, and only the second admits the نون', 'It is fixed to الحال, so the نون never attaches'],
          correct: 2,
        },
        {
          title: 'مثبتًا',
          kind: 'mcq',
          prompt: 'The first condition for وجوب is that the verb be مُثْبَتًا. What does that exclude?',
          options: ['A past verb', 'A verb separated from its لام', 'A verb after a طلب', 'A negated verb'],
          correct: 3,
        },
        {
          title: 'في جواب قسم',
          kind: 'mcq',
          prompt: 'The third condition places the verb where?',
          options: ['After a شرط particle', 'After a طلب', 'After لَمْ', 'As the answer to an oath'],
          correct: 3,
        },
        {
          title: 'غير مفصول',
          kind: 'mcq',
          prompt: 'The fourth condition concerns the لام. What does it require?',
          options: ['That the لام be doubled', 'That the لام follow the verb', 'That nothing come between the لام القسم and the verb', 'That the لام be dropped'],
          correct: 2,
        },
        {
          title: 'لأكيدنَّ',
          kind: 'mcq',
          prompt: 'In ﴿وَتَاللَّهِ لَأَكِيدَنَّ أَصْنَامَكُمْ﴾, which element is the قسم؟',
          options: ['لَأَكِيدَنَّ', 'أَصْنَامَكُمْ', 'The لام', 'وَتَاللَّهِ'],
          correct: 3,
        },
        {
          title: 'الواجب والممتنع',
          kind: 'mcq',
          prompt: 'How does the sixth state relate to the first?',
          options: ['الممتنع requires a fifth condition', 'الممتنع is defined by the failure of the four conditions of الواجب', 'They are unrelated', 'الممتنع is a subset of الواجب'],
          correct: 1,
        },
        {
          title: 'تركيب إمَّا',
          kind: 'mcq',
          prompt: 'إمَّا الشرطية is described as إِنْ المؤكَّدة بما الزائدة. What role does the ما play?',
          options: ['It has no role', 'It reinforces إِنْ, and that reinforcement is what draws the نون', 'It negates إِنْ', 'It makes إِنْ a حرف جر'],
          correct: 1,
        },
        {
          title: 'وإمَّا تخافنَّ',
          kind: 'mcq',
          prompt: '﴿وَإِمَّا تَخَافَنَّ مِنْ قَوْمٍ خِيَانَةً﴾ is from which sūra?',
          options: ['الزخرف', 'مريم', 'إبراهيم', 'الأنفال'],
          correct: 3,
        },
        {
          title: 'فإمَّا نذهبنَّ بك',
          kind: 'mcq',
          prompt: '﴿فَإِمَّا نَذْهَبَنَّ بِكَ﴾ is from which sūra?',
          options: ['الأنفال', 'مريم', 'يوسف', 'الزخرف'],
          correct: 3,
        },
        {
          title: 'فإمَّا ترينَّ',
          kind: 'mcq',
          prompt: '﴿فَإِمَّا تَرَيِنَّ مِنَ الْبَشَرِ أَحَدًا﴾ is from which sūra?',
          options: ['الزخرف', 'الأنبياء', 'مريم', 'الأنفال'],
          correct: 2,
        },
        {
          title: 'ست أدوات',
          kind: 'mcq',
          prompt: 'Which list gives the six أدوات طلب after which the نون is كثير؟',
          options: ['قسم، شرط، نفي، جزاء، عرض، تمنٍّ', 'أمر، نهي، نفي، جزاء، قسم، استفهام', 'دعاء، عرض، تمنٍّ، قسم، شرط، نفي', 'أمر، نهي، دعاء، عرض، تمنٍّ، استفهام'],
          correct: 3,
        },
        {
          title: 'ليقومنَّ زيد',
          kind: 'mcq',
          prompt: 'لِيَقُومَنَّ زَيْدٌ has the نون after which أداة طلب؟',
          options: ['أداة التمني', 'لام الأمر', 'أداة النهي', 'أداة الاستفهام'],
          correct: 1,
        },
        {
          title: 'ولا تحسبنَّ',
          kind: 'mcq',
          prompt: '﴿وَلَا تَحْسَبَنَّ اللَّهَ غَافِلًا﴾ has the نون after which أداة طلب؟',
          options: ['الدعاء', 'الاستفهام', 'النهي', 'الأمر'],
          correct: 2,
        },
        {
          title: 'خرنق بنت هفَّان',
          kind: 'mcq',
          prompt: 'لا يَبْعَدَنْ قَوْمِيَ الَّذِينَ هُمُ … illustrates which أداة طلب؟',
          options: ['النهي', 'العرض', 'التمني', 'الدعاء'],
          correct: 3,
        },
        {
          title: 'هلَّا تمُنِنْ',
          kind: 'mcq',
          prompt: 'هَلَّا تَمُنِنْ بِوَعْدٍ غَيْرَ مُخْلِفَةٍ illustrates which أداة طلب؟',
          options: ['العرض', 'التمني', 'الاستفهام', 'الدعاء'],
          correct: 0,
        },
        {
          title: 'فليتك ترينَّني',
          kind: 'mcq',
          prompt: 'فَلَيْتَكِ يَوْمَ المُلْتَقَى تَرَيِنَّنِي illustrates which أداة طلب؟',
          options: ['الاستفهام', 'التمني', 'العرض', 'الدعاء'],
          correct: 1,
        },
        {
          title: 'أفبعد كندة',
          kind: 'mcq',
          prompt: 'أَفَبَعْدَ كِنْدَةَ تَمْدَحَنَّ قَبِيلًا illustrates which أداة طلب؟',
          options: ['الاستفهام', 'التمني', 'العرض', 'النهي'],
          correct: 0,
        },
        {
          title: 'الجامع بين الأدوات',
          kind: 'mcq',
          prompt: 'What do all six أدوات طلب have in common?',
          options: ['Each negates the verb', 'Each requires a لام', 'Each makes the verb مبني', 'Each seeks something not yet realised, supplying futurity'],
          correct: 3,
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'القليل والأقلّ والممتنع',
      subtitle: 'The Last Three Grades — after لا and ما, after لَمْ and the جزاء particles, and where the نون cannot come at all',
      concepts: [
        {
          heading: 'الحالة الرابعة: القليل',
          lines: [
            { html: `<bdi>ويكونُ قَلِيلًا إذا كان بَعْدَ: (لا) النافِيَةِ، أو (ما) الزائِدَةِ، التي لم تُسْبَقْ بِإِنِ الشَّرْطِيَّةِ</bdi> — it is قليل when it follows لا النافية (the negating لا), or ما الزائدة (the added ما) not preceded by إنْ الشرطية.`, list: false },
            { html: `<bdi>كقولِهِ تعالى: ﴿وَاتَّقُوا فِتْنَةً لَا تُصِيبَنَّ الَّذِينَ ظَلَمُوا مِنْكُمْ خَاصَّةً﴾ [الأنفال: ٢٥]</bdi>.`, list: false },
            { html: `<bdi>وإنَّما أُكِّدَ مع النافي: لأنَّهُ يُشْبِهُ أَداةَ النَهْيِ صُورَةً</bdi> — and it is emphasized with the negator because it resembles the prohibiting particle in form — the negating لا looks exactly like the prohibiting لا, and the resemblance in form is what licenses the نون.`, list: false },
            { html: `<bdi>وقولِهِ: إذا ماتَ مِنْهُم سَيِّدٌ سَرَقَ ابْنُهُ ... ومِنْ عِضَةٍ ما يَنْبُتَنَّ شَكِيرُها</bdi>`, list: false },
          ],
          exercise: {
            prompt: `A نون attaches after لا النافية, though the نون belongs with طلب. What licenses it?`,
            kind: 'mcq',
            options: ['The negating لا resembles the prohibiting لا in form', 'لا النافية is itself a طلب', 'The verb is in the ماضي', 'Nothing — it is شاذ'],
            correct: 0,
          },
        },
        {
          heading: '(ما) الزائدة و(ما) بعد رُبَّ',
          lines: [
            { html: `<bdi>وما زائِدَةٌ في الجَمِيعِ، وشَمَلَ قَوْلُنا (ما) الزائِدَةُ (ما) الواقِعَةَ بعدَ رُبَّ</bdi> — ما is زائدة (added) in all these cases, and our phrase "ما الزائدة" includes the ما that occurs after رُبَّ.`, list: false },
            { html: `<bdi>كقولِ جَذِيمَةَ الأَبْرَشِ: رُبَّما أَوْفَيْتُ في عَلَمٍ ... تَرْفَعَنْ ثَوْبِي شَمالاتُ</bdi>`, list: false },
            { html: `So the ما that follows رُبَّ counts as a زائدة ما for this purpose, and a verb after it may take the نون on the same footing.`, list: false },
          ],
          exercise: {
            prompt: `رُبَّما أَوْفَيْتُ في عَلَمٍ ... تَرْفَعَنْ ثَوْبِي شَمالاتُ. Under which state does تَرْفَعَنْ fall?`,
            kind: 'mcq',
            options: ['الكثير', 'الممتنع', 'القليل — the ما after رُبَّ counts as a زائدة ما', 'الواجب'],
            correct: 2,
          },
        },
        {
          heading: 'الحالة الخامسة: الأقلّ',
          lines: [
            { html: `<bdi>ويكونُ أَقَلَّ إذا كان بعدَ (لَمْ)، وبعدَ أَداةِ جَزاءٍ غَيْرِ (إمَّا)، شَرْطًا كان المُؤَكَّدُ أو جَزاءً</bdi> — it is أقلّ when it follows لَمْ, and when it follows a جزاء particle other than إمّا, whether the emphasized verb is the شرط or the جزاء.`, list: false },
            { table: { headers: ['الحالة (Case)', 'المثال (Example)'], rows: [
              ['بعدَ (لَمْ) — after لَمْ', 'يَحْسَبُهُ الجاهِلُ ما لَمْ يَعْلَمَا ... شَيْخًا عَلَى كُرْسِيِّهِ مُعَمَّمَا — أي يَعْلَمَنْ ، يَصِفُ جَبَلًا'],
              ['بعدَ أَداةِ جَزاءٍ غَيْرِ (إمَّا) — after a جزاء particle other than إمّا', 'مَتَى تَجْتَهِدَنَّ تَنْجَحْ'],
            ] } },
            { html: `The second row shows the نون on the شرط; the rule allows it equally on the جزاء.`, list: false },
            { html: `Note the contrast with the second state: after إمَّا the نون is nearly obligatory, after any other جزاء particle it is the rarest case but one.`, list: false },
          ],
          clarification: `Why does إمَّا stand so far apart from every other جزاء particle? Because of the ما. إِنْ on its own is a plain conditional and does nothing to press the verb towards emphasis; reinforced by the زائدة ما it becomes emphatic itself, and an emphatic particle naturally draws an emphatic verb after it. Strip the ما away and you are back to an ordinary شرط, where the نون is a rarity. That single letter is the whole distance between the second state and the fifth.`,
          exercise: {
            prompt: `ما لَمْ يَعْلَمَا stands for يَعْلَمَنْ. What has happened to the نون؟`,
            kind: 'mcq',
            options: ['The light نون has been turned into an alif at the end of the line', 'The نون has been dropped', 'The نون was never there', 'The نون has become a تنوين'],
            correct: 0,
          },
        },
        {
          heading: 'الحالة السادسة: الممتنع',
          lines: [
            { html: `<bdi>ويكونُ مُمْتَنِعًا إذا انْتَفَتْ شُرُوطُ الواجِبِ، ولم يَكُنْ مِمَّا سَبَقَ</bdi> — three ways that happens:`, list: false },
            { table: { headers: ['الحالة', 'الشاهد'], rows: [
              ['أن يكونَ في جَوابِ قَسَمٍ مَنْفِيٍّ، ولو كان النافي مُقَدَّرًا', 'تاللهِ لا يَذْهَبُ العُرْفُ بينَ اللهِ والناسِ ؛ ﴿تَاللَّهِ تَفْتَؤُ تَذْكُرُ يُوسُفَ﴾ [يوسف: ٨٥] — أي: لا تَفْتَؤُ'],
              ['أن يكونَ حالًا', 'كقراءةِ ابنِ كَثِيرٍ: ﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾ [القيامة]'],
              ['أن يكونَ مَفْصُولًا من اللامِ', '﴿وَلَئِنْ مُتُّمْ أَوْ قُتِلْتُمْ لَإِلَى اللَّهِ تُحْشَرُونَ﴾ [آل عمران: ١٥٨] ؛ ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى﴾ [الضحى: ٥]'],
            ] } },
            { html: `Each of the three undoes one of the four conditions of the first state: the first negates, the second removes futurity, the third breaks the لام's contact with the verb.`, list: false },
            { html: `And the plainest case of all needs no special description: an ordinary مضارع with nothing before it — <bdi>يَذْهَبُ زَيْدٌ</bdi> — is ممتنع simply because none of the five preceding states applies to it.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ﴾, why is the نون barred?`,
            kind: 'mcq',
            options: ['There is no قسم', 'سَوْفَ has come between the لام and the verb', 'The verb is negated', 'The verb refers to the present'],
            correct: 1,
          },
        },
      ],
      quiz: [
        {
          q: 'The نون is قليل after which two things?',
          options: ['إمَّا ولام القسم', 'أداة الطلب والقسم', '(لا) النافية و(ما) الزائدة', '(لَمْ) وأداة الجزاء'],
          correct: 2,
        },
        {
          q: 'Why is the نون tolerated after لا النافية؟',
          options: ['Because it resembles the prohibiting لا in form', 'Because لا is a طلب particle', 'Because the فعل is ماضٍ', 'Because لا is extra (زائدة)'],
          correct: 0,
        },
        {
          q: 'The نون is أقلّ after which two things?',
          options: ['أداة الطلب والدعاء', '(لَمْ) وأداة جزاء غير (إمَّا)', '(لا) النافية و(ما) الزائدة', 'إمَّا ولام القسم'],
          correct: 1,
        },
        {
          q: '﴿تَاللَّهِ تَفْتَؤُ تَذْكُرُ يُوسُفَ﴾ is understood as:',
          options: ['لا تَفْتَؤُ — with a suppressed negative', 'تَفْتَؤَنَّ', 'لَتَفْتَؤُ', 'قد تَفْتَؤُ'],
          correct: 0,
        },
        {
          q: 'ابن كثير’s reading of ﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾ shows which case of امتناع؟',
          options: ['Answering a negated oath', 'Being separated from its لام', 'Following لَمْ', 'Being حال'],
          correct: 3,
        },
        {
          q: '﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى﴾ shows which case of امتناع؟',
          options: ['Being separated from its لام', 'Being حال', 'Being negated', 'Following a جزاء particle'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'قيد (ما) الزائدة',
          kind: 'mcq',
          prompt: 'The fourth state names (ما) الزائدة with a قيد. What is it?',
          options: ['That it not be preceded by إِنْ الشرطية', 'That it follow a قسم', 'That it be doubled', 'That it precede a لام'],
          correct: 0,
        },
        {
          title: 'لا تصيبنَّ',
          kind: 'mcq',
          prompt: '﴿وَاتَّقُوا فِتْنَةً لَا تُصِيبَنَّ الَّذِينَ ظَلَمُوا﴾ is from which sūra?',
          options: ['يوسف', 'الضحى', 'الأنفال', 'إبراهيم'],
          correct: 2,
        },
        {
          title: 'الشبه الصوري',
          kind: 'mcq',
          prompt: 'The نون after لا النافية is licensed by a resemblance. Between what and what?',
          options: ['Between the قسم and the شرط', 'Between the negating لا and the prohibiting لا in form', 'Between the نون and the تنوين', 'Between the مضارع and the أمر'],
          correct: 1,
        },
        {
          title: 'ما ينبتنَّ شكيرها',
          kind: 'mcq',
          prompt: 'In وَمِنْ عِضَةٍ ما يَنْبُتَنَّ شَكِيرُها, what is the ما؟',
          options: ['زائدة', 'نافية', 'موصولة', 'استفهامية'],
          correct: 0,
        },
        {
          title: 'ما بعد رُبَّ',
          kind: 'mcq',
          prompt: 'Does the ما following رُبَّ count as a زائدة ما for this rule?',
          options: ['Yes — it counts as a زائدة ما here', 'No — it is excluded', 'Only in poetry', 'Only if the verb is مثبت'],
          correct: 0,
        },
        {
          title: 'جذيمة الأبرش',
          kind: 'mcq',
          prompt: 'رُبَّما أَوْفَيْتُ في عَلَمٍ ... تَرْفَعَنْ ثَوْبِي شَمالاتُ is attributed to whom?',
          options: ['ابن كثير', 'جَذِيمة الأبرش', 'خِرْنِق بنت هَفَّان', 'رُؤْبَة بن العَجَّاج'],
          correct: 1,
        },
        {
          title: 'شرطًا أو جزاءً',
          kind: 'mcq',
          prompt: 'In the fifth state, where may the emphasised verb stand?',
          options: ['As the شرط only', 'As the جزاء only', 'Neither — only after لَمْ', 'Either as the شرط or as the جزاء'],
          correct: 3,
        },
        {
          title: 'يحسبه الجاهل',
          kind: 'mcq',
          prompt: 'يَحْسَبُهُ الجاهِلُ ما لَمْ يَعْلَمَا is describing what?',
          options: ['A mountain', 'A ruler', 'A camel', 'A tribe'],
          correct: 0,
        },
        {
          title: 'إمَّا وغيرها',
          kind: 'mcq',
          prompt: 'إمَّا puts the verb in the second state; any other جزاء particle puts it in the fifth. What accounts for the gap?',
          options: ['The زائدة ما that makes إِنْ emphatic, which draws an emphatic verb after it', 'إمَّا is a طلب particle', 'إمَّا negates the verb', 'إمَّا requires a لام'],
          correct: 0,
        },
        {
          title: 'تعريف الممتنع',
          kind: 'mcq',
          prompt: 'When is the نون ممتنعًا؟',
          options: ['When the verb answers an oath', 'When the verb follows a طلب', 'When the conditions of الواجب fail and none of the other states applies', 'When the verb is مثبت'],
          correct: 2,
        },
        {
          title: 'جواب قسم منفيّ',
          kind: 'mcq',
          prompt: 'تاللهِ لا يَذْهَبُ العُرْفُ بينَ اللهِ والناسِ. Why is the نون barred?',
          options: ['The verb is in the ماضي', 'There is no لام', 'The verb refers to the present', 'The verb answers an oath but is negated'],
          correct: 3,
        },
        {
          title: 'النافي المقدَّر',
          kind: 'mcq',
          prompt: 'In ﴿تَاللَّهِ تَفْتَؤُ تَذْكُرُ يُوسُفَ﴾ there is no visible negative. Why is the نون still barred?',
          options: ['There is no قسم', 'The negative is مقدَّر — the sense is لا تَفْتَؤُ', 'The verb is separated from its لام', 'The verb is حال'],
          correct: 1,
        },
        {
          title: 'سورة تفتؤ',
          kind: 'mcq',
          prompt: 'From which sūra is ﴿تَاللَّهِ تَفْتَؤُ تَذْكُرُ يُوسُفَ﴾؟',
          options: ['الأنفال', 'القيامة', 'آل عمران', 'يوسف'],
          correct: 3,
        },
        {
          title: 'الفصل باللام',
          kind: 'mcq',
          prompt: 'In ﴿وَلَئِنْ مُتُّمْ أَوْ قُتِلْتُمْ لَإِلَى اللَّهِ تُحْشَرُونَ﴾, what separates the لام from the verb?',
          options: ['سَوْفَ', 'A negative particle', 'Nothing — they are adjacent', 'إِلَى اللَّهِ, a جار ومجرور'],
          correct: 3,
        },
        {
          title: 'سورة تحشرون',
          kind: 'mcq',
          prompt: 'From which sūra is ﴿وَلَئِنْ مُتُّمْ أَوْ قُتِلْتُمْ لَإِلَى اللَّهِ تُحْشَرُونَ﴾؟',
          options: ['الضحى', 'آل عمران', 'الأنفال', 'يوسف'],
          correct: 1,
        },
        {
          title: 'الفاصل في الضحى',
          kind: 'mcq',
          prompt: 'In ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ﴾, what is the فاصل between the لام and the verb?',
          options: ['A جار ومجرور', 'رَبُّكَ', 'There is none', 'سَوْفَ'],
          correct: 3,
        },
        {
          title: 'ثلاث صور للامتناع',
          kind: 'mcq',
          prompt: 'In how many ways may the نون be ممتنعًا؟',
          options: ['خمس', 'ثلاث', 'أربع', 'اثنتان'],
          correct: 1,
        },
        {
          title: 'مقابلة الشروط',
          kind: 'mcq',
          prompt: 'Each of the three cases of امتناع undoes one condition of الواجب. Which one does حالًا undo?',
          options: ['غير مفصول عن لامه', 'مستقبلًا', 'مثبتًا', 'في جواب قسم'],
          correct: 1,
        },
        {
          title: 'قراءة ابن كثير',
          kind: 'mcq',
          prompt: 'ابن كثير’s reading of ﴿لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ﴾ makes the verb:',
          options: ['مستقبلًا, so the نون is required', 'منفيًّا, so the نون is قليل', 'مفصولًا من اللام', 'حالًا, so the نون is barred'],
          correct: 3,
        },
        {
          title: 'سلم الحالات',
          kind: 'mcq',
          prompt: 'Ranking the six states from most to least admitting of the نون, which comes third from the bottom?',
          options: ['الأقلّ', 'الممتنع', 'القليل', 'الكثير'],
          correct: 2,
        },
      ],
    },
  ],
};
