// Module 01 — المقدمة والميزان الصرفي (The Introduction and the Morphological Scale)
//
// Covers Weeks 1–2 of the Advanced Sarf course: خطبة الكتاب and الميزان
// الصرفي, i.e. the opening of شذا العرف في فن الصرف by أحمد الحملاوي.
// Definitions, examples and شواهد are kept faithful to the source. Concept
// bodies are short by design (a sentence or two, not teaching prose);
// quiz/bank question text is English with Arabic morphological terms left in
// Arabic.
//
// Scope: the مبادئ of علم الصرف (definition, subject, scope, founder, fruit,
// source, ruling), تقسيم الكلمة with علامات الأسماء والأفعال, and الميزان
// الصرفي in full — وزن الثلاثي, وزن ما زاد على ثلاثة أحرف, and the special
// cases of إبدال، حذف and قلب مكاني. The seven تقسيمات of الفعل begin in
// Module 02.
//
// 2026-08-12: restructured to match content/module-01.js's (Advanced Nahw)
// revamped presentation style, per explicit instruction — same facts,
// counts, and lesson/concept boundaries, no new grammar content. Every
// concept-level formal definition or rule that previously sat as unboxed
// prose now gets its own inline Definition/Careful/Rule box (Arabic
// capsule statement + English explanation alongside it in `lines`),
// matching how content/module-01.js boxes up its own standalone claims
// rather than leaving them as plain prose. The two `clarification` fields
// this module carried (a pre-revamp field content/module-01.js's 22
// concepts use zero times) were folded into their concept's `lines` as a
// Careful box plus ordinary prose, the same distillation COURSE-MAP.md
// documents for Modules 02/14 of the Nahw revamp: "state the point in
// English prose... distilled into a short Arabic box statement... with the
// full English explanation kept in the surrounding prose." Every new
// Arabic box line is built only from terms and phrases already present
// verbatim in this file's own prose (`هَيْئَةُ الكَلِمَةِ المَلْحُوظَة`,
// `صُورِيٌّ لا حَقِيقِيٌّ`, `نَظَرًا إلى الأصل`, etc.) or a standard,
// universally-attested صرف formula already paraphrased in the surrounding
// English (e.g. الصرف لغة: التغيير) — nothing new was invented. Tables and
// bullet lists that were already enumerative (the four مبادئ, the three
// أقسام الكلمة, the fائدة الميزان list) are left as-is: content/module-01.js
// itself leaves purely enumerative concepts unboxed the same way.

export default {
  id: 'as-01',
  title: 'المقدمة والميزان الصرفي',
  heading: 'مقدمة',
  blurb: 'The foundations of علم الصرف: what it is, what it applies to, and الميزان الصرفي — how any word is weighed against ف ع ل.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'تعريف علم الصرف',
      subtitle: 'Defining the Science — الصرف in language and in technical use, its subject, its scope, and the مبادئ that frame it',
      concepts: [
        {
          heading: 'الصرف لغةً واصطلاحًا',
          lines: [
            { html: `<bdi>الصَّرْف</bdi> — also called <bdi>التَّصْرِيف</bdi> — means change in the language itself.`, list: false },
            { box: { title: 'Definition', lines: [`الصَّرْفُ لُغَةً: التَّغْيِيرُ`] } },
            { html: `The same sense sits behind <bdi>تَصْرِيفُ الرِّيَاح</bdi>, the turning of the winds, i.e. <bdi>تَغْيِيرُهَا</bdi>.`, list: false },
            { html: `Technically it carries two definitions, one describing the activity and one describing the discipline.`, list: false },
            { table: { title: 'The Two Technical Senses', headers: ['Sense', 'Definition', 'Illustration'], rows: [
              ['بالمعنى العَمَلي', 'turning the one أصل into different أمثلة, for intended meanings that cannot be reached any other way', 'اسْمَا الفَاعِلِ والمَفْعُولِ، اسْمُ التَّفْضِيلِ، التَّثْنِيَةُ، الجَمْعُ'],
              ['بالمعنى العِلْمي', 'a body of أصول by which the أحوال of أبنية الكلمة are known — those states which are neither إعراب nor بناء', '—'],
            ] } },
            { html: `That closing exclusion is the boundary line with النحو: إعراب and بناء belong to النحو, and everything else about a word's shape belongs here.`, list: false },
          ],
          exercise: {
            prompt: `Which of these is the definition of الصرف بالمعنى العِلْمي؟`,
            kind: 'mcq',
            options: ['Turning the one أصل into different أمثلة, for intended meanings', 'A body of أصول by which the أحوال of أبنية الكلمة are known', 'التَّغْيِير — change, as in تَصْرِيفُ الرِّيَاح', 'Guarding the tongue from error in vocabulary'],
            correct: 1,
          },
        },
        {
          heading: 'موضوعه وما يختص به',
          lines: [
            { box: { title: 'Definition', lines: [`مَوْضُوعُ الصَّرْفِ: الأَلْفَاظُ العَرَبِيَّةُ مِنْ حَيْثُ الصِّحَّةِ وَالإِعْلَالِ وَالأَصَالَةِ وَالزِّيَادَةِ وَنَحْوِهَا`] } },
            { html: `<bdi>مَوْضُوعُه</bdi> — its subject matter — is <bdi>الأَلْفَاظُ العَرَبِيَّة</bdi>, but only from the angle of those أحوال: <bdi>الصِّحَّة والإعْلَال</bdi>, <bdi>الأَصَالَة والزِّيَادَة</bdi>, and their like.`, list: false },
            { html: `It applies to two classes of word only:`, list: false },
            { html: `<bdi>الأَسْمَاء المُتَمَكِّنَة</bdi> — nouns that decline.`, list: true, bullet: true },
            { html: `<bdi>الأَفْعَال المُتَصَرِّفَة</bdi> — verbs that conjugate.`, list: true, bullet: true },
            { box: { title: 'Careful', lines: [`مَا يُذْكَرُ مِنْ تَثْنِيَةِ وَجَمْعِ وَتَصْغِيرِ بَعْضِ الأَسْمَاءِ المَوْصُولَةِ وَالإِشَارَةِ: صُورِيٌّ لَا حَقِيقِيٌّ`] } },
            { html: `What is reported of the تَثْنِيَة, جَمْع and تَصْغِير of certain <bdi>أسماء موصولة</bdi> and <bdi>أسماء إشارة</bdi> is formal in appearance only, not a genuine صرف operation on a مُتَمَكِّن noun.`, list: false },
          ],
          exercise: {
            prompt: `اللَّذَانِ looks like the dual of الَّذِي, yet الَّذِي is an اسم موصول — a مبني word, not مُتَمَكِّن. How is this تثنية classified?`,
            kind: 'mcq',
            options: ['It is an إعلال, not a تثنية', 'صُورِيٌّ لا حَقِيقِيٌّ', 'حَقِيقِيٌّ, since the form genuinely changed', 'It falls under النحو, not الصرف, because it is مبني'],
            correct: 1,
          },
        },
        {
          heading: 'الواضع والثمرة والاستمداد والحكم',
          lines: [
            { html: `The remaining مبادئ are given briefly and are worth memorising as a block.`, list: false },
            { table: { title: 'مبادئ علم الصرف (The Principles of علم الصرف)', headers: ['المبدأ (Principle)', 'What it is'], rows: [
              ['الوَاضِع (its founder)', 'مُعَاذ بن مُسْلِم الهَرَّاء — with a shadda on the راء; and it is said, سَيِّدُنا عليٌّ كرَّم الله وجهه (our master عَلِيّ, may الله ennoble his face)'],
              ['الثَّمَرَة (its fruit)', 'Guarding the tongue from error in مُفْرَدَات (individual words), and observing the rules of the language in writing'],
              ['الاسْتِمْدَاد (its source)', 'From the speech of الله تعالى, the speech of His Messenger ﷺ, and the speech of the العرب'],
              ['حُكْمُ الشَّارِعِ فيه (the Lawgiver’s ruling on it)', 'الوُجُوبُ الكِفَائي — a communal obligation (binding on the community as a whole, lifted from the rest once some undertake it)'],
            ] } },
            { html: `Note the division of labour the ثمرة implies: النحو guards the end of the word against error, while الصرف guards the word itself — its <bdi>مُفْرَدَات</bdi>.`, list: false },
          ],
          exercise: {
            prompt: `The حكم of studying الصرف is الوجوب الكفائي. What does that mean in practice?`,
            kind: 'mcq',
            options: ['It is recommended but never obligatory', 'It is obligatory only on those who already know النحو', 'Every individual Muslim is obliged to learn it', 'It is obligatory on the community, and lifted from the rest once some undertake it'],
            correct: 3,
          },
        },
        {
          heading: 'الأبنية والكلمة',
          lines: [
            { html: `<bdi>الأَبْنِيَة</bdi> is the plural of <bdi>بِنَاء</bdi>, the observable shape of a word. Four things make it up.`, list: false },
            { box: { title: 'Definition', lines: [`البِنَاءُ: هَيْئَةُ الكَلِمَةِ المَلْحُوظَةُ`] } },
            { html: `<bdi>حَرَكَة</bdi> — the vowels it carries.`, list: true, bullet: true },
            { html: `<bdi>سُكُون</bdi> — where it carries none.`, list: true, bullet: true },
            { html: `<bdi>عَدَدُ الحُرُوف</bdi> — how many letters it has.`, list: true, bullet: true },
            { html: `<bdi>التَّرْتِيب</bdi> — the order those letters come in.`, list: true, bullet: true },
            { box: { title: 'Definition', lines: [`الكَلِمَةُ: لَفْظٌ مُفْرَدٌ وَضَعَهُ الوَاضِعُ لِيَدُلَّ عَلَى مَعْنًى`] } },
            { html: `<bdi>الكَلِمَة</bdi> is a <bdi>لَفْظٌ مُفْرَد</bdi> which الواضع laid down to indicate a meaning, such that whenever that لفظ is uttered, the meaning assigned to it is understood from it.`, list: false },
          ],
          exercise: {
            prompt: `عَلِمَ and عُلِمَ have the same letters in the same order and the same count. Given the four things that make up a بناء, do they share one بناء؟`,
            kind: 'mcq',
            options: ['No — الحركة والسكون are part of the بناء, so they differ', 'No — but only because one is معلوم and the other مجهول, which is a نحو matter', 'Yes — a difference in حركة changes الإعراب, not البناء', 'Yes — بناء is fixed by the letters and their order alone'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What does الصرف mean لغةً؟',
          options: ['التغيير', 'التركيب', 'التقدير', 'التقسيم'],
          correct: 0,
        },
        {
          q: 'What does the expression تصريف الرياح establish about الصرف؟',
          options: ['That الصرف is مستمد from كلام العرب', 'That the ميزان is built on ف ع ل', 'That الصرف applies to الأسماء المتمكنة', 'That الصرف لغةً means التغيير'],
          correct: 3,
        },
        {
          q: 'The المعنى العلمي definition ends with التى ليست بإعراب ولا بناء. What is that clause doing?',
          options: ['Excluding المبني nouns from الصرف', 'Marking off the territory of النحو from that of الصرف', 'Excluding the حروف from الصرف', 'Restricting الصرف to the ثلاثي word'],
          correct: 1,
        },
        {
          q: 'Which pair does الصرف actually operate on?',
          options: ['الأسماء والحروف', 'الأسماء المتمكنة والأفعال المتصرفة', 'الأسماء المبنية والأفعال الجامدة', 'الأسماء الموصولة وأسماء الإشارة'],
          correct: 1,
        },
        {
          q: 'Who is named as واضع علم الصرف؟',
          options: ['أحمد الحملاوي', 'أبو الأسود الدؤلي', 'الخليل بن أحمد الفراهيدي', 'معاذ بن مسلم الهراء'],
          correct: 3,
        },
        {
          q: 'الأبنية is the plural of بناء. Which list gives what a بناء is made of?',
          options: ['أصالة، زيادة، حذف، قلب', 'فاء الكلمة، عين الكلمة، لام الكلمة', 'حركة، سكون، عدد الحروف، ترتيب', 'إعراب، بناء، صحة، إعلال'],
          correct: 2,
        },
      ],
      bank: [
        {
          title: 'المعنى العملي',
          kind: 'mcq',
          prompt: 'Which set of forms is given to illustrate what the العملي definition produces?',
          options: ['الصحيح، المعتل، المهموز، المضعف', 'المبتدأ، الخبر، الفاعل، المفعول', 'اسم الفاعل، اسم المفعول، اسم التفضيل، التثنية، الجمع', 'المرفوع، المنصوب، المجرور، المجزوم'],
          correct: 2,
        },
        {
          title: 'العملي أم العلمي؟',
          kind: 'mcq',
          prompt: 'Deriving مَكْتُوب from كَتَبَ is an instance of الصرف in which sense?',
          options: ['بالمعنى العلمي', 'بالمعنى العملي', 'Neither — it is a نحو operation', 'Both equally'],
          correct: 1,
        },
        {
          title: 'التصريف',
          kind: 'mcq',
          prompt: 'What is the relationship between الصرف and التصريف؟',
          options: ['التصريف is the practical sense, الصرف the theoretical', 'They are two names for the same science', 'التصريف is a sub-topic within الصرف', 'الصرف is the لغوي meaning, التصريف the اصطلاحي'],
          correct: 1,
        },
        {
          title: 'لمعان مقصودة',
          kind: 'mcq',
          prompt: 'The العملي definition adds لا تحصُل إلا بها. What does that clause claim?',
          options: ['The intended meanings can only be reached through these derived forms', 'The derived forms occur only in كلام العرب', 'Only المتمكن nouns yield such forms', 'The meanings are known only by السماع'],
          correct: 0,
        },
        {
          title: 'موضوع الصرف',
          kind: 'mcq',
          prompt: 'الألفاظ العربية are the موضوع of الصرف — but من حيث what?',
          options: ['من حيث إعرابها وبنائها', 'من حيث تلك الأحوال، كالصحة والإعلال والأصالة والزيادة', 'من حيث معانيها المقصودة', 'من حيث موقعها من الجملة'],
          correct: 1,
        },
        {
          title: 'الصحة والإعلال',
          kind: 'mcq',
          prompt: 'الصحة والإعلال and الأصالة والزيادة are named as examples of what?',
          options: ['مبادئ العلم', 'علامات الأسماء', 'أقسام الكلمة', 'الأحوال that الصرف studies a word from the angle of'],
          correct: 3,
        },
        {
          title: 'الفعل الجامد',
          kind: 'mcq',
          prompt: 'عَسَى is a فعل جامد — it does not conjugate. Does it fall within what الصرف operates on?',
          options: ['Yes, but only for its ميزان', 'No — because it is سماعي', 'Yes — every فعل is within الصرف', 'No — الصرف takes الأفعال المتصرفة, not الجامدة'],
          correct: 3,
        },
        {
          title: 'الاسم المبني',
          kind: 'mcq',
          prompt: 'هَذَا is an اسم إشارة, and so مبني rather than متمكن. What follows?',
          options: ['It is outside the two classes الصرف operates on', 'It is included, since it is still an اسم', 'It is included, but only under الإعلال', 'It is treated as a حرف for صرف purposes'],
          correct: 0,
        },
        {
          title: 'صوري لا حقيقي',
          kind: 'mcq',
          prompt: 'Which operations are described as صوري لا حقيقي؟',
          options: ['The تثنية, جمع and تصغير of some أسماء موصولة and أسماء إشارة', 'The اسم الفاعل and اسم المفعول of the ثلاثي', 'الإعلال and الإبدال in the معتل verb', 'The جمع of the اسم المتمكن'],
          correct: 0,
        },
        {
          title: 'الحرف والصرف',
          kind: 'mcq',
          prompt: 'Given that الصرف يختص بالأسماء المتمكنة والأفعال المتصرفة, on what ground does الحرف fall outside it?',
          options: ['Because it has no ميزان', 'Because its meaning is غير مستقل بالفهم', 'Because it neither declines nor conjugates, so it is neither متمكن nor متصرف', 'Because it carries no زوائد'],
          correct: 2,
        },
        {
          title: 'ثمرة العلم',
          kind: 'mcq',
          prompt: 'What is the ثمرة of علم الصرف؟',
          options: ['Understanding the speech of الله and His Messenger', 'Knowing the observable أبنية of the word', 'Guarding the tongue from error in الإعراب', 'Guarding the tongue from error in vocabulary, and observing the rules of the language in writing'],
          correct: 3,
        },
        {
          title: 'صرف أم نحو؟',
          kind: 'mcq',
          prompt: 'A speaker says يَكْتُبُونَ when the correct form is يَكْتُبُوا after لَنْ. Which science guards against that specific error?',
          options: ['النحو, since the error is in الإعراب at the end of the word', 'Both equally', 'Neither — it is a matter of سماع', 'الصرف, since the word’s form changed'],
          correct: 0,
        },
        {
          title: 'الاستمداد',
          kind: 'mcq',
          prompt: 'From what three sources is علم الصرف drawn?',
          options: ['كلام العرب، والقياس، والاستحسان', 'القرآن، وأشعار العرب، وأقوال النحاة', 'كلام الله، وكلام رسوله ﷺ، وكلام العرب', 'القرآن، والحديث، والإجماع'],
          correct: 2,
        },
        {
          title: 'فرض عين أم كفاية؟',
          kind: 'mcq',
          prompt: 'A community has a number of scholars who have mastered الصرف. What is the ruling on the rest of that community learning it?',
          options: ['It was never واجب on anyone to begin with', 'It remains واجب on each of them', 'The obligation is lifted from them, since the حكم is الوجوب الكفائي', 'It becomes حرام for them'],
          correct: 2,
        },
        {
          title: 'سيدنا علي',
          kind: 'mcq',
          prompt: 'In what capacity is سيدنا علي كرم الله وجهه mentioned?',
          options: ['As the source of the ميزان الصرفي', 'As the one who named the letters فاء وعين ولام الكلمة', 'As the transmitter of حروف الزيادة', 'As the واضع of الصرف, on one reported view'],
          correct: 3,
        },
        {
          title: 'الحركة والسكون',
          kind: 'mcq',
          prompt: 'كَتَبَ (he wrote) and كُتِبَ (it was written) have the same letters, in the same order, the same count. Given the four things that make up a بناء, do they share one بناء؟',
          options: ['Yes — بناء is fixed by the letters and their order alone', 'No — الحركة differs between the two, and حركة is part of the بناء', 'Yes, since both are ثلاثي مجرد', 'No — but only because one is مبني للمجهول, which is a نحو matter'],
          correct: 1,
        },
        {
          title: 'هيئة الكلمة',
          kind: 'mcq',
          prompt: 'البناء is defined as هيئة الكلمة الملحوظة. What does الملحوظة add?',
          options: ['That it is estimated rather than pronounced', 'That it is fixed by السماع', 'That it excludes the زوائد', 'That it is the shape actually observable in the word'],
          correct: 3,
        },
        {
          title: 'عدد الحروف',
          kind: 'mcq',
          prompt: 'كَتَبَ and اكْتَتَبَ share the same three أصول in the same order. Do they share one بناء؟',
          options: ['No — عدد الحروف differs, and that is part of the بناء', 'No — but only because one is مزيد', 'Yes, since the زوائد are not counted in the بناء', 'Yes — the أصول are what fixes the بناء'],
          correct: 0,
        },
        {
          title: 'الترتيب',
          kind: 'mcq',
          prompt: 'Which of the four components of البناء distinguishes جَبَذَ from جَذَبَ؟',
          options: ['عدد الحروف', 'الترتيب', 'الحركة', 'السكون'],
          correct: 1,
        },
        {
          title: 'لفظ مفرد',
          kind: 'mcq',
          prompt: 'الكلمة is defined as لفظ مفرد وضعه الواضع ليدل على معنى. What does مفرد rule out?',
          options: ['A لفظ carrying no meaning at all', 'A لفظ that is مبني', 'A لفظ whose meaning is tied to time', 'A لفظ built from more than one meaningful word'],
          correct: 3,
        },
        {
          title: 'وضعه الواضع',
          kind: 'mcq',
          prompt: 'The definition of الكلمة requires that the meaning be understood متى ذُكر ذلك اللفظ. What is that condition securing?',
          options: ['That the word carries a زمن', 'That the assignment of the word to its meaning is settled, not occasional', 'That the word must be مفرد', 'That the word must be عربي'],
          correct: 1,
        },
        {
          title: 'مبادئ العلم',
          kind: 'mcq',
          prompt: 'Which of these is NOT among the مبادئ listed for الصرف؟',
          options: ['الموضوع', 'الواضع', 'الثمرة', 'المسائل والدلائل'],
          correct: 3,
        },
        {
          title: 'حد الصرف والنحو',
          kind: 'mcq',
          prompt: 'A word’s final letter changes from ضمة to فتحة because a ناصب entered upon it. Which science owns that change?',
          options: ['Neither', 'الصرف, since the word’s form changed', 'النحو — it is إعراب, which the علمي definition expressly excludes', 'Both, since the بناء includes الحركة'],
          correct: 2,
        },
        {
          title: 'أحوال الأبنية',
          kind: 'mcq',
          prompt: 'A word’s واو turns into an ألف, as in قَوَلَ becoming قَالَ. Which science owns that change?',
          options: ['Neither, since the meaning did not change', 'الصرف, but only in the ميزان', 'النحو, since a حركة is involved', 'الصرف — it is إعلال, one of the أحوال أبنية الكلمة'],
          correct: 3,
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'تقسيم الكلمة وعلاماتها',
      subtitle: 'The Three Classes — اسم, فعل and حرف, and the signs that tell them apart in practice',
      concepts: [
        {
          heading: 'أقسام الكلمة الثلاثة',
          lines: [
            { box: { title: 'Core Text', lines: [
              `تَنْقَسِمُ الكَلِمَةُ إلى اسْمٍ وفِعْلٍ وحَرْفٍ`,
            ] } },
            { html: `The كلمة divides into اسم, فعل and حرف. Three classes, and no fourth.`, list: false },
            { table: { title: 'The Three Divisions', headers: ['القسم (Class)', 'What it was coined to indicate', 'أمثلة (Examples)'], rows: [
              ['الاسْم', 'A meaning independently understood (مستقلّ بالفهم), with time not part of it', 'رَجُل، كِتَاب'],
              ['الفِعْل', 'A meaning independently understood, with time part of it', 'كَتَبَ، يَقْرَأُ، احْفَظْ'],
              ['الحَرْف', 'A meaning not independently understood on its own', 'هَلْ، فِي، لَمْ'],
            ] } },
            { html: `Two tests run through all three: does the meaning stand on its own in the mind (<bdi>الاسْتِقْلَال بِالفَهْم</bdi>), and is time built into it? الاسم and الفعل both pass the first and split on the second; الحرف fails the first outright.`, list: false },
            { html: `Of الحرف one thing more is added:`, list: false },
            { box: { title: 'Core Text', lines: [
              `ولا دَخْلَ لَهُ هُنَا كما مَرَّ`,
            ] } },
            { html: `It has no place in علم الصرف at all — which is why the two lists of علامات that follow cover only الاسم and الفعل.`, list: false },
          ],
          exercise: {
            prompt: `احْفَظْ is a فعل. Since it is a command, what is the زمن that is جزء of its meaning?`,
            kind: 'mcq',
            options: ['The زمن is present but مقدر, so it does not count', 'No زمن — it is an اسم فعل', 'الاستقبال — the action is sought after the moment of speaking', 'الماضي'],
            correct: 2,
          },
        },
        {
          heading: 'علامات الأسماء',
          lines: [
            { html: `A word is an اسم if it accepts any <em>one</em> of six things.`, list: false },
            { html: `<bdi>قَبُولُ حَرْفِ الجَرِّ</bdi>`, list: true, bullet: true },
            { html: `<bdi>أَلْ</bdi>`, list: true, bullet: true },
            { html: `<bdi>لُحُوقُ التَّنْوِينِ</bdi> له`, list: true, bullet: true },
            { html: `<bdi>الإِضَافَة</bdi>`, list: true, bullet: true },
            { html: `<bdi>الإِسْنَادُ إليه</bdi>`, list: true, bullet: true },
            { html: `<bdi>النِّدَاء</bdi>`, list: true, bullet: true },
            { html: `The first شاهد shows several of them at once — praise be to الله, originator of creation from non-existence:`, list: false },
            { box: { title: 'Core Text', lines: [
              `الحَمْدُ لِلَّهِ مُنْشِئ الخَلْقَ مِنْ عَدَمِ`,
            ] } },
            { table: { headers: ['الكلمة', 'العلامة'], rows: [
              ['الحَمْدُ', 'أَلْ — and it is also مُسْنَدٌ إليه'],
              ['لِلَّهِ', 'preceded by حرف الجر (اللام)'],
              ['عَدَمِ', 'مجرور by مِنْ — an instance of قَبُولُ حرف الجر, accepting the حرف الجر'],
            ] } },
            { html: `مُنْشِئ here is an اسم فاعل governing الخَلْقَ as its مفعول به, and عَدَمِ stands in pause, so its تنوين is not sounded.`, list: false },
            { html: `A second شاهد supplies the two signs the first left out — O Ibrāhīm, you have already fulfilled the vision:`, list: false },
            { box: { title: 'Core Text', lines: [
              `﴿يَا إِبْرَاهِيمُ ۝ قَدْ صَدَّقْتَ الرُّؤْيَا﴾`,
            ] } },
            { html: `النداء in يا إبراهيمُ, and أل in الرُّؤْيَا.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿يَا إِبْرَاهِيمُ﴾, إبراهيم takes neither أل nor تنوين nor a حرف جر. On what ground is it still known to be an اسم؟`,
            kind: 'mcq',
            options: ['النداء — it is مُنَادًى, and only an اسم is called upon', 'الإسناد إليه', 'الإضافة', 'It is not established as an اسم from this شاهد'],
            correct: 0,
          },
        },
        {
          heading: 'علامات الأفعال',
          lines: [
            { html: `A word is a فعل if it accepts any one of eight signs. All but one of them have a قرآني شاهد below.`, list: false },
            { table: { title: 'The Eight Signs of الفعل', headers: ['العلامة', 'الشاهد'], rows: [
              ['قَدْ', '﴿قَدْ أَفْلَحَ مَنْ تَزَكَّى﴾ [الأعلى: ١٤]'],
              ['السِّين (وسوف)', '﴿سَنُقْرِئُكَ فَلَا تَنْسَى﴾ [الأعلى: ٦] ، ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى﴾ [الضحى: ٥]'],
              ['النَّوَاصِب', '﴿لَنْ تَنَالُوا الْبِرَّ حَتَّى تُنْفِقُوا مِمَّا تُحِبُّونَ﴾ [آل عمران: ٩٢]'],
              ['الجَوَازِم', '﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾ [الإخلاص: ٣]'],
              ['تَاءُ الفَاعِل', '﴿رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَحْمَةً وَعِلْمًا﴾ [غافر: ٧] ، ﴿أَجْرَ مَا سَقَيْتَ لَنَا﴾ [القصص: ٢٥]'],
              ['تَاءُ التَّأْنِيثِ السَّاكِنَة', '— listed among the signs, but with no شاهد cited for it'],
              ['نُونُ التَّوْكِيد', '﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾ [يوسف: ٣٢]'],
              ['يَاءُ المُخَاطَبَة', '﴿ارْجِعِي إِلَى رَبِّكِ رَاضِيَةً مَرْضِيَّةً﴾ [الفجر: ٢٨]'],
            ] } },
            { html: `Read against their meanings: he has certainly succeeded, who purifies himself (قَدْ); We shall make you recite, and you will not forget, and your Lord will surely give to you and you will be satisfied (السين and سوف); you will never attain righteousness until you spend from what you love (لَنْ); He neither begets nor is begotten (لَمْ); Our Lord, You have encompassed all things in mercy and knowledge, and the wage for what you gave to drink for us (تاء الفاعل, twice); return to your Lord, well-pleased and pleasing (ياء المخاطبة).`, list: false },
            { html: `﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾ — he shall certainly be imprisoned, and shall certainly be among the debased — is worth pausing on: it carries both نونان at once — the heavy مشددة on يُسْجَنَنَّ, and the light one written as an alif on وَلَيَكُونًا.`, list: false },
          ],
          exercise: {
            prompt: `In ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى﴾, which element establishes يُعْطِي as a فعل؟`,
            kind: 'mcq',
            options: ['اللام in ولسوف', 'سَوْفَ, which belongs with السين among علامات الفعل', 'The كاف of يُعْطِيكَ', 'رَبُّكَ, since it is مسند إليه'],
            correct: 1,
          },
        },
        {
          heading: 'ما يميز الحرف',
          lines: [
            { html: `الحرف has no sign of its own. It is identified purely by exclusion:`, list: false },
            { box: { title: 'Core Text', lines: [
              `ويَخْتَصُّ الحَرْفُ بِعَدَمِ قَبُولِ شيءٍ من خَصَائِصِ الاسمِ والفعلِ`,
            ] } },
            { html: `The حرف is marked out by accepting none of the features distinctive of الاسم or الفعل. So the procedure is elimination. Run the six علامات الأسماء, then the eight علامات الأفعال. A word that takes nothing from either list is a حرف.`, list: false },
            { html: `This is also why the section on الحرف closes almost as soon as it opens — there are no signs to list. Every one of the fourteen signs is an effect of a meaning standing on its own: you can only prefix أل to something with an independent referent, only call upon a named thing, only put a زمن-bearing word after قَدْ. الحرف has no such independent meaning by definition, so nothing in either list can attach to it.`, list: false },
            { box: { title: 'Careful', lines: [`لَا يُخْتَبَرُ الحَرْفُ مُبَاشَرَةً، بَلْ يُخْتَبَرُ الاسْمُ ثُمَّ الفِعْلُ، وَمَا سَلِمَ مِنْهُمَا فَحَرْفٌ`] } },
            { html: `In practice you never test for حرف directly. You test for اسم, then for فعل, and what survives both is حرف.`, list: false },
          ],
          exercise: {
            prompt: `A student wants a positive test that proves a word is a حرف, on the pattern of أل for الاسم. What is there?`,
            kind: 'mcq',
            options: ['قبول حروف الجر', 'عدم قبول شيء من خصائص الاسم والفعل — there is no positive sign', 'عدم الاستقلال بالفهم, tested directly', 'قبول أل ونفي التنوين'],
            correct: 1,
          },
        },
      ],
      quiz: [
        {
          q: 'What separates الاسم from الفعل in the definitions given?',
          options: ['Whether the word accepts أل', 'Whether the word is متمكن', 'Whether the meaning is مستقل بالفهم', 'Whether الزمن is part of the meaning'],
          correct: 3,
        },
        {
          q: 'How many علامات does الاسم have?',
          options: ['خمس', 'ست', 'ثمان', 'أربع'],
          correct: 1,
        },
        {
          q: 'Which of these is NOT among علامات الأفعال as listed?',
          options: ['أَلْ', 'نون التوكيد', 'قَدْ', 'النواصب والجوازم'],
          correct: 0,
        },
        {
          q: 'Which علامة does ﴿ارْجِعِي إِلَى رَبِّكِ﴾ display?',
          options: ['الجوازم', 'ياء المخاطبة', 'تاء الفاعل', 'نون التوكيد'],
          correct: 1,
        },
        {
          q: 'Which علامة does ﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾ display?',
          options: ['الجوازم', 'قَدْ', 'السين', 'النواصب'],
          correct: 0,
        },
        {
          q: 'How is a حرف identified?',
          options: ['By carrying no تنوين', 'By its meaning being tied to time', 'By accepting حروف الجر', 'By accepting neither اسم nor فعل signs'],
          correct: 3,
        },
      ],
      bank: [
        {
          title: 'استقلال بالفهم',
          kind: 'mcq',
          prompt: 'What do الاسم and الفعل share that الحرف lacks?',
          options: ['A معنى مستقل بالفهم', 'قبول أل', 'قبول النواصب', 'الزمن as part of the meaning'],
          correct: 0,
        },
        {
          title: 'رجل وكتاب',
          kind: 'mcq',
          prompt: 'رَجُل and كِتَاب are both أسماء. What do they demonstrate?',
          options: ['That they are متمكن', 'A معنى مستقل بالفهم with no زمن as part of it', 'A معنى مستقل بالفهم with a زمن', 'Acceptance of النواصب'],
          correct: 1,
        },
        {
          title: 'كَتَبَ ويقرأ واحفظ',
          kind: 'mcq',
          prompt: 'Why are three examples given for الفعل rather than one?',
          options: ['To cover اللازم and المتعدي', 'To cover المجرد and المزيد', 'To cover الماضي، المضارع and الأمر', 'To cover الصحيح، المعتل and المهموز'],
          correct: 2,
        },
        {
          title: 'هَلْ وفى ولَم',
          kind: 'mcq',
          prompt: 'هَلْ, فِي and لَمْ are all حروف. What do the three have in common?',
          options: ['They all carry a زمن as part of their meaning', 'Their meaning is غير مستقل بالفهم', 'They all enter upon الفعل', 'They all accept أل'],
          correct: 1,
        },
        {
          title: 'ولا دخل له هنا',
          kind: 'mcq',
          prompt: 'The definition of الحرف is followed by the remark ولا دخل له هنا. What does هنا refer to?',
          options: ['باب علامات الأسماء', 'The chapter on الميزان', 'علم الصرف', 'علم النحو'],
          correct: 2,
        },
        {
          title: 'الحمد لله',
          kind: 'mcq',
          prompt: 'In الحمدُ لله منشئ الخلقَ من عَدَمِ, which word shows قبول حرف الجر؟',
          options: ['الخَلْقَ', 'منشئ — it is مضاف', 'عَدَمِ — it is مجرور بمِنْ, and لله is مجرور باللام', 'الحمدُ'],
          correct: 2,
        },
        {
          title: 'منشئ الخلق',
          kind: 'mcq',
          prompt: 'In منشئ الخلقَ, what is الخَلْقَ؟',
          options: ['مفعول به of the اسم فاعل مُنْشِئ', 'فاعل', 'حال', 'مضاف إليه'],
          correct: 0,
        },
        {
          title: 'الإسناد إليه',
          kind: 'mcq',
          prompt: 'الحمدُ in الحمدُ لله shows أل. Which second sign does it also show?',
          options: ['النداء', 'الجر بحرف الجر', 'الإسناد إليه — the sentence is predicated of it', 'التنوين'],
          correct: 2,
        },
        {
          title: 'أل والتنوين معًا',
          kind: 'mcq',
          prompt: 'A word carries أل but no تنوين, and another carries تنوين but no أل. Is either established as an اسم؟',
          options: ['Neither is — both signs must appear', 'Only the one with أل', 'Only the one with التنوين', 'Both are — any one of the six suffices'],
          correct: 3,
        },
        {
          title: 'الرؤيا',
          kind: 'mcq',
          prompt: 'In ﴿قَدْ صَدَّقْتَ الرُّؤْيَا﴾, what marks الرؤيا as an اسم؟',
          options: ['التنوين', 'الإسناد إليه', 'النداء', 'أَلْ'],
          correct: 3,
        },
        {
          title: 'صدَّقْتَ',
          kind: 'mcq',
          prompt: 'In ﴿قَدْ صَدَّقْتَ الرُّؤْيَا﴾, which two علامات فعلية does صدَّقْتَ carry?',
          options: ['A ناصب and a جازم', 'قَدْ before it, and تاء الفاعل attached to it', 'قَدْ and نون التوكيد', 'السين and تاء الفاعل'],
          correct: 1,
        },
        {
          title: 'قد أفلح',
          kind: 'mcq',
          prompt: '﴿قَدْ أَفْلَحَ مَنْ تَزَكَّى﴾ establishes أَفْلَحَ as a فعل by which sign?',
          options: ['تاء الفاعل', 'A جازم', 'ياء المخاطبة', 'قَدْ preceding it'],
          correct: 3,
        },
        {
          title: 'سنقرئك',
          kind: 'mcq',
          prompt: 'What makes نُقْرِئُ in ﴿سَنُقْرِئُكَ فَلَا تَنْسَى﴾ a فعل by the list of علامات؟',
          options: ['The prefixed السين', 'The attached كاف', 'The following فَلَا', 'The نون at its start'],
          correct: 0,
        },
        {
          title: 'لن تنالوا',
          kind: 'mcq',
          prompt: 'In ﴿لَنْ تَنَالُوا الْبِرَّ﴾, which word is the ناصب؟',
          options: ['لَنْ', 'حَتَّى', 'الْبِرَّ', 'تُنْفِقُوا'],
          correct: 0,
        },
        {
          title: 'وسِعْتَ وسقَيْتَ',
          kind: 'mcq',
          prompt: '﴿وَسِعْتَ كُلَّ شَيْءٍ﴾ and ﴿مَا سَقَيْتَ لَنَا﴾ are both cited for the same sign. Which?',
          options: ['قَدْ', 'تاء التأنيث الساكنة', 'تاء الفاعل', 'نون التوكيد'],
          correct: 2,
        },
        {
          title: 'النونان',
          kind: 'mcq',
          prompt: 'In ﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾, what is unusual about the شاهد؟',
          options: ['It carries both a ناصب and a جازم', 'It carries تاء الفاعل and نون التوكيد together', 'It is the only شاهد with no علامة at all', 'It carries both the heavy and the light نون التوكيد'],
          correct: 3,
        },
        {
          title: 'ليكونًا',
          kind: 'mcq',
          prompt: 'وَلَيَكُونًا ends in what looks like an alif with tanwīn. What is it in fact?',
          options: ['تاء التأنيث', 'تنوين, which would make it an اسم', 'The light نون التوكيد, written as an alif', 'ياء المخاطبة'],
          correct: 2,
        },
        {
          title: 'ارجعي',
          kind: 'mcq',
          prompt: 'The ياء in ﴿ارْجِعِي إِلَى رَبِّكِ﴾ is which ياء؟',
          options: ['ياء المخاطبة', 'ياء الجماعة', 'A لام of the root', 'ياء المتكلم'],
          correct: 0,
        },
        {
          title: 'الجوازم',
          kind: 'mcq',
          prompt: 'In ﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾, لَمْ establishes يَلِدْ as a فعل under which category of علامات الأفعال؟',
          options: ['السين', 'النواصب', 'الجوازم', 'تاء الفاعل'],
          correct: 2,
        },
        {
          title: 'علامة واحدة تكفي',
          kind: 'mcq',
          prompt: 'A word accepts أل but takes no تنوين, no إضافة and no نداء. Is it an اسم؟',
          options: ['No — أل and التنوين must both apply', 'Only if it is متمكن as well', 'Yes — any one of the six suffices', 'No — a majority of the six is needed'],
          correct: 2,
        },
        {
          title: 'إلى',
          kind: 'mcq',
          prompt: 'إِلَى in ﴿ارْجِعِي إِلَى رَبِّكِ﴾ takes no أل, no تنوين, no قَدْ and no نون توكيد. What is it?',
          options: ['حرف — it accepts nothing from either list', 'اسم مبني', 'اسم, since it precedes an اسم', 'فعل, since it precedes a مجرور'],
          correct: 0,
        },
        {
          title: 'ترتيب الاختبار',
          kind: 'mcq',
          prompt: 'What is the practical order for classifying an unknown word by this method?',
          options: ['Test for حرف first, then فعل, then اسم', 'Test whether it carries a زمن, and stop there', 'Test whether it is متمكن or متصرف', 'Test the six اسم signs, then the eight فعل signs, and what survives both is حرف'],
          correct: 3,
        },
        {
          title: 'الزمن في الاسم',
          kind: 'mcq',
          prompt: 'الغَدُ names a time, yet it is an اسم. Is that a counter-example to the definitions?',
          options: ['Yes — so الغَد should be classed as a فعل', 'No — because الغد accepts أل', 'Yes — a زمن is part of its meaning', 'No — الاسم may denote a time; what makes a فعل is that time is built into it as part of its وضع'],
          correct: 3,
        },
        {
          title: 'مِنْ عَدَمٍ',
          kind: 'mcq',
          prompt: 'عَدَمٍ in الحمدُ لله منشئِ الخلقَ من عَدَمٍ shows two signs at once. Which pair?',
          options: ['التنوين, and being مجرور by a حرف جر', 'النداء and التنوين', 'الإسناد إليه and الإضافة', 'أل and الإضافة'],
          correct: 0,
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الميزان الصرفي: وزن الثلاثي',
      subtitle: 'The Morphological Scale — why ف ع ل, the four things a وزن records, and weighing the three-letter word',
      concepts: [
        {
          heading: 'لماذا الفاء والعين واللام',
          lines: [
            { html: `Since most Arabic words are ثُلَاثِيّ, علماء الصرف took the أصول of a word to be three letters and set them against الفَاء والعَيْن واللَّام:`, list: false },
            { box: { title: 'Core Text', lines: [
              `مُصَوَّرَةً بِصُورَةِ المَوْزُونِ، نحو: انْكَسَرَ = انْفَعَلَ`,
            ] } },
            { html: `مُصَوَّرَةً بِصُورَةِ المَوْزُون — cast in the very shape of the word being weighed — is the whole method. The ميزان is a copy of the موزون: same number of letters, same vowels, same sukūns, same order, with ف ع ل standing in for the root letters.`, list: false },
            { html: `Every rule that follows is just a case of keeping that copy faithful when the موزون does something unusual.`, list: false },
          ],
          exercise: {
            prompt: `Why is ف ع ل used as the scale rather than any other three letters?`,
            kind: 'mcq',
            options: ['Because they are حروف الزيادة', 'Because they cannot undergo إعلال', 'Because most Arabic words are ثلاثي, so three أصول were taken as the norm', 'Because ف ع ل are the lightest letters to pronounce'],
            correct: 2,
          },
        },
        {
          heading: 'فائدة الميزان',
          lines: [
            { html: `The ميزان exists to record four things about a word, and nothing else.`, list: false },
            { html: `<bdi>الحَرَكَات والسَّكَنَات</bdi> — its vowels and its sukūns.`, list: true, bullet: true },
            { html: `<bdi>الأُصُول والزَّوَائِد</bdi> — which letters are root and which are added.`, list: true, bullet: true },
            { html: `<bdi>تَقَدُّمُ الحُرُوف وتَأَخُّرُهَا</bdi> — their order.`, list: true, bullet: true },
            { html: `<bdi>ذِكْرُ الحُرُوف وحَذْفُهَا</bdi> — which are present and which have dropped out.`, list: true, bullet: true },
            { html: `Read the later rules against this list and they stop looking arbitrary: the rule on حروف الزيادة serves point two, the rule on حذف serves point four, the rule on قلب مكاني serves point three.`, list: false },
          ],
          exercise: {
            prompt: `قُلْ weighs فُلْ, with the عين dropped. Which of the four فوائد is that rule serving?`,
            kind: 'mcq',
            options: ['الحركات والسكنات', 'الأصول والزوائد', 'تقدم الحروف وتأخرها', 'ذكر الحروف وحذفها'],
            correct: 3,
          },
        },
        {
          heading: 'وزن الثلاثي المجرد',
          lines: [
            { html: `With three letters and nothing added, the ميزان differs from word to word only in its vowelling.`, list: false },
            { table: { headers: ['الموزون', 'الوزن', 'الضبط'], rows: [
              ['قَمَر', 'فَعَل', 'بالتَّحْرِيك — فاء and عين both vowelled'],
              ['جِمْل', 'فِعْل', 'بكسر الفاء وسكون العين — فاء carries كسرة, عين is ساكن'],
              ['كَرُمَ', 'فَعُل', 'بفتح الفاء وضم العين — فاء carries فتحة, عين carries ضمة'],
            ] } },
            { html: `<bdi>وهَلُمَّ جَرًّا</bdi> — and so on through the rest of the ثلاثي patterns.`, list: false },
            { html: `All three have identical letters in the ميزان. What is being recorded here is purely الحركات والسكنات — the first of the four فوائد, in isolation.`, list: false },
          ],
          exercise: {
            prompt: `قَمَر, جِمْل and كَرُمَ all weigh on the same three letters ف ع ل. What alone distinguishes their أوزان؟`,
            kind: 'mcq',
            options: ['عدد الحروف', 'الحركات والسكنات', 'الأصول والزوائد', 'الترتيب'],
            correct: 1,
          },
        },
        {
          heading: 'فاء الكلمة وعينها ولامها',
          lines: [
            { html: `The three positions get fixed names, used constantly for the rest of علم الصرف.`, list: false },
            { table: { headers: ['الموضع', 'الاسم', 'في قَمَر'], rows: [
              ['الحرف الأول', 'فَاءُ الكَلِمَة', 'ق'],
              ['الحرف الثاني', 'عَيْنُ الكَلِمَة', 'م'],
              ['الحرف الثالث', 'لَامُ الكَلِمَة', 'ر'],
            ] } },
            { box: { title: 'Rule', lines: [`تَتْبَعُ أَسْمَاءُ فَاءِ الكَلِمَةِ وَعَيْنِهَا وَلَامِهَا الحَرْفَ الأَصْلِيَّ نَفْسَهُ لَا مَوْضِعَهُ فِي اللَّفْظِ`] } },
            { html: `The names attach to the <em>root</em> letter, not to a fixed slot in the word — so they travel unchanged when the word grows. In <bdi>اسْتَخْرَجَ = اسْتَفْعَلَ</bdi>, خ is still فاء الكلمة, ر عينُها, and ج لامُها, even though خ is now the fourth letter you pronounce.`, list: false },
            { html: `This is why terms like <bdi>مُضَعَّف العين</bdi>, <bdi>مُعْتَلُّ اللام</bdi> and <bdi>مَهْمُوزُ الفاء</bdi> are unambiguous however long the word is.`, list: false },
          ],
          exercise: {
            prompt: `In مُجْتَهِد = مُفْتَعِل, which letter of مجتهد is عين الكلمة؟`,
            kind: 'mcq',
            options: ['ت', 'م', 'ج', 'ه'],
            correct: 3,
          },
        },
      ],
      quiz: [
        {
          q: 'Why did علماء الصرف take the أصول of a word to be three letters?',
          options: ['Because most Arabic words are ثلاثي', 'Because ف ع ل are three letters', 'Because the رباعي is سماعي', 'Because the ثلاثي is the lightest form'],
          correct: 0,
        },
        {
          q: 'مصوَّرة بصورة الموزون means the ميزان must match the word in:',
          options: ['Meaning', 'Vowelling, letter count and order', 'Root letters only', 'Its أصول but not its زوائد'],
          correct: 1,
        },
        {
          q: 'Which is NOT among the four فوائد of the ميزان?',
          options: ['المعنى المقصود من الكلمة', 'ذكر الحروف وحذفها', 'الحركات والسكنات', 'الأصول والزوائد'],
          correct: 0,
        },
        {
          q: 'What is the وزن of انْكَسَرَ؟',
          options: ['اسْتَفْعَلَ', 'تَفَعَّلَ', 'افْتَعَلَ', 'انْفَعَلَ'],
          correct: 3,
        },
        {
          q: 'كَرُمَ weighs فَعُل. What does that record?',
          options: ['بالتحريك', 'بضم الفاء وفتح العين', 'بفتح الفاء وضم العين', 'بكسر الفاء وسكون العين'],
          correct: 2,
        },
        {
          q: 'In اسْتَخْرَجَ = اسْتَفْعَلَ, which letter is لام الكلمة؟',
          options: ['ج', 'س', 'خ', 'ر'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'صورة الموزون',
          kind: 'mcq',
          prompt: 'A student weighs ضَرَبَ as فِعْل. What has gone wrong?',
          options: ['A زائد has been omitted', 'The letters are wrong', 'The ميزان must be مصوَّرة بصورة الموزون — the vowelling must match, so it is فَعَلَ', 'The order is wrong'],
          correct: 2,
        },
        {
          title: 'انكسر',
          kind: 'mcq',
          prompt: 'In انْكَسَرَ = انْفَعَلَ, why do ا and ن appear in the ميزان as themselves?',
          options: ['They are أصول of the word', 'They are زوائد, and a زائد is written by its own لفظ', 'They are مبدلة من تاء الافتعال', 'They stand in for a محذوف letter'],
          correct: 1,
        },
        {
          title: 'الفائدة الأولى',
          kind: 'mcq',
          prompt: 'Which فائدة of the ميزان does the difference between فَعَل and فَعُل illustrate?',
          options: ['الأصول والزوائد', 'تقدم الحروف وتأخرها', 'ذكر الحروف وحذفها', 'الحركات والسكنات'],
          correct: 3,
        },
        {
          title: 'الفائدة الثانية',
          kind: 'mcq',
          prompt: 'Which فائدة lets you see at a glance that the ت of مُجْتَهِد is not part of its root?',
          options: ['الحركات والسكنات', 'الأصول والزوائد', 'تقدم الحروف وتأخرها', 'ذكر الحروف وحذفها'],
          correct: 1,
        },
        {
          title: 'الفائدة الثالثة',
          kind: 'mcq',
          prompt: 'Which فائدة is at work when جَاه weighs عَفَل rather than فَعَل؟',
          options: ['الأصول والزوائد', 'تقدم الحروف وتأخرها', 'ذكر الحروف وحذفها', 'الحركات والسكنات'],
          correct: 1,
        },
        {
          title: 'قَمَر',
          kind: 'mcq',
          prompt: 'What is the وزن of قَمَر؟',
          options: ['فَعُل', 'فَعْل', 'فِعْل', 'فَعَل'],
          correct: 3,
        },
        {
          title: 'جِمْل',
          kind: 'mcq',
          prompt: 'جِمْل is weighed فِعْل. What does the sukūn on the عين record?',
          options: ['That the second letter of جِمْل carries no حركة', 'That a letter has been dropped', 'That the لام is مضعفة', 'That the عين is زائدة'],
          correct: 0,
        },
        {
          title: 'وزن كَتَبَ',
          kind: 'mcq',
          prompt: 'كَتَبَ is a فعل ماضٍ with a fatḥa on both its فاء and its عين. What is its وزن؟',
          options: ['فَعَلَ', 'فَعْل', 'فِعْل', 'فَعُل'],
          correct: 0,
        },
        {
          title: 'وزن عِلْم',
          kind: 'mcq',
          prompt: 'عِلْم is an اسم بكسر الفاء وسكون العين, like جِمْل. What is its وزن؟',
          options: ['فِعَل', 'فَعْل', 'فِعْل', 'فَعِل'],
          correct: 2,
        },
        {
          title: 'وزن حَسُنَ',
          kind: 'mcq',
          prompt: 'حَسُنَ is a فعل ماضٍ بفتح الفاء وضم العين, like كَرُمَ. What is its وزن؟',
          options: ['فَعِلَ', 'فَعُلَ', 'فُعِلَ', 'فَعَلَ'],
          correct: 1,
        },
        {
          title: 'فاء الكلمة',
          kind: 'mcq',
          prompt: 'What is فاء الكلمة in كَرُمَ؟',
          options: ['ك', 'ر', 'م', 'The word has no فاء, being ثلاثي'],
          correct: 0,
        },
        {
          title: 'عين الكلمة',
          kind: 'mcq',
          prompt: 'What is عين الكلمة in قَمَر؟',
          options: ['ق', 'م', 'ر', 'The ع of the ميزان itself'],
          correct: 1,
        },
        {
          title: 'لام الكلمة',
          kind: 'mcq',
          prompt: 'What is لام الكلمة in جِمْل؟',
          options: ['There is none — the word is only three letters', 'ج', 'م', 'ل'],
          correct: 3,
        },
        {
          title: 'الأسماء تلزم الأصل',
          kind: 'mcq',
          prompt: 'In تَقَدَّمَ = تَفَعَّلَ, which letter of تقدَّم is فاء الكلمة؟',
          options: ['ق', 'د', 'م', 'ت'],
          correct: 0,
        },
        {
          title: 'مضعَّف العين',
          kind: 'mcq',
          prompt: 'A word is described as مضعَّف العين. What is being said about it?',
          options: ['It has a زائد after its عين', 'Its first root letter is doubled', 'Its second root letter is doubled', 'Its third root letter is doubled'],
          correct: 2,
        },
        {
          title: 'معتل اللام',
          kind: 'mcq',
          prompt: 'Why can the term معتل اللام be used of a long word like اسْتَدْعَى without ambiguity?',
          options: ['Because استدعى is ثلاثي in origin', 'Because لام الكلمة names the third root letter wherever it sits in the word', 'Because لام الكلمة always means the last letter pronounced', 'Because the زوائد are ignored in naming'],
          correct: 1,
        },
        {
          title: 'الميزان والمعنى',
          kind: 'mcq',
          prompt: 'Does the ميزان record anything about a word’s meaning?',
          options: ['Yes, but only for المشتقات', 'Only for the ثلاثي', 'Yes — the وزن fixes the meaning of the derived form', 'No — the four فوائد are all about form: vowelling, أصول and زوائد, order, and presence or absence of letters'],
          correct: 3,
        },
        {
          title: 'هلم جرا',
          kind: 'mcq',
          prompt: 'قَمَر (فَعَل), جِمْل (فِعْل) and كَرُمَ (فَعُل) are followed by وهلم جرا. What does that signal?',
          options: ['That the ميزان does not apply beyond these three', 'That these three are the only ثلاثي patterns', 'That the remaining ثلاثي patterns follow the same method', 'That the remaining patterns are سماعية'],
          correct: 2,
        },
        {
          title: 'ترتيب الحروف',
          kind: 'mcq',
          prompt: 'Two words share letters and vowelling but differ in the order of their أصول. Will their أوزان differ?',
          options: ['Yes — تقدم الحروف وتأخرها is one of the four فوائد', 'No — order is a نحو matter', 'Only if one of them contains a زائد', 'No — the ميزان records only حركات and سكنات'],
          correct: 0,
        },
        {
          title: 'حرف مقابل حرف',
          kind: 'mcq',
          prompt: 'What does مقابلة mean in the phrase وقابلوها عند الوزن بالفاء والعين واللام؟',
          options: ['Comparing the word with another word of the same pattern', 'Reversing the order of the letters', 'Deleting the زوائد before weighing', 'Setting each root letter opposite its counterpart in ف ع ل'],
          correct: 3,
        },
        {
          title: 'الأصل ثلاثة',
          kind: 'mcq',
          prompt: 'What is the reasoning that made three the assumed number of أصول؟',
          options: ['The رباعي and خماسي are borrowed forms', 'أكثر كلمات اللغة العربية ثلاثي', 'The ثلاثي alone accepts الزيادة', 'ف ع ل happen to be three letters'],
          correct: 1,
        },
        {
          title: 'موزون بلا زوائد',
          kind: 'mcq',
          prompt: 'A ثلاثي مجرد word is weighed. How many letters will its ميزان have?',
          options: ['Three, unless a letter has been dropped from the موزون', 'Four, counting the ف of the ميزان', 'It varies with الحركات', 'Three, always'],
          correct: 0,
        },
        {
          title: 'الميزان والصورة',
          kind: 'mcq',
          prompt: 'A student writes the وزن of انكسر as فَعَلَ, discarding the ا and ن as not being أصول. What principle has he broken?',
          options: ['تقدم الحروف وتأخرها', 'ذكر الحروف وحذفها', 'مصوَّرة بصورة الموزون — the ميزان must mirror the word, زوائد included', 'الأصول والزوائد'],
          correct: 2,
        },
        {
          title: 'الحرف الأول',
          kind: 'mcq',
          prompt: 'In انْكَسَرَ = انْفَعَلَ, which letter of انكسر is فاء الكلمة؟',
          options: ['ك', 'س', 'ا', 'ن'],
          correct: 0,
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'وزن ما زاد على ثلاثة أحرف',
      subtitle: 'Weighing Longer Words — extra root letters, doubled letters, حروف الزيادة, and the special cases of إبدال, حذف and قلب',
      concepts: [
        {
          heading: 'الزيادة الناشئة من أصل الكلمة',
          lines: [
            { html: `When a word runs beyond three letters, the first question is where the extra letters come from. If they belong to the root itself — a four- or five-letter أصل — you add a <bdi>لام</bdi> or two <bdi>لامين</bdi> to ف ع ل.`, list: false },
            { table: { headers: ['الموزون', 'عدد الأصول', 'الوزن'], rows: [
              ['دَحْرَجَ (to roll) ، بَعْثَرَ ، وَسْوَسَ', 'رباعي — أفعال', 'فَعْلَلَ'],
              ['جَعْفَر ، ثَعْلَب', 'رباعي — أسماء', 'فَعْلَل'],
              ['جَحْمَرِش (an old woman)', 'خماسي', 'فَعْلَلِل'],
            ] } },
            { html: `Note that the added letter is a لام, not a repetition of ف or ع — the scale extends at its end.`, list: false },
            { html: `All five sit under فَعْلَلَ. They divide into the أفعال, which carry the final fatḥa of the ماضٍ (فَعْلَلَ), and the أسماء, which do not (فَعْلَل) — the letters of the ميزان are the same either way.`, list: false },
          ],
          exercise: {
            prompt: `زَلْزَلَ has four root letters, none of them added. What is its وزن؟`,
            kind: 'mcq',
            options: ['فَعَّلَ', 'فَعْفَلَ', 'افْتَعَلَ', 'فَعْلَلَ'],
            correct: 3,
          },
        },
        {
          heading: 'الزيادة الناشئة من تكرير حرف أصلي',
          lines: [
            { html: `If the extra letter comes from repeating one of the word's own أصول, you repeat the corresponding letter of the ميزان — not add a new one.`, list: false },
            { table: { headers: ['الموزون', 'الوزن', 'التسمية'], rows: [
              ['قدَّم (بتشديد العين)', 'فَعَّلَ', 'مُضَعَّف العين'],
              ['جَلْبَبَ', 'فَعْلَلَ', 'مُضَعَّف اللام'],
            ] } },
            { html: `جَلْبَبَ is worth holding beside دَحْرَجَ from the previous rule: both weigh <bdi>فَعْلَلَ</bdi>, but for different reasons. دحرج has four distinct أصول; جلبب has three, with the لام repeated.`, list: false },
            { box: { title: 'Careful', lines: [`مَا يَتَشَارَكُ فِي الوَزْنِ قَدْ يَفْتَرِقُ فِي التَّسْمِيَةِ`] } },
            { html: `The وزن records the form, and دحرج and جلبب genuinely share one. What separates them is not visible in the وزن itself but in the التسمية that goes with it: جلبب is مُضَعَّف اللام, a ثلاثي whose third root letter is repeated, while دحرج is a plain رباعي مجرد. This is why the naming — <bdi>ويقال له مضعَّف العين أو اللام</bdi> — is attached directly to this rule: the label carries the information the وزن alone cannot.`, list: false },
          ],
          exercise: {
            prompt: `Both دَحْرَجَ and جَلْبَبَ weigh فَعْلَلَ. What distinguishes them?`,
            kind: 'mcq',
            options: ['جلبب contains a حرف زائد from سألتمونيها', 'دحرج is خماسي and جلبب رباعي', 'Nothing — they are the same type of word', 'دحرج has four distinct أصول; جلبب is ثلاثي with its لام repeated'],
            correct: 3,
          },
        },
        {
          heading: 'الزيادة من حروف سألتمونيها',
          lines: [
            { html: `If the extra letter is one of <bdi>حُرُوف الزِّيَادَة</bdi> — the ten collected in <bdi>سَأَلْتُمُونِيهَا</bdi> — you match أصل against أصل and write the added letter <bdi>بِلَفْظِه</bdi>, as itself.`, list: false },
            { table: { headers: ['الموزون', 'الوزن'], rows: [
              ['قَائِم', 'فَاعِل'],
              ['تَقَدَّمَ', 'تَفَعَّلَ'],
              ['اسْتَخْرَجَ', 'اسْتَفْعَلَ'],
              ['مُجْتَهِد', 'مُفْتَعِل'],
              ['مَرْمَرِيس', 'فَعْفَعِيل'],
            ] } },
            { html: `مَرْمَرِيس shows two mechanisms in one word: the repeated <bdi>فع</bdi> is تكرير of أصول (the previous rule), while the ي is a حرف زائد written by its own لفظ (this one).`, list: false },
          ],
          exercise: {
            prompt: `In مُجْتَهِد = مُفْتَعِل, why do م and ت appear as themselves in the ميزان while ج، ه and د do not?`,
            kind: 'mcq',
            options: ['Because م and ت cannot be represented by ف ع ل', 'Because the word is رباعي in origin', 'Because م and ت are زوائد from سألتمونيها, and a زائد is written بلفظه', 'Because م and ت are أصول and the others are زوائد'],
            correct: 2,
          },
        },
        {
          heading: 'المبدل من تاء الافتعال',
          lines: [
            { html: `A special case of the زائد. When the added letter is an <bdi>إبدال</bdi> of <bdi>تاء الافتعال</bdi>, the ميزان is pronounced with the original تاء.`, list: false },
            { box: { title: 'Rule', lines: [`يُوزَنُ المُبْدَلُ مِنْ تَاءِ الِافْتِعَالِ نَظَرًا إِلَى الأَصْلِ لَا إِلَى النُّطْقِ`] } },
            { html: `So <bdi>اضْطَرَبَ</bdi> weighs <bdi>افْتَعَلَ</bdi>, not افْطَعَلَ, even though the letter actually pronounced is ط. <bdi>وقد أجازه الرَّضِيّ</bdi> — الرضي permitted the other way.`, list: false },
            { table: { title: 'The إبدال in stages', headers: ['الأصل', 'بتاء الافتعال', 'بعد الإبدال'], rows: [
              ['صلح', 'اصْتَلَحَ', 'اصْطَلَحَ'],
              ['زجر', 'ازْتَجَرَ', 'ازْدَجَرَ'],
            ] } },
            { html: `This is the one place where the ميزان deliberately does <em>not</em> copy what you hear — it copies what the letter originally was.`, list: false },
          ],
          exercise: {
            prompt: `ازْدَجَرَ is pronounced with a دال. What is its وزن on this rule?`,
            kind: 'mcq',
            options: ['انْفَعَلَ', 'فَعْلَلَ', 'افْدَعَلَ', 'افْتَعَلَ'],
            correct: 3,
          },
        },
        {
          heading: 'الحذف والقلب المكاني',
          lines: [
            { html: `Two final cases, each keeping the ميزان a faithful copy of the موزون.`, list: false },
            { html: `<bdi>الحَذْف</bdi> — if a letter has dropped from the موزون, drop its counterpart from the ميزان.`, list: true, bullet: true },
            { html: `<bdi>القَلْب المَكَاني</bdi> — if the موزون has had its letters transposed, transpose the ميزان to match.`, list: true, bullet: true },
            { table: { headers: ['الموزون', 'الوزن', 'ما حدث'], rows: [
              ['قُلْ', 'فُلْ', 'the عين has dropped'],
              ['قَاضٍ', 'فَاعٍ', 'the لام has dropped'],
              ['عِدَة', 'عِلَة', 'the فاء has dropped'],
              ['جَاه', 'عَفَل', 'العين has been advanced before الفاء'],
            ] } },
            { html: `عِدَة is the clean illustration: its أصل is وَعَدَ, and the واو — its فاء — has gone, so the ميزان opens at the عين.`, list: false },
          ],
          exercise: {
            prompt: `عِدَة weighs عِلَة rather than فِعَة. Which letter of the ميزان has been dropped, and why?`,
            kind: 'mcq',
            options: ['The عين, because the word is only three letters', 'The لام, because the ة is a زائدة', 'None — عِلَة merely reverses the order', 'The فاء, because the واو of وَعَدَ has dropped from the word'],
            correct: 3,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the وزن of دَحْرَجَ؟',
          options: ['فَعَّلَ', 'فَعْلَلَ', 'فَعْلَلِل', 'افْتَعَلَ'],
          correct: 1,
        },
        {
          q: 'جَحْمَرِش is خماسي. What is its وزن؟',
          options: ['فَعْفَعِيل', 'فَعَالِل', 'فَعْلَل', 'فَعْلَلِل'],
          correct: 3,
        },
        {
          q: 'How is a حرف زائد from سألتمونيها represented in the ميزان?',
          options: ['By its own لفظ', 'By a repeated لام', 'It is omitted', 'By the matching letter of ف ع ل'],
          correct: 0,
        },
        {
          q: 'What is the وزن of مَرْمَرِيس؟',
          options: ['فَعْلَلَ', 'فَعْلَلِيل', 'فَعْفَعِيل', 'مُفْتَعِيل'],
          correct: 2,
        },
        {
          q: 'اضْطَرَبَ weighs افْتَعَلَ rather than افْطَعَلَ. On what ground?',
          options: ['The ط is مبدلة من تاء الافتعال, and the ميزان looks to الأصل', 'The ط is لام الكلمة', 'Because الرضي permitted it', 'The ط is a حرف زائد written بلفظه'],
          correct: 0,
        },
        {
          q: 'جَاه weighs عَفَل. What has happened?',
          options: ['إبدال', 'قلب مكاني — the عين has come before the فاء', 'تضعيف', 'حذف'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: 'زيادة من الأصل',
          kind: 'mcq',
          prompt: 'A word has four أصول, none of them added. What do you do to ف ع ل?',
          options: ['Repeat the عين', 'Add one لام', 'Add two لامين', 'Write the extra letter بلفظه'],
          correct: 1,
        },
        {
          title: 'الخماسي',
          kind: 'mcq',
          prompt: 'A word has five أصول, none of them added. What do you do to ف ع ل?',
          options: ['Add two لامين', 'Repeat the فاء and the عين', 'Write two of the letters بلفظهما', 'Add one لام'],
          correct: 0,
        },
        {
          title: 'بَعْثَرَ',
          kind: 'mcq',
          prompt: 'What is the وزن of بَعْثَرَ؟',
          options: ['فَعْفَلَ', 'تَفَعْلَلَ', 'فَعْلَلَ', 'فَعَّلَ'],
          correct: 2,
        },
        {
          title: 'ثَعْلَب',
          kind: 'mcq',
          prompt: 'ثَعْلَب and جَعْفَر weigh فَعْلَل, while دَحْرَجَ and بَعْثَرَ weigh فَعْلَلَ. What accounts for the difference?',
          options: ['The first pair contain a حرف زائد', 'The first pair are خماسي', 'The first pair are أسماء; the second are أفعال ماضية carrying the final fatḥa', 'The first pair are مضعَّف اللام'],
          correct: 2,
        },
        {
          title: 'وَسْوَسَ',
          kind: 'mcq',
          prompt: 'وَسْوَسَ falls under الزيادة من أصل الكلمة, not under تكرير. What does that imply about its letters?',
          options: ['It is مضعَّف العين', 'Its four letters are all أصول', 'Its س is a repeated أصل', 'Its و is a حرف زائد'],
          correct: 1,
        },
        {
          title: 'قدَّم',
          kind: 'mcq',
          prompt: 'قدَّم, with a shadda on the دال, weighs فَعَّلَ. Why is the عين doubled rather than a لام added?',
          options: ['Because the word is رباعي', 'Because a shadda always doubles the عين of the ميزان', 'Because the extra letter is a repetition of an أصل, not a new أصل', 'Because the دال is a حرف زائد'],
          correct: 2,
        },
        {
          title: 'مضعَّف العين أو اللام',
          kind: 'mcq',
          prompt: 'What determines whether a word is called مضعَّف العين or مضعَّف اللام?',
          options: ['Whether the doubling is أصلي or زائد', 'Whether the second or third root letter is the one repeated', 'Whether the shadda is written or not', 'Whether the word is فعل or اسم'],
          correct: 1,
        },
        {
          title: 'جَلْبَبَ',
          kind: 'mcq',
          prompt: 'جَلْبَبَ is مضعَّف اللام. Which of its letters is the repeated one?',
          options: ['The whole syllable لب', 'ج', 'ل', 'ب'],
          correct: 3,
        },
        {
          title: 'حروف الزيادة',
          kind: 'mcq',
          prompt: 'The حروف الزيادة are collected in which mnemonic?',
          options: ['أَمَان وتَسْهِيل', 'يَنْمُو', 'سَأَلْتُمُونِيهَا', 'هَوِيتُ السِّمَان'],
          correct: 2,
        },
        {
          title: 'قَائِم',
          kind: 'mcq',
          prompt: 'قَائِم weighs فَاعِل. What is the ألف doing in the ميزان؟',
          options: ['Indicating قلب مكاني', 'Standing in for عين الكلمة', 'Appearing as itself, since it is a حرف زائد', 'Marking a محذوف letter'],
          correct: 2,
        },
        {
          title: 'تَقَدَّمَ',
          kind: 'mcq',
          prompt: 'تَقَدَّمَ weighs تَفَعَّلَ. Which two of the three rules on زيادة are at work?',
          options: ['تكرير of an أصل (the دال), and a حرف زائد written بلفظه (the تاء)', 'إبدال, and حذف', 'قلب مكاني, and تكرير', 'زيادة من الأصل, and تكرير'],
          correct: 0,
        },
        {
          title: 'اسْتَخْرَجَ',
          kind: 'mcq',
          prompt: 'اسْتَخْرَجَ weighs اسْتَفْعَلَ. How many of its letters are زوائد؟',
          options: ['واحد', 'اثنان', 'ثلاثة', 'أربعة'],
          correct: 2,
        },
        {
          title: 'مَرْمَرِيس',
          kind: 'mcq',
          prompt: 'In مَرْمَرِيس = فَعْفَعِيل, what does the repeated فع record?',
          options: ['A رباعي أصل', 'A قلب مكاني', 'A تكرير of the word’s own أصول', 'Two حروف زائدة written بلفظهما'],
          correct: 2,
        },
        {
          title: 'الزائد بلفظه',
          kind: 'mcq',
          prompt: 'Why is a حرف زائد written as itself rather than as a letter of ف ع ل?',
          options: ['Because it may later be dropped', 'So that الأصول والزوائد — the second فائدة — can be read off the وزن directly', 'Because ف ع ل have already been used up', 'Because حروف الزيادة cannot be replaced'],
          correct: 1,
        },
        {
          title: 'تاء الافتعال',
          kind: 'mcq',
          prompt: 'اصْطَلَحَ passes through اصْتَلَحَ. What does that intermediate form show?',
          options: ['That a letter has been dropped', 'That the letters have been transposed', 'That the ط is an إبدال of تاء الافتعال', 'That the ص is a حرف زائد'],
          correct: 2,
        },
        {
          title: 'رأي الرضي',
          kind: 'mcq',
          prompt: 'What is الرضي’s position on weighing اضطرب؟',
          options: ['He required افْتَعَلَ only', 'He permitted افْطَعَلَ as well', 'He weighed it فَعْلَلَ', 'He held that it has no وزن'],
          correct: 1,
        },
        {
          title: 'نظرًا إلى الأصل',
          kind: 'mcq',
          prompt: 'The إبدال rule is the one place the ميزان departs from what is pronounced. What does it copy instead?',
          options: ['Nothing — the letter is dropped', 'The letter’s original form before الإبدال', 'The nearest letter in ف ع ل', 'The letter of the same مخرج'],
          correct: 1,
        },
        {
          title: 'قُلْ',
          kind: 'mcq',
          prompt: 'قُلْ weighs فُلْ. Which position of the ميزان has gone?',
          options: ['العين', 'اللام', 'The ميزان is complete', 'الفاء'],
          correct: 0,
        },
        {
          title: 'عِدَة',
          kind: 'mcq',
          prompt: 'عِدَة weighs عِلَة. What does the missing فاء tell you about its أصل؟',
          options: ['Its ة is a حرف زائد replacing the فاء', 'Its letters have been transposed', 'Its أصل is وَعَدَ, and the واو has dropped', 'Its أصل is رباعي'],
          correct: 2,
        },
        {
          title: 'قاضٍ',
          kind: 'mcq',
          prompt: 'قاضٍ weighs فَاعٍ. Which letter has dropped, and what is it?',
          options: ['The ياء, which is لام الكلمة', 'The ألف, which is زائدة', 'The قاف, which is فاء الكلمة', 'The ضاد, which is عين الكلمة'],
          correct: 0,
        },
        {
          title: 'حذف في الميزان',
          kind: 'mcq',
          prompt: 'What is the rule when a letter has dropped from the موزون؟',
          options: ['Transpose the remaining letters', 'Keep the ميزان complete and note the loss separately', 'Drop the corresponding letter of the ميزان', 'Replace it with a حرف زائد'],
          correct: 2,
        },
        {
          title: 'جَاه',
          kind: 'mcq',
          prompt: 'جَاه weighs عَفَل, بتقديم العين على الفاء. What does the وزن record?',
          options: ['That the عين is doubled', 'That a letter has dropped', 'That the word’s letters have been transposed relative to its أصل', 'That the ألف is زائدة'],
          correct: 2,
        },
        {
          title: 'أي فائدة؟',
          kind: 'mcq',
          prompt: 'The قلب مكاني rule serves which of the four فوائد؟',
          options: ['تقدم الحروف وتأخرها', 'ذكر الحروف وحذفها', 'الحركات والسكنات', 'الأصول والزوائد'],
          correct: 0,
        },
        {
          title: 'تمييز القواعد',
          kind: 'mcq',
          prompt: 'A four-letter word weighs فَعْلَلَ. Which two situations could have produced that وزن؟',
          options: ['A ثلاثي with إبدال, or one with حذف', 'A رباعي أصل, or a ثلاثي whose لام is repeated', 'A رباعي أصل, or a ثلاثي with one حرف زائد', 'A خماسي أصل, or a قلب مكاني'],
          correct: 1,
        },
      ],
    },
  ],
};
